canonical/lxd

lxd/container.go, test/config.sh
Fixes #1014.
Profiles are applied in container.init. The config and devices sent
to ConfigReplace in Start() should be just the base.
Adds tests to check this - NOTE these tests depend on 'config show' and
'device list' not showing extended config/device info, which should
probably change.
=> Don't copy profile settings to container in start

lxd/storage_lvm.go, test/lvm.sh
=> Allow unsetting lvm_thinpool_name after vg_name

Vagrantfile, scripts/vagrant/install-go.sh
Use a different vagrant base box which supports vbox/vmware/parallels
and has guest tools.
update package lists before installing packages since this base box
does not have any package lists pre-fetched.
Signed-off-by: Ragnar Rova <ragnar.rova@gmail.com>
=> Vagrant box also for vmware

lxc/remote.go
=> Fix adding a remote by its IPv6 address

lxd/container.go, lxd/db.go, lxd/db_update.go, lxd/storage.go, lxd/storage_lvm.go, test/lvm.sh
Both snapshot and copy are implemented using LVM thin snapshots.
LXD snapshots are read-only LVM thin snapshots.
Because of LVM naming limitations, we must munge snapshot names, replacing / with - and - with --.
Handles situations where a dir-backed container is copied after setting the LVM config, we copy into an LVM container.
When a dir-backed container is snapshotted, it gets a dir-backed snapshot (this change is in container.go, containerLXDCreateAsSnapshot().)
Adds tests to verify that these situations work well.
This includes some code from @pcdummy's PR #1000. I commented there with more details about what was used.
=> Add support for LVM native snapshot and copy

lxd/storage_lvm.go, test/lvm.sh
Uses lvrename, adds tests.
Code almost entirely from @pcdummy's #1000, except for the name munging.
=> Add container rename to LVM driver

client.go, lxc/move.go, test/snapshots.sh
The optimization to use rename instead of copy for 'lxc move' did not
work with snapshots.
Fixes #1038 
=> Allow renaming snapshots on same system

lxc/init.go, po/lxd.pot
Compared to `lxc/launch.go` this file is now correct.
Also the initial problem was that `lxc help --all` yielded
```text
Usage: lxc [subcommand] [options]
Available commands:
config     - Manage configuration.
copy       - Copy containers within or in between lxd instances.
delete     - Delete containers or container snapshots.
exec       - Execute the specified command in a container.
file       - Manage files on a container.
finger     - Fingers the LXD instance to check if it is up and working.
help       - Presents details on how to use LXD.
image      - Manipulate container images
info       - List information on containers.
init       - lxc init [remote:]<image> [remote:][<name>] [--ephemeral|-e] [--profile|-p <profile>...]
launch     - Launch a container from a particular image. …
```
=> help text of lxc init now displayed correctly

lxd/storage_lvm.go, specs/configuration.md, test/lvm.sh
Checks for containers or images in the db that are using the
currently-configured thin pool, and would hence be broken if the config
was changed.
Includes the names of the offending images/containers in the error message.
Updates tests.
Fixes #953.
=> Disallow changing LVM config if pool is in use.

lxd/container.go, lxd/storage_lvm.go, test/lvm.sh, test/snapshots.sh
Use storage.ContainerSnapshotRename to rename snapshot storage, allowing snapshot-dir-specific cleanup.
Also fix a TODO: rename snapshots of renamed containers, and add tests for this.
Finally implement ContainerSnapshotRename for the LVM storage backend.
=> Snapshot Renaming Fixes - general and LVM

lxd/storage_lvm.go
Simply sets s.sTypeVersion to all three lines of "lvm version" output, since they all seem potentially useful.
Here's an example:
```
ubuntu@canonical-lxd:~$ sudo lvm version
LVM version:     2.02.111(2) (2014-09-01)
Library version: 1.02.90 (2014-09-01)
Driver version:  4.29.0
```
=> Add version output to LVM storage driver

scripts/lxd-images
The Ubuntu simplestream format changed earlier today breaking our parser.
This branch makes the parser more tolerant to random fields disappearing
or getting removed (will return nothing rather than blow up).
I'm also keeping support for the old keys in the very likely event that
the simplestream change is reverted.
=> lxd-images: Update simplestream parser for recent breakage

lxd/api10.go, lxd/main.go, shared/server.go, specs/rest-api.md
This implements the shutdown command as a lxd argument.
When called, SIGPWR is sent to LXD by fetching the daemon's PID over the
API, we then wait for LXD to stop responding before returning.
This is meant to be used by init systems to perform a clean shutdown of
LXD on host shutdown.
=> Implement shutdown command (and some cleanup)

README.md
1. don't have 3 different apt-get lines you have to copy. Just have one.
2. don't have people add the PPA unless they are on an old enough Ubuntu to
not have 1.3
=> rework dependencies in the readme:

lxd/api10.go, lxd/daemon.go, lxd/daemon_test.go, lxd/db.go, lxd/db_update.go, lxd/storage_lvm.go, specs/configuration.md, test/basic.sh, test/lvm.sh
This is in preparation for ZFS support. I think it makes sense to move the storage configuration stuff to its own namespace.
=> Rename core.lvm to storage.lvm (and fix testsuite)

lxd/main.go
apparmor_parser won't do anything if the apparmor fs isn't mounted, so let's
check that too.
=> apparmor: also stat kernel security path

lxd/apparmor.go, lxd/container.go, lxd/db_containers.go, lxd/images.go, lxd/main.go
Closes #1002 
This suffices to allow me to run lxd containers within lxd containers.
When running lxd inside a lxd container, a few things must be done differently.
First, we cannot create devices.  This means when init'ing a container we have
to avoid extracting the devices as that will fail.
Secondly, we need some extra permissions from apparmor for mounting and
pivot_root.
Thirdly, we cannot load new apparmor policies, so avoid that.  Intead, tell
lxc to use the same policy we are currently in.  (There is no way to tell
lxc "don't switch apparmor profiles at all")  We support running lxd
containers under a lxc-container-default-with-nesting profile, as well
as supporting lxc-container-default containers under lxd containers.
HOWTO
To tell lxd that a container should allow nesting …
=> Support nested lxd [RFC]

lxd/migration/migrate.go
In particular, srcIdmap is created via new(IdmapSet), so it'll never be nil
when dstIdmap is. Instead, let's make an actual object, since the actual empty
object means the same thing as nil (i.e. "don't uidmapshift anything"), the
resulting reflective deep comparison works and we get the expected behavior,
instead of this giant stack trace:
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x5c77eb]
goroutine 59 [running]:
runtime.panic(0x9eb400, 0x11003d3)
/usr/lib/go/src/pkg/runtime/panic.c:279 +0xf5
github.com/lxc/lxd/shared.func·002(0xc20806a300, 0x1d, 0x7fb709518b98, 0xc20820b5e0, 0x0, 0x0, 0x0, 0x0)
/home/ubuntu/packages/go/src/github.com/lxc/lxd/shared/idmapset.go:234 +0x47b
path/filepath.walk(0xc20806a300, 0x1d, …
=> copy: fix idmap shifting

lxd/container.go, lxd/main.go, specs/environment.md
This is currently needed for Snappy until we figure out how to load all
the LXC profiles. This isn't a regression since Snappy never had
AppArmor support.
=> Make it possible to force AppArmor off

scripts/lxd-setup-lvm-storage
Creates a sparse-file backed loop device and makes it an LVM PV, then creates a VG that includes that PV and then lets LXD do the rest.
Tear down only works if you have no containers/images using the storage.
=> Add script to set up and delete LVM storage

shared/util.go, shared/util_linux.go
This brings LXD client closer to be built on Windows (#825)
=> Move unused IsMountPoint to OS-specific util_linux.go

lxd/container.go, lxd/containers_post.go
if we are creating a privileged container, we shouldn't fail
creation because of there being no subuids.  But we can't
easily know at the start of containers_post whether the container
is privileged.  So delay the check until we have the info, and
until we definately need it.
As a downside, an error message won't be seen until we've
downloaded the image.  To change that we'd have to do c.init()
before checking for and downloading the image.
=> delay check for subuids

lxd/container.go
Without this, the following would end up with invalid permissions:
lxc init ubuntu blah
lxc config set blah security.privileged true
lxc start blah
=> Fix missing original idmap

lxd/container.go, shared/util.go
This pair fixes the problems when starting privileged containers nested inside a container.  It probably also fixes some other problems.
The first problem was that we were making some decisions based on c.IsNesting and c.IsPrivileged before we had applied profiles and configuration to c.
The second was that we were only adding ubuntu.userns.conf for an unprivileged container, but we also need to do so when we are starting a nested container.
=> 2015 09 19/nest

scripts/lxd-images
using http by default means benefit of caching proxies.
Also here, remove FIXME comment that is now fixed.
=> use http rather than https for ubuntu cloud images.

test/suites/basic.sh
=> tests: Don't chown stdin when it's not a tty

shared/idmapset.go
This is required to run LXD on Fedora (#830) where Go is
built without cgo support required by user.Current
=> Attempt to fix `user: Current not implemented on linux/amd64`

lxd/container.go, lxd/devlxd.go
This is meant to be temporary until we get something similar in go-lxc itself.
=> Redirect all SetConfig so we can return a useful error

client.go, lxc/image.go, lxd/devices.go, lxd/images.go, scripts/lxd-images, shared/image.go, shared/util.go
This does the following:
- Introduce new --quiet global switch
When passed, all non-error output will be hidden.
- Introduce new --sync ubuntu importer switch
When passed, an image property will be set, this property is what the
sync command looks for.
- Introduce new "sync" command
This command will look for any image which was imported with --sync,
check if a newer version of the image is available and if so, update the
image to it.
- Drops redundant image hashing
Instead of locally hashing the downloaded files, just forward the
fingerprint that's available in the simplestream data.
- Improves pre-existing image detection
When importing an Ubuntu image that's already in the store, no
download will occur, instead, any extra alias passed on the command line
will be set.
Closes #1161 …
=> Last couple of 0.19 features

lxd/container.go
Since we use load_config ot load raw.lxc, empty lines and comments
aren't a problem and so can be allowed in raw.lxc.
Reported-by: Chuck Short
=> Allow comments and empty lines in raw.lxc

lxd/apparmor.go
In order to attach to a container (nested), we need 'ptrace'.
In order for lxc-stop to work, we need 'signal'.
The stock lxc nesting profile provides these by inheriting them
from the 'start-container' profile.  We hadn't added them to the
apparmor code for containers with security.nesting=1.  Add them.
=> Add needed apparmor permissions for nesting

lxd/container.go, test/suites/lvm.sh
Fixes publishing LVM-backed snaps and containers.
=> Start container storage before publish

test/suites/basic.sh
On some systems it seems to be possible to run into a case where the MAC
address of a device isn't actually set for a while.
This is likely a kernel issue as a veth pair device should always have a
MAC, but it's shown up a few times, especially in the Ubuntu CI lab and
is annoying, so let's ignore that case since it's clearly not a LXD bug.
=> tests: Don't fail on kernel race conditions

scripts/lxd-setup-lvm-storage
Fixes a minor annoying message that can happen when repeatedly using the script to set up and tear down storage, and occasionally forgetting to clear out all images, causing the script to bail halfway at first.
=> scripts: Don't attempt to delete nonexistent file

shared/image.go
We need to ensure the value we push is a bool and not an integer.
=> Fix image show/edit

lxd/storage_zfs.go
It looks like in some cases we have a stopped container that still holds
some fs reference in the kernel, causing some problems at destroy time.
So let's do a lazy unmount ahead of time which seems to help the kernel
clean things up, making zfs succeed.
=> zfs: Force an unmount ahead of destroy

lxd/migrate.go, lxd/rsync.go, lxd/rsync_test.go
Fixes #1212 
Also includes extra support for debugging rsync, but doesn't do anything verbose by default.
=> Start LVM storage at source before migration

lxd/storage_lvm.go
Greatly reduces amount of time it takes to mkfs for newly created LVs,
for images and copy targets.
=> Reduce default LV size

Makefile
Otherwise you can never rebuild the tags. If this gets too cumbersome, we
can just mark it .PHONY.
=> add some dependencies for the tags makefile target

shared/util.go, shared/util_linux.go
This function is not available on Windows and is not used
in lxc client. After this is merged `go get ...` should work ok
on this platform (#825).
=> Move GetFileStat into shared/util_linux.go

test/suites/lvm.sh
- vgcreate would fail when LXD_DEBUG was not defined because the first
arg would be ""
- losetup -d was given list of devs as a single argument in quotes
=> Fix test breakage: shellcheck quoting suggestions

shared/util_linux.go
So let's free these manually. This (in large part) addresses #1237, but I'm
still seeing a small leak somewhere I think.
=> C.CString results need to be freed manually

lxd/container.go, lxd/container_exec.go, lxd/container_file.go, lxd/container_snapshot.go, lxd/container_state.go, lxd/container_test.go, lxd/containers.go, lxd/containers_post.go, lxd/db_containers.go, lxd/db_devices.go, lxd/db_profiles.go, lxd/db_test.go, lxd/devices.go, lxd/devlxd.go, lxd/images.go, lxd/migrate.go, lxd/profiles.go, lxd/profiles_test.go, lxd/storage.go, lxd/storage_btrfs.go, lxd/storage_dir.go, lxd/storage_lvm.go, lxd/storage_zfs.go
Mostly this is just sed, but there is also a slight refactoring in that
containerLXD had a single public member named Storage, which collided with
Storage() once you remove the Get postifx. This commit switches that and
its usage to a private member. Also:
1. Go is not Java.
2. Go is not Java.
3. Go is not Java.
4. Go is not Java.
5. Go is not Java.
6. Go is not Java.
7. Go is not Java.
8. Go is not Java.
9. Go is not Java.
10. Go is not Java.
11. Go is not Java.
12. Go is not Java.
13. Go is not Java.
14. Go is not Java.
15. Go is not Java.
16. Go is not Java.
17. Go is not Java.
18. Go is not Java.
19. Go is not Java.
20. Go is not Java.
21. Go is not Java.
22. Go is not Java.
23. Go is not Java.
24. Go is not Java.
25. Go is not Java.
26. Go is not Java.
27. Go is not Java.
28. Go is …
=> nuke *Get postfix from orbit

lxd/daemon.go
In case people are running their LXDs behind a proxy, LXD should also look
in its environment for this information.
Closes #1264
=> LXD should also look in its environment for a proxy

shared/util.go, test/suites/basic.sh
Since we have the concept of "trusted" and "untrusted" requests, and we
don't verify the client cert for untrusted requests, we may as well not
require one.
=> don't require a client cert for untrusted reqs

client.go
This avoids keeping the control socket open indefinitely when Exec is
used within a long running software.
=> Close the control socket on exit

lxd/images.go
The extra hyphen causes 'lxc image import foo.tar.bz2' to fail.
=> Fix extraction of bz2 images

lxd/container_exec.go
We should do this in the server as well.
=> close exec's control connection on cmd finish

shared/util.go
This should fix #1282 issue when a btrfs subvolume is mounted on /var/lib/lxd
=> Fix logic for sharedmount check

client.go, lxc/main.go, lxc/monitor.go, lxd/api10.go, lxd/events.go, lxd/images.go, lxd/operations.go, po/lxd.pot, specs/rest-api.md
This adds the events interface and eventSend function that can be hooked
wherever we want to send events back to the client.
Also adds a basic "lxc monitor" command (hidden) to show messages as
they arrive.
Note that some operation events aren't currently handled as the
operation subsystem doesn't provide a single codepath for operation
completion and cancelation, making it hard to send an event for those.
Also, this doesn't hook in our logging system yet.
=> Add events interface

scripts/lxd-images
If an image can't be found in the releases stream, try to find it in the
daily stream instead.
That only applies if --stream isn't specified and doesn't apply to
automatic image update.
=> lxd-images: Fallback to daily stream

lxd/rsync.go, lxd/storage.go
Reported-by: Jamie Brown <Jamie.Brown@mpec.co.uk>
=> rsync: always use --numeric-ids

scripts/lxd-images, test/suites/config.sh
=> lxd-images: Use tempfile instead of memory

lxd/apparmor.go
This doesn't have any effect, since we do a change_profile later, so let's
drop it.
=> drop extra change_profile call in nesting case

lxc/exec_windows.go
Because it is already used by log15.v2
=> Use github.com/mattn/go-colorable instead of shiena/ansicolor

lxd-bridge/lxd-bridge-proxy/main.go
This gets us rid of goproxy and all its dependencies.
The result is equivalent for HTTP proxying, we do loose support for
proxying of other protocols but since lxd-bridg-proxy has never been
turned on for anyone, that's fine for now.
We'll set it as an HTTP proxy by default and if there's strong demand,
add HTTPs proxying then (CONNECT support).
=> Replace goproxy by minimal http proxy

lxd/container.go, lxd/images.go, lxd/main.go, lxd/storage.go, lxd/storage_btrfs.go, lxd/storage_dir.go, lxd/storage_lvm.go, lxd/storage_test.go, lxd/storage_zfs.go, test/main.sh, test/suites/lvm.sh
This makes our compression be reproducible and then fixes publication of a snapshot.
In the past our code was utterly broken and would always publish the container rather than the requested snapshot, once that was fixed, lvm, btrfs and zfs all failed for different reasons:
- lvm: snapshot is read-only
- btrfs: snapshot is read-only
- zfs: snapshot isn't mountable and is read-only
So I had to extend the storage API to add the ContainerSnapshotStart and ContainerSnapshotStop functions which are now called when calling StorageStart and StorageStop on a snapshot.
In those functions, I had to do different tricks depending on the way things are stored in the different supported filesystems:
- dir: nothing
- btrfs: move existing mount to a ".ro" and make a temporary read-write snapshot in the …
=> Various image fixes

README.md, lxd/container.go, lxd/db.go, lxd/db_profiles.go, lxd/db_test.go, lxd/profiles_test.go
As of kernel 4.4/criu 1.8, users will be able to checkpoint/restore
containers which are in user namespaces and using seccomp filters (as well
as STRICT mode). Since (at least) these versions will be in 16.04, let's
drop this restriction.
=> drop security restrictions from "migratable" profile

lxd/container.go
These include common.conf, which explicitly allows creation of 5:1, which
is what we're trying to deny.
=> init: move cgrouop devices deny after includes

lxd/migrate.go
Mostly for my own sanity, let's name these directories something a little
more descriptive.
=> migrate: use more descriptive names for tempdirs

scripts/lxd-images
Fixes errors caused by shutil not being defined when `__del__` is called.
specifically, when called with --help, it would display the following traceback:
```
~/go/src/github.com/lxc/lxd/scripts/lxd-images --help
usage: lxd-images [-h] [--quiet] {import,sync} ...
LXD: image store helper
positional arguments:
{import,sync}
import       Import images
sync         Sync images
optional arguments:
-h, --help     show this help message and exit
--quiet        Silence all non-error output
Examples:
To import the latest Ubuntu Cloud image with an alias:
/home/ubuntu/go/src/github.com/lxc/lxd/scripts/lxd-images import ubuntu --alias ubuntu
To import a basic busybox image:
/home/ubuntu/go/src/github.com/lxc/lxd/scripts/lxd-images …
```
=> Use atexit instead of __del__ for cleanup

lxd/storage_btrfs.go, lxd/storage_lvm.go, lxd/storage_zfs.go
except for zfs, which can't create empty snapshots. In that case, render a
more accurate error message. N.b. that this means people can't copy
containers with zfs snapshots right now, because the zfs-specific fs
transfer mechanism hasn't landed yet.
=> fix alternate storage backends snapshotting

lxd/daemon.go
so check whether it is on a shared mount ptah after we created it
=> setupSharedMounts: always create shmounts

lxc/exec.go, po/lxd.pot
This allows overriding the setup mode, most useful to force
non-interactive mode when one wants to get PIPEs allocated for stdin,
stdout and stderr without having to close stdin.
Launchpad bug: https://bugs.launchpad.net/ubuntu/+source/lxd/+bug/1522755
Reported-by: Martin Pitt <martin.pitt@ubuntu.com>
=> Introduce a new --mode option to exec

lxc/main.go
This makes it possible to create much more complex aliases like:
aliases:
console: exec @ARGS@ -- bash
Which will define a new "lxc console" command that will execute
"lxc exec <arguments> -- bash".
Closes #1395
=> Allow moving arguments in aliases

README.md
=> fix jenkins build link

lxd/container_lxc.go, lxd/daemon.go, lxd/devices.go
Skip limits code when the controller isn't available, print a message at
daemon startup, similar to AppArmor.
=> Detect available CGroup controllers

lxd/container_lxc.go, lxd/db.go, lxd/db_containers.go, lxd/db_update.go, lxd/devices.go, specs/configuration.md
- Implement basic converter for various units to bytes and bits
- Have existing memory limit code call said converter code
- Update the DB to move everything to the supported syntax
- Adds support for percentage based memory allocation
- Implement limits.memory.enforce (soft or hard, defaults hard)
- Implement limits.memory.swap (true or false, defaults true)
- Implement limits.memory.swap.priority (1 to 10, defaults 10)
Note that on some older kernel (3.13 at least), swap restrictions,
specifically, the swappiness configuration only works in some cases and
fails with EINVAL in others. It's advised that those users upgrade to a
newer kernel (3.19 has been confirmed to work properly) or don't use the
swap restrictions (default configuration doesn't hit the issue).
Signed-off-by: Stéphane …
=> Implement the rest of limits.memory.*

shared/log.go, shared/logging/log.go
We can't use it anyway without some special casing in logContextMap (see panic
below), and all of the code in lxd/ still uses log.Ctx. I think it's a good
idea only to have one "entry point" for this, so let's not declare a second
false one.
Creating nonlive EROR[12-15|09:38:45] TYCHO: got zfs snapshot LOG15_ERROR= LOG15_ERROR="Normalized odd number of arguments by adding nil"
panic: interface conversion: interface is shared.Ctx, not string
goroutine 53 [running]:
main.logContextMap(0xc8200f1740, 0x4, 0x4, 0x0)
/home/tycho/packages/go/src/github.com/lxc/lxd/lxd/events.go:27 +0x13e
main.eventsHandler.Log(0xc82021ed00, 0x0, 0x0)
/home/tycho/packages/go/src/github.com/lxc/lxd/lxd/events.go:41 +0x89
main.(*eventsHandler).Log(0x11ef6e8, 0xc82021ed00, 0x0, 0x0)
<autogenerated>:88 +0xa3 …
=> log: get rid of shared.Ctx

test/backends/btrfs.sh, test/backends/dir.sh, test/backends/zfs.sh
This avoids:
==> TEST: doing static analysis of commits
In test/backends/btrfs.sh line 1:
btrfs_setup() {
^-- SC2148: Tips depend on target shell and yours is unknown. Add a shebang.
In test/backends/dir.sh line 1:
^-- SC2148: Tips depend on target shell and yours is unknown. Add a shebang.
In test/backends/zfs.sh line 1:
zfs_setup() {
^-- SC2148: Tips depend on target shell and yours is unknown. Add a shebang.
=> tests: add a shebang to backend scripts

lxd/storage_zfs.go
If two people try and migrate a snapshot in the same second (or indeed, if
one snapshot doesn't finish deleting before the next migration back starts
as in our test suite) we can get collisions. Let's use a uuid instead.
=> zfs: use uuid instead of timestamp for zfs temp snapshot

lxd/container_exec.go
This avoids:
fatal error: concurrent map writes
goroutine 1337 [running]:
runtime.throw(0x876c710, 0x15)
/lxd/build/tmp.FYCkSnkCEv/gimme/versions/go/src/runtime/panic.go:530 +0x7f fp=0x5082e608 sp=0x5082e5fc
runtime.mapassign1(0x856bac0, 0x506feb40, 0x5082e690, 0x5082e694)
/lxd/build/tmp.FYCkSnkCEv/gimme/versions/go/src/runtime/hashmap.go:445 +0x8b fp=0x5082e668 sp=0x5082e608
main.(*execWs).Connect(0x50670af0, 0x50670bd0, 0x5071cc40, 0x71502130, 0x5066a100, 0x0, 0x0)
/lxd/build/tmp.1h89I19sQ8/go/src/github.com/lxc/lxd/lxd/container_exec.go:76 +0x1e7 fp=0x5082e71c sp=0x5082e668
main.(*execWs).Connect-fm(0x50670bd0, 0x5071cc40, 0x71502130, 0x5066a100, 0x0, 0x0)
/lxd/build/tmp.1h89I19sQ8/go/src/github.com/lxc/lxd/lxd/container_exec.go:321 +0x4c fp=0x5082e73c sp=0x5082e71c …
=> exec: lock fds map for exclusive writes

lxd/storage_lvm.go
ImageCreate() accepts the image fingerprint, not .lv symlink.
This bit me when I was creating a container after changing the storage backend from other to lvm.
```
config: {}
Image imported as: 30e7e15f81023247468be0a3d703e74e52d6fbf83b60917005f518714f08d432
Setup alias: busybox
Creating c1 error.
error: Error Creating LVM LV for new image: Error making filesystem on image LV: exit status 1
config:
storage.lvm_thinpool_name: LXDPool
storage.lvm_vg_name: lxd
LV                                                                  VG   Attr      LSize  Pool    Origin Data%  Move Log Copy%  Convert
30e7e15f81023247468be0a3d703e74e52d6fbf83b60917005f518714f08d432.lv lxd  Vwi-a-tz- 10.00g LXDPool          0.00                        
LXDPool …
```
=> lvm: Fix ImageCreate() call in ContainerCreateFromImage()

lxd/storage_lvm.go
-kn, aka '--setactivationskip n', is required after LVM version 2.02.99, which sets
the activationskip flag to true by default for thin LVs.
However, it is not supported prior to that version so we need to send it
conditionally.
Fixes #1470 
=> lvm: only pass -kn to lvcreate for lvm > 2.02.99

lxd/migrate.go
=> migration: correctly uidshift unprivileged CRIU images

lxd/api_1.0.go, lxd/daemon.go, lxd/storage_lvm.go, specs/configuration.md
LXD has hardcoded ext4 as the filesystem to be used when LVM storage backend is choosed, I don't like very much ext* filesystems and prefer xfs over them so I've done a little patch to be able to use it with LXD.
To be able to choose preferred filesystem a key was added to the configuration parameter of LXD: storage.lvm_fstype, for now it's value can be only ext4 (default, so I don't break anything) and xfs, but it's trivial to add other filesystems.
For now the filesystem has to be choosen at LXD installation time, in the future I think it will be better to let the users to choose filesystem at container creation time so it'll be possible to have different filesystem for different container and so migrating a container from one host to another will be possible even if they have different …
=> Added choosable formatting filesystem for LVs

lxd/migrate.go
See comments, this is another instance of:
https://github.com/golang/go/issues/13155
=> fix race in forkmigrate

lxd/container_lxc.go, lxd/daemon.go
We want to be able to install LXD without pulling all the LXC templates
and tools, at least on Ubuntu systems.
As a result, we can't rely on the template configs and need to move the
parts that matter to us, in LXD itself.
=> Don't depend on the LXC config files anymore

scripts/lxd-images
In the case of an error, if we're in the middle of a progress report, we
might overwrite one of the \rs. Instead, let's just print a \n to clear the
error.
=> lxd-images: print newline when reporting an error

lxd/container.go, lxd/container_lxc.go, specs/configuration.md
Make it possible to load kernel modules before starting a container.
=> Add a new linux.kernel_modules option

scripts/lxd-setup-lvm-storage
-s is optional, but if you don't specify it, you just get errors.
A default size fixes this.
=> lxd-setup-lvm-storage: Add default size of 10G

client.go, config.go, lxc/main.go, lxc/remote.go
Users of the API probably don't want to have to set an environment variable
before loading the config (juju already has code to do this which is pretty
ugly :)
=> api: {Save|Load}Config should take a path as an argument

scripts/lxc-to-lxd
This new script supports migrating most privileged containers to LXD
containers. It supports all the networking and bind-mount options that
LXD itself does, it also properly sets the nesting mode, boot options
and environment variables.
Various options are available to migrate all or just some specific
containers, specify custom lxcpath and lxdpath, make a copy of the
container or move the data and delete the source, ...
Security knobs which LXD doesn't provide cause an error so containers do
not accidently get migrated to a configuration which is less secure.
Unprivileged containers will require some extra work to unmap and remap
them to the LXD range.
=> Initial work on a LXC to LXD script

lxc/main.go
My eyes are still at the prompt, so I have to scroll back visually and
parse all of this output to find the error, which is actually the first
line printed. Instead, let's just print it as the last thing, which means
that it's probably the first thing I see.
=> move usage() message before error

lxd/images.go
All of our other API calls error out when you try to delete something that
doesn't exist, and it seems like this one should too.
=> error out on deleting nonexistent alias

README.md, lxd/container_lxc.go, lxd/daemon.go, lxd/devices.go
If LXC fails to parse the config, we should make it clearer by setting a
BROKEN container status which downstreams can react to.
This specifically should allow removing containers with broken LXC config.
Reported-by: Justin Thomas
=> Better deal with broken LXC

lxd/container_lxc.go, lxd/devices.go
My kernel doesn't like setting zero limits:
lxc 20160126090053.350 ERROR    lxc_cgmanager - cgmanager.c:cgm_setup_limits:1535 - call to cgmanager_set_value_sync failed: invalid request
lxc 20160126090053.350 ERROR    lxc_cgmanager - cgmanager.c:cgm_setup_limits:1538 - Error setting cgroup blkio:lxc/unpriv limit type blkio.throttle.read_bps_device
lxc 20160126090053.350 ERROR    lxc_start - start.c:lxc_spawn:1090 - failed to setup the cgroup limits for 'unpriv'
lxc 20160126090053.383 ERROR    lxc_start - start.c:__lxc_start:1272 - failed to spawn 'unpriv'
lxc 20160126090438.835 ERROR    lxc_monitor - monitor.c:lxc_monitor_open:209 - connect : backing off 10
lxc 20160126090438.864 ERROR    lxc_cgmanager - cgmanager.c:cgm_setup_limits:1535 - call to cgmanager_set_value_sync failed: invalid …
=> only set io limits when they are nonzero

specs/command-line-user-experience.md, test/extras/stresstest.sh
This pull request fixes configthread() in stresstest.sh and command-line-user-experience.md examples of limits.memory to include byte suffix.
Signed-off-by: Janne Savikko <janne.savikko@aalto.fi>
=> fix profile tests and cli user experience examples of limits.memory to include byte suffix

lxd/container_lxc.go
This re-enables a pts device backing /dev/console and allows container
writes to it.
That change will break CRIU until it knows how to deal with
/dev/console, but lakc of /dev/console is breaking enough workloads that
it's the best option for now.
Closes #1463
=> Re-enable /dev/console

lxc/image.go, lxc/list.go
Proposal : regex on lxc image filter. Example with images.linuxcontainers.org : 
- before : 
lxc image list images: description=Ubuntu => no results
- after : 
lxc image list images: description=Ubuntu 
OR
lxc image list images: description='Ubu.*'
==> all ubuntus images 
Used a regex test and falling back to old test to ensure it won't fail. 
Let me know if it sounds good for you. 
Signed-off-by: Joel Seguillon <joel.seguillon@gmail.com>
=> Regex for image list filters

lxd/container_lxc.go
... instead of failing the action entirely.
My root disk is mounted on /dev/mapper/root, note the unexpected
subdirectory.  Without the continue clause, 'lxc init' fails with the
"Disk is missing /sys/class/block entry" error since there is no
/sys/class/block/mapper/root.  Also 'lxc list' fails silently (displays
a table with a header but no containers).
Since a device node with the same major:minor is also at /dev/dm-0, it's
valid to simply ignore the identical node at /dev/mapper/root
Signed-off by: Erik Mackdanz <stasibear@gentoo.org>
=> Disregard block devices in /dev subdirectories

lxd/storage_zfs.go
Without this change, copying a non-zfs container to a new container
that's backed by zfs was failing due to ContainerCreate already creating
the symlink and setting the permissions on the new path.
Reported-by: Brad Figg
=> zfs: Fix cross-backend copies

lxd/db_profiles.go
I'm not sure if we want to try and do this retroactively or not.
Closes #1491
=> add eth0 "name" to the default profile

lxd/container_lxc.go, lxd/devices.go
Lets not completely fail startup/update on things the user cannot do
anything about. It's almost impossible to know what devices we can set
block limits on, so if we can't, just move on.
Closes #1568
=> Make blkio limits more robust

lxc/list.go, lxd/devices.go, po/lxd.pot
This improves performance about as much as we can realistically do it,
less than 100ms per container when retrieving all network information,
cgroup and disk usage.
To get any faster, simply not requesting the information by using -c is
the way to go.
Closes #671
=> list: Query containers by batch of 10

shared/cert.go, shared/cert_test.go, shared/util_test.go
Juju was working around the fact that GenCert always wrote directly to disk. Instead split the
function into 2 functions. One that just generates the certificate bytes, and another one
that will write that content into files.
Add a test for the helper function. It is unfortunately a bit slow (2s), but it can be skipped with 'go test -short'.
Also, suppress printing all the lines that were read by ReadLastNLines, as it makes it
hard to see what the actual test suite is doing.
Signed-off-by: John Arbash Meinel <john@arbash-meinel.com>
=> Refactor the GenCert function so it can be reused.

shared/util_test.go
Rather than go through another reivew cycle, here's my only comment for
PR #1641.
=> tests: get rid of commented out code

lxd/container.go, lxd/container_lxc.go, lxd/db_update.go, lxd/devices.go, shared/util.go
For other golang clients who want to figure out the memory from a LXD limit
in string format from the config, this is useful.
=> shared: export limit parsing function

README.md
Wording can be changed. This was just confusing for me since I thought both binaries ship together in the `lxd` package, however `lxc` is a separate package `lxd-client`.
=> Add upgrade procedure to README

lxd/container_lxc.go
If we get garbage back from the cgroup subsystem we should just render
the values as empty or -1 rather than fail the entire REST call for it.
=> Don't allow the state functions to fail

shared/util_linux.go
=> exec: don't s/\\n/\\r\\n/g when interactive

shared/util_linux.go
This reverts commit 17d3dcf7404f9e6f5bc2702193cb8cac1153ed9e.
=> Revert "exec: don't s/\\n/\\r\\n/g when interactive"

client.go, config.go, lxc/image.go, lxc/remote.go, lxd/containers_post.go, lxd/daemon.go, lxd/daemon_images.go, lxd/images.go, po/lxd.pot, shared/architectures.go, shared/architectures_linux.go, shared/architectures_others.go, shared/simplestreams.go, shared/util.go, specs/rest-api.md
With this, we get the two simplestreams remote and can interact with the remote image store, copy from it, export from it and start containers from it.
The next step will involve implementing sync support into the LXD daemon so that those images can be kept in sync in the background.
=> Implement initial simplestreams support

client.go, lxc/action.go, lxd/container_lxc.go, lxd/db_containers.go, shared/container.go, specs/rest-api.md
This exports the fact that the container contains stored state through
the same "stateful" property already used by snapshots.
With this information, the client can now only restore a stateful
startup when state is in fact stored.
Which in turn means the daemon can return an error when requested to
restore state for a container which has none.
=> Improve stateful stop

README.md
This pull request adds missing package "make" to build dependencies installation command.
Signed-off-by: Janne Savikko <janne.savikko@aalto.fi>
=> Add package "make" to build dependencies installation command

shared/idmapset_linux.go
We parse /etc/sub?id and stop when we find an entry for the user.  If
that isn't big enough, we later refuse to start unpriv containers.  But
sub?id may have later entries which are big enough - so just always
make sure to only return entries which will suffice.
Closes #1687
=> Don't stop at an unsatisfactory sub?id entry

lxc/action.go, po/lxd.pot
$ lxc stop images:
error: Must supply container name for: "images:"
Closes #1689
=> client: better error on `lxc stop remote:`

client.go
Now that the API is designed to use these default "ubuntu" remotes, let's
make sure they're available in all instances of the client.
=> client: add default config in NewClientFromInfo

lxd/container_lxc.go
The kernel prevents us from bind-mounting filesystems which have entries
hidden by overmounting.
This currently prevents startup of some containers when
/sys/kernel/debug/tracing, an auto-mounted path has been accessed on the
host.
Fix this by simply recursively bind-mounting things into the container.
Reported by: cmars & stokachu
=> Workaround kernel overmounting protection

lxd/storage_lvm.go, test/backends/lvm.sh
We spend more than 50% of the LVM test time in mkfs.ext4, despite using
test images only a few kB large, so lets make the LV size configurable
through environment and set it to something really small for the
testsuite.
=> Allow reducing the LVM LV size and update tests

client.go
We need the other attributes of RemoteConfig in order to connect
to the simplestreams and other 'static' hosts.
Signed-off-by: John Arbash Meinel <john@arbash-meinel.com>
I'm not 100% sure this is enough for us, I want to update the Juju client to match, so that Juju can use the known remotes to copy images for LXD provider instead of "lxd-images import". But I wanted to check that this is an ok step in that direction.
=> WIP: Change ConnectInfo to take a RemoteConfig.

lxd/db_profiles.go
If we mask this error with the useless "here" prefix, the rest of the error
handling code doesn't figure out that it's a sql.NoRows error, and thus
doesn't propagate the 404 correctly, so we end up with:
$ lxc profile edit host1:invalid
error: here: sql: no rows in result set
=> profiles: don't mask error message when not found

lxd/db_test.go, lxd/migrate.go, lxd/storage.go, lxd/storage_btrfs.go, lxd/storage_dir.go, lxd/storage_lvm.go, lxd/storage_test.go, lxd/storage_zfs.go
This breaks up live migrations into two parts: first we send a snapshot of
the filesystem while the container is running (and all of its snapshots),
then we do the checkpoint and do a final incremental send. The goal here is
to minimize the amount of downtime for the container.
=> migration: attempt to be slightly smart about moving filesystems

lxd/container_lxc.go, lxd/devices.go
If we lxc config device add x1 disk type=disk source=/dev/null, lxd
should not try to detect the filesystem (and fail when it can't).
The function as it stands woudl've made sense, but every caller of
it really wants to know whether it's a block device, so rename the
fn and have it return false for chardevs.
=> mounting: only block devices hold filesystems

client.go, lxc/remote.go, lxd/api_1.0.go, lxd/daemon.go, lxd/daemon_images.go, lxd/images.go, shared/network.go, shared/proxy.go, shared/simplestreams.go, specs/configuration.md
juju will want to set proxy information on the daemon to tell it where to
ask for images. This commit adds configuration varaibles for common proxy
information, so that juju can use the LXD API as opposed to hacking the
init script to start LXD with HTTP_PROXY env enabled.
Note that this commit will no longer use HTTP_PROXY, but requires users to
use the configuration instead.
=> daemon: support proxy configuration options

lxd/storage_lvm.go
Since these are actual errors that are unexpected, let's log them as such.
Perhaps we should even go so far as to render the LVM output in the error
that's reported to the user, although I didn't do that right now.
=> lvm: make errors log as errors

lxd/container.go
This pull requests fixes inaccurate error message of snapshotting with existing snapshot name (issue #1725) by using message format "Snapshot '<container>/<snapshot>' already exists".
Signed-off-by: Janne Savikko <janne.savikko@aalto.fi>
=> Fix error message when snapshot with duplicate name

lxc/list.go, lxd/container_lxc.go, lxd/containers_get.go, shared/container.go, shared/status.go
If a container monitor is unresponsive, we may wait forever for
responses over the lxc command socket.
An easy way to reproduce this is to choose a container monitor
process (look for a process like:
[lxc monitor] /var/lib/lxc/containers containername
) and suspend it with 'kill -STOP'.
So put a one-second timeout around calls to the go-lxc State()
function.  This leads to lxc list feedback like:
0 ✓ serge@sl ~ $ lxc list
+------+-------+------+------+------------+-----------+
| NAME | STATE | IPV4 | IPV6 |    TYPE    | SNAPSHOTS |
+------+-------+------+------+------------+-----------+
| x1   | ERROR |      |      | PERSISTENT | 0         |
+------+-------+------+------+------------+-----------+
0 ✓ serge@sl ~ $ lxc info x1
error: Monitor is hung
1 ✗ serge@sl ~ $ lxc stop x1
error: …
=> Handle unresponsive container monitors

lxd/devlxd.go
When some containers are stopped and devlxd is accessed through an
interactive LXD exec shell, the code fails to find what container the
request came from.
To fix that, just make sure we skip stopped containers.
This may be the source of #1751
=> Fix devlxd failing to detect container

lxd/container_lxc.go, lxd/images.go, specs/image-handling.md
We unfortunately can't use the suggested "overwrite" keyword because
we'd need it to default to true when unset and the yaml parser doesn't
let us do that.
So instead we call it "create_only" and have it default to false
(default for bool types) which gives us an equivalent behavior.
Closes #1757
=> Make it possible to have templates only apply for non-existing files

lxd/db.go, lxd/db_profiles.go, lxd/db_test.go, lxd/db_update.go
Until we have stackable apparmor profiles, docker needs to be told that
apparmor is not enabled, so that it won't try (and fail) to load new
profiles.
Do this by mounting /dev/null over /sys/module/apparmor/parameters/enabled
=> docker profile: add the apparmor enabled overmount

lxd/container_lxc.go
After we just made that change in LXC, lets replicate it in the LXD
default config too.
=> Block sys_rawio in LXD too

doc/rest-api.md
Signed-off-by: Jeff Shantz <jeff@csd.uwo.ca>
I just added the `auto_update` parameter to the API documentation for `POST /1.0/images`.  I'm implementing an API client in Ruby and didn't realize it was allowed until I inspected the output of `lxc image copy ... --debug --verbose`.
=> Document 'auto_update' parameter for 'POST /1.0/images'

lxd/container_lxc.go
We deleted the snapshot contents on failure, but not the db state. Let's do
that too.
=> stateful stop: remove snapshot from db on failure too

lxd/container_lxc.go
After some discusssion on IRC, it seems that 1s might not be long enough.
Let's bump it to 5s until we have a better solution.
=> bump the monitor timeout to 5s

lxd-bridge/lxd-bridge
- Don't start dnsmasq when no IPv4 or IPv6 is configured
- Don't try to kill dnsmasq or the proxy if there's no pid file
- Use /etc/default/lxd-bridge instead of /etc/default/lxd
=> lxd-bridge: Some tweaks

lxc/config.go, lxc/profile.go, lxd/api_internal.go, lxd/container_lxc.go, lxd/daemon.go, lxd/db_test.go, lxd/db_update.go, lxd/devlxd_test.go, lxd/main.go, lxd/main_test.go, lxd/storage.go, po/lxd.pot
We need a way to update the default profile at startup time before any container gets spawned but after the daemon is responsive over REST.
This is achieved through a new setup mode which lets us do just that.
While doing that, also improve waitready to wait until the daemon is actually ready rather than just until it answers.
And then because having to rewrite device entries every time you want to change a property is a bit annoying, implement device set/unset too.
=> Bits needed by lxd-bridge init scripts

lxd-bridge/lxd-bridge
Otherwise we can't stop it after changing the settings.
=> Allow the bridge to be brought down even if disabled

lxd-bridge/lxd-bridge
- Use /run/lxd-bridge and /var/lib/lxd-bridge
- Set the right path for lxd-bridge-proxy
- Correctly pass the address to lxd-bridge-proxy
- Properly configure IPv6 forwarding
- Disable IPv6 duplicate address detection and auto-configuration even
if not setting a global IPv6 address
=> Some more lxd-bridge fixes

lxd/container_exec.go
This error message looks to be copy pasted from somewhere incorrectly.
=> exec: remove dead code path

config/bash/lxd-client
* Fix `lxc file` completion.
* Fallback to default bash file/path completion if we do not provide
any. Useful with `lxc file push` and `lxc file pull`, maybe with
others.
Signed-off-by: Yura Pakhuchiy <pakhuchiy@gmail.com>
=> Improve bash completions

test/main.sh
tests_basic_usage for example parses the output of `lxc` so we need LC_ALL to be english/C.
Signed-off-by: Rene Jochum <rene@jochums.at>
=> Tests: Don't translate lxc output for parsing it.

lxc/exec.go, lxd/container.go, lxd/container_exec.go, lxd/container_lxc.go, lxd/containers.go, lxd/main.go
This introduces a new "forkexec" sub-command which is used for all exec
calls. The thought is that the random lockups we were seeing before this
were caused by a race between go-lxc calling liblxc which called fork()
and some of the other goroutines.
Closes #1803
=> Use fork for command execution

lxd/container_lxc.go
Without this we forget to unmount the partition on LVM which then
prevents the container from starting.
Closes #1839
=> Stop the storage code after we're done remapping

lxd/cgroup.go, lxd/devices.go
it shows offline cpus.  So as discussed on irc,
17:51 < stgraber> hallyn: so I think we should 1) get rid of
deviceGetCurrentCPUs 2) change deviceTaskBalance to read
/sys/fs/cgroup/cpuset/cpuset.effective_cpus 3) replicate it to
/lxc/cpuset.effective_cpus (not sure if we need that but I seem to remember
cpuset being weird) 4) use that list instead of deviceGetCurrentCPUs when
nothing is listed in limits.cpu
Add two simple helpers in lxd/cgroup.go to get/set cgroup files.
=> rebalance: don't use the cpu map from /proc/self/status

lxd/container_lxc.go, lxd/daemon.go
If a container is setup without security.nesting = true, and someone
runs lxd in that container, we want lxd to run but fail (with clear
error) when starting a container.  Otherwise 'lxc list' and
dpkg-reconfigure lxd will hang forever, with errors going only to
syslog.
=> lxd: do run if we fail to mount shmounts

lxd/api_1.0.go
This is needed to make a proxy config change immediately effective.
=> Invalidate the simplestreams cache on proxy change

lxd/container_lxc.go, lxd/containers.go
Now that we're dending on this file to exist in all cases when execing,
let's always write it.
=> write the container's config file on start to the log path directly

shared/simplestreams.go
Before, we always tried to hash the body regardless of the status code,
which meant that we would hash the contents of e.g. a 404 message if the
thing wasn't found, and issue a "Hash mismatch" error, masking the real
error.
=> simplestreams: give better error on invalid source stream

lxc/launch.go, po/lxd.pot
Let's give a CLI example that actually launches a container successfully.
=> command line: fix example in `lxc launch`

lxd/devices.go
cpuset.effective_cpus is better because it does not include cpus which
we cannot use.  But it is not available on older kernels.  In that
case fall back to using cpuset.cpus and hoping for the best.
Closes #1929
=> cpuset: fall back to cpuset.cpus on older kernels

lxd/migrate.go
068313ad07d8971cd148a345463310227fcdad39 moved the config file to a
non-temp file, so let's not delete it.
=> don't remove config file on forkmigrate

lxd/daemon.go, lxd/daemon_config.go, lxd/storage_lvm.go
Storage functions unfortunately have the habit of reading the daemon
configuration, so we need to at least temporarily set daemonConfig to
the right value...
=> Fix daemonConfig handling of storage

lxd/rsync.go
When rsyncing something, let's not mask err, so we can fail properly if the
rsync fails.
=> don't alias rsync error condition

lxd/container_lxc.go
We were using /containers/$container/rootfs/state as the directory to save
CRIU state in; instead, let's just use /containers/$container/state.
=> state: fix state dir

lxd/images.go
e.g. if someone deletes the zpool manually, they then can't delete an
image, because we can't detect the filesystem type for the path, because it
doesn't exist any more. Let's not fail so hard when we can't detect the
filesystem.
=> images: don't fail deleting when the storage delete fails

lxd/container.go, lxd/container_lxc.go
In particular, stateful stop/snapshot didn't have a check.
=> add more checks for the criu binary

test/suites/migration.sh
In particular, same-host-different-lxd migration doesn't work right now
because of some cgroup path issues. CRIU will need to learn how to rewrite
mount paths to support this use case, but it's not a super high priority
right now.
Instead, let's use stateful snapshot/restore which will work, so that we
can at least test the CRIU machenery.
=> rework (live) migration tests

client.go, doc/rest-api.md, lxc/init.go, lxc/launch.go, test/lxd-benchmark/main.go
containers_post.go has an implementation which respects the devices
parameter. Let's document it and also pass it in.
=> client: Init() supports passing in devices

lxc/image.go, po/lxd.pot, test/suites/basic.sh
Adds the --format option to the `lxc image list` command. Possible options are table and json.
Image list filters still work regardless of output format.
--format table example:
```
$ lxc image list images: 'description=.*yakkety.*s390x.*' --format table
+-------------------------------+--------------+--------+-----------------------------------------+-------+---------+------------------------------+
|             ALIAS             | FINGERPRINT  | PUBLIC | DESCRIPTION               | ARCH  |  SIZE   |         UPLOAD DATE |
+-------------------------------+--------------+--------+-----------------------------------------+-------+---------+------------------------------+
| ubuntu/yakkety/s390x (1 more) | 03a93a03d6bb | yes    | Ubuntu yakkety (s390x) (20160517_03:49) | s390x | 73.19MB | …
```
=> Add --format and json output for image list command

config/bash/lxd-client
* add completion of global and container config keys
* ignore --arguments when completing
* add completion of remote and profile names where it makes sense (but
still always prefer completing local container names in commands like
`lxc start`)
* do a better job of completing subcommands like `lxc config trust` and
`lxc config device`
=> better bash completion

shared/operation.go
Let's use the default for this now so we do less copying. In my tests this
doesn't make a huge difference, but it does shave 2 seconds off of a 50
second or so transfer on average. Presumably bumping this higher when we
know we're going to be dumping a lot of data is a good idea, but that's for
a later set when I've done more experiments.
=> use default buffer size for WebsocketUpgrader

config/bash/lxd-client, doc/configuration.md, lxd/container.go, lxd/containers.go, test/suites/basic.sh
Currently, if a container takes more than 30 seconds to shutdown it is stopped anyway. The 30 second timeout is hardcoded and this change makes the timeout configurable.
This `boot.force_shutdown_timeout` container config key sets how long to wait (in seconds) for a container to shutdown before it is force stopped.
I used config key `boot.force_shutdown_timeout` as its pretty meaningful, and shouldn't get confused with unrelated `lxd shutdown --timeout` option. If there are any other suggestions for the config key name, or if it should be in a different namespace than "boot", please let me know.
Closes https://github.com/lxc/lxd/issues/2027
Signed-off-by: Rene Fragoso <ctrlrsf@gmail.com>
=> Add config key for container force shutdown timeout

doc/configuration.md, lxd/api_1.0.go, lxd/container.go, lxd/container_lxc.go, lxd/profiles.go, lxd/seccomp.go, test/suites/basic.sh
In particular,
* make the default seccomp config optional
* add a knob to block x32 syscalls on amd64 (enabled by default)
* add a way for users to inject their own seccomp stuff
=> add some seccomp knobs

client.go, lxd/container_exec.go, lxd/storage_btrfs.go, lxd/storage_zfs.go, shared/network.go, shared/util.go, shared/util_test.go
Here's some more work on #1890, namely, to use a larger buffer to cut down on the CPU work needed to do by LXD on a per-frame basis for websocket frames.
Note that I played with various websocket parameters here (in addition to and independent of) this one, see the top two commits here: https://github.com/tych0/lxd/commits/buffering-extras
But this is the one that had the biggest effect. Using bigger buffers for the websocket i/o itself actually slowed things down.
Also note that I chose a 4MB buffer here. Larger buffers (I tested up to 128MB) seem to speed things up, but only marginally, and 4MB is enough to capture most of the speedup (>50s down to about 25-28s).
Finally, there is one more thing I can think to try here, so I'm still not closing that issue, as we may be able to speed …
=> Use buffers for zfs btrfs send

shared/util_test.go
We don't really need good crypto data here, but the nice math/rand.Read API
wasn't added until go 1.6, and we still test on 1.5, so let's just use this
for now.
Some day in the future we can revert this and have our tests go fast again.
=> use crypto/rand instead of math/rand for testing

shared/network.go
Consider,
t=2016-05-31T20:49:07+0000 lvl=dbug msg=MigrationSink driver=storage/dir live=false container=nonlive objects=[nonlive/snap0]
t=2016-05-31T20:49:07+0000 lvl=dbug msg="sending write barrier"
t=2016-05-31T20:49:07+0000 lvl=dbug msg="Got message barrier, resetting stream"
t=2016-05-31T20:49:07+0000 lvl=dbug msg="sending write barrier"
t=2016-05-31T20:49:07+0000 lvl=dbug msg="Got message barrier, resetting stream"
panic: concurrent write to websocket connection
goroutine 560 [running]:
panic(0x9b9da0, 0xc42012a000)
/lxd/build/tmp.xTgWRy05x1/go/golang/src/runtime/panic.go:500 +0x1a1
github.com/gorilla/websocket.(*Conn).flushFrame(0xc42000bb00, 0xc42034e601, 0x0, 0x0, 0x0, 0xc42034e778, 0xc42046c001)
/lxd/build/tmp.xTgWRy05x1/go/src/github.com/gorilla/websocket/conn.go:481 +0x414 …
=> probably fix a concurrent websocket write

client.go, lxc/file.go, test/suites/basic.sh
This change prevents `lxc file edit` from changing the target file's permissions when a container's file is edited. To fix this, a new PushFileEdit() method was added that does not send any permission information to lxd server. When no permission information is passed on, permissions for the target file are not changed.
Reason for adding PushFileEdit instead of reusing existing PushFile() method is that there was no way of specifying -1 for its mode argument(os.FileMode type, which is uint32). The zero value of os.FileMode is actually a valid mode, so couldn't use that to indicate "no mode" either.
Closes https://github.com/lxc/lxd/issues/2047
=> Make sure lxc file edit doesn't change target file's permissions

lxc/image.go, po/lxd.pot, test/suites/basic.sh
This change allows lxc image delete subcommand to take multiple arguments. Each image name specified will be deleted.
Currently we try to delete the images in sequence, but will exit with an error if deleting any image returns an error.
Change is backwards compatible since `lxc image delete [remote:]<image>` still works as before.
Closes https://github.com/lxc/lxd/issues/2054
New subcommand help output:
```
lxc image delete [remote:]<image> [<image>...]
Delete one or more images from the LXD image store.
```
Sample usage / confirmation:
```
vagrant@vagrant:~/go/src/github.com/lxc/lxd/test$ lxc image list
+-------+--------------+--------+-------------------------------------+--------+--------+-----------------------------+
| ALIAS | FINGERPRINT  | PUBLIC |             DESCRIPTION …
```
=> Allow lxc image delete to delete multiple images

client.go, client_test.go, lxc/main.go, po/de.po, po/fr.po, po/ja.po, po/lxd.pot, test/suites/static_analysis.sh
Modify the client's error handling to support os.SyscallErrors.  Move
the error handling to an exported function in the client so that the
code can be reused by other projects, e.g. juju.
Add a message to the 'funcs starting with empty line' test to help
users with bad habits understand what they did wrong.
=> Add support for os.SyscallError in client

doc/api_extensions.md, doc/rest-api.md, lxc/list.go, lxd/api_1.0.go, lxd/container.go, lxd/container_lxc.go, lxd/db.go, lxd/db_containers.go, lxd/db_update.go, po/lxd.pot, shared/container.go, test/suites/basic.sh
From the `lxc list` command, we have a new column key `l`, that shows the `LAST USED AT` field. The column will be blank of container was never started or lxc client is connecting to an older lxd daemon whose API response doesn't include a `last_used_at` field.
- API documentation was updated. Please let me know if I missed something
- DB schema and migration scripts were updated. Tested by creating DB with older lxd and then running newer lxd, which updated schema and continued functioning properly.
- Tried to keep naming scheme of JSON, DB, and struct fields consistent with existing image last use field
One tricky part with adding this feature was what date should we show if a container has not been started yet. In original issue it was suggested to use 0 EPOCH (1970-01-01T00:00:00Z). …
=> Store and show time when container was last started

lxd/daemon.go, shared/network.go
- This drops the ECDSA ciphers from the announced list by the server as
since our certificate is RSA, those cannot be used.
- We also now allow connections using CBC-SHA instead of GCM-SHA256 as
this is needed by some older clients.
Closes #2034
=> Tweak TLS cipher list a bit

client.go, client_test.go, lxc/remote.go, shared/util.go
Use strings.TrimPrefix to strip 'unix://' from the URL/path in both
remoteCmd.addServer() and connectViaUnix.  This resolves the direct
cause of the panic and makes the handling of relative paths consistent
in both flows.
Add a check for IsDir when determining whether HTTPS or UNIX should
be assumed.  The UNIX scheme requires a full path to the UNIX socket,
i.e. a directory can never be a valid LXD server.
Fixes #2089
=> Fix a panic in 'remote add'

doc/configuration.md
Fix the description of the "unix-block" device type to talk about block
devices rather than character devices.
=> doc: Fix typo in "unix-block" description

lxd/container.go
In principle these should be the same, but in practice they're different,
because the time.Times are loaded from the database using the local time
zone, giving the error below on non-UTC hosts.
ok  	github.com/lxc/lxd	0.004s
?   	github.com/lxc/lxd/fuidshift	[no test files]
ok  	github.com/lxc/lxd/lxc	0.003s
--- FAIL: TestContainer_LoadFromDB (1.45s)
Error Trace:	container_test.go:122
Error:		Not equal: &main.containerLXC{architecture:2, cType:0, creationDate:time.Time{sec:63601175312, nsec:0, loc:(*time.Location)(0x1377f80)}, lastUsedDate:time.Time{sec:62135596800, nsec:0, loc:(*time.Location)(0x1281c00)}, ephemeral:false, id:3, name:"testFoo", stateful:false, expandedConfig:map[string]string{"security.privileged":"true", "volatile.eth0.hwaddr":"00:16:3e:0a:38:39", …
=> actually load the LastUsedDate from the database on create

lxc/main.go, lxc/remote.go, test/main.sh, test/suites/basic.sh, test/suites/remote.sh
Delay certificate generation until the client attempts to communicate
with with a remote server.
Change the check for the 'first time using LXD' message to key off the
existence of the client's config directory (create the directory after
the help message has been printed).  Invert the check for the existence
of /var/lib/lxd when printing the help message; the message should be
printed if /var/lib/lxd missing, which implies that 'lxd init' has not
been run.
Fixes #1851
=> Generate the LXD client certificate on-demand

client.go, test/deps/import-busybox, test/suites/basic.sh
The split image path didn't pass in 'target' to the Join call.
Add an integration test to verify exporting split images.  Add an
option to the import-busybox script to control whether or not to
set the filename for split images.  Change the effective filename
to be 'busybox', previously it was being set to 'busybox.rootfs'.
Fixes #1980
=> Add target path to rootfs tarball in image export

client.go
This avoids generating URLs which Go then drops on the floor.
Closes #2112
=> Normalize the URLs in the client

config.go, lxc/main.go, test/suites/basic.sh
Move default aliases into the alias checking code itself instead of
making them a property of the default config.  Add unix-like aliases
to the map of default aliases, e.g. cp, ls, mv and rm.
Fixes #1615
=> Build unix-like aliases directly into LXC

lxc/action.go
=> similar to lxc delete, add a -f shortcut to lxc stop

lxd/container_lxc.go
Defer the function to undo changes and track whether or not the changes
should be kept using a closure over a bool.  This eliminates the need to
explicitly call undoChanges() in every failing return path.
=> Use defer to undo changes on failed update

lxd/images.go, lxd/main.go, lxd/storage_btrfs.go, lxd/storage_dir.go, lxd/storage_lvm.go, lxd/storage_zfs.go, shared/simplestreams.go
This is now needed for Ubuntu 16.10 images.
Has been tested both directly on a host and inside a container.
=> Add squashfs support

lxc/list.go, lxc/list_test.go, lxd/container.go, po/de.po, po/fr.po, po/ja.po, po/lxd.pot, shared/container.go, shared/util.go
Extend column option for table format to accept a separated list of
attributes to display.  Attributes can be specified using pre-defined
shorthand chars (existing functionality) or via config keys (new).
Move syntactic checking functionality into shared/container.go so
that LXC can perform basic validation of config keys.
=> Add support for config key columns in 'lxc list'

lxd/migrate.go
Add a function that can be called inline with return to handle all
cleanup if an error occurs after migration has been started.  This
fixes a missing call to driver.Cleanup() and hopefully reduces the
probability of a similar bug occuring in the future.
This PR was prompted by discussion in #2141.  My intent is to get most of the automatic cleanup handling provided by defer without introducing any new fragility into the code.
=> Add function to consolidate Do's error handling

lxd/migrate.go
If we fail to create the tempdir, we don't need to delete it. We *do*
however, need to inform the main thread that the restore failed.
=> migration: fix tempdir handling

lxd/container_lxc.go
let's always include the path, so it's obvious which device is broken.
=> better errors when sanity checking devices

lxd/db_update.go
The user may not have actually started LXD or imported any containers, so
let's not fail in this case.
Launchpad #1602025
=> don't fail db upgrade if $LXD_DIR/containers doesn't exist

lxc/list.go
We can't concurrently write, but we can't concurrently read either, so let's
extend the lock duration.
Closes #2183
fatal error: concurrent map read and map write
goroutine 1 [running]:
runtime.throw(0x9cd180, 0x21)
/usr/lib/go-1.6/src/runtime/panic.go:530 +0x90 fp=0xc8200f0fa8 sp=0xc8200f0f90
runtime.mapaccess2_faststr(0x808280, 0xc8201db140, 0xc8201b43d0, 0xb, 0x0, 0xdbf920)
/usr/lib/go-1.6/src/runtime/hashmap_fast.go:307 +0x5b fp=0xc8200f1008 sp=0xc8200f0fa8
main.(*listCmd).listContainers(0xc82000be30, 0xc8200d0700, 0xc8201e0000, 0x32, 0x50, 0xc820011a50, 0x1, 0x1, 0xc82008ff00, 0x3, ...)
/build/lxd-ma7bPQ/lxd-2.0.2/obj-x86_64-linux-gnu/src/github.com/lxc/lxd/lxc/list.go:254 +0x651 fp=0xc8200f1750 sp=0xc8200f1008
main.(*listCmd).run(0xc82000be30, 0xc8200f2030, 0x0, 0x0, 0x0, 0x0, 0x0) …
=> list: fix concurrent read/write

README.md
Testing the 1st example "talking over the socket", I got this error: curl: (35) gnutls_handshake() failed: An unexpected TLS packet was received. Because the url is pointing to the TCP and not the socket.
Testing the 2nd example "talking over TCP", I got these warnings:
1-Warning: You can only select one HTTP request method! You asked for both POST
2-Warning: (-d, --data) and HEAD (-I, --head).
With these changes both examples run without errors.
=> Fixed errors on api examples with curl

lxd/container_lxc.go
1MB is not very big, let's make that bigger.
=> migrate: bump ghost limit

client.go, lxc/image.go, po/lxd.pot, test/suites/basic.sh, test/suites/remote.sh
Add help documentation for the target of `image export`.
If the target is a file, append the appropriate file extension to the
user-provided filename.  Properly parse the Content-Disposition header
to retrieve the image's filename instead of assuming `filename` is the
only parameter in the header.
Fix a bug where specifying a filename (as opposed to a directory) would
create the file with incorrect permissions (664 instead of 600).
Fixes #2205
=> Document image export target behavior and fix bugs

lxd/container_lxc.go
=> remove unused "name" argument from {create,remove}UnixDevice

shared/network.go
We don't use the Close method any more, so let's make these Writers, not
WriteClosers.
=> relax constraints on WebsocketRecvStream args

lxd/container_lxc.go, lxd/devices.go, lxd/networks.go, shared/devices.go, shared/devices_test.go
Unfortunately, there's not a way to range over a custom type, and there's
no way to sort a map, so we end up with this verbosity :(
Closes #2233
=> alphabetize device processing

lxd/main.go
This also adds some validation: namely that ip addresses are valid and that
any block device specified as a ZFS pool is indeed an actual block device.
Closes #1933
=> add some reasonable defaults to `lxd init`

client.go, lxd/patches.go, lxd/profiles.go
Profile names with slashes or called "." or ".." will get mangled/eaten
by the http server, so creating them works, using them works but they
can't be modified or deleted.
This prevents creating such profiles now and also removes any existing
one that already exists (they couldn't have been configured so it should
be safe).
Closes #2274
=> Prevent using invalid profile names

lxd/images.go, test/suites/basic.sh
The metadata tarball may use a different compression algorithim
than the rootfs tarball, e.g. rootfs may be a squashfs file system.
Using the file name from the metadata tarball as the base file name
for image exports can result in an incorrect file extension for the
rootfs, e.g. .tar.xz instead of .squashfs.
Technically I think this is only an issue for split images, but consistency in the default behavior seemed like a good thing.  I also find that using the fingerprint is helpful when exporting images that were pulled from someone else's repository, e.g. the ubuntu cloud-images repo; the original name doesn't usually provide meaningful insight and naming collisions are common, e.g. there are a lot of images named …
=> Always use fingerprint for image export filename

shared/util_test.go
We get intermittent failures like the one below. It looks like the problem is
that the test runners don't have enough randomness to fill up a 64 MB buffer,
so they just fail. Since the point of this test really is to test anything >
the default buffer size which is 128k, 1MB should suffice, and will hopefully
cut down on eating all the entropy from the test runners.
=== RUN   TestReaderToChannel
SIGQUIT: quit
PC=0x45fbe1 m=0
goroutine 0 [idle]:
runtime.futex(0x9f3a90, 0x0, 0x0, 0x0, 0x0, 0x9f3360, 0x0, 0x0, 0x7ffe2e658080, 0x40ff52, ...)
/lxd/build/tmp.qQKnZ6Eutl/go/golang/src/runtime/sys_linux_amd64.s:387 +0x21
runtime.futexsleep(0x9f3a90, 0x0, 0xffffffffffffffff)
/lxd/build/tmp.qQKnZ6Eutl/go/golang/src/runtime/os_linux.go:45 +0x62
runtime.notesleep(0x9f3a90) …
=> make TestReaderToChannel transfer smaller

lxc/exec.go
A better code for https://github.com/lxc/lxd/pull/2289 =)
=> Use os.LookupEnv from go 1.5 to find environment vars

lxd/devices.go
I noticed USB support wasn't working properly so I went digging into the issue and finally tracked it down to a transposition of the major and minor ids in createUSBDevice. 
Steps to reproduce.
```
$ ls -l /dev/bus/usb/001/013
crw-rw-rw- 1 root root 189, 12 Aug 19 21:47 /dev/bus/usb/001/013
$ lxc init ubuntu:16.04 test
$ lxc config device add test sdr usb vendorid=0bda productid=2838
Device sdr added to test
$ lxc start test
$ lxc exec test -- ls -l /dev/bus/usb/001/013
crw-rw---- 1 root root 12, 189 Aug 20 02:08 /dev/bus/usb/001/013
```
=> USB support - major/minor transposed

lxd/container_lxc.go, lxd/devices.go
As the comment notes, it's okay to fail because there may be other USB
devices still connected.
Also, I need to find a USB device SWAG because I didn't bring one to this
conference and so I don't really have a way to test this, but I think this
will do it right :)
Closes #2306
=> try to remove the usb bus dir after device disconnect

lxd/containers_post.go
newer versions of petname have a smaller name list, which increases the
liklehood of conflicts. let's retry a few times to avoid them.
=> retry generating petnames

lxd/container_lxc.go, lxd/devices.go
* do a deep copy of the device entry so config doesn't accidentally get
saved in the DB
* remember to remove the bus directory when a USB device goes away
* remove unused param to insertUnixDevice()
Closes #2306
Closes #2312
=> minor USB fixes

lxd/main.go
=> init: use more intelligent logic for partition sizing

shared/util_linux.go, shared/util_test.go
golang/x/sys/unix library is not yet packaged. So let's use the deprecated
syscall library for now.
=> xattrs: use syscall library

lxd/storage_dir.go
Instead of just copying the rootfs.
Closes #2371
=> dir: Copy everything on container copy

lxd/images.go
On low-memory systems (below 2GB of RAM), limit unsquashfs to a single
CPU and to 10% of the RAM for its fragment size.
Closes #2382
=> Tweak squashfs for low-memory systems

shared/idmapset_linux.go
So far doUidshiftIntoContainer() expanded all symlinks in the path it got
passed. This meant, that when the user created symlinks referring to
non-existing files or referring to paths on the host fuidshift would either fail
in the first case or change files on the host. With this commit, we start to
only resolve the path that gets passed to fuidshift up to the last path
component. This should be safe since shiftowner() in shared/util_linux.go will
a) perform another safety check and b) will only change ownership of the symlink
itself.
=> fuidshift: expand symlinks to last path component

lxd/apparmor.go, lxd/container_exec.go, lxd/containers_post.go, lxd/daemon.go, lxd/daemon_images.go, lxd/db_update.go, lxd/images.go, lxd/storage.go, lxd/storage_btrfs.go
Relates to #1928.
- Switch a bunch of log instructions to new log functions I've missed before.
- Demotes a bunch of server messages from `LogInfo*()` to `LogDebug*()`. Now, when doing
```
lxc launch images:ubuntu/xenial test
```
while having started `LXD` with
```
lxd --verbose --group lxd
```
Should take care of outputting (See commit `lxd/daemon_images: improve log for image downloads`):
- Downloading image {trigger: "/1.0/containers/abc", operation: UUID, image: ...}
- Image downloaded {operation: UUID, fingerprint: HASH, image:...}
=> 2016 09 17/logging issue 1928

lxd/container_lxc.go
Running `LXD` with `--verbose` will now show the following on *successful* container start:
```
INFO[09-18|02:12:26] Starting container                       last used=2016-09-16T12:25:29+0000 name=test1 action=start creation date=2016-09-14T19:38:10+0000 ephemeral=false
INFO[09-18|02:12:27] Started container                        name=test1 action=start creation date=2016-09-14T19:38:10+0000 ephemeral=false last used=2016-09-16T12:25:29+0000
```
and on *failed* container start:
```
INFO[09-18|02:14:52] Starting container                       name=test action=start creation date=2016-09-12T12:29:34+0000 ephemeral=false last used=2016-09-18T00:08:32+0000
EROR[09-18|02:14:57] Failed starting container …
```
=> lxd/container_lxc: improve log for container start

lxc/info.go, po/lxd.pot
Name: test
Remote: unix:/var/lib/lxd/unix.socket
Architecture: x86_64
Created: 2016/09/12 12:29 UTC
Status: Stopped
Type: persistent
Profiles: default
This is quite helpful in my eyes and has been requested in #1843. (Although this was probably also about showing the remote in the log.)
=> lxc/info: show remote in lxc info output

lxc/launch.go
output now looks like:
~/packages/go/src/github.com/lxc/lxd master lxc start kernel:foo2
error: Missing parent 'lxcbr0' for nic 'eth0'
Try `lxc info --show-log kernel:foo2` for more info
Closes #1843
=> include remote name in pretty printed error message

lxd/daemon.go, lxd/images.go
Relates to #1928.
Adapt log levels and add complimentary start/stop logging if missing.
=> 2016 09 20/logging issue 1928

lxd/container_lxc.go
Some of these are relevant and potentially useful in debugging.
=> also show warnings on c/r errors

doc/api-extensions.md, doc/configuration.md, lxd/container.go, lxd/container_lxc.go
This option for bridged nic devices turns on MAC filtering on the host,
preventing the container from sending traffic for a MAC other than the
one known by LXD.
=> Introduce security.mac_filtering

Makefile, lxd/networks_utils.go
We only want LXD's own test dependencies, not the ones for every single
package we use.
=> Makefile: Don't recursively include test deps

lxd/networks.go
On very busy systems (like our Jenkins), a network interface may
disappear between the time we list the interfaces and the time we
attempt to set the sysctl, so just ignore ENOENT.
=> network: Fix rare race condition with sysctl

lxd/networks.go
default and all must also be set to 1 if we want forwarding to work.
=> network: Fix IPv6 forwarding

lxd/main.go
For auto subnets and for disabled connectivity, we don't need to know if
NAT is needed, but for user provided settings, we do.
=> init: Ask about NAT if needed

client.go, doc/api-extensions.md, doc/rest-api.md, lxc/copy.go, lxd/api_1.0.go, lxd/containers_post.go, lxd/migrate.go, po/lxd.pot
This series of commits adds push support to container creation via migration.
In one sentence:
- The client serves as a proxy between source and target server.
As a short story:
- The client does a `POST` on the source server and requests a set of websockets and secrets. This is step is the same irrespective of `push` or `pull` mode. The affected code is located in `lxd/container_post.go`.
- Afterwards, the client do a `POST` on the target server. The target server will be informed that `push` mode is being used and that it should expect a websocket connection. The target server will then respond by sending back an `async` `operationClassWebsocket` operation. A set of websockets and secrets will be sent back to the client as part of the metadata. The set of websockets and secrets received …
=> push support

Makefile, shared/log.go, test/suites/static_analysis.sh
downstream users of shared/ (i.e. juju) don't want to have a log15
dependency.
log.Ctx() is defined as a map[string]interface{}, but the log15 package
does some fancy stuff to normalize it when it gets passed, which is why we
needed to wrap it in a log.Ctx() again. Instead, let's just not unwrap the
type in the first place, which means log15's machinery will see the log.Ctx
users passed us and behave correctly.
=> remove logging import

doc/configuration.md, lxd/container.go
The code was doing the right thing, skipping devices that didn't match
vendorid and allowing devices that don't have a productid set to still
be passed through.
But the documentation and configuration parser were doing things the
other way around, requiring a productid and considering vendorid
optional.
So fix the documentation and config parser to do the right thing.
=> usb: vendorid is mandatory, productid isn't

shared/cert.go
- check that IPv6 and IPv4 is no link-local address
- skip prefix length
- use IP for IP addresses
=> shared/cert: be more thorough when parsing ip addr

client.go, lxd/daemon.go
http/transport.go says:
// By default, Transport caches connections for future re-use.
// This may leave many open connections when accessing many hosts.
// This behavior can be managed using Transport's CloseIdleConnections
// method
// and the MaxIdleConnsPerHost and DisableKeepAlives fields.
In particular,
babbageclunk | Yeah - we end up leaking 10 goroutines everytime we destroy a model.
juju uses the client from a long running daemon, which creates a new
http.Transport for each call to the API, which creates a new
http.Transport, which leaks these goroutines.
Perhaps we can fix this more better with the client rewrite, but for now
let's just not do the keepalive, since that's how we're using
http.Transport anyway.
=> disable keepalives in http.Transports

lxd/container_lxc.go
=> lxd/container_lxc: record the err from go-lxc

lxd/daemon.go, lxd/daemon_images.go, shared/util.go
Right now, we store simplestreams data for up to an hour. This is done
through a simple memory cache in LXD.
The goal of this was to decrease load on the simplestreams servers and
that's been working pretty well so far.
One thing that this cache doesn't help much with is dealing with
simplestreams servers being offline or the client being temporarily
disconnected from the internet.
Right now once the cache times out, LXD will refresh it, if that fails,
then the cache is gone.
This commit makes it so that our cache persists across LXD restarts by
serializing it to disk. It also changes its use a bit, so that if we
fail to refresh the cache, we log a warning and bump its expiry for
another hour.
This effectively allows LXD to be used completely offline and work fine
with any image that's …
=> Store the simplestreams cache to disk

doc/api-extensions.md, lxc/exec.go, lxc/exec_unix.go, lxd/api_1.0.go, lxd/container.go, lxd/container_exec.go, lxd/container_lxc.go, lxd/containers.go, shared/container.go
This series of commits is part of: https://github.com/lxc/lxd/issues/1830.
- lxd/container_lxc: add prepareExec() helper fun
We will add another Exec*() style function that does the same setup operations
as Exec(). So let's create a common helper that does the setup for both.
- lxd/container_lxc, lxd/container: add ExecNoWait()
ExecNoWait() constructs a lxd forkexec command that calls a go-lxc binding which
in turn calls low-level liblxc's c->attach(). In contrast to Exec() ExecNoWait()
calls a go-lxc wraper that does not wait on the command to exit. Rather,
the go-lxc wrapper will simply return the PID it receives from low-level
liblxc's c->attach(). Hence, it returns the PID of the attached process. To
retrieve the attached PID from the go-lxc wrapper ExecNoWait() passes a pipe fd
to …
=> Forward signals to executing process

lxc/exec_unix.go
We should use a buffered channel since we might miss signals otherwise.
=> lxc/exec_unix: use buffered chan in sig forwarding

doc/api-extensions.md, doc/configuration.md, lxd/api_1.0.go, lxd/container.go, lxd/container_lxc.go, lxd/db_devices.go, lxd/devices.go
- lxc config device add c1 gpu0 gpu => Pass everything we have
- lxc config device add c1 gpu0 gpu vendor=10de => Pass whatever we have from nvidia
- lxc config device add c1 gpu0 gpu vendor=10de id=1 => Pass the second nvidia GPU
- lxc config device add c1 gpu0 gpu pci=0000:02:08.0 => Pass whatever GPU is at that PCI address
This parses /sys/bus/pci/devices/* and looks for the drm subfolder. All
subfolders under that, e.g.
card0
controlD64
renderD128
belong to the same PCI address and probably all need to be handed to the
container when the user somehow selects card0.
We then retrieve the vendor ID, and if available the device ID from
/sys/bus/pci/devices/*/vendor
/sys/bus/pci/devices/*/device
The major and minor number for each device can be gathered from the
card0/dev
controlD64/dev …
=> add gpu device type

lxd/containers_post.go, lxd/storage.go
In particular: the migration storage might have been in use after a
migration, so it's not safe to stop it like we were before (presumably it
was giving EBUSY, but since we didn't cehck the return code it was ok).
Instead, let's only start it before we need it, and stop it when we're
done. The OnStart hook will start the storage again if it is needed by the
actual container, so we don't need to take care of that.
Closes #2505
=> migration: start migration storage at the right time

README.md
we need 2.0.0 becuse of the migrate symbol
=> readme: bump liblxc version required

lxd/container_lxc.go
Similar to 38d794806a8ca781a0ed69798c8a6e9ea8ea7a70, we need to start the
storage at the right time for stateful start and stop. In particular, the
onstart hook will start the storage for us, but we need to be sure and
start it so that we can uidshift the images.
=> stateful start: start storage when necessary

lxd/container_lxc.go
We do the same in LXC itself. If we don't we might unnecessarily check comment
that have leading whitespace.
=> raw LXC: skip leading whitespace

lxc/file.go, lxc/file_unix.go, lxc/file_windows.go
This removes system dependent path manipulations (path/filepath) as target path uses forward slashes always. A better fix for #2565.
=> Clean up path handling for push

lxd/container_lxc.go
=> correctly set liblxc loglevel to debug when in --debug mode

lxd/container.go, lxd/container_exec.go, lxd/container_lxc.go, lxd/containers.go
ExecNoWait() was an unnecessary method addition to the containerLXC struct. It
also complicated the lxd forkexec command. I mainly added it because I
considered the methods defined on the containerLXC struct to be part of our API.
Now that I know better, let's simplify this code.
- Exec() gains an additional int pointer argument attachedPid.
1. passing in nil for attachedPid
- equivalent to calling cmd.Run()
2. passing in non-nil for attachedPid
- return PID of the lxd forkexec command and store the PID of the
executing process in attachedPid. It's the callers responsibility to
wait on the command. (Note. The PID returned in attachedPid can not be
waited upon since it's a child of the lxd forkexec command. It can
however be used to e.g. forward signals.)
- Move all the pipe magic into …
=> exec: remove ExecNoWait() and improve Exec()

shared/idmapset_linux.go
It doesn't make sense to add e's map range to i; this is a typo, and we
should be using i's map range instead.
=> idmapset: fix typo in Intersects

config/bash/lxd-client
Removed extra whitespaces +
lxd_names grep fix, symbol + needs to be backslashed.
We could have e.g. profile named 'test--test', so `lxc list --fast` result would be:
```
+-----------------------+---------+--------------+----------------------+--------------+------------+
|         NAME          |  STATE  | ARCHITECTURE |      CREATED AT      |   PROFILES   |    TYPE    |
+-----------------------+---------+--------------+----------------------+--------------+------------+
| aarseniev-test-media  | RUNNING | x86_64       | 2016/11/23 17:22 UTC | test--test   | PERSISTENT |
|                       |         |              |                      | base         |            |
+-----------------------+---------+--------------+----------------------+--------------+------------+
```
this result …
=> More clean filter for container names in bashcompl

lxd/container_lxc.go
- lxc.syslog: syslog() calls localtime() internally given that LXD is
multithreaded disallow it for now.
- lxc.ephemeral: Destroys containers on shutdown via the LXC API but this job
should __only__ be done by LXD. If not, then we end up with
containers in the database that have been destroyed already.
=> blacklist lxc.syslog and lxc.ephemeral

lxd/container.go, test/suites/migration.sh
Otherwise, we won't have this snapshot in the list of snapshots in the
slurp file, and we'll miss it.
=> save slurp file after a snapshot is created

scripts/lxc-to-lxd
- lxc.syslog
- lxc.ephemeral
- lxc.logfile
=> lxc-to-lxd: add more unsupported config keys

lxd/daemon.go
I'm not sure if this actually matters or not, but it's implementation
dependent and might matter.
=> disable insecure TLS in CA mode

scripts/lxc-to-lxd
We keep a whitelist for supported configuration keys. We then perform a check
whether the container sets any unsupported configuration keys. We report the
first unsupported configuration key we found back to the user and the error out.
=> lxc-to-lxd: switch to using whitelist

client.go, lxc/file.go, po/lxd.pot, test/suites/filemanip.sh
If filepath.Dir(someDir) returns "." we need to substract minus one to include
the first letter of the directory we want to create. This seems to only affect
recursive mode.
Also this adds two tests: One for when we are in the same working directory as
the directory we want to push (This will cover filepath.Dir(someDir) returning
".".). And one for when we give a directory via "../".
=> file push: fix off by one error

lxd/container_exec.go, lxd/rsync.go, shared/network.go, shared/network_linux.go, shared/util_linux.go
This adds the function ExecReaderToChannel() to our linux specific utility
functions. It is the workhorse that reads from the master side of a pty file
descriptor. Background tasks are identified correctly. That means you can run:
chb@conventiont|~/source/go/bin
> ./lxc exec xen1 -- bash
root@xen1:~# sleep infinity &
or
chb@conventiont|~/source/go/bin
> ./lxc exec xen1 -- bash
root@xen1:~# yes &
[1] 290
root@xen1:~# y
root@xen1:~# y
root@xen1:~# y
.
.
.
and still cleanly exit via "Ctrl+D" or "exit". The function is explained in
detail directly in the code.
=> exec: detect background tasks to allow clean exit

test/suites/filemanip.sh
=> tests: Fix shellcheck being confused by cd

client.go, lxc/config.go, lxc/copy.go, lxc/init.go, lxc/launch.go, lxd/container.go, lxd/container_lxc.go, lxd/container_put.go, lxd/container_test.go, lxd/containers_post.go, lxd/db_containers.go, lxd/db_devices.go, lxd/db_profiles.go, lxd/db_test.go, lxd/profiles.go, lxd/storage.go, lxd/types/devices.go, lxd/types/devices_test.go, shared/container.go
We don't need any of their functions in the client code so move them to
be daemon-only and instead use generic go types in the client.
=> Move Device/Devices types to lxd package

lxd/networks.go
Should fix #2765 
I tested this change for 12 days (build in [ppa:hda-me/lxd-dnsmasq-test](http://launchpad.net/~hda-me/+archive/ubuntu/lxd-dnsmasq-test)), and didn't spotted any backdrops.
There no any exploits in the wild, but it not he reason to avoid it or wait for it to happen. Also we can't warranty there no any exploits for dnsmasq in NSA briefcase. 
Summary to someone who not in theme: Currently all dnsmasq processes run with root privileges, and dnsmasq port accessible from containers and this slight change fix it. As for lxd user, lxd user have more privileges, then nobody, and it works without a problem with nobody.
=> Run dnsmasq with lower privilege

lxc/list.go
This closes an issue in a different repo: https://github.com/lxc/lxc/issues/1383
=> sort addresses in `lxc list` output

shared/util.go
When we are passed in a number with a suffix, assume it is already in bytes.
(Not sure if this is the most idiomatic way to do it.)
=> shared/util: ParseByteSizeString() deal with bytes

lxd/container_exec.go, lxd/container_lxc.go, lxd/main_forkexec.go
The standard shell convention is to report 128 + n where n := signal that killed
the process. This signal number is usually within a reasonable range so that the
magic 8-bit wall of sound is not breached. Essentially, we now report exit codes
like a standard shell would:
1.
chb@conventiont|~/source/go/bin
> ./lxc exec zest1 sleep 100
chb@conventiont|~/source/go/bin
> echo $?
143
caused by sending:
kill -15 $(pidof sleep 100)
2.
chb@conventiont|~/source/go/bin
> ./lxc exec zest1 sleep 100
chb@conventiont|~/source/go/bin
> echo $?
129
caused by sending:
kill -HUP $(pidof sleep 100)
3.
chb@conventiont|~/source/go/bin
> ./lxc exec zest1 sleep 100
chb@conventiont|~/source/go/bin
> echo $?
137
caused by sending:
kill -KILL $(pidof sleep 100)
This is way more fine-grained than what ssh does and …
=> exec: report exit code when we got killed by signal

lxd/db.go, lxd/db_images.go
According to: https://www.sqlite.org/pragma.html#pragma_foreign_keys (and
the comments in the code deleted by this patch); the foreign keys pragma
needs to be set per connection to a sqlite database. The problem here is
that the golang sql driver hides the fact that there might be more than one
connection, and they're pooled, so only the first connection would have
foreign keys enabled. This means that e.g. the constraints aren't enforced
on other connections that were automatically created by the sql driver.
This patch installs our own sql driver and uses that, which uses the
sqlite3 hook interface to always enable foreign keys on every connection
that's created, so we don't have this problem any more.
=> db: actually enable foreign keys per connection

lxd/main_nsexec.go
This _could_ explain the "sweep increased allocation count" problems.
=> main nsexec cgo allocation fixes

client.go, lxd/daemon.go
We don't use sensitive headers so don't need to be concerned about
crossing domain boundaries. So simply always copy all headers to
subsequent requests in the redirect chain.
Closes #2805
=> Forward user-agent and other headers on redirect

doc/configuration.md, doc/rest-api.md, lxd/patches.go, lxd/storage_lvm.go, lxd/storage_pools_config.go, lxd/storage_volumes_config.go, lxd/storage_zfs.go, test/suites/storage.sh
Closes #2914.
```
Reuse an already existing LVM volume group:
- lxc storage create <pool_name> lvm lvm.vg_name=LXDvg lvm.thinpool_name=LXDthin
Create a new LVM volume group or reuse an existing one:
- lxc storage create <pool_name> lvm source=/dev/sdb lvm.vg_name=LXDvg lvm.thinpool_name=LXDthin
- lxc storage create <pool_name> lvm source=/dev/sdb
```
@stgraber, do the semantics make sense to you?
=> lvm: reuse existing volume group

lxd/container_lxc.go, test/suites/storage.sh
We currently only allow attaching storage volumes of type custom. So remove any
code that gives a different impression. Also, handle things a little nicer.
=> storage: improve storage volume attachment

lxd/storage.go, lxd/storage_btrfs.go, lxd/storage_core.go, lxd/storage_dir.go, lxd/storage_lvm.go, lxd/storage_migration.go, lxd/storage_mock.go, lxd/storage_shared.go, lxd/storage_zfs.go
I intended to do this right at the beginning but then focused on the crucial parts.
- rip out all the unnecessary log-wrapping stuff: We can achieve the same with simply logging directly in the functions like we e.g. do in `lxd/container_lxc.go`.
- move separate interfaces into separate files
=> storage: simplify backend

lxd/patches.go
It really doesn't make a lot of sense to look at the size of the volume group.
Simply set the default.
=> patches: do not parse volume.size for lvm

lxd/storage.go
This is more visual cruft but ensures that a non-confusing error is returned.
For example, in a lvm test-run on another branch Jenkins returned:
INFO[02-27|00:03:30] Creating container                       ephemeral=false name=nonlive
INFO[02-27|00:03:31] Deleting container                       created=2017-02-27T00:03:30+0000 ephemeral=false name=nonlive used=1970-01-01T00:00:00+0000
INFO[02-27|00:03:31] Deleted container                        created=2017-02-27T00:03:30+0000 ephemeral=false name=nonlive used=1970-01-01T00:00:00+0000
EROR[02-27|00:03:31] Failed to initialize container storage   ephemeral=false name=nonlive
error: Invalid storage type.
As container creation is API internal it is actually not possible that a
non-valid storage driver was passed. So this error stems from …
=> storage: return correct error

lxd/db_storage_pools.go, lxd/patches.go, lxd/storage.go, lxd/storage_btrfs.go, lxd/storage_pools.go, lxd/storage_pools_utils.go, lxd/storage_volumes.go, lxd/storage_volumes_utils.go
So this may be somewhat debatable. One could make a reasonable argument that we simply leave the profile devices that have a pool property set alone and simply let users figure this out. However, I feel that this might be a problem. Consider the case where a user has a profile that has a disk device entry like:
```
sensitive-device:
path: /opt
source: sensitive-vol1
pool: pool1
```
and the user deletes the volume and the pool but we leave the properties set in the device. Now the user creates a new pool of the same name and a new volume of the same name that contains sensitive data and creates a container on the profile that still contains this device. This could potentially be a problem. So wipe the pool property on pool delete. For disk devices outside of LXD's storage management …
=> storage: bugfixes

lxd/storage_btrfs.go, lxd/storage_cgo.go
For loop-backed btrfs pools we actually mount the loop device and so it's fine
to use LO_FLAGS_AUTOCLEAR since the loop device is guaranteed to be kept around
for as long as the mount exists. When we implement lvm loop-backed pools
however, we do not mount the loop device so we need to make sure that it is not
deconfigured automatically when we close all handles to it.
=> storage_cgo: make flag argument configurable

lxd/storage_cgo.go, lxd/storage_lvm.go, test/suites/basic.sh, test/suites/snapshots.sh
LVM has some very specific naming requirements for logical volumes. We have a
specific function that turns a container name into a valid logical volume name.
The only thing left to do is to actual use that valid logical volume name...
=> lvm: use lvmized container name

shared/util_linux.go
From the golang help for filepath.Walk:
"If there was a problem walking to the file or directory named by path, the
incoming error will describe the problem and the function can decide how to
handle that error (and Walk will not descend into that directory)."
It seems that we should really be checking for an error that is passed in
through type WalkFunc:
```
+ /lxd/build/tmp.TDmNlEAzM1/go/bin/lxc storage create lxdtest-TtKYYWxz2-pool4 btrfs source=/dev/loop30 --verbose
INFO[03-02|06:36:21] Creating BTRFS storage pool "lxdtest-TtKYYWxz2-pool4".
2017/03/02 06:36:22 http: panic serving @: runtime error: invalid memory address or nil pointer dereference
goroutine 326 [running]:
net/http.(*conn).serve.func1(0xc8202c2380)
/lxd/build/tmp.TDmNlEAzM1/go/golang/src/net/http/server.go:1389 +0xc1 …
```
=> util: check for err in {UUID, BlockDev} lookup

lxd/containers_post.go, lxd/daemon.go, lxd/images.go, lxd/patches.go, lxd/storage.go, lxd/storage_btrfs.go, lxd/storage_cgo.go, lxd/storage_dir.go, lxd/storage_lvm.go, lxd/storage_pools.go, lxd/storage_pools_utils.go, lxd/storage_zfs.go
The operations performed in StoragePoolCheck() are only operations that are
necessary to guarantee correct functionality of the storage pool. So call them
in storagePoolInit(). To support this, storagePoolInit() gains the boolean
argument "poolExistsOnDisk" which is used to indicate whether the pool has
already been created on disk.
The only exception is in the case of calling StoragePoolCreate(). In this case
StoragePoolCheck() needs to be called explicitly, to make sure that things are
alright after creation.
=> storage: call StoragePoolCheck() if pool exists

lxd/patches.go, lxd/storage_btrfs.go, lxd/storage_dir.go, lxd/storage_lvm.go, test/suites/storage.sh
This improves handling:
```
1. lxc storage create pool1 source=/path/to/subvolume
- create /path/to/subvolume if it doesn't already exist and bind-mount onto
${LXD_DIR}/storage-pools/pool1
2. lxc storage create pool1 source=${LXD_DIR}/storage-pools/pool1
- create subvolume if LXD is located on btrfs
3. lxc storage create pool1 source=/path-somewhere-under-${LXD_DIR}-but-not-under-storage-pools-subdir
- This is considered invalid (As it might mess with LXD's on-disk layout).
The following error message is given:
chb@conventiont|~/source/go/src/github.com/lxc/lxd|2017-03-05/btrfs_improvements *$%>
> lxc storage create pool1 btrfs source=/home/chb/mnt/l1/storage-pools/
error: BTRFS subvolumes requests in LXD directory "/home/chb/mnt/l1" are only valid under "/home/chb/mnt/l1/storage-pools" …
```
=> btrfs: improvements

lxd/container_snapshot.go
The MAX() statement consistently returns snap9 when it should actualy return
snap10 or greater.
=> snapshots: find max value currently used

lxd/patches.go
When the daemon gets killed mid-upgrade and the storage_api patch doesn't
successfully complete but a storage pool entry was already created in the db it
is vital that we do not alter the current config. We should only alter it when
it is not set in the first place.
=> patches: ensure existing pool config is kept

scripts/lxc-to-lxd
The description of the `--move-rootfs` argument swaps the effect of the
flag — it actually moves the container, rather than copying it.
Signed-off-by: Luke W Faraone <luke@faraone.cc>
=> lxc-to-lxd: Typo in description of --move-rootfs

doc/production-setup.md
By default the Linux kernel grants access to the kernel ring buffer
(dmesg) to all users. Consequently containers do have access to this
data. The kernel ring buffer might contain sensitive information.
Fixes #1397
=> Add note about restricting access to kernel ring buffer

doc/backup.md, lxd/api_internal.go, lxd/container.go, lxd/container_lxc.go, lxd/container_snapshot.go, lxd/container_test.go, lxd/main.go, lxd/main_import.go, lxd/migrate.go, lxd/storage.go, lxd/storage_btrfs.go, lxd/storage_dir.go, lxd/storage_lvm.go, lxd/storage_migration.go, lxd/storage_mock.go, lxd/storage_pools.go, lxd/storage_pools_utils.go, lxd/storage_volumes.go, lxd/storage_volumes_utils.go, lxd/storage_zfs.go, test/main.sh, test/suites/backup.sh, test/suites/migration.sh
This way we can have Storage{Start,Stop}() indicate whether the operation that
is taking place has been initialized by us and if so we can make an informed
decision about stopping it or not. This should e.g. avoid unnecessary
{u,m}ounts and also should improve writing out the Backup.yaml file.
=> improve backup handling

doc/production-setup.md
Table is broken in `doc/production-setup.md`.
Escaped charactor `*`.
=> doc: fix broken table

lxd/container_lxc.go, lxd/container_put.go, lxd/storage_zfs.go
With the new storage api work done {m,um}ounting containers is done on demand
so we need to ensure that storage is available at the right time. In the
restore case, when the container is running it is stopped which will also
unmounted the storage volume for e.g. the zfs backend. So let's make sure that
it is mounted again right after.
=> migration: fix stateful restore

test/main.sh, test/suites/backup.sh, test/suites/basic.sh
- Add respawn_lxd() and shutdown_lxd() to allow stopping and restarting an
already running LXD daemon in the test-suite.
- Stop the daemon before calling sqlite3 to avoid db locked errors in the
test-suite.
=> test: improve import tests

Makefile, shared/log_debug.go
This allows to build LXD with debug logging enabled which prints the file name,
line number, and function name in all log output. This is mostly meant for
development purposes.
Normal LXD output:
```
INFO[03-24|01:49:08] LXD 2.12 is startingin normal mode      path=/home/chb/mnt/l2
WARN[03-24|01:49:08] CGroup memory swap accounting is disabled, swap limits will beignored.
INFO[03-24|01:49:08] Kernel uid/gid map:
INFO[03-24|01:49:08]  - u 0 0 4294967295
INFO[03-24|01:49:08]  - g 0 0 4294967295
INFO[03-24|01:49:08] Configured LXD uid/gid map:
INFO[03-24|01:49:08]  - u 0 100000 65536
INFO[03-24|01:49:08]  - g 0 100000 65536
DBUG[03-24|01:49:08] Initializing and checking storage pool "pool1".
DBUG[03-24|01:49:08] Initializing a …
```
=> build: add debug logging

lxd/container_lxc.go
This got fixed in the insert function a little while back, but the
matching code in the remove function was missed.
Closes #3107
=> Fix unix device removal (bad cgroup.deny entry)

lxd/container_lxc.go
When hard memory limit is set, OOM is called even if buffers/cache can be released to free memory. To avoid this, soft limit can be enabled in addition to hard. I propose to set soft limit at 90% of hard limit value. It's mentioned in cgroup documentation:
https://www.kernel.org/doc/Documentation/cgroup-v1/memory.txt
> NOTE2: It is recommended to set the soft limit always below the hard limit, otherwise the hard limit will take precedence. 
Signed-off-by: Lukasz Matczak <lukasz.matczak@cba.pl>
=> Added soft memory limit even when hard is selected

lxd/storage_dir.go
When the container directory was created by other application(such as nova-lxd), the
container directory maybe has the wrong perrmissions, so chmod 755 to ensure the directory has the right permission
Signed-off-by: codejuan <xh@decbug.com>
=> storage: ensure the container directory has the right permission

lxd/container.go
Spelling fix in container config validation.
Signed-off-by: Thomas Johnson <NTmatter@gmail.com>
=> lxd/container.go: Typo in securtiy.syscalls.blacklist

lxd/container_lxc.go
Device minor numbers are 12-bit, and the kernel expects combined major-minor device IDs to be passed as a 32-bit integer with the following components, from MSB to LSB:
* 12 zero bits
* the 4 upper bits of the minor number
* all 8 bits of the major number
* the 8 lower bits of the minor number
Currently LXD writes `(major | minor >> 8)` in the bits where the kernel expects to find the major number.
=> Fix handling of devices with minor>255

lxd/container_lxc.go
Without this we'd run the risk of changing idmap values and then doing
an action like a publish with an incorect map.
=> Properly invalidate the idmap cache

doc/backup.md, doc/configuration.md
Remove the deprecated storage keys from server configuration documentation.
This also sort keys in the table to match ordering in the code.
An added mention in the backup documentation about supported filesystems
=> Remove deprecated storage keys from documentation

lxd/apparmor.go, lxd/container_lxc.go, lxd/daemon.go
This does the following
- Re-work detection code to always fill all the various AppArmor variables
- Add detection of LXD being run in an AppArmor stacked configuration
- If running stacked (nesting), then load a per-container profile but
don't attempt to setup a second level of stacking as this isn't
supported by AppArmor.
- Treat a security.privileged=true container inside an unprivileged
container the same as running an unprivileged container.
Closes #3172
=> Fix AppArmor stack handling with nesting

test/suites/serverconfig.sh
The serverconfig.sh relies on client.crt being generated, running
`lxc remote add` (via ensure_has_localhost_remote) does the trick.
With this branch "sudo -E ./main.sh server_config" will no longer
fail.
=> Make sure a client certificate is generated

test/main.sh, test/suites/storage.sh
Instead of unconditionally run storage tests depending on the
availability of the underlying backend tools, run them depending on
the value of LXD_BACKEND.
There's a small hack detecting whether we are running as
lxd-github-pull-test Jenkins job, and in that case LXD_BACKEND gets
automatically set to $backend. I think it'd be best to change the
Jenkins configuration instead, and I'm not sure what other jobs would
need a change too (beside lxd-github-pull-test).
Closes #3201.
=> Honor the LXD_BACKEND environment variable in storage tests

lxc/init.go
This branch drops an unnecessary else statement, as highlighted by a
linting hint in my emacs setup. Essentially since the "if" part ends
up with a return, there's no need for "else".
Signed-off-by: Free Ekanayaka <free.ekanayaka@gmail.com>
=> Drop unnecessary else statement

lxd/container_lxc.go, lxd/patches.go, lxd/storage.go, lxd/storage_btrfs.go, lxd/storage_dir.go, lxd/storage_lvm.go, lxd/storage_mock.go, lxd/storage_zfs.go
Until we have an upstream fix for https://github.com/zfsonlinux/zfs/issues/5796
we need to work around zfs's EBUSY bug. So use syscall.Mount() directly and
simply move on when EBUSY is returned.
Closes #3228.
=> zfs: try to work around zfs EBUSY bug

shared/util.go
Trivial change to add "mode:yaml" markers to configuration templates used by edit actions, so that emacs will use the correct mode.
=> Add yaml-mode marker in template for "lxc edit" actions.

shared/cmd/context.go, shared/cmd/context_test.go, shared/cmd/doc.go, test/suites/static_analysis.sh
This is a proof of concept of some unit-testable code that I'd like
to later use for making cmdInit testable (as per #2834).
It's small so should it be easy to review and because I wish to have
some feedback on the approach before moving forward. I hope that the
branch gives a feel of what further branches would look like.
As a general note, I feel it'd be important to improve coverage of the
parts that can be unit tested easily (so basically most higher-level
application logic except for system-level interactions). An advantage
of this type of approach is of course the possibility to work and test small
fragments of logic in isolation while developing them. I think this
can be done incrementally without too much disruption, if we agree.
Signed-off-by: Free Ekanayaka <free@ekanayaka.io>
=> Add a new shared/cmd package with initial command I/O logic

test/README.md, test/backends/btrfs.sh, test/backends/lvm.sh, test/backends/zfs.sh, test/main.sh, test/suites/backup.sh, test/suites/basic.sh, test/suites/database_update.sh, test/suites/filemanip.sh, test/suites/image.sh, test/suites/init.sh, test/suites/migration.sh, test/suites/remote.sh, test/suites/security.sh, test/suites/snapshots.sh, test/suites/storage.sh
This selects a random backend for the second LXD instance used in tests, so that migration tests can be run cross-backend.
The LXD2_BACKEND can be specified to select a specific backend. The randomly-chosen backend is always different from LXD_BACKEND.
=> Select random storage backend for the second LXD instance in tests.

shared/cmd/context.go, shared/cmd/context_test.go, shared/cmd/testing.go
This branch is a mechanical follow-up of the first one introducing
cmd.Context. It adds the rest of AskXXX methods as defined in cmdInit,
and should be a step towards making cmdInit itself testable.
The logic is exactly the same as the inline functions currently
defined in main_init.go, although some boilerplate could be avoided by
factoring common logic together.
To get a sense of how this will be used in cmdInit, you can have a look at:
https://github.com/freeekanayaka/lxd/commit/f3b0847422a5f85f2d8bacc46ee433aee4b69858
which would be the followup change.
Signed-off-by: Free Ekanayaka <free@ekanayaka.io>
=> Complete cmd.Context support for various AskXXX methods

lxd/main_init.go, lxd/main_init_test.go, lxd/main_test.go
This branch consists of a couple of separate commits:
1) make cmdInit testable by extracting its global variables and "boundaries", so most of its logic can be run in isolation in a unit test. A sample unit test has been added as exemplification, I plan to add more as I add the logic for the new "pre-seed" feature as per #2834.
2) extract a few inline functions into methods, for easier reading of the core logic.
The commit messages of the individual commits provide a bit of extra narrative.
I'm bundling these two changes together for convenience, but I'm happy to split them in separate branches if more appropriate.
=> Testable cmd init

lxd/db_storage_pools.go, lxd/main_import.go
Fixes this long-standing bug:
```
chb@conventiont|~
> ~/source/go/bin/lxd import
panic: runtime error: index out of range
goroutine 1 [running]:
main.cmdImport(0xc42008e090, 0x1, 0x1, 0x6, 0xffffffffffffffff)
/home/chb/source/go/src/github.com/lxc/lxd/lxd/main_import.go:8 +0x320
main.run(0xc420120750, 0x0)
/home/chb/source/go/src/github.com/lxc/lxd/lxd/main.go:217 +0x844
main.main()
/home/chb/source/go/src/github.com/lxc/lxd/lxd/main.go:53 +0x26
```
=> lxd import: bugfixes

client.go, lxc/file.go, shared/util.go
The file chmod that go uses calls out to syscall.Fchmod() which is not
implemented for Windows. The os.Chmod() method call out to syscall.Chmod()
which seems to be implemented on all platforms if I read the go sources
correctly.
Closes #3275.
=> tree-wide: replace file Chmod() with os.Chmod()

doc/containers.md
At line #140 device type _nic_ is written as _ic_.
=> Correct device type name

lxd/db_images.go, lxd/db_test.go, lxd/images.go
Return a more meaningful error when trying to import an already existing image.
Closes #3244
=> Return an error if an image already exists on import

client.go
filepath.Walk() sends filenames with backslashes there
=> Fix recursive file push on Windows

lxd/storage_volumes.go
We do currently not support deleting any other type of storage volume.
=> storage volumes: only delete custom volumes

lxd/container_test.go, lxd/daemon_test.go, lxd/main_test.go
Since the standard "go test" tool is not aware of testify and since
unit tests using testify are all direct methods of lxdTestSuite, it's
not possible to easily run a particular set of tests in isolation (say
all tests in container_test.go).
This commit changes the test files to declare their own test suite,
based on lxdTestSuite, so now running:
```
go test -v -run TestContainerTestSuite ./lxd
```
or
```
go test -v -run TestDaemonTestSuite ./lxd
```
will only execute the the tests in those suites, as opposed to the
entire suite.
=> Support running individual testify test suites

lxd/db_update.go
A few db patches are currently checking if the daemon is being run in
mock mode (i.e. unit tests), and no-op the patch in that.
It turns out that this is not really necessary, becasue the underlying
logic will work fine in mock mode too (and also, more generally it
might open the doors to creating tests that specicically exercise
certain patches).
This change removes all current occurrences of the special casing, the
main goal would be to reduce coupling between daemon
code (higher-level) and db code (lower-level), so eventually we can
have dependencies only in one direction (deamon depends on db but not
viceversa).
=> Don't special-case mock mode unnecessarily in db patches

lxd/main_test.go
Currently unit tests based on lxdSuiteTest all share the same
database, meaning that state left by certain tests can influence other
tests (for instance it's not possible to create a pool with the same
name in two different tests).
This change resets the db state after each individual test run,
increasing isolation between tests.
Note that we need to reset the daemon config in-memory map because
it's a cache of the db state. I think there other cases of such caches, but
it should be fine to deal with them as we go. For now current tests are
happy with this change.
=> Clear database state in the mock daemon after each lxdSuiteTest

lxd/storage_btrfs.go
If we receive btrfs subvolumes from an older LXD instance they are not called
".migration-send" but rather ".root". Handle this case.
Closes #3323.
=> storage: handle btrfs migration on different lxds

lxd/daemon.go, lxd/db.go, lxd/db_test.go, lxd/db_update.go, lxd/patches.go
Separate db-level update logic from daemon-level one
Our DB patches are currently performing a mix of pure SQL changes and
some legacy higher-level upgrade logic (such as dealing with container
paths and LVM volumes).
Such non-db logic was written before the lxd/patches.go mechanism was
put in place, and prevents removing the coupling between the daemon
layer and the db layer, making it harder to test SQL upgrade logic
in isolation, and perhaps to eventually turn the db code into its own
self-contained package that doesn't depend on deamon code.
This change extracts all daemon-specific upgrade logic from
db_updates.go to patches.go, and adds a 'postApply' hook parameter to
dbUpdatesApplyAll in order to preserve their exact current
semantics (i.e. these patches are applied during the …
=> Separate db-level update logic from daemon-level one

shared/cmd/context_test.go, shared/cmd/testing.go
Move out the assertions to the test package instead.
=> Don't depend on testify in the cmd package

Makefile
It was braking because of a name/path change.
=> Fix static-analysis target

lxd/api_1.0.go, lxd/api_internal.go, lxd/certificates.go, lxd/container_get.go, lxd/containers_get.go, lxd/containers_post.go, lxd/images.go, lxd/operations.go, lxd/profiles.go, lxd/profiles_utils.go, lxd/storage_pools.go, lxd/storage_volumes.go
Replace many uses of InternalError with SmartError, which can detect some specific errors and give a nicer error message for the user.
These are mostly db-related errors.
Closes #1927
=> Replace some uses of InternalError with SmartError.

lxd/container_lxc.go
This deprecates defining multiple networks in the following format:
lxc.network.type = veth
lxc.network.flags = up
lxc.network.link = lxdbr0
lxc.network.hwaddr = 00:16:3e:09:7a:39
lxc.network.name = eth0
lxc.network.type = veth
lxc.network.flags = up
lxc.network.link = lxdbr1
lxc.network.hwaddr = 00:16:3e:b2:8f:56
lxc.network.name = eth1
in favor of:
lxc.network.0.type = veth
lxc.network.0.flags = up
lxc.network.0.link = lxdbr0
lxc.network.0.hwaddr = 00:16:3e:09:7a:39
lxc.network.0.name = eth0
lxc.network.1.type = veth
lxc.network.1.flags = up
lxc.network.1.link = lxdbr1
lxc.network.1.hwaddr = 00:16:3e:b2:8f:56
lxc.network.1.name = eth1
The former syntax is utterly misleading and difficult to handle in liblxc while
the latter will let liblxc nicely handle network configuration even if you …
=> network: use lxc.network.<n>.*

lxd/storage_btrfs.go, test/suites/migration.sh
Enabling quota is an expensive operation that seems to have consequences for
every other operation after it has been enabled. So let's only do it on demand.
=> btrfs: only enable quota when necessary

lxd/storage_dir.go
This ensures that we unfreeze the container even if rsync fails
for some reason.
=> dir: Unfreeze on rsync error

lxd/container_lxc.go
Right now, liblxc is not yet able to handle configuring network devices
starting from arbitrary indices. For example, you couldn't start a network
configuration with:
lxc.network.1.type=veth
lxc.network.1.name=eth0
Also, arbitrary ordering the keys, e.g.
lxc.network.0.name=eth0
lxc.network.0.type=veth
does as of now also not work correctly. That is why we need to ensure in LXD
that the configuration keys are always set in correct order.
Now, about this commit. LXD did something dumb before. It bumped the index of
the network keys independent of whether the next configuration item was
actually a network key. This meant we would confuse liblxc by inserting keys
with different indices that actually should all have the same index since they
were meant to define a single network. Let's not do …
=> network: fix network indices

lxd/storage_zfs.go, lxd/storage_zfs_utils.go
Instead of creating the dataset and then setting its mountpoint let's create
the dataset with the mountpoint right away.
Closes #3399.
=> zfs: improve dummy dataset creation

lxc/config.go, lxc/image.go, lxc/utils.go, lxc/utils_test.go
Output is now sorted in column order.
I also renamed SortImage since it can now be used to sort any list of list of strings.
Closes #3413
=> Fix crash when sorting images with custom columns

lxd/container_exec.go, shared/util_linux.go
In case the child simply dies or the client exits the fd will be closed and we
will receive a POLLNVAL event. We need to handle this case otherwise we will
keep poll()ing without ever exiting.
Closes #2964.
=> exec: detect POLLNVAL when poll()ing

lxd/container_lxc.go
When we have a new enough version we should use the new network configuration
keys.
=> container_lxc: use new network keys

lxd/container_lxc.go, lxd/container_lxc_utils.go, lxd/storage.go, lxd/storage_volumes_config.go, test/main.sh, test/suites/storage_volume_attach.sh
Since it's implementation the LXD storage API has supported attaching storage
volumes to containers. One of the oustanding challenges before a working
implementation of the shiftfs concept in the kernel is how to deal with id
mappings when mounting custom storage volumes. This spec tries to propose a
viable solution that aims at security.
When a new custom storage volume is created:
lxc storage volume create <pool> <volume>
and attached to a container for the first time:
lxc storage volume attach <pool> <volume> <container> <path-to-attach-to>
it will not have any prior id mapping associated with it.
1. Attaching a previously not id-mapped storage volume
The first container to attach the storage volume will perform an id mapping on
the storage volume. The serialized id mapping recorded in …
=> storage: allow attaching storage volumes

lxd/storage_lvm.go
=> lvm: allow non-empty VGs when thinpool exists

lxd/container_lxc.go
We should check whether the disk device exists under the containers disk device
entries and only then try to forkumount.
=> container_lxc: check whether disk device exists

lxd/storage_zfs.go
removed s.zfsPoolVolumeCreate()
changed all s.zfsPoolVolumeCreate() to use zfsPoolVolumeCreate()
added proper logging error messages
Signed-off-by: David Negreira <David@otherreality.net>
=> Replace all calls to s.zfsPoolVolumeCreate() with zfsPoolVolumeCreate()

doc/api-extensions.md, doc/debugging.md, doc/security.md
Fixes #3448 
This renames the documentation file as suggested and extends it with answers from comments.
=> Extend/rework security-related documentation

lxc/file.go, lxd/container_lxc.go, lxd/main.go, test/suites/filemanip.sh
=> Don't specify mode for intermediate directories created with `push -p`

lxd/devices.go
Added remount of binded mounts with readonly mode if flag "readonly" is "true".
Signed-off-by: Denis Pynkin <denis.pynkin@collabora.com>
=> Fix readonly mode for directory mount

doc/backup.md
Expand `backup.md` with more info on how to use `lxd import`
=> Expand lxd import documentation

lxd/patches.go, lxd/storage_zfs.go, lxd/storage_zfs_utils.go, test/suites/migration.sh, test/suites/snapshots.sh, test/suites/storage.sh
We don't want the container host to randomly mount stuff behind our back.
Closes #3437
=> zfs: Set canmount=noauto on all mountable datasets

lxd/images.go
Use the complete fingerprint in exported filenames, even when the short one is passed to `lxc image export`
=> lxc/image: always use long fingerprint in exported filenames

doc/api-extensions.md, lxd/api_1.0.go, lxd/storage_btrfs.go, lxd/storage_dir.go, lxd/storage_lvm.go, lxd/storage_volumes.go, lxd/storage_zfs.go
This commit introduces the ability to wipe storage volumes for images from a
specific storage pool.
Closes #3539.
=> storage: allow deleting images via storage API

lxc/image.go, lxc/publish.go, lxc/utils.go, lxc/utils_test.go, po/de.po, po/el.po, po/fr.po, po/it.po, po/ja.po, po/lxd.pot, po/nl.po, po/ru.po, po/sr.po, po/sv.po, po/tr.po, test/suites/basic.sh, test/suites/image.sh
This makes the CLI explicitly remove existing aliases that conflict with the ones of the image being copied/imported, and recreate them.
Closes #3560
=> Update image aliases when they already exist

lxc/main.go, lxc/remote.go, po/de.po, po/el.po, po/fr.po, po/it.po, po/ja.po, po/lxd.pot, po/nl.po, po/ru.po, po/sr.po, po/sv.po, po/tr.po, po/zh.po, po/zh_Hans.po
This fixes the config dir handling of LXD on Windows.
Before this, it'd fail if the config dir didn't exist AND defaulted to c:\.config\lxc as the default path, which is obviously wrong and unsuitable for unprivileged Windows users.
This solves it by moving things under the user's home directory and also creates the paths as needed.
This will require a manual fix for existing users. Moving c:\.config to c:\Users\USERNAME\.config but it's unlikely that we had very many functional users given that bug so it shouldn't end up being too painful a fix.
@techtonik FYI, as this is likely to affect you.
=> Fix config dir on Windows

client/interfaces.go, client/lxd_containers.go, doc/rest-api.md, lxc/config.go, po/de.po, po/el.po, po/fr.po, po/it.po, po/ja.po, po/lxd.pot, po/nl.po, po/ru.po, po/sr.po, po/sv.po, po/tr.po, po/zh.po, po/zh_Hans.po, test/suites/config.sh
Add a new `lxc config template <op>` section to the CLI to perform operations related to template files.
=> client: Add container template files operations

lxd/patches.go
When either one of those datasets does not exist (e.g. the user has deleted it
or has upgrade from a LXD instance that didn't automatically create these
datasets already) then the upgrade will fail.
Closes #3594.
=> patches: fix canmount=noauto patch

doc/api-extensions.md, doc/rest-api.md, lxc/init.go, lxc/launch.go, lxd/api_1.0.go, lxd/container_instance_types.go, lxd/containers_post.go, lxd/daemon.go, po/de.po, po/el.po, po/fr.po, po/it.po, po/ja.po, po/lxd.pot, po/nl.po, po/ru.po, po/sr.po, po/sv.po, po/tr.po, po/zh.po, po/zh_Hans.po, shared/api/container.go, test/suites/basic.sh
This makes it possible to use standard instance types as used by major
cloud providers to define LXD resource limits.
lxc launch ubuntu:16.04 c1 -t t2.micro
lxc launch ubuntu:16.04 c2 -t n1-highcpu-16
lxc launch ubuntu:16.04 c3 -t Standard_A8_v2
LXD will attempt to find a unique match for the instance type.
If it's ambiguous, the cloud provider can be specified with:
lxc launch ubuntu:16.04 c4 -t azure:A11
This can also be used with an internal format string to specify simple limits:
lxc launch ubuntu:16.04 c5 -t c2.5-m2
stgraber@castiana:~$ lxc config show c5 | grep limits
limits.cpu: "3"
limits.cpu.allowance: 83%
limits.memory: 2048MB
All provided memory amounts are in GB, LXD will convert internally to MB
to allow for fractions. For fractions of CPU, LXD will apply both hard
CPU limits …
=> Implement instance types as proxy for limits

lxd/daemon.go
Since cloud instance type definitions change pretty regularly (new ones
added), lets try to refresh our cache once a day.
=> Add missing refresh code for instance types

doc/api-extensions.md, doc/rest-api.md
Escaping some unescaped path params in API docs that caused the paths to be rendered incorrectly (the params were missing).
=> Escaping path params in docs

scripts/lxc-to-lxd
Ignore sysfs and proc mounts, which are mounted
in LXD containers by default. If they're not ignored,
the os.path.exists test will fail.
Ignore lxc.cap.drop values that are dropped by
default in LXD containers, rather than bailing.
Also, add a missing comma at the end of the line
for lxc.cap.drop in the list of handled attributes.
Signed-off-by: Andrew Wilkins <axwalk@gmail.com>
=> lxc-to-lxd: permit defaults in lxc.mount.entry and lxc.cap.drop

lxd/storage_zfs.go, lxd/storage_zfs_utils.go
Convert all `zfsXxx` functions in `lxd/storage_zfs_utils.go` to standalone function, so that `storageZfs` methods are all in `lxd/storage_zfs.go`, passing pool/dataset names as parameters.
Closes #3472
=> Rework ZFS utility functions

lxc/config/file.go
This transitions "images:" from "lxd" to "simplestreams"
=> lxc: Re-introduce remote protocol migration

lxd/container_lxc.go, lxd/devices.go
The previous code assumes that the nvidia card index and the dri card index are
identical, i.e. for a given pair {/dev/card\<card-idx\>, /dev/nvidia\<nvidia-idx\>}
it was assumed that \<card-idx\> == \<nvidia-idx\> but it is definitely possible
that \<card-idx\> != \<nvidia-idx\>.
Also, let's report an error when we don't find the gpu device that the user
requested.
Closes #3642.
=> gpu: fix gpu attach

lxd/.dir-locals.el, lxd/daemon.go, lxd/db.go, lxd/db_test.go
This branch drops any mention of the Daemon structure in db.go, and is
a step towards making the db functionality self-contained (in order to
put it in a separate db/ package).
=> Drop dependencies on Daemon in db.go

lxd/types/devices.go, lxd/types/devices_test.go
Make sure we always get the exact same order.
Closes #2895
=> Fix sorting order of devices

lxd/api_internal.go, lxd/container.go, lxd/container_put.go, lxd/containers.go, lxd/containers_get.go, lxd/containers_post.go, lxd/daemon.go, lxd/devices.go, lxd/images.go, lxd/main_daemon.go, lxd/networks.go, lxd/patches.go, lxd/profiles.go, lxd/profiles_utils.go, lxd/storage.go, lxd/storage_pools.go, lxd/storage_pools_utils.go, lxd/storage_volumes.go, lxd/storage_volumes_utils.go
All higher-level entry points to entity-related functionality now
takes a State parameter as opposed to Daemon. With this commit, only
the REST-API layer is still depending direcly on Daemon, and that will
be squashed too in coming branches, effectively paving the ground for
new unit-testing possibilities.
=> Finish replacing Daemon with State also in higher-level entity APIs

lxd/db/query/slices_test.go, lxd/main.go, lxd/main_activateifneeded.go, lxd/main_args.go, lxd/main_args_test.go, lxd/main_callhook.go, lxd/main_daemon.go, lxd/main_forkexec.go, lxd/main_forkgetnet.go, lxd/main_forkmigrate.go, lxd/main_forkstart.go, lxd/main_import.go, lxd/main_init.go, lxd/main_init_test.go, lxd/main_migratedumpsuccess.go, lxd/main_netcat.go, lxd/main_ready.go, lxd/main_shutdown.go, lxd/main_subcommand.go, lxd/main_subcommand_test.go, lxd/main_waitready.go, shared/cmd/context.go, shared/cmd/parser.go, shared/cmd/parser_test.go, shared/subtest/doc.go, shared/subtest/go1_6.go, shared/subtest/go1_7.go
This streamlines the invocation of of the various lxd sub-commands. The goals are:
- reduces/eliminate the use of global variables to make the code more unit-test friendly (no risk of mutating shared state across tests)
- make our subcommand-handling code more normalized and declarative
- make main.go easier to read in a glance (only high-level blocks are there)
Here's an highlight of the four commits in this branch:
1. Add a shared/cmd/parser.go utility to avoid using global variables to store command line flags. This parser is simply a gnuflag wrapper that knows about LXD's specific command line structure (roughly ```<lxd> [subcmd [params]] [flags] [-- [extra]]```) and could be potentially used for other binaries as well which share the same command line structure (e.g. lxc). …
=> Normalize sub commands invocation

lxd/devices.go, shared/util_linux.go
LXD was copying only the lowest 8 bits of the minor device number when adding a device to a container. This caused a wrong device node to be created when adding a device with minor number above 255. Here is a fix to the problem.
=> Fix handling of major and minor numbers in device IDs

lxd/main_init.go, lxd/main_init_test.go, lxd/main_test.go
This branch essentially wires into cmdInit the logic previously
introduced in the shared/cmd package.
In order to be able to run the underlying logic in isolation a few
globals (such as command line arguments) have been replaced with
explicit parameters, that get passed to the CmdInit structure.
An initial unit test has been added, mostly for exemplification, and I
plan to keep working on the logic and on the tests in order to
implement #2834.
Signed-off-by: Free Ekanayaka <free@ekanayaka.io>
=> Make the log cmdInit unit-testable

doc/storage.md
This affects the storage entities that are used to form OSD storage pools not
the RBD storage volumes themselves.
=> ceph: add note about filesystems for Ceph cluster

lxd/main_init.go, shared/network.go
This is a mechanical refactoring of the logic that fills in the
cmdInitData structure given the configuration parameters passed via
auto or collected in interactive mode.
It makes it a bit easier to both see in a blick what the high-level
logic workflow is and what individual configuration parameters
actually translate to low-level data to send via APIs.
=> Extract logic to fill init data to standalone methods

lxd/daemon_config.go
This fixes a bug where changing the auto-update images interval with
the API would not take effect unless the daemon is restarted.
See also the comments to:
https://github.com/stgraber/lxd/commit/28e7d344175097877af7747fd5f2926e9965b17
=> Reset the images auto-update loop when configuration changes

shared/util_linux.go
Fixes #3581.
The condition was always false because `C.size_t` casts -1 to a positive number.
https://github.com/lxc/lxd/blob/6fa008204f5ae55860922d626ddc24bb83e5e2f0/shared/util_linux.go#L294-L299
=> util linux: guess size when sysconf() returns -1

lxd-benchmark/benchmark/batch.go, lxd-benchmark/benchmark/benchmark.go, lxd-benchmark/benchmark/operation.go, lxd-benchmark/benchmark/util.go, lxd-benchmark/main.go
This does the folliwing:
- extract more code from the main `SpawnContainers` and `DeleteContainers` functions to reusable helper methods
- add `start` and `stop` commands to `lxd-benchmark`
=> More lxd-benchmark refactors

lxd/patches.go, lxd/storage_pools.go, lxd/storage_pools_config.go, lxd/storage_pools_utils.go, test/backends/ceph.sh, test/suites/image_auto_update.sh, test/suites/storage_driver_ceph.sh, test/suites/template.sh
Running containers when backed by LVM or Ceph may be in an inconsistent
state during copy.
=> test: Don't copy running lvm/ceph containers

lxd/container_lxc.go, lxd/storage_ceph.go, lxd/storage_ceph_utils.go, test/backends/ceph.sh, test/suites/backup.sh, test/suites/basic.sh, test/suites/image_auto_update.sh, test/suites/storage_driver_ceph.sh
Ceph is similar to zfs in that storage volumes need to be kept around in case they have dependent snapshots. That is:
```
- <storage-volume-1>
- snapshot(<storage-volume-1) = <snap1>
- protect(<snap1>)            = <snap1_protected>
- delete(<storage-volume-1>)
```
will fail since \<snap1_protected\> is dependent. Because of this the way I implemented the ceph driver it will map the delete() operation onto a rename() operation:
```
- delete(<storage-volume-1>) -> rename(<storage-volume-1>) = zombie_<storage-volume-1>
```
But consider the following:
```
lxc init images:alpine/edge a = <storage-volume-a>                                  /* succeeds */
lxc copy a b                  = <storage-volume-b> depends <storage-volume-a>       /* succeeds */
lxc delete a                  = …
```
=> ceph: use uuid when creating zombie storage volumes

lxd-benchmark/benchmark/benchmark.go, lxd-benchmark/benchmark/operation.go, lxd-benchmark/benchmark/report.go, lxd-benchmark/main.go, test/perf.sh
- add support for CSV reporting in `lxd-benchmark`, conforming to the JMeter CSV format (understood by the Jenkins performance plugin)
- add a `perf.sh` script that runs performance tests (create/start/stop/delete containers)
- fix the `--image` parameter in `lxd-benchmark` to correctly fail when a local image fingerprint/alias is passed (without `remote:`) and is not found.
To test, run something like
```
sudo -E LXD_TMPFS=1 LXD_TEST_IMAGE=images:alpine/3.6 ./perf.sh
```
The script also supports setting `LXD_BACKEND` so that matrix testing can be done for different storage backends.
Closes #3670
=> Add performance tests for regression testing

fuidshift/main.go, lxd/container.go, lxd/container_lxc.go, lxd/container_lxc_utils.go, lxd/container_test.go, lxd/main_activateifneeded.go, lxd/main_init.go, lxd/main_test.go, lxd/migrate.go, lxd/storage.go, lxd/storage_btrfs.go, lxd/storage_ceph_migration.go, lxd/storage_dir.go, lxd/storage_lvm.go, lxd/storage_migration.go, lxd/storage_mock.go, lxd/storage_zfs.go, lxd/sys/os.go, lxd/util/sys.go, shared/idmap/empty.go, shared/idmap/idmapset_linux.go, shared/idmap/idmapset_linux_test.go, shared/idmap/shift_linux.go, shared/util_linux.go
Move idmap-related functions to the `shared/idmap` package.
Fixes #3787
=> shared: move idmap/acl functions to a separate package

lxd/storage_zfs.go
=> storage/zfs: use "referenced" property when zfs.use_refquota=true

lxc/move.go, lxd/containers_post.go
When a container is running users can pass "--stateful" to the lxd command line
tool "lxc move". This will move the container and restore the state of the
container on the target.
My original implementation of this feature only applied to stateless container
copies but not to requests to move a container. The only thing we need to do is
pass the stateless argument along in the move codepath for the "lxc move"
command line tool and then restore state on the receiving side based on the
container's config. This is trivial since we know the source container's state
because we preserve volatile keys when moving containers.
Closes #3798.
=> migration: restore state when moving container 

lxd/container_lxc.go, shared/idmap/idmapset_linux.go, test/suites/idmap.sh
Our code has explicitly disallowed this for a long time but somehow we have
never correctly errored out in these cases like we should.
After having discussed this with Eric at Plumbers I think this should be
considered a security liability. The problem I see with this is that it
accidently allows users to escalate a container that is unprivileged to a
privileged container without their knowledge. The most obvious case is when
the allocated range of subids is accidently 0-65536 which is rare but basically
runs afoul of creating an unprivileged container but there are more subtle
problems when using "{uid,gid,both} \<id\> \<id\>" directly so I prefer to disallow
this for now. Especially since this feature is currently not very useful since
the maximum number of allowed idmappings is …
=> idmapping: disallow hostids intersecting subids

client/connection.go, client/util.go, shared/network.go
Added a flag in ConnectionArgs struct that controls whether a client verifies the certificate chain and host name. This allows users to use self signed certificates when connecting to remote host through https. Of course the default value is false, but if you need that you can set it to true when connecting.
Signed-off-by: Ivan Georgiev <vanko.georgiev@gmail.com>
=> Added InsecureSkipVerify flag the ConnectionArgs struct

lxd/main_init_test.go, lxd/storage_btrfs.go, lxd/storage_ceph.go, lxd/storage_ceph_utils.go, lxd/storage_dir.go, lxd/storage_lvm.go, lxd/storage_lvm_utils.go, lxd/storage_pools_config.go, lxd/storage_volumes_config.go, lxd/storage_zfs.go, test/suites/storage.sh, test/suites/storage_driver_ceph.sh
=> storage: rework storage pool + volume updating

shared/util_linux.go
Some arches have the uname as [65]int8, some others have it as [65]uint8.
=> Fix uname handling on some architectures

lxd/storage_lvm.go
xfs explicitly mentions:
"nouuid Don't check for double mounted file systems using the file system uuid.
This is useful to mount LVM snapshot volumes, and often  used  in
combination with "norecovery" for mounting read-only snapshots."
=> lvm: mount xfs snapshots with "nouuid"

lxd/storage_btrfs.go
It seems that btrfs v4.12.1 allows:
(1) btrfs send -p <ro-snap-1> <ro-snap-0>
but disallows
(2) btrfs send <ro-snap-0> -p <ro-snap-1>
Code-wise it assumes that <ro-snap-1> is always found at optind == 1. I
reported upstream and might patch this once they told me which direction they
want to go with this. Until then, work around it.
Closes #3843.
=> btrfs: workaround btrfs bug 

lxd/storage_btrfs.go, lxd/storage_ceph.go, lxd/storage_lvm.go, lxd/storage_volumes.go, lxd/storage_volumes_config.go, lxd/storage_volumes_utils.go, lxd/storage_zfs.go, test/suites/storage.sh
For storage volumes of type storagePoolVolumeTypeContainer We only allow to
change properties directly on the storage volume if there's not corresponding
way to change it by other means. A good example is the "size" property which
can be manipulated by setting a root disk device "size" property.
=> storage: rework container volume properties 

doc/image-handling.md
I had to look in the code to figure out all supported image formats. https://github.com/lxc/lxd/blob/master/lxd/images.go#L67
#3355 made me ^^
=> Document that squashfs images can also be used.

shared/logging/log_posix.go
log15 broke their v2 API earlier today, this change should get things
building again until upstream log15 fixes the API breakage.
Related: https://github.com/inconshreveable/log15/issues/139
=> Temporary workaround for log15 API breakage

lxd/apparmor.go
mem and kmem are really in /dev, and they're not propagated into lxd
containers, privileged or otherwise anyways, so these are useless.
=> drop useless apparmor denies

lxc/storage.go, lxd/daemon.go, lxd/daemon_config.go, lxd/db/images.go, lxd/images.go, lxd/main_init.go, lxd/main_test.go, lxd/patches.go, test/suites/basic.sh, test/suites/concurrent.sh, test/suites/config.sh, test/suites/deps.sh, test/suites/image.sh
=> Fix image expiry, init storage handling when nested and remote storage operations

lxd-benchmark/benchmark/benchmark.go, lxd-benchmark/main.go, lxd/networks.go, shared/cert.go, test/perf.sh
=> lxd-benchmark improvements, fix network renames and cleanup use of log

lxd/patches.go, lxd/storage_pools_config.go
The size property does not make sense for osd storage pools since the cluster
effectively determines the size.
=> ceph: remove size property from osd pools

doc/api-extensions.md, doc/containers.md, lxd/api_1.0.go, lxd/container_lxc.go, shared/container.go, test/main.sh, test/suites/kernel_limits.sh
This adds support for liblxc's lxc.prlimit.[limit name] feature.
Closes #3272.
=> containers: add limits.kernel.[limit name] support 

lxc/file.go, lxc/image.go
Prefix local paths with `/var/lib/snapd/hostfs` when running in the snap.
Closes #3921
=> Prefix paths when lxc is run in a snap

lxd/container.go, lxd/container_lxc.go, lxd/types/devices.go
In order to determine whether a given device needs to be updated LXD will diff
the keys and values for the old and the new device settings. If LXD determines
a difference it will append the key and the corresponding value to the device.
If it determines they don't differ the key and value won't be in the updated
devices list that is passed to the the container's update method. So we can
simply rely on checking whether the given key exists in the device that is to
be updated if it isn't we don't need to run the actual update.
Closes #3920.
=> network: do not update limits unconditionally

doc/api-extensions.md, doc/containers.md, lxd/api_1.0.go, lxd/container.go, lxd/container_lxc.go, lxd/networks_utils.go
The `vfio` interface type supports SR-IOV enabled network devices. These
devices associate a set of virtual functions (VFs) with the single physical
function (PF) of the network device. PFs are standard PCIe functions. VFs on
the other hand are very lightweight PCIe functions that are optimized for data
movement. They come with a limited set of configuration capabilites to prevent
changing properties of the PF. Given that VFs appear as regular PCIe devices to
the system they can be passed to containers just like a regular physical
device. The `vfio` interface type expects to be passed the name of an SR-IOV
enabled network device on the system via the `parent` property. LXD will then
check for any available VFs on the system. By default LXD will allocate the
first free VF it finds. If it …
=> Add support for SR-IOV enabled network devices

shared/util.go
The kernel won't allow us to bind-mount stuff through /proc.
Since the main reason for my previous change was to fix /dev handling,
lets just whitelist /dev as safe to read from within the snap, which
should be fine so long as distros use devtmpfs.
Closes #3968
=> Fix failure due to bind-mount through /proc

lxd/container_lxc.go, lxd/migrate.go, lxd/util/sys.go
This requires us to link against liblxc.
Closes #3934.
=> liblxc: detect version at runtime

lxd/storage_zfs.go
=> zfs: try pool import

lxd/container_logs.go
Those files are used by the container runtime.
=> lxd/logs: Don't allow removing lxc.conf or lxc.log

shared/api/server.go
=> shared/api: Add API extension label to AuthMethods

lxc/console.go, lxc/file.go, po/de.po, po/el.po, po/fr.po, po/id.po, po/it.po, po/ja.po, po/lxd.pot, po/nl.po, po/ru.po, po/sr.po, po/sv.po, po/tr.po, po/zh.po, po/zh_Hans.po
This will likely show as redundant until we SRU the -1 fix to the various LXC releases, but for recent LXC, this is useful.
=> Print detach message in console and improve lxc file logging

test/suites/config.sh
=> tests: Deal with missing ttyS0/ttyS1 (on s390x)

doc/environment.md, lxd/util/sys.go
This is needed for the LXD snap.
The pre-start/post-stop container hooks point to the LXD path and are
called when the container shuts down.
As the snapd paths include the revision of the daemon, a system which
got updated would then have a hook path pointing to a non-existing
binary.
This extra env variable allows us to point to the "current" path in the
snap, which is effectively a symlink to whichever is the latest binary.
=> lxd/dameon: Add LXD_EXEC_PATH to override execPath

config/bash/lxd-client
A couple of profile actions had wrong autocompletions.
This commit aims to fix them.
=> Fix some profile autocompletions

lxd/container_instance_types.go, lxd/daemon.go, lxd/images.go, lxd/logging.go, lxd/util/http.go
The various periodic tasks that the Daemon spawns have been changed so
they do their best to gracefully terminate as soon as possible when
the given context gets cancelled (which happens upn daemon
shutdown). Due to some of underlying APIs not supporting cancellation
yet, this should be considered just a starting point.
=> Gracefully cancel tasks on daemon shutdown

doc/storage.md
This document the common case of using an existing LVM thinpool when your volume
group is not empty, for instance, when you have no option to add an spare disk for it.
=> doc: Add example to create an storage pool from existing LVM thinpool.

lxc/exec.go, po/de.po, po/el.po, po/fr.po, po/id.po, po/it.po, po/ja.po, po/lxd.pot, po/nb_NO.po, po/nl.po, po/pt_BR.po, po/ru.po, po/sr.po, po/sv.po, po/tr.po, po/zh.po, po/zh_Hans.po
See https://github.com/lxc/lxd/issues/3054#issuecomment-347925994
This probably needs to be adjusted in the i18n translation files, but I have no idea how that works.
=> Added documentation about shell env to lxc exec

lxd/storage_zfs_utils.go
Completely fixes #4056.
While #4060 fixed something, this was the root cause of my problems.
Tested, working.
Signed-off-by: Adrian Pistol <vifino@tty.sh>
=> zfs: fix argument order of zfs get commands.

lxd/storage_btrfs.go, lxd/storage_dir.go
dir and btrfs allow the bind-mounting of an existing fs path, as this
can be outside of the snap's mount namespace, we need to wrap those
paths using shared.HostPath.
=> storage: Use HostPath for dir/btrfs

lxd/container.go, lxd/container_console.go, lxd/container_lxc.go, test/suites/console.sh
Not too long ago we merged
lxc/lxc#1925
which adds the new configuration keys
- lxc.console.buffer.size
- lxc.console.buffer.logfile
- lxc.console.rotate
LXD will always set
lxc.console.buffer = auto
which allocates a 128kB ringbuffer for each container and
lxc.console.buffer.logfile=/var/log/lxd/<container-name>/console.log
which is an on-disk representation of the console ringbuffer. liblxc will
always dump the in-memory ringbuffer when a container stops so users can
request the last contents of the ringbuffer if a container fails to start. When
a container is running and a request is sent to the retrieve the current
in-memory ringbuffer contents liblxc will also automatically dump the current
contents to disk.
As of this commit LXD will ignore lxc.console.logfile i.e. it cannot be …
=> console: adapt to new liblxc changes 

lxd-benchmark/main.go
The default count for lxd-benchmark is 100 containers.
This can crash systems with less than 16GB of RAM.
The default should be 1, and then let the user select a bigger value.
Signed-off-by: Simos Xenitellis <simos@users.noreply.github.com>
=> lxd-benchmark: Change the default count of containers from 100 to 1

lxd/container_lxc.go, shared/util.go
This allows us to e.g. mount stuff like:
/some/path with spaces
to
/some/other path with spaces
Closes #4064.
=> container_lxc: escape paths fstab style 

config/bash/lxd-client, doc/api-extensions.md, doc/containers.md, lxd/containers.go, shared/container.go, shared/version/api.go
boot.stop.priority is now an attribute of a container and can be set similar to that of boot.autostart.priority.  Upon shutdown, containers will shutdown based on priority level with higher priority containers shutting down before those of lower priority containers.  If boot.stop.priority is never set on any container, the same performance and behavior of LXD prior to this change can be expected.
Signed-off-by: Kevin Pick  <cyberkpick@utexas.edu>
=> Implements boot.stop.priority as described in #2082

lxc/action.go, po/de.po, po/el.po, po/fr.po, po/id.po, po/it.po, po/ja.po, po/lxd.pot, po/nb_NO.po, po/nl.po, po/pt_BR.po, po/ru.po, po/sr.po, po/sv.po, po/tr.po, po/zh.po, po/zh_Hans.po, test/suites/basic.sh
Allow running actions (start, stop, ...) against all containers.
Signed-off-by: Michael Schubert <michael@kinvolk.io>
=> lxc/action: add `--all` flag

lxc/main.go, lxd/api_1.0.go, lxd/containers.go, lxd/storage.go, lxd/storage_pools_utils.go
This moves all the data we need into the cache so that we don't cause
any filesystem related calls when we received "GET /1.0".
Closes #4025
=> Improve storage cache, first-run flag and auto-start error handling

lxd/container_lxc.go, lxd/migrate.go
With the previous commits pre-copy migration was opt-in as not all architecture/kernel/CRIU combinations support it. With the newly added CRIU feature checking support added to lxc and go-lxc the pre-copy migration is now switched from defaulting to off to default to what the platform actual supports.
If the architecture/kernel/CRIU combination supports pre-copy migration it is turned on. The user has still the chance to opt-out of pre-copy migration by setting 'migration.incremental.memory' to 'false'.
=> mirgation: enable pre-dumping based on CRIU's feature check

lxc/list.go, lxc/list_test.go, po/de.po, po/el.po, po/fi.po, po/fr.po, po/id.po, po/it.po, po/ja.po, po/lxd.pot, po/nb_NO.po, po/nl.po, po/pt_BR.po, po/ru.po, po/sr.po, po/sv.po, po/tr.po, po/zh.po, po/zh_Hans.po
Title is self-explanatory :)
Reason to have this done is that I saw this post: https://discuss.linuxcontainers.org/t/lxc-list-column-for-process-number/1017/4 and seemed pretty easy to implement.
```
ubuntu@lxd-dev:~/go/bin$ ./lxc info c1 | grep Proc
Processes: 26
ubuntu@lxd-dev:~/go/bin$ ./lxc list -c n,N
+------+-----------+
| NAME | PROCESSES |
+------+-----------+
| c1   | 26        |
+------+-----------+
ubuntu@lxd-dev:~/go/bin$ 
```
=> Lxc list display number of processes inside of container

shared/idmap/idmapset_linux.go
Instead of hardcoding always using root's idmap, let's ask for the current
user's idmap. This should have no effect for LXD, but may potentially be
useful for downstream users of idmap :)
=> allow arbitrary users to read idmaps

lxd/container_lxc.go, lxd/util/sys.go, shared/idmap/idmapset_linux.go
1. We just strip the newline everywhere we use this anyways, so we can drop
the stripping code too.
2. liblxc itself doesn't even accept this string with a newline on the end,
so it's not even an LxcString :)
=> drop \n from IdmapSet's ToLxcString

config/bash/lxd-client
When containers have mulitple IP addresses, `lxc list` rows span over multiple lines, like:  
```
+------------------+---------+--------------------------------+-----------------------------------------------+------------+-----------+
| maas             | RUNNING | 192.168.200.1 (maas0)          | fd42:1fe6:bf48:a57d:216:3eff:fefd:a254 (eth0) | PERSISTENT | 0         |
|                  |         | 10.215.5.126 (eth0)            |                                               |            |           |
+------------------+---------+--------------------------------+-----------------------------------------------+------------+-----------+
```
This causes bash completion to include a `|` among container names.
=> fix parsing for container name tab-completion

lxd/main_activateifneeded.go, lxd/main_init.go, lxd/util/sys.go, shared/idmap/idmapset_linux.go
Make this more generally useful by accepting a username.  If that
is "", then use the current user.
Signed-off-by: Serge Hallyn <shallyn@cisco.com>
=> shared/idmap:DefaultIdmapSet(): take a user argument

lxd/storage.go, shared/version/useragent.go
This can be used by some image server to return a different set of
images based on the storage backends in use and will also make it easier
for us to know what storage backends to focus efforts on.
=> shared/version: Include storage backends in agent

test/suites/config.sh
=> Make the test suite use lxc.apparmor.profile instead of lxc.aa_profile

doc/api-extensions.md, doc/containers.md, lxd/container.go, lxd/container_lxc.go, lxd/daemon.go, lxd/devices.go, lxd/sys/os.go, shared/util.go, shared/version/api.go
This adds support to hotplug unix devices into the container by supporting the
"required" property.
Closes #3995.
=> container_lxc: add unix device hotplug support

scripts/bash/lxd-client
Inside snaps, bash completion snippets run for the _unaliased_ command. That means that the completion needs to be looking for `lxd.lxc`, not just `lxc`. Fortunately you can ask for both, so it's an easy tweak (and people are very unlikely to have an unrelated `lxd.lxc` command lying around with different completion).
=> scripts/bash: tweak complete line for snaps

doc/rest-api.md
Trivial fix adding some missing "Return:" headings to correctly format sample return content.
=> fix API documentation formatting

lxd/container_lxc.go
Unprivileged container don't need to drop any capabilities. The kernel will
enforce security for us.
=> container_lxc: keep full capability set

test/includes/clustering.sh
It seems that on single-CPU machines the 'ip link del "${veth1}"' call
fails pretty much always. I assume because one side of the veth pair
is attached to the net namespace of the process being killed and the
kernel wipes it immediately, or something like that.
=> Delete the namespaced veth before killing the process

lxd/main_init.go
The lxd init code used to get networks and storages via a dedicated
cluster API, which was filtering out managed networks. The code was
updated to use the regular GET /networks API instead, and to filter
out managed networks. However it was creating a slice of networks
assuming that no network would be skipped.
I tried to add an integration test for interactive mode, but filling
in the trust password is not straightforward. We'll probably want to
figure it out separately.
=> Fix regression in "lxd init" in interactive mode for clustering

lxd/main_shutdown.go
=> Ignore io.EOF errors when performing PUT /internal/shutdown

lxd/main_shutdown.go
=> lxd/shutdown: Fix typo in error handling

shared/idmap/idmapset_linux.go
I believe these checks are intended as a heuristic to indicate whether or
not the current userspace understands idmaps. However, it is perfectly
possible to have a userspace that knows about /etc/subuid, but doesn't have
newuidmap installed. In fact, on my recent upgrade to bionic, it helpfully
uninstalled newuidmap, which is how I noticed this in the first place.
Given that there are additional checks to see if /etc/uidmap actually
exists, we should just go with those and assume people know what they're
doing.
=> idmap: get rid of new{u,g}idmap checks

lxd/containers_post.go, lxd/db/node.go, lxd/db/node_test.go, test/suites/clustering.sh
If no target node is specified, place the container on the non-offline node with the least number of containers. Closes #4305.
=> Clustering placement

client/lxd_containers.go, lxc/move.go, lxd/api_internal.go, lxd/container.go, lxd/container_lxc.go, lxd/container_post.go, lxd/containers_post.go, lxd/db/containers.go, lxd/db/containers_test.go, lxd/db/storage_pools.go, lxd/patches.go, lxd/profiles_utils.go, lxd/storage_btrfs.go, lxd/storage_ceph_migration.go, lxd/storage_migration.go, lxd/storage_zfs.go, shared/container.go, test/suites/clustering.sh
This implements moving ceph-based containers across cluster nodes.
It supports both moves with renames and without renames (the container keeps the same name), and moving a container also if the node currently hosting the container is offline.
As discussed, later down the road we'll want to extend this functionality to all kinds of containers, not only the ceph-based ones. At that point we might also rearrange the code to be more generic, if needed.
Closes #4306.
=> Clustering move ceph based containers

lxd/db/certificates.go, lxd/db/cluster/open.go, lxd/db/containers.go, lxd/db/db.go, lxd/db/images.go, lxd/db/migration.go, lxd/db/networks.go, lxd/db/profiles.go, lxd/db/query/retry.go, lxd/db/storage_pools.go, lxd/db/storage_volumes.go
Make all our DB APIs use transactions.
This change is in preparation of a new dqlite release that properly supports distributed checkpoints (iow, compacting the write-head log file content atomically across all nodes). In order to safely do that, dqlite needs to know about ongoing transactions, so now LXD explicitly goes through the BEGIN,COMMIT/ROLLBACK dance in every database API.
=> Always use transactions when querying the database

Makefile, lxd/cluster/gateway.go, lxd/cluster/raft.go, lxd/db/db.go, lxd/db/query/retry.go, lxd/main_activateifneeded.go
This adapts the LXD code to the new dqlite API which supports proper checkpointing.
Note that the forked sqlite source code now needs to be built with "--enable-replication", otherwise the replication API won't be available. This was done to hopefully facilitate merging the replication patch upstream (all experimental or less used SQLite APIs generally require to pass a non-default ./configure flag)
=> Adapt to new dqlite api

lxd/container_lxc.go, lxd/db/certificates.go, lxd/db/config.go, lxd/db/containers.go, lxd/db/images.go, lxd/db/networks.go, lxd/db/profiles.go, lxd/db/storage_pools.go, lxd/db/storage_volumes.go, lxd/profiles_utils.go
The two commits are:
- Fix a few spots were database errors were effectively swallowed.
- Retry all transactions initiated with db.begin()/db.TxCommit()
The second commit somehow fixes a regression introduced by #4347, where retry logic for TxCommit was dropped. However that logic was broken, since it was retrying only the COMMIT statement, although a "database is locked" error can be raised at any point during the transaction.
Longer term, we should further rework the db package so that:
1) No call sites outside the db package run SQL queries directly (at the moment there are 3 spots left that are using db.Cluster.Begin to run queries)
2) All call sites outside the db package use db.Cluster.Transaction as entry point
3) All APIs in the db package should be methods of db.ClusterTx, iow …
=> Fix ignored database errors

lxc/image.go
=> lxc/image: Fix crash due to bad arg parsing

lxd/main_forkfile.go
On systems without glibc, as Alpine, you might lack definition of PATH_MAX.
This patch adds the limits.h header to solve this issue.
Signed-off-by: Roberto Oliveira <robertoguimaraes8@gmail.com>
=> lxd: add missing limits.h include

lxd/main_init_interactive.go
=> lxd/init: Don't setup a remote storage pool by default

lxd/main_init_interactive.go
AFAIU, we were passing to POST /1.0/storage-pools some internal config keys that
are generated by LXD when it handles the request, and shouldn't be included in
the request payload.
For some reason doing that didn't break in the case where you were creating a
new zfs pool (setting "source" to a block device), but it does break when
setting "source" to an existing zfs pool name.
I manually tested the fix to confirm it works, since at the moment we don't have
a way to run lxd init interactively in integration tests (the main issue is how
to ask for the trust password).
The lxd init --preseed case was not affected by this bug, as long as you avoid
including those internal config keys in your YAML.
Closes #4404.
=> Fix interactive lxd init failing to join a cluster with an existing zfs dataset

lxd/db/storage_pools.go, lxd/db/storage_pools_test.go
This bug was effectively preventing from creating two storage pools in the same clusters, under certain circumstances (e.g. a zfs pool and a ceph pool).
=> Properly filter node-level storage configs by pool ID

lxc/config_trust.go
=> lxc/config: Fix adding trust cert on snap

lxd/devices.go
=> devices: fail if Nvidia device minor is missing

lxd/cluster/raft.go
This will use the raftLogger wrapper that we already have, and forward to our
logger. The output will be just a few INFO messages when connecting between
nodes, joining and leaving, so pretty low noise. It helps in case of errors at that
layer because error messages will be logged.
=> Pass a logger to raft-http

lxd/main_init_interactive.go
=> lxd/init: Require root for interactive cluster join

lxd/daemon.go
Should make debugging startup failures a bit easier.
=> Log the error that made Daemon.Init() fail

lxd/api_cluster.go, lxd/api_cluster_test.go, lxd/api_internal.go, lxd/cluster/gateway.go, lxd/cluster/membership.go, lxd/cluster/membership_test.go, lxd/db/cluster/open.go, test/suites/clustering.sh
This commits make the cluster automatically promote a spare node as database node (if available) when another node gets deleted.
=> Promote database node upon delete

lxc/cluster.go, po/de.po, po/el.po, po/es.po, po/fa.po, po/fi.po, po/fr.po, po/hi.po, po/id.po, po/it.po, po/ja.po, po/lxd.pot, po/nb_NO.po, po/nl.po, po/pa.po, po/pl.po, po/pt_BR.po, po/ru.po, po/sr.po, po/sv.po, po/tr.po, po/uk.po, po/zh.po, po/zh_Hans.po, test/main.sh, test/suites/clustering.sh
This allows to turn an existing non-clustered LXD instance in the first node of a cluster.
=> Add "lxc cluster enable" command

lxd/main_init_interactive.go
When one selects the `no` option when setting up MAAS and then selects the option to set up a custom bridge, the prompt still appears to ask if the interface is connected to MAAS. This is due to the value `config.Config["maas.api.url"]` is set to nil and not to `""`.
=> lxd init: fix maas.api.url check when setting up existing bridge

lxd/container_lxc.go
=> container_lxc: fix optional property for disk devs

lxd/container_lxc.go, lxd/devices.go, shared/util_linux.go
Copy the mode of a devices for:
- Implicitly Added Devices:
Some device types (e.g. infiniband or (Nvidia) gpu) implicitly add devices to
guarantee correct functionality.
- Nvidia GPUs:
In order for Nvidia tools to correctly function we need to copy the mode of
the devices. We should do this for GPUs in general.
- Hotplugged Devices:
We can retrieve the mode of devices that are supposed to be hotplugged.
Closes #4534.
=> devices: clone mode of device

lxc/remote.go, po/de.po, po/el.po, po/es.po, po/fa.po, po/fi.po, po/fr.po, po/hi.po, po/id.po, po/it.po, po/ja.po, po/lxd.pot, po/nb_NO.po, po/nl.po, po/pa.po, po/pl.po, po/pt_BR.po, po/ru.po, po/sr.po, po/sv.po, po/tr.po, po/uk.po, po/zh.po, po/zh_Hans.po
This adds the --format option to lxc remote list
closes #4500
=> add --format option to lxc remote list

lxd/main_callhook.go
It seems that I didn't properly check the `LXD_SOCKET` implementation in #4426 . Because in the meantime I found a missing piece: `lxd callhook` also needs to support the environmental variable (see ganto/copr-lxc3#4).
> First check the LXD_SOCKET environment variable which might
> contain a user provided Unix socket before trying to connect
> to default LXD socket.
=> lxd/callhook: Respect LXD_SOCKET environment variable

doc/api-extensions.md, doc/containers.md, lxd/container.go, lxd/container_lxc.go, lxd/devices.go, shared/version/api.go
we add a new option `propagation`, which allows to specify exactly how
bind-mounts will be shared between the host and a container.
Signed-off-by: Igor Galić <igor.galic@automatic-server.com>
=> Allow configuration of mount-propagation

lxd/api_internal.go, lxd/cluster/heartbeat.go, lxd/containers_get.go, lxd/db/db_internal_test.go, lxd/profiles_test.go
This change makes us use transactions also in test code, and the /internal/sql
API endpoint which was not doing that before.
It also drops concurrent calls in the GET /containers and cluster heartbeat
code, since at the moment they are hardly going to take advantage of
concurrency, as the nodes are going to serialize db reads anyways (and db reads
atm are a substantial part of the total time spent in handling an API request).
The lower-level change to actually serialize reads was committed partly in
go-grpc-sql and partly in dqlite.
This should mitigate #4548 for now. Listing containers will still be relatively slow, but the timing is going to be predictable and consistent.
Moving forward we should start optimizing dqlite to be faster (I believe there
are substantial gains to be made …
=> Serialize reads to the cluster database

lxd/images.go, test/main.sh, test/suites/clustering.sh
=> Redirect container/snapshost publish API requests to the relevant node

doc/clustering.md, lxd/networks.go, lxd/storage_pools.go
=> Better errors and docs about node-specific config keys of pools and networks

lxd/container_lxc.go, lxd/profiles.go, lxd/profiles_utils.go, test/main.sh, test/suites/clustering.sh
This fixes #4575.
The implementation is slightly complicated by the fact that containerLXC.Update() requires database changes about the new profile to be already persisted, but that happens in the node that first serves the request, so a call to containerLoadByName on another node that gets notified would load the new data and Update() would be a no-op. For this reason I added the new containerLXCInstantiate, expandConfigFromProfiles, expandDevicesFromProfiles that allow creating a containerLXC object using the old profile data.
=> Propagate profile changes to cluster nodes

scripts/lxc-to-lxd
The unix socket path of the LXD service can be customized via
LXD_SOCKET variable. Make sure this is also supported when migrating
containers from LXC to LXD.
_**Edit:** Ah, sorry, initial naming (lxd-p2c instead of lxc-to-lxd) was wrong_
=> lxc-to-lxd: Respect LXD_SOCKET environment variable

lxd/main_nsexec.go
Avoid the costly string-parsing and readlink() calls.
=> nsexec: simplify attach_userns()

lxd/cluster/membership.go, lxd/db/networks.go, lxd/db/networks_test.go, lxd/db/storage_pools.go, lxd/db/storage_pools_test.go
The filter was broken since it should have been "storage_pools_config.node_id=?"
instead.
The method has been renamed to StoragePoolsNodeConfig for extra clarity.
I changed the logic of NetworksConfig to perform node filtering as well (and
renamed it to NetworksNodeConfig), and dropped Go-land manual filtering in the
call sites.
This fixes #4629.
=> Fix the storage_pool_id filter from the WHERE clause of StoragePoolsConfig

shared/network.go
With out keep alive, lxc will block indefinitely when there is network change.
=> Enable tcp KeepAlive

lxd/main_activateifneeded.go, lxd/main_init_interactive.go, lxd/util/sys.go, shared/idmap/idmapset_linux.go
Since this code is handy, let's allow it to parse other roots on the
filesystem than just /.
=> allow uidmaps to be parsed from alternate roots

lxd/main_forkproxy.go
Usually we should wait for the child process somewhere here. But we cannot
really do this. The listener file descriptors are retrieved in the go runtime
but at that point we have already double-fork()ed to daemonize ourselves and so
we can't wait on the child anymore after we received the listener fds. On the
other hand, if we wait on the child here we wait on the child before the
receive. However, if we do this then we can end up in a situation where the
socket send buffer is full and we need to retrieve some file descriptors first
before we can go on sending more. But this won't be possible because we're
waiting before the call to receive the file descriptor in the go runtime.
Luckily, we can just rely on init doing it's job and reaping the zombie
process. So, technically unsatisfying …
=> proxy: handle full socket buffer

lxd/container.go
Allow identity mapped uid/gid ranges in the raw.idmap config even if the
LXD_UNPRIVILEGED_ONLY environment variable is set.  Make sure that this
also prevents the root user in the parent namespace from being mapped
into the child namespace.
This is useful for mapping the uid of the user into the child namespace
so that they can still access files in their home directory.
I tried running the tests locally but they complained about not being able to find "golang.org/x/tools/go/gcimporter".  From what I can see the path is actually "golang.org/x/tools/go/internal/gcimporter" but I'm not sure where it's getting the incorrect path.
I did test this specific behavior locally:
```bash
(termina) chronos@localhost ~ $ lxc config set penguin raw.idmap "both 1000 0"
error: Cannot create non-identity …
```
=> Allow identity mappings for unprivileged containers

shared/util.go
This change prevents failure when adding disk devices to containers
where the source is a symlinked directory.
=> shared: Dereference directory symlinks

lxd/main_forkproxy.go
Currently, the mode (Unix file permissions) is converted from string to decimal using `Atoi()`.
The mode is traditionally provided as octal, therefore the conversion should be from string to octal, with `strconv.ParseUint()`.
=> Convert mode from string to octal (not to decimal)

lxd/networks.go
Include prefix-len, which defaults to 64, in the --dhcp-range
option to dnsmasq.
Signed-off-by: Mikael Magnusson <mikma@users.sourceforge.net>
=> networks: Support stateful DHCPv6 with prefixes longer than /64

shared/network.go
This string
&{%!s(*os.file=&{{{1 0 0} -1 {0} <nil> 1 true true true true} master <nil> false false})}
is not helpful at all so stop dumping it to the log. It is just irritating.
=> network: do not print writer struct on error

lxd/cluster/raft.go
We have been taking raft snapshots agressively for a while now, in order
to mitigate #4485.
This change makes the frequency less aggressive. It shouldn't really make a
difference regarding #4485, since we take a raft snapshot at daemon shutdown
anyways, so the net effect is virtually the same (except in case of hard
crashes).
It seems snapshots might have some impact on #4769, so this should help.
The snapshots trick will go away altogether in the new dqlite implementation.
=> Reduce the frequency of raft snapshots

lxd/container_lxc.go, lxd/networks_utils.go
dnsmasq doesn't record the MAC address for IPv6 leases, so add logic to
detect that case and then cleanup base on the container name.
This isn't perfect as there's no guarantee that the reported name over
DHCP matches the container's LXD name, but there's really nothing else
to match against.
Closes #4635
=> lxd/networks: Improve dnsmasq leases cleanup

doc/production-setup.md
The default ARP table size in the kernel has a limit of 1024 entries. 
If you launch more than a thousand containers, you will fill up the time 
and no new entries get accepted because each container takes up an entry in the ARP table.
=> "neighbour: ndisc_cache: neighbor table overflow"

lxd/apparmor.go
=> lxd/apparmor: Fix typo in nesting profile

client/lxd.go, client/lxd_containers.go, client/lxd_images.go, client/simplestreams_images.go
This adds the needed logic in the client to look for and use /dev/lxd/sock, attempting to download the image binaries through the host when possible.
@tvansteenburgh sorry it took 3 months :)
This should let you reduce your bandwidth usage quite a bit once host and containers run a version of LXD that supports it AND you have the needed security flags enabled (`security.devlxd` and `security.devlxd.images`).
=> Support downloading through host LXD

doc/api-extensions.md, doc/networks.md, lxd/iptables.go, lxd/networks.go, lxd/networks_config.go, shared/version/api.go
The current implementation of the NAT feature in LXD causes some
issues when it should collaborate with firewall/IPsec packages. This
patch adds therefor some flexibility within LXD on how firewall
rules are handled. This espacially comes into play during restarts
of lxd(8).
The ipv[46].nat configuration options are advanced to accept the
following options:
- true|insert: the firewall rule is insert at the beginning of the
POSTROUTING table
- false: no rule is added
- append: the iptables rule is appended at the end of the POSTROUTING
table
To keep the configuration options backwards compatible the old value
"true" and "false" are kept.
=> Allow NAT rule to be appended to POSTROUTING table

lxd/cluster/gateway.go, lxd/cluster/gateway_test.go, lxd/daemon.go
This branch configures dqlite to use lxd's logger instead of its default one (from the stdlib)
=> Forward dqlite logging

shared/idmap/shift_linux.go
When I suggested the `memcpy()` between ` vfs_cap_data` to `vfs_ns_cap_data` in order
to copy fscaps I forgot to mention that we need to ensure that all fields are
passed as 32 bit little endian integers. This commit makes sure to convert from
big to little endian when passing the uid down.
=> fscaps: translate from big to little endian

client/lxd_cluster.go, doc/clustering.md, lxd/api_cluster.go, lxd/main_init.go, lxd/main_init_interactive.go, test/includes/clustering.sh
This changes the format of the YAML, but the code handling the old format is
still there so it will continue to work (although we now print the new format
when you dump the YAML config at the end of interactive mode).
Fixes #4830.
=> Make use of the new cluster join API in lxd init

lxd/patches.go
Daemon patches were recently changed (PR #4881) to use the new
ContainersNodeList API instead of the older ContainersList one. Unfortunately
the newer API requires the "node_id" column to be present, which is not the case
when those patches are triggered during an upgrade from a pre-clustering
version.
=> Fix "no transaction is active" error during database updates

lxc/remote.go
=> lxc/remote: Fix crash on bad remote name

lxd/api_cluster.go
=> lxd/cluster: Properly skip pending networks/pools

lxd/daemon.go, lxd/images.go
As LXD may have been downloading or publishing an image as it got
restarted or crashed, it's not that unusual for there to be leftovers in
the images directory.
This adds a function which compares the content of the images directory
with what's expected to be there according to the database and deletes
any file that shouldn't be there.
=> lxd/images: Cleanup any leftovers on startup

lxd/images.go, test/suites/clustering.sh
The peers will remove the image from disk upon receiving the notification.
Fixes #4906.
=> Send a notification to other nodes when an image is removed

lxc/image.go
=> lxc/image: Fix URL-based imports

Makefile
The complete clone of sqlite repo is about 89 MB while the shallow copy is just about 9 MB. There is a significant gain primary in bandwidth saving and consequently in compilation speed.
=> shallow clone for deps

lxd/api_cluster.go, lxd/cluster/membership.go, lxd/container_backup.go, lxd/container_console.go, lxd/container_delete.go, lxd/container_exec.go, lxd/container_post.go, lxd/container_put.go, lxd/container_snapshot.go, lxd/container_state.go, lxd/containers_post.go, lxd/daemon_images_test.go, lxd/db/cluster/schema.go, lxd/db/cluster/update.go, lxd/db/cluster/update_test.go, lxd/db/node.go, lxd/db/node_test.go, lxd/db/operations.go, lxd/db/operations_test.go, lxd/images.go, lxd/migrate_container.go, lxd/operations.go, lxd/storage_volumes.go
Add a new "type" column to the operations table, which identifies the type of the operation being performed, and associates a description with it. All call sites creating an operation have been modified to pass the operation type code, rather than a description.
Change the scheduling logic for picking a cluster node when no target is specified: pending operations for creating a container are taken into account when calculating the number of containers on a node.
There's no integration test since there's no way to reliably submit a create container request during the time window between creating an operation and completing it.
Closes #4884.
=> Container scheduling honors pending operations

lxc/copy.go, lxc/init.go
Otherwise we end up with differing structs pointing to the same server,
bypassing handling for copy/move within the same server.
Closes #4956
=> lxc: Only target if --target is passed

scripts/bash/lxd-client
Bash autocomplete is missing 'lxc network info'
Signed-off-by: Asterios Dimitriou <asterios@pci.gr>
=> bash completion for 'lxc network info'

lxd/cluster/upgrade.go, lxd/cluster/upgrade_test.go, lxd/daemon.go, lxd/db/node.go, lxd/db/node_test.go
When clustered, a task will check every 5 minutes if the node is out
of date with respect to other nodes in the cluster, and, if so trigger
an upgrade using the LXD_CLUSTER_UPDATE environment variable.
Fixes #4942.
=> Support lxd cluster update env var

lxd/api.go, lxd/api_cluster.go, lxd/cluster/heartbeat_test.go, lxd/cluster/membership_test.go, lxd/daemon.go, lxd/db/db.go, lxd/db/query/retry.go, lxd/db/testing.go, lxd/response.go
This makes database queries timeout after 10 seconds if quorum is lost **after** the node had initially started fine (e.g. cluster was up but a majority of db nodes were shutdown), which is probably the most common case we want to address.
What it does **not** do is trying to make the node minimally operational (e.g. server responding to "lxc info" without hanging forever) in the case where the daemon is still going through its startup sequence and it's stuck waiting for other nodes to be upgraded, since it found that its own version is more recent. That information is of course present in the logs of the daemon tho, so it should be pretty obvious to figure what's wrong with the stuck client.
Given that we're going to trigger snap refreshes explicitly when we detect that one node has …
=> Make database queries timeout after 10s if cluster db is unavail

lxd/main_forkproxy.go
See https://discuss.linuxcontainers.org/t/howto-configure-logrotate-capabilities-for-proxy/2575/4
=> proxy: Only log errors

doc/api-extensions.md, doc/containers.md, lxd/container_lxc.go, scripts/bash/lxd-client, shared/container.go, shared/version/api.go
This introduces an additional 3 configuration keys to control the
libnvidia-container integration:
- nvidia.driver.capabilities (maps to NVIDIA_DRIVER_CAPABILITIES)
- nvidia.require.cuda (maps to NVIDIA_REQUIRE_CUDA)
- nvidia.require.driver (maps to NVIDIA_REQUIRE_DRIVER)
Details on the valid values for those options can be found in the NVIDIA
documentation here:
https://github.com/NVIDIA/nvidia-container-runtime
=> Extend nvidia runtime options

lxd/container_lxc.go, lxd/daemon.go, lxd/main_checkfeature.go, lxd/main_forknet.go, lxd/main_nsexec.go, lxd/networks_utils.go, lxd/sys/os.go, shared/netns_getifaddrs.c, shared/network.c, shared/network.go, shared/network_linux.go
This commit introduces my concept of a network namespace aware
getifaddrs(), i.e. `netns_getifaddrs()`.
This presupposes a kernel that supports IF{L}A_TARGET_NETNSID.
I am also introducing:
```C
struct netns_ifaddrs {
struct netns_ifaddrs *ifa_next;
// Can - but shouldn't be - NULL.
char *ifa_name;
// This field is not present struct ifaddrs
int ifa_ifindex;
unsigned ifa_flags;
// This field is not present struct ifaddrs
int ifa_mtu;
struct sockaddr *ifa_addr;
struct sockaddr *ifa_netmask;
union {
struct sockaddr *ifu_broadaddr;
struct sockaddr *ifu_dstaddr;
} ifa_ifu;
// If you don't know what this is for don't touch it.
void *ifa_data;
};
```
which is a superset of struct ifaddrs. It contains additional
information such as the mtu and ifindex of the corresponding network
devices. Note …
=> network: add netns_getifaddrs()

shared/netns_getifaddrs.c
=> netns_getifaddrs: fix argument passing

lxd/container_lxc.go
=> lxd/containers: Force bring up of SRIOV parent

doc/containers.md, lxd/container_lxc.go
This matches the behavior prior to the introduction of
nvidia.driver.capabilities.
=> nvidia: Default to compute,utility

shared/netns_getifaddrs.c
=> netns_getifaddrs: don't print useless info

lxc/image.go, po/de.po, po/el.po, po/es.po, po/fa.po, po/fi.po, po/fr.po, po/hi.po, po/id.po, po/it.po, po/ja.po, po/ko.po, po/lxd.pot, po/nb_NO.po, po/nl.po, po/pa.po, po/pl.po, po/pt_BR.po, po/ru.po, po/sr.po, po/sv.po, po/tr.po, po/uk.po, po/zh.po, po/zh_Hans.po
```sh
$ lxc image list -clF
+---------------------+------------------------------------------------------------------+
|        ALIAS        |                           FINGERPRINT                            |
+---------------------+------------------------------------------------------------------+
| alpine/3.4 (3 more) | cc8b580121227c92e05123e00cc52046b0139253db2c7a034234915f05a43eeb |
+---------------------+------------------------------------------------------------------+
```
* This is useful for shell scripts wanting the full image hash from csv output.
```sh
$ lxc image list -clF --format=csv
alpine/3.4 (3 more),cc8b580121227c92e05123e00cc52046b0139253db2c7a034234915f05a43eeb
```
Signed-off-by: fqbuild <TerraTech@users.noreply.github.com>
=> lxc/image: add new column shorthand char 'F' that displays the full image hash/fingerprint

lxd-p2c/setns.go, lxd/devlxd_gccgo.go, lxd/main_checkfeature.go, lxd/main_forkfile.go, lxd/main_forkmount.go, lxd/main_forknet.go, lxd/main_forkproxy.go, lxd/main_nsexec.go, lxd/storage_cgo.go, shared/idmap/shift_linux.go, shared/network_linux.go, shared/termios/termios_unix.go, shared/util_linux.go
In LXC I've introduced the policy that the minimum supported compiler
version will be the same as for the kernel. This is currently gcc 4.8.
As such we can support the niceties that the C11 standard provides and
also disable the crazyness that are VLAs that have been marked optional
from C11 onwards. So always pass -std=gnu11 and -Wvla.
Closes #5066.
=> tree-wide: pass -std=gnu11 -Wvla

lxc/list.go, lxc/list_test.go, po/de.po, po/el.po, po/es.po, po/fa.po, po/fi.po, po/fr.po, po/hi.po, po/id.po, po/it.po, po/ja.po, po/ko.po, po/lxd.pot, po/nb_NO.po, po/nl.po, po/pa.po, po/pl.po, po/pt_BR.po, po/ru.po, po/sr.po, po/sv.po, po/tr.po, po/uk.po, po/zh.po, po/zh_Hans.po
Supercedes: #5057
```sh
$ lxc list alpine-34 -cnfF
+-----------+--------------+------------------------------------------------------------------+
|   NAME    |  BASE IMAGE  |                            BASE IMAGE                            |
+-----------+--------------+------------------------------------------------------------------+
| alpine-34 | cc8b58012122 | cc8b580121227c92e05123e00cc52046b0139253db2c7a034234915f05a43eeb |
+-----------+--------------+------------------------------------------------------------------+
```
Signed-off-by: fqbuild <TerraTech@users.noreply.github.com>
=> lxc/list: add new column "BASE IMAGE" for both short and long image fingerprint variants

doc/rest-api.md
it was not obvious how to specify a target through the api. 
Thanks to @stgraber for his quick irc support.
=> Added optional ?target=<member> to /containers POST documentation

mkdocs.yml
The documentation of LXD is converted and published on readthedocs.org.
In this conversion, mkdocs is used. When this conversion, mkdocs uses
"mkdocs" theme by default.
With the mkdocs theme, the menu at the top of each page is too large,
and contents of a page will be hidden.
So add mkdocs.yml, and set it to use the "readthedocs" theme. Current
configuration is minium.
=> doc: Add configuration for readthedocs

doc/storage.md
LVM backend supports storage quotas while the documentation still refers
to this feature as being unsupported:
ac1740d7092bf0dfb5e70cc66330e60b68e95613
f88e381d2d7c63c3a35f82691cd3627bf029c2b8
https://github.com/lxc/lxd/issues/1205
Signed-off-by: Dmitrii Shcherbakov <dmitrii.shcherbakov@canonical.com>
=> Document LVM support for storage quotas

lxd/apparmor.go
=> apparmor: Allow cgroupv2 in cgns

client/operations.go
This commit fixes a potential race condition when listening
for events and extracting operations by moving the lock
to before the operation struct is created.
For #5117
=> client: Fix potential event race condition

doc/api-extensions.md, doc/server.md, lxd/api_1.0.go, lxd/cluster/config.go, lxd/daemon.go, scripts/bash/lxd-client, shared/version/api.go, test/suites/external_auth.sh
This introduces a new "candid.api.key" option which can be set to the
expected public key for the candid server.
Setting this key is effectively required if using a non-HTTPs server.
When using HTTPs, this is optional as LXD can fetch the key directly
from the candid server.
An issue with validation of domains is also fixed, effectively
preventing a candid token which doesn't include a domain for being
considered valid when a list of valid domains is set.
=> candid: Improve domain validation and pubkey

lxd/containers_post.go, lxd/daemon_images.go, lxd/daemon_images_test.go, lxd/db/images.go, lxd/images.go
There were a few issues with remote images and projects:
1) When creating a container from a remote image, the image was correctly downloaded but unconditionally linked to the the "default" project.
2) No check was performed before downloading to see if an image is already available in another project (no need to download in that case).
3) Image auto-update logic was only considering images in the "default" project.
Fixes #5136.
=> Fix remote images in projects

doc/api-extensions.md, doc/networks.md, lxd/networks.go, lxd/networks_config.go, shared/container.go, shared/version/api.go
This is mandatory in multicast routing scenarios.
Signed-off-by: Julian Pelizäus <jp@adformc.de>
=> lxd: Add an additional VXLAN TTL configuration key

lxd/api_project.go, test/suites/projects.sh
=> Re-create the project default profile when turning on the project profiles feature

scripts/bash/lxd-client
There's probably some work to do under `case ${no_dashargs[1]}` but I'm not sure what's required.
Signed-off-by: Eric Wolf 19wolf@gmail.com
=> Add 'project' to lxc_cmds

doc/architectures.md, doc/configuration.md, doc/contributing.md, doc/daemon-behavior.md, doc/database.md, doc/debugging.md, doc/dev-lxd.md, doc/environment.md, doc/image-handling.md, doc/production-setup.md, doc/rest-api.md, doc/security.md, doc/userns-idmap.md
In some documents, the first level header ("#") is "Introduction". In
readthedocs, this header is used for menus. So we add the first level
header that represents the contents of the documents.
=> doc: add the appropriate titles to some documents

client/lxd_images.go, client/util.go, lxd/api_cluster_test.go, lxd/api_project.go, lxd/cluster/events.go, lxd/container.go, lxd/container_console.go, lxd/container_exec.go, lxd/containers_get.go, lxd/containers_post.go, lxd/db/images.go, lxd/events.go, lxd/response.go, test/main.sh, test/suites/clustering.sh
This fixes #5163 and also a couple of other bugs that I've noticed while working on it:
- it was not possible to create a project-bound container on a node using a client connected to another node
- images were not transferred correctly between nodes, when bound to projects
There are likely other bugs around projects when used with clustering, but this is a good first pass.
=> Fix listing and creating cluster containers inside projects

lxd/container_lxc.go, test/suites/projects.sh
=> Fix lxc exec when using a container inside a project

lxd/container_lxc.go
=> Prefix the container name with the project name when invoking forkconsole

shared/cert.go, shared/cert_test.go
This switches the key generation code to using an EC384 private key
rather than RSA4096.
This significantly speeds up key generation on some architectures.
Note that existing installations will keep using whatever client or
server key they have, this only affects certification generation on
first use.
If you want a newer installation to use RSA rather than EC, you can
generate a normal x509 cert/key pair using RSA4096 with tools like
openssl and put them in place.
=> shared/cert: Switch default key to EC384

doc/index.md
github.com/miekg/dns requires go >= 1.10 now
Set necessary environment variables before `make`
=> Update build instruction

lxd/migrate_container.go
Doesn't do us any good advertising what the map should be instead of
what it actually is, so let's use the right one instead.
Closes #5205
=> lxd/migration: Use current idmap instead of next

lxd/api_cluster.go, lxd/daemon.go, lxd/db/db.go
This is a workaround for #5234. Later down the road we'll want to implement a
proper fix in dqlite, as described in the issue.
=> Increase go-dqlite client timeout when not-clustered

lxd/api_cluster.go, lxd/daemon.go
Clustering tasks cause a lot of un-necessary wakeups on non-clustered
systems so only start them when needed.
=> lxd: Rework task handling

lxd/db/containers.go
=> lxd/db: Avoid un-needed query on container move

lxd/storage_ceph_utils.go, lxd/storage_lvm_utils.go
This sets user_subvol_rm_allowed for btrfs on block storage, matching
the default behavior on the btrfs backend.
block mount options overrides will still override this default.
Closes #5301
=> lxd/storage: user_subvol_rm_allowed for btrfs

client/events.go, client/lxd_events.go, client/operations.go, lxc/monitor.go, lxd/cluster/events.go, lxd/events.go
Improve EventListener's AddHandler function to use an api.Event
struct rather than an interface{}.
Fix an asymmetry between the AddHandler functions for
Operation and EventListener, as the former provides an
api.Operation struct to its handler function, but the latter
gives just an interface{} that must be either be teased apart
with type assertions or marshaled back into JSON and
unmarshaled into the appropriate type.
Signed-off-by: Stephen Barber <smbarber@chromium.org>
=> client: convert EventListener to use api.Event

lxd/main_init_interactive.go, lxd/storage_zfs_utils.go
Follow up of: https://github.com/lxc/lxd/pull/5345
The ZFS pool is only verified at a later stage as soon LXD tries to create it.
This causes some frustration as we need to go through the whole lxd init process only to find out a mistake was made at a later stage.
This PR implements a function to verify if a ZFS pool exists and a check on the `lxd init` interactive process that calls that same function when a user defines the pool setting to have a ZFS backend.
=> LXD init: Verify ZFS pool when in interactive mode.

lxd/db/node/schema.go, lxd/db/schema/schema.go
The 'make generate' command was not run when patch 38 was introduced, so newly
installed LXDs are inconsistent: the schema version is effectively 38, but the
one stored in local.db is 37.
Closes #5364.
=> Re-generate the fresh schema, bumping the schema version

client/simplestreams_images.go, shared/util.go
Remove DownloadFileSha{256,512}, and export DownloadFileHash. This
removes the restriction of only using sha256 and sha512.
=> Export function DownloadFileHash

shared/network.go, shared/network_unix.go
This is for snap users, during update of the core snap, the custom mount
namespace setup by LXD may be missing, causing access to the host CA
configuration to be temporarily broken (until the next LXD restart).
With this patch, we directly go look for the CA certificates of the host
and merge those with what's in the snap environment.
Closes https://github.com/lxc/lxd-pkg-snap/issues/28
=> shared: Read certificates from host

lxd/db/db.go
While working on LXD 3.0 deb to LXD 3.8 snap upgrades, I ran into an
issue where loading the prepared statements was erroring out, causing
the daemon to exit.
That happens when the first node upgrades as the rest of the cluster is
still on the older schema version, causing the schema upgrade code to be
skipped. The prepared statements were then loaded regardless, causing
the crash when preparing them.
Instead, as soon as we know that the DB hasn't been upgraded, return and
let the retry logic happen. Once the remaining nodes have upgraded, the
schema update will happen and the prepared statements will be
re-processed.
=> lxd/cluster: Fix schema upgrades

doc/image-handling.md
During 'lxc image import', yaml.Unmarshal() and is applied to the following struct:
```go
// ImageMetadata represents LXD image metadata
type ImageMetadata struct {
Architecture string                            `json:"architecture" yaml:"architecture"`
CreationDate int64                             `json:"creation_date" yaml:"creation_date"`
ExpiryDate   int64                             `json:"expiry_date" yaml:"expiry_date"`
Properties   map[string]string                 `json:"properties" yaml:"properties"`
Templates    map[string]*ImageMetadataTemplate `json:"templates" yaml:"templates"`
}
```
ImageMetadata.Properties is a map[string]string, and applying any property as a list will
result in the following error:
> Error: Could not parse metadata.yaml: yaml: unmarshal errors:
> line …
=> image-handling.md: 'release' should be a string and not a list

lxc/storage_volume.go
=> lxc/storage: Fix argument count check for delete

lxd/backup.go, lxd/container.go, lxd/container_instance_types.go, lxd/images.go, lxd/logging.go
Calling op.Run() if operationCreate() has failed will cause a segfault.
This problem is mentioned in #5436.
=> lxd: Fix possible segfaults in tasks

lxd/images.go
When importing a packed image, send 'fingerprint' and 'size'
in metadata when an error occurs because the image already
exists.
=> lxd: Send metadata in CreateImage error importing image

lxd/backup.go, lxd/images.go, lxd/patches.go
This is part 1 of a series of patches to add better progress
tracking support for export and import.
By using Reader and Writer rather than filename for compressing
the caller can provide a tracking reader/writer for progress.
=> lxd/images: change compressFile to take io.Reader and io.Writer

lxd/container.go, lxd/containers_post.go, lxd/images.go, lxd/storage.go, lxd/storage_btrfs.go, lxd/storage_ceph.go, lxd/storage_dir.go, lxd/storage_lvm.go, lxd/storage_lvm_utils.go, lxd/storage_mock.go, lxd/storage_zfs.go
This is part 4 of a series of patches to add better progress
tracking support for export and import.
Add a tracker field to ContainerCreateFromImage and ImageCreate
which can be used during Unpack.
=> storage: Add ioprogress.ProgressTracker field to storage

lxd/containers_post.go, lxd/images.go, shared/util.go
Modify the progress metadata to send stage, percent, speed in
a map keyed by 'progress'. Metadata format will now be:
* progress => {stage: <string>, percent: <string>, speed: <string>}
* <stage>_progress => <string>
=> shared: Progress metadata as a map

client/lxd_containers.go
The stdin channel from WebsocketSendStream needs to be consumed,
otherwise that goroutine will leak.
Signed-off-by: Stephen Barber <smbarber@chromium.org>
=> client: fix goroutine leak in ExecContainer

lxd/main_forkfile.go, lxd/main_nsexec.go
The ELF binary spec doesn specify:
SHT_INIT_ARRAY
This section contains an array of pointers to initialization functions,
as described in ``Initialization and Termination Functions'' in Chapter
5. Each pointer in the array is taken as a parameterless procedure with
a void return.
which means libcs other than glibc might not pass down argc and argv to
constructors.
This reverts commit 2149bdaf895a1145d49e7627b50e0097678de189.
=> Revert "lxd: remove /proc/self/cmdline parsing"

lxd/container_lxc.go
=> lxd/containers: Set liblxc env for CVE-2019-5736

lxd/backup.go
Instead of failing right away when no root device can be found in
devices, check expanded devices as well. Fail only if no root device
could be found.
=> lxd: Fix failing backup import

lxd/container.go
This fixes scheduled snapshots being created twice after each other.
This fixes #5504.
=> lxd: Fix duplicate scheduled snapshots

client/lxd_containers.go
This reverts commit e2379cf367ef76f1b42f5a747c475c18cbdf6cac.
This fix ended up causing issues as outlined in #5519
Reverting until we have a better fix.
=> Revert "client: fix goroutine leak in ExecContainer"

lxd/backup.go, lxd/storage_btrfs.go, lxd/storage_ceph.go, lxd/storage_dir.go, lxd/storage_lvm.go, lxd/storage_zfs.go
Remove the backup backup directory as soon as the tarball has been
created. That way one will hopefully not run out of disk space when
doing backups.
See #5515
=> lxd: Remove backup directory after creating tarball

shared/util_linux_cgo.go
lxc_abstract_unix_recv_fds() used to return 0 if recvmsg() returned 0
and ret if it return < 0. Let's restore that behavior.
=> util_linux_cgo: restore old behavior

lxd/api_cluster.go, lxd/daemon.go, lxd/db/images.go, lxd/db/operations.go, lxd/images.go, test/suites/clustering.sh
1. Sync all available images to the new node after it's joined
2. Add a daily task that is launched only by the leader node to do image synchronization if an image doesn't get synced successfully across the nodes in the past
3. Minor improvement on image sync between the nodes
=> Image sync for joined node

client/lxd_containers.go
=> client: Empty stdin channel on exec completion

lxd/main_nsexec.go
=> lxd/main_nsexec: Fix type of length in file_to_buf

lxd/daemon.go
=> When starting up, use the cluster.https_address as key for updating the nodes table

lxc/cluster.go, lxd/api_cluster_test.go, lxd/db/node.go, lxd/db/node_test.go, po/de.po, po/el.po, po/es.po, po/fa.po, po/fi.po, po/fr.po, po/hi.po, po/id.po, po/it.po, po/ja.po, po/ko.po, po/lxd.pot, po/nb_NO.po, po/nl.po, po/pa.po, po/pl.po, po/pt_BR.po, po/ru.po, po/sr.po, po/sv.po, po/tr.po, po/uk.po, po/zh_Hans.po, test/suites/clustering.sh
This is a first pass at mitigating #5434. We check that the node to be removed has no custom volumes and also require confirmation by default when using ```---force```.
=> Stricter node remove checks

lxc/console.go, lxc/exec.go, lxc/main.go, lxc/main_aliases.go, lxc/monitor.go, po/de.po, po/el.po, po/es.po, po/fa.po, po/fi.po, po/fr.po, po/hi.po, po/id.po, po/it.po, po/ja.po, po/ko.po, po/lxd.pot, po/nb_NO.po, po/nl.po, po/pa.po, po/pl.po, po/pt_BR.po, po/ru.po, po/sr.po, po/sv.po, po/tr.po, po/uk.po, po/zh_Hans.po
Direct calls to Exit() will prevent the global post functions from running, which among other things will prevent the cookie jar from getting saved. This also was preventing a number of defers from ever running, requiring needless code duplication.
=> Don't use Exit() within lxc commands

doc/rest-api.md
Fixed formatting by adding spaces to lines starting with "*" (as that's more commonly used than without) and also fixed header for one `PUT` heading
=> misc(rest-api.md): formatting

lxd/containers_post.go
When Profiles is set to nil, we default to the default profile.
This is normally done by ContainerCreateInternal but in the migration
case we actually need a list of profiles before that's called, so let's
fill it ahead of time.
=> lxd/migration: Fix handling of missing profiles

shared/util_linux_cgo.go
Otherwise you'll change the permissions on /dev/ptmx which is bad...
=> terminal: do not chown master fd

shared/util.go
This should avoid some issues with polling /proc
=> shared: Switch ParseNumberFromFile to simple read

doc/api-extensions.md, lxc/info.go, lxd/util/resources.go, shared/api/resource.go, shared/version/api.go
It's a bit unlikely but not impossible to be on a system with multiple CPUs and have CPU0 offline, which would cause our current socket logic to break down.
Now, we'll be explicit and directly list the socket number in each entry so it's guaranteed to be correct.
=> Add socket number to resources API

shared/idmap/idmapset_linux.go
=> shared/idmap: Use separate uid and gid entries

lxd-p2c/transfer.go
Apparently some systems sometimes return garbage in that path even for
what shouldn't be a deleted file.
In such cases, just use os.Args[0] and hope for the best.
Closes #5555
=> lxd-p2c: Workaround for broken /proc/self/exe

shared/simplestreams/simplestreams.go
Hi,
FWIS current [index.json](https://uk.images.linuxcontainers.org/streams/v1/index.json) file doesn't contain updated attributes so I added `omitempty` to these options.
In additional in current SimpleStreamsIndexStream struct is not present an attribute for `format` (related to value `products:1.0`)
=> simplestreams: Align JSON struct for index.json

doc/containers.md
The current documentation for usage of "creation_date" is unclear for users not familiar with pongo2. In addition the documentation about date formatting with pongo2 out there is minimal.
The explanation of the suffix is just wrong and should be corrected.
=> Update documentation for snapshots.pattern

lxd/main_forkproxy.go
Fixes: https://discuss.linuxcontainers.org/t/lxd-proxy-device-tcp-not-responding/4356/18
Suggested-by: nomi <nomi@click-mail.net>
=> forkproxy: fix epoll

lxd/container.go, lxd/containers_post.go
This is rather ugly as there's no container struct around to pass to the
normal delete functions, but this will hopefully do the trick for now.
Once we get the new internal storage API, we should be able to change
this to returning a lower level storage driver and can then call its
delete function rather than ContainerDelete.
Closes #5597
=> lxd/backups: Attempt to delete storage on failure

lxc/action.go
If a container is already stopped or running skip it so we don't report
useless errors.
=> lxc/action: skip containers with intended state

doc/api-extensions.md, doc/containers.md, lxd/container.go, lxd/container_console.go, lxd/container_exec.go, lxd/container_lxc.go, lxd/container_test.go, lxd/devlxd.go, lxd/migrate_container.go, lxd/storage.go, scripts/bash/lxd-client, shared/container.go, shared/version/api.go
This should properly split the 3 different cases we have for idmap throughout the LXD codebase.
It also renames all our existing functions to have names better matching their use.
This is infrastructure needed for the upcoming shiftfs work.
=> Introduce volatile.idmap.current

client/lxd_containers.go
If the user requests that a container be copied on the same node that it
currently resides on, skip using the migration API and just use the
local copy API instead.
Closes #5613
=> client: Optimize copies on same nodes

doc/storage.md, lxd/storage.go, lxd/storage/quota/projectquota.go, lxd/storage_btrfs.go, lxd/storage_ceph.go, lxd/storage_dir.go, lxd/storage_lvm.go, lxd/storage_zfs.go
With this and an adequately configured block device (non-default), you get a hard quota set which is properly displayed in `df` inside the container as well as proper usage reporting in `lxc info`.
=> Add support for xfs/ext4 project quotas

doc/api-extensions.md, lxd/networks.go, lxd/networks_config.go, scripts/bash/lxd-client
Adds the following network config settings to allow specifying an SNAT source address:
```
ipv4.nat.address
ipv6.nat.address
```
Related to https://github.com/lxc/lxd/issues/5648
=>  Allow setting the NAT source address (SNAT instead of MASQUERADE)

lxd/main_forkproxy.go
Proxy processes currently exit when `epoll_wait` is interrupted, leaving a broken connection that (I think) can only be fixed by restarting the container or removing and re-adding the device. This just handles `EINTR` so the proxy keeps listening.
I reused the body of the `lxc_read_nointr` function in main_forkproxy.go, which did basically the same thing for `read(2)` but didn't seem to be used anywhere (it was introduced in 45be3534).
=> forkproxy: Retry epoll on EINTR

lxd/api_internal.go, lxd/container.go, lxd/container_lxc.go, lxd/main_callhook.go
lxd/container: Moves network limits to be run as a network up hook rather than container start hook
Signed-off-by: tomponline <tomp@tomp.uk>
=> lxd/container: network up hook for network limits

lxd/container_lxc.go
Signed-off-by: tomponline <thomas.parrott@canonical.com>
=> lxd/container: removes unused arg from network limits function

lxc/utils/progress.go
lxc/file: Dynamically shrinks output for long files when using `lxc file pull`
Fixes #5668
Signed-off-by: tomponline <thomas.parrott@canonical.com>
=> lxc/file: Dynamically shrinks output for long files

doc/index.md
Adds ebtables to main install step, and socat to testing step.
Signed-off-by: tomponline <thomas.parrott@canonical.com>
=> doc: Adds missing packages to install guide

lxc/copy.go
=> lxc/copy: Don't strip volatile keys on refresh

lxd/patches.go, lxd/storage_btrfs.go
Ran into some problems when using btrfs combined with shiftfs where we could create read-only snapshots but then not clear the read-only flag nor delete it.
=> lxd/storage/btrfs: Don't make ro snapshots when unpriv

lxd/container_lxc.go
=> lxd/containers: Don't fail on old libseccomp

lxd/container.go
=> lxc/container: Fixes minute rollover issue in scheduled snapshots

doc/containers.md
=> doc: Re-structures container nic docs into each nic type

doc/containers.md
=> doc/containers: Adds IPVLAN required sysctls to docs

lxd/container_lxc.go, test/suites/container_devices_nic_bridged.sh, test/suites/container_devices_nic_p2p.sh
This re-works the previously added static routes feature to add support for bridged nic types.
It uses the volatile config keys to store the previous config so that static routes are cleaned up.
=> network: static routes for bridged nic types

lxd/container_lxc.go, test/suites/container_devices_nic_p2p.sh
This PR modifies the network up hook to run for all p2p/bridged NICs so that the boot time nic host_name can be extracted from LXC and saved into volatile data.
This is then used for post-boot updates to p2p/bridged nics, such as static routes, and network limits.
Also removes unused `getHostInterface` function.
=> network: p2p/bridged static route consistency updates

lxd/storage_btrfs.go
See #5763
During a publish, a *.ro subvolume snapshot copy is made
whilst the original snapshot is set read-write.
If lxd is killed before publish finishes, the *.ro copy
can be left orphaned, and should be deleted when
the associated snapshot is deleted.
=> lxd/storage/btrfs: Delete any orphaned *.ro snapshots

lxd/storage_btrfs.go
This fixes #5804.
The problem was that btrfs send wants a snapshot to be readonly (to prevent
interim modification), but we were not passing the "-r" flag when creating btrfs
subvolume for copying the snapshots of a source container.
=> Pass the -r flag when copying a snapshot backed by a btrfs subvolume

lxd/container_lxc.go, lxd/storage_btrfs.go, test/suites/idmap.sh
This lets LXD shift ro btrfs subvolumes.
When users create subvolumes in btrfs backed containers they can make
them ro. In this case LXD will fail to shift the rootfs. To handle this
case we temporarily make these subvolumes rw, shift them, and make them
ro again.
Closes #5818.
=> idmap: shift ro btrfs subvolumes

lxd/api_internal.go
I just hit this error message and noticed the pool name was inverted here  ;)
=> lxd/internal: Fix backup.Pool.Name check error message

lxd/main_forkdns.go, lxd/networks.go, shared/dnsutil/dnsutil.go
Resolves issue https://github.com/lxc/lxd/issues/5798 that caused DHCP created reverse DNS entries to be returned with the suffix ".__internal" rather than ".lxd".
The original expectation with this PR was that it would be a single line to add forwarding of RDNS zones to the existing forkdns process.
However because the reverse zone name cannot be renamed to something else, unlike the LXD DNS domain, this was not possible.
Instead the following approach was used:
1. Remove the concept of `__internal` zones and make dnsmasq allocate DHCP hostnames to the ".lxd" domain. This makes the behaviour consistent in both clustered and standalone mode.
2. In clustered mode, configure dnsmasq to forward any queries for ".lxd" and FAN RDNS zones that cannot be answered locally to the local forkdns …
=> Fan reverse DNS requests

lxd/daemon.go, lxd/main_forkdns.go, lxd/networks.go, lxd/networks_utils.go, test/main.sh, test/suites/clustering.sh
Ensures that DNS clustered mode is correctly enabled when starting the networks, even if the network is being started as part of LXD init before a cluster has been setup.
This has the effect of starting dnsmasq and forkdns with the correct settings for clustered mode.
It uses the node.ClusterAddress() to indicate an intention for the node to join a cluster at some point in the future.
Fixes #5805
Progress:
=> networks: Maintain DNS clustered mode config during LXD init and node changes

lxd/main_forkdns.go, lxd/main_nsexec.go, lxd/networks.go, test/suites/clustering.sh
Adds double fork to forkdns.
Also adds PID path as first command argument.
=> main_forkdns: Ensures forkdns remains running when LXD exits

lxd/main_forkdns.go
@stgraber  emphasised the use of the usage text when running the program here https://github.com/lxc/lxd/pull/5817#discussion_r291122104
This change restores access to it when running without any arguments.
This PR also removes some unused includes.
=> main_forkdns: Restores usage output text when running with no arguments

doc/containers.md, lxd/api_internal.go, lxd/container.go, lxd/container_lxc.go, lxd/daemon.go, lxd/main_callhook.go, lxd/main_forknet.go, lxd/main_nsexec.go, lxd/networks.go, lxd/networks_utils.go, shared/container.go, test/suites/container_devices_nic_physical.sh
This exposes the `network_phys_macvlan_mtu` support in LXC for setting a boot time custom MTU on `physical` and `macvlan` nic device types and updates tests to expect the MTU to be changed if that feature is present.
It also modifies LXD to restore the MTU and MAC of physical devices if changed by the container's settings or from within the container.
Depends on https://github.com/lxc/lxc/pull/2985
=> network: physical and macvlan nictype MTU support

lxd/main_forkmknod.go
Have forkmknod attach to the mntns when the target is chrooted.
When the target is chrooted we can either go on to diff `/proc/<pid>/cwd`
and `/proc/<pid>/root`, strip what is identical from `/proc/<pid>/cwd`, then
`chroot("/proc/<pid>/root")` and take the remainder of `/proc/<pid>/cwd` to
be relative to the new root or we simply attach to the mnts and chdir to
`/proc/<pid>/cwd`. Guess what's simpler.
=> forkmknod: attach to mntns when task is chrooted

lxd/seccomp.go
According to Arnd there are two scenarios as long as __NR_mknodat is
defined:
1. __NR_mknod is defined too
2. __NR_mknod was never defined on that architecture
Even if tools manually define __NR_mknod it must be defined in the
header for them to do this correctly.
If it isn't in the header the number will be wrong and we might
intercept a wrong syscall.
Suggested-by: Arnd Bergmann <arnd@arndb.de>
=> seccomp: rework missing syscall number definitions

lxd/networks.go, lxd/networks_utils.go, test/suites/container_devices_nic_bridged.sh
networks: Fixes bug preventing 3rd party routes from being restored on network start.
=> networks: Fixes bug preventing 3rd party routes from being restored

lxd/container.go, lxd/container_lxc.go, lxd/main_forkmknod.go, lxd/seccomp.go
When device creation via mknod fails, fallback to messing with mounts.
=> seccomp: retry with mount hotplug

lxc/export.go, test/suites/container_devices_nic_p2p.sh, test/suites/container_devices_nic_physical.sh, test/suites/container_devices_nic_sriov.sh, test/suites/storage_snapshots.sh
Some users after containers that take hours to backup, the one hour expiry would cause them to expire before they've been retrieved. As we immediately call Delete on the backup post-export, the expiry is only needed to handle with crashes/network issues so 24 hours should be fine.
=> lxc/export: Bump expiry to 24 hours

lxd/networks_utils.go
=> networks/utils: Cleaned up the device bind/unbind functions for SR-IOV

lxd/container_lxc.go, lxd/networks.go, lxd/networks_utils.go, test/suites/container_devices_nic_bridged.sh
This PR addresses https://github.com/lxc/lxd/issues/5833 by sending DHCP release packets to dnsmasq when a container is deleted rather than stopping dnsmasq, manually removing the entry from the leases file and restarting dnsmasq.
Progress:
=> Use DHCP Release to remove dnsmasq leases to avoid restarting dnsmasq

lxd/container_lxc.go, shared/containerwriter/container_tar_writer.go
This has been done because the existing logic was difficult to understand,
as implementation details of the tarring, such as requiring a linkMap, were
exposed to the call site; it was also slower than necessary as it would decode
the container's idmap set, even if the call site had already decoded it (it had
in the single place it was being used).
Signed-off-by: Julian Watson <juwa@google.com>
=> Move container taring logic into standalone class

lxc/copy.go
=> lxc/copy: Always strip volatile.last_state.power

lxd/main_daemon.go
This change https://github.com/lxc/lxd/commit/0c51a6574afe002a2ac795f42eff09f78eb9b5ed was upsetting the test runner because of this: 
https://github.com/lxc/lxd/blob/master/test/includes/lxd.sh#L46
Specifically the `"${DEBUG-}"` bit.
=> main/daemon: Fixes test runner by allowing empty command arg

lxd/container_lxc.go, test/suites/container_devices_nic_bridged.sh
One of my earlier attempts to keep the dnsmasq cleanup code together has introduced a bug where the dnsmasq host config file is not removed on container delete.
This PR reverts the original problem commit, adds comments explaining why the ordering is important, and adds a test to ensure it isn't re-introduced in the future.
=> Fixes dnsmasq host file cleanup

lxd/container_lxc.go, test/suites/container_devices_nic_bridged.sh
Previously dnsmasq config was not refreshed when a NIC was added or removed, resulting in static IP config not being applied consistently.
=> Refreshes dnsmasq config on NIC add/remove

lxd/container_lxc.go, lxd/main_forknet.go, test/suites/container_devices_nic_bridged_filtering.sh
Also removes -f from stop command in physical nic tests as not needed.
=> forknet: Cleans up forknet detach error logging and output

lxd/container.go, lxd/container_lxc.go, lxd/networks_utils.go, test/suites/container_devices_nic_bridged_filtering.sh
Adds support for using IP filtering with dynamically allocated IPs.
=> IP Filtering with dynamic IPs

lxd/container_lxc.go, lxd/networks_utils.go
=> networks/utils: Remove unused state.State from networkClearLease()

lxd/container_lxc.go
This now reads from volatile data if not available from kernel.
=> container/lxc: Fixes showing host_name of veth pair in lxc info

lxd/cluster/heartbeat.go
Previously new nodes were not detected if they joined during heartbeat process.
=> cluster/heartbeat: Fixes bug when nodes join during heartbeat

doc/dev-lxd.md
`/var/lib/lxd/devlxd` looks to be the directory containing this socket file while `/var/lib/lxd/devlxd/sock` is the actual bound socket on a system I tested.
=> doc: fix path to host's communication socket

lxd/instance/instance.go
Defines constants for the different instance types (just container currently) and will allow us to expose name, type and other properties to other packages (such as device package).
=> instance: Adds new type instance

lxd/device/device_instance_id.go
This is used by the device implementations to expose a common subset of functions that are implemented by every instance type.
=> device/instance/id: Adds instanceIdentifier interface

lxd/container_lxc.go, lxd/device/device_utils.go, lxd/devices.go, lxd/networks.go, lxd/networks_utils.go
This PR creates a new package called `device` and moves some of the network and device related utility functions into it, as well as updating all existing references to the functions.
Its purpose is to allow these functions to be accessed by the device interface project and other non-main packages.
=> Device Utils

lxd/container_lxc.go, lxd/networks_utils.go
Updates references to use dnsmasq.UpdateStaticEntry() instead
=> networks/utils: Removes networkUpdateStaticContainer

lxd/main_forksyscall.go
=> forksyscall: use correct error handling for chdirchroot()

lxd/task/group.go
=> task/group: Moves wait group Done() after g.running update 

lxd/cluster/gateway.go, lxd/cluster/heartbeat.go, lxd/cluster/membership.go, lxd/daemon.go
This PR changes how the heartbeat members list is generated, it now uses the `nodes` table as the authoritative source of all nodes (and their associated IDs in the map). However it also uses the `raft_nodes` table to detect members by address and mark them as raft members.
Also includes fix from @stgraber in https://github.com/lxc/lxd/pull/5985
=> Cluster heartbeat format change

lxd/container_lxc.go, lxd/main_forksyscall.go, lxd/seccomp.go
This fixes a variety of problems I ran into when testing the following:
```
root@tmp:/var/lib/docker# mkdir a
root@tmp:/var/lib/docker# touch b
root@tmp:/var/lib/docker# setfattr -n user.blah -v y a
root@tmp:/var/lib/docker# setfattr -n user.blah -v y b
root@tmp:/var/lib/docker# setfattr -n trusted.blah -v y a
setfattr: a: Operation not permitted
root@tmp:/var/lib/docker# setfattr -n trusted.blah -v y b
setfattr: b: Operation not permitted
root@tmp:/var/lib/docker# setfattr -n trusted.overlay.opaque -v y a
root@tmp:/var/lib/docker# setfattr -n trusted.overlay.opaque -v y b
```
The output above is the expected one and the one that this branch achieves.
=> Fix setxattr handling

test/suites/clustering.sh
There is a tiny potential race right between a cluster node joins and
the event forwarding being functional. If we immediately get requested
to do cross-node activity (in this case importing an image and creating
a container from it), there is a chance that one or multiple events
won't make it, leading to the client tool hanging (waiting for an event).
This problem should disappear when we rework event distribution to move
away from the current broadcast approach, at which point we can have
individual LXD nodes refuse to serve requests until they are connected
to the event hub.
=> tests: Avoid event forwarding race condition

test/suites/container_devices_nic_sriov.sh
=> test: Ensures SR-IOV tests remove all containers

lxd/seccomp.go
This should fix Centos 7 builds.
Closes #5993
=> lxd/seccomp: Only define Go arch (and include elf)

shared/osarch/architectures.go
These aliases are needed for Funtoo Linux.
=> shared/osarch: Add more aliases

lxd/container_lxc.go
The recent device interface PR #5900 removed detection of disk limit related fields that meant that updates to these would not take effect until container restart.
=> container/lxc: Restores update of disk limit options

test/suites/container_devices_nic_bridged.sh, test/suites/container_devices_nic_bridged_filtering.sh
Now tests can run without udhcpc6 cleanly.
=> test: Fixes bridge tests detection of busybox udhcpc6 presence

lxd/dnsmasq/dnsmasq.go
=> lxd/dnsmasq: Don't fail file deletion if missing

lxd/device/nic_bridged.go, test/suites/container_devices_nic_bridged_filtering.sh
Fixes issue when using IP filtering with a statically assigned IP and a parent device that has no DHCP or IP address assigned.
=> Bridged IP Filtering no parent IP fix

lxd/container_lxc.go, lxd/device/device.go, lxd/device/device_runconfig.go, lxd/device/nic_bridged.go, lxd/device/nic_ipvlan.go, lxd/device/nic_macvlan.go, lxd/device/nic_p2p.go, lxd/device/nic_physical.go, lxd/device/nic_sriov.go, lxd/device/proxy.go, test/suites/container_devices_nic_bridged.sh, test/suites/container_devices_nic_bridged_filtering.sh, test/suites/container_devices_nic_ipvlan.sh, test/suites/container_devices_nic_macvlan.sh, test/suites/container_devices_nic_p2p.sh, test/suites/container_devices_nic_physical.sh, test/suites/container_devices_nic_sriov.sh
This modifies the `device` interface to allow the `Stop()` function to return a `RunConfig` struct, similar to the `Start()` function. 
This allows the `Stop()` function to return a partially populated `RunConfig` struct to communicate with LXD which devices it should detach from the container and how to do it (such as what interface name to use when detaching a NIC back onto the host).
It also allows a slice of functions to be returned in the `PostHooks` variable, which LXD will then execute after the device has been detached.
This also changes when the `Stop()` function is called, it is now executed *before* any devices are detached from a running container, however the `PostHooks` are called after the detaching has been completed.
It also has a nice side-effect of mirroring the …
=> Device post stop hook

test/suites/container_devices_proxy.sh
The file permission on /tmp in the Busybox image on Ubuntu Eoan did not allow global access for all users.
This caused problems when running forkproxy as a non-root UID/GID with UNIX sockets.
This commit sets /tmp inside the container to 1777 before running the UNIX socket tests.
Suggested-By: Stéphane Graber <stgraber@ubuntu.com>
=> test: Fixes proxy device unix tests on Ubuntu Eoan

lxd/device/proxy.go
The common device implementation provides the same behaviour.
=> device/proxy: Removes unnecessary CanHotPlug function

doc/containers.md, lxd/device/proxy.go
The documentation states that the default listen file mode is 0755 if not supplied.
However the mode argument was currently being passed to forkproxy as empty string if not supplied.
There was also no mention of 755 or umask in forkproxy itself, leading me to think the default as documented was not implemented.
After discussions with stgraber, we agreed a sensible default of 0644.
=> device/proxy: Implements default listen file mode of 0644

lxd/device/nic_sriov.go
When testing on mellanox cards, the mac_filtering feature wasn't working when no hwaddr address was specified.
This was because LXD is supposed to set the VF interface's MAC on the parent's VF setting first before enabling spoof checking. However it was using the wrong volatile key.
=> device/nic/sriov: Fixes mac_filtering when no hwaddr specified

lxc/file.go, po/bg.po, po/de.po, po/el.po, po/es.po, po/fa.po, po/fi.po, po/fr.po, po/hi.po, po/id.po, po/it.po, po/ja.po, po/ko.po, po/lxd.pot, po/nb_NO.po, po/nl.po, po/pa.po, po/pl.po, po/pt_BR.po, po/ru.po, po/sr.po, po/sv.po, po/tr.po, po/uk.po, po/zh_Hans.po
So we can indicate that the initial server side handling cannot be canceled.
As soon as the transfer does begin, it is cancelable and ctrl+c will work.
Closes #6062
=> lxc/file: Intercept user cancelation

lxd/logging.go
=> lxd: Check RemoveAll() error properly

lxd/storage_cgo.go, lxd/storage_utils.go
Use the provided unix.MS_LAZYTIME instead of defining the constant
ourselves.
=> lxd: Use unix.MS_LAZYTIME

doc/containers.md, lxd/device/device_utils_network.go, test/suites/container_devices_nic_bridged.sh, test/suites/container_devices_nic_ipvlan.sh, test/suites/container_devices_nic_macvlan.sh
It has come to my attention that there is a feature in LXD bridged NIC devices that will inherit the MTU of the parent device if not overriden using the `mtu` device property.
However it has stopped working in LXD 3.16.
This issue existed in LXD 3.15 (and possibly earlier), but only during hot-plug, as LXD used liblxc's MTU inheritance feature for boot time setup.
However in LXD 3.16 the boot-time and hot-plug device setup code was unified and this bug is now present also during boot-time setup.
=> Bridged device MTU inheritance

lxc/export.go, lxd/backup.go, lxd/container_backup.go, shared/api/container_backup.go
As even our CLI doesn't make much use of that yet, I don't think the field rename is likely to break anyone and should make things a lot less surprising to API users.
=> Fix API inconsistency with backups

lxd/container_lxc.go, lxd/device/device.go, test/suites/container_devices_proxy.sh
Allows devices to be stopped and removed even if their config is invalid.
=> container/lxc: Fixes scenario where invalid device config cannot be fixed

lxc/copy.go
=> lxc/copy: Really always strip volatile.last_state.power

lxd/backup.go
Otherwise the encoded user/group names may differ on target system
leading to a rewrite of uid/gid...
Closes #6097
=> lxd/backup: Call tar with --numeric-ids

lxd/container_lxc.go, lxd/device/device_utils_infiniband.go, lxd/device/device_utils_network.go, lxd/device/infiniband_physical.go, lxd/device/infiniband_sriov.go, lxd/device/nic_sriov.go, test/suites/container_devices_infiniband_physical.sh, test/suites/container_devices_infiniband_sriov.sh
- Updates infiniband device to use resources package for host device discovery
- Moves some SR-IOV code that was shared between nic/sriov and infiniband/sriov devices into nic/sriov device, as no longer needed by infiniband/sriov
- Removes MAC based tests for infiniband devices as they do not work reliably
- Removes ineffective use of "infiniband" as nictype property in fillNetworkDevice
Includes https://github.com/lxc/lxd/pull/6104
=> Device Infiniband resources package

lxd/container_lxc.go, lxd/dnsmasq/dnsmasq.go, lxd/networks.go, lxd/seccomp.go, shared/util.go
Fixes #6109
- Checks error response from `dnsmasq.GetVersion()`.
- Updates `dnsmasq.GetVersion()` to use the new `shared.RunCommandCLocale()` which runs the `dnsmasq --version` command with a `LANG=C.UTF-8` environment variable to avoid issues when the user is using a different locale that affects version string comparison.
- Updates `shared.RunCommandSplit()` to accept and optional environment variable slice to replace the current environment.
=> dnsmasq version check fix with different locales
