canonical/lxd

client/connection.go
lxc/query.go
lxd/api_metrics.go
lxd/daemon_images.go
lxd/db/instances.go
lxd/db/instances_test.go
lxd/instance.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/instance_utils.go
lxd/locking/lock.go
lxd/network/acl/acl_load.go
lxd/network/driver_bridge.go
lxd/network/driver_ovn.go
lxd/network/network_utils.go
lxd/network/network_utils_sriov.go
lxd/patches.go
lxd/storage/backend_lxd.go
lxd/storage/backend_lxd_patches.go
lxd/storage/drivers/driver_lvm_utils.go
lxd/storage/drivers/volume.go
lxd/storage/s3/miniod/miniod.go
lxd/storage/utils.go

This PR aims to fix an issue that @stgraber is experiencing on his own LXD cluster where requests to the `/1.0/metrics` endpoint are piling up and apparently becoming deadlocked.
This PR makes the following improvements:
- Uses VM non-agent metrics if lxd-agent isn't reachable.
- Pre-allocates slices and maps where possible.
- Reduces DB transactions where possible.
- Cancels DB transactions if client request context is cancelled.
- Adds timeout when acquiring the metrics update lock. So that if there is an ongoing metrics build requests do not pile up if they are coming in too frequently.
- Limits concurrency of instance metrics building to avoid potentially spawning unlimited go routines.
- Fixes an issue in `lxc query` where any failed request was retried in plain mode, rather than …

Metrics: Limits concurrency of instance metrics building to avoid potentially spawning unlimited go routines

---

doc/howto/instances_configure.md
doc/howto/instances_create.md

You can now specify device options when you create an instance.

doc/devices: document device option override at creation

---

lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/migrate_instance.go
lxd/storage/drivers/driver_btrfs_volumes.go
lxd/storage/drivers/driver_zfs_volumes.go
lxd/storage/drivers/utils.go
test/suites/migration.sh

The ZFS and BTRFS storage drivers were already not doing optimised transfers in the final stage of multi-sync mode (just returning nil). Which causes ZFS temporary snapshots to be left behind. So make this invocation type an error, and detect the use of non-optimized transfer mode earlier to avoid using MultiSync=true in the first place.
This then resolves the issue of the temporary snapshots not being cleaned up on the source.
Instead of https://github.com/lxc/lxd/pull/11193
Fixes #11194

Storage: Don't attempt multi-sync mode optimized transfers

---

lxd/device/nic_sriov.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/drivers/qmp/commands.go

Fixes two regressions:
- Fixes macvlan NICs losing connectivity when LXD is reloaded regressed by https://github.com/lxc/lxd/pull/10876
- Fixes multi-queue support for veth and macvlan NICs regressed by https://github.com/lxc/lxd/pull/11075
This PR fixes the issue that `macvlan` NICs lose connectivity when LXD is reloaded by switching to using `monitor.SendFile()` rather than `monitor.SendFileWithFDSet()`, as there appears to be some rather strange behaviour going on with QEMU when used with macvtap NICs.
If you pass the macvtap file handles using `monitor.SendFileWithFDSet()` it will use a separate FD set for each file handle. This works fine, and I can see the correct file handles opened by the QEMU process. But when LXD is restarted (the monitor connection is closed), the file handles …

VM: Fix `macvlan` NICs losing connectivity when LXD is reloaded

---

lxd/migrate_instance.go
lxd/storage/drivers/driver_ceph_volumes.go

This brings ceph storage driver in-line with the behaviour of zfs and btrfs storage drivers that do not expect a multi-stage sync when doing an optimized migration.

Storage: Don't expect multi-sync for live optimized ceph migration

---

lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/drivers/qmp/commands.go

Rather than using workaround added in https://github.com/lxc/lxd/pull/8793 which required handling the RESET event and then racing the guest to shut it down and restart it from LXD.
This restores the original behaviour we had originally with the `-no-reboot` but using the QMP `set-action` command added in QEMU 6.0.
This allows us to both workaround the QMP `device_add` boot-order bug by resetting the system after adding the devices, yet still set the `reboot` action to `shutdown` afterwards to allow us to more cleanly handled guest initiated reboots.
This PR also includes a change to ignore mount in-use errors when trying to unmount the instance's root disk on stop.
This is because it is possible for another user request to being using the mount as the instance is stopped, and the mount …

Instance: Handle VM guest initiated reboot via SHUTDOWN event

---

lxd/storage/drivers/driver_ceph_utils.go

When working with a slow but fonctional Ceph cluster, the 10s timeout causes a lot of issues as it interrupts the kernel part way through the map operation resulting in a bad state that requires a full reboot to clear.

lxd/storage/ceph: Increase OSD map timeout to 30s

---

lxd/instance/drivers/qmp/errors.go
lxd/instance/drivers/qmp/monitor.go

Instance: Don't mask unexpected VM monitor QMP response errors with sentinel

---

lxd/db/db_internal_test.go
lxd/db/images.go
lxd/images.go
lxd/instance/instance_utils.go
lxd/storage_volumes.go
lxd/util/http.go

Following on from https://github.com/lxc/lxd/pull/11217 as part of https://github.com/lxc/lxd/pull/11180 we need to load image profiles before running the placement scriptlet.
In order to do this properly and efficiently we should do it in as few DB transactions as possible, and in order to achieve this, a refactor of several of the image management functions was required to work within an existing transaction.
This has also presented the opportunity to introduce context support to these functions for proper cancellation as well.

Images: Update database functions to use transactions

---

lxd/instance/drivers/driver_qemu.go

The PR https://github.com/lxc/lxd/pull/11147 in LXD 5.9 introduced a change that meant that the `checkFeatures()` QEMU invocation was required to return a non-nil error in order for LXD to consider VMs supported at all on the host.
https://github.com/lxc/lxd/pull/11147/files#diff-87040b4a9b898c058e0f889f869c7a0448135f0a7f02db851824f48290c3a2f5R6428
This exposed a long standing bug in the specific qemu invocation being used, which was the use of the `-bios` flag which is only needed on UEFI platforms (LXD's normal qemu invocation only uses this flag on UEFI platforms).
This caused the following error:
```
qemu-system-s390x: could not find stage1 bootloader
```
The feature check functionality had not been working on s390x since it was introduced in …

Instance: Fix VM support and feature detection on s390x and ppc64le

---

.sphinx/conf.py
.sphinx/requirements.txt

Docutils <0.18 is incompatible with the latest version of Sphinx. Sphinx 6.0.0 does not include jquery by default anymore, so need to add an extension for it.

doc: fix version conflicts for doc tools

---

lxd-migrate/main_migrate.go

This changes the usage string to clarify that lxd-migrate is an
interactive tool, and doesn't use positional arguments.
Resolves #11231.

lxd-migrate: Fix usage string

---

lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/storage/backend_lxd.go
lxd/storage/drivers/driver_zfs.go
lxd/storage/s3/miniod/miniod.go

Reported from https://discuss.linuxcontainers.org/t/lxd-init-error-message-when-zfs-storage-pool-cannot-be-created-could-be-more-descriptive/15733

Storage: Improve error when existing zpool isn't empty

---

lxd/storage/drivers/driver_btrfs_utils.go
lxd/storage/s3/miniod/miniod.go

Fixes #11210
Reproduced and tested working on `images:alpine/edge` which has BRRFS 6.1.1

Storage: Fix BTRFS driver `getQGroup` to suport BTRFS >= 6.0.1

---

go.mod
go.sum
lxd/db/query/dump.go
lxd/db/query/dump_test.go
lxd/db/warnings.go

Fixes #11205 and adds some additional changes to try and better align with the output format of `sqlite3 .dump`.

lxd: Fix escaping of `lxd sql .dump` command

---

lxd/instance/drivers/driver_qemu.go
lxd/instance/drivers/driver_qemu_config_test.go
lxd/instance/drivers/driver_qemu_templates.go

- Fixes detection on aarch64 (fixes #11254).
- Switches to integer architecture constants for config architecture logic.
Tested working in custom sideloaded build of snap package on:

Instance: Fix VM QEMU feature detection on aarch64

---

lxd/api_cluster.go
lxd/db/node.go
lxd/db/node_test.go
lxd/instances_post.go

This is part of the work to accommodate providing candidate members list to the instance placement scriptlet (https://github.com/lxc/lxd/pull/11180).
Also enables the cluster notification header when forwarding an instance creation request to another cluster member, which allows for avoiding running certain checks (and thus DB queries) again on the target member.

Instance: Split cluster member targeting logic to generate candidate members list before selecting least used

---

lxd/db/instances.go

Today I noticed that snapshot names when doing `lxc info <instance name>` are only sorted by _date_ which does not include the timestamp as well. This is quite annoying as then it reverts back to alphabetical when a snapshot has the same date as another. Im currently using `5.0` as well. Any chance this can be backported too? Not sure whats required for that
```
$ lxd sql global "SELECT instances_snapshots.name, instances_snapshots.creation_date
FROM instances_snapshots
JOIN instances ON instances.id = instances_snapshots.instance_id
JOIN projects ON projects.id = instances.project_id
WHERE instances.name='instance name' ORDER BY date(instances_snapshots.creation_date)"
+----------------------------+--------------------------------+
|            name            |         creation_date …
```

lxd/db: Changed snapshot sort from date to datetime

---

lxd/api_cluster.go
lxd/db/node.go
lxd/db/node_test.go
lxd/instance/instance_utils.go
lxd/instance_post.go
lxd/instances_post.go
lxd/project/permissions.go
lxd/project/permissions_test.go
test/suites/clustering.sh

In a restricted project new instances can no longer be targeted at specific cluster members that do not exist in the `restricted.cluster.groups` setting (if set). However if it is not set or is empty, then all cluster members are allowed.
This also changes the behaviour of an empty/unset `restricted.cluster.groups` setting when using cluster group targeting. Previously it would have prevented the use of any targeted cluster groups in a restricted project. 
Now if the setting is empty all cluster groups can be targeted.
Also continues work to reduce unnecessary queries and transactions within the instances_post API endpoint by removing the use of `ResolveTarget` (which would then load all the member info again).
Fixes #11263

Instance: Don't allow manual targeting of a member outside of the allowed groups of a restricted project

---

doc/cloud-init.md

Upstream changed their doc site links.

doc: Fix broken cloud-init doc links

---

lxd/api_cluster.go
lxd/db/network_zones.go
lxd/db/node.go
lxd/db/node_test.go
lxd/instance/instance_utils.go
lxd/instance_post.go
lxd/instances_post.go
lxd/network/zone/reverse.go
lxd/network/zone/zone.go
lxd/network_zones.go
lxd/project/permissions.go
lxd/project/permissions_test.go
test/suites/clustering.sh

Backports https://github.com/lxc/lxd/pull/11264 to stable-5.0.
Also fixes clustering groups test failures by modifying use of `tx.ClusterGroupExists`
Also backports parts (non user facing changes) of https://github.com/lxc/lxd/pull/11160 to aid with future maintenance.

Instance: Don't allow manual targeting of a member outside of the allowed groups of a restricted project (stable-5.0)

---

lxc/info.go
lxd/db/instances.go
lxd/db/storage_volumes.go

Order instance and custom volume snapshots in creation order (oldest first).
Continues changes started in https://github.com/lxc/lxd/pull/11271 and fixes snapshot ordering in `lxc info <instance>` described within that PR.

lxd: Use consistent snapshot ordering in API and `lxc info` output

---

doc/api-extensions.md
lxd/device/device_utils_network.go
lxd/device/nic.go
lxd/device/nic_bridged.go
lxd/device/nic_p2p.go
lxd/device/nic_routed.go
lxd/ip/link.go
lxd/network/network_utils.go
shared/version/api.go
test/suites/container_devices_nic_bridged.sh

Add possibility to change txqueuelen on veth devices using `lxc config device set c1 eth0 txqueuelen=100`
fix lxc#11198
Signed-off-by: Viktor Iakovchuk <viktor@yakovchuk.net>

lxd Add support for setting txqueuelen on veth based NICs

---

lxd/instance/drivers/driver_lxc.go
lxd/migrate_instance.go
lxd/migration/utils.go

Signed-off-by: kayos@tcp.direct <kayos@tcp.direct>

lxc/migrate: Make live migration error message more helpful

---

shared/osarch/architectures.go

Debian's mips architectures are reported as "mipsle" and "mips64le". Add them to the list of architecture aliases, otherwise we get an error like:
```
panic: Architecture isn't supported: mips64le
goroutine 1 [running]:
github.com/lxc/lxd/shared/version.getUserAgent()
github.com/lxc/lxd/shared/version/useragent.go:22 +0x72c
github.com/lxc/lxd/shared/version.init()
github.com/lxc/lxd/shared/version/useragent.go:15 +0x38
```

Add mipsle and mips64le architecture aliases

---

lxd/cluster/member_state.go

Cluster: Fix TotalRAM field in MemberState output

---

lxd/instance/drivers/driver_lxc.go

Instance: Comment typo and spacing

---

shared/util.go

shared/util: Update RunCommandCLocale to pass LANGUAGE=en env var

---

lxd/storage/drivers/driver_ceph.go
lxd/storage/drivers/driver_ceph_volumes.go
lxd/storage/drivers/driver_lvm.go
lxd/storage/drivers/driver_lvm_volumes.go
lxd/storage/drivers/utils.go

This drops the `{lvm,ceph}AllowedFilesystems` variables in favor of
`blockBackedAllowedFilesystems`.

drivers: Unify allowed filesystems variable

---

lxd/device/nic_macvlan.go
lxd/ip/link.go

Previously IPv6 for `macvlan` NICs on VMs only (coincidentally) worked for SLAAC addresses.
This is because the host interface still had IPv6 enabled and so was generating its own link-local address which was in the
same multicast group required for SLAAC address NDP operation.
However if the guest used a non-SLAAC address (static or DHCPv6 stateful) because the host interface did not know about this the NDP solication didn't work and the address was unreachable.
This disables IPv6 on the host-side to ensure there are no IPv6 addresses at all on the host interface, and instead enables all multicast processing to allow the guest to configure any IP it wants.
This aligns with the macvlan behaviour for containers, where because we pass the host interface directly into the container, any …

Device: Allow all multicast to fix IPv6 NDP for `macvlan` NICs in VMs

---

lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/storage/backend_lxd.go

This is to aid in resource tracking in LXD cloud and reduce the number of requests required to align storage volumes with instances when they are being attached.

Adds location to event context on instance and local storage volume creation

---

lxd/device/device_utils_disk.go
lxd/device/device_utils_unix.go
lxd/device/disk.go
lxd/instance/drivers/driver_qemu.go
lxd/storage/drivers/driver_btrfs.go
lxd/storage/drivers/driver_ceph_volumes.go
lxd/storage/drivers/driver_lvm_volumes.go
lxd/storage/drivers/utils.go
lxd/storage/filesystem/fs.go

- Fixes separator character from `-` to `,` of `raw.mount.options` setting.
- Updates `DiskMount` to separate mount flags from mount options when calling the `mount` syscall.
- Removes redundant `readonly` argument to `DiskMount`, and instead expects callers to use the existing `mountOptions` argument. 
Fixes #11303

Device: Fix `disk` device `raw.mount.options` setting

---

test/suites/container_devices_disk.sh

Follows on from https://github.com/lxc/lxd/pull/11315
Previously this test was only check for mount options support.

Device: Update `disk` device tests to check for mount flag support in raw mount.options

---

client/connection.go
client/lxd.go
client/lxd_instances.go
client/util.go

On this [PR](https://github.com/lxc/lxd/pull/11318) I added a way to wrap the http transport of the http client.
I only noticed later that there were 2 places where the http client transport was cast to `*http.Transport`.
This PR adds a func to get the http transport, with or without the wrapper.
Signed-off-by: Sebastiao Pamplona <sebastiaodsrp@gmail.com>

client: fix cast to http.Transport when using TransportWrapper

---

doc/metrics.md

Since each cluster member will report metrics of the instances running on itself, Prometheus can simply scrape every members without having to use a query parameter (`?target=<member-name>`)

doc/metrics: greatly simplify the cluster's scrape_configs

---

lxd/backup/backup_info.go

Signed-off-by: Gabriel Mougard <gabriel.mougard@gmail.com>
Fixes: #11211

lxd/backup: update the error msg when "backup/index.yaml" can't be found

---

lxd/storage/drivers/driver_btrfs_utils.go

In addition to https://github.com/lxc/lxd/pull/11252 BTRFS tooling has also changed the number of columns in `btrfs qgroup show` output:
Previously we expected 4 columns, but in btrfs-progs >= 6.0 this has changed to 5 columns.
E.g. in Jammy btrfs-progs v5.16.2:
```
sudo btrfs qgroup show /var/lib/lxd/storage-pools/btrfs
qgroupid         rfer         excl
--------         ----         ----
0/5          16.00KiB     16.00KiB
0/256         9.66MiB    400.00KiB
0/257         9.66MiB    392.00KiB
```
And in Lunar btrfs-progs v6.1.3:
```
btrfs qgroup show /var/lib/lxd/storage-pools/btrfs
Qgroupid    Referenced    Exclusive   Path
--------    ----------    ---------   ----
0/5           16.00KiB     16.00KiB   <toplevel>
0/256          9.63MiB    400.00KiB …
```

Storage: Only check for minimum number of columns in `btrfs qgroup show` command

---

lxd/include/macro.h
lxd/include/mount_utils.h
lxd/include/syscall_numbers.h
lxd/include/syscall_wrappers.h
lxd/instance/drivers/driver_lxc.go
lxd/instance/instance_interface.go
lxd/main_forkmount.go
lxd/main_forksyscall.go
lxd/seccomp/seccomp.go
shared/idmap/shift_linux.go

For centuries we've worked ourselves to the bone with mount propagation
to hotplug mounts. No more! The new mount api does have proper support
for moving a mount into a container. I've had that on my ToDo for a
while but due to recent events this has been bumped up on my priority
list.
So here it is. A way to simply have LXD prepare a mount with exactly the
options we want and then to hand that fd to the container and the
container can just attach it to the correct place. No more pointless
mount propagation shenaningans.
I would also like to call out that this has some elegant properties. For
example, every filesystem that supports idmapped mounts can be exposed
to a container completely idmapped. The filesystem can be directly
created with the idmap applied. Neither does the filesystem …

lxd: hotplug mounts

---

doc/explanation/clustering.md
lxd/api_cluster.go
lxd/api_internal.go
lxd/cluster/gateway.go
lxd/instances_post.go
lxd/scriptlet/instance_placement.go
lxd/scriptlet/starlark.go
lxd/scriptlet/starlark_test.go
shared/api/scriptlet/instance.go
test/suites/clustering_instance_placement_scriptlet.sh

- Adds new `shared/api/scriptlet.InstancePlacement` struct that embeds `api.InstancesPost` and adds `Reason` and `Project` fields. This allows the instance's project to be passed to the scriptlet.
- Updated https://discuss.linuxcontainers.org/t/lxd-scriptlet-based-instance-placement-scheduler/15728
- Integrates improvements and fixes to `StarlarkMarshal` from https://github.com/lxc/lxd/pull/11326
- Fixes multi-level embedded structs in `StarlarkMarshal`.

Instance: Updates instance_placement scriptlet function to accept both project and reason as part of `request`

---

lxd/db/cluster.go
lxd/db/network_zones.go
lxd/db/patches.go

This also happens to workaround a temporary dqlite regression.

lxd/db: Remove needless semi-colons in queries

---

lxd/apparmor/instance_forkproxy.go

forkproxy loads dynamic libraries that use
/var/lib/snapd/hostfs/run/systemd/resolve/stub-resolv.conf /sys/devices/virtual/dmi/id/product_uuid
/etc/machine-id
Let's allow access to resolv.conf and machine-id
and deny access to product_uuid
fix #11241
Signed-off-by: Viktor Iakovchuk <viktor@yakovchuk.net>

lxd/apparmor: fix AppArmor forkproxy profile

---

lxd/db/images.go
lxd/images.go
test/suites/image.sh

Fixes #11355 
And uses fewer transactions and queries.

Images: Only remove cached image files & volumes when image is expired in all projects that use it

---

lxd/db/cluster/schema.go
lxd/db/cluster/update.go
lxd/network_zones_records.go
test/suites/network_zone.sh

Fixes #11364 
This PR fixes 2 bugs:
- Allows management of zone records in non-default project zones.
- Updates the `networks_zones_records` unique index to fix an issue that prevented creating records of the same name in different zones.

Network: Allow management of zone records in non-default project zones

---

test/suites/basic.sh
test/suites/container_syscall_interception.sh

Let's check the seccomp state in `/proc/self/status` and if it has non-zero value then skip seccomp-related tests.

tests: make it work when seccomp is enabled externally

---

doc/howto/images_copy.md
doc/howto/images_create.md
doc/howto/images_manage.md
doc/howto/images_profiles.md
doc/howto/images_remote.md
doc/howto/initialize.md
doc/howto/storage_volumes.md
doc/image-handling.md
doc/images.md
doc/instances.md
doc/operation.md
doc/reference/image_format.md
doc/reference/remote_image_servers.md

Clean up the Images section - part of the content that is in there at the moment doesn't belong there, and a lot of instructional content is missing.
This PR adds this content, partly moving it over from the Getting Started and Advanced Guide on the website, partly adding new content.

doc: Images section

---

lxd/db/network_forwards.go
lxd/db/network_load_balancers.go
lxd/network/driver_bridge.go
lxd/network/driver_common.go
lxd/network/driver_ovn.go

Something I noticed whilst advising @gabrielmougard on how to approach #11332
Detects network forward & load balancer listen address conflicts between OVN networks and those defined on a bridge uplink network.
E.g. this is now prevented:
```
lxc network forward create lxdbr0 10.0.0.1
lxc network forward create ovn1 10.0.0.1 # Where ovn1 network uses lxdbr0 for uplink.
Error: Failed creating forward: Forward listen address "10.0.0.1/32" overlaps with another network or NIC
```
Associated tests https://github.com/lxc/lxc-ci/pull/709

Network: Improve network forward and load balancer conflict validation between networks

---

client/lxd_containers.go
client/lxd_instances.go
lxd/instance/drivers/driver_common.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/instance_interface.go
lxd/instance_snapshot.go
lxd/instances_post.go
lxd/main_forkmigrate.go
lxd/migrate.go
lxd/migrate_instance.go
lxd/migrate_storage_volumes.go
lxd/operations.go
lxd/storage/drivers/generic_vfs.go
test/suites/migration.sh

For very, very limited definitions of "working".
Using CRIU v1.17.1 (same as LXD snap uses) on Jammy, this is about all I could get working:
```
lxc launch images:busybox/1.34.1 c1 -c raw.lxc=lxc.console.path=none
lxc stop c1 --stateful
lxc start c1
```
Did also manage to get working migration and stateful snapshots.

Instance: Get CRIU working again

---

lxd/api_metrics.go
lxd/instance/drivers/driver_lxc.go

The commit https://github.com/lxc/lxd/commit/ba24d18dcba4fca6f55f264ef5d9bf3fafd2e1be introduced an optimisation that avoided the need to initialize liblxc in order to ascertain the container's state during a running start/stop operation.
This aligned LXC driver behaviour with the QEMU driver, by inferring the instance's state by the presence of an ongoing operation.
Unfortunately this change has had the unintended consequence of causing panics in LXD when instance metrics are collected during an instance stop operation.
```
Feb 18 03:52:56 abydos lxd.daemon[1380579]: panic: runtime error: invalid memory address or nil pointer dereference
Feb 18 03:52:56 abydos lxd.daemon[1380579]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1222382]
Feb 18 03:52:56 abydos …
```

Instance: Fix panic if metric collection occurs during stop operation

---

doc/explanation/clustering.md
lxd/scriptlet/starlark.go

Fixes unpredictable ordering of Starlark dict keys.
https://jenkins.linuxcontainers.org/job/lxd-github-pull-test/8930/arch=arm64,backend=dir,compiler=golang-tip,section=standalone/console#console-section-3

Scriptlet: Fixes unpredictable ordering of Starlark dict keys

---

lxd-agent/devlxd.go

Instead of failing immediately, retry getting the vsock client.
Fixes #11381

lxd-agent: Retry getting vsock client

---

lxd/storage/drivers/driver_zfs.go

zfs defaults to using `atime=on` and `relatime=off` and man 7 zfsprops:
> relatime=on|off
>   Controls the manner in which the access time is updated when atime=on is set.
To align with other FSes, we want `relatime=on`. By not forcing `atime` to on, we
get the `relatime` behavior and we also allow an admin to disable the feature by
setting `atime=off` on the dataset itself or on a parent.
This also fixes commit d3e3b3df775f989a6f

lxd/storage/drivers/zfs: don't force atime to on

---

lxd/device/none.go
lxd/storage/backend_lxd.go

Also allow the `none` device type to be "hot plugged" into a running VM.

Storage: Only activate & mount VM config volume when updating backup.yaml

---

lxd-agent/network.go
lxd/device/device_utils_network.go
lxd/device/infiniband_physical.go
lxd/device/infiniband_sriov.go
lxd/device/nic_macvlan.go
lxd/device/nic_physical.go
lxd/ip/link.go
lxd/ip/link_veth.go
lxd/network/driver_bridge.go
lxd/network/driver_ovn.go
lxd/network/driver_physical.go
lxd/network/openvswitch/ovs.go

Hopefully fixes https://bugs.launchpad.net/lxd/+bug/1991552
I suspect the problem is the change to systemd-networkd that adds a default link policy of:
`MACAddressPolicy=persistent`
Which would apply to new veth interfaces created.
See:
https://bugzilla.suse.com/show_bug.cgi?id=1136600
https://github.com/systemd/systemd/issues/25555
https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/merge_requests/15#note_162509
https://github.com/moby/libnetwork/pull/2380
Specifically the last one was key:
> We set the address before udev gets to the networking rules, so udev
sees /sys/devices/virtual/net/docker0/addr_assign_type = 3
(NET_ADDR_SET). This means there's no need to assign a different
address and everything is fine.
This got me thinking that if we can set the MAC address at the …

Network: Update ip.Link to support applying settings atomically when adding interfaces

---

lxd/storage/drivers/utils_ceph.go

This is needed to fix LXD VMs on MicroCeph.

lxd/storage/drivers: Match ceph keyring lookup logic

---

.sphinx/conf.py
.sphinx/requirements.txt

This extension adds a button to each code block that makes it easy to copy the contents.

doc: add sphinx-copybutton extension

---

doc/doc-cheat-sheet.md
doc/explanation/clustering.md

Seems an update to the myst-parser broke how automatic anchors can be used. We hardly use them anyway though, so this shouldn't affect us much.

doc: fix documentation warnings

---

lxd/api_internal.go
lxd/instance/drivers/driver_qemu.go
lxd/instance_put.go
test/main.sh
test/suites/backup.sh
test/suites/snapshots.sh

This PR causes an instance's `volatile.uuid` key to be regenerated upon snapshot restore and backup import.
The `volatile.uuid` key is then used for VM instances as its generation ID.
In this way the VM's generation ID will change whenever the VM's place in time moves backwards.
This allows for the VM guest OS to reinitialize any state it needs to avoid duplicating potential state that has already occurred.

Instance: Add support for VM generation ID

---

lxd/storage/drivers/driver_zfs.go

@stgraber not sure if the version detection shouldn't be dropped altogether since < 0.8.0 is no longer support.

lxd/storage/drivers/zfs: remove redundant ZFS version detection

---

.sphinx/.wordlist.txt
.sphinx/conf.py
doc/cloud-init.md
doc/reference/devices_disk.md
doc/reference/instance_options.md

Cleanup of the existing docs.
The first two commits move around existing content and do **not** contain content changes. :wink:

Clean up cloud-init docs

---

doc/authentication.md
doc/debugging.md
doc/faq.md
doc/howto/initialize.md
doc/howto/network_acls.md

Also, provide the path to the client config/cert for snap users in other doc files.

doc/faq: add a section explaining where lxc stores its config

---

.github/workflows/tests.yml

This cancels running tests when a change is pushed to the branch (which retriggers the tests anyway) - this definitely makes sense for the documentation checks, but I don't know for sure about the other tests. I don't really see why we wouldn't want it there though.
Also, should we add the same for the builds?

GitHub actions: cancel running tests

---

test/includes/clustering.sh

This brings LVM inline with other storage driver tests. And tries to avoid the "data volume group not empty" errors.

test: Use per-instance storage pool VG for clustering tests

---

lxd/storage/drivers/driver_ceph_volumes.go
lxd/storage/drivers/driver_common.go
lxd/storage/drivers/driver_lvm.go
lxd/storage/drivers/driver_zfs_volumes.go

This fixes an issue where recent writes to an in-use (mounted) ZFS block mode filesystem volume were not being reflected in the copies made of the volume if the copy was made immediately after a write.
It was initially thought that is only occurred when the instance was stopped and a recent offline file operation (such as `lxc file push`) had been performed, which had left a temporary lingering mount active (by design), and so the recent write had not yet been flushed to the underlying zvol, and thus was not included in the snapshot used for the copy.
However further testing using this script showed that it also affected running instances:
```bash
lxc storage create zfs1 foo1 volume.zfs.block_mode=true volume.block.filesystem=xfs
lxc init images:alpine/3.17 c1 -s foo1
lxc start c1
echo …
```

Storage: Sync and freeze in-use ZFS block mode filesystem volumes during consistent copy

---

test/suites/clustering.sh

This might avoid the evacuation hangs when triggering a shutdown and then stopping 5s later, as this seems to cause a race somewhere in liblxc. Maybe stopping forcefully sooner works around it until it can be fixed.

test: Shorten boot.host_shutdown_timeout in clustering_evacuation tests

---

lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/migrate.go
lxd/migrate_instance.go

This is done in a way that is backward compatible with older clients (by not waiting forever for a confirmation receipt).
I needed this as part of my live VM migration work as I noticed that migration errors were randomly being masked by disconnection errors. This has been a long term issue and was not introduced by the recent changes in:
https://github.com/lxc/lxd/pull/11440
https://github.com/lxc/lxd/pull/11414

Instance: Don't mask source errors with disconnection error by adding synchronisation of receipt of control message

---

lxd/instances_get.go

Passing a pointer to the loop iterator variable meant that the resulting instance actually appended was non-deterministic. This resulted in missing entries and duplicated entries in the instance list.

API: Fix clustered instances list

---

lxd/devices.go

Use InitPID rather than IsRunning because this task is triggered during the container's onStart hook, which is during the time that the start lock is held, which causes IsRunning to return false.
This is an alternative approach than #11463 that avoids introducing new methods to the Instance interface, and avoids exposing further status complexity to the wider LXD.
Fixes #11462
Closes #11463

lxd/devices: Updates deviceTaskBalance to check the container's InitPID as running indicator

---

doc/api-extensions.md
doc/reference/instance_options.md
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/instance_utils.go
lxd/instance_put.go
shared/instance.go
shared/version/api.go
test/suites/backup.sh
test/suites/snapshots.sh

closes #11449 
- [**READY FOR REVIEW**] The instance volatile.uuid key should remain unchanged during snapshot and backup restores (effectively reverting https://github.com/lxc/lxd/pull/11385). It should also remain unchanged when moved between servers. However it should change when a new instance is created by copying and existing instance (or snapshot). This should be existing behaviour and require no code changes. But worth checking.
- [**READY FOR REVIEW**] A new instance key called `volatile.uuid.vmgenid` should be added. This should be set to the same value as volatile.uuid at instance creation time (instance.CreateInternal) and should also be populated if not populated to the same value as volatile.uuid during qemu.Start().
- [**READY FOR REVIEW**] Whenever the `volatile.uuid` key …

instance: Add Generation ID support for Virtual Machines

---

client/lxd_containers.go
client/lxd_instances.go
go.mod
lxc-to-lxd/utils.go
lxd-agent/exec.go
lxd-migrate/utils.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/instance_interface.go
lxd/instance_console.go
lxd/instance_exec.go
lxd/instances_post.go
lxd/migrate.go
lxd/migrate_instance.go
lxd/migrate_storage_volumes.go
lxd/storage_volumes.go
shared/api/migration.go

Uses the `errgroup` package combined with the `args.Disconnect` call to coordinate detecting errors in each of the concurrent phases of migration receive. This ensures that all go routines are finished before `MigrateReceive` returns, but that only the first error is returned as to the cause of the failure. Additionally it ensures that each go routines' reverter (if used) is run before the function returns.
Additionally:
- Fixes an unnecessary redirect when creating instances in a cluster.
- Renames DataConn and CriuConn to FilesystemConn and StateConn respectively.
- Adds constants for migration channel secrets and uses them throughout code base (so we can easily see where those concepts are used).

Instance: Fix hang during migration if target member encounters an error

---

lxd/apparmor/instance_qemu.go

Fixing an error that appears during the startup of a vm when lxd uses ceph storage:
```
Error: Failed setting up device via monitor: Failed adding block device for disk device "root": Failed adding block device: error reading conf file /etc/ceph/ceph.conf: No such file or directory
```
Audit log:
```
audit: type=1400 audit(1678041471.655:71): apparmor="DENIED" operation="open" class="file" profile="lxd-adapting-mantis_</var/snap/lxd/common/lxd>" name="/var/snap/microceph/220/conf/ceph.conf" pid=2388 comm="qemu-system-x86" requested_mask="r" denied_mask="r" fsuid=999 ouid=0
```
Related discussion: https://discuss.linuxcontainers.org/t/lxc-launch-ubuntu-22-04-vm-fails-when-lxd-uses-ceph-storage/16580

lxd/apparmor: fix AppArmor instance_qemu profile

---

lxd/network/driver_bridge.go

By defualt, dnsmasq will cache failed queries. Unfortunately, this makes LXD difficult to use when accessing resources behind a VPN.

network: ask dnsmasq not to cache failed queries

---

client/lxd.go
lxd/cluster/gateway.go
lxd/instance_exec.go
lxd/migrate.go
lxd/storage/drivers/driver_btrfs_utils.go
lxd/storage/drivers/driver_ceph_utils.go
lxd/storage/drivers/driver_zfs_utils.go
shared/network.go

- Add read lock to `WebsocketIO.Read()` function as the underlying gorilla websocket package only allows 1 reader at a time.
- Use gorilla websocket's `WriteMessage()` function in `WebsocketIO.Write()` function as this benefits from a fastpath mode.
- Set timeouts in migration push mode to mirror those setup in pull mode.
- Fixes hang in `zfs send` (and potentially other storage drivers) due to Go waiting for socket to become writable sometimes when migration fails on target (even though websocket is closed).

Migration: Socket improvements

---

lxc/config_trust.go

Checks the meaning of the first argument (is remote or not). This allow to determine the method of adding trusted client.
Fixes: #11466

Fix `config trust` command fail when remote is specified

---

shared/simplestreams/products.go

We've now started to publish binary diffs for our VM images too, so let's use those when available.

shared/simplestreams: Add support for disk-kvm.img.vcdiff

---

lxd/api_cluster.go
lxd/api_internal.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/instance_interface.go
lxd/instance_post.go
lxd/instance_snapshot.go
lxd/instances_post.go
lxd/migrate.go
lxd/migrate_instance.go
lxd/migration/migration_volumes.go
lxd/storage/backend_lxd.go
lxd/storage/backend_mock.go
lxd/storage/drivers/driver_ceph_volumes.go
lxd/storage/pool_interface.go

- Pushes instance cluster move on ceph storage pools down into migration subsystem (if the source member is online).
- This lays the groundwork for adding VM live migration support for instance cluster member moves on ceph.
- Prevents rename of instance when doing "live" (currently stateful stop/start) cluster member move.
- Adds support for cleaning up instance mount paths on the source member when doing cluster member move using ceph (previously they were just left behind from what I can see).

Instance: Rework intra-cluster ceph instance move to use migration subsystem

---

lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/instance_interface.go
lxd/instance_post.go
lxd/instance_snapshot.go
lxd/instances_post.go
lxd/migrate.go
lxd/migrate_instance.go
lxd/migrate_storage_volumes.go
lxd/migration_connection.go
lxd/storage_volumes.go
shared/network.go

Rather than using dedicated variables for each type of migration connection, as well as duplicating the associated certificate parsing and connection establishment logic, this PR introduces the concept of a `migrationConn` type that manages the lifecycle of the underlying `websocket.Conn`.
This allows us to stop using a separate variable for the connection itself and any associated "connection established" type variables, and instead store them all in a central `conns` map keyed on the existing `api.Secret*` constants (which are already used exchanging secrets between LXD servers).
This PR also brings the parsing of the push target certificate earlier on in the process, before the operation is created.
Whilst I feel this PR makes the handling of migration connections easier to understand …

Migration: Reworks how migration connections are established and managed

---

doc/api-extensions.md
lxd/apparmor/instance_qemu.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/drivers/qmp/commands.go
lxd/storage/backend_lxd.go
lxd/storage/drivers/driver_ceph.go
lxd/storage/drivers/driver_types.go
shared/version/api.go

This adds support for non-shared live QEMU to QEMU migration utilising the built-in NBD client and server in QEMU.
See https://discuss.linuxcontainers.org/t/lxd-online-vm-live-migration-qemu-to-qemu/16635#add-live-migration-support-for-non-shared-storage-13
Tests:

Migration: Add VM live migration for non-shared storage

---

lxd/storage/drivers/driver_zfs_volumes.go

Something I noticed this morning while working on VM live migration.
Most likely a regression introduced by https://github.com/lxc/lxd/pull/11206 as the logic for deactivating a block volume was only considering block backed filesystem volumes, and not VM or custom block volumes.
Also avoided an unnecessary extra call to ascertain to the block volume's `volmode` which was being done twice.
Finally also introduced a changed discussed with @stgraber yesterday that stops using the ARC cache for VM volume content, as this would lead to double caching both inside the guest OS's filesystem cache and on the host.

Storage: Fix UnmountVolume not deactivating ZFS block devices

---

lxd/instance/drivers/driver_qemu.go
lxd/instance/drivers/qmp/commands.go

- Fixes source QEMU block device cleanup.
- Fixes target QEMU process hang on incoming migration state.

Migration: Fixes VM live migration premature error cleanup process

---

doc/api-extensions.md
doc/reference/devices_nic.md
lxd/device/nic.go
lxd/device/nic_bridged.go
lxd/device/nic_ovn.go
lxd/network/driver_ovn.go
lxd/network/openvswitch/ovn.go
shared/version/api.go

This PR adds support for nesting `ovn` NICs inside another `ovn` NIC.
This allows multiple logical OVN switch ports to be tunneled to an instance using VLAN tagging over a single `ovn` NIC, without having to incur the cost of passing multiple NICs to the instance.
This can be beneficial, for example, if you are running containers inside a virtual machine, and want each container to join the parent OVN network, without having to pass in a NIC per container. 
Instead a single "proper" `ovn` NIC is added to the instance, and then one or more "nested" `ovn` NICs are added that specify the propert `ovn` NIC as its `nested` parent. Each nested NIC also needs to specify which `vlan` ID it will use when tunneling through the parent NIC.
Inside the instance, the admin is required to setup virtual …

Device: Adds nested OVN NIC support

---

lxd/device/device_utils_network.go
lxd/device/nic_ovn.go
lxd/network/network_utils.go
lxd/network/network_utils_sriov.go

Fixes various cleanup issues with the `acceleration=sriov` `ovn` NIC implementation:
- `postStop` expected the VF interface to exist before triggering a cleanup - but it never will for VMs (it needs to be rebound to the host first).
- The representor interface was being stored in `volatile["host_name]` but its more useful to store the VF name so we can use it to rebind it onto the host.
- The representor interface was not being removed from OVN integration bridge.
- Improve handling of VF rebinding to accommodate slow kernel/drivers.
- The VF interface was not being cleaned up on failed starts.

Device: Fix VF and representor interface cleanup when using OVN NIC with `acceleration=sriov`

---

.sphinx/.wordlist.txt
doc/api-extensions.md
doc/reference/devices_nic.md
doc/reference/instance_options.md
doc/rest-api.yaml
go.mod
lxd/device/device_utils_network.go
lxd/device/nic.go
lxd/device/nic_ovn.go
lxd/instance/drivers/driver_qemu.go
lxd/ip/vdpa.go
lxd/resources/network.go
shared/api/resource.go
shared/version/api.go

Support VDPA alongside SR-IOV on OVN NICs

---

lxd/device/nic_ovn.go
lxd/instance/drivers/driver_qemu.go
lxd/network/driver_ovn.go
lxd/network/openvswitch/ovn.go

Since adding support for live QEMU to QEMU VM migrations (https://discuss.linuxcontainers.org/t/lxd-online-vm-live-migration-qemu-to-qemu/16635) `ovn` NICs were breaking when performing live cluster member moves.
This is for 2 reasons:
1. The instance's logical switch port was being removed when the instance was stopped on the source after migration completed.
2. The logical switch port was not having its `requested-chassis` option set to the new chassis.
This PR fixes this by:
1. Storing the LXD server name in the `external-ids` field on device `Start()` so that it can be compared on device `Stop()` and if its no-longer the local server name then logical switch port cleanup is skipped, as it indicates this port has been started on another host.
2. Sets the `request-chassis` port option …

Device: Add support for live VM cluster member move for `ovn` NICs

---

lxd/device/config/devices_sort.go

Just a little improvement I noticed this evening, in case someone creates a nested NIC that is alphabetically before the parent.

Device: Start non-nested OVN NICs before nested OVN NICs

---

lxd/apparmor/network_forkdns.go

lxd uses /proc/pid/cpuset and /var/lib/snapd/hostfs/run/systemd/resolve/stub-resolv.conf so this path is added to AppArmor profile to prevent denials
Audit log:
[Sun Apr 16 11:31:07 2023] audit: type=1400 audit(1681644667.565:47): apparmor="DENIED" operation="open" profile="lxd_forkdns-lxdfan0_</var/snap/lxd/common/lxd>" name="/var/lib/snapd/hostfs/run/systemd/resolve/stub-resolv.conf" pid=3972 comm="lxd.debug" requested_mask="r" denied_mask="r" fsuid=999 ouid=101 [Sun Apr 16 11:31:07 2023] audit: type=1400 audit(1681644667.569:48): apparmor="DENIED" operation="open" profile="lxd_forkdns-lxdfan0_</var/snap/lxd/common/lxd>" name="/proc/3972/cpuset" pid=3972 comm="lxd.debug" requested_mask="r" denied_mask="r" fsuid=999 ouid=999

lxd/apparmor: fix AppArmor forkdnsProfile

---

lxd/storage/backend_lxd.go

Previously all profiles in the instance's project were being included. This avoids an extra DB transaction and queries too, which is valuable given that this function is called during instance start up.
@stgraber does this make sense? To my mind there's no reason to include all profiles from the project in the backup.yaml of every instance? But only the profiles assigned to the instance.

Instance: Only add profiles the instance is using to backup config

---

lxd/instance/drivers/driver_common.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go

closes #11538 
Here is an test script : 
```go
package main
import (
"fmt"
"sync"
"time"
lxd "github.com/lxc/lxd/client"
"github.com/lxc/lxd/shared/api"
)
const LxdSock = "/var/snap/lxd/common/lxd/unix.socket"
func main() {
fmt.Println("Trying to connect to LXD...")
if srv, err := lxd.ConnectLXDUnix(LxdSock, nil); err == nil {
fmt.Println("LXD server connection acquired")
imageServer, err := lxd.ConnectSimpleStreams("https://images.linuxcontainers.org/", nil)
panic(err)
}
fmt.Println("Connected to image server")
alias, _, err := imageServer.GetImageAlias("alpine/3.17/cloud/amd64")
panic(err)
}
fmt.Println("Got image alias")
image, _, err := imageServer.GetImage(alias.Target)
panic(err)
}
fmt.Println("Got image")
req := api.InstancesPost{ …
```

instance: stop API races while creating/deleting snapshots

---

lxd/network/driver_bridge.go

If the network config key {ipv4,ipv6}.ovn.ranges is set, LXD currently checks if these ranges overlap with configured {ipv4,ipv6}.dhcp.ranges. These leads to an erroneous validation of DHCP ranges if dhcp=false.

Network: Skip `bridge` ovn/dhcp range overlap check when DHCP is off

---

lxd/instance/drivers/driver_common.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/instance_utils.go

Fixes regression introduced by https://github.com/lxc/lxd/pull/11586 that prevented deleting VMs with snapshots.
Also adds missing call to `d.updateBackupFileLock` in `Stop` for `lxc` driver to bring in line with `qemu` driver.
This would have flagged up the issue earlier as the jenkins test suite would have failed on the same problem.
Finally, adds an optimisation to avoid updating the backup file as each snapshot is removed as part of an overall instance delete operation, as it is wasteful to potentially update the file multiple times only to then delete it at the end of the instance delete operation.

Instance: Fixes deadlock when deleting a VM that has snapshots 

---

lxd/instance/drivers/driver_qemu.go

What was previously generating a warning from `lxc info v1 --show-log` like:
```
warning: tap: open vhost char device failed: Permission denied
```
Is now causing an assert crash with:
```
warning: tap: open vhost char device failed: Permission denied
qemu-system-x86_64: ../../net/net.c:1106: net_client_init1: Assertion `nc' failed.
```
Disable the vhost-accelerator until we figure out how to work around it by passing FDs.
The likelihood is that given it was unable to open the vhost char device before 7.2 the accelerator wasn't working anyway and this change won't result in any performance regression.
Fixes #11482 
Also reported by https://discuss.linuxcontainers.org/t/failed-adding-nic-netdev-monitor-is-disconnected/15946

Instance: Disable vhost accelerator for veth based NICs in QEMU >= 7.2

---

doc/howto/storage_buckets.md

This is mentioned in the explanation, but should be part of the how to.

doc/storage/buckets: add info on configuring the S3 address

---

doc/howto/storage_backup_volume.md
lxc/export.go

Fixes #11543
With this patch, running `lxc export` without an explicit file name will no longer fallback to the hardcoded file name `backup.tar.gz`. Instead, the backup is named based on the instance name combined with appropriate file extension for the detected compression type for the tarball.

lxc/export: Rename backup file based on compression type

---

lxc-to-lxd/utils.go
lxd-migrate/utils.go
lxd/migrate_storage_volumes.go

@edlerd was experimenting with the migration API and managed to crash LXD by sending a success response without a message.
```
Apr 27 14:40:08 EDLERD-T14 lxd.daemon[592325]: panic: runtime error: invalid memory address or nil pointer dereference
Apr 27 14:40:08 EDLERD-T14 lxd.daemon[592325]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x184e16c]
Apr 27 14:40:08 EDLERD-T14 lxd.daemon[592325]: goroutine 2025 [running]:
Apr 27 14:40:08 EDLERD-T14 lxd.daemon[592325]: main.(*migrationSink).DoStorage(0xc001fde900, 0xc000cc5f20?, {0xc000fd3e77, 0x7}, {0xc000aaa478, 0x5}, 0xc0011aafc0, 0xc0010d9560)
Apr 27 14:40:08 EDLERD-T14 lxd.daemon[592325]: #011/build/lxd/parts/lxd/src/lxd/migrate_storage_volumes.go:477 +0xf8c
Apr 27 14:40:08 EDLERD-T14 lxd.daemon[592325]: …
```

lxd: Use protobuf helpers to avoid panics with invalid client responses

---

client/interfaces.go
client/lxd_storage_volumes.go
client/util.go

Fixes the method (previously failed with "Unexpected URL Path ...") and changes the return type to easily differentiate between resources in different projects.
Closes #11607

Update return type of GetStoragePoolVolumeNamesAllProjects.

---

lxd/db/cluster/certificate_projects.mapper.go
lxd/db/cluster/certificates.mapper.go
lxd/db/cluster/cluster_groups.mapper.go
lxd/db/cluster/config.mapper.go
lxd/db/cluster/devices.mapper.go
lxd/db/cluster/images.mapper.go
lxd/db/cluster/instance_profiles.mapper.go
lxd/db/cluster/instances.mapper.go
lxd/db/cluster/nodes_cluster_groups.mapper.go
lxd/db/cluster/operations.mapper.go
lxd/db/cluster/profiles.mapper.go
lxd/db/cluster/projects.mapper.go
lxd/db/cluster/snapshots.mapper.go
lxd/db/cluster/warnings.mapper.go
lxd/db/generate/README.md
lxd/db/generate/db/lex.go
lxd/db/generate/db/mapping.go
lxd/db/generate/db/method.go
lxd/db/query/marshal.go

@tomponline @stgraber @masnax Following from the chat in IRC I've written this simple implementation of database marshalling/unmarshalling. This allows us to add any type to the database in a TEXT column, the type should implement `query.MarshalDB` and `query.UnmarshalDB`, and should be added to the database type representation with `marshal=true` in the struct tag for the field.
I have implemented this only for the methods it seemed necessary, and only for simple tables (no reference or association tables).
There are no changes to generation for LXD (save for a quick fix on a comment). I'll submit a draft PR for LXD Cloud shortly to show what this looks like in practice.

Generated marshaling/unmarshaling of non-native database types

---

lxd/instance/drivers/driver_common.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/operationlock/operationlock.go
lxd/instance_state.go
lxd/storage/drivers/driver_zfs_volumes.go

Operation locks have previously had an automatic timeout of 30s.
However many of the tasks that used operation locks take an indeterminate amount of time, and so it required the task to periodically reset the operation lock so that it didn't lapse, because if it did, then it would open the door for conflicting tasks to be started whilst the original task was ongoing (which was the purpose of the lock to prevent this).
Most of the instance tasks that use locks are dependent on external factors (such as system load, image size and I/O performance) which varies the time they take, so the automatic timeout concept was not helpful, and in some cases damaging.
Rather than requiring tasks to keep resetting the lock timeout for an operation that takes an unknown amount of time, this PR removes …

Instance: Remove automatic timeout concept from operation locks

---

client/lxd_oidc.go
lxd/auth/oidc/oidc.go

This makes use of the email scope/claim which makes it easier to identify the user.

oidc: Use email scope/claim

---

lxd/api.go
lxd/auth/oidc/oidc.go
lxd/daemon.go

This introduces a few API routes:
- /oidc/login
- /oidc/callback (internal)
- /oidc/logout
And effectively allows someone to navigate to `/oidc/login`, go through the OIDC login flow and then get back to LXD with a valid set of cookies used to authenticate against LXD.
Code changes are relatively minimal on the LXD side, effectively keeping most of it in the OIDC auth package.

Add support for browser OIDC login

---

lxd/daemon.go

This fixes a bug where the client would be unable to refresh the access
token as the server failed to send any OIDC information.

oidc: Always set OIDC headers if needed in case of an error

---

client/lxd_oidc.go
lxd/auth/oidc/oidc.go
lxd/daemon.go
lxd/response/response.go

This changes the behaviour of OIDC in that it only tries to authenticate if the server returns Unauthorized (401). All other errors will be returned immediately.

oidc: Return and handle Unauthorized error

---

lxd/cgroup/abstraction.go
lxd/instance/drivers/driver_lxc.go
lxd/seccomp/seccomp.go

lxd/cgroup: use `cg.GetProcessesUsage` instead of `cg.GetTotalProcesses` and fix error values inconsistency 

---

lxd-agent/api_1.0.go
lxd/endpoints/endpoints.go
lxd/endpoints/vsock.go
lxd/instance/drivers/driver_qemu.go
lxd/vsock/vsock.go

LXD will now always listen on the special "host" vsock context ID, even when nesting (rather than listening on the VM's context ID) which means that it will be reachable from the lxd-agent when nesting as well.

Instance: Fix VM /dev/lxd connections from lxd-agent to LXD on host when nesting

---

lxd/api_cluster.go

This removes the ability to create cluster groups when simply
authenticated. This action should be reserved for admins only.

cluster: Disable cluster group creation by anyone authenticated

---

lxd-agent/devlxd.go
lxd/endpoints/network.go
lxd/endpoints/vsock.go

The VM lxd-agent /dev/lxd service was not working for VMs launched on the first member of a cluster after it had been initially switched to a cluster member after the cluster was created. This is because the vm vsock listener was still using the old server certificate and not the new cluster certificate.
Also fixes same issue for storage buckets and metrics API listeners.

Instance: Fix incorrect vm vsock listener certificate for lxd-agent /dev/lxd when setting up a cluster

---

lxc/config_device.go

System tests for this PR https://github.com/canonical/lxd-cloud/pull/287 are failing because the device map is nil (https://github.com/canonical/lxd-cloud/actions/runs/4893364018/jobs/8736415167?pr=287#step:6:2856). 
This adds a nil check on the profile device map before assignment.

lxc/config_device: Don't panic on nil device map.

---

lxd/certificates.go
test/suites/pki.sh

Up until now, non-admin users could delete certificates other than their
own. This should not be possible, but instead align with what is done
when updating certificates. There, non-admin users can only update their
own certificate.
This ensures that non-admin users can only delete their own certificate.

lxd/certificates: Allow non-admin users to delete only their certificates

---

doc/howto/network_bridge_resolved.md

As raised in https://discuss.linuxcontainers.org/t/integration-with-systemd-resolved-inside-a-vm/16936

doc/bridge/resolved: clarify use of "~"

---

doc/howto/network_zones.md

This PR enhances the documentation by elucidating an undocumented behavior regarding the generation of TSIG key names within network zones. This change aims to prevent confusion and aid in the correct utilization of the feature.
Link to the corresponding code:
https://github.com/lxc/lxd/blob/d4cfed376e76e47bcf4bf8b1e72ce101200fb4bc/lxd/db/network_zones.go#L104

doc: clarify TSIG key name generation for network zones

---

lxd/daemon.go
lxd/endpoints/endpoints.go
lxd/endpoints/listeners/fancytls.go
lxd/endpoints/network.go

This allows these listeners to be bound to a managed network addresses.

Daemon: Start tertiary listeners (storage buckets and metrics) after managed network are initialised

---

doc/rest-api.yaml
lxd/network_zones.go

This renames `name` to `zone` as that's what zone records use as well.

lxd/network_zones: Use `zone` for consistency

---

doc/reference/instance_options.md
lxd/device/nic_ovn.go
lxd/network/driver_ovn.go
lxd/network/network_utils.go
lxd/network/openvswitch/ovn.go
shared/instance.go

This PR introduces the instance volatile key `volatile.<name>.last_state.ip_addresses` which is used to store a comma-separated list of the DNS IPs associated to an OVN NIC port on last start.
This is then provided to the OVN driver when creating the port so that the OVN driver can choose to allocate this IPv4 address to the port if it is still appropriate to use (DHCPv4 is enabled, no static IPs being used and subnet is unchanged) and is available for use (not statically reserved or in use by another instance).
This fixes an issue where, because OVN allocates IPs from the subnet sequentially (unlike dnsmasq), if an instance with an IP lower than another instance is stopped/deleted and then that other instance is rebooted it will be then allocated that lower IP.
Whilst technically …

Network: Add support for sticky DHCPv4 dynamic allocations for `ovn` NICs

---

doc/explanation/security.md
doc/faq.md
doc/howto/network_bridge_firewalld.md
doc/howto/server_expose.md

Clean up the FAQ (mostly adding links to existing content and moving details to the respective doc sections) and add an entry for the common firewall question.

Doc: clean up FAQ

---

lxc/export.go

lxc/export: Fix export rename when run inside snap

---

lxd/api_cluster.go
lxd/storage/drivers/utils.go

When there is nothing to heal.
Fixes https://github.com/lxc/lxd/issues/11702

Cluster: Don't create a cluster heal operation every minute (and cause unnecessary logs) 

---

lxd/daemon.go
lxd/db/storage_volume_snapshots.go
lxd/db/storage_volumes.go
lxd/main_activateifneeded.go
lxd/storage_volumes_snapshot.go

Fixes  #11691
Also merges auto snapshot schedule task and auto prune task into single task to reduce duplicated queries ans transactions and to provide predictable ordering.
Tests:

Storage: Fix cluster and remote pool support for custom volume snapshot expiry

---

doc/howto/network_bridge_firewalld.md
doc/howto/network_ovn_setup.md

Inspired by https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=865975
Thanks to https://discuss.linuxcontainers.org/t/lxd-and-docker-firewall-redux-how-to-deal-with-forward-policy-set-to-drop/9953/17

Doc: Updates bridge docker firewall fixes to include easier forwarding option

---

lxd/storage/drivers/driver_zfs_volumes.go
lxd/storage/drivers/volume.go

VM filesystem volumes should always be ZFS datasets.
Fixes #11403

Storage: Fix VM filesystem volumes incorrectly being created as ZVOLs when zfs.block_mode enabled

---

lxd/api_internal.go
lxd/instances_post.go

Discovered from https://discuss.linuxcontainers.org/t/how-to-recover-a-failed-cluster-node-after-lxc-import/17013/2?u=tomp
`internalImportFromBackup` originally harked from the `lxd import` recovery command (as well as still being used for `lxc import).
However now that we have `lxd recover`, the `internalImportFromBackup` doesn't need to support a `force` option as when we are restoring an instance from a backup we should require that there are no conflicting DB entries before completing.

Instance: Reject import if conflicting DB records found

---

lxd/daemon.go
lxd/instance.go

Aligns with behaviour of custom volume snapshot schedules in https://github.com/lxc/lxd/pull/11701
This reduces the changes of running out of disk space.

Instance: Deleted expired snapshots before creating new scheduled snapshots

---

doc/howto/network_bridge_firewalld.md

Make it clearer that there are three different alternatives for how to prevent issues with LXD and Docker.
(It looks like a lot of changes, but it's really just adding indentation and moving one note around, plus some language nitpicking ;) )

doc/network/bridge: clarify options for using LXD with Docker

---

doc/howto/network_zones.md

This CL adds some documentation aiming to reduce friction of learning
how to set up a zone to serve DNS.
Without this information, it is fairly hard for a newcomer: down below
both peers.NAME.address and peers.NAME.key is marked as optional. The
error messages are also unobvious: it is a simple "Transfer failed" on
the client side, leaving it to the imagination of the reader if it failed
because of authorization issues, or because some other configuration is
missing. There is no server side log about it.

Document how to enable manual testing of zone DNS.

---

lxc/copy.go
lxd/instance.go
lxd/storage/backend_lxd.go
lxd/storage/drivers/driver_btrfs_volumes.go
lxd/storage/drivers/driver_ceph_volumes.go
lxd/storage/drivers/driver_zfs_volumes.go

Fixes #11729 
- Removes some blunt checks that prevented copying running VMs locally (both same pool and cross-pool).
- Updates the "should freeze instance" logic in `CreateInstanceFromCopy` to consider whether the source pool indicates whether the instance should be frozen during copy, rather than consulting the target, which is incorrect during a cross-pool copy.
- Applies the same freezing logic from `CreateInstanceFromCopy` to `RefreshInstance`.
- Incorporates check for raw block transfer mode in `MigrateInstance` into source instance freezing logic, rather that outright banning the migration.
- Switches `CreateInstanceFromCopy` and `RefreshInstance` migration mode to use `errgroup` to simplify and improve the UX so that only the first error is returned to the user rather than a slice …

Instance: Allow copying running VMs (both consistently and inconsistently) locally

---

shared/ws/mirror.go

Allow passing `nil` to `InstanceExecArgs.{Stdin,Stdout,Stderr}`
Reintroducing this fix https://github.com/lxc/lxd/commit/b91a4fa6de83151996c68a68d3f0ca8d139385a9

shared/ws/mirror: Allow passing nil to Exec

---

doc/howto/access_ui.md

The UI is now part of the stable snap, but it must be explicitly enabled.

doc/UI: update instructions for enabling the UI

---

doc/reference/storage_ceph.md
doc/reference/storage_lvm.md
doc/reference/storage_zfs.md
doc/rest-api.md

Add `block.filesystem` and `block.mount_options` to the list of storage volume configuration options.
As mentioned in #10077.

doc/storage/zfs: add missing storage volume configuration

---

lxd/cluster/gateway_test.go
lxd/cluster/heartbeat_test.go
lxd/cluster/membership_test.go
lxd/cluster/upgrade_test.go
lxd/daemon.go

The actual operation (in memory) will be long gone, so lets not leave anything orphaned in the global DB.
Related to #11636

Daemon: Clear left over operations for member during start up

---

lxd/db/images.go
lxd/events/internalListener.go
lxd/instance.go
lxd/instance/operationlock/operationlock.go
lxd/instances_post.go
lxd/locking/lock.go

Avoids checking for local images twice.
Related to #11636

Images: Rework concurrent download locking

---

lxd/instance/drivers/driver_qemu.go

If the guest had panicked it would have shown as STOPPED, but the QEMU process would still be running and not be stoppable using `lxc stop -f`. This PR fixes this by:
1. Instructing QEMU to shutdown when a panic occurs.
2. Reporting unknown statuses (such as panic) as "ERROR" status.
Fixes #11741

Instance: Handle VM panic by shutting down

---

lxd/acme.go
lxd/api_cluster.go
lxd/backup.go
lxd/images.go
lxd/instance.go
lxd/instance_instance_types.go
lxd/instance_post.go
lxd/logging.go
lxd/operations.go
lxd/operations/operations.go
lxd/storage_volumes_snapshot.go
lxd/tokens.go
lxd/warnings.go

Also make task operation logging consistent.
Also fixes various missing returns on earlier errors.
Related to #11636 - as needed to have a way to handle operation errors.

Operations: Refactor op.Wait() to return an error so operation failures can be easily discovered

---

lxd/instance/drivers/driver_qemu.go

Following on from https://github.com/lxc/lxd/pull/11768 I thought it would actually be better for QEMU processes to pause on panic so the issue can be investigated.
The status of the VM won't show as STOPPED, so it can still be force stopped if needed.

Instance: Pause on VM panic

---

doc/faq.md

A likely cause for instance creation to hang is that LXD runs out of space.

doc/faq: add info about hanging instances

---

lxc/alias.go
lxc/cluster.go
lxc/cluster_group.go
lxc/config_template.go
lxc/config_trust.go
lxc/list.go
lxc/network.go
lxc/network_acl.go
lxc/network_forward.go
lxc/network_load_balancer.go
lxc/network_peer.go
lxc/network_zone.go
lxc/operation.go
lxc/profile.go
lxc/project.go
lxc/remote.go
lxc/storage.go
lxc/storage_bucket.go
lxc/storage_volume.go
lxc/utils/sort.go

Rename the sort interface `ByName` into `SortColumnsNaturally` to avoid any confusion regarding its implementation.
Fixes #11645

lxc/utils: Change sort ByName interface name to SortColumnsNaturally

---

lxd/apparmor/qemuimg.go
lxd/storage/utils.go

Ensures when using a not optimized storage driver like `dir`, that the `qemu-img` command isn't executed concurrently if multiple VMs are going the be created at the same time. See https://github.com/lxc/lxd/issues/11244.
Fixes https://github.com/lxc/lxd/issues/11244

lxd/storage: Use a unique apparmor profile for qemu-img unpacking

---

doc/rest-api.yaml
lxd/api_1.0.go
lxd/instance/drivers/driver_common.go
lxd/instance/instance_interface.go
lxd/instance_exec.go
lxd/instance_logs.go
lxd/response/response.go

Store the output of an exec command (when `record-output` is true) in the instance storage instead of the log directory, as instance's storage quota is not applied to the log directory.
Fixes #11643

lxd/instance: Fix exec record-output location

---

lxd/instance_logs.go
lxd/response/response.go

This PR references the remaining comments in #11791:

lxd/instance_logs: Cleanup function call

---

doc/api-extensions.md
doc/rest-api.yaml
lxd/api_1.0.go
shared/api/server.go
shared/version/api.go

This is primarily meant as a way to confirm that the user is authenticating using the method that they think they are.
It's not really needed by LXD usually but it's something that will be useful for the UI as that way it can know whether to offer an option to logout in the case of OIDC.

Introduce auth_user_name and auth_user_method in /1.0

---

lxd/storage/drivers/driver_zfs_utils.go
lxd/storage/drivers/driver_zfs_volumes.go

Read ZFS dataset `atime` property and convert it to appropriate mount flag to ensure `noatime` mount option is set accordingly.
Fixes #11659

lxd/storage/zfs: Fix ZFS does not respect atime=off option

---

lxd/daemon.go
lxd/network/driver_ovn.go
lxd/network/network_utils.go
lxd/operations/operations.go
lxd/storage/utils.go

Fixes #11492
This works around a bug in OVN where in some cases the ARP/NDP neighbour learning of the uplink next-hop address is not triggered for egress traffic from instances.
LXD will try and ping the OVN network's external router IPs from each member, and if they can reach the OVN virtual router then this is sufficient to trigger next-hop neighbour learning inside OVN.
This is not a full solution to the problem, as if the LXD members cannot reach the OVN virtual router (which is a valid configuration) then pings from LXD members will not be able to trigger neighbour learning inside OVN.

Network: Ping OVN virtual router external addresses when using physical uplink network

---

lxc/copy.go

lxc/copy: Don't try and modify volatile.idmap.next on refresh if not set in source

---

doc/reference/devices_gpu.md
lxd/device/device_utils_generic.go
lxd/device/gpu.go
lxd/device/gpu_mdev.go
lxd/device/gpu_mig.go
lxd/device/gpu_physical.go
lxd/device/gpu_sriov.go

Allow adding physical GPU devices to containers by setting the DRM ID with the `id` setting. Before a new device `/dev/nvidia[0123...]` was added for each graphics card regardless of what was configured with `id`. This was caused by a filtering mechanism that only took `vendorid`, `pci` and `productid` into account.
A new generic filter function is now used for each GPU device type (containers & virtual machines) which is checking all the attributes `vendorid`, `pci`, `productid` and `id`. 
For `gputype=mig` the check for the `id` filter is now also added since it was missing but supported according to the docs.
Fixes https://github.com/lxc/lxd/issues/11442

Allow the consistent selection of a GPU device by DRM ID

---

.sphinx/.wordlist.txt
doc/container-environment.md
doc/daemon-behavior.md
doc/database.md
doc/debugging.md
doc/environment.md
doc/explanation/lxd_lxc.md
doc/howto/images_remote.md
doc/howto/lxc_alias.md
doc/howto/server_configure.md
doc/index.md
doc/installing.md
doc/instances.md
doc/internals.md
doc/operation.md
doc/remotes.md
doc/server.md
doc/syscall-interception.md
doc/userns-idmap.md

A draft PR to review the planned structure.
Does it make sense to move most of the internal information under a new "Server and client" section?
Also, is all of that information still correct and relevant, or should some of it just be removed? If so, I'd rather remove it before I clean it up. ;)
This commit does not add or update any content, but only moves existing content into new sections.
Cleanup will be done later.

doc: restructure the Manage LXD and Internals sections

---

lxd/instance.go
lxd/instance/drivers/driver_lxc.go
lxd/instances_post.go
test/suites/fdleak.sh

Sets finalizer for garbage collector to release liblxc.Container reference inside `d.initLXC` rather than on `d` initialisation.
This way the finalizer is always certain to have been activated if `d.c` has been set, and also there's no need to activate it if `d.c` isn't being set.
This still results in some FDs lingering until the garbage collector runs normally or is triggered by `/internal/gc` request.
But it does fix the long-lasting FD leaks for liblxc log files.
It also updates the fdleak test to check for them as it was previously missing these.
Finally, as a step on the road to performing more proactive releasing of the liblxc.Container reference I have made `d.initLXC` return the `liblxc.Container` reference and updated the call sites to use the returned variable rather than using …

Instances: Fix file descriptor leaks of liblxc

---

lxd/device/gpu_physical.go

The Github test runners have a GPU but they do not support DRM. This revealed a bug in the `gpu` device.

Device: Fix panic when GPU device doesn't have DRM support in startContainer

---

lxd/device/gpu.go

Finding from https://github.com/lxc/lxd/pull/11825, fixes a bug introduced with https://github.com/lxc/lxd/pull/11799

lxd/device: Fix regression for not properly checking for GPU DRM information

---

lxd/device/gpu.go

The actual fix was provided here: https://github.com/lxc/lxd/pull/11825
Reverts lxc/lxd#11827

Revert "lxd/device: Fix regression for not properly checking for GPU DRM information"

---

.github/workflows/tests.yml

- Pin tests at Ubuntu 22.04, so we have to conciously change it and doesn't automatically switch over.
- Remove uneeded dependencies.

github: Simplify static-analysis tests

---

.github/workflows/tests.yml
lxd/instance_rebuild.go
lxd/storage/drivers/driver_btrfs_utils.go
test/suites/clustering.sh

Looks like there is an intermittent issue with btrfs when the disk is purposefully filled up to cause dqlite errors:
```
lxc storage delete lxdtest-M5g --force-local
time="2023-06-15T15:37:26Z" level=warning msg="Failed setting subvolume writable" driver=btrfs err="Failed to run: btrfs property set -f -ts /home/runner/work/lxd/lxd/test/tmp.08S/M5g/storage-pools/lxdtest-M5g ro false: exit status 1 (ERROR: Could not get subvolume flags: Inappropriate ioctl for device)" path=/home/runner/work/lxd/lxd/test/tmp.08S/M5g/storage-pools/lxdtest-M5g pool=lxdtest-M5g
Error: Failed deleting subvolume "/home/runner/work/lxd/lxd/test/tmp.08S/M5g/storage-pools/lxdtest-M5g": Failed to run: btrfs subvolume delete /home/runner/work/lxd/lxd/test/tmp.08S/M5g/storage-pools/lxdtest-M5g: exit status 1 (ERROR: …
```

test: Add support for running test suite on Github runners

---

test/main.sh

According to previous CI runs, that's save between 2-60s which isn't a lot but still better than nothing.
We do the same with LXD Cloud.

test: skip cleanup if executing from a GitHub Action runner

---

lxd/bgp/server.go

This should allow for larger clusters to refresh without losing advertisements.

lxd/bgp: Allow one hour for LXD restart

---

lxd/ip/vdpa.go

As recommended in the official doc [^1], `(*os.File).ReadDir` is a more efficient choice if we only need to know the name and whether it is a directory.
Sample benchmark:
```go
func Benchmark_Readdir(b *testing.B) {
for i := 0; i < b.N; i++ {
f, err := os.Open("/dev")
b.Fatal(err)
}
_, err = f.Readdir(-1)
f.Close()
b.Fatal(err)
}
f.Close()
}
}
func Benchmark_ReadDir(b *testing.B) {
for i := 0; i < b.N; i++ {
f, err := os.Open("/dev")
b.Fatal(err)
}
_, err = f.ReadDir(-1)
f.Close()
b.Fatal(err)
}
f.Close()
}
}
```
```
goos: linux
goarch: amd64
pkg: example
cpu: AMD Ryzen 7 PRO 4750U with Radeon Graphics
Benchmark_Readdir-16    	    6583	    400522 ns/op	   54612 B/op	     592 allocs/op
Benchmark_ReadDir-16    	   14204 …
```

lxd/ip: improve performance of `getVhostVDPADevInPath`

---

lxd/instance/drivers/driver_qemu.go

Otherwise /dev/vsock may not be present and VM support detection will fail.
Fixes regression from https://github.com/lxc/lxd/pull/11834
Related to https://github.com/lxc/lxd/issues/11794

VM: Load vhost_vsock kernel module if /dev/kvm is available

---

lxd/api_internal_recover.go
lxd/storage/drivers/driver_btrfs.go
lxd/storage/drivers/driver_ceph.go
lxd/storage/drivers/driver_cephfs.go
lxd/storage/drivers/driver_cephobject.go
lxd/storage/drivers/driver_dir.go
lxd/storage/drivers/driver_lvm.go
lxd/storage/drivers/driver_mock.go
lxd/storage/drivers/driver_zfs.go
lxd/storage/drivers/interface.go

Extract the defaults generation inside each pool driver's `Create()` function into a separate `PopulateConfig()` function.
On `lxd recover`, the pool's configuration is populated with default values before the configuration gets validated.
Fixes #10862

lxd/recover: Use configuration defaults

---

.github/workflows/builds.yml
.github/workflows/tests.yml
test/suites/clustering.sh
test/suites/database.sh

- Adds latest Go version test for `dir` driver.
- Adds unit testing as part of "Code tests" (formerly Static analysis) workflow.
- Renames "Unit tests (client)" to "Client tests".
- Adds support for opportunistic Go dependency build caching (seems to work only for later Go versions).
- Attempts fix of intermittent BTRFS test failure.

github: Extended testing

---

doc/.sphinx/.wordlist.txt
doc/installing.md

Move the installation instructions from
https://linuxcontainers.org/lxd/getting-started-cli/ into the docs.

doc: move installation instructions from the website

---

lxd/instance/drivers/driver_qemu.go

Fixes regression introduced by https://github.com/lxc/lxd/pull/11834

lxd/instance/qemu: Fix vsock id type

---

.github/workflows/tests.yml

This avoids needing to build the docs multiple times and keeps the documentation steps together.
Also fixes intermittent disk corruption in ceph tests due to the ephemeral disk being on a different device on different runners.
In the end I went for a loop file on the ephemeral disk's filesystem as this will be the most generic solution for different future environments.
Also introduces some ceph optimisations suggested by @stgraber

github: Combine documentation steps into single job

---

.github/workflows/tests.yml

The actual dependency review action takes ~0s but due to the extra checkout and cleanup, it ends up taking ~7s which == 1m of CI.

github: move dependency review (~0s) to Code tests job

---

.github/workflows/tests.yml
CONTRIBUTING.md

Follow-up on https://github.com/lxc/lxd/pull/11871#pullrequestreview-1492020461

github: inclusive naming should fail on error

---

lxd/api_cluster.go
lxd/db/node.go
lxd/instances_post.go
lxd/project/permissions.go
shared/util.go

Predecessor of https://github.com/lxc/lxd/pull/11813 to establish the new structure for cluster target permission checks.

api: Restructure target checks for the instancesPost endpoint

---

doc/reference/instance_options.md

Make it clear that security.csm and security.secureboot are related.

doc/instance options: clarify usage of security.csm

---

doc/howto/cluster_manage_instance.md
lxd/instance_post.go
test/main.sh
test/suites/clustering_move.sh

When launching new instances, the target node or cluster group can be defined by setting the `--target` flag. If specified the cluster members `scheduler.instance` or global `instances.placement.scriptlet` config setting gets evaluated to find a fitting target node. 
The same should apply when moving instances between cluster members. Especially when specifying `--target @group`, the scheduler mechanism can now pick up the right node from the list of cluster group members.
Since lots of the permission checking is done for both instance creation and movement, both endpoints should use the same functions for checking permissions when the `target` query parameter is set. The logic is now moved into the `lxd/project` package.
A new test suite is added for testing the movement of instances in …

api: Allow the selection of cluster groups when moving instances

---

doc/conf.py
doc/config_options_cheat_sheet.md
doc/doc-cheat-sheet.md

Exclude the two cheat sheets from the search index. Since this only excludes the pages, but not the _objects_ in the page, also exclude the config options cheat sheet from processing.

doc: exclude pages from search index

---

lxd/daemon.go
lxd/devices.go

Pass  `deviceEventListener` a function that can get a fresh copy of state, rather than using a long held version, which can become out of date.
This manifested itself in no container CPU scheduling being run for instances launched on a server that had just joined a cluster.
This was because the `ServerName` property in the `state.State` object `deviceEventListener` was passed on LXD start up contained "none" but after the server had joined the cluster its ServerName changed to its cluster member name.
This then meant that the `instance.LoadNodeAll()` call used inside `deviceEventListener` was filtering instances that were on server "none", of which there weren't any because the new instances were associated with the cluster member's name.
This then meant that those instances did not get …

lxd: Fix deviceEventListener resource scheduling when joining cluster

---

lxd/patches.go
lxd/storage/drivers/driver_btrfs.go
lxd/storage/drivers/driver_ceph.go
lxd/storage/drivers/driver_cephfs.go
lxd/storage/drivers/driver_cephobject.go
lxd/storage/drivers/driver_dir.go
lxd/storage/drivers/driver_lvm.go
lxd/storage/drivers/driver_zfs.go
lxd/storage/drivers/driver_zfs_utils.go
lxd/storage/drivers/driver_zfs_volumes.go

Drop filesystem suffix and DB settings from VM block volumes

---

lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
test/suites/basic.sh

When updating an instance, it's possible to override the devices
in such a way that it lacks a root disk device.
This adds a root device check before finalizing the update so that an
instance will always have a root disk device.
Fixes #11900

lxd/instance/drivers: Ensure root disk device

---

lxd-agent/api_1.0.go
lxd-agent/devlxd.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/drivers/driver_qemu_templates.go
lxd/vsock/vsock.go

When acquiring a new Context ID for the communication via vsock, pick the first four bytes of the instances UUID (try to get as much randomness as possible out of the 16 bytes) and convert it into an uint32. If there is a collision, try again after adding +1 to the ID. The syscall to the vsock returns ENODEV in case the Context ID is not yet assigned.
Fixes https://github.com/lxc/lxd/issues/11508

lxd/instance/drivers/qemu: Pick a random vsock Context ID

---

lxd/storage/drivers/driver_btrfs_utils.go
lxd/storage/drivers/driver_btrfs_volumes.go
lxd/storage/drivers/utils.go

Fixes a condition were subsequent snapshot attempts fail due to the root subvolume being already there.
When doing a snapshot, subvolumes of the root get discovered by walking the roots directory.
However this causes an issue if `filepath.Walk` probes volatile files from the actual filesystem.
Since `lstat` is called on all the files `filepath.Walk` has loaded into memory beforehand,
it returns an error for already deleted files.
Fixes https://github.com/lxc/lxd/issues/11682

Storage: Fix Btrfs snapshot race conditions

---

lxd/api_1.0.go
lxd/auth/oidc/oidc.go
lxd/daemon.go

This fixes an issue where LXD would fail on start if the OIDC server
isn't reachable.
Instead of failing on start, `NewVerifier` always returns a Verifier
struct, regardless of whether the OIDC server is reachable or not. If
unreachable, the verifier will try contacting the OIDC server during
the actual authentication. If that fails, so does the authentication.
This also removes the `keySet` variable from the `Verifier` struct as
it's not used anywhere.

oidc: Don't fail if server is not reachable

---

lxd/device/device_utils_network.go
test/suites/container_devices_nic_bridged.sh

When dealing with reasonably complex bridges that are not LXD managed, in my case, a bridge using VLAN filtering, it's not unusual for some VLANs to use a different MTU than others.
The problem is that currently LXD slams the same MTU on both the host and guest side device.
This feels like a good idea overall, if it wasn't for the fact that the Linux kernel will automatically lower the bridge MTU should any device be added to it with an MTU lower than its current value.
In practice what this means is that starting a single instance which has a network interface using an MTU lower than the current one on the bridge (1500 vs 9000 in my case) will cause the bridge MTU to get lowered and break a whole bunch of stuff.
Instead what we need to do is ensure that the host side device always has …

Fix LXD lowering host bridge MTU

---

client/operations.go

Hey there,
There was documentation missing in one [function](https://github.com/lxc/lxd/blob/71fd927db5672c33fa2c8a7b04ccb555834dba53/client/operations.go#L147) in the **client/operations.go** file. I added 2 lines of text there to make them understandable.
Thank you!

Added a heading in the client/operations.go file that was missing

---

client/lxd_containers.go

Hey there,
I just added a heading in the **client/lxd_containers.go** file that was missing. With this heading, it will be easy to understand what this function does.
Thank you!

Added a heading in the client/lxd_containers.go file that was missing

---

doc/profiles.md

This PR fixes a minor typo in `Edit a profile` section.

doc: Fix typo in edit a profile section

---

lxd/api_cluster.go
test/suites/clustering.sh

The `nodes_cluster_groups` table doesn't have a row with the given group_id if the group itself doesn't have any members. This leads to the error message `NodeClusterGroup not found` when trying to delete all rows affecting the cluster group.
Since the list of active and required members already gets compared and created/removed by another loop, this deletion/creation is effectively not required.
Fixes https://github.com/canonical/lxd/issues/11943

Cluster: Remove obsolete group delete/create for PUT endpoint

---

client/lxd_instances.go

Hey there,
I just added headings in the **client/lxd_instances.go** file that were missing. With these headings, it will be easy to understand what these functions do.
Thank you!

Added headings in the client/lxd_instances.go file that were missing

---

client/lxd.go

Hey there,
I updated the headings in some of the functions in the **client/lxd.go** file. With these headings, it will be easy to understand what each function does.
Thank you!

Some functions in the client/lxd.go file were missing the documentation headings

---

doc/syscall-interception.md

It should be level 3 so correct it as it is.

Correct `sysinfo` system call header level

---

lxd/instance/drivers/driver_qemu.go

This updates the `Documentation` key in the lxd-agent service file.

lxd/instance/drivers: Update system unit documentation

---

lxc/action.go
lxc/alias.go
lxc/config/remote.go

Hey there,
I added multiple headings in 3 files that are **remote.go, action.go and alias.go** files in the LXC directory with multiple commits
Thank you!

Added multiple headings in the the files of doc/LXC directory

---

lxd/instance/drivers/driver_qemu.go

When applying configuration to a VM, container specific configuration keys should be ignored.
When config settings are applied indirectly through a profile, running VMs should not raise error messages and instead silently ignore the configuration setting.
Fixes https://github.com/lxc/lxd/issues/11888

VM: Ignore container config keys

---

lxd/device/disk.go
lxd/instance/drivers/driver_qemu.go

Both host directories and CephFS shares can be shared to VMs. Hot plugging is already forbidden since the preparation for both virtio flavors (`9p` and `virtio-fs`) requires upfront configuration to the `qemu.conf` file.
Hot unplugging the share removes the `virtiofsd` process on the host side which leads the VM to hang if the share was mounted using `mount -t virtiofs` by the `lxd-agent`. Gracefully removing the corresponding device upfront from the VM seems not to be supported. See https://github.com/canonical/lxd/pull/11916#issuecomment-1623386489.
The issue is fixed by disabling hot unplugging of directory shares from VMs.
Fixes https://github.com/lxc/lxd/issues/11574

Disk: Disable directory disk hot plugging from VMs

---

lxd/db/instances.go
lxd/instances_get.go

This fixes #11947 where the instance type of instances of offline cluster members would always be shown as "CONTAINER".
For these instances, the instance type field was an empty string which then was interpreted as "CONTAINER" by the CLI.

Add instance type to instances of offline cluster members

---

lxd/storage/drivers/driver_zfs_volumes.go

When copying/migrating an instance without snapshots between two ZFS pools, an already existing root volume cannot be deleted on the target before doing the actual migration. This is currently happening if an instance doesn't have any snapshots which doesn't allow for optimized incremental copy.
When the migration fails (due to network outages or other errors on the source), there won't be any volume left on the target side. This is critical if `lxc copy` is used with the `--refresh` flag.
By keeping the volume on the target, `zfs receive` will update/overwrite it anyway.
If another storage backend is chosen at the source end, `rsync` will be used instead and this isn't applicable then.
Fixes https://github.com/canonical/lxd/issues/11822

Storage: Don't delete the target root volume when migrating between ZFS pools

---

doc/contributing.md
doc/metadata.yaml
doc/metrics.md
grafana/LXD.json
lxd/main_cluster.go
lxd/migrate.go
lxd/resources/utils.go
lxd/util/http_test.go
shared/api/url_test.go
shared/cert.go

There still are some occurrences for `git grep linuxcontainers.org  | grep -vF images.linuxcontainers.org` but those will need more work. We might need to extract content from the discourse instance.

Replace links

---

lxd/instance/drivers/driver_qemu.go

Handles a panic condition if the connection attempt to the vsock returns syscall errors other than ENODEV. In such situations the socket was never opened up and therefore cannot be closed with `c.Close()`.
This can be observed for exported/imported VMs and does not happen for individually created VMs. 
Since other errors might occur, fixing this should be a good idea in general. Investigation why this is happening especially for imported VMs is part of https://github.com/canonical/lxd/issues/11907:
```
Jul 10 10:31:14 thinkpad lxd.daemon[3689]: panic: runtime error: invalid memory address or nil pointer dereference
Jul 10 10:31:14 thinkpad lxd.daemon[3689]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xfe7919]
Jul 10 10:31:14 thinkpad lxd.daemon[3689]: goroutine 38684 …
```

VM: Skip every other vsock syscall error except ENODEV

---

doc/explanation/storage.md
doc/howto/storage_volumes.md

Also change storage volume type `vm` to `virtual-machine`.

doc/storage: clarify when to specify storage volume type

---

lxd/firewall/drivers/drivers_nftables.go
lxd/firewall/drivers/drivers_xtables.go
test/suites/network_forward.sh

Reuses the logic from #9633 to optimise firewall rule generation when applying network forwards.
Additionally adds some revert logic to the `NetworkApplyForwards` method in `xtables` to clean up any forwarding rules that may be partially applied (this is not required for `nftables` as the rules are collated and applied together in a template).
Closes #11911

Optimize network forwards

---

doc/external_resources.md
doc/howto/benchmark_performance.md
doc/howto/images_copy.md
doc/howto/images_manage.md
doc/howto/images_remote.md
doc/howto/instances_create.md
doc/reference/remote_image_servers.md

In examples, use the ubuntu: image server instead of the images: server.

doc: update to use the ubuntu: image server

---

lxd/storage/drivers/driver_zfs_volumes.go
test/main.sh
test/suites/backup.sh

This fixes an issue where custom block volumes would be listed as
datasets instead of volumes.
Fixes #11984

lxd/storage/drivers/zfs: Fix content type detection for custom block volumes

---

lxd/instance/instance_utils.go
test/suites/container_devices_nic_bridged.sh

Imported instances have the same set of addresses as their parent.
Starting those duplicates should produce a warning.
Fixes https://github.com/canonical/lxd/issues/11907

Instance: Prevent MAC/address conflict for imported instances

---

.github/workflows/tests.yml
client/lxd_containers.go
client/lxd_instances.go
lxc-to-lxd/transfer.go
lxc-to-lxd/utils.go
lxd/instance_console.go
lxd/storage/drivers/driver_ceph.go
lxd/storage/drivers/generic_vfs.go
shared/ws/mirror.go
test/main.sh
test/suites/lxc-to-lxd.sh
test/suites/migration.sh

Fix hang in lxc-to-lxd and re-enable the tests.
This currently doesn't support the storage pool having rsync compression disabled, which is why the tests were passing when run individually but failed if run after the migration test.
To solve this issue I've ensure the migration tests return the rsync compression state to default (enabled) so that the lxc_to_lxd tests pass. I will also look into whether we can support rsync compression disabled in lxc-to-lxd.
Related to #11910

Fix lxc-to-lxd

---

lxd/instance/drivers/driver_qemu.go
lxd/instance/drivers/driver_qemu_config_test.go
lxd/instance/drivers/driver_qemu_templates.go

When trying to acquire a new vsock Context ID, we want to occupy it right away to prevent collisions.
This helps for scenarios where two VMs have the same identical volatile.vsock_id (VM export/import) and
in case LXD is used in a nested environment.
If either the acquisition or the syscall fails, the next one gets selected.
Follow up on https://github.com/canonical/lxd/pull/11896 and observed during investigation of https://github.com/canonical/lxd/issues/11907

QEMU: Occupy vsock Context ID through syscall

---

.github/workflows/tests.yml
Makefile
lxc-to-lxd/main.go
lxd/devices.go
lxd/images.go
lxd/main_checkfeature.go
lxd/main_forkcoresched.go
lxd/main_forkexec.go
lxd/main_forkfile.go
lxd/main_forkmount.go
lxd/main_forknet.go
lxd/main_forkproxy.go
lxd/main_forksyscall.go
lxd/main_forkuevent.go
lxd/main_nsexec.go
lxd/seccomp/seccomp.go
lxd/storage/quota/projectquota.go
lxd/util/net.go
shared/idmap/shift_linux.go
shared/linux/socket_linux_cgo.go
shared/netutils/network_linux_cgo.go
shared/network.go

The PR ensures golangci-lint is the latest version when running in CI. If lint errors occur in CI that a developer did not encounter locally, they can check against the latest version with `rm $GOPATH/bin/golangci-lint && make static-analysis`.
It looks like the `gci` linter has changed a little and is unhappy with any files containing GCO. It is possible to reorder the imports to make this pass but I found the change less clear so I have excluded any files containing CGO from `gci` linting (other linters will still run).
Partially addresses #12011

Ensures golangci-lint is latest release version in CI

---

doc/api-extensions.md
doc/dev-lxd.md
doc/rest-api.md
doc/rest-api.yaml
lxd/operations.go
shared/api/instance_state.go
shared/api/resource.go

The REST API returns responses in JSON format, and [JSON](https://www.json.org/json-en.html) does not specify the term `dict` but `object` instead. This PR changes the API documentation to use the exact term from the JSON specification. Although the term `dict` may be familiar to many technical people (especially in the Python community), the term `dict` may be confusing to other users of the REST API.

doc/rest-api: Use JSON object as term instead of dict 

---

doc/database.md

For some reason, the title cannot be extracted reliably, so state it explicitly.

doc: explicitly state title of related link

---

lxd/network/driver_common.go
test/suites/network_forward.sh

Using either `0.0.0.0` or `::` for the forwards listen address is not supported.
Closes https://github.com/canonical/lxd/issues/11975

Network: Prevent unspecified forward address

---

shared/instancewriter/instance_tar_writer.go
test/main.sh
test/suites/image_acl.sh

When creating an archive from a container, use the right header key for the go tar module. There is no reference to `SCHILY.acl.*` in the go codebase under `src/archive/tar` which is what we use to create the instances tarball. Instead `SCHILY.xattr.*` is used.
Looks like the `SCHILY.acl.*` keys are from a withdrawn standard, see https://man.freebsd.org/cgi/man.cgi?query=star&sektion=5. Interestingly the page mentions:
> Note that the POSIX 1003.1e draft has been withdrawn in 1997 but some operating systems still support it with some filesystems.
Fixes https://github.com/canonical/lxd/issues/11901

instancewriter: Use right header key for tar ACLs

---

doc/authentication.md

Adds a line to the OIDC section to specify that `Device Authorization Grant` should be enabled on the OIDC provider for this to work.

doc: Specifies the type of OIDC authentication flow more explicitly.

---

lxd/instance/drivers/driver_lxc.go

It was reported that limits.memory.swap container instance config is not working as described in the LXD Documentation. Instead, observable behavior is opposite. Let's fix that.
Fixes #11566

lxd/instance/drivers/driver/lxc: make limits.memory.swap work properly

---

lxd/backup.go
lxd/daemon.go
lxd/db/backups.go
lxd/db/operationtype/operation_type.go
lxd/db/storage_volumes.go
test/main.sh
test/suites/backup.sh

This adds an hourly task which removes expired storage volume snapshots.

Expiry storage volume backups

---

.github/workflows/tests.yml

The regression in `curl` has been fixed in the latest version `7.81.0-1ubuntu1.13`. See https://ubuntu.com/security/notices/USN-6237-2
Reverts canonical/lxd#12046

Revert "github: pin curl to older version"

---

doc/conf.py
doc/installing.md

Configure the Discourse link extension to allow for two different Discourse instances (linuxcontainers and ubuntu), and update the link to the snap management tutorial to use the tutorial on the Ubuntu Discourse.

doc: add a link to Ubuntu Discourse

---

client/lxd_server.go
client/lxd_storage_volumes.go
doc/api-extensions.md
doc/rest-api.yaml
lxc/storage_volume.go
lxd/storage/drivers/driver_zfs_volumes.go
lxd/storage_volumes.go
lxd/storage_volumes_snapshot.go
shared/api/storage_pool_volume_snapshot.go
shared/version/api.go
test/suites/storage_snapshots.sh

Adds support for copying volume snapshots to and from a remote.
Includes tests for local and remote volume snapshot copy scenarios.
Fixes https://github.com/canonical/lxd/issues/11112

Volumes: Add remote copy support for snapshots

---

lxc/utils_properties.go
test/suites/config.sh

closes #12071 
Now this will work
```
lxc config set c1/snap0 expires_at="2023-08-01T00:00:00Z" --property
lxc config show c1/snap0 | grep expires_at
expires_at: 2023-08-01T00:00:00Z
lxc config get c1/snap0 architecture --property
x86_64
lxc config get c1/snap0 expires_at --property
2023-08-01T00:00:00Z
```

lxc: Support parsing of anonymous nested structs for getting properties

---

lxd/device/disk.go

Fixes regression caused by 81ffb0146a5cc770b3a0fa130c4e9b716cf6323e from https://github.com/canonical/lxd/pull/11852

VM: Fix boot from Windows ISO by setting correct FSType for .iso files

---

lxd/storage/backend_lxd.go
lxd/storage/drivers/driver_zfs_volumes.go
lxd/storage/drivers/volume.go
lxd/storage/utils.go

The root cause of this issue was that filesystem block volume related settings were incorrectly being stored for ZFS VM block volumes. This PR changes that so that only filesystem volumes using ZFS block mode have the volume block settings stored.
Fixes #12067
Closes #12075

Storage: Fix ZFS incorrect VM cached image volume regeneration when zfs.block_mode enabled

---

lxd/cluster/membership.go
test/suites/clustering.sh

There are some target-specific storage pool keys (i.e. source) that are applied to the driver, but not saved to the database when specified in a joining cluster member's MemberConfig data.
This commit ensures all node-specific keys supplied in MemberConfig are applied to the database appropriately.
I'm not sure on the reasoning for why they were explicitly skipped before, but given that that these config keys would exist on a storage pool created on an existing cluster, it stands to reason that adding the storage pool via `MemberConfig` should properly apply these too.

Apply MemberConfig to storage config table

---

lxd/device/device_utils_disk.go

Arch-based distributions install it there because they do not have /usr/libexec/.
Fixes #12086

lxd/device/device/utils/disk: Look for virtiofsd in /usr/lib/

---

test/suites/config.sh
test/suites/console.sh
test/suites/kernel_limits.sh
test/suites/storage_driver_zfs.sh

Also a small tweak to `test/suites/storage_driver_zfs.sh` to only match on `zone` if it's a sub-command of `zfs`.

Remove detection of LXC versions that are EOL

---

test/suites/container_syscall_interception.sh

```
$ lxc query /1.0 | jq -r .environment.server_version
4.0.9
$ lxc query /1.0 | jq -r .environment.lxc_features.seccomp_notify
true
```

test/container_syscall_interception: supported releases have seccomp_notify support

---

doc/conf.py

The start page is called differently for topical navigation (so that we can have different toctrees). However, RTD requires an `index` page to be present (even though Sphinx doesn't need it ...) So this is a workaround for this problem.

doc: add an index.html redirect for topical navigation

---

lxd/api_cluster.go
test/suites/clustering.sh

Sometime，In a 2-node cluster that one node's role is RaftSpace and the ohter one is Leader, I Remove the leader node from the cluster; At this time, Remove Operation was failed and the cluster would be unavailable, because of no node can be Leader.
So I change the RaftSpare node to RaftVote when remove leader from 2-node cluster

Change RaftSpare node to RaftVoter

---

lxd/config/generate/lxddoc.go
lxd/config/generate/lxddoc_test.go

Alphabetically sort the config options within a config group

lxddoc: Within a config group, alphabetically sort the config options

---

.github/workflows/tests.yml

Commit 916f032b62 tried skipping the clean up if ran inside a GitHub Action runner but that didn't work because sudo stripped the needed variable when launching the tests. This should make it work as intended.

github: keep GITHUB_ACTIONS in the test env to skip cleanup

---

test/extras/stresstest.sh
test/suites/fdleak.sh

This fixes shellcheck 0.9.x complaints, so that anyone using a recent version of shellcheck can get a clean output when running `make static-analysis`.

static-analysis: Fix shellcheck 0.9.x complaints

---

.github/labeler.yml
.github/workflows/tests.yml
test/suites/backup.sh
test/suites/migration.sh
test/suites/storage_local_volume_handling.sh
test/suites/storage_volume_import.sh

Apparently we are running tight on space and that's causing test failures:
> timeout --foreground 120 /home/runner/go/bin/lxc storage volume copy l1:lxdtest-3vW/iso1 l2:lxdtest-fut/iso1 --verbose
> ...
> time="2023-08-02T10:58:47Z" level=info msg="Migration channels disconnected on target" pool=lxdtest-fut project=default push=false volume=iso1
> Error: Failed storage volume creation: Error transferring storage volume: Error copying from migration connection to "/dev/zvol/lxdtest-fut/custom/default_iso1.iso": write /dev/zvol/lxdtest-fut/custom/default_iso1.iso: no space left on device
**Note**: I tried multiple size for ISO files (1, 2, 4, 8) and only
8MiB was reliable. Smaller sizes would always fail on some tests
with the dir backend. Cause: unknown.
Random drive-by fix: update the …

Use smaller ISO files in tests

---

doc/howto/instances_routed_nic_vm.md
doc/instances.md
doc/reference/devices_nic.md

This PR adds a simple tutorial for adding a routed nic device to a virtual machine. With the default gateway configured via cloud init and netplan.
https://github.com/canonical/lxd/pull/9529#issuecomment-1658248174

Adds a "how to" for routed nic devices on VMs

---

test/includes/lxc.sh

Turns:
> + LXD_DIR=/home/runner/work/lxd/lxd/test/tmp.GTh/938 lxc ls
> + LXC_LOCAL=1 lxc_remote ls
> + set +x
> + eval timeout --foreground 120 /home/runner/go/bin/lxc "ls" --verbose
> + timeout --foreground 120 /home/runner/go/bin/lxc ls --verbose
Into (2 less lines):
> + LXD_DIR=/home/runner/work/lxd/lxd/test/tmp.GTh/938 lxc ls
> + set +x
> + timeout --foreground 120 /home/runner/go/bin/lxc ls --verbose
While trimming 2 lines for each lxc invocation, might not seem much, I find those 2 lines to be essentially noise.
Also, one of our test outputs ~79k lines which would be reduced by ~11k with that PR so down to ~68k lines. This would make navigating those logs a tad less annoying IMHO.

Reduce noise in CI/test logs when DEBUG is set 

---

doc/api-extensions.md

Found in https://github.com/canonical/lxd/pull/12125

Doc: Clarify scope of nexthop config keys in BGP extension

---

doc/api-extensions.md

While all the other extensions use "_" as word separator, it seems that "virtual-machine" was typo'ed when VM support was introduced. It's too late to change the extension name though but we should have matching doc at least.

doc/api-extensions: fix extension name for VM support

---

doc/reference/storage_dir.md
doc/reference/storage_drivers.md

Also add a footnote about zfs.delegate, and make the existing asterisk a valid footnote.
Fixes #12142.

doc/storage: mark ZFS as usable inside a container

---

doc/api-extensions.md

This changes the header of the API extension to match the actual API
extension.

doc: Align header of macaroon_authentication

---

lxd/network/driver_common.go

These keys were added to validation rules in `driver_bridge.go` instead of inside `bgpValidationRules()` in `driver_common.go`, leading the latter to declare them as "invalid network keys".

fix: bgp.ipv*.nexthop keys treated as unknown

---

doc/.sphinx/requirements.txt

The latest Sphinx version that was released today removes functions that some extensions require.
Temporarily restrict the Sphinx version until the extensions have been fixed.

doc: restrict Sphinx version

---

lxd/instance_post.go
test/suites/clustering_move.sh

First observed in https://github.com/canonical/lxd/pull/12143. 
When moving instances within the same cluster group, the node which is currently hosting the instance should not be selected by the scheduler due to having the least amount of instances. 
`GetNodeWithLeastInstances()` most probably returned the instances in a different order than usual. This led the scheduler to pick the node that is already hosting the instance as candidate.

Instance: Fix placement when moving within same cluster group

---

Makefile
doc/.readthedocs.yaml
doc/conf.py

@ru-fu Now `lxd-doc` can be built from source and executed entirely from the `conf.py` file which means that we no longer have to use the makefile and it should directly integrates with the readthedoc pipeline.

lxddoc: Add a readthedoc pre-build hook to build and generate codebase doc

---

lxd/api_internal_recover.go
lxd/main_recover.go
test/suites/backup.sh

Currently, empty storage pools cannot be recovered, because the missing storage pool DB entries are restored during the recovery only if the *unknown volumes* are detected within the storage pool.
Not being able to recover empty storage pools, prevents the creation of a new storage pool with the same.
This PR changes the recovery process to first recover the missing storage pool DB entries and then the unknown volumes.

Allow recovery of empty storage pools

---

lxd/device/device_utils_generic.go
lxd/device/gpu_physical.go

lxd/device/gpu: if `gputype=physical`, check that no processes are tied to the card before unbinding it

---

lxd/devices.go
lxd/instance/drivers/driver_lxc.go

https://github.com/canonical/lxd/pull/12135#issuecomment-1687736767

lxd: network.limit-related bugfixes

---

lxd/device/nic_bridged.go
lxd/instance/drivers/driver_common.go
shared/instance.go

This PR fixes the migration condition of bridged network device.
It also adds logging to show instances where auto-migration is prevented due to a device's lack of migration support.
Fixes #12174

Fix migration condition for bridged network devices

---

doc/authentication.md
doc/dev-lxd.md
doc/explanation/clustering.md
doc/explanation/security.md
doc/explanation/storage.md
doc/faq.md
doc/howto/access_ui.md
doc/howto/cluster_config_networks.md
doc/howto/cluster_form.md
doc/howto/cluster_groups.md
doc/howto/cluster_manage.md
doc/howto/cluster_recover.md
doc/howto/instances_backup.md
doc/howto/instances_manage.md
doc/howto/move_instances.md
doc/howto/network_bgp.md
doc/howto/network_zones.md
doc/howto/server_expose.md
doc/howto/storage_buckets.md
doc/image-handling.md
doc/instance-exec.md
doc/metrics.md
doc/reference/devices_disk.md
doc/reference/instance_options.md
doc/reference/remote_image_servers.md
doc/reference/storage_btrfs.md
doc/reference/storage_dir.md
doc/reference/storage_lvm.md
doc/reference/storage_zfs.md
doc/remotes.md

Replace the links to config option sections with links directly to the respective config option.

doc: directly link to config options

---

doc/internals.md

The build for topical navigation was failing since the config option index wasn't included in the navigation.

doc: fix breaking build

---

lxd/auth/authorization.go

This actually initializes the struct like it used to be, fixing LXD from panicing on every request.
Closes #12181

lxd/auth/rbac: Fix regression

---

lxd/storage/drivers/driver_zfs_utils.go
shared/version/version.go

Backport version parsing fix from Incus

Fix version parsing

---

lxc/action.go
lxc/init.go
lxc/monitor.go
lxc/query.go

This un-hides the following commands:
- `lxc pause`
- `lxc init`
- ~`lxc manpage`~
- `lxc monitor`
- `lxc query`
Fixes #12175

Un-hide hidden commands

---

doc/.sphinx/requirements.txt

All extensions we use have now been fixed to work fine with the latest Sphinx version, so no need to pin the version anymore.

doc: unpin Sphinx version

---

doc/.sphinx/.markdownlint/exceptions.txt
doc/.sphinx/.wordlist.txt
doc/howto/import_machines_to_instances.md

Add a small example of using virt-v2v to convert Windows VMs to LXD.
Closes https://github.com/canonical/lxd/issues/12154

doc: add guide about virt-v2v

---

doc/conf.py

Anchors in GitHub documentation are handled in a way that the link checker can't deal with.
Therefore, don't check the validity of anchors. The general URLs are still checked.

doc: don't check validity of GitHub anchors

---

doc/cloud-init.md
doc/events.md
doc/faq.md
doc/howto/instances_create.md
doc/metrics.md
doc/reference/instance_options.md
doc/rest-api.md

Add references to the manpages for the formerly hidden commands.

doc: link to manpages

---

shared/util.go

https://www.gnu.org/savannah-checkouts/gnu/gettext/manual/html_node/Locale-Environment-Variables.html:
> LC_ALL is an environment variable that overrides all of the LC_*.
> It is typically used in scripts that run particular programs.
This *might* help with #11902
Closes #11902

shared/util: use LC_ALL instead of LANG in RunCommandCLocale()

---

lxd/instance.go
lxd/instance_patch.go
lxd/instance_put.go

This adds an instance lock when updating instances so that an instance
cannot be updated concurrently.
When trying to change the instance config concurrently, only one call
will succeed, the others will return an etag missmatch error.
Fixes #12189

lxd: Use instance lock when updating instance

---

lxd/resources/system.go

If DMI is not available, `lshw` is used to retrieve system information.
Fixes #12112

lxd/resources: Use `lshw` if DMI is not available

---

doc/conf.py
doc/howto/instances_configure.md
doc/howto/instances_manage.md
doc/rest-api.md

This PR adds an example of how to present API instructions alongside the CLI instructions.
Updating all instructions will be a separate task. In addition, we also want to include UI instructions in the future.

Doc: PoC for adding API instructions

---

lxd/instance/drivers/driver_common.go

drivers: Use StatusError to ensure error code consistency

---

lxd/instance_exec.go

This returns an error if `record-output` and `wait-for-websocket`, or
`interactive` and `record-output` are used in combination.
Fixes #12216

instance_exec: Add contraint validation

---

lxd/cgroup/abstraction.go

Sometimes (not always), something in LXD's snap loop device causes some IOs to be accounted against a given container:
```
sdeziel@ocelot:~$ lxc query /1.0/metrics | grep -F 'device="loop'
lxd_disk_read_bytes_total{device="loop2",name="git",project="default",type="container"} 2048
lxd_disk_read_bytes_total{device="loop2",name="git",project="default",type="container"} 2048
lxd_disk_reads_completed_total{device="loop2",name="git",project="default",type="container"} 1
lxd_disk_reads_completed_total{device="loop2",name="git",project="default",type="container"} 1
lxd_disk_written_bytes_total{device="loop2",name="git",project="default",type="container"} 0
lxd_disk_written_bytes_total{device="loop2",name="git",project="default",type="container"} 0 …
```

Skip loop devices from IO stats

---

Makefile

I don't know if anyone uses `make tags` (I don't) but it's been broken for a while. This should fix it anyway.

Makefile: fix "tags" target and don't make it PHONY

---

doc/reference/storage_zfs.md

It is now possible to delegate part of the pool to containers. (No need to mention the required modules, that is documented for the `zfs.delegate` option.)

doc/zfs: remove limitation

---

lxd/device/disk.go

This PR fixes a couple of validation issues with `disk` devices relating to detecting whether a disk can be hotplugged into a VM or not.
Before:
```
lxc storage volume create default vol1fs --type=filesystem
lxc launch ubuntu:jammy v1 --vm
lxc config device add v1 vol1 disk source=vol1fs pool=default 
Error: Failed add validation for device "vol1": Custom filesystem volumes require a path to be defined
lxc config device add v1 vol1 disk source=vol1fs pool=default path=/mnt
Error: Failed to start device "vol1": Failed to add drive config: Invalid device path format "36"
lxc stop v1
lxc config device add v1 vol1 disk source=vol1fs pool=default path=/mnt
lxc start v1
lxc config device remove v1 vol1
Device vol1 removed from v1
lxc exec v1 -- ls /mnt #hangs
```
After:
```
lxc storage volume …
```

Device: Fix disk hot-plug validation for VMs

---

test/lint/metadata-up-to-date.sh

The script would abort when a delta between "before" and "after" was noticed because `diff` would return with a non-`0` code. Fix that so that we can see the delta if there is one and use "unified" mode.

Fix metadata-up-to-date lint script

---

doc/getting_started.md
doc/howto/access_documentation.md
lxd/api.go

JIRA task: https://warthogs.atlassian.net/jira/software/c/projects/LXD/boards/54?modal=detail&selectedIssue=LXD-359&assignee=63d9eb6128cddcc70770aff1
Spec: https://discourse.ubuntu.com/t/expose-the-full-lxd-documentation-website-as-part-of-a-lxd-deployment/37516
Once this gets merged, we need to merge https://github.com/canonical/lxd-pkg-snap/pull/136 to make it work with snap

lxd: expose a documentation server to LXD

---

Makefile

If `shellcheck` is missing, this avoids the following error:
> $ make deps
> /bin/sh: 1: shellcheck: not found
> ...
This affected every targets because each `ifeq` directives are evaluated, irrespective of the target called:
> $ make foo
> /bin/sh: 1: shellcheck: not found
> make: *** No rule to make target 'foo'.  Stop.

Makefile: check `shellcheck`'s version only if present

---

lxc/cluster.go
lxc/config_trust.go
lxc/main.go
lxc/remote.go
lxd-migrate/main.go
lxd-migrate/main_migrate.go
lxd-migrate/utils.go
lxd/main.go
lxd/main_init_interactive.go
lxd/main_recover.go
shared/cmd/ask.go

Adds SetReader to allow setting the default reader for the CLI (from the default Stdin). This can be helpful for managing inputs to the CLI when testing.

shared/cmd/ask: Allow setting CLI function reader

---

test/suites/storage_local_volume_handling.sh
test/suites/storage_volume_import.sh

In #12113, all ISO files were shrunk down to 8MiB. Smaller sizes (1, 2 and 4MiB) were tried but caused increased failure rate in the `migration`, `storage_local_volume_handling` and `storage_volume_import` test cases. 
It seems that even 8MiB is too small causing those tests to fail and account for ~25% of all the failures. Until the root cause can be find and fixed, it's better to revert those commits.

Small ISO workaround

---

.github/CODEOWNERS

This is so we can increase the team's permissions to allow for better management of issues/tags and for allowing pushing to each others pull requests, whilst still requiring approval from code owners before being able to merge.

github: Adds CODEOWNERS file

---

lxd/apparmor/instance_qemu.go

This is causing some apparmor denials in our current policy, and allowing access to this file is acceptable.

apparmor: Allow /etc/machine-id

---

.github/workflows/tests.yml
Makefile

tests: Test the distribution tarball can be used to build LXD and its dependencies

---

lxd-agent/metrics.go

This fixes a bug where lines with less than 9 fields in /proc/stat would
return an error. However, /proc/stat doesn't only contain CPU
information. Therefore, the field validation should only be done for CPU
related lines.
Fixes #12255

lxd-agent: Validate fields only for CPU info

---

.github/workflows/tests.yml

@tomponline I opted to bail for 3 reasons:
* it's a rare condition (haven't witnessed it, yet)
* the fix is on it's way (https://github.com/snapcore/snapd/pull/13150)
* the workarounds feel like hacks
The cleanest workaround I could think of was to use a loop-dev but backed by the partition instead of a FS:
```
sudo swapoff /mnt/swapfile
sudo umount /mnt
ephemeral_disk="$(findmnt --noheadings --output SOURCE --target /mnt)"
blkdiscard "${ephemeral_disk}"
loop_dev="$(sudo losetup --show --direct-io=on --nooverlap -f "${ephemeral_disk}")"
devInfo=($(sudo stat -c '%t %T' "${loop_dev}"))
sudo mknod -m 0660 /dev/sdia b 0x"${devInfo[0]}" 0x"${devInfo[1]}"
sudo microceph disk add --wipe /dev/sdia
```

Bail if the rootfs and the ephemeral one are on the same disk

---

lxd/device/nic_ovn.go
lxd/network/driver_ovn.go
lxd/network/openvswitch/ovn.go

This PR fixes OVN leases not showing static IPs. Due to this error, dynamic leases also disappeared from the list after instance restart.
Fixes #12177

Fix OVN leases not showing static IPs

---

lxd/storage/drivers/driver_btrfs_utils.go

This pull request changes `getSubvolumes` to use command `btrfs subvolume list` instead of walking the entire tree.
It took over three seconds to walk the entire tree in my test environment with a large tree. This can be reduced to a few milliseconds using the command.

storage: Use btrfs subvolume list command instead of walking dir to get subvolumes

---

lxd/auth/driver_rbac.go

This fixes an issue where the goroutine would continue to run even if
RBAC has been disabled.

lxd/auth: Exit goroutine if RBAC has been disabled

---

shared/simplestreams/products.go

Also adds support for the new `Requirements` field as an alternative to the existing `LXDRequirements` field.
This is to maintain LXD's compatibility with the community `images.linuxcontainers.org` images from the `images:` remote in the `lxc` client.
Fixes #12206
Closes https://github.com/canonical/lxd/pull/12232

simplestreams: Adds support for incus.tar.xz items

---

lxd/api_1.0.go

Part of the PR from @monstermunchkin https://github.com/canonical/lxd/pull/12190

lxd: Revert server config if it cannot be set

---

lxd/device/device_utils_network.go

Previously if the wait timeout passed the error displayed would include %w(nil).

device: Improve error handling and messaging in networkSRIOVRestoreVF

---

lxd/api_internal.go

Returns `429 Too Many Requests` from the shutdown API if called again when a shutdown is already happening. This facilitates checking if an error in the shutdown API is recoverable.

Add shutdown api http error

---

lxd/main_forknet.go

This can occur with physical or SR-IOV NICs where the altname is added and can prevent clean rename and post-stop clean up.

forknet: Remove altname if preventing rename of NIC interface

---

lxd/storage/drivers/driver_zfs_volumes.go

This PR disallows setting `zfs.block_mode` for custom volumes and VM block volumes. It also disallows setting `block.*` settings for VMs.

Disallow block settings for VM block volumes

---

.github/workflows/tests.yml
shared/validate/validate.go
test/suites/basic.sh
test/suites/network.sh

IsHostname() used to refuse name starting with a digit possibly to comply with RFC 952 but this was relaxed in RFC 1123:
> One aspect of host name syntax is hereby changed: the
> restriction on the first character is relaxed to allow either a
> letter or a digit.
Compatibility with DNS and UTS was mentioned in #1122, where the new restrictions were put in place. However, it seems that hostname can also start with a digit:
```
0foo
```

shared/validate: names starting with a digit are valid

---

grafana/LXD.json

Here's what it looks like
The Loki logs section is static as there is currently no way to know which LXD server generated the associated logs. I think we are missing the equivalent of a Prometheus "instance" label. I also think we'll want to enrich the `lifecycle` events eventually to have `name` and `project` labels. Those are for another day/PR however.
@tomponline if/when that gets merged, I'll deal with updating the copy on Grafana's site.

grafana: add Loki logs section with lifecycle and logging events

---

doc/.sphinx/.wordlist.txt
doc/api-extensions.md
doc/config_options.txt
doc/howto/network_ovn_setup.md
lxd/api_1.0.go
lxd/cluster/config/config.go
lxd/daemon.go
lxd/events.go
lxd/events/internalListener.go
lxd/loki/loki.go
lxd/metadata/configuration.json
lxd/node/config.go
lxd/syslog.go
shared/api/event.go
shared/version/api.go
test/main.sh
test/suites/syslog.sh

This adds an OVN log monitor which listens for log messages on a unix socket. If messages are received, they are sent to the events API which will then forward them to Loki (if configured). The log monitor can be enabled by setting `core.syslog_socket` to `true`. The logs will only be sent to Loki, if `loki.types` contains `ovn`.
In this case, the `ovn` events can also be monitored using `lxc monitor
--type=ovn`.
On Ubuntu, OVN uses the `/etc/default/ovn-host` environment file. To enable the OVN controller to send their logs via unix socket, one needs to add the following:
```
OVN_CTL_OPTS="--ovn-controller-log='-vsyslog:info --syslog-method=unix:/var/lib/lxd/syslog.socket'"
```
There are also `--ovn-sb-log` and `--ovn-nb-log` which take the same arguments. These need to be set in …

Send OVN logs to events API and Loki

---

doc/config_options.txt
lxd/cluster/config/config.go
lxd/metadata/configuration.json

Mention that LXD adds the `/loki/api/v1/push` suffix to the provided
`loki.api.url` config value.
Fixes https://github.com/canonical/lxd/issues/12271

doc: Update docs on loki.api.url

---

doc/howto/network_ovn_setup.md
shared/api/event.go

And improve the OVN syslog setup docs from https://github.com/canonical/lxd/pull/12200

shared: Add support for OVN logs to `lxc monitor --pretty`

---

shared/simplestreams/products.go

For reasons that are likely lost to history simplestreams uses lxd.tar.xz whereas the combined file is lxd_combined.tar.gz (not xz).
Fixes regression introduced by https://github.com/canonical/lxd/pull/12260

simplestreams: Fix regression in lxd_combined.tar.gz handling

---

lxd/loki/loki.go

- loki: Check return value of reflect.TypeOf()
- loki: Fix labels names with hyphens

Small Loki fixes

---

doc/conf.py

We're excluding the cheat sheets for the starter pack, but we want to include this one ...

doc: include the cheat sheet again

---

doc/.wordlist.txt
doc/api-extensions.md
doc/config_options.txt
doc/reference/devices_nic.md
lxd/cgroup/init.go
lxd/device/device_utils_network.go
lxd/device/nic.go
lxd/device/nic_bridged.go
lxd/device/nic_p2p.go
lxd/device/nic_routed.go
lxd/firewall/drivers/drivers_nftables.go
lxd/firewall/drivers/drivers_nftables_templates.go
lxd/firewall/drivers/drivers_xtables.go
lxd/firewall/firewall_interface.go
lxd/metadata/configuration.json
shared/instance.go
shared/version/api.go
test/suites/container_devices_nic_bridged.sh

lxd/device: add support for network device limits.priority option
This is a replacement feature for per-instance limits.network.priority option.
New approach does not require netprio cgroup to be suppored (it's from legacy
cgroup v1) and also it allows to set priority for virtual machine instances.
The recommended Linux kernel version (for full functionality) is 5.16.

Add support for network device limits.priority option

---

lxd/device/nic_ovn.go

Due to a bug in OVN, we should not allow setting static IPv6 if static IPv4 is not set.
Closes #12297

lxd/device/nic_ovn: Prevent setting static IPv6 if static IPv4 is not set

---

lxd/storage/backend_lxd.go
lxd/storage/drivers/driver_common.go
test/suites/container_devices_disk.sh

Adds a check to the common driver volume validation that the `security.shifted` and `security.unmapped` config options are only set on custom volumes and cannot be set at the same time.

Enforce `security.shifted` and `security.unmapped` to be mutually exclusive.

---

doc/config_options.txt
doc/explanation/projects.md
doc/howto/network_forwards.md
doc/howto/network_load_balancers.md
doc/howto/network_zones.md
doc/reference/projects.md
lxd/api_project.go
lxd/metadata/configuration.json

This requires [this](https://github.com/canonical/lxd-sphinx-extensions/pull/22) to be merged first
JIRA task : [here](https://warthogs.atlassian.net/jira/software/c/projects/LXD/boards/54?modal=detail&selectedIssue=LXD-430&assignee=63d9eb6128cddcc70770aff1)

doc: document the project config options

---

doc/.sphinx/_static/github_issue_links.js

The JavaScript we include to display the feedback button uses the window.onload function. Swagger uses the same function ... which means it's overwritten.
Fix the script we control (`github_issue_links.js`) to preserve an existing onload function.
Fixes https://github.com/canonical/lxd/issues/12318

doc: fix swagger display

---

README.md

And update the link so it shows workflow results filtered by branch and action.
The previous image seemed to be stuck on failure due to a test name change.
The "tests.yml" file covers both client and server tests now.

README: Update test status badge so it accurately shows status of tests.yml workflow

---

README.md

And update the link so it shows workflow results filtered by branch and action.
The previous image seemed to be stuck on failure due to a test name change.
The "tests.yml" file covers both client and server tests now.

README: Update test status badge so it accurately shows status of tests.yml workflow (stable-5.0)

---

lxd/resources/network.go
lxd/resources/utils.go

This PR recursively expands the device directory path of `sys/class/net` devices by appending `/device` until the it finds a `device` regular file as a child.
This is needed for devices like wwan which include sub-devices and they differ from typical `sys/class/net` devices. For such kind of devices, the net info is present at the top `./device` directory but rest information needed to fill `Card` struct is located at `./device/device`.
Please take a look below for more info:
```
total 0
drwxr-xr-x 7 root root    0  ./
drwxr-xr-x 3 root root    0  ../
lrwxrwxrwx 1 root root    0  device -> ../../../0000:08:00.0/
-r--r--r-- 1 root root 4096  index
drwxr-xr-x 3 root root    0  net/
drwxr-xr-x 2 root root    0  power/
lrwxrwxrwx 1 root root    0  subsystem -> ../../../../../../class/wwan/ …
```

Fix info --resources for wwan devices

---

test/suites/network.sh

As it conflicts if running LXD on the host at the same time. Use $$ suffix like the other tests.

tests: Don't use lxdbr0 in network tests

---

lxc/storage_volume.go
test/suites/storage_local_volume_handling.sh

When calling `lxc storage volume move` it internally always calls `lxc
storage volume copy`. This in itself is not a problem. However, the
`copy` handler expects LXD to always return an `OperationResponse`. This
doesn't happen though as LXD will return a `SyncResponse` if it detects
a move request.
This changes the `move` handler to call `lxc storage volume rename` if
it detects a rename request, instead of passing it to the `copy`
handler.
Fixes #12344

lxc: Handle volume rename in `lxc storage volume move` command

---

lxd/api_cluster.go

When a new node is added to the cluster, it should get all cluster config (now present after it joins the cluster db) and apply configuration changes locally.
Previously we were attempting to apply changes based on the daemons current cluster config (from state) which did not reflect the full cluster configuration. Additionally, we were only applying a subset of configuration changes. This change utilises the doApi10UpdateTriggers to apply all changes consistently.

lxd: Fully configure new node from cluster config after it is added.

---

lxc/storage.go

After creating an empty pool with e.g. `lxc storage create test dir`, the following command panics `lxc storage set test rsync.compression true` and the config key is not set.
This commit initialises the writable config map if it is nil and fixes the command.

lxc/storage: Initialise writable storage pool config map if nil.

---

client/lxd_instances.go

`(*ProtocolLXD).queryOperation` calls `(*ProtocolLXD).query` which will set the project query parameter if necessary. Including it here as part of a formatted string can lead to urls like
`/1.0/instances/c1/rebuild?project=`. This isn't necessarily a problem but would be unexpected on the API side.

client: Remove project from format string API path.

---

.github/workflows/tests.yml

The edge snap build failed anyway because of the inaccessible secret. But its clearer to see it skipped.

github: Skip edge snap build for pushes on branches from dependabot (stable-5.0)

---

client/lxd.go
client/lxd_certificates.go
client/lxd_cluster.go
client/lxd_containers.go
client/lxd_images.go
client/lxd_instances.go
client/lxd_projects.go
client/lxd_storage_volumes.go
client/operations.go

Is it not always necessary to set up an event listener when interacting with operations via the client. For example, many client methods call `queryOperation` and then call `Wait` on the returned operation. Instead of receiving all events, filtering by operation, then filtering by the ID of the operation, and checking the status code for "success" or "failure", we can just use `/1.0/operations/wait`.

client: Pass a flag into `queryOperation` to skip event listener setup if not required.

---

.github/workflows/tests.yml

github: build static lxc and lxd-migrate bins for arm64

---

lxd/api_cluster.go
lxd/certificate/cache.go
lxd/certificate/type.go
lxd/certificates.go
lxd/cluster/gateway.go
lxd/cluster/gateway_test.go
lxd/cluster/heartbeat_test.go
lxd/cluster/membership.go
lxd/cluster/membership_test.go
lxd/cluster/tls.go
lxd/cluster/upgrade_test.go
lxd/daemon.go
lxd/db/certificates.go
lxd/db/cluster/certificates.go
lxd/db/cluster/certificates.interface.mapper.go
lxd/db/cluster/certificates.mapper.go
lxd/db/migration_test.go
lxd/patches.go

For #12313 we need to access the certificate cache from the `auth` package for the TLS driver. While making this change I also noticed that the certificate cache is not strictly thread safe since the certificates and projects are stored in maps. E.g. It would be possible to get the certificate map within a lock, unlock it, then read/write from/to the map and cause a panic. Additionally, [here](https://github.com/canonical/lxd/blob/d2067ea5407311d90fecd29430343a98a838275f/lxd/daemon.go#L1040) the length of the certificate map is read without a lock which is may be thread safe but could also be a race condition.
This PR moves the certificate cache logic into a new package and adds methods for writing/reading from it safely. The returns maps are copies.

Move certificate cache into new package

---

lxd-agent/api_1.0.go
lxd-agent/operations.go

After recent changes to the client in #12349, when calling ExecInstance we wait for the operation to complete by directly calling the operation wait endpoint instead of listening for the event.
When calling exec on a VM, the client is used to connect with the LXD agent via vsock. This was failing with a 404 because the endpoint didn't exist.

lxd-agent: Adds an operation wait endpoint to fix VM exec operations

---

lxd/storage/storage.go

Fix duplicate used by entry in storage pool 

---

lxd/resources/storage.go

lxd/resources: if `SCSI_IDENT_SERIAL` is available, use it as serial nr before `ID_SERIAL_SHORT`

---

.github/workflows/tests.yml

Tests failing at:
```
lxc storage create lxdtest-5zO ceph volume.size=25MiB ceph.osd.pg_num=8
```
All seem to have `microceph.ceph status` show as:
```
+ sudo microceph.ceph status
cluster:
id:     7e42c215-815d-477f-afa9-5f218fcc3081
health: HEALTH_WARN
mon fv-az1234-656 is low on available space
nobackfill,norebalance,norecover,noscrub,nodeep-scrub,nosnaptrim flag(s) set
3 pool(s) have no replicas configured
OSD count 0 < osd_pool_default_size 1
services:
mon: 1 daemons, quorum fv-az1234-656 (age 63s)
mgr: fv-az1234-656(active, since 55s)
mds: 1/1 daemons up
osd: 0 osds: 0 up, 0 in
flags nobackfill,norebalance,norecover,noscrub,nodeep-scrub,nosnaptrim
data:
volumes: 1/1 healthy
pools:   3 pools, 65 pgs
objects: 0 objects, 0 B
usage:   0 B used, 0 B / 0 B avail
pgs:     100.000% pgs …
```

Improve ceph test reliability

---

.github/workflows/tests.yml

ceph's mon was complaining about low free space in the rootfs.

github: tune ext4 for speed and reclaim some space

---

test/main.sh
test/suites/backup.sh
test/suites/lxd_user.sh
test/suites/syslog.sh

Port of https://github.com/lxc/incus/pull/159

Add lxd-user test

---

client/lxd_instances.go
doc/api-extensions.md
shared/version/api.go

#12349 introduced to the client the concept of waiting for an operation to complete via the operation wait endpoint rather than using the events websocket. This is used for `InstanceExec` and `InstanceConsole`.
Unfortunately this did not work for VMs as the lxd-agent did not contain the operation wait endpoint. This was fixed in #12372, but this fix will not work for older versions of the lxd-agent. This change introduces an API extension for the change so that we can check if the operation wait endpoint exists before choosing how to handle waiting for the operation.

Operation wait extension

---

lxd/api_metrics.go
lxd/daemon_images.go
lxd/images.go
lxd/instance.go
lxd/instance/drivers/driver_common.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/instance_patch.go
lxd/instance_put.go
lxd/locking/lock.go
lxd/network/driver_ovn.go
lxd/storage/backend_lxd.go
lxd/storage/drivers/driver_btrfs_volumes.go
lxd/storage/drivers/driver_ceph_volumes.go
lxd/storage/drivers/driver_cephfs_volumes.go
lxd/storage/drivers/driver_dir_volumes.go
lxd/storage/drivers/driver_lvm_utils.go
lxd/storage/drivers/driver_lvm_volumes.go
lxd/storage/drivers/driver_zfs_volumes.go
lxd/storage/drivers/volume.go
lxd/storage/s3/miniod/miniod.go

In case the provided context for `locking.Lock()` gets cancelled an error is returned. This obsoletes any `!= nil` checks for the returned unlock function.
See here for some more reasoning: https://github.com/canonical/lxd/pull/12304#discussion_r1354384719

Return error from locking.Lock

---

client/lxd_operations.go

The `ResponseHeaderTimeout` in the `http.Transport` for the client was, in most cases, set to 1 hour. This change unsets the timeout, allowing us to wait for an operation to complete indefinitely.

client: Unset response header timeout when waiting for operations.

---

lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/storage/backend_lxd.go
lxd/storage/backend_mock.go
lxd/storage/pool_interface.go
test/main.sh
test/suites/backup.sh

Snapshots are no longer appended to the `backup.yaml` when instance is exported using `--instance-only` flag.
Fixes #12370

Respect instance-only flag when generating backup.yaml

---

.github/workflows/tests.yml

Let's be consistent with go-lxc [1] and use ppa:ubuntu-lxc/daily to fetch and install development build of liblxc.
I have checked that builds in ppa:ubuntu-lxc/daily and ppa:ubuntu-lxc/lxc-git-master right now are equal. Likely we need to get rid of ubuntu-lxc/lxc-git-master at some point, but as a first step let's just start using ubuntu-lxc/daily for LXD CI builds.
[1] https://github.com/lxc/go-lxc/blob/ccae595aa49e779f7ecc9250329967aa546acd31/.github/workflows/test.yml#L29

github: use ppa:ubuntu-lxc/daily instead of ppa:ubuntu-lxc/lxc-git-master

---

lxd-agent/api_1.0.go
lxd-agent/daemon.go
lxd-agent/main_agent.go

Sometimes we were seeing the initial vsock context ID of 4294967295 (equivalent to VMADDR_CID_ANY) and then a few seconds later the context ID was returning the valid context ID for the VM.
This was previously causing the vsock listener to be restarted 30s after the VM booted, which if there were any exec sessions ongoing would cause them to be terminated.
This fixes the issue by waiting for a valid vsock ID and ignoring the value 4294967295.

lxd-agent: Fixes vsock listener restart on boot due to vsock module not being fully initialised

---

lxd/apparmor/rsync.go
lxd/device/device_utils_generic.go
lxd/lxd-metadata/lxd_metadata.go
lxd/storage/backend_lxd.go

lxd: Remove use of ioutil

---

lxd-agent/api_1.0.go
lxd-agent/daemon.go
lxd-agent/main_agent.go
lxd/vsock/vsock.go

This PR switches the lxd-agent vsock listener to use the VMADDR_CID_ANY (4294967295) CID, rather than trying to ascertain the VM's local CID and listening only on that.
The reason is two-fold:
1. We were seeing that sometimes the vsock.ContextID() call was returning 4294967295 just after the vsock module was loaded, but shortly afterward then started returning the correct CID assigned in QEMU. This would trigger the vsock CID change detector up to 30s later and cause the vsock listener to be restarted. Any ongoing exec operations that had started before that would be prematurely terminated. The vsock VID change detector was originally added to detect when a VM was statefully restored/migrated in such a way that its QEMU assigned CID was changed whilst the VM was running. This prevented …

lxd-agent: Fixes intermittent exec EOF closure when vsock listener is restarted just after boot

---

shared/api/url.go
shared/api/url_test.go

Go's net.URL requires Path to be populated with unencoded path and RawPath to be populated with the hint on how we want Path to be encoded.
This avoids double path encoding when calling url.EscapedPath(), which is used in url.String().
Fixes #12398
Before:
```
lxc storage volume create default tüdeldü
lxc storage show default
config:
source: /var/lib/lxd/storage-pools/default
name: default
driver: dir
used_by:
- /1.0/storage-pools/default/volumes/custom/t%25C3%25BCdeld%25C3%25BC
```
After:
```
lxc storage show default
config:
source: /var/lib/lxd/storage-pools/default
name: default
driver: dir
used_by:
- /1.0/storage-pools/default/volumes/custom/t%C3%BCdeld%C3%BC
```
Closes #12406

shared/api/url: Fix double path encoding issue

---

lxd/network/driver_bridge.go

network: Don't consider an IP parse failure of a proxy listen address an error

---

lxc/storage_volume.go
test/suites/clustering.sh

This fixes a regression introduced in https://github.com/canonical/lxd/pull/12348
which causes the `--destination-target` flag to be ignored.
When renaming a volume using `lxc storage volume move`, the args were
passed to the handler behind `lxc storage volume rename` which does not
support the `--destination-target` flag.
Instead if the destination flag is set when renaming a volume, use the handler for volume movements.

Fix volume rename if cluster desination target is set

---

.github/workflows/tests.yml

If dependabot creates new PRs, those are not originating from a fork. Instead a new branch is created in the same repository which triggers on both `push` and `pull_request`.
Limiting the push trigger to the main and release branches doesn't anymore duplicate the jobs for dependabot PRs.
Check here for reference: https://github.com/canonical/lxd/pull/12376

github: Run push actions on main and release branches only

---

client/doc.go
test/suites/remote.sh

Also fix `lxc remote add` of public simplestreams servers with valid certs to not prompt for fingerprint acceptance.

test/remote: switch to cloud-images.ubuntu.com URLs

---

.gitignore
lxd/daemon.go
lxd/patches.go

Fixes start up issue for ZFS volumes from https://github.com/canonical/lxd/pull/12390

lxd: Initialise server name and global config before storage patches are run

---

lxd/api.go
lxd/auth/oidc/oidc.go
lxd/devlxd.go

Fix one of the low hanging fruit found by `make staticcheck` (see #12422).

Use HTTP status codes constants instead of literal numerics

---

lxd/firewall/drivers/drivers_nftables_templates.go

Network interface name must be double-quoted to avoid collisions with the nftables syntax.
For example a bridge network called `rt` will cause the following error prior to this commit:
```
Error: syntax error, unexpected rt
iifname rt jump acl.rt
^^
```
when trying to set ACL:
`lxc network set rt security.acls="rt-acl"`
because `rt` is a restricted token in the nftables syntax: https://wiki.nftables.org/wiki-nftables/index.php/Quick_reference-nftables_in_10_minutes#Rt

lxd/firewall: Fix nftables ACL template

---

doc/howto/import_machines_to_instances.md
doc/howto/initialize.md
doc/installing.md

Our binaries are now available for different architectures. Update the download links to the new links.

doc: update link to tool downloads

---

lxd/api_cluster.go

A change that will be introduced by #12313 is that requests originating from other cluster members will no longer be implicitly trusted, since these requests can originate from a client. For example, if the request context contains `request.CtxProtocol` equal to `cluster`, but the `request.ForwardedProtocol` is `tls`, the forwarded request currently has admin privilege. In contrast, #12313 will extract the `request.ForwardedUsername` and authenticate with that. This is not only much safer, it is also necessary in order to perform filtering of resources where these need to be collected from other cluster members (operations).
This leads to a problem with this test: https://github.com/canonical/lxd/blob/6ab06f9dc9f73b458ab8acd6843ea91d089d6f5d/test/suites/clustering.sh#L1878-L1954 …

lxd: Update certificate cache again after cluster join.

---

doc/.sphinx/_extra/rest-api.yaml
doc/rest-api.yaml

Cherry-pick this fix to 4.0 as well.

[Stable-4.0] doc: fix symbolic link to rest-api.yaml after moving the directory

---

.golangci.yml
Makefile
staticcheck.conf

This flags a bunch of interesting things among which are when deprecated functions are used. It uses the Go version from `go.mod` which is why it wouldn't have caught the `ioutil` bits from #12400 as those are not deprecated in Go 1.18.
I tried different approaches like the `dominikh/staticcheck-action` or the `golangci-lint` integration. I ruled out the GitHub Action as I assumed you wanted something to use locally too. The `golangci-lint` integration is not endorsed by `staticcheck` upstream and isn't really reliable nor intuitive.
So I went for this additional target that isn't run as part of `make static-analysis` because it flags too much (interesting) stuff for me to tackle now.

Add staticcheck target

---

lxd/instance/drivers/driver_lxc.go

Cgroup storage limits are not applied when the container starts up. That
is because `IsRunning` returns `false` during the container startup.
This commits fixes this issue by relying on `InitPID` instead of
`IsRunning`. The former will return a positive integer if the container
is running even if the container is not fully set up yet.
Fixes #12343

lxd/instance/drivers: Check running status with `InitPID` for cgroups

---

lxc/remote.go
test/suites/remote.sh

Ensure the remote connection using simplestreams is valid before adding it

---

lxc/remote.go
test/suites/remote.sh

Reverts #12442 as it prevented adding simplestreams remotes.

Revert "Ensure the remote connection using simplestreams is valid before adding it"

---

doc/custom_conf.py

There are currently some issues with the MAAS documentation. To prevent the link checker from complaining, temporarily exclude those links from the checks.

doc: temporarily ignore MAAS links

---

client/connection.go
client/lxd_server.go
lxc/config/file.go
lxc/config/remote.go
lxc/remote.go
lxd-agent/api_1.0.go
lxd-migrate/main_migrate.go
lxd-migrate/utils.go
lxd/api_1.0.go
lxd/daemon.go
shared/api/auth.go

Adds constants for authentication methods and replaces instances of `"tls"`, `"candid"`, and `"oidc"` where appropriate. This was requested for #12252 (https://github.com/canonical/lxd/pull/12252#discussion_r1369846524) but I'd rather not make that PR any larger.

Authentication method constants

---

lxd/migration_connection.go
lxd/storage_volumes.go
lxd/util/http.go
shared/cert.go
shared/network.go

None of the callers of `GetTLSConfig()` provide any client cert, key or CA files, so drop those args.

Drop `GetTLSConfig()` unused args

---

lxd/instance/drivers/driver_qemu.go

While this sha1 usage is perfectly fine as it's not used for its security properties, there is no downside to using sha256 instead. On the other hand, not using sha1 anywhere makes auditing this part trivial.

lxd/instance/driver/qemu: replace sha1 by sha256 in blockNodeName()

---

client/lxd_storage_volumes.go
doc/api-extensions.md
doc/rest-api.yaml
lxd/db/storage_volumes.go
lxd/storage_volumes.go
shared/api/storage_pool_volume.go
shared/version/api.go

Support server side copy/move of custom storage volumes in clusters

---

README.md

Please consider also addressing the LXC link on the https://documentation.ubuntu.com/lxd/en/latest/explanation/security/ page.

readme: reference Ubuntu's LXD security page

---

go.mod
go.sum
lxc-to-lxd/transfer.go
lxd-migrate/transfer.go
lxd/api_1.0.go
lxd/apparmor/rsync.go
lxd/auth/oidc/oidc.go
lxd/bgp/server.go
lxd/daemon.go
lxd/db/warnings.go
lxd/device/gpu_mdev.go
lxd/events/devlxdEvents.go
lxd/events/events.go
lxd/firewall/drivers/drivers_nftables.go
lxd/instance/drivers/driver_common.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/instance_utils.go
lxd/instance_put.go
lxd/operations/operations.go
lxd/rsync/rsync.go
lxd/storage/drivers/driver_btrfs_utils.go
lxd/storage/drivers/driver_btrfs_volumes.go
lxd/storage/drivers/driver_ceph_utils.go
lxd/storage/drivers/driver_ceph_volumes.go
lxd/storage/drivers/driver_zfs_utils.go
lxd/storage/drivers/driver_zfs_volumes.go
lxd/storage/s3/miniod/miniod.go
shared/validate/validate.go
test/rbac/auth.go

This effectively removes `github.com/pborman/uuid` from the list of dependencies and moves `github.com/google/uuid` to be a direct dependency. It's already included as an indirect dependency from other packages.
The package `github.com/pborman/uuid` leverages `github.com/google/uuid` itself. See the projects README for more details.

gomod: Switch UUID package

---

lxd/patches.go

This changes `partchStorageRenameCustomISOBlockVolumes` to ensure that,
in clustered environments, only the leader renames the volumes.

lxd/patches: Ensure renaming is only done on cluster leader

---

test/suites/operations.sh

The `get_operations` test is failing for me on main because the result of `lxc query /1.0/operations?all-projects=true` is empty when there are no operations. If this is a problem with LXD and not just the test please let me know!

test/suites: Fixes wait_no_operations helper.

---

doc/explanation/instances.md
doc/howto/images_create.md
doc/index.md
doc/instances.md
doc/projects.md
doc/restapi_landing.md

Some ubuntu.com pages recently started returning errors when trying to retrieve the page title.
Until this is fixed, work around this problem by explicitly specifying the title for related links.

doc: add page title for related links

---

lxd/main_forksyscall.go
lxd/seccomp/seccomp.go

Ported from https://github.com/lxc/incus/pull/197
This PR fixes an issue of `mount` syscall interception when `security.syscalls.intercept.mount.shift` is `true` and we mount block-device based filesystem inside the container (with a new superblock, not bindmount). Without this PR only bindmount case works properly in combination with enabled `security.syscalls.intercept.mount.shift`.

Fix idmapped mount layer on intercepted mounts

---

lxd/config/map.go
test/suites/config.sh

When unsetting a config key, the value should be reset correctly to
the default value.
Fixes #12478

config: Ensure config key values are reset to their default

---

lxd/instance/drivers/driver_lxc.go

When a memory limit is applied to an instance and swap is available on the system, the limit should apply to both memory and swap.
Without it, each instance would be allowed to go over the memory limit by as much as the total system swap space.

instance/lxc: Fix swap limit handling

---

lxd/instance/drivers/driver_lxc.go
lxd/metrics/metrics.go
lxd/metrics/metrics_test.go
test/suites/metrics.sh

This changes the Merge function to apply any missing labels from the
receiver to all samples from the argument.
This fixes an issue where filesystem stats would be missing certain
labels which were not explicitly set for the filesystem stats metric
set.

metrics: Fix label merging in metric sets

---

lxd/device/proxy.go

These too are reachable from the host, just like bridged NIC ones.

lxd/device/proxy: Consider routed NIC IPs for wildcard target check

---

lxd/device/proxy.go

These too are reachable from the host, just like bridged NIC ones.

lxd/device/proxy: Consider routed NIC IPs for wildcard target check (stable-5.0)

---

doc/howto/instances_troubleshoot.md
doc/howto/network_ovn_setup.md
lxd/devlxd.go
test/suites/basic.sh
test/suites/clustering.sh
test/suites/config.sh
test/suites/devlxd.sh
test/suites/image_acl.sh
test/suites/storage_snapshots.sh

While not strictly required, it is best practice to use it.

Always use `--` with `exec delimiter`

---

lxd/config/map.go
test/suites/config.sh

This restricts `user.*` keys to only include letters, digits, and punctuation characters.
Fixes #12308

Restrict user.* keys

---

lxc/storage_volume.go
test/suites/storage_local_volume_handling.sh

This fixes a regression introduced in https://github.com/canonical/lxd/pull/12348. When the target project flag is set don't use the function for renaming volumes.
Fixes https://github.com/canonical/lxd/issues/12518

lxc: Use volume copy when moving to target project

---

lxd/auth/driver_tls.go
lxd/daemon.go
test/suites/pki.sh

This PR cherry-picks fixes from https://github.com/lxc/incus/pull/221 which prevented TLS authorization when using CA certificates.
I have added an extra commit to enforce that a user is authenticated before calling the access handler.

Trust ca certs

---

lxd/instance_exec.go

Keepalives aren't particularly useful on Unix sockets, and it seems that there are some issues with them sometimes being written but not read: this means that processes launched via `lxc exec` can sometimes eventually hang because a websocket buffer fills up, causing an attempt to send a keepalive to return `EAGAIN`, causing LXD to give up on mirroring output from the corresponding file descriptor, and thus eventually causing subprocesses to hang when the buffer for their standard output/error fills up in turn.
I've observed this particularly on slower architectures such as riscv64 and arm64 in the context of non-interactive `lxc exec` via `launchpad-buildd`, though I don't quite know the exact set of triggers and so don't have a minimal test case - the best I have is building a snap from …

lxd/instance/exec: Only use keepalives on TCP sockets

---

lxd/storage/drivers/driver_btrfs.go
lxd/storage/drivers/driver_btrfs_utils.go
test/suites/storage_driver_btrfs.sh

This fixes an issue where btrfs pools whose source is a subvolume outside of the pool mount path would fail being created.
However, as this scenario is totally valid, it should be handled correctly.
Fixes #12496
Fixes regression from https://github.com/canonical/lxd/pull/12258/commits/7ebca54656208a4d24f7fd488271d677b8882c16

btrfs: Handle pools whose source is a subvolume outside of the pool mount path

---

client/interfaces.go
client/lxd_instances.go
shared/ws/mirror.go

This changes the Stdout and Stderr fields to be of type io.Writer
instead of io.WriteCloser since `Close()` is never called on these
fields.
Fixes #12197

client: Use io.Writer for Stdout/Stderr in InstanceExecArgs

---

lxd/instance/drivers/driver_qemu.go

Force 4MB edk2 firmware for existing VMs with 2MB firmware

lxd/instance/drivers/driver_qemu: force 4MB UEFI firmware in snap

---

shared/network_unix.go

If LXD failed to pick up system certs from `/etc/ssl` via `x509.SystemCertPool` (https://pkg.go.dev/crypto/x509#SystemCertPool and https://cs.opensource.google/go/go/+/master:src/crypto/x509/root_linux.go) then it would try to read `/var/lib/snapd/hostfs/etc/ssl`, which is itself symlinked to `/etc/ssl` in the LXD snap confinement. 
As of https://forum.snapcraft.io/t/custom-certificate-support/28168, snaps should be able to read `/etc/ssl` directly, so this makes the second check redundant. Additionally, any other snap using `ConnectLXD` should be able to read the system certs as well, though they may fail to read `/var/lib/snapd/hostfs`.

Read system certs directly from `/etc/ssl`

---

doc/config_options.txt
lxd/instance/drivers/driver_qemu.go
lxd/metadata/configuration.json
shared/instance.go

This option enables Qemu to use debug version of EDKII firmware.
The story behind this is that we have seen many reports from the community about weird and hardly reproducible issues or reproducible on some specific systems and having debug version of the EDKII seems like a good solution so users can easily enable it and provide us with more details.
LXD will expect that firmware named as OVMF_CODE.4MB.debug.fd and all the debug output will be captured and written to the file edk2.log (inside the $LXD_DIR/logs/<instance_name> directory).
Usage as simple as:
lxc config set myvm boot.debug_edk2=true
and then inspect logs:
cat /var/snap/lxd/common/lxd/logs/myvm/edk2.log

lxd/instance/drivers/driver_qemu: add the boot.debug_edk2 option

---

doc/installing.md

doc/installing: LXC_DEVEL needs to be fixed on 22.04+

---

client/lxd_containers.go
client/lxd_instances.go
lxc/exec.go
lxd/instance_exec.go
shared/ws/mirror.go

Following on from @cjwatson PR https://github.com/canonical/lxd/pull/12530 that disabled websocket level ping messages when using Unix sockets, this PR re-enables them for the purposes of trying to identify whether the same issues exist when using TCP sockets and trying to fix the issue more generally.
We will test this PR with the Launchpad folks before moving this to latest/stable.
This PR:
1. Closes websockets on the client as they finish reading/writing rather than keeping them open until all sockets have finished.
2. Consumes ping messages being sent from the LXD server over the control and stdin websocket channels. This wasn't happening before this PR because there wasn't an expectation of receiving messages from the LXD server on the control and stdin channels (only data from the …

Exec cleanup improvements

---

lxd-agent/main_agent.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/drivers/driver_qemu_config_test.go
lxd/instance/drivers/driver_qemu_templates.go

This PR updates the name of ring buffer from `org.linuxcontainers.lxd` to `com.canonical.lxd`.
With this change in place, restart of existing VMs will be required. Otherwise, (old) lxd-agent will write data to the `org.linuxcontainers.lxd` qemu serial device that is not connected to the new ring buffer from which lxd server will try to read. After VM is restarted, new lxd-agent will be copied from the shared host filesystem to the VM.
Fixes #12149

Rename ring buffer to com.canonical.lxd 

---

.github/dependabot.yml

As found by @roosterfish we need to duplicate the `updates` config to have the 2 branches covered by Dependabot. This is also what another project does (https://github.com/paritytech/parity-bridges-common/blob/master/.github/dependabot.yml#L124) and it works for them as Dependabot opened 2 PRs, one for their `master` branch and another for their `polkadot-staging` one:
https://github.com/paritytech/parity-bridges-common/pull/2714
https://github.com/paritytech/parity-bridges-common/pull/2715

github: instruct dependabot to also look after the stable-5.0 branch

---

.github/dependabot.yml

This might be useful to push out more point releases to 4.0 whenever one of our dependency gets a security fix.

github: instruct dependabot to also look after the stable-4.0 branch

---

lxd/instance/drivers/driver_qemu.go

In the LXD snap we ship a patched version of the CSM edk2 firmware. Implementation is in the patch ("edk2: force CSM boot mode for bootorder").
Idea behind this is to be able to apply boot priority configuration for CSM boot mode. While it works perfecly well for UEFI boot mode, it does not work with CSM mode. It means that CSM boot options are always come after UEFI boot options, and even worser, manual changing of the UEFI configuration does not help because bootorder setting are always reset during reboot of the VM (edk2 maintains bootorder settings in agreement with what Qemu supplies using fw_cfg "bootorder" interface).
Usage example:
Suppose that you have a "iso" disk device:
lxc config device add myvm iso disk source=/fullpath/to.iso
And you want to choose it as a first option:
$ …

VM: Support bootorder in edk2 CSM mode

---

doc/api-extensions.md
doc/reference/storage_cephfs.md
lxd/storage/drivers/driver_cephfs.go
lxd/storage/drivers/driver_cephfs_utils.go
shared/version/api.go
test/suites/storage_driver_cephfs.sh

Adds the config keys:
* `cephfs.create_missing`
* Creates the filesystem and the necessary data and metadata OSD pools if they don't exist
* `cephfs.osd_pg_num`
* Specifies the pg_num for the OSD pools that are created with `create_missing`. If unset, will default to 32.
* `cephfs.meta_pool`
* `cephfs.data_pool`
* Specifies the respective names of the metadata and data OSD pools to expect if we need to create the filesystem with `create_missing`. If these OSD pools already exist, then they will be re-used, otherwise they will be created.
If any of the above keys are set but the `fs` already exists, then the creation will error out.

Optionally create entities for `cephfs` storage pool

---

lxd/instance/drivers/driver_qemu.go
lxd/project/permissions.go
lxd/storage/backend_lxd.go
lxd/storage/drivers/driver_btrfs.go
lxd/storage/drivers/driver_ceph.go
lxd/storage/drivers/driver_cephfs.go
lxd/storage/drivers/driver_dir.go
lxd/storage/drivers/driver_lvm.go
lxd/storage/drivers/driver_mock.go
lxd/storage/drivers/driver_types.go
lxd/storage/drivers/driver_zfs.go
lxd/storage/drivers/volume.go

To accommodate the Dell PowerFlex storage driver, the default size for VM block filesystems should be exported directly through the storage driver. This allows changing the default size per driver and removes the burden of having internal driver knowledge outside of the `lxd/storage` package.
The projects instance limits accounting requires a follow up since the total value will be incorrect in case of the PowerFlex driver. See this issue for later reference: https://github.com/canonical/lxd/issues/12567.

Use default VM block filesystem size from driver

---

doc/howto/instances_create.md

Fix missing `<pool>` parameter in volume import command in docs (boot from iso section).

Update iso import in instances_create

---

doc/howto/instances_create.md

#12572 fixed the missing pool name in the storage volume import command. It added the pool as `<pool>`. However the next command uses the `default` pool. I've changed this to `<pool>` to make it consistent.

doc/howto: Make pool name consistent in iso tutorial.

---

lxd/storage/drivers/driver_btrfs_utils.go

#12258 Added an optimisation to the btrfs storage driver to use `btrfs subvolume list` instead of traversing the file structure when listing subvolumes. 
Unfortunately this may fail due to a permission error when using `btrfs` on `btrfs`. This commit reverts to using the previous method if `btrfs subvolume list` fails.
Closes #12555

Revert to filepath traversal if subvolume list fails

---

doc/howto/instances_create.md

Follow-up to #12574 and #12572 - use `<pool>` as the pool name instead of `default`.

doc/instances: change pool name to be consistent

---

lxd/instance_post.go
test/main.sh
test/suites/container_move.sh

This PR fixes the behavior of #12412 where root disk device is moved if different one is specified by new profiles.
Root disk device is now always retained unless the user explicitly specifies it using `--storage` flag.
Example:
```sh
$ lxc project create p1
$ lxc storage create test zfs
$ lxc profile device add default root disk pool=test path=/ --project p1
$ lxc init ubuntu:22.04 c1
$ lxc move c1 --target-project p1
$ lxc config show c1 --project p1
```

Retain root disk device when moving an instance to different project

---

lxd/instance/drivers/driver_qemu_cmd.go

Currently, when VM is halted, an error including operation URL is displayed to the user.
~Instead of returning an entire error we return just EOF (so that error can still be detected on the client's side).~
Return no error if error is of type EOF.
Fixes #12511

VM: Strip noisy eof error when lxd-agent disconnects during exec session

---

.github/workflows/tests.yml

The goal it to avoid this sort of error https://github.com/canonical/lxd/actions/runs/7079803622/job/19269110476?pr=12588:
```
+ curl -s https://api.github.com/repos/openfga/openfga/releases/latest
+ jq -r '.assets | .[] | .browser_download_url | select(. | test("_linux_amd64.tar.gz$"))'
+ xargs -I '{}' curl -L '{}' -o openfga.tar.gz
jq: error (at <stdin>:1): Cannot iterate over null (null)
++ go env GOPATH
+ tar -xzf openfga.tar.gz -C /home/runner/go/bin/
tar (child): openfga.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
Error: Process completed with exit code 2.
```

github: have curl fail instead of feeding bogus data on download error

---

lxd/instance/drivers/driver_qemu.go

In case a Ceph RBD gets added to the instances qemu config, the correct content type needs to be taken in order to generate the right volume name including it's specific suffix for either block or ISO drives.

Set correct RBD content type for qemu drives

---

lxd/db/instances.go

I've noticed that when generating an instance name ([lxd/instances_post.go#1005](https://github.com/canonical/lxd/blob/main/lxd/instances_post.go#L1005-L1008)), existing instance names are not respected. The issue seems to be in `GetInstanceNames()` which fetches instance names from a given project with type `Any`.
Since instance type `Any == -1`, no instance names are fetched.
---
Example sql queries (for `default` project):
```sh
$ lxd sql global 'SELECT instances.name FROM instances JOIN projects ON projects.id = instances.project_id WHERE projects.name = "default" AND instances.type = "-1"'
+------+
| name |
+------+
+------+
$ lxd sql global 'SELECT instances.name FROM instances JOIN projects ON projects.id = instances.project_id WHERE projects.name = "default" AND instances.type = …
```

Fix instance name generation not respecting existing instances

---

lxd/cluster/membership.go

When lots of nodes are joining the dqlite cluster concurrently, there's a good chance that some of these nodes will reach out to the leader in the middle of a role-change. `go-dqlite` will fail to add the node to the cluster, and LXD doesn't recover cleanly from this, resulting in LXD on the joining node basically fully locking up, and being unrecoverable on a restart as well.
go-dqlite errors out here because the underlying request to dqlite is reporting a `SQLITE_BUSY` error with the message `a configuration change is already in progress`. We can infer from this error (and also `go-dqlite`'s own handling of cluster joins) that we should keep trying to join the cluster until it either succeeds or we receive some other error.
To that end, this PR adds a `clusterBusyError` sentinel error …

Fix LXD lock-up on concurrent cluster joins.

---

test/suites/container_devices_disk.sh

This fix avoids running into the issue of having a `LXD_BACKEND=random` but being zfs underneath leading to a failure of `test_container_devices_disk` for a zfs version not being greater of equal to `2.2` (official support for idmapped mounts for ZFS). Now, we read the `${lxddir}/lxd.backend` (and not the env variable) to be certain  of that.

test: if backend is ZFS (also through random backend) and version less than 2.2, skip idmapped mount

---

lxd/apparmor/instance_qemu.go

This is going to be necessary once https://github.com/canonical/lxd-pkg-snap/commit/dd708ada26e490e0e782e5c3af23b9bd3538e8a7 is promoted to `latest/stable` for qemu to be able to access the path to `ceph.conf` created by the snap content interface, rather than directly symlinking to the state directory of MicroCeph.

lxd/apparmor: Allow qemu access to microceph conf

---

lxd/storage/s3/miniod/miniod.go

Fixes https://github.com/canonical/lxd/issues/12586
In case MinIO gets enabled on a system with IPv6 disabled, binding to the IPv6 localhost address during port discovery will fail due to an unsupported address family.

Discover MinIO port using IPv4 address family

---

lxd-agent/api_1.0.go

Prevent panic when devlxd server is stopped on VM with `security.devlxd=false`.
Fixes #12629

 Prevent panic when devlxd server is stopped

---

client/lxd_containers.go
client/lxd_instances.go

When long polling the operation wait endpoint, we can never guarantee that the request will not time out for very long operations (e.g. an exec session) because intermediate proxies or load balancers may timeout the request if there is no activity. This commit changes the `useEventListener` argument to getOperations to true for all requests. Regardless of whether the `operation_wait` API extension is present.

client: Always use event listener for operations.

---

lxd/operations.go
lxd/response/response.go

When calling `/1.0/operations/{id}/wait` the client times out for long requests. This is because we were not setting `keep-alive` headers before waiting for the operation. These commits are cherry picked from incus.

Set keep-alive headers early in operation wait handler

---

lxd/instance/drivers/driver_qemu.go

This was caused by https://github.com/canonical/lxd/pull/12566. 
When validating the live migration of a VM, the pool needs to be loaded first since that is the first time the value gets accessed. Otherwise it will panic.

Fix VM live migration regression in edge

---

.golangci.yml
Makefile
lxd/firewall/drivers/drivers_nftables.go
test/lint/golangci.sh

This PR adds the [`revive`](https://github.com/mgechev/revive) linter to our golangci-lint configuration.
Unfortunately there are thousands of lint errors. To ensure that no new errors enter the code base I have added a script to invoke golangci-lint so that it only evaluates commits between HEAD and revision of the most recent commit in the target branch.
We should still strive to fix the existing lint errors, but it's quite a time sink.
Creating as draft so I can ensure it all works in CI. Will mark as ready when it's all passing and request a review.
Edit: Note that this change will mean that invoking `golangci-lint run` directly in the repo will fail.

Adds the revive linter.

---

client/lxd_instances.go

Inspired by @MusicDin #12633 but with some changes.
Fixes #12636
Closes #12633

client: Discard non-interactive stdout/stderr output if writer(s) not supplied in ExecInstance

---

doc/howto/storage_pools.md
doc/reference/storage_cephfs.md

You can now automatically create the required file system and pools when setting up a CephFS storage pool.

doc/storage/cephfs: specify that you can automatically create pools

---

AUTHORS
CONTRIBUTING.md
COPYING
doc/.wordlist.txt
doc/index.md
doc/rest-api.yaml
lxd/swagger.go

Canonical has decided to change the default contributions to the LXD project to AGPLv3 to align with our standard license for server-side code. All Canonical contributions have been relicensed and are now under AGPLv3. Community contributions remain under Apache 2.0. We follow the Software Freedom Law Center [guidance](https://softwarefreedom.org/resources/2007/gpl-non-gpl-collaboration.html) in relation to this. Going forward, any contribution to LXD will be made under AGPLv3 by default. The author of a change remains the copyright holder of their code (no copyright assignment).
It is important to note this change does not prevent our users from using, modifying, or providing LXD-based software solutions, provided that they share the source code if they are modifying it and making it …

Change license to AGPLv3

---

README.md
doc/config_options.txt
doc/explanation/security.md
lxd/metadata/configuration.json
shared/instance.go

Include essential information instead of just linking to the LXC security page.

doc/security: include info on privileged/unprivileged containers

---

doc/config_options.txt
lxd/api_project.go
lxd/metadata/configuration.json

Fixes https://github.com/canonical/lxd/issues/12591
The fact that it automatically assumes `security.idmap.isolated=true` if `restricted.containers.privilege` is set to `isoldated` seems a bit odd since it is not the default value. However saying that this is the default behavior should explain the config option more thoroughly.

Clarify restricted.containers.privilege config option

---

CONTRIBUTING.md
README.md
client/COPYING
shared/COPYING

Licenses the `shared` and `client` packages as Apache-2.0.

License Go SDK client as Apache-2.0

---

.github/workflows/tests.yml
test/lint/golangci.sh

Our CI is failing on push events because the `GITHUB_BASE_REF` only exists when running the action on a pull request. This adds some commits from incus which set a `GITHUB_BEFORE` environment variable from [github.event.before](https://docs.github.com/en/webhooks/webhook-events-and-payloads#push) to be used instead.

GitHub push event base ref

---

lxd/instance/drivers/driver_qemu.go

It was discovered (https://bugzilla.tianocore.org/show_bug.cgi?id=4588) that CSM module was removed from the edk2 which means that we have to switch on the scheme with using SeaBIOS firmware directly.
Recently we have been doing some debugging around edk2/CSM module issue that was preventing some Linux distros from booting (CentOS/Fedora ones). It was found, that issue lays in the BIOS call (INT 13h / 02h) that reads sectors from the disk. Just after this bios call gets called from the Linux kernel earlyboot code (https://github.com/torvalds/linux/blob/052d534373b7ed33712a63d5e17b2b6cdbce84fd/arch/x86/boot/edd.c#L33) something terribly wrong happens with the memory which makes Linux kernel execution to fail later on during the uncompression. It was also discovered that Debian/Ubuntu has …

lxd/instance/qemu: Start using seabios as CSM firmware

---

lxd/instance_post.go

Error out if instance with attached custom volumes is being live migrated.

Prevent live migration of instances with custom volumes

---

shared/idmap/idmapset_linux.go
test/suites/idmap.sh

Imagine container created with:
lxc launch ubuntu:j c1 -c raw.idmap="both 1000 1000"
Then "volatile.last_state.idmap" will be like:
[
{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000},
{"Isuid":true,"Isgid":true,"Hostid":1000,"Nsid":1000,"Maprange":1},          // <-- our custom idmapping
{"Isuid":true,"Isgid":false,"Hostid":1001001,"Nsid":1001,"Maprange":999998999},
{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000},
{"Isuid":true,"Isgid":true,"Hostid":1000,"Nsid":1000,"Maprange":1},          // <-- oops, 2nd time!
{"Isuid":false,"Isgid":true,"Hostid":1001001,"Nsid":1001,"Maprange":999998999}
]
This makes idmapset.ToUidMappings() output incorrect (because mapping will be reported 2 times) and breaks "lxc file push" functionality for containers …

shared/idmap: handle "both" idmappings in raw.idmap properly

---

lxd/daemon.go
lxd/task/group.go
lxd/task/group_test.go
lxd/task/start.go

Hopefully fixes #12540 by simplifying the calls to unlocking the mutex.
Even if it doesn't fix it, it should make it easier to reason about, rather than using defer unnecessarily.
Closes #12540

Task: Remove unnecessary calls to defer g.mu.Unlock()

---

lxd/rsync/rsync.go
test/suites/migration.sh

The rsync `--checksum` flag has a history in LXD which ultimately led to the fact that remote container copies can be faster than local ones:
1. https://github.com/canonical/lxd/commit/64fd7f913a5aa87ec074b5a89ae7eefd2dd0f147 initially added it in with the note `TODO: Not sure we need this option`.
2. https://github.com/canonical/lxd/commit/a88e667ccb09a2a00c95cbf5ff43ae79d9f69988 removed it since it is causing significant IO
3. https://github.com/canonical/lxd/commit/6518166f441269843a0c17250ce517c23af73341 added it back in since the rsync version 3.1.1 back then didn't had support for checking the files modification times on nanoseconds granularity
4. https://github.com/canonical/lxd/commit/47f4509457056b6011e2076288f43ebf2aac9a89 moved it into `lxd/rsync.go` without any changes
Today …

Use rsync flags consistently for local and remote copy

---

lxd/apparmor/archive.go
lxd/apparmor/network_dnsmasq.go
lxd/sys/apparmor.go

The unconfined profile mode adds ` (unconfined)` to the profile label and is now used in snapd for lxd since https://github.com/snapcore/snapd/pull/13333 was merged recently. lxd needs to treat this the same as the "unconfined" label used previously AND we also add a couple required signal rules and remove any peer restriction - this allows LXD to work as expected again in snapd.

lxd: Add support for apparmor unconfined profile mode

---

doc/config_options.txt
lxd/cgroup/abstraction.go
lxd/devices.go
lxd/instance/drivers/driver_lxc.go
lxd/metadata/configuration.json
scripts/bash/lxd-client
shared/instance.go

Remove deprecated instance config option limits.network.priority

---

Makefile
doc/.readthedocs.yaml

Sphinx creates an objects.inv file that contains a mapping of IDs and locations in the docs. The UI needs this mapping to be able to resolve links within the descriptions of config options.
The UI would require additional dependencies to decode the objects.inv file, so providing the decoded version with the documentation is easier.

doc: decode the objects.inv file

---

doc/config_options.txt
doc/reference/devices_disk.md
lxd/api_project.go
lxd/metadata/configuration.json

Clarify that you really should set `restricted.devices.disk.paths` when you set `restricted.devices.disk=allow`.
Fixes #12606.

doc/projects: clarify restricted.devices.disk

---

doc/.wordlist.txt
doc/cloud-init.md
doc/reference/devices_disk.md
lxd/instance/drivers/driver_qemu.go

This adds a workaround for the lack of `lxd-agent-loader` package in official (`ubuntu:` and `ubuntu-daily:`) images for releases before `20.04`.
This also document another workaround needed to have `lxd-agent` working on `16.04` images, namely use the `-hwe` kernel.

Use `cloud-init` to enable `lxd-agent` on Ubuntu releases before `20.04`

---

doc/api-extensions.md
doc/howto/initialize.md
doc/rest-api.yaml
lxd/init.go
shared/api/init.go
shared/version/api.go
test/suites/init_preseed.sh

Add support for configuring storage volumes in preseed init.
Fixes #10956

lxd/init: Add support for storage volumes in preseed init

---

doc/howto/images_manage.md

Add a small section regarding image deletion. I did not find it elsewhere

doc: Add paragraph on how to delete images

---

test/lint/golangci.sh

Previously this was only performed when the GITHUB_BEFORE environment variable was set.

test/lint: Always fetch the target branch if it cannot be found.

---

doc/api-extensions.md
lxd/api_metrics.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/drivers/driver_qemu_metrics.go
lxd/metrics/metrics.go
lxd/metrics/types.go
shared/version/api.go
test/suites/metrics.sh

Thomas' PR https://github.com/canonical/lxd/pull/12476 without the `metrics: Add LXD server info` commit https://github.com/canonical/lxd/pull/12476/commits/ece77a1ad3ea51524a8485d58753ea306293756e
This would fix https://github.com/canonical/lxd/issues/12333.

Add metrics for stopped instances

---

lxd/devlxd.go

Allow re-enabling `security.devlxd` for virtual machines.
Fixes #12656

Allow re-enabling security.devlxd (stable-5.0)

---

doc/api-extensions.md

It was likely introduced back when LXD only knew about containers.
This was tested by toggling `security.devlxd` on a VM and an container. In both cases, `/dev/lxd/sock` vanishes when `security.devlxd=false`.

doc/api-extensions: `security.devlxd` applies to both containers and VMs

---

doc/config_options.txt
doc/howto/cluster_config_storage.md
doc/reference/storage_btrfs.md
doc/reference/storage_ceph.md
doc/reference/storage_cephfs.md
doc/reference/storage_cephobject.md
doc/reference/storage_dir.md
doc/reference/storage_lvm.md
doc/reference/storage_zfs.md
lxd/metadata/configuration.json
lxd/storage/drivers/driver_btrfs.go
lxd/storage/drivers/driver_ceph.go
lxd/storage/drivers/driver_ceph_volumes.go
lxd/storage/drivers/driver_cephfs.go
lxd/storage/drivers/driver_cephobject.go
lxd/storage/drivers/driver_lvm.go
lxd/storage/drivers/driver_lvm_volumes.go
lxd/storage/drivers/driver_zfs.go
lxd/storage/drivers/driver_zfs_volumes.go
lxd/storage/utils.go

Fix the [Storage drivers](https://documentation.ubuntu.com/lxd/en/latest/reference/storage_drivers/)  configuration to be generated from the code. This means, for all storage drivers:
* Move the descriptions to the code
* Replace the table in the docs with an include from the generated options file
* Search and replace any links to those properties with a config reference
JIRA ticket: https://warthogs.atlassian.net/browse/LXD-441
blocked by: https://github.com/canonical/lxd/pull/12642

feat: annotate codebase for storage config options

---

doc/api-extensions.md
doc/rest-api.yaml
lxd/api_1.0.go
shared/api/server.go
shared/version/api.go
test/main.sh
test/suites/basic.sh

Add ServerEnvironment field for `instance_type` indicating which instance types are supported by the server.
```sh
node-1:~# lxc query /1.0 | jq '.environment | {server_name, instance_types}'
{
"server_name": "node-1",
"instance_types": [
"virtual-machine",
"container"
]
}
node-1:~# lxc query /1.0?target=node-2 | jq '.environment | {server_name, instance_types}'
{
"server_name": "node-2",
"instance_types": [
"virtual-machine",
"container"
]
}
c2:~# lxc query /1.0 | jq '.environment | {server_name, instance_types}'
{
"server_name": "c2",
"instance_types": [
"container"
]
}
```
API extension is named `server_instance_type_info`.

Indicate supported instance types when querying /1.0

---

lxd/storage/drivers/driver_ceph_volumes.go
test/suites/storage.sh

Ceph RBD snapshots are a read-only logical copy of the parent volume. Rewriting the filesystems UUID on the snapshot itself fails.
That was observed in https://github.com/canonical/lxd/pull/12743
Fixes https://github.com/canonical/lxd/issues/12744

Ceph RBD: Restore the filesystems UUID on the volume

---

doc/.wordlist.txt
doc/environment.md
lxd/apparmor/instance.go
lxd/apparmor/instance_qemu.go
lxd/instance/drivers/driver_qemu.go
lxd/util/sys.go

- We want our users to step out from EDK2-based CSM firmwares to SeaBIOS as these firmwares were removed from upstream (see https://bugzilla.tianocore.org/show_bug.cgi?id=4588).
- @tomponline suggested to extend firmware lookup algorithm to handle multiple paths specified in the `LXD_OVMF_PATH`.
- Do some renaming
- Forbid `security.csm` for arches except `x86_64`

Force SeaBIOS instead of OVMF-based firmware & some firmware lookup logic changes

---

doc/.sphinx/spellingcheck.yaml

Pyspelling has a new option to run jobs in parallel. This should make the spelling check considerably faster.

doc: enable multiprocessing for pyspelling

---

Makefile
test/lint/golangci.sh

For a nice explanation on various types of git clones: https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/
In our case, since we want `git log` to work, we need at least a treeless clone.
> git clone --filter=tree:0 <url> creates a treeless clone. These clones download all reachable commits while fetching trees and blobs on-demand. These clones are best for build environments where the repository will be deleted after a single build, but you still need access to commit history.

Improve `test/lint/golangci` script

---

Makefile
doc/.sphinx/spellingcheck.yaml

Use nproc to find the best number of jobs for parallel processing.

doc: use all processors for spelling check

---

test/lint/golangci.sh

The value of `github.event.before` is a revision, so prefixing it with "origin/" was causing the fetch to fail when ensuring the revision existed locally.

test/lint: Treat GITHUB_BEFORE as a revision.

---

client/lxd_certificates.go
client/lxd_cluster.go
client/lxd_containers.go
client/lxd_images.go
client/lxd_instances.go
client/lxd_network_acls.go
client/lxd_network_forwards.go
client/lxd_network_peer.go
client/lxd_network_zones.go
client/lxd_networks.go
client/lxd_projects.go
client/lxd_server.go
client/lxd_storage_buckets.go
client/lxd_storage_pools.go
client/lxd_storage_volumes.go
client/lxd_warnings.go

Replaces `HasExtension` with `CheckExtension` API extension checks.

Replace deprecated HasExtension checks

---

lxd/endpoints/network.go
shared/cert.go

CertInfo is used across several LXD-adjacent projects to store certs, but it really only allows populating from a filesystem or from a slice of bytes which results in a lot of back-and-forth conversions: https://github.com/canonical/lxd/blob/1f42fd0d4737210ad8447cef01580e968472f360/shared/cert.go#L48
This introduces a function that instantiates a new CertInfo with the given keypair/ca/crl parameters.

shared: Add helper for obtaining a CertInfo struct

---

lxd/auth/oidc/oidc.go

This PR implements the OIDC fixes that can be found in https://github.com/canonical/lxd/pull/12628 except for encryption of identity and refresh tokens when accessing LXD via the UI. This is because we are awaiting a security review (https://warthogs.atlassian.net/browse/SECQ-60?atlOrigin=eyJpIjoiMGM5MzRlZTc1ZTc2NDQ4ODkyYjc0ZGFiMGIyODZkNzMiLCJwIjoiaiJ9). 
Related to https://github.com/canonical/lxd/issues/12531

OIDC fixes (without encryption)

---

Makefile
doc/.sphinx/_templates/domainindex.html

Combining two different improvements into one PR because both rely on an update to https://github.com/canonical/canonical-sphinx-extensions/pull/33.
- Add some context to the output of the configuration option index to distinguish duplicate options (see https://canonical-ubuntu-documentation-library--12770.com.readthedocs.build/lxd/en/12770/config-options/#cap-storage)
- Speed up the build by enabling parallel processing

Doc improvements (config option index and build speedup)

---

Makefile
doc/config_options.txt
lxd/lxd-metadata/lxd_metadata.go
lxd/lxd-metadata/main.go
lxd/metadata/configuration.json

This fix enables the `lxd-metadata` tool to be able to do simple template rendering operations.
Any `{{(.*?)}}` in a longdesc field will now be rendered with its substitution value, if the inner substitution key is found. Else, this template will not be rendered.

lxdmetadata: connect a substitution database 

---

lxd/storage/drivers/driver_ceph_volumes.go
lxd/storage/drivers/driver_lvm_volumes.go

This PR adds missing functionality to also restore the VM block filesystem volumes during restore on LVM thinpools and Ceph RBD.
A bit of refactoring was required to ensure the reverter can also be applied when restoring on the LVM thinpool.

Restore the VM's filesystem volume on LVM and Ceph RBD

---

lxc/move.go

Contributed under Apache-2.0 License
Signed-off-by: Stéphane Graber <stgraber@stgraber.org>
Signed-off-by: Din Music <din.music@canonical.com>
(cherry picked from commit 6df2cd00c48834dab78710ccdc448f28b137d1c2)

lxc/move: Only use server-side move when dealing with a single server (stable-5.0)

---

.github/workflows/tests.yml

Using `--edge` is getting us reef which seems to be breaking on ubuntu 22.04 GH runners.
https://discourse.canonical.com/t/microceph-default-channel-update/3030

github: Pin microceph to quincy edge

---

test/lint/golangci.sh

This PR updates the `test/lint/golangci.sh` script to:
- Handle running locally more cleanly.
- Add the `--whole-files` flag (https://golangci-lint.run/usage/configuration/#command-line-options) which will help us incrementally fix existing lint errors.

Golangci whole files

---

.github/workflows/commits.yml

@tomponline I think a better fix would be to switch to the DCO app: https://github.com/apps/dco

github: check DCO last as it fails on big PRs

---

.golangci.yml

- Removes the "unused-receiver" rule. These are quite innocuous and more of a code smell than an indicator of a problem.
- Removes the "import-shadowing" rule. I think it's fine to shadow an import name especially in small scopes.
- Allows unchecked type assertions if the assertion result is explicitly ignored, e.g. v, _ := variable.(T). As this is enough to avoid a panic.

golangci: Remove/update some overly-pedantic revive lint rules.

---

README.md
doc/.readthedocs.yaml
doc/installing.md

While at it, update readthedocs config to use Go 1.21 (https://github.com/readthedocs/readthedocs.org/issues/10884)

Advertise snap sources

---

lxd/storage/drivers/driver_ceph_volumes.go
lxd/storage/drivers/driver_lvm_volumes.go
test/suites/storage_snapshots.sh

See https://github.com/canonical/lxd/pull/12743#issuecomment-1920746200
Due to https://github.com/canonical/lxd/pull/12745 that issue didn't surface.

Ceph RBD: Regenerate the FS UUID for filesystem volumes only

---

.golangci.yml
lxd/api_cluster.go
lxd/cluster/membership.go

Closes #12624 
Joining dqlite happens in the `Join` function under `lxd/cluster/membership.go` where we lock the global database, create raft node entries in the local database, and reload the gateway. If there's an issue on the dqlite end that prevents us from joining the cluster, we error out and return, but the database is still locked, and the gateway will still behave as though the node has joined the cluster. This leaves the node in an unrecoverable state as the node will perpetually wait for for connections to a cluster that it's not a part of.
To fix that, this adds some revert hooks that ensure the node returns to a state where we can tell it to re-join the cluster with a new join token. In particular, the revert hooks clear out the raft nodes in the local database, refresh the …

Revert database on joining node if cluster join fails

---

doc/rest-api.yaml
shared/api/certificate.go

The swagger documentation is currently incorrect. To generate slightly different examples in each case I had to duplicate the `Certificate` field on `CertificatesPost`. Please let me know if there is a better way to do this :grimacing:

Document that the `certificate` field is base64 on `POST /1.0/certificates`

---

lxd/api_1.0.go
lxd/api_cluster.go
lxd/auth/oidc/oidc.go
lxd/daemon.go

This PR encrypts the OIDC cookies that are set in the response after logging in to LXD. It finishes the implementation of changes to handling of OIDC authentication as discussed in #12531.
To ensure that the encryption key is the same on all cluster members, we are deriving the key from the cluster private key using [HKDF](https://pkg.go.dev/golang.org/x/crypto/hkdf). 
Closes #12531

Encrypt OIDC cookies

---

shared/simplestreams/products.go
shared/simplestreams/simplestreams.go

When support for Incus images was added in https://github.com/canonical/lxd/pull/12260 at the time the LinuxContainers remote contained both LXD and Incus entries and so a fix was added to stop searching for a file when a compatible one had been found during the parsing of the simplestreams index.
However this caused a bug when parsing the remote index for https://cloud-images.ubuntu.com/buildd/daily/streams/v1/com.ubuntu.cloud:daily:download.json because it contains both combined and non-combined image files for LXD.
In principle stopping after the first compatible image was found makes sense and is more efficient.
However LXD parses the simplestreams index (albeit cached) multiple times during a single image resolution process (once to convert alias to fingerprint and again to find the …

simplestreams: Fix regression when parsing indexes that contain both combined and non-combined variants

---

shared/simplestreams/products.go
shared/simplestreams/simplestreams.go

When support for Incus images was added in https://github.com/canonical/lxd/pull/12260 at the time the LinuxContainers remote contained both LXD and Incus entries and so a fix was added to stop searching for a file when a compatible one had been found during the parsing of the simplestreams index.
However this caused a bug when parsing the remote index for https://cloud-images.ubuntu.com/buildd/daily/streams/v1/com.ubuntu.cloud:daily:download.json because it contains both combined and non-combined image files for LXD.
In principle stopping after the first compatible image was found makes sense and is more efficient.
However LXD parses the simplestreams index (albeit cached) multiple times during a single image resolution process (once to convert alias to fingerprint and again to find the …

simplestreams: Fix regression when parsing indexes that contain both combined and non-combined variants (stable-5.0)

---

lxd/patches.go

This adds a patch to remove the `block.*` settings from VMs and custom volumes of type block in the LVM and Ceph driver. 
That is required after https://github.com/canonical/lxd/pull/12805 and follows the same procedure as in https://github.com/canonical/lxd/pull/12390.

Add patch to remove `block.*` settings from LVM and Ceph RBD block volumes

---

doc/howto/snap.md
doc/installing.md
doc/support.md

Update the docs to reflect 5.21 as the new LTS and 6.1 as the next feature release.
Also make sure that the installation commands use the correct channels, and mention that the default channel will be the LTS channel in the future.
@tomponline and @mionaalex, please make sure this is actually what we want.
It's a bit awkward since it isn't really true until 5.21 is released, and also then we don't have a 6.1 channel yet.

Doc: update versioning scheme and snap channels

---

shared/simplestreams/products.go

By merging https://github.com/canonical/lxd/pull/12834 it is now causing problems consuming `images:` remote because the stable-5.0 didn't get the change to stop searching for incus files from the `images:` remote (https://github.com/canonical/lxd/pull/12748/commits/0c9253da9448475e6de60dd345c67c0179884f13).
Confirmed that the images.linuxcontainers.org metadata is still giving out both incus (`"incus.tar.xz"`) and lxd (`"lxd.tar.xz"`) metadata entries, and so the revert from https://github.com/canonical/lxd/pull/12834 is now causing the original problem I was trying to work around.
```
"ubuntu:jammy:amd64:default": {
"aliases": "ubuntu/jammy/default,ubuntu/22.04/default,ubuntu/jammy,ubuntu/22.04",
"arch": "amd64",
"os": "Ubuntu",
"release": "jammy",
"release_title": "jammy", …
```

shared/simplestreams/products: Search only for lxd archives (stable-5.0)

---

lxd/auth/driver_tls.go
test/suites/tls_restrictions.sh

The TLS authorization driver was returning an error on calls to `GetPermissionChecker` when it should have been returning `allowFunc(false)` to indicate the user does not have the given entitlement on any resources of the given type. 
Closes #12846

Auth: TLS driver should return a false permission checker when client is restricted.

---

.github/ISSUE_TEMPLATE.md

@tomponline You'll probably pick up that `core24` is normally not yet on many systems but `snap list` just doesn't care as we can see:
```
$ snap list --all lxd core20 core22 core24 snapd
Name    Version      Rev    Tracking       Publisher   Notes
core20  20231123     2105   latest/stable  canonical✓  base
core22  20231123     1033   latest/stable  canonical✓  base
lxd     git-59a5a74  26985  latest/edge    canonical✓  disabled
lxd     git-def587b  27004  latest/edge    canonical✓  -
snapd   2.61.1       20671  latest/stable  canonical✓  snapd
```

github: ask bug reporters to provide the list of relevant snaps

---

lxd/endpoints/network_util.go
lxd/endpoints/network_util_test.go

Cherry picked from https://github.com/lxc/incus/pull/296

Hide read errors from proxies

---

test/suites/tls_restrictions.sh

Follow up to #12848 (see https://github.com/canonical/lxd/pull/12848#discussion_r1484133257)

test/suites: Ensure restricted certs cannot view storage pool config.

---

lxd/storage/drivers/generic_vfs.go

This fixes a regression caused in https://github.com/canonical/lxd/pull/12852/files#diff-30511c7ce3bcabd6a4ddc8624541cc2f5240a13b5e3b19aac8c787fdbd0e4720.
Due to the refactoring it doesn't anymore exit the loop but instead falls back to printing the `"Could not find %q"` after unpacking.

lxd/storage/drivers/generic_vfs: Return if the right file was found

---

test/lint/golangci.sh

This flag was added with the intention that we will slowly improve the quality of the code-base. Some current features are under significant time pressure and affect a large portion of the code base, and this flag is quite prohibitive.
It will still not be possible to add new code that causes lint errors.

test/lint: Temporarily remove `--whole-files` flag.

---

client/lxd_oidc.go
doc/api-extensions.md
doc/config_options.txt
lxd/api_1.0.go
lxd/auth/oidc/oidc.go
lxd/certificates.go
lxd/cluster/config/config.go
lxd/cluster/connect.go
lxd/daemon.go
lxd/db/cluster/identities.go
lxd/metadata/configuration.json
lxd/operations.go
lxd/request/const.go
shared/api/auth.go
shared/version/api.go
test/suites/oidc.sh

This PR adds a new server configuration key `oidc.groups_claim`. If set, the value of this config key is:
1. Added to the `scope` of the Authorization Code Flow (UI).
2. Sent to the client as an `X-LXD-OIDC-groups-claim` header, to be added to the scope for the Device Authorization Grant Flow (CLI).
3. The value of the claim represents the groups that the identity is a member of at the identity provider level. It is extracted from both identity tokens (UI) and access tokens (CLI) and is expected to be a string slice.
4. Identity provider groups are added to the request context.
5. Identity provider groups are forwarded to other cluster members in the `X-LXD-forwarded-identity-provider-groups` header. The value of this header is a JSON encoded string.
6. Forwarded identity provider groups …

Auth: Add OIDC identities to identity cache and extract identity provider groups

---

doc/api-extensions.md
doc/config_options.txt
grafana/LXD.json
lxd/api_1.0.go
lxd/cluster/config/config.go
lxd/daemon.go
lxd/loki/loki.go
lxd/metadata/configuration.json
shared/version/api.go

If/when merged, this will require to upload the updated Grafana dashboard to Grafana's website.

Add support for `loki.instance` from Incus

---

client/lxd_oidc.go
lxd/api_1.0.go
lxd/auth/oidc/oidc.go
lxd/daemon.go
lxd/db/cluster/identities.go
lxd/identities.go
lxd/identity/cache.go
test/includes/oidc.sh
test/mini-oidc/main.go
test/suites/oidc.sh

This was deliberated in a meeting with the identity team and some folks working on Juju (JIMM). It turns out that it is possible for the OIDC subject to change when using some identity brokers (e.g. keycloak) in certain circumstances. JIMM are using email addresses translated into UUIDs for their users.
Changing the unique identifier to email from OIDC subject has a few benefits for us:
1. It will be easier to use in the API (e.g. `GET /1.0/auth/identities/oidc/jane.doe@example.com`).
2. Group membership (and therefore permissions) will persist even if an administrator changes the configured OIDC provider for LXD.
However, email addresses are not present in the access tokens that are sent as bearer tokens when using the client. To work around this. This PR does the following:
1. Stores …

Auth: Use email address as identifier for OIDC users.

---

.github/workflows/tests.yml

Essentially do what `strip -s` does but using just `go build` as `strip` couldn't work on foreign arches (arm64 bins compiled on amd64).
This leads to smaller artifacts for Chocolatey and also produces smaller artifacts attached to each test runs.

Smaller lxc and lxd-migrate binaries

---

.github/workflows/tests.yml
doc/.readthedocs.yaml

Due to an error on my part (sorry about that), my latest changes didn't go in #12883 so here they are.
This version does a proper job of generating smaller binaries on all OSes and for all arches.

Smaller clients bis

---

lxd/storage/backend_lxd.go
lxd/storage/drivers/driver_btrfs_volumes.go
lxd/storage/drivers/driver_ceph_volumes.go
lxd/storage/drivers/driver_cephfs_volumes.go
lxd/storage/drivers/driver_common.go
lxd/storage/drivers/driver_dir_volumes.go
lxd/storage/drivers/driver_lvm_utils.go
lxd/storage/drivers/driver_lvm_volumes.go
lxd/storage/drivers/driver_mock.go
lxd/storage/drivers/driver_zfs_volumes.go
lxd/storage/drivers/generic_vfs.go
lxd/storage/drivers/interface.go
lxd/storage/drivers/volume.go

This is a requirement for https://github.com/canonical/lxd/pull/12840 in order to be able to pass down volume's information like the upcoming snapshot's `volatile.uuid` field into the respective storage driver.
The new struct `VolumeCopy` contains not only the volume that requires modification but also all of its snapshots as they were created in the database.
The already existing approach of identifying snapshots that require a refresh is kept. Only for `CreateVolumeFromCopy` the `copySnapshots` field got removed as this information can now be retrieved by checking if the target volume has any snapshots.
Having this information present in the storage drivers allows driver internal logic to access resources that were previously hidden from the driver. That is especially useful for the …

Support passing down extra information to storage drivers

---

lxd/instance/drivers/driver_qemu.go

Cherry picked from https://github.com/lxc/incus/pull/489

Instance: Handle SELinux for VM LXD agent

---

lxd/storage/backend_lxd.go

The final `snapshotStorageName` contains the projects identifier twice if the storage name used to create the vol is used a second time:
```go
// Already using the volStorageName including the project
vol := b.GetVolume(volType, contentType, volStorageName, volumeConfig)
...
// Produces project_project_vol/snapX since vol.Name() already includes the project
snapshotName := drivers.GetSnapshotVolumeName(vol.Name(), volSnap.Name)
snapshotStorageName := project.Instance(srcBackup.Project, snapshotName)
```
This didn't surface since the `genericVFSBackupUnpack()` function where this is used initially created its snapshot `Volume` construct from the snapshot names passed into the function. For https://github.com/canonical/lxd/pull/12840/ this changes since the snapshot `Volume`s passed into …

Storage: Don't use storage name when creating source snapshots

---

doc/reference/devices_disk.md
doc/reference/devices_nic.md

Add configuration examples for NIC devices, and move the configuration examples for disk devices to a separate section to make it consistent.

Doc: Add some device examples

---

lxd/db/generate/db/method.go

LXD generate cannot create update method for associative tables if the reference table has more than one "natural key" or if it doesn't have a field called 'Name' or 'Fingerprint'. In the former case it will fail silently (generating incorrect methods). In the latter case it will panic.
This commit returns a helpful error message instead.
I encountered this when trying to generate methods to associate groups to identities and vice-versa. Identities are keyed on authentication method and identifier. I will just write custom queries to update those relations instead.

lxd-generate: Return helpful error instead of panicking.

---

lxd/migrate_storage_volumes.go
lxd/storage/backend_lxd.go
test/suites/migration.sh
test/suites/snapshots.sh
test/suites/storage_local_volume_handling.sh
test/suites/storage_snapshots.sh

When generating a custom volume's backup config, make sure it's creation date is included in the struct. This is currently causing snapshots of copied volumes to not have any creation date:
```bash
julian@thinkpad:~/dev/lxd/test$ lxc storage volume show dir vol2/snap0
expires_at: 0001-01-01T00:00:00Z
name: snap0
config: {}
content_type: filesystem
created_at: 0001-01-01T00:00:00Z
```
Additionally this change ensures that when refreshing custom storage volumes and their snapshots, LXD does not re-transfer all of the snapshots. This was caused by:
* the migration header protocol not sending the snapshots creation date
* and the comparison on the target side using different granularity for both source and target timestamps
This PR adds a check for both custom storage volume …

Storage: Populate custom volume snapshot creation date

---

doc/api-extensions.md
doc/config_options.txt
lxd/metadata/configuration.json
lxd/patches.go
lxd/storage/backend_lxd.go
lxd/storage/drivers/generic_vfs.go
lxd/storage/drivers/volume.go
lxd/storage/utils.go
shared/version/api.go
test/suites/backup.sh
test/suites/migration.sh
test/suites/snapshots.sh
test/suites/storage.sh
test/suites/storage_buckets.sh
test/suites/storage_local_volume_handling.sh
test/suites/storage_snapshots.sh
test/suites/storage_volume_import.sh
test/suites/storage_volume_initial_config.sh

This PR adds add a `volatile.uuid` config field for each volume, snapshot and bucket. This is a requirement for the Dell PowerFlex storage driver (https://github.com/canonical/lxd/pull/12304) in order to be able to create an equally sized volume name that fits under the size constraints.
A new field gets added to the `drivers.Volume` struct to pass down relevant information from the DB:
* `parentUUID` which contains the parent volumes `volatile.uuid` in case `drivers.Volume` is used to identify a snapshot. This is used when creating snapshots from volumes to be able to reference the parent volume from within the storage driver.
This is a follow up on https://github.com/canonical/lxd/pull/12871 and now applies the `volatile.uuid` also on top of the `drivers.VolumeCopy` struct to allow …

Storage: Set `volatile.uuid` for all volumes and snapshots

---

lxd/storage/drivers/driver_ceph_volumes.go
lxd/storage/drivers/driver_zfs_volumes.go

This fixes a regression caused by https://github.com/canonical/lxd/pull/12871. Since the `CreateVolumeFromCopy` function is called recursively, it expects the snapshots to be there also when copying the VMs filesystem volume. Otherwise the snapshots get skipped.
@simondeziel thanks for pointing that out, it's awesome to now have the `lxd-ci` tests. The pipeline failed when trying to delete a volume that has snapshots https://github.com/canonical/lxd-ci/actions/runs/7913899479/job/21615586614

Storage: Fix regression when copying VMs

---

lxd/project/project.go

Don't panic if the given volume name doesn't contain a project.
I have observed this whilst trying to recover custom storage volumes using `lxd recover`.

Project: Don't panic on `StorageVolumeParts`

---

lxd/storage/drivers/driver_btrfs_volumes.go
lxd/storage/drivers/driver_common.go
lxd/storage/drivers/driver_zfs_volumes.go
lxd/storage/drivers/generic_vfs.go
lxd/storage/drivers/interface.go
lxd/storage/drivers/volume.go

Adds a new function `HasVolumeSnapshots` to the storage interface.
This replaces https://github.com/canonical/lxd/pull/12909 by moving the snapshot comparison logic into the storage driver. If a storage driver decides to not store volumes based on its name (e.g Dell PowerFlex https://github.com/canonical/lxd/pull/12304), the logic from the common driver can be re-implemented without leaking driver internal logic into the calling backend.
By passing the information from the new `VolumeCopy` struct, the storage driver can access all of the snapshots information from the database in order to perform various comparisons.
The functions signature is using the same as `HasVolume` which returns (bool, error)`.

Storage: Move snapshot comparison logic into the driver

---

.github/workflows/tests.yml

Also make remount non-fatal which can sometimes fail as seen in https://github.com/canonical/lxd/actions/runs/7964300360/job/21741552801?pr=12913

Remove more container runtimes from GitHub runners

---

lxd/backup/backup_config_utils.go

Should have been included in https://github.com/canonical/lxd/pull/12916. 
If the backup configs volume configuration has been changed, make sure it also gets updated when the changes are written to file.

Storage: Update instance volume config when saving file

---

client/interfaces.go
client/lxd_instances.go
doc/api-extensions.md
lxc/import.go
lxd/api_internal.go
lxd/backup/backup_config_utils.go
lxd/instances_post.go
shared/version/api.go

Fixes:  [#12000](https://github.com/canonical/lxd/issues/12000)
This PR is for setup device config when importing container.
When the CLI receives the "--device" parameter (just like "lxc copy --device"), it encodes it into a string and places it to "X-LXD-devices" header to send to the LXD API server. These code are referenced from "X-LXD-properties" and "X-LXD-profiles" header.
The "OverrideConfigYamlFile" function is intended to ensure that the device config in backup.yaml match the current instance settings to avoid potential issues.
Maybe we could remove it to make it simple.

Add device parameter for importing instance command

---

doc/howto/access_ui.md

The UI is now enabled by default in the snap.

doc/getting started: update how to access the UI

---

lxd/auth/oidc/oidc.go

When the `oidc.groups.claim` config key was added in #12827, the logic governing optional configuration of the OIDC verifier was incorrect. This caused the config expiry interval to be set to zero if not passed in by the caller.
This caused the verifier to rotate the encryption keys of the relying party on every call. These keys are used to encrypt the `state` and `pkce` cookies that OIDC needs to work. As they had been rotated during the OIDC flow, the callback handler to failed to decrypt the cookies, and so login was failing.

Auth: Ensure the default config expiry interval is set.

---

doc/config_options.txt
lxd/metadata/configuration.json
lxd/storage/drivers/driver_powerflex.go
lxd/storage/drivers/driver_powerflex_utils.go
lxd/storage/drivers/driver_powerflex_volumes.go

This is a follow up on https://github.com/canonical/lxd/pull/12304.
To prevent a user from hitting the PowerFlex snapshot limit of 126, LXD supports the creation of volume clones to circumvent this limitation. This can be controlled using the `powerflex.clone_copy` setting. 
The PR ensures `powerflex.clone_copy` is set to `true` by default so that a user who isn't aware of this limitation doesn't run into issues during operations.
If the user is aware of the limit, the PowerFlex snapshot feature for copying volumes can be activated by setting `powerflex.clone_copy` to `false`.
Additionally this PR fixes two docstrings in the PowerFlex driver.

Storage: Clone PowerFlex volume copies by default

---

lxd/storage/drivers/driver_ceph_volumes.go
lxd/storage/drivers/driver_lvm_volumes.go
test/suites/storage.sh

Backport the cherry-pick list from https://github.com/canonical/lxd-pkg-snap/pull/297/files into LXD's stable-5.0
This should address the issue affecting 5.0/edge with lvm-thin (https://github.com/canonical/lxd-ci/actions/runs/7964620311/job/21742565715):
```
==> Checking restore VM snapshot
+ lxc restore v1 snap0
+ waitInstanceReady v1
+ set +x
+ lxc exec v1 -- cat /root/foo.txt
+ grep -Fx foo
foo
==> Checking VM filesystem volume was restored too
+ echo '==> Checking VM filesystem volume was restored too'
+ nsenter --mount=/run/snapd/ns/lxd.mnt '[' -f /var/snap/lxd/common/lxd/storage-pools/vmpool-lvm-thin-2372/virtual-machines/v1/foo ']'
+ cleanup
+ set +e
+ echo ''
+ '[' 1 = 1 ']'
+ echo 'Test failed'
```

Storage: Misc backports (stable-5.0)

---

doc/.sphinx/spellingcheck.yaml
doc/cloud-init.md
doc/howto/instances_access_files.md
doc/howto/instances_backup.md
doc/howto/instances_configure.md
doc/howto/instances_console.md
doc/howto/instances_create.md
doc/howto/instances_manage.md
doc/howto/instances_routed_nic_vm.md
doc/howto/instances_troubleshoot.md
doc/howto/storage_backup_volume.md
doc/instance-exec.md
doc/profiles.md
doc/reference/devices_nic.md

Add API instructions for the different how-tos and clean up the ones that we already had.

Doc: Add API instructions to instances how-tos

---

lxd/storage/backend_lxd.go
lxd/storage/drivers/driver_btrfs_volumes.go
lxd/storage/drivers/driver_ceph_volumes.go
lxd/storage/drivers/driver_cephfs_volumes.go
lxd/storage/drivers/driver_dir_volumes.go
lxd/storage/drivers/driver_lvm_volumes.go
lxd/storage/drivers/driver_powerflex_volumes.go
lxd/storage/drivers/driver_zfs_volumes.go
lxd/storage/drivers/generic_vfs.go

A small addition for PowerFlex instance movements/migrations. 
When migrating instances using the PowerFlex driver, the receiving side has to pay extra attention to not regenerate the UUID. Instead check if it's a cluster internal move and reuse the actual volume's config from the database.
Additionally when preparing the instance for migration, also `genericVFSMigrateVolume` has to use the `VolumeCopy` struct in order to call the drivers `d.MountVolumeSnapshot` with the right config and snapshot's UUID. This is the same change as applied for all the other generic VFS methods.

Storage: Also use `VolumeCopy` struct for migrations

---

lxd/instance/drivers/driver_qemu.go

This allows a user to do:
```
lxc launch ubuntu:jammy v1 --vm --config migration.stateful=true -s local
```
Whereas it was only working with a `remote` storage backend before.
The root disk's `size.state` related error will only arise when a user attempts to do a stateful operation like `lxc stop v1 --stateful`

Instance: Allow a stateful VM to be started even if its root disk `size.state` parameter is not set

---

lxd/apparmor/rsync.go
lxd/rsync/rsync.go

Closes #12838 
The issue here was introduced with https://github.com/canonical/lxd/commit/3444070ac8dcc9ff5281a0eb4840acd9b40fdf92 which began wrapping rsyncs in `aa-exec -p <profile> rsync...`
We were generating an apparmor profile in `sendSetup` and deferring its deletion, but this would all happen before we actually finished running the rsync. Deleting the profile would forcibly close the connection and we would get an EOF error.
Instead, this adds a reverter to only delete the profile if there's an error in `sendSetup`, and otherwise propagate it to its caller who actually returns when the rsync is done, and so can defer the cleanup without issue.

lxd/rsync: Remove apparmor profile after finishing rsync send

---

lxd/storage/drivers/driver_ceph_volumes.go
lxd/storage/drivers/driver_lvm_volumes.go
lxd/storage/drivers/driver_powerflex_volumes.go

For VM type volumes on `ceph`, `lvm`, and `powerflex` storage pools, always set the block volume filesystem to `ext4`, regardless of what is set in `volume.block.filesystem`.
Closes #12921 
Initial discussion in #12907

lxd/storage/drivers: Always use default block.filesysem for VM volumes

---

lxd/db/networks.go
lxd/devices.go
lxd/networks_utils.go

The PR https://github.com/canonical/lxd/pull/12754 introduced a commit https://github.com/canonical/lxd/commit/011affcdc4a300cc6db7815d207de8e2224059de which incorrectly started logging warnings if `networkAutoAttach` wasn't able to find a matching network for the network device.
This is incorrect because the majority (possibly all) of new network devices that appear on a system won't be candidates for auto attach. In fact only if a bridge network specifies `bridge.external_interface` will this be potentially relevant.
So this was causing lots of log noise unnecessarily.
However the old implementation also didn't differentiate between a "not found" DB error and a problem performing the query (which we should log about) so this PR fixes those issues.

lxd: Fix incorrect network device attach warnings

---

lxd/patches.go
lxd/storage/drivers/driver_ceph_volumes.go
lxd/storage/drivers/driver_lvm_volumes.go
lxd/storage/drivers/driver_powerflex_volumes.go

In https://github.com/canonical/lxd/pull/12813 we have removed the `block.*` config keys for custom block volumes and VM block volumes. But the latter requires those settings in order to successfully mount the VMs filesystem volume. 
This PR adapts the patch `patchStorageUnsetInvalidBlockSettings` (added in https://github.com/canonical/lxd/pull/12813) to only remove those settings from custom block volumes and reverts the same in the three block backed drivers Ceph, LVM and PowerFlex (changed in https://github.com/canonical/lxd/pull/12805).

Storage: Fix block volume patch

---

lxd/instance_uefi_vars.go

Fixes etag conflict error when trying to set UEFI vars whilst VM is booting:
```
lxc config uefi set v1 testvar-8be4df61-93ca-11d2-aa0d-00e098032b8c=48656c6c6f2066726f6d204c5844
==> Try to set EFI variable while VM is running (should fail)
Error: ETag doesn't match: 53b5a2ee77d20eb5df6039fdff5defc03cdf99260ee805b9a54e19a855391682 vs f2f48344528a8477ccbba077ba5a6d62f6d09a7e94250a1697c1a6e90aa53417
```

Instance: Check if VM is running earlier to prevent etag errors when setting UEFI vars

---

doc/howto/images_manage.md

Quote the command to ensure the shell doesn't replace it with a file name.

doc/images: quote command containing asterisk

---

lxd/db/cluster/entities.go

The `server`, `network_zone`, and `image_alias` entity types were added in #12872 as they were needed for replacing authorization objects. However, the database analogues for these entity types were not added because they are not required for the warning subsystem. This pull request adds these database entity types as they will be needed for authorization (#12914).

DB: Adds database representation of `server`, `network_zone`, and `image_alias` entity types.

---

lxd/apparmor/pyuefivars.go

Fixes issue found by lxd-ci: https://github.com/canonical/lxd-ci/actions/runs/8053199642/job/21995023738?pr=74#step:6:557:
```
Feb 26 17:37:42 kernel: audit: type=1400 audit(1708969062.731:160): apparmor="STATUS" operation="profile_load" profile="unconfined" name="lxd_pyuefivars-<var-snap-lxd-common-lxd-virtual-machines-v1-qemu.nvram>" pid=4041 comm="apparmor_parser"
Feb 26 17:37:42 kernel: audit: type=1400 audit(1708969062.887:161): apparmor="DENIED" operation="open" class="file" profile="lxd_pyuefivars-<var-snap-lxd-common-lxd-virtual-machines-v1-qemu.nvram>" name="/snap/lxd/27360/bin/" pid=4042 comm="python3" requested_mask="r" denied_mask="r" fsuid=999 ouid=0
Feb 26 17:37:43 kernel: audit: type=1400 audit(1708969063.111:162): apparmor="DENIED" operation="open" class="file" …
```

lxd/apparmor/pyuefivars: allow reading bin/ directory

---

.github/workflows/tests.yml
doc/howto/benchmark_performance.md

This was tested successfully. In my tests, I noticed the lxd-benchmark (either build via GH or with `go install`) required exporting LXD_DIR for it to talk to the snap as otherwise it only tried connecting to `/var/lib/lxd/unix.socket`.

Prepare for lxd-benchmark to not be shipped in the snap

---

doc/api-extensions.md
lxd/instance/instance_utils.go
lxd/instance/instancetype/instance.go
lxd/seccomp/seccomp.go
shared/version/api.go

api: add a new extension `container_syscall_filtering_allow_deny`
Commit 0c987f66b6f1c added support for the respectful config key names
(`security.syscalls.allow` and `security.syscalls.deny*`) but kept support for
the offensive names for backward compatibility. However, that commit did not
add the `container_syscall_filtering_allow_deny` extension to
`shared/version/api.go`, presumably by mistake.
Now that we are dropping support for the offensively named configuration keys,
use the API extension name and advertise it properly.
Items changed:
* doc/api-extensions: rewrite keys `from container_syscall_filtering` and
update `container_syscall_filtering_allow_deny` description
* shared/version/api: add `container_syscall_filtering_allow_deny` extension
* lxd/instance/instancetype/instance: …

Drop offending legacy config names for syscall filtering

---

test/suites/storage_buckets.sh

The latest minio server now relies on the lower level storage subsystem to track usage quotas. And due to storage volume size rounding using 2MB is not sufficient to always trigger storage driver quota detection.
Fixes #12968

test: Increase minio storage bucket test file size to 5MB

---

lxd/daemon.go

Previously, any error returned from (*Daemon).Authenticate was being ignored if the error was not an oidc.AuthError. The user was still not trusted so this was not a security risk, but it made inspecting the error much more difficult.

Auth: Correctly return authentication error.

---

doc/custom_conf.py

The REST API docs display okay with Swagger UI v5.11.7, but not with v5.11.8. Let's temporarily pin the version until we figure out why ...

doc/api: pin Swagger version

---

lxc/storage_volume.go
lxd/api_internal.go
lxd/certificates.go
lxd/daemon.go
lxd/lifecycle/identity.go
shared/api/event_lifecycle.go

When a new OIDC identity authenticates with LXD, they are added to the `identities` table and the identity cache is updated so that authentication does not require calls to the database. However, if the same OIDC identity then makes a request to another cluster member, this will fail because the other member does not have the user in their cache (the other member will attempt to add the user to the database, but this will fail because the identity already exists). This was initially flagged here: see https://github.com/canonical/lxd/pull/12914#discussion_r1497778097.
This PR adds an internal endpoint to be used for updating the identity cache in this scenario, and adds lifecycle events for `identity-created` and `identity-updated`. Additionally, this PR changes the certificates API to use …

Auth: Notify cluster members of new or updated OIDC identities

---

lxd/db/network_peers.go

Fixes this error in the CI tests: https://github.com/canonical/lxd-ci/actions/runs/8062199894/job/22021469170#step:6:3297
This was recently refactored here:
https://github.com/canonical/lxd/pull/12754/files#diff-6ba9a4d3cf752f98f07e5a8ff4ba755b19eb813013b0550931532405b46ba9b9
At the end of this block, we return the `err` var. Previously this block was wrapped in a transaction which was assigned to an error, but the transaction itself would assign `err` to `nil` if we received a `sql.ErrNoRows` error. When the transaction was removed, the `return nil` line was removed as well, and so the `sql.ErrNoRows` error was being propagated to the caller, instead of `nil`.

lxd/db: Don't propagate expected errors

---

.github/workflows/tests.yml
Makefile
go.mod
go.sum
test/mini-oidc/go.mod

Also switches back to using `go mod tidy` for Go version enforcement as `go get go@` was modifying pinned dependencies automatically which is not desired (rather than erroring).

Set minimum Go version to 1.21.5 to accomodate forthcoming openga package

---

lxd/device/disk.go
lxd/instance/drivers/driver_qemu.go

Fixes #12808
Aside from being an undesirable FD leak, it was also preventing clean unmount of the VM's config volume on some pool drivers.
Also added cleanup of the config.iso file if the cloud-init drive is removed from the instance (whether or not it is running).

VM: Don't leak file descriptor when probing for Direct I/O support

---

client/lxd_auth.go
doc/.wordlist.txt
doc/api-extensions.md
shared/api/auth.go
shared/version/api.go

Including "api" in the extension name is redundant and we can still change this because it has not been released yet. See https://github.com/canonical/lxd/pull/12976#discussion_r1506062798

API: Change `authorization_apis` extension name to `access_management`.

---

doc/howto/migrate_from_lxc.md

Replaces #12951 as `lxc-to-lxd` isn't yet easy to statically build (#12988).

doc/howto/migrate_from_lxc: 5.0 is the last LTS release shipping lxd.lxc-to-lxd

---

lxd/db/cluster/schema.go
lxd/db/cluster/update.go

This PR adds three columns to the identities table: `first_seen_date`, `last_seen_date`, and `updated_date`. The columns are unused and have a default value. They will be used in future to remove users that have not been seen recently so that the identities table cannot grow indefinitely.

DB: Add columns to identities table for auditing.

---

lxd/api_1.0.go
lxd/auth/oidc/oidc.go
lxd/daemon.go
lxd/daemon_config.go

The HTTP requests that are performed as part of OIDC discovery and authentication should comply with the `core.proxy_http(s)` settings. This PR adds a `httpClientFunc` field to the OIDC verifier so that it can get a fresh HTTP client when it refreshes it's config. The caller is responsible for passing in a `httpClientFunc` that returns a client that will correctly proxy requests.
To ensure the verifier is updated when the proxy settings are applied, a new `ForceConfgRefresh` method is exported. This method sets the config expiry to zero so that a new HTTP client will be used for the next call.

Auth: Set OIDC relying party HTTP client to comply with proxy configuration.

---

lxd/project/project.go
lxd/storage_volumes.go
lxd/storage_volumes_backup.go
lxd/storage_volumes_snapshot.go
lxd/storage_volumes_state.go

In some cases the requested project name was passed directly to the storage layer.
Fixes https://github.com/canonical/lxd/security/code-scanning/147
Also standardises request and effective project name variables in the storage volume API endpoints for clarity.
Also uses appropriate contexts where possible.

API: Ensure request project name isn't passed to storage layer directly

---

lxd/storage_volumes.go

Fixes https://github.com/canonical/lxd/security/code-scanning/147
Was not an actual security issue though because the storage subsystem tried to load the volume record from the DB and was failing with:
```
Error: Failed generating volume refresh config: Storage volume "vol1" in project "foo2" of type "custom" does not exist on pool "default": Storage volume not found
```
So the raw request was never passed to the storage layer directly.
However this was a bug which is now fixed.

API: Ensure request project name isn't passed to storage layer directly when copying/refreshing volumes

---

lxd/migration/migration_volumes.go

For both `MigrationFSType_RSYNC` and `MigrationFSType_BLOCK_AND_RSYNC` the target can agree on `rsync` features. Don't skip the features offered by the target if the mode is `MigrationFSType_BLOCK_AND_RSYNC`. Otherwise the list of features returned in the migration response is empty which leads to not using any `rsync` features for the migration in case of `MigrationFSType_BLOCK_AND_RSYNC`.
I found this whilst adding a new type for the Ceph RBD refresh that also requires using `rsync` for VMs filesystem volumes.
This can be tested easily by printing the list of features from the storage driver:
```go
func (d *ceph) MigrateVolume(vol VolumeCopy, conn io.ReadWriteCloser, volSrcArgs *migration.VolumeSourceArgs, op *operations.Operation) error {
fmt.Println("--> type:", …
```

Migration: Accept offered rsync features for `BLOCK_AND_RSYNC`

---

lxd/auth_groups.go

`can_view_groups` is defined on server. For fine-grained permissions on this endpoint, we want `can_view` defined on `group`.

Auth: Fix entitlement for group list request.

---

.github/workflows/tests.yml

Minio newer than RELEASE.2024-02-24T17-11-14Z breaks on btrfs blocking our edge builds.

Github: Pin minio to RELEASE.2024-02-24T17-11-14Z to unblock edge builds

---

lxd/instance/drivers/driver_lxc.go

Follow up on https://github.com/canonical/lxd/pull/13040 to get rid of LXD version 3.7 rsync feature assumptions.

Container: Remove LXD 3.7 rsync feature exception when doing live migration

---

.github/workflows/tests.yml

The btrfs issues fixed by commit 8543c93a8 have been addressed upstream in MinIO in the latest release, so we can go back to pulling that.

Use latest minio in test suite

---

.github/workflows/tests.yml
Makefile
doc/requirements.md
go.mod
test/lint/licenses.sh
test/mini-oidc/go.mod

There don't appear to be LTS releases of the OpenFGA server. I suspect we'll need to pin it at v1.5.0.

Set minimum Go version to 1.22.0 to accomodate OpenFGA.

---

.github/workflows/tests.yml

Testing with go tip IMHO offers little benefit as we get the odd failure that later resolves itself
which causes distractions. And if a stable release introduces changes that cause our tests to fail
we will have time to fix them before we switch the snap to build with the later version as we now
pin the snap to build with a specific Go version for reproduciblity.
So instead lets do a basic standalone and cluster test with the latest stable version.
At the moment this will cause some duplication of tests as we are explicitly testing with go 1.22,
which is also the latest stable. But this will not be the case when go 1.23 comes out.
This also has the benefit of of not needing to have a conditional on push as we should take a
breakage on the latest stable release more seriously and stop the …

github: Restore testing latest stable version of go rather than go tip

---

lxd/instance/drivers/driver_qemu.go

A change that was made to satisfy the linter as part of https://github.com/canonical/lxd/pull/12754 (commit https://github.com/canonical/lxd/commit/3dec35308f1b504f8f4ce72a586afa9cff389267) is causing an error message on subsequent migrations:
```bash
julian@thinkpad:~$ lxc cp v1 localhost:v2
julian@thinkpad:~$ lxc rm v2
julian@thinkpad:~$ lxc cp v1 localhost:v2
Error: Failed instance creation: Error transferring instance data: Failed migration on target: Failed creating instance snapshot record "v2/snap0": Instance is busy running a "create" operation
```
This PR ensures a pointer is used to track the VMs operations so that the actual operation is then marked as done.

VM: Further fix linter fixes preventing copy to remote

---

lxd/db/cluster/identity_provider_groups.go

This was meant to be fixed in #13043 but it appears it hasn't been. I must have missed this while rebasing or something. Thanks to @mas-who for reporting.

lxd/db/cluster: Actually swap argument order in SQL statement.

---

lxd/storage/backend_lxd.go

Fixes https://github.com/canonical/lxd/security/code-scanning/147
Although not actually a security issue because the DB load function is checking the volume name is correct and so any invalid input would fail before the actual storage commands were called.
But hopefully this will appease GH's security scanner.

Storage: Use volume name from the database in RefreshCustomVolume and CreateCustomVolumeFromCopy

---

doc/config_options.txt
doc/reference/devices_nic.md
lxd/device/nic.go
lxd/device/nic_routed.go
lxd/metadata/configuration.json

JIRA ticket: https://warthogs.atlassian.net/jira/software/c/projects/LXD/boards/54?assignee=63d9eb6128cddcc70770aff1&selectedIssue=LXD-440
____
Searching for references in `/doc` (more precisely in `doc/*.md,doc/explanation/*.md,doc/howto/*.md,doc/reference/*.md,doc/tutorial/*.md`) of the form `[<key_name>](<section_name>)` to replace:

lxd-metadata: Annotate codebase for `nic` device config keys

---

lxd/auth/authorization_types.go
lxd/auth_groups.go
lxd/db/cluster/auth_groups.go
lxd/db/cluster/identities.go
lxd/db/cluster/identity_provider_groups.go
lxd/identities.go
lxd/identity_provider_groups.go

This is an oversight from #12914.

Auth: Filter out identities, groups and, IdP groups that the requestor cannot view

---

lxd/migration/migration_volumes.go

This allows staying backwards compatible with older versions of LXD.
The removal of legacy LXD 3.7 rsync feature assumptions from https://github.com/canonical/lxd/pull/13040 and https://github.com/canonical/lxd/pull/13041 can stay as the check for rsync features in the `RSYNC` migration type is already part of the older LXD releases.

Migration: Revert adding rsync features for BLOCK_AND_RSYNC

---

doc/config_options.txt
doc/reference/devices_tpm.md
lxd/device/tpm.go
lxd/metadata/configuration.json

lxd-metadata: Annotate codebase for `tpm` device config keys

---

lxd/storage/drivers/driver_ceph_utils.go
lxd/storage/drivers/driver_ceph_volumes.go

This PR adds a comment to clarify local volume refreshes from snapshots as requested in https://github.com/canonical/lxd/pull/12743#discussion_r1516255599. 
Some slices are now initialized using their final size to improve performance.
Furthermore new log messages for local copies and migrations now indicate when a RBD volumes gets copied or sent/received.

Storage: Ceph RBD followup

---

doc/config_options.txt
doc/reference/network_macvlan.md
lxd/metadata/configuration.json
lxd/network/driver_macvlan.go

See the root PR https://github.com/canonical/lxd/pull/13027 for a summary

lxd-metadata: Annotate codebase for `macvlan` network config keys

---

lxd/identity/cache.go
lxd/identity/util.go

Adds OIDC identities to the `AuthenticationMethodFromIdentityType` method. This was causing errors in the OpenFGA driver (mroe details in commit message). Additionally adds a method `GetIdentityProviderGroupMapping` to the identity cache that will be used by the OpenFGA authorization driver.
Blocks #12976

Auth: Identity cache improvements

---

lxd/api_1.0.go
lxd/api_metrics.go
lxd/auth/util.go
lxd/certificates.go
lxd/images.go
lxd/networks.go
lxd/project/permissions.go
lxd/storage_pools.go

The OpenFGA driver will return a 404 if the user does not have permission to view a resource, otherwise it will return a 403. This PR adds a util to check for auth errors being one of those codes and improves how error codes are being checked in the handlers.
Blocks #12976

Auth: Improve error handling

---

doc/config_options.txt
doc/reference/network_bridge.md
lxd/metadata/configuration.json
lxd/network/driver_bridge.go

JIRA ticket: https://warthogs.atlassian.net/jira/software/c/projects/LXD/boards/54?assignee=63d9eb6128cddcc70770aff1&selectedIssue=LXD-442
____
Searching for references in `/doc` (more precisely in `doc/*.md,doc/explanation/*.md,doc/howto/*.md,doc/reference/*.md,doc/tutorial/*.md`) of the form `[<key_name>](<section_name>)` to replace:

lxd-metadata: Annotate codebase for `bridge` network config keys

---

lxd/network/acl/acl_ovn.go

Closes #12933
ovn-controller.log no longer reports the protocol on the `severity` field, instead including it with the `direction` field.
Previously, the log line would include:
`severity=info: tcp`
Whereas now, it simply reports the log level:
`severity=info`
The protocol is now reported with the direction:
`direction=to-lport: icmp`

Network: Change protocol field for OVN ACL logs

---

lxd/api_project.go
lxd/network_acls.go
lxd/network_peer.go
lxd/network_zones.go
lxd/profiles.go
lxd/project/permissions.go

Additionally, ensure that all UsedBy fields are filtered by what the user can view.
Blocks #12976

Auth: Filter UsedBy results outside of transactions

---

lxd/auth/authorization.go
lxd/db/cluster/entities.go
lxd/db/openfga.go

Adds further clarification to comments and updates handling of a not found error. I will create another PR for the error wrapping in the driver itself.

Auth: Openfga driver followup

---

lxd/storage/drivers/driver_ceph_volumes.go

This is sometimes causing an error in the pipeline when subsequent migrations are called right after another and the earlier migration isn't yet finished as the snapshot requires locking.
The generic volume migration (refresh) is triggering the Ceph RBD drivers `MountVolumeSnapshot()` which is calling `vol.MountLock()` for the respective volume. Before https://github.com/canonical/lxd/pull/13079 the drivers `MountVolumeSnapshot()` was also used for the initial migration using type `RBD`.
As a result we also have to use the lock here so that subsequent generic refreshes will wait until the lock is returned.
That was first observed in https://github.com/canonical/lxd/actions/runs/8206575452/job/22446018257?pr=13084 and caused by https://github.com/canonical/lxd/pull/13079.

Storage: Ceph RBD lock concurrent snapshot migrations

---

lxd/response/response.go

SyncResponse's `success` field can hint that SyncResponse can potentially handle errors. However, when an error is passed in like so:
```
err = ceph.ServicePlacementHandler(interfaces.CephState{State: s}, payload)
return response.SyncResponse(false, err)
}
```
The syncResponse does not set the `error` field of the response, so the result has no metadata or error:
```
{
"type": "sync",
"status": "Failure",
"status_code": 400,
"operation": "",
"error_code": 0,
"error": "",
"metadata": {}
}
```
It seems `SyncResponse(false, ...)` is never used in the LXD codebase for any reason, so I think it's safe to just handle this type of response like an error. So I've changed `Render` to just fallback to a SmartError, which will also try to maintain the http information from the …

lxd/response: Use SmartError if SyncResponse success=false

---

lxd-agent/main.go
shared/version/useragent.go

Indicate LTS version in LXD agent. 
In addition, indicate LTS version in useragent, which simplifies scraping LXD version from various logs, such as Nginx log.

Indicate LTS version in LXD agent and useragent

---

lxd/storage/backend_lxd.go

Fixes https://github.com/canonical/lxd/security/code-scanning/142
Although not an actual security issue because the `VolumeDBGet` was already validating the input was a valid volume name.

Storage: Use volume name from VolumeDBGet in BackupCustomVolume

---

go.mod
go.sum
lxd/api.go

closes https://github.com/canonical/lxd/issues/12920
This adds the required security headers to LXD UI server responses as well as server-side gzip compression.

ui: add server-side gzip and security headers for LXD UI

---

.github/workflows/commits.yml

This should handle stable-NM.XYZ instead of only stable-X.Y

github: fix branch target name/version extraction logic

---

.github/workflows/commits.yml

This should handle stable-NM.XYZ instead of only stable-X.Y

Branch target multi digits (stable-5.0)

---

.github/workflows/commits.yml

This should handle stable-NM.XYZ instead of only stable-X.Y

github: fix branch target name/version extraction logic (stable-5.21)

---

lxd/device/nic_ovn.go

This fixes a panic caused when stopping a device with an invalid config.
This doesn't yet fully resolve all the issues in https://github.com/canonical/lxd/issues/13082 but allows running the evacuation.

Network: Only stop OVN device if network is populated

---

client/lxd_auth.go

`lxc permission list` expects an explicit `project=<project_name>` argument. If the client has a project set (other than default) then all requests made by the client will add a `project=<project_name>` query parameter if it is not already set. This leads to confusing/inconsistent results for this command.

client: Unset project when querying permissions.

---

doc/howto/images_manage.md

After #12895 was apparently a temporary issue, update the docs to use PATCH for changing an alias.
Also fix the links to the Swagger API (no idea why I didn't catch that before ...).

Doc: Fix CLI instructions for changing an image alias

---

lxd/auth/authorization.go
lxd/auth/driver_common.go
lxd/auth/driver_openfga.go
lxd/auth/driver_tls.go
lxd/db/openfga.go

This only builds the parts of the auth package that are referenced by the state.State struct
used by the lxd-agent when building the lxd-agent.
This significantly reduces the size of the lxd-agent.

Auth: Don't build authorization drivers into the lxd-agent

---

Makefile

And link to the upstream bug: https://github.com/canonical/sphinx-docs-starter-pack/issues/197

Makefile: consistently use pip

---

shared/version/flex.go

Adds missing `.0` to internal version.

Release LXD 5.21.0 (stable-5.21)

---

scripts/bash/lxd-client

I'm vacillating over including `idp-groups` in the top-level completion ([L198](https://github.com/MggMuggins/lxd/blob/auth-bash-completions/scripts/bash/lxd-client#L198)). I think `idp` ought to complete to `idp-groups`, but it makes `identity` less convenient. Happy to change it if needed.
Resolves #12989
I've tested this pretty thoroughly but If @markylaing is willing to give them a quick spin I'd appreciate someone with a little more knowledge of the domain making sure they don't do anything too dumb.

scripts: Add bash completions for `lxc auth`

---

lxd/instances_put.go

Previously, state updates invoked against all instances in a project were applied partially - depending on the permissions of the caller. The commit checks permissions for all instances in the project and enforces that the caller has permission to update all of them before continuing.
Partially addresses #12461 - see https://github.com/canonical/lxd/pull/12313#discussion_r1371526260

Auth: Pre-check permissions when performing bulk state update.

---

lxd/api.go

closes https://github.com/canonical/lxd/issues/13108

UI: Update `X-Xss-Protection` (deprecated) for `Content-Security-Policy`

---

doc/config_options.txt
lxd/device/nic.go
lxd/metadata/configuration.json

This was apparently a typo as a link-local address should be used for both IPv4 and IPv6.

lxd/device/nic: fix default IP for routed NIC (`ipv4.host_address`)

---

lxd/api.go

And add security response headers to documentation endpoint.
Fixes https://github.com/canonical/lxd/issues/13150

API: Enable gzip compression

---

lxd/instance/drivers/driver_common.go

When instantiating a new device make sure to clone it's config. This ensures that the downstream drivers don't modify the original config map.
This fixes https://github.com/canonical/lxd/issues/13082 since the call to `dev.CanMigrate()` will populate the devices `mtu` field through `dev.validateConfig()` which will modify the outer config map passed down to the driver.

Migration: Always clone the device config

---

scripts/bash/lxd-client

The main point is the fixed `lxc storage <TAB>` as well as adding a few missing keys to this completion group.

Few improvements to bash completion

---

lxd/storage/drivers/driver_btrfs.go

Fixes https://github.com/canonical/lxd/issues/12605.
This moves the replacement of the pools `source` property from path to its block UUID into `FillConfig()`. The recovery procedure can now reconstruct all of the pools config without actually creating the pool using the drivers function.
Additionally this addresses an unhandled timeout in https://github.com/canonical/lxd/pull/13184/commits/79c17806506cef4a8c4a72cadc13fbe5050c5b2f.

Storage: Recover BTRFS pools `source` to block device UUID to align with creation process

---

lxd/instance/drivers/driver_lxc.go

In cgroup-v1 memcg implementation we have a concept of "soft" memory limit (`memory.soft_limit_in_bytes`). In cgroup-v2 memcg we don't have an explicit analog of it. Originally, when hard memory limit is set, we set it value to `memory.limit_in_bytes` and set 90% of its value to `memory.soft_limit_in_bytes`. And it was working quite well. But in cgroup-v2 we tried to treat `memory.high` as analogy to `memory.soft_limit_in_bytes` which is not fully correct. Yes, reaching `memory.high` limit does not invoke OOM-killer, at the same time it forces process to go into memory reclaim on each page fault that want's to charge pages in memcg which makes its execution terribly slow. Let's stop doing that. If hard limit is set, let's set only `memory.max` value and do nothing with `memory.high`. But …

drivers/driver_lxc: do not set "soft" limit when hard limit is set

---

doc/external_resources.md

Needed to prevent the build for the topical navigation from failing.

doc: workaround for undefined references

---

lxd/api.go

Partially reverts c9ffbb29e01b0c0198ec93e8d17ac4c71061174d and 26e61c005f634d999fa490a170e2109181cb7de4
Because its applying gzip compression even if Accept-Encoding header isn't set.
This was breaking Go SDK clients using the LXD API, this was causing microcloud setup errors:
```
microcloud init
Waiting for LXD to start...
Error: Failed to check LXD initialization: invalid character '\x1f' looking for beginning of value
```
Furthermore we should more carefully evaluate if there are security implications to gzipping TLS traffic before potentially re-enabling correctly.
See https://en.wikipedia.org/wiki/BREACH

lxd/api: Revert gzip compression on API

---

lxd/api_internal.go

Noticed this while working on #13118. [This](https://github.com/canonical/lxd/commit/14a5882905bfe79a24dddd7733d1a417d6b8b94a) commit made some older conditions impossible to reach.

lxd/api_internal.go: remove impossible conditions

---

lxd/storage/backend_lxd.go

Noticed this while working on #13183. If this was intentional to mantain a standard in the functions feel free to just close this PR.

Storage: Remove unused parameters

---

lxd/storage/drivers/driver_btrfs_volumes.go
lxd/storage/drivers/driver_ceph_volumes.go
lxd/storage/drivers/driver_dir_volumes.go
lxd/storage/drivers/driver_lvm_volumes.go
lxd/storage/drivers/driver_powerflex_volumes.go
lxd/storage/drivers/driver_zfs_volumes.go
lxd/storage/drivers/generic_vfs.go

This ensures snapshots are cleaned up in case the refresh fails. Otherwise this leads to error messages for subsequent refreshes as some of the snapshots already exist.

Storage: Use reverter for Ceph RBD volume refresh

---

.gitignore

I somehow ended up with a `doc/.sphinx/__pycache__`; seems like a safe bet that nobody will ever want to check in one of those...

gitignore: Ignore all __pycache__ under doc/

---

doc/rest-api.yaml
lxd/instance_file.go
shared/util.go

And add some rigor to the documentation around these fields. This came up during #13193

Ensure `uid`, `gid`, and `mode` are valid during parsing

---

lxd/storage/drivers/driver_btrfs_utils.go
lxd/storage/drivers/driver_btrfs_volumes.go
shared/ioprogress/reader.go

From https://github.com/lxc/incus/pull/683.
Additionally this PR ensures that the Btrfs driver is consistently using the daemons shutdown context instead of the `context.TODO()` for all the command executions.

Storage: Use progress tracker for Btrfs migration

---

.gitignore

See #13232; `.bak` are generated by a few make targets.

gitignore: Ignore all `.bak`

---

client/lxd_containers.go
client/lxd_instances.go
lxd/instance_file.go
shared/util.go
shared/util_test.go

Depends on #13230 (didn't rebase, figured it would be easier to have these merged in order)
In preparation for https://github.com/canonical/lxd/pull/13193, we will need to return additional fields from `ParseLXDFileHeaders`. This makes that less gross.

Refactor file header parsing

---

client/interfaces.go
client/lxd_instances.go
doc/api-extensions.md
doc/rest-api.yaml
lxc/file.go
lxd/instance_file.go
shared/util.go
shared/util_test.go
shared/version/api.go

Add an API extension `instances_files_modify_permissions` which allows setting the permissions of existing files using the file API. Also updates `lxc` to send the `X-LXD-modify-perm` header when `--mode`, `--uid`, or `--gid` are passed.
I elected to go with a new header rather than adding complexity to the existing headers as discussed in https://github.com/canonical/lxd/issues/12724; maintaining the client's backwards compatibility with older servers would have been non-trivial. This way the new header is simply ignored by older servers.
I'm happy to add integration tests if needed.
Closes https://github.com/canonical/lxd/issues/12724

Allow setting file permissions via API and `lxd file push --mode`

---

lxd/device/disk.go
lxd/instance/drivers/driver_qemu.go

The auto-converge feature in QEMU throttles down the guest to speed up convergence of RAM migration.
Previously this was only being used for shared storage VM live migrations, but this PR ensure its also used for local storage live VM migrations.

VM: Use auto-converge for all live migrations (from Incus)

---

lxd/api_metrics.go
lxd/instance/drivers/driver_lxc.go
lxd/metrics/metrics.go
lxd/metrics/types.go
test/suites/metrics.sh

closes https://github.com/canonical/lxd/issues/13217
This partially reverts https://github.com/canonical/lxd/pull/12639 , while keeping the ability to track the instances counts (containers count, live or stopped + vms count, live or stoppped). This also fix a negative metric issue (in case of CGroup Controller issue, we  want to expose `0` values and not negative ones) 
* This will be taken care of by https://github.com/canonical/lxd/pull/13214

Metrics: Do not expose the stopped instance metrics anymore

---

lxd/backup.go
lxd/db/backups.go
lxd/db/errors.go
lxd/db/networks.go
lxd/db/networks_test.go
lxd/db/node.go
lxd/db/node_test.go
lxd/db/storage_pools.go
lxd/db/storage_pools_test.go
lxd/instance/instance_utils.go
lxd/networks.go
lxd/response/smart.go
lxd/storage_pools.go
lxd/storage_pools_utils.go

This error is imported by the `lxd/request` package so that it canconvert it to an `http.StatusConflict` on a call to `response.SmartError`. Other applications are using the `lxd/request` package. Removing this error prevents the import of `lxd/db` into `lxd/request` and therefore prevents the import of `lxd/db` into downstream repositories.
Unblocks https://github.com/canonical/microcluster/pull/97

DB: Remove `ErrAlreadyDefined` sentinel error.

---

doc/api-extensions.md
doc/config_options.txt
lxd/instance/drivers/driver_lxc.go
lxd/instance/instancetype/instance.go
lxd/main.go
lxd/main_forksyscallgo.go
lxd/metadata/configuration.json
lxd/project/permissions.go
lxd/seccomp/cgo.go
lxd/seccomp/seccomp.go
scripts/bash/lxd-client
shared/version/api.go

This PR introduces support for `finit_module` syscall interception that allows to lazily load Linux kernel modules from inside unprivileged container if module is in the allow list `linux.kernel_modules`
Specification:
https://discourse.ubuntu.com/t/lxd-container-instance-lazy-modules-loading/42837

Instance: Add container `finit_module()` syscall interception support

---

lxd/devices.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/instance_interface.go

Make our pinning balancer aware of VM instances existence.

VM: Instance's CPU auto rebalancing/pinning

---

lxd/storage/backend_lxd.go

We shouldn't trust the volume names in the backup's index.yaml file.

Storage: Improve volume name validation in CreateCustomVolumeFromBackup

---

renovate.json

The renovate bot was first tested on the `lxd-pkg-snap.git` repo and we liked it.

Enable renovate bot

---

shared/simplestreams/products.go

When delta file is detected in product catalog, its source image fingerprint is always set to the container's rootfs. Instead, we should determine source image fingerprint based on the delta file type.
This issue only happened when a VM image is being pulled while older container image existed because in such case the source image hash for VM delta file would be set to container image.
---
Reproducer prior this fix:
```sh
$ lxc image copy images:349cf03fadf87a872caf596b781469719e45d60bec6ec08a83906236f1bfd622 local:
Image copied successfully!  
$ lxc image copy images:alpine/3.18/cloud local: --vm 
Error: Failed remote image download: Failed to run: xdelta3 -f -d -s /var/snap/lxd/common/lxd/images/349cf03fadf87a872caf596b781469719e45d60bec6ec08a83906236f1bfd622.rootfs …
```

Determine delta source file based on delta file type

---

lxd/daemon.go
lxd/instances.go

I (Stephane) noticed a few cases where an offline network or storage coming back online on an evacuated host would cause instances coming back online.
As all code paths to instancesStart come from locations attempting auto-start on daemon startup, lets just move the evacuation check to the function itself.
(cherry picked from commit 6b3a2bf770de3db734d172cc4e827a4f1c009f34)

lxd/instances: Don't start instances when evacuated (from Incus)

---

lxd/api.go

- Add any domain under canonical.com to content security policy as data source
- The UI needs to load the [images index](https://images.lxd.canonical.com/streams/v1/images.json)

Add canonical.com domain to content security policy

---

doc/tutorial/first_steps.md

This relates to [Open Documentation Academy Issue #43](https://github.com/canonical/open-documentation-academy/issues/43)
Two suggested changes to the tutorial:
- Check for free disk space before starting (the error reported by `lxc launch` when space runs out  is obscure)
- Provide an option for a shorter output from `lxc image list`

Doc: Suggested changes to the first steps tutorial

---

lxd/api_internal.go
lxd/warnings.go
test/suites/auth.sh

The OpenFGA model states that the "can_view_warnings" entitlement grants permission to view warnings. However, this is currently incorrect as the handlers are checking for `can_edit` on `server`.
I've added a regression test for this. Also, while working on it I have simplified the `POST /internal/testing/warnings` endpoint because while debugging it was very unclear why the request body was being unmarshaled into a `shared.JMap`.
I found this while working on #13262

lxd: `GET /1.0/warnings` should use the `can_view_warnings` entitlement.

---

lxd/storage/drivers/driver_zfs_volumes.go

From https://github.com/lxc/incus/pull/517.
Fixes https://github.com/canonical/lxd/issues/13304.
The ZFS logic has most of its functions call themselves with the filesystem datset after processing the block volume for virtual machines.
This is usually correct, but in the case of receiving a refresh stream, we specifically want to handle the snapshot rollback separately for both volumes.
(cherry picked from commit 2fc95eb5ef355ad507d4369b355b687713f920f9)

Storage: Fix refresh of zfs backed VM volumes (from Incus)

---

doc/api-extensions.md

This should cover most config options.
The ones that are still missing are options that exist in different contexts (for example, for each storage driver). We can't have a link to those unfortunately.
I've opened https://github.com/canonical/canonical-sphinx-extensions/issues/39 to look into a way of providing a target for such options.

doc/api extensions: add links to config options

---

lxd/daemon_images.go
lxd/db/images.go
lxd/images.go
test/suites/remote.sh

closes https://github.com/canonical/lxd/issues/13271

lxd/image: set `Cached: false` for pre-existing cached image

---

lxc/config/default.go
lxd-benchmark/benchmark/benchmark.go
lxd/api_metrics.go
test/suites/metrics.sh

Fixes https://github.com/canonical/lxd/issues/13301
Reproduced the issue by using `lxd-benchmark init --count=50 images:alpine/3.19` to create 50 containers and then polled `/1.0/metrics` repeatedly until LXD crashed using: `while true; do lxc query /1.0/metrics; done`
Also noticed that the new `images` remote isn't included in the `lxc` client default config, so have included that now too.
This was preventing using `lxd-benchmark` with the `images:` remote.
Fixes regression introduced by https://github.com/canonical/lxd/pull/13222/commits/07813c4d59058e3ba11b8119e9b4ad67857eb35a#diff-60d020b36265ee4faf6bd479348533eb75f0c8244f573a1ed848fd1a685ae06cR254-R257

lxd: Fix metrics crash due to absent locking

---

lxd/device/device_utils_disk.go

Fix diskAddRootUserNSEntry logic to correcly handle case when we have not-groupped UID/GID mapping like this:
`[{true false 1000 0 1} {false true 1000 0 1}]`
because right now it assumes that mapping should be like [{true true 1000 0 1}]
which is logically equivalent.
This become noticable after my change in #12718, before that this issue in logic was reproducible only if user will do something like this:
cat << EOF
uid $(id -u) 1000000
gid $(id -g) 1000000
EOF
) | lxc config set idmap raw.idmap -
which is an extremely rare usecase.
Fixes: #13325

Device: Fix diskAddRootUserNSEntry to add root mapping only if it's required

---

doc/howto/instances_access_files.md

No need to be specific that these flags work both for new and existing files, this is implied.

doc/file push: include information about permission flags

---

lxd/api.go

Fixes https://github.com/canonical/lxd/issues/12997. When the UI is disabled an error message and a navigable link to the LXD documentation is returned to the browser. 
Further improvements:
1. Return a nicer HTML error page
2. Centralize all error messages in one place to ensure the wording is consistent and avoid duplications

lxd: Display HTML error page with a link to the LXD documentation when the UI is disabled

---

lxd/daemon.go
test/suites/network_zone.sh

This should fix #12955. Did not change anything regarding BGP for now as I would like to set a test environment for that first.

lxd: Start the DNS listener after the networks are started

---

lxd/storage_volumes.go
test/suites/auth.sh

When calling `GET /1.0/storage-volumes`, the `poolName` mux variable is not populated. Using this parameter in the call to `entity.StorageVolumeURL` was leading to invalid storage volume URLs that were not in the list of URLs that the permission checker performs a lookup with.
Closes #13357

Auth: Use correct pool name in storage volume URLs when calling the permission checker.

---

lxd/instance/drivers/driver_qemu.go

VM: Wait until hotplugged vCPUs are visible

---

doc/.sphinx/build_requirements.py

myst-parser 3.0.0 causes a build failure - need to investigate more, but pinning the version is a quick workaround.

doc: pin version of myst-parser

---

doc/.sphinx/build_requirements.py

myst-parser 3.0.0 causes a build failure - need to investigate more, but pinning the version is a quick workaround.

 doc: pin version of myst-parser (stable-5.21)

---

doc/.sphinx/requirements.txt

myst-parser 3.0.0 causes a build failure - need to investigate more, but pinning the version is a quick workaround.

doc: pin version of myst-parser (stable-5.0)

---

lxd/db/migration_test.go
lxd/db/storage_volumes.go
lxd/patches.go
lxd/storage/storage.go
lxd/storage_pools.go
lxd/storage_volumes.go

Optimize database calls on `storagePoolVolumesGet` as discussed @tomponline @markylaing @roosterfish

Optimize database calls on `storagePoolVolumesGet`

---

lxd/storage/drivers/driver_zfs.go
lxd/storage/drivers/driver_zfs_utils.go
test/suites/storage_driver_zfs.sh

Fixes #12278 by making It possible for LXD to get ZFS dataset properties before setting them and avoid resetting those that already have the desired value. Performs this operation on `ensureInitialDatasets`.

Storage: Fix redundant settings of zfs properties

---

doc/.sphinx/build_requirements.py

The regression in `myst-parser` has been fixed, so we can use the latest version again.

doc: unpin version of myst-parser

---

doc/installing.md
doc/tutorial/first_steps.md

@ru-fu added `lxd` group creation information as discussed.

Add `lxd` group creation to installation process

---

test/README.md

Handy for reproducing CI failures; took me a bit to find it the first time.

test/README: Document LXD_VERBOSE

---

.github/workflows/tests.yml
doc/api-extensions.md
doc/config_options.txt
doc/rest-api.yaml
lxd/device/device_utils_usb_events.go
lxd/device/usb.go
lxd/devices.go
lxd/metadata/configuration.json
lxd/resources/usb.go
shared/api/resource.go
shared/version/api.go

Adds `serial`,  `busnum` and `devnum` as selector config keys for device type `usb`.
Feature has been added, to make it possible to distinguish between devices with identical `vendorid` and `productid`.
Fixes #13411

Device: Allow specific USB ports to be passed through to instances (from Incus)

---

lxd/device/usb.go
lxd/fsmonitor/drivers/driver_fanotify.go

Fixes regression from https://github.com/canonical/lxd/pull/13419 which was now requiring that USB devices have a `serial` file before considering them as candidates.
But not all USB devices provide a serial.
Also fixes unnecessary error from fanotify during LXD shutdown.

Device: Don't require `usb` devices to have a `serial`

---

doc/rest-api.yaml
lxc/cluster.go
lxc/config.go
lxd/api_1.0.go
lxd/api_cluster.go
lxd/cluster/config/config.go
lxd/cluster/config/config_test.go
lxd/cluster/notify_test.go
lxd/cluster/recover.go
lxd/config/map.go
lxd/config/map_test.go
lxd/config/safe_test.go
lxd/config/schema.go
lxd/config/schema_test.go
lxd/daemon_config.go
lxd/db/cluster/instances.go
lxd/images.go
lxd/instance/drivers/driver_common.go
lxd/instance/instancetype/instance_utils.go
lxd/instances_post.go
lxd/main_init.go
lxd/main_init_auto.go
lxd/main_init_interactive.go
lxd/network/network_utils_sriov.go
lxd/node/config.go
lxd/node/config_test.go
lxd/project/permissions.go
lxd/project/state.go
shared/api/server.go
test/suites/auth.sh

This PR includes cherry picks from https://github.com/lxc/incus/pull/62, https://github.com/lxc/incus/pull/63 and https://github.com/lxc/incus/pull/64. 
Essentially the concept of hidden config entries is removed and the overall server configuration is normalized to use a `map[string]string` instead of `map[string]any` which was required to support the hiding of passwords using the special `true` indicator as value. 
As we now have the fine grained permission concept in place a user requires at least the `can_edit` entitlement on the `server` entity type in order to view and edit the server configuration. Just by having the `viewer` entitlement on `server` doesn't return the server's configuration.
If the necessary permissions are granted we can also safely return the passwords.

Config: Remove concept of hidden config entries and consistently use strings

---

doc/howto/instances_configure.md

Relates to [ODA issue 16](https://github.com/canonical/open-documentation-academy/issues/16)
Change provides a reference the lxc config device override command and a little context.

Doc: Add reference to device override cmd in how to instance conf

---

.github/workflows/tests.yml
Makefile

Stop building `lxd-agent` and `lxd-migrate` in the default `make` target.

Finer grain builds

---

lxd/storage/drivers/driver_btrfs.go
lxd/storage/drivers/driver_lvm.go
lxd/storage/drivers/utils.go
test/suites/storage.sh

A few goals here RE #13339:
- Add some minimal tests for `source.wipe` so that the logic there is covered at least a little
- Fix two bugs I found while adding those tests:
- `wipeBlockHeaders` in the LVM backend was given the wrong parameter (lv name instead of the device path)
- Btrfs would create a default loop device instead of using `source` when `source` is an empty raw block device or MBR/GPT
The tests I've added wouldn't catch the btrfs bug here since it's not directly relevant to `source.wipe`. See my comment below for more details on why this wasn't caught by the tests sooner.

Storage: Fix `source.wipe` for lvm and correctly detect raw disks in btrfs

---

doc/howto/instances_troubleshoot.md

https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1959047/comments/5 is a good example where the systemd debug flag was used.

doc/howto/instances_troubleshoot: add instructions for debugging systemd

---

lxd/api_1.0.go
lxd/cluster/membership.go

Those were reported by the CodeQL check in https://github.com/canonical/lxd/pull/13465.

Config: Add int conversion upper bound check

---

doc/howto/network_increase_bandwidth.md

The current document does not work properly for Ubuntu 22.04 and probably any version >= 18.04.
I updated this page to include details on how to do this for versions 18.04+ and kept the original section, renaming that to be for versions <= 17.04.
Also added an example command at the bottom on how to change the queue.tx.length in the default LXD profile so that change would apply to all containers.

Update network_increase_bandwidth.md document with details for u18.04+

---

doc/cloud-init.md

Resolves https://github.com/canonical/open-documentation-academy/issues/63

doc: configure cloud-init from a file

---

lxd/daemon.go
lxd/task/group.go

lxd/daemon: Fix task mutex double unlock

---

lxd/instance_state.go
lxd/instances_put.go
test/suites/basic.sh

- Prevents stopping frozen instances without supplying `--force` (aka `"timeout": 0` in the API); frozen instances must either be started explicitly before graceful stop or forcefully shut down
- #12578
- `PUT /instances/{name}/state` with `"action": "start"` now unfreezes frozen instances
- Fixes `lxc start --all` for frozen instances
- #12491
This was fixed in incus with the same patch as in #12493
Not sure if this warrants an API extension: if users were expecting `start` to fail on frozen instances, then this does break that workflow. Happy to add one if needed.

LXD: Fix start and stop for `FROZEN` instances

---

lxd/storage/drivers/driver_common.go
lxd/storage/drivers/driver_lvm.go
lxd/storage/drivers/driver_zfs.go
lxd/storage/drivers/driver_zfs_utils.go
lxd/storage/drivers/driver_zfs_volumes.go
lxd/storage/drivers/interface.go
lxd/storage/drivers/utils.go
lxd/storage/drivers/volume.go
test/suites/storage.sh

This rounds ZFS volume sizes using `zfs.blocksize` or the openzfs default 16KiB instead of LXD's default 8KiB. Reported in #13420.
It looks like the default was changed in OpenZFS in Q3 2021: https://github.com/openzfs/zfs/pull/12406
I'm not super pleased with the refactor of `roundVolumeBlockSizeBytes` to take a `vol Volume`, but we need a reference to the volume in order to query its config keys. This seemed like the least invasive way to accomplish it.
The new test fails before patches and passes after.

Storage: Round ZFS volume sizes to nearest 16KiB

---

lxd/network/driver_ovn.go
lxd/network/openvswitch/ovn.go

The OVN `lb-add` command that adds entries to the `Load_Balancer` OVN northbound table has a bug that in certain situations allows multiple records with the same name to be created.
This then causes issues with the `lb-del` command that does not support the scenario of duplicate records of the same name.
This fix has multiple facets:
1. Changes the way LXD deletes existing load balancer entries by searching for them by name and then deleting them by UUID, this supports multiple records of the same name existing.
2. Changes the way LXD associates load balancer entries to a logical router by using the `add` database command directly rather than `lr-lb-add` that allows multiple records to exist with the same name.
3. Drops unused associated of load balancers to logical switches.
Fixes …

Network: Work around OVN lb-add bug that allows multiple Load_Balancer records to be created with same name

---

lxd/instance.go
lxd/instance/drivers/driver_lxc.go
lxd/instance_rebuild.go
lxd/instances_post.go

I made these changes while investigating #13220

Minor refactorings

---

doc/howto/logs_loki.md

doc/howto/logs_loki: `loki.instance` needs to match the Prometheus job name

---

lxd/instance/drivers/driver_qemu.go

…GUEST_CID
We can't hardcode VHOST_VSOCK_SET_GUEST_CID ioctl() number, because it may be different depending on the platform.

instance/driver_qemu: properly calculate VHOST_VSOCK_SET_GUEST_CID

---

lxd/storage/drivers/driver_btrfs_utils.go

ioctl() numbers are architecture-dependent (endianness and not only)

storage/driver_btrfs_utils: properly calculate BTRFS_IOC_SET_RECEIVED_SUBVOL

---

lxd/idmap/shift_linux.go

Workaround idmapped mounts-related issue in Linux kernel 6.9
(cherry picked from commit ec223f75e7056f271fb84be56980243cd68e67b3)

shared/idmap: Make get_userns_fd configure the userns

---

lxd/seccomp/seccomp.go

Let's tighten capability checks in mknod interception code to align this with what we have in the kernel. So, if mknod interception is enabled then only user with CAP_MKNOD in the container's initial user namespace can use it.

Seccomp: Tighten container capability checks a bit to align with kernel behaviour

---

doc/metrics.md

Changed: /var/snap/prometheus/common/tls/ to /var/snap/prometheus/current/tls/ as the location for the metrics.crt, metrics.key & server.crt files in Prometheus.
I was getting no data in Grafana after following this page.
Looked into my syslog and found the following message:
2024-05-11T03:08:48.449690+00:00 lxd-metrics prometheus.prometheus[2973]: ts=2024-05-11T03:08:48.448Z caller=manager.go:212 level=error component="scrape manager" msg="error creating new scrape pool" err="error creating HTTP client: unable to load specified CA cert /var/snap/prometheus/86/tls/server.crt: open /var/snap/prometheus/86/tls/server.crt: no such file or directory" scrape_pool=lxd
So I made a copy of server.crt in the /86/tls/ folder where the message states it was missing from and that error went away. …

Update metrics.md Changed /common/tls to /current/tls for metrics.crt, metrics.key & server.crt location

---

doc/howto/grafana.md

Updated note at bottom of page with details on where to find the Prometheus job_name value, the command to set the value as the loki.instance key and the command to check/verify the value that was set.

Update grafana.md with additional details on setting loki.instance key value.

---

lxd/firewall/drivers/drivers_nftables.go
lxd/firewall/drivers/drivers_nftables_templates.go
lxd/firewall/drivers/drivers_xtables.go
lxd/firewall/firewall_interface.go
lxd/network/driver_bridge.go
test/suites/container_devices_nic_bridged.sh

Blocks DNS requests originating outside the managed bridge per #13081.
Still working on tests and evaluating if/how this is relevant to fan bridges.

Network: Block external req to `bridge` managed dns service

---

doc/Makefile.sp

In `false || (true; exit 1)`, the `exit 1` only exists the subshell. Since the intention is to terminate the whole command pipeline, `{}` should be used instead.
Here it is in action:
Will sleep 30:
```
false || (true; exit 1) ; sleep 30
```
Will exit immediately, closing the terminal window:
```
false || { true; exit 1; }; sleep 30
```

doc/Makefile.sp: replace subshell by command group

---

lxd/instance/drivers/driver_qemu.go

Fixes [#13495](https://github.com/canonical/lxd/issues/13495).
Helps to avoid problems with [these](https://github.com/canonical/lxd-ci/pull/177) tests.
The old `blockNodeName` function was modified, renamed and repurposed to also help generating device tags for QEMU.

Handle long device names when creating QEMU device tags

---

lxc/config/remote.go
lxc/network_forward.go
lxc/network_load_balancer.go
lxd/network/driver_bridge.go
lxd/network/driver_ovn.go
lxd/network/network_utils.go
lxd/network/network_utils_test.go

Addresses remaining discussions in #13379.
Depends on #13543
Closes #13422

Automatic IP allocation follow up

---

doc/cloud-init.md
doc/howto/instances_create.md

While we could use `cloud-init` to install the LXD agent on a VM image that doesn't yet have it, it is cumbersome.
The main issue is that by the time we have the manually installed VM, `cloud-init` has already fired as during the first boot. As such, even if we provide it with a new recipe, it will simply not process it.
Furthermore, when `cloud-init` detects it executes in a LXD instance, it tries to use the LXD data source which depends on the `lxd-agent` to be functional.
Technically, providing a config disk would allow to side-step this catch-22 but then you have to ensure `cloud-init` was "re-armed" (`cloud-init clean`) so that it processes the "new" recipe upon the next reboot.
At this point, it is probably easier/simpler and less confusing to simply give instruction on how to run …

Remove the `cloud-init` way of installing the LXD agent

---

lxd/apparmor/instance_lxc.go

As noticed by Aleks we have duplicated mount options rules for unprivileged containers.
The apparmor parser does rule deduplication so it doesn't really matter. However, the "limited" part of the "Allow limited modification of mount propagation" comment was misleading. As such, it's best to avoid the duplicated rules and make it clear that privileged containers have limited permissions while unprivileged ones have unlimited permissions for mount options.
Fixes "lxd/apparmor/lxc: remove dup mount options rules" commit 2e55b23f9f24537ce4469f6e5f0fd70f55ef615d.
lxd/apparmor/lxc: reorganize mount options rules for priv containers

lxd/apparmor/lxc: reorganize mount options rules for priv containers

---

.github/workflows/tests.yml

This reverts commit 21244792541688d4fa9a7b0b6dab9c9e9ffcda74.
With `swagger` version 0.31.0 we no longer have the crash.

Revert "github: run code-tests with 1.21 to avoid swagger crash"

---

lxc/network_forward.go
lxc/network_load_balancer.go

The location header must be parsed into a URL before extracting the IP address. This is so we can get the IP from the path only, and not from the full URL string (which may contain query parameters).

lxc: Parse location header into URL

---

lxd/device/device_utils_disk.go
lxd/device/tpm.go
lxd/instance/drivers/driver_qemu.go
lxd/util/sys.go
test/suites/container_devices_tpm.sh

Fixes #12539.
These changes generally include getting the file descriptor of the directory of a socket's file to use an alternative shorter path to the same socket. This same fix is applied during VM start (with disk virtiofsd sockets, qemu config virtiofsd sockets and the swtpm sockets), and when hotplugging a disk on a VM (with disk virtiofsd sockets)

Use shorter virtiofsd and swtpm socket paths

---

lxd/archive/archive.go

Closes https://github.com/lxc/incus/issues/815
(cherry picked from commit c72cfab8a91db44e8f1871cf7bf09c9282280915)

lxd/archive: Properly anchor exclude rules - from Incus

---

README.md
doc/authentication.md
doc/debugging.md
doc/howto/instances_troubleshoot.md
doc/howto/move_instances.md
doc/howto/network_bridge_firewalld.md
doc/index.md
doc/reference/storage_powerflex.md
doc/tutorial/first_steps.md

The link checker conveniently tells us when it follows temporary or permanent redirects. I went through the list of those and update our doc to use more direct links where applicable. There are some temporary/permanent redirects left in place, mostly due to redirecting to localized landing pages.

doc: Use more direct HTTP links where possible

---

client/connection.go
lxd-migrate/main_migrate.go
lxd-migrate/utils.go
shared/util_unix.go
shared/util_windows.go

If tool `lxd-migrate` is capable of connection to a local LXD unix socket, first offer the user option to use the socket.
In addition, go client function for connecting to a LXD unix socket is expanded to check for snapped LXD unix socket.

Support local unix socket in lxd-migrate - from Incus

---

shared/cert.go

In the following made up conditions:
* a remote LXD server `s` has its time set to `13:42:00`
* a client `foo` has its time set to `13:42:15` (15s in advance of `s`)
* a remote add token is created for `foo`
* `foo` uses the token and since it's brand new, it creates its self-signed cert and save its current time in the Not Before field: 13:42:15
* `s` inspect `foo`'s cert and refuses it because it is in future
In the above situation, the fact that a token was used make it easier to trip on a time delta between the client and server because the cert is create on the spot before being sent to the server.
Having the client set a Not Before time slightly in the past should make it easier to interact with remote servers that are slightly "in the past".
Fixes #13388.

shared/cert: Set Not Before in self-signed cert to now-1minute
