client.go
container.go

Spotted these while doing my slides, just minor annoyances.

More miscellaneous fixes

---

client.go
lxd/api_1.0.go
lxd/trust.go
operation.go
util.go

Signed-off-by: S.Çağlar Onur <caglar@10ur.org>

make golint happy

---

lxc/file.go

Signed-off-by: S.Çağlar Onur <caglar@10ur.org>

make sure enough number of arguments provided

---

client.go
lxc/config.go
lxc/remote.go
lxd/trust.go
specs/command-line-user-experience.md
specs/rest-api.md
test/remote.sh
util.go

implement the 'lxc config trust *' cli

---

client.go
lxc/delete.go
lxd/operations.go
operation.go
specs/rest-api.md

Update status/result codes for API improvements

---

client.go
config.go
lxc/action.go
lxc/config.go
lxc/create.go
lxc/delete.go
lxc/exec.go
lxc/file.go
lxc/finger.go
lxc/list.go
lxc/remote.go
lxc/snapshot.go
lxd/certificates.go
test/remote.sh

Actually check password

---

client.go

So this fixes our websocket negotiation problem so they all work. However, it exposes a larger race condition around `exec`: what happens when the command finishes but the client tries to connect afterwards? If I run `cat /etc/issue` via a websocket it seems to work (as in the tests), but if I run that over an http socket, the resulting overhead (perhaps crypto negotiation) causes it to fail with:
`error: status is Success, can't connect`
(alternatively, sometimes it succeeds with blank output, presumably because the output was written to the PTY before the client connected; very rarely it actually works as expected.)
What do we want to do in this case? We could cache all the command output, but if someone runs a command with Very Lots Of Output, they can EOM the lxd instance. If we don't …

Negotiate websockets correctly

---

specs/image-handling.md

spec: Update image handling spec to add support for aliases

---

Makefile
flex.go

Add a 'make dist' target for packaging

---

lxc/help.go

fix `lxc help foo`

---

lxd/containers.go

Use petname to generate names when not specified

---

lxd/containers.go

check that the container is running in exec API call

---

specs/image-handling.md

rest: Update image handling doc to fix wrong key name

---

Makefile
client.go
lxc/Makefile
lxc/exec.go
lxd/Makefile
lxd/operations.go
lxd/response.go
operation.go
test/main.sh

...and other bugfixes for the new-style exec.

Remove make target

---

lxc/action.go
lxd/containers.go

Wait on actions, and then also fix a bug which causes shutdown to always fail if we wait on actions :)

Fix shutdown

---

lxd/containers.go
lxd/daemon.go
lxd/main.go

Some code cleanup

---

lxd/containers.go

Another style fix; this occurrs in several places in the code; the plan is to
convert the larger (n > 2 fields) to using structs.

Use struct unparsing instead of by-hand unparsing

---

lxd/daemon.go

This reverts commit 2ef7d47ca36a86a21d7a7619ef6518ca358eb6e7.
It's not obvious to me why this allows the tests to pass but fails when things
are actually run, but it does. We need this fix, but apparently I need to read
some more documentation :). Revert it for now, until we can figure out what's
going wrong.

Revert "Fix race in tomb invocation"

---

lxd/daemon.go

This exactly the same as 2ef7d47ca36a86a21d7a7619ef6518ca358eb6e7, but with a
nil check so that it doesn't crash when a TCP socket isn't bound.

Fix tomb race condition

---

lxc/config.go

Fix a few places where we use args without checking for them

---

Makefile

Fix Makefile after flex.go was moved

---

lxc/main.go
lxd/main.go
po/lxd.pot
test/static_analysis.sh

Add a --version flag to lxc and lxd

---

specs/database.md

spec: Initial database specification

---

README.md

readme updates for lxd release

---

lxd/main.go

Seed lxd's random number generator

---

specs/image-handling.md
specs/rest-api.md

specs: clarify image handling

---

lxd/api10.go
lxd/api10_32bit.go
lxd/api10_64bit.go
lxd/api10_arm.go

I *think* this should fix #206, but I'm not entirely sure :)

Fix arches

---

specs/database.md

spec: Fix DB spec types of foreign keys

---

config.go
fuidshift/idmap.go
fuidshift/main.go
lxc/delete.go
lxc/exec.go
lxc/file.go
lxd/certificates.go
lxd/containers.go
lxd/daemon.go
lxd/idmap.go
lxd/list.go
lxd/networks.go
lxd/operations.go
lxd/response.go
shared/operation.go

Signed-off-by: S.Çağlar Onur <caglar@10ur.org>

remove some redundant code (mainly else blocks), stop using 'make(Type, ...0)'

---

client.go
config.go
lxc/main.go
po/lxd.pot

Always create the client certificate on first use

---

lxd/certificates.go
lxd/containers.go
lxd/daemon.go
lxd/db.go
lxd/images.go
lxd/list.go
lxd/main.go

Move the code into lxd/db.go
and have it always open.

move database into Daemon class

---

specs/rest-api.md

specs: Update wording of source dict (container creation)

---

lxd/containers.go
po/lxd.pot
test/snapshots.sh

Convert snapshot, file pull, and container get to using the database.

Db.snapshots.3

---

lxd/containers.go

Only list containers, not snapshots from /1.0/containers

---

lxd/containers.go

Add network default configuration

---

lxd/db.go

add schema and db updating

---

README.md
lxd/images.go

Fix a couple of typos

---

lxc/list.go
lxd/certificates.go
lxd/containers.go
lxd/daemon.go
lxd/db.go
lxd/images.go
lxd/main.go

db: cleanup tx and rows on errors

---

lxc/info.go
lxc/main.go
po/lxd.pot

Doesn't show any more than list does yet.  (ip address
info etc isn't yet exported over rest)

Implement the 'info' command

---

client.go
lxd/containers.go
lxd/operations.go
lxd/response.go
shared/operation.go
shared/util.go
test/basic.sh

Move the exec protocol to three separate websockets.

Multiple websockets

---

test/basic.sh

test: Update to use lxd-images

---

specs/rest-api.md

specs: Add environment passing to exec

---

test/basic.sh

Add support for local test images

---

test/main.sh
test/snapshots.sh
test/static_analysis.sh

tests: A few fixes

---

client.go

Fix the build

---

lxd/main.go

fixed startup crash if NewDaemon returns error

---

test/main.sh

Let's not eat all the CPU :)

---

README.md

update readme for new lxd path and running as root

---

lxd/containers.go
lxd/networks.go

Use newLxdContainer everywhere

---

lxd/containers.go
lxd/images.go

Compression detection added

---

.travis.yml
test/basic.sh
test/database.sh
test/main.sh

tests: Run more tests in Travis and catch DB locks

---

lxd/containers.go

Be a little more intelligent when receiving config values

---

lxd/images.go

* don't defer a close() of a file that was never opened
* respect X-LXD-Fingerprint if it is set
* s/uuid/hash, since we've got a hash and not a uuid

Fix several nits with imagePost

---

scripts/lxd-images

lxd-images: Remove debug code

---

.gitignore
Makefile
po/fr.po
po/lxd.pot

Add an initial french translation

---

lxc/config.go
lxd/containers.go
test/config.sh

Fix the tests and a few more nits regarding profiles.

Profiles.e

---

specs/rest-api.md

fix typo in rest spec

---

test/main.sh

tests: Run the DB lock test last

---

client.go

There are other places we need to do this, but this one Closes #332

image alias create: parse error from server

---

Makefile
po/fr.po
po/lxd.pot

i18n: Fix multi-line strings

---

client.go

This is the last such bug i could find.

make sure to check for error response at profile create

---

.travis.yml

travis: Use gettext backport

---

lxc/info.go
lxc/list.go
lxd/containers.go
shared/container.go

add init pid and ips to lxc info output

---

lxd/migration/migrate.go

Depend on the URL proto url that protoc outputs

---

specs/database.md

Fix markdown

---

specs/command-line-user-experience.md
specs/image-handling.md

specs: Add command line output examples

---

client.go
lxc/config.go
lxc/image.go
lxd/db.go
lxd/images.go
po/lxd.pot
shared/image.go

Implement 'lxc image edit'

---

specs/configuration.md

specs: Add details about the default profile

---

client.go
lxc/image.go
lxd/images.go
po/lxd.pot
shared/image.go
specs/rest-api.md

Improve the 'lxc image list' output

---

scripts/lxd-images

lxd-images: Use pre-packed images

---

client.go
lxc/move.go
lxd/containers.go
lxd/migration/migrate.go

We should migrate the container config along with the container. We should also actually respect profiles on create.

Migrate config

---

lxd/containers.go
lxd/images.go

Use lxc's load config instead of our own crappy config parsing

---

lxd/containers.go
lxd/images.go
lxd/migration/migrate.go
lxd/migration/rsync_test.go

Consistent tempfile naming

---

client.go
lxd/images.go
po/fr.po
po/lxd.pot
specs/rest-api.md

Not sure if I did the right thing with GetText. Tested with a few combinations, e.g. Euro sign, arabic signs.
Closes #353

Added URL-Encoding in LXD header

---

client.go
po/lxd.pot

Changed certificate messages Closes #308

---

client.go

Errors were not shown with image import

---

lxd/containers.go
lxd/migration/migrate.go
lxd/migration/rsync.go

At some point we must have stopped creating the container directory, so rsync started complaining.

Migration fixes

---

specs/command-line-user-experience.md

specs: Make "image import" and "publish" more consistent

---

po/ja.po

Hi, I made an initial Japanese translation.
This is untested, rough-cut version.
However this may be a good starting point.
Could you review this pull request?
Thanks!

Add an initial Japanese translation

---

lxc/launch.go
lxc/move.go

The most used command should be in the help

---

lxc/image.go
lxd/containers.go
lxd/db.go
lxd/images.go
shared/image.go

This is based on Jens' work, I've just rebased it on current lxc/master.

Add support for short hashes

---

lxc/move.go
lxd/containers.go
lxd/daemon.go
lxd/images.go
lxd/migration/migrate.go
lxd/migration/migrate.pb.go
lxd/migration/migrate.proto
lxd/response.go
shared/idmap.go
test/basic.sh
test/main.sh
test/migration.sh

Implement `lxc move ...` for containers that aren't running. I'll do copy on Monday.

Nonlive migration

---

lxc/launch.go

Fix lxc launch with remote image

---

specs/command-line-user-experience.md

specs: Update command-line spec for filters in list

---

lxc/list.go
lxc/list_test.go
po/lxd.pot
test/config.sh
test/remote.sh

Add support for filters in `lxc list`

---

lxc/config.go
lxc/copy.go
po/lxd.pot

translate all the errors in the client

---

lxd/db.go

always use NoSuchImageError

---

client.go
lxc/image.go
po/lxd.pot
specs/command-line-user-experience.md

Implement 'lxc image copy'

---

client.go
lxd/api10.go
specs/rest-api.md

All key/value config storage should be dicts

---

specs/architectures.md
specs/configuration.md
specs/database.md
specs/image-handling.md

Some updates to the specs

---

lxd/containers.go
lxd/images.go
lxd/remote.go
shared/image.go
specs/rest-api.md

Fixing a few of the remaining 0.5 bugs

Small fixes for 0.5

---

lxd/daemon.go
lxd/db.go
lxd/profiles.go
shared/container.go
shared/db.go

Use a temporary go-sqlite3 fork

---

.gitignore
Vagrantfile
scripts/vagrant/install-go.sh
scripts/vagrant/install-lxd.sh

this tooling:
* uses 14.04 official image
* Install the ubuntu-lxc ppa
* Install go
* Build, setup LXD from source
* Startup LXD using upstart
Signed-off-by: John Brooker <john.edw.brooker@hp.com>

Vagrant - Vagrant config for lxd startup

---

lxd/containers.go

1. Don't have a double negative in the condition for applying id maps
2. Correct the condition for applying id maps
3. Remember to propagate things from profiles

Fix security.priveleged

---

lxd/api10_32bit.go
lxd/api10_64bit.go

Define some more architectures

---

scripts/lxd-images

lxd-images: Use a proxy friendly GPG server

---

lxc/copy.go
lxc/move.go
lxd/containers.go
test/basic.sh

persist mac address across container boots

---

lxd/images.go

fixed hash in export Closes #452

---

client.go
config.go
lxc/image.go
lxd/images.go
po/fr.po
po/ja.po
po/lxd.pot
specs/command-line-user-experience.md
specs/rest-api.md
test/basic.sh
test/migration.sh
test/remote.sh

This includes all but one of the commits of my other pull request (will rebase on this one is merged) and addresses the other test failures.
It also fixes a few more issues found along the way.

Random fixes

---

specs/command-line-user-experience.md

specs: Fix alias description

---

shared/util.go

Only allow strong ciphers

---

lxc/info.go
test/remote.sh

Fix lxc info

---

test/basic.sh

This pull request will fail to pass Travis, that's because it's introducing tests for currently broken code paths which should be resolved.
I've filed individual github issue for those.

Add some more tests

---

lxd/containers.go

fix the travis build for new go vet release

---

lxd/api10.go
lxd/certificates.go
lxd/db.go

Move the trust password to the database

---

lxd/containers.go

short id launch fixed Closes #498

---

lxd/images.go
lxd/profiles.go

catch cases where we leave db locked

---

lxc/file.go
lxd/containers.go

Signed-off-by: Nobin Mathew <nobin.mathew@gmail.com>

Fix "lxc file push <file> <container>/<target>/<filename>"

---

lxd/daemon.go
lxd/response.go
shared/json.go
shared/util.go

A bit java-esque with the readers and buffers, but it works.

Prettier debugging

---

test/basic.sh

Extend the file test a bit

---

lxd/daemon.go
lxd/db.go
lxd/profiles.go
lxd/response.go
shared/container.go
shared/db.go

Use new txlock=immediate option when opening sqlite3 db.

---

test/basic.sh

Else the testsuite waits for y/n

basic test: do rm -f

---

test/basic.sh
test/main.sh

test: Fix lxc wrapper

---

lxd/containers.go

only uidshift files in unprivileged containers

---

client.go

Read proxy from environment in custom http Transport

---

specs/image-handling.md

specs: Define file templating

---

lxd/api10.go
lxd/certificates.go
lxd/containers.go
lxd/db.go
lxd/images.go
lxd/profiles.go
shared/db.go

These commits are intended to solve the remaining db locked issues.
Since we are using BEGIN EXCLUSIVE, db.Begin can return a dblocked error.  Retry in that case as we do in queries and execs.

2015 04 22.push1

---

test/main.sh

now that we are doing lxd | tee, $! gives us the pid of tee.
So just find all lxds in our pgrp and kill them.

kill our lxds

---

lxd/debug.go
lxd/main.go
test/main.sh
test/profiling.sh

cpu profiling happens continuously.
memory profiling happens when lxd receives a SIGUSR1.

[RFC] Implement cpu and memory profiling

---

lxc/list.go

List the # snapshots in a column.
If listing a single container, show the list of snapshots.  (i'm not convinced
this is what we want, since info can show it anyway and this seems superfluous,
but it's there for now)
Closes #530

list: list snapshots

---

test/main.sh

- Require root
- Check for test dependencies
- Drop extra debug code

tests: Improve test runner

---

client.go
lxc/copy.go
lxc/snapshot.go
lxd/containers.go
shared/util.go
test/snapshots.sh

Make 'lxc copy' work with with snapshots

---

lxd/containers.go

Set container dir acl when creating container from copy

---

lxd/api10.go
lxd/containers.go
lxd/images.go
shared/util.go
shared/util_32bit.go
shared/util_64bit.go
test/main.sh

Implement btrfs optimization

---

lxd/api10.go
lxd/containers.go
lxd/images.go
shared/util.go

fs.Type varies between arches, so don't bother returning it

---

lxd/containers.go

don't set the log path twice

---

lxd/containers.go
shared/util.go

Fix travis and ppc64el issue

---

lxd/containers.go

only shift unprivileged rootfses when creating

---

test/main.sh

skip the fdleak test temporarily

---

lxc/config.go
po/lxd.pot

don't destroy user's input if it was invalid

---

lxc/main.go
po/lxd.pot

Rebased off lastest trunk, also, a single commit now instead.
Signed-off-by: Christopher Glass <christopher.glass@canonical.com>

Added first run doc on importing images.

---

test/fdleak.sh
test/main.sh

verbosify the leaky fds test

---

client.go
lxc/config.go
po/lxd.pot
shared/container.go

remaining todos:
write a nice help for the top of the file we show in the editor
should volatiles (like macaddr) be not presented?

implement lxc config edit

---

lxd/containers.go

This allows users to read/write from any file on the system, which is a bad
thing.

prevent setting lxc.logfile in raw.lxc

---

lxc/config.go

lxc config: show example of directory binding into container

---

lxd/db.go
lxd/db_test.go

The previous  branhc introducing cascading functionlaity forgot the
database schema migration code, so this commit introduces such a
migration.
The logic is: for each table with future cascade behavior: create a
temporary table with all the "real" table's data. Delete the real table.
Recreate the real table with the modified schema (adding the ON DELETE
CASCADE on foreign keys), then repopulate the table with the contents of
the temporary table.
Signed-off-by: Christopher Glass <christopher.glass@canonical.com>

Added data migration for ON DELETE CASCADE

---

lxd/containers.go
shared/util.go
test/basic.sh

exec: chown opened pty to container root

---

lxd/containers.go

Apply raw.lxc at end of container setup

---

lxd/main.go
po/lxd.pot

lxd: exit if there are extra unknown arguments

---

lxc/config.go
lxc/delete.go
lxc/image.go
lxc/launch.go
po/lxd.pot

Switch out the word 'resource' in some places.

---

client.go
lxc/list.go
lxd/containers.go
lxd/main.go
shared/container.go

Signed-off-by: Nobin Mathew <nobin.mathew@gmail.com>

Add recursion support to /1.0/containers #471

---

lxd/networks.go

Signed-off-by: Matt Morrison <matt@mojo.net.nz>

Add recursion support to /1.0/networks #474

---

lxc/profile.go
po/lxd.pot

add `lxc profile copy` to help output

---

client.go
lxd/containers.go
po/lxd.pot

Signed-off-by: Nobin Mathew <nobin.mathew@gmail.com>

Add recursion support to /1.0/containers/{name}/snapshots #472

---

lxd/containers.go

+ a minor refactor
Signed-off-by: Matt Morrison <matt@mojo.net.nz>

sort containers list by container name

---

lxc/remote.go
po/lxd.pot
test/remote.sh

Signed-off-by: Ben Booth <benbooth493@gmail.com>

implemented password flag from lxc remote add

---

lxd/images.go

When trying to use "lxc image import" I ran into a problem where my tarball metadata.yaml was not at the "root" level of the tarball, but was rather at "./". The error message that was returned by lxd was not very helpful (IMO): "Could not get image metadata: exit status 2".
This PR attempts to address this by making the error messages a bit more clear by changing the wording and including more stderr.
Signed-off-by: Josh Butikofer `<joshbutikofer+github@gmail.com>`

Improved debug and error messages when importing new tarball images.

---

lxd/containers.go
test/config.sh

check new config before saving it to db

---

README.md

finger is no longer valid, so let's not pretend it is

---

lxc/image.go
lxd/images.go
shared/image.go

Fix lxc image edit

---

README.md
client.go
lxc/config.go
lxc/image.go
lxd/api10.go
lxd/containers.go
lxd/daemon.go
lxd/db.go
lxd/debug.go
lxd/main.go
shared/container.go
shared/util.go
specs/command-line-user-experience.md
specs/daemon-behavior.md
specs/rest-api.md
test/main.sh
test/serverconfig.sh
test/stresstest.sh

Various features targeted to milestone 0.11

---

lxd/db.go
lxd/db_test.go
lxd/response.go

send a proper 404 for missing profiles

---

lxc/image.go
lxd/containers.go
lxd/images.go
lxd/template.go
shared/architectures.go
specs/image-handling.md

Add file templating support

---

lxc/delete.go

Add syntax to remove snapshot into `lxc delete` help

---

po/de.po

Signed-off-by: Felix Engelmann <felix-lxd@nlogn.org>

Add initial German translation

---

lxd/containers.go

Fix hang on exec during non-interactive runs

---

lxd/containers.go

Drop useless goroutine

---

.travis.yml

run using go 1.3 and 1.4 in travis

---

.travis.yml

Also run tests on go tip, but allow failures

---

lxd/containers.go

Sort device entries

---

specs/command-line-user-experience.md

Fixes issue #783  - Typo in tar command

Fixed typo in tar command

---

config/bash/lxc.in

Closes #172
Signed-off-by: Chris J Arges <christopherarges@gmail.com>

Add basic bash completion script.

---

lxd/devlxd.go

clean up devlxd socket if necessary

---

test/lvm.sh

Skip LVM tests when lvm2 is not installed

---

lxd/containers.go
lxd/template.go
shared/util.go
specs/configuration.md
specs/image-handling.md
specs/rest-api.md

Branch with all the bits needed to get us to properly import Ubuntu cloud images and support cloud-init with them.

Image handling fixes and improvements

---

.gitignore

See [My Atom Install](http://rene.jochums.at/2015/06/14/atom.io-my-editor-of-choice/) - [Atom](https://atom.io) is the best go editor available. :)

Ignore .tags, .tags1 which Atom-ctags generates.

---

lxd/container_snapshot.go

Several failure cases weren't handled correctly here; we need to delete
both the directory if we fail, and the db data for the snapshot (if we had
gotten far enough to insert it).
Closes #823

cleanup after failed snapshot

---

lxd/containers.go

Don't include the leading / in publish tar's, fixes issue #839.

---

client.go
lxd/containers_post.go

Fix IPv6 with websockets

---

lxc/main.go
lxd/container_new.go
lxd/daemon.go
lxd/main.go
shared/idmapset.go
shared/log.go

An example of using log15, if people like it i will use it everywhere here.
Refs issue #482

Use log15 for logging.

---

lxd/certificates.go
lxd/db.go
lxd/db_test.go
shared/cert.go
shared/util.go
specs/rest-api.md

See my file comment(s) please.
Fixes issue #470

Implement feature request #470.

---

client.go
lxc/config.go
lxc/help.go
lxc/main.go
lxd/container_file.go
po/lxd.pot
scripts/lxd-images
shared/cert.go
shared/util.go
test/remote.sh

User experience improvements

---

.travis.yml
Makefile
README.md

Signed-off-by: Abhishek Chanda <abhishek.becs@gmail.com>

Automatically install deps in the default target

---

client.go
lxd/devlxd_gc.go
lxd/images.go
specs/dev-lxd.md
test/devlxd-client.go

0.14 features

---

lxd/template.go

Turn off autoescaping for LXD templates

---

scripts/lxd-images

Implement basic simplestream support in lxd-images

---

lxd/images.go

Fix container rootfs mode in split images

---

lxd/db_container.go

Sorry for making a bug into it, ty to @mikemccracken

Fix dbContainerCreate.

---

lxd/daemon.go

fix (?) recent fdleak race that is cropping up in travis

---

lxd/container_exec.go
lxd/container_new.go
lxd/db_container.go
specs/configuration.md

Implement environment.* config keys

---

lxd/storage_lvm.go
test/lvm.sh

Delete .lv symlink when container is deleted

---

test/lvm.sh

Trivial: Add test checks for image .lv symlink

---

test/lvm.sh

tests: Fix LVM test on btrfs

---

lxd/main.go
shared/log.go

Don't crash when log path doesn't exist

---

lxd/container_new.go
lxd/container_post.go
lxd/container_put.go
lxd/container_snapshot.go
lxd/containers.go
lxd/containers_post.go
lxd/daemon.go
lxd/db.go
lxd/db_test.go
lxd/migration/migrate.go
lxd/profiles_test.go
lxd/storage.go
lxd/storage_lvm.go
lxd/template.go
test/basic.sh
test/filemanip.sh
test/lvm.sh
test/migration.sh
test/snapshots.sh

Rename /var/lib/lxd/lxc to /var/lib/lxd/containers

---

lxd/daemon.go

Use a single socket list

---

lxd/daemon.go
lxd/db.go

Fix crash during /var/lib/lxd/lxc migration

---

client.go
lxc/config.go

client: make SetContainerConfig look sync

---

lxd/storage_lvm.go

check for error on s.ImageCreate

---

lxc/main.go
po/lxd.pot

fix `lxc`'s error messages to be more helpful

---

test/lvm.sh

Use wipe in lvm test

---

lxc/config.go
po/lxd.pot

'lxc config show remote:': go ahead and show remote config

---

lxd/container.go

Fix templating for privileged containers

---

specs/storage-backends.md

Includes table tracking what is currently optimized

Add initial documentation for storage backends

---

lxc/image.go
lxc/profile.go
lxc/publish.go
lxd/daemon.go

Various fixes

---

scripts/lxd-images

lxc-images: Add a new --public flag

---

lxd/storage.go

Clarify log message for ContainerCreateWithImage

---

lxd/containers_post.go
lxd/db_images.go
lxd/db_test.go
lxd/images.go
test/migration.sh

Fix container copy when baseImage isn't set

---

Makefile
README.md
lxc/main.go
lxd/container.go
lxd/db.go
lxd/db_profiles.go
lxd/db_test.go
lxd/migration/migrate.go
lxd/profiles_test.go
po/lxd.pot

A few fixes for things I ran into today.

Fix some random stuff

---

lxd/container.go
lxd/daemon.go
lxd/db_containers.go
lxd/db_devices.go
lxd/db_images.go
lxd/devices.go
lxd/devices_test.go
lxd/devlxd.go
lxd/devlxd_test.go
lxd/images.go
lxd/main.go
lxd/operations.go
lxd/response.go

3 more "optimizations":
- Make all methods in lxd/* private.
- Move a db query.
- Use container.Storage(Start|Stop)() instead of c.Storage.Container(Start|Stop)() in containers.go - This way we can extend container.Storage(Start|Stop)() if we want.

Optimizations

---

lxd/storage_btrfs.go

Also fixes:
- Always create the parent directory of the container in ContainerCreate.
- Copy the whole container not only the rootfs over rsync.
Signed-off-by: René Jochum <rene@jochums.at>

Create a BTRFS Container on copy, fixes #967.

---

client.go
lxc/copy.go
po/lxd.pot
shared/server.go

Support copies from local (unix socket) to remote (https)

---

lxc/copy.go
lxd/container.go
lxd/db.go
lxd/db_containers.go
lxd/db_update.go
test/migration.sh

Rename volatile.baseImage to volatile.base_image

---

lxd/container_post.go
lxd/migration/migrate.go
lxd/migration/migrate.pb.go
lxd/migration/migrate.proto
shared/idmapset.go

Send the host uid/gid map over the migration socket

---

lxd/container.go
shared/util.go

See issue: #996 
Signed-off-by: René Jochum <rene@jochums.at>

Allow the per container config to overwrite profile(s), fixes #996.

---

client.go
lxd/container.go
lxd/container_exec.go
lxd/containers_post.go
lxd/daemon.go
lxd/db.go
lxd/db_update.go
lxd/devlxd.go
lxd/images.go
lxd/migration/migrate.go
lxd/operations.go
lxd/storage.go
lxd/storage_lvm.go
shared/network.go
shared/operation.go

- Update all strings to start with a capital
- Update all strings not to end with a dot
- Re-order daemon startup a bit to always end with binding TCP
- Clarify some errors

Improve logging

---

lxd/container.go

Let's not try to start a container twice

---

Makefile
lxd/container.go
lxd/container_test.go
lxd/containers.go
lxd/daemon.go
lxd/daemon_test.go
lxd/db.go
lxd/db_test.go
lxd/db_update.go
lxd/main_test.go
lxd/storage.go
lxd/storage_btrfs.go
lxd/storage_dir.go
lxd/storage_lvm.go
lxd/storage_test.go

Signed-off-by: René Jochum <rene@jochums.at>

Add basic unit tests for a lxdContainer.

---

scripts/lxd-images

Sort the list of cloud images to download the latest version when
a version is not specified.
Signed-off-by: Robert C Jennings <robert.jennings@canonical.com>

lxd-images: Download the latest cloud image, fixes #1006

---

lxd/container.go
lxd/containers.go

Fix spelling error

---

test/lvm.sh

Avoid duplication in LVM tests

---

lxc/file.go
lxd/container.go
lxd/container_file.go
lxd/db_containers.go

Allow changing idmap of an existing container

---

lxd/profiles.go

If we don't tell people why this screwed up, it's impossible to figure out why.

actually report DB error

---

lxc/main.go
po/lxd.pot

Fix error message

---

Makefile
shared/util_linux.go

Reduce confusion about build failures

---

lxd/mntnsexec.go

let's fix some more build warnings

---

lxc/image.go

image.go: Improve help about aliases and remotes

---

CONTRIBUTING.md

CONTRIBUTING.md: mention git commit -s shortcut

---

README.md
lxc/main.go
po/de.po
po/fr.po
po/ja.po
po/lxd.pot
scripts/lxd-images

Time to deprecate "lxd images import lxc"

---

lxd/api10.go
lxd/db_update.go
lxd/storage.go
lxd/storage_btrfs.go
lxd/storage_dir.go
shared/server.go

Cleanup storage information

---

lxc/file.go
po/lxd.pot

Signed-off-by: benaryorg <binary@benary.org>

first version of lxc file edit (fixes #1055)

---

test/remote.sh

tests: Fix race condition

---

specs/rest-api.md

Signed-off-by: jensg-st <jens.gerke@sisa-tech.com>

update error message in docu closes #1060

---

lxd/container.go

Fix image creation of privileged containers

---

lxd/apparmor.go
lxd/container.go
lxd/main.go
test/basic.sh

implement per-container apparmor profiles

---

lxd/daemon.go

Without this change, any socket-activated unix socket will be removed,
preventing any later request from spawning lxd.
https://groups.google.com/forum/#!topic/golang-nuts/UtBR4IfgaEw
https://github.com/coreos/go-systemd/issues/71

Fix socket-activation on exit

---

.travis.yml
config.go
lxc/help.go
lxc/main.go
po/lxd.pot

Add --force-local flag to lxc and document others + fix and tweak travis a bit

---

lxd/storage_lvm.go

LVM takes care of this for us - it sends a device mapper 'suspend'
message to the origin thin volume before taking the (block-level)
snapshot. This ends up calling freeze_super and freeze_fs, which
quiesces the filesystem and allows for a consistent snapshot.
freeze_fs is supported on ext3/4 and btrfs, and others.

Do not freeze containers when taking LVM Snapshots

---

test/signoff.sh
test/static_analysis.sh

tests: Fix running the testsuite outside of git

---

specs/storage-backends.md

Update LVM info in specs

---

lxc/file.go
lxc/profile.go
lxd/apparmor.go
lxd/container.go
lxd/migration/migrate.go

The usual set of bugfixes right after I prepare a length demo :)

container.camp fixes

---

lxc/list.go
test/basic.sh
test/concurrent.sh
test/exec.sh
test/lvm.sh
test/migration.sh
test/remote.sh
test/snapshots.sh

list: Restore uppercase status

---

shared/util.go
shared/util_linux.go

Move unused ReadLastNLines into util_linux.go (#825)

---

lxd/container.go

Fix container rename when snapshots exist

---

lxd/api10.go
lxd/daemon.go
lxd/storage.go
lxd/storage_btrfs.go
lxd/storage_lvm.go
lxd/storage_zfs.go
specs/configuration.md
specs/storage-backends.md

Initial ZFS support

---

specs/configuration.md

add security.nesting to specs/configuration.md

---

shared/util.go

Make LXD buildable on 32bit arches again

---

lxd/container.go
lxd/main.go

And store whether we're in a userns in a new variable.

don't do aa if in userns

---

lxd/main.go

bail if lxd_dir is too long for our unix sockets

---

lxc/delete.go
lxd/container_exec.go
lxd/daemon.go
shared/util_test.go
test/main.sh
test/suites/basic.sh
test/suites/fdleak.sh
test/suites/image.sh
test/suites/lvm.sh
test/suites/migration.sh
test/suites/remote.sh

Fix the testsuite

---

lxd/apparmor.go
lxd/container.go
lxd/daemon.go
lxd/images.go
lxd/main.go
shared/idmapset.go

Improve some early start code

---

lxc/action.go
po/lxd.pot

give a better error message for `lxd forkstart`

---

lxd/container_exec.go

Block until the websocket mirror is done

---

lxd/daemon.go

and set aaEnabled = false if we don't have it
Closes #1180

check for cap_mac_admin

---

client.go
lxc/action.go
lxc/image.go
lxc/list.go
lxc/main.go
lxd/container.go
lxd/container_exec.go
po/lxd.pot

And also fix some problems with handling of frozen containers.

Implement "pause" command in the client

---

lxd/daemon.go

The symptom of this bug was that if you try to set the https port twice,
you get:
$ lxc config set core.https_address 0.0.0.0:8443
error: cannot listen on https socket: listen tcp 0.0.0.0:8443: bind: address already in use
We can't just use ip.Addr.String here, since we stick 0.0.0.0 in as [::] in
the db some cases. Instead, let's use a more intelligent comparison
mechanism.
Further, there seems to be a small issue with the intelligent comparison
mechanism in the stdlib, so let's agument that.

compare IPs more intelligently

---

lxd/container.go
lxd/daemon_images.go
shared/container.go

As usual, I noticed a couple of small problems when preparing the demo for my talk, here are the fixes.

LinuxCon talk fixes

---

lxd/container_delete.go
test/suites/basic.sh

I have no idea if this works because the network is so bad here I can't run the test suite. But if it doesn't work, I'll fix it tomorrow :)

refuse to delete containers when running

---

lxd/container_put.go

better error for `lxc restore`

---

lxc/image.go
po/lxd.pot
specs/command-line-user-experience.md

Rename copy-alias to copy-aliases in help and spec

---

lxd/container.go
lxd/devices.go
lxd/devices_test.go
shared/devices.go
shared/idmapset_linux.go
specs/configuration.md
test/main.sh
test/suites/config.sh

This set implements unix-char and unix-block devices, as well as disk devices backed by block devices.

Blockmount

---

lxd/container_snapshot.go
lxd/containers_get.go

Fix snapshot name handling

---

lxd/devlxd.go

don't pass lock by value

---

README.md

add some dependencies for tests to the readme

---

lxc/exec.go

Fix non-interactive mode detection

---

shared/log.go
shared/log_linux.go
shared/log_posix.go
shared/log_windows.go

Another incremental fix for #825. Is there a better way to do this?

Do not try to use syslog on Windows

---

lxd/container_snapshot.go

get rid of some snapshot copypasta

---

lxd/storage_lvm.go

Ensure LV is mounted before applying 'create' template

---

lxc/config.go
lxc/exec.go
lxc/exec_windows.go
lxc/file.go
lxc/image.go
lxc/profile.go

This is the last commit necessary to properly close #825.

Convert syscall.Stdin to int explicitly for Windows

---

lxc/launch.go

launch: show --config in help text

---

lxd/container.go

Fixes from first few days of try-it in production

---

lxd/operations.go
shared/operation.go

Implement recursion for operations

---

README.md

add instructions for bind mounting $HOME to FAQ

---

lxd/migrate.go

In the case of migration, you get the following when you don't have CRIU
installed:
error: Error transferring container data: checkpoint failed:
Problem accessing CRIU log: open /tmp/lxd_migration_899480871/dump.log: no such file or directory
Which, while correct, is ugly. Let's give people a better error.

better error message when CRIU is missing

---

lxd/containers.go

fix race condition in start

---

scripts/lxd-images

don't merge yet, I'll add a real discussion of the issue when I write up a
patch to the busybox ML. for now, hopefully this will test that it actually
works in jenkins.

fix busybox image

---

scripts/lxd-setup-lvm-storage

Signed-off-by: Mike McCracken <mike.mccracken@canonical.com>

lvm setup: Add check and note about thinp tools

---

scripts/lxd-setup-lvm-storage

losetup on trusty doesn't have the --list arg

Make lvm-setup script work on trusty again

---

client.go

Ensure all websockets get closed after Exec

---

test/main.sh
test/suites/config.sh

tests: Hide some more error messages

---

lxc/main.go
lxd/daemon.go
lxd/db_test.go
lxd/main.go
shared/log.go

This forwards every log message to the events API

Implement basic logging forwarder

---

lxc/info.go
lxd/container.go
po/lxd.pot
shared/container.go

Add per container processcount

---

lxd/container.go

Signed-off-by: Jeroen Simonetti <jeroen@simonetti.nl>

Fix processcount when a process terminates during loop

---

lxc/action.go
lxc/config.go
lxc/restore.go
po/lxd.pot

This is alohasteveb's branch with a make i18n on top so it passes testing.
Closes #1312

alohasteveb's fix with i18n on top

---

README.md

Update README for new Jenkins URL

---

lxd/container.go

In an optimization of moving things out of init(), we forgot that migration
needs these devices configured as well.

c/r: remember to populate devices/shmounts on restore

---

lxd/containers_post.go
lxd/daemon_images.go
lxd/images.go

Implement download progress reporting

---

README.md

Add how to setup LXD access to FAQ (fixes #1281)

---

client.go
lxc/image.go
lxd/containers_post.go
lxd/daemon_images.go
lxd/images.go
po/lxd.pot
specs/rest-api.md

Implement image import from URL

---

lxc/launch.go
lxd/daemon_images.go

Also tell about --show-log on launch failure

---

lxd/storage_32bit.go
lxd/storage_64bit.go

Signed-off-by: Dimitri John Ledkov <xnox@ubuntu.com>

lxd/storage_*bit.go add build tags for s390(x)

---

lxc/config.go
lxd/container_file.go
lxd/container_lxc.go
lxd/daemon.go
lxd/storage_zfs.go

Expand args[0] and use common result everywhere

---

test/suites/config.sh

tests: Avoid device conflicts

---

lxd/daemon.go

1. fix the calculation of the expiry date in sql
2. run the image expiry function at start of lxd too, don't wait
until after the expiry time has passed for first run.
Closes #1366

images: fix expiry logic

---

scripts/lxd-images
shared/architectures.go
specs/architectures.md

Add proper s390x support

---

specs/rest-api.md

specs: Fix layout

---

lxd/container_lxc.go

Live-apply memory limits

---

lxd/container_lxc.go
lxd/db_containers.go
lxd/devices.go
specs/configuration.md

This implements limits.cpu.priority and limits.cpu.allowance.

Implement the rest of CPU limits

---

lxd/container_lxc.go
lxd/storage.go
lxd/storage_btrfs.go
lxd/storage_dir.go
lxd/storage_lvm.go
lxd/storage_test.go
lxd/storage_zfs.go
specs/storage-backends.md

zfs: Prevent restoring from old (not latest) snapshosts

---

lxd/container_lxc.go
lxd/daemon.go
lxd/mntnsexec.go
lxd/storage_zfs.go
shared/util.go
test/backends/btrfs.sh
test/backends/dir.sh
test/backends/zfs.sh
test/main.sh
test/suites/basic.sh
test/suites/config.sh
test/suites/static_analysis.sh

Fix various test-related bugs and add btrfs testing

---

lxd/daemon.go

Signed-off-by: Jeroen Simonetti <jeroen@simonetti.nl>

Tiny logic fix for cgroup message

---

lxd/apparmor.go
lxd/container.go
lxd/container_lxc.go
lxd/daemon.go
lxd/devlxd.go
lxd/devlxd_test.go
lxd/storage_lvm.go
test/main.sh

lvm: Workaround failure on older LVM versions

---

lxd/devices.go

Use a more reliable default CPU map

---

lxd/storage_zfs.go

Let's try to unmount the zfs volume in two cases: 1. when it is a
mountpoint (so we know for sure it is mounted), or 2. when zfs thinks it is
mounted (via 'zfs mount'). Presumably zfs will not refuse to recv something
if `zfs mount` says it's unmounted, but who really knows.
i.e. I'm not sure if this will actually fix the race, but I hope so :)

zfs: hopefully fix some more races

---

lxd/container.go
lxd/container_lxc.go

Signed-off-by: Boris Kuschel <kuschel@ca.ibm.com>

Add ability to add VIF name (veth.pair) using host_name #1444 (second try)

---

.travis.yml
Makefile
lxd/container_lxc.go
test/suites/static_analysis.sh

remove unused functions

---

shared/network.go

Closes #1469
Signed-off-by: Jeroen Simonetti <jeroen@simonetti.nl>

Add a 10 second dial timeout to RFC3493Dialer

---

lxc/restore.go
lxc/snapshot.go
po/lxd.pot
test/suites/static_analysis.sh

update the lxc {snapshot|restore} docs

---

lxd/daemon.go
test/suites/basic.sh

I've wanted to do this for a long time, but couldn't figure out how. Paul
knows how :)
Reported-by: Paul Hummer

support /1.0/ _and_ /1.0

---

specs/rest-api.md

add path=... arg to container file post

---

client.go
lxc/config.go
lxd/api_1.0.go
lxd/images.go
lxd/storage_zfs.go
po/lxd.pot
test/suites/basic.sh

Make it possible to unset the zfs pool

---

lxd/daemon.go
specs/rest-api.md
test/README.md
test/main.sh

tests: Make it possible to extract all the log files

---

lxd/container_lxc.go
specs/configuration.md

Fix automatically adding veth interface to the host bridge

---

lxd/devices.go

Fix parsing /proc/self/mountinfo when rshared

---

lxd/container.go
lxd/container_lxc.go
lxd/daemon.go
lxd/devices.go
shared/devices.go
specs/configuration.md

Add network limits

---

lxd/main.go

fix comment

---

lxc/file.go
po/lxd.pot
specs/command-line-user-experience.md

Update specs and documentation on file pull/push

---

client.go
lxc/image.go
po/lxd.pot

Example:
[root@lxc-dev ~]# lxc image copy images:centos/6/i386 local: --alias c6
Image copied succesfully!
[root@lxc-dev ~]#
Fixes #1530
Signed-off-by: Nehal J Wani <nehaljw.kkd1@gmail.com>

Print message on sucessfull copy of image

---

lxc/image.go
po/lxd.pot

Signed-off-by: Nehal J Wani <nehaljw.kkd1@gmail.com>

Fix small typo s/sucessfully/successfully

---

lxd/containers.go

This pull request is for iterative testing only, please don't merge.

Improve forkstart debugging

---

client.go
lxd/container_lxc.go
lxd/mntnsexec.go
specs/configuration.md

Use a tempfile for image uploads

---

lxc/file.go
po/lxd.pot

Fixes #1472
Signed-off-by: Nehal J Wani <nehaljw.kkd1@gmail.com>

lxc file push: preserve file permissions if not specified

---

README.md

add newgrp note to readme

---

lxc/profile.go
po/lxd.pot

only print profile applied message on success

---

lxc/restore.go
po/lxd.pot

This one line of help text stands out as *really* wordy :-)

reduce verbiage to fit help text more efficiently

---

lxc/info.go
po/lxd.pot

Name: foo
Status: Running
Type: persistent
Profiles: default
Init: 30777
Processcount: 14
Ips:
eth0: IPV4  10.0.3.143  vethE44BHB
lo: IPV4  127.0.0.1
lo: IPV6  ::1
Closes #1583

lxc info: add profiles

---

lxc/main.go
lxc/main_test.go
po/lxd.pot

cli: allow recursive aliases

---

shared/network.go

Make sure we always use the right dialer and proxy

---

lxd/container_lxc.go

Allow acces to /dev/zero

---

lxd/apparmor.go

allow cgroupfs mounting on cgns kernels

---

client.go
lxc/info.go
lxc/list.go
lxd/container_lxc.go
lxd/main.go
lxd/nsexec.go
lxd/storage.go
lxd/storage_btrfs.go
lxd/storage_dir.go
lxd/storage_lvm.go
lxd/storage_test.go
lxd/storage_zfs.go
po/lxd.pot
shared/container.go
specs/rest-api.md
test/suites/basic.sh

Rework container state

---

client.go
lxc/finger.go
shared/network.go
test/main.sh

This is a bugfix version of @tych0's rebase of @jameinel's branch.
Closes #1633 
Closes #1643

LXD client API tweaks

---

lxd/container_lxc.go

This is absolutely unsupported (just like anything through raw.lxc) but
when restricted to only numbered interface and only those two keys, this
shouldn't conflict with LXD's one network handling.
Note that finding the right interface index is left to the user to
figure out, LXD doesn't in any way guarantee LXC configuration ordering
to be consistent across restarts.
Closes #1259

Allow setting lxc.network.X.ipv{4,6}[.gateway]

---

lxd/container_lxc.go

Update lxc.mount.auto based on situation

---

lxc/list.go
lxd/main.go
shared/container.go
specs/rest-api.md

Export and use the address scope

---

lxd/migrate.go

We were panic()ing sometimes (see below) on current writes. Let's not do
that.
panic: concurrent write to websocket connection
goroutine 429 [running]:
github.com/gorilla/websocket.(*Conn).flushFrame(0x504d5a70, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
/lxd/build/tmp.39Rjv1YQMz/go/src/github.com/gorilla/websocket/conn.go:450 +0x516
github.com/gorilla/websocket.(*Conn).NextWriter(0x504d5a70, 0x8, 0x0, 0x0, 0x0, 0x0)
/lxd/build/tmp.39Rjv1YQMz/go/src/github.com/gorilla/websocket/conn.go:378 +0x7c
github.com/gorilla/websocket.(*Conn).WriteMessage(0x504d5a70, 0x8, 0x509ac9e0, 0x2, 0x2, 0x0, 0x0)
/lxd/build/tmp.39Rjv1YQMz/go/src/github.com/gorilla/websocket/conn.go:585 +0x37
main.(*migrationFields).disconnect(0x505755c0)
/lxd/build/tmp.39Rjv1YQMz/go/src/github.com/lxc/lxd/lxd/migrate.go:93 +0x1ba …

websocket: fix panic() on concurrent writes

---

lxc/copy.go
lxc/list.go
lxc/remote.go

Signed-off-by: Rene Jochum <rene@jochums.at>

Go tool vet lxc/*.

---

lxd/db_images.go
shared/image.go
specs/rest-api.md

Export image last use and cache state

---

README.md
lxd/db.go
lxd/db_profiles.go
lxd/db_test.go
lxd/db_update.go

so that you can easily launch a container in which you can run docker.
Thanks stgraber for the idea.

implement a docker profile

---

lxd/db_update.go

Use sql to update db for docker profile

---

lxd/events.go

This should avoid the case where we attempt to read a now deleted
listener and also fix a race condition on listener deletion.

Better lock around event listeners

---

client.go
lxc/image.go
lxd/container_lxc.go
po/lxd.pot
test/suites/basic.sh

Upload progress and bugfix

---

lxc/list.go
po/lxd.pot

Rebase of issue 1685

---

.travis.yml
lxd-bridge/lxd-bridge
lxd/daemon_images.go

Fix default protocol in image download

---

lxd/main.go

Make it clear that the init arguments only apply in auto mode

---

lxd/migrate.go

The problem here is that depending on the migration type, we might delete
the container on the source host directly after the migrate returns, which
can race with defer and cause the delete to fail. Instead, let's explicitly
delete the stuff we need to before returning, so there is no race.

migration: don't defer cleanup of sending snapshots

---

lxc/config.go

devices client: only print success message when successful

---

lxc/config.go

Have "device show" print yaml

---

lxd/containers.go

Fix container shutdown to actually happen in parallel

---

lxd/container_lxc.go

Systemd is pretty picky on having something mounted there, doesn't care
much whether it's optional or not though :)

Bind-mount mqueue if unprivileged

---

README.md

update documentation on using docker in containers

---

lxd/main.go

Some usability changes for lxd init.

2016 03 22/lxdinit

---

README.md

README: document composing docker and default profiles.

---

lxd-bridge/lxd-bridge

lxd-bridge: Make shellcheck happy

---

lxc/config.go
lxc/profile.go
po/lxd.pot
test/suites/snapshots.sh

And fix output of existing config get to be vaguely parsable.

Implement "lxc config device get"

---

lxd/containers_get.go

List broken containers (with state set to ERROR)

---

lxc/info.go
po/lxd.pot
shared/util.go

Add resource reporting to lxc info

---

config/bash/lxd-client

Signed-off-by: Yura Pakhuchiy <pakhuchiy@gmail.com>

Improve bash completions

---

client.go

Fix initial exec size

---

lxc/info.go

Fix wrong packets sent value

---

lxc/image.go
po/lxd.pot
test/suites/basic.sh

* similar to lxc image filter
* resolves #1798

add filtering of lxc aliases

---

po/de.po
po/fr.po
po/ja.po

Update Japanese messages 

---

lxd-bridge/lxd-bridge
lxd/container_lxc.go

Set lxc.rootfs.bdev

---

test/lxd-benchmark/main.go

This makes it possible to measure scalability with limited
container-generated load.

benchmark: Allow instantly freezing containers

---

lxd/api_1.0.go

Mark 1.0 API stable

---

doc/image-handling.md

specs: Images are auto-updated every 6 hours

---

lxd/main.go

Have ActiveIfNeeded trigger if we have running containers

---

lxd/devices.go

Say you have 8 cpus, and two are offline.  If we try to dereference
usage[7] it will fail, because the array only has entires 0-6.
Turn usage into a map which supports holes, then use an array of
the entries to sort when rebalancing.

cpu rebalance: support holes in @usage

---

Makefile
lxd/images.go

Fix most other compression algorithms

---

lxc/info.go
lxc/version.go
po/lxd.pot

Tweak help messages

---

lxc/list.go
lxc/list_test.go

Filter on expanded config rather than local config

---

lxc/list.go
po/lxd.pot
test/suites/basic.sh

Output detailed container, state and snapshot info in JSON format.
Fixes #1789.

Add json format option.

---

lxc/info.go

Show the snapshot name instead of the path

---

lxc/action.go

Fix "lxc start" and "lxc stop" options.

---

README.md

Signed-off-by: Daniel Middleton <d@monokal.io>

Add basic REST API usage example to README.md

---

doc/configuration.md
lxc/init.go
lxc/launch.go
lxc/list.go
lxc/main.go
lxc/profile.go
lxd/container_lxc.go
lxd/daemon.go
lxd/events.go
lxd/images.go
lxd/operations.go
lxd/response.go
lxd/storage_btrfs.go
lxd/storage_lvm.go
lxd/storage_zfs.go
po/lxd.pot
scripts/lxc-to-lxd

Note that pylxd is currently a bit broken on python3, I sent a branch to fix this too.
Closes #1901

Once bored on a plane

---

po/de.po
po/fr.po
po/ja.po

i18n: Update Japanese translation and other po files

---

lxd/api_1.0.go
lxd/certificates.go
lxd/containers_post.go
lxd/daemon.go
lxd/daemon_config.go
lxd/daemon_test.go
lxd/db_images.go
lxd/db_test.go
lxd/db_update.go
lxd/images.go
lxd/main.go
lxd/storage_lvm.go
lxd/storage_zfs.go

Properly validate the server configuration keys

---

doc/rest-api.md

Signed-off-by: Hiroki Kiyohara <hirokiky@gmail.com>

Fixed Markdown Syntaxt

---

po/ja.po

Improve messages in the Japanese translation

---

lxd/storage_zfs.go

Fix ZFS refcounting issues

---

README.md

Signed-off-by: Daniel Middleton d@monokal.io

Add Unix socket example to REST API usage.

---

config.go

add a `shell` alias by default

---

lxd/storage_zfs.go

zfs: Mount if not mounted

---

lxd/container_file.go
lxd/container_lxc.go
lxd/nsexec.go
test/suites/filemanip.sh

GET of a nonexistent file 404s

---

lxd/db_update.go

don't try to chmod zfs.img when testing db upgrades

---

shared/util.go
shared/util_test.go

Run gofmt on shared/util_test.go to resolve a test failure.
Fixes #2072

Check for zero byte send in ReaderToChannel

---

lxc/main.go

Check all alias args to support subcommand aliases

---

lxd/storage_lvm.go

lvm: Don't call lvextend on new LVM

---

lxc/action.go

show remote in the --show-log example provided on error

---

lxd/container.go
lxd/container_lxc.go
lxd/migrate.go

cherry picks of a few commits from master

Stable 2.0/simplify migration code

---

doc/api_extensions.md
doc/rest-api.md
lxc/config.go
lxd/api_1.0.go
lxd/certificates.go
lxd/container.go
lxd/container_get.go
lxd/container_lxc.go
lxd/container_put.go
lxd/container_snapshot.go
lxd/container_test.go
lxd/containers_get.go
lxd/containers_post.go
lxd/daemon.go
lxd/images.go
lxd/profiles.go
lxd/response.go
lxd/util.go
po/lxd.pot
shared/network.go

Implement ETag support

---

doc/api_extensions.md
doc/rest-api.md
lxd/api_1.0.go
lxd/certificates.go
lxd/container_patch.go
lxd/containers.go
lxd/daemon.go
lxd/images.go
lxd/profiles.go

Implement the PATCH method

---

test/main.sh

lxc asks about the fingerprint more now, so let's tell it that fingerprint
is okay.

tests: fix hang

---

lxd/container_lxc.go

improve error message

---

lxc/finger.go

remove unused field from finger cmd

---

lxc/action.go
lxd-bridge/lxd-bridge-proxy/main.go
lxd/apparmor.go
lxd/container_lxc.go
lxd/container_state.go
lxd/main.go
lxd/storage_zfs.go
scripts/lxc-to-lxd

Bunch of random bits that piled up during my current trip.

Apparmor, /dev/net/tun and bugfixes

---

lxd-bridge/lxd-bridge

Enable IPV6 name resolution inside containers.

enable IPV6 name resolution

---

lxd/db_profiles.go
lxd/db_test.go

remove fuse device from docker profile

---

lxd/images.go
lxd/storage_zfs.go

Remove subvolume in zfs.ImageCreate error flow

---

lxd/container_exec.go
test/suites/basic.sh

remember the return code in the non wait-for-websocket case

---

doc/configuration.md

we supply these devices now, so let's document it

add /dev/net/tun and /dev/fuse to docs

---

lxd/devices.go

actually handle containers list error

---

lxd/main.go

Signed-off-by: Jason Travis <jasontravis@nau.edu>

Fix flag name in init error message

---

doc/configuration.md
lxd/api_1.0.go
lxd/container.go
lxd/container_lxc.go
lxd/db_devices.go
lxd/devices.go

I've tested all the cases I can think of (hotplug the actual device,
hotplug the container config, and cold container start/stop), but I'm not
really sure how to add any automated tests for this, since there's no real
way to ensure USB devices will be available.
Closes #2241

initial implementation of the "usb" device type

---

config/bash/lxd-client
doc/api_extensions.md
doc/configuration.md
lxd/api_1.0.go
lxd/daemon.go
lxd/daemon_config.go

Original issue: https://github.com/dobin/lxd-webgui/issues/5
Updated my previous PR, added
`Signed-off-by: Nikolay Koshenkov <18augst@gmail.com>`
to commit message.

Closes #2245 Added global key `core.https_allowed_credentials`

---

doc/production-setup.md

A collection of server changes in order for LXD to function correctly
when many file operations are requried
Closes #2256
Signed-off-by: Eric Jaw naisanza@gmail.com

Initial documentation for production use of LXD

---

shared/server.go

Fix API info reporting in "lxc info"

---

lxc/config.go
po/lxd.pot

fix spacing alignment in config.go's exmaples

---

lxd/container_state.go

Return an error on "restart" without force of a paused container

---

lxd/db_update.go

Make a database backup on schema updates

---

lxc/help.go

Closes #2301
Closes #2317
Signed-off-by: Carlos <cneirabustos@gmail.com>

Change lxc help to to go to stdout

---

doc/api_extensions.md
doc/production-setup.md

Some minor typo fixes, rewording of one paragraph and removal of trailing spaces for `api_extensions.md` and `production-setup.md`.
Hope you're having a great day! :)

Minor typo fixes

---

lxc/main.go

Closes #2320
Closes #2329
Signed-off-by: Carlos Neira <cneirabustos@gmail.com>

lxc: Add a "rename" alias

---

po/de.po
po/fr.po
po/ja.po

Update po files and Japanese translation

---

doc/production-setup.md

Changes I was talking about in #2342

Add txqueuelen tweak.

---

doc/api-extensions.md
doc/rest-api.md
lxc/info.go
lxd/api_1.0.go
lxd/container_lxc.go
lxd/daemon.go
po/lxd.pot
shared/container.go

lxc info: show cpu usage

---

lxd-bridge/lxd-bridge-proxy/main.go

Fix crash in lxd-bridge-proxy

---

lxd/main.go

On lxd init, ask the user whether he wants lxd to automatically refresh stale
images. Defaults to true.
Closes #2167.

lxd init: ask for images.auto_update_cached

---

lxd/container_lxc.go
shared/util_linux.go
shared/util_test.go

container_lxc: handle xattrs

---

lxc/publish.go

lxc: Don't force gzip compression

---

config/bash/lxd-client

Update bash completion for current options

---

lxd/main.go

init: Enable compression on new zfs pools

---

lxc/config.go
lxc/move.go
lxc/profile.go
lxc/remote.go
lxd/networks.go
shared/container.go

Couple of tweaks that I ended up doing while working on the network management branch.

Random bits from my network branch

---

lxd/images.go

Clarify unsquashfs limit logic

---

lxd/container_lxc.go
lxd/container_put.go
lxd/containers.go
lxd/daemon.go
lxd/daemon_config.go
lxd/daemon_images.go
lxd/db_containers.go
lxd/db_update.go
lxd/devices.go
lxd/main.go
lxd/patches.go
lxd/profiles.go
lxd/storage.go
lxd/storage_btrfs.go
lxd/storage_lvm.go
lxd/storage_zfs.go

Switch to new logging functions.

2016 09 16/logging issue 1928

---

shared/log.go

shared/log: fix LogDebug()

---

lxd/main.go

init: Change validation functions for consistency

---

lxd/networks.go

network: Move and rename isOnBridge

---

lxd/daemon_images.go

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x47fe07]
goroutine 14 [running]:
panic(0xbad660, 0xc82000e160)
/usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
main.(*Daemon).ImageDownload(0xc820086a00, 0x0, 0xc8207708a0, 0x22, 0xd075d0, 0xd, 0x0, 0x0, 0x0, 0x0, ...)
/home/stgraber/data/code/go/src/github.com/lxc/lxd/lxd/daemon_images.go:119 +0x6457
main.autoUpdateImages(0xc820086a00)
/home/stgraber/data/code/go/src/github.com/lxc/lxd/lxd/images.go:882 +0x8a4
main.(*Daemon).Ready.func2(0xc820086a00)
/home/stgraber/data/code/go/src/github.com/lxc/lxd/lxd/daemon.go:1013 +0x30
created by main.(*Daemon).Ready …
```

lxd/daemon_images: avoid null deref

---

lxd/container_lxc.go

2016 09 18/logging issue 1928

---

lxd/db.go
lxd/networks.go
shared/util.go

Variable name re-use was breaking it.

network: Fix networkIsInUse

---

lxc/file.go

make the target directory on recursive pull

---

lxc/file.go

Proper fix for #2403 - create target dir on recursive pull

---

doc/environment.md

Closes #2410
Signed-off-by: Meaglith Ma genedna@gmail.com

Fix the table style of environment.md

---

doc/rest-api.md

doc: Fix rest-api for PATCH addition

---

scripts/lxc-to-lxd

Added LXDAPI exception during container name check.
Signed-off-by: Denis Pynkin <denis_pynkin@epam.com>

Fixed container convert from LXC to LXD

---

config/bash/lxd-client

Signed-off-by: Pawel Gajda <mis@pld-linux.org>

Bash completion: containers state checking 

---

lxd/apparmor.go
lxd/container_lxc.go
lxd/daemon.go
test/suites/basic.sh

apparmor: create an apparmor namespace for each container

---

lxd/daemon.go

apparmor: Only turn on stacking for >= 1.2

---

lxd/main.go
test/main.sh

init: Various fixes

---

lxd/networks.go

allow nil network config

---

client.go
shared/util_linux.go
shared/util_unix.go
shared/util_windows.go

Add GetOwner stub for Windows (fixes #2438)

---

lxc/remote.go
lxd/daemon.go
shared/cert.go
shared/cert_test.go

Generate client certificate with proper extended usage info

---

lxd/storage_zfs.go

LXD assumes that it completely owns whatever storage.zfs_pool_name
points to, so lets make sure it's always empty. Then to avoid potential
problems with the mounts LXD will make, set mountpoint=none.

zfs: Extra checks and config for ZFS pools

---

lxd/migrate.go

migrate: don't use ActionScript if it's not available

---

config/bash/lxd-client

Added the command "shell" to lxc-client bash-completion.

Added the command shell to lxc-client bash-completion

---

config/bash/lxd-client

- Added the command network to lxc-client bash-completion
- Allow dash in parameters to lxc-client bash-completion
- Fix _lxd_profiles in lxc-client bash-completion

Lxc client bash completion

---

lxd/rsync.go

Don't mind me, I'm a barbarian.

lxd netcat: remove debugging by file creation

---

doc/configuration.md

doc: Workaround github markdown renderer

---

lxd/migrate.go

The problem here is that with the new action script method for waiting
until the restore is successful to finish the dump. The issue is that the
action script waits until the operation is done, but the operation deleted
the logs. Since the Migrate function is the one that actually collects the
logs, the logs got deleted before the Migrate function had a chance to
collect them.
Instead, let's make the goroutine that is calling Migrate responsible for
cleaning up the checkpoint directory, so that the logs are always
guaranteed to be collected. This means we have to be more explicit
elsewhere about deleting the logs in error cases, but we avoid the race.
In the legacy case, we can still just use the defer, since the Migrate
call returns immediately in the function itself.
Fixes a race …

migration: fix a race for collecting logs

---

lxd/images.go

Don't make unnecessary image copies

---

lxd/devices.go

We don't need to retrieve busnum and devnum to construct the path for the usb
device. The DEVNAME entry of the netlink kobject will tell us the path, e.g.:
DEVNAME: bus/usb/003/013
This should simplify the code a little bit. Hotplug still works as confirmed on
my local machine.

lxd/devices: use DEVNAME entry of netlink for usb

---

lxc/copy.go
lxd/migrate.go

Fix more races

---

lxd/container_lxc.go
lxd/main.go
lxd/storage_zfs.go
lxd/util.go

Only load kernel modules if not loaded

---

lxd/devices.go

In case netlink does not give us the cheap way of retrieving the usb device path
let's fallback to using the busnum and devnum as before. In other news, I'm less
optimistic about netlink infos then before. :)

lxd/devices: be less optimistic about netlink info

---

lxc/exec.go
lxc/exec_unix.go
lxc/exec_windows.go

set term to "dumb" on windows

---

.appveyor.yml

Add appveyor config to git

---

.appveyor.yml
README.md

Provide daily Windows binaries for client with AppVeyor

---

lxd/container_lxc.go

lxd/container_lxc: report correct dev type in log

---

lxd/container_state.go

Don't destroy ephemeral container on restart

---

lxc/file.go
lxc/file_unix.go
lxc/file_windows.go

Prepending / on windows seems like a bad idea ;)
Closes #2565

only normalize paths on linux

---

lxc/publish.go
lxd/container.go
lxd/container_lxc.go
lxd/images.go

lxd: save properties on publish

---

scripts/lxc-to-lxd

lxc-to-lxd: Check that source path exists (disk)

---

doc/configuration.md

This was recently introduced in the cloud images.

Document user.network-config

---

lxd/networks.go

network: Spawn dnsmasq on FAN bridges

---

doc/debugging.md

Some wisdom from https://github.com/lxc/lxd/issues/2561#issuecomment-256372524

doc/debugging.md: Add hacking guide

---

doc/configuration.md

doc/configuration: add missing pci options for gpu

---

lxd/container_lxc.go

devices: call deviceGetAttributes() when needed

---

lxd/daemon.go

Don't update images at all if interval is 0

---

lxd/container_lxc.go

actually surface the last used update error

---

README.md

Signed-off-by: Akshay Karle <akshay.a.karle@gmail.com>

update README to specify docker installation details

---

lxd/storage_dir.go

This tries to ensure that dir backed containers are in a consistent state when
snapshotted.
In my testing this didn't interfere with `--stateful` since there is a comment in `containers_post.go` warning about freezing the container before migrating it. It should be fine because we're freezing after migrating. @tych0, does this make sense? :)
Closes #2601.

lxd/storage_dir: rsync + freeze + rsync unfreeze

---

lxc/delete.go
lxc/finger.go
lxc/restore.go
po/lxd.pot

This address the minor issues raised in https://github.com/lxc/lxd/issues/2627.
I've updated the relevant source file and then ran `$ make update-pot`. Frankly I'm not sure that is it. I feel the other three `*.po` need some love too.

Improve help texts

---

client.go
lxc/copy.go
lxd/containers_post.go

Make container copy more robust

---

lxd-bridge/lxd-bridge

Makes firewall filter rule insertion optional. Add ip6tables filter rules while at it.
Closes #2647

Optional firewall

---

lxd/container_file.go

Cleanup leftover temp file

---

lxd/container_lxc.go
lxd/db_containers.go

Avoid race condition in network fill function

---

test/main.sh
test/suites/concurrent.sh
test/suites/exec.sh
test/suites/fuidshift.sh

tests: Simplify testsuite spawn code

---

lxd/daemon_config.go
lxd/storage_zfs.go

Properly validate daemon keys on unset

---

doc/api-extensions.md
doc/configuration.md
lxd/api_1.0.go
lxd/networks.go
lxd/networks_config.go

network: Allow adding static routes to a bridge

---

lxd/container_lxc.go

Fix device hotplug with major/minor set

---

lxd/container_lxc.go
test/suites/config.sh

In particular, if there are two paths to be mounted:
/mnt
/mnt/foo
We should always mount /mnt before we mount /mnt/foo, otherwise, the /mnt
mount will overmount /mnt/foo, which is almost certainly not what people
want.
Closes #2717

do mounts in the right order

---

client.go
lxc/remote.go
lxd/certificates.go
lxd/daemon.go
shared/cert.go
shared/log.go
test/main.sh

Here's some random patches that add or abstract bits that we'll need for clustering.

Some patches in prep for clustering

---

po/fr.po

Avec respect des conventions typographiques
Signed-off-by: Olivier Le Monnier <olm@unicaen.fr>

Traduction intégrale (et cohérente) en français

---

po/de.po
po/fr.po
po/ja.po

Update PO templates

---

lxd/daemon.go

use our custom http server when updating HTTPS address too

---

lxc/image.go
lxc/info.go
lxd/daemon_images.go
lxd/storage.go
shared/util.go

util: GetByteSizeString() take precision argument

---

po/fr.po

- Use of french verbs indiquer/spécifier
- Limit use of conjugation, prefer infintive
- Tested in CLI
Signed-off-by: Olivier Le Monnier <olm@unicaen.fr>

Improved and completed french translation

---

client.go
lxc/init.go
lxc/monitor.go
lxd/main_shutdown.go

Otherwise there is no way to close these connections.

add a done signal to Monitor API

---

lxd/response.go

allow passing in-memory buffers to a FileResponse

---

shared/api/certificate.go
shared/api/container.go
shared/api/image.go
shared/api/network.go
shared/api/profile.go
shared/api/response.go
shared/api/server.go

Fix yaml rendering of composite structs

---

lxc/network.go

lxc/network: sort UsedBy []string slice on show

---

lxd/main_init.go

Not just the subnet. So 10.1.2.1/24 instead of 10.1.2.0/24.
Update the question to make it a bit clearer.

init: We need an address and subnet

---

lxd/container_exec.go
lxd/main_forkexec.go
test/suites/basic.sh
test/suites/config.sh

This makes exec behave even more similar to ssh.

exec: report -1 (255) on signal exit

---

lxd/daemon.go
lxd/daemon_images.go
lxd/main_activateifneeded.go
lxd/main_test.go

Close race condition in image download

---

lxd/devices.go

zfs: Simplify device tracking logic

---

lxd/container_lxc.go

Don't block resolution on non-existing paths

---

shared/util.go

shared: FileCopy should keep the same mode

---

lxd/main_init.go

The 'storageBackend' has already been checked.
Signed-off-by:sungengze

The 'storageBackend' has already been checked.

---

lxd/containers_post.go

The condition of 'req.Source.Fingerprint != ""' has already been deal.
Signed-off-by:sungengze

This condition has already been deal.

---

lxd/images.go
lxd/patches.go
lxd/storage_pools.go
lxd/storage_zfs.go

storage pools: bugfixes

---

lxd/api_internal.go
lxd/storage_volumes.go
lxd/storage_volumes_utils.go
lxd/storage_zfs.go

storage: bugfixes

---

test/main.sh

tests: The monitor can exit on its own

---

lxc/storage.go
po/lxd.pot

storage: Sort volume list by type and name

---

lxd/storage_btrfs.go

btrfs: Enable quotas on the pools we create

---

lxd/patches.go
lxd/storage_dir.go

dir: delete image from database

---

test/suites/storage.sh

tests: Always use 10Mib volumes for LVM

---

doc/storage-backends.md

doc: add client tool illustration for storage api

---

lxd/patches.go

When we upgrade from an existing dataset we must make sure that we refer to the
right entity in the right places:
- When we want to talk about the pool in the db, we need to use "poolName" which
will always hold the correct name for the db entry.
- When we want to talk about the pool on-disk, we need to use "defaultPoolName"
which will always hold the correct on-disk name of the zfs pool.
The good news is that users who are ran this upgrade on an existing dataset will
have not moved any further then the pool-in-db creation step. So simply
re-running the upgrade or replacing their db with the old backed-up one and rerunning the upgrade should
fix all issues since no on-disk information has been touched yet.

patches: fix zfs upgrade from existing dataset

---

lxd/patches.go
lxd/storage_lvm.go
lxd/storage_pools_config.go

Activating the volume group will activate all logical volumes as well.

storage: activate volume group

---

lxd/container_exec.go

exec: kill forkexec on abnormal websocket closure

---

doc/api-extensions.md
lxd/api_1.0.go
lxd/storage.go
lxd/storage_btrfs.go
lxd/storage_dir.go
lxd/storage_lvm.go
lxd/storage_mock.go
lxd/storage_pools_utils.go
lxd/storage_zfs.go
test/suites/storage.sh

storage: improvements + implement lvm volume group renaming.

---

lxd/main_init.go
lxd/storage_lvm.go
lxd/storage_shared.go
lxd/storage_volumes_config.go

lxd init: allow rerunning

---

lxd/storage_cgo.go

Improves the the logic a little and might come in handy once I figured out how to use loop-file backed lvm pools.

storage_cgo: detect if loop file is already in use

---

lxd/storage_cgo.go
lxd/storage_lvm.go
lxd/storage_pools_config.go
test/backends/lvm.sh
test/suites/storage.sh

Closes https://github.com/lxc/lxd/issues/2983.
Addresses https://github.com/lxc/lxd/issues/2866.

lvm: allow loop-backed storage pools

---

lxd/container.go
lxd/containers_post.go

Fix base image tracking

---

lxd/containers_post.go
lxd/daemon.go
lxd/images.go
lxd/patches.go
lxd/storage.go
lxd/storage_cgo.go
lxd/storage_lvm.go
lxd/storage_pools.go
lxd/storage_pools_utils.go
lxd/storage_zfs.go

zfs: import loop-backed storage pools + bugfixes

---

lxd/storage_lvm.go

lvm: fix defer calls

---

doc/api-extensions.md
doc/configuration.md
lxd/api_1.0.go
lxd/container.go
lxd/container_lxc.go
lxd/networks_utils.go

Add "vlan" property to "macvlan" interfaces

---

lxd/container_lxc.go

Properly revert memory limits on failure

---

lxd/patches.go

patches: hardening

---

lxd/patches.go
lxd/storage_lvm.go

patches: detect logical volume size

---

lxd/container.go
lxd/container_exec.go
lxd/container_lxc.go
lxd/rsync.go

Don't use FindProcess, just pass exec.Cmd

---

test/lxd-benchmark/main.go

lxd-benchmark: Fix --help and --version handling

---

lxd/daemon_images.go

images: Record the server certificate in the cache

---

lxc/list.go
po/de.po
po/el.po
po/fr.po
po/ja.po
po/lxd.pot
po/nl.po
po/ru.po

Add a simple list formatting example for #3055

---

lxd/daemon.go
lxd/patches.go

And as usual:
[![asciicast](https://asciinema.org/a/106820.png)](https://asciinema.org/a/106820)

patches: fix upgrade when daemon got killed during migration

---

lxd/daemon.go
lxd/patches.go
lxd/storage_lvm.go

We need a way to force a check right at the end of the storage api upgrade.

storage: improvements

---

lxd/storage_zfs.go

zfs: load kernel module in case it isn't

---

doc/rest-api.md

doc: Document that X-LXD-type is valid for POST

---

lxd/daemon_config.go

Allow unsetting deprecated keys with default

---

lxd/api_internal.go
lxd/storage_zfs.go

zfs: try lazy umount if zfs umount fails

---

lxd/containers_post.go

containers_post: better error message

---

doc/api-extensions.md
doc/storage-backends.md

doc: Update storage documentation

---

lxd/container.go
lxd/container_lxc.go
lxd/profiles.go
lxd/profiles_utils.go

storage: Check that pool exists on profile changes

---

doc/configuration.md

doc: fix storage volume configuration

---

doc/api-extensions.md
doc/configuration.md
lxd/api_1.0.go
lxd/container.go
lxd/container_lxc.go
test/suites/config.sh

Feature request : #3125

---

client.go
test/suites/filemanip.sh

client: fix file push

---

lxd/apparmor.go
lxd/container_lxc.go

Enable stacking for privileged containers

---

lxd/storage_lvm.go
lxd/storage_pools_config.go
test/suites/storage.sh

storage pools: fix + improve config validation

---

doc/configuration.md
doc/storage-backends.md
lxd/api_1.0.go
lxd/storage_lvm.go
lxd/storage_pools_config.go
test/suites/migration.sh
test/suites/snapshots.sh
test/suites/storage.sh

lvm: implement non-thinpool based storage pools

---

lxd/main_forkexec.go

Replace it by syscall.Wait4() in this case. This should remove the last traces
of FindProcess.
Closes #3037.
Possibly relates to #3157.

forkexec: remove os.FindProcess

---

lxc/list.go

Document list format options

---

lxc/list.go

See https://golang.org/pkg/encoding/csv/#pkg-overview for details

Add CSV format to list output (fixes #2363)

---

lxc/list.go

Fill missing csv docs

---

lxc/copy.go
lxd/storage_lvm.go
po/de.po
po/el.po
po/fr.po
po/ja.po
po/lxd.pot
po/nl.po
po/ru.po
test/suites/storage.sh

copy: wait asynchronously

---

lxc/list.go

list: Re-add dropped sort.Sort call

---

lxd/main.go
lxd/main_init.go

lxd init: allow to create subvolume for btrfs pool

---

doc/api-extensions.md
doc/configuration.md
doc/storage-backends.md
lxd/api_1.0.go
lxd/db_update.go
lxd/migrate.go
lxd/patches.go
lxd/rsync.go
lxd/storage.go
lxd/storage_btrfs.go
lxd/storage_dir.go
lxd/storage_lvm.go
lxd/storage_migration.go
lxd/storage_pools_config.go
lxd/storage_zfs.go
test/suites/storage.sh

storage pools: implement rsync.bwlimit property

---

README.md
test/main.sh
test/suites/static_analysis.sh

Use flake8 instead of separate pep8/pyflakes for python linting

Use flake8 instead of separate pyflakes and pep8

---

lxd/main_netcat.go

rsync: handle eagain in netcat

---

lxd/api_internal.go
test/suites/backup.sh

lxd import: handle non-existing snapshots path

---

lxd/container.go
lxd/main_netcat.go
lxd/migrate.go
lxd/rsync.go
lxd/storage_migration.go
shared/util_linux.go

netcat: add new errno detection helpers, switch netcat over to them and implement netcat logging

---

lxd/patches.go
lxd/storage.go
lxd/storage_btrfs.go
lxd/storage_cgo.go
lxd/storage_dir.go
lxd/storage_lvm.go
lxd/storage_migration.go
lxd/storage_pools.go
lxd/storage_pools_config.go
lxd/storage_pools_utils.go
lxd/storage_shared.go
lxd/storage_volumes.go
lxd/storage_volumes_config.go
lxd/storage_volumes_utils.go
lxd/storage_zfs.go

storage: make golint clean

---

doc/containers.md
lxd/container_lxc.go
shared/container.go

Allow for stable host interface names

---

doc/storage.md

doc: add not about escaping btrfs qgroups

---

lxc/main.go
lxc/manpage.go

lxc: Show all commands in "man lxc"

---

lxd/container_lxc.go
lxd/container_snapshot.go
lxd/db_update.go
lxd/storage_btrfs.go
lxd/storage_dir.go
lxd/storage_lvm.go
lxd/storage_pools_utils.go
lxd/storage_zfs.go

tree-wide: use containerGetParentAndSnapshotName()

---

lxc/file.go
po/de.po
po/el.po
po/fr.po
po/ja.po
po/lxd.pot
po/nl.po
po/ru.po
po/sv.po
po/tr.po

Fix #3240 - file push broken on windows with 2.13

---

lxc/copy.go
lxc/move.go

lxc {copy,move}: improve error handling

---

lxd/storage_btrfs.go

btrfs: remove unused variable

---

lxc/copy.go

lxc copy: simplify

---

shared/logging/format.go
shared/logging/log.go

I'd like to use it in another project of mine :)

shared/logging: Export LogfmtFormat

---

doc/api-extensions.md
doc/storage.md
lxd/api_1.0.go
lxd/storage_btrfs.go
lxd/storage_pools_config.go
lxd/storage_utils.go
test/suites/storage.sh

Closes #3264.
References: https://discuss.linuxcontainers.org/t/storage-pool-default-mount-options/80

api extension: btrfs.mount_options

---

lxd/storage_cgo.go
lxd/storage_utils.go

storage utils: add MS_LAZYTIME to mount options

---

test/suites/migration.sh

test: make sure storage volume is mounted

---

lxd/db_test.go

This moves db tests to testify

Add a testify test suite for db tests, rework existing tests

---

lxd/images.go

Extract the code to update a single image from autoUpdateImages, so that the logic can be reused.

Split autoUpdateImage function

---

lxd/storage.go
lxd/storage_btrfs.go
lxd/storage_lvm.go
lxd/storage_utils.go
test/suites/storage.sh

lvm: resolve mount options properly

---

client/lxd_server.go
lxc/remote.go
lxd/api_1.0.go
lxd/db.go
lxd/db_profiles.go
lxd/db_test.go
po/lxd.pot

I have no idea what Github just did with @stgraber's branch, but whatever. Opening here again with `maki18n` on top.

bugfixes from stgraber

---

client.go

client: fix profiles list

---

README.md

See https://github.com/lxc/lxd/issues/3299

README.md update docker instructions

---

lxd/storage_btrfs.go

storage btrfs: cleanup empty migration dirs

---

test/main.sh

tests: Drop jenkins-specific check again

---

lxd/container.go
lxd/container_lxc.go
test/suites/storage.sh

ConfigKeySet() called Update() and Update called ConfiKeySet().

storage: avoid infinite loop

---

test/suites/storage.sh

test: kill and restart

---

lxd/storage_utils.go
lxd/storage_zfs.go

zfs: fix folder permissions after dataset creation

---

doc/storage.md

doc: document zfs quota vs refquota

---

doc/storage.md
lxd/storage_zfs.go
lxd/storage_zfs_utils.go

zfs: create image dataset with mountpoint=none

---

lxd/storage_lvm.go
lxd/storage_lvm_utils.go
lxd/storage_utils.go

lvm: bugfixes

---

lxd/networks.go

network: Always pass --conf-file to dnsmasq

---

lxd/patches.go

patches: make sure localdevices are updated

---

lxd/networks_utils.go

Signed-off-by: Georg Hopp <georg@steffers.org>
This is an addition to the fix of #2781 which also removes IPv6 leases on container delete.

Remove IPv6 leases on container delete

---

lxd/storage_dir.go

dir: create symlink on freeze failure

---

lxd/db_storage_pools.go
lxd/patches.go

upgrade fixes

---

lxd/migrate.go
lxd/storage_btrfs.go
lxd/storage_migration.go
lxd/storage_zfs.go
test/suites/migration.sh

fix zfs container copy

---

lxd/rsync.go

rsync: handle sparse files when rsyncing

---

lxd/storage_btrfs.go

btrfs: Apply default flags BEFORE detecting type

---

lxd/container_lxc.go
lxd/storage_zfs.go

container_lxc: fail on ebusy on start hook

---

lxd/daemon_images.go

lxd/images: Initialize image info in direct case

---

lxd/networks.go

network: Only generate DHCP fw rules if enabled

---

doc/api-extensions.md
doc/containers.md
doc/userns-idmap.md
lxc/publish.go
lxd/api_1.0.go
lxd/container_lxc.go
shared/container.go
test/suites/idmap.sh

Bugfixes and minor features

---

lxd/api_internal.go
test/suites/backup.sh

import: remove last dependency on symlink

---

lxd/container_lxc.go

Better handle errors in memory reporting

---

client/lxd_containers.go
shared/util.go
shared/util_test.go
test/suites/filemanip.sh

Fix file push/pull with names containing spaces

---

lxc/list.go
test/suites/basic.sh

Error if --columns and --fast are used together in lxc list

---

README.md

README: Seriously rework the content

---

shared/util.go

shared: Use custom error type for RunCommand

---

lxd/main_init.go

lxd/init: Detect LVM thin provisioning tools

---

test/main.sh

tests: Validate that the right busybox is present

---

doc/rest-api.md

Make easier to use rest-api for beginners
Signed-off-by: Fedor Dikarev <fedor.dikarev@gmail.com>

Fix spaces, commas, quotes, brackets where needed

---

lxc/list.go
po/de.po
po/el.po
po/fr.po
po/it.po
po/ja.po
po/lxd.pot
po/nl.po
po/ru.po
po/sr.po
po/sv.po
po/tr.po

Using 1 doesn't display privileged containers but if we use true it does.

Fix help to provide sample that actually works

---

lxd/storage_zfs.go

May help with some of the EBUSY.

zfs: Use tryMount when mounting filesystem

---

lxd/container_lxc.go

liblxc: adapt to new config keys

---

lxd/container_lxc.go

Show underlying error when container delete fails

---

README.md
doc/backup.md
doc/configuration.md
doc/preseed.md
doc/production-setup.md
doc/rest-api.md
doc/storage.md

Cleanup trailing whitespace in a few .md files

Whitespace cleanup in doc

---

README.md
doc/backup.md
doc/configuration.md
doc/preseed.md
doc/production-setup.md
doc/rest-api.md
doc/storage.md

This reverts commit b9416c1cf7a28277d151b8764422acee01b014e9.

Revert "Whitespace cleanup in doc."

---

lxd/storage_volumes.go
test/suites/storage.sh

storage: Fix ETag handling of volumes

---

lxd/storage_volumes_utils.go

storage: Fix UsedBy for containers and images

---

lxd/storage_lvm.go
lxd/storage_lvm_utils.go

lvm: fix non-thinpool container creation

---

lxd/container.go
lxd/container_lxc.go
lxd/storage.go
lxd/storage_btrfs.go
lxd/storage_dir.go
lxd/storage_lvm.go
lxd/storage_lvm_utils.go
lxd/storage_mock.go
lxd/storage_volumes_config.go
lxd/storage_volumes_utils.go
lxd/storage_zfs.go

https://lists.linuxcontainers.org/pipermail/lxc-users/2017-July/013565.html

storage API: implement generic quota support

---

lxd/storage_btrfs.go
test/suites/storage.sh

storage: add quota tests

---

doc/api-extensions.md
doc/containers.md
lxd/api_1.0.go
lxd/container_lxc.go
lxd/networks_utils.go

Signed-off-by: Vincent Catros <vincent.catros@orange.com>

vlan property added to physical nictype (issue #3375)

---

lxc/image.go

Improve "lxc image list" filter handling

---

lxc/image.go

Fix "lxc image copy" not recording the source

---

lxd/images.go

Fix image refresh when fingerprint is passed

---

lxd/storage.go
lxd/storage_volumes_utils.go

When a storage volume is attached through a profile we need to make sure that
all attachers specify the same id mapping for their next id map.
Closes #3548.

storage: check idmaps of all attaching containers

---

lxc/main.go

lxc: Respect HOME if set

---

client/interfaces.go
client/lxd_containers.go
doc/api-extensions.md
doc/rest-api.md
lxc/copy.go
lxc/move.go
lxd/api_1.0.go
lxd/container_lxc.go
lxd/container_snapshot.go
lxd/containers_post.go
po/de.po
po/el.po
po/fr.po
po/it.po
po/ja.po
po/lxd.pot
po/nl.po
po/ru.po
po/sr.po
po/sv.po
po/tr.po
po/zh.po
po/zh_Hans.po
shared/api/container_snapshot.go
test/suites/migration.sh

migration: state{ful,less} snapshot migration 

---

shared/util_linux.go

util linux: guess size when sysconf() returns -1

---

README.md
doc/storage.md
lxd/main_init.go
lxd/migrate.pb.go
lxd/migrate.proto
lxd/storage.go
lxd/storage_ceph.go
lxd/storage_ceph_migration.go
lxd/storage_ceph_migration_utils.go
lxd/storage_ceph_utils.go
lxd/storage_pools_config.go
test/README.md
test/backends/ceph.sh
test/main.sh
test/suites/init_preseed.sh
test/suites/migration.sh
test/suites/snapshots.sh
test/suites/storage.sh
test/suites/storage_driver_ceph.sh

storage: implement ceph storage driver

---

doc/image-handling.md

doc: Add note on use of previous image from cache

---

test/main.sh

test: use $storage_backends variable

---

doc/api-extensions.md
doc/storage.md
lxd/api_1.0.go
lxd/storage_ceph.go
lxd/storage_ceph_migration.go
lxd/storage_ceph_utils.go
lxd/storage_pools_config.go

ceph: add ceph.user.name

---

client/connection.go
lxc/config/remote.go

client: Simplify ConnectPublicLXD logic

---

lxd/storage_btrfs.go
lxd/storage_dir.go
lxd/storage_lvm.go

Fix wrong driver name for log output

---

lxc/image.go
test/suites/remote.sh

client: fix image copy

---

lxc/image.go

Make "lxc image copy" fast again

---

lxc/remote.go

lxc/remote: Don't require a crt for public remotes

---

scripts/lxc-to-lxd

lxc-to-lxd: Fix bad test

---

lxd/storage_pools_utils.go

storage: Count custom volumes in pool UsedBy
