canonical/lxd

lxd-agent/events.go
lxd/device/disk.go
lxd/instance/drivers/driver_common.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/drivers/driver_qemu_config_test.go
lxd/instance/drivers/driver_qemu_templates.go

- Aligns naming differences between host drive passthrough at boot time and hotplug - this allows a virtiofs share added at boot time to be hot unplugged later.
- Adds escaping and hashing to host drive device names to allow LXD disk device names to be long and contain `/` characters.
- Updates devlxd events and lxd-agent event handler to support passing `mount_tag` info so that lxd-agent doesn't assume the mount tag is the device name.
Unfortunately due to the historic setup of these devices it has been impossible to maintain complete backward compatibility with the mount tag formats. For short and simple names they remain the same, but for longer ones or ones with `/` the mount tag has changed necessarily to support that functionality.
Closes #13596

Device: Support long device names for host path passthrough to VMs

---

lxd/storage/backend_lxd.go

This should fix the alert from https://github.com/canonical/lxd/security/code-scanning/289
However I don't believe this was a genuine security issue, as although the raw input from the request was ending up at the filesystem path, it would not have been able to proceed unless the raw input matched the fingerprint of an existing image because of an earlier check for an existing image record.
However it is better practice to use the fingerprint from the DB record once it has been loaded.

Storage: Use validated image fingerprint from DB record in EnsureImage

---

.github/workflows/tests.yml

(cherry picked from commit 499912adcce3c4be65ab7cd7946d4414070e1497)

Workaround microceph rgw default enable (stable-5.0)

---

lxd/instance/drivers/load.go

As device.Validate does this too and checks for < 64 rather than <= 64 here.

Instance: Remove unnecessary check for device name length

---

client/lxd_images.go
lxd/db/images.go

Instead of introducing a breaking change by separating the image type which is only used when new image needs to be downloaded, populate the source image type when fetching an image.
Fixes #13586

Populate source image type when fetching an image

---

lxd/storage/drivers/driver_ceph_volumes.go

A PR from yesterday (https://github.com/canonical/lxd/pull/13612) has broken Ceph RBD pool backed VM migrations that use the `RBD_AND_RSYNC` migration type.
This migration type is special as the VM's block vol is transferred using the Ceph RBD export/import diff methods whilst the VM's filesystem vol is transferred via the generic methods.
In https://github.com/canonical/lxd/pull/13612 we have effectively removed the option to use the generic method as part of `RBD_AND_RSYNC` when transferring a VM's filesystem vol.
If the content type is `filesystem` and the migration type is `RBD_AND_RSYNC` the lower level `createVolumeFromMigration()` still has to trigger the generic function to receive the VM's filesystem vol.

Storage: Fix regression in Ceph RBD migration

---

lxd/storage/backend_lxd.go
lxd/storage/drivers/driver_btrfs.go
lxd/storage/drivers/driver_powerflex.go
lxd/storage/drivers/driver_powerflex_utils.go
lxd/storage/drivers/driver_powerflex_volumes.go
lxd/storage/drivers/utils.go

https://github.com/canonical/lxd/pull/13073 was meant to resolve an error that happens during the resizing of a volume. As the error wasn't anymore present I thought this has fixed it by unmapping the volume prior to the resize.
But this breaks the `lxc import ...` command as the `driver.SetVolumeQuota()` function isn't expected to unmap/map the volume which might cause the path of the device to be different after the map. This can lead to an error during the unpack operations.
Instead it looks that the actual error comes from a race if LXD doesn't wait for the volume to disappear from the system. A subsequent map operation might pick the path from the old volume that is still to be removed from the system.
For Ceph RBD this is not an issue as we call `rbd unmap` directly on the host and …

Storage: Prevent race when unmapping PowerFlex volume

---

lxd/storage/drivers/driver_dir.go
test/main.sh
test/suites/storage_driver_dir.sh

Allow `lost+found` subdirectory when storage pool's source is a root of the mounted filesystem.
Fixes #13630

storage: Allow `lost+found` subdirectory when storage pool source is root of the filesystem

---

test/lint/licenses.sh

This reverts commit f8180dec5cba69ec066e7444a65ae021a3941cbb.
It's possible now that we require Go 1.22+. Fixes #13048

Revert "test/lint: Disable licence check."

---

doc/howto/projects_confine.md
doc/howto/projects_create.md
doc/howto/projects_work.md
doc/howto/server_expose.md
doc/profiles.md

Add API instructions for working with projects.

doc/projects: Add API instructions

---

lxc/remote.go

This fixes a regression introduced in #13567.
If the client talks to an older LXD that has the `explicit_trust_token` extension, let the provided password take priority and don't ask for the token if not provided.
See the following table:
Client Version | Server Version | Command | Result
-- | -- | -- | --
6.1 | 6.1 | lxc remote add | Ask for trust token
6.1 | 6.1 | lxc remote add --password | Err: not authorized (Token field not set in request body. We cannot check if the server still supports passwords.)
6.1 | 6.1 | lxc remote add --token | Continue without any prompts
6.1 | 5.21 (with `explicit_trust_token`) | lxc remote add | Ask for admin password
6.1 | 5.21 (with `explicit_trust_token`) | lxc remote add --password | Continue without any prompt
6.1 | 5.21 (with …

lxc: Always allow specifying a password when adding remotes

---

lxd/storage/drivers/driver_powerflex_utils.go

The output format of `nvme list-subsys -o json` has changed as part of moving the LXD snap from `core22` to `core24` (See https://github.com/canonical/lxd-pkg-snap/pull/471). By using sysfs directly we are independent from future output changes.

Storage: Don't use nvme CLI to retrieve subsystems

---

test/suites/container_devices_nic_bridged_filtering.sh
test/suites/container_devices_nic_ipvlan.sh

Later versions appear to be setting up routes on container start, but leaving them behind on container stop.
LXD doesn't use liblxc's route management in later versions so this is just to get the test suite passing.

test: Flush routes on lo interface left over from liblxc ipvlan bug

---

lxd/instance/drivers/driver_lxc.go
test/suites/security.sh

Fixes `security_protection` test on kernels without shiftfs support.

Add support for LXD_IDMAPPED_MOUNTS_DISABLE env var to allow running shift protection tests

---

test/godeps.list

This is necessary for static analysis to pass.

test: Order client dependencies alphabetically.

---

client/lxd_events.go
lxd-agent/devlxd.go
lxd/api.go
lxd/cluster/migrate.go
lxd/events/devlxdEvents.go
lxd/events/events.go
lxd/instance_delete.go
lxd/instance_get.go
lxd/storage_volumes.go

This is required for static analysis to pass.
Missed this because I thought it was my IDE running goimports, but it is in fact part of the static analysis script.

*: Runs `gofmt -w -s ./`.

---

lxd/apparmor/instance_lxc.go

In core24 AppArmor includes security fixes and our ruleset, although the source code remains unchanged become stricter.
devpts was always available for unprivileged containers because of AppArmor bugs like [1]. Let's now allow it explicitly.
[1] https://bugs.launchpad.net/apparmor/+bug/1597017

Instance: Allow devpts in AppArmor profile for unprivileged containers

---

lxd/storage/drivers/driver_zfs_volumes.go

Fix the regression introduced in #13656 where only the path `/dev/zvol/<dataset>` is checked for existence. Instead, modify the approach to obtain the device path as done in the `GetVolumeDiskPath` method. This ensures that the device path is correctly identified, whether it appears as `/dev/zvol/<dataset>` or `/dev/zd*`.
The previously failing lxd-ci test suite `storage-disks-vm` is passing locally.

Storage: Check if device has appeared in /dev/zd* when activating or creating a volume

---

lxd/apparmor/instance_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/storage/drivers/driver_powerflex_utils.go
lxd/storage/drivers/driver_zfs_volumes.go

- Fixes ZFS activation regression.
- Reverts VM CPU auto pinning (due to performance regression on P+E core systems).
- Pulls in fixes for core24.

Backports (stable-5.21)

---

lxc/config/default.go
lxd-benchmark/main.go

(cherry picked from commit b365672a32e3edff0d92a39ea65b40317e230934)

Add minimal remotes (stable-4.0)

---

lxd/devices.go
lxd/instance/drivers/driver_qemu.go

Restores the previously reverted `SetAffinity` implementation for qemu driver so we can easily cherry-pick fixes from main in the future for this.
And instead adds logic to prevent auto pinning for VMs in the `deviceEventListener` which also stops the logging of the `level=debug msg="Scheduler: virtual-machine v1 changed: re-balancing"` message.
We can take this out later once needed.

Disable VM CPU auto pinning (stable-5.21)

---

Makefile
doc/Makefile
doc/cloud-init.md
doc/custom_conf.py
doc/faq.md
doc/howto/benchmark_performance.md
doc/howto/images_manage.md
doc/howto/instances_create.md
doc/howto/instances_routed_nic_vm.md
doc/installing.md
doc/tutorial/first_steps.md

Several small doc fixes - see the separate commits.

doc: small fixes

---

lxd-agent/events.go
lxd-agent/main.go
lxd-agent/main_agent.go
lxd-agent/server.go
lxd/auth/drivers/tls.go
lxd/auth/generate/main.go
lxd/cluster/membership.go
lxd/daemon.go
lxd/firewall/drivers/drivers_xtables.go
lxd/identities.go
lxd/project/permissions.go

Sometimes the hotplug event is received from LXD before the virtiofs device is available in the guest VM.
So retry several times before giving up to allow it to be activated.
This, in conjunction with a sleep in the lxd-ci tests makes the storage-disks-vm tests more reliable:
https://github.com/canonical/lxd-ci/pull/210
Also enables lxd-agent syslog logging for better feedback about what the agent is doing.
Also standardises using the `err` field in contextual logging rather than `error`.
The majority of uses were already using `err`, but there were a few stragglers using `error`.

lxd-agent: Retry VM hotplug directory share mounts

---

doc/.custom_wordlist.txt
doc/config_options.txt
doc/reference/storage_powerflex.md
go.mod
go.sum
lxd/metadata/configuration.json
lxd/storage/drivers/driver_powerflex.go
lxd/storage/drivers/driver_powerflex_utils.go
lxd/storage/drivers/driver_powerflex_volumes.go

This adds the SDC operation mode to the Dell PowerFlex storage driver.
To discover the presence of the SDC and to request further information from it, Dell's `goscaleio` library is added to LXD in order to able to import already existing utility functions. It's license is Apache-2.0.
Using this library we don't have to perform any actions against the SDC ourselves. The library is making use of the SDC's `/dev/scini` device using syscalls.
In addition it refactors the map/unmap functions to be generic so that both the `nvme` and `sdc` operation modes are supported. 
Furthermore constants are used to identify either `nvme` or `sdc` operation mode.
An extension to the test suite is added with https://github.com/canonical/lxd-ci/pull/212.
Using the `sdc` mode currently is limited to images …

Storage: Add Dell PowerFlex SDC operation mode

---

lxd/device/disk.go

This PR fixes the issue which caused failure to start instances when backed by zfs pools in degraded state.
As per https://openzfs.github.io/openzfs-docs/man/master/7/zpoolconcepts.7.html#Device_Failure_and_Recovery, if pools are in degraded state then sufficient replicas exist for continued functioning. As such, we should allow instances to be backed by pools with status of `DEGRADED`.
Closes #13641

Device: Allow zfs storage pools in degraded state

---

Makefile

Even Go 1.21 has improved support for it since 1.21.11 (https://github.com/golang/go/issues/62278)

Makefile: the toolchain directive should be better supported now

---

doc/.custom_wordlist.txt
doc/architectures.md
lxd/include/syscall_numbers.h
lxd/seccomp/seccomp.go
lxd/seccomp/sysinfo_64.go

Based on https://github.com/canonical/lxd/pull/13691 and https://github.com/lxc/incus/pull/370

Add loongarch64 (from Incus)

---

lxd/instance/drivers/driver_qemu.go

I don't think this is currently causing any bugs, but the correct limit for QEMU IDs is 63, not 64. If longer than that, QEMU truncates the ID internally.

VM: Correct QEMU device ID max length

---

lxd/device/tpm.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/drivers/driver_qemu_templates.go

This fixes TPM failing due to the device ID being trimmed if too long, that caused any references to that device to be incorrect after trimming.
To reproduce the issue:
1.`LONG_DEVICE_NAME="device-with-very-long-name-and---4-qemu-property-handling-test_"`
2.`lxc init ubuntu:n vm --vm`
3.`lxc config device add vm "${LONG_DEVICE_NAME}" tpm`
4.`lxc start vm`
This also allows using `/` in TPM names

Device: Fix TPM name errors

---

lxd/api_internal.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/instance_utils.go
lxd/instances.go

Ignore `liblxc.ErrNotRunning` error when stopping.
If the container refuses to stop, then check if the error is ErrNotRunning, and if so ignore it, because sometimes if an earlier shutdown request was sent, but timed out, the actual guest shutdown can still be proceeding and the container may have reached a stop state by now and is in the process of running the onStop hook to cleanup host side devices. If we returned here with ErrNotRunning then this would be incorrect as the onStop hook could still be running and we aren't fully cleaned up yet, which can cause issues with state reporting after Stop has returned.

Instance: Fix containers not always starting up after host reboot

---

lxd/auth/drivers/openfga.go
lxd/auth/drivers/tls.go
lxd/auth/util.go
lxd/daemon.go
lxd/identities.go
lxd/identity/cache.go
lxd/identity/util.go

This avoids repeating similar logic in multiple places by additionally checking the identity cache for unrestricted clients when checking for admin privileges. See https://github.com/canonical/lxd/pull/13702#discussion_r1665955250

Auth: Use util for determining if the caller is a server administrator

---

test/main.sh

The command xgettext is not used, only xgettext-go is but that's a different
thing.
The xgettext command comes from the gettext package which also provides
some other commands that are actually used like msgmerge and msgfmt. As such,
the list of dependencies to install remains unchanged.

test/main: don't check for xgettext command

---

doc/config_options.txt
lxd/cluster/config/config.go
lxd/metadata/configuration.json

The short description was missed when copying the metadata format from the audience key.

Update short description for the OIDC groups claim

---

lxd-agent/server.go
lxd/certificates.go
lxd/cluster/tls.go
lxd/daemon.go
lxd/util/http.go
lxd/util/net.go
shared/network.go
test/suites/pki.sh

This PR enables mTLS for server certificates when CA mode is present. Allowing intra-cluster traffic when server certificates are not signed by the CA.
Depends on #13704

Enable mTLS for server certificates (stable-4.0)

---

lxd/certificates.go

When a certificate add operation is returned by another member, the operation metadata is unmarshalled into a map[string]any. Since there is no hint that the value of `Metadata["request"]` should be an `api.CertificatesPost`, the contents will be another `map[string]any` following json unmarshalling defaults.
So that we do not encounter issues with diverging field names if the `api.CertificatesPost` type changes, I have opted to marshal the `any` that is in `Metadata["request"]`, and subsequently unmarshal it into the correct type.
Closes #13732

Extract certificate add token metadata from remote member

---

test/suites/pki.sh

We expect the exact string to be present. Also makes the test more consistent with what is in `main`. See https://github.com/canonical/lxd/pull/13705#discussion_r1672781680.

test/suites: Grep for trusted certificate names with `-wF` flags (stable-4.0)

---

doc/api-extensions.md
doc/config_options.txt
doc/explanation/storage.md
doc/howto/storage_volumes.md
lxd/db/instances.go
lxd/device/config/devices.go
lxd/device/disk.go
lxd/metadata/configuration.json
lxd/network/acl/acl_ovn.go
lxd/network/acl/driver_common.go
lxd/network/network_utils.go
lxd/storage/backend_lxd.go
lxd/storage/drivers/driver_common.go
lxd/storage/utils.go
shared/version/api.go
test/suites/storage_profiles.sh

Closes #12254.
Changes mostly based on [lxc/incus#467](https://github.com/lxc/incus/pull/467) and [lxc/incus#529](https://github.com/lxc/incus/pull/529).
This creates the `security.shared` config key for block volumes and adds checks for it during device creation and instance start.
This also includes checks for path definition when adding custom volume devices to profiles (filesystem volumes require a path and block volumes don't) and does some refactoring on the `validateConfig` function to make the disk validation process more readable.

Prevent custom block volume sharing

---

test/includes/uuid.sh
test/main.sh
test/suites/clustering.sh

Tests the case where a certificate add operation is running on cluster member A, but the `POST /1.0/certificates` request containing the join token is sent to cluster member B.

Test certificate add token remote operation

---

test/suites/backup.sh
test/suites/basic.sh
test/suites/clustering.sh
test/suites/config.sh
test/suites/container_devices_nic_bridged.sh
test/suites/devlxd.sh
test/suites/incremental_copy.sh
test/suites/migration.sh
test/suites/network_zone.sh
test/suites/snapshots.sh
test/suites/storage_buckets.sh
test/suites/storage_local_volume_handling.sh

This PR is mainly to improve debuggability. Here's why:
```
echo foo > test-file
cat test-file | grep -Fx "foo"
echo bar > test-file
cat test-file | grep -Fx "foo"
```
Versus:
```
echo foo > test-file
[ "$(cat test-file)" = "foo" ]
echo bar > test-file
[ "$(cat test-file)" = "foo" ]
```
In the last case, it will be easy to figure what was in the test file as we'll see `[ "bar" = "foo" ]` thanks to the test being run with `set -x`.
**Additional bonus**: this caught a bogus invocation of `curl` where the output was not properly redirected.

test: replace many `grep -Fx` by shell comparison

---

lxd/certificates.go
test/suites/clustering.sh
test/suites/remote.sh

When using a certificate add token stored in an operation on a non-local cluster member the expiry time of the token wasn't being taken into account due to incorrect data type conversion and error checking.

lxd: Improve certificate add token validation

---

shared/simplestreams/products.go

In addition to extracting image creation date, try to extract image creation time. If parsing fails, fallback to parsing only the date.

Try to extract version creation/upload time for simplestream images

---

lxd/daemon.go
lxd/devlxd.go
lxd/devlxd_test.go
lxd/images.go
test/suites/tls_restrictions.sh

This was caused by calling `CheckPermission` without considering that the handler is called internally by devlxd.
In this PR I have updated all image handlers that have `AllowUntrusted` set to true. The handling of authentication/authorization is clarified with comments indicating what should happen when the caller is:
- A guest instance.
- An untrusted client.
- An untrusted client with an image secret.
- An authenticated client.
Comments contextual of whether the image is public, private, or cached.
Closes #13678
Closes #13167

Fix devlxd image export

---

lxd/apparmor/apparmor.go
lxd/apparmor/feature_check.go
lxd/apparmor/instance.go
lxd/apparmor/instance_lxc.go
lxd/sys/apparmor.go
lxd/sys/os.go

Closes https://github.com/canonical/lxd/pull/12698

Instance: Allow nosymfollow mount flag for container apparmor profile

---

lxd/instance/drivers/driver_common.go

Device: Fix crash when device doesn't return run config when being live updated (stable-5.21)

---

lxd/apparmor/apparmor.go
lxd/apparmor/feature_check.go
lxd/apparmor/instance.go
lxd/apparmor/instance_lxc.go

Right now this patch does not change anything, because user namespaces are always allowed. But after we merge https://github.com/canonical/lxd-pkg-snap/pull/277 user namespaces become restricted by default and we need to explicitly allow it when needed.

lxd/apparmor: allow userns for security.nesting=true case

---

doc/.custom_wordlist.txt
doc/.sphinx/.markdownlint/exceptions.txt
doc/contributing.md

Add a section on how to add instructions for CLI, API, and UI.

doc/contributing: add section on how-tos

---

lxd/storage/backend_lxd.go

Lower `qemu-img convert` priority instead of limiting it to 2 minutes during the image conversion. This also make it consistent with ImageUnpack.

Lower qemu-img convert priority during conversion instead of limiting cpu time

---

lxd/api_project.go
test/suites/projects.sh

This PR provides an update to the logic for patching project configurations. Previously, there was an overwrite of the existing project config such that it was updated to consist solely of the data in the patch. With this update we maintain existing key/value pairs, and only overwrite those also present in the patch.
Closes #13632.

lxd: Update logic for project config patch

---

Makefile
doc/requirements.md
go.mod
go.sum
lxd/db/openfga/openfga.go
test/godeps/lxd-agent.list

Closes #13667 by updating openfga to version 1.5.6.

Openfga dependency update

---

doc/metrics.md

Tiny fix. Trailing slash in the symbolic link probably should not be there.
When I run the command: "ln -s /var/snap/prometheus/common/tls/ /var/snap/prometheus/current/tls/"
The result is: "ln: failed to create symbolic link '/var/snap/prometheus/current/tls/': No such file or directory"
Removing the trailing slash from the symbolic link command corrects this and creates the sym link.

Update metrics.md to remove symlink trailing slash

---

lxd/device/device_utils_disk.go
lxd/device/disk.go
lxd/instance/drivers/driver_qemu.go

Otherwise virtiofsd doesn't start and this causes VMs to hang on start up when used on Ubuntu 18.04 generic kernels (4.15) with QEMU >= 8.0 (which replaced the bundled virtiofsd with an external one written in rust which defaults to namespace sandbox mode relying on pidfd_open syscall).
Fixes #12856
Tested on Ubuntu 18.04 4.15 kernel and Ubuntu 22.04 6.5 HWE kernel.

VM: Use virtiofsd chroot sandbox mode on pre pidfd_open kernels

---

doc/howto/projects_create.md

The functionality was fixed in https://github.com/canonical/lxd/pull/13786

doc/projects: fix documentation for PATCH request

---

doc/explanation/storage.md
doc/howto/storage_pools.md

This adds another tab in the how-to section which shows some examples on how to setup Dell PowerFlex storage pools.
In addition the explanation section of the docs now also mentions Dell PowerFlex.

Doc: Add more details on Dell PowerFlex pool creation

---

.github/workflows/tests.yml

Caused by requirement to use 3GiB pool size.

github: Exclude lvm standalone tests as they fail on Github due to lack of space (stable-4.0)

---

doc/howto/storage_pools.md

We have too many storage drivers now, so using tabs for them doesn't scale. ;-)
Also, it will cause problems when adding API/UI instructions anyway, so converting it into sections.

doc/storage: change examples to sections instead of tabs

---

lxd-migrate/main_migrate.go

Wrong path is passed to the `isImageTypeRaw` check.
Introduced in https://github.com/canonical/lxd/pull/13385

lxd-migrate: Fix path provided to the raw disk check

---

lxd/apparmor/instance_lxc.go

It turns out, that a ruleset:
```
{{- if .feature_mount_nosymfollow }}
mount options=(ro,remount,bind,nosuid,noexec,nodev,nosymfollow) /[^spd]*{,/**},
mount options=(ro,remount,bind,nosuid,noexec,nodev,nosymfollow) /d[^e]*{,/**},
mount options=(ro,remount,bind,nosuid,noexec,nodev,nosymfollow) /de[^v]*{,/**},
mount options=(ro,remount,bind,nosuid,noexec,nodev,nosymfollow) /dev/.[^l]*{,/**},
mount options=(ro,remount,bind,nosuid,noexec,nodev,nosymfollow) /dev/.l[^x]*{,/**},
mount options=(ro,remount,bind,nosuid,noexec,nodev,nosymfollow) /dev/.lx[^c]*{,/**},
mount options=(ro,remount,bind,nosuid,noexec,nodev,nosymfollow) /dev/.lxc?*{,/**},
mount options=(ro,remount,bind,nosuid,noexec,nodev,nosymfollow) /dev/[^.]*{,/**},
mount options=(ro,remount,bind,nosuid,noexec,nodev,nosymfollow) …
```

Container: Allow apparmor nosymfollow mount flag in more cases

---

lxc/config/cert.go
lxc/file.go
lxd-agent/network.go
lxd-migrate/utils.go
lxd-user/lxd.go
lxd/instance/drivers/driver_qemu.go
lxd/util/encryption.go
shared/cert.go
shared/cert_test.go

This is primarily for microcluster. From the discussions in Madrid about join token verification (the MITM discussions), we decided we would verify that the SAN of the `server.crt` of a joiner microcluster node must match the node name specified when creating the join token.
By default, LXD sets this to be the hostname of the system that generated the certificate. In microcluster, the node name does not necessarily always have to line up exactly with the hostname of the system, rather the name is supplied at the time we bootstrap or join a cluster. So we need to be able to set the name in the certificate ourselves.

Specify subject name when generating keypair

---

lxd/api_project.go
lxd/auth/drivers/openfga.go
lxd/auth/drivers/tls.go
lxd/db/cluster/entities.go
lxd/db/openfga/openfga.go
lxd/project/permissions.go
shared/entity/type.go
shared/entity/type_test.go

In our implementation of `(github.com/openfga/openfga/pkg/storage).OpenFGADatastore`, entity URLs are expected to include the project query parameter even if it is the default project. However, LXD typically displays URLs without the project query parameter when a resource is in the default project (with the exception of permissions, where we have been explicit).
This PR ensures that the project query parameter is added to URLs inside the Authorizer so that this doesn't need to be done elsewhere in the codebase (such as in `project.FilterUsedBy` which has now been simplified). 
Closes #13072

Auth: Add project query parameter to URLs in authorizer

---

doc/howto/storage_pools.md

A follow up on https://github.com/canonical/lxd/pull/13819 that addresses https://github.com/canonical/lxd/pull/13819#discussion_r1692685809.

doc: Use consistent naming for remote pool creation examples

---

lxd/cluster/connect.go
lxd/response.go
lxd/storage_buckets.go
lxd/storage_volumes.go
lxd/storage_volumes_backup.go
lxd/storage_volumes_snapshot.go
shared/entity/type.go

This PR fixes fine grained authorization for storage volumes and storage buckets in clustered LXD. 
When listing volumes, we can use the `Location` field of the storage volume or bucket to perform an access check.
When performing an action on a single storage volume, we need to perform the following checks:
1. Is the pool containing the volume remote? If so, the `target` query parameter may have been used to target a particular cluster member, but should not be used in the URL for the volume (volumes in remote pools do not have a location).
2. Is the volume located on another cluster member? If so, and the target parameter is set, use the target parameter as the location. If so, and the target parameter is unset, use the cluster member name as the location. If not, use the server name as …

Auth: Add storage volume and bucket location to URL in access check

---

doc/howto/import_machines_to_instances.md

Fix closing code tag and update link to `rhsrvany` to point to the section "Binary releases" in the README where installation example is provided.

doc: Update rhsrvany link and fix code blocks

---

lxd/device/device_utils_disk.go

Sorry for the previous PR spam!
Unless there's a reason for the lack of extended attributes on `virtiofs` I'm not aware of, it would be nice to have this option enabled as there are some use-cases where read/writing extended attributes are needed on files within the mounted disk.

VM: Add support for extended attributes for virtiofs shares

---

lxd/seccomp/seccomp.go

A right bpf() syscall number on arm64 is 280:
https://github.com/torvalds/linux/blob/dc1c8034e31b14a2e5e212104ec508aec44ce1b9/tools/lib/bpf/bpf.c#L49

lxd/seccomp: fix bpf syscall number for arm64

---

lxd/include/lxd_bpf.h
lxd/include/lxd_bpf_common.h

Our bpf UAPI header files are obsolete, which leads to errors like:
level=debug msg="Handling bpf syscall" audit_architecture=3221225655 bpf_attach_type=-22 bpf_cmd=-22 bpf_prog_type=-22 container=t1 project=default seccomp_notify_fd=35 seccomp_notify_flags=0 seccomp_notify_id=8290735664846847091 seccomp_notify_mem_fd=34 seccomp_notify_pid=1942874 syscall_continue=true syscall_handler_error="file too large - Failed to handle bpf syscall" syscall_number=280
Let's update our headers to ones from Linux kernel version 6.10.

lxd/include: update bpf header files

---

lxd/device/disk.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/instance_interface.go
lxd/instance_post.go

Enables live-migration of an instance with volumes attached as long as those disks are also on a remote storage pool.
Created as draft while I finish writing tests.
Closes #12694

Live migration with attached storage volumes (from Incus)

---

doc/api-extensions.md
doc/howto/instances_manage.md
doc/metadata.txt
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/instancetype/instance.go
lxd/instances.go
lxd/metadata/configuration.json
scripts/bash/lxd-client
shared/version/api.go
test/suites/security.sh

This PR adds a new instance configuration option `security.protection.start`, and throws an error if a given instance with this option set to `true` is started.
Closes #12110.

Add `security.protection.start` to optionally prevent instance start up

---

lxd/device/device_utils_disk.go

To support more versions of virtiofsd.
Follows from https://github.com/canonical/lxd/pull/13828

Device: Use -o flag for xattr mode of virtiofsd for `disk` device

---

lxd/storage/backend_lxd.go

In conversion API the file was not created on the server when receiving a raw image on directory storage pool.
In addition, there are two minor fixes:
- Remove unnecessary usage of VolumeCopy
- Set volume size directly on volume's config (instead of on args.Config which points to the same map).

lxd: Ensure file is created when receiving raw image

---

lxd/instance/drivers/driver_qemu.go

This PR adds a check for a missing/offline qemu agent in the notification logic, so that we can avoid returning an error when updating instance config.
Cherry picked from https://github.com/lxc/incus/pull/324.

VM: Don't fail event sending on missing agent (from Incus)

---

lxd/instance/drivers/driver_common.go
lxd/instance/drivers/driver_lxc.go
test/main.sh
test/suites/snapshots.sh

Fixes #13466
We need a non-locking delete on an `Instance`; otherwise a failure while mounting the instance/updating the backup file will deadlock.
I don't love the type assertion here. However, since `CreateInternal` returns `Instance`, we don't have a lot of options beyond enriching that interface or providing an additional one.
In order to avoid using type assertions we'd need to define an internal interface `instance` for `delete` and possibly a few other functions in the drivers/ package and implement it for `lxc`/`qemu`. Alternatively, moving the `Interface` interface into the same package as the drivers would allow us to define some private methods on `Interface` instead.
(Updating the backup file on the full volume was very likely the failure in #13466; this is after applying the …

Instance: Fix deadlock during failed snapshot creation

---

lxd/firewall/drivers/drivers_nftables.go
lxd/firewall/drivers/drivers_xtables.go

This was confusing when I ran into it; initially thought PyLXD had mixed up some json fields...

lxd/firewall/drivers: Fix netprio error message

---

lxd-migrate/main_migrate.go
lxd/storage/backend_lxd.go

Prevents conversion from OVA file format. On the server side we check whether the file is a tarball when the file is uploaded.
To prevent file from being uploaded in the first place, we also use the same check in `lxd-migrate`.

lxd: Prevent conversion from OVA file format

---

doc/metadata.txt
lxd-agent/devlxd.go
lxd/instance/instancetype/instance.go
lxd/metadata/configuration.json

Adds an endpoint to the LXD agent `/dev/lxd` socket listener that proxies requests to `/1.0/images/{fingerprint}/export` on the host LXD devlxd listener.
Additionally cleans up `lxd-agent/devlxd.go` and moves the `security.devlxd.images` config key from the container specific config key map into the shared container/VM config key map and regenerates the metadata.
I just worked on this to speed up my local test runs :)
Closes #12589

Image export over devlxd for virtual machines

---

doc/api-extensions.md
shared/version/api.go

This isn't explicitly used in the client, but will be useful in testing.

Adds an API extension for image export over devlxd in VMs

---

doc/custom_conf.py

The latest version of Swagger works with our docs again.
Closes #12974

doc: unpin Swagger version

---

lxd/firewall/drivers/drivers_xtables.go

cherry-picked from lxc/incus#376
When xtables uses the nft shim, the actual xtables kernel modules never get loaded, therefore the files containing the list of valid tables never get populated.
This then leads to iptablesClear always skipping all tables despite rules having been added previously.
(cherry picked from commit 3c6a60d844a7fccfb207f53e01fbb111958d42be)

lxd/firewall: Fix iptablesClear on nft shim (from Incus)

---

lxd/instance_post.go

When migrating an instance between clustered servers, beginning the source operation before the destination operation allows us to return more helpful error messages.
Cherry pick from https://github.com/lxc/incus/pull/1039.
Relevant to https://github.com/canonical/lxd/issues/11948.

Migration: Show source errors first (from Incus)

---

lxd/instance/instance_utils.go
lxd/storage/backend_lxd.go
test/suites/backup.sh

Storage: Fix import of instance snapshots with underscores in their names

---

lxd/api_cluster.go

This small PR ensures we update state upon cluster put/join.
Cherry picked from https://github.com/lxc/incus/pull/366.

lxd: Refresh the state on cluster put/join (from Incus)

---

doc/howto/images_copy.md

To upload a split image through the API, you must upload the metadata tarball before the rootfs image.

doc/images: specify the order of split images

---

lxd/firewall/drivers/drivers_xtables.go

Based on https://github.com/lxc/incus/pull/310.
This also fixes a bug where the Iptables rules were not being set correctly on xtables, it was included here because the linter was failing because of it.

lxd/firewall/drivers: Make sure to always use locking (from Incus)

---

lxd/instance/drivers/driver_qemu_config_test.go
lxd/instance/drivers/driver_qemu_templates.go

Although this changes qemu device IDs for physical PCI and GPU under some specific circumstances, it is safe to merge since the device ID is only a reference inside QEMU and does not affect how the device is shown inside the instance (`lspci`  information is the same regardless of these changes). Applying this changes was tested and it does not affect previously created devices, they will may have a different device ID iin QEMU the next reboot.
Since `lxd-ci` does not include tests with these types of devices, no tests related to these changes will be added.
Fixes #13597

VM: Improve QEMU passthrough device ID generation

---

lxd/api_cluster.go
test/suites/clustering.sh

In https://github.com/canonical/lxd/pull/13957#discussion_r1726718542 we found that currently `none` is a valid LXD cluster member name.
This collides with the internally used concept which identifies if LXD is clustered or not by setting it's internal `ServerName` to `none` or it's actual cluster name.
The PR ensures that a LXD cluster member's name cannot be `none` as well as blocking the creation of join tokens with name `none`.

Cluster: Enforce member name cannot be `none`

---

doc/metadata.txt
lxd/device/nic_ovn.go
lxd/instance/instancetype/instance.go
lxd/metadata/configuration.json
lxd/network/driver_ovn.go
lxd/patches.go

Confirmed that creating an OVN NIC when there is insufficient space causes an error:
```
Error: Failed instance creation: Failed creating instance record: Failed initialising instance: Failed to add device "eth0": Failed setting up OVN port: Insufficient dynamic addresses allocated
```
WRT to exploring if we can later add a network option to allow dynamic allocation at start time rather than create time, this should be possible to do by not setting the `dynamic` option when we create the port, but instead setting it at start time and removing it at stop time. **But will not add this functionality in this PR.**
E.g.
```
sudo ovn-nbctl find logical_switch_port
addresses           : ["00:16:3e:24:9c:4c"]
dhcpv4_options      : 592a6788-4c73-4773-a8fa-12808377eccf
dhcpv6_options      : …
```

Network: Switch to long-lived OVN ports

---

lxd/api_cluster.go
lxd/daemon.go

Stop networks when a cluster member has been evacuated.
Includes cherry-picks from https://github.com/lxc/incus/pull/747

lxd: Disable networks during evacuation (from Incus)

---

doc/explanation/projects.md
lxd/auth/drivers/openfga.go
lxd/auth/drivers/tls.go
lxd/auth/types.go
lxd/events.go
lxd/images.go
lxd/network_acls.go
lxd/network_allocations.go
lxd/network_forwards.go
lxd/network_load_balancers.go
lxd/network_peer.go
lxd/network_zones.go
lxd/network_zones_records.go
lxd/networks.go
lxd/profiles.go
lxd/project/project.go
lxd/storage_volumes.go
test/includes/storage.sh
test/suites/auth.sh
test/suites/storage_buckets.sh
test/suites/tls_restrictions.sh

Implements the following:
1. Always sets the effective project when querying entities that have associated `features.*` project config. This includes:
i. Adding network, network zone, image, and profile specific access handlers.
ii. For each entity type above, setting details in the request context to avoid repeated calculation (same pattern as for storage buckets and volumes).
2. Always uses the request project in calls to `(Authorizer).CheckPermission` and in calls to the `auth.PermissionChecker` returned by `(Authorizer).GetPermissionChecker`.
3. In the TLS driver, we remove effective project handling (we always expect calls to use the request project, this is what we check in their allowed project list).
4. In the OpenFGA driver, overwrite the request project with the effective …

Effective project handling

---

lxc/main.go
lxd-migrate/main.go
lxd/main.go
shared/cmd/ask.go

If a command asker is with a logger, the question and answer (even if it is invalid) are systematically logged to the logger destination. This will greatly help debugability in integration test suites like in MicroCloud which have a lot of interactions in the command line.

shared/cmd: Allow a cmd asker to be created with a logger instance

---

lxd/daemon.go
lxd/instances.go
lxd/storage/drivers/driver_zfs_volumes.go

Because otherwise ZFS volumes aren't deactivated during instance shutdown during LXD shutdown
because `d.state.ShutdownCtx` is canceled already.

Storage: Don't use d.state.ShutdownCtx in ZFS GetVolumeDiskPath

---

doc/reference/instance_options.md

Adds a short warning about volatile keys in the reference page. I wasn't sure how explicit to be about this warning so recommendations welcome.
Edit: I've just seen that a similar warning exists for `raw.*` config keys so I've copied that instead.

doc/reference: Add warning about volatile keys

---

doc/rest-api.yaml
shared/api/instance.go

Not sure if this is too late to be fixed, but json and yaml keys for source disk size have incorrect case (`sourceDiskSize` -> `source_disk_size`).

shared: Fix conversion source disk size JSON and YAML key name

---

lxd/apparmor/instance_lxc.go

A new AppArmor includes security fixes and our ruleset become stricter, while the source code remains unchanged.
procfs was always available for unprivileged containers because of AppArmor bugs like [1]. Let's now allow it back by explicit rule.
[1] https://bugs.launchpad.net/apparmor/+bug/1597017

AppArmor: Allow procfs for unprivileged containers

---

doc/reference/devices_gpu.md
lxd/device/cdi/spec.go
lxd/device/cdi/spec_unsupported.go

Related issue: https://launchpadlibrarian.net/746341085/buildlog_snap_ubuntu_noble_armhf_lxd-latest-edge_BUILDING.txt.gz

lxd/device/cdi: Disable NVIDIA CDI for `armhf` platforms

---

lxd/device/cdi/spec_unsupported.go

Fix `armhf` build
https://launchpadlibrarian.net/746378162/buildlog_snap_ubuntu_noble_armhf_lxd-latest-edge_BUILDING.txt.gz

lxd/device/cdi: add no-op `defaultNvidiaTegraCSVFiles` for `armhf` build

---

Makefile

This avoids crashes in LP on riscv64

Makefile: pin gorilla/websocket version (stable-5.0)

---

client/lxd_instances.go

This PR adds functionality to report source errors during copy. This helps to solve the issue of the incorrect error being reported when a live migration is attempted while `migration.stateful` is missing or set to false.
(Also rectifies a few unchecked type assertions in `client/lxd_instances.go` since the linter complained)
Closes https://github.com/canonical/lxd/issues/11948.

Migration: Forward migration errors (from Incus)

---

test/lint/godeps.sh

Check all godeps list files rather than abort on the first error:
```
$ test/lint/godeps.sh 
==> Checking for imports/deps that have been added to client...
ERROR: you added a new dependency to client; please make sure this is what you want
--- test/godeps/client.list	2024-08-30 12:07:58.629873467 -0400
+++ -	2024-08-30 13:14:25.140400058 -0400
@@ -75,6 +75,7 @@
vendor/golang.org/x/crypto/hkdf
vendor/golang.org/x/crypto/internal/alias
vendor/golang.org/x/crypto/internal/poly1305
+vendor/golang.org/x/crypto/sha3
vendor/golang.org/x/net/dns/dnsmessage
vendor/golang.org/x/net/http/httpguts
vendor/golang.org/x/net/http/httpproxy
==> Checking for imports/deps that have been added to lxc/config...
ERROR: you added a new dependency to lxc/config; please make sure this is what you want
--- …
```

test/lint/godeps: don't abort on first error

---

lxd/storage/drivers/driver_dir_utils.go

Fixes #13115
This avoids setting project quotas when the project does not change ([from Incus](https://github.com/lxc/incus/pull/1163)), and also avoids unnecessary project setting on `DeleteProject`.
Reported-by: Marius Klocke [mklocke@maxcluster.de](mailto:mklocke@maxcluster.de)
Closes https://github.com/canonical/lxd/pull/13813

Storage: Fix unnecessary dir project quota updates (from Incus)

---

test/suites/clustering.sh

As we have both the password and token support in `5.21`, we can completely backport https://github.com/canonical/lxd/commit/c49ef5f1c599c9c6883b20527387a7e8057b8155.
An additional commit ensures that also when joining cluster nodes using the legacy password (which is still in `5.21`) the name cannot be `none`.
This change works with the LXD snap from `5.21/edge`.

Tests: Check cluster member names cannot be 'none' (stable-5.21)

---

lxd/device/gpu_physical.go

CDI GPU are not hotpluggable because the configuration of a CDI GPU requires a LXC hook that is only run at instance start. A classic GPU device can be hotplugged.

lxd/device/gpu_physical: forbid CDI GPU hotplugging

---

doc/guest-os-compatibility.md
lxd/instance/drivers/driver_qemu.go

Make lxd-agent install script compatible with SUSE

---

lxd/project/permissions.go
test/suites/projects.sh

See [the docs](https://documentation.ubuntu.com/lxd/en/latest/reference/projects/#project-restricted:restricted.devices.disk) for disk device restrictions. This PR prevents checking the `restricted.devices.disk.paths` for managed devices when `restricted.devices.disk: allow`.
Contains cherry-picks from https://github.com/lxc/incus/pull/708

lxd/project: Allow managed volumes under "allow" (from Incus)

---

lxd/instances_post.go

User reported in https://github.com/lxc/incus/issues/463 that project limits were not being enforced on the cluster member in direct communication with the client during instance creation.
~I also noticed that the limit checks were being skipped based on the value of the [`User-Agent` header](https://github.com/canonical/lxd/commit/d6871e49e4ae7c1ee173c49ca08e350e11f45b73), which is spoofable. This pushes the limits check back to the target cluster member.~
Contains cherry-picks from https://github.com/lxc/incus/pull/505

lxd/instances: Don't bypass instance limit check (from Incus)

---

lxd/cluster/heartbeat.go
lxd/db/cluster/entities.go
shared/entity/type.go
shared/entity/type_test.go

Updates `TypeNode` to `TypeClusterMember` and its value from `node` to `cluster_member`.
This is done because the term node is inappropriate to be exposed to users, and it will be when the API metrics are introduced.
As of now this type is not exposed to users so an API extension is not needed.

Entity: Rename TypeNode to TypeClusterMember

---

test/includes/net.sh
test/main.sh
test/suites/tls_restrictions.sh

Make sure LXD accepts only TLS 1.3 in its default configuration. Also verify that `LXD_INSECURE_TLS=true` reduces the security just enough to provide TLS 1.2 for backward compatibility without allowing CBC nor SHA1.
The fine grain cipher checks will likely require changes over time as Go default cipher list evolves.

Test `LXD_INSECURE_TLS`

---

shared/cert.go
shared/trust/hmac.go
shared/trust/hmac_argon2.go
shared/trust/hmac_test.go

This PR adds additional HMAC and cert utils to the `shared` package.
The HMAC implementation follows the practices from the [explicit trust establishment spec](https://discourse.ubuntu.com/t/explicit-trust-establishment-mechanism-for-microcloud/44261).
It's imported as a general utility in LXD to be used by MicroCloud during trust establishment.
In order to make the use of a KDF (in this case argon2) optional, there is a second factory function that allows using some extended functionality added by argon2.
To create a HMAC header, the caller runs:
```go
// Specific HMAC version to allow indicating protocol changes in the future.
const HMACMicroCloud10 trust.HMACVersion = "MicroCloud-1.0"
// Basic format
hmac := trust.NewHMAC(<key>, NewDefaultHMACConf("LXD1.0"))
// Create the …
```

Shared: Add HMAC and cert utils

---

shared/version/api.go

NOTE: This change would normally be committed with an update to `doc/api-extensions.md` (582b2ccddeebbfa17df7becfd3979d4f5438a0a1) but this was missed. These commits need to be cherry-picked together.

api: Add `metrics_api_requests` extension.

---

lxd/instance/drivers/driver_qemu.go
lxd/instance/drivers/edk2/edk2.go

Based on:
- https://github.com/lxc/incus/pull/1187
- https://github.com/lxc/incus/pull/1193
Follows on from https://github.com/canonical/lxd/pull/14032
Also improves the removal of old firmware vars files by not checking the if the associated firmwares exist on the host and not trying to remove the same files multiple times.

VM: Firmware detection fixes (from Incus)

---

lxc/completion.go
lxc/config.go
lxc/profile.go

`cmpInstanceAllKeys()` was only grabbing config keys that apply to any instance, but we also want to grab/complete keys that are specific to containers or VM's.

Completions: Fix completions for config keys

---

lxd/instance/drivers/driver_qemu_cmd.go
lxd/instance_exec.go

Includes cherry picks from https://github.com/lxc/incus/pull/362

Improve VM shutdown

---

lxd/project/limits/permission_internal_test.go
lxd/project/limits/permissions.go

Before this change, setting container-specific/VM-specific "low-level" config values on a profile required both `restricted.containers.lowlevel: true` and `restricted.virtual-machines.lowlevel: true`.
The test failed before and passes after.
Contains cherry-picks from https://github.com/lxc/incus/pull/827

Rework permissions checks (from Incus)

---

.github/workflows/commits.yml
.github/workflows/tests.yml
Makefile

This PR:
1. Moves the building of the LXD binaries for the system tests into the code test stage and uses GH artifacts system in order to avoid building the LXD binaries multiple times for each concurrent runner.
2. Adds functionality to build LXD binaries with code coverage support and uploads them to the GH artifact system for collection later (this will come in a future PR).
3. Various Makefile improvements and cleanups.

CI Profiling precursor changes

---

lxd/instance/drivers/driver_qemu.go
lxd/instance/drivers/driver_qemu_templates.go

This improvement will resolve https://github.com/canonical/lxd/issues/14001 with the inclusion of an armhf 32-bit lxd-agent binary in the lxd snap.

lxd/instance: Add support for armhf vm's on arm64 hosts

---

lxc/config/config.go

The actual tokens are already safe with 0600 but let's also avoid disclosing which tokens we have by making the directory a bit more private. Same as the `servercerts` directory.

lxc/config: create `oidctokens` dir with 0750

---

lxd/instance_instance_types.go

The same line is logged as an error on [lines 91-94](https://github.com/canonical/lxd/blob/main/lxd/instance_instance_types.go#L93).
Fixes #13964

lxd: Deduplicate logging for instance types update failure

---

test/suites/exec.sh

Adding test to check for `lxc exec` behavior if container disconnects, after our discussion this week.

test: Container disconnection on `lxc exec`

---

lxd/api_project.go
test/main.sh
test/suites/projects.sh

From https://github.com/lxc/incus/pull/1109.
After https://github.com/canonical/lxd/pull/14078 got merged the following error started to appear on MicroCloud when forming clusters: `
Error: System "micro02" failed to join the cluster: Failed to update cluster status of services: Failed to join "LXD" cluster: Failed to configure cluster: Failed to initialize member: Failed to initialize storage pools and networks: Failed to update local member project "default": Failed loading storage pool names: Storage pool(s) not found`
The DB`s `GetStoragePoolNames()` returns 404 in case of no storage pools. This has to be checked explicitly otherwise the error is returned back to the caller.

Project: Don't fail creation on missing pools (from Incus)

---

lxd/api.go
lxd/auth/types.go
lxd/daemon.go
lxd/devlxd.go
lxd/events.go
lxd/images.go
lxd/instance_sftp.go
lxd/metrics/api_rates.go
lxd/operations/response.go
lxd/operations/websocket.go
lxd/request/request.go
lxd/response/response.go
test/devlxd-client/devlxd-client.go
test/suites/devlxd.sh

This makes it so that we don't expect the metrics callback to be present on devlxd endpoints and neither on the `/` endpoint.
It does so by reworkin how we check for requests originating from `/dev/lxd`. Instead of  setting the request remote address, this sets a newly introduced authentication method on the request context for all devlxd requests and uses that to validate devlxd requests. So this makes it possible to avoid logging a warning for devlxd requests when they are not supposed to be tracked for the API metrics. Thanks for the suggestion @markylaing :D.

Request: Fix request not counted warning

---

doc/environment.md
lxd/fsmonitor/drivers/driver_inotify.go
lxd/fsmonitor/drivers/load.go
test/suites/container_devices_unix.sh

The `fsmonitor` package has two drivers, but only fanotify is tested for unix devices (see https://github.com/canonical/lxd/pull/14110#discussion_r1761232451). This is the default driver but it may not be available in all kernels/architectures.
This PR adds an environment variable to force a specific driver to be used. The unix char and block device tests are then run with both drivers.
The `inotify` package was encountering some unknown events. As it turned out, mapping these events to `fsmonitor` events broke the test suite, so I've added exceptions for them to reduce log verbosity.

fsmonitor: Test unix devices with both drivers

---

lxd/images.go

Fixes #13855 
`imageOperationLock`s are not being taken at the start of a `POST /1.0/images` because the image fingerprint can't be trusted until the file has been uploaded (see [lxd/images/go](https://github.com/canonical/lxd/blob/main/lxd/images.go#L1225)). This makes it fairly easy to forget to take a lock at all.

lxd/image: Acquire image lock for uploaded images

---

doc/howto/cluster_recover.md
lxd/cluster/recover.go
lxd/main_cluster.go
test/suites/clustering.sh

This follows a similar feature in microcluster. While any failure of the recovery process may be recoverable, expecting a user to surgically determine the exact step where the failure occurred, manually correct their `database/`, and create a recovery tarball is entirely unreasonable.
This PR creates a database backup `/var/snap/lxd/common/lxd/db_backup.TIMESTAMP.tar.gz` before any sensitive recovery operations so that a failed recovery doesn't cause data loss.
This also prevents `lxd cluster edit` from attempting to reconfigure the database more than once, as a failure during the recovery should allow the user to troubleshoot and retry from the backup.
LXD-1468

Backup before cluster reconfigure

---

doc/howto/container_gpu_passthrough_with_docker.md

https://cloudinit.readthedocs.io/en/latest/reference/modules.html#runcmd does not mention if line continuation work so err on the safe side by making those single line commands.

doc/howto/container_gpu_passthrough_with_docker: use single line cmds

---

doc/.sphinx/.markdownlint/exceptions.txt
doc/howto/import_machines_to_instances.md
lxd-migrate/main_migrate.go
lxd-migrate/utils.go

Added flags for `lxd-migrate` to allow non-interactive usage.
List of added flags:
```
--cert-path            Trusted certificate path
-c, --config               Config key/value to apply to the new instance
--key-path             Trusted certificate key path
--mount-path           Additional container mount paths
--name                 Name of the new instance
--network              Network name
--no-profiles          Create the instance with no profiles applied
--non-interactive      Prevent further interaction if migration questions are incomplete
--profiles             Profiles to apply on the new instance (default [default])
--project              Project name
--server               Unix or HTTPS URL of the target server
--source               Path to the root filesystem for …
```

Add lxd-migrate flags for non-interactive usage

---

lxd/main_init_interactive.go

When using `lxd init` to configure default profile with an existing network, differentiate between managed and unmanaged networks by first trying to retrieve an existing network (and checking if it is managed).
Unamanaged network:
```sh
...
Would you like to configure LXD to use an existing bridge or host interface? (yes/no) [default=no]: yes
Name of the existing bridge or host interface: tmpbr0
...
Would you like a YAML "lxd init" preseed to be printed? (yes/no) [default=no]: y
config: {}
networks: []
storage_pools: []
storage_volumes: []
profiles:
- config: {}
devices:
eth0:
name: eth0
nictype: bridged # <--
parent: tmpbr0   # <--
type: nic
name: default
projects: []
cluster: null
```
Managed network:
```sh
...
Would you like to configure LXD to use an existing bridge or …
```

lxd/init: Differentiate managed and unmanaged network

---

lxd-migrate/main_migrate.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/instance_utils.go
lxd/instance/instancetype/instance.go
lxd/instance_logs.go
lxd/instance_post.go
lxd/instances_post.go
lxd/storage/backend_lxd.go

Prevent `lxd-migrate` from progressing if instance name is not valid.
Noninteractive mode:
```sh
$ sudo ./lxd-migrate --name "test test"
Error: Invalid instance name "test test": Name can only contain alphanumeric and hyphen characters
$ sudo ./lxd-migrate --name "test"
The local LXD server is the target [default=yes]: ...
```
Interactive mode:
```sh
$ sudo ./lxd-migrate
The local LXD server is the target [default=yes]: 
Would you like to create a container (1) or virtual-machine (2)?: 1
Name of the new instance: test test
Invalid instance name "test test": Name can only contain alphanumeric and hyphen characters
Name of the new instance: test
Please provide the path to a root filesystem: ...
```
Closes https://github.com/canonical/lxd/issues/12130

lxd-migrate: Prevent invalid instance names

---

test/suites/tls_restrictions.sh

Making a TLS 1.2 connection with an unsupported cipher does not reliably produces a broken pipe error:
```
for _ in $(seq 100); do
for cipher in ECDHE-ECDSA-AES128-SHA ECDHE-ECDSA-AES256-SHA; do
my_curl --tls-max 1.2 --ciphers "${cipher}" -X GET "https://${LXD_ADDR}" -w "%{errormsg}\n"
done
done 2>&1 | sort | uniq -c
1 Empty reply from server
196 OpenSSL SSL_write: Broken pipe, errno 32
3 OpenSSL SSL_write: Connection reset by peer, errno 104
```
but it always fail so let not look for a specific error, just make sure the connection fails.

test/suites/tls_restrictions: don't check for broken pipe error

---

lxd/storage/drivers/utils.go

`msg` only contains stdout from the child process, so this wasn't passing back any information about what actually failed.
Still working on root cause for these failures: https://github.com/canonical/lxd/actions/runs/10919085792/attempts/1?pr=14122

Storage: Return `growFileSystem` errors

---

.github/workflows/tests.yml
lxd/api_1.0.go
lxd/api_cluster.go
lxd/auth/drivers/openfga.go
lxd/auth/drivers/openfga_model.openfga
lxd/auth/drivers/tls.go
lxd/auth/drivers/tls_test.go
lxd/db/openfga/openfga.go
lxd/storage_pools.go

Removes the [type-bound public access](https://openfga.dev/docs/modeling/public-access) for server and storage pool and replace with an authentication check. This is to simplify the model and the underlying OpenFGADatastore implementation.
This does not change any users existing permissions, as it is not possible to create a permission with `can_view` on `server` or `storage_pool`.
Additionally, this PR improves the TLS authorization driver (see commit message) and adds tests.

Remove type bound public access

---

.github/workflows/tests.yml
doc/api-extensions.md
doc/metadata.txt
lxd-agent/devlxd.go
lxd/daemon.go
lxd/devlxd.go
lxd/instance/instancetype/instance.go
lxd/metadata/configuration.json
lxd/state/state.go
lxd/ubuntupro/client.go
lxd/ubuntupro/client_test.go
shared/api/devlxd.go
shared/version/api.go

This PR implements the LXD side of things for auto-attachment of ubuntu guests:
- Adds a `lxd/ubuntupro` package containing a `Client` which contains an fsmonitor for LXD related configuration.
- Adds the `ubuntupro.Client` to Daemon and State.
- Adds a new config option `ubuntu_pro.guest_attach` with allowed values `on`, `off`, or `available`.
- Adds two `devlxd` endpoints: `GET /1.0/ubuntu-pro` and `POST /1.0/ubuntu-pro/token`. The first returns the value of `ubuntu_pro.guest_attach` (if enabled on the host, otherwise it returns "off"). The second executes a `pro` command on the host to request a guest token, which is returned to the guest.
- Adds the `devlxd` endpoints to the LXD agent.
To use the `fsmonitor` package for this, I needed to refactor it somewhat. This makes the fsmonitor …

Ubuntu Pro auto-attachment of guests

---

lxd-agent/main_agent.go

(cherry picked from https://github.com/lxc/incus/pull/389/commits/c3172b748e0eba8cfd4e959a14bc609a14fa5ac7)

lxd-agent: Handle built-in vsock module (from Incus)

---

lxd/instances_post.go

This PR updates the copy operation response body when using a snapshot as the source. Previously, the response body allocated the snapshot to `resources.instances` and `resources.containers`. This is not entirely accurate, so we now check to see if the source is a snapshot, and if so, we allocate it to `resources.instances_snapshots` instead of `resources.instances` and `resources.containers`.
Closes https://github.com/canonical/lxd/issues/13999.

lxd: Update copy op response body when source is snapshot

---

test/main.sh

It would have saved me some time if the dmesg hadn't been collapsed while I was chasing [this kernel bug](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/2081231).
Not thinking of any situation where we wouldn't want to know about a call trace in the dmesg during CI.

test: Don't collapse dmesg in CI when there's a kernel call trace

---

.github/workflows/tests.yml
test/suites/projects.sh

Workaround our test failures related to https://bugs.launchpad.net/ubuntu/+source/linux/+bug/2081231
Reverts https://github.com/canonical/lxd/pull/14146
This PR contains commits cherry-picked from https://github.com/lxc/incus/pull/1246

tests: Don't over-provision test volume (from Incus)

---

lxd/instances_put.go

Cherry-picked from https://github.com/lxc/incus/pull/387. Tested locally ✅.

lxc: Fix bulk unfreeze (from Incus)

---

doc/api-extensions.md
doc/rest-api.yaml
lxd/auth/generate/main.go
lxd/documentation.go
lxd/lxd-metadata/lxd_metadata.go
lxd/metadata/configuration.json
shared/api/metadata_configuration.go
shared/version/api.go

This is so that we can manage configuration metadata with API extensions as we do with any other API response over `/1.0`
* Adds an API extension for adding entity metadata to `GET /1.0/configuration/metadata`.
* Adds types under `shared/api` for configuration metadata.
* Updates entity metadata such that each entity maps to a JSON object, with `requires_project` and `entitlements` fields.
* Enforces that generated metadata conforms to the new API type.
* Updates the swagger doc for `GET /1.0/configuration/metadata` to include the newly defined type.

Add API types for configuration metadata

---

lxd/fsmonitor/drivers/driver_fanotify.go
lxd/fsmonitor/drivers/driver_inotify.go
lxd/fsmonitor/drivers/load.go
lxd/fsmonitor/fsmonitor_interface.go

This change allows the caller to specify a driver when loading an fsmonitor, or they can specify "any" to try to load fanotify but fallback to inotify if it fails.

Remove fanotify warning on ubuntu pro fsmonitor initialisation

---

lxd/main_forknet.go

Closes https://github.com/lxc/incus/issues/385
(cherry picked from commit 61a7f3237527ac8736ed3267c8e237da4174ed34, pr: https://github.com/lxc/incus/pull/1100)

lxd/forknet: Handle wifi detach (from Incus)

---

client/doc.go
doc/howto/instances_create.md
doc/howto/instances_routed_nic_vm.md
doc/rest-api.yaml
lxc/config/default.go
shared/api/image.go
shared/api/instance.go
test/suites/remote.sh

Of the 4 builtin remotes, 2 don't have a trailing `/`:
```
$ lxc remote list -f csv | awk -F, '/^ubuntu/ {print $2}' | grep -v /$
https://cloud-images.ubuntu.com/releases
https://cloud-images.ubuntu.com/daily
```
They should probably have one to avoid a permanent redirection (301):
```
$ wget -qSO /dev/null https://cloud-images.ubuntu.com/releases 2>&1 | grep -E 'HTTP/|Location'
HTTP/1.1 301 Moved Permanently
Location: https://cloud-images.ubuntu.com/releases/
HTTP/1.1 200 OK
$ wget -qSO /dev/null https://cloud-images.ubuntu.com/daily 2>&1 | grep -E 'HTTP/|Location'
HTTP/1.1 301 Moved Permanently
Location: https://cloud-images.ubuntu.com/daily/
HTTP/1.1 200 OK
```

Add trailing `/` to `ubuntu:` and `ubuntu-daily:` remotes to avoid redirects

---

.github/workflows/security.yml

This adds two jobs to our workflows. One uses Trivy to scan LXD's dependencies and the other scans the snap.

Trivy vulnerability scanning

---

client/interfaces.go
client/lxd_server.go
lxc/completion.go
lxc/config.go
lxc/console.go

Resolves https://github.com/canonical/lxd/issues/14098.
All the improvements made to the `lxc config get/set` completions have been tested locally. I made a minor change that deviates from the requirements outlined in https://github.com/canonical/lxd/issues/14098. Instead of typing `lxc config get foo:core.<tab>` to retrieve server configuration options, typing `lxc config get foo: core.<tab>` (notice the [SPACE]) will now return server configuration options. This change was implemented to differentiate from the conventional usage of `remote:instance` across the CLI. However, please let me know if you'd prefer server configuration completions without the [SPACE] 😄.

lxc: Add completions for server keys and console

---

doc/metadata.txt
lxd/instance/instancetype/instance.go
lxd/metadata/configuration.json

It looks like `volatile.cloud_init.instance-id` should actually be `volatile.cloud-init.instance-id` on [this page](https://documentation.ubuntu.com/lxd/en/latest/reference/instance_options/#instance-volatile:volatile.cloud_init.instance-id). I found a few other references in a grep of the code base.

Fix cloud-init instance key typos

---

lxc/completion.go
lxc/config/remote.go
lxc/exec.go
lxc/project.go

`strings.Cut()` is a wrapper around `stringslite.Cut()`: https://cs.opensource.google/go/go/+/refs/tags/go1.23.1:src/internal/stringslite/strings.go;l=108
`strings.SplitN()` is a wrapper around `strings.genSplit()`: https://cs.opensource.google/go/go/+/refs/tags/go1.23.1:src/strings/strings.go;l=236
The former (`strings.Cut()`) seems to be slightly more efficient as it doesn't do any slice allocation.

Use `strings.Cut()` where appropriate.

---

lxd/auth_groups.go
lxd/db/cluster/auth_groups.go
lxd/db/cluster/entity_type_certificate.go
lxd/db/cluster/entity_type_identity.go
lxd/identities.go
lxd/identity/util.go
lxd/patches.go
lxd/patches_test.go
test/suites/auth.sh

This PR redefines the `identity` and `certificate` entity types such that a `certificate` is considered to be any existing certificate type (e.g. client, metrics, server) and an `identity` is any identity whose permissions are managed via group membership.
Closes #13372 
Opening as draft as I would like to perform more testing on the patch before merging.

Auth: Redefine identity certificate entity types to prevent overlap

---

lxc/completion.go
lxc/config_device.go

Fixes https://github.com/canonical/lxd/issues/14138
Adds shell completions for `lxc config device add`:
- `lxc config device add [TAB]` shows all possible devices; and
- `lxc config device add <device> [TAB]` shows all possible device options.
Shell completions for `lxc config device get/set/unset` are unchanged, as they currently return set config options from either the config or profile (whichever exists), and I think it makes sense to keep it this way. Please let me know if you have any suggestions 😄

Add shell completions for `lxc config device`

---

lxc/completion.go

Fixes https://github.com/canonical/lxd/issues/14189

lxc/completion: Update instance completions to not show server configs

---

lxc/action.go
lxc/completion.go
lxc/delete.go
lxc/exec.go
shared/api/status_code.go

This PR includes improvements to `cmpInstances()`:
lxc pause|stop|exec <tab> completes RUNNING instances
lxc stop --force <tab> completes RUNNING|FROZEN instances
lxc start <tab> completes STOPPED|FROZEN instances
lxc delete <tab> completes STOPPED instances
lxc delete --force <tab> completes ALL instances
Resolves https://github.com/canonical/lxd/issues/14198

lxc/completions: Improvements to completions for `lxc action`, `lxc delete` and `lxc exec`

---

lxd/devices.go

`min()` is builtin since Go 1.21, https://tip.golang.org/ref/spec#Min_and_max

lxd/devices: use builtin `min()`

---

.github/workflows/security.yml

This renames a few steps names and, most importantly, fixes the vulnerability database caching.
The database caching is updated every run and is used for all snap scanning jobs in that run.
We had to drop the [`trivy-action`](https://github.com/aquasecurity/trivy-action) for the use of `cache-dir` to be effective and for us to be able to point to the right directory when downloading and using Trivy's vulnerability database.

Improve Trivy scanning

---

test/suites/backup.sh

In CI, untar'ing backups lead to those warnings about time discrepancies:
```
+ tar -xzf /home/runner/work/lxd/lxd/test/tmp.yy0/T5U/testvol.tar.gz -C /home/runner/work/lxd/lxd/test/tmp.yy0/T5U/non-optimized
tar: backup/index.yaml: time stamp 2024-10-04 13:47:24 is 0.053552327 s in the future
tar: backup/volume-snapshots/test-snap0/test: time stamp 2024-10-04 13:47:24 is 0.053404079 s in the future
tar: backup/volume-snapshots/test-snap0: time stamp 2024-10-04 13:47:24 is 0.053373382 s in the future
tar: backup/volume-snapshots/test-snap1/test: time stamp 2024-10-04 13:47:24 is 0.053263225 s in the future
tar: backup/volume-snapshots/test-snap1: time stamp 2024-10-04 13:47:24 is 0.053238839 s in the future
tar: backup/volume/test: time stamp 2024-10-04 13:47:24 is 0.053151806 s in the …
```

test/suites/backup: ignore time discrepancies when untar'ing

---

test/suites/pki.sh

There was a test failure when I last pushed #14207 (https://github.com/canonical/lxd/actions/runs/11183415209/job/31092412149#step:12:64275) that led to me noticing a few things we could do better in this test:
1. When asserting that a truststore entry is added, we should grep for exactly what we expect (e.g. more than just the common name).
2. When asserting that a truststore entry has not been added, we shouldn't grep for anything (nothing to grep for, also what if a truststore entry is added with a name we don't expect). We should check that the number of entries is what is expected.
3. When in the subshell, we always should be talking to the LXD running in `LXD5_DIR`. The setting of `LXD_DIR="${LXD5_DIR}"` preceding a command was missed in some cases, meaning that we were checking the …

PKI test improvements

---

lxd/storage/drivers/driver_powerflex.go
lxd/storage/drivers/driver_powerflex_utils.go

This allows showing the actual usable storage capacity after PowerFlex interal data duplication.
Furthermore the factor is changed to 1024 as the returned value is in KiB and not KB as suggested by the name of the variables. The values are now identical to what is reported in PowerFlex UI even though in the UI the units are written in TB/GB instead of TiB/GiB:

Storage: Use the `Net*` response variables for PowerFlex pool stats

---

.github/workflows/codeql.yml

The repo has very few lines of python codes and they are all related to testing bits that very rarely change. Not worth spending ~1300 minutes of CI per month.

github: stop scanning Python through CodeQL

---

doc/custom_conf.py

`sphinx-tabs` version 3.4.7 was released addressing the root cause so we no longer need to ignore those warnings.

Remove workaround for sphinx-tabs warnings

---

.github/workflows/tests.yml

This reverts commit 2acc480e4926697a61931ae57a8b14a173290fce now that https://github.com/actions/upload-artifact/releases/tag/v4.4.2 contains a fix.

Revert "github: Workaround GHA download artifact bug"

---

lxc/completion.go

Resolves https://github.com/canonical/lxd/issues/14209.

lxc/completion: Add `images` and `ubuntu` remote completions

---

lxd/apparmor/rsync.go

The `CAP_SYS_ADMIN` cap is required for rsync to write to files using security.* xattrs. In order to preserve these xattrs and ensure proper updates when these xattrs are present, we must include this capability in the rsync AppArmor profile.
Related: https://github.com/canonical/lxd/issues/13707.

lxd: Include CAP_SYS_ADMIN in rsync AppArmor profile

---

.github/workflows/codeql.yml

Suggested-by: Thomas Parrott <thomas.parrott@canonical.com>

github: only run CodeQL (go) on PRs and on weekly schedule

---

lxd-user/callhook/callhook.go
lxd-user/main.go
lxd-user/main_callhook.go
lxd/main_callhook.go

- Adds ability for lxd-user to handle container stop hook requests.
- Uses a context rather than a go routine for 30s timeout.
- Adds `callhook` package used from both `lxd-user` and `lxd` to avoid duplication.
- Uses URL builder rather than crafting URLs manually.
Related to https://github.com/canonical/lxd/issues/13331
Depends on https://github.com/canonical/lxd-pkg-snap/pull/564

lxd-user: Add callhook support for container stop hooks

---

lxd/tokens.go

This task is running every minute but doesn't need to, because token expiry is checked at the time of use. Additionally, a comment where the task is added to the daemon specifies that it runs hourly.

lxd: Change token pruning task to hourly.

---

.github/actions/install-trivy/action.yml
.github/workflows/security.yml

This introduces a new GitHub action for installing Trivy using the deb package as a workaround to properly cache Trivy's vulnerability database.

Install Trivy with GitHub action

---

shared/util_linux.go
test/suites/exec.sh

With this, processes spawned by `lxc exec` stopped due to being signaled now return the proper exit code to LXD.
From the [docs](https://pkg.go.dev/os#ProcessState.Sys):
> Sys returns system-dependent exit information about the process. Convert it to the appropriate underlying type, such as [syscall.WaitStatus](https://pkg.go.dev/syscall#WaitStatus) on Unix, to access its contents.

lxc exec: Fix exit codes for signaled processes 

---

test/suites/container_devices_nic_bridged_filtering.sh

Also avoid forking `grep` to read read from `/proc`.

test/container_devices_nic_bridged_filtering: unload br_netfilter once done

---

lxc/completion.go
lxc/storage.go
lxc/storage_volume.go

Fixes https://github.com/canonical/lxd/issues/14264.
This PR also replaces the use of `Sprintf()` with string concatenation where possible, and adds go doc comments to all completion functions.

lxc/completion: `lxc storage volume copy` shell completion fixes and improvements to `completions.go`

---

lxd/network/driver_ovn.go

This PR adds support for OVN uplink networks attached to a VLAN. The implementation details closely track https://github.com/canonical/lxd/issues/12234#issuecomment-2379005076.
Testing here: https://github.com/canonical/lxd-ci/pull/302.
Closes https://github.com/canonical/lxd/issues/12234.

Network: Add support for OVN uplink networks attached to a VLAN

---

lxd/metrics/api_rates.go
lxd/operations/response.go
lxd/response/response.go

Recently we are getting unwanted API metrics logging on the LXD agent, MicroCloud and MicroCluster.
As a fix, this PR removes the logging logic, as it is not needed since https://github.com/canonical/lxd/pull/14228. We are now typing the endpoints manually and checking if all the appropriate endpoints are typed.
This also fixes handling communication errors for the metrics, to not let those errors affect the request result.

Improve API metrics logging

---

lxd/firewall/drivers/drivers_nftables_templates.go
lxd/firewall/drivers/drivers_xtables.go

In case `br_netfilter` is loaded on the host all traffic is also passing the respective postrouting chain. This leads to false masquerading of multicast traffic if the traffic stays within the network.
An investigation on the traffic passing the `pstrt.{network name}` chain of a LXD managed bridge surfaced the following behavior:
> INFO: In the examples `wlp0s20f3` is my uplink nic and the traffic is generated between two VMs attached to `lxdbr0`.
1) `br_netfilter` enabled:
* multicast traffic shows the following attributes: `IN= OUT=lxdbr0 PHYSIN=tapc938f176 PHYSOUT=tap48ceb22c`
* unicast traffic shows this attributes: `IN=lxdbr0 OUT=wlp0s20f3 PHYSIN=tapc938f176`
2) `br_netfilter` disabled:
* multicast traffic doesn't show up
* unicast traffic shows this attributes: `IN=lxdbr0 …

Firewall: Don't masquerade multicast traffic

---

lxd/network/driver_ovn.go

We can allow IPv6 subnets smaller than /64 for the case when stateful DHCPv6 is used or DHCP is completely disabled.
Suggested-by: Thomas Parrott <thomas.parrott@canonical.com>
See also:
https://github.com/canonical/lxd-ci/pull/321
https://github.com/canonical/lxd/pull/14276

Network: Allow OVN subnets smaller than /64 when stateful DHCPv6 is enabled

---

lxc/completion.go
lxc/storage_volume.go

This PR partially fixes https://github.com/canonical/lxd/issues/14264. I'll spend some more time trying to figure out why the completions generated during the snap build include an erroneous space, but a fix for that will likely land in the lxd snap repo.

`lxc storage volume copy/move` shell completion fixes

---

.github/workflows/security.yml

The GitHub UI trims long names like this:
> Trivy vulnerability scanner - Rep...
> Trivy vulnerability scanner - Sna...
> Trivy vulnerability scanner - Sna...
> Trivy vulnerability scanner - Sna...
> Trivy vulnerability scanner - Sna...
Since the workflow title already makes it clear that Trivy is a vulnerability scanner, there is no need to repeat it.

github: use shorter job names for Trivy scanning

---

doc/api-extensions.md
shared/version/api.go

This PR adds API extension `network_ovn_uplink_vlan`, which adds support for using a bridge network with a specified VLAN ID as the uplink for an OVN network.
Related: https://github.com/canonical/lxd-ci/pull/302, https://github.com/canonical/lxd/pull/14196.

api: Add network_ovn_uplink_vlan API extension

---

lxd/network/driver_bridge.go
lxd/network/network_utils.go

During cherry-pick from Incus of refactor of this function in e5f5b887ae11d50f9b6bb99df2a008d2edd6e4e9 the project filtering logic was incorrectly returning rather than continuing to next instance.
This meant some instances were being excluded incorrectly.
Also fixes a potential issue with concurrent modification of the leases slice in `bridge.Leases()` when collecting leases from each cluster member concurrently.
Fixes https://github.com/canonical/lxd/issues/13412

Networt: Fix incorrect handling of instances in UsedByInstanceDevices

---

doc/explanation/authorization.md
doc/howto/snap.md
doc/installing.md
doc/reference/remote_image_servers.md
doc/reference/uefi_variables.md

This PR explicitly specifies the link text for Discourse posts (from the posts' titles) instead of extracting it at build time. Recent Discourse outages have caused build failures when the link text couldn't be fetched dynamically. Hard-setting the link text should prevent this.
**Note:** Docs on specifying link text [here](https://github.com/canonical/canonical-sphinx-extensions/?tab=readme-ov-file#specify-links-for-a-page). The docs also describes a backup link text option, but I did not use it due to buggy behavior. _My expectation:_ The backup link text will be used if the link text cannot be extracted dynamically, and the build will not fail. _Reality:_ The backup link text is recognized, yet the build still fails.

doc: embed discourse post title as link text

---

doc/rest-api.yaml
lxd/api_1.0.go
lxd/api_cluster.go
lxd/auth_groups.go
lxd/certificates.go
lxd/cluster/member_state.go
lxd/cluster/member_state_test.go
lxd/cluster/notify.go
lxd/cluster/notify_test.go
lxd/cluster/upgrade.go
lxd/daemon.go
lxd/db/node.go
lxd/identities.go
lxd/identity_provider_groups.go
lxd/images.go
lxd/network/acl/driver_common.go
lxd/network/driver_bridge.go
lxd/network/driver_common.go
lxd/network/driver_ovn.go
lxd/network/zone/zone.go
lxd/networks.go
lxd/profiles.go
lxd/scriptlet/instance_placement.go
lxd/state/testing.go
lxd/storage_pools.go
shared/api/cluster_state.go

This includes preparatory changes as described in #14247:
- Notifier improvements
- Use `state.ServerClustered`
- Don't query for `OfflineThreshold` unless needed (see commit msg)
- Allow passing `db.NodeInfo` to `NewNotifier`
- Pass `db.NodeInfo` to the notifier hook to reduce the need for extra http calls for basic info (like the target server's name)
- Member state updates
- Add `CPUThreads` to `ClusterMemberSysInfo` (name tbd)
- Refactor `MemberState` to expose local `ClusterMemberSysinfo`
- Implement helper to collect member state from all cluster members, using the notifier improvements above
- Other odds and ends
Performance improvements for project limits will be in a separate PR.

Notifier update; MemberState update

---

doc/howto/projects_confine.md

doc/howto: Fix argument order when adding permissions to a group.

---

doc/installing.md
doc/reference/remote_image_servers.md

- Cherry-picked update to doc/installing.md from #14295
- Updated doc/reference/remote_image_servers manually per different links set from main branch
- The three other Discourse links in main branch not backported per the pages do not exist in stable-5.0

doc: embed discourse titles as link text (stable-5.0)

---

lxd/api_internal_recover.go
lxd/backup/backup_config_utils.go
lxd/db/cluster/instances.go
lxd/db/cluster/profiles.go
lxd/db/instances.go
lxd/db/profiles.go
lxd/instance_patch.go
lxd/instance_post.go
lxd/instance_put.go
lxd/instances_post.go
lxd/network/acl/acl_load.go
lxd/network/network_utils.go
lxd/profiles.go
lxd/project/limits/permissions.go
lxd/storage/storage.go
lxd/storage/utils.go

Improves listing profiles/instances by caching some data on the entities and making DB queries way more efficient.
Contains cherry picks from https://github.com/lxc/incus/pull/1140 and https://github.com/lxc/incus/pull/1314.
@MggMuggins

Profiles & instance listing efficency improvements (from Incus)

---

lxd/api_cluster.go

This PR makes a small update to `evacuateInstances`, so that we provide the given project's restricted cluster groups in the call to `tx.GetCandidateMembers` for each instance.
Closes https://github.com/canonical/lxd/issues/14280.

lxd: Consider project's restricted cluster groups during instance evacuation

---

lxd/api_cluster.go

This was noticed in MicroCloud. When removing a node from the LXD cluster, and then adding it back to the cluster, the old `core.https_address` and `cluster.https_address` are preserved.
When handling the request, LXD will attempt to use the `core.https_address` value and apply it to `cluster.https_address`, but if this value is a wildcard, we should continue with the explicit address defined under `ServerAddress` in the request body.

lxd: Use explicit cluster addr when core addr is wildcard

---

.github/workflows/tests.yml

This simplifies the go version setting to automatically match that of the go mod version.
The removal of the go version matrix is ineffectual as it was already effectively removed when we switched to the 2-stage build + system test pattern, where LXD is only built once.
The snap tests do use the later versions of Go that LXD snap is built with. And the system tests in this repo check our support of the go mod minimum Go version.

Github: Use go mod version of go

---

.github/actions/setup-microceph/action.yml

This avoids getting 404 when trying to install packages that were superseded by updates:
```
+ sudo apt-get install --no-install-recommends -y ceph-common
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
libbabeltrace1 libboost-context1.83.0 libboost-filesystem1.83.0
libboost-iostreams1.83.0 libboost-program-options1.83.0
libboost-thread1.83.0 libcephfs2 libdaxctl1 libgoogle-perftools4t64
libndctl6 liboath0t64 libpmem1 libpmemobj1 librados2 libradosstriper1
librbd1 librdmacm1t64 libtcmalloc-minimal4t64 python3-ceph-argparse
python3-ceph-common python3-cephfs python3-prettytable python3-rados
python3-rbd python3-wcwidth
Suggested packages:
ceph ceph-mds
The following NEW packages will be installed: …
```

github: update apt definition in setup-microceph

---

doc/api-extensions.md
doc/metadata.txt
doc/reference/instance_options.md
lxd/cgroup/cgroup_cpu.go
lxd/devices.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/instance_utils.go
lxd/instance/instancetype/instance.go
lxd/metadata/configuration.json
shared/validate/validate.go
shared/version/api.go
test/suites/config.sh

Fixes https://github.com/canonical/lxd/issues/14133.
This pull request introduces a configuration option for virtual machines, `limits.cpu.pin_strategy`. This option allows users to specify the strategy for CPU auto pinning. The possible values are `none` (disables CPU auto pinning - also the new default) and `auto` (enables CPU auto pinning).
For reference when back-porting: https://github.com/canonical/lxd/pull/13670/commits/56bd496649a8c044e41272acae5ef693d3b48712

Add `limits.cpu.pin_strategy` setting to disable VM CPU auto pinning by default

---

lxd/api_cluster.go
lxd/db/cluster/nodes_cluster_groups.go
lxd/db/cluster/nodes_cluster_groups.mapper.go
test/suites/clustering.sh

This PR fixes cluster group creation when multiple nodes are present in the request. This is currently failing due to an incorrect check for existing mappings in the `nodes_cluster_groups` table. This is due to the `NodeClusterGroups` struct not properly matching the backing table. To fix this, we ensure the `NodeClusterGroups` uses the `primary` directive where necessary.
Fixes https://github.com/canonical/lxd/issues/14286.

lxd: Fix cluster group create when >1 node is defined in the request

---

lxd/api_cluster.go

(cherry picked from commit 2a3a7052ebfb716bc420c865e3a96355eb12d88b)

lxd: Use explicit cluster addr when core addr is wildcard (stable-5.21)

---

lxd/db/instances.go
lxd/project/limits/permissions.go

Follow-up to #14315
This tidies up the queries used for project limits checking; it likely results in improved performance for clusters with many entities.

Project limits: Use `InstanceList`

---

lxd/apparmor/instance_forkproxy.go
lxd/apparmor/instance_qemu.go
lxd/apparmor/network_forkdns.go

Related to https://github.com/canonical/lxd-pkg-snap/pull/564 and https://github.com/canonical/lxd/issues/13331

lxd/apparmor: Update with new lxd binary location in sbin

---

lxd/device/cdi/configure.go
lxd/device/cdi/id.go

Adding a GPU with `nvidia.com/gpu=all` was actually not adding any physical card devices. This should fix it. With 'all', we should make the difference between CDI device index that are integer and the ones represented by a UUID that could contain the same cards. For example, these two devices are identical (target the same resources) though not named with the same convention:
```
[
{
"name": "0",
"containerEdits": {
"deviceNodes": [
{
"path": "/dev/nvidia0",
"hook",
"create-symlinks",
"--link",
"../card1::/var/lib/snapd/hostfs/dev/dri/by-path/pci-0000:01:00.0-card",
"hook",
"create-symlinks",
"--link",
"../card1::/var/lib/snapd/hostfs/dev/dri/by-path/pci-0000:01:00.0-card",
"--link",
"../renderD128::/var/lib/snapd/hostfs/dev/dri/by-path/pci-0000:01:00.0-render"
]
},
{
"hookName": …
```

lxd/device/cdi: Fix the case of adding a CDI device with the 'all' identifier

---

lxd/network/driver_common.go
lxd/network/driver_ovn.go

This PR updates `ovn.ovnNetworkExternalSubnets` to consider the volatile IP of each OVN network using a given uplink. This is added to prevent the use of one OVN network's volatile IP on another OVN network, namely in the cases of creating network forwards and IP passthrough.

Network: Consider volatile IP in ovnNetworkExternalSubnets

---

lxc/completion.go
lxc/config.go
lxc/profile.go

This PR adds `cmpInstanceAllKeys()` to provide all possible instance config keys for `lxc profile set <profile>` completions. Function names and go doc comments have also been reworded for clarity.
Resolves: https://github.com/canonical/lxd/issues/14370.

lxc/completion: Rework instance config key completion functions

---

lxd/images.go

This small PR removes the duplicated logic in the `imageDeleteFromDisk` function.

lxd: Deduplicate logic for deletion of main image file

---

lxc/console.go

closes https://github.com/canonical/lxd/issues/14241

lxc: Handle sigkill in `vga()` properly to clean spice sockets and avoid accumulating them

---

lxd/acme.go
lxd/api_cluster.go
lxd/api_internal.go
lxd/daemon.go
lxd/db/cluster/identities.go
lxd/identities.go
lxd/images.go
lxd/instance_post.go
lxd/instances_post.go
lxd/operations.go
lxd/patches.go
lxd/state/state.go
lxd/tokens.go
test/suites/auth.sh
test/suites/remote.sh

As part of the [TLS fine-grained authorization specification](https://discourse.ubuntu.com/t/tls-fine-grained-authorization/48497), pending TLS identities must be pruned when their associated token expires. This pull request adds logic to the `autoRemoveExpiredTokens` task such that the leader will retrieve all the pending TLS identities and delete those that have expired. Non-leaders will continue to cancel "certificate add" and "cluster join" operations in-memory in each member.
There was a lot of duplication of logic to identify the database leader. This PR adds a method to `Daemon` and `State` to determine if the member is a leader and refactors existing code to use that method. If the Daemon is standalone it is considered to be the leader. It is the responsibility of the caller to …

Auth: Prune pending TLS identities

---

lxd/device/cdi/spec_unsupported.go

Compilation fails on armhf without this change.

Device: Update CDI generateSpec signature

---

lxd/instance/drivers/driver_lxc.go

Addresses https://github.com/canonical/lxd-ci/pull/135#issuecomment-2345508827

Log some errors as warnings

---

doc/howto/cluster_form.md
doc/howto/cluster_recover.md
lxd/cluster/gateway.go
lxd/cluster/gateway_test.go
lxd/cluster/info.go
lxd/cluster/recover.go
lxd/db/db.go

The Dqlite LTS provides a new API [`ReadLastEntryInfo`](https://pkg.go.dev/github.com/canonical/go-dqlite/v2#ReadLastEntryInfo) to provide the raft term and index of a dqlite db on disk. This allows us to be more precise with the definition of "most up-to-date cluster member" in the recovery docs.

db: Print last dqlite entry

---

doc/.sphinx/.markdownlint/exceptions.txt
doc/howto/import_machines_to_instances.md

Clarify examples of how to convert Windows disk image to a raw format with the necessary drivers. In addition, provide an explicit example for VMDK format (in addition to qcow2 and VMX).

docs: Improve Windows image conversion examples

---

lxd/network/driver_common.go
lxd/network/driver_ovn.go

Since we would like to prevent the use of one OVN network's volatile IP on another OVN network, we should consider this when retrieving external subnet information during validation.

Prevent use of one OVN network's volatile IP on another OVN network (stable-5.0)

---

lxd/device/gpu_physical.go

closes https://github.com/canonical/lxd/issues/14372

Device: Forbid any `nvidia.*` instance config option if the GPU device has been added through the CDI mode

---

lxd-agent/devlxd.go
lxd-agent/events.go
lxd-agent/server.go
lxd-agent/sftp.go
lxd/api.go
lxd/api_cluster.go
lxd/api_internal.go
lxd/auth/oidc/oidc.go
lxd/cluster/notify_test.go
lxd/daemon.go
lxd/devlxd.go
lxd/events.go
lxd/instance_sftp.go
lxd/operations.go
lxd/operations/response.go
lxd/operations/websocket.go
lxd/response/response.go

This backports the necessary commits into `stable-5.21` that allow passing the request into the response `Render` func.
See https://github.com/canonical/microcluster/pull/277#issuecomment-2459421554 for the origin of this request.

Pass request to `Render` backport (stable-5.21)

---

.github/workflows/security.yml

This updates the Trivy workflow to cache the vulnerability database when the download is successful and, when it is not, use the latest cached database instead. Motivated by some failures seen on some recent runs: https://github.com/canonical/lxd/actions/runs/11603622604/job/32310941454

github: Use cache when Trivy DB download fails

---

doc/metadata.txt
lxd/metadata/configuration.json
lxd/network/driver_ovn.go

- fix OVN ipv4/6 address description, this was wrongly referencing a "bridge"

Docs: Fix ovn ipv4/6 address description

---

doc/metadata.txt
lxd/instance/drivers/driver_qemu.go
lxd/instance/instancetype/instance.go
lxd/metadata/configuration.json

#13878 Added `security.devlxd.images` for virtual machines but this key was not live-updatable. There was no particular reason for this. The endpoint is always available in the LXD agent and access is restricted by the host daemon.
This PR allows the config key to be set while the instance is running.
Closes #14206

Make `security.devlxd.images` live-updatable for VMs

---

lxc/init.go
test/suites/clustering.sh

In LXD init, if the `--storage` or `--network` flags are provided the CLI will check the storage pool or network exists before setting up a device on the instance config. When targeting a cluster group this would lead to calls like `GET /1.0/storage-pools/foo?target=@bar` which doesn't make sense. 
This commit (cherry-picked from Incus) moves setting the cluster group target to after those lookups.
I've added tests have checked that they fail before this change and pass afterwards.

Set Target after network/storage lookup (from Incus)

---

lxd/networks.go

Adds a missing lifecycle event on creation of cluster wide networks (e.g. when one is created first on a per member basis).

lxd/networks: Emit lifecycle event for OVN networks (from Incus)

---

lxd/auth/drivers/openfga.go

While working on https://github.com/canonical/lxd/issues/14085 I set up a new fine-grained TLS identity and issued the following commands as that identity, without any permissions yet (I forgot I'd changed my default remote):
```
$ lxc auth group create tmp
Error: Forbidden
$ lxc auth group permission add tmp server admin
Error: Failed to check OpenFGA relation: No such entity "/1.0/auth/groups/tmp"
```
Creating the group failed, this is correct behaviour. 
When attempting to add a permission to the non-existent group, the request failed (correct) but the OpenFGA Authorization driver returned the above error. This is incorrect.
This PR checks if the error returned by a `Check` request on the embedded OpenFGA server is a `Not Found` error and returns a generic not found error. This makes …

Auth: Mask errors returned by OpenFGADatastore

---

doc/rest-api.yaml
lxd/certificates.go
lxd/db/cluster/identities.go
lxd/identities.go
shared/api/auth.go
test/suites/auth.sh

Implements the final part of the TLS fine-grained auth specification. This allows any user to update their own certificate, as well as allowing an administrator with `can_edit` on a given identity to update the certificate for that identity.

Auth: Allow updating TLS identity certificates

---

test/includes/lxc.sh
test/suites/auth.sh
test/suites/basic.sh
test/suites/remote.sh

The `gen_cert` util had a weird side-effect if I was concurrently running a LXD snap with OIDC configured. (I realise that there can be some test failures when doing this related to networks etc. but I do it regularly when running a single suite as I'm often using the snapped LXD for something else). I've put more details in the commit messages.
Additionally simplifies the `user_is_server_admin` function in the fine-grained auth tests.

Tests: Remove `gen_cert` util

---

.github/workflows/security.yml

A github cache can not be updated using the same key, so instead we update using a different key each time but use the same key to restore it.
This also fixes the snap scanning that was broken on a recent update to the workflow.

github: Fix database cache update

---

doc/howto/initialize.md

Fixes a broken link that's causing causing [a test to fail](https://github.com/canonical/lxd/actions/runs/11769759482/job/32781226116).

Doc: Fix broken link to maas docs

---

lxc/remote.go

When adding a remote by putting the token in the positional argument (not `--token`) also check if the server supports the `explicit_trust_token` extension and send the password using the `TrustToken` field instead.
This seems to be fixed already in [`main`](https://github.com/canonical/lxd/blob/main/lxc/remote.go#L271).

lxc: Use TrustToken field if supported by the server (stable-5.21)

---

.github/workflows/tests.yml

To align with expectations of microcloud 2.x LTS to be used with microceph squid.

github: Use squid/candidate for microceph (stable-5.21)

---

.github/workflows/triage.yml

> Heads up @foo - the "Documentation" label was applied to this issue.

github: stop adding notification comments to issues/PRs

---

lxd/instance/drivers/driver_common.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go

If an instance self-stops while `statusCode()` is waiting for `getLxcState()` to finish, `statusCode()` may return a stale instance state.
This PR is a workaround for the use-case in #13453 and significantly reduces the likelihood that `statusCode` returns a stale status.
In an ideal world, LXD would maintain a canonical cluster-wide view of instance state. This would allow making race-free decisions based on whether an instance is running or not. For example:
- Project CPU/RAM limits could be enforced at instance start instead of at instance creation
- Volumes with content-type block could be attached to more than one instance without `security.shared`; instance start could fail if another instance with any shared block volumes is already running.

Workaround container self-stop race

---

lxc/main.go

The completion command is a useful tool that includes detailed instructions for setting up completions across shell environments. Most CLI applications don't hide this by default so it's quite intuitive for a user to locate/use this command. Furthermore, the LXD snap completions are only set up for Bash shells.
With this change, running `lxc completion <shell> --help` shows instructions on generating completions.

lxc/completion: Don't hide default completion command

---

doc/metadata.txt
doc/reference/devices_unix_block.md
doc/reference/devices_unix_char.md
doc/reference/devices_unix_hotplug.md
lxd/device/unix_common.go
lxd/device/unix_hotplug.go
lxd/metadata/configuration.json

Resolves https://github.com/canonical/lxd/issues/14451.

Update device option descriptions to accurately convey compatibility with containers and VMs

---

lxd/instance/drivers/driver_qemu.go

Two commits were identified as potential imports in https://github.com/canonical/lxd/issues/13311:
The first commit adds a function `blockNodeName` which hashes block node names if they exceed 31 characters. The second commit applies the node name overflow function when adding a QEMU config to a drive.
@simondeziel pointed out that we already have a function `qemuDeviceNameOrID` so this PR just adds missing node name overflow handling.

VM: Add missing `disk` block node name overflow handling

---

.github/workflows/tests.yml

Sometimes it needs to modify them.
Related to fixing tests on https://github.com/canonical/lxd/pull/14388

github: Move chmod of go.mod, go.sum before go mod download

---

.github/workflows/tests.yml

There is no real speed benefit to stripping and no known downside to keeping debug symbols. The only minor change is going to be bigger cached artifacts.
On the plus side though, having debug symbols will make crash investigations much easier.

github: stop stripping libs and binaries

---

doc/metadata.txt
lxd/instance/instancetype/instance.go
lxd/metadata/configuration.json

- fix defaultdesc format for instance configuration related to boot for the documentation and metadata api

doc: fix defaultdesc format for instance configuration related to boot

---

.github/workflows/security.yml

Although we are now resilient to failures from the Trivy server by using our cache, we are still using an older version of the cache, so this assures we are always using the latest by using the `restore-keys` option appropriately.

github: Always use the latest Trivy database cache

---

.github/actions/reclaim-disk-space/action.yml

When using this action on the Canonical runners (e.g. MicroCloud) we cannot purge the aproxy snap as it is a critical component to ensure connectivity between the runner and GitHub. Removing it will cause the runner to hang up.
See [this](https://github.com/canonical/microcloud/actions/runs/11934150325/job/33262745369) job for an example. The error message is something like the following:
```
The self-hosted runner: openstack-amd64-large-ps6-3-c9077065b675 lost communication with the server. Verify the machine is running and has a healthy network connection. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.
```

GitHub: Don't purge aproxy snap when reclaiming disk space

---

.github/workflows/tests.yml

Sets `GOTRACEBACK=crash` as a follow up to #14499 because in @mihalicyn's words
> yeah, as withoutGOTRACEBACK="crash" we won't get a coredump at all, as golang runtime handles segfaults gracefully and Linux kernel won't realize that coredump collecting is required.

github: Set `GOTRACEBACK=crash` on system test runs.

---

doc/.custom_wordlist.txt
doc/api-extensions.md
shared/version/api.go

Add an API extension for adding the CDI mode for GPU passthrough (see https://github.com/canonical/lxd/pull/13562)

api: Add `gpu_cdi` extension

---

go.mod
lxd/instance/drivers/qmp/commands.go

This reverts commit cbffaf10d16687f19efe69f472db285163b701c5 from https://github.com/canonical/lxd/pull/14479
It breaks various tests.

Revert "lxd/instance/drivers/qmp: Return an error if no fd is found"

---

doc/metadata.txt
lxd/metadata/configuration.json
lxd/storage/utils.go

cephfs does not support block volumes, thus `security.shared` does not apply to it.
Closes https://github.com/canonical/lxd/issues/14534

lxd/storage: Remove `security.shared` from cephfs keys

---

lxc/completion.go
lxc/config.go
lxc/profile.go

This PR includes updates to `lxc/completion.go`, improving the shell completion functionality for instance configuration keys. 
- Refactorings that improve performance and correctness;
- Updates `cmpInstanceKeys` and `cmpInstanceAllKeys` functions to use the metadata API (resolves https://github.com/canonical/lxd/issues/14537);
- Adds `cmpInstanceSetKeys` function for improved `lxc config unset` completions.

CLI: Improvements to `lxc config` and `lxc profile` shell completions

---

lxd/api_cluster.go
lxd/daemon.go
lxd/networks.go

This way a fresh copy of state can be retrieved on each iteration when
trying to start networks that couldn't be started on the first pass.
This helps in scenarios where the network couldn't be started due to
a problem with the server/cluster's global config that is rectified
and then the go routine running the retry mechanism needs to get an
updated copy of the global config before retrying starting the network.
Reorganises this function so that the scope of the initial setup attempt's
state variable is limited.

Network: Get fresh copy of global config when retrying network startup

---

lxd/instances_get.go

I noticed this `err` parameter was unused. So I had this idea of, instead of removing it, logging these erros, as the errors used with that function are currently not being disclosed to the user in any way. This way it is clear why one was not able to get info on that particular instance when looking in the logs. If this logging is not desirable, I will update the PR to just remove the unused parameter.

lxd: Log error on `resultErrListAppend`

---

lxd/device/unix_hotplug.go

Fixes 1/2 related issues raised in https://github.com/canonical/lxd/issues/14266. This fix has been tested locally with a USB hard disk and by @jonathan-conder with USB camera devices.
- Adds support for discovering multiple `unix-hotplug` devices which share the same `productid` and/or `vendorid`;
- Improves `productid` and `vendorid` matching logic;
- Resolves inconsistent device matching bug.

Device: Add support for discovering multiple `unix-hotplug` devices

---

doc/metadata.txt
lxd/device/tpm.go
lxd/device/usb.go
lxd/instance/instancetype/instance.go
lxd/metadata/configuration.json
lxd/network/driver_common.go
lxd/storage/drivers/driver_cephobject.go
lxd/storage/drivers/driver_powerflex.go

`validate.Optional()` checks if the provided value is not empty before calling the other validator.
As such, `validate.Optional(validate.IsNotEmpty)` is conceptually the same as `validate.IsAny`.
Also, since `validate.IsAny` accepts anything, using, `validate.Optional(validate.IsAny)` is conceptually the same as `validate.IsAny`.

Simplify config validation

---

client/interfaces.go
client/simplestreams_images.go
lxc/image.go

Fixes https://github.com/canonical/lxd/issues/14561 introduced with https://github.com/canonical/lxd/pull/14260.
This PR fixes a regression introduced with https://github.com/canonical/lxd/pull/14260 by adding `GetImagesAllProjects` and
`GetImagesAllProjectsWithFilter` functions to `client/simplestreams_images.go`, and moving their method signatures to
the `ImageServer` interface. While adding support for fetching images across all projects, we changed the logic in the `lxc image list` command to call different functions based on whether the `--all-projects` flag is passed in or not:
https://github.com/canonical/lxd/pull/14260/commits/1fae6e6d99d68538ae29f01937d4dfc8338bf923
This is fine, but we needed to add `simplestreams` protocol support as well to facilitate listing public images …

LXC: Fix `lxc image list` regression

---

doc/api-extensions.md
doc/metadata.txt
doc/rest-api.yaml
lxd/metadata/configuration.json
lxd/network/driver_bridge.go
lxd/network/driver_macvlan.go
lxd/network/driver_physical.go
lxd/network/driver_sriov.go
lxd/storage/drivers/driver_btrfs.go
lxd/storage/drivers/driver_ceph.go
lxd/storage/drivers/driver_ceph_volumes.go
lxd/storage/drivers/driver_cephfs.go
lxd/storage/drivers/driver_cephobject.go
lxd/storage/drivers/driver_lvm.go
lxd/storage/drivers/driver_lvm_volumes.go
lxd/storage/drivers/driver_powerflex.go
lxd/storage/drivers/driver_powerflex_volumes.go
lxd/storage/drivers/driver_zfs.go
lxd/storage/drivers/driver_zfs_volumes.go
lxd/storage/utils.go
shared/api/metadata_configuration.go
shared/version/api.go

Resolves https://github.com/canonical/lxd/issues/14125.
This PR adds `scope` to the metadata configuration API endpoint, `/1.0/metadata/configuration`.
- Adds api extension, `metadata_configuration_scope`;
- Adds `Scope` field to `MetadataConfigurationConfigKey` struct;
- Adds `scope` to metadata for member specific config keys in `lxd/network/driver_{bridge/macvlan/physical/sriov}.go`;
- Updates API docs and metadata.

API: Add `scope` to metadata configuration API

---

.github/workflows/codeql.yml

This reverts commit 9ab852f8803c252949543b12d3c9bc7db8606fea as the GHA runners log those 2 warnings:
> 1 issue was detected with this workflow: Please specify an on.push hook to
> analyze and see code scanning alerts from the default branch on the Security
> tab.
> Unable to validate code scanning workflow: MissingPushHook

Revert "github: only run CodeQL (go) on PRs and on weekly schedule"

---

doc/howto/import_machines_to_instances.md

Mention the noble package in the virt-v2v docs section.
I removed the note about `virtio-win` as the LP source package [is empty](https://launchpad.net/ubuntu/+source/virtio-win); if that package is accessible to customers or I'm missing something I'm happy to reintroduce that bit.
Doclint failures are `Bare URL` warnings because of the terminal output; not sure how to silence.

doc: Add noble package to Windows image conversion

---

README.md

We should link to the relevant LTS series docs in the LTS code branches.

README: Update references to latest documentation to stable-5.21 (stable-5.21)

---

test/suites/tls_restrictions.sh

This check is already performed in the `authorization` suite but isn't actually being performed in the `tls_restrictions` suite. We do already have unit tests that show that a restricted client certificate does not have `can_edit` on `server` (required for viewing server configuration), but this is a good thing to triple check.

test/suites: Check that a restricted client certificate cannot view server configuration

---

lxd/instance/instance_utils.go

Thanks to @escabo for reporting the issue where conversion fails if LXD is clustered and supports API extension `instance_import_conversion`.
Not sure how this slipped through for such a long time. Seems I have messed something up when juggling with commit order on initial implementation, as I remember configuring this.
Anyway, the issue is detection of suitable architecture, where source type was not matched with any case resulting in an error:
```
Error: Unknown instance source type "conversion"
```

Fix detection of suitable architecture for conversion when LXD is clustered

---

lxd/storage_pools_utils.go

Fixes https://github.com/canonical/lxd/issues/14046.
This PR adds a storage driver cache update to `storagePoolCreateLocal`. `storagePoolCreateLocal` is called in `storagePoolsPostCluster` and whenever a `storagePoolPost` request is a cluster notification.

Storage: Add storage driver cache update to `storagePoolCreateLocal`

---

lxd/cluster/connect.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/instance_utils.go
lxd/instance_get.go
lxd/instances.go
lxd/warnings.go
test/suites/clustering.sh

If not using recursion on `GET /1.0/instances/:instanceName`, almost all the instance information used in the response comes from the database. So when forwarding the request is not possible, fallback to reading the instance info from the node being queried. The only change is the response is the instance state, that in this case would show as Error since we can't determine the state of a remote instance.
closes https://github.com/canonical/lxd/issues/13698

lxd: Get config for instance on offline cluster member

---

lxd/scriptlet/instance_placement.go
lxd/storage/backend_lxd.go
lxd/storage/drivers/driver_btrfs.go
lxd/storage/drivers/driver_ceph.go
lxd/storage/drivers/driver_ceph_volumes.go
lxd/storage/drivers/driver_cephfs.go
lxd/storage/drivers/driver_common.go
lxd/storage/drivers/driver_dir.go
lxd/storage/drivers/driver_lvm.go
lxd/storage/drivers/driver_mock.go
lxd/storage/drivers/driver_powerflex.go
lxd/storage/drivers/driver_powerflex_volumes.go
lxd/storage/drivers/driver_types.go
lxd/storage/drivers/driver_zfs.go
lxd/storage/drivers/driver_zfs_volumes.go
lxd/storage/drivers/volume.go
lxd/storage/drivers/volume_test.go
lxd/storage/utils.go

This includes some improvements that were originally a part of the fix implemented in https://github.com/canonical/lxd/pull/14511, but ended up not being needed for that fix. They are still nice to have and thus were included here.

Storage: Define per-pool default block size

---

lxd/db/instances.go
lxd/db/projects.go
lxd/project/limits/permissions.go
lxd/project/limits/state.go

The use of `InstanceList` I introduced in #14318 causes 3 queries (`GetProfiles`, `GetConfig`, `GetDevices`) to be run twice. This eliminates the duplication.

Optimize Project Queries during limits checks

---

doc/cloud-init.md
doc/explanation/clustering.md
doc/explanation/storage.md
doc/howto/initialize.md
doc/howto/instances_backup.md
doc/howto/storage_backup_volume.md
doc/howto/storage_buckets.md
doc/howto/storage_pools.md
doc/metadata.txt
doc/reference/devices_disk.md
doc/reference/storage_lvm.md
doc/reference/storage_powerflex.md
doc/reference/storage_zfs.md
doc/tutorial/first_steps.md
doc/tutorial/ui.md

To address #14349 where users seek information about disk quotas, these commits clarify that when storage `size` is discussed in LXD docs, it means the same as `quota`. This already exists in some of the docs, but sparsely and inconsistently.

doc: clarify that storage size is equal to quota

---

.github/actions/setup-microceph/action.yml
.github/workflows/tests.yml
doc/api-extensions.md
doc/metadata.txt
lxd/metadata/configuration.json
lxd/storage/drivers/driver_ceph.go
lxd/storage/drivers/driver_ceph_utils.go
lxd/storage/drivers/driver_cephfs.go
lxd/storage/drivers/driver_cephfs_utils.go
shared/version/api.go
test/suites/storage_driver_ceph.sh

Closes #14006
Adds the keys `ceph.osd.pool_size` and `cephfs.osd_pool_size` (in keeping with the other naming schemes).
By default, if no value is supplied, the pool size will be pulled from the global default pool size. It can be set to any value larger than 0. 
On update, we will try to re-apply the OSD pool size value, if it has changed.

Set OSD pool size when creating `ceph` and `cephfs` storage pools

---

lxd/devices.go

Fixes https://github.com/canonical/lxd/issues/14591.
This PR reworks the logic in `ueventParseVendorProduct` to allow adding `unix-hotplug` devices with only `subsystem` specified. Rather than an early return for devices with subsystems that don't match `hidraw`, we gather the missing device info (`vendorid`/`productid`) when device system is `hidraw`. Otherwise, the `vendorid` and `productid` found in the config are returned.

Device: Rework `ueventParseVendorProduct` logic

---

lxd/auth/drivers/openfga.go
lxd/daemon.go
lxd/db/cluster/permissions.go
lxd/db/openfga/openfga.go
lxd/request/const.go

This PR decrease the latency of API calls that are going through the OpenFGA fine-grained authorizer. Thanks to a per-request cache mechanism, we avoid calling the database when the cache key is present.
This work has been benchmarked and has been used in the following PR: https://github.com/canonical/lxd/pull/14476
[openfga_benchmark.pdf](https://github.com/user-attachments/files/17960500/openfga_benchmark.pdf)
The benchmarking script can be found at: https://paste.ubuntu.com/p/WCwsk6gSSK/

OpenFGA: Add request cache to the OpenFGA datastore

---

doc/howto/storage_volumes.md

This is a first draft of changes I discussed with @minaelee last week. Broadly speaking:
- Replaces CLI specifications with concrete examples (shift from a [generic how to use](https://www.diataxis.fr/reference/) to [more specific/focused tasks](https://www.diataxis.fr/how-to-guides/)). This doesn't entirely turn this into a How-to the diataxis way, but it's closer. CLI specs should be left to `--help` and the man pages.
- Convert from the old `lxc config set key value` to the new `lxc config set key=value`
- Misc wording and content improvements
- align with the current state of LXD (ex. add `powerflex`)
- improve precision (ex. `s/path for accessing/mount point/` as in `mount(8)`)
- Move "View storage volumes" to the beginning of the document:
The first thing I do as a user is ask "how …

docs: Update storage volume How-to

---

lxc/completion.go
lxc/storage_volume.go
test/suites/storage.sh

The completions suggest the volume name but the client doesn't parse it correctly and this has been annoying me, so I took some of my time off to fix it and also improved the completions for detach/attach commands. Along with other small improvements.

lxc: Accept volume full name on `detach`

---

.github/actions/lp-snap-build/action.yml
.github/workflows/tests.yml

The system PATH on GHA runners needs to be updated in a special way: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#adding-a-system-path

lp-snap-builder action v3

---

lxd/storage/drivers/driver_ceph.go
lxd/storage/drivers/driver_ceph_utils.go
lxd/storage/drivers/driver_cephfs.go
lxd/storage/drivers/driver_cephfs_utils.go

Fixes `lxd-ci` pipeline errors from `mon_allow_pool_size_one` not being set

Check default osd pool size before setting on create.

---

doc/howto/network_load_balancers.md

This PR removes an unnecessary <listen_ports> option in the syntax for `lxc network load-balancer backend add`. This is correct in [the man page](https://documentation.ubuntu.com/lxd/en/latest/reference/manpages/lxc/network/load-balancer/backend/add/) but incorrect in [the how-to guide this PR fixes](https://documentation.ubuntu.com/lxd/en/latest/howto/network_load_balancers/#configure-backends). There is no `listen_ports` backend property. `listen_ports` is a port property that is used in `lxc network load-balancer port add`.

doc: fix lxc network load-balancer backend add command syntax

---

doc/explanation/storage.md
lxd/storage_volumes.go
test/suites/storage_local_volume_handling.sh

I noticed `lxc storage volume create "${pool}" isoVol --type=iso` worked inconsistently across drivers. Which led me to see that, according to the docs: `A custom storage volume of type `iso` can only be created by importing an ISO file using`, which makes sense because an empty ISO volume is useless AFAIK. So this implements this prohibition of creating empty ISO volumes.

lxd: Deny creation of empty ISO volume

---

lxd/api_internal.go

The defer rule was removed from our golangci-lint configuration in 0b3a0941185bad6b52808c30c313aff08d41742d. With this change, the defer in this function (which is called in a for loop) no longer needs to be ignored by the linter.
The defer rule was originally removed because refactoring existing code to stop calling defer within loops was resulting in subtle bugs that were hard to reason about.
We have extensive tests for LXD, so we should:
- Avoid calling defer inside a for loop, and watch for these in pull requests.
- Focus on improving code quality from a TICS perspective first.
Closes #12854

lxd: Remove lint exception for defer rule.

---

lxc/completion.go
lxd/instance/instance_utils.go
lxd/instance/instancetype/instance.go

Fixes https://github.com/canonical/lxd/issues/14570.
This PR reworks configuration key validation in `validConfigKey`, in `lxd/instance/instance_utils.go`. The intent of the first two commits is to:
1. Validate keys that begin with a prefix, such as `user.*` and `linux.sysctl.*`; and
2. Validate keys based on their instance type.
For example, when attempting to set `linux.sysctl.*` for a VM instance, a meaningful error message should be shown indicating the key is not valid for VMs, rather than the generic `Unknown configuration key: <key>`.
This PR also expands the use of the new slices `instancetype.ConfigKeyPrefixesAny` and `instancetype.ConfigKeyPrefixesContainer` to contextually provide completions for prefixed config keys when running`lxc config unset`, based on instance type.

LXC: Improve configuration key validation and add missing completions for `lxc config unset`

---

lxc/completion.go
lxc/config.go

Resolves https://github.com/canonical/lxd/issues/14647.
Adds the `cmpServerSetKeys` function for improved `lxc config unset` completions - only server config keys that are currently set will be completed when running `lxc config unset`.

CLI: Add dynamic `lxc config unset` shell completions for server config keys

---

Makefile
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/operationlock/operationlock.go
test/lint/i18n-up-to-date.sh
test/lint/licenses.sh
test/lint/metadata-up-to-date.sh
test/lint/test-tests.sh

I added some "quality of life" improvement to our `make static-analysis` target after looking at the `revive` error flagged during CI.

Fix typo: Reusuable -> Reusable

---

lxd/patches.go

In https://github.com/canonical/lxd/pull/13900 we introduced the concept of long-lived OVN NIC ports and removed the need for the `volatile.%.last_state.ip_addresses` keys. 
That PR added the `patchInstanceRemoveVolatileLastStateIPAddresses` patch to remove them.
However that patch loaded all instances and snapshots, then matched the specific keys to remove and removed each one by a separate query.
Although this allowed better debug logging, it was causing problems with users who have a lot of instances or snapshors from starting LXD as the patch was taking over 10s to apply and the single transaction was timing out.
See https://discourse.ubuntu.com/t/lxd-cant-restart-probably-a-dqlite-database-problem-maybe-related-to-snapshots/51162
This PR fixes the issue by pushing the matching logic …

Patches: Remove `volatile.%.last_state.ip_addresses` keys more efficiently

---

lxd/main.go
lxd/main_sql.go
shared/cmd/table.go

This allows specifying the output of `lxd sql` as `sql`, `csv`, `table`, `compact`, `json`, or `yaml`. The new `sql` format is added so that the column names are not auto-formatted (upper cased, replacing underscores with spaces).
This is added to ease scripting in tests and is required for #14651.

Add `--format` flag to `lxd sql`

---

lxd/instance/instance_utils.go

This PR fixes the following regression:
https://github.com/canonical/lxd-ci/actions/runs/12367790805/job/34516721509#step:11:93.
We always need to check config keys applied to VM's to ensure container-specific prefixed keys are disallowed.

VM: Move check for container-specific prefixed keys applied to VMs up

---

.golangci.yml

This PR adds the [`prealloc`](https://golangci-lint.run/usage/linters/#prealloc) linter to our `golangci-lint` config. `prealloc` finds slice declarations that could potentially be pre-allocated.

golangci: Add `prealloc` linter

---

lxc/completion.go
lxc/remote.go

Resolves 1/2 issues raised in https://github.com/canonical/lxd/issues/14635.
This PR adds logic to exclude the default (current) remote from shell completions when running `lxc remote switch|remove`. As described in [this comment](https://github.com/canonical/lxd/issues/14635#issuecomment-2547022037), it appears that `snapd` is intercepting the response and excluding non-default remotes (`cdimage` in this case). I'll see if I can land a fix for the second issue in https://github.com/canonical/lxd-pkg-snap.

CLI: Exclude default remote from `lxc remote switch|remove` shell completions

---

doc/reference/storage_cephfs.md

This PR adds the `lxc` prefix to the link in `doc/reference/storage_cephfs`. It was missed with https://github.com/canonical/lxd/pull/14600/commits/b15618883058d334807ab0c35502928cd03d8947#diff-15639efc2f09d9560a2350f733e0aa1b1ace86af9678844499d5c16c72582ecc.

Documentation: Update link prefix for `doc/reference/storage_cephfs`

---

lxd-agent/main.go
lxd/api_internal_recover.go
lxd/db/cluster/entities.go
lxd/instance_test.go
lxd/operations.go
test/mini-oidc/storage/storage_dynamic.go

Some `//nolint` comments have become defunct after changes to the linter configuration. This PR removes them!
Follow up to #14649

Remove defunct lint exceptions

---

test/suites/auth.sh
test/suites/backup.sh
test/suites/clustering.sh
test/suites/oidc.sh
test/suites/sql.sh

Support for the `--format` flag was added in #14670. This PR uses the format flag where possible in our test suite to avoid e.g. grepping for table formatted output.
In some cases I've changed queries to use a `SELECT count(*) FROM ...` instead of a `SELECT * FROM ...` where the output was piped into a word count or grepped with the -c flag.

test: Improve usage of `lxd sql` in tests

---

lxd/storage_volumes_utils.go
test/suites/storage_volume_attach.sh

Follow-up to #14491; if a volume is specified as `source: custom/c1`, then a rename of `c1`->`c2` should leave the device with `source: custom/c2`.

Preserve `custom/c1` syntax during storage volume rename

---

.github/workflows/tests.yml

As per https://discourse.canonical.com/t/end-of-the-year-update-for-tiobe-tics-required-action-to-disable-tics-cicd-pipelines/4890

github: Disable TICS temporarily

---

.github/.jira_sync_config.yaml

I changed the 'jira_key' and 'components' in .jira_sync_config.yaml configuration file for the synchronization with Jira.
The issues in LXD will be created in a separated epic and the 'component' key will allow filtering by 'LXD' key

github: update of .jira_sync_config.yaml 

---

lxd/resources/cpu.go

When VM has more than 9 vCPUs and they are exposed as sitting on a different "physical" sockets we don't handle it properly [1] as we implicitly assume that entries in /sys/devices/system/cpu/ are sorted the same way as in /proc/cpuinfo. But it's not correct assumption.
To reproduce that, the following QEMU command line parameter can be used: -smp 12,sockets=12,cores=1,threads=1
Affected systems have more than one line in the following command output: cat /sys/devices/system/cpu/cpu*/topology/physical_package_id | uniq and more than 9 CPUs.
[1] https://github.com/canonical/lxd/issues/14159#issuecomment-2551838382
Fixes: #14159
Signed-off-by: Alexander Mikhalitsyn <aleksandr.mikhalitsyn@canonical.com>

lxd/resources/cpu: fix GetCPU() to handle multisockets systems

---

lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go

PR https://github.com/canonical/lxd/pull/14539 broke live migration in commit https://github.com/canonical/lxd/pull/14539/commits/d734721b3d3e2000dd71bfc1c2cb7c92ff8c298d
This is because when live migrating a VM, the VM's `Start()` function is called on the target side (so that live migration can occur) before the Location of the instance is updated in the DB. This in turn calls `statusCode` during the start process.
The change to the `statusCode` function meant that this returned an error status because the instance was in theory non-local, and that prevented the qemu process from being started.
This PR reverts the `statusCode` error change and moves that logic into the Render function.
Fixes https://github.com/canonical/lxd/issues/14679

VM: Fix live migration

---

lxd/db/cluster/update.go
lxd/db/generate/db.go
lxd/db/generate/db/schema.go
lxd/db/node/update.go
lxd/db/schema.go
lxd/db/schema/update.go
lxd/db/schema/update_test.go

This is an alternative to #14704 
I didn't understand why `runtime.Caller` was required. It was because of where the `SchemaDotGo` functions were defined in the `node` and `cluster` packages.
We can instead just split the `go:generate` directives into their respective packages so that invocation there will cause the `schema.go` files to be created in the current directory.
As an aside, since `lxd-generate` is used by `micro*` packages, I'd also be in favour of removing the `schema` subcommand from it, as it only supports generating the LXD node or cluster schemas.

Remove `runtime.Caller` from `schema.DotGo`

---

lxd/storage_volumes.go
lxd/storage_volumes_utils.go
test/suites/clustering.sh

This makes `storagePoolVolumeUpdateUsers` safe to call without using a reverter.
This also adds a few tests around renaming attached local custom storage volumes in a clustered context. As we've discussed previously (#14681), updating disk devices in profiles isn't necessarily sound. These tests give me a little more confidence that updates behave sanely for local storage volumes in a cluster.
We should consider eliminating this feature altogether and simply making it a hard error to rename a custom storage volume while it is referred to by any disk device.

Storage: Add reverter to disk device update & test

---

lxc/completion.go

This PR fixes the logic in `cmpRemotes` to ensure remotes are contextually completed correctly based on the current remote. While testing https://github.com/canonical/lxd-pkg-snap/pull/674, I noticed that the `local` remote was not completed while on a different remote.

CLI: Fix remote completions

---

lxd/patches.go

Fix from https://github.com/canonical/lxd/pull/14659

lxd/patches: Remove volatile.%.last_state.ip_addresses keys more efficiently (stable-5.21)

---

doc/.custom_wordlist.txt
doc/howto/network_ovn_setup.md
lxd/network/acl/acl_interface.go
lxd/network/acl/acl_ovn.go
lxd/network/acl/driver_common.go
lxd/network_acls.go
shared/util.go

closes https://github.com/canonical/lxd/issues/12836
We need to remember to enable the log tests for microovn on https://github.com/canonical/lxd-ci/pull/368 when this is merged

Network: Return ACL logs from syslogs when the OVN controller is deployed in MicroOVN

---

lxd/api.go
lxd/devlxd.go

This implements a better handling of errors during Render on devlxd handlers, following the same pattern seen on https://github.com/hamistao/lxd/blob/unmask_write_errors/lxd/daemon.go#L846
When rendering a response (send it to the client) fails, instead of masking the error we try to send a response using `DevLxdErrorResponse` to the client communicating the error, since this determines the response type used for communicating erros on the devlxd API. If that also fails, an error is logged on the server.

devlxd: Unmask Render errors

---

lxd/devlxd.go
lxd/response/response.go

The returned response will be rendered using the same `ResponseWriter` object, resulting on a redundant call to `WriteHeader` on the second Render call.
Closes https://github.com/canonical/lxd/issues/14641

devlxd: Avoid superfluous call to `WriteHeader`

---

lxc/init.go
lxc/main.go
lxc/move.go

Closes https://github.com/canonical/lxd/issues/14691.
This PR adds flag completions for the following flags and commands:
- `--project` for all commands;
- `--profile` for `lxc init|launch`; and
- `--mode` for `lxc move`.

CLI: Add flag completions for `--project`, `--profile` and `--mode`

---

doc/cloud-init.md

Recent update in cloud-init docs https://github.com/canonical/cloud-init/pull/5909 included changing an anchor #vendordata to #vendor-data in one of their pages, which caused `WARNING: undefined label: 'cloud-init:vendordata' [ref.ref]` error when building our docs. This PR simply updates that reference to `cloud-init:vendor-data`.

doc: update ref to cloud-init docs

---

lxc/completion.go
lxc/image_alias.go

This PR adds completions for `lxc image alias`.
- Adds a function `cmpImageFingerprintsFromRemote` which provides shell completion for image fingerprints.
- Adds completions for `lxc image alias create|list|delete|rename`.

CLI: `lxc image alias` completions (from Incus)

---

lxc/completion.go
lxc/network_forward.go

Closes https://github.com/canonical/lxd/issues/14697.
- Fixes `cmpNetworkLoadBalancers`. `cmpNetworkLoadBalancers` should return load balancer addresses, not
network forward addresses.
- Adds `cmpNetworkForwardPortTargetAddresses` to provide target address completions for `lxc network forward port add`.
- Adds network completions to `lxc network forward` create.

CLI: `lxc network forward` completion improvements

---

.github/actions/reclaim-memory/action.yml
.github/workflows/tests.yml

Reclaims between 80 and 120MiB of memory from `ubuntu-22.04` runners.

github: add `actions/reclaim-memory`

---

lxd/devlxd.go

Fixes https://github.com/canonical/lxd/issues/14706

Devlxd: Fix crash due to concurrent pidMapper map access

---

lxd/storage/drivers/generic_vfs.go

This reverts commit ab910ac2cfbe2c91d6b5bcfe303dfe350b79ebe9 from https://github.com/canonical/lxd/pull/14761.
It is causing failures with our LVM CI tests due to the additional time it takes to do a slow `blkdiscard --zeroout` run when resetting the volume after an initial snapshot is transferred.
As the other commit in this PR deals with resetting the newly created volume, no old data from previously deleted volumes will be present, and this commit is just designed to ensure that "holes" of zeroes in the incoming data stream don't corrupt the volume when using the sparse writer.
As we've not landed the sparse writer yet, all of the bytes from the incoming data stream are written to the volume and thus there is no issue.
So we can hold off from landing this commit until we land the …

Storage: Revert "lxd/storage/drivers/generic/vfs: Truncate/Discard ahead of sparse write"

---

doc/howto/import_machines_to_instances.md

Add missing command `file` requirement for `lxd-migrate` in the docs.

doc: Add file command as requirement for lxd-migrate

---

doc/metadata.txt
lxd/metadata/configuration.json
lxd/storage/utils.go

The scope for `volume.size` should be global since `volume.size` on a storage pool is not node specific.

lxd/storage: Fix scope of `volume.size` for storage pools

---

lxd/storage_volumes.go
test/suites/clustering.sh

Fixes https://github.com/canonical/lxd/issues/14155.
- Includes the request project name in the `clusterCopyCustomVolumeInternal` function when building the `storageVolumePost` request. This is required to ensure the request project name is not always default when copying storage volumes with a target project set.
- Fixes storage volume migration error handling by checking if effective project and target project are the same only when the target project is not `default`.
- Adds a test for copying storage volumes across cluster members when both a target and target project are set.

Storage: Fix copying storage volumes between cluster nodes when target and project parameters are set

---

lxd/network/driver_ovn.go
test/suites/network_ovn.sh

Fixes https://github.com/canonical/lxd/issues/14531
The original problem was that the LXD UI was removing the `volatile.network.ipvx.address` keys, and these were being partially regenerated on the member that received the update request, but not on the other cluster members, leading to inconsistent BGP next hop addresses.
But really we shouldn't be allowing the `volatile.network.ipvx.address` keys to be removed when the associated `ipvn.address` keys are populated in the network.

Network: Prevent removal of OVN uplink volatile keys when associated network IP is populated

---

lxd/network/acl/acl_ovn.go

Requires https://github.com/canonical/lxd-pkg-snap/pull/688
This way, we rely on the `journalctl` host binary and not on the one shipped within the snap (which the version might differ whether LXD uses core22 or core24 as a base snap) We can also remove the `--directory ..` flag as the wrapper script which executes the host journalctl targets by default the host journal directory.

lxd/network/acl: Use the `journalctl` wrapper script introduced in the LXD snap

---

lxc/completion.go

Fixes https://github.com/canonical/lxd/issues/14689.
- Correctly provides instance config key completions based on instance type.

CLI: Rework `cmpInstanceKeys` for contextual completions based on instance type

---

lxd/device/device_utils_disk.go
lxd/device/disk.go
lxd/instance/drivers/driver_qemu.go

Different calls of `DiskGetRBDFormat` and `DiskParseRBDFormat` are currently using both senses of "volume":
- A Ceph block device (RBD Image)
- A LXD storage volume
Because a disk device can specify an RBD image with source `ceph:<pool_name>/<volume_name>"`, these functions should use the first meaning: the name passed should be the name of a RADOS block device (RBD image), not a LXD storage volume.
These functions should (in future) be replaced with a more comprehensive abstraction for what `MountInfo.DevPath` is currently doing. This serialization doesn't seem to be written anywhere, it's just deserialized when it gets to the instance driver.
This fixes the failures from https://github.com/canonical/lxd-ci/pull/366; the QEMU driver was inferring a virtual-machine `VolumeType` only when …

Storage: Align Ceph block device name encoding

---

lxd/devices.go

Fixes: https://github.com/canonical/lxd/issues/14709

Devices: CPU pinning fix (allow explicit pinning on isolated CPUs for VM instances)

---

.github/actions/install-lxd-runtimedeps/action.yml
test/main.sh
test/suites/container_devices_tpm.sh

ATM, GHA runners don't have the needed kconfig:
```
$ grep TPM_PROXY /boot/config-*
/boot/config-6.8.0-1020-azure:# CONFIG_TCG_VTPM_PROXY is not set
```
but those running the test suite locally should have no problem when using a non-Azure kernel (like `linux-image-virtual`).

Add missing `swtpm` command for container_devices_tpm test

---

client/lxd_containers.go
client/lxd_server.go
lxd/storage/drivers/utils.go

Deprecation notices need to be on their own paragraph so all our `// Deprecated: ` markers were missing a `//` before them.
https://go.dev/blog/godoc:
> To signal that an identifier should not be used, **add a paragraph to its doc comment** that begins with “Deprecated:” followed by some information about the deprecation.
This PR fixes most of them except for `RunCommand` as that's used in so many places.

Godoc deprecation notice

---

.github/workflows/tests.yml

This reverts commit ce0756b4e6be431bf0b556953b9b968ba341eb8f.
https://discourse.canonical.com/t/end-of-the-year-update-for-tiobe-tics-disable-tics-cicd-pipelines-if-needed-service-will-be-shutdown/4890/6?u=tomp

Revert "github: Disable TICS temporarily"

---

client/interfaces.go
client/simplestreams_images.go
lxc/image.go

https://github.com/canonical/lxd/pull/14563 attempted to fix https://github.com/canonical/lxd/issues/14561 by adding `GetImagesAllProjects` and `GetImagesAllProjectsWithFilter` functions to `client/simplestreams_images.go`, and moving their method signatures to the `ImageServer` interface. Instead, we should only expand the `InstanceServer` interface and correctly use the client functions when `--all-projects` is set.

LXC: Fix `lxc image list --all-projects`

---

lxd/images.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/instance_interface.go

Cherry-picks from https://github.com/lxc/incus/pull/1043.
Closes https://github.com/canonical/lxd/issues/14816.

VM: Send two ACPI events on shutdown, fix timeout errors and add progress tracking to export (from Incus)

---

doc/api-extensions.md
doc/metadata.txt
lxd/api_project.go
lxd/metadata/configuration.json
lxd/network/driver_common.go
lxd/network/driver_ovn.go
lxd/project/limits/permissions.go
shared/version/api.go
test/suites/network_ovn.sh

Introduces per-network project uplink IP limits, adding a `limits.networks.uplink_ips.NETWORK_NAME` configuration key to projects.
This config key defines the maximum value of IPs made available on a network named NETWORK_NAME to be assigned as uplink IPs for entities inside a cetain project.

Per-project uplink IP quotas

---

doc/cloud-init.md
doc/dev-lxd.md
lxd/devlxd.go

Some misconceptions/observations regarding some `cloud-init` concepts were pointed out throughout the discussions on https://github.com/canonical/lxd/issues/13853 and are addressed here.

cloud-init: Address `cloud-init` misconceptions

---

shared/util.go

Fixes 4add3b838521325af557e4827914c6654e298a34.

shared/util: set the path variable provided to the editor

---

doc/installing.md

Follow up to https://github.com/canonical/lxd/pull/14844/commits/0c0e89fd218e0241daf3b0e214dcad30fb63f89a.

Documentation: Add missing `swtpm` package to installing from source section

---

doc/howto/cluster_manage.md

- Add missing command syntax code blocks and examples
- Expand on cluster evacuation section, including adding subsections and additional information about live migrations
- Note that migration.stateful must be set on instances before they can be live-migrated, and that this can only be set while the instance is stopped
- Misc grammar / readability improvements

doc: add live-migration info, command syntax, misc improvements

---

doc/rest-api.yaml
lxc/storage_volume.go
lxd/storage/backend_lxd.go
shared/api/instance_state.go
shared/api/storage_pool_volume_state.go
test/suites/storage.sh

As per discussed on https://github.com/canonical/lxd/pull/14595#issuecomment-2589868308, this implements the standard of showing the size of unbound volumes as 0.
To keep the API consistent, also updates getting custom volume state so that total is shown even when usage is not supported and shows 0 to represent unsupporte usage of both custom and instance volumes.

Storage: Use zero for unbound volumes' total size on the API

---

lxd/storage/connectors/connector.go
lxd/storage/connectors/connector_common.go
lxd/storage/connectors/connector_nvme.go
lxd/storage/connectors/connector_sdc.go
lxd/storage/connectors/utils.go
lxd/storage/drivers/driver_powerflex.go
lxd/storage/drivers/driver_powerflex_utils.go
lxd/storage/drivers/driver_powerflex_volumes.go
lxd/storage/drivers/utils.go

This PR contains cherry-picks from #14700 to include only connectors and PowerFlex changes (without Pure Storage bits)
The aim of the connector is to handle connections with the target storage. Currently, connectors support NVMe, and SDC.
Once PowerFlex will use `Connect`/`Diconnect`, the following connector functions can be removed:
- `ConnectAll`
- `DisconnectAll`
- `SessionID`
Closes https://github.com/canonical/lxd/pull/14708

Storage: Add NVMe and SDC storage connectors

---

lxd/storage/connectors/utils.go

Allow the caller to set any timeout, avoiding 30 seconds timeout to be an upper limit.

Storage: Remove context timeout upper limit in connectors utils

---

lxd/auth/oidc/oidc.go

The remote key set will automatically fetch new keys when the current ones expire. If LXD is behind a proxy, this will fail unless the proxy enabled HTTP client is used.

OIDC: Use proxy enabled HTTP client for relying party remote key set

---

doc/reference/devices_proxy.md

Removes unsupported proxy connection types (udp <-> anything not udp) 
Also includes some wording improvements (no changes in meaning)
Closes #14874

doc: remove unsupported proxy connection types and improve wording

---

lxd/backup/backup_utils.go
lxd/instance_backup.go
lxd/storage_volumes_backup.go

This PR adds a function `ValidateBackupName` which enforces that backup names do not contain dangerous characters ('..', '/', '\').

Backup: Add consistent name validation

---

lxd/storage/block/utils.go
lxd/storage/connectors/utils.go
lxd/storage/drivers/driver_powerflex_utils.go
lxd/storage/drivers/driver_powerflex_volumes.go

This has to land after https://github.com/canonical/lxd/pull/14710 got merged as it was tested together. 
1. Don't map the volume before actually performing the resize in `SetVolumeQuota`. As we can get the current volume's size directly from PowerFlex it does not need to be mapped beforehand. This also allows reducing errors in `dmesg` caused by the resize in case the vol is already mapped to the system.
2. Prevent volume creation in case the PowerFlex pool isn't using zero-padding. This is to prevent leaking data from a previous volume in case the storage pool on PowerFlex wasn't setup appropriately.
3. Lock the PowerFlex client's API token to not cause concurrent logins and to save time in case of parallel access.
4. Always copy the PowerFlex client's request body for retries. Before, …

Storage: PowerFlex fixes and improvements

---

doc/custom_conf.py

Increasing the max rate limit timeout should help with linkcheck issues due to rate limits. 
Increasing the number of retries might also help with this & other linkcheck issues.

doc: increase linkcheck max rate limit timeout and retries

---

doc/rest-api.yaml
lxd/api_1.0.go
lxd/auth_groups.go
lxd/certificates.go
lxd/identities.go
lxd/images.go
lxd/instance_backup.go
lxd/instance_snapshot.go
lxd/networks.go
lxd/storage_pools.go
lxd/storage_volumes_backup.go
lxd/storage_volumes_snapshot.go
shared/api/auth.go
shared/api/image.go
shared/api/instance_backup.go
shared/api/instance_snapshot.go
shared/api/server.go
shared/api/storage_pool_volume_backup.go
shared/api/storage_pool_volume_snapshot.go
test/suites/auth.sh

This should fix the issues discussed here: https://chat.canonical.com/canonical/pl/c3bjkis1g3nmbytao6q5gcaxuc
This also add entitlement enrichment for API entities that weren't added as part as https://github.com/canonical/lxd/pull/14748

lxd: Entitlement enrichment for remaining API entities

---

client/lxd_images.go
client/lxd_oidc.go
client/lxd_profiles.go
client/lxd_projects.go
lxc/config/cert.go
lxc/network_peer.go
lxd/network/driver_physical.go

This fixes an unintended change introduced by https://github.com/canonical/lxd/commit/963f555865fbf8cdc4855fe458430f48bfd32aad

Follow-up on `fmt.Sprintf()` replacement

---

doc/metadata.txt
lxc/config_device.go
lxd/device/nic.go
lxd/device/nic_physical.go
lxd/metadata/configuration.json

Fixes https://github.com/canonical/lxd/issues/14879.
This PR adds parsing of the host physical NIC MAC address, allowing `agent.nic_config` to be set to `true` for physical NIC devices. I've also updated the metadata and included a small completion fix for a bug I discovered while testing this.
- Fixes conditional completions for `lxc config device add`.
- Updates metadata for physical NIC `hwaddr` config key.
- Updates the physical NIC `Start` method to retrieve host physical NIC MAC address and store in device config (for use in `addNetDevConfig` -> `writeNICDevConfig`).

Network: Parse host physical NIC MAC address for storing in device configuration

---

doc/metadata.txt
lxd/api_project.go
lxd/metadata/configuration.json
lxd/network/driver_common.go
lxd/project/limits/permissions.go

Moving the checks for uplink quotas to `AllowProjectUpdate` enables us to:
1- Be more aligned with our code standards;
2- Perform the check and update the quota values in a single transaction;
3- Be more efficient if setting many uplink quotas at once;

Projects: Peform uplink quota validation in a single transaction

---

doc/howto/storage_pools.md
doc/metadata.txt
lxd/metadata/configuration.json
lxd/storage/drivers/driver_pure.go
lxd/storage/drivers/driver_pure_util.go
lxd/storage/drivers/driver_pure_volumes.go

Fixes:
- Some typos
- Metadata description for `pure.target` to not include newlines (`\n`)
- Improve disk device ID construction when waiting for mapped NVMe disk device (inspired by [Cinder Pure Storage - get_nguid()](https://github.com/openstack/cinder/blob/651bb416899007b49bf4de2a9bd76afafb70de31/cinder/volume/drivers/pure.py#L3548-L3563))

Storage: Minor fixes for `pure` storage driver

---

doc/metadata.txt
lxd/device/nic.go
lxd/instance/instancetype/instance.go
lxd/metadata/configuration.json

This PR updates the long description for `agent.nic_config` and adds a container condition to container-specific physical NIC device options.

Network: Update physical NIC device options for added clarity

---

lxd/daemon_storage.go
lxd/device/disk.go
lxd/storage/backend_lxd.go
lxd/storage/backend_mock.go
lxd/storage/pool_interface.go

This is largely a revert of #14491. The functionality provided by the reverted commits is implemented in the last commit here.
Rather than using a common `MountVolume` which changes its behavior based on volume type, the disk device driver should choose the function to call based on the volume type provided by the user in the `source-type` field.

Storage: Restore specialized mount functions 

---

lxd/storage/connectors/connector_iscsi.go
lxd/storage/drivers/driver_pure_util.go
lxd/storage/drivers/driver_pure_volumes.go

Pure Storage does not allow mounting snapshots directly. Instead, we create a temporary volume with the snapshot's volume name. If the LXD was abruptly closed when temporary volume is being used, it may remain in the Pure Storage until the pool is removed.
To prevent such situation, when snapshot is removed also remove the potentially existing temporary snapshot volume.
Addresses comment: https://github.com/canonical/lxd/pull/14599#discussion_r1940802947

Storage: Delete potentially left snapshot temporary volume

---

lxd/storage/connectors/connector_iscsi.go

Running discovery from multiple routines can cause discovery to fail. When discovery fails the routine will not attempt to connect to the given address because it will error out after discovery. This can cause incomplete multipath, with some addresses left unconnected.
One way to handle this is to run discovery only once, when the lock in connect is acquired. However, we can always ensure the entry is inserted before connecting, and remove all entries for a given IQN after disconnecting. Managing iSCSI database manually is faster and cleaner.

Storage: Replace iscsi discovery with manual db management

---

lxd-agent/events.go
lxd/instance/drivers/driver_common.go

Closes https://github.com/canonical/lxd/issues/13677
Related CI tests in: https://github.com/canonical/lxd-ci/pull/403

VM: Apply mount options to hotplugged disks

---

lxd/auth/oidc/oidc.go

Adds a general method `getResultFromClaims` and associated methods to extract claims from ID tokens or userinfo responses. This function verifies that the authenticated party has a `sub` claim, and has an `email` claim that is a valid email address.
This is being added because we found that it was possible to authenticate with LXD without an email address claim. This caused an identity to be created with a blank identifier.

OIDC: Add methods to extract and verify claims

---

lxd/instance/drivers/driver_qemu.go

In LXD 4.0 the EFI firmware variables file was copied directly from the template file to the qemu.nvram file, rather than the copy being a separate file named after the firmware variant and symlinked to the qemu.nvram file.
Following on from https://github.com/canonical/lxd/pull/14555 this PR now considers that the EFI firmware variables file needs regenerating if the qemu.nvram file isn't a symlink.

VM: Fix nvram file update from older non-symlinked templates file in LXD 4.0

---

doc/howto/move_instances.md

- Separated move and copy into own sections & moved text out of unnecessary annotation boxes
- Improved section on live-migrating VMs, including info about setting `migration.stateful` only while VM is stopped, and a syntax example
- Added brief section about cluster evacuate/restore for moving all instances temporarily

doc: update guide on moving instances and live migration

---

lxd/instance/drivers/driver_qemu.go

Volumes with a `-` in their name would fail to detach as the device name used at device removal was different than the one used at creation.
This only manifested in the LVM driver, although I didn't check zfs.
Fixes the failures from https://github.com/canonical/lxd-ci/pull/409

lxd/instance/drivers/qemu: Fix double-escaped device name

---

doc/metadata.txt
lxd/metadata/configuration.json
lxd/storage/drivers/driver_pure.go

Adds required API token role in `pure.api.token` field description.
The required role is `array_admin` to allow LXD full control over managed storage pools (Pure Storage pods). One example of this requirement is removal of default protection rules when storage pool is created.

Storage: Include required Pure Storage API token role in description

---

doc/.custom_wordlist.txt
doc/metadata.txt
lxd/metadata/configuration.json
lxd/storage/drivers/driver_powerflex.go

Adds a short note about the minimum required role the PowerFlex user needs to have set.

Storage: Document Powerflex user minimum require role

---

doc/reference/storage_pure.md

Clarify that sharing Pure Storage array is possible between LXD installation as long as they use different storage pool names.

docs: Clarify Pure Storage array usage between LXD installations

---

lxd/locking/lock.go
lxd/storage/connectors/utils.go

This PR supersedes https://github.com/canonical/lxd/pull/14955.
It adds a new `TryLock` function which tries to acquire a lock but doesn't block if the lock is already acquired.
This beahvior is used to check if there already is an active connection so that subsequent callers don't try to run through the connection attempts again but rely on the already existing connection(s).

Storage: Add `TryLock` loop for faster connection attempts during errors

---

lxd/network/openvswitch/ovn.go

Now gets the list of ha_chassis first to convert the received chassis_name into a _uuid for later comparison.
Fixes #14902.

Network: Fix OVN ChassisGroupChassisDelete to convert chassis_name

---

doc/.custom_wordlist.txt
doc/metadata.txt
lxd/metadata/configuration.json
lxd/patches.go
lxd/storage/connectors/connector.go
lxd/storage/connectors/connector_iscsi.go
lxd/storage/connectors/connector_nvme.go
lxd/storage/connectors/connector_sdc.go
lxd/storage/drivers/driver_powerflex.go
lxd/storage/drivers/driver_powerflex_utils.go
lxd/storage/drivers/driver_powerflex_volumes.go

Closes https://github.com/canonical/lxd/issues/14814
This aligns the PowerFlex driver with the implementation of Pure in https://github.com/canonical/lxd/pull/14599 to use the NVMe/TCP `Connect` and `Disconnect` functions instead of their `(Connect|Disconnect)All` counterparts.
Furthermore a patch is introduced to remove the `powerflex.sdt` config key from already existing storage pools. 
Currently only a single address is stored in the key and using `nvme connect-all` all of the other targets (SDTs) are discovered anyway.
As the driver is now querying for all the SDTs in case `powerflex.sdt` config key is not set, the behavior is the exact same.
In addition `powerflex.sdt` now accepts multiple addresses separated by comma which allows overriding the addresses discovered by asking the …

Storage: Powerflex use `Connect` and `Disconnect` for NVMe/TCP

---

lxd/network/openvswitch/ovn.go
test/suites/network_ovn.sh

Follow on from https://github.com/canonical/lxd/pull/14904
I suspected here https://github.com/canonical/lxd/pull/14904#discussion_r1951177670 the call to get `ha_chassis` list requires both `--format=csv` to get them onto one line per record, *and* `--data=bare` to avoid the output being (double in this case) quoted.
This was preventing the previous fix from actually working. 
Also moved the zero-length initialised slices back to uninitialised ones, as nil slices can be appended to, and is more in keeping with how we use slices elsewhere.
Also added a test for chassis removal on LXD shutdown.

Network: Fix OVN ChassisGroupChassisDelete quoting values

---

lxd/network/openvswitch/ovn.go
lxd/network/zone/zone.go
shared/dnsutil/reverse.go
test/suites/network_ovn.sh

Backports of:
- https://github.com/canonical/lxd/pull/14956
- https://github.com/canonical/lxd/pull/14904
- https://github.com/canonical/lxd/pull/14964

OVN bug fixes backports (stable-5.21)

---

lxd/storage/drivers/driver_powerflex_utils.go

This reverts commit d298a4487cce36cf9230855f062b8c5b119f643e.
Whilst reviewing https://github.com/canonical/lxd/pull/14968 I realized that the lock on the token is not required as there isn't any case with multiple callers on the same instance of the storage driver struct.
See [comment](https://github.com/canonical/lxd/pull/14968#discussion_r1952783018) for reference.

Storage: Revert PowerFlex client API token lock

---

lxd/instance_logs.go

- Don't load full record until after internal redirect to correct cluster member has occurred, otherwise the instance is potentially loaded twice.
- Also always use instance name from DB when constructing paths.
- Improve file name checks to appease codeql.

API: Avoid premature load of instance DB record in log endpoints

---

doc/api-extensions.md
doc/cloud-init.md
doc/metadata.txt
lxd/device/disk.go
lxd/devlxd.go
lxd/devlxd_test.go
lxd/instance/instancetype/instance.go
lxd/metadata/configuration.json
lxd/util/config.go
shared/validate/validate.go
shared/version/api.go

This adds supports for addition of SSH keys on instances in such a way that neither `cloud-init.vendor-data` and `cloud-init.user-data` are not overwritten.
This is done through the addition of the config key `cloud-init.ssh-keys.KEYNAME`, where KEYNAME can be any arbitrary name for the added key. The content of this key is merged into any pre-existing `cloud-config` defined in either `cloud-init.vendor-data` or `cloud-init.user-data`.
LXD CI tests in https://github.com/canonical/lxd-ci/pull/412

cloud-init: Support injection of additional SSH keys on instances

---

client/lxd.go
client/lxd_oidc.go
doc/api-extensions.md
doc/metadata.txt
lxd/api_1.0.go
lxd/auth/oidc/oidc.go
lxd/cluster/config/config.go
lxd/daemon.go
lxd/metadata/configuration.json
lxd/patches.go
lxd/patches_test.go
shared/version/api.go
test/suites/oidc.sh

In the end, just having `oidc.scopes` was the way to go (see https://github.com/canonical/lxd/pull/14888#issuecomment-2642783581). I've added tests for the validation of the config key and also tested it locally with Keycloak by disabling the `profile` claim.
Closes #14141.

OIDC: Make scopes configurable

---

doc/howto/network_forwards.md

Fixes #14970. Replaced `lxd` with `lxc` in command examples.

doc: lxd to lxc typo in network_forwards.md

---

.github/workflows/tests.yml

- Separated a portion of the documentation job from the test workflow into its own job. This prevents the UI E2E tests from depending on unrelated parts of the documentation job.
NOTE: On my fork [run](https://github.com/mas-who/lxd/actions/runs/13309237496/job/37167572965), the documentation test job was executed successfully, but it seems like the doc link checker is failing at the same spot

github: split documentation job into build and test

---

doc/cloud-init.md
lxd/device/disk.go
lxd/devlxd.go

Addressing some left over comments from https://github.com/canonical/lxd/pull/14959

cloud-init: Follow up on SSH key injection

---

doc/metadata.txt
lxc/storage_volume.go
lxd/device/disk.go
lxd/metadata/configuration.json
lxd/storage/utils.go

This is the kind of thing that makes people wonder "what the heck were they thinking" (see [docs](https://documentation.ubuntu.com/lxd/en/latest/reference/devices_disk/#device-disk-device-conf:size)):
I couldn't unsee it. Namespacing these keys under `source` just seems like a really good idea. I will use `source.snapshot` for snapshots.
There shouldn't be any changes needed for the lxd-ci tests; I ran them on this locally and they pass.

Replace `source-type` with `source.type`

---

.github/workflows/tests.yml

- Move inclusive name checker into main documentation build and test workflow.
- Separate out the link checker workflow from rest of documentation workflow as unreliable - this avoids unnecessary checkout and download of documentation build just to run inclusive name check on normal PRs.

github: Rework documentation tests

---

lxd/api_1.0.go
lxd/daemon_storage.go

Should close https://github.com/canonical/lxd/security/code-scanning/1 (although not real security issue because codeql is not correctly detecting that the existing validation prevents using unvalidated raw input anyway).

Daemon: Update storage.backups_volume and storage.images_volume validation

---

lxd/db/cluster/identities.go
test/suites/auth.sh

The error message displayed when adding an identity to groups is currently:
```
fmt.Errorf("Failed to write expected number of rows to identity auth group association table (expected %d, got %d)", len(groupNames), rowsAffected)
```
Which is a bit gross. It also isn't returning an appropriate HTTP error code.
I've added some error handling to check all the inputted groups and return a nice error containing all the groups that are missing.

Auth: Return missing group names on error

---

lxd/daemon_storage.go

Should hopefully please CodeQL for https://github.com/canonical/lxd/security/code-scanning/1031 and possibly https://github.com/canonical/lxd/security/code-scanning/1

lxd: Extra validation of daemon storage options pool and volume names

---

lxd/daemon_storage.go
test/suites/serverconfig.sh

This prevents using FS vols from unsupported remote storage drivers for the `storage.(images|backups)_volume` config keys.
It prevents concurrent reads/writes from multiple hosts when used inside a cluster.
Just checking for remote drivers is not sufficient as CephFS volumes can be used.

Storage: Prevent using remote storage pools for `(images|backups)_volume`

---

lxd/device/cdi/spec.go

After we've got https://github.com/NVIDIA/nvidia-container-toolkit/pull/847 merged we can use WithConfigSearchPaths() nvcdi option to specify where NVIDIA configuration files are located and revert our previous hacky fix from https://github.com/canonical/lxd-pkg-snap/pull/679
No behavior change for non-Ubuntu Core environment intended.
Please, merge with https://github.com/canonical/lxd-pkg-snap/pull/739

lxd/device/cdi/spec: use config search paths option for Ubuntu Core

---

lxd-agent/events.go

This regression was introduced in https://github.com/canonical/lxd/commit/fbecd19220f350697d756ac9d7f9c7db1c3601e6 and detected in https://github.com/canonical/lxd-ci/actions/runs/13406893641/job/37448392311.

VM: Fix path check logic

---

doc/howto/cluster_form.md

The YouTube links still points to the outdated initialization process.
Also the link is now updated to point to the LTS version of the docs (`v2-edge`).

doc: Update outdated MicroCloud info

---

lxd/device/disk.go

We can't add make these values available through `ds.config` as we do when using the LXD datastore, so this is the next best thing.
This does raise the risk of adding duplicate keys since `user.meta-data` could include the same key as some `user.*`. Similarly to what is reported in https://github.com/canonical/lxd/issues/13853. But this won't be a concern after `user.meta-data` is removed.
Closes https://github.com/canonical/lxd/issues/14803

cloud-init: Include `user.*` keys in `meta-data` file

---

lxd/network/driver_ovn.go
lxd/network/openvswitch/ovn.go

This PR changes the way LXD configures OVN's logical switch ports so that it doesn't request `dynamic` IPs for the switch port when `ipv4.dhcp` **and** `ipv6.dhcp` are disabled on the network.
Because OVN doesn't currently allow us to request protocol specific dynamic allocation, LXD has a workaround where if `ipv4.dhcp` is disabled, but `ipv6.dhcp` is enabled, LXD will generate an EUI64 address from the MAC address and set that as a static address in OVN. This avoids OVN needing to also allocate an IPv4 address. It also means that no DNS A records will be created for that port.
However in the case where `ipv4.dhcp` is enabled and `ipv6.dhcp` is false, we need to ask OVN to assign `dynamic` addresses, and so the logical switch port will get both an IPv4 and IPv6 address (and DNS entries …

Network: Don't ask OVN to allocate dynamic addresses when DHCP is disabled

---

lxd/instance/drivers/driver_common.go

Setting a new instance ID prompts `cloud-init` to get and apply configuration from LXD. So we update the instance ID if an instance restarts after changing configuration that is relevant for `cloud-init` to make sure it is applied. This PR does this with `cloud-init.ssh-keys` so they are applied even after the first boot.

cloud-init: Reset Instance ID when SSH keys are defined

---

doc/rest-api.yaml
lxd/instance_backup.go
lxd/instance_snapshot.go
lxd/network_acls.go
lxd/network_zones.go
lxd/storage_volumes_backup.go
lxd/storage_volumes_snapshot.go
shared/api/instance_backup.go
shared/api/instance_snapshot.go
shared/api/storage_pool_volume_backup.go
shared/api/storage_pool_volume_snapshot.go
test/suites/auth.sh

This adds tests for the enrichment of the remaining LXD entities that are eligible. This also remove support for entitlement enrichment for instance<snapshot|backup> and volume<snapshot|backup>. These are managed by the parent instance/volume `can_mange_<snapshots|backups>`

auth: Add more tests for entity enrichment with entitlements

---

lxd/db/cluster/entity_type_identity.go
test/suites/auth.sh

The database queries for certificate and identity entity types were
changed in #14173 so that they don't overlap. This included restricting
the ID from URL query for identities to only include OIDC identities
(which were the only fine-grained identities at the time).
When fine-grained TLS identities were added in #14207, the new identity
types were not added to the ID from URL query. This prevents permission
subsystems from resolving the URL of a pending or activated fine-grained
TLS identity, and therefore prevents permissions from being granted against
identities of this type.
Reported by @mas-who:
```
mason@BlackMumba:~/Desktop/work/forks/lxd-ui/keys$ lxc auth group show tls-group
name: tls-group
permissions:
- entity_type: server
url: /1.0
entitlement: admin
- …
```

Auth: Fix `idFromURLQuery` for fine-grained TLS identities

---

.github/workflows/tests.yml

The code test job fails ~18% of the time according to https://github.com/canonical/lxd/actions/metrics/performance?tab=jobs
Since the client tests are super quick to run and are not gating anything, it's best to run them only once the code tests have passed.

github: require code tests to pass before running client ones

---

lxd/instance_backup.go

Help CodeQL understand the instance name was validated. Should address the following warnings:
* https://github.com/canonical/lxd/security/code-scanning/64
* https://github.com/canonical/lxd/security/code-scanning/287

lxd/instance_backup: Save the implicitly validated instance name

---

test/main.sh
test/suites/backup.sh

This mostly aims at being faster by using smaller instances/volumes.
It also renames the `backup_different_instance_uuid` test to `backup_instance_uuid` to avoid any confusion. As explained in cb5bb787dbf, the UUIDs should be preserved through `export`/`import`.

Tweaks for backup tests

---

lxd/device/nic_ovn.go
lxd/network/acl/driver_common.go
lxd/network/driver_ovn.go
lxd/network/openvswitch/ovn.go

State was imported only to get some config keys for setting up the OVN command connection arguments. We should try to not import state where possible, and only import the fields we need at the lowest level. This helps not only with reducing the size of imports, but also for use of packages externally, and also for unit testing.
This is required for using the OVS package externally. See #15044 and #14606. cc @ghadi-rahme

OVN: Remove `state.State` from `openvswitch`

---

lxd/network/driver_ovn.go
lxd/network/openvswitch/ovn.go

It is a tested behaviour that `ipv{n}.routes` and `ipv{n}.routes.external` can be set on an OVN NIC when its network has `ipv{n}.dhcp=false`, so we need to ensure OVN is still allocating dynamic IPs for the port in this case.
Also refactors `InstanceDevicePortStart` to reduce scope of variables and, hopefully, improve clarity of IP assignment logic.

Network: Fix OVN NIC dynamic IPs not being allocated when DHCP is disabled but NIC device has routes

---

lxd/operations.go

If the operation fails to render, we should not log the whole operation as it can contain sensitive information (tokens, passwords, etc).
Addresses https://github.com/canonical/lxd/security/code-scanning/307
Co-developed-by: Mark Laing <mark.laing@canonical.com>

lxd/operations: don't log whole operation on failure

---

CONTRIBUTING.md
doc/README.md
doc/contributing.md

- replaces the Contributor Covenant Code of Conduct with the Ubuntu Code of Conduct 
- a few minor fixes

doc: Code of Conduct replacement and minor fixes

---

lxd/apparmor/instance_lxc.go

- core20 is updated
- core20 update contains a fixed AppArmor user space utilities version which contains a fix for an old bug https://bugs.launchpad.net/apparmor/+bug/1597017
- this makes AppArmor to be more strict than before
- and... we have a problem with devpts mount after.

AppArmor-related cherry-picks due to core20 update (stable-4.0)

---

doc/installing.md

Adds missing word `snap` in two places.

doc/installing: fix missing words in command syntax

---

lxd/device/disk.go

Prior to this change, the following disk types could have `readonly: true` in their device config and still be mounted rw in VMs:
- root disks (not likely to work very well but the disk device config semantics should be consistent)
- cloud-init config drive (unknown to me if a CD image would be writable)
- `source: ceph:...` disks
- Delegated ceph block volumes (all ceph block volumes are delegated)
I alluded in #14930 to a regression introduced by this change; that was a mistake on my part. This is good to go, tests at https://github.com/canonical/lxd-ci/pull/422.

lxd/device/disk: Consider `readonly` for other volume types

---

lxd/instance/drivers/driver_lxc.go

The handling of `NVIDIA_REQUIRE_CUDA` and `NVIDIA_REQUIRE_DRIVER` env variables seem to have been backward causing empty variables to be exported when the respective configuration keys were empty and not defined when actually populated.

lxd/instance/drivers/lxc: tiny improvements

---

lxd/network/openvswitch/ovs.go
lxd/resources/network.go

Adds extra functions to ovs.go to allow for the needed OVS bridge information to be read. 
These are needed for `GetNetworkState()` to be able to retrieve OVS bridge information.  
Fixes #14606

Network: Add OVS bridge information 

---

doc/howto/initialize.md

- Fixed broken link to MAAS documentation in doc/howto/initialize.md.

doc: update broken link in howto/initialize

---

doc/howto/cluster_manage.md

This backports https://github.com/canonical/lxd/pull/14870 into `stable-5.21` to get the doc reference labels `cluster-restore` and `cluster-evacuate-restore` into the stable branch to unblock the MicroCloud [`v2-edge` backports](https://github.com/canonical/microcloud/pull/681) which reference those labels using the docs from `stable-5.21`.

Backport docs (stable-5.21)

---

lxd/device/config/device_runconfig.go
lxd/device/device_utils_disk.go
lxd/device/device_utils_unix.go
lxd/device/disk.go
lxd/device/gpu_physical.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/storage/drivers/driver_ceph_utils.go
lxd/storage/drivers/utils_ceph.go

`DiskGetRBDFormat` and `DiskParseRBDFormat` have been the gifts that keep on giving... bugs! Instead of trying to hack yet another field into these functions, I went ahead and refactored `MountEntryItem`'s `DevPath` field to use `any` instead of `string`.
Beyond being more comprehensible and less error-prone, it also makes adding fields to delegated RBD disk devices pretty trivial.
The second piece of this PR makes attaching RBD volume snapshots work (@tomponline was correct, this never worked and somehow slipped through my local tests). LXD uses Ceph in two ways:
- The `rbd` cli utility (`man 8 rbd`)
- Via Qemu QMP ([docs](https://www.qemu.org/docs/master/interop/qemu-qmp-ref.html))
The rbd utility requires the snapshot's name to be appended to the volume name with an `@`.
QMP expects a …

Fix Snapshot Root attachment for RBD Volumes

---

lxd/instance_instance_types.go

Closes https://github.com/canonical/lxd/issues/13135.
This pull request simplifies the process of updating instance types in the `instance_instance_types.go` file by consolidating the parsing of instance type sources into a single step.

lxd/instance_instance_types: Update `instanceRefreshTypes` function to use `all.yaml` instance type file

---

lxd/device/proxy.go
test/suites/container_devices_proxy.sh

Closes https://github.com/canonical/lxd/issues/14972 and https://github.com/canonical/lxd/issues/15023.
Co-authored by @simondeziel.
This pull request includes changes to `lxd/device/proxy.go` to improve error handling and cleanup processes, as well as a test update in `test/suites/container_devices_proxy.sh` to ensure proper socket removal.
Changes to `lxd/device/proxy.go`:
* Updated `killProxyProc` to also perform any necessary cleanup (removing the created unix socket) and improved error message formatting.
* Modified `checkProxyStarted` function to to prioritize the 'Failed to listen on...' error message.
Test update in `test/suites/container_devices_proxy.sh`:
* Added a check to the `container_devices_proxy_unix` function to ensure that the host socket is removed upon proxy device …

LXD: Proxy device fixes

---

doc/api-extensions.md
doc/rest-api.yaml
lxd/api_1.0.go
shared/api/server.go
shared/version/api.go

* show if client cert was present for an unauthenticated request to GET /1.0
* this is for the UI to use, as it can't know if a cert is present otherwise
* following a suggesting from @markylaing

Client cert presence check in GET /1.0

---

CONTRIBUTING.md
doc/index.md

Replaces third-party Code of Conduct with Ubuntu Code of Conduct per https://github.com/canonical/lxd/pull/15113#issuecomment-2710247105.

doc: update code of conduct and its link (stable-5.0)

---

CONTRIBUTING.md
doc/README.md

Update links to point to 5.21 docs per https://github.com/canonical/lxd/pull/15092#discussion_r1977123112
(Code of Conduct replacement from that PR already backported via https://github.com/canonical/lxd/pull/15125)

doc: update contributing guide links to 5.21 docs (stable-5.21)

---

test/suites/container_devices_nic_bridged_filtering.sh

Sometimes we see a ping failure to the gateway in our tests after adding the IPs to the container. Perhaps this is caused by Duplicate Address Detection not yet completing and the IPs being in tentative state.
```
lxc exec nt22616A -- ip a add 192.0.2.2/24 dev eth0
lxc exec nt22616A -- ip a add 2001:db8::2/64 dev eth0
lxc exec nt22616A -- ping -c2 -W5 192.0.2.1
PING 192.0.2.1 (192.0.2.1): 56 data bytes
64 bytes from 192.0.2.1: seq=0 ttl=64 time=0.079 ms
64 bytes from 192.0.2.1: seq=1 ttl=64 time=0.057 ms
--- 192.0.2.1 ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.057/0.068/0.079 ms
lxc exec nt22616A -- ping -c2 -W5 2001:db8::1
PING 2001:db8::1 (2001:db8::1): 56 data bytes
--- 2001:db8::1 ping statistics ---
2 packets transmitted, …
```

test: Add wait_for_add call during test_container_devices_nic_bridged_filtering

---

lxd/api_internal.go
lxd/instances_post.go

This in in preparation for https://github.com/canonical/lxd/pull/15129.
It only applies for instances, custom storage volumes are not affected.
In case a backup using the newer version gets imported on LXD 5.x, it should not panic.
The same applies in case the backup file was intentionally/unintentionally modified.

API: Don't panic if instance backup config is invalid (stable-5.0)

---

.github/actions/setup-microovn/action.yml

CI fails occasionally due to race:
```
+ sudo microovn cluster bootstrap
Error: Post "http://control.socket/core/control": dial unix /var/snap/microovn/common/state/control.socket: connect: no such file or directory
```
MicroOVN added support for a `waitready` subcommand for us in https://github.com/canonical/microovn/pull/225, we just need to use it.
MicroCeph is [not affected](https://github.com/canonical/microceph/blob/210e20f30bba4b3e0c9247bdd6539d70f1ccedfb/microceph/cmd/microceph/cluster_bootstrap.go#L80).

github: Use `microovn waitready`

---

lxd/backup/backup_config.go

Follow up on https://github.com/canonical/lxd/pull/15165.
The field is still accessed down the line (the code is structured differently in 4.0 therefore I have missed this bit).
The previous PR only had half of the fixes.

API: Don't panic if backup config is missing (stable-4.0)

---

.github/actions/install-lxd-runtimedeps/action.yml
test/suites/network.sh

This tests makes sure that we are able to retrieve OVS bridge information as well as native linux bridge information after disabling the openvswitch service using "$ lxc network info <bridge>".

tests/suites/network.sh: Add test for fetching bridge info

---

lxd/db/cluster/storage_volume_type.go
lxd/db/instances.go
lxd/db/storage_pools_test.go
lxd/db/storage_volume_snapshots.go
lxd/db/storage_volumes.go
lxd/device/disk.go
lxd/instance/drivers/driver_qemu.go
lxd/instance_test.go
lxd/migrate_storage_volumes.go
lxd/patches.go
lxd/project/project.go
lxd/storage/backend_lxd.go
lxd/storage/utils.go
lxd/storage_volumes.go
lxd/storage_volumes_snapshot.go
lxd/storage_volumes_state.go
lxd/storage_volumes_utils.go

This:
- Communicates intent via a variable's type, not just its name
- Prevents accidental assignment of e.g. a volume type where a content type was expected
- Enforces the type safety at the database boundary; any type IDs coming out of the database layer can be assumed to be correct
- Provides convenient conversions using `Name()`

Storage: Newtype for Database Volume/Content types

---

lxd/db/cluster/storage_volume_type.go
lxd/db/storage_volume_snapshots.go
lxd/db/storage_volumes.go
lxd/device/disk.go
lxd/instance/drivers/driver_qemu.go
lxd/storage/utils.go

As requested in the review of https://github.com/canonical/lxd/pull/14885
Yields a few readability improvements in the disk device driver as well; kudos on the suggestion.

Rename `StoragePoolVolume{Content}Type` `Name` methods to `String`

---

lxc/file.go

To help with syntax highlighting
(cherry picked from commit 7d456f725477e136473b68e8cdae595c23d6ae1f)

lxc/file: Use the file extension of the edited file for the temp file (from Incus)

---

lxd/instance/drivers/driver_qemu.go
lxd/instance/drivers/qmp/commands.go

Cherry-picks from https://github.com/lxc/incus/pull/1531, https://github.com/lxc/incus/pull/1601, and https://github.com/lxc/incus/pull/1196.
Fixes https://github.com/canonical/lxd/issues/14916.

VM: Fix QMP arguments typing to support QEMU 9.2 (from Incus)

---

lxd/instance/drivers/driver_lxc.go
lxd/storage/drivers/driver_lvm_utils.go
lxd/storage/drivers/driver_lvm_volumes.go

When a thick LVM volume is activated, its snapshots are activated, and vice versa.
When I introduced snapshot attachment for VM volumes (https://github.com/canonical/lxd/pull/14930), it became possible for a snapshot to be mounted independently of its parent volume. The [previous logic](https://github.com/canonical/lxd/commit/44d4b432fb032fc57084afe4cad08d71979c7ae1) (see https://github.com/canonical/lxd/issues/10302) allowed for snapshots to be mounted while their parent volumes were mounted, but not vice versa.
In order to correctly identify when an LV can be safely deactivated, this introduces a reference count for LVs to prevent deactivation of an LV which was activated by another instance/operation.

Storage: Reference counts for LVM LV activation

---

doc/.custom_wordlist.txt
doc/howto/oidc_ory.md
doc/operation.md

- added how to configure ory hydra as login provider for the lxd ui

docs: add oidc configuration with ory hydra

---

doc/api-extensions.md
doc/rest-api.yaml
lxd/api_cluster.go
lxd/db/cluster.go
lxd/db/cluster/cluster_groups.go
shared/api/cluster.go
shared/version/api.go
test/suites/clustering.sh

Adds an API extension `clustering_groups_used_by` and adds a `UsedBy` field to `api.ClusterGroup`. On GET requests, the `UsedBy` URLs are projects that contain the cluster group in `restricted.cluster.groups`. DELETE requests will fail if the cluster group is used by a project.
Closes #15118

Prevent cluster groups from being deleted when referenced by a projects' configuration

---

lxd/api_1.0.go
lxd/bgp/server.go
lxd/daemon.go
test/suites/network_forward.sh

Includes cherry-pick from https://github.com/lxc/incus/pull/1761.
**Changes:**   
- BGP listener is now started after all the networks are set up.
-  Predefined network forwards are now added correctly during the BGP listener start up.
- Extended test/suites/network_forward to test the BGP listener start up and subsequent restart of LXD daemon.

lxd/bgp: Rework start/stop logic (from Incus)

---

go.mod
go.sum
lxd/sys/apparmor.go

The github.com/moby/sys/capability package is a fork of the original one, which is apparently no longer maintained.
For changes since the fork took place, see
https://github.com/moby/sys/blob/main/capability/CHANGELOG.md
(The indirect dependency still remains because of runtime-tools; this is being fixed in
https://github.com/opencontainers/runtime-tools/pull/777).
Related to: https://github.com/moby/sys/issues/183

deps: switch to github.com/moby/sys/capability

---

.github/actions/require-gha-pinning/action.yml
.github/workflows/tests.yml

This PR is supposed to fail until I bring in the commit to pin the `actions/setup-node@v4`.
**Update:** this failed as needed until the last commit  was added.

Require GHA pinning

---

doc/rest-api.yaml
lxd/identities.go

Replaces incorrect `token` with `trust_token`, as that is what is required for this endpoint to work.

doc: Untrusted TLS identity post endpoint description

---

.github/actions/require-gha-pinning/action.yml

The old pattern authorized local aliases with `./.` prefix but `./` is also a legitimate way to refer to local actions. That was found when working on [`canonical/setup-lxd`](https://github.com/canonical/setup-lxd/pull/27). This one is special as it's an action itself.

github: fix regex allow list for local actions

---

lxd/api_project.go
test/suites/clustering.sh

Fixes https://github.com/canonical/lxd/issues/15179.  
Fixed early return in `projectIsEmpty()` by simplifying if statement to check associated profiles.

lxd: Prevent deleting non-empty project

---

doc/cloud-init.md
lxd/cloudinit/config.go
shared/validate/validate.go

A `none` value can be used to avoid inheriting an SSH key from profile configuration.

cloud-init: Allow `none` for `cloud-init.ssh-keys.*`

---

lxd/network/driver_bridge.go

Fixes 376c6a69c4d3bdb697564da12fcef6c20d8d0b68
Addresses https://github.com/canonical/lxd/issues/15212

Network: Fix bridge fan mode by adding "/" back into `fanAddress()` output

---

doc/.custom_wordlist.txt
doc/howto/oidc_keycloak.md
doc/operation.md

- added how to configure keycloak as login provider for the lxd ui

docs: add oidc configuration with keycloak

---

.github/workflows/tests.yml
Makefile

We don't want to use any [Go toolchain](https://go.dev/doc/toolchain) as it introduces another variable (an uncontrolled one at that) in the testing matrix.

Do not use Go toolchain directive

---

lxd/network/driver_common.go

Includes cherry-pick from https://github.com/lxc/incus/pull/1818.

lxd/network/common: Handle missing BGP peer (from Incus)

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/config.yml

This PR uses the new [issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms) option to reproduce the legacy issue template at `.github/ISSUE_TEMPLATE.md` with web form fields. It adds to the contents of the legacy template a checkbox for the issue submitter to indicate they have searched for duplicate issues.
It also adds a configuration file that affects the [template chooser](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser). The configuration disables blank templates and sets a link in the template chooser to the Discourse forums …

github: add issue form and template configuration

---

lxd/firewall/drivers/drivers_nftables.go

Fixes regression from 3725dbc78ca8f51b076639a7d5118ec36b46da10
Missing "-" in generated nftables rules.
Fixes https://github.com/canonical/lxd/issues/15257

Firewall: Fix regression in nftables port range rules

---

client/connection.go
client/util.go

The modern post-quantum curve that has been enabled by default with [Go 1.23+](https://go.dev/doc/go1.23) causes the `ClientHello` message to be much bigger than before due to MLKEM/Kyber needing big `key_share`. This size inflation sometimes causes the `ClientHello` message to be split over multiple (usually 2) TCP packets.
This message splitting can confuse broken middleboxes and lead them to abort the connection (`connection reset by peer`). This problem is well explained [here](https://tldr.fail/).
Those middleboxes are more likely to be intercepting connections to images servers (`images:`, `ubuntu:`, etc) than `lxc` to `lxd` communication. As such, do not use modern post-quantum curves when dealing with `simplestreams` remote.
Addresses #14839.

client/connection: use LegacyCurvesOnly for simplestreams connections

---

doc/custom_conf.py

Links to `localhost:8080` and `localhost:8080/admin` I added in recently merged Keycloak docs (https://github.com/canonical/lxd/pull/15216) are not passing linkcheck (the Keycloak docs PR skipped the linkcheck test). This PR adds them to the linkcheck_ignore list.

doc: add localhost:8080 to linkcheck_ignore

---

lxc/storage_volume.go
lxd/api_internal.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/instance_utils.go
lxd/storage/backend_lxd.go

Whilst rebasing https://github.com/canonical/lxd/pull/15129 I found new linter warnings due to the switch of `golangci-lint` to v2. 
I have decided to move the bits into a separate PR to reduce the changes in the original PR.

lint: Fix new warnings from switching to `golangci-lint` v2

---

doc/howto/cluster_form.md
doc/howto/initialize.md
doc/howto/network_create.md
doc/howto/network_ovn_setup.md
doc/installing.md
doc/tutorial/first_steps.md
doc/tutorial/ui.md

This PR adds hidden annotations in certain LXD pages that only appear when viewed through the [MicroCloud docs integration](https://canonical-microcloud.readthedocs-hosted.com/en/latest/lxd).
Their purpose is to advise MicroCloud users when they are viewing parts of the LXD documentation that are not relevant for MicroCloud (such as LXD initialization instructions, since MicroCloud handles initializing LXD), or only partially relevant (such as the UI tutorial, where the latter part about using the UI is relevant, but the initial part about installing LXD is not).

doc: show annotations in microcloud docs integration

---

doc/tutorial/first_steps.md

Currently tutorial provide steps to create both container and virtual machine instances. But it doesn't verify lxd host support for kvm virtualization. Due to this if user try to create a virtual machine on a non-supported lxd host following error will be prompted.
```
Launching ubuntu-vm
Error: Failed instance creation: No suitable cluster member could be found
```
This change will add additional steps to the tutorial to install cpu-checker and check output of kvm-ok status. Similar approach is followed in MAAS documentation.

feat(doc): add steps to verify lxd host support for vms

---

lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go

Addresses #15254 to silence this kind of log spam for instances/volumes backed by `ceph`:
```
Mar 27 19:34:37 micro1 lxd.daemon[1779]: time="2025-03-27T19:34:37Z" level=warning msg="Error getting disk usage" err="Cannot get disk usage of unmounted volume when ceph.rbd.du is false" instance=vm01 instanceType=virtual-machine project=e2e-testing
Mar 27 19:35:34 micro1 lxd.daemon[1779]: time="2025-03-27T19:35:34Z" level=warning msg="Error getting disk usage" err="Cannot get disk usage of unmounted volume when ceph.rbd.du is false" instance=vm01 instanceType=virtual-machine project=e2e-testing
Mar 27 19:35:35 micro1 lxd.daemon[1779]: time="2025-03-27T19:35:35Z" level=warning msg="Error getting disk usage" err="Cannot get disk usage of unmounted volume when ceph.rbd.du is false" instance=vm01 …
```

Lower log level of error messages when checking disk usage fails

---

client/interfaces.go
client/lxd_instances.go
doc/api-extensions.md
doc/rest-api.yaml
lxc/copy.go
lxc/move.go
lxd/instance.go
lxd/instance_post.go
lxd/instances_post.go
shared/api/instance.go
shared/version/api.go
test/suites/container_move.sh
test/suites/snapshots.sh

Fixes https://github.com/canonical/lxd/issues/15078

lxd: Fix target profile on snapshot copy

---

doc/rest-api.yaml
lxd/identities.go

The swagger comment was incorrectly referencing the struct type name.

doc: Fix swagger definition for `POST /1.0/auth/identities/tls`

---

lxd/storage/drivers/driver_ceph_utils.go
test/suites/storage_volume_import.sh

Ceph storage has a limitation that if the size of the image is less than 512B, the image is not writable.
Fixes: https://github.com/canonical/lxd/issues/15196

Storage: Fix import of iso images smaller than 512B on ceph

---

lxd/instance/drivers/driver_qemu.go

In QEMU 9.1.1, using the device serial as a default for its ID fails if the serial is longer than 20 characters (https://github.com/lxc/incus/issues/1536). So a cherry pick that we performed from Incus made it so we explicitly provide the `device_id` (https://github.com/canonical/lxd/pull/15154/commits/e0f99467da0ae6431c716d1ce6a66d41d34d104b). This changed the format the `device_id` takes and broke our tests (https://github.com/canonical/lxd-ci/actions/runs/13923914369/job/38963532720).
This proposes an improvement to the format of `device_id`. I concluded from manually testing that we don't have a lenght limit for `device_id`, we can just use the full `lxd_<escaped_lxd_device_name>`. lxc-ci tests are adapted in https://github.com/canonical/lxd-ci/pull/434.

VM: Use full device name in qemu's `device_id`

---

client/util.go
lxc/config.go
lxc/profile.go
lxd/api_cluster.go
lxd/api_internal.go
lxd/db/cluster/instances.go
lxd/db/cluster/open.go
lxd/db/cluster/open_test.go
lxd/db/cluster/update.go
lxd/db/cluster/update_test.go
lxd/instance/drivers/driver_common.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/instance_put.go
lxd/instance_snapshot.go
lxd/instances_post.go
lxd/profiles.go
lxd/storage/backend_lxd.go
lxd/storage_volumes_utils.go

Work on #15277 has thrown a lot of linter errors. I think this is due to updates to `golangci-lint` as a lot of these files have already had lint errors fixed, but now the linter seems to be catching a lot more cases (especially unused parameters).
There were also a couple of other things I fixed/removed along the way. Adding them here to keep the size of the other PR down and focused.

Pre- instance-placement fixes

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/feature-request.yml

- Adds `type: "Feature"` and `type: "Bug"` to feature request and bug report template forms respectively
- Replaces `container` wording with `instance` in bug report template form

github: Update issue template forms

---

lxd/api_internal.go
lxd/daemon.go
lxd/daemon_storage.go
lxd/instances.go
lxd/operations.go
test/includes/check.sh
test/includes/lxd.sh
test/includes/operations.sh
test/main.sh
test/suites/shutdown.sh

closes: #13460 
JIRA ticket: https://warthogs.atlassian.net/browse/LXD-2600

lxd: Make the LXD shutdown sequence more concurrent to avoid long-running operations blocking unrelated instances shutdown 

---

lxd/instance/drivers/driver_qemu.go

closes https://github.com/canonical/lxd/issues/15082
When configuring VMs with `limits.cpu.nodes` but without CPU pinning (using a simple CPU count in `limits.cpu`), the NUMA node selection was not being properly applied. This resulted in VM memory always being allocated from NUMA node 0, regardless of the specified node in `limits.cpu.nodes`.
The issue occurs because the `cpuTopology` function only populates the NUMA node mapping (nodes map) when CPU pinning is used, but not when using a simple CPU count. As a result, when limits.cpu.nodes is specified along with a simple CPU count like `limits.cpu=4`, the memory would still be allocated from NUMA node 0 instead of the requested node.
This modifies the `cpuTopology` function to handle NUMA node assignments correctly even when using a …

VM: Fix NUMA node binding when using CPU count without pinning

---

lxd/device/tpm.go
lxd/storage/drivers/driver_ceph.go
lxd/storage/drivers/driver_cephfs.go
lxd/storage/drivers/driver_zfs.go

ATM, if no `zpool` of the right version can be found in the LXD snap, this error is displayed:
```
root@v1:~# lxc storage create zfs zfs
Error: Required tool 'zpool' is missing
```
There is also a more verbose error logged by the snap'ed daemon but it requires the user to look at `journalctl -u snap.lxd.daemon`.
Make the workaround more easily discoverable by tweaking the error message.

lxd/storage/drivers/zfs: suggest `zfs.external` if in snap and ZFS tools are missing

---

test/suites/backup.sh

Fixes the flaky test of volume export on cephfs.
Tested with custom PR on github which isolates the core of the backup_volume_export test and runs it in a loop:
https://github.com/canonical/lxd/pull/15306
Without the sync call, the test suite failed after 17 runs of the inner loop. With the sync, it run for 100 runs without failure.

test/suites/backup: On cephfs add sync calls after `file push`

---

lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
test/suites/migration.sh

(cherry picked from commit b4399dfc50a5238c9a63434a37205358c16489bf)
Tested with:
```
$ lxc init images:alpine/edge u2
$ lxc config device override u2 eth0 ipv4.address=10.142.210.80      # Add custom IP address to eth0
$ lxc snapshot u2 snap2
$ lxc copy u2 tester: -d eth0,ipv4.address=10.64.126.100                    # From target remote IP range
Error: Failed migration on source: Error from migration control target: Failed creating instance snapshot record "u2/snap2": Failed initialising instance: Invalid devices: Device validation failed for "eth0": Device IP address "10.142.210.80" not within network "lxdbr0" subnet
```

lxd/instance: Don't enforce device/config validation on snapshots (from Incus)

---

doc/.sphinx/_static/swagger-override.css

Cherry pick from https://github.com/lxc/incus/pull/1599.
Forces white background for SwaggerUI-generated API reference at https://documentation.ubuntu.com/lxd/en/latest/api/ even if dark mode is selected, making it easier to read.

doc: Force white background for swagger API (from Incus)

---

lxd/instance/drivers/driver_qemu.go

Fixes regression introduced by bbdc307da8b632b5eb2fae943f8dc224e8c741b4

VM: Fix regression when hotplugging qemu virtio-blk drives in addDriveConfig

---

doc/api-extensions.md
doc/rest-api.yaml
lxd/resources/storage.go
lxd/storage/block/utils.go
lxd/storage/drivers/utils.go
shared/api/resource.go
shared/util.go
shared/version/api.go

This allows MicroCloud checking (https://github.com/canonical/microcloud/pull/724) whether or not a device is already used after fetching the list of disks from `/1.0/resources`. 
The PR adds another field `device_fs_uuid` to both disks and partitions returned from the resources endpoint.
A new API extension `resources_device_fs_uuid` is added to indicate this change.

Resources: Add device's filesystem UUID if present

---

doc/api-extensions.md
doc/rest-api.yaml
lxd/resources/storage.go
lxd/storage/block/utils.go
lxd/storage/drivers/utils.go
shared/api/resource.go
shared/util.go
shared/version/api.go

Backports https://github.com/canonical/lxd/pull/15310.

Resources: Add device's filesystem UUID if present (stable-5.21)

---

lxd/device/config/device_runconfig.go
lxd/device/device_utils_disk.go
lxd/device/device_utils_unix.go
lxd/device/disk.go
lxd/device/gpu_physical.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/storage/backend_lxd.go
lxd/storage/pool_interface.go
lxd/storage/utils.go

The startVM function was always using the project.StorageVolume() function to derive the underlying ceph rbd image name. This is incorrect when the volume being attached is from an instance in the default project because the `default_` prefix is only added for custom volumes, not instance volumes.
Additionally this function was also using the instance or volume's project name directly rather than using the existing `storageProjectName := project.StorageVolumeProjectFromRecord()` variable. This is a problem because for custom volumes it wasn't taking into account the value of `features.storage.volumes` set on the project (indicating the effective project for a custom volume).
So instead I switched to using the same invocation pattern we already have from disk.mountPoolVolume() function. …

Device: Fix disk attachment of ceph instance volumes in default project

---

.github/workflows/tests.yml

With this change, most use of `actions/upload-artifacts` have a `retention-days` specified to avoid the implied default of 90 days. 
The only exception are per-OS `lxd-clients` artifacts as those are only uploaded on `push` events and can be useful for those wanting binaries like `lxd-benchmark` and `lxd-migrate`.

github: set artifact retention days

---

lxd/device/disk.go

This fixes an issue where detaching a running VM's (v1) root volume (using ceph) from another running VM (v2) (only allowed when `security.shared=true`) was incorrectly triggering an unmount of the attached VM's root volume from the running VM (v1) due to the mount reference counters not being correctly maintained when attaching/detaching v1's root volume from v2.
Reproducer:
```
lxc launch ubuntu:24.04 v1 --vm -s ceph
lxc launch ubuntu:24.04 v2 --vm -s dir
lxc storage volume set ceph virtual-machine/v1 security.shared=true
lxc config device add v2 v1-root disk source=v1 pool=ceph source.type=virtual-machine
lxc config device remove v2 v1-root 
```

Storage: Fix missing mount reference counting when attaching ceph VM root volume to another VM

---

lxd/api_cluster.go
lxd/api_project.go
test/suites/clustering.sh

Follow up to https://github.com/canonical/lxd/pull/15119
Cluster group used-by URLs we're not being filtered by what the caller is able to view. This allowed restricted users to see the URLs of projects that they do not have access to.

Auth: Filter cluster group used by URLs

---

doc/custom_conf.py
doc/redirects.py

Currently there are ~40+ files in the `doc/` directory that should be inside one of the category directories (`doc/howto`, etc). When those files are moved, their URLs will change, so we will need to redirect them to preserve links from external sources.
Redirects are handled by Sphinx using a `redirects` dict currently defined in `custom_conf.py`. Adding ~40+ new redirects to this dict would clutter `custom_conf.py`. This PR prepares for the move by extracting that dict to a new `redirects.py`, which is then imported by `custom_conf.py`.

doc: use external file to store redirects

---

lxd/instance/drivers/driver_qemu.go

This restores the previous behaviour that qemu had of setting the device_id to the serial concatenated to 20 chars.
We want to maintain this behaviour in 5.21 LTS so as not to break guests who rely on that naming scheme.
However it will change in LXD 6.4 and onwards.

VM: Restore qemu guest /dev/disk/by-id naming stability (stable-5.21)

---

lxd/api_cluster.go
test/suites/clustering.sh

This fixes a regression introduced in https://github.com/canonical/lxd/pull/15314/commits/cc14d2b45785a58b74315ef581ccd6753d5ed563.
When querying `GET /1.0/cluster/members` without `recursive=1` a simple list of cluster members should be returned.
This was causing errors in MicroCloud as it polls LXD until the API returns the first cluster member after enabling clustering. As an example see https://github.com/canonical/microcloud/actions/runs/14488020785/job/40637889229?pr=754#step:3:4054

Fix: Return cluster members in non-recursive mode

---

doc/custom_conf.py

Seems to be denied when running from Github (403 response).

Doc: Ignore link checking of https://www.schlachter.tech/solutions/pongo2-template-engine/

---

lxd/instance_instance_types.go

Includes https://github.com/canonical/lxd/pull/15132.

lxd/instance_instance_types: Update instanceRefreshTypes function to use all.yaml instance type file (stable-5.0)

---

doc/.custom_wordlist.txt
doc/howto/instances_configure.md
doc/howto/network_acls.md
doc/rest-api.md

Re-submit of https://github.com/canonical/lxd/pull/15274
Improvements to network ACLs docs, including:
- Document the ability to provide a YAML file to create an ACL (previously only in man page)
- Clarify that the only arguments accepted for CLI-based ACL creation (aside from a YAML file) are the ACL name and the custom user keys
- Add missing sections for listing, showing, renaming, and deleting ACLs
- Add API instruction counterparts to all CLI instructions
- Add links to relevant parts of API reference
- Add command syntax examples
- Improve descriptions of ACL and ACL rule properties
- Detailed information about how to edit the ACL via the API, where and how to use PATCH and POST
- Clarify how logging works
- General formatting improvements and copyedits
- Also updated the PUT vs …

doc: improve network ACLs docs

---

lxd/device/nic_ovn.go
lxd/network/driver_bridge.go
lxd/network/driver_common.go
lxd/network/driver_ovn.go
lxd/network/driver_physical.go
shared/network_ip.go
shared/network_ip_test.go
test/suites/network_ovn.sh

Fixes https://github.com/canonical/lxd/issues/15221.
**Changes:**
- Validate that listen addresses of network forwards and load balancers do not overlap with OVN ranges. However, allow forwards and load balancers on OVN networks using `volatile.network.ipv4.address` and `volatile.network.ipv6.address` as listen address.
- Validate that `ipv4.routes` and `ipv6.routes` on physical and bridge networks are compatible with existing forwards and load balancers.
- Prevent using IPs from OVN range for NIC passthrough to an instance using `ipv4.routes.external` and `ipv6.routes.external`.
- Add tests to check that forwards and load balancers cannot be created with a listen address that overlaps with OVN ranges.
- Add tests to check that `ipv4.routes` and `ipv6.routes` cannot be removed for …

Network: Improve network validation

---

doc/howto/initialize.md

Per MAAS docs has changed the anchor id.

doc: update broken maas anchor link

---

lxd/storage/backend_lxd.go

This implements `SyncFS` when snapshotting custom volumes, similarly to what we already do with instance volumes.
This also includes a warning it fit fails for either instance or custom volumes. In a different manner as `fsfreeze`, we do not expect `sync` to fail even if the filesystem is busy.
I was at odds on whether I should gate SyncFS on `RunningCopyFreeze` as even after some digging on the PRs that populated this field on each of the drivers, it was unclear on what specifically determined the value of  `RunningCopyFreeze` for each driver.
After some more research on each driver's inner workings, I got to the conclusion that `RunningCopyFreeze=false` indeed means the driver syncs the volume on snapshot (as snapshots generally follow a similar mechanism to the one used for copy).
As …

storage: Instance and custom volume snapshot consistency

---

lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go

This isn't a cherry-pick, but rather inspiration from a change in Incus.
At this point LXD's code base has diverged somewhat from Incus and the exact same bug was not present, however I have taken the point and run with it by making the scheduler re-run occur after 2 other places that might impact the scheduler.
Inspired by https://github.com/lxc/incus/pull/1938

Instance: Run CPU scheduler after DB changes made (from Incus)

---

lxd/devlxd.go
lxd/response/response.go

Fixes the regression introduced in https://github.com/canonical/lxd/pull/15317 - the devLXD endpoint `GET /1.0` should be allowed despite `security.devlxd` not being enabled.

devlxd: Enable access to GET devlxd/1.0 (regression)

---

lxd-user/main.go
lxd-user/main_daemon.go
lxd/api_cluster.go
lxd/cluster/gateway.go
lxd/cluster/membership.go
lxd/daemon.go
lxd/db/cluster/open.go
lxd/main.go
lxd/main_daemon.go
lxd/main_forkfile.go
lxd/networks.go

In some cases the `cluster.https_address` can become unset in the local DB and this can cause LXD to try and start up
in standalone mode and enter a start up loop that cannot be easily stopped.
Adds sense check to detect when this situation occurs.

lxd: Improve clustering start up checks

---

lxd/daemon.go
lxd/logging.go

Fixes https://github.com/canonical/lxd/issues/14791.
This pull request refactors the `expireLogsTask` functions to use the `Daemon` struct directly instead of the `state.State` object to avoid using a long lived state.

VM: Use fresh state in `expireLogsTask`

---

lxd/network_acls.go

Follow up to https://github.com/canonical/lxd/pull/15369.

lxd: Use `api.NewURL()` to construct `network-acl` result urls

---

lxd-agent/state.go
lxd/device/disk.go
lxd/network/openvswitch/ovn.go
lxd/network/openvswitch/ovs.go
lxd/storage/drivers/driver_btrfs_volumes.go
lxd/storage/drivers/driver_zfs_volumes.go
shared/api/instance.go

Those tweaks were accumulated while manually reviewing the commits moving away from `fmt.Sprintf()` and `fmt.Sprint()`.

Random assorted tweaks

---

lxd/api_internal.go
lxd/main_daemon.go

To prevent systemd from restarting the service.

lxd: When shutting down by request ensure non-error exit status

---

lxd/device/gpu_physical.go

Fixes https://github.com/canonical/lxd/issues/15372.

lxd/device: Only remove GPU CDI device files for device being started

---

.github/actions/install-lxd-runtimedeps/action.yml

If not there, pull it from the archive if on 24.04+ otherwise from the snap store. GitHub CI runners already have `yq` installed.

github: actions/install-lxd-runtimedeps only install `yq` if not there already

---

lxc/config/default.go

The images remote is hard-coded and is therefore static.
(part 2 of #15311)

lxc/config: Make the images remote static

---

doc/getting_started.md
doc/howto/index.md

Contributing guidelines should be a little easier to find in the docs.
Also, I noticed that the diff of `CONTRIBUTING.md` and `doc/contributing.md` is quite substantial; should these documents be maintained as one document instead?

doc: Move contributing out of "Getting Started"

---

lxd/main_waitready.go

We are calling `/internal/ready` in a loop already, so no need to call `/1.0` in a loop too.

lxd: No need to call /1.0 repeatedly in waitready

---

lxc/cluster.go
lxc/cluster_group.go
lxc/completion.go
lxc/copy.go
lxc/image.go
lxc/image_alias.go
lxc/list.go
lxc/move.go
lxc/network.go
lxc/network_acl.go
lxc/network_zone.go
lxc/profile.go
lxc/project.go
lxc/publish.go
lxc/remote.go
lxc/storage.go

We currently have a boolean to indicate if `cmpRemotes` should return all remotes, or just those that are not image servers (minus the default). This isn't specific enough when completing for commands such as `lxc remote set-url`, which cannot be performed on static remotes.
This is part 4 of splitting up #15311 and depends on #15458 (marking as draft until that is merged).

lxc/completion: Use filters when completing remotes

---

lxc/completion.go
lxc/export.go
lxc/file.go
lxc/import.go
lxc/main.go

While adding tests to #15311 I found that we were missing completions for many top-level commands. `lxc import` and `lxc export` were two of these. I figured we can have a quick win by refactoring the existing `cmpFiles` function, which wasn't just comparing files, but also comparing instances. This PR makes the function usage clearer and adds the missing completions.
Additionally, I've removed a completion function that was defined twice for `lxc file delete` and also prevented file completions from happening by default when no other completion function has been set.

lxc: Refactor file completion

---

lxc/completion.go
lxc/image.go
lxc/image_alias.go
lxc/init.go
lxc/launch.go

After implementing #15458 I noticed a few things about image comparison.
1. Public image remotes were being suggested for destructive/mutative operations on images.
2. No image fingerprints would be suggested even though they are equally valid, just not human friendly. 
This is updated to allow specifying if only instance server remotes should be suggested (that allow image mutation/deletion) and to suggest image fingerprints in certain circumstances (see comments).
This is part 6 of splitting up #15311 and depends on #15467

lxc: Image alias/fingerprint completion

---

lxc/completion.go
lxc/rename.go
lxc/restore.go
lxc/snapshot.go

This refactors snapshot completions to use the new established patterns and top-level resource comparisons introduced in #15458. Completions for snapshots are factored out into another method which accepts a remote name, an instance name, and a partial snapshot name.

lxc: Refactor snapshot completions

---

lxc/completion.go

Addresses https://github.com/canonical/lxd/pull/15477/commits/39439ea80becf899eff375203f7111e60d98fb9f#r2064096914

lxc/completion: Use `strings.HasPrefix` over `strings.Contains`

---

lxc/completion.go
lxc/config.go
lxc/config_device.go
lxc/profile.go

Updates completions for config options to suggest only `core.` rather than including all sub-options. This reduces the number of completions shown to the user for readability, while also allowing discoverability.
The driver behind this change was the testing added in #15311 (which will be re-added in a later PR) from which I found that `lxc config set <TAB>` did not show any server completions unless I specified the remote (e.g. `local:`). Similarly, I noticed lots of incorrect config keys being suggested when running `lxc profile device add ...` which could only be fixed by parsing the subtype of the device from the metadata API.
This is part 5 of splitting up #15311 and depends on #15467

lxc: Config option completion

---

lxd/storage/drivers/driver_common.go

Fixes https://github.com/canonical/lxd/issues/15411.
When moving the GPT alternative header, `sgdisk` will exit with code 2 if no valid GPT header is found (read error) or code 3 if it detects an MBR disk without `-g` (write skipped). Neither condition represents a failure in our context, there is simply no GPT backup header to move. Treat both codes as non-fatal so raw/MBR images continue without error, while still propagating any other `sgdisk` failures.

Storage: Skip GPT alt‐header move on non-GPT disks (handle `sgdisk` exits 2 & 3)

---

lxc/query.go
lxd/api_internal.go
lxd/daemon.go
lxd/main_waitready.go
lxd/network/driver_bridge.go

So its available for use with gateway heartbeats.
Also several other LXD start up and shutdown improvements.

lxd: Make d.gateway.Cluster available even if OpenCluster returns with PreconditionFailed

---

client/lxd_instances.go
lxd/instance_console.go
lxd/instance_exec.go
shared/ws/upgrader.go

To avoid prematurely disconnecting console clients using LXD UI.
Closes https://github.com/canonical/lxd/pull/15439 as is unnecessary with this change.
Fixes https://github.com/canonical/lxd-ui/issues/1193

lxd: Generate server-side initiated web socket pings for remote console connections

---

lxd/main_waitready.go

https://github.com/canonical/lxd/pull/15495#pullrequestreview-2807703090

lxd: Use uint64 for waitready timeout flag for consistency with server side

---

.github/workflows/security.yml

This downloads the KEV json list in `trivy-repo` and caches it to use in `trivy-snap`. Then in both jobs uses it to check which alerts IDs are included in it and if so, tag the alert with `(KEV)`

github: Add KEV matching to security alerts

---

lxc/cluster.go

Fixes https://github.com/canonical/lxd/issues/15222.

lxc/cluster: Improve error message when evacuating offline member

---

doc/userns-idmap.md

Cherry-picked from https://github.com/lxc/incus/pull/1353
Adapted during cherry-pick to use LXD terminology (say LXD where it says Incus)
Confirmed that the change from `lxd/incus` to `root` for user name occurred in [this 2017 commit](https://github.com/canonical/lxd/commit/1f6218101f16c1a1d5521dc5bfd97d532626d03b)

doc/idmap: Clarify subuid/subgid configuration (from Incus)

---

lxd/db/cluster/auth_groups.mapper.go
lxd/db/cluster/cluster_groups.mapper.go
lxd/db/cluster/config.mapper.go
lxd/db/cluster/devices.mapper.go
lxd/db/cluster/identities.mapper.go
lxd/db/cluster/identity_provider_groups.mapper.go
lxd/db/cluster/images.mapper.go
lxd/db/cluster/instances.mapper.go
lxd/db/cluster/nodes_cluster_groups.mapper.go
lxd/db/cluster/operations.mapper.go
lxd/db/cluster/profiles.mapper.go
lxd/db/cluster/projects.mapper.go
lxd/db/cluster/snapshots.mapper.go
lxd/db/cluster/warnings.mapper.go
lxd/db/generate/db/constants.go
lxd/db/generate/db/method.go

Discussed here https://github.com/canonical/lxd/pull/15502#discussion_r2071295337 and quickly put up a PR as I only found a few other cases. Verified that there are no more generated occurrences of this using `grep -r 'fmt\.Errorf[^%]*)' lxd/db/cluster | grep -c 'mapper.go'`.

Stop generating `fmt.Errorf` calls without format directives in `lxd-generate`

---

lxd/storage/backend_lxd.go
lxd/storage/utils.go
test/suites/backup.sh

Fixes a general bug in LXD which caused an instance's backup file not to be updated when updating the storage pool of its root volume.
This was discovered whilst working on https://github.com/canonical/lxd/pull/15523.

Storage: Update instance backup file when root vol pool gets updated

---

lxd/instance.go
lxd/instance/drivers/driver_common.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/instance_interface.go
lxd/instance_snapshot.go
lxd/storage/backend_lxd.go
lxd/storage/backend_mock.go
lxd/storage/pool_interface.go
lxd/storage_volumes_snapshot.go
test/suites/snapshots.sh
test/suites/storage_snapshots.sh

Applies the changes suggested in https://github.com/canonical/lxd/pull/15503#discussion_r2070417058 for both instances and custom vols. 
In addition the test suite is modified to not anymore strip off the microsecond portion of the timestamps.
Furthermore a bug is fixed which always set the zero timestamp for an instance's snapshot vol expiry. Before only the actual instance snapshot DB entry contained the expiry date. A small test for this is added too.

Storage: Fix snapshot expiry date test regression

---

lxd/device/nic_bridged.go
test/suites/container_devices_nic_bridged.sh

Fixes https://github.com/canonical/lxd/issues/15300.

lxd/device: Skip address conflict validation for instance NIC rename

---

.github/workflows/tests.yml

Moving to https://launchpad.net/~lxd-snap/+snaps

github: Update repo of lp-snap-build (stable-5.0)

---

.github/workflows/tests.yml

Moving to https://launchpad.net/~lxd-snap/+snaps
(cherry picked from commit 5d6b575a0359e96fc9dd8d57f7add17794c1a462)

github: Update repo of lp-snap-build (stable-5.21)

---

.github/SUPPORT.md
CONTRIBUTING.md
README.md
doc/README.md
doc/custom_conf.py
doc/howto/cluster_form.md
doc/myconf.py
grafana/LXD.json
lxd/api.go
lxd/instance/drivers/driver_qemu.go
lxd/main_cluster.go
scripts/setup-grafana.sh

This PR updates absolute links to both the MicroCloud and LXD documentation due to both recently changing URLs to remove /en/ from the path and, in MicroCloud's case, moving to a subdirectory of documentation.ubuntu.com. Redirects are already in place, but this PR reduces the need for redirects.

Update absolute docs links

---

doc/howto/snap.md

This PR updates the instructions for using the Snap Store Proxy, replacing them with instructions for the Enterprise Store, which has replaced the Snap Store Proxy. It also adds an admonition to instruct Snap Store Proxy users to migrate to the Enterprise Store.

doc/howto/snap: update snap store proxy to enterprise store

---

doc/clustering.md
doc/explanation/authorization.md
doc/explanation/instances.md
doc/explanation/performance_tuning.md
doc/explanation/security.md
doc/howto/cluster_form.md
doc/howto/grafana.md
doc/howto/images_create.md
doc/howto/snap.md
doc/index.md
doc/instances.md
doc/projects.md
doc/reference/remote_image_servers.md
doc/reference/storage_cephobject.md
doc/reference/uefi_variables.md
doc/reference/vm_live_migration_internals.md
doc/restapi_landing.md

A `relatedlinks` link that has the title hard-coded is still trying to fetch from the link and is causing a build failure [here](https://launchpadlibrarian.net/791856650/buildlog_snap_ubuntu_noble_s390x_lxd-latest-candidate_BUILDING.txt.gz) as a result. Using double quotes instead of single quotes around the link might help with this. This PR updates all relatedlinks (including discourse links; they use the same relatedlinks extension) in the documentation to use double quotes. At the least, it won't hurt.

doc: use double instead of single quotes around relatedlinks

---

lxd/daemon.go
lxd/events/common.go
lxd/events/devlxdEvents.go
lxd/events/events.go
lxd/instance_exec.go
lxd/loki/loki.go
lxd/operations/operations.go
lxd/patches_test.go
lxd/storage/s3/miniod/miniod.go
shared/cancel/canceller.go
shared/cancel/canceller_test.go

Previously `Canceller` embedded a `context.WithCancel` and its associated cancel function.
This made it easy to leak the go routine created in `context.WithCancel` in a way that linters were not detecting.
This reworks `Canceller` to still implement the `context.Context` interface (so it can be passed to other functions as a context.Context), but avoids using `context.WithCancel` internally.

shared/cancel: Reworks Canceller to not embed Context

---

lxd/auth/drivers/openfga.go
lxd/instance_post.go
shared/entity/type.go
shared/entity/type_test.go
shared/entity/url.go
test/suites/clustering_move.sh

This PR fixes couple of issues in the auth subsystem when moving instances. 
Unfortunately, [maintaining instance ID's](https://github.com/canonical/lxd/issues/14932#issuecomment-2643099960) when moving them between pools/members became quite difficult - we'd need quite a large rewrite. Happy to talk further on this, but I'm not sure the pros of maintaining the instance ID outweigh the cons. The main benefit is not needing to update database entries that reference the instance by ID, whereas the main drawback is that move and copy would use different code paths, meaning more code to test and maintain.
In any case, for now, I've opted to update the permissions table to point to the new instance ID.
Closes #14932

Auth: Maintain permissions on instance move

---

doc/userns-idmap.md

This PR notes that the Allowed ranges section is not needed for the LXD snap, due to the daemon running as root in the snap environment and disregarding the `/etc/sub{u,g}id` files.

doc: add info about snaps and user idmaps

---

lxd/storage/backend_lxd.go

Closes https://github.com/canonical/lxd/issues/14256.
This improves error handling in `CreateInstanceFromMigration` by validating instance root disk size against the migration source volume size.
Cherry-picked from https://github.com/lxc/incus/pull/1971 and https://github.com/lxc/incus/pull/2041.

Improve migration API error handling (from Incus)

---

lxd/db/cluster/images.go
lxd/images.go

Otherwise leave UpdateSource as nil.
Fixes regression from https://github.com/canonical/lxd/pull/15548

lxd/db/cluster/images: Only populate update image source if found

---

test/includes/lxd.sh
test/main.sh
test/suites/exec.sh

This addresses a few issues I ran into when running the LXD test suite in a minimal (`ubuntu-minimal-daily:24.04`) VM with just enough preparation done through cloud-init.

Minor fixes

---

.github/workflows/tests.yml

Rather than build lxc and lxd-agent binaries again, simply `install --strip` the already compiled versions into a temporary directory. `install --strip` is functionally equivalent to `cp`+`strip`. This should make the workflow a tad faster.

github: improve efficiency of lxc/lxd-agent bin size checks

---

.github/workflows/tests.yml

Binaries built with coverage information are inherently bigger than
regular/production builds.

github: only check lxc/lxd-agent bin sizes of not built for coverage

---

lxd/certificates.go
test/suites/clustering.sh

In #15554 the server certificates were removed, this broke the cluster. This PR does not add a mechanism for re-adding server certificates as the author suggests, instead it prevents deletion of server certificates via `DELETE /1.0/certificates`. There is no reason that a server certificate should be deleted. Updating server certificates is still allowed as this could be used to rotate expiring certificates, but no process is documented for this yet.

Prevent server certificate deletion

---

staticcheck.conf

Some linters like VSCode's Go extension and TIOBE scanner do not consult the `.golangci.yaml` so reporting many problems with error strings not starting with a capital letter.

staticcheck.conf: add dedicated config to ignore ST1005

---

test/suites/clustering_move.sh

This was missed with https://github.com/canonical/lxd/pull/15534/commits/f31af2ba509efe9a1bb8c4a55d76d06f845c4bea.
Excerpt from today's tests:
```
++ query cluster:/1.0/instances/c1
suites/clustering_move.sh: line 65: query: command not found
```

tests: Fix `command not found` error

---

README.md

Include information about Ubuntu Pro for instances in the Commercial support section of the README (which is pulled via an include into the docs' [How to get support guide](https://documentation.ubuntu.com/lxd/latest/support/)).

doc: add info about Ubuntu Pro for instances

---

lxd/storage/drivers/driver_cephobject.go

storage: Fix typo in cephobject bucket name prefix error

---

.github/workflows/codeql.yml

The simple CodeQL config (which requires **not** having any `.github/workflows/codeql.yml` file) started scanning GH actions.
Add that to our advanced configuration.
https://codeql.github.com/docs/codeql-overview/supported-languages-and-frameworks/
https://codeql.github.com/docs/codeql-language-guides/codeql-for-actions/

github: ask codeql to check actions themselves

---

lxd/storage/backend_lxd.go
lxd/storage/utils.go
test/suites/backup.sh

This reverts https://github.com/canonical/lxd/pull/15527.
Instead of updating each instance's backup config file when updating the pool, we should rather update the file for individual instances when starting them to not require mounting each instance's vol when updating the pool.

Revert "Storage: Update instance backup file when root vol pool gets updated"

---

lxd-migrate/utils.go
lxd/storage/s3/miniod/miniod.go

This is in preparation of Go 1.25 new vet warning: https://tip.golang.org/doc/next#vet

Use `net.JoinHostPort()` instead of `fmt.Sprintf("%s:%d", host, port)`

---

lxd/api_internal.go
lxd/daemon.go
lxd/main_waitready.go
lxd/networks.go
lxd/state/state.go
lxd/storage.go
test/main.sh
test/suites/waitready.sh

The new MicroCloud e2e test suite surfaced a situation where after rebooting a cluster member, MicroCeph/MicroOVN aren't yet fully up and running which causes LXD not being able to start the networks and storage pools in the first shot. 
Whilst LXD will retry in the background, the `lxc cluster restore` command should not be called until the networks and storage pools are ready.
Therefore two new flags `--network` and `--storage` are added to the `lxd waitready` command to allow a client to wait for all resources to be ready.

Daemon: Extend `waitready` with networks and storage pools

---

test/main.sh

This adds a colorful `$PS1` to the `LXD_INSPECT=1` session
```
...
==> TEST DONE: network_forward (13s)
==> Test result: success
Dropping to a shell for inspection.
Once done, exit (Ctrl-D) to continue
LXD-TEST root@v1:~/lxd/test$ 
```
The `LXD-TEST` bit is red on test failures and green on successes. The welcome text is always in yellow so that it sticks out.

Improve `LXD_INSPECT=1` sessions

---

lxd/storage/backend_lxd.go
lxd/storage/drivers/driver_zfs_volumes.go
test/suites/storage_buckets.sh

The bucket configuration is applied when configured through storage pool `volume.*` options. This is because when no configuration is provided, the default pool configuration applies. Therefore, if custom storage bucket configuration is provided, the volume is incorrectly mounted during bucket activation, as the configuration is not applied.
Fixes #15588

storage: Ensure storage bucket config is applied during bucket activation

---

.golangci.yaml
Makefile

This is the first step to addressing https://github.com/canonical/lxd/issues/15648. It however does not deal with fixing existing violation as our `test/lint/golangci.sh` script only looks at new code.
Also update `golangci-lint` itself as it ships an updated `musttag` version.

Add `musttag` linter now to catch newly missed tags

---

doc/rest-api.yaml
shared/api/instance_backup.go
shared/api/storage_pool_volume_backup.go

Not having the tag shouldn't be a big deal for those two fields as their default is 'version' anyway. But to stay consistent will all the other fields also add the 'version' struct tag for instance and custom vol backups.
The problematic piece is that the metadata used `Version` and not `version`.
Thanks @edlerd for raising this in https://github.com/canonical/lxd-ui/pull/1270#discussion_r2104038375.

API: Add missing 'version' struct tag

---

Makefile

Kadin found out that PR tests would be run with a `lxc` binary built from
sources that didn't match those associated with the PR. He then tracked the
issue down to a faulty commit where the archive produced by `make dist` would
use the sources from the main branch.
The problem is that `git show-ref --hash HEAD` gives the commit hash of the
origin/main's HEAD, not the one corresponding to the current branch.
Switch to using `git rev-parse HEAD` that is specifically made to get the hash
of the current commit.
Also, rename the variable to `COMMIT_HASH` to avoid shadowing the exising
`HASH` one.
Fixes https://github.com/canonical/lxd/commit/113279fb493cc638e37906c5b1afc81e0c8e888a

Makefile: use `git rev-parse HEAD` to get current commit hash

---

.github/actions/download-minio/action.yml
.github/workflows/tests.yml

Also tweak the cluster tests to **not** reclaim disk space as they don't use much so it's best to skip this operation that is sometimes very slow (~2 minutes). This required working around https://github.com/canonical/lxd/issues/14768

Daily caching of external assets

---

lxd/idmap/structs.go

Required as part of https://github.com/canonical/lxd/pull/15523
The lowercase representation can be used as it won't break existing `volatile.idmap.*` config keys. When doing `json.Unmarshal()`, the correct config key is pulled in any case:
* If the JSON key is in uppercase, it will get unmarshalled accordingly even if the lowercase tag is set
* If the JSON key is in lowercase, it matches the struct tag and will work as expected
* If the JSON key is in lowercase, but LXD expects the uppercase (no tag set, old version), it still unmarshalls accordingly
A patch is not required as all of the containers `volatile.idmap.*` config keys are getting updated progressively when LXD rewrites the keys.

idmap: Add missing struct tags (musttag)

---

Makefile

One of the nice side effect of those changes is that it's now possible to easily build LXD without having to bother exporting an variables. One just needs a machine with all the build-deps already installed and `make deps && make` is all it takes.
```
$ lxc launch ubuntu-minimal-daily:24.04 v1 --vm -p lxd-test
Launching v1
root@v1:~# cd lxd
root@v1:~/lxd# make deps && make
...
LXD agent built successfully
CGO_ENABLED=0 go install -v -trimpath -tags netgo ./lxd-migrate
github.com/canonical/lxd/shared/i18n
archive/tar
github.com/canonical/lxd/lxd/linux
github.com/canonical/lxd/lxd/backup/config
github.com/canonical/lxd/lxd/storage/block
github.com/canonical/lxd/lxd/rsync
github.com/canonical/lxd/lxd/migration
github.com/canonical/lxd/shared/cmd
github.com/canonical/lxd/shared/eagain …
```

Makefile: add `make tics` target

---

lxd/api.go

- restrict CSP for UI serving to only include the image and assets server domains.

feat(csp) harden content security policy for the ui serving to include only an allowed list of domains

---

doc/howto/instances_routed_nic_vm.md

small fix: command examples in this page refer to a parent network named `my-parent`, and the text called it `my-parent-network` instead

doc: update howto/instances_routed_nic_vm.md

---

lxd/storage_volumes_state.go

- Add target request forwarding to storagePoolVolumeTypeStateGet
1. Given a clustered LXD and a cluster member local pool (driver directory or zfs).
2. Have a volume on cluster member micro2.
3. Then query the api on member micro1 for the volume size. This results in `Storage volume \"test\" in project \"default\" of type \"custom\" does not exist on pool \"dirydir\": Storage volume not found`.
The target param on the endpoint is present, but it is not used for forwarding the request to the right node. When switching the api host to the right cluster member (the one the volume lives on) then the error "...Storage volume not found" vanishes and the right response appears.

lxd: Add target request forwarding to storagePoolVolumeTypeStateGet

---

lxc/export.go
lxc/storage_volume.go

The progress renderer's UpdateOp gets added as a handler to the operation. This allows the operation to update the progress on its own pace.
However when overwriting the initial progress renderer and assigning a new instance of it, this also replaces the underlying mutex which can cause a race if the operation is in the process of calling the orignial progress renderer's UpdateOp, obtains a lock of the mutex but the mutex is in the process of getting replaced because a new instance of the progress renderer is assigned.
This causes the following error https://github.com/canonical/lxd-ci/actions/runs/15387812020/job/43290215796?pr=485
In order to protect the initial mutex, assign the progress renderer for the actual export to a new variable.
```go
func main() {
progress := …
```

lxc: Prevent panic when overwriting the progress renderer

---

lxd/network/driver_macvlan.go
test/suites/container_devices_nic_macvlan.sh

Fixes https://github.com/canonical/lxd/issues/15479.
This is to prevent `lxc network info <net>` failing when used on a macvlan network.
Example output:
```
root@vm1:~/lxd# lxc network info net1
Name: net1
MAC address: ab:cd:ef:12:34:56
MTU: 1500
State: up
Type: broadcast
Network usage:
Bytes received: 0B
Bytes sent: 0B
Packets received: 0
Packets sent: 0
```

Network: Show info for macvlan networks

---

lxd/cloudinit/config.go

More follow-up fixes after #15689 and #15707 .

lxd/cloudinit: Fix behavior when vendor-data parsing fails and when user-data are not provided.

---

lxd/cluster/membership.go
lxd/db/db.go
lxd/db/query/retry.go
test/suites/clustering.sh

Replaces `EnterExclusive` and `ExitExclusive` with `RunExclusive` which takes a function as an argument to run inside the exclusive mode. The `RunExclusive` function takes care of acquiring and releasing the lock, which simplifies what the caller has to care about.
Fixes panic caused by error during cluster exclusive DB mode:
```
fatal error: sync: Unlock of unlocked RWMutex
goroutine 453 gp=0xc0004e7500 m=3 mp=0xc000089008 [running]:
runtime.fatal({0x26eb90a, 0x20})
runtime/panic.go:1123 +0x5c fp=0xc00143f1d8 sp=0xc00143f1a8 pc=0x45a09c
sync.fatal({0x26eb90a?, 0x2b8ccb0?})
runtime/panic.go:1038 +0x18 fp=0xc00143f1f8 sp=0xc00143f1d8 pc=0x492df8
sync.(*RWMutex).Unlock(0xc000d6d710)
sync/rwmutex.go:212 +0x45 fp=0xc00143f230 sp=0xc00143f1f8 pc=0x4a71e5 …
```

cluster: Fix panic during exclusive DB mode

---

doc/howto/ubuntu_pro_guest_attach.md
doc/instances.md
doc/metadata.txt
lxd/instance/instancetype/instance.go
lxd/metadata/configuration.json

Adds a how-to guide for Ubuntu Pro guest attachment. Including a matrix describing the interaction between the `pro` `lxd_guest_attach` setting, and the guest `ubuntu_pro.guest_attach` config option.

doc: Add Ubuntu Pro how-to

---

CONTRIBUTING.md
doc/lxd-test.yaml
test/main.sh
test/test-shell.bashrc

Add examples of how to make use of the interactive `test-shell` feature.
Add necessary bits to have `lxc` command completions working.

Improve `make test-shell` a bit

---

.github/workflows/tests.yml

This slightly improves the speed of everything needing the Python venv for the `doc` actions. ATM, there are 2 different cached copies due to having some steps running on 22.04 and some on 24.04:
* `setup-python-Linux-x64-22.04-Ubuntu-python-3.13.3-pip-7d...9c`
* `setup-python-Linux-x64-24.04-Ubuntu-python-3.13.4-pip-7d...9c`
It still provides a benefit and also reduces the amount of stuff we needlessly pull from PyPi.

github: use actions/setup-python to cache pip dependencies

---

CONTRIBUTING.md
Makefile

Add a `make update-fmt` target that runs `gofmt` on all files and update contribution guidelines.

Makefile: Add `make update-fmt`

---

test/lint/bad-grep.sh
test/suites/auth.sh
test/suites/basic.sh
test/suites/container_devices_infiniband_physical.sh
test/suites/container_devices_infiniband_sriov.sh
test/suites/container_devices_nic_bridged_filtering.sh
test/suites/container_devices_nic_macvlan.sh
test/suites/container_devices_nic_sriov.sh
test/suites/migration.sh
test/suites/serverconfig.sh
test/suites/waitready.sh

Also, updated a few places using `[ "$(... | wc -l)" = 0 ]` to directly check for no output `[ "$(...)" = "" ]` instead.

 test/lint/bad-grep: check test scripts for `grep` misuse

---

lxd/daemon.go
lxd/daemon_storage.go
lxd/patches.go
test/suites/clustering.sh
test/suites/serverconfig.sh

This depends on https://github.com/canonical/lxd/pull/15482 .
This also contains the move of images and backups to their own sub-directories if storage.{backups,images}_volume is set.

Allow using the same volume for storage.images_volume and storage.backups_volume

---

lxd/device/proxy.go

lxd/devices/proxy: Fix unix socket cleanup

---

lxd/storage/backend_lxd.go

Small PR to move unrelated bits from https://github.com/canonical/lxd/pull/15523.
Even though in some cases the "to be reverted" action is the last one in the row, having the reverter pattern in place allows adding additional instructions in the future without having to care about reverting existing actions in case of error.
This is starting to get useful with https://github.com/canonical/lxd/pull/15523 when reverting the instance's backup config file in case of errors.

Storage: Add reverter pattern for custom volume backend actions

---

doc/.custom_wordlist.txt
doc/api-extensions.md
doc/reference/devices_gpu.md

Per request from FE, mention `vGPU` where `virtual GPU` is mentioned so that references can be found through searching for `vGPU`.

doc: add vGPU acronym for virtual GPU

---

doc/api-extensions.md
doc/metadata.txt
doc/requirements.md
lxd/device/device_utils_disk.go
lxd/device/disk.go
lxd/instance/drivers/driver_qemu.go
lxd/metadata/configuration.json
lxd/project/limits/permissions.go
shared/validate/validate.go
shared/version/api.go

- Switches to modern flags provided by Rust implementation of `virtiofsd`, in the process fixes https://github.com/canonical/lxd/issues/15248
- Enables direct I/O passthrough from guest when using virtiofs (for correctness when an application specifies to open a file with direct I/O rather than silently converting that to a non-direct operation).
- Adds `io.threads` option for filesystem `disk` devices when being passed to the VM as `virtiofsd` based shares - this can improve performance. Fixes https://github.com/canonical/lxd/issues/15742
- Restricts use of this new `io.threads` option in restricted projects unless `restricted.virtual-machines.lowlevel` is set to `allow` to prevent restricted VMs from setting a high thread pool count and consuming extra host resources.
- Adds …

Device: Add thread pool option for VM filesystem `disk` shares using `virtiofsd`

---

test/main.sh
test/suites/basic.sh

The first commit also ensures that `LXD_TMPFS` reaches the system-tests env.
The rest of the PR does minor tweaks to the `basic_usage` test and add a `basic_version` one which mostly aims at providing minimal code coverage for TiCS.

test/suites/basic: check `--version` and `--help` for all binaries

---

lxd-agent/metrics.go

**Previous PR Notice**: I initially submitted this fix in  #15093 but discovered after submission that my Git commit signatures weren't properly configured, causing CLA validation failures. This new PR contains:  
- Properly signed commits matching my GitHub account  
- Verified DCO (Developer Certificate of Origin)  
- Clean commit history  
Apologies for the earlier misconfiguration - this version passes all contribution checks.  
---
This PR resolves the "FIXME: Missing RSS" comment in `metrics.go` by implementing proper RSS memory metric calculation in lxd-agent using kernel memory accounting. The solution provides O(1) complexity with accuracy matching standard system tools.
The original FIXME existed because:
1. RSS metrics weren't populated
2. Previous approaches misunderstood …

lxd-agent: Added  RSS metrics + Simplified calculation for better scalability

---

doc/custom_conf.py

Adds `sphinx-sitemap` extension to generate `sitemap.xml` for SEO purposes. This is in response to a DOCPR-wide request that applies to all public-facing RTD documentation sets.

doc: add sphinx-sitemap to generate sitemap for SEO

---

lxd/instance/drivers/driver_qemu.go

Fixes https://github.com/canonical/lxd/issues/15358.
Includes cherry-pick from https://github.com/lxc/incus/pull/1669.   
Previously `MigrateReceive()` function would incorrectly try calling `CreateVolumeFromMigration()` for attached local volumes during instance migration and fail with "not supported" error. This change fixes the issue. Now, `CreateVolumeFromMigration()` is called only for shared storage volumes in order to notify the shared storage driver to setup the volume on the receiving cluster member.

lxd/instance/qemu: Fix shared storage volume setup during instance migration (from Incus)

---

client/devlxd_ubuntu_pro.go
client/interfaces.go
lxd/ubuntupro/client.go
lxd/ubuntupro/client_test.go
shared/api/devlxd.go

As part of devLXD refactoring, we want devLXD response types to be prefixed with `DevLXD`.
This change only rename the UbuntuPro response types, but the actual responses from devLXD are intact.
~Since UbuntuPro types (without DevLXD prefix) are not used outside devLXD, I would also prefer moving them into `lxd/ubuntupro` package - to be used only internally.~
Let me know if we want to proceed with the renaming for consistency.

devlxd: Separate UbutuPro type used in LXD and in devLXD

---

lxd/api_cluster.go
lxd/api_cluster_test.go
lxd/daemon.go
lxd/daemon_integration_test.go
lxd/sys/os.go

Cherry-picked from https://github.com/lxc/incus/pull/727.
This moves `UnixSocket` to the `sys` package and renames it to `GetUnixSocket`. This allows us to call it on `daemon.os` and `state.OS`.

Refactor UnixSocket function (from Incus)

---

doc/howto/snap.md

Per https://github.com/canonical/lxd/pull/15785#discussion_r2150563984, revert `lxd.daemon` to `lxd` to affect all lxd snap services.

doc: use lxd instead of lxd.daemon for snap services mgmt

---

lxc/remote.go
lxd-migrate/main_migrate.go
lxd-migrate/utils.go
lxd/main_init.go
lxd/main_init_interactive.go
shared/cert.go

This pull request adds a context parameter to `GetRemoteCertificate` in preparation for https://github.com/canonical/lxd/pull/14884. When creating and connecting to cluster links, it is necessary to retrieve the remote cluster member's certificates concurrently and verify their fingerprints. Therefore, we should include context when calling `GetRemoteCertificate`.

shared: Add context to `GetRemoteCertificate`

---

lxd/migrate_instance.go

Fixes a regression introduced by https://github.com/canonical/lxd/pull/15552. We only want to run `PostMigrateSend` on instance devices.

lxd: Only run `PostMigrateSend` when migrating instances

---

.github/workflows/tests.yml

Follow-up to https://github.com/canonical/lxd/pull/15706.
- Adds LXD_OIDC_CLIENT_SECRET environment variable to be used in the ui-e2e-tests.

github: Add LXD_OIDC_CLIENT_SECRET env var to ui-e2e-tests

---

test/includes/setup.sh

There is no binary in `${PATH}` so provide a fully qualified path that works on both 22.04 and 24.04.

test/includes/setup: fix how virtiofsd is detected

---

lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/drivers/util.go
test/suites/vm.sh

Fixes https://github.com/canonical/lxd/issues/15882.
We should allow setting `limits.memory` to a percentage of host memory to match container `limits.memory` behavior.

VM: Fix `limits.memory` when using % of host memory (from Incus)

---

lxd/auth/drivers/tls.go

@roosterfish fixed a regression by allowing restricted certificates to view server metrics and added a comment to explain the reasoning. This was somehow lost so I'm just re-adding it as it led to confusion.
Note that metrics are always filtered at the project level.

lxd/auth/drivers: Add comment to explain metrics entitlement

---

test/includes/net.sh
test/suites/clustering.sh
test/suites/container_devices_nic_bridged.sh
test/suites/container_devices_nic_bridged_acl.sh
test/suites/container_devices_nic_bridged_filtering.sh
test/suites/container_devices_nic_bridged_vlan.sh
test/suites/container_devices_nic_ipvlan.sh
test/suites/container_devices_nic_macvlan.sh
test/suites/container_devices_nic_p2p.sh
test/suites/container_devices_nic_routed.sh

The numbers below are for the `dir` backend:
Test|Time
:---           | :---
clustering_fan|13
container_devices_nic_p2p|10
container_devices_nic_bridged|77
container_devices_nic_bridged_acl|37
container_devices_nic_bridged_filtering|128
container_devices_nic_bridged_vlan|66
container_devices_nic_macvlan|15
container_devices_nic_ipvlan|18
container_devices_nic_routed|26
Total: 390s (~6.5 min)
Test|Time
:---           | :---
clustering_fan|12
container_devices_nic_p2p|7
container_devices_nic_bridged|76
container_devices_nic_bridged_acl|15
container_devices_nic_bridged_filtering|58
container_devices_nic_bridged_vlan|19
container_devices_nic_macvlan|7
container_devices_nic_ipvlan|7
container_devices_nic_routed|13
Total: 214s (~3.5 min)

Faster ping checks

---

doc/conf.py
doc/custom_conf.py

Unresolved Sphinx linkcheck bug with anchors (as filed [here](https://github.com/sphinx-doc/sphinx/issues/12688) and [here](https://github.com/sphinx-doc/sphinx/issues/9255)) sometimes causes our link to maas.io to fail with:
```
broken [https://maas.io/docs/how-to-manage-machines#p-9078-use-lxd-vms](https://maas.io/docs/how-to-manage-machines#p-9078-use-lxd-vms) - Anchor 'p-9078-use-lxd-vms' not found
```
...even though the anchor exists and works when going directly to `https://maas.io/docs/how-to-manage-machines#p-9078-use-lxd-vms`, and linkcheck does not fail it consistently. This is an intermittent upstream bug; this PR works around it by adding the maas.io page to `linkcheck_anchors_ignore_for_url` in the Sphinx configuration file, which should cause the linkcheck to check that the …

doc: ignore anchor when checking maas link (stable-5.0)

---

doc/metrics.md

Suggested-by: Minae Lee <minae.lee@canonical.com>

doc/metrics: improve wording for `project` parameter

---

doc/howto/snap.md

The documentation on holding snap updates provided steps to `--unhold` the LXD snap before manually updating/refreshing, then reinstating the hold. This PR removes these steps as they are not necessary; you can manually update a snap while it is held.

doc: remove unnecessary step to remove hold to refresh snap

---

lxd/auth/drivers/openfga.go
lxd/auth/drivers/tls.go
lxd/auth/types.go
lxd/images.go
lxd/network_allocations.go
lxd/network_zones.go
lxd/networks.go
lxd/profiles.go
lxd/storage_buckets.go
lxd/storage_volumes.go
test/suites/auth.sh
test/suites/tls_restrictions.sh

Checks the URLs returned by the network allocations endpoint. This required jumping through a few feature flag related hoops (see comments).
I've confirmed the tests are failing before this change and passing afterwards.
Closes #15855

Auth: Improvements to network allocation used by URL checks

---

lxd/backup.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/storage/backend_lxd.go
lxd/storage/backend_mock.go
lxd/storage/cache.go
lxd/storage/pool_interface.go
test/suites/backup.sh
test/suites/snapshots.sh

Preceded by:
* https://github.com/canonical/lxd/pull/15775
* https://github.com/canonical/lxd/pull/15776
* https://github.com/canonical/lxd/pull/15777
* https://github.com/canonical/lxd/pull/15859
This PR uses the new backup config metadata format introduced in https://github.com/canonical/lxd/pull/15129 to track all of an instance's custom storage volumes.
In addition all of the storage volume's storage pools are now listed too.
Whenever a custom volume (or its snapshots) gets updated, LXD has to check whether or not this custom volume is attached to any instance. If it's attached, with the changes proposed in this PR, LXD rewrites the backup config file to propagate the latest state of the volume.
In order to pick up an instance's custom volume changes, the outcome of such a change has …

Storage: Add all custom storage vols to instance's backup config

---

test/main.sh

Wraps the escape sequences (colours) so that they don't contribute to what bash thinks are the number of characters in the prompt. This seems to fix text wrapping in the LXD_INSPECT subshell for me.

test: Omit escape sequences from prompt length in inspect subshell.

---

.golangci.yaml

It was failing on the lxd/util package naming which we dont want to change in this series.

golangci: Disable package name checks in var-naming revive checker (stable-5.21)

---

lxd/daemon.go
lxd/db/cluster/projects.go
lxd/events.go
lxd/images.go
lxd/instances_get.go
lxd/network_acls.go
lxd/network_allocations.go
lxd/network_zones.go
lxd/networks.go
lxd/operations.go
lxd/profiles.go
lxd/request/parse.go
lxd/storage_buckets.go
lxd/storage_volumes.go
test/includes/ovn.sh
test/main.sh
test/suites/auth.sh
test/suites/network_ovn.sh
test/suites/projects.sh

I noticed that multiple handlers were performing close to identical logic to get the project and all-projects parameters - returning an error if both are set.
This just factors it out into one place.

Add util to get both "project" and "all-projects" parameters

---

lxc/config/remote.go
lxd/api_1.0.go
lxd/api_cluster.go
lxd/instance/drivers/driver_common.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/instances_get.go
lxd/instances_post.go
lxd/network/driver_common.go
lxd/network/network_utils.go
lxd/network/openvswitch/ovn.go
lxd/resources/gpu.go
lxd/storage/drivers/driver_zfs_volumes.go
lxd/storage/s3/headers.go
lxd/storage/s3/headers_test.go
shared/util.go
test/mini-oidc/storage/storage.go

The initial changes were done mechanically with:
```
go run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@latest -fix -test ./...
```
Some proposed changes were **NOT APPLIED** as I was unsure if they were safe:
```diff
// purePort represents a network interface in Pure Storage.
type pureNetworkInterface struct {
Name     string `json:"name"`
Ethernet struct {
Address string `json:"address,omitempty"`
-       } `json:"eth,omitempty"`
+       } `json:"eth"`
}
```
And
```diff
diff --git i/lxd/instance/drivers/driver_lxc.go w/lxd/instance/drivers/driver_lxc.go
index b59ccdeb5d..86465e7b62 100644
--- i/lxd/instance/drivers/driver_lxc.go
+++ w/lxd/instance/drivers/driver_lxc.go
@@ -6083,21 +6083,21 @@ func (d *lxc) MigrateReceive(args instance.MigrateReceiveArgs) error { …
```

Apply `modernize` changes

---

lxd/api.go
lxd/daemon.go
test/suites/serverconfig.sh

And change browser client detection to look for user-agents that start with `Mozilla`.

Daemon: Only enforce content-type checks for browser clients

---

.github/workflows/tests.yml
doc/.sphinx/requirements.txt
doc/conf.py

Cherry-picks [a100d75](https://github.com/canonical/lxd/commit/a100d75c5b7ac31a15255a86591a714fe95c1cca), [0a5abb5](https://github.com/canonical/lxd/commit/0a5abb5dc2c9bfb6b21d191e0a0974781f118ce7), and [2e11304](https://github.com/canonical/lxd/commit/2e1130485ccae69b365489c112d217b15a3196ba) from main.
Adds `sphinx-sitemap` to generate `sitemap.xml` for `stable-5.0` docs version, including updating documentation test workflow to use `fetch-depth: 0` (needed by sitemap dependency `sphinx-last-updated-by-git`; this has the side effect of also fixing the "Last updated" date in docs footer)
Adds sourceforge domain to `linkcheck_ignore` list per recent 403 errors during spellcheck, likely linked to cloudflare bot rejection.
Note: The original changes targeted `custom_conf.py`, which does not …

doc: backport docs config updates for sitemap and linkcheck (stable-5.0)

---

lxd/api_devlxd.go
lxd/daemon.go
lxd/instance/drivers/load.go
lxd/instance/instance_utils.go
lxd/seccomp/seccomp.go

If the process name looks like a lxc monitor process, but claims to be a different container than the origin process' PID namespace then continue walking up the process tree to find the real lxc monitor process.

devlxd: Add check for origin PID being in same PID NS as the container name in found process

---

lxd/db/cluster/projects.go
lxd/db/cluster/projects.interface.mapper.go
lxd/db/cluster/projects.mapper.go

@tomponline this is cherry-picked from #15827.
Now that the project-specific settings won't actually be project config options, this commit won't be needed, but could be useful on its own.

lxd/db/cluster/projects: Optimize GetProjectConfig()

---

doc/.sphinx/build_requirements.py

Recent buggy update to canonical-sphinx-extensions causing build failures with "WARNING: more than one target found for 'myst' cross-reference" messages. This PR pins the extension to a previous version.

doc: pin canonical-sphinx-extensions version

---

doc/.sphinx/build_requirements.py

Recent buggy update to canonical-sphinx-extensions causing build failures with "WARNING: more than one target found for 'myst' cross-reference" messages. This PR pins the extension to a previous version.
(cherry picked from commit c96e9b2332e10db822c27247b1a43b85e6e2d383)

doc: pin canonical-sphinx-extensions version (stable-5.21)

---

lxd/daemon.go
lxd/devlxd.go
lxd/images.go
lxd/network_acls.go
lxd/network_allocations.go
lxd/network_zones.go
lxd/networks.go
lxd/profiles.go
lxd/project/limits/permissions_test.go
lxd/request/const.go
lxd/request/context.go
lxd/request/request.go
lxd/storage_buckets.go
lxd/storage_volumes.go
lxd/ucred/ucred.go

When setting up the context info, we should never use the existing value verbatim. This is because the UI multiplexes requests over HTTP2, and per https://pkg.go.dev/net/http#Request.Context, this context is cancelled when the clients connection is cancelled. This means that multiple requests are made on the same connection and they can all share a context.
Happily, when we set the Info in the request context, we perform a shallow clone of the Request and pass it down to further handlers. This means that we can set an empty value when the request is received and rely on it being correct when we later retrieve it because it is set higher in the context tree (this behaviour is also relied upon by mux for HTTP vars).

lxd/request: Never get existing Info when setting up request context

---

.gitignore
test/lxd-client/main.go
test/main.sh
test/suites/filemanip.sh

Test file push using `strings.Reader` which causes the `Content-Length` to be set by `(net/http).NewRequest()`. This test is for https://github.com/canonical/lxd/pull/15974

tests: Test instance file push using strings.Reader

---

lxd/auth/oidc/oidc.go

When the browser calls `GET /oidc/callback`, it is a redirect from the IdP. Even though the cookie is set for this domain, the browser doesn't send it because it's a redirect.
Thank you to the UI e2e tests for catching this!

lxd/auth/oidc: The `login_id` cookie must have `SameSite=Lax`

---

lxd/apparmor/apparmor.go
lxd/apparmor/archive.go
lxd/sys/apparmor.go
lxd/sys/os.go
test/includes/lxd.sh

Also address a couple CodeQL alerts.

Cache `apparmor_parser --version` info during daemon init

---

test/suites/deps.sh

`command -v lxc` was finding the `lxc` wrapper function from `test/include/lxc.sh` instead of finding the path to the actual binary:
```
2025-07-21T14:20:14.4321927Z ==> TEST BEGIN: checking dependencies
2025-07-21T14:20:14.4325266Z ++ date +%s
2025-07-21T14:20:14.4337930Z + START_TIME=1753107614
2025-07-21T14:20:14.4338301Z + local skip=false
2025-07-21T14:20:14.4338622Z + '[' -n '' ']'
2025-07-21T14:20:14.4338924Z + '[' false = false ']'
2025-07-21T14:20:14.4339252Z + test_check_deps
2025-07-21T14:20:14.4339655Z + echo 'lxc binary must not be linked with liblxc'
2025-07-21T14:20:14.4340191Z lxc binary must not be linked with liblxc
2025-07-21T14:20:14.4346568Z + grep -F liblxc
2025-07-21T14:20:14.4347830Z ++ command -v lxc
2025-07-21T14:20:14.4354242Z + ldd lxc …
```

test/suites/deps: run `ldd` on the actual `lxc` binary

---

lxd/api_cluster.go
lxd/daemon.go
lxd/network/driver_bridge.go
lxd/network/driver_common.go
lxd/network/driver_ovn.go
lxd/network/driver_physical.go
lxd/network/network_interface.go
lxd/networks.go
lxd/storage.go
test/includes/clustering.sh
test/includes/lxc.sh
test/includes/lxd.sh
test/includes/uuid.sh
test/main.sh
test/suites/clustering.sh
test/suites/clustering_waitready.sh
test/suites/database.sh
test/suites/lxd_user.sh
test/suites/projects.sh
test/suites/remote.sh
test/suites/waitready.sh

Mainly backports #16035 and #16066 but also some other PRs/commits to retain a clean history:
* https://github.com/canonical/lxd/pull/15926
* https://github.com/canonical/lxd/pull/15934
* https://github.com/canonical/lxd/commit/158073c54a73e61e1b48d9dfd04f44cea155f4e9 (#15820)
* https://github.com/canonical/lxd/commit/ebfb168bf63b599b5135d9fa211ad3aa68718921 (#15820)
* https://github.com/canonical/lxd/pull/16035
* https://github.com/canonical/lxd/pull/16066
This allows making use of the new features in the MicroCloud test suite which pulls LXD `5.21/edge`.

Backport waitready enhancements (stable-5.21)

---

test/suites/clustering_waitready.sh
test/suites/waitready.sh

Backports https://github.com/canonical/lxd/pull/16079.

Backport fixes to not use `lxd sql` in waitready test suite (stable-5.21)

---

doc/reference/storage_powerflex.md

Add a limitation note.
We have initially reported this issue in https://bugs.launchpad.net/cloud-images/+bug/2072929.
The partitions for the releases after Noble now use a different partitioning scheme (not exceeding the 15 partition limit):
```
sda       8:0    0    5G  0 disk 
├─sda1    8:1    0    4G  0 part /
├─sda14   8:14   0    4M  0 part 
├─sda15   8:15   0  106M  0 part /boot/efi
└─sda16 259:0    0  913M  0 part /boot
sda       8:0    0    5G  0 disk 
├─sda1    8:1    0  3.9G  0 part /
├─sda13   8:13   0 1023M  0 part /boot
├─sda14   8:14   0    4M  0 part 
└─sda15   8:15   0  106M  0 part /boot/efi
sda       8:0    0    5G  0 disk 
├─sda1    8:1    0  3.9G  0 part /
├─sda13   8:13   0 1023M  0 part /boot
├─sda14   8:14   0    4M  0 part 
└─sda15   8:15   0  106M  0 part …
```

doc: Add limitation note about SDC and Ubuntu Noble Numbat images

---

lxd/sys/apparmor.go
lxd/sys/os.go

Fixes commit f4be44fa9214ac9d88a9ba256077a64580f070ca that accidentally introduced a `panic` if Appamor is not available.
Reported-by: Katie May <katie.may@canonical.com>
Co-authored-by: Mark Laing <mark.laing@canonical.com>

lxd/sys/apparmor: do not try to get the cache dir if Apparmor is not available

---

lxd/instance/drivers/driver_qemu.go
lxd/instance/drivers/driver_qemu_bus.go

This PR restores the previous "classic" PCIe port allocation method (including its flaws) but isolates it in a single standardised function so it can be altered in the future in a cleaner way.
Due to the laggy behaviour of QEMU's QMP `query-pci` command was not suitable for providing a reliable way of discovering free PCIe ports for hotplugging. Despite the work done in https://github.com/canonical/lxd/pull/16049
Related to https://github.com/canonical/lxd/issues/16003

VM: Restore classic PCIe allocation and standardise allocator functions

---

.github/SUPPORT.md
README.md
doc/custom_conf.py
doc/installing.md
doc/myconf.py

This PR updates several docs and README references to `6` and the `latest` docs version, which are appropriate for the current`main` branch. These are changed to refer to `5.21` and the `stable-5.21` docs version, as appropriate for the `stable-5.21` GH branch.

docs: updates to references from main branch (stable-5.21)

---

lxd/network/driver_ovn.go
lxd/network/openvswitch/ovn.go
test/suites/network_ovn.sh

This PR associates OVN load balancers and network forwards with the internal OVN switch. As a result, instances created on the OVN network are now able to access the listen address of OVN load balancers and forwards.
Fixes https://github.com/canonical/lxd/issues/14166.

Network: Associate OVN load balancers and forwards with internal switch

---

lxd/api_cluster.go
test/suites/clustering.sh

- validate a cluster group edit does not ignore a member removal
fixes #16074

Cluster: Validate a cluster group member removal

---

lxd/api_1.0.go
lxd/daemon.go
lxd/state/state.go

Renames `(*Daemon).getSecrets` and `(state.State).Secrets` to address https://github.com/canonical/lxd/pull/15832#discussion_r2254252619 and https://github.com/canonical/lxd/pull/15832#discussion_r2254253640

Cluster secret followup

---

lxd/instance/drivers/driver_lxc.go
test/suites/container_devices_unix.sh

Follow up to https://github.com/kadinsayani/lxd/pull/new/tests/mount-point-removal.
This pull request adds tests to ensure removal of `/dev` directories when a disk device is removed and warns rather than returns an error when removal fails.

Mount point removal follow up

---

lxd/auth/drivers/openfga.go
lxd/auth/util.go
lxd/daemon.go
lxd/db/cluster/identities.go
lxd/identities.go
lxd/identity/cache.go
lxd/identity/certificate_client.go
lxd/identity/certificate_metrics.go
lxd/identity/certificate_server.go
lxd/identity/oidc_client.go
lxd/identity/type_common.go
lxd/identity/type_interface.go
lxd/identity/util.go

This pull request replaces string-based utility functions with a `Type` interface that provides type-safe access to identity type behavior. This change moves away from utility functions like `IsFineGrainedIdentityType` and `IsRestrictedIdentityType` to a centralized, interface-based approach.
Key changes:
- Add `identity.Type` interface with methods for authentication, admin status, caching, and fine-grained permission capabilities
- Implement `New()` function to validate identity type strings and return concrete types that implement the interface
- Create individual identity type structs (`OIDCClient`, `CertificateClient`, etc.) with embedded `typeInfoCommon` for shared default behavior
- Update all callers to use the new interface methods instead of utility functions
- Preserve behavior …

Refactor identity type handling with type-safe interface

---

.github/workflows/tests.yml

This action was introduced to save `pip`'s cache to speed up the building of the docs. However, since commit a7828ec63c0dddf207c11bc029508d8bc3a09be1, when running `make dist` in the `Code` job, we skip building the docs if running as part of a PR. This was made as a speed optimization too.
Since we have no use for Python during `make dist` on PR test runs, we might as well not even invoke the action. This should save ~5s per run and also avoid putting unneeded artifacts in the cache.
This avoids https://github.com/actions/setup-python/issues/1169

github: use actions/setup-python only for non-PRs

---

lxd/auth/types.go
lxd/auth/util.go
lxd/daemon.go
lxd/devlxd.go
lxd/instances_post.go
lxd/request/const.go

This is also part of https://github.com/canonical/lxd/pull/16223 but can be merged separately to ease it's review.

Auth: Move authentication methods to `request` package and rename to Protocol

---

lxd/daemon.go

Fixes commit 39f6f8b46cadc424db5db0cc4430a72a2cbc848f

lxd/daemon: fix typo when checking identity type

---

Makefile
test/main.sh

In #16281, builds with coverage enable (for TiCS) were accidentally broken:
```
+ make test-binaries
CGO_ENABLED=0 go install -C test -v -trimpath -buildvcs=false -tags netgo ./devlxd-client -cover
malformed import path "-cover": leading dash
make: *** [Makefile:107: devlxd-client] Error 1
Error: Process completed with exit code 2.
```

Makefile: `-cover` must not be the last argument

---

lxd/storage/drivers/driver_pure_volumes.go

(cherry picked from commit 3a131e718237add96df27efba15d3f4ef1552aba)

lxd/storage/drivers/pure: fix volume copy always copying the same snapshot (stable-5.21)

---

test/lint/golangci.sh

Also "cherry-pick" the same change done in `main` via https://github.com/canonical/lxd/pull/16315 to not run `golangci-lint` once merged into the target branch.

test/lint/golangci: compare rev from the stable-5.21 branch (stable-5.21)

---

lxd/storage/drivers/driver_pure_volumes.go

(cherry picked from commit 07b1821ad34d12f5696fae031add6c956201b074)

lxd/storage/drivers/pure: Ensure volume is unmapped after changing quota (stable-5.21)

---

shared/util.go

(cherry picked from commit f6a50a0be5e97ca9bca15666dc1be26902dbcee7)

shared/util: Break aliasing in RemoveElementsFromSlice (stable-5.21)

---

doc/reference/storage_pure.md
lxd/storage/drivers/driver_pure.go
lxd/storage/drivers/driver_pure_volumes.go

PureStorage driver rejects sizes that are not divisible by `512B`.
For example creating a volume with volume size `10MB` is rejected.
Therefore, we ensure that the size is multiple of 512 by rounding it up if necessary.
Additionally, we ensure that the volume size is `1MiB` (minimum PureStorage volume size) if smaller size is provided.
---
For example, if user enters volume size `10KB`, should we round it to `1MiB` (minimum allowed size), or error out as we currently do?

storage/pure: Round volume size to make it divisible by 512B

---

lxd/dnsmasq/dhcpalloc/dhcpalloc.go

This linter error doesn't seem to be triggered in CI but I keep hitting it locally in my pre-push git hook. The linter error is:
> var-declaration: should omit type error from declaration of var ErrDHCPNotSupported; it will be inferred from the right-hand side (revive)

lxd/dnsmasq/dhcpalloc: Fix linter error (revive: var-declaration)

---

doc/reference/storage_pure.md
lxd/storage/drivers/driver_pure.go
lxd/storage/drivers/driver_pure_volumes.go

Cherry-picked from:
- https://github.com/canonical/lxd/pull/16345

storage/pure: Round volume size to make it divisible by 512B (stable-5.21)

---

lxd/identities.go
lxd/identity/certificate_client.go
lxd/identity/certificate_metrics.go
lxd/identity/certificate_server.go
lxd/identity/devlxd_token_bearer.go
lxd/identity/oidc_client.go
lxd/identity/type_common.go
lxd/identity/type_interface.go

This is another follow up and something Tom noticed while reviewing #16225 
`IsCacheable` is currently just the opposite of `IsPending`, so it is unnecessary. This may change after OIDC sessions are introduced, as it is not clear at this point whether OIDC identities will need to be cached after sessions are introduced.

auth: Remove `identity.Type.(IsCacheable)`

---

lxc/auth.go
lxd/db/cluster/entity_type_identity.go
lxd/db/cluster/identities.go
test/suites/auth.sh

Earlier I was demonstrating the permissions API for the anbox team. I noticed that running `lxc auth permission list` returned a bogus URL for a `DevLXD token bearer` identity. The URL looked like:
```
/1.0/auth/identities//{uuid}
```
e.g. the authentication method was missing. 
I then attempted to grant a group the `can_edit` entitlement on the identity and found it to be broken, with all combinations of `lxc auth group permission add <group> identity {bearer,devlxd}/{name,UUID} can_edit` failing.
This PR does a few things:
1. Updates `lxd/db/cluster.AuthMethod` to use a map of database code to text when scanning from the db.
2. Uses the above map to generate a case statement when querying for entity URLs via the permissions APIs.
3. Updates `lxc auth group permission add/remove` to …

Auth: Fix permission management for entitlements on bearer identities

---

lxd/instance/drivers/driver_common.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go

This refactoring was included with https://github.com/canonical/lxd/pull/15349. I've extracted this change to reduce the size of https://github.com/canonical/lxd/pull/16336. I've also included a commit which expands the godoc comment of `(*common).snapshotCommon()`.

Extract `(*common).restoreCommon()` method from `(*lxc/*qemu).Restore()`

---

.github/workflows/tests.yml

- github/tests: adjust to new ui test project and setup
- UI test projects have been split into unclustered and clustered backend tests. Relying on the big unclustered suite for now. Leaving addition of setup and run of the clustered suites for a later iteration.

github/tests: adjust to new ui test project and setup

---

.github/workflows/tests.yml

This will ensure the `main` and `stable-*` branches have warm caches which should then speed up the check done in PRs.

github: also run `golangci/golangci-lint-action` on schedule

---

lxd/auth/drivers/openfga.go

This timeout was added with the intention of surfacing access checks that are taking too long to perform. However, we can't help access checks taking a long time when the cluster is under heavy load, as we need to wait for a lock on the database. This commit removes the timeout and instead relies on the global 10s transaction timeout.
This is a likely fix for #16365

lxd/auth/drivers: Remove 5s timeout on fine-grained auth checks

---

lxc/file.go
lxc/file_test.go

While the SFTP server is bound to localhost by default, we should avoid `math/rand` as it provides predictable output (deterministic) which works against the purpose of using authentication to begin with.

lxc/file: use `crypto/rand` to generate username/password that are not trivially guessable

---

lxd/storage/backend_lxd_patches.go

This fixes #16282 and also removes couple of nested cluster transactions, which made the main transaction to always time out on patch apply:
```
INFO   [2025-09-05T19:32:14Z] Applying patch                                name=storage_missing_snapshot_records stage=3
INFO   [2025-09-05T19:32:14Z] Applying patch                                driver=zfs name=storage_missing_snapshot_records pool=default
WARNING[2025-09-05T19:32:24Z] Transaction timed out. Retrying once          err="Failed to begin transaction: context deadline exceeded" member=1
```

Fix storage patch update with instance volume with `size` config

---

.github/actions/cache-dqlite-liblxc/action.yml
.github/actions/download-minio/action.yml
.github/actions/download-snaps/action.yml
.github/actions/setup-microceph/action.yml
.github/actions/setup-microovn/action.yml
.github/workflows/tests.yml
test/includes/snap.sh

This changes how `minio` and `dqlite`/`liblxc` are cached as well as introduce a cache for snap dependencies.
* `minio` is now cached for up to 7 days
* `dqlite`/`liblxc` is still cached only for 1 day
* snap dependencies are cached for only 1 day
A notable change is that `minio` and `dqlite`/`liblxc` are no longer saved in separated caches and duplicated in the `system-test-deps` artifact.
The concept of artifact is kept to group the things that are build during a given CI run and the other cached assets are using the `actions/cache` mechanism alone to be saved and reused independently between the parent and derived PRs.
This change of strategy will reduce the network consumption (a non-goal but still a benefit) but will also reduce the cache space consumption and improve the cache hit …

Rework CI caching strategy

---

lxd/storage/backend_lxd_patches.go

The nested transaction commits are not needed as stable-5.0 does not contain dde93645e570e7b97895f2d8eba2b5e35920b3c5 ("Move db instance functions to ClusterTx") commit which caused these.
Tested with reproducer from #16282:
```
INFO   [2025-09-08T09:36:45Z] Applying patch                                name=storage_missing_snapshot_records stage=2
INFO   [2025-09-08T09:36:45Z] Applying patch                                driver=zfs name=storage_missing_snapshot_records pool=default
INFO   [2025-09-08T09:36:45Z] Creating missing volume snapshot record       driver=zfs instance=c1/snap0 pool=default project=default
```

Fix storage patch update with instance volume with size config (stable-5.0)

---

lxd/instance/drivers/driver_qemu.go

This fixes transferred FDs from LXD to QEMU to be consistent with the caching mode and their `O_DIRECT` flag validity and fixes starting VMs with QEMU 9.1+ on btrfs. 
Without this patch (since qemu checks the `O_DIRECT` flag since  qemu/qemu@99c147e2f53726290bbdde795b6efbb4d9138657) files are always opened `O_DIRECT` by lxd, and qemu just accept and uses them, even though this is not consistent with the expected caching behavior (especially LXD's manual override for `btrfs` and `zfs` NOT to use `O_DIRECT` is ignored currently)
VMs on btrfs don't work without this patch because the caching mode is changed via that override, but the file opening flag is not.
This fixes #16348

Fix QEMU 9.1+ VM starting by syncing caching options and fd flags

---

lxd/storage/drivers/clients/alletra_wsapi1.go
lxd/storage/drivers/driver_alletra.go
lxd/storage/drivers/driver_alletra_volumes.go

This is a second part of HPE Alletra storage driver
Based on https://github.com/canonical/lxd/pull/15946

HPE Alletra storage driver (part 2)

---

lxd/backup/backup_config_utils.go
lxd/backup/backup_config_utils_test.go
lxd/backup/config/backup_config.go

As part of the recovery it's important to understand whether one backup config file is newer than another one. This PR adds unexported metadata to the `Config` struct.
As part of custom volume discovery from an instance's backup config, each of the custom volumes gets packaged into its own backup config. Those backup configs derive their last modification time from their parent instance.
When listing all the unknown volumes attached to instances and the ones discovered just by name, we can then consult this last modification time to figure out whether or not the current backup config should be used instead as it might replace one which is outdated or not enriched enough.
Custom volumes recovered only from name have a backup config with a last modification time of zero. So they will be …

Backup: Add metadata to the config struct

---

lxd/api_cluster.go
lxd/daemon_images.go
lxd/images.go
lxd/lifecycle/instance.go
lxd/lifecycle/instance_backup.go
lxd/lifecycle/instance_snapshot.go
lxd/lifecycle/storage_volume.go
lxd/lifecycle/storage_volume_snapshot.go
lxd/operations/operations.go
lxd/request/requestor.go
lxd/storage_volumes_backup.go

`operations.Operation` holds an `*api.EventLifecycleRequestor`. This contains limited information compared with the internal `request.Requestor`, and since operations will shortly also report the requestor using an `api.OperationRequestor` (see #15991) it makes sense to use the internal requestor representation - which can be converted into the appropriate API type as required..

Use `request.Requestor` for `operations.Operation`

---

doc/api-extensions.md

Quick fix for doc linter. Lists should have blank lines around them.

doc/api-extensions: Fix list format

---

doc/lxd-test.yaml
test/includes/lxd.sh
test/includes/net.sh
test/main.sh
test/suites/auth.sh
test/suites/basic.sh
test/suites/clustering.sh
test/suites/clustering_move.sh
test/suites/clustering_waitready.sh
test/suites/container_devices_disk.sh
test/suites/container_devices_nic_bridged.sh
test/suites/container_devices_nic_bridged_acl.sh
test/suites/container_devices_nic_bridged_filtering.sh
test/suites/container_devices_nic_bridged_vlan.sh
test/suites/container_devices_nic_ipvlan.sh
test/suites/container_devices_nic_macvlan.sh
test/suites/container_devices_nic_p2p.sh
test/suites/container_devices_nic_physical.sh
test/suites/container_devices_nic_routed.sh
test/suites/container_devices_nic_sriov.sh
test/suites/container_devices_tpm.sh
test/suites/network.sh
test/suites/projects.sh
test/suites/shutdown.sh
test/suites/snapshots.sh
test/suites/storage_driver_dir.sh
test/suites/storage_local_volume_handling.sh
test/suites/storage_snapshots.sh
test/suites/tls_restrictions.sh
test/suites/waitready.sh

The cluster tests are 20-30s quicker
The standalone tests are 1.5 to 3 minutes quicker.
Some unexpected savings were made by not assigning IP addresses to some networks that didn't needed them.
Indeed, the network creation time is much slower when IP addresses are assigned:
```
$ time lxc network create foo 
Network foo created
real    0m2.933s
user    0m0.056s
sys     0m0.028s
$ time lxc network create bar ipv4.address=none ipv6.address=none
Network bar created
real    0m0.183s
user    0m0.039s
sys     0m0.054s
$ time lxc network create baz ipv4.address=192.0.2.1/24 ipv6.address=2001:db8::1/64
Network baz created
real    0m0.725s
user    0m0.038s
sys     0m0.051s
```
The overhead could come from many places like:
* time taken to generating random subnets
* spawn `dnsmasq`
* wait for …

Tests speedup

---

lxd/network/driver_ovn.go
lxd/network/network_utils.go

Follow-up to https://github.com/canonical/lxd/pull/16320.
Refactor the `complementRangesIP4` function.
- Avoid unnecessary string parsing of IP addresses.
- Fix the comment for the `previousEnd` var.
- Simplify checking if the calculated gap is a single IP or multi-IP.

Network: Follow-up to OVN IPv4 DHCP ranges

---

doc/custom_conf.py
doc/explanation/clusters.md
doc/howto/storage_buckets.md

The HPE Alletra link was tested despite being on the ignore list which I believe was due to this missing `,`.
For the MinIO link, they have non-optimized redirections which means I didn't pick the right final destination in the first try (#16520).
The dqlite one was just missed :/

Update more doc links to avoid some redirections

---

lxc/auth.go
test/suites/auth.sh

Fixes a regression whereby `lxc auth identity group remove <id> <group>` did not actually remove the group. This was caused by 8140c332a2b01d3f0bdba4c5ab55d64d31d648ef. Added a test to ensure it doesn't happen again!

Auth: Actually remove group in `lxc auth identity group remove`

---

test/suites/devlxd.sh

Fix order of the initial DevLXD access test to ensure `token` variable is set before creating an invalid token. This prevents unbound variable error.
Seems that passed in GH actions because token is set elsewhere, and for me locally, because I set `token` variable to test devlxd bearer token to simplify local development 🙄

test/devlxd: Fix token check order

---

.github/workflows/tests.yml
Makefile
test/main.sh

This will slow down the default make target (what gets build when just running `make`). On my machine, it's ~10s for the first run and then ~3s.
For those using `make` to iterate during development, might benefit a lot to using non-default target instead, like `make lxd`, `make lxc` or `make lxd-agent` and such. This was true before this change but will be even more beneficial after.

test/main: build test binaries if they are missing

---

.github/workflows/tests.yml

The `code` job has a relatively high failure rate (~17% over the last year). The `documentation` job only fails occasionally (~5% over the last year).
As such, let's skip many pointless documentation checks because the failing code tests will need to be addressed anyway thus requiring subsequent CI runs.

github: delay running the `documentation` job after the `code` job

---

client/lxd_server.go
client/lxd_server_test.go

Currently the `httpUnixPath` field isn't copied over. This should hopefully prevent further issues of this type!

client/lxd_server: Copy all fields in UseProject and UseTarget

---

doc/metadata.txt
lxd/cluster/config/config.go
lxd/metadata/configuration.json

* Adding a default string to the docs for the server config `oidc.scopes`, `core.bgp_asn` and `instances.migration.stateful`.

Fix OIDC scopes default

---

test/README.md
test/lint/empty-test-fail.sh
test/suites/auth.sh
test/suites/backup.sh
test/suites/basic.sh
test/suites/completions.sh
test/suites/concurrent.sh
test/suites/config.sh
test/suites/container_devices_disk.sh
test/suites/image_profiles.sh
test/suites/lxd-benchmark.sh
test/suites/network.sh
test/suites/network_acl.sh
test/suites/projects.sh
test/suites/remote.sh
test/suites/serverconfig.sh
test/suites/sql.sh
test/suites/tls_restrictions.sh
test/suites/vm.sh

We set -e in the test suite to ensure an exit on error. Unfortunately, as far as I can tell -e doesn't apply inside a test. The man page for bash (https://man7.org/linux/man-pages/man1/bash.1.html) has:
> The shell does not exit if the
> command that fails is part of the command list
> immediately following a while or until reserved
> word, part of the test following the if or elif
> reserved words, part of any command executed in a
> && or || list except the command following the
> final && or ||, any command in a pipeline but the
> last (subject to the state of the pipefail shell
> option), or if the command's return value is being
> inverted with !.
Which to me indicates that it should be failing, but at least locally for me it is not.
This means that any test that runs `[ "$(cmd)" = …

test/suites: When asserting empty output, get output and test on different lines

---

lxd/certificates.go
test/suites/auth.sh

Fixes https://github.com/canonical/lxd/issues/16392.
Extend client name validation during certificate add token in the `POST /1.0/certificates` request to reject empty values.

lxd: Reject certificate add token with an empty client name

---

test/suites/basic.sh
test/suites/container_devices_tpm.sh

This includes a different workaround for https://github.com/canonical/lxd/issues/16569 which is now known to affect more than only LVM.
The script is now also installing the missing package to get the kernel module so we can run the test when on local machines/VMs. The `-azure` kernel does not however have the needed `CONFIG_` option so there is no way to have it in CI.

Tests speedup followup

---

lxd/storage/backend_lxd.go
lxd/storage/drivers/driver_powerflex_volumes.go
lxd/storage/drivers/driver_pure_volumes.go
lxd/storage/drivers/volume.go

Addresses the comment here https://github.com/canonical/lxd/pull/16567#discussion_r2362523668.
Also I somehow missed properly testing VM recovery :(. The `container` type was always the default (int 0) so I didn't encounter the issue during volume normalization.
Just a few more lines and missing bits to get VM recovery working too for both PowerFlex & Pure.
I have now cross tested everything, also by having Pure & PowerFlex instances running in parallel, having vols on PowerFlex attached to Pure backed instances and so on.

Storage: Recovery followups 

---

lxd/storage/backend_lxd.go
lxd/storage/backend_mock.go
lxd/storage/cache.go
lxd/storage/pool_interface.go

Required for #16336.
We can generalize the cache introduced for backup config creation so that it can be used outside of the `storage` package. For an example of usage in `lxd/instance/drivers/driver_common.go`, please see: https://github.com/canonical/lxd/pull/16336/commits/363013a38438299b1dc923a62b89cdff8c00644c.

Generalize storage cache for external use

---

client/devlxd.go

Add `UseBearerToken` function for devLXD client to allow changing token without creating a new client. This is helpful for CSI - when we detect the new token we can create a copy of the client with new bearer token (while retaining http client, context, etc) and start using it from that moment onward, allowing us to keep the client for the entire lifecycle of the CSI container.

client/devlxd: Add UseBearerToken function 

---

lxd/instance_post.go
test/suites/clustering.sh

Fixes https://github.com/canonical/lxd/issues/16468.
- Extend validation inside of the `instancePostClusteringMigrate()` function to prevent instance migration if the target member is evacuated.

lxd: Prevent instance migration to evacuted member

---

lxd/storage/backend_lxd.go
lxd/storage/backend_mock.go
lxd/storage/pool_interface.go
lxd/storage_volumes_snapshot.go

Required for #16336.
When creating a snapshot of an attached custom storage volume, we need a way to map attached volumes to their snapshots. `volatile.attached_volumes` will be a JSON-serialized map of attached volume UUIDs to the UUIDs of their corresponding snapshots. We can use this key to identify attached volume snapshots during restore and deletion.

Return generated UUID from (*lxdBackend).CreateCustomVolumeSnapshot()

---

lxd/storage/block/utils.go
lxd/storage/drivers/driver_common.go
lxd/storage/drivers/driver_lvm_volumes.go

Fixes regression caused by https://github.com/canonical/lxd/commit/38646b68235eba2ae07211fbb0f2e3028a523fc5
> It appears that the [LXD] images are meant for 512, and QEMU emulates 512, but since the backing storage is 4096 according to the host, when sgdisk is run on the host (where the block device is 4096) to move the second GPT header, it finds a valid protective MBR with no GPT header and corrupts the entire partition table.
https://github.com/lxc/incus/issues/1375#issuecomment-2547416266
Fixes https://github.com/canonical/lxd/issues/16477

Storage: Fix regression of LVM pools with underlying storage using 4096 bytes sector size (from Incus)

---

lxd/network/driver_ovn.go
test/suites/network_ovn.sh

Observed this while trying to edit a network definition to change its ipv4 segment. The validation expected an ipv6 volatile entry but ipv6 was actually turned off with none.
Fixes https://github.com/canonical/lxd/issues/16607.

Network: We don't need an OVN volatile uplink when the address is none

---

lxd/network/driver_ovn.go
lxd/network/openvswitch/ovn.go

Includes cherry-picks from https://github.com/lxc/incus/pull/1160.
This PR configures OVN so it doesn't fill the MAC_Binding table with every single MAC address it sees through ARP. Instead MAC_Binding entries will be generated for the default gateway only, leading to two entries per network.

Network: Limit OVN MAC binding (from Incus)

---

doc/howto/network_bridge_firewalld.md

In https://documentation.ubuntu.com/lxd/latest/howto/network_bridge_firewalld/#prevent-connectivity-issues-with-lxd-and-docker, we recommend three approaches to resolve connectivity issues when Docker is installed on the same system as LXD. One of those ways is to enable IPv4 forwarding; however, this included a warning about how this can cause Docker container ports to be reachable from any machine on your local network.
That issue has been resolved on Docker's side as of v28 (see this [closed issue](https://github.com/moby/moby/issues/14041)). The warning in our docs is updated in this PR to include this, along with a link to their [blog announcement](https://www.docker.com/blog/docker-engine-28-hardening-container-networking-by-default/) about the fix.
This PR also moves the "Uninstall …

doc: update docker compatibility guidance

---

lxd/resources/cpu.go

While for many CPU architectures in /proc/cpuinfo output, each CPU info block starts with "processor\s+:" (regex) block, it is not always the case.
Also, some architectures, for example, arm tend to add an additional text block at the beginning of the file or at the end.
Let's make our /proc/cpuinfo parser less strict and just skip the block we can't handle.
Fixes: #16481
Manually tested with `tf-reserve rpi4b https://cdimage.ubuntu.com/ubuntu-server/noble/daily-preinstalled/current/noble-preinstalled-server-arm64+raspi.img.xz` and `lxc query /1.0/resources`.

lxd/resources/cpu: make /proc/cpuinfo parser less strict

---

Makefile
test/main.sh
test/suites/basic.sh
test/suites/serverconfig.sh
test/suites/vm.sh

With https://github.com/canonical/lxd/commit/9f431d9ee933b40dd2c433218aeb7b2d71373908, `make test-shell` stopped spawning a LXD and cleaning up when closing the test shell. This was found to be inconvenient (thanks Kadin) and also breaks the documented CONTRIBUTING guide that says you can directly interact with LXD once in the test shell.

Misc improvements to tests

---

test/includes/setup.sh
test/suites/backup.sh
test/suites/clustering.sh
test/suites/projects.sh

Improve `ensure_import_testimage` support for projects and use the helper in more places as it is a tad quicker than using `deps/import-busybox`.

Use `ensure_import_testimage` where possible
