canonical/lxd

README.md, shared/idmapset_linux.go, shared/util_linux.go
=> Implement shifting of UID/GID in ACL xattrs

lxd/devices.go
=> devices: handle empty isolcpus set

lxd/storage_zfs.go
=> zfs: Always require existing datasets to be empty

doc/api-extensions.md, doc/storage.md, lxd/api_1.0.go, lxd/storage_btrfs.go, lxd/storage_ceph.go, lxd/storage_dir.go, lxd/storage_lvm.go, lxd/storage_pools_config.go, lxd/storage_zfs.go
=> storage: add volatile.initial_source key 

lxc/utils.go, lxd/main_daemon.go, lxd/main_init.go, lxd/networks.go, test/main.sh
=> Don't hard depend on dnsmasq and fix progress reporting

lxd/container_lxc.go
Signed-off-by: AJ Ruckman <aj@eyestra.in>
=> Typo: now -> know

lxd/networks_iptables.go
=> Fix networkIptablesClear with missing ip{6}tables

lxd/patches.go, lxd/storage_dir.go, lxd/storage_pools_config.go, lxd/storage_volumes_config.go, lxd/storage_zfs.go
=> storage: fix "size" property

lxd/container_lxc.go
=> Another LXC 2.1 key rename, lxc.idmap

shared/util.go
=> Fix bad check for snap paths

README.md
=> doc: Link to release notes and downloads

README.md, lxd/container_lxc.go, lxd/networks.go, lxd/networks_utils.go, lxd/patches.go, test/suites/network.sh
=> Tweak Docker documentation and fix dnsmasq static allocations

shared/util_linux.go
=> shared: Fix growing of buf in GroupId

client/lxd.go, lxd/main_migratedumpsuccess.go
=> Fix live migration (bad URL in dumpsuccess)

lxd/apparmor.go, test/suites/basic.sh
=> apparmor: Support new stacking syntax

doc/api-extensions.md, doc/storage.md, lxd/api_1.0.go, lxd/storage_ceph.go, lxd/storage_pools_config.go
=> ceph: add "ceph.osd.force_reuse" property

lxd/main_subcommand.go
=> Fix error message when log path is missing

lxd/main_init.go
This is a mechanical commit just moving the various inline helpers
functions of CmdInit.Run to separate methods, in order to make Run()
itself a bit slimmer and easier to read with a brief eye look.
There's no logic change.
Signed-off-by: Free Ekanayaka <free@ekanayaka.io>
=> Move state-changing inline functions to own methods

lxd/daemon_images.go
=> lxd/images: Fix private image copy with partial fp

lxd/storage_ceph_utils.go
=> ceph: sanitize path return from rbd map

lxd/patches.go, lxd/storage_dir.go, test/suites/storage.sh
=> dir: use bind-mount for pools outside ${LXD_DIR}

lxd/storage_ceph.go, lxd/storage_ceph_utils.go, lxd/storage_lvm.go, lxd/storage_lvm_utils.go, lxd/storage_utils.go
=> {ceph,lvm}: generate new xfs uuid

lxd/storage_ceph.go, lxd/storage_ceph_utils.go, lxd/storage_lvm_utils.go, test/suites/storage_driver_ceph.sh
=> ceph: implement resizing

lxd/events.go
This adds additional locking around the event handler code to ensure
that there is no race between the time where we first fail to send a
message and the time where the listener is removed from the list.
Closes #3770
=> lxd/events: Fix race condition in event handlers

lxc/image.go
Signed-off-by: Alberto Donato <alberto.donato@canonical.com>
=> Fix typo in comment

lxd/storage_ceph.go, lxd/storage_ceph_utils.go
=> ceph: set ACL on container copy

lxd/storage_dir.go
=> dir: use correct function

lxd/container.go
=> container: remove from db on storage failure

test/suites/image_auto_update.sh
=> tests: include lvm in image auto update

lxd/storage_ceph_utils.go
Signed-off-by: Greg Smith <me@smith.gr>
=> ceph: fix divide error

lxc/image.go, test/suites/basic.sh
=> lxc: Fix import crash when adding properties

lxd/networks.go
This should fix things for Solus users.
=> network: Don't require ipt_checksum

doc/api-extensions.md, lxd/api_1.0.go, lxd/daemon_config.go, lxd/storage_btrfs.go, lxd/storage_ceph.go, lxd/storage_lvm_utils.go, lxd/storage_pools_config.go, lxd/storage_utils.go, lxd/storage_volumes_config.go, test/suites/storage.sh
=> Support using btrfs as volume block filesystem

lxd/container_lxc.go
=> storage: If volume creation fails, delete DB entry

shared/api/response.go
=> Fix new golint warning

lxd/db/images.go, lxd/main_init.go
=> Fix image expiry and improve lxd init

lxd/main_init.go
=> init: Fix btrfs subvolume creation

lxd/storage_lvm_utils.go
=> network: only add --quiet-* options to dnsmasq if version supports them

lxd/daemon.go, shared/network.go
=> tls: Add some more TLS ciphers

lxd/storage_btrfs.go, lxd/storage_ceph.go, lxd/storage_ceph_utils.go, lxd/storage_lvm.go, lxd/storage_zfs.go
=> storage: don't fail on non existent storage entities

lxd/container_lxc.go
=> networks: Update dnsmasq on container renames

lxd/api_1.0.go, shared/osarch/architectures.go, shared/osarch/architectures_linux.go, shared/osarch/release.go, shared/osarch/release_test.go, shared/testhelpers/tempfile.go, shared/util.go, shared/util_linux.go, shared/version/flex.go, shared/version/platform_linux.go, shared/version/platform_others.go
=> Add OS, architecture and possibly distribution name and version to the User-Agent

shared/version/platform_linux.go
=> version: Only include kernel version, not build id

test/suites/storage.sh
Signed-off-by: Alberto Donato <alberto.donato@canonical.com>
=> test/storage: add tests using btrfs on LVM and ceph volumes

shared/osarch/release_test.go, shared/osarch/tempfile_test.go
=> testhelpers: Only build when running tests

test/suites/static_analysis.sh
=> tests: Fix dependency check

lxd/rsync.go
=> rsync: ignore vanished file warnings

lxc/image.go, test/suites/basic.sh, test/suites/remote.sh
=> lxc/image: Fix regression in exported filename

lxd/api_internal.go, lxd/container_lxc.go, lxd/storage.go, lxd/storage_btrfs.go, lxd/storage_ceph.go, lxd/storage_dir.go, lxd/storage_lvm.go, lxd/storage_lvm_utils.go, lxd/storage_mock.go, lxd/storage_volumes_utils.go, lxd/storage_zfs.go, test/suites/backup.sh
=> lxd import: rewrite

shared/util_linux.go
The mountpoint -q tool simply looks at /proc/<pid>/mountinfo per default and
falls back to stat()ing the relevant path in case /proc/<pid>/mountinfo does
not exist. There's really no point in spawning a new subprocess for this. Let's
simply pars /proc/<pid>/mountinfo per default and fallback to stat()ing when
the file doesn't exist or is busted.
Closes #3877.
=> util linux: implement mountpoint checking

lxd/images.go
=> images: Fix bad error message

lxd/daemon_images.go, shared/cancel/canceler.go
=> support canceling with parallel downloads

po/ja.po
Translate untranslated messages and messages marked fuzzy.
=> i18n: Update Japanese translation (for stable-2.0)

lxc/image.go, lxc/main.go, lxc/network.go, lxc/profile.go, lxc/rename.go, po/de.po, po/el.po, po/fr.po, po/id.po, po/it.po, po/ja.po, po/lxd.pot, po/nl.po, po/ru.po, po/sr.po, po/sv.po, po/tr.po, po/zh.po, po/zh_Hans.po, test/suites/basic.sh, test/suites/config.sh, test/suites/network.sh
=> Support renaming networks, profiles and image aliases

lxd/storage_dir.go
=> dir: make sure pool is mounted

lxd/storage_dir.go
=> dir: check whether pool is already mounted

shared/util.go
=> shared/util: More snap handling logic

lxd/util/resources.go
=> resources: Deal with missing cpufreq directory

lxd/main_init_test.go, lxd/seccomp.go, shared/container.go
=> seccomp blacklist fix and invalid key error tweak

client/connection.go, client/lxd.go, lxc/config/config.go, lxc/config/remote.go
=> client: Fix crash when missing cookiejar

lxd/daemon.go, test/includes/external_auth.sh
=> Fix build with current version of bakery

shared/util.go
=> Fix file transfers to/from stdin/stdout in snap

lxd/container_lxc.go
=> container: fix vfio logic

doc/api-extensions.md, doc/containers.md, lxd/api_1.0.go, lxd/container.go, lxd/container_lxc.go, lxd/networks_utils.go
=> Rename nictype=vfio to nictype=sriov

shared/util.go
=> If running as root in the snap, use /proc/1/root

client/connection.go, client/lxd.go, lxc/config/config.go, lxc/main.go, lxd/daemon.go, test/godeps.list, test/macaroon-identity/auth.go, test/macaroon-identity/formschema.go
Signed-off-by: Thomas Hipp <thomashipp@gmail.com>
=> all: move to bakery.v2

lxd/networks_config.go, lxd/storage_zfs_utils.go, test/includes/external_auth.sh, test/suites/init_auto.sh, test/suites/init_preseed.sh, test/suites/kernel_limits.sh, test/suites/storage.sh
=> Support newer ZFS, fix testsuite with older liblxc and stop requiring a low MTU for tunnels

shared/logging/log_posix.go
Allows building of the LXD client on FreeBSD.
Rudimentary testing shows that the client is functional, too.
Minuscule change, great profit for FreeBSD users. :)
Signed-off-by: Adrian Pistol <vifino@tty.sh>
=> shared/logging: Add freebsd build conditional to log_posix.go

lxd/storage_ceph.go, lxd/storage_ceph_utils.go, lxd/storage_lvm.go, lxd/storage_lvm_utils.go, lxd/storage_utils.go, test/suites/storage.sh
=> {ceph,lvm}: generate new UUIDS for btrfs filesystems

lxd/container_lxc.go
=> lxd/containers: Fix typo

test/suites/console.sh
=> {container_lxc, test}: runtime liblxc fixes

lxd/container_lxc.go, lxd/container_test.go
=> lxd/containers: Only init the config if needed

shared/idmap/idmapset_linux.go
=> shared/idmap: Fix handling of hardlinks

lxd/container_lxc.go
=> lxd/containers: Skip sockets in tarballs

lxc/main.go
=> lxc/shell: Switch to using su -l

lxd/devices.go
When the Nvidia driver isn't loaded the needed information about Nvidia gpu
devices cannot be gathered. In this case skip trying to list Nvidia cards.
Closes #4044.
=> gpu: skip non-existing Nvidia devices

lxd/storage_zfs.go
=> zfs: fix storage pool import

lxd/container_lxc.go, lxd/devices.go, lxd/patches.go
This encodes the device name into the path/name.
=> devices: switch to improved device naming scheme

lxd/certificates.go
=> lxd/certificates: Add missing name value

lxd/storage_zfs.go
=> zfs: Make sure to allow devices, setuid and exec

Makefile
=> Makefile: Don't hardcode gcc

doc/api-extensions.md, doc/containers.md, lxd/container.go, lxd/container_lxc.go, lxd/db/devices.go, lxd/devices.go, shared/version/api.go
=> api: add "infiniband" api extension

lxd/container_lxc.go
=> infiniband: name devices inside container ib<idx>

shared/util_linux.go
=> shared/utils: deal with symlinks

.travis.yml
=> travis: Limit to just Go 1.9

lxd/containers.go
=> lxd/containers: Fix race condition in shutdown

lxd/main.go
KishanRPatel
katiewasnothere
dinopanda
jialin-li
kianaalcala
Signed-off-by: KishanRPatel <kishanrpatel@utexas.edu>
=> Fixed typo in comment about SubCommands in lxd/main.go

lxd/container_lxc.go, lxd/patches.go
=> containers: Fix device names containing slashes

lxd/container_lxc.go, lxd/patches.go, lxd/profiles_utils.go
=> lxd/containers: Don't drop the description

scripts/vagrant/install-go.sh
=> scripts/vagrant: The LXD PPA is gone

doc/api-extensions.md, doc/containers.md, lxd/container.go, lxd/container_lxc.go, lxd/db/devices.go, lxd/main.go, lxd/main_args.go, lxd/main_nsexec.go, lxd/main_proxy.go, lxd/proxy_device_utils.go, shared/util.go, shared/version/api.go, test/main.sh, test/suites/proxy.sh
Signed-off-by: Kishan R Patel <kishanrpatel@utexas.edu>
Signed-off-by: Kathryn E Baldauf <kathrynbaldauf@utexas.edu>
Signed-off-by: Jasper Wu <jasperwu@utexas.edu>
Signed-off-by: Jialin Li <jialin_li@utexas.edu>
Signed-off-by: Kiana C Alcala <kiana.alcala@utexas.edu>
=> Added proxy device for forwarding tcp connections

lxc/file.go, test/suites/basic.sh, test/suites/proxy.sh
=> lxc/file: Fix edit in a snap environment

lxd/networks.go
=> networks: Drop all firewall rules when disabled

test/includes/lxd.sh, test/includes/setup.sh, test/includes/storage.sh, test/main.sh, test/suites/basic.sh, test/suites/config.sh, test/suites/image_auto_update.sh, test/suites/image_prefer_cached.sh, test/suites/init_auto.sh
=> test: fix shellcheck complaints

doc/containers.md
=> doc/containers: fix formatting

client/interfaces.go, client/lxd_images.go, client/simplestreams_images.go, client/util.go, lxc/utils.go, lxd/container_lxc.go, lxd/daemon_images.go, lxd/devices.go, lxd/images.go, shared/archive_linux.go, shared/ioprogress/data.go, shared/util.go, shared/util_linux.go
Move the functions `Unpack` and `DownloadFileSha256`, along with some dependencies, to shared.
=> move some functions to shared

lxd/container_lxc.go, lxd/migrate.go
Reported-by: Thomas Hipp <thomas.hipp@canonical.com>
=> container_lxc: ensure container is initialized

lxd/main_proxy.go
=> proxy: Fix environment handling

doc/containers.md
Signed-off-by: Goran Miskovic <schkovich@gmail.com>
=> The fifth argument of proxy add command should be connect and not listen

lxc/config.go
=> lxc/config: Fix metadata edit

lxd/container_lxc.go
=> containers: Default to pids cgroup for fork bomb mitigation

test/suites/proxy.sh
=> tests: Fix race in proxy test

config/bash/lxd-client, doc/api-extensions.md, doc/networks.md, lxd/networks.go, lxd/networks_config.go, shared/version/api.go
=> network: Add ipv4.dhcp.gateway

doc/api-extensions.md, lxc/file.go, lxd/container_file.go, lxd/main_nsexec.go, shared/version/api.go
=> file: Implement retrieving symlinks

lxc/main.go
=> lxc: Properly handle the --version flag

test/suites/config.sh
=> Check for LXC version to decide which apparmor profile config key to use

lxd-benchmark/benchmark/benchmark.go
=> lxd-benchmark: Fix new go vet warnings

lxd/endpoints/endpoints.go, lxd/endpoints/network.go
=> lxd: Rework listening logic

lxd/storage_zfs.go
=> zfs: Don't fail on missing image snapshot

test/suites/static_analysis.sh
=> tests: Drop lxd/sqlite golint test

test/perf.sh
=> tests: Fix perf.sh after lxd-benchmark changes

test/suites/init_preseed.sh
=> tests: Fix pool conflict in preseed

test/suites/backup.sh
=> tests: Fix race condition in import tests

test/perf.sh
=> tests: Fix perf.sh after clustering branch

lxd/container_lxc.go
=> lxd: Fix console logging after API change

doc/clustering.md
=> The "name" field is now called "server_name"

lxd/util/sys.go
=> Fix version parsing of LXC betas

lxd/main_shutdown.go
=> lxd/shutdown: Fix error string check

doc/index.md, doc/requirements.md
=> Bump Go requirement to 1.9 or higher

lxd/networks_iptables.go
=> network: Workaround iptables locking issues

lxd/daemon.go, lxd/db/migration.go
=> Cope with broken foreign key references when upgrading

lxd/storage_ceph.go, lxd/storage_lvm.go, lxd/storage_zfs.go
=> storage: do not mount custom volumes on create

lxd/containers_get.go
=> lxd/containers: Fix crash on container error

lxd/daemon.go, lxd/endpoints/local.go, lxd/endpoints/socket.go
=> lxd: Re-introduce early check for running daemon

lxd/endpoints/socket.go
=> lxd: Fix socket activated startup

doc/index.md
…to be able to run & pass our tests.
=> doc: when building our own lxc too, we need more deps

lxd/storage_btrfs.go
=> lxd/storage/btrfs: Optimize create from image

client/interfaces.go, client/lxd.go, client/lxd_cluster.go, client/lxd_containers.go, client/lxd_images.go, client/lxd_storage_volumes.go, client/operations.go, lxc/config.go, lxc/copy.go, lxc/delete.go, lxc/exec.go, lxc/image.go, lxc/publish.go, lxc/storage.go, lxc/utils/cancel.go, lxd-p2c/utils.go, lxd/container_console.go, lxd/container_exec.go, lxd/containers_post.go
=> client: Make Operation and RemoteOperation interfaces

lxd/main.go
=> lxd: Fix logging events

doc/api-extensions.md, doc/rest-api.md, lxc/monitor.go, lxd/container.go, lxd/container_lxc.go, lxd/events.go, po/lxd.pot, shared/api/event.go, shared/version/api.go
=> *: Add lifecycle events to events API

lxc/image.go
=> lxc/image: Fix import from URL

client/interfaces.go, client/lxd_storage_volumes.go, doc/api-extensions.md, doc/rest-api.md, lxc/storage.go, lxd/main_netcat.go, lxd/migrate.go, lxd/migrate_storage_volumes.go, lxd/storage.go, lxd/storage_btrfs.go, lxd/storage_ceph.go, lxd/storage_dir.go, lxd/storage_lvm.go, lxd/storage_migration.go, lxd/storage_mock.go, lxd/storage_volumes.go, lxd/storage_volumes_utils.go, lxd/storage_zfs.go, shared/api/storage_pool_volume.go, shared/version/api.go, test/suites/migration.sh
=> storage: remote {copy,move} custom storage volumes

lxd/main_init.go, lxd/main_init_auto.go, lxd/main_init_interactive.go, test/suites/clustering.sh
=> lxd: Fix auto init without a storage backend

test/suites/migration.sh
=> tests: add "push" and "relay" storage migration

shared/util.go
`distrobuilder` uses `DownloadFileSha256` to download and verify image tarballs. Gentoo however only provides sha512 checksums which makes the function unusable.
This PR adds a second function `DownloadFileSha512` which takes care of files with sha512 checksums.
=> shared: Add downloader with sha512 verification

doc/api-extensions.md, doc/containers.md, lxd/container_lxc.go, scripts/bash/lxd-client, shared/container.go, shared/version/api.go
=> Add support for NVIDIA runtime passthrough

lxd/containers_post.go
=> lxd/migration: Pre-validate profiles

client/lxd_containers.go, client/lxd_images.go, client/lxd_storage_volumes.go, client/util.go
=> client: Improve remote operation errors

doc/clustering.md
Just some clean up around the wording and fix some typos.
=> Fix some typos and wording.

lxd/main_init_auto.go, test/suites/init_auto.sh
=> lxd/init: Fix --auto with network config

lxc/file.go, test/suites/filemanip.sh
=> lxc/file: Fix pushing files to remote

lxc/network.go, po/de.po, po/el.po, po/es.po, po/fa.po, po/fi.po, po/fr.po, po/hi.po, po/id.po, po/it.po, po/ja.po, po/lxd.pot, po/nb_NO.po, po/nl.po, po/pa.po, po/pl.po, po/pt_BR.po, po/ru.po, po/sr.po, po/sv.po, po/tr.po, po/uk.po, po/zh.po, po/zh_Hans.po
=> Fix typo in help of "lxc network"

lxc/file.go
=> lxc/file: Allow using -r to follow symlinks

lxd/daemon.go
=> Replace juju/idmclient with CanonicalLtd/candidclient

Makefile
=> Makefile: Add a manifest

lxd/container_snapshot.go
=> containers: fix snapshot deletion

lxc/file.go
=> lxc/file: Fix pull target logic

doc/userns-idmap.md
=> doc: Fix example in userns-idmap

lxd/patches.go, lxd/storage.go, lxd/storage_btrfs.go, lxd/storage_ceph.go, lxd/storage_lvm.go, lxd/storage_utils.go, lxd/storage_zfs.go, lxd/sys/fs.go
=> storage api: fix permissions

doc/backup.md
=> doc: Tweak backup.md

doc/backup.md
Signed-off-by: Simon Deziel <simon@sdeziel.info>
=> doc/backup.md: update snap path

lxd/api_internal.go, lxd/db/cluster/open_test.go, lxd/db/cluster/schema.go, lxd/db/cluster/schema_export_test.go, lxd/db/cluster/update.go, lxd/db/node/update.go, lxd/db/query/dump.go, lxd/db/query/dump_export_test.go, lxd/db/query/dump_test.go, lxd/main_sql.go, test/main.sh, test/suites/backup.sh, test/suites/image.sh, test/suites/sql.sh
This is a first stab at #4390, it implements the low-hanging fruits. The rest will come in separate branches.
=> Improve database handling

doc/environment.md, lxd/container.go, lxd/container_lxc.go, test/suites/security.sh
Signed-off-by: Jingkui Wang <jkwang@google.com>
=> add LXD_UNPRIVILEGED_ONLY to disallow privileged containers.

lxc/action.go, lxc/utils/progress.go, lxd/container.go, lxd/container_lxc.go, lxd/container_state.go
=> lxd/containers: Allow sending progress

lxc/rename.go
=> lxc/rename: Deal with remote renames

lxd/networks_utils.go
=> lxd/network: Fix fan subnet calculation logic

lxd/patches.go
=> lxd/storage: Also set zfs.pool_name on upgrade

test/includes/lxd.sh, test/suites/clustering.sh, test/suites/init_auto.sh, test/suites/serverconfig.sh
=> tests: Add extra cleanup code

lxd/container_lxc.go, lxd/migrate_container.go, lxd/storage_btrfs.go
=> migration: fix btrfs live migration

lxd/container_lxc.go
This fixes:
- Setup of the inotify watch when required=false
- Empty file created when host file is missing
- Validation error when required=false an path missing
Closes #4495
=> lxd/containers: Fix broken unix hotplug logic

lxc/list.go
=> lxc/list: Reduce number of API calls

lxd/main_init_interactive.go
=> lxd/init: Offer to setup a Fan bridge when clustered

lxd/cluster/raft.go
This should mitigate/solve #4485 and similar issues.
=> Take raft snapshots more frequently and at shutdown

lxd/main_waitready.go
=> Make waitready less verbose

test/deps/import-busybox
=> test: Fix busybox image

lxc/action.go
=> lxc/action: Fix pause

lxd/main_init_auto.go
=> lxd/init: Have --auto setup networkng if missing

lxd/main_forkfile.go
Closes #4552.
Signed-off-by: Christian Brauner <christian@brauner.io>
=> forkfile: only open O_RDWR if necessary

lxd/storage_btrfs.go, lxd/storage_ceph.go, lxd/storage_dir.go, lxd/storage_zfs.go
=> container backup: fixes

lxd/storage_lvm_utils.go
=> lvm: use internal pool name

lxd-p2c/transfer.go
=> lxd-p2c: Add rsync version check

doc/rest-api.md, doc/storage.md, lxd/cluster/config.go, lxd/patches.go, lxd/storage_lvm_utils.go, lxd/storage_pools_config.go
=> lvm: s/LXDPool/LXDThinPool/g

test/backends/ceph.sh, test/includes/clustering.sh, test/suites/clustering.sh, test/suites/storage_driver_ceph.sh, test/suites/storage_local_volume_handling.sh
=> tests: Reduce ceph pg_num down to 1

lxd/main_forkmount.go
=> forkmount: ignore ENOENT and EINVAL on umount2()

lxd/devices.go
findNvidiaMinorOld() only handles the most common case; it's a bit of a placeholder.
Fixes #4617 for case of a single nvidia card (probably enough to reduce user complaints)
Very lightly tested.  This is my first go.
=> Fall back to alternate way of detecting minor version of Nvidia drivers if needed

doc/api-extensions.md, doc/containers.md, lxd/container_exec.go, lxd/container_lxc.go, lxd/db/query/dump.go, lxd/debug/memory.go, lxd/images.go, lxd/main_forkproxy.go, lxd/main_nsexec.go, lxd/migrate_container.go, lxd/proxy_device_utils.go, lxd/storage_lvm.go, shared/util_linux.go, shared/version/api.go, test/suites/proxy.sh
=> proxy: udp and unix support

lxc/export.go, lxc/import.go
=> lxc/{import,export}: Deal with snap paths

test/suites/proxy.sh
=> tests: make sure nc processes for udp and unix sockets die

lxd/cluster/resolve.go, lxd/response.go
=> lxd/cluster: Improve error on bad target

doc/api-extensions.md, doc/containers.md, lxd/main_forkproxy.go, shared/eagain/file.go, shared/version/api.go, test/main.sh, test/suites/proxy.sh
=> proxy: port ranges

doc/rest-api.md
This change adds links to each section, and fixes the section order.
=> doc: Add links to REST API

lxd/storage_zfs.go, lxd/storage_zfs_utils.go
=> lxd/storage/zfs: Improve defaults

lxd/certificates.go
=> lxd/certificates: Log password failures

test/main.sh, test/suites/basic.sh, test/suites/config.sh, test/suites/kernel_limits.sh, test/suites/static_analysis.sh
This addresses shellcheck v0.5.0 complaints.
=> test: Fix static analysis

lxd/container_lxc.go, lxd/devices.go
=> gpu: special case passing all GPUs

lxd/container_lxc.go, lxd/devices.go
=> gpu: don't fail during parse

lxd/container_lxc.go, lxd/devices.go
=> gpu: handle cards among Nvidia devices

lxd/devices.go
=> gpu: fix Nvidia minor index parsing

lxc/network.go
=> lxc/network: Add --format option to list

lxd/api_internal.go
=> lxd/db: Don't hang after bad request

lxd/container_lxc.go, lxd/storage.go, lxd/storage_btrfs.go, lxd/storage_ceph.go, lxd/storage_dir.go, lxd/storage_lvm.go, lxd/storage_shared.go, lxd/storage_zfs.go, lxd/storage_zfs_utils.go, shared/idmap/idmapset_linux.go
=> idmap: support skipping directories

lxd/storage_pools.go
=> lxd/storage: Fix PATCH on storage pools

doc/api-extensions.md, lxd/container.go, lxd/container_lxc.go, lxd/main_forkproxy.go, lxd/proxy_device_utils.go, shared/version/api.go
=> proxy: add non-abstract unix socket DAC properties

doc/containers.md
=> doc: Document hostname requirements

lxd/networks.go
=> lxd/networks: Skip DHCP mangle if firewall off

lxd/patches.go
This is to catch anyone who's upgraded to 3.0 but still has some 2.0
configs around.
=> lxd/patches: Force a one-time config re-gen

lxd/storage_btrfs.go
=> lxd/storage/btrfs: Fix recursive snapshots

lxd/cluster/connect.go
=> lxd/cluster: Fix attaching CEPH custom volumes

lxd/storage_ceph.go
=> lxd/storage/ceph: Don't keep snapshots mounted

test/includes/lxd.sh
=> tests: Perform a lazy umount in case of errors

lxd/main_init.go, lxd/main_init_dump.go, test/suites/init_dump.sh
=> Dump LXD config

lxc/profile.go
=> lxc/profile: Fix "get" command

doc/profiles.md, doc/rest-api.md, lxd/profiles.go, test/includes/check.sh, test/includes/lxd.sh, test/suites/basic.sh, test/suites/clustering.sh, test/suites/init_interactive.sh, test/suites/init_preseed.sh
=> Prevent deleting or renaming the default profile

lxd/db/storage_pools.go, lxd/storage_pools.go
The function should return the actual names, not the amount.
=> lxd: Fix StoragePoolVolumesGetNames

doc/api-extensions.md, doc/containers.md, lxd/container.go, lxd/container_lxc.go, lxd/main_forkproxy.go, lxd/proxy_device_utils.go, shared/version/api.go
=> lxd/proxy: Add support for PROXY header

lxd/patches.go
=> lxd/patches: Make config re-gen fault tollerant

doc/api-extensions.md
fix links in api-extension.md
Signed-off-by: Jingkui Wang <jkwang@google.com>
=> fix links in api-extension

lxd/networks.go
=> lxd/networks: Fix revert on update failure

lxd/storage_pools.go, test/suites/storage.sh
=> Allow deleting storage pools that only contain image volumes

lxd/db/cluster/schema.go, lxd/db/cluster/update.go, lxd/db/cluster/update_test.go, lxd/db/storage_pools.go
=> Make lvm.thinpool_name and lvm.vg_name node-specific

lxd/storage_ceph_utils.go, lxd/storage_lvm_utils.go, shared/util.go, test/suites/storage.sh
=> shared/util: Fix unit parsing (metric vs iec)

doc/api-extensions.md, doc/containers.md, lxd/container.go, lxd/container_lxc.go, lxd/iptables.go, lxd/main_forkproxy.go, lxd/main_forkproxy_test.go, shared/version/api.go, test/suites/proxy.sh
=> Optimized UDP/TCP proxying (NAT)

lxd/storage_zfs.go, lxd/storage_zfs_utils.go
=> zfs: Support querying version through modinfo

lxd/networks.go
=> lxd/networks: Fix port number for DHCPv6

client/interfaces.go, client/lxd_containers.go, doc/rest-api.md, lxc/copy.go, lxd/api_internal.go, lxd/backup.go, lxd/container_lxc.go
=> Don't include container name in backups/snapshots

lxc-to-lxd/main_migrate_test.go
=> tests: Fix lxc-to-lxd unit tests

doc/storage.md
=> doc: Fix typo

lxd/main_forkproxy.go
__{g,u}id_t are internal types
Closes #4848.
=> forkproxy: use correct types for {g,u}ids

lxd/networks_utils.go
The new logic introduced in 3.3 was both slower due to having to do
multiple file operations and also wrong as forknet doesn't actually have
the container's /sys view.
The result was the expected list of interfaces and addresses but
statistics coming from the host's device, if a matching one existed.
Closes #4851
=> networks: Fix packet stats logic for containers

lxc/storage.go, lxc/storage_volume.go, test/suites/storage.sh
=> lxc/storage: Fix bad argument parsing

lxd/main.go
=> lxd: Fix --syslog flag

lxd/containers.go, test/main.sh, test/suites/clustering.sh
=> Improve shutdown logic for cluster nodes

lxd/container_lxc.go
=> lxd/containers: Don't flush leases for snapshots

shared/idmap/idmapset_linux.go, shared/idmap/shift_linux.go
=> shared/idmap: Shift fscaps

lxd/db/node.go, lxd/db/operations.go, lxd/db/raft.go
=> lxd/cluster: Fix typo in errors

shared/idmap/shift_linux.go
=> shared/idmap: Fix xattr.h import

lxc/file.go, lxc/import.go, lxc/utils/progress.go, po/de.po, po/el.po, po/es.po, po/fa.po, po/fi.po, po/fr.po, po/hi.po, po/id.po, po/it.po, po/ja.po, po/ko.po, po/lxd.pot, po/nb_NO.po, po/nl.po, po/pa.po, po/pl.po, po/pt_BR.po, po/ru.po, po/sr.po, po/sv.po, po/tr.po, po/uk.po, po/zh.po, po/zh_Hans.po, shared/util.go
=> Show download progress for `lxc file` and `lxc import` subcommands

lxd/container_lxc.go, lxd/containers.go, lxd/daemon.go, lxd/devices.go, lxd/devlxd.go, lxd/logging.go, lxd/networks.go, lxd/networks_utils.go, lxd/patches.go, lxd/storage_lvm_utils.go
This should improve performance on systems with a lot of containers and a lot of network interfaces.
=> Improve cluster performance a bit

lxc/main_aliases.go, lxc/main_test.go
=> lxc: Allow aliases to external commands

lxd/db/containers.go, lxd/db/containers_test.go, lxd/db/devices_export_test.go
=> Add ContainerArgsList and ContainerArgsNodeList

lxc-to-lxd/main_migrate.go
=> lxc-to-lxd: Fix lxc.rootfs parsing

lxc-to-lxd/main_migrate_test.go
=> lxc-to-lxd: Fix rootfs tests

lxd/storage_zfs.go
=> lxd/storage/zfs: Optimize getting disk usage

Makefile
=> Makefile: Set PKG_CONFIG_PATH

doc/requirements.md
=> doc: Update requirements

doc/index.md
=> doc: Add some more packages to README

doc/index.md
=> doc: Pass LD_LIBRARY_PATH through sudo

doc/rest-api.md
=> doc: Add example of exec with record-output

lxd/devices.go
=> lxd/devices: Iterate /sys/class/drm for GPUs

doc/storage.md
=> doc: add note about ignoring mount options

shared/idmap/idmapset_linux.go, shared/idmap/shift_linux.go
=> shared/idmap: test fcaps support

lxd/api_internal.go, lxd/db/migration.go, lxd/db/node/update.go, lxd/db/query/dump.go, lxd/db/schema/query.go
=> Add a few missing rows.Close() calls

scripts/bash/lxd-client
I added security.protection.delete as seen in the code change, it seems simple but I don't know if I did it properly.
Signed-off-by: Eric Wolf <19wolf@gmail.com>
=> Add autocomplete phrase

lxd/patches.go
=> lxd/patches: Profiles are in the cluster db

lxd/storage_ceph.go
=> lxd/storage/ceph: Only freeze container if running

lxd/response.go, shared/api/response.go
=> shared/api: Don't re-define fields

test/suites/security.sh
=> tests: Always pass --force to stop

doc/api-extensions.md, doc/server.md, lxd/backup.go, lxd/cluster/config.go, lxd/container.go, lxd/storage.go, lxd/storage_btrfs.go, lxd/storage_ceph.go, lxd/storage_dir.go, lxd/storage_lvm.go, lxd/storage_mock.go, lxd/storage_zfs.go, scripts/bash/lxd-client, shared/version/api.go, test/suites/backup.sh
=> lxd/backups: Make compression configurable

lxd/images.go
=> lxd/images: Add missing cleanup code

lxd/container_file.go
=> lxd/containers: Fix bad function name

test/suites/pki.sh
=> tests: Fix pki with newer easyrsa

lxd/db/db_internal_test.go
=> lxd/db: Fix internal DB test

doc/containers.md
fix incorrect key name and make description easy to understand
=> doc: Fix and improve the description

lxd/operations.go
This line sounds to me that is an error.
=> operations: return true if operation is done before timeout

lxd/proxy_device_utils.go
=> lxd/proxy: Fix unix socket paths in snap

lxd/storage_volumes.go
=> lxd: Rename API endpoints

lxc/storage_volume.go
=> lxc: Identify snapshots when listed

shared/version/platform_linux.go
=> shared/version: Support detecting ChromeOS versions

lxd/main_checkfeature.go
The loopback device needs to be up for netnsid_getifaddrs() to actually
work. Let's avoid this churn and be smarter and assign a netnsid to the
host as seen from another network namespace.
Also, log an error on failure.
=> netnsid_getifaddrs: fix check for netnsid support

lxd/container_lxc.go
=> network_linux: handle network retrieval smarter

lxd/container_lxc.go, lxd/main_forkexec.go
=> lxd/containers: Rework exec FD handling

lxd/container.go
=> lxd/containers: Fix cleanup on create failure

lxd/devices.go
=> lxd/containers: Fix bad nvidia information parsing

doc/api-extensions.md, doc/storage.md, lxd/storage.go, lxd/storage_volumes_config.go, lxd/storage_volumes_utils.go, shared/version/api.go
=> lxd/storage: Implement security.unmapped

shared/netns_getifaddrs.c, shared/network_linux.go
=> network_linux: use struct_rtnl_link_stats64

lxc/remote.go, lxd/daemon.go
=> candid: Cleanup code a bit

shared/network.c
=> network: fix netns_get_nsid() signature

client/util.go, shared/network.go
=> candid: Fix client when using https candid server

Makefile, shared/i18n/i18n.go, shared/i18n/i18n_linux.go, shared/util_linux_notcgo.go
=> lxd-p2c: Fix static build

lxd/daemon.go, lxd/devices.go, lxd/main.go, lxd/main_checkfeature.go, lxd/main_forkuevent.go, lxd/main_nsexec.go, lxd/sys/os.go
=> lxd: support uevent injection for USB devices

lxc/config/remote.go
=> lxc/config: More TLS optimizations

lxd/main_checkfeature.go, shared/netns_getifaddrs.c, shared/network.c
=> netns_ifaddrs: support NETLINK_DUMP_STRICT_CHK

lxd/main_checkfeature.go
=> checkfeature: Avoid double line break

lxd/main_checkfeature.go
=> checkfeature: dial logging down from to debug

lxc/utils/progress.go
Closes: https://github.com/lxc/lxc/issues/2683
=> lxc/progress: Add terminal detection

doc/backup.md
=> doc: Rework backup documentation

doc/rest-api.md, lxc/project.go, lxd/db/cluster/update.go
=> lxd/projects: Fix some issues

lxd/images.go, test/suites/basic.sh
=> lxd/images: Fix parsing of public property

lxd/db/cluster/constants.go
=> lxd: Don't regress URLs for default project

lxd/api_internal.go, lxd/container.go, lxd/container_lxc.go, lxd/db/containers.go, lxd/db/containers.mapper.go, lxd/db/db_internal_test.go, lxd/db/devices.go, lxd/db/projects.go, lxd/profiles_test.go, lxd/profiles_utils.go, shared/generate/db/method.go, test/suites/projects.sh
=> Fix container profile in projects

po/de.po, po/fr.po, po/ja.po, po/lxd.pot
=> i18n: Update message catalogs and Japanese translation

po/ja.po
=> i18n: Update Japanese translation

lxd/containers.go, test/suites/clustering.sh
=> lxd/containers: Fix cluster shutdown

lxd/daemon.go, lxd/sys/os.go, shared/idmap/idmapset_linux.go, shared/idmap/shift_linux.go
=> checkfeature: check for vfs3 fscaps support 

lxd/db/cluster/update.go
Fixes #5162.
For this fix to properly work a build of dqlite v0.2.4 is needed.
=> Increase database timeout when creating indexes in db update 12

lxd/db/containers.go
=> db: Fix listing container backups

lxd/db/cluster/update.go
=> Speed up execution of update from v11 of the db

lxd/db/cluster/update.go
=> Sanitize references to containers table

client/lxd_events.go
Currently the EventListener.Disconnect() method just removes the listener from
the list, but does not close the underlying websocket connection (since there
might be other listeners). However if the list of event listeners has become
empty, the current logic won't close the connection since it's blocked on
conn.ReadMessage().
This change separates the job of fetching events via conn.ReadMessage() from the
job of monitoring if all listeners are gone.
This is an attempt to fix #5179: I was not able to reproduce the issue, but an event listeners leakage is the only thing that comes to my mind, and hopefully the scenario described above is indeed what's happening for real.
=> Prevent event listeners from lying around even after Disconnect()

lxd/container_console.go, lxd/container_exec.go
=> lxd/projects: Fix clustered exec/console

lxd/container.go
=> Fix bad check for recursive mounts

lxd/storage_zfs_utils.go, test/suites/projects.sh
=> Destroy the correct ZFS volume when deleting a container in a project

lxd/container.go
I caught this issue while working on a fix for #5203.
=> Consider the container's project when loading profiles in containerLoadAllInternal

lxd/storage_btrfs.go, lxd/storage_lvm.go, lxd/storage_zfs.go
=> lxd/storage: Fix importing preseed dump

lxd/container.go, lxd/container_lxc.go, lxd/db/containers.go, lxd/db/containers_test.go, lxd/db/profiles.go, lxd/db/storage_volumes.go, lxd/profiles_utils.go, test/suites/clustering.sh, test/suites/projects.sh
Before attaching a custom volume on a Ceph pool, check that it's either not attached to any container yet, or that it's attached to containers on the same node.
Fixes #5203.
=> Check if a ceph volume is on the same node of the target

lxd/backup.go, lxd/container_backup.go, lxd/daemon.go, lxd/db/containers.go, lxd/db/operations.go
=> Make backup expiry work

lxd/container_lxc.go, lxd/main_forkmount.go
Let's use the dedicated shmouts option for lxc.mount.auto mounts in
liblxc.
Needed-by: https://github.com/lxc/lxd/issues/5227
=> container_lxc: use lxc.mount.auto shmounts: option

lxd/daemon.go, lxd/patches.go
=> Detect and shrink large boltdb files

lxd/profiles_utils.go
=> lxd/projects: Fix profile updates

lxd/storage_cgo.go
If a loop device gets stolen in between getting an fd for it and setting
it up let's retry for a bit.
Closes #5246.
=> loop: retry on EBUSY

lxd/container_lxc.go, lxd/container_patch.go, lxd/container_put.go, lxd/container_state.go, lxd/storage_volumes_utils.go
=> lxd/containers: Fix missing project in args

lxd/container_lxc.go
=> lxd/containers: Prevent duplicate profiles

lxd/patches.go
=> lxd/patches: Add missing transition for symlinks

lxd/migrate_container.go
The source advertises what it will use, then the sink has to adapt and
receive it. We were doing pointless feature advertisement on the sink
side and then not passing the needed options for the CRIU part of the
transfer.
Closes #5243
=> lxd/migration: Fix CRIU rsync option negotiation

lxd/storage_dir.go
=> lxd/storage/dir: Don't fail when quota are set

lxd/container_lxc.go
=> lxd/containers: Respect optional=true for disks

doc/api-extensions.md, doc/containers.md, lxd/container.go, lxd/container_lxc.go, lxd/devices.go, shared/version/api.go
Sometimes I just want a stupid way to pass in everything.
Signed-off-by: Jingkui Wang <jkwang@google.com>
=> Don't require vendorid for USB devices

doc/api-extensions.md, doc/containers.md, lxd/container.go, lxd/container_snapshot.go, lxd/daemon.go, lxd/db/containers.go, shared/container.go, shared/util.go, shared/version/api.go
=> Snapshot scheduling

lxc/image.go
=> lxc/image: Fix rootfs file handling on snap

lxc/project.go
=> lxc/project: Check existence on switch

lxd/container_lxc.go
=> lxd/containers: Improve hwaddr retry logic

lxd/storage_zfs.go, lxd/storage_zfs_utils.go
=> lxd/storage/zfs: Detect tool version on Ubuntu

lxd/migrate.go, lxd/migrate_container.go, lxd/migrate_storage_volumes.go, lxd/migration/utils.go, lxd/rsync.go, lxd/storage_migration.go, lxd/storage_zfs.go
=> lxd/migration: Cleanup feature negotiation

lxd/main_init_interactive.go
=> lxd/init: Fix typo

lxd/storage_zfs.go
=> lxd/storage/zfs: Fix setting quotas on project

shared/termios/termios_other.go
=> shared/termios: Add shim for non-cgo builds

shared/idmap/shift_linux.go
=> shared/idmap: Workaround Go tip change

shared/network.go, shared/network_unix.go, shared/network_windows.go
=> shared: Fix windows cert handling

client/lxd_images.go
=> client: Fix crash on missing ProgressTracker

lxd/storage_zfs.go
=> lxd/storage/zfs: Fix missing dir on copy

doc/index.md
=> README: Update doc links

lxd/storage_zfs.go
=> lxd/storage/zfs: Fix dataset handling on copy

lxd/container.go
=> lxd/containers: bind default value is host

lxd/container_lxc.go
=> lxd/containers: Fix unix devices with liblxc 3.1

lxc-to-lxd/main_migrate_test.go, lxd/cluster/config_test.go, lxd/container_test.go
=> lxd: Fix go test

scripts/bash/lxd-client
=> bash: Add snapshot keys

lxc/monitor.go
=> lxc/monitor: Fix rendering

lxd/db/cluster/constants.go
=> lxd/projects: Fix crashes on project list

lxd/container_lxc.go, test/suites/fdleak.sh
=> lxd/containers: Adapt to go-lxc Release

lxc/image.go, po/de.po, po/el.po, po/es.po, po/fa.po, po/fi.po, po/fr.po, po/hi.po, po/id.po, po/it.po, po/ja.po, po/ko.po, po/lxd.pot, po/nb_NO.po, po/nl.po, po/pa.po, po/pl.po, po/pt_BR.po, po/ru.po, po/sr.po, po/sv.po, po/tr.po, po/uk.po, po/zh.po, po/zh_Hans.po
=> lxc: Fix image list help

shared/osarch/architectures.go
=> shared/osarch: Add armhfp (centos)

lxd/images.go
Include fingerprint and size metadata in CreateImage error
response when image already exists.  When creating an image
from a container snapshot, it is useful to know the fingerprint
of an existing image.  It can currently be parsed from the error
string, but this makes it more explicit.
=> lxd: Send metadata in CreateImage error response

lxd/container_lxc.go
Part of https://github.com/lxc/lxc/issues/2798
=> lxd/containers: Fix lxc.mount.entry for musl

client/connection.go
=> client: Strip trailing slashes in URLs

lxc/profile.go, po/de.po, po/el.po, po/es.po, po/fa.po, po/fi.po, po/fr.po, po/hi.po, po/id.po, po/it.po, po/ja.po, po/ko.po, po/lxd.pot, po/nb_NO.po, po/nl.po, po/pa.po, po/pl.po, po/pt_BR.po, po/ru.po, po/sr.po, po/sv.po, po/tr.po, po/uk.po, po/zh_Hans.po
Handy to have if we have to deal with lots of profiles.
=> Allow to format output for lxc profile list

lxd/api_internal.go, test/suites/config.sh, test/suites/fdleak.sh
=> tests: Tweak fdleak test

lxd/api_cluster.go
=> lxd/cluster: Don't prompt for internal config keys

lxd/images.go
By doing tar and compress in a combined stream, we require
1 less copy of the tarred image, and save time for IO for
writing and reading that file.
In my tests with an image of about 1.4GB when compressed this
saves 2.6GB of space used by the tar file, and reduces total
export time from approx 4m40s to 4m10s (30s quicker).
=> images: Tar and compress in a combined stream when packing an image

lxc/profile.go
=> lxc/profile: Make json/yaml consistent

shared/osarch/architectures.go
=> shared/osarch: Add gentoo armhf variant

client/lxd_certificates.go
Signed-off-by: Denis Khalturin <dhalturin@hotmail.com>
=> client: Fix empty return in GetCertificateFingerprints

lxd/db/migration_test.go
=> lxd/db: Fix tests for current go-sqlite3

lxd/container.go
=> lxd: Fix snapshot expiry for scheduled snapshots

lxd/container.go, lxd/container_lxc.go, lxd/networks.go, lxd/networks_config.go, lxd/networks_utils.go, lxd/storage_cgo.go
This is a bunch of modified cherry-picks from #5182, upstreaming some parts of the branch before I rebase it and take a closer look at the IPVLAN parts themselves.
=> Network fixes

shared/osarch/architectures.go
=> shared/osarch: Add ArchLinux name for armv7

lxd/main_forkfile.go, lxd/main_nsexec.go
=> lxd: remove /proc/self/cmdline parsing

lxd/main_nsexec.go
=> nsexec: make cmdline parsing more reliable

lxd/storage_lvm_utils.go
=> lxd/storage/lvm: Call wipesignatures

lxd/storage_ceph.go, lxd/storage_ceph_utils.go
=> lxd/storage/ceph: Rework df handling

lxc/remote.go
=> lxc/remote: Tweak remote list

lxd/devlxd_gccgo.go, lxd/include/compiler.h, lxd/include/macro.h, lxd/include/memory_utils.h, lxd/main_checkfeature.go, lxd/main_forkfile.go, lxd/main_forkmount.go, lxd/main_forkuevent.go, lxd/main_nsexec.go, lxd/storage_cgo.go, shared/idmap/shift_linux.go, shared/network.c, shared/util_linux_cgo.go
=> tree-wide: C code hardening

lxd/main_forkproxy.go
=> proxy: Add locking around UDP timer

lxc/exec.go
=> lxc/exec: Cleanup terminal logic

lxc/remote.go
=> lxc/remote: Use candid if supported

lxd/profiles.go
=> lxd/profiles: Fix project update when clustered

lxd/api_1.0.go, lxd/certificates.go, lxd/cluster/tls.go, lxd/daemon.go, lxd/images.go, lxd/util/http.go
=> lxd: Add username/fingerprint to request context

lxd/api_1.0.go, lxd/certificates.go, lxd/daemon.go, lxd/images.go
=> lxd: Cleanup authentication code

doc/faq.md
=> doc: Fix typoes in faq.md

lxd/response.go
=> lxd/response: Simplify SmartError

lxd/container_lxc.go
=> lxd/backup: Re-order checks for backup.yaml

lxd/storage_lvm.go
=> lxd/storage/lvm: Pass nouuid for xfs backups

doc/api-extensions.md
=> doc: Fix typo in api-extensions.md

lxd/networks.go
=> network: Bring mtu device up

lxd/devices.go
=> lxd: Don't leak netlink fds

lxd/api_cluster.go
=> lxd/cluster: Initialize candid on join

lxd/backup.go, lxd/storage_btrfs.go, lxd/storage_ceph.go, lxd/storage_dir.go, lxd/storage_lvm.go, lxd/storage_zfs.go
Reported at: https://discuss.linuxcontainers.org/t/4380
=> lxd/backups: Cleanup on failure

shared/simplestreams/simplestreams.go
Fix minor options for JSON creation of the images.json file.
=> simplestreams: Align JSON struct for images.json

doc/faq.md, doc/storage.md
=> Fix typo in faq.md and tweak format

lxd/containers_post.go
=> lxd/containers: Fix crash on refresh of non-existing

lxd/storage_btrfs.go, lxd/storage_ceph.go, lxd/storage_ceph_utils.go, lxd/storage_dir.go, lxd/storage_lvm.go, lxd/storage_lvm_utils.go, lxd/storage_volumes.go, lxd/storage_volumes_utils.go, lxd/storage_zfs.go, test/suites/storage_local_volume_handling.sh
=> Fix custom volume copies

shared/osarch/architectures.go
=> shared/osarch: Add i586 to arch aliases

lxd/patches.go
=> lxd/patches: Fix LVM VG name

client/lxd_containers.go
=> client: Don't crash on missing stdin

lxd/daemon_images.go
=> lxd/images: Fix simplestreams cache expiry

test/suites/security.sh
=> tests: Handle built-in shiftfs

client/lxd_storage_volumes.go, doc/api-extensions.md, lxd/migrate.go, lxd/migrate_storage_volumes.go, lxd/storage_btrfs.go, lxd/storage_ceph.go, lxd/storage_ceph_migration.go, lxd/storage_migration.go, lxd/storage_volumes.go, lxd/storage_volumes_utils.go, lxd/storage_zfs.go, shared/api/storage_pool_volume.go, shared/version/api.go, test/suites/migration.sh
=> Fix storage volume migration

lxd/storage_ceph.go
=> lxd/storage/ceph: Don't mix stderr with json

lxd/storage/quota/projectquota.go
=> lxd/storage/quota: Build on older systems

lxd/main_forkproxy.go
=> lxd/proxy: Fix goroutine leak

shared/network_windows.go
=> shared: Fix Windows build

doc/networks.md
Signed-off-by: tomponline <thomas.parrott@canonical.com>
=> doc: Updates docs for SNAT addresses.

lxd/main_forkproxy.go
=> forkproxy: non-functional changes

lxd/main_forkproxy.go
=> forkproxy: only attach to mntns for unix sockets

doc/api-extensions.md, shared/version/api.go
=> api: Fix network_nat_address extension

client/lxd_storage_volumes.go
=> client: Copy volume config and description

client/connection.go, client/interfaces.go, client/lxd.go, client/lxd_containers.go
=> client: Fix copying between two unix sockets

lxd/main_forkproxy.go
We only need to attach to the mount namespace for non-abstract unix
sockets.
=> forkproxy: handle mnts for abstract unix sockets

lxd/include/macro.h, lxd/main_checkfeature.go, shared/netns_getifaddrs.c, shared/network.c
s/NETLINK_DUMP_STRICT_CHK/NETLINK_GET_STRICT_CHK/g
=> netns_getifaddrs: adapt to kernel changes

lxd/api_1.0.go, lxd/api_cluster.go, lxd/cluster/config.go, lxd/daemon.go
=> lxd/candid: Cleanup config handling

lxd/api_1.0.go, lxd/daemon.go, lxd/main_checkfeature.go, lxd/sys/os.go
=> seccomp: detect listener support

lxd/migrate_container.go
=> lxd/migration: Fix feature negotiation

lxd/images.go
=> lxd/images: Replicate images to the right project

lxd/container.go
=> lxd/containers: Fix profile snapshot settings

lxd/certificates.go
=> lxd/certificates: Make certificate add more robust

doc/containers.md
=> doc: Correct host_name property

lxd/cluster/raft.go
=> lxd/cluster: Workaround new raft logging

lxd/container_snapshot.go
=> lxd/containers: Speed up simple snapshot list

lxd/container_lxc.go, lxd/db/containers.go, lxd/db/containers.mapper.go, lxd/db/containers_test.go, shared/generate/db/method.go, shared/generate/db/stmt.go
=> lxd/containers: Optimize snapshot retrieval

lxd/storage/quota/projectquota.go
=> lxd/storage/quota: guard quota defs for compiling

lxd/container_put.go
=> lxd/containers: Fix bad operation type

doc/api-extensions.md, lxd/container_lxc.go, lxd/daemon.go, lxd/main.go, lxd/main_forkmknod.go, lxd/main_nsexec.go, lxd/seccomp.go, shared/util_linux_cgo.go, shared/version/api.go
=> seccomp: add support for SECCOMP_RET_NOTIF_USER

lxd/storage_ceph.go, lxd/storage_ceph_utils.go
=> lxd/storage/ceph: Only rewrite UUID once

lxd/cluster/heartbeat.go, lxd/cluster/membership.go
=> lxd/cluster: Fix race condition during join

lxd/container_lxc.go, lxd/seccomp.go
=> lxd/seccomp: Really handle old libseccomp

lxd/containers_post.go
=> lxd/container: Early check for running container refresh

lxd/daemon_images.go
=> lxd/images: Properly handle invalid protocols

lxd/container_lxc.go, test/suites/container_devices_nic_ipvlan.sh
Some small modifications to make a test less dependent on prior environment setup, and to allow the IPVLAN stuff to be expanded later.
=> network: IPVLAN cleanup

lxd/container_lxc.go
Also alerts user if they try to add ipvlan nic to running container.
=> container/lxc: Fixes ipvlan support check

lxd/networks_utils.go
=> lxd/network: Log failures to reload

doc/networks.md
=> doc: Fix typo in networks.md

doc/containers.md
=> doc: Removes trailing whitespace

lxd/container_lxc.go
=> lxd/container_lxc: Adds IPVLAN L3S mode l2proxy sysctl checks

doc/environment.md, doc/index.md, doc/security.md, doc/server.md
=> doc: Clarify API security and options to restrict

lxd/storage_zfs.go
=> lxd/storage/zfs: Fix snapshot restore on project

lxd/cluster/gateway.go, lxd/cluster/upgrade.go
=> Trigger the upgrade script if we detect a dqlite client with higher version

scripts/empty-lxd.sh
=> scripts: Add script to completely reset LXD

lxd/networks.go
=> lxd/networks: Fix ETag handling on clusters

lxd/container_lxc.go
=> lxd/containers: Fix bad error

lxd/images.go
=> lxd/images fix compressErr return

lxd/patches.go, lxd/proxy_device_utils.go
=> lxd: Satisfy static analysis

lxd/db/containers.go
=> lxd/db: Sort container snapshots by creation date

lxd/storage_zfs.go
=> zfs: Handle projects correctly

lxd/container_lxc.go
Also clears volatile host_name keys when container stops.
=> container/lxc: Moves volatile host_name enrichment to fillNetworkDevice

lxd/storage_btrfs.go
=> Don't change permissions of existing containers directory

doc/containers.md
=> doc: IPVLAN doc tweaks for gateway and DNS nameservers

lxd/seccomp.go
=> seccomp: handle mknodat

lxd/storage_volumes_config.go
Should have done that when I implemented project quotas.
=> lxd/volumes: Allow quota on ext4

lxd/patches.go
=> lxd/patches: Fix handling of containers-snapshots

lxd/storage_btrfs.go
We are deleting qgroups but not re-creating them when needed...
Closes #5842
=> lxd/storage/btrfs: Fix qgroup handling

lxd/seccomp.go
=> seccomp: define __NR_mknod if missing

lxd/patches.go
=> lxd/patches: Handle btrfs snapshots properly

lxd/main_checkfeature.go, lxd/main_forkmknod.go
=> cgo: bugfixes

lxd/main.go
=> main: Fixes debug mode flag to actually enable debug mode

test/suites/container_devices_nic_bridged.sh
=> tests: Make shellcheck happy

lxd-p2c/main_migrate.go
=> lxd-p2c: Add --storage-size option

shared/termios/termios_bsd.go, shared/termios/termios_linux.go, shared/termios/termios_unix.go
=> shared/termios: Fix port to sys/unix

lxd/patches.go, lxd/rsync.go, lxd/storage_btrfs.go, lxd/storage_ceph.go, lxd/storage_ceph_utils.go, lxd/storage_dir.go, lxd/storage_lvm.go, lxd/storage_lvm_utils.go, lxd/storage_zfs.go
A couple of fixes I got while working on the CEPHFS backend.
=> Storage fixes

lxd/main_daemon.go, test/suites/security.sh
=> lxd: Better handle bad commands

lxc/storage_volume.go, lxd/storage_btrfs.go, lxd/storage_ceph.go, lxd/storage_dir.go, lxd/storage_lvm.go, lxd/storage_zfs.go, test/suites/storage_snapshots.sh
=> Fix volume snapshot renaming

doc/storage.md, lxd/storage_cephfs.go
=> lxd/storage/cephfs: Cleanups

lxd/networks.go
=> lxd/networks: Allow querying state on non-managed

lxd/container_lxc.go, lxd/main_forkmknod.go, lxd/seccomp.go
Reported-by: Stéphane Graber <stgraber@ubuntu.com>
=> seccomp: ensure correct owner on __NR_mknod{at}

lxd/cluster/gateway.go
=> Perform heartbeats only on the leader

lxd/storage_lvm.go
Also optimises volume group reporting to avoid running vgs twice by retrieving both fields needed in one go.
Fixes #5868
=> storage/lvm: Adds spaced used reporting for LVM thinpools

lxd/container_lxc.go
Moves stop time physical/sriov device detach into cleanupNetworkDevices.
This paves the way for the device interface to move all other host-side setup/cleanup out of container_lxc.go.
=> container/lxc: Moves on stop device detach into single place

lxd/container_lxc.go
Moves all nic hot plug functionality into separate functions
=> container/lxc: Moves NIC hotplugging into own functions

lxd/container_lxc.go, lxd/networks_utils.go
Fixes https://github.com/lxc/lxd/issues/5891
=> Clean up old DHCPv6 leases when IPv6 static IP changed.

lxd/container_lxc.go
=> lxd/containers: Fix snapshot restore on ephemeral

lxd/container_metadata.go
Fix error messages and handle cases where templates.yaml or templates
directory are missing.
=> lxd/containers: Fix template handling

lxd/seccomp.go, shared/netutils/network_linux.go, shared/netutils/unixfd.c
=> seccomp: handle new liblxc seccomp notify updates

lxd/container_lxc.go, lxd/db/containers.go
=> lxd/containers: Combine state updates

lxd/container_instance_types.go
=> lxd/instances: Improve errors

lxd/main_forkmknod.go, lxd/seccomp.go
=> seccomp: handle compat arch syscalls

lxd/seccomp.go
If liblxc is sending us messages of an indeterminate size we have two
options:
1. trigger a default response and _close_ the connection
2. trigger a default connection and _keep_ the connection
Option 1. means that we keep hanging the container for 30s on each
request. If liblxc is sending us garbage or a message of unknown size.
Options 2. means we keep handling the requests and responding with a
dummy response without doing anything. This will cause liblxc to respond
with the defaule ENOSYS response to the kernel. The container will not
be stalled.
I think option 1. is better than option 2.
=> seccomp: cause a default message to be sent

shared/netutils/unixfd.c
Signed-off-by: Thomas Parrott <tomp@tomp.uk>
=> shared/netutils: Fixes bug with getting container PID

lxd/container_lxc.go, lxd/main_forkmknod.go, lxd/seccomp.go
=> seccomp: fix error reporting

lxd/storage_cephfs.go
=> lxd/storage/cephfs: Handle multiple mons

lxd/container_lxc.go, lxd/main_forkmknod.go, lxd/seccomp.go, shared/idmap/shift_linux.go
=> seccomp: simplify and make more secure

lxd/main_forkproxy.go
=> lxd/proxy: Fix error handling for unix

lxd/backup.go, lxd/cluster/events.go, lxd/cluster/gateway.go, lxd/cluster/gateway_test.go, lxd/cluster/heartbeat.go, lxd/cluster/heartbeat_test.go, lxd/cluster/migrate_test.go, lxd/cluster/upgrade.go, lxd/cluster/upgrade_test.go, lxd/container.go, lxd/container_instance_types.go, lxd/daemon.go, lxd/images.go, lxd/logging.go, lxd/networks_utils.go, lxd/task/func.go, lxd/task/group.go, lxd/task/group_test.go, lxd/task/task.go, lxd/task/task_test.go, lxd/util/http.go, test/macaroon-identity/auth.go
=> various: Removes use of golang.org/x/net/context in place of stdlib

lxd/main_forkmknod.go, lxd/seccomp.go
=> seccomp: more security enhancements

lxd/storage_dir.go, lxd/storage_volumes_config.go
=> lxd/storage: Allow size limits on dir volumes

lxd/container_lxc.go
=> container/lxc: fixes return value of detachInterfaceRename

lxd/api.go, lxd/api_cluster.go, lxd/cluster/gateway.go, lxd/cluster/gateway_test.go, lxd/cluster/heartbeat.go, lxd/cluster/heartbeat_test.go, lxd/cluster/membership.go, lxd/cluster/membership_test.go, lxd/cluster/upgrade.go, lxd/cluster/upgrade_test.go, lxd/daemon.go, lxd/networks.go, lxd/networks_utils.go, lxd/task/group.go
Addresses https://github.com/lxc/lxd/issues/5824
=> Use cluster heartbeats to notify of needed LXD update

lxd/seccomp.go, shared/netutils/network_linux.go
=> seccomp: cleanup + simplify

Makefile
=> Makefile: include libraft and libco

lxd/seccomp.go
=> bugfix, cleanup, and simplify 

lxd/container_lxc.go, lxd/iptables/iptables.go, lxd/networks.go
For use both from LXD main and from the new devices package.
=> iptables: Moves iptables helper functions into own package

lxd/main.go, lxd/main_forksyscall.go, lxd/main_nsexec.go, lxd/seccomp.go
=> seccomp: abstract syscall handling

lxd/api_internal.go, lxd/api_project.go, lxd/apparmor.go, lxd/container_lxc.go, lxd/networks_utils.go, lxd/project/project.go, lxd/storage.go, lxd/storage_btrfs.go, lxd/storage_ceph.go, lxd/storage_ceph_migration.go, lxd/storage_ceph_utils.go, lxd/storage_dir.go, lxd/storage_lvm.go, lxd/storage_lvm_utils.go, lxd/storage_migration.go, lxd/storage_zfs.go, lxd/storage_zfs_utils.go
=> lxd/project: Adds project package and updates references to it

lxd/container_lxc.go, lxd/dnsmasq/dnsmasq.go, lxd/networks.go, lxd/networks_utils.go
Also includes project package from PR https://github.com/lxc/lxd/pull/5951
=> dnsmasq package

test/suites/clustering.sh
=> tests: Fix CEPH pool names

test/suites/clustering.sh
=> tests: Avoid ceph pool conflict

lxd/main_forksyscall.go
=> forksyscall: mknod fixes

lxd/main_forksyscall.go
=> forksyscall: switch chdirchroot() and setns() order

lxd/main_forksyscall.go, lxd/seccomp.go
Sigh, until we have a method to:
- tell seccomp to resume a syscall if we tell it to do so
- have seccomp filter pointer arguments as well
we are stuck in the unfortunate situation that we can't nicely handler
syscalls with pointer arguments.
This brings us to setxattr() which is just such a syscall - YAY ME.
I want to be clear that what we do here is a best-effort to handle this
but it is not necessarily to be considered safe and this feature needs
to come with the appropriate big fat warning. I have no desire to get
CVEed because of this feature.
What I do is to add the following filter:
setxattr(const char *path /* we can't filter on this */,
const char *name /* we can't filter on this */,
const void *value /* we can't filter on this */,
size_t size /* we can filter on this since
* …
=> seccomp: handle setxattr syscall

lxd/migrate_storage_volumes.go
=> lxd/storage: Fix hangs on volume migration failures

lxd/main_forksyscall.go
Link: https://launchpadlibrarian.net/433373076/buildlog_snap_ubuntu_xenial_amd64_lxd-latest-edge_BUILDING.txt.gz
Reported-by: Stéphane Graber <stgraber@ubuntu.com>
=> forksyscall: protect CLONE_NEWCGROUP with ifdef

lxc/list.go
=> lxc/list: If no snapshots, show 0

lxd/container_lxc.go, lxd/main_forksyscall.go, lxd/seccomp.go
=> seccomp: improvements

shared/util_linux.go
=> shared: Don't open files to get their mode

lxd/cluster/gateway.go, lxd/cluster/heartbeat.go, lxd/cluster/heartbeat_test.go, lxd/daemon.go, lxd/task/task.go
=> lxd/cluster: Use hook for initial heartbeat

lxd/cluster/gateway.go
=> Workaround watchFunc kicking hearbeats to early

test/suites/container_devices_nic_bridged_filtering.sh
=> tests: Always pass -f to stop

lxc-to-lxd/main_migrate.go, lxc-to-lxd/main_migrate_test.go, lxd/api_project.go, lxd/container.go, lxd/container_lxc.go, lxd/container_test.go, lxd/containers_post.go, lxd/db/containers.go, lxd/db/containers_test.go, lxd/db/db_internal_test.go, lxd/db/devices.go, lxd/db/profiles.go, lxd/device/config/devices.go, lxd/device/config/devices_sort.go, lxd/device/config/devices_test.go, lxd/device/config/devices_utils.go, lxd/device/device_instance_id.go, lxd/seccomp.go, lxd/storage_migration.go, test/suites/static_analysis.sh
Updates all references to types.* to device.config.*
=> device/config: Moves types.* to device.config.*

lxd/main_forksyscall.go, lxd/seccomp.go
=> seccomp: improve syscall interception

lxd/main_forksyscall.go
=> lxd/seccomp: Fix broken setxattr

lxd/main_forksyscall.go
=> forksyscall: introduce acquire_basic_creds()

lxd/main_checkfeature.go
Link: https://discuss.linuxcontainers.org/t/error-while-compiling-lxd-3-14-3-15/5262
=> checkfeature: ifdef SECCOMP_GET_ACTION_AVAIL

lxd/container_lxc.go, lxd/maas/controller.go, lxd/response.go
Ran into this was I was looking into #6014
=> Various MAAS related fixes

lxd/images.go
=> lxd/images: Fix crash on refresh error

test/suites/clustering.sh
=> test: Works around race condition in image import event listener

lxd/device/nic_bridged.go, test/suites/container_devices_nic_bridged_filtering.sh
Adds explicit checks for the scenario where DHCP is disabled on the managed parent and no static IP is set on the NIC device.
=> Bridged IP Filtering DHCP checks

shared/simplestreams/simplestreams.go
=> shared/simplestreams: Add support for combined.tar.gz

doc/containers.md
=> doc: Updates proxy bind settings to host or guest

lxd/storage_zfs_utils.go
=> lxd/storage/zfs: Properly wrap mount error

lxc/alias.go, lxc/cluster.go, lxc/config_template.go, lxc/config_trust.go, lxc/image.go, lxc/image_alias.go, lxc/list.go, lxc/network.go, lxc/operation.go, lxc/profile.go, lxc/project.go, lxc/remote.go, lxc/storage.go, lxc/storage_volume.go, lxc/utils.go, lxd/storage_zfs.go, lxd/storage_zfs_utils.go, test/suites/container_devices_nic_bridged.sh, test/suites/container_devices_nic_bridged_filtering.sh, test/suites/container_devices_nic_macvlan.sh
=> Various fixes ahead of LXD 3.16

test/suites/storage_driver_ceph.sh
=> tests: Fix CEPH RBD leakage

lxd/storage_cgo.go
=> lxd: Remove MS_LAZYTIME definition

lxd/storage_lvm_utils.go
=> lxd/storage/lvm: Log actual error

lxd/storage.go, lxd/storage_btrfs.go, lxd/storage_ceph.go, lxd/storage_cephfs.go, lxd/storage_dir.go, lxd/storage_lvm.go, lxd/storage_volumes.go, lxd/storage_volumes_snapshot.go, lxd/storage_volumes_utils.go, lxd/storage_zfs.go
=> lxd/storage: Fix bad UsedBy check

lxd/response.go, test/suites/backup.sh
=> lxd/response: Show wrapped errors

shared/util.go
=> shared: Handle symlinks in FileCopy()

doc/api-extensions.md, doc/server.md, lxd/api_1.0.go, lxd/daemon.go, lxd/daemon_storage.go, lxd/node/config.go, lxd/storage_volumes.go, lxd/storage_volumes_snapshot.go, lxd/storage_volumes_utils.go, scripts/bash/lxd-client, shared/version/api.go, test/suites/serverconfig.sh
=> Add support for on-pool backups/images files

lxc/utils.go
=> lxc: Don't show header in CSV output

doc/metadata.yaml
=> doc: Add documentation metadata

lxd/container.go, lxd/container_lxc.go, lxd/daemon.go, lxd/device/device.go, lxd/device/device_instance_id.go, lxd/device/device_runconfig.go, lxd/device/device_utils_unix.go, lxd/device/device_utils_usb.go, lxd/device/gpu.go, lxd/device/infiniband_physical.go, lxd/device/infiniband_sriov.go, lxd/device/usb.go, lxd/devices.go, lxd/main_forkuevent.go, shared/container.go
Migration of usb device into the new device interface.
Part of #5819
Still WIP.
Includes https://github.com/lxc/lxd/pull/6050
=> Device USB

lxc/main.go
=> lxc: Just show help on missing subcommand

lxd/device/gpu.go
Updates GPU device to use resources package for probing info about the GPUs available on the host.
Includes  https://github.com/lxc/lxd/pull/6100
=> GPU device port to use resources package

lxd/container_lxc.go
Removes volatile device keys when device is removed. 
Or when a device is updated such that it's device type changes.
It will also ensure that if the device type remains the same but the new device's config replaces an old volatile key that the old volatile key is removed.
Fixes issue where `hwaddr` property was left even if device type changed from profile's `bridged` type to manually added `infiniband` type.
Also ensures existing behaviour of a profile `bridged` device's `name` property replacing an old `name` volatile key when a manually added device is removed and the profile device is re-added.
This re-works the old code that was device and key name specific with a device type agnostic version.
=> container/lxc: Removes volatile device keys when device is removed

lxd/device/device_utils_infiniband.go
=> lxd/infiniband: Workaround weird sysfs behavior

Makefile
=> Makefile: Fix sqlite manifest path

lxd/db/cluster/update.go, lxd/db/cluster/update_test.go
=> Fix selecting NULL description columns

lxd/storage_zfs_utils.go
=> lxd/storage/zfs: Fix error reporting

doc/storage.md
=> doc/storage: Clarify defaults for size

lxc/file.go
=> lxc/file: Fix error handling

doc/storage.md
=> doc/storage: Typo and example fix

lxd/networks.go
Closes #6165
Suggested-by: Skruppy <skruppy@onmars.eu>
=> lxd/networks: Allow ipv6.dhcp=true with ipv6.firewall=false

lxd/storage_dir.go
=> lxd/storage/dir: Don't hide error message

shared/util.go
Use Lchown when copying symlinks.
=> shared: Use Lchown when copying symlinks

lxd/networks.go, lxd/networks_config.go
=> lxd/networks: Allows limited ipv4 config with fan

lxd/api_1.0.go
This allows modifying cluster.https_address when LXD isn't clustered yet.
Closes #6167
=> lxd/config: Allow modifying cluster.https_address

lxd/container.go, lxd/container_lxc.go, lxd/containers.go, lxd/containers_get.go, lxd/daemon.go, lxd/devices.go, lxd/devlxd.go, lxd/networks.go, lxd/networks_utils.go, lxd/storage_volumes_utils.go
- And changes return type to []Instance
=> lxd: Renames containerLoadNodeAll to instanceLoadNodeAll

lxd/container_lxc.go
=> lxd/containers: Respect raw.lxc on stop/shutdown

shared/generate/db/mapping.go
=> shared/generate: Support instance.Type

lxd/devlxd.go
=> lxd/devlxd: Fix handling of projects

lxd/storage_ceph.go
=> lxd/storage/ceph: Fix volume snapshot handling

lxc/main.go
=> lxc: Don't print first-use on init/launch

lxd/db/db.go, lxd/db/operations.go
=> lxd/db: Flush any leftover operation on startup

lxd/api_cluster.go, lxd/api_project.go, lxd/backup.go, lxd/container.go, lxd/container_backup.go, lxd/container_console.go, lxd/container_delete.go, lxd/container_exec.go, lxd/container_instance_types.go, lxd/container_post.go, lxd/container_put.go, lxd/container_snapshot.go, lxd/container_state.go, lxd/containers_post.go, lxd/images.go, lxd/logging.go, lxd/migrate_container.go, lxd/operations/operations.go, lxd/storage_volumes.go, lxd/storage_volumes_snapshot.go
=> lxd/operations: Use state struct

lxd/container.go, lxd/container_lxc.go, lxd/daemon.go, lxd/devlxd.go, lxd/events.go, lxd/events/events.go, lxd/events/logging.go, lxd/main.go, lxd/main_forkdns.go, lxd/operations/operations.go, lxd/state/state.go, lxd/state/testing.go, shared/api/event.go
This allows multiple users of the events package with their own list of listeners and configuration.
=> Switch to fully standalone events package

.github/SUPPORT.md
=> doc: Update remaining reference to readthedocs

lxd/device/device_utils_network.go
=> lxd/devices/nic: Set MTU on both side of veth

lxd/cgroup/cgroup_cpu.go, lxd/container_lxc.go, lxd/devices.go
Created cgroup package and moves CPU task balancing code out of main package and into cgroup package. This is part of the work to move containerLXC out of main package.
=> Cgroup package

lxd/container.go, lxd/container_backup.go, lxd/container_lxc.go, lxd/devlxd.go, lxd/instance_interface.go
=> lxd: Changes instance and containerLXC function Id() to ID()

lxc/info.go, lxc/list.go, po/bg.po, po/de.po, po/el.po, po/es.po, po/fa.po, po/fi.po, po/fr.po, po/hi.po, po/id.po, po/it.po, po/ja.po, po/ko.po, po/lxd.pot, po/nb_NO.po, po/nl.po, po/pa.po, po/pl.po, po/pt_BR.po, po/ru.po, po/sl.po, po/sr.po, po/sv.po, po/te.po, po/tr.po, po/uk.po, po/zh_Hans.po
=> lxc: Changes lxc list and lxc info Type field to show instance type

lxc/info.go, lxc/list.go
=> lxc/{list,info}: Fix type on older LXD

lxd/device/disk.go
=> lxd/device/disk: Apply limits through post hook

lxd/device/disk.go
- Removes duplicated `if diskPriority != ""` check.
- Don't try and apply limits on stopped container during update.
- Fail if limits on a device are specified but device isn't mounted yet (this avoids silently not setting limits).
- Fixes path detection of expanded devices when applying limits.
=> lxd/device/disk: Improvements in disk limits

doc/contributing.md
=> doc: Add commit structure to contributing.md

lxd/storage_ceph_utils.go
=> lxd/storage/ceph: Fix to work on older releases

doc/debugging.md
Should fix rendering of this doc on https://linuxcontainers.org/lxd/docs/master/debugging
=> fix debugging.md rendering

lxd/sys/fs.go
=> lxd/sys: Enforce directory permissions

lxd/daemon.go
=> lxd/daemon: Bump NOFILE to max on startup

lxc/list.go, lxc/list_test.go, po/bg.po, po/de.po, po/el.po, po/es.po, po/fa.po, po/fi.po, po/fr.po, po/hi.po, po/id.po, po/it.po, po/ja.po, po/ko.po, po/lxd.pot, po/nb_NO.po, po/nl.po, po/pa.po, po/pl.po, po/pt_BR.po, po/ru.po, po/sl.po, po/sr.po, po/sv.po, po/te.po, po/tr.po, po/uk.po, po/zh_Hans.po
=> Support device keys as `lxc list` columns

lxd/api_1.0.go, lxd/daemon.go, lxd/include/lxd_seccomp.h, lxd/main_checkfeature.go, lxd/seccomp/seccomp.go, lxd/sys/os.go
=> seccomp: implement syscall continuation

shared/netutils/network_linux.go, shared/netutils/unixfd.c, shared/netutils/unixfd.h
=> unixfd: split into unixfd.{c,h}

lxd/include/compiler.h, shared/netutils/netns_getifaddrs.c, shared/netutils/network.c, shared/netutils/unixfd.h
=> unixfd: hide symbols

Makefile
=> Makefile: Switch to tsenart/deadcode

lxd/include/compiler.h
=> lxd/include: Don't include missing file

Makefile, lxd-p2c/setns.go, lxd/include/compiler.h, lxd/main_checkfeature.go, lxd/main_forkdns.go, lxd/main_forkfile.go, lxd/main_forkmount.go, lxd/main_forknet.go, lxd/main_forkproxy.go, lxd/main_forksyscall.go, lxd/main_forkuevent.go, lxd/main_nsexec.go, lxd/seccomp/seccomp.go, lxd/storage/quota/projectquota.go, lxd/storage/storage_cgo.go, lxd/ucred/ucred_gccgo.go, shared/idmap/shift_linux.go, shared/netutils/netns_getifaddrs.c, shared/netutils/network.c, shared/netutils/network_linux.go, shared/netutils/unixfd.h, shared/termios/termios_unix.go, shared/util_linux_cgo.go
=> tree-wide: rework cgo compilations

lxd-p2c/cgo.go, lxd-p2c/setns.go, lxd/cgo.go, lxd/main_checkfeature.go, lxd/main_forkdns.go, lxd/main_forkfile.go, lxd/main_forkmount.go, lxd/main_forknet.go, lxd/main_forkproxy.go, lxd/main_forksyscall.go, lxd/main_forkuevent.go, lxd/main_nsexec.go, lxd/seccomp/cgo.go, lxd/seccomp/seccomp.go, lxd/storage/cgo.go, lxd/storage/quota/cgo.go, lxd/storage/quota/projectquota.go, lxd/storage/storage_cgo.go, lxd/ucred/cgo.go, lxd/ucred/ucred_gccgo.go, shared/cgo.go, shared/idmap/cgo.go, shared/idmap/shift_linux.go, shared/netutils/cgo.go, shared/netutils/network_linux.go, shared/termios/cgo.go, shared/termios/termios_unix.go, shared/util_linux_cgo.go
=> cgo: more hardening

lxd/storage/drivers/errors.go, lxd/storage/drivers/utils.go, lxd/storage/drivers/utils_test.go, lxd/storage/drivers/volume.go, lxd/storage/errors.go, lxd/storage/storage.go
This PR comes from #6285, but to make that PR smaller I am breaking it into parts.
This PR adds some generic storage driver utils and definitions which will be used by the driver implementations to come.
=> Storage Driver Utils

lxd/container_lxc.go, lxd/storage/quota/projectquota.go
=> lxd/storage/quota: Fix bad typing

lxd-p2c/cgo.go, lxd/cgo.go, lxd/include/compiler.h, lxd/main_checkfeature.go, lxd/main_forkfile.go, lxd/main_forkmount.go, lxd/main_forksyscall.go, lxd/seccomp/cgo.go, lxd/seccomp/seccomp.go, lxd/storage/cgo.go, lxd/storage/quota/cgo.go, lxd/ucred/cgo.go, shared/cgo.go, shared/idmap/cgo.go, shared/netutils/cgo.go, shared/netutils/netns_getifaddrs.c, shared/netutils/network.c, shared/termios/cgo.go, shared/util_linux_cgo.go
=> tree-wide: cgo: add -Wunused and __ro_after_init macro

client/lxd.go
=> client: Ignore unresolvable addresses

lxd/networks.go
=> lxd/networks: Nicer error on misisng IPv6

lxd-p2c/cgo.go, lxd/cgo.go, lxd/seccomp/cgo.go, lxd/storage/cgo.go, lxd/storage/quota/cgo.go, lxd/ucred/cgo.go, shared/cgo.go, shared/idmap/cgo.go, shared/netutils/cgo.go, shared/termios/cgo.go
=> global: Drop -Wcast-align (breaks armhf)

lxd/device/nic_bridged.go, test/suites/container_devices_nic_bridged_filtering.sh
Fixes https://discuss.linuxcontainers.org/t/lxd-3-18-security-mac-filtering-on-bridged-nic-fails/6022/9
=> Allow MAC filtering on unmanaged parent bridge

lxd/container_lxc.go
=> lxd/containers: Push MAAS entry after dev creation

lxd/storage/backend_lxd.go, lxd/storage/backend_mock.go, lxd/storage/drivers/driver_dir.go, lxd/storage/drivers/interface.go, lxd/storage/interfaces.go, lxd/storage/utils.go, lxd/storage_volumes.go, lxd/storage_volumes_utils.go
Links storage volumes update and restore functionality to new storage package and implements for dir driver.
=> Storage Update and Restore volumes

lxd/storage/backend_lxd.go, lxd/storage/backend_mock.go, lxd/storage/drivers/driver_common.go, lxd/storage/drivers/interface.go, lxd/storage/drivers/load.go, lxd/storage/load.go, lxd/storage/utils.go
- Adds contextual logger to backends and drivers.
- Updates backendLXD functions to log start and finish of each function with context of args supplied.
Includes https://github.com/lxc/lxd/pull/6373
=> Storage Logging

lxd/container_lxc.go, lxd/storage/backend_lxd.go, lxd/storage/backend_mock.go, lxd/storage/drivers/driver_dir.go, lxd/storage/drivers/interface.go, lxd/storage/interfaces.go
Includes https://github.com/lxc/lxd/pull/6375
=> Storage Instance Root Device Usage

lxd/storage_volumes_snapshot.go
=> lxd/storage: Use correct operation type

lxd/resources/storage.go
=> lxd/resources/storage: Improve cdrom handling

lxd/device/nic_bridged.go
=> lxd/devices/nic: Handle recent ebtables

lxd/container.go, lxd/container_lxc.go, lxd/containers_post.go, lxd/instance_interface.go, lxd/storage/backend_lxd.go, lxd/storage/drivers/utils.go, lxd/storage/interfaces.go, lxd/storage_btrfs.go, lxd/storage_ceph.go, lxd/storage_ceph_utils.go, lxd/storage_dir.go, lxd/storage_lvm.go, lxd/storage_lvm_utils.go, lxd/storage_zfs.go
Includes https://github.com/lxc/lxd/pull/6399
=> Storage Instance Create

lxd/storage/backend_lxd.go, lxd/storage/backend_mock.go, lxd/storage/interfaces.go
Includes https://github.com/lxc/lxd/pull/6400
=> Storage Instance Mount and Unmount

lxd/container.go, lxd/device/device_utils_disk.go, lxd/device/disk.go, lxd/storage.go, lxd/storage/backend_lxd.go, lxd/storage/backend_mock.go, lxd/storage/drivers/driver_dir.go, lxd/storage/drivers/interface.go, lxd/storage/drivers/load.go, lxd/storage/errors.go, lxd/storage/interfaces.go
Includes https://github.com/lxc/lxd/pull/6401
=> Storage Instance Quota

lxc/move.go, lxd/container_lxc.go, lxd/storage/backend_lxd.go, lxd/storage/interfaces.go
=> Storage Instance Rename

lxd/operations/operations.go
This adds support for a nil state which may occur when using the
lxd-agent.
=> lxd/operations: Support nil state

lxd/storage_pools.go
=> lxd/storage: Switch Delete to new logic

lxd/storage.go
=> lxd/storage: Switch Mount to new logic

lxd/storage/drivers/driver_cephfs.go
=> lxd/storage/cephfs: Don't fail if already mounted

lxd/api_internal.go, lxd/container.go, lxd/container_lxc.go, lxd/container_post.go, lxd/container_test.go, lxd/containers_post.go, lxd/db/containers.go, lxd/db/containers_test.go, lxd/db/storage_pools.go, lxd/storage.go, lxd/storage/backend_lxd.go, lxd/storage/drivers/driver_dir.go, lxd/storage/drivers/utils.go, lxd/storage/load.go, lxd/storage/storage.go, lxd/storage_dir.go, lxd/storage_zfs.go
- Some function renames to change "container" to "instance".
- Add support for instance type to some functions.
=> Pre VM function renames

lxd/storage/drivers/driver_dir.go
=> lxd/storage/dir: Don't apply quotas on snapshots

client/connection.go, lxd/vm_qemu.go, lxd/vsock/vsock.go
This PR links the LXD VM implementation with the lxd-agent running inside the VM.
=> VM Agent Link

lxd/vm_qemu.go, lxd/vsock/vsock.go
=> lxd/vm: Fixes to agent connection

client/connection.go, client/interfaces.go, client/lxd.go, client/lxd_events.go, client/simplestreams.go
=> client: Add Disconnect function

lxd/vm_qemu.go
=> lxd/vm: Secure boot

lxd/seccomp/seccomp.go
=> seccomp: only apply shift when it is needed

lxd/vm_qemu.go
- Also removes temporary config drive folder after iso creation
=> lxd/vm/qemu: Adds missing secure boot EFI firmware error

shared/simplestreams/products.go
=> shared/simplestreams: Support disk-kvm.img

lxd/main_forksyscall.go, lxd/seccomp/seccomp.go, lxd/seccomp/seccomp_test.go
=> seccomp: tests, logging, pid namespaces

lxd/storage/backend_lxd.go, lxd/storage/backend_mock.go, lxd/storage/drivers/driver_cephfs.go, lxd/storage/drivers/driver_dir.go, lxd/storage/drivers/interface.go, lxd/storage/interfaces.go, lxd/storage/utils.go, lxd/vm_qemu.go
=> lxd/storage: Only use raw images

lxd/vm_qemu.go
=> lxd/vm: Add install script in 9p

lxd/vm_qemu.go
=> lxd/vm: Update systemd units

lxd/vm_qemu.go
If the storage pool cannot be initialized using the new storage backend,
try removing the storage pool volume the old way.
This fixes #6461.
=> lxd: Cleanup storage volumes properly for VMs

lxd/container_logs.go, lxd/containers.go, lxd/containers_get.go
Not used by our own client but useful for debugging and manual
API interaction.
=> lxd/instances: Add /1.0/virtual-machines

doc/environment.md, lxd/vm_qemu.go
=> lxd/vm: Make OVMF path configurable

lxd/storage/backend_lxd.go
If source volume and target volume are on the same storage pool then don't use migration system, and instead use driver's CreateVolumeFromCopy() directly.
=> lxd/storage/backend/lxd: Adds same pool optimisation to CreateCustomVolumeFromCopy

scripts/bash/lxd-client
=> scripts/bash: Refresh list of commands

doc/api-extensions.md, doc/containers.md, lxd/device/device_utils_disk.go, lxd/device/device_utils_unix.go, lxd/device/disk.go, shared/container.go, shared/version/api.go, test/suites/container_devices_disk.sh
Addresses #6174
You can attach rbd with a command like lxc config device add c1 ceph-rbd1 disk source=ceph:my-pool/my-volume ceph.user_name=admin ceph.cluster_name=ceph path=/ceph
You can attach a fs with a command like:
lxc config device add c1 ceph-fs1 disk source=cephfs:my-fs/some-path ceph.user_name=admin ceph.cluster_name=ceph path=/cephfs
=> Ceph clean

lxd/storage_zfs.go
=> lxd/storage/zfs: Fix migration on zfs 0.6

lxd/storage/backend_lxd.go
This fixes the return value of the DeleteImage function.
=> lxd/storage: Fix DeleteImage return value

lxd/vm_qemu.go
=> lxd/vm: Reverse interface counters

lxd/container_lxc.go, lxd/vm_qemu.go
- Re-orders instance delete stages to reduce duplication of code for different storage layers.
- Reinstates returning during error in VM.Delete() to be consistent with container behaviour.
- Adds detection of missing storage volume record and skips step.
=> Instance Delete ordering

lxd/vm_qemu.go
- Caches storage pool and agent client handle for efficiency.
- Tweaks agent TLS config generation so that it mounts the config volume before generation.
=> lxd/vm/qemu: Adds storage pool Mount/Unmount calls

doc/metadata.yaml
=> doc: Add new pages to metadata

doc/clustering.md, lxd/api_cluster.go, lxd/cluster/membership.go, lxd/cluster/membership_test.go, test/suites/clustering.sh
Closes #6230
Signed-off-by: Rizwan Lubis <rizwan.lubis@gmail.com>
Signed-off-by: Jack Stenglein <jackstenglein@gmail.com>
=> Only extend cluster database when reaching three member

lxd/api_internal.go, lxd/container.go, lxd/container_console.go, lxd/container_exec.go, lxd/container_lxc.go, lxd/container_post.go, lxd/container_snapshot.go, lxd/devlxd.go, lxd/migrate_container.go, lxd/storage.go, lxd/storage_btrfs.go, lxd/storage_ceph.go, lxd/storage_ceph_utils.go, lxd/storage_dir.go, lxd/storage_lvm.go, lxd/storage_lvm_utils.go, lxd/storage_migration.go, lxd/storage_utils.go, lxd/storage_zfs.go
- Where instance.Instance can satisfy dependency, uses that.
- Otherwise uses containerLXC directly.
=> Removes container type

lxd/api_internal.go, lxd/container.go, lxd/container_console.go, lxd/container_exec.go, lxd/container_lxc.go, lxd/container_post.go, lxd/container_snapshot.go, lxd/devlxd.go, lxd/migrate_container.go, lxd/storage.go, lxd/storage/backend_lxd.go, lxd/storage/backend_mock.go, lxd/storage/drivers/driver_dir.go, lxd/storage/drivers/load.go, lxd/storage/interfaces.go, lxd/storage_btrfs.go, lxd/storage_ceph.go, lxd/storage_ceph_utils.go, lxd/storage_dir.go, lxd/storage_lvm.go, lxd/storage_lvm_utils.go, lxd/storage_migration.go, lxd/storage_utils.go, lxd/storage_zfs.go
Includes https://github.com/lxc/lxd/pull/6500
=> Storage create instance snapshot

doc/instances.md
=> doc: Documents the VM cloud-init:config drive option

lxd-agent/exec.go
=> lxd-agent: Put /snap/bin in PATH

lxd/storage_btrfs.go
=> lxd/storage/btrfs: Fix StorageEntitySetQuota

lxd/backup.go, lxd/container_backup.go, lxd/storage/backend_lxd.go, lxd/storage/drivers/driver_cephfs.go, lxd/storage/drivers/driver_dir.go, lxd/storage/drivers/interface.go
Includes https://github.com/lxc/lxd/pull/6510
=> Storage create backup

lxd/containers_post.go, lxd/storage/utils.go
Initial clean up of createFromMigration.
=> Storage create from migration cleanup

lxd/storage_zfs.go
=> lxd/storage/zfs: Fix pool import

lxd/containers_post.go, lxd/migrate_container.go, lxd/storage/backend_lxd.go
Links migration sink to new storage package.
=> Storage migration sink

lxd/container_post.go, lxd/container_snapshot.go, lxd/migrate_container.go, lxd/migrate_storage_volumes.go, lxd/storage/backend_lxd.go, lxd/storage/backend_mock.go, lxd/storage/pool_interface.go
Lays the groundwork to link the new storage layer to instance migration source.
=> Storage migration source cleanup

lxd/storage/backend_lxd.go, lxd/storage_pools.go, lxd/storage_pools_utils.go
=> lxd/storage: Properly handle driver config changes

lxd/migrate_container.go, lxd/migration/migration_volumes.go, lxd/rsync/rsync.go, lxd/storage/backend_lxd.go, lxd/storage/drivers/driver_dir.go
Fixes bug where 2 phase sync was not supported when using new storage layer.
=> Storage migration target - support 2 phase sync

lxc/copy.go
=> lxc/copy: Updates copyContainer to not modify volatile.idmap.next

lxd/container_post.go, lxd/migrate_container.go, lxd/migration/migration_volumes.go, lxd/storage/backend_lxd.go, lxd/storage/drivers/driver_common.go, lxd/storage/drivers/interface.go
This is a WIP that links the new storage layer for instance migration source.
Includes https://github.com/lxc/lxd/pull/6546
=> Storage migration source

lxd/storage_btrfs.go, lxd/storage_ceph.go, lxd/storage_zfs.go
=> lxc/storage: Fix template apply on cross-pool copy

test/suites/security.sh
=> tests: Really fix non-shiftfs security test

lxd/instance/qemu/vm_qemu.go
=> lxd/instance/qemu: Sets log file to qemu.log

test/suites/database.sh, test/suites/image_profiles.sh
=> tests: Always pass --force

lxd/daemon_storage.go
=> lxd/daemon: Port daemon storage to new functions

doc/index.md
Adding some more detail on building from source (latest version) vs. building a release. Also adding information on installing required libraries.
=> index.md build from source improvements

test/suites/database.sh
=> tests: Don't leak storage in ENOSPC test
