canonical/lxd

lxd/container_lxc.go, lxd/devices.go
Starting LXD with a container running that has a non-required dev already existing on host, fails to add inotify for that device with `Failed to add "/tmp/testdev" to inotify targets: not a directory` which means it also doesnt get removed if the file is removed.
@stgraber I thought this might be useful to cherry pick into stable releases before I port it over to the `device` package.
=> Fixes some issues with unix inotify

lxd/device/nic_bridged.go, lxd/networks.go, test/suites/container_devices_nic_bridged.sh
Fixes issue where if DHCP is disabled on the parent network after a bridged device has acquired a lease you can no longer remove the device (as it cannot do DHCP release).
Fixes #6102
=> Allow bridged device removal when DHCP disabled on parent network

lxd/apparmor.go
Matches https://github.com/lxc/lxc/pull/3117
=> lxd/apparmor: Prevent writes to /proc/acpi/**

lxd/cluster/gateway.go, lxd/cluster/migrate_test.go, lxd/db/testing.go
This is a small tweak in the go-dqlite API, which helps decoupling a few things internally.
=> Adapt to changed dqlite.New() signature, not requiring NodeInfo anymore

lxc/init.go, lxc/launch.go, po/bg.po, po/de.po, po/el.po, po/es.po, po/fa.po, po/fi.po, po/fr.po, po/hi.po, po/id.po, po/it.po, po/ja.po, po/ko.po, po/lxd.pot, po/nb_NO.po, po/nl.po, po/pa.po, po/pl.po, po/pt_BR.po, po/ru.po, po/sr.po, po/sv.po, po/tr.po, po/uk.po, po/zh_Hans.po
It's now possible to parse configuration options from stdin in both `lxc init` and `lxc launch` commands.
Example:
```
$# $ cat /tmp/config.yml 
config:
raw.lxc: |
lxc.net.0.ipv4.address = 10.10.10.1/24
ephemeral: True
profiles:
- sdpool
- net-lxdbr0
$# lxc launch 64362190ee7c c1 < /tmp/config.yml
```
=> lxc/init: Add parse of options from stdin

lxc/init.go
=> lxc/init: Fix usage with no args

doc/containers.md, lxd/container.go, lxd/container_lxc.go, lxd/device/config/devices.go, lxd/device/config/devices_sort.go, lxd/device/config/devices_test.go, lxd/device/device.go, lxd/device/device_instance_id.go, lxd/device/device_runconfig.go, lxd/device/device_utils_disk.go, lxd/device/device_utils_unix.go, lxd/device/disk.go, lxd/device/nic_bridged.go, lxd/device/nic_p2p.go, lxd/device/none.go, lxd/device/proxy.go, lxd/device/unix_common.go, lxd/device/usb.go, lxd/devices.go, lxd/patches.go, lxd/profiles.go, lxd/profiles_utils.go, lxd/storage.go, lxd/sys/cgroup.go, lxd/sys/os.go, shared/container.go, test/suites/storage_profiles.sh
Migration of disk device into the new device interface.
Adds following behaviour changes:
- Host-side mounts for custom volumes are now unmounted after device start (like rootfs is).
- The `optional` property has been deprecated and replaced with `required` property (defaulting to true) to be consistent with other device types. The `optional` property still works but it has been removed from docs.
- Adds new `CGroupBlkioWeightController` check for `limits.disk.priority`.
- If disk limits cannot be applied due to lack of host cgroup controllers then container wont start.
Part of #5819
=> Device Disk

client/lxd_certificates.go, client/lxd_containers.go, client/lxd_images.go, client/lxd_networks.go, client/lxd_operations.go, client/lxd_profiles.go, client/lxd_projects.go, client/lxd_storage_pools.go, client/lxd_storage_volumes.go, client/simplestreams_images.go
It was possible to do:
`lxc project create "test project"`
But one could not then do:
`lxc project delete "test project"`
As the project name was encoded on the URL as "test+project", but was not decoded when being passed to the database query.
Also see https://discuss.linuxcontainers.org/t/cant-rename-image-alias/5638
=> api/project: Fixes issue handling project names with URI encodable characters

lxd/device/disk.go, shared/container.go
The recent modification to `IsRootDiskDevice` to correctly verify for a non-empty `pool` property has caused issues with the migration process from older server versions that don't have storage pool support, and will also cause problems when using the client against older version versions.
As such this change has been reverted and the non-empty `pool` property check moved into the disk device validation itself.
A comment has been added to avoid confusion in the future.
Part of #5819
=> Reverts root disk device non-empty pool check

test/suites/storage.sh
- Adds basic quota checks for zfs, lvm and ceph (dir and btrfs not supported)
- ZFS checks for live setting and resetting
- LVM doesn't support unsetting quota
- BTRFS doesn't support checking quota using df (AFAIK)
Part of https://github.com/lxc/lxd/issues/5819
=> test: Adds storage quota tests

test/suites/storage.sh
=> test: Tunes ZFS quota tests after intermittent failures

doc/api-extensions.md, lxd/container.go, lxd/containers_get.go, lxd/db/containers.go, lxd/db/containers_test.go, lxd/db/instances.mapper.go, lxd/instance/instance.go, shared/version/api.go
- Adds `/1.0/instances` endpoints with support for a `type` field that indicates instance type.
- Adds `instances` API extension.
Includes https://github.com/lxc/lxd/pull/6176
=> API Instances

client/connection.go, client/interfaces.go, client/interfaces_legacy.go, client/lxd_containers.go, client/lxd_server.go, client/lxd_storage_volumes.go
And same to associated structs, alias old names.
Moving forward we will be using the new names in our own code and the
new Instance related functions will be using new versions of the various
argument structs.
=> client: Rename ContainerServer to InstanceServer

client/interfaces.go, client/lxd_instances.go, shared/api/instance.go, shared/api/instance_backup.go
This PR continues what was started in https://github.com/lxc/lxd/pull/6193 
- Adds a full set of instance management functions to the `InstanceServer` interface.
- Adds the implementations of those functions that use the `/1.0/instances` endpoints if supported by the server or falls back to using `/1.0/containers`.
=> client: instance types

lxd/container.go, lxd/container_lxc.go, lxd/instance_interface.go, lxd/migrate_container.go, lxd/storage.go, lxd/storage_btrfs.go, lxd/storage_ceph.go, lxd/storage_ceph_utils.go, lxd/storage_cephfs.go, lxd/storage_dir.go, lxd/storage_lvm.go, lxd/storage_lvm_utils.go, lxd/storage_migration.go, lxd/storage_migration_btrfs.go, lxd/storage_mock.go, lxd/storage_zfs.go
- Adds `Instance` interface in main package.
- Modifies `Snapshots()` and `Restore()` definitions to accept/return Interface type.
- Embeds `Instance` interface into `container` interface (and removes duplicated definitions).
- Updates Storage API to use `Instance` rather than `container` to support the `Snapshots()` and `Restore()` change.
=> Instance Interface

lxd/db/db.go
The above bug causes dqlite to crash when a read query issued during a big
transaction triggers a page cache spill. The value of 50M should be
enough for most users until we fix this in dqlite.
=> Band aid for https://github.com/canonical/dqlite/issues/163

lxd/storage_btrfs.go
=> lxd/storage/btrfs: Fixes bug with BTRFS snapshot copy

lxd/container.go, lxd/container_lxc.go, lxd/container_test.go, lxd/containers_post.go, lxd/db/containers.go, lxd/db/db_internal_test.go, lxd/db/devices.go, lxd/db/profiles.go, lxd/device/device.go, lxd/device/device_instance.go, lxd/device/device_utils_disk.go, lxd/device/device_utils_infiniband.go, lxd/device/device_utils_instance.go, lxd/device/device_utils_network.go, lxd/device/device_utils_unix.go, lxd/device/device_utils_unix_events.go, lxd/device/device_utils_usb_events.go, lxd/device/disk.go, lxd/device/infiniband.go, lxd/device/nic.go, lxd/device/nic_bridged.go, lxd/device/nic_p2p.go, lxd/device/unix_common.go, lxd/device/usb.go, lxd/instance_interface.go, lxd/seccomp/seccomp.go, lxd/storage.go
Also makes import alias of device config package consistent throughout codebase as `deviceConfig`.
=> Device Instance rename

doc/index.md
=> doc/index: Point to https://linuxcontainers.org/lxd/docs/master/

lxd/images.go
The DB record of the image source does not include the image type, this
needs to be instead retrieved from the image info itself.
=> lxd/images: Fix image type during refresh

lxd/storage_btrfs.go, lxd/storage_ceph.go, lxd/storage_ceph_utils.go, lxd/storage_lvm_utils.go
lxd: Updates error handling of MakeFSType after stderr split of RunCommand.
- Adds stdout output in brackets after error.
- Makes lvmCreateLv error output consistent with other uses of MakeFSType.
=> lxd: Updates error output of MakeFSType

lxd/container.go, lxd/containers.go, lxd/containers_post.go
Adds `instanceInstantiate` function and replaces use of `containerLXCLoad` with it.
This function will then detect the instance type and call `containerLXCLoad` for containers and will then be modified in the future to instantiate VM instance types.
=> Adds instanceLoad function

test/suites/container_devices_nic_bridged.sh, test/suites/container_devices_nic_p2p.sh
To ensure no regression of #6272 and #6270
=> test: Adds host-side MTU veth checks

doc/api-extensions.md, doc/storage.md, lxd/storage_ceph.go, lxd/storage_ceph_utils.go, lxd/storage_pools_config.go, scripts/bash/lxd-client, shared/version/api.go
It's now possible to create a lxd storage pool that's backed by a Ceph erasure encoded pool. To do so supply both the `ceph.osd.pool_name` (this will be used to store the metadata about the rbd image) and the `ceph.osd.data_pool_name` (this is where the actual data will be stored). 
For example `storage create erasure-pool ceph ceph.osd.pool_name=rbd ceph.osd.data_pool_name=k2m1-pool`
=> lxd/storage/ceph: Implement --data-pool argument.

lxd/device/nic_bridged.go, test/suites/container_devices_nic_bridged_filtering.sh
This fixes failures during concurrent runs of ebtables by LXD.
=> lxd/device/nic: Pass --concurrent to ebtables

lxc/storage_volume.go, lxd/migrate_container.go, lxd/migrate_storage_volumes.go, lxd/storage_volumes.go, lxd/storage_volumes_utils.go, shared/util.go
This one threw me for a while, although there seems to be snapshot renaming support in `storagePoolVolumeTypePost` it appears to be unreachable via the API because snapshot renaming is now covered by the `storagePoolVolumeSnapshotTypeCmd` handler and specifically `storagePoolVolumeSnapshotTypePost` function.
This removes the misleading code and clarifies what the function can do.
Includes https://github.com/lxc/lxd/pull/6315
=> Removed seemingly unused snapshot handling code from storagePoolVolumeTypePost

lxc/storage_volume.go, lxd/migrate_container.go, lxd/migrate_storage_volumes.go, lxd/storage_volumes_utils.go, shared/util.go
- Fixes LXC snapshot rename crash
- Replaces ExtractSnapshotName with ContainerGetParentAndSnapshotName
=> Replaces ExtractSnapshotName with ContainerGetParentAndSnapshotName

doc/storage.md
I have to trigger a loopback resize in addition to the steps included in the documentation on both Ubuntu (snap) and Fedora 30 (dnf). After growing the relevant storage pool's `img` file, I have to re-read the file with `losetup -c` before attempting to grow the loop backed BTRFS filesystem. I have otherwise been unsuccessful in following this documentation without `losetup -c`.
=> Add step to trigger re-read on loopback device in BTRFS resize

lxd/db/storage_pools.go, lxd/migrate_storage_volumes.go, lxd/storage_btrfs.go, lxd/storage_ceph.go, lxd/storage_ceph_utils.go, lxd/storage_cephfs.go, lxd/storage_dir.go, lxd/storage_lvm.go, lxd/storage_migration.go, lxd/storage_volumes.go, lxd/storage_volumes_snapshot.go, lxd/storage_volumes_utils.go, lxd/storage_zfs.go
This PR comes from https://github.com/lxc/lxd/pull/6285, but to make that PR smaller I am breaking it into parts.
This PR changes the return type of `StoragePoolVolumeSnapshotsGetType` to return a slice of `StorageVolumeArgs` structs so that getting a list of snapshots with their descriptions only requires a single query, rather than n+1 for queries for the number of snapshots a volume has.
Also it explicitly defines the return order of snapshots as this is important for migration, rather than implicitly depend on sqlite returning in creation order.
=> DB StoragePoolVolumeSnapshotsGetType returns more snapshot info

lxd/migration/migration_volumes.go, lxd/storage.go, lxd/storage_btrfs.go, lxd/storage_ceph.go, lxd/storage_migration.go, lxd/storage_migration_btrfs.go, lxd/storage_migration_ceph.go, lxd/storage_migration_zfs.go, lxd/storage_zfs.go
This PR comes from #6285, but to make that PR smaller I am breaking it into parts.
- Adds migration volume source/target type and associated helper functions for converting migration headers to/from.
- Moves migration progress functions from main to migration package and updates usage.
=> Adds migration volume source/target types and moves migration progress functions

lxd/seccomp/seccomp.go
=> seccomp: protect against syscall supervision override

client/lxd_storage_volumes.go
Fixes bug in client migration code that failed to respond to remote API errors when migrating a volume to a machine where a volume of the same name exists.
During a `move` operation this would cause the local volume to be removed even though it hadn't been transferred to the far side.
During a `copy` operation this would give the illusion that the copy had been successful even though it hadn't been.
=> Client migration existing volume check bug

lxd/storage/utils.go
- VolumeFillDefault now does not populate an empty string for the "size" property for new volumes.
- This is aligned with the other storage types that support the size property.
- Allows dir validation to translate the `size` property for other storage engines.
=> lxd/storage/utils: Dir validation tweaks for size property

doc/api-extensions.md, doc/containers.md, lxd/main_forksyscall.go, lxd/seccomp/seccomp.go, scripts/bash/lxd-client, shared/container.go, shared/version/api.go
This allows to intercept and subsequently to emulate the mount syscall.
To implement an efficient seccomp filter, we filter based on the flags
argument of the mount syscall. We don't want to filter any of the
following flag combinations since they do not cause the creation of a
new superblock:
```
MS_REMOUNT
MS_BIND
MS_MOVE
MS_UNBINDABLE
MS_PRIVATE
MS_SLAVE
MS_SHARED
MS_KERNMOUNT
MS_I_VERSION
So define the following mask of allowed flags:
long unsigned int mask = MS_MGC_VAL | MS_RDONLY | MS_NOSUID | MS_NODEV |
MS_NOEXEC | MS_SYNCHRONOUS | MS_MANDLOCK |
MS_DIRSYNC | MS_NOATIME | MS_NODIRATIME | MS_REC |
MS_VERBOSE | MS_SILENT | MS_POSIXACL | MS_RELATIME |
MS_STRICTATIME | MS_LAZYTIME;
Now we inverse the flag:
inverse_mask ~= mask;
```
Seccomp will now only intercept these flags if they do …
=> seccomp: implement mount syscall interception

lxd/include/lxd_seccomp.h
=> lxd/include: Fix definition of SECCOMP_USER_NOTIF_FLAG_CONTINUE

lxd/devlxd.go, lxd/events.go, lxd/events/events.go, lxd/migrate.go, lxd/migrate_container.go, lxd/migrate_storage_volumes.go, lxd/migration/interfaces.go, lxd/migration/migration_volumes.go, lxd/rsync/rsync.go, lxd/storage/backend_lxd.go, lxd/storage/backend_mock.go, lxd/storage/drivers/driver_common.go, lxd/storage/drivers/driver_dir.go, lxd/storage/drivers/interface.go, lxd/storage/drivers/load.go, lxd/storage/drivers/utils.go, lxd/storage/drivers/utils_test.go, lxd/storage/drivers/volume.go, lxd/storage/interfaces.go, lxd/storage/load.go, lxd/storage/storage.go, lxd/storage/utils.go, lxd/storage_migration.go, lxd/storage_volumes.go, lxd/storage_volumes_snapshot.go, shared/network.go, test/suites/static_analysis.sh
Based on https://github.com/lxc/lxd/pull/6274
Includes https://github.com/lxc/lxd/pull/6317
Includes https://github.com/lxc/lxd/pull/6360
=> Storage package

lxd/devlxd.go, lxd/events.go, lxd/events/events.go, lxd/migrate.go, lxd/migrate_container.go, lxd/migrate_storage_volumes.go, lxd/migration/migration_volumes.go, lxd/rsync/rsync.go, lxd/storage_migration.go, shared/network.go
This PR modifies the migration code and rsync package to use a ReadWriteCloser for remote connection rather than a web socket. The intention for this is to allow the re-use of migration code for copying local volumes between different storage pools.
=> Migration using ReadWriteCloser

lxd/migrate_storage_volumes.go, lxd/migration/migration_volumes.go, lxd/storage/backend_lxd.go, lxd/storage/drivers/driver_common.go, lxd/storage/drivers/driver_dir.go, lxd/storage/memorypipe/memory_pipe.go
- Updates Storage volume copy to use the migration logic with a bi-directional in-memory pipe.
- Adds progress tracker indicator to storage migration functions so that when doing a local copy one can disable the progress tracker on one side.
=> Storage Volume Copy using in-memory pipe and migration logic

lxd/storage/backend_lxd.go, lxd/storage/drivers/driver_common.go, lxd/storage/drivers/driver_dir.go, lxd/storage/drivers/interface.go, lxd/storage/utils.go
Moves Volume validation to use a Volume struct so that volume type and content type can be used during validation if needed.
=> Storage Volume Validation to use Volume struct

lxd/main_forksyscall.go
=> forksyscall: remove left-over advance_arg() call

lxd/migrate_storage_volumes.go, lxd/migration/migration_volumes.go, lxd/storage/backend_lxd.go
Modifies MatchTypes to accept a fallback type which is used when doing cross-pool migrations on different backend drivers.
=> Storage Migration Types - accept fallback type

lxd/storage_volumes.go, lxd/storage_volumes_snapshot.go, lxd/storage_volumes_utils.go
Moves the DB logic from the legacy storage functions directly into the API (which is similar to existing functions that do DB lookups and modifications for simple cases). This way the legacy storage function can be removed and it does fewer DB queries.
Includes https://github.com/lxc/lxd/pull/6371
=> Storage Update Snapshot

lxd/images.go, lxd/storage/backend_lxd.go, lxd/storage/backend_mock.go, lxd/storage/interfaces.go
Partially implements Create Image (for directory which is a no-op).
Other storage drivers will return ErrNotImplemented.
Includes https://github.com/lxc/lxd/pull/6376
=> Storage Create Image

lxd/storage/drivers/driver_dir.go
Every single call to "lxc info" hits GetVolumeUsage, leading to a lot of
warnings and errors being logged.
The only case where a log message is really appropriate is if the user
requests a quota be applied and we are unable to do so due to lack of
support.
=> lxd/storage/dir: Don't fail/complain about missing quotas

lxd/rsync/rsync.go
This is just a hunch as to the possible cause of the race condition in rsync.Recv.
I believe the function go be exiting early (because the 2 synchronisation channels are filled with an error value) meaning the Recv function exists before the go routines, and in the situation where the Recv function is called immediately afterwards (when transferring multiple volume snapshots) and using a new wrapper of WebsocketIO (with its own lock) this could cause multiple writers to the parent websocket conn concurrently. 
=> lxd/rsync: Tweaks Recv's internal synchronisation to avoid race

doc/api-extensions.md, lxd/backup/backup.go, lxd/cluster/config.go, lxd/container.go, lxd/images.go, shared/archive_linux.go, shared/version/api.go
=> Support squashfs as compression algorithm

lxd/storage/load.go
The recently added project logic in the volume code incorrectly assumes
that underscores are only valid as separate between project names and
volume names.
This isn't true for custom volumes which may already have undercores in
their names despite us not having support for custom volumes in projects.
When we do implement custom volumes in projects, we will rename all
volumes to include the project prefix at which point we will be able to
always split those and extract the project. Until then, only do project
splitting on containers.
=> lxd/storage: Fix custom volume with underscores

lxd/images.go, lxd/storage/backend_lxd.go, lxd/storage/backend_mock.go, lxd/storage/interfaces.go, lxd/storage/load.go
- Renames `CreateImage` to `EnsureImage` to indicate that it can (and will) be called multiple times but that it will only actually do something (create an optimized image volume in the storage pool) if needed.
- Removes duplicated `HasVolume` check in `CreateInstanceFromImage`.
- Adds some more comments.
=> Storage Backend EnsureImage

lxd/container.go, lxd/storage/drivers/driver_dir.go, lxd/storage/drivers/errors.go, lxd/storage/load.go
- Renames `GetPoolByInstanceName` to `GetPoolByInstance` - now accepts an Instance type directly.
- This allows it to inspect the Instance's Type and check it is supported by the underlying storage pool driver.
- If not it returns `drivers.ErrNotImplemented` if the instance type is not supported by the storage pool's driver.
- This allows us to cleanly fail operations where the storage driver hasn't implemented VM support yet.
- It also allows a nice side effect of allowing new storage drivers to be merged and used when they only support custom volumes, allowing for new drivers to be implemented in smaller testable chunks.
=> Storage Pool Load By Instance

lxc/init.go
=> lxc/init: Properly handle errors with --empty

doc/api-extensions.md, doc/containers.md, lxd/device/device_utils_disk.go, lxd/device/device_utils_unix.go, lxd/device/disk.go, shared/version/api.go, test/suites/container_devices_disk.sh
This PR adds support for passing in raw mount option string for disk device mounts, e.g: 
lxc config device add first vfat1 disk source=/dev/loop9 path=/mnt/test raw.mount.options=gid=123,uid=456
=> Mount options for disk device mounts #6225

doc/api-extensions.md, doc/containers.md, lxd/daemon.go, lxd/device/nic.go, lxd/device/nic_ipvlan.go, lxd/device/nic_routed.go, shared/version/api.go, test/main.sh, test/suites/container_devices_nic_routed.sh
Adds `routed` NIC type:
Example usage 1: Routed mode with parent for layer 2 proxy:
This is useful when you want the container to "join" the parent's layer 2 network.
lxc config device add c1 eth0 nic nictype=routed parent=eth0 ipv4.address=192.168.1.200 ipv6.address=2a02:xxx:xxx:3::200/128
Example usage 2: Routed mode without parent (layer 2 proxy disabled):
This is useful in a fully routed or multihoned environment where layer2 ARP/NDP proxying isn't required.
lxc config device add c1 eth0 nic nictype=routed ipv4.address=192.168.1.200 ipv6.address=2a02:xxx:xxx:3::200/128
In both examples the container will see the following default gateways added:
169.254.0.1
fe80::1
These are static link-local addresses that are added to each veth pair on the host-side, and provides a consistent …
=> lxd/device/nic/routed: Adds veth routed NIC device

lxd/container.go, lxd/container_lxc.go, lxd/device/device_instance.go, lxd/device/device_utils_generic.go, lxd/device/device_utils_unix.go, lxd/device/disk.go, lxd/device/gpu.go, lxd/device/nic_bridged.go, lxd/device/unix_common.go, lxd/profiles.go, lxd/profiles_utils.go, lxd/vm_qemu.go
Adds the ability to attach a cloud-init config drive to a VM:
E.g.
```
lxc config device add v1 config disk source=cloud-init:config
```
This will generate and attach an ISO file containing the VM's cloud-init config variables in such a way that cloud-init inside the VM will detect it and action them.
=> VM cloud-init config drive

lxd/include/lxd_seccomp.h
There was a typo in the code, resulting with compilation error on system
where SECCOMP_GET_ACTION_AVAIL is not defined by the standard headers.
Signed-off-by: Louis Solofrizzo <lsolofrizzo@online.net>
=> lxd/include: Fix SECCOMP_GET_ACTION_AVAIL define

lxd/storage/backend_lxd.go, lxd/storage/drivers/driver_cephfs.go, lxd/storage/drivers/driver_dir.go, lxd/storage/drivers/utils.go
This removes the unneeded error return value in GetVolumeSnapshotDir.
=> lxd/storage: Fix GetVolumeSnapshotDir return value

lxd/vm_qemu.go
When a VM create is attempted on a storage pool that does not support VMs the new storage pool driver cannot be loaded to remove the storage pool DB record. 
This PR detects this specific scenario and removes the DB record only.
=> VM remove storage volume record on creation fail

lxd/container.go, lxd/containers_post.go
This lays the ground work for linking createFromCopy to the new storage layer's CreateInstanceFromCopy function.
- Renames container references to instance
- Adds proper revert function
- Improves comments
=> Storage createFromCopy instance rename

lxd/storage/drivers/driver_cephfs.go
=> lxd/storage/cephfs: Properly handle root path

lxd/container_lxc.go, lxd/device/config/device_runconfig.go, lxd/device/device.go, lxd/device/device_instance.go, lxd/device/device_utils_infiniband.go, lxd/device/device_utils_unix.go, lxd/device/device_utils_unix_events.go, lxd/device/device_utils_usb_events.go, lxd/device/disk.go, lxd/device/gpu.go, lxd/device/infiniband_physical.go, lxd/device/infiniband_sriov.go, lxd/device/nic_bridged.go, lxd/device/nic_ipvlan.go, lxd/device/nic_macvlan.go, lxd/device/nic_p2p.go, lxd/device/nic_physical.go, lxd/device/nic_routed.go, lxd/device/nic_sriov.go, lxd/device/none.go, lxd/device/proxy.go, lxd/device/unix_common.go, lxd/device/usb.go, lxd/instance/instance_interface.go, lxd/vm_qemu.go
This is required to avoid the `instance` package needing to import the `device` package which causes circular imports when using `instance` in the `storage` package.
This is because the `device` package uses constants from the `storage` package and so requires an import.
This move makes sense though as it moves a Config struct into the config package.
=> Device: Moves RunConfig to device/config package

lxd/cluster/membership.go, lxd/db/node.go, lxd/patches.go
=> Use the node ID from the nodes ID table, not the raft one

lxd/device/disk.go
=> lxd/device/disk: Prevents error logs about unsupported disk drive on VM stop

lxd/seccomp/seccomp.go
The mount interception is requested we need to block the new mount API since it
keeps in-kernel state across multiple and an arbitrary number of syscalls.
=> seccomp: block new mount API when mount interception is requested

lxd/container.go, lxd/containers_post.go, lxd/images.go, shared/archive_linux.go
This PR lays the groundwork needed to link backup restoration to new storage layer.
- Renames containerCreateFromBackup to instanceCreateFromBackup.
- Modifies instanceCreateFromBackup to return a revert function rather than the old storage pool (used to delete the unpacked backup files on error).
- Restructures instanceCreateFromBackup to only use the storage pool in a single place (which will then be replaced with the new storage pkg where possible).
=> Storage backup import cleanup

lxd/db/cluster/schema.go, lxd/db/cluster/update.go, lxd/networks.go, test/suites/clustering.sh, test/suites/projects.sh
First pass at #6491. I'm planning to change the user-visible bits in a separate branch.
=> Change 'containers' to 'instances' in used_by fields for projects and profiles

lxd/cluster/membership.go, lxd/db/cluster/open.go, lxd/db/cluster/open_test.go, lxd/db/cluster/schema.go, lxd/db/cluster/update.go, lxd/db/cluster/update_test.go, lxd/db/node.go, shared/osarch/architectures.go
This adds a new "arch" column to the "nodes" table, in preparation for putting in place multi-arch cluster support, see #6380.
=> Database changes for multi arch cluster

doc/clustering.md
Clarify what happens when one does not define a target when
launching a container in a LXD cluster.
Signed-off-by: David Negreira <david.negreira@canonical.com>
=> Document container launch algorithm on cluster

lxd/backup/backup_instance_config.go, lxd/container.go, lxd/container_lxc.go, lxd/containers_post.go, lxd/storage/backend_lxd.go, lxd/storage/backend_mock.go, lxd/storage/drivers/driver_cephfs.go, lxd/storage/drivers/driver_dir.go, lxd/storage/drivers/interface.go, lxd/storage/pool_interface.go
Includes https://github.com/lxc/lxd/pull/6521
=> Storage backup import

lxd/containers_post.go, lxd/migrate_container.go, lxd/migrate_storage_volumes.go
Restructures migration sink Do() function to allow linking of new storage layer more cleanly.
=> Storage migration sink cleanup

lxd/daemon.go, lxd/seccomp/seccomp.go
This fixes handling of an RBAC server not being online during startup, especially hits when running RBAC in a LXD container.
=> Don't block RBAC on startup

lxd/api_cluster.go, lxd/cluster/connect.go, lxd/cluster/events.go, lxd/container_post.go, lxd/images.go, lxd/networks.go, lxd/operations.go, lxd/response/response.go
With this change, connections to other cluster nodes for non-notify operations will now be held until a working event connection is established with the target.
This should avoid race conditions where we forward a request to another node but then fail to forward operation updates due to not being connected to that node's events stream yet.
=> Block cluster connections on working event forwarding

lxd/storage/backend_lxd.go, lxd/storage/drivers/driver_cephfs.go, lxd/storage/drivers/driver_dir.go, lxd/storage/drivers/driver_types.go, lxd/storage/drivers/interface.go, lxd/storage/drivers/load.go
Adds a new type called `VolumeFiller` which contains a filler function and an optional image fingerprint string.
This is then used by `CreateVolume` for volume filling, but also specifically `CreateVolumeFromMigration` to support a pre-filler optimisation when using Rsync and `dir` driver for migration. If the base image exists on the target, the new volume will be pre-filled from the image before performing the rsync in an attempt to reduce the amount of data needing to be transferred over the network.
By supplying the image fingerprint in the VolumeFiller as well, other storage drivers that use optimised volumes can check if the volume exists first and then just create a volume from that existing volume.
=> Storage migration volume pre-filler

doc/environment.md, lxd/backup.go, lxd/daemon.go
Adds `LXD_SHIFTFS_DISABLE` env var to allow shiftfs to be disabled at runtime to allow testing of traditional UID shifting on kernels with shiftfs support.
=> Storage adds LXD_SHIFTFS_DISABLE env var to disable shiftfs at runtime

lxd/container_lxc.go, shared/containerwriter/container_tar_writer.go
Includes https://github.com/lxc/lxd/pull/6558
- Links publish feature to use new storage package for mounting.
- Removes volume ID Map unshifting (as we shouldn't modify the rootfs or snapshots and new storage package ensures snapshots are readonly).
- Fixes tar writer to unshift as part of tar creation.
=> Storage publish

lxd/vm_qemu.go
The GPU isn't really useful in most cases and when it is useful, some
flexibility around the type of GPU being passed would be good.
So I think we should instead implement the "gpu" device type rather than
have one by default.
=> lxd/vm: Remove default GPU

lxd/container_lxc.go, lxd/storage/backend_lxd.go, lxd/vm_qemu.go
Begins linking new storage package to containerLXC.
- Makes mount/unmount functions storage pkg aware.
- Adds cached pool loader that is storage pkg aware.
- Deprecates StorageStart/StorageStop/Storage functions (plan to remove in future).
- Fixes backendLXD mount/unmount instance snapshot bug.
Closes #6564
=> Storage containerLXC linking

lxd/main.go
This is a temptative fix for the:
lxd: sqlite3.c:66776: removeFromSharingList: Assertion `0' failed.
failure that we occasionally see in jenkins.
=> Enable SQLITE_CONFIG_MULTITHREAD

test/suites/security.sh
Image publication no longer shiftfs so publish isn't impacted by the
shifting protection anymore.
=> tests: Fix security test on non-shiftfs

lxd/storage_lvm.go, test/suites/backup.sh
=> Fix hyphenated container names when handling backups

lxd/containers_post.go, lxd/db/containers.go
We're dealing with a single namespace for both containers and VMs, so we
need to extract the combined list.
=> lxd/db: Rename ContainerNames to InstanceNames

lxd/cgroup/init.go, lxd/container_lxc.go
We only do force-premounting if we are on a cgroup2-only system.
While it's paranoid to check for both since cgroup2-only should imply cgroupns
but let's not rely on that.
Closes #6587.
=> cgroups: pre-mount on pure-cgroup2 systems with cgroup namespaces

lxd/instance/qemu/vm_qemu.go
Starts VMs with `-no-user-config` and `-chroot` flags.
=> VM: Add no-user-config and chroot to start flags

lxd/db/storage_pools.go, lxd/db/storage_pools_test.go, lxd/patches.go, lxd/storage.go, lxd/storage/backend_lxd.go, lxd/storage/backend_mock.go, lxd/storage/drivers/driver_common.go, lxd/storage/load.go, lxd/storage/pool_interface.go, lxd/storage_ceph.go, lxd/storage_lvm.go, lxd/storage_volumes.go, lxd/storage_volumes_snapshot.go, lxd/storage_volumes_utils.go
- Enforces that "size" volume property can only be updated on custom volume types.
- Adds UpdateInstance and UpdateImage functions that can be used to add driver specific update rules.
- Removes `dbPool` argument from storage pool `create` function, as same data is available via `b.db`
=> Storage update validation

lxd/container_lxc.go
This moves the cgroup initialization below initLXC().
The previous order caused a segfault when trying to set limits.memory
for a running container. The segfault would occur in
lxcCgroupReadWriter.Get() as the cc variable would be nil when
dereferencing it.
=> lxd: Fix order of cgroup initialization

lxd/storage/drivers/driver_cephfs.go, lxd/storage/drivers/driver_common.go, lxd/storage/drivers/interface.go, lxd/storage/drivers/load.go
When `init` was modified to call `d.load()` back in https://github.com/lxc/lxd/commit/de19b81a3a53379e5d2bcb4a255c1bbd2e8506cc the intention was that if a driver needed to define it's own `load()` function then it would override the common one.
However this isn't working as designed, and instead, because inside `driverCommon.load()` `d` is always of type `driverCommon` it is always calling the common `load` function which does nothing.
This change pushes the call to the driver specific `load` function to the main driver `Load()` function where the type of the driver is the interface rather than the common driver.
This will allow the cephfs `load()` and future driver's to work correctly.
=> Storage loader fix

lxd/storage/backend_lxd.go, lxd/storage/drivers/interface.go, lxd/storage/drivers/utils.go, shared/util.go
- Removes implied (not actual) project awareness from driver mount path helper utils.
- Fixes rename instance lack of project awareness for symlink.
- Some minor comment improvements.
=> Storage tweaks

lxd/patches.go, lxd/storage/drivers/driver_cephfs.go, lxd/storage/drivers/driver_dir.go, lxd/storage/drivers/utils.go, lxd/storage/utils.go, lxd/storage_btrfs.go, lxd/storage_ceph.go, lxd/storage_ceph_utils.go, lxd/storage_lvm.go, lxd/storage_lvm_utils.go, lxd/storage_utils.go, lxd/storage_zfs_utils.go
- Removes mount helper functions that were in the `storage` package and copies them into both `main` and `storage/drivers` packages as unexported functions.
- This was needed as the new `storage/drivers` drivers need access to these functions, but we do not want to export them when the only external users is the old storage layer.
- The exception to this is `TryMount` and `TryUnmount` which is used from the patches.go file and will need to remain after the old storage layer is removed, so these are left as exported in `storage/drivers` pkg.
=> Storage mount tweaks

lxd/backup.go, lxd/container.go, lxd/container_lxc.go, lxd/migrate_container.go
When loading the new storage pool package we check that the underlying driver supports the instance type. This allows for deploying partially supported new drivers that only implement custom volumes.
As part of my testing for the new LVM driver I found some areas where this instance type check was not happening.
=> Storage pool loader instance type checks

doc/rest-api.md
The `/operations` endpoint is no longer returning a list, but a dict on LXD 3.18.
=> Update /operations endpoint API doc

lxd/revert/revert.go, lxd/revert/revert_test.go, lxd/storage/backend_lxd.go, lxd/storage/drivers/driver_btrfs_volumes.go, lxd/storage/drivers/driver_dir_utils.go, lxd/storage/drivers/driver_dir_volumes.go, lxd/storage/drivers/generic.go
As I've been working on the new storage layer I've found myself using a revert pattern that worked well but had a fair amount of boiler plate, so this package removes some of the duplication and makes it clearer to read.
Original pattern
```go
func main() {
revertFuncs := []func{}
defer func()  {
range _, f := revertFuncs {
f()
}
}
// Do step 1
revertFuncs := append(revertFuncs, func() {
//something that undoes step 1
})
// Do step 2
revertFuncs = nil
return
}
```
This also has the disadvantage that the revert steps are not run in reverse order.
This PR introduces the `revert` package which reduces boiler plate and runs revert steps in reverse order:
```go
func main() {
revert := revert.New()
defer revert.Fail()
// Do step 1
revert.Add( func() {
//something that undoes step 1
}) 
// Do …
```
=> Revert helper

lxd/storage/backend_lxd.go, lxd/storage/drivers/driver_btrfs_volumes.go, lxd/storage/drivers/driver_cephfs_volumes.go, lxd/storage/drivers/driver_dir_utils.go, lxd/storage/drivers/driver_dir_volumes.go, lxd/storage/drivers/generic.go, lxd/storage/drivers/utils.go, lxd/storage/drivers/volume.go, lxd/storage/utils.go
Includes https://github.com/lxc/lxd/pull/6647
Back in https://github.com/lxc/lxd/pull/6641 @stgraber modified `lxdBackend.newVolume()` to merge the pool's `volume.*` keys into the volume's config (stripping the `volume.` prefix).
In order to do this safely the PR also copies the supplied `volConfig` so that any modifications do not affecting the external config map passed in.
Unfortunately this has had 2 negative side effects:
1. In `CreateVolumeFromMigration` the incoming config is validated and if some keys are not suitable for the target storage pool the validation process removed them. However the change to copy the supplied config when creating a new volume struct prevented this from bubbling up to the function that creates the database row (luckily the DB row create function itself …
=> Storage config expansion tweaks

lxd/storage/backend_lxd.go, lxd/storage/memorypipe/memory_pipe.go, lxd/storage/utils.go
Biggest change here is to increase `memorypipe` buffer so that if sender fails before sending anything, we can close the sender side and still allow the recv side to send a close signal even if they have already sent opening message.
=> Storage misc changes

lxd/container_lxc.go, lxd/instance/instance_interface.go, lxd/instance/qemu/vm_qemu.go, lxd/networks_utils.go
This lets us fix the lack of MAC expension in the dnsmasq lease handling logic.
=> lxd/instances: Export FillNetworkDevice

lxd/storage/drivers/driver_btrfs_volumes.go, lxd/storage/drivers/driver_dir_volumes.go, lxd/storage/drivers/generic.go
Also uses driver's CreateVolume function when not refreshing in  `genericCopyVolume` to allow it to be usable with non-dir drivers that still use rsync for syncing.
=> Storage updates generic copy and migrate functions to use revert package

lxd/container.go, lxd/container_lxc.go, lxd/containers_post.go, lxd/instance/instance_interface.go, lxd/instance/instance_utils.go, lxd/instance/qemu/vm_qemu.go, lxd/storage/backend_lxd.go, lxd/storage/backend_mock.go, lxd/storage/pool_interface.go
Includes https://github.com/lxc/lxd/pull/6675
This PR adds a new function to the storage pool interface: `BackupInstanceConfig()` that will ultimately replace the existing `instance.WriteBackupYaml()` function.
The reason for this is that writing the backup config yaml file is inherently dependent on the storage layer and for drivers where the volume needs to be mounted, ensuring that the volume was mounted in all occurrences that the backup yaml file needed writing was becoming error prone to track.
Instead this moves the yaml generation and writing into the backendLXD, where it can directly mount the volume if needed.
The remaining changes then expose a new function on `Instance` called `BackupConfig()` that then selectively uses the new storage function or the legacy one based on the …
=> Storage Instance Backup Config

doc/rest-api.md
At least for me, it wasn't clear that one websocket connection per file descriptor was needed to run the command.
=> Improve websocket doc in container exec

lxd/storage_pools.go
This allows storage pools that have *all* volumes in a non-default project to be deleted.
Note: This still does not allow storage pools that have a mixture of volumes from different projects to be deleted.
=> Storage: Support non-default project in storagePoolDelete

Makefile, doc/index.md
libcap 1.29 was extended to support go, in turn adding some extensions
to the distributed pkgconfig files [1]. By default for security reasons,
the cgo compiler only allows -D, -I, and -l however allows us to extend
this by adding a regex filter to CGO_ALLOW_LDFLAGS [2].
It should be noted that libcap implement the same in their build systems
[3], but use a more relaxed ALLOW regex. Restrict ours as it probably
shouldn't be too wide.
Fixes: #6727
[1]: https://git.kernel.org/pub/scm/libs/libcap/libcap.git/commit/?id=1a61e6f395f2d2784365920872c14d9f69ff8cf1
[2]: https://golang.org/cmd/cgo/
[3]: https://git.kernel.org/pub/scm/libs/libcap/libcap.git/commit/?id=b2b267ef1c83f1f3d3105a4bb84f8bebbc130dec
Signed-off-by: Morten Linderud <morten@linderud.pw>
=> [Makefiles] Whitelist ldflags in libcap pkgconfig

lxd/storage/drivers/driver_lvm_utils.go, lxd/storage/drivers/utils.go
Ensures that VM image files created use an 8K block boundary size, even if the volume size specified by the user is in metric units. This is to work around a qemu bug when volume size is not a standard block boundary multiple.
=> VM: Block boundary size

doc/storage.md
When doing the weekly news (https://discuss.linuxcontainers.org/t/weekly-status-131/6545) I noticed that the docs for LVM volume striping used the old convention of `lvm.volume.stripes` rather than the new volume prefix, e.g. `volume.lvm.stripes`. It also missed off the volume specific settings.
I've also corrected the LXD 3.19 release notes: https://discuss.linuxcontainers.org/t/lxd-3-19-has-been-released/6529
=> doc: Corrects lvm striping options

doc/api-extensions.md, doc/instances.md, lxd/container_logs.go, lxd/container_lxc.go, lxd/device/config/device_runconfig.go, lxd/device/disk.go, lxd/device/infiniband_physical.go, lxd/device/infiniband_sriov.go, lxd/device/nic.go, lxd/device/nic_bridged.go, lxd/device/nic_macvlan.go, lxd/device/nic_p2p.go, lxd/device/nic_physical.go, lxd/device/nic_sriov.go, lxd/instance/drivers/driver_qemu.go, scripts/bash/lxd-client, shared/version/api.go
- Adds support for Disk and NIC device `boot.priority` setting.
- Unifies root disk and other disk qemu config creation.
- Makes root disk default `boot.priority` 1 and other devices default `boot.priority` 0.
- Uses boot index for SCSI ID.
=> VM: boot priority

lxd/cluster/connect.go, lxd/cluster/gateway.go, lxd/cluster/membership.go, lxd/cluster/notify.go
This avoids deadlocks, since client.GetServer() might connect but not return
since it waits for the daemon to be fully up.
=> Use a light TCP/TLS connection attempt instead of a client request

lxd/instance/drivers/driver_qemu.go, lxd/storage.go, lxd/storage/drivers/driver_btrfs.go, lxd/storage/drivers/driver_cephfs.go, lxd/storage/drivers/driver_dir.go, lxd/storage/drivers/driver_lvm.go, lxd/storage/drivers/driver_types.go, lxd/storage/drivers/driver_zfs.go, shared/version/version.go
Detects if the storage root disk is running on a ZFS pool backed by a loop file and switches to use unsafe cached I/O when using old ZFS version to avoid kernel hangs.
Additionally if a raw disk is attached to a VM that is hosted on a ZFS filesystem we switch to using writeback cached I/O and disable O_DIRECT semantics as this is not supported.
Based on reports of ZFS issues from https://discuss.linuxcontainers.org/t/testing-out-lxd-3-19-candidate/6531/37
=> VM: Switch to unsafe async I/O mode on ZFS pools backed by files

lxd/instance/drivers/driver_qemu.go, lxd/instance/drivers/driver_qemu_templates.go
- Moves config generation templates into own file that is parsed at LXD start time to avoid repetitive parsing and possibility of crashing LXD at VM start time due to invalid template.
- Simplifies NIC config generation to support more config types (such as physical and SR-IOV) in the future.
=> VM: Config templates

lxd/storage/utils.go
On debian 9.9 xfs_growfs version, the binary does not accept the block
device as an argument, but the mount point. Since this behavior is also
supported on later versions, I've replaced the command from the block
device to the mount point, in order not to crash older versions of XFS.
Signed-off-by: Louis Solofrizzo <lsolofrizzo@online.net>
=> storage: Fix xfs_growfs command for older versions

shared/simplestreams/simplestreams.go, shared/simplestreams/sort.go
We don't actually want to filter other architectures, instead we want to
keep the top aliases that match our native or foreign architecture.
=> shared/simplestreams: Fix architecture filtering

doc/instances.md
=> doc/instance: Clarifies disk path not available for VMs

lxd/instance/drivers/driver_qemu.go, lxd/instance/drivers/qmp/monitor.go
If the VM start up fails for some reason, clean up devices added on the host so we don't leave stray devices around.
Also, if failure occurs after VM process is launched, then actively kill VM process if `Start()` still fails to complete cleanly.
=> VM: Failed startup cleanup

lxd/storage/backend_lxd.go
Fixes https://discuss.linuxcontainers.org/t/high-load-when-launching-container/6603/6
=> Storage: Only detect volume.block.filesystem changes on block backed pool FS volumes

lxd/api_cluster.go, test/suites/clustering.sh
Since this is not an internal request we can't redirect it, we need to handle
it.
Fixes #6770.
=> Fix request redirect when removing a cluster member

lxd/migration/migration_volumes.go
=> Migration: Adds support for pre-bidirectional negotiation targets

lxd/container_lxc.go, lxd/device/device_utils_network.go, lxd/device/infiniband_physical.go, lxd/device/infiniband_sriov.go, lxd/device/nic_bridged.go, lxd/device/nic_ipvlan.go, lxd/device/nic_macvlan.go, lxd/device/nic_p2p.go, lxd/device/nic_physical.go, lxd/device/nic_routed.go, lxd/device/nic_sriov.go, lxd/instance/drivers/driver_qemu.go, lxd/instance/drivers/driver_qemu_templates.go, shared/instance.go
This PR add support for passing through a physical network device into a VM:
Usage:
```
lxc config device add v1 eth1 nic nictype=physical parent=enp4s0f1
```
Note: At this time you may need to increase the ulimits for MEMLOCK, e.g.
/etc/security/limits.conf
```
*       soft    memlock unlimited
*       hard    memlock unlimited
```
=> VM: Physical PCI passthrough

lxd/instance/drivers/driver_qemu.go
Otherwise during update if the VM isn't mounted the NVRAM file is written to the host's filesystem preventing subsequent mounts.
=> VM: Mount VM config vol before generating NVRAM file

lxd/storage/backend_lxd.go
When deleting images, some drivers need to know the config in order to
handle zombie volumes properly.
=> lxd/storage: Pass config when deleting images

lxd/migrate_container.go, lxd/migrate_storage_volumes.go, lxd/migration/migration_volumes.go, lxd/storage/backend_lxd.go
Fixes rsync features negotiation for CRIU transport when preferred volume transport isn't rsync.
Tested with a sideloaded SNAP, with an Alpine container with no NICs.
=> Migration: CRIU rsync features

lxd/storage/drivers/utils.go
As the man page suggests, xfs_growfs should take the mount point, not
the dev path.
=> lxd/storage/drivers: Pass mountPath to xfs_growfs

lxd/storage/locking/lock.go
There is a race modifying the lock map with a new lock channel for a named lock which causes hangs during high load benchmarks.
=> Storage: Fixes concurrent access race to map

lxd/instance/drivers/driver_qemu.go, lxd/main.go, lxd/main_forklimits.go
- Adds `forklimits` command for launching a process with locally changed rlimits.
- Switches qemu process to use `forklimits` with unlimited `memlock` rlimit for PCI passthrough.
=> VM: forklimits

lxd/instance/drivers/driver_qemu.go, lxd/main_forklimits.go
Switches forklimits to use `syscall.Exec` to avoid keeping the lxd binary in memory.
=> VM: forklimits exec

lxd/instance/drivers/driver_qemu_templates.go
=> lxd/vm: Fix bad bus name on ppc64el

lxd/instance/drivers/driver_qemu_templates.go
=> lxd/vm: Don't specify addresses for pci on ppc64

lxd/migrate_container.go, lxd/migration/migration_volumes.go, lxd/storage/drivers/driver_zfs_volumes.go
When a container is running, and has a new snapshot to sync during refresh mode, after the snapshot has been synced initially, it is also still sent as part of the final sync stage, which is not needed as snapshots are not being modified.
Reported from: https://discuss.linuxcontainers.org/t/snapshots-should-not-be-transferred-during-final-sync/6677
=> Storage: Fixes migrate refresh final sync snapshot bug

lxd/seccomp/seccomp.go
So it also does the same stuff that the kernel does.
=> seccomp: make device number checking more robust

lxd/device/disk.go, lxd/instance/drivers/driver_qemu.go, lxd/instance/drivers/driver_qemu_templates.go, shared/archive_linux.go
Switches to vhost_net to match qemu recommendation (significant performance improvement).
Also enables discard on virtio-scsi so file backed storage can shrink as blocks are released in the VM and SSD backing devices can also better manage their blocks.
=> VM optimization and fixes

doc/api-extensions.md, doc/instances.md, lxd/container_lxc.go, lxd/device/nic.go, lxd/device/nic_bridged.go, lxd/instance/drivers/driver_qemu.go, lxd/network/network.go, lxd/networks_config.go, shared/version/api.go, test/suites/container_devices_nic_bridged.sh
Introduces the concept of a "linked network" for `bridged` NIC devices using the `network` property.
When a bridged NIC device is linked to a LXD network some of the options will go away and instead be controlled globally at the network level.
These options will be inherited from the network and *not* be configurable on the instance device:
* `parent`
* `mtu`
* `maas.subnet.ipv4`
* `maas.subnet.ipv6`
This also adds stricter enforcement of `ipv4.address` and `ipv6.address` as it uses info from the linked network to validate subnet properly and whether the options are supported by parent network (i.e. DHCP enabled).
Fixes https://github.com/lxc/lxd/issues/5890
=> Network: Adds "network" property to bridged NIC device

lxd/storage/drivers/driver_zfs_utils.go
Some ZFS versions are a bit picky about this.
Suggested-by: atersurs
Closes #6830
=> lxd/storage/zfs: Fix argument ordering

lxd/main_checkfeature.go
=> lxd/main_checkfeature: don't depend on kcmp header

lxd/daemon.go, lxd/db/cluster/schema.go, lxd/db/cluster/update.go, lxd/patches.go, lxd/storage.go, lxd/storage/drivers/driver_lvm.go, lxd/storage/drivers/driver_zfs.go
Related to https://github.com/lxc/lxd/issues/6828
Adds `updateFromV23` DB patch to ensure that older storage pools that do not have the `lvm.vg_name` config property set will have it set to the pool name.
=> Storage: Adds updateFromV23 DB patch to ensure lvm.vg_name

lxd/device/nic_bridged.go, test/suites/container_devices_nic_bridged_filtering.sh
If using a `bridged` NIC connected to an unmanaged bridge (or one that didn't use DHCP) with static IPs assigned (just for filtering purposes not DHCP allocation) then when the device is stopped the static IPs defined in config were not considered when removing filters.
This could lead to ebtables filter rules leaks. 
Adds a test for this scenario too.
Includes https://github.com/lxc/lxd/pull/6851
=> Device: Fixes ebtables filter leak with Bridged NIC on umanaged bridge

lxd/project/project.go, lxd/project/project_test.go, lxd/storage/load.go
And tests.
Will be used in forth coming bridged filtering dnsmasq improvements.
=> Project: Adds InstanceParts() function for separating project prefixed Instance name

lxd/cluster/gateway.go
The following ensures that when requesting isLeader and an error is
returned, that the code correctly unlocks, otherwise you could end up
with a lockup.
I'm unsure how often this would happen, I found this just looking over
the codebase.
=> Unlock when isLeader failure

lxd/util/net.go, lxd/util/net_test.go
=> Consider the default port when checking address overlap

lxd/instance/drivers/driver_qemu.go
This reverts commit 78b4b396c8413e4b6e6c32317611d0fead72d09b.
This is because although it fixes the hanging lxc clients and leaking go routines, it also introduces a regression when using `lxc exec` without a single command that is expected to output data directly to the console.
With the escape sequence being sent, this was intermittently wiping out the output of the command.
=> Revert "lxd/instance/drivers/driver/qemu: Fix go routine leak and hanging lxc clients

lxd/instance/drivers/driver_qemu.go, lxd/instance/drivers/driver_qemu_templates.go, shared/util.go
This adds support for comparing the requested CPU pin with physical hardware layout and if consistent, configures qemu to mimic the setup (sockets, cores, threads) and pin the resulting threads on the matching cores.
The logic also sorts the provided pinning data by hardware order (socket, core, thread) which matches what qemu itself uses and is how the pin is lined up with qemu threads later on.
=> VM: CPU topology

doc/api-extensions.md, lxd/api_1.0.go, lxd/daemon.go, lxd/firewall/drivers/drivers_nftables.go, lxd/firewall/drivers/drivers_nftables_templates.go, lxd/firewall/drivers/drivers_xtables.go, lxd/firewall/firewall_interface.go, lxd/firewall/firewall_load.go, lxd/network/network.go, shared/api/server.go, shared/version/api.go, test/suites/container_devices_nic_bridged_filtering.sh, test/suites/container_devices_proxy.sh
This is a WIP that adds initial nftables support to the `firewall` package.
One way that nftables is quite different to iptables is that there are no built in tables or chains.
Additionally `tables` in nftables are just namespaces (or containers) for chains and their rules, they have no inherent meaning to nftables itself.
Chains are added to tables, and so-called "base chains" hook themselves into the netfilter subsystem at the required point. Only then will these chains actually handle packets. Chains hook themselves into the netfilter system using a priority. I've used the same priorities as iptables does when hooking into netfilter as documented https://wiki.nftables.org/wiki-nftables/index.php/Configuring_chains#Base_chain_priority.
From from my research, if multiple chains are added …
=> Firewall: nftables driver

doc/api-extensions.md, doc/storage.md, lxd/storage/drivers/driver_lvm.go, lxd/storage_pools_config.go
A bug that was fixed in 3.19 that allowed existing non-empty volume groups to be used for new storage pools has caused issues with some users depending on that behaviour.
This PR introduces the `lvm.vg.force_reuse` pool config option to allow an existing non-empty volume group to be used for new storage pools.
Related discussion: https://discuss.linuxcontainers.org/t/error-when-trying-to-use-an-existing-lvm-pool-with-a-new-installation/6809
=> Storage: Allow LVM pool to be backed by existing non-empty volume group

lxd/api.go, lxd/api_internal.go, lxd/container_lxc.go, lxd/storage/storage.go
- The check for ".importing" file wasn't project aware, could cause the container on storage device to be incorrectly removed.
- When using `--force` flag, the old DB volume records removal code was not project aware, preventing the container from being imported.
=> Storage: Fixes container import bugs when using projects

lxd/daemon.go
If the hardware is slow or loaded spurious timeouts can kick in.
Should help with #6439.
=> Increase timeout of standalone SQL statements

lxd/backup.go
This adds the 'S' flag to tar's transformation. It tells tar to not
apply transformation to symbolic link targets.
=> lxd/backup: Have tar not transform symlink targets

scripts/bash/lxd-client
Closes #6912
-Add project list function
-Add project key list
-Add tab complete for "create delete edit get list rename set show switch unset " functions
-Add project list after above functions
-Add project key list after "get"|"set"|"unset" functions
-Add additional project list for "rename" function
Question: How would I test this functionality on my local computer? I tried to make a copy of /snap/lxd/current/etc/bash_completion.d/snap.lxd.lxc on my local server then replace it with my edited version, but the file is in use. I'm guessing that's due to lxd running, how would one hot swap the file?
Edit:
Signed-off-by: Brian Neumeyer bpneumey@oakland.edu
=> Update Project Tab Complete Script

lxd/db/containers.go, lxd/db/containers_export_test.go, lxd/db/containers_test.go, lxd/db/storage_volumes.go
The code in ```ContainerListExpanded``` did not honor the ```features.profiles``` project configuration when expanding instance configs.
This code path is hit only when checking if a Ceph storage volume is attachable, and is such a corner case that it probably went unnoticed so far.
=> Honor "features.profiles" when expanding instance configs

lxd/storage/drivers/driver_btrfs_volumes.go, lxd/storage/drivers/driver_ceph_volumes.go, lxd/storage/drivers/driver_common.go, lxd/storage/drivers/driver_dir_utils.go, lxd/storage/drivers/driver_dir_volumes.go, lxd/storage/drivers/driver_lvm_volumes.go, lxd/storage/drivers/driver_zfs_volumes.go, lxd/storage/drivers/generic_vfs.go, lxd/storage/drivers/utils.go
Addresses issue https://github.com/lxc/lxd/issues/6929
There are 2 issues here:
1. We need to move the GPT alternative header to the end of the disk after unpacking a VM image to a disk file. This is what the GPT standard requires so it knows where to find the backup header. This change needs to be added to each VM capable driver:
2. When cloning a ZFS volume from a snapshot, because snapshots don't have the `volmode` property, the property is instead inherited from parent (which LXD currently doesn't modify from default), and so when the new volume is created ZFS then probes the partitions on the disk and creates a device for each partition. This probing causes the host kernel to detect the the problem GPT header and logs warnings to the kernel log.
There is also potentially a bug in ZFS …
=> Storage:  Fixes GPT alternative header not being at the end of the VM block device

lxd/db/cluster/query.go
=> lxd/db: Start-up check ignores pending nodes with out-of-date schema

lxd/storage/drivers/driver_ceph_volumes.go
=> Storage: Don't format ceph block volumes with a filesystem

lxd/storage/drivers/driver_btrfs_volumes.go, lxd/storage/drivers/driver_zfs_volumes.go
=> lxd/storage/drivers: Don't use named temporary dirs

doc/instances.md
=> doc: Typo and formatting improvements

lxd/instance/drivers/driver_lxc.go, lxd/instance/drivers/driver_qemu.go, lxd/instance/instance_interface.go
Removes `CGroupGet` as is unused.
Includes https://github.com/lxc/lxd/pull/6958
=> Instance: CGroupGet remove

lxd/instance/drivers/driver_qemu_templates.go
=> lxd/vm: Set gic-version on arm64

lxd-agent/main_agent.go, lxd/device/disk.go, lxd/instance/drivers/driver_qemu.go, lxd/instance/drivers/driver_qemu_templates.go, lxd/instance/instancetype/instance_vmagentmount.go
Adds the ability to share directories from the host into the VM guest using the 9p protocol.
Requires that the `lxd-agent` is running inside the VM.
Example usage:
```
lxc config device add v1 test disk source=/some/host/dir path=/some/vm/dir
```
The `readonly` property is supported.
=> VM: 9p disk device shares

lxd/api_cluster.go
Attempting to patch the cluster.http_address if it's not set isn't
being checked if there is an error loading the configuration or
patching the value.
Signed-off-by: Simon Richardson <simon.richardson@canonical.com>
=> Missing bootstrap error check

.travis.yml
relates to https://github.com/Homebrew/homebrew-core/pull/51206 (brew formula already shipped with go 1.14)
=> Add go 1.14.x check

doc/api-extensions.md, doc/instances.md, lxd/device/device_utils_network.go, lxd/device/nic.go, lxd/device/nic_routed.go, shared/version/api.go
Adds support for multiple interfaces by allowing the disabling of the automatic default gateway being added using the NIC config keys `ipv4.gateway=none` and `ipv6.gateway=none` respectively.
Fixes https://github.com/lxc/lxd/issues/6965
=> NIC Routed: Adds support for multiple interfaces

lxd/util/fs.go
=> Util: Fixes go vet conversion from int64 to string yields a string of one rune error

lxd/device/disk.go
Fixes "root device not found" log error when shutting down VM.
=> Disk: Only unmounts non-root volumes attached

lxd/db/images.go, lxd/images.go
Avoids errors such as:
```
DBUG[03-12|09:36:31] New task Operation: c0d6aaba-3130-4987-8002-74f069bebe10 
DBUG[03-12|09:36:31] Failure for task operation: 28799184-e121-4ad6-8139-9da30b7130b2: Error retrieving image info 8bac6546bbc5cfbe5c490f2c991cff8cff1428b57fb9a74d33a64cb6dff66601: No such object 
```
=> Images: Allow pruning of expires images in non-default project

lxd-agent/exec.go, lxd/instance_exec.go, shared/netutils/network_linux.go, shared/network.go, shared/util_linux_cgo.go
The websocket read go routines were being started before the instance.Exec process was confirmed to have started.
This was leaking go routines and leaving websocket readers running on closed connections which could result in infinite loops in the websocket reader functions.
Changes made:
1. Re-orders the code so that the websocket mirroring go routines are not started until the process being execed has started.
2. Changes any channels that were used for coodination only (i.e not actually sending any data) from bool to struct{} to indicate that the value has no meaning, and instead using close(ch) to indicate whatever coodination point was needed. This has the added benefit of not needing to use a buffered channel, as channels can be closed with no readers without blocking.
3. Properly …
=> VM: Fixes exec read loop when agent not started

lxd/instance.go
This fixes the expiry check for instances. Like with backups, it checks
the unix timestamp instead of `IsZero()` as zero time has caused issues
in the past due to timezones.
=> lxd/instance: Fix expiry check

lxd/storage/drivers/driver_btrfs_volumes.go
We shouldn't activate BTRFS quotas if not actually being used.
Fixes #7029
=> Storage: Dont activate BTRFS quotas if not used

lxd/db/cluster/schema.go, lxd/db/cluster/update.go, lxd/db/cluster/update_test.go
=> db/cluster: Bump the value of sqlite_sequence for storage_volumes

lxd/db/node.go
So that NULL handling isn't needed.
As discussed in https://github.com/lxc/lxd/pull/7049
=> DB: Tweaks LEFT JOIN to just JOIN in NodeIsEmpty()

lxd/sys/fs.go
=> lxd/sys: Don't fail chmod on unresolvable symlinks

lxd/response/response.go, lxd/util/http.go
And accept both quoted and unquoted values in If-Match.
Closes #7068
=> lxd/etag: Quote generated etag values

lxd/backup.go, lxd/backup/backup.go, lxd/instances_post.go, lxd/storage/backend_lxd.go
Changes instanceOnly arg to snapshots.
Removes `privileged` field.
Adds `optimized` field to indicate if optimized backup format is used.
Adds `type` field to indicate the instance type being backed up.
=> Backup: Adds OptimizedStorage and Type fields to index.yaml

lxd/storage/drivers/driver_btrfs_utils.go, test/suites/storage.sh
This adds the `--raw` flags to `btrfs qgroup show`. The flag is needed
as the sizes in the output are listed with suffixes (KiB, MiB, etc.).
Since `ParseInt` cannot deal with that, it fails and returns -1. Adding
the `--raw` flag removes all suffixes, and returns the correct usage.
=> lxd/storage/drivers/btrfs: Fix quota

lxd/storage/drivers/driver_btrfs_volumes.go
When deleting a qgroup, it's not possible to get the usage of an
instance or volume anymore. Therefore, instead of deleting the qgroup,
we just don't set a limit.
=> lxd/storage/drivers/btrfs: Don't destroy qgroups

lxd/instance/drivers/driver_qemu.go
This ensures that the lxd-agent is started before cloud-init.service and
cloud-init-local.service.
=> lxd/instance/drivers: Fix lxd-agent running order

lxd/api_internal.go, lxd/backup.go, lxd/storage/backend_lxd.go, lxd/storage/drivers/driver_btrfs_volumes.go, lxd/storage/drivers/driver_zfs_volumes.go, lxd/storage/drivers/generic_vfs.go
Adds support for virtual machine backups:
**Generic tarball output:**
Stores primary volume as a `backup/virtual-machine.img` and the associated config file system volume in `backup/virtual-machine/` directory.
Similarly, snapshots volumes are stored as `backup/virtual-machine-snapshots/<snapName>.img` and its associated config file system volume in `backup/virtual-machine-snapshots/<snapName>/` directory.
**Optimised tarball output:**
For optimised output, the primary volume will store the storage driver specific volume dump file as `backup/virtual-machine.bin` and, for ZFS only, the associated config file system volume in `backup/virtual-machine-config.bin`.
Similarly, snapshots volume dump files are stored as `backup/virtual-machine-snapshots/<snapName>.bin` and, for ZFs only, its …
=> VM: Backup

lxd/storage/backend_lxd_patches.go
Ignores snapshots when getting list of custom volumes to be renamed.
Snapshots of custom volumes will be renamed as part of parent volume rename.
Fixes #7076
=> Storage: Ignores snapshots rename renaming custom volumes

doc/api-extensions.md, doc/instances.md, lxd/device/nic.go, lxd/device/nic_routed.go, scripts/bash/lxd-client, shared/version/api.go
This introduces the `ipv4.host_address` and `ipv6.host_address` NIC config keys that can be used to control the host-side veth interface's IP addresses. This can be useful when using multiple routed NICs at the same time and needing a predictable next-hop address to use.
This also alters the behaviour of `ipv4.gateway` and `ipv6.gateway` NIC config keys. When they are set to "auto" the container will have its default gateway set to the value of `ipv4.host_address` or `ipv6.host_address` respectively.
The default values are:
`ipv4.host_address`: 169.254.0.1
`ipv6.host_address`: fe80::1
This is backward compatible with the previous default behaviour.
=> NIC Routed: Host addresses for multiple NIC support

doc/api-extensions.md, doc/instances.md, lxd/device/nic_ipvlan.go, shared/version/api.go
Using the `ipv4.gateway` and `ipv6.gateway` settings set to "none" to avoid conflicting default gateway routes being added to the container and preventing startup.
=> NIC IPVlan: Adds support for multiple NIC devices

lxd/device/nic_routed.go
=> NIC Routed: Sets accept_ra=0 on host interface

lxd/include/memory_utils.h, lxd/instance/drivers/driver_lxc.go, lxd/main_forkexec.go, lxd/main_nsexec.go, shared/util_linux_cgo.go
This reworks our forkexec logic to switch from go because it's just not working
well with anything that gets close to any libc and their state assumptions.
=> forkexec: rework

lxd/device/nic_bridged.go
Prevents host-side interface getting IPv6 link-local address which isn't needed as interface is added to bridge.
=> NIC Bridged: Disables IPv6 on bridged host side interface

lxd/instance/drivers/driver_lxc.go, lxd/instance/drivers/driver_qemu.go, lxd/storage/drivers/driver_btrfs_volumes.go, lxd/storage/drivers/driver_zfs_volumes.go, lxd/storage/drivers/generic_vfs.go, shared/instancewriter/instance_tar_writer.go
This restores old behaviour and prevents `lxc export` failing when files are being modified inside a running container.
Addresses https://discuss.linuxcontainers.org/t/lxd-export-fails-with-archive-tar-write-too-long/7207
=> Backup: Only read up to original size of file during export

lxd-agent/main_agent.go, lxd/instance/drivers/driver_qemu.go
Was seeing errors like this on ubuntu 18.04 VMs:
```
[    3.304595] systemd[1]: cloud-init-local.service: Found ordering cycle on lxd-agent.service/start
[    3.305700] systemd[1]: cloud-init-local.service: Found dependency on sysinit.target/start
[    3.306768] systemd[1]: cloud-init-local.service: Found dependency on cloud-init.service/start
[    3.307790] systemd[1]: cloud-init-local.service: Found dependency on systemd-networkd-wait-online.service/start
[ SKIP ] Ordering cycle found, skipping LXD - agent
```
This seems to fix it.
=> VM: lxd-agent systemd dependency conflicts

lxd/storage/drivers/driver_btrfs_volumes.go, lxd/storage/drivers/driver_zfs_volumes.go, lxd/storage/drivers/volume.go
As tarball creation will not create consistent backup when instance is running and files are being modified during backup, we avoid this by creating a read-only snapshot of the main volume.
This is possible because BTRFS allows us to create a snapshot quickly without freezing the main volume.
=> Storage: Take snapshot when backing up BTRFS volumes

lxd/instance/drivers/driver_lxc.go, lxd/instance/drivers/driver_qemu.go
To speed up lxc list command.
Fixes #7124
=> Storage: Removes storagePools.RenderSnapshotUsage from RenderFull()

lxd/instance.go, lxd/storage/backend_lxd.go, lxd/storage/drivers/driver_ceph_volumes.go, shared/subprocess/proc.go
Addresses failed snapshot creation leaving database records as discussed in https://discuss.linuxcontainers.org/t/not-able-create-snapshot-through-zfs-snapshot-storage-name-containers-containers-name-snapshot-snapshot-name-due-to-invalid-argument-in-its-name/7243
=> Storage: Improve failed snapshot create revert cleanup

lxd/cluster/membership.go
The timeout was hit by Anbox in particularly loaded scenarios.
=> Increase timeout when calling dqlite.Client.Add() to join the cluster

lxd/storage/drivers/driver_btrfs_volumes.go, lxd/storage/drivers/driver_cephfs_volumes.go, lxd/storage/drivers/driver_dir_volumes.go, lxd/storage/drivers/driver_lvm_volumes.go, lxd/storage/drivers/driver_zfs_volumes.go
Makes snapshot usage reporting as consistent in meaning as possible (CoW usage as opposed to volume size) and if not possible returns -1/ErrNotSupported.
=> Storage: Snapshot usage

lxd/api_cluster.go, lxd/main_init_dump.go, shared/api/network.go
This should never have been there in the first place.
`Managed` is a read-only property, you can't create an un-managed network.
=> Drop invalid `Managed` field from NetworksPost

lxd/instance/drivers/driver_qemu.go, lxd/instance/drivers/driver_qemu_templates.go
Adds NIC devices using a different PCIe addr prefix.
Fixes #7175
E.g.
```
root@v1:~# lspci -t -vvv
-[0000:00]-+-00.0  Intel Corporation 82G33/G31/P35/P31 Express DRAM Controller
+-01.0  Red Hat, Inc. Virtio console
+-02.0-[01]----00.0  Red Hat, Inc. Virtio SCSI
+-02.1-[02]----00.0  Red Hat, Inc. Virtio memory balloon
+-02.2-[03]----00.0  Red Hat, Inc. Virtio RNG
+-02.3-[04]----00.0  Red Hat, Inc. Device 1053
+-03.0  Red Hat, Inc. Virtio filesystem
+-04.0-[05]----00.0  Red Hat, Inc. Virtio network device
+-04.1-[06]----00.0  Red Hat, Inc. Virtio network device
+-04.2-[07]----00.0  Red Hat, Inc. Virtio network device
+-04.3-[08]----00.0  Red Hat, Inc. Virtio network device
+-04.4-[09]----00.0  Red Hat, Inc. Virtio network device
+-04.5-[0a]----00.0  Red Hat, Inc. Virtio network device …
```
=> VM: Allow up to 8 NIC devices

lxd/instance/drivers/driver_qemu_templates.go
Is used by MAAS to identify devices inside VM.
=> VM: lxd_ device name prefix cannot be changed

lxd/instance/drivers/driver_lxc.go, lxd/instance/drivers/driver_qemu.go, lxd/instance_patch.go, lxd/instance_put.go, lxd/instance_state.go, lxd/patches.go
This updates all calls to Update() to properly set userRequested to true
if the config change comes through a user request.
If it doesn't, then ignore validation issues as reverting will be just
as broken and there's nothing the user can do at that point anyway.
This also removes the logic checking if `volatile.` keys have been
modified since the check never actually applied to PUT/PATCH requests
due to us having to use that API when handling migrations.
So in practice userRequested was never set to true when a change was
actually requested by the user, making the check useless.
Closes #6661
=> lxd/instances: Better use userRequested on Update

doc/api-extensions.md, doc/instances.md, lxd/device/nic.go, lxd/device/nic_routed.go, shared/version/api.go, test/suites/container_devices_nic_routed.sh
When using custom policy routing on the host, proxy ARP and proxy NDP will not function unless static routes for the instance's IPs are added to the custom policy routing table (in addition to the host's main routing table to ensure reverse path filtering doesn't kick in).
This PR introduces new `routed` NIC config settings: `ipv4.host_table` and `ipv6.host_table` which can be set to the routing table ID that LXD will add static routes to for each of the instances IPs.
Fixes https://github.com/lxc/lxd/issues/7152
=> NIC Routed: Add custom policy routing table support

doc/api-extensions.md, doc/instances.md, lxd/device/nic_ipvlan.go, shared/version/api.go, test/suites/container_devices_nic_ipvlan.sh
When using custom policy routing on the host, proxy ARP and proxy NDP will not function unless static routes for the instance's IPs are added to the custom policy routing table (in addition to the host's main routing table).
This PR introduces a new `ipvlan` NIC config setting: `host_table` which can be set to the routing table ID that LXD will add static routes to for each of the instances IPs.
Fixes #7123
Includes https://github.com/lxc/lxd/pull/7192
=> NIC IPVLAN: Add custom policy routing table support

doc/api-extensions.md, doc/instances.md, lxd/device/nic_ipvlan.go, shared/version/api.go, test/suites/container_devices_nic_ipvlan.sh
Adds l2 mode support for `ipvlan` NIC. This mode allows a container to define its own IPs and avoid the need to use proxy ARP/NDP. Although l2 mode removes the ability for the host to firewall the container traffic.
Adds a new NIC config key `mode`, which can be either `l3s` or `l2` (defaults to `l3s` which is current behaviour).
In `l2` mode, the `ipv4.address` and `ipv6.address` keys allow addresses to be specified in CIDR format, e.g. `192.168.0.1/27` allowing for the container to join the same layer 2 subnet as the wider network. If a singular address is specified, such as `192.168.0.1` then the subnet is assumed to be `/24` for IPv4 and `/64` for IPv6.
In `l2` mode the `ipv4.gateway` and `ipv6.gateway` keys require a specific IP address if used, as the host is not used as a router …
=> NIC IPVLAN: Adds l2 mode support

lxd/instance/drivers/driver_qemu.go, lxd/instance/drivers/driver_qemu_templates.go
This PR fixes an issue introduced in https://github.com/lxc/lxd/pull/7185 that caused PCIe addressing conflicts due to qemu 9p devices assigning their own PCIe addresses that conflicted with the statically assigned NIC device addresses. This PR also now statically assigns 9p disk devices a PCIe address in a separate range to NICs, which will also be separate independent of the order the devices are configured in LXD config.
Fixes #7175
=> VM: PCIe addressing take two

doc/index.md
Tiny detail that makes a big difference: Following README file, at the
moment of machine setup, PATH should be $GOPATH/bin. This PATH contains
the "lxd-agent" binary and, if PATH is not passed by sudo, it won't get
included in machine's 9p config filesystem.
Signed-off-by: Rafael David Tinoco <rafaeldtinoco@ubuntu.com>
=> index.md: add PATH env variable to sudo command example

lxd/device/device_utils_disk.go, lxd/device/disk.go
Testing done:
```
lxc storage create cephfs cephfs source=persist-cephfs/persist-edfu
lxc config device add c1 testvol disk source=cephfs:persist-cephfs/persist-edfu path=/mnt
lxc start v1
mount
[2001:470:b0f8:1015:5054:ff:fe5e:ea44]:6789,[2001:470:b0f8:1015:5054:ff:fe0a:750f]:6789,[2001:470:b0f8:1015:5054:ff:fe5e:4c7b]:6789:/persist-edfu/test on /var/lib/lxd/devices/v1/disk.testvol.mnt- type ceph (ro,relatime,name=admin,secret=<hidden>,acl,mds_namespace=persist-cephfs,wsize=33554432)
lxc exec c1 mount
lxd_testvol on /mnt type 9p (rw,relatime,sync,dirsync,access=client,trans=virtio)
lxc stop v1
mount on host gone.
```
=> VM: Adds cephfs disk support

lxd/main_init_interactive.go
Note for reviewers (especially @stgraber): I realized that now that we try to listen to the configured network address in `lxd init`, the behavior is not idempotent anymore. If you try to run again `lxd init` and use the same network address you'll get an error. Not sure if we care about this.
=> lxd/init: Improve error messages when failing to bind an address

lxd/device/proxy.go, lxd/firewall/drivers/drivers_nftables.go, lxd/firewall/drivers/drivers_nftables_templates.go, lxd/firewall/drivers/drivers_xtables.go, test/suites/container_devices_proxy.sh
Allows instances to access the proxy device's listen IP when using NAT mode.
Fixes https://github.com/lxc/lxd/issues/7205
=> Proxy: Adds hairpin NAT rules

lxd/instance/drivers/driver_lxc.go
=> lxd/instance/lxc: Don't crash in setNetworkPriority

lxd/util/net.go
=> lxd/util: Tweak NetworkInterfaceAddress to only return global

lxd/util/net.go
=> lxd/net/util: Updates comment on NetworkInterfaceAddress behaviour change

lxd/storage/backend_lxd.go, lxd/storage/drivers/driver_ceph_volumes.go, lxd/storage/drivers/driver_lvm_volumes.go, lxd/storage/drivers/driver_zfs_volumes.go, lxd/storage/drivers/errors.go, lxd/storage/drivers/generic_vfs.go, lxd/storage/drivers/utils.go
When creating containers on a block backed pool or creating a VM that supports optimized images, a cached image volume is created that contains the unpacked image using the `volume.size` property of the pool (or the default block size). This is used to speed up subsequent image creations by creating a snapshot of the cached image volume.
However if the `volume.size` property of a pool is changed *after* the initial cached block volume is created, subsequent instance creates will notice this an attempt to resize the new volume to the correct size.
A problem occurs if the new `volume.size` is smaller than the cached image volume size, as some filesystems used by containers don't support shrinking, and no VM volumes allow for shrinking currently.
This PR allows the storage pool driver to …
=> Storage: Regenerate cached image volumes when cannot be shrunk

lxd/device/proxy.go, test/suites/container_devices_proxy.sh
Fixes https://github.com/lxc/lxd/issues/7221
- Prevents using wildcard listen address in NAT mode.
- Prevents using proxy_protocol in NAT mode.
- Prevents mixing IP version addresses in NAT mode.
=> Proxy: Improves validation

lxd/migrate_instance.go, lxd/storage_migration.go
Although I don't believe that instance type in snapshots is used by the database layer anymore, it shouldn't be hardcoded to container in case the struct is used in other places in the future.
=> lxd: Updates snapshotProtobufToInstanceArgs to support instance type

lxd/instance/drivers/driver_qemu.go, lxd/instance/drivers/driver_qemu_templates.go
This now mimics the NUMA layout of the host in the guest for cases where
specific CPUs have been pinned.
=> lxd/qemu: Match basic NUMA layout

lxd/storage/drivers/driver_zfs_volumes.go
This was previously relying on the backend_lxd revert logic, but now we need CreateVolumeFromCopy to correctly revert on error so we can call it again if needed.
=> Storage ZFS: Delete volume on error in CreateVolumeFromCopy

lxd/device/device_utils_disk.go
Hello,
I had a little issue while configuring a CephFS device as described [here](https://lxd.readthedocs.io/en/latest/instances/#devices-configuration):
```
root@ubuntu-focal:~# lxc config device add u1 myfs disk source=cephfs:myfs/ ceph.user_name=admin ceph.cluster_name=ceph path=/cephfs
Error: Failed to start device "myfs": Unable to mount 10.0.0.1:6789:6789,10.0.0.2:6789:6789,10.0.0.3:6789:6789:/ at /var/lib/lxd/devices/u1/disk.myfs.cephfs: invalid argument
root@ubuntu-focal:~# cat /etc/ceph/ceph.conf 
[global]
mon_host = 10.0.0.1:6789,10.0.0.2:6789,10.0.0.3:6789
```
If the `/etc/ceph/$cluster_name.conf` file already has ports configured for the `mon_host` variable, the `diskCephfsOptions` should not append it another time.
This PR checks whether or not the ports should be added. …
=> lxd/device/utils: Do not add the Ceph mon port if already present in /etc/ceph config file

lxd/storage/drivers/driver_zfs_utils.go, lxd/storage/drivers/driver_zfs_volumes.go, lxd/storage/drivers/utils.go
When a block backed pool's settings change (such as changing the `volume.size` setting) the old cached image volume (which is set to the old pool's volume.size or default) needs to be deleted and regenerated. 
However some storage drivers have an 'undelete' feature whereby when an image volume is 'deleted', if it is in use as a parent to other volumes, it is only renamed and not actually deleted. Then if a subsequent call to `EnsureImage()` is performed then the existing volume is just 'undeleted' and renamed back to its original name.
This causes problems when we really want to regenerate the volume from fresh, as the old image is still using the old larger size.
This PR introduces driver level detect of deleted image volumes being larger than the pool's `volume.size` setting and then …
=> Storage: ZFS image volume regeneration when pool volume.size smaller than cached volume

shared/usbid/load.go
It's always missing during `lxd init` when run from the snap, even if
the daemon itself has access to it.
Closes #7256
=> share/usbid: Don't print error when missing

lxd/util/net.go, lxd/util/net_test.go
=> Resolve both core.https_address and cluster.https_address when comparing IPs

lxd/images.go
=> Export: Fixes hang in export when invalid --compression argument passed

lxd/instances_post.go, lxd/storage/backend_lxd.go, lxd/storage/drivers/driver_btrfs_volumes.go, lxd/storage/drivers/driver_ceph_volumes.go, lxd/storage/drivers/driver_dir_volumes.go, lxd/storage/drivers/driver_lvm_volumes.go, lxd/storage/drivers/driver_zfs_volumes.go, lxd/storage/drivers/generic_vfs.go, lxd/storage/drivers/volume.go
For generic VM backups, restore the original volume sizes rather than the target's default volume size.
In order to accommodate this change, whilst avoiding unnecessary scans of the compressed backup file, I have introduced the concept of a `Volume` setting called `allowUnsafeResize` that allows us to indicate to the storage driver that a we can shrink block volumes (as we do this before unpacking the backup volume).
=> Storage: Restore VM generic backups using their original volume size

lxd/storage/drivers/driver_ceph_utils.go, lxd/storage/drivers/driver_ceph_utils_test.go, lxd/storage/drivers/driver_ceph_volumes.go, lxd/storage/drivers/driver_zfs_volumes.go, lxd/storage/utils.go
This PR is larger than expected as I found a number of bugs and issues along the way:
- Allows regeneration of cached image volume if size is larger than pool's volume size.
- Ensures new volumes have their size set correctly (was previously ignored) when creating from an image volume.
- Always respects setting of `ceph.rbd.clone_copy`.
- Zombie image volumes were always suffixed with `_ext4` even if their filesystem wasn't that.
- Reworks zombie volume management to use volume type consistently rather than a mixture of volume type and volume name.
=> Storage: CEPH Support cached image regeneration

lxd/api_cluster.go, lxd/api_internal.go, lxd/backup.go, lxd/backup/backup.go, lxd/certificates.go, lxd/cluster/connect.go, lxd/db/certificates.go, lxd/db/config.go, lxd/db/containers.go, lxd/db/containers_test.go, lxd/db/db_internal_test.go, lxd/db/instances.mapper.go, lxd/db/migration_test.go, lxd/instance.go, lxd/instance/drivers/driver_lxc.go, lxd/instance/drivers/driver_qemu.go, lxd/instance/instance_utils.go, lxd/instance_post.go, lxd/instance_snapshot.go, lxd/instances.go, lxd/instances_get.go, lxd/instances_post.go, lxd/patches.go, lxd/storage/backend_lxd.go, lxd/storage/load.go, shared/generate/db/method.go
This is a first batch of renames of db functions, to make them more consistent with current naming conventions in LXD.
Other similar renames will be done progressively in follow-up branches.
=> Cleanup db function names

lxd/storage/backend_lxd.go
They have a filesystem config volume too, so need to also use this check.
=> Storage: Detect cached image filesystem changes for VM images too

lxd/storage/drivers/driver_btrfs_utils.go, lxd/storage/drivers/driver_btrfs_volumes.go, lxd/storage/drivers/driver_ceph_utils.go, lxd/storage/drivers/driver_ceph_volumes.go, lxd/storage/drivers/driver_dir_utils.go, lxd/storage/drivers/driver_dir_volumes.go, lxd/storage/drivers/driver_lvm_utils.go, lxd/storage/drivers/driver_lvm_volumes.go, lxd/storage/drivers/driver_zfs_utils.go, lxd/storage/drivers/driver_zfs_volumes.go, lxd/storage/drivers/generic_vfs.go, lxd/storage/drivers/utils.go
Updates dir, btrfs, lvm, zfs and ceph drivers to behave in a consistent way in terms of setting volume size (be it block volume size or quota).
Ensures that:
- `SetVolumeQuota()` function does nothing when supplied with a "0" or "" size argument for block volumes and removes quota if driver uses quotas.
- `volumeSize()` function returns the value of `vol.ExpandedConfig("size")` (which takes the size from volume config or pool config) and if not specified in either will return the `defaultBlockSize` if relevant for the driver (i.e for block backed drivers always return it, and for non-block-backed drivers only return it if creating a block volume).
Tested:
=> Storage: Updates volume size treatment to be consistent across drivers

lxd/instance/drivers/driver_qemu_templates.go
At least on aarch64, core_id doesn't appear to be supported.
So this will need more testing and potentially a different approach on
some architectures.
=> lxd/qemu: Restrict NUMA layout to x86_64

lxd/cluster/gateway.go
This is now safe since dqlite itself will return empty responses
when probing non-voting nodes.
=> Consider all nodes when looking for the leader, not only voters

lxd/storage/drivers/driver_zfs_volumes.go, lxd/storage/drivers/generic_vfs.go
This PR changes the way that `genericVFSMigrateVolume` detects if a VM root device exists as a disk image in the instance's config filesystem (and needs to be excluded when rsyncing that volume to the target) or whether it exists as a block device outside of the filesystem's mount path.
This allows us to avoid a pre-mount of snapshot volumes, as previously it required thid to activate the volume in order to ascertain whether the root disk was a disk image or a block device.
=> Storage: ZFS migration improvement

lxd/storage/drivers/driver_btrfs_volumes.go, lxd/storage/drivers/driver_ceph_volumes.go, lxd/storage/drivers/driver_dir_volumes.go, test/suites/storage_volume_attach.sh
This PR fixes an issue where for DIR and BTRFS drivers, if the custom volume root permission was modified inside the instance, it was then modified on restart back to the default value of `0711`.
Also fixes an issue with the created permissions on ceph volumes.
This issue was reported here https://discuss.linuxcontainers.org/t/secondary-disk-rights-issue/7679/
=> Storage: Don't reset custom volume root permissions on mount for DIR and BTRFS

lxd/resources/storage.go
=> lxd/resources: Skip NVME multipath entries

lxd/storage/drivers/driver_zfs_volumes.go
"zfs unmount" annoyingly wraps errors so just use our own TryUnmount
instead so we can deal with things taking a bit long to unmount.
Closes #7296
=> lxd/storage/zfs: Use TryUnmount

lxd/storage/drivers/driver_btrfs_utils.go, lxd/storage/drivers/driver_btrfs_volumes.go
The `snapshotSubvolume` function used to have a `readonly` argument. However it was not applied when using the `recursion` option.
However fixing the function so that it did apply the `readonly` argument when `recursion` was set to true caused more problems because when snapshotting an instance volume, it is expected that only the root subvolume be marked as readonly and not any subvolumes (so that their write status is preserved in the snapshot in order to correctly backup or migrate the volumes with the same state).
However all subvolumes do need to be set readonly when migrating/exporting (the marking of subvolumes as readonly will follow in a separate PR).
As such we need to do different things in different scenarios and a 'one size fits all' option here doesn't make sense. So I have …
=> Storage: Removes readonly option from snapshotSubvolume()

lxd/firewall/drivers/drivers_nftables.go
This fixes the `nft` syntax, as it causes the following error in LXD:
```
EROR[05-11|18:09:29] Firewall nftables unable to parse existing ruleset:
invalid character '^' looking for beginning of value
```
When running the command in a shell, it says:
```
$ nft list ruleset --json -nn
Error: syntax error, options must be specified before commands
nft list ruleset --json -nn
^             ~~
```
=> lxd/firewall/drivers: Fix nft syntax

lxd/storage/drivers/driver_lvm_utils.go, lxd/storage/drivers/driver_lvm_utils_test.go, lxd/storage/drivers/driver_lvm_volumes.go, test/suites/storage_snapshots.sh
Adds LVM volume snapshot parser and unit tests similar to ceph's `parseParent` function.
The intention is to more thoroughly parse LVM volume names to avoid issues like  https://github.com/lxc/lxd/issues/7335.
=> Storage: LVM snapshot parsing improvements

lxd/storage/drivers/driver_lvm.go, lxd/storage/drivers/driver_lvm_utils.go, lxd/storage/drivers/driver_lvm_volumes.go
This PR modifies the LVM driver to be more like the ZFS and Ceph drivers in that it will not activate all LXD logical volumes (in so much as entries will not appear in `/dev`) until the volumes are needed, and will deactivate them when they are not needed.
This uses the `--setactivationskip y` option in LVM to mark a volume as one that should not be automatically activated when the volume group is scanned.
For non-thinpool volumes, any snapshots are activated and deactivated by LVM when the parent is activated/deactivated. However LVM does not allow a non-thin snapshot to be activated without the parent already being activated (similar to ZFS) so we also detect this and activate the parent volume when needed.
=> Storage: LVM volume activation

lxd/cluster/gateway.go
This should get rid of a lot of spurious WARN messages when nodes disconnect from each other gracefully.
=> Don't run a connection proxy when connecting with the Go dqlite client

lxd/backup.go, lxd/backup/backup.go, lxd/device/device_utils_generic.go, lxd/device/device_utils_unix.go, lxd/device/disk.go, lxd/device/unix_common.go, lxd/storage/backend_lxd.go, lxd/storage/drivers/driver_btrfs.go, lxd/storage/drivers/driver_btrfs_utils.go, lxd/storage/drivers/driver_btrfs_volumes.go, lxd/storage/drivers/driver_ceph_volumes.go, lxd/storage/drivers/driver_cephfs_volumes.go, lxd/storage/drivers/driver_dir_volumes.go, lxd/storage/drivers/driver_lvm_volumes.go, lxd/storage/drivers/driver_types.go, lxd/storage/drivers/driver_zfs_volumes.go, lxd/storage/drivers/drivers_mock.go, lxd/storage/drivers/interface.go, lxd/storage/drivers/utils.go, test/suites/storage_driver_btrfs.sh
This PR introduces BTRFS subvolume support for optimized backups.
It introduces a new optional field in the index.yaml file called `optimized_header` which is a boolean.
This is used to indicate to the restorer that we should look for a storage driver specific optimized header file called `optimized_header.yaml` in the backup file next.
e.g.
```
name: c1
backend: btrfs
pool: btrfs
snapshots:
- snap0
optimized: true
optimized_header: true
type: container
```
The BTRFS `optimized_header.yaml` is now always added to optimized tarballs, even if subvolumes haven't been detected. It contains all subvolumes and snapshot subvolumes (even just the root subvolume if no subvolumes have been detected).
e.g.
```
subvolumes:
- path: /
snapshot: snap0
readonly: true
- path: /rootfs/a
snapshot: snap0 …
```
=> Storage: BTRFS backup subvolume support

doc/index.md
When I tried 'shifted=true' with lxd 4.1 snap on Ubuntu 20.04, I got this:
Error: Invalid devices: Device validation failed "test4src": Invalid device option "shifted"
=> Fix 'how to mount home directory' shiftfs FAQ

lxd/rsync/rsync.go, lxd/storage/utils.go
Unified image VM unpack was not working for dir and btrfs drivers because the rsync of unpacked config files was removing the generated rootfs block file that was generated.
This was silently failing because subsequently the storage driver attempted to set the generated volume to the correct size, and as it was missing, just generated a new blank image of the correct size.
However the resulting VM was unbootable.
=> Storage: Fix VM unified image unpack for dir and btrfs drivers

lxd/resources/network_ethtool.go
the same way we don't in the legacy part of the interface.
Closes: #7382.
=> ethtool: don't report -1 for speed in ethtoolLink()

lxd/firewall/drivers/drivers_nftables_templates.go
=> firewall: Fixes proxy nat rule dynamic family when using nftables

lxd/patches.go, lxd/storage/drivers/driver_btrfs.go, lxd/storage/drivers/driver_ceph.go, lxd/storage/drivers/driver_cephfs.go, lxd/storage/drivers/driver_common.go, lxd/storage/drivers/driver_dir.go, lxd/storage/drivers/driver_lvm.go, lxd/storage/drivers/driver_lvm_patches.go, lxd/storage/drivers/driver_zfs.go
Applies the skipactivation=y flag to LXD managed LVM volumes.
This brings existing volumes into line with new volume behaviour introduced in https://github.com/lxc/lxd/pull/7303.
=> Storage: LVM skipactivation patch

lxd/firewall/drivers/drivers_nftables.go, lxd/firewall/drivers/drivers_xtables.go, lxd/firewall/firewall_interface.go, lxd/firewall/firewall_load.go
Warning contains the issue as to why the xtables driver we are using as "last resort" is not fully compatible and may still cause unexpected behaviour.
=> Firewall: Updates detection to warn when falling back to non-compatible xtables driver

lxd/instance_exec.go
```
DBUG[05-21|14:59:09] Finished mirroring websocket             instance=f3 PID=623244
DBUG[05-21|14:59:18] Failed to set window size                instance=f3 PID=623244 LOG15_ERROR= LOG15_ERROR= LOG15_ERROR="Normalized odd number of arguments by adding nil"
DBUG[05-21|14:59:18] Interactive child process handler finished instance=f3 PID=623244
panic: interface conversion: interface {} is int, not string
goroutine 3111 [running]:
github.com/lxc/lxd/lxd/events.logContextMap(0xc0005f4fa0, 0xa, 0xa, 0xc000108080)
/home/brauner/src/go/src/github.com/lxc/lxd/lxd/events/logging.go:42 +0x1ae
github.com/lxc/lxd/lxd/events.Handler.Log(0xc000108080, 0x0, 0x0)
/home/brauner/src/go/src/github.com/lxc/lxd/lxd/events/logging.go:32 +0x79
github.com/lxc/lxd/shared/log15.MultiHandler.func1(0xc000108080, …
```
=> instance_exec: don't panic

lxd/api_cluster.go, lxd/cluster/gateway.go, lxd/cluster/membership.go, lxd/daemon.go
Although it's possible to hold leadership while being demoted to spare, that
creates a few issues down the line.
=> lxd/cluster: Transfer leadership before adjusting roles, not after

lxd/storage/drivers/driver_btrfs_utils.go, lxd/storage/drivers/driver_btrfs_volumes.go, shared/archive.go
This PR fixes the intermittent BTRFS optimized import errors seen in jenkins.
The `context.cancelFunc` returned by `CompressedTarReader()` just cancelled context (which kills the unpacker process), however the `cancelFunc` does not wait until the process has finished, it just signals it to end.
This means after cancelling the tar reader when finding a file we want, and the immediately moving onto rewinding the same io.Reader and reading it again causes unexpected io.EOF and concurrent readers of the same stream.
Instead, once the unpacker process has started, we now return a custom `context.cancelFunc` that wraps the internal `cancelFunc` passed to the unpacker process, with one that calls the `cancelFunc` to signal the process to end, and then waits for it to end before returning.
This …
=> Storage: Fix intermittent BTRFS optimized restore errors

lxd/api.go, lxd/api_internal.go, lxd/daemon.go, lxd/main_daemon.go
We need to do this since now we're leaving the endpoints open for a good part of
the shutdown sequence, to allow for cluster membership adjustments.
=> lxd/api: Fail /internal/ready requests made after shutdown has started

lxd/daemon.go, lxd/device/proxy.go, lxd/include/compiler.h, lxd/include/macro.h, lxd/include/process_utils.h, lxd/include/syscall_numbers.h, lxd/instance/drivers/driver_lxc.go, lxd/main_checkfeature.go, lxd/main_forkfile.go, lxd/main_forkmount.go, lxd/main_forknet.go, lxd/main_forkproxy.go, lxd/main_forksyscall.go, lxd/main_forkuevent.go, lxd/main_nsexec.go, lxd/seccomp/seccomp.go, lxd/sys/os.go, shared/util.go, shared/util_linux_cgo.go
This ports all of the forkfile() handlers to verify the validity of the target
process via pidfds. This hardens our codebase and specifically means that we
can't accidently operate on a wrong process when under heavy contention.
I'm going to port all subcommand but want to do so step by step to minimize the
risk of subtle breakages. Once they're all switched over I will do another
cleanup sweep.
=> forkfile: port to using pidfds

test/suites/container_devices_nic_bridged.sh
Older kernels prevent bridge MTU from being raised to value higher than
lowest member.
=> tests: Don't assume bridge MTU can be forced up

lxd/storage/backend_lxd.go, lxd/storage/drivers/driver_btrfs_volumes.go, lxd/storage/drivers/driver_ceph_volumes.go, lxd/storage/drivers/driver_cephfs_volumes.go, lxd/storage/drivers/driver_common.go, lxd/storage/drivers/driver_dir_volumes.go, lxd/storage/drivers/driver_lvm_utils.go, lxd/storage/drivers/driver_lvm_volumes.go, lxd/storage/drivers/driver_types.go, lxd/storage/drivers/driver_zfs_volumes.go, lxd/storage/drivers/generic_vfs.go, lxd/storage/drivers/utils.go, lxd/storage/drivers/volume.go, lxd/storage/drivers/volume_test.go, lxd/storage/utils.go
This PR allows images larger than the default 10GB block disk size to be used.
Fixes https://github.com/lxc/lxd/issues/7346 
Create a VM image larger than the default 10GB block disk size:
```
lxc init images:ubuntu/focal/cloud v1 --vm
lxc config device override v1 root size=15GB // Enlarge beyond default 10GB block disk size
lxc start v1  // Wait for boot and cloud init to resize rootfs inside guest
lxc exec v1 -- df -h  | grep /dev/sda2
/dev/sda2        14G  796M   13G   6% /
lxc stop v1
lxc publish v1 --alias myvm
lxc delete v1
```
Now check we can create new VM from the image when the storage pool has no `volume.size` set.
```
lxc init myvm v1
sudo zfs get volsize default/images/f037ad0b451277b594d9f5d80f518f77a6f1a7184a2c7d55939946192ee9a896.block
NAME …
```
=> Storage: Support VM image unpack size greater than volume size

lxd/storage/utils.go
Missed removing this when introducing `convertBlockImage` which calls `qemu-img convert`.
=> VM: Removes duplicated qemu-img call in ImageUnpack

lxd/storage/drivers/driver_zfs_utils.go, lxd/storage/drivers/driver_zfs_volumes.go, lxd/storage/drivers/utils.go, lxd/storage/utils.go
Works around issues unpacking images on loopback files that causes kernel hangs on ZFS and slow downs on LVM.
Includes https://github.com/lxc/lxd/pull/7459
=> VM: Use qemu-img dd mode instead of convert

lxd/db/images.go
The function was failing when more than one image was matching, although that's
expected in case multiple projects have it.
Fixes #7474
=> Fix regression in GetImageFromAnyProject

lxd/device/nic_bridged.go, lxd/network/network_utils.go
Stopping an instance was not detaching the bridged NIC device from the openvswitch bridge, causing port leaks such as:
```
sudo ovs-vsctl show
84593e35-9a66-45ba-b647-929e396b3a59
Bridge lxdbr1
Port lxdbr1
Interface lxdbr1
type: internal
Port veth1d5cd6a9
Interface veth1d5cd6a9
error: "could not open network device veth1d5cd6a9 (No such device)"
```
Also includes some other comment/code clarity improvements.
=> NIC: Bridged device fix openvswitch port leak

doc/instances.md
According documentation supported types with virtual machines are physical, bridged, macvlan, p2p, sriov
=> Remove incorrect statement about supported network devices with virtual machines

lxd/api_cluster.go, lxd/db/db.go
The Driver.SetContextTimeout() has been a no-op for a while now and should be
dropped.
The functionality has been moved to the WithContextTimeout() option, which we
use when creating the driver object and that sets a 30 seconds timeout for
DB.Begin().
In all other cases we don't actually timeout anymore and rather rely on the
network layer to report a broken connection. So the original #5234 issue can't
happen anymore for non-clustered deployments.
=> Stop using Driver.SetContextTimeout() which is a no-op

lxd/instance/drivers/driver_lxc.go, lxd/instance/drivers/driver_qemu.go
Whilst working on https://github.com/lxc/lxd/pull/7488 I noticed that when the mount failed the container failed to start and left orphaned veth pairs hanging around on the host.
This PR runs the device cleanup code when an instance fails to start.
Also makes a tentative start at introducing contextual debug logging to instances.
=> Instance: Device cleanup on failed start

lxd/storage/drivers/driver_ceph_utils.go, lxd/storage/drivers/driver_ceph_volumes.go, lxd/storage/drivers/driver_lvm_utils.go, lxd/storage/drivers/driver_lvm_volumes.go, lxd/storage/drivers/volume.go
Fixes LVM driver that wasn't reading volume's `block.mount_options` when mounting.
Addresses an issue discovered in https://discuss.linuxcontainers.org/t/volume-block-mount-options-not-working/8049
=> Storage: Unifies LVM and Ceph filesystem mount option logic

lxd/device/config/devices_sort.go, lxd/device/config/devices_test.go, lxd/instance/drivers/driver_qemu.go, lxd/instance/drivers/driver_qemu_templates.go, lxd/instance/drivers/qmp/monitor.go
This adds a new helper function within the config generation logic that
automatically figures out the best PCI config to minimize the use of
bridge ports and devices by using multi-function devices when possible.
=> lxd/vm: Centralize port generation

doc/instances.md, lxd/device/config/device_runconfig.go, lxd/device/device_utils_generic.go, lxd/device/gpu.go, lxd/instance/drivers/driver_qemu.go, lxd/instance/drivers/driver_qemu_templates.go
Tested with following devices:
For each GPU tested, I checked that `lspci` shows VGA compatible device in VM, and that `lspci -k` shows it using the relevant graphics driver in use, and that it shows in `/sys/class/drm`.
Additionally for the NVIDIA GPU, I installed `nvidia-smi` and check it could run and was able to extract info, such as temperature and product name.
The NVIDIA card required starting the VM with these options in order for nvidia-smi to work.
```
raw.qemu: -cpu host,kvm=off,hv_vendor_id=null -machine type=q35,kernel_irqchip=on
```
Onboard Intel i915 graphics:
```
00:02.0 VGA compatible controller: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller (rev 06)
```
Discrete NVIDIA GTX 770 (and associated sound device in an IOMMU group):
``` …
```
=> VM: Adds GPU passthrough support

lxd/instance/drivers/driver_qemu.go, lxd/instance/drivers/driver_qemu_bus.go, lxd/instance/drivers/driver_qemu_templates.go, lxd/instance/drivers/qmp/monitor.go
Some small clarification comments, and tweaks to constants and var naming for clarity.
Also adds `qemuSerialChardevName` constant to share serial char dev name between qemu and qmp to avoid hardcoding it in two places.
=> VM: Bus allocation comments, constants and var naming

lxd/cluster/heartbeat.go
Aims to fix crashed caused in https://jenkins.linuxcontainers.org/job/lxd-github-pull-test/1324/arch=amd64,backend=dir,compiler=golang-1.13/console#console-section-1
```
fatal error: concurrent map iteration and map write
goroutine 3542 [running]:
runtime.throw(0x14f00f9, 0x26)
/lxc-ci/build/tmp.hp8MOZNie4/go/golang/src/runtime/panic.go:774 +0x72 fp=0xc000a79638 sp=0xc000a79608 pc=0x43c3f2
runtime.mapiternext(0xc001e655c0)
/lxc-ci/build/tmp.hp8MOZNie4/go/golang/src/runtime/map.go:858 +0x579 fp=0xc000a796c0 sp=0xc000a79638 pc=0x41c349
runtime.mapiterinit(0x12e3ee0, 0xc0022a4450, 0xc001e655c0)
/lxc-ci/build/tmp.hp8MOZNie4/go/golang/src/runtime/map.go:848 +0x1c3 fp=0xc000a796e0 sp=0xc000a796c0 pc=0x41bce3
reflect.mapiterinit(0x12e3ee0, 0xc0022a4450, 0xc0008bbdc0) …
```
=> Cluster: Fix race in HeartbeatNode

lxd/instance/drivers/driver_qemu.go
Otherwise CentOS 7 VM guests can't mount 9p shares.
See https://discuss.linuxcontainers.org/t/lxd-attach-volume-to-qemu-vm/7273/16
=> VM: Adds trans=virtio to 9p mounts

lxd-agent/main_agent.go
Convert to absolute from /.
Skip if mount point doesn't exist and can't be created.
See https://discuss.linuxcontainers.org/t/lxd-4-2-error-when-attaching-additional-disk-to-vm/8215
=> VM agent: Fix 9p mount when relative target path is supplied

test/suites/container_devices_nic_bridged.sh, test/suites/container_devices_nic_bridged_filtering.sh
=> test: Updates udhcpd args to ensure process quits one lease acquired

lxd/db/storage_pools_test.go, lxd/db/storage_volumes.go, lxd/storage_volumes_snapshot.go
This changes the snapshot index retrieval to consider the storage pool
as well. Previously, the behaviour would have been:
```
lxc storage create dir1 dir
lxc storage create dir2 dir
lxc storage volume create dir1 vol
lxc storage volume create dir2 vol
lxc storage volume snapshot dir1 vol # creates vol/snap0
lxc storage volume snapshot dir2 vol # creates vol/snap1
```
=> lxd: Fix snapshot index retrieval

lxd/cluster/upgrade.go
When running lxd cluster recover-from-quorum-loss, if your raft node 1 is still
around it wasn't added back to the raft configuration after recovery.
=> lxd/cluster: If raft node 1 gets remove during recovery, add it back

lxd/storage/drivers/volume.go
The UEFI nvram on aarch64 is 64MB so wasn't fitting in our previous
value when stored on a block based storage driver.
=> lxd/storage/drivers: Bump VM fs size to 100MB

lxc/action.go
=> lxc/action: Show usage on missing target

lxd/main_forksyscall.go, lxd/seccomp/seccomp.go
=> forksyscall: use nsids for shiftfs syscall intercepts

lxd/storage/drivers/utils.go
=> lxd/storage: Fix regression in truncate handling

lxd/.dir-locals.el, lxd/api_cluster.go, lxd/cluster/connect.go, lxd/cluster/gateway.go, lxd/cluster/membership.go, lxd/cluster/notify.go, test/suites/clustering.sh
This effectively replaces some of LXD's built-in logic around dqlite roles management with equivalent logic now available downstream in the go-dqlite/app package.
There's no change in behavior, except that the switch also brings in a bug fix, since LXD was previously demoting offline voters to spare, even if no replacement was available (i.e. another spare or stand-by node to be promoted to voter). In that situation it's better to not take away the role from the offline voter node (as otherwise we would be left with a cluster of 2 voters), hoping that the offline voter will come back or a spare/stand-by will become available to replace it.
=> Plug go-dqlite roles logic into LXD

doc/server.md
This adds a few more pointers to what's needed for listening on network
and the external auth and RBAC features.
Closes #7591
=> doc/server: Cover listen + authentication

doc/rest-api.md, lxd/instance/drivers/driver_lxc.go, lxd/instance/drivers/qmp/monitor.go, shared/util_linux.go
The ptmx and pts abbreviations contain their problematic terminology.
=> terminals: update terminology again

lxd/daemon.go
=> lxd/rbac: Always allow internal cluster traffic

lxd/main.go, lxd/rsync/rsync.go
As we consume lxd/rsync from lxc-to-lxd and lxd-p2c, trying to keep
dependency chain small.
=> lxd/rsync: Untangle from daemon package

lxd/instance/drivers/driver_qemu.go
=> lxd/qemu: Don't use file.locking with rbd

lxd/resources/storage.go
=> lxd/resources: Use udev model data if available

lxd/cluster/connect.go
When attempting invoke setup trust, if the passed in cert fails to
decode there isn't any error to return and will just return nil.
Considering this will always be nil, then the error message will never
be displayed. Change to always return the error and will work as
expected.
Signed-off-by: Simon Richardson simon.richardson@canonical.com
=> Decode error

lxd/instance/drivers/driver_qemu_templates.go
Without this, a VM that would use hugepages without an optimized CPU
pinning would end up consuming both hugepages and normal memory.
=> lxd/qemu: Properly connect memory

lxc/console.go
=> lxc: Populate cmdConsole.flagType also when ran manually

lxd/instance/drivers/driver_qemu_templates.go
This adds two additional named serial ports for interacting with guest
services over SPICE.
With those in place, clipboard sharing, improved cursor/resolution
management and folder sharing are all possible.
=> lxd/qemu: Add support for spice agent

doc/api-extensions.md
=> doc/api-extensions: Fix over-escaping

lxd/network/driver_bridge.go, lxd/network/driver_common.go, lxd/network/network_interface.go, lxd/networks.go
- Moving common functionality out of bridge driver and into common driver.
- Adds contextual logging support.
- Unifies and clarifies naming of `notify` and `withDatabase` arguments.
Testing:
- Single node create, update, rename, delete.
- Cluster create (with --target first on each node), update and delete (checking for `clusterNotification` contextual logging).
=> Network: Bridge updates to use common driver functionality

lxd/network/driver_bridge.go, lxd/network/driver_common.go, lxd/network/network_interface.go, lxd/network/network_load.go, lxd/network/network_utils.go, lxd/networks.go
- Pushes FillConfig logic down into network driver.
- Adds support for different network types to `doNetworkGet`.
- Adds no-op `HandleHeartbeat` to common driver to avoid needing drivers to implement if not needed.
- Exposes actual error message from `ValidNetworkName` when validating driver config.
=> Network: Pushes FillConfig logic down into network driver

lxd-agent/operations.go, lxd/images.go, lxd/operations.go, lxd/operations/operations.go
The PR https://github.com/lxc/lxd/pull/7629 introduced a race condition by using the `operations.Operations()` function that returns a reference to the internal `operations.operations` map in a loop.
Additionally, even with a lock (like the existing usage of the `operations.Operations()` function, it is still not 100% safe, as after getting a reference to the map, the items can still be concurrently changed in an unsafe way. There are other places in the code base that also have this issue.
This PR replaces the unsafe `operations.Operations()` with an `operations.Clone()` function that locks the internal operations map and returns a clone of the map, whilst keeping the elements of the map as references to the original operations themselves.
=> Operations: Fixes race condition and unsafe Operations() function

lxd/api_cluster.go, lxd/db/networks.go, lxd/device/nic_bridged.go, lxd/network/driver_bridge.go, lxd/network/driver_common.go, lxd/network/network_interface.go, lxd/network/network_load.go, lxd/networks.go, lxd/networks_utils.go, shared/api/network.go
- Removes `GetNetwork` as no longer needed.
- Adds constants for network string statuses.
- Adds check for `bridged` NIC validation that prevents adding a NIC using `network=` for a pending network.
- Adds check preventing starting a pending `bridge` network.
- Fixes issue with `Errored` clustered network not being removable (due to `network.LoadByName()` failing).
- Fixes issue with `Errored` clustered network preventing LXD from starting (due to `network.LoadByName()` failing).
=> Network: Fixes "Errored" networks from preventing LXD start

lxd/db/networks.go, lxd/network/driver_bridge.go, lxd/network/driver_common.go, lxd/network/network_interface.go, lxd/networks.go
@freeekanayaka continues on from yesterday's cluster network improvements.
- Adds network type checks when setting up pending and final networks.
- Rejects node-specific key updates without `--target` flag.
- Rejects non-node-specific key updates when used without `--target` flag.
- Strips node-specific keys when forwarding to other nodes for notification of change.
- Only sends notifications to other nodes when no `--target` specified.
- Forwards node-specific update requests to correct node (fixes etag mismatch issue when used with `--target`).
- Loads node-specific config before applying update keys, to allow proper per-node validation.
- Merges PUT and PATCH network update routes as now functionality equivalent.
- Allows 'repair' of `Errored` clustered network setup by allowing `lxc …
=> Network: Cluster updates

doc/clustering.md, lxd/db/networks.go, lxd/device/nic_macvlan.go, lxd/network/driver_macvlan.go, lxd/network/network_load.go, lxd/networks.go, test/suites/container_devices_nic_macvlan.sh
This PR allows one to use a `macvlan` managed network for adding `macvlan` NICs, e.g.
```
lxc network create test --type=macvlan parent=enp3s0
lxc config device add c1 eth0 nic network=test
```
- Adds support for `network` property to `macvlan` NIC devices.
Please dont merge until after https://github.com/lxc/lxd/pull/7676 has been merged and this has been rebased.
=> Network: Adds network property support to macvlan NIC driver

doc/instances.md, doc/networks.md, lxd/db/networks.go, lxd/device/nic_sriov.go, lxd/device/nictype/nictype.go, lxd/network/driver_sriov.go, lxd/network/network_load.go, lxd/networks.go, test/suites/container_devices_nic_sriov.sh
This PR allows one to use a sriov managed network for adding sriov NICs, e.g.
```
lxc network create test --type=sriov parent=enp4s0f0
lxc config device add c1 eth0 nic network=test
```
=> Network: Adds network property support to sriov NIC driver 

lxd/device/nic_bridged.go, lxd/network/driver_bridge.go, lxd/network/network_utils.go, lxd/network/openvswitch/ovs.go, lxd/networks.go
As part of the planned OVN work I am intending to create a wrapper struct to encapsulate calls to the `ovn-*` commands.
The OVN project will also require running some `ovs-*` commands too, so for the first part of this I have created `openvswitch` package that will house both OVS and OVN wrapper functions, and initially moved just the OVS related functions over to it.
=> Network: Moves calls to ovs-vsctl to own package

doc/api-extensions.md, shared/version/api.go
=> api: Adds network types API extension for macvlan and sriov

doc/image-handling.md
=> doc: Typo fix

lxd/network/driver_bridge.go, lxd/networks.go
Fixes bug where removing a config key when doing an EDIT/PUT did not result in the key being removed due to the existing config being merged (in order to support node-specific config being validated when updating non-node specific config).
Changes the behaviour so that if HTTP method is PATCH we always merge submitted keys with existing config. 
However for PUT method we now check if the `target` flag has been supplied, and if not, then we only merge in the node-specific config keys (which are not allowed to be updated without a target flag anyway). In this way non-node specific config keys that are removed in the PUT data are removed from the database.
In node-specific PUT requests (i.e those with a non-empty target flag), we expect the full config (including node specific keys should be …
=> Network: Differentiate between PUT and PATCH in certain circumstances

lxd/migrate.go, lxd/network/driver_bridge.go, lxd/network/driver_common.go, lxd/network/network_interface.go, lxd/network/network_load.go, test/suites/container_devices_nic_bridged.sh
Applies defaults to missing config keys on `Update()` not just when creating the initial network.
This fixes a bug where if one of the fields that is automatically populated at create time is removed via an update, the key is re-populated using new (sometimes random) values.
Includes https://github.com/lxc/lxd/pull/7689 (dont merge until after it has been and this has been rebased please).
=> Network: Bridge defaults on Update

lxd/device/device_utils_network.go, lxd/device/nic.go, lxd/network/driver_bridge.go, shared/instance.go
With the forthcoming OVN network feature, the first part of this feature will require the use of an existing bridge network to be used as the external "uplink" network to get access to external resources. When running OVN in a clustered environment, OVN chooses one node as the active default gateway, and will use the local bridge on that node as the default gateway next-hop MAC address.
When a node goes down, OVN will switch the default gateway to a different node automatically, however it does not re-run neighbour discovery (ARP/NDP) and continues to use the previously discovered MAC address of the uplink bridge for the default gateway next-hop.
This causes problems at the moment because each bridge defined is given a random MAC address on every start up, which is different on every …
=> Network: Persistent randomly generated MAC address for bridge interface

lxd/device/device_utils_jnfiniband_test.go
=> lxd/device/device/utils/infiniband/test: Changes test name for linter

lxd/network/driver_bridge.go, lxd/networks.go
- Adds check to avoid using stable volatile MAC addresses when using `bridge.external_interfaces` and no bridge IPs to avoid possible MAC conflicts in a clustered environent where multiple nodes are connected to same network segment.
- Fixes a bug that prevented updating/removing a network's node-specific keys when in non-clustered mode.
=> Network: Don't use stable volatile MAC when using bridge.external_interfaces with no bridge IPs

lxd/device/device_utils_network.go
When tc fails (e.g. kernel module not present) it will output to stderr and stdout will be empty.
However currently stderr is completely ignored in the error path:
```
Error: Common start logic: Failed to start device "eth0": Failed to create ingress tc qdisc:
Try `lxc info --show-log foobar` for more info
```
This commit fixes that.
=> lxd/device: fix empty error message when tc fails

test/suites/clustering.sh
Pending operations take up to 5 seconds to be removed from the database, even
after completion. Since we don't record the status in the database, and that
status appears to be something that only the local node stores, we can't cheaply
know what the status is when we querying the database to decide placement of a
new container.
=> test: Wait for operations to be removed from the database

doc/networks.md, lxd/device/device_utils_network.go, lxd/device/nic.go, lxd/device/nic_bridged.go, lxd/device/nic_macvlan.go, lxd/device/nic_sriov.go, lxd/network/driver_bridge.go, lxd/network/driver_macvlan.go, lxd/network/driver_sriov.go, lxd/storage/utils.go, shared/instance.go, shared/validate/validate.go
- Adds mtu and vlan options for macvlan and sriov networks.
- Introduces `validate.Optional()` wrapper which can be used with existing validate helper functions to make them optional, rather than building support into every helper.
- Updated `validate.IsInt64` to not be optional and updated usage of it to wrap with `validate.Optional()`.
=> Networks: Adds mtu and vlan options for macvlan and sriov networks

lxd/device/device_utils_network.go, lxd/device/nic_bridged.go, lxd/device/nic_p2p.go, lxd/device/nic_routed.go, lxd/network/driver_common.go, lxd/network/network_interface.go, lxd/network/network_utils.go, lxd/networks.go
- Splits host veth helper functions, so that OVN NICs can make selective use of them.
- Standardises enrichment of `hwaddr` and `host_name` fields from volatile map.
- Adds `Create` function for networks, and defaults to it being a no-op.
- Updates network in-use detection to directly match managed network names referenced by `network` property in NIC.
=> Network: Splits host veth helper functions

lxd/device/device_utils_network.go, lxd/device/nic_bridged.go, lxd/dnsmasq/dhcpalloc/dhcpalloc.go, lxd/dnsmasq/dnsmasq.go, lxd/network/driver_bridge.go, lxd/network/driver_common.go, lxd/network/network_interface.go, lxd/network/network_utils.go, lxd/networks.go
We need to perform static DHCP allocation against the dnsmasq config on a managed LXD bridge in order to allocate an IP for the OVN uplink ports.
This is very similar to what we already do in the bridged NIC when automatically allocating  static IP for use with the `security.ipN_filtering` features.
The existing implementation was tightly coupled to said IP filtering features and the bridged NIC type. Also I was not happy with the clarity of the existing code (I wrote it) as the way it dealt with the ability to selectively generate IP allocations for each protocol dependent on which IP filtering feature was enabled, whilst still only parsing the dnsmasq leases file once, was not particularly clear and had to handle many edge cases in multiple places.
In hind site what would have made it …
=> Network: DHCP static allocation package

lxd/main_activateifneeded.go
Specify the database name in each debug statements.
Signed-off-by: Michael Jeanson <mjeanson@efficios.com>
=> lxd/main_activateifneeded: Clarify 'No DB' debug statements

lxd/apparmor/apparmor.go, lxd/apparmor/instance.go
This ensures that all the low-level functions properly handle the lack
of AppArmor support.
The higher level functions can therefore ignore this situation entirely.
=> lxd/apparmor: Don't fail on missing apparmor

lxd/daemon.go, lxd/main_checkfeature.go, lxd/main_forksyscall.go, lxd/main_nsexec.go
In nested workloads where the outer LXD hasn't used shiftfs the container's
rootfs won't be marked for shifting and since the inner container hasn't
mounted the rootfs itself it's user namespace doesn't own the superblock of the
rootfs filesystem. Since we require CAP_SYS_ADMIN in the owning user namespace
of the superblock shiftfs isn't useable for the inner LXD. Handle that case.
=> daemon: check whether shiftfs is useable

lxd/main_init_interactive.go, lxd/network/driver_bridge.go, lxd/network/driver_macvlan.go, lxd/network/driver_sriov.go, lxd/network/network_interface.go, lxd/network/network_load.go, lxd/network/network_utils.go, lxd/networks.go, lxd/storage/utils.go
Introduces concept of "real" networks vs "virtual" networks, where the former is tied to one or more actual Linux network interfaces, and the latter is not. These "virtual" networks have much relaxed naming rules compared with their "real" counterparts.
=> Network: Validate network name differently based on network type

doc/networks.md, lxd/cluster/config.go, lxd/device/nic_bridged.go, lxd/network/driver_bridge.go, lxd/network/driver_common.go, lxd/network/network_interface.go, lxd/network/network_utils.go, lxd/network/openvswitch/ovs.go
- OVS command wrapper function naming consistency and efficiency.
- Import ordering.
- Doc typo.
- Adds `ID()` function to `Network` interface.
=> Network: Small miscellaneous networking tweaks

shared/validate/validate.go
This is an idea I had whilst working on the network name validation.
Sometimes it would be useful to run multiple validators on a field, and right now the only choice we have is to create an anonymous function that calls multiple validators.
This PR modifies the existing `Optional()` function to make it variadic so it can accept multiple validators.
It also adds a `Required()` function which does the same as `Optional()` without the check that causes it to return nil if the supplied value is an empty string.
This allows validation rules to be defined as follows:
```go
rules := map[string]func(value string) error{
"parent":           validate.Required(validInterfaceName, validate.IsURLSegmentSafe),
"mtu":              validate.Optional(validate.IsInt64),
"vlan": …
```
=> Validate: Adds Required() and makes Optional() accept multiple validators

lxd/network/driver_bridge.go
The same MAC address on all fan bridge interfaces in the cluster breaks host<->fan comms.
=> Network: Don't generate volatile.bridge.hwaddr in fan mode or allow static hwaddr to be set

doc/api-extensions.md, doc/instances.md, doc/production-setup.md, lxd/daemon.go, lxd/include/lxd_seccomp.h, lxd/include/syscall_numbers.h, lxd/main_checkfeature.go, lxd/seccomp/seccomp.go, lxd/sys/os.go, scripts/bash/lxd-client, shared/instance.go, shared/version/api.go
Thing's aren't normal on Linux anymore and we have users that want to run bpf
in unprivileged containers. This is of course completely opt-in and not to be
used lightly.
This patch makes it possible for LXD to manage the bpf() syscalls of an
unprivileged task in a container.
For a start, this enables support for BPF_PROG_TYPE_CGROUP_DEVICE program types
and BPF_CGROUP_DEVICE attach and detach types. This serves as a POC that it is
possible to manage bpf programs for a task running in an unprivileged
container.
I expect this to be extended in the future should users have a need for it.
There are a several ways we could extend this:
- supporting more program types
- supporting maps of pre-compiled or pre-written bpf programs instead of
loading the container's own
Signed-off-by: Christian …
=> seccomp: enable bpf in unprivileged containers

lxd/daemon.go, lxd/include/process_utils.h, lxd/include/syscall_numbers.h, lxd/include/syscall_wrappers.h, lxd/main_checkfeature.go, lxd/main_forkexec.go, lxd/sys/os.go
Starting with v5.9 we don't need the crazy proc-based loop anymore since we've
implemented the close_range() syscall: detact and use it!
=> exec: switch to close_range()

lxd/apparmor/network_dnsmasq.go
=> lxd/apparmor/dnsmasq: Add binary for nesting

lxd/db/storage_volumes.go
This fixes a bug in which volumes wouldn't be listed at all if one of
the nodes didn't have any volumes.
=> lxd/db: Fix premature failure when listing cluster volumes

lxd/storage/drivers/driver_ceph_utils.go
This fixes a bug in which deleting a volume with snapshots would only
delete the snapshots, not the volume itself.
=> lxd/storage/drivers/ceph: Fix volume deletion

lxd/network/driver_bridge.go, lxd/network/network_load.go, lxd/network/network_utils.go, lxd/patches.go
Up until now there was no way (AFAIK) for the LXD client to indicate to the LXD server that the local network being created/updated was a precursor to joining the node to a cluster.
This caused an issue because in LXD 4.4 new bridge networks have a static bridge MAC address generated on create/update. 
If a network on the existing cluster was created before the cluster was upgraded to LXD 4.4, then the network does not get a static MAC until it is updated (by design to avoid network interruption).
Unfortunately this meant that when a fresh node was joined to the (now up to date) cluster, part of the process requires that the networks on the cluster be created on the new node before it is joined (and the cluster checks that the network configs match before allowing the join).
What was …
=> Network: Allow an LXD 4.4 node to join a cluster where the networks were created before LXD 4.4

lxd/api_cluster.go, lxd/cluster/heartbeat.go, lxd/cluster/upgrade.go, lxd/cluster/upgrade_export_test.go, lxd/cluster/upgrade_test.go, lxd/daemon.go
If there are other raft-related changes in progress, trying to upgrade a node without raft configuration (typically when upgrading a pre-3.20 cluster to >=3.20) might race with other cluster changes (e.g. node removal).
This change makes sure that we perform such upgrades serially, by acquiring the same Daemon.clusterMembershipMutex lock used for other membership operations.
=> cluster: Don't upgrade nodes without raft role concurrently

lxd/apparmor/network.go, lxd/apparmor/network_dnsmasq.go, lxd/apparmor/network_forkdns.go, lxd/instance/drivers/driver_qemu.go, lxd/network/driver_bridge.go, lxd/resources/usb.go, lxd/sys/os.go, shared/subprocess/proc.go, shared/usbid/load.go
This branch has the eventual goal of running `forkproxy` under an apparmor profile as well as running it as an unprivileged user.
To achieve this I needed a few extra things:
- Ability to run a subprocess as another user/group
- An unprivileged group to use
Additionally because `lxd forkdns` is a sub-command of LXD, a lot of code gets loaded just because it's LXD.
Part of that was loading the whole USB database which we only need for `lxd/resource` so I've changed that code a bit.
We still are accessing a bunch of files on startup that we shouldn't be. The cgroup and apparmor bits come from us loading liblxc. No idea where the hugepage one comes from.
=> Reduce privileges and confine forkdns

lxd/dnsmasq/dhcpalloc/dhcpalloc.go, lxd/network/driver_common.go, lxd/network/network_interface.go, shared/network_ip.go
Replaces `dhcpalloc.DHCPRange` and will be used in upcoming OVN networks.
Removes dependency on dnsmasq specific `dnsmasq/dhcpalloc` package in network common and interface.
=> Network: Adds shared IPRange struct

lxd/seccomp/seccomp.go
No more than the current limit of 1 million instructions aka 8 mb and no more
than a 4096 byte log buffer.
Reported-by: Alban Crequy <alban.crequy@gmail.com>
=> seccomp: cap instruction limit and log buffer to reasonable sizes

lxd/apparmor/instance.go, lxd/apparmor/instance_lxc.go
=> lxd/apparmor: Disable cgroup2 on legacy hosts

doc/api-extensions.md, doc/networks.md, doc/server.md, lxd/cluster/config.go, lxd/db/networks.go, lxd/device/device_load.go, lxd/device/nic_ovn.go, lxd/device/nictype/nictype.go, lxd/network/driver_bridge.go, lxd/network/driver_ovn.go, lxd/network/network_load.go, lxd/network/network_utils.go, lxd/network/network_utils_test.go, lxd/network/openvswitch/ovn.go, lxd/network/openvswitch/ovs.go, lxd/networks.go, scripts/bash/lxd-client, shared/version/api.go
This PR adds the `ovn` network type and the associated `ovn` NIC device type.
It provides the ability to setup an OVN logical network and connect it (via SNAT) to a parent LXD managed bridge.
Install the OVN tools and configure the OVN integration bridge on the local node:
```
apt install ovn-host ovn-central
ovs-vsctl set open_vswitch . \
external_ids:ovn-remote=unix:/var/run/ovn/ovnsb_db.sock \
external_ids:ovn-encap-type=geneve \
external_ids:ovn-encap-ip=n.n.n.n \ # The IP of your LXD host on the LAN
```
Create an OVN network and an instance using it:
```
lxc network create ovntest --type=ovn parent=lxdbr0
lxc init images:ubuntu/focal c1
lxc config device override c1 eth0 network=ovntest
lxc start c1
lxc ls
+------+---------+---------------------+--------------------------------------- …
```
=> Network: OVN

lxd/db/networks.go, lxd/network/driver_ovn.go
- Aims to prevent concurrent OVN network creation from allocating the same IP on the parent network by using transactions. 
- Relies on the sqlite snapshot behaviour in WAL mode to detect if a the IP info of other networks has changed when writing the allocated IP back to the database.
- Adds `GetNonPendingNetworks` and `UpdateNetwork` to `ClusterTx` type so that all network related queries can be done inside a transaction.
- Updates `setupParentPortBridge` to start a transaction and pass it to its associated functions.
=> Network: OVN use DB transactions when allocating external IP on parent network

lxd/db/networks.go
To avoid returning pending networks with null description, which is causing problems when creating clustered OVN networks.
=> Network: Populate description col with empty string in CreatePendingNetwork

doc/networks.md, lxd/device/nic.go, lxd/device/nic_ovn.go, lxd/network/driver_bridge.go, lxd/network/driver_common.go, lxd/network/driver_macvlan.go, lxd/network/driver_ovn.go, lxd/network/driver_sriov.go, lxd/network/network_utils.go, lxd/network/network_utils_ovn.go, lxd/network/openvswitch/ovn.go, lxd/networks.go, shared/validate/validate.go
Adds `bridge.mtu` setting for OVN networks and defaults it to `1442` to allow normal network operation to work when using host<->host geneve tunnels. Propagates this setting into the OVN DHCP and IPv6 RA options and into the per-device NIC devices.
Also fixes OVS uplink bridge and port cleanup in clustered environment when network is deleted.
=> Network: OVN MTU

doc/networks.md, lxd/network/driver_ovn.go, lxd/network/network_utils.go
To trigger parent bridge gateway MAC learning.
=> Network: Ping OVN router's external IPv6 address on startup

lxd/db/instances.go
This fixes an issue when:
- Two storage pools
- Two projects
- Instance called `c1` is created in first project and storage pool
- Instance called `c1` is created in second project and storage pool
This breaks because this function returns the name of the first storage pool for the second container.
=> Storage: Ensure correct pool name is returned in GetInstancePool

lxd/apparmor/network_dnsmasq.go, lxd/apparmor/network_forkdns.go
man apparmor.d(5):
>    Globbing
>        File resources may be specified with a globbing syntax similar to that used by popular shells, such as csh(1), bash(1), zsh(1).
> 
>        *   can substitute for any number of characters, excepting '/'
This means `/snap/lxd/*/` covers `/snap/lxd/current/`.
=> Apparmor redux

doc/security.md
=> doc/security: Adds note about non-IP ethernet frame filtering to stop VLAN QinQ bypass

lxc/remote.go, lxd-agent/main_agent.go, lxd-p2c/utils.go, lxd/device/device_utils_proxy.go, lxd/main_init.go, lxd/main_init_auto.go, lxd/main_init_interactive.go, lxd/util/http.go, lxd/util/net.go, lxd/vsock/vsock.go, shared/util.go
- Further improves upon https://github.com/lxc/lxd/pull/7796/commits/6f3bd86122b84ef64b5cc2c4c6662a8afe942aee by using the canonical address (including port) for comparison rather than just the requested listen IP, as in the default case the existing listen socket was not detected and failed `lxd init`.
- Uses `CanonicalNetworkAddressFromAddressAndPort` rather than manual `fmt.Sprintf`, to make explicit which address types we accept.
- Converts `shared.DefaultPort` to an int, and replaces some internal usage of hardcoded "8443" with it.
=> Network: Use CanonicalNetworkAddressFromAddressAndPort rather than manual fmt.Sprintf

lxd/storage/backend_lxd.go
This is needed as QEMU will normally acquire a lock on the block device
backing the instance, preventing any further reader/writer to it.
Closes #7745
=> lxd/storage: Refuse BLOCK_AND_RSYNC with running instance

lxd/api_cluster.go
With the intention of removing the old pre-clustering_join approach.
=> Cluster: Makes ServerAddress field required for clusterPutJoin

lxd/api.go, lxd/api_cluster.go, lxd/cluster/connect.go, lxd/init.go, lxd/main_init.go, lxd/network/driver_bridge.go, lxd/network/driver_common.go, lxd/network/driver_macvlan.go, lxd/network/driver_ovn.go, lxd/network/driver_sriov.go, lxd/network/network_interface.go, lxd/networks.go
When a node joins a cluster that has an OVN network, the join process requires that the local storage pools and networks are created on the joining node (both in the local database and any host-side setup, such as creating network interfaces) before joining the cluster.
For networks this is achieved by calling the `n.Create()` followed by the `n.Start()` functions on the network driver.
However for OVN networks this causes a problem because whilst the `n.Start()` function is expected to be called on every node, the `n.Create()` function creates the logical network configuration in the remote OVN cluster's northbound database.
As we are joining an existing cluster it is expected that this logical configuration already exists in the OVN northbound database and as such the creation will fail …
=> Network: Adds support adding nodes to clusters that have OVN networks

lxd/daemon.go, lxd/db/instances.go, lxd/db/instances_test.go, lxd/db/storage_pools.go, lxd/db/storage_volumes.go, lxd/storage/drivers/load.go
Now that `StorageRemoteDriverNames()` is being used to generate frequently used DB queries, there is a cost implication to calling `SupportedDrivers()` when a particular driver isn't supported and the time taken to discover this is significant.
If a driver load fails then it (correctly) doesn't set its `loaded` boolean to true, meaning that the discovery process occurs on every call to `SupportedDrivers()` for every non-supported driver.
Instead we now cache (negatively - for unsupported drivers) the list of supported drivers, which in turn improves the performance of `StorageRemoteDriverNames()`.
This should fix the speed issues introduced with commits https://github.com/lxc/lxd/commit/d83e73d17b9a2b576ef436dc9bd8db319b8fe60e and …
=> Storage: Cache supported drivers

lxd/daemon.go, lxd/storage/drivers/driver_btrfs.go, lxd/storage/drivers/driver_ceph.go, lxd/storage/drivers/driver_cephfs.go, lxd/storage/drivers/driver_common.go, lxd/storage/drivers/driver_dir.go, lxd/storage/drivers/driver_lvm.go, lxd/storage/drivers/driver_zfs.go, lxd/storage/drivers/drivers_mock.go, lxd/storage/drivers/interface.go, lxd/storage/drivers/load.go
Hot on the heals of https://github.com/lxc/lxd/pull/7822 this PR removes the cache added in that last PR as the cache invalidation logic (when combined with the required locking) was getting complicated.
It occurred to me that the "is remote" property is a static property of the driver and not related to the version probing.
So this PR decouples the two concepts and simplifies the `RemoteDriverNames` function.
=> Storage: Make remote driver list not depend on loading storage driver (and performing driver version inspection)

lxd/storage_volumes.go
Avoids wiping out the parent volume's volatile shift config and causing a subsequent additional shift on next usage.
Fixes #7831
=> Storage: Only apply config changes when restoring snapshot if non-nil config is supplied

lxd/network/driver_bridge.go
Avoids detecting the incorrect fan underlay address when /32 VIPs from the underlay subnet are added to a different interface than the underlay subnet is being used on.
Fixes https://discuss.linuxcontainers.org/t/delete-a-stopped-container-bring-down-the-fan-interface/8803
=> Network: Exclude /32 underlay addresses from fan overlay address generation

doc/api-extensions.md, doc/networks.md, lxd/device/device_utils_network.go, lxd/device/nic_bridged.go, lxd/device/nic_macvlan.go, lxd/device/nic_ovn.go, lxd/device/nic_p2p.go, lxd/device/nic_routed.go, lxd/network/driver_bridge.go, lxd/network/driver_common.go, lxd/network/driver_ovn.go, lxd/network/network_interface.go, lxd/network/network_utils.go, shared/version/api.go
This PR introduces the `ovn.ovs_bridge` bridge network setting. It is used by OVN networks that specify the bridge network as its parent `network` in order to create an OVS uplink bridge using the setting's name (and as a name prefix for the associated veth interfaces). 
This is being introduced to work around an issue when joining an node to an existing cluster that has an OVN network, because previously the internal DB network row ID was used as part of the OVS bridge name. However this caused issues during the pre-join phase because potentially a different local network ID would be used to create the OVS bridge than is used in the rest of the cluster.
This removes the use of internal DB IDs for interface names and uses config setting instead, which will be used in the pre-join phase of …
=> Network: Adds ovn.ovs_bridge setting to bridge networks to specify OVS uplink bridge name for OVN networks

lxd/instance/drivers/driver_lxc.go, lxd/instance/drivers/driver_qemu.go
Also makes error logging and returned error messages consistent between lxc and qemu.
=> Instance: Fixes crash when removing device that cant be loaded

doc/api-extensions.md, doc/networks.md, lxd/network/driver_ovn.go, lxd/network/openvswitch/ovn.go, shared/version/api.go
- During cluster pre-join the local node's database row IDs can be different than the actual cluster row IDs.
- This can cause inconsistencies when adding local OVS chassis IDs to OVN logical HA chassis groups as part of network start.
- Makes the original OVN logical network name (derived from original database row ID) available during pre-join phase.
- Modifies parent network's `ovn.ovs_bridge` value to also be derived from original parent network's row ID.
- Re-arranges parent port setup to perform all DB modifications in single transaction.
- Adds and deletes local OVS chassis entry from OVN chassis group on network start/stop.
=> Network: Adds ovn.name setting to allow chassis group add during cluster pre-join phase

lxd/instance/drivers/driver_qemu_templates.go
Despite max and host supposedly being equivalent when in KVM mode, on a
limited number of platforms, host fails to fallback to 2 when no kernel
irqchip support is detected whereas max will properly select 2 in such
cases.
=> lxd/drivers/qemu: Use gic-version=max on aarch64

lxd/db/cluster/update.go, lxd/db/cluster/update_test.go
Might help with #7857, although I'm not sure since we don't have the database tarball yet.
In any case, this change seems to make sense regardless, since strictly speaking the `SELECT *` in the patch is not guaranteed to return columns in a specific order, and the `description` column doesn't have a `NOT NULL` constraint, so we need to coalesce it.
=> db: Handle NULL storage_volume description column in patch 34

lxd/storage/drivers/utils.go
=> Storage: Corrects argument order of mkfs in makeFSType for wider compatibility

doc/api-extensions.md, doc/networks.md, lxd/api_cluster.go, lxd/network/driver_bridge.go, lxd/network/driver_ovn.go, lxd/networks.go, shared/version/api.go
When joining a node to a cluster, there is a "pre-join" phase where the joining node is asked to create each network locally so that its config will match the existing cluster's when it asks to join.
This is achieved by calling `doNetworksCreate()` on the local node, which in turn calls the `n.Start()` function to start the network once it has been created in the local database.
Unfortunately this is causing problems with both `bridge` and `ovn` network types as they both rely on cluster state to start up correctly, and this "pre-join" phase start up is leaving the networks in an inconsistent state on the joining node.
For `bridge` networks the recently added stable random MAC address for the bridge interface itself is derived from the cluster's certificate when in cluster mode. During …
=> Network: Reverts ovn.name and ovn.ovs_bridge settings and defers network start until after cluster pre-join phase

lxc/main_aliases.go
This allows things like:
- lxc --project=blah shell abc
- lxc --debug shell abc
Not that it aliases cannot support leading flags with value separated by
spaces as the alias handling logic does not know what flag is a boolean
and what flag takes a value.
As a result, use `lxc --project=blah shell` and not `lxc --project blah shell`
as the latter cannot work and will lead to a confusing error.
Closes #7625
=> lxc: Better handle arguments

lxd/util/sys.go
During development I noticed that a long running lxd process would fail to start a VM after the underlying lxd binary had changed with the error:
```
lxc start v1
Error: Failed to run: apparmor_parser -rWL /var/lib/lxd/security/apparmor/cache /var/lib/lxd/security/apparmor/profiles/lxd-v1: AppArmor parser error for /var/lib/lxd/security/apparmor/profiles/lxd-v1 in /var/lib/lxd/security/apparmor/profiles/lxd-v1 at line 41: syntax error, unexpected TOK_OPENPAREN, expecting TOK_MODE
```
I found this was due to the aa profile exec path variable containing " (deleted)" at the end. 
=> AppArmor: Fix invalid aa profile generation when lxd binary has changed/gone

lxd/daemon_images.go, lxd/db/images.go, lxd/db/images_test.go, lxd/instance.go, test/suites/clustering.sh
This PR fixes an issue reported at https://discuss.linuxcontainers.org/t/cannot-launch-container-in-a-project-on-ubuntu-20-04-cluster/8744 where if an image is initially download into a project and then the next instance created is on a different node AND a different project then the image wouldn't be transferred from the first node and instance creation would fail.
=> Images: Handle downloading images from other cluster nodes across projects

scripts/bash/lxd-client
`_lxd_names()` already made use of list --format=csv so use it consistently for other functions.
While in there, add proper regex grouping to prevent `lxc start <tab>` from matching on container having "STOPPED" in their name.
=> Bash completion

lxd/network/driver_bridge.go
Fixes issue https://discuss.linuxcontainers.org/t/lxd-container-stuck-in-running-without-ip-address/8973 caused by https://github.com/lxc/lxd/pull/7833 whilst also not regressing https://discuss.linuxcontainers.org/t/delete-a-stopped-container-bring-down-the-fan-interface/8803
=> Network: Skip lo interface addresses when deriving a fan overlay address

lxd/apparmor/instance_forkproxy.go
=> lxd/apparmor: Allow unix sockets binding

lxd/network/driver_ovn.go
=> Network: Improve error message when parent 'network' option not specified for OVN networks

lxd/backup.go, lxd/backup/backup.go, lxd/instance_backup.go, lxd/instances_post.go, lxd/patches.go, lxd/storage/drivers/driver_btrfs_volumes.go, lxd/storage/drivers/driver_zfs_volumes.go, lxd/sys/fs.go
This is to accommodate custom future custom volume backups that will go in `shared.VarPath("backups", "custom")` without conflict.
=> Instance: Moves backups from shared.VarPath("backups") to  shared.VarPath("backups", "instances")

lxd/db/errors.go, lxd/main_init_interactive.go, lxd/network/driver_bridge.go, lxd/network/driver_common.go, lxd/network/driver_macvlan.go, lxd/network/driver_ovn.go, lxd/network/driver_sriov.go, lxd/network/network_interface.go, lxd/network/network_load.go, lxd/networks.go
- Removes network loader helpers that don't require a DB record and replace it with a generic `LoadByType` that returns an interface that is safe to use without a DB record.
- Adds `DBType()` and `Type()` functions to each network driver.
- Adds `NodeSpecificConfig` flag to driver `Info` type indicating whether the network driver supports per-node cluster config.
- Updates network creation to populate "pending" network node entries automatically when network driver doesn't support per-node cluster config, to avoid needing to specify `--target` when creating a network of that type.
- Fixes dependent network start order, so that networks specifying another network always start after their parent.
=> Network: Don't require --target arg when adding networks in a cluster that don't require per-node config 

lxd/db/instances.go, lxd/project/permissions.go, lxd/project/permissions_test.go
To avoid unexpectedly only filtering for container types.
Fixes #7897
=> lxd: Ensure all use of db.InstanceFilter defines instance type

doc/storage.md
Just a minor fix. In the bash examples you should not escape the underscores.
=> doc/storage: no need to escape underscore in bash examples

lxd/device/device_utils_network.go, lxd/device/nic_ovn.go, lxd/network/driver_ovn.go, lxd/network/network_utils.go, lxd/network/network_utils_ovn.go, lxd/network/openvswitch/ovs.go, shared/validate/validate.go
- Auto generates `bridge.mtu` setting for OVN networks if not specified (on create and update).
- Bridge MTU setting is derived from OVN's underlay network's `ovn-encap-ip`, which is used to ascertain the underlay network interface's MTU and IP address family (which both influence the maximum MTU size that can be used without fragmentation in the overlay network due to geneve tunnel overhead).
=> Network: Adds optimal MTU detection for bridge.mtu setting based on OVN's underlay MTU and address family

lxd/networks.go
Checks that non-admin users have the `manage-networks` RBAC permission before allowing access to API routes that create/modify networks.
=> Network: Enforce RBAC permission manage-networks for managing networks

lxd/networks.go
Fixes single node OVN network creation.
=> network: Only add pseudo pending node records when in cluster in networksPost

lxc/network.go, lxd/networks.go
If non-default network project in use, and network type not specified by user, default to `ovn` type. Otherwise default to `bridge` type.
=> Network: Pick default network type based on project

lxd/cgroup/init.go
This fixes swappiness on CgroupV1.
CGroupV2 support is still missing though.
Closes #7916
=> lxd/cgroup: Fix memory.swappiness detection

lxd/instance_post.go
Without this, the notification to create the mountpath is incorrectly
received for the default project.
=> lxd/instances: Fix ceph cluster target move

lxd/backup.go, lxd/backup/backup_info.go, lxd/backup/backup_instance.go, lxd/backup/backup_utils.go, lxd/db/backups.go, lxd/db/storage_volumes.go, lxd/instance.go, lxd/storage/drivers/driver_btrfs_utils.go, lxd/storage/drivers/driver_btrfs_volumes.go, lxd/storage/drivers/driver_zfs_volumes.go, lxd/storage/drivers/generic_vfs.go
- To allow for custom volume backups in future.
- Fixes removal of instance backup parent directory when instance is renamed.
- And various other small tweaks that are not directly related to custom volume backups.
=> Backup: Change Type field type in index.yaml to own backup.Type

lxd/cluster/membership.go
Currently, the output of `lxc cluster list` appears with the following status message when a node is offline:
(written out, this is "no heartbeat since" followed by a countup timer.)
This commit changes "since" to "for" (a grammatical fix).
Signed-off-by: Adam Bell <adam.bell@canonical.com>
=> lxd/cluster: Changing "no heartbeat" language in membership.go

lxd/daemon_storage.go
The config key is node-local, so as long as a different volume is used
per server, this is perfectly fine to use.
=> lxd/storage: Allow ceph/cephfs for images/backups

lxd/device/config/devices.go, lxd/device/config/devices_utils.go, lxd/instance/drivers/driver_lxc.go, lxd/instance/drivers/driver_qemu.go, lxd/instance/drivers/qmp/monitor.go
- Cleans up VM Update() to remove duplicated logic and reject device config changes when running.
- Adds support for shrinking the memory limit of VM (when hugepages are not being used) using `lxc config set limits.memory`.
- Fixes detection of all updated device keys which triggers a MAAS update.
=> VM: Add support for live shrinking of limits.memory

doc/networks.md, lxd/device/nic_ovn.go, lxd/network/driver_ovn.go, lxd/network/openvswitch/ovn.go
- Allows OVN networks to enable `ipv6.dhcp.stateful` and allows OVN NICs to specify `ipv6.address` statically.
- Allows OVN NICs to specify `ipv4.address` statically.
=> Network: Adds DHCPv6 stateful support

lxd/device/device_interface.go, lxd/device/nic_bridged.go, lxd/device/nic_ovn.go, lxd/instance/drivers/driver_qemu.go, lxd/network/driver_ovn.go, lxd/network/network_utils_ovn.go, lxd/network/openvswitch/ovn.go
- Adds `device.NICState` interface for detecting and retrieving NIC state from devices that support it.
- Updates `qemu.RenderState()` to use the `NICState` interface.
- Implements the `NICState` interface on `bridged` NIC type.
=> Network: OVN NIC fallback state info

lxd/instance/drivers/driver_qemu.go
This PR should help detect scenarios such as those in https://github.com/lxc/lxd/issues/7962 where the QMP monitor isn't reachable, but the qemu process is still running. 
The way I've simulated this is to start a VM, then remove the qmp socket file, and restart lxd so that it cannot open a monitor connection. This simulates a broken/unreachable qemu process.
Fixes https://github.com/lxc/lxd/issues/7962
=> VM: Detect broken/hung qemu process and reflect in LXD state output

lxd/apparmor/network_dnsmasq.go
=> lxd/apparmor: Allow access to zoneinfo files

lxd/device/nic_bridged.go, lxd/network/network_utils.go
Improves bridged NIC IP detection & guessing when the actual instance IP data cannot be retrieved from inside the container or VM.
- Only tries to parse dnsmasq leases file if parent network is managed.
- If parent is managed and has stateless IPv6 then guess NIC's IPv6 address using EUI64.
- If parent network is not managed, no longer treat this as complete failure.
- Try and find IP addresses from IP neighbour cache using network.GetNeighbourAddresses.
- Load interface MTU using NIC's `host_name` rather than parent interface (should be the same but more consistent with how OVN NIC does it).
- Also means that if the NIC's host veth interface is missing, then this call will not return any results.
- If interface is available, will return interface stats even with no IPs found.
- Guess …
=> Network: Add EUI64 guessing for bridged NIC state

shared/simplestreams/simplestreams.go
Since commit aef8f1928 ("shared/simplestreams: Implement caching support")
the index url contains double '/' between the host part and the path part,
so the resulting url looks like:
https://STREAMSERVER//streams/v1/index.json
Certain servers will literaly take '/streams/v1/index.json' as the path,
and therefore return 404 or 403.
Fix parseStream(), by removing the prepended '/' passed to
s.cachedDownload().
Signed-off-by: Shmulik Ladkani <shmulik.ladkani@gmail.com>
=> shared/simplestreams: Fix stream's index download url

shared/cmd/ask.go
fixes #7944 
Signed-off-by: Jose R. Gonzalez <josegonzalez89@gmail.com>
**Summary**
When initializing using `lxd init`, don't allow for a user to initialize a cluster with an empty password if password authentication is enabled.
**Change Description**
- Updated `AskPassword()` to ensure that checking for empty input from the user will result in a call to `invalidInput()`
- Updated `AskPasswordOnce()` to do the same check, which required putting it into a `for` loop (previously it did not have any validation). I also converted it to a string one line earlier so that the length check matches what was done in `AskPassword()`.
Thanks for participating in Hacktoberfest!
=> Prevent empty passwords during init if password authentication is enabled

doc/index.md
Since we don't ship our own anymore.
Closes #7978
=> doc/index: Add libsqlite3-dev back to dependencies

lxd/apparmor/apparmor.go, lxd/dnsmasq/dnsmasq.go, lxd/firewall/drivers/drivers_nftables.go, lxd/rsync/rsync.go, shared/version/version.go
Instead of using NewDottedVersion(), use Parse() which can handle
version strings containing suffixes, e.g. "3.0.0-beta1" or similar.
=> Use Parse when parsing versions from external tools

lxd/network/driver_ovn.go, lxd/network/openvswitch/ovn.go, shared/validate/validate.go
- Adds support for multiple upstream DNS servers in OVN networks using the `dns.nameservers` setting that will be supported in `physical` and `sriov` uplink network types.
- Adds detection of `ipv4.gateway` and `ipv6.gateway` OVN uplink network settings that will be supported in `physical` and `sriov` uplink network types.
=> network: Adds support for multiple upstream DNS servers in OVN networks

lxd/daemon_images.go
This fixes a crash happening when all of those conditions are met:
- Clustered environment
- Image is downloaded using the LXD protocol
- Source image is marked as private
- Image was downloaded previously to the cluster
- The server processing the download doesn't have the image
=> lxd/images: Fix crash when no "info" struct

doc/api-extensions.md, doc/networks.md, lxd/db/networks.go, lxd/device/device_utils_network.go, lxd/device/infiniband_physical.go, lxd/device/infiniband_sriov.go, lxd/device/nic_bridged.go, lxd/device/nic_macvlan.go, lxd/device/nic_ovn.go, lxd/device/nic_p2p.go, lxd/device/nic_physical.go, lxd/device/nic_sriov.go, lxd/network/driver_bridge.go, lxd/network/driver_macvlan.go, lxd/network/driver_ovn.go, lxd/network/driver_physical.go, lxd/network/driver_sriov.go, lxd/network/network_load.go, lxd/network/network_utils.go, lxd/util/net.go, shared/validate/validate.go, shared/version/api.go
- Adds `physical` network type.
- Updates `ovn` networks to allow the use of a `physical` network as an uplink network.
- Updates `ovn`network's veth uplink interconnect to inherit parent network's `bridge.mtu` setting when used with a `bridge` network.
=> network: Adds physical network type and adds OVN support for using it as an uplink

lxc-to-lxd/main_migrate.go
This should let us come up with a proper fix for https://github.com/lxc/lxd/issues/8004
=> lxc-to-lxd: Handle snap better

lxd/dnsmasq/dnsmasq.go
Otherwise trying to immediately start dnsmasq again can result in socket binding errors.
=> dnsmasq: Adds 100ms sleep to successful Kill() to allow sockets to be released by OS

lxd/device/disk.go, lxd/instance/drivers/driver_qemu.go
- Moves check for preventing update of devices when VM is running into updateDevices().
- Fixes regression introduced by 6697599#diff-8ac4860b5f669c17c92c37545fe2ecfd.
- Removes 1 call to IsRunning() by passing into updateDevices() from Update().
=> VM: Fixes disk resize regression

lxd/storage/drivers/driver_lvm.go
Discussed here https://discuss.linuxcontainers.org/t/lvm-lxc-storage-delete-xxx-removes-lvm-volumegroup-by-default/9143
=> Storage: Don't remove empty LVM thinpool and volume group if lvm.vg.force_reuse enabled

doc/api-extensions.md, doc/networks.md, lxd/device/nic_ovn.go, lxd/network/driver_common.go, lxd/network/driver_ovn.go, shared/validate/validate.go
- Ensures consistent use of uplink terminology rather than parent in docs and code.
- Adds new validators for forthcoming restricted subnets feature
- Bans colon char from network name.
=> Network: OVN uplink terminology

lxd/main_forksyscall.go
Somehow the compiler didn't detect that we called a non-existing function.
=> forksyscall: use correct function

shared/simplestreams/simplestreams.go
* use time.Since() instead of time.Now().Sub() for readability
* entry.Name is already string type, no need for fmt.Sprintf
* remove unneeded for-loop in getImages()
=> simplestreams.go: remove unneeded fmt.Sprintf and simplify getImages()

lxd/network/driver_bridge.go
Normal bridge (and docs) say if unset, the default is false, however the fan bridge was defaulting to true if unset.
=> Network: Fixes inconsistency between normal bridge and fan bridge default ipv4.nat value

doc/api-extensions.md, doc/networks.md, lxd/network/driver_ovn.go, lxd/patches.go, shared/version/api.go
These will be automatically added to new OVN networks when the associated IP address setting is being auto-generated.
Otherwise if these settings are missing then the default is to disable NAT.
=> network: Adds OVN ipv4.nat and ipv6.nat keys

lxd/device/nic_ovn.go, lxd/network/driver_ovn.go
Fixes an issue where if a static IPv4 address was set for a NIC using ipv4.address, as OVN does not allow a mixture of static and dynamic IPs on a port, this would prevent a dynamic IPv6 address from being added to the port, which in turn prevented a DNS name from being created. 
We now populate the logical port with a static EUI64 address if only static IPv4 addresses are set, and IPv6 is enabled on the bridge.
=> Network: Generates EUI64 IPv6 DNS record for OVN NICs when static IPv4 address is defined

lxd/revert/revert.go
Use a single append to concatenate two slices
=> revert/revert.go: remove a for-loop from Clone() method

doc/networks.md, lxd/network/driver_ovn.go, lxd/network/openvswitch/ovn.go
- Adds validation for OVN network's subnet that checks whether it is within the allowed uplink and project networks when disabling NAT.
- Allows for instance IPs on OVN networks to be published to the external uplink network (when in no NAT mode).
=> Network: Adds support for external subnets for OVN networks

lxc/image.go
* Removed unneeded for-loop in lxc/copy.go
=> lxc/copy.go: Remove unneeded for-loop in c.Run()

lxd/network/driver_ovn.go
=> Network: Only call Validate in OVN's FillConfig if state is set

doc/instances.md
- Adds explanation of `network` property.
- Removes `nictype` prefix on each NIC device type section (to avoid confusion when a NIC can be specified using both `nictype` and `network).
- Adds `Managed` column for `bridged` NIC type.
- Re-formats additional info section at bottom.
- Re-orders device order to match current master.
- Adds "Selected by" section to each NIC type.
- Removes unnecessary white space in columns.
=> Doc: Re-organises NIC device type docs introducing section about network property

lxd/instance.go, lxd/instance/drivers/driver_lxc.go, lxd/instance/drivers/driver_qemu.go, lxd/instance_logs.go
I noticed this issue whilst working on OVN CI tests.
The reproducer was:
```
lxc launch images:ubuntu/focal c1 --project default
lxc exec c1 -- whoami --project default # Succeeds
lxc init images:ubuntu/focal c1 --project test
lxc exec c1 -- whoami --project default # Fails. Because the /var/log/lxd/c1/lxc.conf was removed when creating c1 in test project.
```
Further inspection revealed several issues with the use of `shared.LogPath()` function when in a project context.
=> Instance: Fix a class of bugs related to incorrect log path generation when instance is in non-default project

doc/networks.md, lxd/network/driver_bridge.go, lxd/patches.go
Fixes an issue introduced by https://github.com/lxc/lxd/pull/8037 where fan bridges do not have `ipv4.nat` setting by default which broke external connectivity.
=> Network: Sets ipv4.nat=true by default for new fan bridges and adds the setting if missing to existing fan bridges

lxd/device/config/devices_sort.go, lxd/instance/drivers/driver_lxc.go, lxd/instance/drivers/driver_qemu.go, lxd/storage/backend_lxd.go, lxd/storage/drivers/driver_btrfs_volumes.go, lxd/storage/drivers/driver_ceph_volumes.go, lxd/storage/drivers/driver_cephfs_volumes.go, lxd/storage/drivers/driver_dir_volumes.go, lxd/storage/drivers/driver_lvm_volumes.go, lxd/storage/drivers/driver_zfs_volumes.go, lxd/storage/drivers/drivers_mock.go, lxd/storage/drivers/generic_vfs.go, lxd/storage/drivers/interface.go, lxd/storage/drivers/utils.go, lxd/storage/drivers/volume.go
This is to accommodate TPM devices (https://github.com/lxc/lxd/pull/8041) that need to write their state to the instance's root/config volume during start.
- Mount instance volume before starting devices.
- Adds ability to prevent block backed storage drivers from deactivating their block device when unmounting (allows the block device to be left for `UnmountTask()` used when shrinking filesystems that need to be unmounted first).
- Previously this was implicit and relied upon the volume not being mounted to avoid block device deactivation (which is now not the case when doing pre-start disk shrinking after initial mount).
- Modifies device start order to ensure `disk` type devices are started between `nic` types and other types. This ensures that (with the exception of `nic` types) other …
=> Instance: Mount instance volume before devices start

lxd/cluster/connect.go, lxd/db/storage_volumes.go, lxd/response.go, lxd/storage_volumes.go, lxd/storage_volumes_backup.go, lxd/storage_volumes_snapshot.go
Was previously hard coded to default, but custom volumes can support projects now.
=> Storage: Fixes forwarded response if volume is remote to support projects

lxc/delete.go, lxc/move.go
=> lxc/move: Bypass security.protection.delete

lxd/instance/drivers/driver_lxc.go, lxd/instance/drivers/driver_qemu.go
Fixes #8071
Tested using dir and btrfs backends using `lxd import` after renaming a container before starting and then removing the database.
=> Instance: Write out updated backup.yaml after rename

lxd/device/nic_ovn.go, lxd/network/driver_ovn.go, lxd/project/project.go, lxd/storage/utils.go
This PR adds validation of OVN NIC external routes (`ipv4.routes.external` and `ipv6.routes.external`) settings to check they do not overlap with any other OVN NICs that are connected to networks that use the same uplink, and that they do not overlap with any OVN networks (including the OVN network the OVN NIC we are validating is connected to) that use external subnets and also use the same uplink.
=> Network: OVN NIC external route overlap validation

lxd/device/nic_sriov.go
We've seen some systems where the driver is in an inconsistent state
briefly and returns EBUSY, effectively needing a retry.
So let's just assume that this may happen on any VF reconfig and wrap
everything with TryRunCommand.
=> lxd/device/sriov: Harden calls to ip link vf

lxd/instance/drivers/qmp/monitor.go
VMs tend to have events every few seconds, as a result the timeout was
never hit and the agent never detected.
=> lxd/qmp: Ensure checkbuffer is called

lxd/instance/drivers/driver_lxc.go, lxd/instance/drivers/driver_qemu.go
- Detect when instance being mounted is snapshot and call `MountInstanceSnapshot` on pool.
- Unify the mount behaviour when restoring snapshot for both LXC and Qemu.
=> VM: Call MountInstanceSnapshot when mounting vm snapshots

lxd/instance.go, lxd/instance/drivers/driver_lxc.go, lxd/instance/drivers/driver_qemu.go, lxd/patches.go, lxd/storage/backend_lxd.go, lxd/storage/backend_mock.go, lxd/storage/drivers/driver_ceph_utils.go, lxd/storage/drivers/driver_ceph_volumes.go, lxd/storage/drivers/driver_zfs_volumes.go, lxd/storage/drivers/generic_vfs.go, lxd/storage/drivers/volume.go, lxd/storage/pool_interface.go, lxd/storage/utils.go
Fixes #8114 
- Moves responsibility for resizing/regenerating an existing cached image volume from `CreateInstanceFromImage` to `EnsureImage`.
- Updates `CreateInstanceFromImage` to create a one-off non-optimized instance volume when the existing cached image volume is larger than the instance's root disk device and cannot be shrunk.
=> Storage: Allow instances to be created with root disks smaller than pool's cached image volume

lxd/storage/backend_lxd.go, lxd/storage/utils.go
- Updates `EnsureImage` to take into account existing image volume's `volatile.rootfs.size` property when calculating the current size the volume should be. Avoids trying to shrink an existing volume that is larger than the default size when the pool doesn't have volume size limit.
- Improves comments in `CreateInstanceFromImage`.
=> Storage: EnsureImage and CreateInstanceFromImage improvements on size management

lxd/instance/drivers/driver_qemu.go
As we supply mebibytes to qemu for boot time memory size.
Fixes https://discuss.linuxcontainers.org/t/cpu-burst-windows-vm/8965/
=> VM: Converts all supplied memory byte values to mebibytes for comparison

lxc/storage_volume.go, lxd/cluster/connect.go, lxd/db/storage_volumes.go, lxd/db/storage_volumes_test.go, lxd/device/disk.go, lxd/patches.go, lxd/storage/backend_lxd.go, lxd/storage/drivers/driver_ceph_volumes.go, lxd/storage/drivers/generic_vfs.go, lxd/storage/utils.go, lxd/storage_volumes.go, lxd/storage_volumes_snapshot.go, lxd/storage_volumes_utils.go
Fixes issue with attaching volumes and resource usage when a volume exists on multiple cluster members, described on https://discuss.linuxcontainers.org/t/how-to-attach-a-storage-volume-with-the-same-name-defined-in-multiple-nodes-in-lxd-cluster/9387
It solves this by passing in the `api.StorageVolume` struct into `storagePools.VolumeUsedByInstances` and then modifying `VolumeUsedByInstances` to use the `Location` field in the `StorageVolume` supplied to decide whether the volume is local to the specific cluster member or available on all. If it is only available on the local cluster member then it will filter the instance list to only include instances on that node.
This PR also replaces `GetStorageVolumeNodeAddresses` with `GetStorageVolumeNodes` which returns a list of `db.NodeInfo` …
=> Storage: Fix custom volume attach and resource usage reporting when volumes exist on multiple nodes

lxd/cluster/connect.go, lxd/db/instances.go, lxd/device/disk.go, lxd/instance/drivers/driver_lxc.go, lxd/storage/backend_lxd.go, lxd/storage/utils.go, lxd/storage_volumes.go, lxd/storage_volumes_utils.go
- Fixes profile and instance device config update on custom volume rename & move.
- As part of that, makes custom volume used by profile detection support projects and storage pools.
Continues fixing issues related to those described in:
- https://discuss.linuxcontainers.org/t/how-to-attach-a-storage-volume-with-the-same-name-defined-in-multiple-nodes-in-lxd-cluster/9387
- https://github.com/lxc/lxd/pull/8125
=> Storage: Further bug fixes in relation to volume used by detection

lxd/device/disk.go, lxd/instance/drivers/driver_lxc.go
Avoid disk device cleanup issues due to container mounts still being active.
=> Container: Stop non-NIC devices after container fully stopped

lxd/apparmor/instance_forkproxy.go
It appears that on some kernel at least, the connect operation is
evaluated against the non-dereference path when dealing with a symlink.
=> lxd/apparmor: Workaround socket handling

lxd/instance.go, lxd/storage/backend_lxd.go
Don't post-set volume size after volume creation, rely on correct device size being available at volume creation time.
Avoids subtle differences in sizes between the actual block volume size sent in migration header and size in instance disk config.
Fixes https://github.com/lxc/lxd/issues/8112
=> Storage: Remove instance configure internal function

lxd/cgroup/abstraction.go, lxd/cgroup/cgroup_cpu.go, lxd/instance/drivers/driver_lxc.go
This gets us CPU weight and CPU max limits, at which point the only two things missing are:
- swappiness
- net_prio
Both of which aren't currently supported in the kernel and are reported by LXD on startup, everything else is functional and tested.
=> Final bits of CGroupV2 support

lxd-agent/main_agent.go
=> lxd-agent: Don't allow connections when rebooting

lxd/api_project.go
This is because some storage drivers cannot support quotes in the volume name.
Also AppArmor policies do not support double quotes in their names.
=> Project: Reject quotes in project names

lxd/api_internal.go, lxd/instance/drivers/driver_lxc.go, lxd/main_callhook.go
This change ensures that if the instance ID changes while it is running (which can happen if one performs an `lxd import` over the top of a running container) that the container's stop hooks will still be able to find the instance by name and be able to cleanly shutdown.
The start hook is also updated for consistency with the others.
All 3 hooks still handle being passed instance ID in order to allow clean shutdown of instances started before this change.
=> Container: Pass name rather than ID to LXC start, stopns and stop hooks

doc/instances.md, lxd/instance/drivers/driver_lxc.go, lxd/instance/drivers/driver_qemu.go, lxd/patches.go, shared/instance.go, shared/validate/validate.go
- Tested patch on running VMs with the `volatile.vm.uuid` key with and without snapshots to check they all get renamed.
=> Instance: Adds volatile.uuid key for container and VMs, replaces volatile.vm.uuid for VMs

lxd/instance/drivers/driver_lxc.go
Don't attempt to call the function if we don't have the runtime extension.
Closes #8159
=> lxd/instance/lxc: Add extra check for devpts_fd

lxd/device/nic_sriov.go
Apparently the bnx2x devices don't allow this.
Fixes #8162
=> Network: Don't fail when resetting SRIOV VF MAC to 00:00:00:00:00:00

lxd/device/nic_ovn.go, lxd/network/driver_ovn.go, lxd/network/openvswitch/ovs.go
- Switches new OVN instance port names to use the instance's UUID setting rather than the instance's ID property.
- This is because the instance's ID property can change if the instance is recovered using `lxd import` while it is still running.
- This has the knock on effect that when the running instance is eventually stopped, its OVN logical switch port is not cleaned up as the ID has changed (and it is left in the OVN NB database).
- Using the `volatile.uuid` setting ensures that it will remain the same between recoveries.
However this introduces a related problem. What about instances that are already started and have an OVN port name containing the instance ID from the old regime. Once this change is applied, any running instance that is stopped will then also leave its OVN port …
=> Network: Use Instance UUID for generating OVN logical switch port names

lxd/api_cluster.go, lxd/api_project.go, lxd/db/cluster/schema.go, lxd/db/cluster/update.go, lxd/db/migration_test.go, lxd/db/networks.go, lxd/device/nic_bridged.go, lxd/device/nictype/nictype.go, lxd/network/driver_bridge.go, lxd/network/driver_common.go, lxd/network/driver_macvlan.go, lxd/network/driver_ovn.go, lxd/network/driver_physical.go, lxd/network/driver_sriov.go, lxd/network/network_interface.go, lxd/network/network_load.go, lxd/networks.go, lxd/patches.go, lxd/storage_pools.go, lxd/storage_pools_utils.go, test/suites/clustering.sh
- Adds state column to networks_nodes table.
- Modifies network create process to allow per-node state tracking.
- Allows fixing of per-node creation blockers when creating a network in a cluster.
Checks:
Related to https://github.com/lxc/lxd/issues/8111
=> Network: Adds network node state to improve clustered network creation process

lxd/instance.go, lxd/storage/backend_lxd.go, lxd/storage/drivers/driver_ceph_volumes.go, lxd/storage/drivers/driver_common.go, lxd/storage/drivers/driver_zfs_volumes.go
Allows unpacking of images larger than default volume size (while filler function itself still checks the storage pool's `volume.size` setting to ensure no additional restrictions set) into new image volumes (before potential read-only snapshot is taken).
Fixes https://discuss.linuxcontainers.org/t/widnows-vm-creation-from-image-error-increasing-volume-size/9552
=> Storage: Allow unsafe resize when filling initial image volume

lxd/instance/drivers/driver_qemu.go
For those few distros that use a symlink instead of the real thing.
Closes #8185
=> lxd/instance/qemu: Follow symlink to lxd-agent

doc/networks.md, lxd/network/driver_bridge.go, lxd/network/driver_ovn.go, test/suites/network.sh
This allows for `ipv4.address`, `ipv6.address` and `fan.underlay_subnet` settings to be removed and have the effect of "none" rather than "auto".
=> Network: Don't fill default config when doing an update

lxd/device/disk.go
Allows for migration of instances who have snapshots with invalid devices.
Fixes #8187
=> Device: Only validate disk source pool when an actual instance is set

lxc-to-lxd/main.go, lxc-to-lxd/main_migrate.go
Running lxc-to-lxd from a snap environment is tricky.
We can't just use the previous approach of resolving the main container
dir through HostPath as any included file will cause a config read
failure. We also can't just have the snap run the entire binary on the
host as the linker would fail on liblxc.
Instead, this approach lets the loader take care of the dynamic
libraries and we then attach to the host mount namespace and process the
rest from there.
=> lxc-to-lxd: Fix handling on snap

lxd/api_1.0.go, lxd/instance.go, lxd/instance/drivers/driver_lxc.go, lxd/instance/drivers/driver_qemu.go, lxd/instance/drivers/load.go, lxd/instance/instance_interface.go
As requested, this is a draft pull request for issue #7869, having implemented most of the things mentioned in the most recent comments.
As noted in the description of commit ead2141 the Info() function in driver_qemu.go isn't quite working yet, there's some runtime bugs that I haven't sorted out relating to finding the path of the qemu binary.
Additionally, there seems to be some kind of race condition in the creation of the driver cache, as either ``lxc`` or ``qemu`` can end up appearing first in the list, though I am unsure where this would be generated so it is not listed in any particular commit.
=> Report `qemu` driver with version in `/1.0`

lxd/backup.go, lxd/backup/backup_instance.go, lxd/backup/backup_utils.go, lxd/daemon.go, lxd/instance.go, lxd/instance/drivers/driver_common.go, lxd/instance/drivers/driver_lxc.go, lxd/instance/drivers/driver_qemu.go, lxd/network/driver_bridge.go, lxd/network/driver_common.go, lxd/network/driver_ovn.go, lxd/network/driver_physical.go, lxd/storage/drivers/generic_vfs.go
This implements consistent events for:
- instance-created
- instance-renamed
- instance-deleted
- instance-updated
- instance-started
- instance-stopped
- instance-shutdown
- instance-restarted
- instance-paused
- instance-resumed
- instance-snapshot-create
- instance-snapshot-renamed
- instance-snapshot-deleted
- instance-restored
- instance-backup-created (new)
- instance-backup-renamed (new)
- instance-backup-deleted (new)
- network-created (new)
- network-updated (new)
- network-renamed (new)
- network-deleted (new)
It also fixes the URLs to properly contain the project name when applicable.
The branch also has a couple of unrelated fixes:
- Fix for RBAC failure on clients that are not using RBAC (due to bad checks in the exception rules)
- Fix for a failure to rename VM snapshots on …
=> Lifecycle improvements

lxd/api.go, lxd/api_cluster.go, lxd/cluster/connect.go, lxd/cluster/request/clienttype.go, lxd/network/driver_bridge.go, lxd/network/driver_common.go, lxd/network/driver_macvlan.go, lxd/network/driver_ovn.go, lxd/network/driver_physical.go, lxd/network/driver_sriov.go, lxd/network/network_interface.go, lxd/networks.go
To avoid circular imports conflicts with storage package.
Related to https://github.com/lxc/lxd/pull/8205
=> Cluster: Moves ClientType, its constants and helper into own package

lxd/apparmor/instance_qemu.go
This allows NSS related files:
- nsswitch.conf
- passwd
- group
As well as /proc/version which QEMU apparently accesses sometimes.
=> lxd/apparmor/qemu: Allow some more files

lxd/storage/drivers/driver_zfs_volumes.go
This is caused because /dev/zvol appears to not be populated when using the snap.
=> Storage: Fixes 10s delay when using VMs with ZFS in snap

lxd/config/map.go, shared/util.go
Issue #7870 -- this allows configuration keys starting with `user.*` in server config (`lxc config`). In a cluster, `user.*` keys are replicated across the cluster.
=> Allow `user.*` keys everywhere we store configuration

lxc/storage.go, lxd/api_cluster.go, lxd/backup/backup_config.go, lxd/daemon_storage.go, lxd/db/migration_test.go, lxd/db/storage_pools.go, lxd/device/disk.go, lxd/instance_post.go, lxd/instances_post.go, lxd/patches.go, lxd/storage/backend_lxd.go, lxd/storage/backend_mock.go, lxd/storage/drivers/driver_ceph.go, lxd/storage/load.go, lxd/storage/pool_interface.go, lxd/storage_pools.go, lxd/storage_pools_utils.go, lxd/storage_volumes.go, lxd/storage_volumes_backup.go, lxd/storage_volumes_snapshot.go, shared/api/storage_pool.go, test/suites/clustering.sh
- Adds state column to `storage_pools_nodes` table.
- Modifies storage pool create process to allow per-node state tracking.
- Allows fixing of per-node creation blockers when creating a storage pool in a cluster.
Fixes https://github.com/lxc/lxd/issues/8111
Checks:
=> Storage: Adds storage node state to improve clustered creation process

lxd/storage/backend_lxd.go, lxd/storage/drivers/driver_btrfs_volumes.go, lxd/storage/drivers/utils.go, lxd/storage/utils.go
Fixes image block volume resize errors.
=> Storage: Allow BTRFS to detect volume.size pool changes and regeneration image volumes

lxd/rbac/server.go
The data from RBAC uses resource IDs not project names, so we need to
map things through r.resources.
=> lxd/rbac: Fix checks by matching proper name

lxd/instance.go, lxd/storage/backend_lxd.go, lxd/storage/drivers/driver_ceph_volumes.go, lxd/storage/drivers/driver_zfs_utils.go, lxd/storage/drivers/driver_zfs_volumes.go, lxd/storage/drivers/utils.go
Fixes issue when copying from ceph to zfs pools, the zfs volumes were being rounded to the nearest 8192 bytes, which sometimes meant the volume size created was just too small to accommodate the source ceph volume (which doesn't round to nearest 8192 bytes).
This modifies the ZFS volumes to round up to nearest 8192 bytes.
Also fixes a revert cleanup issue that prevented removing the errored instance record if the storage volume record was already gone.
Also fixes an issue in the Ceph driver that prevented deleting an image volume if the readonly snapshot didn't exist.
=> Storage: ZFS rounding up and Ceph image deletion improvements

doc/api-extensions.md, doc/networks.md, lxd/device/nic_ovn.go, lxd/network/driver_ovn.go, lxd/network/driver_physical.go, lxd/network/network_utils.go, shared/version/api.go
Adds `ovn.ingress_mode` (either `l2proxy` (default) or `routed`) to `physical` networks to allow OVN NICs to change the way they advertise their external IPs on the uplink network.
=> Network: OVN Ingress mode

doc/api-extensions.md, doc/networks.md, lxd/network/driver_ovn.go, lxd/network/driver_physical.go, shared/version/api.go
Adds `ipv4.routes.anycast` and `ipv6.routes.anycast` boolean settings for `physical` networks. Defaults to false.
Allows OVN networks using physical network as uplink to relax external subnet/route overlap detection when used
with `ovn.ingress_mode=routed`.
=> Network: Adds ipv4.routes.anycast and ipv6.routes.anycast settings to physical networks

lxd/network/driver_ovn.go
Fixes log message "No path for static route 0.0.0.0/0; next hop n.n.n.n" when creating/editing network.
Also only add default routes and SNAT rules if logical router has external IPs.
=> Network: Only add default route and SNAT rules to OVN router after adding external router port

lxd/network/driver_bridge.go, lxd/network/driver_common.go, lxd/network/driver_macvlan.go, lxd/network/driver_ovn.go, lxd/network/driver_physical.go, lxd/network/driver_sriov.go, lxd/network/network_interface.go, lxd/networks.go
- If a network was successfully "created" (using `n.Create()`) on a local node, but then failed to start (using `n.Start()`) then it was possible for setup done in `n.Create()` to be left behind because although `n.Delete()` was called on failure, the node status was still Pending and so the tear down was not performed.
- To cope with this, and to better align with storage pool state management, I've moved the DB record deletion and cluster notification logic into the API route handler function, leaving the network package's `Delete()` function to always tear down local setup.
- This allows the API route handler functions to decide for themselves (using `n.LocalStatus()`) whether it is appropriate to call `n.Delete()` depending on the scenario.
Example scenario:
1. Create `physical` …
=> Network: Improvements to clustering node state to better handle failed startup during network create

.deepsource.toml, client/lxd.go, lxc/delete.go, lxc/image.go, lxc/list.go, lxc/query.go, lxc/utils/progress.go
Hey folks, 
I recently ran the [DeepSource](https://deepsource.io) static analyser on the lxd code repository, and it [generated this report]([https://deepsource.io/gh/de-sh/lxd](https://deepsource.io/gh/de-sh/lxd)) that I think you should check out!
I am opening this PR to fix a few of the highlighted issues, as mentioned below:
- Omit comparison with boolean constant
- Remove unnecessary fmt.Sprintf() on string
- Replace .Sub(time.Now()) with time.Until() handler
- Use result of type assertion to simplify cases
- Add .deepsource.toml
=> Fixes to code quality

lxd/api_cluster.go, lxd/db/cluster/schema.go, lxd/db/cluster/update.go, lxd/db/networks.go, lxd/device/nic_bridged.go, lxd/device/nic_macvlan.go, lxd/device/nic_ovn.go, lxd/device/nic_sriov.go, lxd/network/driver_ovn.go, lxd/network/driver_physical.go, lxd/network/network_utils.go, lxd/networks.go, lxd/networks_utils.go, lxd/patches.go, test/suites/clustering.sh
When doing a `lxc network create` for subsequent attempts after failed initial attempt, avoid creating duplicate global config by ignoring global config supplied on subsequent attempts.
- Reintroduces the `Errored` status for a network when initial create attempt fails - so we can identify a partially created network both from global config existing and from its status (in cases where no global config is supplied).
- Blocks global config being supplied on subsequent re-create attempts when network is partially created.
- Skips global config insert on subsequent re-creates to avoid duplicate config (even if no config is supplied, could be default values generated and duplicated).
- Blocks re-create attempts once the network is successfully created.
- Makes looking for created networks …
=> Network: Clustering state avoid duplicate global config when doing re-create

lxd/api_cluster.go, lxd/db/cluster/schema.go, lxd/db/cluster/update.go, lxd/db/storage_pools.go, lxd/storage.go, lxd/storage_pools.go, lxd/storage_pools_utils.go, test/suites/clustering.sh
- Restructures storage pool creation to align with network creation process.
- Adds checks for any future duplicated config in DB load function.
- Adds rejection of global config when performing a storage pool re-create attempt.
- Skips global config insert on subsequent re-creates to avoid duplicate config (even if no config is supplied, could be default values generated and duplicated).
- Reinstates the Errored storage pool status so that we can detect re-create attempts even when no global config supplied.
- Blocks re-create attempts once the storage pool is successfully created.
Includes https://github.com/lxc/lxd/pull/8244
=> Storage: Clustering state avoid duplicate global config when doing re-create

lxd/instance/operationlock/operationlock.go
Calling `Reset()` from `Create()` was causing a deadlock causing `lxc stop -f` requests to hang if initiated while an `lxc stop` was in progress.
=> Instance: Fix deadlock in instance operationlock package

lxd/network/driver_ovn.go
=> lxd/network/driver/ovn: Detect IPv6 DHCP options correctly

doc/instances.md, lxd/device/proxy.go, lxd/instance/drivers/driver_qemu.go
Allows `proxy` devices to attach to VMs, and runs the necessary startup hooks for the proxy device to work.
CC: @grant-he @benhartcheatham
=> #7868: `proxy` device support for VMs (NAT-only)

lxd/device/nic_routed.go
Although liblxc should remove the interface, if it still exists for some reason we should try again to remove it.
Addresses https://discuss.linuxcontainers.org/t/unknown-error-17-failed-to-setup-ipv4-address-route-for-network-device/9718
=> NIC: Remove host-side veth interface if exists on routed device stop

lxd/network/driver_physical.go
=> Network: Clarify error when changing physical parent interface when in use

lxd/network/driver_bridge.go, lxd/network/driver_macvlan.go, lxd/network/driver_ovn.go, lxd/network/driver_physical.go, lxd/network/driver_sriov.go, lxd/storage/backend_lxd.go
Only apply changes to DB.
These commits are from the stable-4.0 branch ported to the master branch for the bridge network driver and backendLXD storage framework, and then a subsequent commit to align the non-stable-4.0 network drivers with the bridge driver.
=> Cluster: Don't apply node changes when network/pool is in pending state

lxd/network/driver_bridge.go, lxd/networks.go, lxd/storage/backend_lxd.go, lxd/storage_pools.go, test/suites/clustering.sh
Don't apply node changes when network or storage pool is in pending state.
We can't allow re-create attempts on errored networks/pools, as we don't track per-node state and so cannot tell which nodes have successfully been setup and which ones haven't. So the only valid approach is to require the user to delete and start again.
=> Cluster: Don't allow re-create attempts on errored networks and storage pools

lxd/db/cluster/schema.go, lxd/db/cluster/update.go
Prevents duplicate config rows for the same node and key being inserted.
Uses `IFNULL(node_id, -1)`  to ensure unique index is still enforced for non-node specific config keys where node_id is NULL, and uses `-1` as the pseudo value in order to avoid issues where the node ID is genuinely `0` which @stgraber advises is potentially possible on DBs from older installations.
I tried creating a new table with an updated `UNIQUE` constraint, but sqlite doesn't support the `IFNULL` expression in the `CREATE TABLE` statement.
Also updates previous duplicate row detection patch to use `IFNULL(node_id, -1)` too.
Fixes #8260
=> DB: Adds updateFromV43 patch that adds unique index to storage_pools_config and networks_config table

lxd/instance/drivers/driver_qemu.go
Otherwise qemu expects a single queue TAP device which isn't what we're
preparing these days :)
=> lxd/instance/qemu: Use a minimum of 2 network queues

lxd/storage/backend_lxd.go, lxd/storage/drivers/driver_zfs_volumes.go
When setting `volume.zfs.remove_snapshots=true` on a ZFS storage pool, this fixes several issues:
- The wrong snapshot was being checked for deletion suitability (resulting in not deleting any snapshots).
- Once that was fixed, there was also an issue with only the storage volume and storage volume DB record of the snapshot being deleted, not the instance snapshot record as well. Leaving orphaned snapshots in `lxc info <instance>` output and preventing deletion of instance (because snapshot volume DB record had been removed).
- Because of the scope of the `err` being returned, it was likely that as a new `err` was created inside the subsequent snapshot deletion block, that the original error would be returned even on successful restore. Added `return nil` after successful restore.
- …
=> Storage: Fix snapshot remove subsequent

doc/image-handling.md
=> doc/image-handling: Fix typo

doc/environment.md, shared/proxy.go
Sometimes, for example if you need a proxy to access the internet but
not local resources, it can be necessary to bypass the http(s)_proxy for
entire ranges.
Add support for CIDR ranges in no_proxy. This means, for example, that
10.0.0.0/8 will work as expected.
Fixes #8288
Signed-off-by: Iain Lane <iain@orangesquash.org.uk>
=> shared/proxy: Support CIDR ranges in `no_proxy`

test/suites/static_analysis.sh
Caused by https://github.com/gordonklaus/ineffassign/commit/664217a59c00a74b4491898ca757d3f711fff321
=> test/suites/static/analysis: Fixes ineffassign usage due to upstream changes

lxd/instance/drivers/qmp/monitor.go
Can end up calling close() on the chDisconnect channel multiple times if called concurrently.
Fixes #8294
=> QMP: Fix race in Disconnect

shared/simplestreams/simplestreams.go
Could be better in the near future to use url.Parse but i will review the code with the integration of the RFC changes.
=> simplestreams: Drop duplicated slash

lxd/api_internal.go, lxd/storage/drivers/driver_dir_utils.go, lxd/storage/quota/projectquota.go
Reinitialise root disk quota on `lxd import` so that directory project quota is reinitialised based on the instance's new volume ID.
Fixes https://github.com/lxc/lxd/issues/8280
=> Storage: Reinitialise root disk quota on lxd import

lxd/migrate_instance.go, lxd/storage_migration.go, test/suites/migration.sh, test/suites/snapshots.sh
Snapshot device names could be mixed up during migration due to use of loop pointer for name.
Fixes https://github.com/lxc/lxd/issues/8283
=> Instance: Copy snapshot devices reliably during migration

lxd/network/driver_ovn.go, lxd/network/openvswitch/ovn.go
Don't tear down all OVN config and rebuild, instead try and apply only changes, so as to reduce impact on instance port config.
=> Network: Make OVN updates more nuanced and less destructive

lxd/network/driver_common.go, lxd/network/driver_ovn.go, lxd/network/driver_physical.go, lxd/network/network_interface.go
This allows changes to a physical uplink network's `dns.nameservers` setting to be applied to dependent OVN networks that use it.
=> Network: Adds support for notifying dependent networks when their uplink networks change config

lxd/device/nic_ovn.go, lxd/network/driver_ovn.go, lxd/network/openvswitch/ovn.go
- When an OVN network's uplink's `ovn.ingress_mode` is set to `l2proxy` or empty, will find all instance NICs using the network and reinstate the l2proxy DNAT_AND_SNAT rules for any active switch port.
- When it is set to `routed` it will remove all DNAT_AND_SNAT rules for the network.
=> Network: Handle changes to OVN uplink ovn.ingress_mode setting

lxd/db/instances.go, lxd/db/instances_test.go, lxd/network/driver_ovn.go, lxd/patches.go, lxd/storage/utils.go
Allows DB level filtering before running callback function on each returned instance record.
This will be used in forthcoming OVN SR-IOV uplink support.
=> DB: Adds optional filter argument to InstanceList function

lxd/network/driver_bridge.go, lxd/network/driver_ovn.go
The chassis priority value is a stable-random value derived from chassis group name and node ID. 
This is so we don't end up using the same chassis for the primary uplink chassis for all OVN networks in a cluster.
=> Network: Generate OVN chassis priority using stable random value

doc/instances.md
=> doc: Fixes typo in macvlan NIC section

lxd/network/openvswitch/ovs.go
Simplify return in ``Installed`` method
=> openvswitch/ovs.go: Simplify return in Installed method

lxd/rbac/server.go
Fix ``time.Sleep()`` in ``StartStatusCheck()`` method to use seconds instead of nanoseconds
=> rbac/server.go: Sleep for seconds instead of nanoseconds

lxd/api_internal.go, lxd/instance/drivers/driver_qemu.go, test/suites/backup.sh
To allow exec to work when running container is recovered.
Fixes https://github.com/lxc/lxd/issues/8320
=> Instance: Regenerate container config file during lxd import recovery

lxd/cluster/raft/file_snapshot.go
Fix for deferring ``parentFH.Close()`` before checking ``parentFH, err := os.Open(s.parentDir)`` for possible error.
=> cluster/raft/file_snapshot.go: defer after checking error

lxd/storage/drivers/driver_ceph_volumes.go, lxd/storage/drivers/driver_cephfs_volumes.go
Ceph storage driver was not attempting to rename the filesystem volume for VMs, nor was it deactivating block volume for VMs.
Fixes https://github.com/lxc/lxd/issues/8328
=> Storage: Fix ceph VM rename and VM block volume deactivation

test/suites/container_devices_nic_bridged.sh
=> test/suites/container/devices/nic/bridged: Adds port isolation feature test

lxc/network.go, test/suites/container_devices_nic_bridged.sh, test/suites/container_devices_nic_bridged_filtering.sh, test/suites/container_devices_proxy.sh, test/suites/network.sh
Updates `lxc network attach` to detect the use of a managed network and rather than adding a NIC with a `nictype` property, instead adds a NIC with a `network` property. This enables support for attaching all types of managed networks (bridge, macvlan, physical, sriov and ovn).
If the network is unmanaged, falls back to old behaviour of defaulting to `macvlan` NIC type unless the network interface is a bridge in which case it uses `bridged` NIC type.
This also has the side effect that attaching to a managed bridge (i.e `lxc network attach lxdbr0 ...`) will now create a NIC with a `network` property rather than a `nictype` property.
Reported from https://discuss.linuxcontainers.org/t/confusion-about-hosting-dhcp-server-inside-linux-container/9929/6
Signed-off-by: Thomas Parrott …
=> lxc: Adds support for attaching instance to a managed network

lxd/device/nic_routed.go
And ensure that IP neighbour proxy entries are cleaned up after failed start.
Fixes https://github.com/lxc/lxd/issues/8341
=> Device: Add duplicate address detected to routed NIC

lxd/device/disk.go
Reported from https://discuss.linuxcontainers.org/t/fat-fingered-disk-override-container-can-no-longer-start/9962
=> Device: Validate disk size field properly

lxd/device/nic_bridged.go
=> Device: Allow bridged NIC removal even when parent bridge interface is missing

lxd/project/permissions.go, test/suites/projects.sh
Changes made:
- Created a list of safe volatile keys
- Modified checkRestrictionsOnVolatileConfig function to parse through the list of safe volatile keys and skip any keys that were safe and deleted any unsafe volatile keys from the config file instead of failing the copy
Fixes https://github.com/lxc/lxd/issues/7896
=> Smarter handling of `volatile` keys in restricted projects #7896

lxd/instance/drivers/driver_lxc.go, lxd/instance/drivers/driver_qemu.go, lxd/storage/backend_lxd.go, lxd/storage/drivers/utils.go
- Copy parent volume config into snapshot volume config.
- Respect volume config when mounting in `UpdateInstanceBackupFile`.
- Optimise snapshot restore process.
Fixes #8301
=> Storage: Copy parent volume config into snapshot volume config

lxd/storage/backend_lxd.go, lxd/storage/utils.go
Use our built in driver volume type and content type types to make argument usage clearer.
Precursor to https://github.com/lxc/lxd/pull/8357
=> Storage: VolumeDBCreate function argument type change and other clean ups

lxd/db/instances.go, lxd/instance/drivers/driver_common.go, lxd/instance/drivers/driver_lxc.go, lxd/instance/drivers/driver_qemu.go
- Adds insertConfigkey function which uses DB Retry function for retrying transactions.
- Refactors FillNetworkDevice to use shared insertConfigkey function for both instance drivers.
- Improves error message on failed inserts in CreateInstanceConfig.
Fixes #8359
=> Instance: Fix missing retry when generating NIC volatile.%s.name key

lxd/db/instances.go, lxd/instance/drivers/driver_common.go, lxd/instance/drivers/driver_lxc.go, lxd/instance/drivers/driver_qemu.go
- Adds insertConfigkey function which uses DB Retry function for retrying transactions.
- Refactors FillNetworkDevice to use shared insertConfigkey function for both instance drivers.
- Improves error message on failed inserts in CreateInstanceConfig.
Fixes #8359
=> Instance: Fix missing retry when generating NIC volatile.%s.name key (stable-4.0)

lxd/db/images.go
=> lxd/images: Skip keys with empty values

lxd/device/disk.go, lxd/device/gpu_physical.go, lxd/device/nic_physical.go, lxd/device/nic_sriov.go
When validating the instance type as part of device config validation,
we need to keep in mind that instancetype.Any is a valid value.
This is used for profiles as they can apply to any of the types.
In such cases, the config validation should only error out when directly
applied to an instance and further checks should be added for a start
time error on instances getting the device through profiles.
Closes #8377
=> lxd/device: Fix instance type validations

lxd/db/query/retry.go
=> DB: Make checkpoint in progress a candidate for IsRetriableError (stable 4.0)

lxd/main_forkdns.go, test/suites/clustering.sh
Fixes compatibility with nslookup that looks up A and AAAA records and returns with non-zero exit status if AAAA is returned as NXDOMAIN.
Fixes #8389
Tested in Alpine 3.13:
Before
```
c2:~# nslookup c1; echo $?
Server:		240.33.0.1
Address:	240.33.0.1#53
Name:	c1.lxd
Address: 240.126.0.249
** server can't find c1.lxd: NXDOMAIN
1
```
After:
```
c2:~# nslookup c1; echo $?
Server:		240.33.0.1
Address:	240.33.0.1#53
Name:	c1.lxd
Address: 240.126.0.249
0
```
=> Network: Bridge forkdns return empty AAAA record response when equivalent A record exists

lxd/device/nic_bridged.go, lxd/network/driver_bridge.go
Extracts fan bridge's IPv4 address to generate DHCPv4 subnet for use in validating NIC statically assigned addresses.
Fixes issue discussed here: https://discuss.linuxcontainers.org/t/static-ips-in-fan-network-for-lxd-4-x/10046
Example  (network bridge `ipv4.address` is effectively derived from the underlay subnet):
```
lxc network show lxdfan0
config:
bridge.mode: fan
fan.underlay_subnet: 10.250.145.0/24
ipv4.nat: "true"
name: lxdfan0
type: bridge
```
Before, assigning static DHCP allocation to instance fails:
```
lxc config device override c2 eth0 ipv4.address=240.33.0.45
Error: Invalid devices: Device validation failed for "eth0": Cannot specify "ipv4.address" when DHCP is disabled on network "lxdfan0"
```
After, succeeds:
```
lxc config device override c2 eth0 …
```
=> Network: Allow static IPs to be assigned to NICs when using fan bridge mode

client/simplestreams_images.go, shared/simplestreams/simplestreams.go, shared/util.go, shared/util_test.go
On expose images through S3 storage like Minio the path with `..` is not
accepted.
Example: http://server.org/simple../images/$path/root.tar.xz
In this case, we need to sanitize the URL to have:
http://server.org/images/$path/root.tar.xz
=> simplestreams: Review and sanitize urls join

client/interfaces.go, client/lxd_containers.go, client/lxd_instances.go, lxc/config_metadata.go, lxc/config_template.go, lxd/instance_metadata.go, lxd/instances.go
This renames a `SettInstanceMetadata` function to `UpdateInstanceMetadata`, following our normal naming scheme.
I'm not touching the much older `SetContainerMetadata` function as that one would be a pretty serious API break but it seems very unlikely that anyone other than ourselves made the switch over to the `Instance` variant and with my plan to deprecate all the `Container` functions with the release of 5.0 in 2022, this will let us get rid of this inconsistency.
If someone files a bug about it, I'm happy to re-introduce it as an alias with a deprecation warning, but I very much doubt that will be necessary.
=> Fix incorrect client function naming

lxd/instance/drivers/driver_qemu_templates.go
We were using an inconsistent mix of ram & memfd in some situations
which apparently causes memory issues.
Closes #8400
=> lxd/instance/qemu: Don't use the RAM backend

lxd/instance/drivers/driver_lxc.go
When we fail to attach to a container we can end up leaving zombies behind.
This rarely happens as this is a pathological case, i.e. something went severly
wrong in the attach codepath which is likely why we have rarely seen this.
=> containers: Attach of The Living Dead

lxd/seccomp/seccomp.go
LXC isn't a long-running daemon so in contrast to LXD it can't simply probe all
available new kernel features during startup as this would be too expensive. So
LXC doesn't follow the feature-probe logic but rather employs a model I like to
refer to as "gated feature checking". The idea being that a given kernel
feature that is reasonably cheap to check serves as a gate. Usually this gate
is a syscall. Every syscall that has been introduced earlier than the gating
syscall is assumed to be available.
A concrete example of gated feature checking is our use of the new mount api in
LXC. In order to make use of the new mount api LXC requires fsopen(),
fsconfig(), fsmount(), open_tree(), move_mount(), and openat2(). The gating
syscall here is openat2(). So if LXC detects that openat2() is …
=> seccomp: block openat2()

lxd/instance/drivers/qmp/commands.go, lxd/instance/drivers/qmp/monitor.go
This branch:
- Temporarily switches us to a fork of go-qemu that supports passing file descriptors through QMP
- Adds support for SendFile, Migrate and MigrateIncoming to be used for stateful stop, snapshots and live migration
- Reworks the way we handle failure to communicate with the VM.
- Splits internals and command wrappers
- Reworks all the command wrappers to use a much simpler way of sending commands and reading the response
This should result in far less confusing `Monitor is disconnected` by having other errors properly reported back to the user.
=> Cleanup and extend our QMP handling

lxd/device/nic_ipvlan.go, lxd/device/nic_routed.go, lxd/network/network_utils.go
Detach ipvlan interface back to random host name on stop, then delete.
Fixes #8427
=> Network: Don't depend on kernel for ipvlan NIC cleanup

lxd/device/nic_sriov.go, lxd/network/network_utils.go
Some SR-IOV NICs require setting an explicit VF MAC on the interface before being brought up it seems.
Fixes #8162
=> Network: Use volatile VF MAC if VF has no automatic MAC set

doc/api-extensions.md, doc/instances.md, lxd/api_internal.go, lxd/device/disk.go, lxd/device/gpu_mdev.go, lxd/device/gpu_physical.go, lxd/device/gpu_sriov.go, lxd/device/nic_physical.go, lxd/device/nic_sriov.go, lxd/device/pci.go, lxd/device/usb.go, lxd/instance/drivers/driver_qemu.go, lxd/instance_snapshot.go, lxd/storage/backend_lxd.go, lxd/storage/backend_mock.go, lxd/storage/drivers/volume.go, lxd/storage/pool_interface.go, shared/instance.go, shared/version/api.go
With this, a VM can be configured using:
- lxc config set v1 migration.stateful true
- lxc config device set v1 root size.state 2GiB
Then after start, it can be stopped and restarted while conserving state using:
- lxc stop v1 --stateful
- lxc start v1
Stateful snapshots will be next but this will need a bunch of cleanups I want to do separately.
For now this branch just prevents them entirely.
=> Implement VM stateful stop/start

doc/api-extensions.md, doc/preseed.md, lxd/api_cluster_test.go, lxd/device/device_common.go, lxd/device/device_interface.go, lxd/device/device_load.go, lxd/device/device_utils_network.go, lxd/device/disk.go, lxd/device/nic_bridged.go, lxd/device/nic_p2p.go, lxd/device/nic_routed.go, lxd/firewall/firewall_interface.go, lxd/instance/drivers/driver_common.go, lxd/instance/drivers/driver_lxc.go, lxd/instance/drivers/driver_qemu.go, lxd/network/network_interface.go, lxd/storage/drivers/driver_btrfs_volumes.go, lxd/storage/drivers/driver_lvm.go, test/suites/database.sh
Previously some NIC devices have supported "live update" of certain config fields. These config settings were able to be applied on the host without removing and re-adding the NIC device inside the instance.
However with the introduction of the `network` property that caused the NIC device to inherit the `nictype` (implicitly) and other settings (explicitly) from the network's config, this caused the live-update feature to break, causing all modification of NIC config fields to trigger a remove and re-add.
This was because the helper function passed to `oldExpandedDevices.Update` in the instance driver's `Update()` function was causing the device to be initialised (which triggers validation, which in turn modifies the supplied config with the explicitly inherited network settings). This …
=> Network: Adds support for live updating NIC fields when using network property

lxd/storage/drivers/utils.go
When creating a storage (btrfs) pool backed by a block device as in this
example
lxc storage create pool-btrfs btrfs source=/dev/sdc
we create the storage pool based on the volatile device path /dev/sdc. Since
this is obviously a bad idea we have logic to replace this device path with the
reliable /dev/disk/by-uuid/<uuid> path based on the uuid we just generated when
creating the filesystem. So we call
blkid -s UUID -o value /dev/sdc
and use the returned uuid in a tryExists(/dev/disk/by-uuid/<uuid>) loop for 10
seconds. This consistently failed for me which means I ended up with the
unreliable /dev/sdc device path as the source property of the storage pool
which I couldn't change later. The reason this happens is that whitespace
is sneaking in making the path whose existence we test for …
=> utils: trim whitespace from block device UUID

lxd/device/nic_ovn.go, lxd/network/driver_ovn.go, lxd/network/openvswitch/ovn.go
Some non-ACL specific OVN changes that will allow accommodation of forthcoming ACL features.
- Move concrete UUID types to avoid confusion now we are using UUIDs for various different object types.
- Change instance device port management functions to use options struct as argument list was getting long.
- Clarify the `InstanceName` option actually mean `DNSName` (which we pass the instance name to).
=> Network: OVN ACL precursor changes

lxd/instance/drivers/driver_qemu.go
With this, you can now run:
- lxc snapshot v1 --stateful
And then later:
- lxc restore v1 --stateful
An easy check to confirm this works as intended is to look at `cat /proc/uptime`.
=> Add stateful snapshots for VMs

lxd/cluster/gateway.go, lxd/cluster/heartbeat.go
With this, only one heartbeat can be running at any one time and
additional requests are ignored. It also replaces the previous logic of
doing a full heartbeat round on dqlite connections to instead doing one
automatically if no heartbeat round succeeded over the past two
intervals.
This should ensure that a newly elected leader will do a hearbeat round
almost immediately and that this heartbeat round will include all data
whereas existing leaders will keep doing normal heartbeats even if
dqlite connections get reset.
=> lxd/cluster: Improve heartbeat logging

lxd/api_internal.go, lxd/instance/drivers/driver_lxc.go, lxd/instance/instance_utils.go, lxd/instances_post.go
When importing a backup, if the import failed at a certain point, the storage volume records were not deleted.
Reported here: https://discuss.linuxcontainers.org/t/ghost-container-volume/10191
=> Instance: Volume cleanup on backup import failure

doc/api-extensions.md, doc/instances.md, doc/metadata.yaml, doc/networks.md, lxd/db/network_acls.go, lxd/device/nic.go, lxd/device/nic_ovn.go, lxd/network/acl/acl_load.go, lxd/network/acl/acl_ovn.go, lxd/network/acl/driver_common.go, lxd/network/driver_ovn.go, lxd/network/network_utils.go, lxd/network/openvswitch/ovn.go, shared/version/api.go
This PR provides the ability to assign Network ACLs to OVN networks and OVN NICs (either directly or via a profile).
E.g.
```
lxc network set ovn1 security.acls=test1,test2
lxc profile device set default eth0 security.acls=test1
lxc config device set c1 eth0 security.acls=test3,test4
```
- Network assigned ACLs are applied to all OVN Instance NICs that are connected to that network (in addition to any specified on the Instance NIC itself).
- LXD will create the OVN port groups (with ACL rules) as needed, and remove them when they are no longer referenced by any LXD resource.
- LXD will update the OVN port group ACL rules when the rules of a LXD Network ACL change.
- LXD will add baseline OVN ACL rules to OVN networks when they are added/updated to allow instance access to services …
=> Network: Support OVN ACLs

lxd/storage/drivers/driver_btrfs.go, lxd/storage_pools_config.go
Tested using:
```
lxc storage create btrfs btrfs # Create BTRFS pool on loop file
lxc storage show btrfs
config:
size: 21GB
source: /var/lib/lxd/disks/btrfs.img
```
Has `size` property generated.
Now create new BTRFS pool using existing filesystem:
```
mount | grep btrfs
/var/lib/lxd/disks/btrfs.img on /var/lib/lxd/storage-pools/btrfs type btrfs (rw,relatime,ssd,space_cache,user_subvol_rm_allowed,subvolid=5,subvol=/)
lxc storage create btrfs2 btrfs source=/var/lib/lxd/storage-pools/btrfs
lxc storage show btrfs2
config:
source: /var/lib/lxd/storage-pools/btrfs
volatile.initial_source: /var/lib/lxd/storage-pools/btrfs
```
Doesn't have `size` property.
There are similar lines in the `lvm` and `zfs` drivers already.
Reported from: https://discuss.linuxcontainers.org/t/btrfs-storage-size/10243
=> Storage: Unset irrelevant BTRFS pool size property when creating from existing filesystem and not loop file

lxd/network/acl/acl_ovn.go, lxd/network/acl/driver_common.go, lxd/network/driver_ovn.go
- Avoids some duplicated steps by creating new function OVNEnsureACLs.
- Prevents removal of port groups if they are referenced by other ACL rules.
- Adds recursive setup of ACLs based on references in rules to other ACPs.
=> Network: Simplify ACL OVN port group creation and updates

Makefile, doc/rest-api.yaml, lxd/api.go, lxd/api_1.0.go, lxd/certificates.go, lxd/swagger.go, shared/api/certificate.go, shared/api/server.go, test/suites/static_analysis.sh
This puts in place the infrastructure for describing our API through swagger and implements the `/` and `/1.0` endpoints.
Getting the full API labeled will take time and will be handled through subsequent PRs until we achieve full coverage and can replace the current manual `rest-api.md` with an automated one.
=> Swagger setup and initial endpoints

lxd/storage/drivers/utils.go
=> lxd/storage/drivers/utils: Comment clarify in BlockDiskSizeBytes

lxd/network/acl/acl_ovn.go, lxd/network/driver_ovn.go, lxd/network/openvswitch/ovn.go
Previously we always created OVN port groups along with their respective ACL rules at the same time.
When we introduced the concept of referenced ACLs within another ACL rule, this then introduced the requirement to recursively setup port groups (and the ACL rules) of any referenced ACLs at the same time.
This was done to stop OVN complaining about missing port groups referenced in the ACL rules. However OVN doesn't actually require the referenced port groups to have ACLs, they just need to exist.
We only need to actually load the ACL rules into a port group when they are being directly referenced by a network or NIC.
So this changes OVNEnsureACLs to only create referenced port groups (and doesn't load them with ACL rules).
This has the benefit that we don't need to recurse, as we are …
=> Network: Refactors OVNEnsureACLs to be smarter in how it sets up referenced ACLs

lxd/instance_logs.go
Updated instanceLogDelete() function to allow deleting of logs from instances in a project other than default
=> Updated instanceLogDelete function

lxd/device/disk.go
Enable joliet encoding on ISOs.
=> lxd/device/disk: Tweak mkisofs flags

lxd/device/nic_ovn.go, lxd/network/acl/acl_load.go, lxd/network/acl/acl_ovn.go, lxd/network/acl/driver_common.go, lxd/network/driver_ovn.go, lxd/network/openvswitch/ovn.go
Extends clean up routine to support indirectly usage ACLs (ACLs referred to by other ACL rules).
Tests updated here: https://github.com/lxc/lxc-ci/pull/247
=> Network: Adds full unused OVN ACL port group clean up

doc/rest-api.md
Updates REST API doc with fields from:
https://github.com/lxc/lxd/pull/6292
https://github.com/lxc/lxd/pull/6294
Reported from: https://discuss.linuxcontainers.org/t/container-backup-expiry-ignored/10323/
=> doc/rest-api: Updates backup endpoint docs

doc/api-extensions.md, doc/projects.md, lxd/api_1.0.go, lxd/api_project.go, lxd/cluster/config.go, lxd/daemon.go, lxd/images.go, lxd/instances_post.go, shared/version/api.go
It's a third part of "Add `images.*` and `backups.*` server config keys to per-project #7900" issue.
Not sure about projectsAutoUpdateTime map but we need to keep somewhere times of autoUpdateTask execution per project. So we know when run it next time.
I've made also some cleanup staff related with remote_cache_expiry and auto_update_interval keys.
=> Images auto update

lxd/storage/drivers/driver_btrfs_volumes.go, lxd/storage/drivers/driver_dir_volumes.go, lxd/storage/drivers/utils.go
When a VM image block file is greater than the default block volume size (10GB) it was being truncated to 10GB during the creation of BTRFS optimized image volumes (if `volume.size` on the storage pool wasn't set). 
There was explicit detection of the scenario where an image was larger than the default and to do not resize, however this was being overridden due to the use of `vol.allowUnsafeResize = true` in `CreateVolume` introduced with f245258acf7e23b74d6d16e050ab9656bde99c18 and 059863e24bcca4e9f53cff413541553e8a3d6f39.
This was added to allow the `ImageUnpack` called from `runFiller` to shrink the optimized block volumes on storage drivers that have to pre-create the volume before they know the size, and for `genericVFSBackupUnpack` to shrink the volume before unpack if needed. …
=> Storage: Stop truncating BTRFS optimized image VM volumes to default volume size after image unpack

lxd/include/macro.h, lxd/include/memory_utils.h, lxd/main_forkproxy.go, lxd/seccomp/seccomp.go, shared/netutils/network_linux_cgo.go, shared/netutils/unixfd.c, shared/netutils/unixfd.h
Enable caller and callee to express expectations and the reality of fd
retrieval. If the expectations of the caller aren't fulfilled then the cleanup
of any received fds will happen in the low-lever helper directly instead of
forcing it upon the caller to cleanup fds.
=> lxd: improve unix fd retrieval infrastructure

lxd/db/cluster/stmt.go, lxd/db/db.go
On startup, we call "lxd activateifneeded", this does a number of simple
database access using sqlite directly. We only need a fraction of the
tables at that point and this will run ahead of any on-startup database
schema update.
This change makes it so that new prepared statements for tables that do
not yet exist won't prevent activateifneeded from accessing the
database.
=> lxd/db: Don't fail preparing statements for activateifneeded

doc/network-acls.md, lxd/network/acl/acl_load.go, lxd/network/acl/acl_ovn.go, lxd/network/acl/driver_common.go, lxd/network/driver_ovn.go, lxd/network/openvswitch/ovn.go
Adds support for using `#external` and `#internal` special subjects in the `source` and `destination` rule fields where one would be able to use an ACL name.
- `#external` is to select any traffic coming to/from the external gateway port of a logical network.
- `#internal` is to select any traffic coming to/from any of the instance NIC ports connect to the logical network (even if they don't have any ACLs assigned to them).
In order to support this I have used several new OVN port groups:
1. When an OVN network is created, a per-network port group is created (irrespective of whether ACLs are assigned or not). When an instance NIC starts that is connected to this network its port is added to the per-network port group. This is what creates the classification of ports that are considered …
=> Network: Adds OVN #internal/#external port subjects

lxd/device/infiniband_physical.go, lxd/device/infiniband_sriov.go, lxd/device/nic.go, lxd/device/nic_bridged.go, lxd/device/nic_ipvlan.go, lxd/device/nic_macvlan.go, lxd/device/nic_ovn.go, lxd/device/nic_p2p.go, lxd/device/nic_physical.go, lxd/device/nic_routed.go, lxd/device/nic_sriov.go, lxd/network/driver_bridge.go, lxd/network/driver_macvlan.go, lxd/network/driver_physical.go, lxd/network/driver_sriov.go, lxd/network/network_utils.go, shared/validate/validate.go
- Checks a NIC's `name` property is a valid interface name and not conflicting with another interface on the instance.
- Prevents passing `%` char as interface name to avoid letting the kernel generate part of the NIC name and losing knowledge of what the NIC's interface name is.
Fixes https://github.com/lxc/lxd/issues/8501
=> Network: Validate NIC interface name and prevent duplicates

lxd/network/network_utils_sriov.go
Ensures that if another application is using this VF (because it is up or has an IP configured on it) that we won't use it when selecting a free VF for `sriov` NICs.
Fixes https://github.com/lxc/lxd/issues/8368
=> Network: Further restrict SR-IOV free VF rules to require VF to be down and have no IPs configured

lxd/network/network_utils_sriov.go
When a VM has used a VF it is unbound from the host OS so the `/sys/class/net/%s/device/virtfn%d/net` directory won't exist.
This is OK, and we should just skip the VF as its in use.
Related CI test update: https://github.com/lxc/lxc-ci/pull/253
=> Network: Don't fail when missing vfListPath in sriovGetFreeVFInterface

doc/rest-api.md
Nothing so critical, just noticed this disturbing typo about the JSON structure.
=> docs: typo on JSON schema

lxd/images.go
Without this, the image would always end up on the leader (unclear why
that was done) and then the next X nodes in database order.
Instead we want the load spread as much as possible, so let's just pick
random nodes instead.
=> lxd/images: Properly spread replicated images

doc/api-extensions.md, doc/projects.md, lxd/api_project.go, lxd/instance_post.go, lxd/instances_post.go, lxd/project/permissions.go, shared/version/api.go
@stgraber not sure about adding new HasFlagTarget field to InstancePost and InstanceSource structs but we need to pass info about use of flag '--target' by user. I thought about using targetNode var (which is used in `lxd/instance_post.go:instancePost` and `lxd/instances_post.go:instancesPost`) but this var is also set in code when request goes to second node.
=> Projects restricted cluster target

lxd/storage/drivers/driver_ceph_utils.go
@stgraber @brauner the change in https://github.com/lxc/lxd/pull/8524 caught my eye as it looked like a good candidate for the `util.SplitNTrimSpace` I added as part of the OVN ACL feature.
I noticed that parsing a (usually comma) separated list and removing white space between the elements was a common pattern for us, so added a function to do it to reduce repetition.
Also, although not so useful in this case because there is a separate not-empty check, but in cases where you don't need to do anything if the option list is empty the `util.SplitNTrimSpace` takes a boolean argument to return a nil slice when the input is an empty string (which avoids returning a single element slice containing an empty string).
=> Storage: Ceph utils util.SplitNTrimSpace usage

lxd/network/acl/acl_ovn.go, lxd/network/openvswitch/ovs.go
=> Network: Use OVN TCP flag constants for OVN ACL baseline rules

lxd/cluster/gateway.go, lxd/cluster/gateway_test.go, lxd/patches.go
Recreates nodes table id column with AUTOINCREMENT.
Related to https://github.com/canonical/raft/pull/176
Related to https://github.com/lxc/lxd/pull/8521
=> Patches: Adds db_nodes_autoinc patch

lxd/network/acl/acl_load.go
=> Network: Fix UsedBy with project profiles

doc/rest-api.md
=> Fix a typo in rest-api.md for renaming a network ACL

client/lxd.go, doc/network-acls.md, doc/rest-api.yaml, lxd/network/acl/acl_ovn.go, lxd/network/acl/driver_common.go, shared/api/network_acl.go
To avoid YAML editors treating unquoted `#` prefixed subject names as comments and removing them.
Also I noticed that the `lxc` client was attempting to parse error responses from the LXD server through `fmt.Error()` causing any `%` in the output to trigger a fmt error.
=> ACL: Deprecate #internal and #external and replace with @internal and @external

lxd/network/acl/acl_ovn.go
=> Network: Ensure to parenthesise || when used with && in OVN rule match

lxd/db/instances.go, lxd/storage/backend_lxd.go, lxd/storage/drivers/driver_btrfs_volumes.go, lxd/storage/drivers/driver_ceph_volumes.go, lxd/storage/drivers/driver_cephfs_volumes.go, lxd/storage/drivers/driver_dir_volumes.go, lxd/storage/drivers/driver_lvm_volumes.go, lxd/storage/drivers/driver_mock.go, lxd/storage/drivers/driver_zfs_volumes.go, lxd/storage/drivers/generic_vfs.go, lxd/storage/drivers/interface.go, lxd/storage/drivers/volume.go
Ensures that snapshots are backed up in the same order they are migrated (age ordered, oldest first) for consistency of behaviour, and to ensure that optimized backups are performed efficiently using the correct snapshot parent for the differential.
Adds `SnapshotsMatch` function to ensure that the snapshot list provided matches the snapshots on the storage layer, ensuring that the DB and storage layer are in sync.
More general solution to https://github.com/lxc/lxd/pull/8542
=> Storage: Update BackupVolume to accept an age ordered list (oldest first) of snapshots

lxd/network/driver_ovn.go, lxd/network/openvswitch/ovn.go
When using `ovn-nbctl --may-exist lr-nat-add` if an existing NAT entry exists it should be ignored and no error returned. However some ovn-nbctl versions return an error.
So instead we delete any existing record and add a new one.
Also fixes issue where if network's `ipv{x}.nat` option is enabled after the instance is started, then when the instance is stopped the DNAT rules were not cleared up. Now always attempt to clear up DNAT rules on stop.
Also adds some optimisations to reduce calls to ovn-nbctl. Significantly speeds up adding DNAT rules for larger external routes.
=> Network: Work around ovn-nbctl NAT bugs in LogicalRouterDNATSNATAdd

lxd/device/disk.go
If `btrfs filesystem show` doesn't work then fallback to extracting major/minor number directly from the parent block device in the mount info for cgroup limits generation.
Fixes #8564
=> Device: Fallback to using disk mount device path for major/minor number extraction for BTRFS

lxd/db/images.go, lxd/db/images.mapper.go
This fixed a very nasty regression introduced in 4b5ba96f19 which
switched the function fetching expired images to filter on a per-project
basis.
That part made total sense but unfortunately what we missed is that we
had no code-generated DB code for that particular filter
(Project-Cached) so instead only the project filter was used, causing
the Cached field to be ignored entirely.
This then resulted in all expired images to be returned to the image
pruner EVEN if an image wasn't cached, causing the deletion of manually
created images that weren't used recently...
Reported at: https://discuss.linuxcontainers.org/t/images-vanished/10498/
=> lxd/db/images: Fix incorrect cached attribute handling

doc/index.md
I add a manually created Table of Content below the Status section in doc/index.md.
I also add the term "feature requests" to the bug reports section.
Fixes: #8559
=> doc: Add a Table of content and a small addition to doc/index.md (Readme.md)

lxc/move.go, lxd/instance_post.go, lxd/migrate_instance.go
@stgraber I'd like to clarify some stuff. It will be easier to discuss with an examle so I made PR draft.
Regarding your conversation #8005 with gzhang1218 `containerPostClusteringMigrate` is only called when instance is moved. You said that we need match operation id we got from the `CopyInstance` call with operation from handler function. But from `CopyInstance` we got operation "Creating instance" and information about progress is in "Migrating instance" operation. This is why I'va added third parameter to `CopyInstance` returning migration operation ID.
In case of copy operation `containerPostClusteringMigrate` method isn't called. So I chose `createFromMigration` to implement metadata updating because we've got there access to migration operation and operation which should be …
=> In-cluster progress information

doc/api-extensions.md, doc/instances.md, doc/network-acls.md, doc/networks.md, doc/rest-api.yaml, lxd/device/nic.go, lxd/device/nic_ovn.go, lxd/network/acl/acl_ovn.go, lxd/network/acl/driver_common.go, lxd/network/driver_ovn.go, lxd/network/openvswitch/ovn.go, lxd/patches.go, shared/api/network_acl.go, shared/version/api.go
Replaces them with new per-network and per-NIC settings:
- `security.acls.default.{in,e}gress.action` - can be `reject`, `drop` or `allow` (defaults to `reject` if not specified).
- `security.acls.default.{in,e}gress.logged` - can be `true` or `false` (defaults to `false` if not specified).
The NIC setting(s) will override the equivalent setting(s) on the network.
Fixes https://github.com/lxc/lxd/issues/8553
Fixes https://github.com/lxc/lxd/issues/8568
Also modifies the OVN ACL rule priority classes to work around an issue caused by OVN's addition of a +10 priority for TCP reject rules (https://github.com/ovn-org/ovn/commit/366ac0d89da7eb6cfac5f4e1245d34b8b9aabe7b) that was causing infinite reject packet generation due to overlapping priorities with the TCP RST|ACK allow rules.
**This …
=> Network: Remove default.action and default.logged ACL settings

lxd/network/driver_ovn.go, lxd/network/openvswitch/ovn.go
Shouldn't happen (I suspect I had some left over entries from a partially deleted dev network), but this patch detects it with clear error.
Also reduces number of calls to ovn-nbctl in the process.
=> Network: OVN detect scenario where there are multiple DHCP option sets for a specific subnet

lxd/device/nic_bridged.go, lxd/device/nic_ovn.go
That way we don't leave an empty ruleset on error when updating a NIC's config.
=> Device: Check bridge NIC's security.ipv6_filtering support before wiping existing rules

lxc/move.go
Support for flagQuiet when in-cluster move is made. Related with #8565.
=> Support for flagQuiet when in-cluster instance is moved

lxd/device/nic_bridged.go, lxd/network/network_utils.go
Also excludes those in FAILED state.
Still outputs IPs in non-valid-states even when valid IPs found so as not to flap between displaying IPv4, IPv6 and link-local addresses, but orders valid entries first.
=> Device: Modifies Bridge NIC state to return IP neighbour entries in valid states first

lxd/instance/drivers/driver_common.go, lxd/instance/drivers/driver_lxc.go, lxd/instance/drivers/driver_qemu.go, lxd/instances.go
There were several unnecessary calls to `getLxcState` which meant that doing:
```
while :; do lxc ls; done
```
With 2 containers would quickly crash LXD. 
This PR reduces the calls to `getLxcState` (which is the function that calls liblxc that triggers the crash mentioned in https://github.com/lxc/lxd/issues/8327), so it is more efficient and crashes less often, although it is still not a full fix. I suspect there is an issue in liblxc or Go but I've not been able to confirm that yet.
Also applies similar optimisation techniques to Qemu driver to reduce calls to QMP and align the two driver's behaviours.
=> Instance: Reduce calls to getLxcState to reduce crashes and improve efficiency

Makefile
=> Makefile: Set GO111MODULE=off

lxd/instance/drivers/driver_qemu_templates.go
=> lxd/instance/qemu: Disable net vectors on ccw

lxd/device/infiniband_physical.go, lxd/device/infiniband_sriov.go, lxd/device/nic_bridged.go, lxd/device/nic_macvlan.go, lxd/device/nic_ovn.go, lxd/device/nic_p2p.go, lxd/device/nic_physical.go, lxd/device/nic_routed.go, lxd/device/nic_sriov.go
This is so that NIC config specified before the type field isn't cleared when the type is specified (https://github.com/lxc/lxc/commit/8d508eaa9).
=> Device: Ensure type field in NetworkInterface is specified first for liblxc

doc/index.md
This reverts commit 10c2387e9a2e01706e0dad737006bf3d11047943.
Github has now introduced its own table of content and we have one on
the website too, so let's drop this one.
=> Revert "doc: Added a Table of Content in /doc/index.md"

lxd/storage/drivers/driver_ceph_volumes.go, test/suites/clustering.sh
I cannot see a reason why we were ignoring the unmount volume errors (which would also return unmap errors https://github.com/lxc/lxd/blob/master/lxd/storage/drivers/driver_ceph_volumes.go#L1053-L1058 and https://github.com/lxc/lxd/blob/master/lxd/storage/drivers/driver_ceph_volumes.go#L1072-L1089), as if the volume is mounted or mapped and cannot be unmounted/unmapped, then it cannot be deleted as I understand.
Also adds a retry for a `test_clustering_remove_raft_node` test to make it more reliable in the face of DB locking.
=> Storage: Remove duplicated attempts to unmap in DeleteVolume

lxd/cluster/membership.go, lxd/cluster/recover.go
go-dqlite has an internal timeout of 5s when attempting to contact a
node. If the timeout of the parent context is not large enough, an
unreachable node might consume the whole time budget, and other,
possible reachable nodes will not be attempted anymore leading to
observed failures while in fact the cluster is healthy.
Signed-off-by: Mathieu Borderé <mathieu.bordere@canonical.com>
=> cluster: Larger Timeout to find leader

lxd/api_internal.go, lxd/api_internal_test.go, lxd/db/profiles.go, test/suites/backup.sh
- If backup.yaml contains a local root disk device, always keep that (just update `pool` property to match target pool).
- If backup.yaml doesn't contain a local root disk device, and profile's expanded root disk pool doesn't match target pool, then add new local root disk device, setting `pool` to target pool, and inheriting any extra config from the expanded root disk device in backup.yaml.
- If backup.yaml doesn't contain a local root disk device, and profile's expanded root disk pool does match target pool, but profile's expanded disk config doesn't match expanded root disk device in backup.yaml (excluding `pool` property), then add new local root disk device, setting `pool` to target pool, and inheriting any extra config from the expanded root disk device in backup.yaml.
- If …
=> Import: Maintain effective root disk config from backup.yaml when doing import

lxd/firewall/drivers/drivers_consts.go, lxd/firewall/drivers/drivers_nftables.go, lxd/firewall/drivers/drivers_xtables.go, lxd/firewall/firewall_interface.go, lxd/network/driver_bridge.go
Simplify `Firewall` interface so that there is only 1 `NetworkSetup` function rather than per-feature setup functions.
This will allow each driver to apply the requested config in a predictable order and in the most efficient way allowed by each driver  (these will be delivered in separate PRs).
=> Network: Firewall interface refactor

lxd/firewall/drivers/drivers_xtables.go
This ensures that if LXD is reloaded and new network level default policy rules are prepended to INPUT and FORWARD chains that these don't take precedence over NIC level filtering rules.
=> Firewall: Add chain for NIC specific security filtering rules.

lxd/firewall/drivers/drivers_nftables.go, lxd/firewall/drivers/drivers_xtables.go, lxd/firewall/firewall_interface.go, lxd/network/driver_bridge.go
In https://github.com/lxc/lxd/pull/8637 we moved to using a separate chain for NIC security filtering rules so they took precedence over the default forwarding policy rules (when LXD was reloaded and the network config was reapplied).
Initially I used a single chain called `lxd_nic` that would contain the NIC rules for all `bridge` networks.
This meant that when an individual network was deleted we didn't need to remove the `lxd_nic` chain.
However with the forthcoming ACL support for bridge networks, we will need to introduce a per-network ACL rule chain, which will require support deleting the chain when the network is deleted.
As we are going to introduce this for ACLs, it makes sense to me to also use the same approach for NIC filtering rules, and switch to a per-network chain for …
=> Firewall: Switch to using network-specific NIC filtering chain in xtables driver

lxd/storage/drivers/driver_zfs_volumes.go
Otherwise calling MountVolume for an instance block volume will increment the filesystem volume mount ref counter again, as MountVolume would have already been called for the filesystem volume as part of the recursive call to CreateVolumeFromBackup for VM Block volumes above.
And as we don't use the post hook function from that function call, we'd end up leaving the filesystem volume of a block volume mounted due to the extra ref count.
Fixes #8649
=> Storage: Only mount instance filesystem volumes in postHook for ZFS CreateVolumeFromBackup

lxd/firewall/drivers/drivers_nftables.go, lxd/firewall/drivers/drivers_nftables_templates.go, test/suites/container_devices_proxy.sh
The inet table is described here: https://wiki.nftables.org/wiki-nftables/index.php/Nftables_families#inet
> Tables of this family see both IPv4 and IPv6 traffic/packets, simplifying dual stack support.
> Within a table of inet family, both IPv4 and IPv6 packets traverse the same rules. Rules for IPv4 packets don't affect IPv6 packets. Rules for both L3 protocols affect both. 
The rationale behind this is to simplify the forthcoming ACL rules that will be added as a single chain with mixed IP4/IPv6 rules, rather than needing to separate or duplicate them over two chains in two tables.
This also makes it easier to reason about where LXD is putting its rules, and can result in rule amount reduction by being able to use the same rule for both IPv4 and IPv6 traffic.
I've ensure that the …
=> Firewall: Changes nftables to use a single inet table rather than separate ip and ip6 tables

lxd/firewall/drivers/drivers_xtables.go, lxd/network/acl/acl_ovn.go, lxd/network/acl/driver_common.go, lxd/network/driver_ovn.go, shared/validate/validate.go
Also improve error message returned when named subject is used in an invalid scenario.
Also lands some miscellaneous firewall related changes from the ongoing xtables/nftables branch that are not directly related to it.
=> Network: Allow single IP in ACL source & destination subjects

lxd/firewall/drivers/drivers_xtables.go
This reverts commit 5ff5df309bdc2305d07fa2872589b0ad352d11e1.
Looks like the proxy device depends on this behaviour so will need to dig into more detail as to why, as I was depending on this behaviour for the xtables ACL driver.
=> Firewall: Revert "lxd/firewall/drivers/drivers/xtables: Don't check for existing rule in iptablesAdd"

lxd/daemon_images.go, lxd/instance.go
This fixes a race condition when transferring an image that exists on another cluster member, but does not exist on the local member.
If two or more instances are created at the same time, then one or more of them would fail with an error:
```
lxc config set cluster.images_minimal_replica=1
lxc init images:ubuntu/focal csrc --target=v1
lxc init images:ubuntu/focal c1 --target=v2 &
lxc init images:ubuntu/focal c2 --target=v2
Creating c1
Creating c2
Error: Failed instance creation: Failed adding image to local node: UNIQUE constraint failed: images_nodes.image_id, images_nodes.node_id
```
=> Image: Add image locks when downloading images

lxd/firewall/drivers/drivers_nftables.go, lxd/firewall/drivers/drivers_nftables_templates.go, lxd/firewall/drivers/drivers_xtables.go
If a proxy device used a listen port range but no connect port range in NAT mode, i.e:
```
p1:
listen: tcp:192.168.1.200:80-81
connect: tcp:10.105.189.2:80
nat: "true"
type: proxy
```
Then we were incorrectly adding multiple identical hairpin masquerade NAT rules for the same connect port.
This wasn't causing any problems, but is inefficient, so now we only add multiple rules if there are multiple connect ports being used, e.g.
```
p1:
listen: tcp:192.168.1.200:80-81
connect: tcp:10.105.189.2:80-81
nat: "true"
type: proxy
```
This also allows us to remove the duplicate rule detection in the `iptables` driver when adding new rules, which speeds up adding new rules, and allows the forthcoming ACL functionality to add duplicate rules (at a higher priority) when adding baseline DNS/DHCP rules …
=> Firewall: Only add multiple proxy masquerade hairpin NAT rules if connect port range used

lxd/network/acl/driver_common.go
=> Firewall: Fix typo in validation error message

lxd/instance/drivers/driver_lxc.go
Fixes: #8608
Fixes: https://discuss.linuxcontainers.org/t/container-fails-to-start-properly-when-a-usb-device-is-attached-to-the-container-before-start-up
=> lxd: don't set device cgroup values for unpriv containers

client/simplestreams_images.go, lxd/daemon_images.go, shared/simplestreams/simplestreams.go, test/godeps.list
These changes allowed me to track down the affected URL generating the `unexpected end of JSON input` error when downloading images.
=> Images: Improve download error messages

lxc-to-lxd/main_migrate_test.go, lxd/cluster/membership.go, lxd/util/encryption.go, test/suites/clustering.sh
Rather than re-using the existing first-member server certificate.
=> Cluster: Generate a new cluster certificate when bootstrapping a cluster

lxd/api_cluster.go, lxd/cluster/membership.go, lxd/cluster/membership_test.go, lxd/db/node.go, lxd/storage_volumes_snapshot.go, test/suites/clustering.sh
This will fix us constantly issuing heartbeats on simple API interactions and instead rely on the state we have in the database.
This should lead to faster API calls and less cross-cluster chatter.
=> Replace cluster.List with GetNodes

lxd/device/nic_routed.go, lxd/instance_test.go
Fixes #7943.
Signed-off-by: Sascha Bast <sash@mischkonsum.org>
=> lxd/lxd: Prevent multiple routed NIC devices from using "auto" gateway mode

lxd/db/storage_volumes.go, lxd/storage_volumes_snapshot.go
- Ensure that local custom volumes are always snapshotted on the local member.
- Skip snapshotting remote volumes if no online members to avoid snapshotting on multiple member during a cluster partition.
- Improve logging.
Fixes #8692
Testing:
=> Storage: Fix auto custom volume snapshots

lxc/storage_volume.go, lxd/db/storage_volumes.go, lxd/endpoints/endpoints.go, lxd/instance/drivers/qmp/commands.go, lxd/storage_pools.go, lxd/storage_volumes_snapshot.go
Just went through a bunch of our open bugs and fixed them :)
This started with the storage volume target issues in the client, then fixed a few more commands, then fixed the server side of those commands, then fixed the snapshot increment bug and finished with the pool deletion.
I then looked into the endpoint binding issue and found a reasonable way to re-try bind failures.
And while looking into QMP and QEMU 6.0 for #8416 I came across the deprecation of query-cpus and so switched us to query-cpus-fast.
=> Assorted bugfixes

lxd/instance/drivers/driver_qemu.go, lxd/instance/drivers/driver_qemu_templates.go
Since QEMU 5.2, if QEMU has its modules compiled as dynamic objects to
be dlopen(2)'d rather than statically compiled into the QEMU binary,
QEMU will not accept [spice] directives through -readconfig. This is a
known issue with QEMU but has been effectively marked as WONTFIX because
-readconfig has sort-of been soft-deprecated [1] [2] [3].
In the meantime, just switch to the -spice commandline since this
appears to only affect modules rather than core QEMU options.
[1]: https://bugs.launchpad.net/qemu/+bug/1910696
[2]: https://lists.gnu.org/archive/html/qemu-devel/2020-11/msg02934.html
[3]: https://bugzilla.suse.com/show_bug.cgi?id=1181549#c11
Fixes #8416
Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>
=> vm/qemu: configure spice using -spice parameter

lxc/config_trust.go, lxc/remote.go, lxd-p2c/utils.go, lxd/api_cluster_test.go, lxd/certificates.go, lxd/cluster/connect.go, lxd/daemon.go, lxd/db/certificates.go, lxd/util/encryption.go, shared/api/certificate.go
- Add constants and helper functions for converting between API and DB type representations.
- Ensure locking is used when accessing cached certificates by way of getTrustedCertificates function.
- Store cached certificates keyed by type to allow retrieval of specific types only.
- Continues to authenticate access using only client certificate type (for now).
- Adds LoadServerCert for future use.
=> Cluster: Introduce server trusted certificate type

test/suites/container_devices_nic_bridged_acl.sh
This is apparently not available on the busybox nc version in later versions of ubuntu.
=> tests: Removes use of -v flag for nc inside busybox

lxd/network/driver_bridge.go
So that `ipv6.address = ["", "none"]` implicitly disables `ipv6.firewall`.
Also applies similar logic for `ipv4.address` for `ipv4.firewall`, except that if `bridge.mode=fan` then we assume `ipv4.address` is enabled even if not set.
Fixes #8705
=> Network: Don't attempt to setup bridge ipv6 firewall when no ipv6.address

lxd/instance/drivers/qmp/commands.go
query-cpus-fast breaks our ability to pin the various PIDs as those
aren't returned.
This reverts commit 200288b76c3fa129ac8cf30aad6bed954bf9d655.
=> Revert "lxd/instance/qemu: Move to query-cpus-fast"

lxd/images.go
I've run into a cluster where a bunch of VM images were incorrectly
recorded as container images. I believe that a combination of
auto-refresh and distribution is what caused the issue and that this
should fix it.
=> lxd/images: Specify image type during distribution

client/connection.go, lxd/db/operations.go, lxd/images.go, lxd/operations.go, lxd/operations/operations.go
Optimises process by only querying the remote members that are online and have running operations of the desired type (`OperationImageToken`).
=> Operations: Updates imageValidSecret to check across all cluster members not just local operations

lxd/instance/drivers/qmp/commands.go
Let's try migrating again, this time updating the struct to match the
renamed fields.
=> lxd/instance/qmp: Switch to query-cpus-fast

doc/api-extensions.md, lxd/cluster/events.go, lxd/cluster/heartbeat.go, lxd/daemon.go, lxd/db/node.go, lxd/db/query/retry.go, lxd/images.go, lxd/task/group.go, lxd/task/group_test.go, lxd/task/start.go, lxd/task/task_test.go, test/suites/clustering.sh
In PR https://github.com/lxc/lxd/pull/8690 we reduced the amount of adhoc heartbeats that were generated by not forcefully reconnecting to cluster members when trying to get a list of cluster members and their statuses. This has highlighted some scenarios where the existing heartbeat logic was weak:
1. If a node was removed during a heartbeat round, then when we attempted to update the heartbeat time in the nodes table it would fail (as the row had been removed) - which failed the whole transaction meaning all nodes didn't have their heartbeat time updated for that round.
2. Sometimes the heartbeat transaction to update the nodes table would fail due to a write lock, have added retry mechanism.
3. Pass the daemon's context into the heartbeat task to allow clean cancellation on shutdown. …
=> Cluster: Fix issues with heartbeats now that we are relying on them more for accurate timings

lxd/main_init_interactive.go
This avoids triggering a 2nd attempt at setting up trust in clusterPutJoin which would fail when using a single-use join token as a password. There's no need for a 2nd attempt at setting up trust when in interactive init with trust password.
=> Cluster: Clear config.Cluster.ClusterPassword after setting up trust during interactive init

lxd/api_1.0.go, lxd/cluster/config.go, lxd/cluster/gateway.go, lxd/cluster/heartbeat.go, lxd/daemon.go, lxd/images.go
Also:
- Use daemon context for heartbeat requests.
- Improve logging and error messages.
This improves test reliability, although we are still seeing a few intermittent failures (which @MathieuBordere believes is caused by https://github.com/canonical/raft/issues/203 in Dqlite). This would seem to make sense because the tests that fail now are all inspecting the `Database` column from `lxc cluster ls`, which indicates the Dqlite role, rather than failing on a LXD heartbeat related status check.
=> Cluster: Make heartbeat interval half of offline threshold

lxd/cluster/heartbeat.go
- Don't log starting heartbeat request twice (`HeartbeatNode` does this already).
- Log as a warning any failed heartbeat requests.
=> Cluster heartbeat: Logging improvements

lxd/network/openvswitch/ovn.go, lxd/network/openvswitch/ovs.go, lxd/network/openvswitch/shared.go
OVS tools dynamically change the quoting they use based on whether the value starts with a number or not.
When the OVS system-id doesn't start with a number it doesn't get quoted which upset the strconv.Unquote() function being used our parser. So now we detect this scenario and return the value unprocessed if it doesn't start with a `"`.
Fixes https://discuss.linuxcontainers.org/t/error-creating-ovn-network/11034
=> Network: Handle non-uuid OVS system-ids for OVN networks

lxd/api_cluster.go, lxd/cluster/gateway.go, lxd/daemon.go, lxd/images.go
This fixes an issue when a raft member was removed that didn't immediately trigger a role rebalance causing out of date role info in the local raft_nodes table.
Also moves to contextual logging for some cluster related sections.
=> Cluster: Rebalance roles when removing raft member

lxd/cluster/gateway.go, lxd/cluster/heartbeat.go, lxd/cluster/heartbeat_test.go, lxd/daemon_images.go
This fixes an issue where when a member joins during a regular heartbeat round, if the offline_threshold (and hence the heartbeat interval) is long, the heartbeats are spread over the heartbeat interval round time. However the member status is only read from the database at the start of the round, and so the heartbeat round can be inadvertently broadcasting stale member information, which can lead to incorrect decisions being made on the other members as they receive this stale data.
The fix is to cancel and restart any ongoing heartbeat round when a member change heartbeat notification is received by the leader.
=> Cluster: Cancel ongoing heartbeat and restart round when notification heartbeat comes from non-leader member

lxd/device/nic_physical.go, lxd/device/nic_sriov.go, lxd/device/pci/pci.go, lxd/instance/drivers/driver_qemu.go, lxd/instance/drivers/driver_qemu_templates.go, lxd/instance/drivers/qmp/commands.go
This still pre-allocates pci ports using static config, but hopefully we can replace that with a QMP based approach next.
Removes the `-chroot` flag usage to simplify adding NICs via QMP without needing to copy devices into a VM specific chroot and mounting `/sys` in it. We guard the qemu process using apparmor which should be sufficient.
Tested with https://github.com/lxc/lxc-ci/pull/280 with qemu version in focal and in snap package (there are differences between some of the QMP command argument data types they accept which required finding a common denominator).
=> VM: Switch to QMP for adding NICs

lxd/cluster/heartbeat.go
To return db.DefaultOfflineThreshold as time.Duration if g.HeartbeatOfflineThreshold not set.
=> Cluster: Fix heartbeatInterval()

doc/environment.md
There is no information in environment section of the documentation about LXD_CONF and LXD_GLOBAL_CONF environment variables. This PR fixes this.
Signed-off-by: Piotr Resztak <piotr.resztak@gmail.com>
=> doc/environment: Documents LXD_CONF and LXD_GLOBAL_CONF env vars

lxd/instance/drivers/driver_qemu.go
`writeInstanceData` in `driver_qemu.go` doesn't respect empty security.devlxd value which is by default true. This is fix for that.
Signed-off-by: Piotr Resztak <piotr.resztak@gmail.com>
=> lxd/instance/qemu: Support for security.devlxd default (true) value

lxd/instance/drivers/driver_qemu.go
This should restore the old functionality, that only wrote `multifunction` to config if enabled, otherwise it defaults to off.
=> VM: Don't set multifunction=off as this upsets ccw driver

lxd/device/device_utils_network.go, lxd/device/infiniband_physical.go, lxd/device/infiniband_sriov.go, lxd/device/nic_macvlan.go, lxd/device/nic_physical.go, lxd/device/nic_sriov.go, lxd/ip/link.go, lxd/network/driver_bridge.go, lxd/network/driver_ovn.go, lxd/network/driver_physical.go, lxd/network/network_utils.go, lxd/network/network_utils_sriov.go
Also cleans up "Mtu" to "MTU" in `ip` package, and removes unnecessary `InterfaceSetMTU` function.
=> Network: Prevent using interface with global unicast IPs for physical network and OVN physical uplink

lxc/cluster.go, lxd/operations.go
When the joining member was requesting join to a member that didn't have the local join-token operation, the method used for iterating the remote result sets was incorrect and causing the last operation to be referenced as all items in the remote list, causing joining to fail.
=> Cluster: Fix join tokens

lxd/api_cluster.go, lxd/certificates.go, lxd/images.go, lxd/main_init_interactive.go, lxd/operations/operations.go
- Don't attempt to connect all cluster members in join token to get cluster certificate, stop at first successful one.
- Delete any existing join tokens for requested new member name when adding join token - to ensure we only ever have 1 active join token per potential new member.
- Add some structured logging.
=> Cluster: Join token improvements

lxd/instance/drivers/driver_qemu.go, lxd/network/driver_bridge.go, shared/subprocess/bgpm_test.go, shared/subprocess/proc.go
Currently LXD's logs won't show if dnsmasq started and then quickly exits due to conflicting socket listeners.
This adds a 500ms wait and then checks for dnsmasq process exiting, and if it does, then logs an error.
Inspired by https://discuss.linuxcontainers.org/t/dhcp-stoped-working/11114
=> Network: Check if dnsmasq has prematurely exited during startup and log an error if so

lxd/daemon_images.go, lxd/images.go, lxd/instances_post.go
- Maintain image public indicator when syncing images between cluster members.
- Refactor ImageDownload to avoid unwieldy long argument list.
=> Image: Improve image distribution

lxd-agent/main_agent.go, lxd/device/disk.go, lxd/instance/drivers/driver_qemu.go, lxd/instance/drivers/driver_qemu_templates.go
- Use 9p virtfs-proxy-helper even when `readonly=true` (fixes #8809 by avoiding qemu apparmor profile).
- Log why virtio-fs isn't being used - rather than a generic, and potentially inaccurate warning.
- Don't use virtio-fs if disk device config has readonly=true (as doesn't appear to be supported). Fallback to 9p instead.
- Improve lxd-agent startup process by waiting for `/dev/vsock` to appear and activating listener before setting up agent mounts. This avoid prematurely exiting (and getting systemd to restart lxd-agent) which was causing the virtiofs mount to be replaced (mounted over) by the fallback 9p mount.
- Adds support for readonly block device disks (previously the `readonly` property was silently ignored).
=> VM: Fix readonly disk shares

lxd/device/disk.go, lxd/instance/drivers/driver_qemu.go
- Ensure bootindex is generated in a stable manner in `deviceBootPriorities()`, as the boot index is used for SCSI-ID which in turn influences disk device name in /dev.
- Move the disk device virtiofsd socket path into the instance's devices directory (to align with where the pid files are stored),  as we don't start qemu with chroot option anymore, so that is not a blocker.
- Stop relying on duplicate path logic in disk device and qemu driver packages to detect virtiofsd socket path, and instead pass the socket path via a mount option (using an option name that is defined as a shared constant to clearly show dependencies).
- Update qemu driver's d.devPaths with the virtiofsd socket path when setting up qemu config file so that its not blocked by apparmor.
=> VM: Ensure bootindex ordering is stable and consistent

lxd/network/driver_ovn.go, lxd/network/driver_physical.go
- If an OVN network uses a physical network who's parent is a bridge, then it is valid for the parent interface to have IPs configured.
- Only prevent OVN networks from using the physical network is the parent isn't a bridge.
- Fixes OVN tests.
=> Network: Relax physical network parent IP checks

lxd/apparmor/instance.go, lxd/apparmor/instance_qemu.go, lxd/device/device_utils_disk.go, lxd/device/disk.go, lxd/device/errors.go, lxd/instance/drivers/driver_qemu.go, lxd/storage/drivers/driver_zfs_utils.go
Removes duplicate virtiofsd start and stop logic to centralise the knowledge for when virtiofsd should be used, rather than duplicating it in both the qemu driver and the disk device packages.
- Also centralises the variable generation for the config drive's virtiofsd socket and pid paths.
- Also explicitly allows the qemu process r/w access to the instance's devices directory. This is to allow access to the virtiofsd socket, and in the future bind-mounted disk directories themselves. I've allowed access to the whole directory rather than explicitly adding boot-time rules individually to allow us to support hot plugged disks in the future.
=> VM: Deduplicate the virtiofsd start and stop logic and simplify disk apparmor rules

lxc/cluster.go
=> lxc cluster add shouldn't have any alias

lxd/device/device_utils_disk.go, lxd/device/disk.go, lxd/instance/drivers/driver_qemu.go, lxd/storage/drivers/driver_zfs_volumes.go
This works around the lack of read-only support in virtio-fs and provides an additional layer of protection for 9p shares.
=> VM: Create bind mount of config drive and instance disk devices for exporting via 9p and virtiofsd

lxd-agent/exec.go, lxd/api_cluster.go, lxd/api_project.go, lxd/backup.go, lxd/backup/backup_utils.go, lxd/events/events.go, lxd/images.go, lxd/instance.go, lxd/instance/drivers/driver_common.go, lxd/instance_backup.go, lxd/instance_console.go, lxd/instance_delete.go, lxd/instance_exec.go, lxd/instance_instance_types.go, lxd/instance_post.go, lxd/instance_put.go, lxd/instance_snapshot.go, lxd/instance_state.go, lxd/instances_post.go, lxd/instances_put.go, lxd/logging.go, lxd/migrate_instance.go, lxd/network/driver_common.go, lxd/operations/operations.go, lxd/storage_volumes.go, lxd/storage_volumes_backup.go, lxd/storage_volumes_snapshot.go, lxd/warnings.go, shared/api/event.go
I'm sorry. I accidentially closed the original pull request, and can't reopen it -> https://github.com/lxc/lxd/pull/8695.
maybe resolves #8011 
I'm aware tthat some attributes on Requestor are duplicate in EventLifecycle. I'm not entirely shure which attributes are relevant. I probably should implement pragmatic solution instead flexibility thats not really needed here. I also got lost pressings buttons on golang : ) 
Signed-off-by: Sascha Bast <sash@mischkonsum.org>
=> lxd/lxd: Record requestor as part of lifecycle events

lxd/instances_post.go, lxd/storage/backend_lxd.go, lxd/storage/drivers/driver_zfs_volumes.go
This way if a failure occurs after CreateVolumeFromBackup is finished, and its returned revert hook is run, the volume's internal mount counter is correctly cleared. This was not leaving an orphaned mount because the revert hook was already deleting the volume, however it was leaving an internal mount counter.
This prevents future import attempts from failing the post import volume resize due to In Use errors caused by the left over mount counter.
Fixes issue reported from https://discuss.linuxcontainers.org/t/why-does-lxd-kill-this-import-process-what-does-error-post-hook-in-use-even-mean-and-how-do-i-solve-it/11222/22 
=> Storage: Include unmount action in the ZFS revert hook returned from CreateVolumeFromBackup

lxd/instance/drivers/driver_qemu.go
- Wait for QEMU process to end before considering VM stopped - to avoid racing the start process when restarting. This should prevent issues caused when the `onStop()` hook is still in the process of cleaning up devices when the VM is being started again.
- Also adds some instance start/stop debug logging.
=> VM: Wait for QEMU process to end before considering VM stopped

lxd/instance/drivers/driver_qemu.go
To allow time for flushing pending I/O to disk.
Also reset the operation afterwards to give more time for operation to complete.
=> VM: Increase max wait time for qemu process to exit

lxd/cluster/heartbeat.go, lxd/instance/drivers/driver_qemu.go
This is because the call to `db.OpenCluster()` (https://github.com/lxc/lxd/blob/966cf0739e1015acf14f21b0b5a303f881c1e80b/lxd/daemon.go#L1016) on start up will return `db.ErrSomeNodesAreBehind` when not all cluster members are up to date, and this is returned before the call to `cluster.NodeID(nodeID)` inside `db.OpenCluster()` which is used by the `tx.GetLocalNodeAddress()` function to get the local node address in order to skip sending a heartbeat request to ourselves.
Otherwise we will potentially end up sending heartbeat to ourself in a loop as the dqlite connection to itself is periodically reconnected as it waits for the schema version to match on all cluster members, this triggers an impromptu heartbeat, which if initiated before the DB connections active causes the resulting …
=> Cluster: Get local cluster address from local DB and avoid sending heartbeats to ourself during cluster upgrade

doc/index.md
Signed-off-by: Mathieu Borderé <mathieu.bordere@canonical.com>
=> README: Add liblz4-dev dependency when building from source

doc/api-extensions.md, doc/server.md, lxd/api_1.0.go, lxd/cluster/config.go, lxd/daemon.go, lxd/endpoints/network.go, shared/version/api.go
Resolves #8757
@stgraber, this is implemented a little bit different then your implementation in https://github.com/nsec/askgod. I used `proxyproto.NewConn()` method because we need to know incoming remote address to check is it in `core.https_trusted_proxy` config. I'm also not quite sure if I'm not miss something. I mean, I update proxy address when server is starting and also when network or cluster listeners are changed. `proxyproto.newConn()` as a second argument takes timeout value (ProxyHeaderTimeout). This value should by configurable or should we use some static value?
=> HAProxy protocol header support

lxd/device/nic_bridged.go, lxd/device/nic_macvlan.go, lxd/device/nic_p2p.go, lxd/device/nic_physical.go, lxd/device/nic_sriov.go, lxd/instance/drivers/driver_common.go, lxd/instance/drivers/driver_qemu.go, lxd/instance/drivers/driver_qemu_bus.go, lxd/instance/drivers/driver_qemu_templates.go, lxd/instance/drivers/qmp/commands.go
This PR adds hot plug and hot unplug support for VM NIC devices.
QEMU does not currently support hotplugging `pcie-root-port` devices (which are required in order to connect a NIC device to) so in order to support hotplugging we now pre-create 4 "free" PCI ports (in addition to the devices present at boot time), these free slots are what new devices are hotplugged into.
However we do not just find the next free slot and plug the NIC into it. This is because NIC device names inside the VM guest are derived from their PCI slot location (i.e `enp5s0`) and so if we just found the next free slot to hotplug a NIC into then its name would likely change when it was rebooted (as it could be reordered differently at boot time based on the LXD name of the device).
So in order to support some …
=> VM: NIC hotplug

lxd/resources/storage.go
Non-ATA drives don't expose their RPMs through udev.
As we don't want to directly have to poke the drives, we instead just
indicate that they are rotating by setting the RPM to 1 if it's
currently 0 and if the kernel recorded them as spinning.
Closes #8718
=> lxd/resources: Set RPM to 1 instead of 0 when rotational

lxd/daemon.go, lxd/instance/drivers/driver_lxc.go
Some versions of LXC come with support for idmapped rootfs but do not
support idmapped mount entries. Let's not support those LXC version and
only support the ones that have full support.
Link: https://github.com/lxc/lxd/issues/8870
=> lxd: check for new idmapped mounts extension in LXC

lxd/instance/drivers/driver_qemu.go, lxd/storage/drivers/generic_vfs.go
Otherwise when a non-optimized VM is imported it won't start due to a non-empty config.mount dir.
=> Instance: Exclude VM config.mount directory from backup exports

lxd/storage/drivers/driver_btrfs_volumes.go, lxd/storage/drivers/driver_ceph_volumes.go, lxd/storage/drivers/driver_common.go, lxd/storage/drivers/driver_dir_volumes.go, lxd/storage/drivers/driver_lvm_volumes.go, lxd/storage/drivers/driver_mock.go, lxd/storage/drivers/utils.go
This is required, at least for LVM, in certain circumstances, as the pre-resize checks run by resize2fs are not always accurate and can prevent successful resize.
For example in the reported forum thread, a container with a 2GB LVM disk, of which 1.2GB was showing as used inside the container, when trying to resize after import from 10GB to 2GB caused the error:
```
resize2fs: New size smaller than minimum (548890)
```
With a block size of 4096, that indicates resize2fs thinks the minimum size is 2248253440 bytes (2.248GB).
The resize2fs manual says that the minimum size is an estimate:
"-P Print an estimate of the number of file system blocks in the file system if it is shrunk using resize2fs's -M option and then exit."
I found that if we skipped doing manual resize using resize2fs and …
=> Storage: Disable filesystem resize safety checks when importing containers

lxd/api_internal.go, lxd/instance.go, lxd/instance/drivers/driver_common.go, lxd/instance/drivers/driver_lxc.go, lxd/instance/drivers/driver_qemu.go, lxd/instance/drivers/load.go, lxd/instance/instance_utils.go, lxd/instance_test.go, lxd/instances_post.go, lxd/migrate_instance.go, lxd/snapshot_common_test.go
This PR improves the revert situation when creating instances such that if the storage pool volume create fails we do not trigger a full instance delete. This is so that if the pool volume creation failed due to an existing conflicting volume, the revert step won't then delete that existing volume (as it would if we triggered an instance delete action).
Instead this PR moves to passing around a top-level reverter which can be used to add more nuanced specific reversion steps rather than using the blunt tool of `instance.Delete()`.
Fixes #8861
=> Storage: Avoid deleting existing storage volume on conflict during create

lxd/network/network_utils.go, lxd/network/network_utils_test.go
Go tip introduces this change which broke the tests:
https://github.com/golang/go/commit/d3e3d03666bbd8784007bbb78a75864aac786967
Also fixes an error reporting bug in the same function.
=> Network: Fix ipRange function due to net.ParseIP changes

lxd/db/warnings_types.go, lxd/network/driver_bridge.go
- lxd/db: Add WarningLargerIPv6PrefixThanSupported
- lxd/network: Create warning if IPv6 prefix is too large
=> Add warning for networks with IPv6 prefix larger than /64

lxd/revert/revert.go, lxd/storage/backend_lxd.go, lxd/storage/backend_mock.go, lxd/storage/drivers/driver_btrfs_volumes.go, lxd/storage/drivers/driver_ceph_volumes.go, lxd/storage/drivers/driver_cephfs_volumes.go, lxd/storage/drivers/driver_common.go, lxd/storage/drivers/driver_dir_volumes.go, lxd/storage/drivers/driver_lvm_utils.go, lxd/storage/drivers/driver_lvm_volumes.go, lxd/storage/drivers/driver_mock.go, lxd/storage/drivers/driver_types.go, lxd/storage/drivers/driver_zfs_volumes.go, lxd/storage/drivers/generic_vfs.go, lxd/storage/drivers/interface.go, lxd/storage/drivers/utils.go, lxd/storage/drivers/volume.go, lxd/storage/pool_interface.go, lxd/storage/utils.go
It was becoming increasingly difficult to track how the `allowUnsafeResize` property on `Volume` was being used.
So I thought it would be easier to reason about how it is being used by having each affected function have an `allowUnsafeResize` argument instead so we can more easily see where it is being used and set to true.
Also introduces `revert.Hook` type and `VolumePostHook` type for reader clarity.
Also reverts most of the changes from https://github.com/lxc/lxd/pull/8872 and https://github.com/lxc/lxd/pull/8864 and instead moves the `allowUnsafeResize` enabling for container imports into `CreateInstanceFromBackup`. I kept it in the backendLXD in the end so that the post-resize step is still applied to optimized volumes as well (in case the effective size of the root disk when taking …
=> Storage: Remove vol.allowUnsafeResize var in place of per-function bool arguments instead

lxd/main_init_interactive.go
We shouldn't push for a trust password now that we can add new cluster
members without it.
=> lxd/init: Update for token based join

lxd/storage/drivers/driver_zfs_volumes.go
This was causing the filesystem volume to be left mounted and the mount counter was not decremented after import.
Which could then later causes issue if volume needed to be unmounted.
Unlike other storage drivers, the ZFS driver was recursively calling `CreateVolumeFromBackup` to handle the VM filesystem volume.
This commit changes that so it handles the VM filesystem volume directly.
This way we can then generate only a single post hook and also the revert in the post hook is correctly handled too (which was also missing before).
=> Storage: Fix bug with ZFS VM optimized import not returning filesystem volume post hook

doc/index.md
Today compilation was not possible with the instruction from the README.
I added the command that was missing
=> lxd: update instructions for compilation from a release tarball

lxd/device/nic_bridged.go, lxd/firewall/drivers/drivers_nftables.go, lxd/firewall/drivers/drivers_xtables.go, lxd/firewall/firewall_interface.go, test/suites/container_devices_nic_bridged_filtering.sh
This requires the user specifies which IP the NIC should be using by setting `ipv{n}.address` on the NIC.
Fixes #7477
Closes #8849
=> Network: Add support for using bridged NIC IP filtering on unmanaged parent bridges

lxd/api_project.go, test/suites/projects.sh
We use underscore as the delimiter between project name and storage volume name and we need to be able to recover the two parts from the underlying storage volume name for the new `lxd recover` tool (see https://discuss.linuxcontainers.org/t/lxd-recover-tool/11296).
Also fixes bug where when renaming a project, only the current name was validated not the new name, effectively allowing the new and existing name validation policy to be bypassed for project names.
=> Projects: Prevent the use of underscores in new project names

lxd/api_project.go, lxd/cluster/config.go, lxd/network/driver_bridge.go, lxd/network/driver_ovn.go, lxd/storage/drivers/driver_ceph.go, lxd/storage/drivers/driver_lvm.go, lxd/storage/drivers/driver_lvm_volumes.go, lxd/storage/utils.go, lxd/storage_pools_config.go, shared/instance.go, shared/validate/validate.go
And don't allow empty value to pass validation, as this is confusing and not expected.
Wraps the existing use of `IsOneOf` where the allowed values did not include `""` with `validate.Optional()` to keep existing behaviour.
=> Validate: Make IsOneOf only allow the specified values
