lxd/iptables/xtables.go

lxd/iptables: Fix ebtables handling regression

---

lxd/storage.go
lxd/storage/backend_lxd.go
lxd/storage/backend_mock.go
lxd/storage/drivers/driver_cephfs.go
lxd/storage/drivers/driver_dir.go
lxd/storage/drivers/interface.go
lxd/storage/load.go
lxd/storage/pool_interface.go
lxd/storage_pools_utils.go

lxd/storage: Port remaining functions

---

test/suites/static_analysis.sh

Signed-off-by: Shreyas Sood <shreyassood@gmail.com>

lxd/{test,cgroup}: Add cgroup package to static analysis tests

---

lxd/main_forkdns.go

lxd/main/forkdns: Adds recursion desired comment that got removed during refactor

---

lxd/cgroup/init.go
lxd/daemon.go

daemon: log cgroup layout on startup

---

lxd/instance/qemu/vm_qemu.go

Ensures dnsmasq host entries are created with generated MAC address.

VM: Implements deviceAdd and deviceRemove

---

shared/simplestreams/simplestreams.go

shared/simplestreams: Only write cache if configured

---

lxd/instance/qemu/vm_qemu.go
lxd/networks.go
lxd/sys/os.go

To try and run as either lxd or nobody user.

VM: Adds -runas flag to qemu

---

lxd/db/cluster/schema.go
lxd/db/cluster/update.go

lxd/db: Add missing unique key

---

lxd/db/cluster/schema.go
lxd/db/cluster/update.go

lxd/db: Add upgrade logic for UNIQUE fix

---

lxd/cgroup/init.go

lxc/cgroup: Fix bad error handling

---

lxd/images.go
lxd/storage/backend_lxd.go
lxd/storage/drivers/driver_cgo.go
lxd/storage/drivers/utils.go
lxd/storage/utils.go
lxd/storage_btrfs.go
lxd/storage_ceph.go
lxd/storage_ceph_utils.go
lxd/storage_lvm.go
lxd/storage_lvm_utils.go

This is pushing some of the bits from the btrfs pull request with minor edits as well as fixes I've had to prepare to get clean test runs with the old drivers removed.

Storage fixes and refactoring

---

doc/networks.md

Trying to flesh out the Network documentation a bit.

Net bridge documentation

---

shared/subprocess/bgpm_test.go
shared/subprocess/manager.go
shared/subprocess/proc.go
shared/subprocess/testscript/exit1.sh
shared/subprocess/testscript/signal.sh
shared/subprocess/testscript/stoprestart.sh
test/suites/static_analysis.sh

We created a package called subprocess, under the shared directory for process management to address the issue: #5826 
Some new features 
* You can start a process and configure it in Go using 'NewProcess(..)' 
* You can manage this process using functions like `Pid(), Stop(), Start(), Restart(), Reload(), Save(path string), Signal(int64), Wait() (int64, error)` 
* You can now serialize and deserialize configurations for a process by calling 'Save()' and 'ImportProcess(..)'

Implementing Background Process Manager

---

lxd/cgroup/abstraction.go
lxd/container_lxc.go

Added the rest of controllers to support different properties and controllers for issue #6305

Replace all CGroup{G,S} to use abstraction in container_lxc.go

---

lxd/storage/backend_lxd.go
lxd/storage/drivers/driver_cephfs.go
lxd/storage/drivers/driver_common.go
lxd/storage/drivers/driver_dir_volumes.go
shared/fs_32bit.go
shared/fs_64bit.go
shared/util_linux.go

This batch fixes some mount/unmount issues with btrfs and moves more logic to common to reduce the size of the upcoming btrfs driver.

More storage fixes and cleanups

---

doc/dev-lxd.md
doc/rest-api.md

The comments aren't supported in JSON, that's why there are shown as red.
An option may be to use an other block code, like YAML (or something else, don't know if there is JSON5).

Use JSON markdown blocks in docs

---

lxd/cgroup/init.go

When we detect that this is a pure cgroup2 layout stop parsing for any
additional mountpoints. Any additional mountpoints are likely a bug.
Closes #6655.

cgroup: shortcut cgroup2 only layouts

---

lxd/cgroup/init.go

cgroups: detect blkio.bfq.weight knob

---

doc/networks.md

Closes #6653
Suggested-by: Marcos Dione

doc/networks: Clarify raw.dnsmasq

---

lxc-to-lxd/utils.go
lxc/remote.go
lxd-p2c/utils.go
lxd/api_cluster.go
lxd/cluster/connect.go
lxd/main_init_interactive.go
shared/cert.go

Always set the user-agent string

---

doc/instances.md
lxd/device/nic_routed.go
test/suites/container_devices_nic_routed.sh

Routed NIC adds detection for proxy_ndp on all interfaces

---

lxd/storage/backend_lxd.go

Storage updates pool create to use revert package

---

lxd/container_lxc.go
lxd/revert/revert.go
lxd/storage/backend_lxd.go
lxd/storage/drivers/driver_dir_volumes.go
lxd/storage/drivers/errors.go
lxd/storage/drivers/generic.go
lxd/storage/drivers/utils.go
lxd/storage/drivers/volume.go

Assorted collection of small changes I've made as part of doing the LVM driver.

Storage tweaks

---

lxd/images.go
lxd/main_test.go
lxd/patches.go
lxd/storage.go
lxd/storage/backend_lxd.go
lxd/storage/drivers/errors.go
lxd/storage_pools.go
lxd/storage_pools_utils.go
test/suites/clustering.sh

Support deleting snapshots during restore & storage fixes

---

lxd/storage/backend_lxd.go
lxd/storage/drivers/volume.go
lxd/storage/utils.go

Adds detection of cached image volume filesystem differing from current pool volume.block.filesystem and regenerates new cached volume using new filesystem.

Storage EnsureImage filesystem regeneration

---

lxd/instance/qemu/vm_qemu.go

lxd/qemu: Fix multiple NICs

---

lxd/storage/drivers/utils.go

Fixes some storage resize issues and adds helper functions for UUID regeneration.

Storage resize and UUID regeneration

---

lxd/storage/backend_lxd.go

Ensures that if an instance's root disk config has a size property this is applied on import.
Fixes #6687

Storage: Applies root disk quota as part of backup import post hook

---

lxd/storage/backend_lxd.go

Storage: Triggers backup file update during BackupInstance and RenameInstanceSnapshot

---

lxd/storage/drivers/generic.go

Based on comment https://github.com/lxc/lxd/pull/6688#discussion_r365398876 from @stgraber wherever a volume is mounted and then modified via rsync or unpacking a tarball, after that the mounted volume has EnsureMountPath run on it to ensure permissions are set correctly.

Storage: Adds EnsureMountPath calls after mounting volumes in generic functions

---

lxd/migrate_container.go

Migrate: Merges duplicate multi sync logic and adds comments

---

lxd/device/disk.go

Defer instance type check until start time for cloud-init config disk drive.
As currently instance type is always container when running profile validation.

Device: Allows cloud-init config drive to be added to profiles used by VMs

---

lxd/storage/drivers/driver_zfs_utils.go

lxd/storage/zfs: Fix set on 0.6

---

doc/api-extensions.md
lxc/cluster.go
lxd/api_cluster.go
lxd/cluster/heartbeat_test.go
lxd/cluster/membership.go
lxd/cluster/membership_test.go
lxd/containers_post.go
lxd/db/node.go
lxd/db/node_test.go
lxd/instance/instance_utils.go
shared/api/cluster.go
shared/version/api.go

Multi architecture clustering

---

lxd/util/net.go
lxd/util/net_test.go

lxd/util: IsAddressCovered takes into account host names

---

lxd/storage/backend_lxd.go
lxd/storage/drivers/driver_btrfs.go
lxd/storage/drivers/driver_zfs.go
lxd/storage/drivers/driver_zfs_volumes.go
lxd/storage/drivers/drivers_lvm.go
lxd/storage/drivers/drivers_lvm_utils.go
lxd/storage/drivers/drivers_lvm_volumes.go
lxd/storage/drivers/load.go
lxd/storage/drivers/utils.go
lxd/storage/utils.go
lxd/storage_ceph_utils.go
test/includes/storage.sh
test/suites/backup.sh
test/suites/storage.sh

- Implements new LVM driver for custom, image and container volumes only.

Storage: LVM driver

---

lxd/db/cluster/schema.go
lxd/db/cluster/update.go
lxd/patches.go

Fixes LXD 2.0 to 3.19 upgrade issues.

lxd/db: Ensure zfs.pool_name is set

---

lxd/instance/instance_utils.go

lxd/instances: Fix creation from simplestreams

---

lxd/container.go
lxd/container_snapshot.go
lxd/instance/qemu/vm_qemu.go
lxd/migration/migration_volumes.go
lxd/storage/backend_lxd.go
lxd/storage/drivers/driver_common.go
lxd/storage/drivers/drivers_lvm.go
lxd/storage/drivers/drivers_lvm_utils.go
lxd/storage/drivers/drivers_lvm_volumes.go

This implements VM support in LVM driver. Note VM qemu doesn't support all features yet so not all features implemented.

Storage: LVM VM support

---

lxd/daemon_images.go
lxd/db/db_internal_test.go
lxd/db/images.go

lxd/db: Fix multi-arch cached images

---

lxd/storage_volumes_utils.go
test/suites/clustering.sh

Fix broken validation logic upon ceph volume rename

---

lxd/storage/drivers/driver_btrfs.go

lxd/storage/btrfs: Fix usage inside containers

---

lxd/storage/backend_lxd.go
lxd/storage/drivers/driver_btrfs.go
lxd/storage/drivers/driver_cephfs.go
lxd/storage/drivers/driver_common.go
lxd/storage/drivers/driver_dir.go
lxd/storage/drivers/driver_dir_utils.go
lxd/storage/drivers/driver_lvm.go
lxd/storage/drivers/driver_lvm_volumes.go
lxd/storage/drivers/driver_zfs.go
lxd/storage/drivers/interface.go
lxd/storage/drivers/load.go
lxd/storage/load.go
lxd/storage/utils.go
lxd/storage_pools.go
lxd/storage_pools_config.go
shared/instance.go

Improves per-pool validation framework for new storage drivers.

Storage: validation

---

doc/api-extensions.md
doc/storage.md
lxd/storage/drivers/driver_lvm.go
lxd/storage/drivers/driver_lvm_utils.go
lxd/storage/drivers/driver_lvm_volumes.go
lxd/storage_pools_config.go
shared/version/api.go

Adds striping support to LVM driver
Fixes #5211

Storage: LVM striping

---

lxd/container.go
lxd/container_lxc.go
lxd/device/config/devices.go
lxd/device/disk.go
lxd/instance/instance_interface.go
lxd/instance/instance_utils.go
lxd/instance/qemu/vm_qemu.go
lxd/profiles.go
lxd/profiles_utils.go

Adds support for adding disk devices to VMs:
Usage: 
```
lxc config device add v1 sdb disk source=/dev/sdb
lxc config device add v1 sdb disk source=/home/my.iso
```

VM: Disk device

---

lxd-agent/main_agent.go

Periodically repopulates STARTED status into vserial ringbuffer so LXD can restablish agent status after LXD restarts.

lxd-agent: Fixes bug when agent not seen as started if LXD restarted

---

lxd/instance/drivers/driver_qemu.go

Given the number of repeated placeholders in some parts of the config, this makes it easier to read and less error prone.

VM: Switch to template pkg to generate qemu conf

---

lxd/container_exec.go
lxd/container_lxc.go
lxd/container_lxc_exec_cmd.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/drivers/driver_qemu_cmd.go
lxd/instance/instance_exec_cmd.go
lxd/instance/instance_interface.go

Adds `WindowResize` to `instance.Cmd` interface and then moves both containerLXC and qemu logic into their separate implementations.
Based on discussion https://github.com/lxc/lxd/commit/86c70c80d5f6a0665087c54dd7552361efc77f33#commitcomment-36877068

Instance: Exec window resize via instance.Cmd interface

---

lxd/device/nic_p2p.go

VM: Adds VM support to P2P NIC device

---

lxd/cluster/gateway.go
lxd/cluster/heartbeat.go
lxd/cluster/tls.go

Close http transports since they might keep connections around

---

lxd/main_daemon.go

lxd/daemon: Ignore SIGHUP

---

lxd/storage/drivers/driver_dir.go

lxd/storage/drivers/driver/dir: Adds HostPath support

---

lxd/patches.go
lxd/storage/drivers/driver_btrfs.go
lxd/storage/drivers/driver_cephfs.go
lxd/storage/drivers/driver_dir.go
lxd/storage/drivers/driver_lvm.go
lxd/storage/drivers/driver_zfs.go
lxd/storage/drivers/driver_zfs_patches.go

lxd/patches: Reset ZFS mountpoint/canmount

---

shared/simplestreams/sort.go

shared/simplestreams: Fix inconsistent sorting

---

doc/instances.md

Doc: Documents which device types can be used with which instance types

---

lxd/device/nic_sriov.go

Includes https://github.com/lxc/lxd/pull/6768

VM: Adds SR-IOV NIC support

---

lxd/dnsmasq/dnsmasq.go
lxd/main_forkdns.go
lxd/main_nsexec.go
lxd/networks.go
lxd/networks_utils.go
lxd/patches.go
shared/subprocess/bgpm_test.go
shared/subprocess/errors.go
shared/subprocess/manager.go
shared/subprocess/proc.go
shared/subprocess/testscript/exit1.sh
shared/subprocess/testscript/signal.sh
shared/subprocess/testscript/stoprestart.sh
test/suites/clustering.sh
test/suites/container_devices_nic_bridged_filtering.sh

Building on issue #5826 to use the new background proceess manager to refactor how dnsmasq and forkdns are processes are started or killed.

lxd: updated dnsmasq and forkdns to use new subprocess module

---

lxd/container.go
lxd/container_logs.go
lxd/container_lxc.go
lxd/containers_post.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/instance_utils.go
shared/instance.go
shared/util.go

Based on suggestion from https://discuss.linuxcontainers.org/t/two-suggestions-to-improve-first-impression-with-lxd-3-19/6645 this PR expands the suggests to improve instance name validation error messages to make them more helpful.
Also validates snapshot names.

Instance name validation improvements

---

doc/api-extensions.md
doc/instances.md
lxd/db/devices.go
lxd/device/device.go
lxd/device/device_utils_unix.go
lxd/device/device_utils_unix_hotplug_events.go
lxd/device/unix_hotplug.go
lxd/devices.go
shared/version/api.go

This is a rebased version of https://github.com/lxc/lxd/pull/6530 .

Uevent-based matching for unix-char and unix-block

---

doc/index.md

doc: Add libudev-dev dependency

---

lxd/container_backup.go
lxd/container_console.go
lxd/container_logs.go
lxd/container_snapshot.go

lxd/instances: Fix URLs to use /1.0/instances

---

lxd/device/nic_bridged.go

Required for IPv6 iptables filtering rules.

Bridged NIC: Load br_netfilter kernel module when using IPv6 filtering

---

lxd/device/unix_hotplug.go

For example:
ACTION=add
EVPATH=/devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1:1.0/0003:093A:2510.0003/input/input20
SUBSYSTEM=input
RODUCT=3/93a/2510/111
NAME="PixArt USB Optical Mouse"
PHYS="usb-0000:00:14.0-1/input0"
UNIQ=""
PROP=0
EV=17
KEY=70000 0 0 0 0
REL=903
MSC=10
MODALIAS=input:b0003v093Ap2510e0111-e0,1,2,4,k110,111,112,r0,1,8,B,am4,lsfw
SEQNUM=38896
USEC_INITIALIZED=64404346109
ID_INPUT=1
ID_INPUT_MOUSE=1
ID_VENDOR=PixArt
ID_VENDOR_ENC=PixArt
ID_VENDOR_ID=093a
ID_MODEL=USB_Optical_Mouse
ID_MODEL_ENC=USB\x20Optical\x20Mouse
ID_MODEL_ID=2510
ID_REVISION=0100
ID_SERIAL=PixArt_USB_Optical_Mouse
ID_TYPE=hid
ID_BUS=usb
ID_USB_INTERFACES=:030102:
ID_USB_INTERFACE_NUM=00
ID_USB_DRIVER=usbhid
.INPUT_CLASS=mouse
ID_PATH=pci-0000:00:14.0-usb-0:1:1.0
ID_PATH_TAG=pci-0000_00_14_0-usb-0_1_1_0 …

unix hotplug: skip devices without associated devpath or major/minor

---

lxc/console.go
lxc/exec.go
lxc/exec_unix.go
lxc/exec_windows.go
lxd/events/events.go
lxd/instance/drivers/driver_qemu.go
shared/netutils/network_linux.go
shared/network.go

Simplifies some of the websocket code.

Websocket: Uses gorilla helper functions rather than lower level functions

---

lxd/storage/backend_lxd.go
lxd/storage/drivers/driver_btrfs.go
lxd/storage/drivers/driver_cephfs.go
lxd/storage/drivers/driver_dir.go
lxd/storage/drivers/driver_lvm.go
lxd/storage/drivers/driver_types.go
lxd/storage/drivers/driver_zfs.go

lxd/storage: Add LocalStructure to Info

---

lxd/network/network_utils.go

lxd/networks: Consider IPv6 neighborhood entries

---

lxd/main_checkfeature.go
lxd/main_forkproxy.go
lxd/main_nsexec.go

lxd/main_checkfeature: improvements

---

lxd-agent/exec.go
lxd/container_exec.go
lxd/daemon.go
lxd/db/cluster/schema.go
lxd/db/cluster/update.go
lxd/instance/drivers/driver_qemu.go
lxd/patches.go
lxd/storage.go
lxd/storage/drivers/driver_lvm.go
lxd/storage/drivers/driver_zfs.go
shared/netutils/network_linux.go
shared/network.go

Includes https://github.com/lxc/lxd/pull/6832
When the lxc client's terminal exits, ensure we don't leak go routines on the LXD server and keep lxc client processes around by ensuring that the the websocket mirror is cleaned up.

VM: Exec hanging fixes

---

lxd/container_lxc.go
lxd/daemon.go
lxd/db/cluster/schema.go
lxd/db/cluster/update.go
lxd/device/config/devices.go
lxd/device/device_utils_network.go
lxd/device/infiniband.go
lxd/device/nic.go
lxd/device/nic_bridged.go
lxd/device/proxy.go
lxd/instance/drivers/driver_qemu.go
lxd/network/network_utils.go
lxd/networks.go
lxd/patches.go
lxd/storage.go
lxd/storage/drivers/driver_lvm.go
lxd/storage/drivers/driver_zfs.go
test/suites/container_devices_nic_bridged.sh

Includes https://github.com/lxc/lxd/pull/6832
- The "nictype" property shouldn't be allowed when "network=" is used
- Rename/deleting a network that's in use through "network=" should fail

Device: NIC network property tweaks

---

lxd/util/net_test.go

lxd/util: Fix IP/host tests on other distros

---

lxd/storage_pools.go

This checks all projects for attached volumes when attempting to
delete a storage pool.
This fixes #6697.

lxd: Fix error message when deleting storage pools

---

lxd/container_lxc.go

lxd/container: Protect file push/pull from shift

---

lxc/exec_unix.go
shared/util_linux_cgo.go

Fixes https://github.com/lxc/lxd/issues/6871

terminal fixes

---

shared/idmap/shift_linux.go

With this change I get:
Before:
```
root@wittgenstein|/var/lib/lxd/storage-pools/zfs/containers/f1/rootfs
> getfacl var/log/journal/
user::rwx
group::r-x
group:100004:r-x
mask::r-x
other::r-x
default:user::rwx
default:group::r-x
default:group:100004:r-x
default:mask::r-x
default:other::r-x
```
After Remapping:
```
root@wittgenstein|/var/lib/lxd/storage-pools/zfs/containers/f1/rootfs
> getfacl var/log/journal/
user::rwx
group::r-x
group:165540:r-x
mask::r-x
other::r-x
default:user::rwx
default:group::r-x
default:group:165540:r-x
default:mask::r-x
default:other::r-x
```

idmap:acl: don't add but update the acls

---

shared/util.go

shared: Fix HostPathFollow for stdin/stdout

---

Makefile

A fix for  #6886
Signed-off-by: Asterios Dimitriou <asterios@pci.gr>

Allow build with GNU Make 4.3

---

shared/osarch/architectures.go

Just adds definitions for mips, build tested

add mips architectures

---

doc/contributing.md

We need linefeed to display as bullets.

doc: tweak markdown format

---

lxd/instance/drivers/driver_qemu.go

lxd/vm: Use -sandbox

---

lxd/api_internal.go
lxd/main_import.go
lxd/storage/backend_lxd.go

Also:
- Adds project support to `lxd import`
- Cleans up import error messages
- Adds storage post-hook logging

Storage: Check for existing directory during pool create

---

shared/util.go

shared/util: Fix relative paths in HostPathFollow

---

lxd/containers_post.go

lxd/instances: Pick correct default type from URL

---

lxd/db/cluster/schema.go
lxd/db/cluster/update.go

lxd/db: Set ceph.user.name if missing

---

lxd/device/disk.go

lxd/vm: Fix disk files and snap

---

lxd/db/cluster/update.go

lxd/db: Fix ceph username in patch

---

lxd/db/db_internal_test.go

lxd/db: Revert 3da5aea1 fix, since in turn testify reverted the change

---

lxd/logging.go

lxd/logging: Handle projects in log expiry

---

lxd/main_init_auto.go
lxd/main_init_interactive.go
test/suites/init_interactive.sh

lxd/init: Use new network syntax

---

lxd/container_lxc.go

lxd/containers: Have findIdmap look at projects

---

lxd/patches.go
lxd/storage/drivers/driver_btrfs.go
lxd/storage/drivers/driver_ceph.go
lxd/storage/drivers/driver_cephfs.go
lxd/storage/drivers/driver_dir.go
lxd/storage/drivers/driver_lvm.go
lxd/storage/drivers/driver_zfs.go
lxd/storage/drivers/driver_zfs_patches.go

lxd/storage/zfs: Set volmode=none for VM datasets

---

lxc/project.go
po/bg.po
po/de.po
po/el.po
po/es.po
po/fa.po
po/fi.po
po/fr.po
po/hi.po
po/id.po
po/it.po
po/ja.po
po/ko.po
po/lxd.pot
po/nb_NO.po
po/nl.po
po/pa.po
po/pl.po
po/pt_BR.po
po/ru.po
po/sl.po
po/sr.po
po/sv.po
po/te.po
po/tr.po
po/uk.po
po/zh_Hans.po

Incorrect syntax, no space allowed
Edit:
Signed-off-by:  Brian Neumeyer bpneumey@oakland.edu

Removed Erroneous Space

---

lxd/logging.go

This allows non-log files to be kept, such as .monitor and .pid files used for VMs.

Logging: Updates log rotate to only remove .log files

---

lxd/patches.go
lxd/storage.go

lxd/patches: Updates patches to use new storage driver mount/unmount

---

scripts/bash/lxd-client

scripts: Fix syntax errror

---

lxd/storage/drivers/driver_lvm_utils.go

Storage: Dont format LVM block volumes with filesystem

---

lxd/storage/drivers/driver_zfs.go
lxd/storage/drivers/driver_zfs_patches.go

lxd/storage/zfs: Skip volmode on 0.6

---

lxd/container_lxc.go

lxc/containers: Fix cgns-less fallback

---

doc/api-extensions.md
doc/instances.md
lxd/cgroup/abstraction.go
lxd/cgroup/init.go
lxd/instance/drivers/driver_lxc.go
lxd/seccomp/seccomp.go
shared/instance.go
shared/version/api.go

add hugetlbfs and hugepages handling for containers

---

lxd/cluster/membership.go

Promote nodes if for whatever reason the n of voters drops below 3

---

lxd/api_internal.go
lxd/apparmor/apparmor.go
lxd/backup.go
lxd/backup/backup.go
lxd/container_backup.go
lxd/container_logs.go
lxd/container_post.go
lxd/device/disk.go
lxd/device/proxy.go
lxd/devlxd.go
lxd/dnsmasq/dnsmasq.go
lxd/firewall/drivers/drivers_nftables.go
lxd/firewall/drivers/drivers_xtables.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/logging.go
lxd/network/network_utils.go
lxd/patches_utils.go
lxd/project/project.go
lxd/project/project_test.go
lxd/storage/backend_lxd.go
lxd/storage/storage.go

Ready for custom volumes in projects.

Project: Rename Prefix() to Instance()

---

lxd/instance/drivers/driver_qemu.go

lxd/instance/drivers: Add trans=virtio to 9p mount

---

doc/api-extensions.md
doc/container-environment.md
doc/instances.md
doc/requirements.md

doc: Tweak markdown format for itemization

---

lxd/storage/drivers/driver_ceph_volumes.go

As discussed in #6953
I was unsure what the best way was to parse the JSON response, I decided to go for dedicated structs, I'm open to other options.

lxd/storage/ceph: Implement GetVolumeUsage

---

lxd/device/unix_hotplug.go
lxd/devices.go

unix-hotplug: fix device removal and zero padding

---

lxd/storage/drivers/driver_zfs.go

lxd/storage/zfs: Fix usage calculation

---

lxd/firewall/drivers/drivers_nftables.go
lxd/firewall/drivers/drivers_xtables.go

lxd/firewall: Don't create zombies

---

lxd/daemon.go
lxd/daemon_storage.go
lxd/patches.go
lxd/storage/backend_lxd_patches.go
lxd/storage/utils.go
lxd/storage_volumes.go
lxd/storage_volumes_snapshot.go
lxd/storage_volumes_utils.go

- Runs the patch before daemon storage is initialised.
- Handles renaming daemon storage symlink targets to renamed volume paths.

Storage: Updates custom volume rename patch to handle daemon storage

---

lxd/instance/drivers/driver_qemu.go
shared/util_linux_cgo.go

vm: console and exec fixes

---

lxd/backup.go
lxd/db/operations_types.go
lxd/instance.go

lxd: Add "instance" string where necessary

---

lxd/storage/drivers/driver_ceph_volumes.go

- Adds support for VM resizing.
- Consistently uses `%dB` for RBD volume `--size` argument, rather than a mix of `%dM` when resizing and `%dB` for new volumes.
- Adds checks for actual current block device size as part of logic to decide whether the new size is a shrink or grow operation.

Storage: Adds Ceph VM block resize support

---

doc/security.md

doc/security: Adds network security section

---

lxd/storage/utils.go

lxd/storage: Fix crash on VM unpack

---

lxd/include/memory_utils.h
lxd/main_checkfeature.go
lxd/main_forkfile.go
lxd/main_forkmount.go
lxd/main_forksyscall.go
lxd/main_forkuevent.go
lxd/main_nsexec.go
lxd/storage/drivers/utils_cgo.go
shared/idmap/shift_linux.go

cgo: fixes

---

lxd/storage/drivers/driver_ceph_volumes.go
lxd/storage/drivers/volume.go

lxd/storage/ceph: Fix ext4 shrinking

---

lxd/main_init_interactive.go

lxd/init: Don't offer dir as a remote backend

---

lxd/storage/drivers/driver_lvm_volumes.go

This bug was introduced in d782daf202cda0de0a88886e21aa056775024139 due to the way that VM snapshot LVs are named differently than container snapshot LVs.

Storage: Fixes LVM VM snapshot list

---

lxd/db/node.go

lxd/cluster: Ignore CEPH custom volumes on removal

---

lxd/storage_volumes_snapshot.go

lxd: Clean up logging for expired volume snapshots

---

doc/networks.md

This allows the local system to resolve all running
lxd containers, using the (by default) .lxd domain.  This will
work only if the local system is using systemd-resolved for DNS.
Signed-off-by: Dan Streetman <ddstreet@canonical.com>

lxd/network/network: tell systemd-resolved we can resolve .lxd

---

lxd/apparmor/apparmor.go
lxd/instance/drivers/driver_lxc.go

lxd/containers: Add configfs and tracefs

---

lxd/storage/drivers/driver_btrfs_volumes.go

Patch for https://github.com/lxc/lxd/issues/7062

btrfs quota to simulate total disk size

---

lxd/instance/drivers/driver_lxc.go

lxd/instance/drivers: Add custom volumes to disk state

---

lxd/storage/drivers/driver_zfs_volumes.go

lxd/storage/zfs: Fix deleted VM images restoration

---

lxd/instance/drivers/driver_lxc.go

lxd/containers: Emit lifecycle event on user shutdown

---

lxd/instance_exec.go

Should address https://discuss.linuxcontainers.org/t/lxd-crashed-via-panic/7198

Exec: Adds protection against clients reconnecting after exec has started

---

lxd/cgroup/init.go

cgroup/init: close controllers file

---

lxd/include/macro.h
lxd/main_forkexec.go

forkexec: tweak

---

lxd/storage/drivers/driver_ceph_volumes.go
lxd/storage/drivers/driver_zfs_volumes.go

lxd/storage/drivers/ceph: Re-create image snapshot

---

lxd/networks.go

Network: Fix network leases list for instances using "network" option

---

shared/idmap/idmapset_linux.go

shared/idmap: Skip empty subuid/subgid

---

doc/api-extensions.md
lxd/resources/pci.go
lxd/resources/resources.go
lxd/resources/usb.go
shared/api/resource.go
shared/usbid/load.go
shared/usbid/load_data.go
shared/usbid/parse.go
shared/usbid/types.go
shared/version/api.go
test/suites/static_analysis.sh

 Add USB and PCI devices to resources API

---

lxc/network.go
lxd/instance/drivers/driver_qemu.go
lxd/network/network_utils.go

Also improves host_name state reporting when using VM with lxd-agent running.

NIC Bridged: Use of network argument when detecting parent

---

lxd/storage/drivers/driver_zfs_volumes.go

As tarball creation will not create consistent backup when instance is running and files are being modified during backup, we avoid this by creating a snapshot of the main volume.
This is possible because ZFS allows us to create a snapshot quickly without freezing the main volume.

Storage: Take snapshot when backing up ZFS volumes

---

lxd/main_activateifneeded.go
test/suites/basic.sh

Extend checks for `activateifneeded`

---

lxd/storage/drivers/driver_btrfs_utils.go

lxd/storage/btrfs: Workaround permission issue

---

lxd/patches.go
test/suites/storage.sh

lxd/patches: Fix snapshot migration

---

lxd/storage/drivers/driver_btrfs_volumes.go
lxd/storage/drivers/driver_ceph_volumes.go
lxd/storage/drivers/driver_cephfs_volumes.go
lxd/storage/drivers/driver_dir_volumes.go
lxd/storage/drivers/driver_lvm_utils.go
lxd/storage/drivers/driver_lvm_volumes.go
lxd/storage/drivers/driver_zfs_volumes.go
lxd/storage/drivers/volume.go

Storage: Create snapshot mount path before mounting

---

lxd/storage/drivers/driver_ceph_volumes.go
lxd/storage/drivers/driver_lvm_volumes.go

- Removes block mode reporting for filesystem volumes (same as LVM driver, to avoid changing used reporting value whether instance is running or not). Now will only report usage when instance is running.
- Fixes cumulative block level reporting for block volumes.
- Adds block level CoW reporting for snapshot volumes (both filesystem and block volumes).

Storage: ceph snapshot usage

---

lxd/main_forkzfs.go
lxd/main_nsexec.go

lxd/main: Move forkzfs mntns to cgo

---

doc/networks.md

doc/networks: Adds note about firewalld and DHCP/DNS

---

lxd/device/nic_routed.go

Related to https://github.com/lxc/lxd/issues/7152

NIC Routed: Improves VLAN validation of sysctl settings

---

lxd/storage/backend_lxd.go
lxd/storage/drivers/driver_zfs_volumes.go
lxd/storage/drivers/generic_vfs.go
lxd/storage/memorypipe/memory_pipe.go

- Fixes migration from ZFS storage pools.
- Improves error reporting back to user and avoids hangs when an error occurs.

Storage: VM migration fixes

---

doc/api-extensions.md

doc: Add missing os_api extension

---

lxd/device/nic_sriov.go

Also adds support for newer versions of the ip tool that use "address" rather than "MAC" field for VF hwaddr.
Addresses issue reported here https://discuss.linuxcontainers.org/t/no-matching-virtual-function-for-sriov-enabled-intel-i350-network-card/7317

NIC SR-IOV: Updates networkGetVirtFuncInfo to use json output from ip tool

---

lxd/main_forkexec.go

forkexec: mark fd cloexec so the attaching process doesn't inherit it

---

lxd/main_forkexec.go

forkexec: close all inherited fds

---

lxd/main_forkexec.go

forkexec: log unexpected fds

---

lxd/daemon_storage.go

lxd/daemon: Ignore .zfs in volumes

---

lxd/network/network.go

lxd/network: Push MTU over DHCP

---

lxd/device/disk.go

lxd/devices/disk: Prevent recursive & readonly

---

lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
test/suites/backup.sh

Fix backup renaming

---

test/suites/clustering.sh

test/clustering: increase timing to detect offline node

---

doc/api-extensions.md
lxd/resources/resources.go
lxd/resources/system.go
shared/api/resource.go
shared/version/api.go

Provide system information

---

shared/util.go

shared/util: Never look into the snap

---

lxd/resources/system.go

lxd/resources: serial/uuid may not be accessible

---

doc/instances.md
lxd/device/disk.go

Adds support for using `ceph:` prefix for `disk` device `source` setting.
This uses Qemu's built in RBD support.

VM: Disk ceph

---

lxd/device/device_utils_disk.go
lxd/storage/drivers/driver_cephfs_utils.go

lxd/storage/ceph: Suppport alternate conf syntax

---

lxd/main_init_interactive.go
shared/cmd/ask.go

lxd/init: Try to bind LXD network address when running interactively

---

lxd/device/nic_bridged.go

This can cause unwanted traffic blocks in its default mode so don't try and load it.
Discussed in https://github.com/lxc/lxd/issues/7205#issuecomment-615299284

NIC Bridged: Dont load br_netfilter

---

shared/simplestreams/sort.go

shared/simplestreams: Fix VM image preference

---

lxd/instance/drivers/driver_qemu.go

Fixes https://github.com/lxc/lxd/issues/7223

VM: Wait for onStop when restarting

---

lxd/cgroup/init.go

lxd/cgroup: Fix memory controller detection

---

lxd/main_init_interactive.go

lxd/init: Auto-detect and use Ubuntu ZFS setup

---

lxd/storage/drivers/generic_vfs.go

Storage: Skip missing files during export

---

lxd/storage/drivers/driver_btrfs_volumes.go

Also properly revert on failure.

Storage: BTRFS CreateVolumeFromCopy only set volume size when source is image

---

lxc/image.go

lxc/image: Actually refresh multiple images

---

lxd/resources/network.go
lxd/resources/network_ethtool.go

lxd/resources: Use permanent MAC when available

---

lxd/daemon.go
lxd/device/device_utils_unix.go
lxd/sys/os.go

lxd/daemon: Detect nodev and improve errors

---

lxd/resources/network_ethtool.go
lxd/resources/utils.go

ethtool: resources/ethtool: implement ETHTOOL_GLINKSETTINGS

---

client/lxd_images.go

client/lxd_images: Fix backward compatibility

---

lxd/storage/drivers/driver_btrfs_utils.go
lxd/storage/drivers/driver_btrfs_volumes.go

lxd/storage/btrfs: Fix migration from snapshot

---

shared/util_linux.go
shared/util_linux_cgo.go

shared: Rewrite OpenPty without cgo

---

shared/util_linux.go

openpty: fixes + tweaks

---

lxd/seccomp/seccomp.go

lxd/seccomp: Fix profile conflict between projects

---

lxc/project.go
test/suites/migration.sh

lxc/project: Fix remote handling

---

shared/util_linux.go

We made this our controlling terminal which is a bit of an issue.

openpty: fix TIOCGPTPEER usage

---

lxd/endpoints/cluster.go
lxd/endpoints/endpoints.go
lxd/endpoints/network.go

Make network address bind error fatal when clustered

---

lxd/device/nic_bridged.go

lxd/device/nic/bridged: Updates github.com/mdlayher/netx/eui64

---

lxd/util/fs_32bit.go
lxd/util/fs_64bit.go
shared/fs_32bit.go
shared/fs_64bit.go

I'm working on getting lxd running on mips and this WIP PR fixes some low hanging fruit, there are some other issues like Rdev uint32/64 mismatches which may affect other platforms so they're not going to be included in this PR.

mips fixes

---

lxd/instances_post.go

Something I spotted whilst investigating https://github.com/lxc/lxd/issues/7365

lxd/instances/post: Delete restored instance on backup post hook failure

---

lxd/resources/memory.go

This calculates the total memory from /sys/devices/system/memory, and
replaces the previously retrieved value if successful.
This fixes #7362.

lxd/resources/memory: Fix memory calculation

---

lxd/storage/drivers/driver_dir_utils.go
lxd/storage/drivers/driver_dir_volumes.go
lxd/storage/quota/projectquota.go

Fixes https://github.com/lxc/lxd/issues/7365

Storage: Restore dir project quotas on import

---

lxd/api.go

lxd/api: Don't strip double slashes

---

lxd/db/query/objects.go
lxd/operations/linux.go

lxd/operations: Improve error message when database insertion fails

---

doc/production-setup.md

Recommend to increase the value of aio-max-nr for production use

---

shared/simplestreams/products.go

shared/simplestreams: Support uefi1.img

---

lxd/storage_pools.go

When a storage pool has image volumes in the database but the image record itself has been deleted, trying to delete the storage pool results in cryptic "not found" errors.
This improves the context of the errors.

lxd/storage/pools: Improves delete pool error info

---

lxd/cluster/gateway.go
lxd/cluster/heartbeat.go
lxd/cluster/membership.go

lxd/cluster: Add time skew detection

---

lxd/cluster/gateway.go
lxd/cluster/membership.go
lxd/daemon.go
test/suites/clustering.sh

Rebalancing now happens around 5 seconds after the heartbeat

test: Wait a few more seconds for the rebalance to happen

---

lxd/devlxd.go
lxd/devlxd_test.go
lxd/seccomp/seccomp.go
lxd/ucred/ucred.go
lxd/ucred/ucred_gc.go

lxc/ucred: Simplify logic

---

lxd/instance/drivers/driver_qemu.go
lxd/instance/drivers/driver_qemu_templates.go

lxd/qemu: Cleanup arch checks

---

lxd/instance/drivers/driver_qemu.go
lxd/instance/drivers/driver_qemu_templates.go

lxd/qemu: Add s390x support

---

lxc/config.go

lxc/config: Add -e shorthand

---

lxd/storage/drivers/driver_lvm_patches.go

lxd/storage/lvm: Correct bad VG name in patch

---

shared/subprocess/testscript/stoprestart.sh

shared/subprocess: Better handle slow systems

---

lxd/instance/drivers/driver_lxc.go
lxd/main_forknet.go
lxd/main_forkproxy.go
lxd/main_forkuevent.go

forknet: add "--" to not misinterpret negative integers as flags

---

lxd/instance/drivers/driver_lxc.go

forknet: add missing "--" to forknet invocation on detach

---

lxd/instance/drivers/driver_lxc.go
lxd/main_forkmount.go

forkmount: prevent interpreting negative numbers as flags

---

lxd/storage/drivers/driver_btrfs_utils.go
lxd/storage/drivers/driver_btrfs_volumes.go
lxd/storage/drivers/driver_ceph_utils.go
lxd/storage/drivers/driver_ceph_volumes.go
lxd/storage/drivers/driver_dir_utils.go
lxd/storage/drivers/driver_dir_volumes.go
lxd/storage/drivers/driver_lvm_utils.go
lxd/storage/drivers/driver_lvm_volumes.go
lxd/storage/drivers/driver_zfs_utils.go
lxd/storage/drivers/driver_zfs_volumes.go
lxd/storage/drivers/volume.go

Also adds:
- Volume.ConfigBlockFilesystem()
- Volume.SetQuota()

Storage: Replaces per-driver volumeSize() with unified Volume.ConfigSize()

---

lxd/storage/drivers/driver_btrfs_volumes.go
lxd/storage/drivers/driver_dir_volumes.go
lxd/storage/drivers/generic_vfs.go
lxd/storage/drivers/utils.go

Merges `genericVFSResizeBlockFile` into `ensureVolumeBlockFile`.

Storage: ensure volume block file

---

lxd/storage/utils.go

Allows for volume type specific validation.

Storage: Updates VolumeValidateConfig to accept a volume type argument

---

lxd/instance/drivers/driver_lxc.go

forkuevent: fix slice allocation

---

shared/subprocess/proc.go

shared/subprocess: Fix Stop handling

---

lxd/devices.go

unix-hotplug: fix uevent injection

---

lxd/firewall/drivers/drivers_xtables.go

Updates iptablesInUse to kill process once first rule found. Avoids hanging LXD startup on large rulesets.
Fixes https://github.com/lxc/lxd/issues/7446

Firewall: Updates iptablesInUse to kill process once first rule found

---

lxd/backup.go

Similar to 5ac84466558c0f48207f0f15807209c758fbf713
Fixes #7455

lxd/backup: Fixes hang in backupCreate when invalid compression argument supplied

---

lxd/daemon.go

This can be enabled with "lxd --debug --trace database"

lxd: New command line option to trace SQL statements

---

doc/backup.md

Fixes #7456
Signed-off-by: Johan Ehnberg johan@molnix.com

Update documentation with backup compression

---

lxd/firewall/drivers/drivers_nftables.go

lxd/firewall/nft: Enhance support detection

---

doc/security.md

Reported-by: Etienne Champetier <champetier.etienne@gmail.com>

doc/security: Adds notes about IPv6 router advertisement security

---

lxd/device/device_utils_network.go
lxd/device/nic_bridged.go
lxd/network/network_utils.go
test/README.md
test/suites/container_devices_nic_bridged_vlan.sh

Adds VLAN support for openvswitch bridges.

NIC: Bridged Openvswitch VLAN support

---

lxd/daemon.go

lxd/rbac: Fix auth for non-RBAC trusted clients

---

lxd/util/fs_64bit.go
shared/fs_64bit.go

global: Add riscv64 to build tags

---

lxd/rbac/server.go

lxd/rbac: Don't close body when missing

---

lxd/instance/drivers/driver_qemu.go
lxd/instance/drivers/driver_qemu_templates.go

This is prep work for `lxc console` GUI support.

Add GPU & spice socket

---

client/connection.go

client: Expand snap path in ConnectLXDUnix

---

lxd/instance/drivers/driver_qemu_templates.go

lxd/vm: Fix PCIe slot for physical/sriov nic

---

doc/rest-api.md

Signed-off-by: Salem Yaslem <s@sy.sa>

add type to specify the instance type on creation

---

lxd/device/device_utils_generic.go
lxd/device/device_utils_network.go
lxd/device/nic_physical.go
lxd/device/nic_sriov.go

Rather than binding the device to a driver, we only override the specific function being passed into the instance.

NIC: Updates physical and sriov NICs to use generic PCI driver override technique

---

lxd/instance/drivers/driver_qemu.go
lxd/instance/drivers/driver_qemu_bus.go

lxd/vm: Move bus allocator to own file

---

lxd/storage/quota/projectquota.go

Trying to set/remove quota on a pipe file causes a hang at the ioctl C level.
Fixes #7516

Storage: Only set ext4 project quota on directories and regular files

---

lxd/db/profiles.mapper.go
lxd/db/projects.mapper.go
lxd/db/projects_test.go
lxd/profiles.go
shared/generate/db/method.go
test/suites/projects.sh

lxd/db: Automatically strip ?project=default

---

lxc/action.go
lxc/main.go

lxc/action: Properly handle --all with remotes

---

lxd/instance/drivers/driver_qemu.go

VM: GPU VGA mode passthrough from host

---

lxd/storage/drivers/driver_zfs_volumes.go

When migrating a snapshot to a main volume and using optimised transfer method, the original snapshot is also transferred.
We need to delete this, as it is not needed.
Fixes #7532

Storage: ZFS Remove snapshot when migrating as main volume

---

lxd/instance/drivers/driver_qemu.go

VM: Only enable GPU vga mode on x86_64 systems

---

lxc/action.go

lxc/action: Also add --console to restart

---

lxd/instance/drivers/driver_lxc.go
shared/util_linux.go

util_linux: update terminology

---

lxd/instances_post.go

lxd/backups: Use backups dir for unpack

---

lxd/instance/drivers/driver_qemu.go

lxd/vm: Add udev rule fallback

---

lxd/images.go

lxd/images: Set arch names when downloading

---

lxd/main_forksyscall.go
lxd/seccomp/seccomp.go

lxd: Fix building with clang

---

lxd/db/images.go
lxd/db/images.mapper.go

This is equivalent to #7564 and fixes #7548.
Thanks @randombenj for the heavy lifting!

lxd/db: Add missing criteria for querying a specific public image

---

lxd/firewall/drivers/drivers_nftables.go
lxd/firewall/drivers/drivers_nftables_templates.go
lxd/firewall/drivers/drivers_xtables.go

Firewall: Filter unwanted Ethernet frame types when IP filtering is enabled

---

lxd/api_cluster.go
lxd/db/migration_test.go
lxd/db/networks.go
lxd/db/networks_test.go
lxd/db/storage_pools.go
lxd/db/storage_pools_test.go
lxd/instance_test.go
lxd/instances_post.go
lxd/networks.go
lxd/patches.go
lxd/storage_pools.go
test/suites/clustering.sh

Validate that pools and networks are not pending

---

lxd/storage/backend_lxd.go

lxd/storage: Better handle broken volumes

---

client/lxd_images.go
lxd/response/response.go

This will fix a hang we've seen on aarch64 when transferring a large-ish image between cluster nodes.
Also in general, this will save potentially a LOT of memory when doing image exports.

Stream multi-part file responses

---

lxd/device/disk.go

lxd/device/disk: Fixes cloud-init errors for VMs

---

lxd/instance/drivers/driver_qemu.go
lxd/storage_pools.go
lxd/storage_pools_utils.go

lxd/storage: Rely on UsedBy for deletion error

---

lxd/storage_volumes.go

lxd/storage: Backward compatibility for content types

---

doc/storage.md

doc/storage: Document block storage volumes

---

lxd/instance/drivers/driver_qemu.go
lxd/util/kernel.go

lxd/util: Detect hugetlbfs mount point

---

lxd/cluster/gateway.go

This simplifies a bit our cluster dqlite connection logic and also gets rid of the spurious/misleading "some nodes are behind" message, which was erroneously logged when the target node was not a voter.

Fix misleading nodes are behind error message

---

lxd/cluster/gateway.go
lxd/cluster/membership.go

lxd/cluster: Only look up raft_nodes for resolving the address of node 1

---

lxd/api_project.go

lxd/project: Add more name checks

---

lxd/instance/drivers/driver_qemu.go
lxd/instance/drivers/driver_qemu_templates.go

lxd/qemu: Don't do file lock on custom volumes

---

doc/api-extensions.md
doc/instances.md
lxd/daemon.go
lxd/instance/instance_utils.go
lxd/seccomp/seccomp.go
scripts/bash/lxd-client
shared/instance.go
test/suites/basic.sh
test/suites/container_local_cross_pool_handling.sh

config key & terminology fixes

---

lxd/instance/drivers/driver_qemu.go
lxd/instance/drivers/driver_qemu_templates.go

lxd/qemu: Use memory backend ram/file

---

lxc/image.go

lxc/image: Fix dir handling on snap

---

lxd/instance/drivers/driver_qemu.go

lxd/qemu: Fix crash on non-pinned VM

---

lxc/image.go

lxc/image: Fix more dir handling on snap

---

doc/instances.md

doc/instances: Improves proxy docs

---

lxc/main_aliases.go

lxc/main_alias: Handle leading arguments

---

shared/units/units.go

units: handle multiplication integer overflow

---

doc/storage.md
lxd/storage/drivers/driver_zfs.go

lxd/storage/zfs: Use autotrim when available

---

lxd/cluster/gateway.go
lxd/db/node/schema.go
lxd/db/node/update.go

lxd: Add clustering_fix_raft_address_zero patch to fix node with "0" as address

---

lxd/instance/drivers/driver_qemu_templates.go

lxd/qemu: Fix unbound hugepages

---

lxc/console.go

lxc/console: Missing error handling

---

lxc/console.go

lxc/console: Prefer remote-viewer

---

lxc/console.go

lxc/console: Disconnect on shutdown

---

lxd/db/networks.go
lxd/network/driver_bridge.go
lxd/networks.go

Also improvements to validate network type conversion.

Network: Minor improvements to bridge driver

---

lxd/resources/storage.go
lxd/resources/utils.go

Signed-off-by: Lee Trager <lee.trager@canonical.com>

Attempt to use get storage model from ID_MODEL_ENC before trying ID_MODEL(#7665)

---

test/suites/projects.sh

tests: Delete leftover storage volume

---

lxd/devices.go
lxd/include/dummy.go
lxd/main_checkfeature.go
lxd/main_forkexec.go
lxd/main_forkmount.go
lxd/main_forknet.go
lxd/main_forkproxy.go
lxd/main_forksyscall.go
lxd/main_nsexec.go
lxd/seccomp/seccomp.go
lxd/storage/drivers/utils_cgo.go
shared/idmap/shift_linux.go
shared/util_linux_cgo.go

tree-wide: add dummy include package for cgo

---

doc/image-handling.md

doc/images: Cover the various image servers

---

lxd/api_project.go
lxd/device/device_utils_infiniband.go
lxd/device/device_utils_jnfiniband_test.go
lxd/device/device_utils_proxy.go
lxd/device/disk.go
lxd/device/gpu.go
lxd/device/nic.go
lxd/device/nic_ipvlan.go
lxd/device/nic_routed.go
lxd/device/proxy.go
lxd/device/unix_common.go
lxd/device/unix_hotplug.go
lxd/device/usb.go
lxd/main_init_interactive.go
lxd/network/driver_bridge.go
lxd/network/driver_macvlan.go
lxd/network/driver_sriov.go
lxd/storage/drivers/driver_btrfs.go
lxd/storage/drivers/driver_ceph.go
lxd/storage/drivers/driver_ceph_volumes.go
lxd/storage/drivers/driver_cephfs.go
lxd/storage/drivers/driver_lvm.go
lxd/storage/drivers/driver_lvm_volumes.go
lxd/storage/drivers/driver_zfs.go
lxd/storage/drivers/driver_zfs_volumes.go
lxd/storage/utils.go
lxd/storage_pools_config.go
shared/instance.go
shared/validate/validate.go
shared/validate/validate_test.go

- Moves validation helpers into own package.
- Updates `IsNetworkMAC` to use `net.ParseMAC`.
- Updates `infinibandValidMAC` to use `net.ParseMAC`.

Validate: Validation helper package

---

lxd/seccomp/seccomp.go

Ensure that we don't cross a page boundary.

seccomp: switch from individual pread() to process_vm_readv()

---

lxd/seccomp/seccomp.go
shared/util_linux_cgo.go

seccomp: fix i386 builds

---

lxd/resources/memory.go

This change applies the same change as
375ce45456e9f0789a48541704014a1695896a0f
To the per NUMA node total memory calculation.
Signed-off-by: Nicolas Bock <nicolas.bock@canonical.com>

Fix total memory for per NUMA node

---

lxd/daemon.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/instance_interface.go
lxd/instance_exec.go
lxd/main_checkfeature.go
lxd/sys/os.go
shared/util_linux.go

lxd: enable safe native container terminal allocation

---

lxd/rsync/rsync.go

lxd/rsync: Don't pass --bwlimit when no limits set

---

lxd/instance_exec.go
shared/util_linux.go

exec: fix OpenPtyInDevpts()

---

Makefile
client/lxd_images.go
client/lxd_instances.go
client/operations.go
lxd/instance/drivers/driver_lxc.go
lxd/operations/operations.go
test/suites/storage.sh

- Fixes some race conditions.
- Adds `make race` target to enable Go's race detector.
- Fixes LVM tests on Focal.

Storage: LVM test tweaks and races fixes

---

Makefile
client/operations.go
lxd/db/db.go
lxd/operations/operations.go

Allows the `basic_usage` test to complete successfully with the Go race detector enabled.

LXD: Races

---

lxd/network/driver_bridge.go
lxd/network/driver_common.go
lxd/network/driver_macvlan.go
lxd/network/driver_sriov.go
lxd/network/network_load.go
lxd/network/network_utils.go
lxd/networks.go
shared/validate/validate.go

As per discussion here https://github.com/lxc/lxd/pull/7721#discussion_r465766380 restricts network names to be URL segment safe.

Network: Name validation changes

---

lxd/seccomp/seccomp.go

Link: https://launchpadlibrarian.net/492514639/buildlog_snap_ubuntu_bionic_amd64_lxd-latest-edge_BUILDING.txt.gz

seccomp: check the return value of pwrite()

---

lxd/instance/drivers/driver_qemu.go

VM: Fix race in onStop getting operation

---

lxd/storage_volumes_snapshot.go

This fixes scheduled storage volume snapshots. Instead of only creating
database entries, it actually creates snapshots.

lxd: Fix automatic storage volume snapshots

---

lxd/main_checkfeature.go
lxd/seccomp/seccomp.go
shared/netutils/unixfd.c

seccomp: fixes and improvements

---

lxc/manpage.go

lxc/manpage: Fix behavior in snap

---

lxd/daemon.go
lxd/include/macro.h
lxd/main_checkfeature.go
lxd/main_forkfile.go
lxd/main_forkmount.go
lxd/main_forknet.go
lxd/main_forkproxy.go
lxd/main_forksyscall.go
lxd/main_forkuevent.go
lxd/main_nsexec.go
lxd/sys/os.go

daemon: support attach to namespaces via pidfds

---

lxc/utils.go
lxc/utils_sortorder.go

Fixes https://github.com/lxc/lxd/issues/7784

lxc: Bundle sortorder

---

lxd/network/openvswitch/ovn.go

lxd/network/ovn: Use snap path

---

doc/networks.md
lxd/device/nic_ovn.go
lxd/network/driver_ovn.go
lxd/network/network_utils.go
lxd/network/network_utils_ovn.go
lxd/network/openvswitch/ovn.go

Adds support for Instance port DNS records.
Includes https://github.com/lxc/lxd/pull/7789

Network: OVN Instance port DNS entries

---

lxd/storage/drivers/utils.go

Storage: Fixes shrinkFileSystem to detect e2fsck filesystem modifications

---

lxd/db/instances.go

And replaces functionality by stripping the snapshot name if supplied in the instance name to GetInstancePool() so that the parent instance's pool is returned.
Ensures that this bug https://github.com/lxc/lxd/pull/7794 doesn't affect snapshots too.

Storage: Removes instancePoolSnapshot function

---

lxd/storage/drivers/driver_zfs_utils.go
lxd/storage/drivers/driver_zfs_volumes.go

lxd/storage/zfs: Don't filter mountpoint on block

---

lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go

Pretty much common sense, but in cases where we were overriding the target pool during a migration, this wasn't actually handled properly and would lead to odd errors.

lxd/instance: Always put snapshots on same pool as parent

---

lxd/apparmor/instance_forkproxy.go

lxd/apparmor/forkproxy: Fix running on i386

---

shared/log15/term/terminal_notwindows.go

shared/log15: Fix due to recent unix change

---

lxd/db/cluster/schema.go
lxd/db/cluster/update.go

DB: Adds networks to project usage view

---

lxd/seccomp/seccomp.go

We use the BPF_DEVCG_DEV_CHAR macro as a cheap way to detect whether the kernel
has the correct headers available to be compiled for bpf support. Since cgo
doesn't have a good way of letting us probe for structs or enums the
alternative would be to vendor bpf.h similar to what we do for seccomp itself.
But that's annoying since bpf.h is quite large. So users that want bpf
interception support should make sure to have the relevant header available at
build time.
Closes: #7849

seccomp: fix compilation on kernels without proper bpf.h

---

Makefile
doc/index.md
doc/requirements.md

Drop custom SQLite and libco

---

shared/idmap/shift_linux.go
shared/instancewriter/instance_tar_writer.go

instancetarwrite: fix vfs caps and ACL unshifting

---

lxd/apparmor/apparmor.go
lxd/apparmor/instance.go
lxd/apparmor/instance_forkproxy.go
lxd/apparmor/instance_qemu.go
lxd/apparmor/network.go
lxd/instance/drivers/driver_common.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/instance_interface.go
shared/subprocess/bgpm_test.go
shared/subprocess/proc.go

Initial apparmor profile for qemu

---

lxd/instance/drivers/driver_qemu.go

When taking snapshots of running VMs on BTRFS backed filesystems this was causing issues when doing BTRFS volume send/recv.
See https://discuss.linuxcontainers.org/t/running-virtual-machines-with-lxd-4-0/7519/98

Storage: Switch to threads locking mode and writeback cache mode for VMs on BTRFS

---

lxd/instance/drivers/driver_qemu_templates.go

lxd/instance/qemu: Fix mem device naming

---

doc/instances.md
lxd/device/proxy.go

Fixes some discrepancies between the code and the doc

Improve proxy doc a little

---

doc/api-extensions.md
shared/version/api.go

api: Add projects_networks

---

lxd/seccomp/seccomp.go

seccomp: improve bpf support detection

---

doc/projects.md

doc/projects: Sort config keys

---

lxd/storage/drivers/driver_cephfs_volumes.go

lxd/storage/cephfs: Fix quota on new volumes

---

lxd/networks.go

lxd/networks: Allow network deletion in projects

---

lxd/db/db.go

lxd/db: Adds boolean support to doDbQueryScan

---

lxc/config_trust.go
lxc/file.go
lxc/image.go
lxc/import.go
lxc/manpage.go
lxc/storage_volume.go

lxc: Always use HostPathFollow

---

lxd/storage/drivers/generic_vfs.go
test/suites/backup.sh

And improve tests for backups to check for project support.

Backup: Fix importing custom volumes for unprivileged containers

---

lxd/api_1.0.go

lxd/api: Restrict access to daemon config

---

lxd/instance/drivers/driver_qemu.go
lxd/instance/drivers/qmp/monitor.go

Allows you to shrink memory and then increase it back to boot time size without reboot VM.

VM: Adds support for live memory growth back to boot time memory size

---

lxd/project/permissions.go

lxd/project: Always allow cloud-init:config drives

---

lxd/apparmor/network_dnsmasq.go

lxd/apparmor: Add /etc/localtime to the list

---

doc/image-handling.md

doc/image-handling: Cover publishing

---

shared/validate/validate.go

Fixes https://github.com/lxc/lxd/issues/7972

validate: Increases IsNetworkMTU max MTU to 16384 to support super jumbo packets

---

lxd/firewall/drivers/drivers_nftables.go

Fixes https://github.com/lxc/lxd/issues/7973

nftables: Updates nft parser to handle nft sets with composite `type` field

---

lxc/copy.go
lxc/move.go

lxc: Better handle copy/move between projects

---

lxd/network/driver_macvlan.go
lxd/network/driver_ovn.go
lxd/network/driver_sriov.go
lxd/network/network_utils.go
lxd/network/network_utils_bridge.go
lxd/networks.go

Network: OVN restructure to accommodate different uplink network types

---

lxd/include/lxd_bpf.h
lxd/include/lxd_bpf_common.h
lxd/include/lxd_posix_acl_xattr.h
lxd/seccomp/seccomp.go
shared/idmap/shift_linux.go
test/suites/static_analysis.sh

lxd: fix failing builds when C headers are missing or too old

---

lxd/apparmor/instance_forkproxy.go

This handles two issues:
- Symlinks that need to be dereferenced.
- Ubuntu Core systems where the initial path should be used rather than
the HostPath.
Closes #5009

lxd/apparmor/forkproxy: Socket path fixes

---

lxd/storage_pools.go

Previously it errored with: `Error: Pool not defined on nodes: none`
As was falling through into cluster storage pool setup mode.

Storage: Gives clear error message when trying to create duplicate storage pool in single node

---

lxd/instance_post.go
test/suites/clustering.sh

lxd: Prevent internal cluster migration of instances with backups

---

lxd/db/query/retry.go
lxd/db/query/transaction.go

This fixes the new failures reported in #6439.

Retry harder upon transient database errors

---

lxd/include/macro.h
lxd/main_forksyscall.go

lxd/include: Relocate ifndef for NEWCGROUP

---

lxd/events.go

lxd/events: Handle default permissiosn in projects

---

lxd/instance/drivers/driver_qemu.go

lxd/instance/qemu: Fix bad event name

---

lxd/storage/backend_lxd.go

This uses a bit of a shortcut by checking the filesystem for it instead
of hitting the database.
Closes #8015

lxd/storage: Check base image is available locally

---

lxd/instance/drivers/driver_qemu_templates.go

lxd/driver/qemu: Add spice usb ports

---

shared/util.go

* use String() method with stdout and stderr
* simplified IsTrue function

shared/util.go: use string method with stdout and stderr

---

lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go

By using an anonymous function so that defer runs at end of each iteration.
Similar to fix in https://github.com/lxc/lxd/pull/8025

Instance: Updates templateApplyNow to close files at end of each iteration

---

lxd/instance/drivers/driver_lxc.go
lxd/main_forkmount.go
lxd/seccomp/seccomp.go

seccomp: bugfixes

---

lxd/main_forksyscall.go
lxd/main_nsexec.go
lxd/seccomp/seccomp.go

seccomp: fix mount emulation

---

lxc/init.go

* remove unneeded for-loop in create()

lxc/init.go: remove for-loop in create()

---

lxd/db/networks.go

lxd/db/networks: Fix NULL description

---

lxd/images.go
lxd/resources/usb.go
lxd/storage/drivers/driver_lvm_volumes.go

Fixes ineffectual assignment warnings from https://goreportcard.com/report/github.com/lxc/lxd#ineffassign

lxd: Fixes ineffectual assignment warnings

---

lxd/main_init_interactive.go

init: Clarifies question about using an existing empty disk

---

scripts/bash/lxd-client

scripts/bash: Fix snap handling

---

lxd/daemon.go

lxd: Switch to new candid URL

---

lxd/storage/drivers/driver_zfs_volumes.go

lxd/storage/zfs: No need to remove dashes from UUID

---

lxd/storage/backend_lxd.go

lxd/storage: Lock during the whole image replace

---

lxd/instance/drivers/qmp/monitor.go

lxd/instance/qmp: Merge Go routines

---

lxd/instance_exec.go

Fixes: https://discuss.linuxcontainers.org/t/can-not-start-bash-on-a-container/9315

exec: make sure to only use TIOCGPTPEER if available

---

lxd/instance/drivers/driver_qemu.go

lxd/instances: Fix virtiofsd for config drive

---

lxd/db/storage_volumes.go

Storage: Adds workaround for old remote volume schema in GetStorageVolumeNodeAddresses

---

lxd/network/driver_ovn.go

In this scenario the intermediate OVS bridge and connecting veth pair is not needed and we configure OVN to connect its patch port directly to the existing uplink OVS bridge.

Network: Adds support for using uplink bridges that have bridge.driver=openvswitch for OVN networks

---

lxd/device/disk.go
lxd/instance/drivers/driver_qemu.go

lxd/virtiofs: Fix handling of config drive

---

lxd/db/storage_pools.go
lxd/patches.go

Recreated all changes but re-forked to fix some git issues we caused by forgetting to include sign-offs in all of our commits.
Signed-off-by: Kyle Colburn <kylecolburn38@utexas.edu>

Remade all typo fix changes and reapplied patch. (Continuation of: Pull request: #8022)

---

lxd/rbac/server.go

lxd/rbac: Fix URL encoding

---

lxd/cgroup/init.go

lxd/cgroup: Fix V2 detection/handling

---

doc/rest-api.md

doc/rest-api: auth property is never set to guest

---

lxd/cgroup/abstraction.go
lxd/instance/drivers/driver_lxc.go

lxd/cgroup: Fix swap limits

---

lxd/storage_pools_utils.go

lxd/storage: Expand local config

---

lxd/storage/backend_lxd.go

lxd/storage: Apply rename template

---

doc/instances.md

Signed-off-by: Simon Deziel <simon@sdeziel.info>

doc: fix typos in instances.md

---

lxd/api_internal.go
lxd/device/disk.go
lxd/device/nic_bridged.go
lxd/device/nic_ovn.go
lxd/instance.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/instances_post.go
lxd/migrate_instance.go
lxd/storage/backend_lxd.go
lxd/storage/drivers/driver_btrfs_volumes.go
lxd/storage/drivers/driver_ceph_volumes.go
lxd/storage/drivers/driver_cephfs_volumes.go
lxd/storage/drivers/driver_dir_volumes.go
lxd/storage/drivers/driver_lvm_volumes.go
lxd/storage/drivers/driver_zfs_volumes.go

Fixes migration quota not being applied (https://discuss.linuxcontainers.org/t/loss-of-zfs-quota-setting-after-container-move/9473)
And fixes migration of instance with snapshot referencing a missing external disk issue (https://discuss.linuxcontainers.org/t/cannot-lxc-copy-refresh-with-option-d-device/9441)

Storage: Fixes migration quota and invalid disk device migration issue

---

lxd/instance/drivers/driver_qemu.go

lxd/instance/qemu: Always render disk

---

lxd/device/disk.go

lxd/device/disk: Include network-config in cidata

---

doc/api-extensions.md
lxd/resources/pci.go
shared/api/resource.go
shared/version/api.go

Hi, I was not able to test this on a system with IOMMU enabled so I would appreciate if you could test it on your servers. Thanks! #7894

Add IOMMU group information to resources API

---

lxd/instance/drivers/driver_qemu.go

lxd/instance/qemu: Fix GPU passthrough

---

test/suites/migration.sh

Related to https://github.com/lxc/lxd/issues/8187

test: Adds tests for copying instance with snapshots containing invalid disk devices

---

lxd/api_1.0.go
lxd/api_project.go
lxd/certificates.go
lxd/daemon.go
lxd/events.go
lxd/images.go
lxd/instance/drivers/qmp/monitor.go
lxd/networks.go
lxd/operations.go
lxd/profiles.go
lxd/project/permissions.go
lxd/rbac/requests.go
lxd/rbac/server.go
lxd/storage_pools.go
lxd/storage_volumes.go
lxd/storage_volumes_snapshot.go

lxd/rbac: Filter storage UsedBy

---

lxd/networks.go
lxd/storage/utils.go
lxd/storage_volumes.go

Fixes https://github.com/lxc/lxd/issues/8203

Storage: Add default content type to /1.0/storage-pools/{name}/volumes route

---

lxd/networks.go

lxd/networks: Fix bad logging level

---

lxd/api.go
lxd/api_cluster.go
lxd/cluster/connect.go
lxd/cluster/request/clienttype.go
lxd/db/networks.go
lxd/network/driver_bridge.go
lxd/network/driver_common.go
lxd/network/driver_macvlan.go
lxd/network/driver_ovn.go
lxd/network/driver_physical.go
lxd/network/driver_sriov.go
lxd/network/network_interface.go
lxd/networks.go

Related to https://github.com/lxc/lxd/pull/8205
Includes https://github.com/lxc/lxd/pull/8211

Network: Various minor changes

---

lxd/instance/drivers/driver_common.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go

lxd/instance: Adds per-struct contextual logger.

---

doc/api-extensions.md
doc/networks.md
lxd/network/driver_ovn.go
lxd/network/openvswitch/ovn.go
shared/version/api.go

Allows DHCP/RA to be disabled.

Network: Adds ipv4.dhcp and ipv6.dhcp settings for OVN networks

---

doc/networks.md

doc/networks: Mention DNSSEC setting

---

lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
test/suites/backup.sh

Fixes https://github.com/lxc/lxd/issues/8227
Signed-off-by: David Munro <davidmunro@google.com>

Update backup file when deleting a snapshot

---

doc/api-extensions.md
doc/projects.md
lxd/api_project.go
lxd/project/permissions.go
lxd/project/permissions_test.go
shared/version/api.go

Adds a new 'limits.instances' key in project

---

lxd/instance/drivers/qmp/monitor.go

lxd/instance/qmp: Update for go-qmp change

---

doc/api-extensions.md
doc/instances.md
lxd/device/nic.go
lxd/device/nic_bridged.go
shared/version/api.go

This is a preliminary pull request to discuss implementation of addition.

lxd/device: Add support for bridge port isolation

---

lxd/instance/drivers/driver_qemu.go
lxd/instance/drivers/qmp/monitor.go

VM: Don't spin when Qemu QMP event channel is closed.

---

lxd/network/driver_ovn.go

Supports either native or OVS bridges. And then uses the existing connection functions used for managed bridge uplinks to connect OVN router to uplink.

Network: Adds support for OVN physical uplink interface to be a bridge

---

lxd/db/networks.go

DB: Corrects comment on GetCreatedNetworks

---

lxd/device/device_utils_network.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/drivers/driver_qemu_templates.go

lxd/instance/qemu: Enable multiqueue on tap NICs

---

lxd/device/disk.go
shared/util.go

Implements suggestion from https://github.com/lxc/lxd/pull/8161#discussion_r524643693

Device: Improves readability of disk device validation

---

lxd/instances_post.go
test/suites/projects.sh

Fixes https://github.com/lxc/lxd/issues/8273
Adds test for this scenario.

Instance: Fix copying snapshot to new instance in different project

---

lxd/resources/pci.go
lxd/resources/usb.go

lxd/resources: Always initialize lists

---

lxd/main_init_interactive.go

lxd/init: Clarify https listener question

---

client/lxd_cluster.go

client: Fix output of GetClusterMemberNames

---

lxd/resources/cpu.go

lxd/resources: Support DMI for CPU information

---

lxd/util/net.go

Closes #8340
Signed-off-by: Piotr Iwaniuk <piwaniuk@poczta.onet.pl>

lxd/utils: Compare all addresses from lookup in IsAddressCovered

---

lxd/instance_post.go

lxd/instance: Fix progress on ceph instance move

---

client/interfaces.go
client/lxd_instances.go
doc/api-extensions.md
doc/rest-api.md
lxc/action.go
lxd/instance_state.go
lxd/instances.go
lxd/instances_put.go
shared/api/instance.go
shared/version/api.go

Allows bulk instance state changes.

---

test/suites/snapshots.sh

test: Adds snapshot block.filesystem config check for LVM & Ceph

---

lxd/instance/drivers/driver_qemu.go
lxd/instance/drivers/driver_qemu_templates.go

lxd/vm: Expose ISO images as SCSI cdroms

---

doc/api-extensions.md
doc/instances.md
doc/networks.md
lxd/device/device_utils_network.go
lxd/device/nic.go
lxd/device/nic_ipvlan.go
lxd/device/nic_macvlan.go
lxd/device/nic_physical.go
lxd/device/nic_routed.go
lxd/network/driver_macvlan.go
lxd/network/driver_physical.go
lxd/network/network_utils.go
shared/version/api.go

Network: Support GVRP on selected Networks and NICs

---

lxd/db/storage_volumes.go
lxd/instance.go
lxd/instance/drivers/driver_common.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/instance_interface.go
lxd/instance_post.go
lxd/instance_snapshot.go
lxd/instance_test.go
lxd/instances_post.go
lxd/storage/backend_lxd.go
lxd/storage/utils.go

This is a precursor to allowing instances to be moved pools server side.

Instance: Adds TemplateTrigger type and makes deferred template application option for copy and rename internally

---

lxd/instances_put.go

lxd/instances_put: Limit to local server

---

lxd/db/query/retry.go

DB: Make checkpoint in progress a candidate for IsRetriableError

---

lxd/instances_put.go

This will properly forward the request to all cluster members,
respecting the provided project and merge all errors into a coherent
output.

lxd/instances_put: Properly handle clusters

---

lxd/main_forkproxy.go

When I originally introduced forkproxy we pretty quickly ran into a zombie
problem because of interactions between the C "runtime" and the Go runtime,
quote:
> Usually we should wait for the child process somewhere here.
> But we cannot really do this. The listener file descriptors
> are retrieved in the go runtime but at that point we have
> already double-fork()ed to daemonize ourselves and so we
> can't wait on the child anymore after we received the
> listener fds. On the other hand, if we wait on the child
> here we wait on the child before the receive. However, if we
> do this then we can end up in a situation where the socket
> send buffer is full and we need to retrieve some file
> descriptors first before we can go on sending more. But this
> won't be possible because we're …

forkproxy: prevent zombies

---

lxd/instance/drivers/driver_qemu.go

Want to make sure I understand the desired behavior.
I noticed that `lxc stop --force` calls `inst.Stop()` whereas `lxc stop` calls `inst.Shutdown()`. 
https://github.com/lxc/lxd/blob/10db3d9aa9c3549b6295bf0957dc189c9e1b54be/lxd/instance_state.go#L129-L133
Some of the comments on the issue mentioned that this should be done in response to a `stop --force` so I added the check to `.Stop()`. I can also add it to `.Shutdown()` if we want to do this as part of a normal stop.
Example:
``` 
$ lxc list
+--------+-------+------+------+-----------------+-----------+
|  NAME  | STATE | IPV4 | IPV6 |      TYPE       | SNAPSHOTS |
+--------+-------+------+------+-----------------+-----------+
| centos | ERROR |      |      | VIRTUAL-MACHINE | 0         | …
```

Instance: attempt to kill qemu proc in Stop() when qemu monitor is unreachable

---

lxd/device/gpu_physical.go

lxd/device/gpu: Skip nvidia directories

---

lxd/instance/drivers/driver_lxc.go

Use the correct cgroup setting.

cgroup: fix cgroup2 device driver settings

---

doc/instances.md

Minor changes to wording for GPU sr-iov and mdev.

doc/instances: Tweaks to make device type linking work

---

doc/storage.md

doc/storage: Add mention of zfs.remove_snapshots

---

lxd/instance/drivers/driver_qemu.go

lxd/instance/qemu: Rework lxd-agent startup

---

lxd/api_project.go
lxd/device/nic_ovn.go
lxd/network/driver_ovn.go
lxd/network/network_utils.go
lxd/storage/utils.go

- Further use of `util.SplitNTrimSpace`.
- Further use of `db.ErrInstanceListStop`.
- Optimisation added to `UsedBy` when using `firstOnly=true`.

LXD: Misc tweaks

---

lxd/cluster/gateway.go
lxd/cluster/heartbeat.go

lxd/cluster: Guarantee single hearbeat loop

---

doc/rest-api.md

doc/rest-api: Fix and clarify backup API

---

doc/rest-api.md

doc/rest-api: More fixes for backups

---

lxd/api_1.0.go
lxd/certificates.go
lxd/cluster/gateway.go
lxd/daemon.go
lxd/db/certificates.go
lxd/db/certificates.mapper.go
shared/util.go

Modernize certificates

---

doc/backup.md

doc/backup: Mention subuid/subgid

---

doc/api-extensions.md
doc/projects.md
lxd/api_project.go
lxd/db/images.go
lxd/images.go
shared/version/api.go

It's a second part of issue: Add `images.*` and `backups.*` server config keys to per-project #7900

Projects remote cache expiry

---

lxd/instance/drivers/driver_lxc.go
lxd/main_forkmount.go

Link: https://discuss.linuxcontainers.org/t/mount-home-directory-read-only-permission-denied

driver_lxc: pass flags to shiftfs mount

---

lxd/network/driver_bridge.go

Recent change from https://github.com/lxc/lxd/pull/8391 to allow static NIC IPs with fan mode has broken fan firewall setup to allow DHCP. This fixes it by allowing DHCP mode check without depending on fan bridge having IP addresses (as these are removed before the firewall is setup).
Reported from: https://discuss.linuxcontainers.org/t/having-problem-with-fan-network-and-ufw/10246

Network: Ensure that DHCP firewall rules are added in bridge fan mode

---

lxd/resources/storage.go

This fixes an issue on s390x and other big endian systems where
unpacking to an int64 causes bogus values. Instead always unpack into a
32bit int.
Closes #8477

lxd/resources/storage: Rework block size handling

---

lxd/network/network_utils.go

This way it can potentially be cheaper when using firstOnly=true.
Stable-4.0 version of https://github.com/lxc/lxd/commit/a00cca8e9632026fefd4d34dd241e609754076c1 without needing to support networks using networks (as OVN support isn't in stable-4.0).

lxd/network/network/utils: Reorders UsedBy to do cheapest search first (stable-4.0)

---

lxd/init.go
lxd/main_init_dump.go

lxd/init: Add projects to dump/init preseed

---

lxd/instance_backup.go
lxd/instance_console.go
lxd/instance_delete.go
lxd/instance_exec.go
lxd/instance_post.go
lxd/instance_put.go
lxd/instance_snapshot.go
lxd/instances_post.go

Fixes https://github.com/lxc/lxd/issues/8484
Also makes the returned `containers` resources conditional on a container instance type for various routes.

Instance: Respect instance project when moving instance to cluster target

---

lxd/cluster/heartbeat.go

lxd/cluster: Don't warn about pending nodes

---

lxd/instances_post.go

lxd/instances: Fix instance copy within project

---

shared/netutils/network_linux_cgo.go
shared/netutils/unixfd.c
shared/netutils/unixfd.h

netutils: improve file descriptor retrieval and increase robustness

---

doc/projects.md

doc/projects: Projects aren't restricted by default

---

shared/netutils/unixfd.c

unixfd: vet all parameters

---

lxd/api_internal.go
test/suites/projects.sh

lxd/internal: Don't access undefined fields

---

doc/index.md

doc/README: Drop readthedocs

---

lxd/vsock/vsock.go

lxd/vsock: Better handle errors

---

lxd/vsock/vsock.go

lxd/vsock: Retry timeouts once

---

lxd/db/cluster/schema.go
lxd/db/cluster/update.go

lxd/db: Set nodes.id to auto-increment for new clusters

---

shared/api/network_acl.go

shared/api: Mark most ACL rule fields omitempty

---

doc/projects.md

Fix typo in doc/projects.md, replace images with backups

---

shared/api/network.go

Doc: fix typo on network typo in doc/rest-api.yaml

---

doc/rest-api.yaml

Related to https://github.com/lxc/lxd/pull/8536

doc/rest-api: Refresh swagger YAML

---

doc/api-extensions.md
doc/projects.md
doc/server.md
lxd/api_project.go
lxd/cluster/config.go
lxd/db/node.go
lxd/db/node_test.go
lxd/db/schema/schema_test.go
lxd/instances_post.go
shared/osarch/architectures.go
shared/osarch/architectures_linux.go
shared/osarch/tempfile_test.go
shared/util.go
shared/validate/validate.go
shared/version/api.go

Add concept of default architecture (global and per-project) #7947

Images default architecture

---

lxd/instance/drivers/qmp/monitor.go

lxd/instance/qemu: Add 5s QMP timeout

---

lxd/cluster/gateway.go
lxd/cluster/membership.go

Just running clustering CI tests to debug test failures.

clustering: Force configuration when bootstrapping first node of cluster

---

lxc/project.go

lxc/project: Show description

---

doc/network-acls.md

Signed-off-by: Simon Deziel <simon@sdeziel.info>

doc: improve wording of network ACLs

---

lxd/network/driver_ovn.go
lxd/network/openvswitch/ovn.go

Reduces the number of calls to `ovn-nbctl`.
This is a precursor to per-instance-NIC default ACL rule actions.

Network: Optimises detection of active OVN switch ports when updating multiple instance NICs

---

test/suites/clustering.sh

tests: Don't block on /dev/random

---

lxd/network/acl/acl_ovn.go
lxd/network/driver_ovn.go

A couple of small improvements I noticed when doing https://github.com/lxc/lxd/pull/8576

Network: OVN ACL cleanup

---

lxd/images.go

Images: Improve error logging in autoUpdateImages

---

lxc/list.go

lxc/list: Handle dots in device keys

---

lxc/network_acl.go
lxd/device/nic_bridged.go
lxd/network/driver_bridge.go

And a couple of other small fixes.

Network: Allow output of lxc network acl show to be used as input to lxc network acl edit

---

lxd/device/gpu_mdev.go

This adds the support needed for using NVIDIA vGPU on top of the A100.

Support mdev on top of SR-IOV

---

lxc/info.go

lxc/info: Sort the mdev profiles

---

lxd/backup.go
lxd/instance.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/migrate_instance.go
lxd/storage/backend_lxd.go
lxd/storage/backend_mock.go
lxd/storage/errors.go
lxd/storage/load.go

Fixes https://discuss.linuxcontainers.org/t/lxd-cephfs-not-implemented-error/10666

Storage: Check instance type is supported by pool during creation

---

doc/metadata.yaml

Follows on from https://github.com/lxc/lxd/pull/8605

doc/metadata: Adds remotes section

---

client/lxd_containers.go
client/lxd_instances.go

client: Fixes GetContainerLogfiles and GetInstanceLogfiles

---

client/lxd_instances.go

client: Fix copy of VM snapshots

---

test/suites/basic.sh

tests: Fix failure on 5.11 kernel

---

lxd/include/macro.h
lxd/main_forkexec.go

forkexec: log more failures

---

lxd/network/acl/driver_common.go
lxd/networks.go

Don't allow obviously wrong combinations of source and destination (for example mixing only ipv4 and ipv6 addresses).
And skip network validation during cluster pre-join as networks using `security.acls` will fail due to ACLs not existing locally yet.

Network: Improve ACL rule validation

---

lxd/project/permissions.go

lxd/project: Only consider syscall interception as low-level

---

lxd/storage_volumes_snapshot.go

lxd/storage: Re-introduce cluster distribution of volume snapshots

---

lxc/remote.go

lxc/remote: Only update URL in set-url

---

lxd/instance/drivers/driver_common.go

Fixes #8674
Note that I tested this on the 4.0 branch, not master, but it doesn't look like things have changed much there

lxd/instance/drivers: Don't overwrite template triggers

---

lxd/daemon_images.go

Has been replaced by imageDownloadLock()

Images: Removes unnecessary imagesDownloadingLock mutex

---

lxd/instance/drivers/driver_common.go
lxd/snapshot_common.go
shared/validate/validate.go
test/suites/snapshots.sh

lxd/snapshots: Fix multiple schedules

---

lxd/images.go

lxd/images: Ignore intervals on manual refreshes

---

lxd/firewall/drivers/drivers_nftables.go

Fixes #8724
The nftables wiki says that support for NAT rules in `inet` tables was added in kernel 5.2. 
We started using inet table type in 4.13 to simplify the support for mixed ipv4/ipv6 firewall rules.
> Since Linux kernel 5.2, there is support for performing stateful NAT in inet family chains.
https://wiki.nftables.org/wiki-nftables/index.php/Performing_Network_Address_Translation_(NAT)#Inet_family_NAT

Firewall: Require kernel version >= 5.2 for nftables driver to allow support for inet table NAT rules

---

lxd/apparmor/instance.go
lxd/apparmor/instance_qemu.go

lxd/apparmor: Respect LXD_OVMF_PATH

---

doc/api-extensions.md
doc/projects.md
lxd/api_project.go
lxd/instance.go
lxd/instance_backup.go
lxd/instance_snapshot.go
lxd/project/permissions.go
lxd/storage_volumes_backup.go
lxd/storage_volumes_snapshot.go
shared/version/api.go

Restricted snapshots and backups

---

lxd/device/config/devices.go

lxd/devices: Allow user.XYZ

---

doc/rest-api.md

doc/rest-api: Fix description of PATCH warning

---

doc/network-acls.md

[Doc] Fix remove duplicated sentences in doc/network-acls.md

---

doc/clustering.md
lxd/init.go
lxd/main_init.go

Cluster certificate path

---

doc/server.md
lxd/cluster/config.go
lxd/operations.go

Shutdown timeout

---

lxd/storage/drivers/driver_ceph_volumes.go

lxd/storage/ceph: Always return VolumeUsage

---

doc/production-setup.md

doc/production-setup: Cover name leakage

---

lxd/apparmor/instance.go

lxd/apparmor/instance: Deref OVMF path

---

lxd/instance/drivers/driver_qemu.go

VM: Remove old pid file on start if exists

---

lxd/instance/drivers/driver_qemu.go

lxd/instance/qemu: queues is uint64

---

lxd-agent/devlxd.go
lxd/devlxd.go
lxd/instance/drivers/driver_qemu.go

Location devlxd api

---

lxd/instances_get.go

Instance: Fix potential nil pointer dereference in instance list

---

lxd/instance_console.go
lxd/instance_exec.go

lxd/instance: Don't use RawOperation

---

lxd/db/node.go
test/suites/clustering.sh

Expose db standby role

---

lxd/instance/drivers/driver_qemu.go
lxd/instance/drivers/qmp/commands.go

A precursor to hotplugging NIC support.

VM: Move to adding macvlan NIC file descriptors using QMP SendFile

---

.github/SUPPORT.md
doc/index.md

README: Update IRC

---

lxd/instance/drivers/driver_qemu_templates.go

lxd/instance/qemu: Remove duplicate key

---

lxc/publish.go
test/suites/basic.sh

lxc/publish: Fix ETag race condition

---

lxd/endpoints/endpoints.go

Update for `Config` struct comments in endpoints.

lxd/endpoints: Update endpoints Config doc

---

lxd/instance/drivers/driver_qemu.go

VM: Fix logger in onStop

---

doc/rest-api.md

doc/rest-api: Linkify API doc

---

lxd/daemon.go
lxd/device/disk.go
lxd/include/mount_utils.h
lxd/include/process_utils.h
lxd/include/syscall_numbers.h
lxd/include/syscall_wrappers.h
lxd/instance/drivers/driver_lxc.go
lxd/instance/instance_interface.go
lxd/main_checkfeature.go
lxd/main_forkmount.go
lxd/main_forkproxy.go
lxd/main_forksyscall.go
lxd/main_nsexec.go
lxd/seccomp/seccomp.go
shared/idmap/shift_linux.go

lxd: support idmapped mounts

---

lxd/daemon.go
lxd/db/warnings_types.go

- lxd/db: Add UnableToConnectToMAAS warning
- lxd: Add unable to connect to MAAS warning

Add unable to connect to MAAS warning

---

Makefile

https://github.com/lxc/lxd/issues/8863

Makefile: Add "build" target

---

lxd/db/warnings_types.go
lxd/network/driver_bridge.go
lxd/warnings/warnings.go

- lxd/db: Add WarningAppArmorDisabledDueToRawDnsmasq
- lxd/warnings: Add more resolver functions
- lxd/network: Add disabled AppArmor warning

Add AppArmor disabled on network warning

---

lxd/db/warnings_types.go
lxd/device/proxy.go
lxd/warnings/warnings.go

- lxd/db: Add WarningProxyBridgeNetfilterNotEnabled
- lxd/warnings: Add more delete functions
- lxd/device: Warn if netfilter is disabled

lxd/device/proxy: Warn if netfilter is disabled

---

lxd/db/warnings_types.go
lxd/network/driver_bridge.go
lxd/network/driver_ovn.go
lxd/network/driver_physical.go
lxd/networks.go

- lxd/db: Add WarningNetworkStartupFailure
- lxd/network: Warn on network startup failure
- lxd: Delete warnings if network is deleted

warnings: Network startup failure

---

doc/networks.md

Based on discussion in https://github.com/lxc/lxd/issues/3391#issuecomment-859686669

Docs:  Adds guide on how to get systemd to configure systemd-resolved on lxdbr0 start up

---

lxd/main_init_interactive.go
shared/validate/validate_test.go

A further simplification of https://github.com/lxc/lxd/pull/8869

Init: Use validate.Optional in askClustering

---

lxd/cluster/heartbeat.go
lxd/db/warnings_types.go

- lxd/db: Add WarningOfflineClusterMember
- lxd/cluster: Add warning around heartbeat

warnings: Offline cluster member

---

lxd/patches.go

Due to a code change, duplicate warnings we created. One with an empty
node string and one with "none". This removes the empty node entry.
Fixes https://github.com/lxc/lxd/issues/8902

lxd/patches: Fix duplicate warnings

---

lxc/warning.go

- lxc/warning: Introduce defaultWarningColumns
- lxc/warning: Hide location if not clustered

lxc/warning: Hide location if not clustered

---

lxd/network/driver_bridge.go

Fixes #8905
So if `raw.dnsmasq=auth-zone=lxd`, for example, then you get this in the log:
```
The dnsmasq process exited prematurely   project=default driver=bridge network=lxdbr0 stderr="dnsmasq: --auth-server required when an auth zone is defined." err="Process exited with non-zero value 1"
```

Network: Surface bridge dnsmasq specific start up errors via log entry

---

lxc/monitor.go
shared/api/event.go

--pretty support for lxc monitor operation events

---

lxd/db/cluster/query.go
lxd/db/cluster/schema.go
lxd/db/cluster/update.go
lxd/db/node.go
lxd/patches.go

Rename cluster column pending to state

---

lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/lifecycle/instance.go

* adding exec and console lifecycle events for instances
* exec events include the command as context
*  console events include the type of console as context

Instance exec and console lifecycle events

---

lxd/lifecycle/profile.go
lxd/profiles.go

* Add created/renamed/updated/deleted lifecycle events for profiles
* `ProfileUpdated` includes the new profile fields as context
* `ProfileRenamed` includes the old and new names as context

Profile CRUD lifecycle events

---

lxd/instance_backup.go
lxd/lifecycle/instance_backup.go

* Add instance backup export lifecycle event

instance backup export lifecycle event

---

lxd/firewall/drivers/drivers_xtables.go

Rely on internal mutex instead.
This is because the `/var/lib/ebtables/lock` file is not accessible when run inside the snap and cannot be changed at runtime.
Tested using the test suite but with xtables driver in use.

Firewall: Don't use ebtables --concurrent flag

---

lxd/api_project.go
lxd/lifecycle/project.go

good old CRUD lifecycle events :)
* `Created` and `Updated` include the new profile configuration in their context.
* `Renamed` includes the new and old names in its context.

project CRUD lifecycle events

---

lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/lifecycle/instance.go

* add instance file lifecycle events for push, pull, and delete
* `InstanceFileRetrieved` includes the file source and destination as context
* `InstanceFilePushed` includes the file source, destination, and file info as context
* `InstanceFileRemoved` includes the file path as context

Instance file push/pull/delete lifecycle events

---

lxd/instance_snapshot.go

lxd/instance: Fix snapshot etag

---

lxd/storage_pools_utils.go

lxd/storage: Handled nil config map

---

lxd/lifecycle/storage_pool.go
lxd/storage_pools.go

* Created, Updated, and Deleted lifecycle events for storage pools.
* If a target can be specified, it is passed in the context.

Storage pool lifecycle events

---

lxd/instance.go

lxd/instance: Fix instance volume DB entry on copy

---

lxd/main_init_interactive.go

Change the exisiting flow to: server name will be promptly required if user doesn't have a join token.
I have wrapped this ask into a function since I am not 100% sure if server name is needed when `cli.AskBool("Are you joining an existing cluster? (yes/no) [default=no]: ", "no")` is `false`.
Resolves: #8860 
Signed-off-by: Jianming Ma ma.jianming@hotmail.com

lxd/main_init_interactive: only ask for server host name when no join token is provided

---

lxd/instances.go

The use of `logger.Warn` with arguments intended for `logger.Warnf` (introduced with https://github.com/lxc/lxd/pull/8953) would have caused a crash had that code path ever been reached.
Also:
- The use of quoting in errors was inconsistent, and used '%q' which would have resulted in double quoted instance name '"instanceName"'.
- Adds instance name to all errors and warnings to help diagnose issues.
- Don't wait 5 more seconds on last start attempt before logging final failure.
- Differentiate between auto start failure and manual start failure error by making clear this is an auto start attempt.
- Differentiate between an attempt error (logged as a warning) and a final error (logged as an error).
- Switches to "attempt" terminology rather than "retry" so that counting in logs starts at …

Instances: Fixes potential crash in instancesRestart and improves logging

---

lxd/device/device_utils_network.go
lxd/device/nic_bridged.go
lxd/device/nic_sriov.go
lxd/device/proxy.go
lxd/ip/class.go
lxd/ip/filter.go
lxd/ip/link.go
lxd/ip/qdisc.go

Move remaining iproute calls to ip package

---

lxd/db/warnings.go

lxd/db/warnings: Improve context in warning unknown entity errors

---

doc/api-extensions.md
shared/version/api.go

For functionality introduced in #8919

api: Adds server_instance_driver_operational extension

---

lxd/lifecycle/operation.go
lxd/operations.go

I added it to both the internal and external cancel functions. Not sure if we just want it on the external one.

Operation cancelled lifecycle events

---

doc/events.md

Events documentation

---

client/lxd.go
client/lxd_events.go
client/lxd_operations.go
client/lxd_storage_volumes.go
client/simplestreams.go
client/util.go
lxc-to-lxd/config.go
lxc-to-lxd/main_migrate.go
lxc-to-lxd/network.go
lxc/action.go
lxc/config_device.go
lxc/copy.go
lxc/exec_unix.go
lxc/image.go
lxc/info.go
lxc/list.go
lxc/remote.go
lxc/warning.go
lxd-agent/server.go
lxd-p2c/utils.go

Slowly going through some of the things reported by https://staticcheck.io/

Extra static analysis fixes

---

doc/api-extensions.md
lxd/request/request.go
shared/api/event.go
shared/version/api.go

Add address field to lifecycle requestor

---

lxd/node/config.go
shared/validate/validate.go

Fixes #8916 
Signed-off-by: Sascha Bast <sash@mischkonsum.org>

lxd/lxd: Validate https address for config key core.https_address

---

lxd/storage/drivers/driver_ceph.go
lxd/storage/drivers/driver_cephfs.go

Shorten the version string a bit.

lxd/storage/ceph: Improve version parsing

---

lxd/node/config.go

lxd/node: Relax constraint on cluster address

---

lxd/device/nic_bridged.go
test/suites/clustering.sh

Based on discussions from https://github.com/lxc/lxd/pull/9018#issuecomment-880180952

NIC: Improve bridged NIC duplicate MAC/IP assignment checks

---

lxd/instance/drivers/driver_lxc.go

lxd/instance/lxc: Fix swappiness calculation

---

lxd/instance/drivers/driver_qemu.go

This way backup file contains the true last-start config.

VM: Update start time volatile keys before backup file is written

---

lxd/storage/drivers/driver_ceph_utils.go
lxd/storage/drivers/driver_lvm_utils.go
lxd/storage/drivers/driver_zfs_patches.go
lxd/storage/drivers/driver_zfs_utils.go

These have come out of the work I am doing for `lxd recover`.

Storage: Naming and code reorganisation tweaks

---

shared/api/event.go

shared/api: Fix crash on missing event requestor

---

lxc/remote.go
lxd/main_init_interactive.go
shared/cmd/ask.go

Prevent tests from entering infinite loops if invalid values or unexpected scenarios occur.

CLI: Handle read errors (such as EOF) to avoid infinite loops

---

lxc/main.go

lxc: Hide built-in completion command

---

doc/cloud-init.md

doc/cloud-init: Update for current images

---

lxd/instance/drivers/driver_common.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go

lxd/instance/drivers: Add ErrInstanceIsStopped

---

scripts/bash/lxd-client

And reorganize the cases
Signed-off-by: JUN JIE NAN <nanjunjie@gmail.com>

Added console and rename to lxd names auto complete

---

lxd/api_internal_recover.go
lxd/instance/drivers/driver_qemu.go
lxd/storage/backend_lxd.go
lxd/storage/backend_mock.go
lxd/storage/drivers/driver_ceph_volumes.go
lxd/storage/drivers/driver_lvm_volumes.go
lxd/storage/drivers/driver_zfs_volumes.go
lxd/storage/drivers/generic_vfs.go
lxd/storage/pool_interface.go

This adds custom volume recovery support to the new disaster recovery tool added in https://github.com/lxc/lxd/pull/8993.
Design doc: https://discuss.linuxcontainers.org/t/lxd-new-disaster-recovery-tool/11296

New disaster recovery tool (custom volume recovery)

---

doc/clustering.md

doc/clustering: Mention evacuate/restore

---

lxd/db/certificates.go
lxd/db/certificates.interface.mapper.go
lxd/db/certificates.mapper.go
lxd/db/generate/db/method.go
lxd/db/images.go
lxd/db/images.interface.mapper.go
lxd/db/images.mapper.go
lxd/db/instances.go
lxd/db/instances.interface.mapper.go
lxd/db/instances.mapper.go
lxd/db/operations.go
lxd/db/operations.interface.mapper.go
lxd/db/operations.mapper.go
lxd/db/profiles.go
lxd/db/profiles.interface.mapper.go
lxd/db/profiles.mapper.go
lxd/db/projects.go
lxd/db/projects.interface.mapper.go
lxd/db/projects.mapper.go
lxd/db/snapshots.go
lxd/db/snapshots.interface.mapper.go
lxd/db/snapshots.mapper.go

Pretty simple PR here, just renaming List/Get to GetMany/GetOne.

Generator: GetOne/Many instead of Get/List

---

lxd/db/generate/lex/case.go
lxd/db/operations.interface.mapper.go
lxd/db/operations.mapper.go

Fixup for #9069:
@tomponline 
> I'll merge this, but if you can send up another small PR to fix that `uUID` argument name that would be great. Thanks

Generator: ID and UUID casing

---

doc/metadata.yaml

doc: Add events doc to navigation

---

lxd/api_internal_recover.go
lxd/main_recover.go
lxd/storage/drivers/driver_cephfs_volumes.go
test/suites/backup.sh

- Add custom volume recovery tests, as well as tests for path restoration.
- Also adds cephfs support.
- Also prevent recovery of storage pool records when clustered.

Recovery: Improve tests and cephfs support

---

lxd/firewall/drivers/drivers_consts.go
lxd/firewall/drivers/drivers_nftables.go
lxd/firewall/drivers/drivers_nftables_templates.go
lxd/firewall/drivers/drivers_xtables.go
lxd/network/driver_bridge.go

Allow ICMP to/from LXD networks

---

fuidshift/main.go
lxc-to-lxd/main.go
lxd-agent/main.go
lxd-benchmark/main.go
lxd-p2c/main.go
lxd/main.go
lxd/main_daemon.go

global: Disable the completion command

---

lxd/instance/drivers/driver_lxc.go

We need to make sure that raw.lxc is applied last in the instance's config.
This is quite hard to do because of devices which are mostly dynamic and
added after the initial configuration is generated.
So instead, this creates a separate configuration file which is always
loaded following the main file. To keep validation working properly,
this then moves the validation logic into Update().
Closes #9093

lxd/instance/lxc: Rework raw.lxc handling

---

lxd/device/device_utils_network.go
lxd/device/device_utils_proxy.go
lxd/network/errors.go
lxd/network/network_utils.go

As part of my work on network forwards.

Network: Some small reorganisations of code

---

doc/clustering.md
lxd/init.go
lxd/main_init.go
lxd/main_init_interactive.go

lxd/init: Allow preseeding cluster_token

---

shared/validate/validate.go

shared/validate: Fix IPv6 wildcard handling in IsListenAddress

---

lxd/db/network_acls.go
lxd/db/transaction.go

And converts the ACL DB functions to use it.
This new function, I feel, provides a better balance of simplicity, safety and query control than the existing function `queryScan`. 
It still ensures that the row resources are cleaned up at the end, without requiring the developer to do it.
However it also provides the ability to run multiple queries in a single transaction (which I have benefited from with the ACL config retrieval), and allows directly scanning row fields into target structs, without having to create intermediate slices of structs.
This PR also switches from using `dbQueryRowScan` to using the stdlib `tx.tx.QueryRow`, for the same reasons.

DB: Adds ClusterTx.QueryScan function

---

lxd/api_cluster.go

lxd/cluster: Drop translated string

---

lxd/db/network_forwards.go
lxd/network/driver_common.go
lxd/network/driver_ovn.go
lxd/network/network_utils.go

- Fixes bug in OVN NIC usage parsing not considering multiple `ipv{n}.routes.external` entries.
- Various code clean ups coming from the work to add bridge forward support.

Network: Forward improvements

---

doc/clustering.md

add 'lxd cluster edit' documentation

---

test/suites/container_devices_proxy.sh

This adds a test to catch the bug introduced with https://github.com/lxc/lxd/commit/96cd8ad1d466be666b90948c9f2f12c2a806001e
The bug itself is fixed in: https://github.com/lxc/lxd/pull/9177

Device: Improve proxy device tests

---

.github/workflows/test.yml

.github/workflows: Update go versions

---

doc/metadata.yaml

doc: Adds network forwards to left hand nav

---

doc/server.md

doc/server: Fix incorrect default for routerid

---

lxd/storage/drivers/driver_zfs_volumes.go

lxd/storage/driver/zfs: Fix ListVolumes with custom zpool

---

shared/instance.go

don't allow 'limits.memory' to be 0

---

lxd/network/driver_bridge.go
lxd/network/driver_common.go
lxd/network/driver_ovn.go
lxd/network/network_interface.go
lxd/network_forwards.go
test/suites/network_forward.sh

Also reorganises bridge and ovn drivers to export BGP prefixes in a consistent manner.

Network: Exports OVN forward addresses via BGP 

---

lxd/project/permissions.go
lxd/project/permissions_test.go

`CheckClusterTargetRestriction` currently is using `projectHasLimitsOrRestrictions` to check restrictions what is not correct. In case when any limits are set and `restricted` setting is not set function doesn't allow for cluster targeting. Targeting should be only dependant from `restricted` and `restricted.cluster.target` settings. This PR fixes this.

Change restrictions check function in CheckClusterTargetRestriction

---

lxd/network/openvswitch/ovn.go

There appears to be a bug in ovn-nbctl where running lr-nat-del as part of the same command as
lr-nat-add doesn't take account the changes by lr-nat-del, and so you can end up with errors
if a NAT entry already exists. So we run them as separate command invocations.

OVN: Work around a bug in lr-nat-del in ovn-nbctl in LogicalRouterDNATSNATAdd

---

lxd/daemon_storage.go
test/suites/config.sh

Triggered by https://github.com/lxc/lxd/pull/9217

Storage: Workaround LVM unmount issues

---

doc/rest-api.md

doc: update link to rest-api.yaml

---

lxd/cgroup/abstraction.go

lxd/cgroup: Implement CPU usage for cgroup v2

---

lxd/storage/drivers/driver_lvm.go

Until such time as we can make deactivating an LVM VG on a loop file reliable.
Have logged the issue for further investigation here: https://github.com/lxc/lxd/issues/9278

Storage: Remove unmount functionality from LVM driver

---

client/interfaces.go
lxd/db/network_forwards.go

Network: Forwards fixes

---

lxd/instances.go

Handle VMs in instancesOnDisk

---

doc/metrics.md

doc/metrics: typo fix

---

lxc/file.go

Create dirs on pull -p

---

lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go

lxd/instance/drivers: Add instance type to metrics

---

lxd/storage/drivers/driver_btrfs_volumes.go
lxd/storage/drivers/driver_zfs_volumes.go
lxd/storage/drivers/generic_vfs.go

Support custom block and filesystem export for all drivers

---

lxd/cgroup/abstraction.go

lxd/cgroup: Fix GetIOStats on cgroup2

---

lxd/daemon.go
lxd/instance/drivers/driver_lxc.go
lxd/sys/os.go

lxd: add core scheduling support

---

lxd/daemon.go
lxd/include/syscall_wrappers.h
lxd/main_checkfeature.go

lxd/checkfeature: check whether the kernel supports core scheduling

---

lxd-agent/metrics.go
lxd/instance/drivers/driver_lxc.go
lxd/metrics/metrics.go

- lxd/metrics: Change ProcsTotal to gauge
- lxd/instance/drivers: Log metrics failures
- lxd-agent: Log metrics failures

Fix metrics issues

---

test/includes/lxd.sh

test: Kill LXD process if doesn't start in time

---

doc/instances.md
lxc/launch.go
lxc/main.go
po/lxd.pot

Suggest Ubuntu 20.04 instead of 18.04

---

lxd/instance.go

If multiple instances were launched on the same cluster member, using the same image, at the same time,
then it was possible for both to come to the conclusion that the image required didn't exist locally
and start the process of downloading it to the local member.
Unfortunately the lock that ensures this process doesn't happen concurrently was being taken too later,
when really we needed to ensure that the 2nd instance waited until the 1st instance has finished downloading
the image and adding it the local member's DB record before checking whether it is available.
Fixes #9326

Instance: Fix image download race condition in instanceCreateFromImage

---

lxd/api_cluster.go

This fixes a bug where if an instance wouldn't stop within its deadline,
we would return nil at that point and so silently abort the restore
entirely.
This was because the old logic would check for
"err != nil || errors.Cause(err) != drivers.ErrInstanceIsStopped"
and so a return value of "nil" be treated as satisfying the condition
and be returned causing the restore operation to succeed despite not
having completed nor having cleared the flag from the database.
Took me a little while to track that down as the lack of any error was
quite disconcerting :)

lxd/cluster: Fix forceful stop on restore

---

scripts/bash/lxd-client

Resolves #9231 
Signed-off-by: Uzi Erdenebileg <lzijbuan@gmail.com>

bash-completion: Add restore snapshots

---

lxd/instance/drivers/driver_lxc.go
lxd/main_forkuevent.go

forkuevent: fixes

---

lxd/api_internal.go
lxd/daemon.go
lxd/operations.go

Daemon: Fix shutdown panic

---

doc/instances.md
lxd/instance/drivers/driver_qemu.go

Fixes for VM CPU topology

---

lxc/import.go

`lxc import` - read from stdin

---

lxd/api_cluster.go

lxd/cluster: Log leader address on failure

---

lxd/fsmonitor/drivers/driver_fsnotify.go

lxd/fsmonitor: Don't crash on Walk errors

---

lxd/storage/drivers/driver_ceph.go

lxd/storage/ceph: Properly support pre-existing empty pools

---

lxd/api_1.0.go

API: Prevent update of cluster.https_address in doApi10Update

---

doc/instances.md

Doc: fix typo for hardware offload

---

doc/networks.md

Doc: fix remove non-existent anchor in link to network-peers.md

---

lxd/instance_post.go

lxd/instances: Use correct project in live migration

---

doc/instances.md

Closes #9439
Signed-off-by: Ryan Bethke <rkbethke@utexas.edu>

doc: Elaborate on pongo2 date-time syntax for snapshots

---

lxd/db/networks.go
lxd/db/storage_pools.go
lxd/db/storage_volumes.go

DB: Always defer close until after statement has returned to avoid panicking on error

---

lxd/api_1.0.go
lxd/daemon.go
lxd/db/warnings_types.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/drivers/load.go

Warning entry for missing instance driver

---

lxd/network/openvswitch/ovn.go

lxd/network/ovn: Support SSL

---

doc/instances.md
lxd/device/nic_routed.go
test/suites/container_devices_nic_bridged.sh
test/suites/container_devices_nic_p2p.sh
test/suites/container_devices_nic_physical.sh
test/suites/container_devices_nic_routed.sh

Albeit it without the automatic IP address and gateway configuration that containers enjoy.
Closes https://github.com/lxc/lxd/pull/9367

NIC: Adds routed NIC support for VMs

---

doc/server.md

Self-explanatory by the subject

doc: Fix misspelling in server.md

---

lxd/include/error_utils.h
lxd/include/lxd.h
lxd/include/macro.h
lxd/include/process_utils.h
lxd/include/syscall_wrappers.h
lxd/main_forkexec.go
lxd/main_forkusernsexec.go

forkusernsexec: close file descriptors before exec

---

lxd/main_forkusernsexec.go

forkusernsexec: fixes

---

shared/util_linux.go

util_linux: ensure that O_NOCTTY is raised when opening terminals

---

doc/api-extensions.md
doc/cloud-init.md
doc/debugging.md
doc/events.md
doc/instances.md
doc/metrics.md
doc/network-acls.md
doc/network-forwards.md
doc/networks.md
doc/preseed.md
doc/rest-api.md
doc/storage.md
doc/syscall-interception.md

Markdown fixes from https://github.com/lxc/lxd/pull/9556/

Simple doc fixes

---

lxd/instance/drivers/driver_qemu.go
lxd/storage/drivers/generic_vfs.go

Fixes https://github.com/lxc/lxd/issues/9557
Associated tests: https://github.com/lxc/lxc-ci/pull/417

VM: Move readonly config mount out of config directory and into devices directory

---

doc/restapi_landing.md

doc: Fix typo in ToC entry

---

shared/termios/termios_unix.go

The race dectector complains otherwise as Tom realized.

shared/termios: manually copy termios settings between Go and C

---

shared/termios/termios_unix.go

shared/termios: actually copy the values not the index

---

shared/termios/termios_unix.go

They are causing some issues with ctrl+c

Shared: Revert recent termios fixes

---

lxd/instance/drivers/driver_lxc_cmd.go

This is available from Go 1.12.
Also removes potential panic situation.

Instance: Use exitErr.ExitCode function for containers

---

test/main.sh
test/suites/exec.sh

Before we starting making changes to the exec handler.

Instance: Add more exec tests

---

lxd/instance_exec.go
test/suites/exec.sh

Instance: Adds non-websocket exec tests

---

lxd/device/disk.go

Addresses https://github.com/lxc/lxd/issues/9584.

lxd/device: Improves error message for custom storage volumes when shift is true.

---

lxd/device/disk.go

lxd/device: Fix golint

---

lxd/device/nic_ovn.go

To avoid any future errors from causing the OVS bridge port from being left behind.

Instance: Clear up OVS integration bridge port earlier in stop sequence for OVN NICs

---

doc/api-extensions.md
lxc/cluster.go
lxd/api_cluster.go
lxd/db/node.go
shared/version/api.go
test/suites/clustering.sh

Add cluster member role to indicate the leader

---

lxd/events/events.go

This allows for the server and client to be suspended and not immediately timeout when resumed sometime later.
Fixes #9622

Events: Switch events websocket heartbeat to counter rather than using absolute deadline times

---

doc/storage.md

Closes #9596
Signed-off-by: Evan Z Seils <evanseils2013@gmail.org>

doc: Clarify btrfs resize documentation

---

doc/api-extensions.md

PR for #9651 Just a one-word typo fix.

doc/api-extensions.md: fixed typo in gpu_mig section

---

doc/storage.md

Signed-off-by: Jeffery Wu <jeff2814@hotmail.com>

doc: Reformatted Storage Documentation to Organize Keys by Storage Type

---

doc/instances.md
lxd/device/nic_routed.go
lxd/ip/route.go
test/suites/container_devices_nic_routed.sh

Add ipv{n}.routes setting for routed NIC type

---

doc/clustering.md

doc/cluster: Clarify join question handling

---

test/backends/ceph.sh
test/includes/clustering.sh
test/suites/clustering.sh
test/suites/container_local_cross_pool_handling.sh
test/suites/storage_driver_ceph.sh
test/suites/storage_local_volume_handling.sh

tests: Bump pg_num to 16

---

lxd/cluster/gateway.go

lxd/cluster: Update not clustered error

---

.gitignore

gitignore: Ignore potential binaries

---

lxc/utils.go

lxc/utils: Make byName sort all columns

---

lxd/db/instance_profiles.go

Small typo was leaving a dangling error :)

lxd/db/instance/profiles: Add missing error to stmt.Exec

---

lxd/device/nic_routed.go
test/suites/container_devices_nic_routed.sh

NIC: Don't add auto gateway when IP family not in use

---

lxd/device/disk.go
test/suites/container_devices_disk.sh
test/suites/container_devices_disk_restricted.sh

Disk: Fix support for bind mounting unix sockets as source by opening with O_PATH

---

lxd/db/cluster/open.go
lxd/db/cluster/open_test.go
lxd/db/cluster/schema.go
lxd/db/cluster/update.go
lxd/db/db_internal_test.go
lxd/db/instances_test.go
lxd/db/node.go
lxd/db/node_test.go
lxd/db/snapshots_test.go
lxd/db/storage_pools.go
lxd/db/storage_volumes.go
lxd/db/storage_volumes_test.go

This reduces error prone handling checks of `sql.NullString`. 
https://github.com/lxc/lxd/pull/9692 Must be merged before this.
Fixes #9414

Makes description columns non-nullable.

---

lxd/api_cluster.go
lxd/cluster/heartbeat.go
lxd/cluster/info.go
lxd/cluster/membership.go
test/suites/clustering.sh

Also improves reliability of clustering rebalance test.

Cluster: Logging consistency improvements and removes unnecessary call to EventsUpdateListeners

---

lxd/daemon_storage.go
lxd/images.go

We have logic which deletes all unknown image files on startup, but this
assumes that the image storage volume isn't shared with other servers.
As we now support using a cephfs volume for shared image storage, we're
finding ourselves deleting images downloaded by other servers on startup
which isn't exactly ideal.
This adds a reasonably fast check to see if we're using a shared storage
volume and if so, skip that logic entirely.

lxd/images: Don't cleanup unknown images from shared volume

---

lxd/main_cluster.go

The daemon is not running when this command is executed. To check
whether the host is clustered, we load it's config and check if it has a
cluster address.
Fixes #9688

Checks that the host node is clustered before editing.

---

lxd-agent/exec.go
lxd/instance/drivers/driver_qemu_cmd.go
lxd/instance_exec.go
shared/network.go

Exec: Don't attempt to send signals to VM lxd-agent process if command has finished

---

lxd/daemon.go

daemon: fix feature indentation

---

CONTRIBUTING.md
README.md
doc/contributing.md
doc/doc-cheat-sheet.md
doc/index.md
doc/installing.md

Fix small issues with includes and links in the docs.

Fix broken include

---

lxd/db/backups.go
lxd/db/storage_volume_snapshots.go

Fixes #9736 "sql: Scan error on column index 2, name \"expiry_date\": converting NULL to string is unsupported"
Also fixes similar issue for backups.

DB: Handle null ExpiryDate for custom volume snapshots

---

lxd/instance/instance_utils.go

lxd/instance: Prevent nvidia.runtime on privileged containers

---

shared/usbid/README.md

shared/usbid: Document reasons to fork

---

.sphinx/_static/custom.css
.sphinx/conf.py
doc/configuration.md
doc/instances.md
doc/server.md

Several small fixes to the docs - see the commits.

Small doc fixes
