canonical/lxd

lxd/device/nic_bridged.go
lxd/device/nic_ovn.go

Rather than failing the entire State() call.
This ensures that if a client is polling the /state endpoint to find when a VM has stopped that it won't sometimes return an error during the VM shutdown process, if the NIC has been cleaned up but the VM is not yet recorded as stopped.

Network: Return -1 for Mtu in State() for bridged and ovn NICs if host interface not available

---

lxd/main_forkexec.go

Fixes: https://discuss.linuxcontainers.org/t/lxc-exec-results-in-error-failed-to-retrieve-pid-of-executing-child-process

forkexec: handle broken close_range() backport in openSUSE Leap 15.3

---

doc/virtual-machines.md

docs: Removes statement about VMs being considered experimental

---

lxd/apparmor/instance.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go

Fixes #8909
Ensure that if the instance has never been started we can still validate apparmor profile if it is changed.

AppArmor: Generate policy file when validating if needed

---

client/lxd_containers.go
client/lxd_images.go
client/lxd_instances.go
client/lxd_storage_volumes.go

Don't try next address if the initial operation creation succeeds, but then the actual operation fails.
This suggests that the error is internal to the server and retrying the same operation just on a different address for the same target can potentially exacerbate the problem.
In one example #8900 the instance copy to a remote target node failed on the target due to insufficent pool size.
This error was successfully being returned to the client, but it subsequently retried, but the original operation was not cleaned up, causing a hang.
There was no reason to retry as this could not have succeeded on a different address.
Fixes #8900

client: Only retry target addresses if initial connection fails

---

lxd/include/macro.h

P_PIDFD is defined in sys/wait.h, but isn't included anywhere explicitly as
far as I can tell, so we'll always get this define even if the kernel
headers have it.
This fixes an inscrutable compiler error on Alpine for me:
In file included from ./../../lxd/include/memory_utils.h:11,
from /root/go/pkg/mod/github.com/lxc/lxd@v0.0.0-20210607165116-5a9c2f17d640/shared/idmap/shift_linux.go:41:
./../../lxd/include/macro.h:279:17: error: expected identifier before numeric constant
279 | #define P_PIDFD 3
|                 ^
Signed-off-by: Tycho Andersen <tycho@tycho.pizza>

lxd/include: include sys/wait.h in macro.h

---

lxd/api_1.0.go
lxd/daemon.go
lxd/instance.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/drivers/load.go
lxd/instance/instance_interface.go
lxd/instance/instance_utils.go
lxd/main_init.go
lxd/state/state.go
lxd/state/testing.go

- Only indicate instance drivers that are operational in `lxc info` (`/1.0` API endpoint) output.
- Add detection for present of `/dev/kvm` and `vhost_vsock` module for `qemu` instance driver support.
- Prevents creation of instances where there is no operational supported driver for that instance type.
This ensures that you cannot copy a VM to a server that doesn't support it:
```
lxc copy va v2:
Error: Failed instance creation: Failed creating instance record: Instance type "virtual-machine" is not supported
```
Fixes #8899

Instance: Add KVM module check for VMs

---

lxd/device/proxy.go
lxd/instance/drivers/driver_lxc.go

Helps to avoid leaving orphaned proxy processes if the process fails to start up because another one is running. 
Previously this would have written over the pid file for the current process, preventing it from being stopped in the future.
Also starts to create operation locks on the `onStop` and `onStopNS` hooks to try and prevent `Start()` from trying to start the container during a container-initiated stop process. There is already a check in `startCommon()` to check if the container is running using `IsRunning()` but there is a window between the container being considered stopped by liblxc and the stop hooks running that we need to also prevent `Start()` from progressing with container start. 

Proxy: Don't write out pid file until process has started OK

---

lxd/instance/drivers/driver_common.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go

- Use the same logic and messaging for operation lock usage in Start, Stop and Shutdown across instance driver types.
- Increase VM qemu driver onStop wait timeout to 5 minutes to accommodate VMs that take a long time to flush to disk on stop.
- Add Start, Stop and Shutdown debug logging to lxc driver to be consistent with qemu logging.

Instance: Make operation lock usage for Start, Stop and Shutdown consistent across lxc and qemu drivers 

---

lxc/alias.go
lxc/cluster.go
lxc/config.go
lxc/config_device.go
lxc/config_metadata.go
lxc/config_template.go
lxc/config_trust.go
lxc/file.go
lxc/image.go
lxc/image_alias.go
lxc/network.go
lxc/network_acl.go
lxc/operation.go
lxc/profile.go
lxc/project.go
lxc/remote.go
lxc/storage.go
lxc/storage_volume.go
lxc/warning.go
lxd/db/generate/db.go
lxd/db/generate/root.go
lxd/main_cluster.go
lxd/main_forkfile.go
lxd/main_forkmount.go
lxd/main_forknet.go
lxd/main_forkuevent.go

Closes #8927
Fix for `spf13/cobra`'s inconsistent handling of errors for sub-commands. This workaround properly returns an error for invalid commands.

Return error on invalid subcommand instead of usage message

---

lxd/instance/drivers/driver_common.go
lxd/instance/operationlock/operationlock.go

To try and catch the cause of the intermittent errors during restart:
```
/lxc-ci/build/tmp.pf8Hs5O5mB/go/bin/lxc restart foo --verbose
INFO[06-22|17:52:49] Restarting container                     instanceType=container instance=foo project=default action=shutdown created=2021-06-22T17:52:40+0000 ephemeral=false used=2021-06-22T17:52:48+0000 timeout=-1ns
Error: Create restart operation: Instance is busy running a stop operation
```
Also ensures that the operation lock entry is removed before closing the chanDone channel.

Instance: Improve error logging in restartCommon

---

lxd/instance/drivers/driver_qemu.go

And skip installing lxd-agent if existing is same size and same modification time as source.
This significantly reduces the per-snapshot tracking cost (in terms of size used) when creating a snapshot and starting the VM, as it doesn't need to copy a fresh lxd-agent across.
Test:
```
lxc launch images:ubuntu/focal v1 -s zfs --vm
sudo zfs list | grep test_v1
zfs/virtual-machines/test_v1                                                         9.65M  85.7M     9.66M  /var/lib/lxd/storage-pools/zfs/virtual-machines/test_v1
zfs/virtual-machines/test_v1.block                                                      1K   223G      383M  -
lxc snapshot v1
lxc start v1
sudo zfs list | grep test_v1
zfs/virtual-machines/test_v1                                                         10.5M  84.8M …
```

Instance: Don't fully regenerate VM config driver on start in generateConfigShare

---

lxd/endpoints/network.go
lxd/instance_post.go

I'm not sure exactly in what case we'd have a entry in the map but have it point to a nil listener, though based on the issue we've seen reported, it certainly looks possible and we should handle it.
Fixes #8940

Fix crash when listener is nil

---

Makefile
doc/index.md

Latest `go-dqlite` master branch requires some additional `CGO_CFLAGS` `-Wl,-z,now`, as these flags are not standard allowed by Go, the environment variable `CGO_LDFLAGS_ALLOW` must be set to be able to build.
I'm not entirely sure if I added it to all Make targets that require it, as I'm unfamiliar with most of them.

Fix godqlite build

---

lxd/api_project.go
lxd/profiles.go

* Use nils instead of the whole struct for created/updated events
* Use _ instead of - for renamed event context field names, for consistency
* Remove redundant `new_name` from Renamed events

Fix up lifecycle event context fields

---

client/lxd_containers.go
client/lxd_images.go
client/lxd_instances.go
client/lxd_storage_volumes.go

This reverts commit 46fe2f1685113a81c0027b67b9081c90dd3400eb.
It seems the retry mechanism is more complicated than I realised and has caused issues:
https://discuss.linuxcontainers.org/t/lxc-copy-to-internal-ip-instead-of-public-ip/11437

Revert "client: Only retry target addresses if initial connection fails"

---

lxd/api_project.go
lxd/lifecycle/network.go
lxd/lifecycle/profile.go
lxd/lifecycle/project.go
lxd/network/driver_bridge.go
lxd/network/driver_common.go
lxd/network/driver_ovn.go
lxd/network/driver_physical.go
lxd/networks.go
lxd/operations/operations.go
lxd/profiles.go
lxd/request/request.go

This one's a messier one!
* CreateRequestor function in lxd/request takes an http request and creates a requestor for lifecycles.
* `lifecycle.Event` will now accept a requestor as a parameter if there is no operation
* Network lifecycles have been moved from `lxd/network/driver_common` to `lxd/networks` to access the requestor
* As a result, the `create` function in `lxd/network/driver_common` and its references were removed

Add requestors for all lifecycle events

---

Makefile

Without this, an existing CGO_LDFLAGS_ALLOW would get double quoted
leading to a shell parsing error.
Closes #8949

Makefile: Tweak quoting

---

lxd/db/warnings_types.go
lxd/instances.go

A rework on the previous PR as I was completely wrong about the contributing rules and messed up the commit messages.
NOTE: The current approach of retrying instance autostart will encounter significant scalability issue if users have scheduled **LOTS** instances autostart. One of the solutions to this issue is by implementing WaitGroup and goroutines to speed up the autostart retries in the backgrounds, however that will contradict with the purpose of **boot.autostart.delay**. Please let me know your thoughts on this :)
Resolves #8858.
Signed-off-by: Ricky Yu lijierickyyu@gmail.com

Add the mechanism of retrying instance autostart when autostart fails

---

doc/rest-api.yaml
lxd/daemon_images.go
lxd/images.go
lxd/lifecycle/image.go
lxd/lifecycle/image_alias.go

* Created, Deleted, Updated, Retrieved, Pushed, Refreshed, and Secret Created events for Images
* CRUD for Image aliases
* I noticed `imageAliasDeleted` was missing its swagger documentation, so I added it.

Image & Image Alias lifecycle events

---

lxd/api_cluster.go
lxd/lifecycle/cluster.go
lxd/lifecycle/cluster_member.go

* A bit more specific events than just CRUD here.
* `Enabled` -- cluster initialized
* `Disabled` -- turning off clustering
* `CertificateUpdated` -- updating the certificates on all cluster members
* `TokenCreated` -- for creating join tokens
For members:
* Updated, Renamed and Removed, and Added

Cluster and Cluster Member lifecycle events

---

client/lxd_containers.go
client/lxd_images.go
client/lxd_instances.go
client/lxd_storage_volumes.go
client/util.go
lxd/cluster/notify.go
shared/network.go

Don't try next address if the initial operation creation succeeds, but then the actual operation fails.
This suggests that the error is internal to the server and retrying the same operation just on a different address for the same target can potentially exacerbate the problem.
In one example #8900 the instance copy to a remote target node failed on the target due to insufficient pool size.
This error was successfully being returned to the client, but because it subsequently retried, and the original operation was not cleaned up, it caused a hang.
There was no reason to retry as this could not have succeeded on a different address.
Also updates the error returned when multiple errors do occur so they are listed in order rather than randomly.
Fixes #8900

Client: Only retry remote operation on a different URL if the last attempt failed to connect

---

lxd/instance/drivers/driver_common.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go

Also prevent trying to start instances that are in Error state to avoid writing over active processes PID file causing to be untracked.
Fixes #8958

VM: Return Error status code if QEMU process running but QMP socket isn't responsive

---

lxd/instance/drivers/driver_common.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go

Also fix shutdown lifecycle events for all instance types which was broken for self-initiated shutdowns in https://github.com/lxc/lxd/commit/69ed7f0e091a6652a527667f215e8404bf3b7a93
Also handles "internal-error" from QEMU QMP status request when KVM has crashed.
Behaviour:
```
lxc launch images:ubuntu/focal v1 --vm
lxc ls v1
+------+---------+---------------------+-------------------------------------------------+-----------------+-----------+
| NAME |  STATE  |        IPV4         |                      IPV6                       |      TYPE       | SNAPSHOTS |
+------+---------+---------------------+-------------------------------------------------+-----------------+-----------+
| v1   | RUNNING | 10.98.30.5 (enp5s0) | fd42:f402:8623:5b6b:216:3eff:fe82:72f2 (enp5s0) | VIRTUAL-MACHINE | …
```

VM: Allow force stop to kill QEMU process if in Error status

---

lxd/device/nic_bridged.go
test/suites/clustering.sh
test/suites/container_devices_nic_bridged_filtering.sh

Also allow specifying static IPs when the managed parent network has DHCP disabled if IP filtering is enabled.

NIC: Apply managed network validation checks when bridged NIC parent is set to a managed network

---

lxd/db/entity.go
lxd/db/instances.go
lxd/db/instances_test.go
lxd/db/warnings.go
lxd/instance/drivers/driver_common.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go

Also:
- Add support for generating warnings for VMs (The use of `GetInstances()` didn't have the correct filter on it and was only considering containers).
- Don't make generating the entity URL an absolute requirement for displaying the persistent warnings (just log a warning on failure).

Warnings: Delete instance related warnings when instance deleted

---

lxd/device/nic_bridged.go

Fixes #8921 and #8799
Tested with:
- Single server and project.
- Single server with instances in different projects connected to same bridge.
- Multi-server cluster with instances on different members connect to the same network (albeit it with different DHCP servers).

NIC: Check static IPs are not defined on other NIC on same network and cluster member

---

lxd/daemon.go

Instead of failing, there should be a warning if warnings cannot be
created using the warnings API.

lxd/daemon: Warn if warnings cannot be created/resolved

---

lxd/network/driver_bridge.go

This adds a _gateway DNS record when dnsmasq is in charge of DNS.
Closes #8976

lxd/networks: Add DNS record for gateway

---

lxd/lifecycle/storage_volume.go
lxd/lifecycle/storage_volume_backup.go
lxd/lifecycle/storage_volume_snapshot.go
lxd/operations/operations.go
lxd/storage/backend_lxd.go
lxd/storage/drivers/volume.go
lxd/storage_volumes.go
lxd/storage_volumes_backup.go
lxd/storage_volumes_snapshot.go

This is a long one :)
* Added SetRequestor to allow setting the requestor on an operation. I mainly used this with empty operations to pass around the requestor easily for both sync and async operations.
* Nil operation parameters replaced with empty structs that contain the requestor
* Created a `VolumeInterface` file that is basically a copy of all the signatures for `drivers/volume.go`. I used this to reduce the number of parameters I was passing around, because there are a lot for volumes. Open to renaming suggestions other than just `VolumeInterface` :)
* Basic CRUD Volume events -- the context mentions the type of volume.
* I tried to limit the changes to `storage/backend_lxd`, but this wasn't an option for backups as they aren't handled by `backend_lxd`.

Storage volume, snapshot, and backup lifecycle events

---

lxd/device/nic_bridged.go
test/suites/clustering.sh

Also improve performance of duplicate bridged NIC IP check in `validateConfig` by filtering for local instances at the DB level.
And adds tests for duplicate IP address assignment detection.

NIC: Add detection of duplicate bridged NIC MAC address assignments

---

lxd/network/network_utils_sriov.go

Before (some instances were trying to use the same VF):
```
lxc init images:ubuntu/focal c1 -s zfs
lxc init images:ubuntu/focal c2 -s zfs
lxc init images:ubuntu/focal c3 -s zfs
lxc init images:ubuntu/focal c4 -s zfs
lxc init images:ubuntu/focal c5 -s zfs
lxc init images:ubuntu/focal c6 -s zfs
lxc config device add c1 eth0 nic nictype=sriov parent=enp1s0f0
lxc config device add c2 eth0 nic nictype=sriov parent=enp1s0f0
lxc config device add c3 eth0 nic nictype=sriov parent=enp1s0f0
lxc config device add c4 eth0 nic nictype=sriov parent=enp1s0f0
lxc config device add c5 eth0 nic nictype=sriov parent=enp1s0f0
lxc config device add c6 eth0 nic nictype=sriov parent=enp1s0f0
lxc start --all
Error: local: The following instances failed …
```

NIC: Add mutex to SRIOVFindFreeVirtualFunction to prevent concurrent start races

---

doc/api-extensions.md
doc/rest-api.yaml
lxd/api_1.0.go
lxd/main_init.go
lxd/main_init_auto.go
lxd/main_init_interactive.go
lxd/storage.go
shared/api/server.go
shared/version/api.go

And update `lxd init` to use it rather than querying the storage layer directly from the client.
Includes #8990 (to avoid conflicts).
Fixes #5955

Info: Return supported storage driver info in /1.0

---

lxd/api_cluster.go
lxd/lifecycle/certificate.go
lxd/lifecycle/network_acl.go

I noticed I wasn't consistently omitting the ID from the lifecycle event when the event was a Created/POST event.
Also noticed CertificateTokenCreated had the wrong source entirely.

Lifecycles: Fix Created source urls. 

---

lxd/api_1.0.go

This should prevent a crash where tasks have not been initialised yet.
Fixes #9006

API: Wait until LXD fully started before applying API changes in doApi10UpdateTriggers

---

doc/instances.md
lxd/instance/drivers/driver_qemu.go
shared/instance.go

Set `volatile.last_state.vsock_id` on each VM start (if VM's DB ID has changed or if key is missing).
This will enable lxd-agent connections to still work after a running VM is recovered after removing its DB records (using future recovery tool) which will cause the instance DB record's ID to change.

VM: Introduce volatile.last_state.vsock_id key

---

lxd/daemon.go
lxd/devices.go
lxd/instances.go

Doing this twice is unnecessary and inefficient.

Daemon: Remove duplicate VM monitor re-connection on start up

---

doc/instances.md
lxd/instance/drivers/driver_qemu.go
shared/instance.go

As per conversation: https://github.com/lxc/lxd/pull/9010#issuecomment-877470119

VM: Renames volatile.last_state.vsock_id to volatile.vsock_id

---

lxd/api_internal.go
lxd/instance.go
lxd/instance/drivers/driver_common.go
lxd/instance/instance_utils.go
lxd/instance_test.go
lxd/instances_post.go
lxd/migrate_instance.go
lxd/snapshot_common_test.go

This will be used (set to `false`) in the future recovery tool to avoid clearing the log dir of the instances being recovered.
This will allow running instance config and socket files to be maintained after recovery.
But for now keep all existing usage of this function passing `true` to get the old behaviour.

Instance: Add clearLogDir argument to CreateInternal

---

Makefile
lxd/api_project.go
lxd/cluster/membership.go
lxd/db/certificates.go
lxd/db/certificates.mapper.go
lxd/db/generate/db/method.go
lxd/db/generate/db/parse.go
lxd/db/generate/db/stmt.go
lxd/db/generate/file/write.go
lxd/db/instances.go
lxd/db/instances.mapper.go
lxd/db/profiles.go
lxd/db/profiles.mapper.go
lxd/db/projects.go
lxd/db/projects.mapper.go
lxd/db/snapshots.go
lxd/db/snapshots.mapper.go
lxd/instance_test.go
lxd/patches.go
lxd/profiles.go

Lots of repetitive commits here :)
This PR extends `DELETE` generation to allow deleting by more than just ID, and to allow deleting many rows at once.
Changes:
* Added `gofmt -s -w ./lxd/db/` to `Makefile` under `update-schema` for file consistency.
* Added `//go:build linux && cgo && !agent` comment as part of the generator. 
* statement generation for delete now requires the field to delete by to be specified, ie: `delete-by-name-and-project`
* method generation can now be one of `DeleteOne` or `DeleteMany`. The difference is just an if-statement that returns an error in the former case.
* the generated `Delete` method now takes the `Filter` struct for its corresponding object as its argument. 
Next up will be operations, since I have that done already. 
After that will be automatic …

Generator: Generate delete-by statements

---

lxd/device/nic_bridged.go

The current check would require BOTH the parent and network properties
to differ for the MAC check to be skipped. This is effectively
impossible and was clearly meant to be an OR instead.
Additionally, if two interfaces share the same parent but are on
different VLANs, they also should skip the MAC duplication check.

lxd/device: Fix duplicate MAC test

---

lxd/instance/drivers/qmp/commands.go

In some tests the QMP command doesn't return an error, but returns no results, so handle that.
Fixes crash:
```
Jul 20 09:52:19 home02 lxd.daemon[142401]: panic: runtime error: index out of range [0] with length 0
Jul 20 09:52:19 home02 lxd.daemon[142401]: goroutine 10261 [running]:
Jul 20 09:52:19 home02 lxd.daemon[142401]: github.com/lxc/lxd/lxd/instance/drivers/qmp.(*Monitor).QueryPCI(0xc0013141c0, 0x7447af, 0xc000010608, 0xc0000cdc00, 0x0, 0x0)
Jul 20 09:52:19 home02 lxd.daemon[142401]:         /build/lxd/parts/lxd/src/.go/src/github.com/lxc/lxd/lxd/instance/drivers/qmp/commands.go:387 +0x145
Jul 20 09:52:19 home02 lxd.daemon[142401]: github.com/lxc/lxd/lxd/instance/drivers.(*qemu).deviceDetachNIC.func1(0xc00066af30, 0xc, …
```

QMP: Fixes potential crash in QueryPCI

---

lxd/cluster/info.go
lxd/daemon.go
lxd/storage.go

- Use contextual logging where variables are logged.
- Increase log level to Warn for some database and cluster startup messages to help to ease visibility of cluster upgrade problems.
- Fixed an error message casing.

Daemon: Improve start up logging

---

shared/api/event.go

Requestor field is missing in lifecycle event log after adding it to `EventLifecycle` struct.

Support for Requestor field in lifecycle event log

---

lxd/api_internal.go
lxd/instance.go
lxd/instance/drivers/driver_common.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/drivers/load.go
lxd/instance/instance_utils.go
lxd/instance_test.go
lxd/instances_post.go
lxd/migrate_instance.go
lxd/snapshot_common_test.go
lxd/storage/drivers/driver_btrfs_volumes.go
lxd/storage/drivers/driver_ceph_volumes.go
lxd/storage/drivers/driver_lvm_volumes.go
lxd/storage/drivers/driver_zfs_volumes.go
lxd/storage/drivers/utils.go
lxd/storage/drivers/volume.go
lxd/storage/utils.go

This is enabled via an optional setting on the `Volume` struct, and will be used in the forthcoming `lxd recover` command to allow mounting of block backed volumes (LVM and Ceph) that have a non-default filesystem type.

Storage: Add ability for volume mount to probe block backed volumes for their filesystem type

---

lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go

Otherwise consider stop action failed.
This is part of an ongoing investigation into intermittent stop & delete failures in our integration network tests.

Instance: Check instance is actually stopped, and not in an error state when stopping

---

lxd/storage/drivers/utils_cgo.go
shared/idmap/shift_linux.go

We've seen some fd leakage recently when LXD spawns subprocesses at the same time as it's working on shifting instances.
This seems to be because of a missing O_CLOEXEC in the shifting logic. Doing a full audit of all our cgo open calls, I noticed another one in the storage logic too and this PR also fixes it.

Always pass O_CLOEXEC in cgo open

---

client/connection.go
lxc/config/config.go
lxc/config/file.go
test/godeps.list

- If `.config/lxc/config.yml` exists, but is empty, then use default remote.
- Reference `DefaultConfig` which exists, but wasn't being used, to avoid duplication of default values in code base.

LXC: Improvements to default config handling

---

doc/instances.md
lxc/list.go
lxc/list_test.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/instance_utils.go
lxd/profiles.go
lxd/profiles_utils.go
shared/instance.go

Adds all the plumbing to validate based on instanceType.
Based off the work of @my5t3ry in #8970 but changed to reduce per-commit delta and simplify cherry-picks.
We also don't have an actual need to determining whether a config is Any, Container or VM, so reduced the changes a bit to remove that.
Closes #8970
Closes #8912

Validate instance config on a per-instance-type basis

---

doc/api-extensions.md
lxd/resources/gpu.go
lxd/resources/network.go
lxd/resources/storage.go
lxd/resources/utils.go
shared/api/resource.go
shared/version/api.go

Machines with DisplayLink adapters would fail to get GPU information using the resources API.
This fixes the source of the issue (nested devices) and attempts to fill in a USBAddress field too.

Add USB GPU support

---

lxd/backup.go
lxd/storage/backend_lxd.go

Storage: Fix incorrect (full) snapshot name being written to Name field in custom volume snapshot backup index

---

lxd/cgroup/file.go

The logic present in the filesystem-based cgroup reader was backwards
and should only extract the parent directory when the cgroup IS
/init.slice and not on other systems. This was leading the cgroup path
to be /sys/fs/ instead of /sys/fs/cgroup/ on non-systemd cgroup2
installs.
Closes #8896

lxd/cgroup: Fix handling of non-systemd cgroup2

---

lxd/api_project.go
lxd/cluster/membership.go
lxd/db/certificates.go
lxd/db/certificates.interface.mapper.go
lxd/db/certificates.mapper.go
lxd/db/db.go
lxd/db/generate/db/lex.go
lxd/db/generate/db/mapping.go
lxd/db/generate/db/method.go
lxd/db/instances.go
lxd/db/instances.interface.mapper.go
lxd/db/instances.mapper.go
lxd/db/operations.go
lxd/db/operations.interface.mapper.go
lxd/db/operations.mapper.go
lxd/db/operations_test.go
lxd/db/profiles.go
lxd/db/profiles.interface.mapper.go
lxd/db/profiles.mapper.go
lxd/db/projects.go
lxd/db/projects.interface.mapper.go
lxd/db/projects.mapper.go
lxd/db/snapshots.go
lxd/db/snapshots.interface.mapper.go
lxd/db/snapshots.mapper.go
lxd/instance_test.go
lxd/operations/linux.go
lxd/patches.go
lxd/profiles.go

The goal here is adding explicit arguments to delete, and introducing a few helpers that will come in handy later on as we refactor/change more of the generator.
Main changes: 
* Generated Delete methods now take arguments instead of filters.
* Generating Delete methods now requires arguments to be passed to the generator via -by- statements, as in: `DeleteMany-by-Name-and-Type`.
* Added `ActiveFilters` and `activeFilters` helpers for parsing the `-by-` field into slices of `Field` and `string`, respectively. 
* Added proper handling of fields named `Type` to `FieldArgs` and `FieldParams` by making the functions into methods on `Mapper`. As well, added support for adding additional arguments directly into the methods, so all arguments are handled in one place.

Generator: Parameterized delete

---

lxd/api_internal_recover.go
lxd/main_recover.go
test/suites/backup.sh

Prefer restoring pool config from instance backup file over user input if available, even if custom volumes come first.

Recovery: Prefer restoring pool config from instance backup file over user input if available

---

lxd/device/disk.go

Update the comment to make it clear that custom block volumes may only
ever be attached to VMs and not containers.

lxd/device/disk: Update comment regading custom block volumes

---

lxd/storage/drivers/driver_btrfs_volumes.go
lxd/storage/drivers/driver_zfs_volumes.go
lxd/storage/drivers/generic_vfs.go

This currently silently exports an empty tarball for some storage driver types and has not been audited to work fully for any storage driver, so disable for now until we can implement properly.
Related to #9064

Storage: Prevent custom block volume export

---

lxc/init.go
test/suites/clustering.sh

Previously we added support for detecting if a server supported the NIC `network` property and then allowed the use of any managed network when doing `lxc network attach` in https://github.com/lxc/lxd/pull/8334.
This PR does something similar for the `--network` flag in `lxc init` and `lxc launch`.

lxc/init: When using network flag support managed networks

---

lxd/main_daemon.go

lxd: Hide built-in completion command

---

lxd/include/syscall_wrappers.h
lxd/main_checkfeature.go
lxd/main_forkexec.go

Newer glibc version's provide a wrapper for close_range().
Fixes: #9084

syscall_wrappers: don't conflict with glibc provided close_range()

---

lxd/device/nic_bridged.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/instance_utils.go
lxd/instance_post.go
test/suites/container_local_cross_pool_handling.sh

Fixes https://discuss.linuxcontainers.org/t/move-migration-operation-failure/11781
- Populates instance `volatile.uuid` config key on creation (so it always exists).
- Uses a consistent temporary instance name (derived from the source instance's `volatile.uuid` config key) when creating a temporary copy of an instance during a migration or storage pool move (before the original is removed and the copy rename to the original name).
- Adds a helper function for use when validating if a resource belongs to the same logical instance (either the original instance or the temporary copy of the original instance).
- Update tests to check for this scenario.
We probably should add a check for `volatile.uuid` being unique in the future, which would then break this fix, however having the …

Instance: Don't trigger duplicate NIC warnings when performing cross-pool move

---

Makefile
lxd/db/certificates.go
lxd/db/certificates.mapper.go
lxd/db/certificates_test.go
lxd/db/generate/db/method.go
lxd/db/generate/db/parse.go
lxd/db/generate/db/stmt.go
lxd/db/images.go
lxd/db/images.mapper.go
lxd/db/images_test.go
lxd/db/instances.mapper.go
lxd/db/operations.mapper.go
lxd/db/profiles.mapper.go
lxd/db/projects.mapper.go
lxd/db/snapshots.mapper.go
lxd/db/transaction.go

This PR drops support for the tag `db:comparison` in the generator. If a `LIKE` query is required, as is the case for `Image`, it is written by hand. 
This caused a bit of an awkward situation with our current strategy of using `false` for boolean zero-values. There's currently a `FIXME` with a conditional that uses `nil` if `Public` is `false`. I'm planning on removing that in an upcoming PR, where I replace Filter fields with pointers.
I also removed some unused statements, and thus needed to add support for queries with no filters, with a simple if-block. The function name `Filters` was quite confusing, and it wasn't very clear to me that it was parsing the statement variable names, so I renamed it to `FiltersFromStmt` to make that clear.
I also added `goimports` to the makefile to …

Generator: Remove wildcard support

---

lxd/apparmor/instance_lxc.go

This should make systemd a bit happier in unprivileged containers.
Closes #9083

lxd/apparmor: Allow remount using strictatime

---

lxd/api_cluster.go
lxd/daemon.go
lxd/device/device_common.go
lxd/device/device_interface.go
lxd/device/disk.go
lxd/device/nic_bridged.go
lxd/device/nic_macvlan.go
lxd/device/nic_ovn.go
lxd/device/nic_sriov.go
lxd/device/none.go
lxd/device/tpm.go
lxd/instance/drivers/driver_common.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/instance_state.go
test/suites/clustering.sh

This fixes some issues in the logic determining whether something is migratable or not, also moves it over to the device package.
On top of that, it fixes a race/conflict around volatile key usage when mixing API level migration with server level Start by fetching a new copy of the entire instance from the database.

lxd/cluster: Fix some early issues with cluster evacuation/restore

---

doc/instances.md
lxd/device/nic_bridged.go
lxd/instance/instance_utils.go

Allows for an instance to be moved between projects without triggering duplicate MAC address errors.

Instance: Change IsSameLogicalInstance to consider volatile.uuid globally unique 

---

lxd/device/nic_routed.go
test/suites/container_devices_nic_routed.sh

See https://discuss.linuxcontainers.org/t/container-cant-ping-its-neighbour-ip-address-since-its-also-its-own-broadcast-address/11829
Change was introduced in liblxc by https://github.com/lxc/lxc/commit/365136359f8bf991ed172b498909000ec18b32de which change how the broadcast address was automatically calculated. Previously when using a `routed` NIC with a /32 IPv4 address it was being set to `255.255.255.255` which allowed adjacent IP communication.
However that commit changed it so that the broadcast address was either set to the same IP as the specified address or the address after it, which could lead adjacent IPs not being reachable if assigned on different instance NICs.
This PR uses the undocumented feature in libxc to specify an all-zero broadcast address, which then works around …

NIC: Works around routed NIC regression in liblxc by setting zero broadcast address

---

doc/api-extensions.md
doc/networks.md
lxd/network/driver_ovn.go
shared/version/api.go

See https://discuss.linuxcontainers.org/t/lxd-floating-ip-addresses/11801 for tech spec.
Adds support for specifying an outbound external NAT address for `ovn` networks using `ipv4.nat.address` and `ipv6.nat.address`.
The specified address must be within one of the uplink network's `ipv{n}.routes` and not overlap with an external subnet in use by another OVN network on the same uplink (either the network itself or one of the NICs connected to it).
NICs connected to the same OVN network may have externally routed subnet(s) that overlap with the network's `ipv{n}.nat.address`.
Because the NAT addresses will be by definition outside of the uplink's own subnet, it is required that routes are added on the uplink that forward the desired addresses to the OVN network's external router IP …

Network: Add source NAT address support

---

lxd/device/gpu_mdev.go

A recent uuid package cleanup incorrectly turned an allocation into a
definition, causing the resulting device to miss its UUID field.

lxd/device/gpu_mdev: Fix mdevUUID logic

---

lxd/response/smart.go
lxd/response/smart_linux.go
lxd/storage_pools.go
lxd/storage_pools_utils.go
test/suites/backup.sh

As we begin the transition to using the stdlib `errors` package for error wrapping rather than `github.com/pkg/errors` this PR updates the `response.SmartError()` function to utilise both packages in order to find the root cause of an error and simplifies the process it uses to match against known errors to convert them to HTTP status codes.
Also switches to using the generic HTTP status text when the errors exactly match rather than a hardcoded internal string.
In some cases this is identical or similar (except the casing), but there are a few differences I felt I should highlight:
* Forbidden used to return "not authorized" now would return "Forbidden" - this seems more appropriate as "not authorized" is a different HTTP error code - perhaps we should be using that instead?
* Conflict …

Response: Rework SmartError function to support stdlib errors package unwrapping

---

lxd/storage/backend_lxd.go
lxd/storage/drivers/driver_btrfs_volumes.go
lxd/storage/drivers/driver_dir_volumes.go

If supported by the storage driver.
Also ensure that BTRFS quota types are consistently set/unset as needed.
This is something I noticed whilst looking at https://discuss.linuxcontainers.org/t/btrfs-issues-storage-pools-btrfs-empty-and-btrfs-quota-100-while-inside-the-vm-only-48-utilized/11897 - that a BTRFS quota set on a VM filesystem volume was not removed if the `size` property was removed.

Storage: Allow quota removal from VM config filesystem volumes

---

client/lxd.go
lxd/network/driver_ovn.go
lxd/response/smart.go
shared/api/error.go

Based on a recent discussion with @morphis to allow LXD client users to access the response status code, and an additional desire to be able to return accurate HTTP status codes back to the client from deeper within LXD's callstack.
- This allows functions that return an error due to a known specific error scenario (such as a conflict or not found error) to explicitly pass than information as an HTTP status code by returning a `api.StatusError` type.
- Adds the `api.StatusErrorf()` helper function for creating `api.StatusError` errors, e.g. `api.StatusErrorf(400, "Field %q is invalid", "myfield")`
- Updates `response.SmartError()` to detect `api.StatusError` type error and alter the API HTTP status response accordingly.
- Updates `client.lxdParseResponse()` to convert the HTTP status code …

API: Adds StatusError error type and updates SmartError to handle it

---

lxd/storage/backend_lxd.go
test/suites/backup.sh

Allows storage pool recovery when mount path is missing.
Reported from https://discuss.linuxcontainers.org/t/moving-a-block-device-storage-pool-to-a-new-server/11935/3?u=tomp

Storage: Create pool mount path if needed in Mount

---

lxd/network/driver_physical.go

This fixes the function description for physical networks as it's not technically a no-op.
It also renames the `start` function to `setup` as it's called in the same way as that function in the bridged implementation.
Lastly the signature is changed to include the old config map as that will be needed later on when adding BGP.

lxd/network/physical: Align with bridged

---

lxd/db/network_acls.go
lxd/network/driver_common.go

- Remove `networkACLConfigUpdate` as not needed  (shifts config deletion into `UpdateNetworkACL` directly).
- Switch to `shared.IsUserConfig()`.

Network: Code cleanups

---

client/lxd_certificates.go
client/lxd_cluster.go
client/lxd_containers.go
client/lxd_images.go
client/lxd_instances.go
client/lxd_network_acls.go
client/lxd_networks.go
client/lxd_operations.go
client/lxd_profiles.go
client/lxd_projects.go
client/lxd_storage_pools.go
client/lxd_storage_volumes.go
client/lxd_warnings.go
client/util.go

- Reduces code duplication.
- Improves correctness of checking that returned URL matches the expected prefix.
- Prevents panic if invalid URL is returned.
- Standardises comments.
- Adds a missing API feature check in Warnings function.

Client: Improve parsing of response URLs in resource name extraction

---

lxc/main_aliases.go

LXC: Fix panic when empty argument passed to lxc command

---

lxd/db/network_forwards.go
lxd/firewall/drivers/drivers_nftables.go
lxd/firewall/drivers/drivers_nftables_templates.go
lxd/firewall/drivers/drivers_xtables.go
lxd/network/driver_ovn.go
lxd/network_forwards.go

Bug introduced by https://github.com/lxc/lxd/commit/96cd8ad1d466be666b90948c9f2f12c2a806001e
Test to catch this bug are here: https://github.com/lxc/lxd/pull/9173
Also improves comments, and adds `memberSpecific` argument to `GetNetworkForwards` and `GetNetworkForwardListenAddresses` for forthcoming bridge network forwards feature.

Device: Fix proxy listen port bug

---

mkdocs.yml

Since we've moved away from readthedocs, this file can be removed.

Remove mkdocs.yml

---

lxd/device/nic_bridged.go
lxd/device/proxy.go
lxd/network/network_utils.go

Reported from: 
* https://discuss.linuxcontainers.org/t/failed-to-update-device-eth0-security-ipv6-filtering-requires-br-netfilter-be-loaded-open-proc-sys-net-bridge-bridge-nf-call-ip6tables-no-such-file-or-directory/12002/4?u=tomp
* https://discuss.linuxcontainers.org/t/problems-setting-up-proxy-device-in-lxd-4-17/12044

Device: Unifies br_netfilter checks and improves error messages for proxy devices

---

lxc/cluster.go
lxd/api_cluster.go

To prevent races creating duplicate entries for the same name.

Cluster: Add mutex to cluster join token creation

---

doc/clustering.md
lxd/init.go
lxd/main_init.go
lxd/main_init_interactive.go

Fixes #9187
Looks like https://github.com/lxc/lxd/pull/9113 didn't get backported to stable-4.0.

lxd/init: Allow preseeding cluster_token (stable-4.0)

---

lxd/endpoints/cluster.go
lxd/endpoints/network.go
lxd/main_init.go
lxd/main_init_interactive.go
lxd/util/net.go

Fixes #9186, and as I was working on that I also discovered that if you specified an initial first-member server address of `2602:fc62:b:1018:0:1::2` then it would later pass the listener coverage checks because of its canonical form `2602:fc62:b:1018:0:1:0:2` causing a listener bind error.
I also noticed that we were doing a partial canonicalisation in the cluster join token logic, so that now uses `util.CanonicalNetworkAddress` too.
So now we are converting the specified addresses to their canonical form in more places, and also using true `net.IP` for coverage checking rather than literal string comparison.

Cluster: More IPv6 listener bug fixes

---

lxc/remote.go
lxd-agent/main_agent.go
lxd-p2c/utils.go
lxd/endpoints/cluster.go
lxd/endpoints/endpoints.go
lxd/endpoints/network.go
lxd/endpoints/pprof.go
lxd/main_cluster.go
lxd/main_init.go
lxd/main_init_auto.go
lxd/main_init_interactive.go
lxd/node/config.go
lxd/resources/network.go
lxd/util/http.go
lxd/util/net.go
lxd/util/net_test.go
lxd/vsock/vsock.go
shared/util.go
test/suites/clustering.sh

Closes #9188
https://github.com/lxc/lxd/pull/9199/commits/c02ab335de1ba726abd6e372d5608ae123358a91
https://github.com/lxc/lxd/pull/9199/commits/2fdc6c952fa539c84073bc44bfdb445fc6ffde27
Changes: 
* Makes sure the network address is not unset to `""` before checking if it covers the cluster address.
* Adds a test for this case.
Closes #9191
https://github.com/lxc/lxd/pull/9199/commits/9ba9447574b9cd91919be49c54886ce88f581521
Changes:
* Uses `api.StatusErrorf` to return a not-found error instead of an internal error.
* Thanks to @tomponline for the fix here :)
Closes #9193
https://github.com/lxc/lxd/pull/9199/commits/a29655125b15448bf7e3ef236783d20241b39ee2 and the rest.
Changes:
* Replaces `shared.DefaultPort` with `shared.HTTPSDefaultPort` and adds `shared.HTTPDefaultPort` to set `8443` …

More listener bugfixes

---

lxc/main_aliases.go
lxc/main_test.go

Consider the following alias: `lxc alias add foo "exec c1 -- echo @ARGS@"`.
Previously, this would expand to `lxc exec c1 -- echo @ARGS@ 1` if
called as `lxc foo 1`, which is incorrect.
This fixes the expansion of `@ARGS@` which makes the above call
correctly expand to `lxc exec c1 -- echo 1`.

lxc: Fix aliases containing @ARGS@

---

doc/clustering.md
lxd/api_cluster.go
lxd/cluster/gateway.go
lxd/cluster/membership.go
lxd/cluster/membership_test.go
lxd/cluster/raft_test.go
lxd/cluster/recover.go
lxd/cluster/upgrade.go
lxd/cluster/upgrade_test.go
lxd/db/node/schema.go
lxd/db/node/update.go
lxd/db/raft.go
lxd/db/raft_test.go
lxd/main_cluster.go
lxd/node/raft.go
lxd/node/raft_test.go

This PR adds the cluster member name field as a column to the `raft_nodes` local table. Since the dqlite representation of a raft node is still limited to `ID,` `Address`, and `Role`, the `Name` is extracted from the global `nodes` database, if the global database is accessible. If not, the field will not be populated. 
Also addressed a few small bugs:
* Typo in `RemoteRaftNode`, should be `RemoveRaftNode`
* If `patch.global.sql` exists already, append to it in `lxd cluster edit`
* Make `latest_segment` a comment instead of a yaml field to prevent any confusion with its value being different node-to-node.

Add 'name' to 'raft_nodes' table.

---

lxd/device/nic_bridged.go
lxd/device/nic_ovn.go

Don't allow instance ipv{n}.address to be same as managed parent network

---

lxd/network/driver_bridge.go
lxd/network/driver_common.go

This PR adds support for exporting `bridge` network address forwards through BGP.
E.g.
```
lxc query /internal/testing/bgp
{
"peers": [],
"prefixes": [
{
"nexthop": "::",
"owner": "network_1",
"prefix": "fd42:b545:2e58:ec06::/64"
},
{
"nexthop": "0.0.0.0",
"owner": "network_1_forward",
"prefix": "10.0.0.1/32"
},
{
"nexthop": "0.0.0.0",
"owner": "network_1",
"prefix": "10.128.213.0/24"
},
{
"nexthop": "0.0.0.0",
"owner": "network_1_forward",
"prefix": "10.128.213.2/32"
}
],
"server": {
"address": "",
"asn": 0,
"router_id": "<nil>",
"running": false
}
}
```

Network: Exports bridge forward addresses via BGP

---

lxd/daemon_storage.go

Closes #9195 
Unmounts any still-mounted storage pools upon cleanly shutting down lxd.

Unmount storage pools on lxd shutdown

---

lxd/cluster/gateway.go
lxd/cluster/heartbeat.go
lxd/cluster/recover.go

Fixes issue introduced by https://github.com/lxc/lxd/pull/9209/commits/1db065b06b2e1b16ea997927d158a4cae5162714 that was reported from https://discuss.linuxcontainers.org/t/heartbeat-timeouts-after-upgrade-to-4-18/12164
The action of performing 1 transaction and query per raft node in heartbeat payload (in order to enrich the member name) was causing the heartbeat handler to take >1s in scenarios where the recipient cluster member was in a remote DC (so the queries back to the leader were slower) and in cases where there was a larger cluster with more raft members.
When the heartbeat handler exceeds 1s, the leader considers the member offline.
This PR instead adds the member name to the heartbeat payload and performs the enrichment in a single transaction and query on the leader. The name …

Cluster: Fix slow heartbeat response due to multiple remote queries when populating raft node names

---

lxd/util/kernel.go

Closes https://github.com/lxc/lxd-pkg-snap/issues/85

lxd/util: Respect modprobe configuration

---

lxd/cgroup/abstraction.go
lxd/cgroup/types.go
lxd/response/response.go
lxd/storage/filesystem/fs.go

- lxd/cgroup: Add GetMemoryStats
- lxd/cgroup: Add GetIOStats
- lxd/cgroup: Add GetCPUAcctUsageAll
- lxd/cgroup: Add GetTotalProcesses
- lxd/response: Add SyncResponsePlain
- lxd/storage/filesystem: Add FSTypeToName

Extend cgroup abstraction and other preparations for metrics

---

shared/api/network_forward.go

shared/api/network/forward: Fix api extension references

---

lxd/device/tpm.go

lxd/device/tpm: Require `path` only for containers

---

lxd/daemon.go
lxd/daemon_storage.go
lxd/main_daemon.go
lxd/storage/drivers/driver_lvm.go

This PR takes just the clear fixes from https://github.com/lxc/lxd/pull/9258 (whilst maintaining the work around that skips unmounting the LVM storage pools at shutdown).
This PR fixes the following issues:
- Stops LXD daemon shutdown from trying to unmount storage pools before instances are stopped during full shutdown.
- Stops LXD daemon unmounting storage pools during a reload (rather than just the LXD daemon storage volumes as originally intended).
- Detects running VMs when considering if to unmount LXD shared mounts during stop.

Daemon: Shutdown storage fixes

---

doc/rest-api.yaml
lxd/instance_console.go

Addresses #9260.
Looking at instance GET (just above instance PATCH) I thought I saw another return-code/example mismatch, and I figured I might as well just PR a fix. When grepping, I realized my mistake, but also found an actual mismatch :grin: This PR fixes that one.

Fix documented HTTP return code in console POST

---

doc/rest-api.md

doc/rest-api: Add missing entry for 112 (error)

---

lxd/instance/drivers/driver_lxc.go

Due to a rework of the raw.lxc handling, the config wouldn't be loaded
when stopping or shutting down a container.  This caused some keys,
e.g. `lxc.signal.*`, to be ignored.

lxd/instance/drivers: Fix raw.lxc handling for shutdown/stop

---

lxd/cgroup/init.go
lxd/sys/os.go

This replaces `init` with `Init` as the former wouldn't show log
messages at all.

lxd/cgroup: Fix logging in cgroup init

---

lxd-agent/metrics.go
lxd/instance/drivers/driver_lxc.go
lxd/storage/filesystem/fs.go
lxd/storage/filesystem/fs_32bit.go
lxd/storage/filesystem/fs_64bit.go

Continues on with the concept from https://github.com/lxc/lxd/pull/9056 in order to fix #9275
Tested this script on 64bit and 32bit plaforms:
```go
package main
import (
"fmt"
"os"
"golang.org/x/sys/unix"
)
// Filesystem magic numbers.
const (
FilesystemSuperMagicZfs = 0x2fc12fc1
)
// StatVFS retrieves Virtual File System (VFS) info about a path.
func StatVFS(path string) (*unix.Statfs_t, error) {
var st unix.Statfs_t
err := unix.Statfs(path, &st)
return nil, err
}
return &st, nil
}
// Detect returns the filesystem on which the passed-in path sits.
func Detect(path string) (string, error) {
fs, err := StatVFS(path)
return "", err
}
return FSTypeToName(int32(fs.Type))
}
// FSTypeToName returns the name of the given fs type.
// The fsType is from the Type …
```

Storage: Fix filesystem detection to work on 32bit platforms

---

lxd-agent/devlxd.go
lxd-agent/server.go
lxd/cluster/gateway.go
lxd/cluster/notify_test.go
lxd/daemon.go
lxd/devlxd.go
lxd/endpoints/endpoints_test.go
lxd/main.go
lxd/operations/response.go
lxd/response/response.go
lxd/util/http.go
shared/json.go

This has helped me debug/understand the different response types and the relationship between api.Response.Code and HTTP response code (i.e they are the same for error responses).
It adds support for passing context to the request and response debug loggers, and I've updated them to include the request info and the response HTTP code.

lxd: Improves API request/response debug logging

---

lxd-agent/devlxd.go
lxd-agent/server.go
lxd/cluster/gateway.go
lxd/cluster/notify_test.go
lxd/daemon.go
lxd/devlxd.go
lxd/endpoints/endpoints_test.go
lxd/main.go
lxd/operations/response.go
lxd/response/response.go
lxd/util/http.go
shared/json.go

Rather than using Jmap.
This brings it inline with `OperationResponse.Render()`, `ForwardedOperationResponse.Render()` and `syncResponse.Render()` functions.
This confused me for a while as I couldn't understand why `api.ResponseRaw.Error` wasn't referenced anywhere in the code, yet the associated `api.Response.Error` field was being used to display the error message in `lxdParseResponse`.  How did it get populated? Well it was because of the manual Jmap being used.
Includes https://github.com/lxc/lxd/pull/9280

LXD: Modifes errorResponse.Render function to JSON encode a api.ResponseRaw struct

---

lxd/util/http.go

lxd/util: Handle ':8443' syntax in ListenAddresses

---

lxd/api_cluster.go
lxd/instance_state.go
lxd/instances_post.go

We use "cluster member" rather than "node" for public facing terminology.
I spotted this whilst watching the demo video https://discuss.linuxcontainers.org/t/lxd-4-17-has-been-released/11812/3?u=tomp

lxd: Remove public facing errors that mention cluster "node"

---

lxd/util/http.go
lxd/util/http_test.go

In reviewing https://github.com/lxc/lxd/pull/9292 I needed to figure out what `ListenAddresses` was supposed to do, so I thought I would document it for future readers and add (limited) tests for its functionality.
I also slightly simplified it.

Util: ListenAddresses improvements

---

lxd/network/network_utils.go
shared/api/url.go
shared/api/url_test.go

I've come across the pattern of manually building URLs in LXD quite a bit.
Whilst updating the network `UsedBy` for another project I thought it might be useful to add a generic helper function for building resource URLs that would:
- Avoid the repetition of whether or not to add a URL query string parameter for `project` based on the project name.
- Escape the `project` and `target` parameters if needed.
- Escape the path parts if needed.
The URL builder type `api.URL` embeds the stdlib's `url.URL` type making it easier to add additional manipulations for more complicated scenarios.
I added it to `shared/api` package as I thought it could also be useful in the LXC client package when building URLs too, as well as on the LXD server side.

API: Adds URL builder and updates network UsedBy to use it

---

lxd/api_cluster.go
test/suites/clustering.sh

Closes #9284
This issue seems to be mostly limited to the test `clustering_remove_leader` which ensures a 2-node cluster will remain functional if the leader is dropped.
Seems the biggest issue was that I was running `changeMemberRole` twice, once on the leader and once on the remaining node. There was a slight race condition where whichever node got to that function first would update the remaining node to `voter`, before that one managed to send off a request too, but other times both would send a request, which caused dqlite to freak out.
To fix it, I just moved the `changeMemberRole` block down past the forward-to-leader block. Now, if a non-leader role is asked to drop the leader in a 2-node cluster, it will forward the whole request to the leader, as opposed to changing its raft …

Fix clustering_remove_leader calling dqlite twice

---

lxd/api_1.0.go
lxd/api_cluster.go
lxd/api_internal.go
lxd/daemon.go
lxd/images.go
lxd/main_daemon.go
lxd/main_shutdown.go

This helps to ensure that `lxd shutdown` doesn't exit until the LXD daemon process has finished, even if the server has lost access to the cluster database. Before this the `lxd shutdown` command tried to request access to the events API to wait until the LXD process finished, however when the cluster database wasn't available the events API request was failing, causing the `lxd shutdown` command think the LXD daemon process had finished and was exiting early.

Daemon: Makes /internal/shutdown synchronous

---

lxd/instance/drivers/driver_qemu_templates.go

This appears to be required on P9 and compatible with P8.
Closes #9306

lxd/qemu: Disable large decrementor on ppc64le

---

lxd/device/disk.go
lxd/storage/drivers/driver_btrfs_volumes.go
lxd/storage/drivers/driver_ceph_volumes.go
lxd/storage/drivers/driver_cephfs_volumes.go
lxd/storage/drivers/driver_dir_volumes.go
lxd/storage/drivers/driver_lvm_volumes.go
lxd/storage/drivers/driver_zfs_volumes.go

Detect the `storageDrivers.ErrInUse` error in the instance `disk` device post stop hook when unmounting a custom volume to avoid logging an error like:
```
EROR[09-29|09:11:32] Failed to stop device                    instanceType=container instance=c1 project=test err="In use" devName=sharedvol
```
Instead let the `disk` device ignore it, and ensure all storage drivers have mount ref counting (even if they don't actually do mount/unmounts, for consistent behaviour across storage drivers).
The storage drivers will then log a debug message:
```
DBUG[09-29|09:39:34] Skipping unmount as in use               pool=default driver=dir volName=test_sharedvol refCount=1
```
This issue was reported in https://discuss.linuxcontainers.org/t/lxd-eror-message-failed-to-stop-device/12247.
A continuation …

Storage: Don't log an error when unmount of custom volume is skipped due to being in use by another instance

---

lxd/api_cluster.go
lxd/response/response.go
test/includes/clustering.sh
test/includes/lxd.sh
test/suites/clustering.sh

Switches to post response hook to replace LXD process after removing a cluster member rather than use a go routine and 3s sleep.
This was causing problems as it was leaving LXD processes around after the test had run due to races in the clean up process.

Cluster: Fix cluster member remove tests

---

lxd/api_cluster.go
lxd/api_internal.go
lxd/cluster/heartbeat_test.go
lxd/cluster/membership.go
lxd/cluster/membership_test.go
lxd/cluster/upgrade_test.go
lxd/daemon.go
lxd/daemon_integration_test.go
lxd/db/db.go
lxd/db/migration_test.go
lxd/db/testing.go
lxd/devlxd_test.go
lxd/main_daemon.go
lxd/main_shutdown.go
lxd/main_test.go
lxd/operations.go
test/includes/lxd.sh
test/suites/clustering.sh
test/suites/container_devices_nic_bridged.sh
test/suites/container_devices_nic_bridged_acl.sh
test/suites/container_devices_nic_bridged_filtering.sh
test/suites/container_devices_nic_bridged_vlan.sh
test/suites/container_devices_nic_ipvlan.sh
test/suites/container_devices_nic_macvlan.sh
test/suites/container_devices_nic_p2p.sh

- Reworks daemon shutdown process to handover cluster roll earlier.
- If handover fails, then server shutting down closes gateway and cluster connection to avoid delayed queries.
- Makes `/internal/shutdown` return a valid response as LXD shuts down and updates `lxd shutdown` to check for it.
- Improves logging.
- Reduces amount of separate shutdown context/channels/locks.

Cluster: Shutdown improvements

---

lxd/endpoints/network.go
lxd/endpoints/network_test.go

Closes #9248
Works off of https://github.com/lxc/lxd/pull/9259 by @dizlv
Seems everything was already in place, just incorrect formatting on the error message. I just changed the assertion to check for any error, since the error that was being checked isn't from us.

[GH-9248] Restrict protocol version

---

lxd/daemon.go

lxd/daemon: Fix crash on lxd start when another lxd already running

---

lxd/instance/drivers/driver_common.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/instance_utils.go
lxd/instance/operationlock/operationlock.go

As part of the series of fixes for https://github.com/lxc/lxd/issues/9327 this PR moves away from using instance ID for operation locks.
This allows them to function properly when the `instance.Instance` has been initialised from a non-DB source.

Instance: Use project and instance name for operation locks

---

lxd/main_shutdown.go

The change to make `/internal/shutdown` blocking has had a knock on effect to `lxd shutdown` when running inside the snap.
Because the process was:
1. Issue shutdown request to `/internal/shutdown` and then wait until LXD ends.
2. Then send request to events API endpoint to confirm LXD has ended.
When run inside the snap, the first request caused the LXD process to end, and then the second request caused the snap's socket activation to start LXD again.
So we've re-organised it so that only the shutdown request is sent.

lxd/main/shutdown: Fix shutdown regression when running in snap

---

lxd/certificates.go
lxd/db/certificates.go
lxd/db/certificates.mapper.go
lxd/db/generate/db/method.go

Closes #9317 
Coincidentally, I actually noticed this while working on the generator! The `certificates_projects` table was always updated independently of the `certificates` table. The fix I've put here should take care of the problem for now, until I finalize my reworking of how the generator handles reference tables.

Generator: Insert into certificates_projects table

---

lxd/api_internal.go
lxd/api_internal_recover.go
lxd/backup/backup_config.go
lxd/daemon.go
lxd/db/instances.go
lxd/instance/drivers/driver_common.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/instance_utils.go
lxd/instances.go
lxd/patches.go
lxd/project/project.go
lxd/storage/drivers/driver_zfs_volumes.go
shared/osarch/architectures.go

As part of the series of fixes for #9327 this PR reworks `instancesOnDisk` to return a slice of `instance.Instance` with the `Type` field correctly populated (to allow differentiation between containers and VMs), as well as loading the config and device config from the instance's backup.yaml if available.
This PR also forcefully closes the cluster DB connection on shutdown if the loading of instances fails, which will cause all subsequent queries to fail quickly. Should help with shutdown speed when shutting down a server that has no access to the global DB.
Because of this point, device cleanup can still fail due to their validation steps requiring DB access.
But this puts in the foundations for proper clean up of instances when no DB access, and then each device type needs updating to …

Instance: Rework instancesOnDisk to load config from backup.yaml if available

---

lxd/api_cluster.go
lxd/cluster/gateway.go
lxd/cluster/heartbeat.go
test/includes/lxd.sh
test/suites/clustering.sh

Also log partial and initial heartbeats as these should only be sent when cluster state changes.
Also adds additional logging and removes sleeps from cluster handover tests to allow us to get a better understanding of how much time role handover actually needs.

Cluster: Error when no leader address found during handover

---

lxd/storage/drivers/driver_zfs_volumes.go

Seems to work better inside the snap than zfs mount.

Storage: Use normal mount rather than zfs mount for ZFS volumes

---

lxd/network/driver_bridge.go
lxd/network/driver_common.go
lxd/network/network_interface.go
lxd/networks.go

Just moving the existing leases logic over to the network package in preparation for an OVN implementation.

lxd/network: Move Leases to network package

---

test/includes/lxc.sh

In recent versions of debianutils, `which` prints a deprecation warning and
there are discussions to remove it completely at some point.

Remove the last 'which' occurence.

---

lxc/file.go

HostPath is meant for accessing user provided paths which may not be
accessible when LXD is run in a confined environment. It shouldn't be
used to access files that are generated within LXD's environment.

lxc/file: Don't use HostPath on temp files

---

lxd/api_cluster.go

Partly addresses #9464
When calling `clusterPutDisable`, the daemon is re-execed in order to
clear the state after clustering is disabled. The response is flushed
via `response.ManualResponse`'s hook, which calls `Flush()` to render the
response before the daemon is replaced. It seems the response is not
rendered quickly enough before the daemon shuts down if a node removes
itself. Waiting for the response context to cancel still causes an `EOF`
error as the daemon still restarts too quickly. Adding a 100ms sleep
should take care of this until we can investigate why `Flush()` isn't
rendering in time.

lxd/api/cluster: Sleep for 100ms to allow http.Flush to render

---

lxd/instance/drivers/driver_lxc.go

This ensures that when restarting we use a freshly generated config rather than the config loaded during stop/shutdown (which was having the raw.lxc config added to it in order to handle shutdown signalling requirements).
This reuse of config was resulting in duplicated raw.lxc config lines being added to the config file on restart, as the raw.lxc lines were adding again during start.
Introduced by https://github.com/lxc/lxd/pull/9270

Container: Release liblxc cache when stopping or shutting down

---

doc/network-acls.md
doc/rest-api.yaml
lxd/db/network_peers.go
lxd/network/acl/acl_ovn.go
lxd/network/acl/driver_common.go
lxd/network/driver_common.go
lxd/network/driver_ovn.go
lxd/network/network_interface.go
lxd/network_peer.go
shared/api/network_peer.go

This PR adds the following:
- When a peer connection is established, router security rules are added to prevent packets with source address of IPs in the peer's target network routes from being allowed in via the router's external uplink port. This prevents spoofed packets coming in from the external network that would appear to come from the peer connection's routes.
- When a peer connection is deleted, these security rules are removed (by way of rebuilding both sides' security rules and excluding the removed peer networks from the allowed list). Combined with the existing egress network IP spoof protection means that we can trust that packets with a source address in the peer's target network's address set truly did come via the peer connection.
- Building on the above trust scenario, …

Network: Add ACL integration for OVN peer connections

---

lxd/operations.go

We were incorrectly using `node.HTTPSAddress()` rather than ` node.ClusterAddress()`.

Operations:  Don't duplicate local operations in operationsGet when running in single member cluster

---

lxd/db/cluster/update.go

Required for https://github.com/lxc/lxd/pull/9485 and https://github.com/canonical/go-dqlite/issues/123

DB: Fix upgrade from LXD 2.0/3.0 when using go-dqlite v1.10.1 NULLable fields

---

lxd/device/gpu_mdev.go

lxd/device: Clean up mdev vGPU on failure

---

lxd/network/driver_ovn.go
lxd/network/openvswitch/ovn.go

Requires host running OVN 21.09 or later (as requires https://github.com/ovn-org/ovn/commit/1c9e46ab5c05043a8cd6c47b5fec2e1ac4c962db).
Related to issue raised in https://github.com/ovn-org/ovn/issues/78
Sets the `options:gateway_mtu` option to the bridge MTU value on both external and internal logical router ports.
With thanks to @fnordahl

Network: Add support for OVN PTMU discovery for external ingress traffic

---

lxd/device/config/device_runconfig.go
lxd/device/usb.go
lxd/instance/drivers/driver_qemu.go

When multiple matching devices are passed through a VM using one
device/usb rule, the logic would pass the random last one that
enumerated.
Fix this by adding each one in sequence. Only tested with Qemu.
To test this, attach multiple devices with the same vedor:product pair,
for example a number of FTDI devices, and bridge them to the virtual
machine with profile or instance configuration.
I'm using an LXD virtual machine to work with development boards
and serial/usb adapters. All of our serial adapters use the vendor:product
pair of 0403:6001 (a common FTDI device). The other devices are 96 Boards
Nitrogen devices with 0d28:0204 pair. There are multiple of those attached
to the host and they are all meant to be forwarded to the virtual machine.
The example profile I'm using with this: …

VM: fix usb pass-through with more than one device

---

lxc/info.go
lxc/list.go
lxc/storage.go
lxc/storage_volume.go
lxd/api_internal.go
lxd/patches_utils.go
lxd/project/permissions.go

Addresses inconsistent units documented in issue #9433
While the original issue suggested changing disk, memory, and transfer units to IEC units, we opted to follow the [Ubuntu Units Policy](https://wiki.ubuntu.com/UnitsPolicy):
Base-10 (SI):
- Bandwidth (network speed/file transfer/etc.)
- Disk sizes
- File sizes
Base-2 (IEC):
- Memory Sizes
Happy to make changes if needed!

lxc/list: Changed units to be IEC consistent

---

lxd/migrate.go
lxd/migrate_instance.go
lxd/migrate_storage_volumes.go

Otherwise it will cause govet to fail on the pragma.DoNotCopy in protoimpl.MessageState

Migrate: Only use pointers to migration.MigrationControl to avoid shallow copies

---

doc/projects.md
lxd/api_project.go
lxd/db/networks.go
lxd/db/storage_pools.go
lxd/db/storage_volumes.go
lxd/device/device_utils_disk.go
lxd/device/disk.go
lxd/device/proxy.go
lxd/network/driver_ovn.go
lxd/project/permissions.go
shared/util.go

Some cleanup and improvements before https://github.com/lxc/lxd/pull/9496
- Switches to mounting `disk` devices via a file descriptor rather than directory passing the source path to the mount syscall (this is so we use a similar code path for both unrestricted and restricted devices (in the future)) to get more thorough testing of that approach in different scenarios.
- Moves block device filesystem detection out of `DiskMount`, requires this to be done externally and passed in via `fsName` argument. Gives more control the caller about when filesystem detection is done. This is required as one cannot to filesystem detection on a file descriptor path.
- Reduces stat syscalls when detecting if a disk source is a directory, file or block device.
- Requires absolute source path for local …

Storage: Disk mounting cleanup and improvements

---

lxd/instance/drivers/driver_lxc.go

We were leaking liblxc file handles to the container's log file when querying the state of a container, and relying on the Go garbage collector to release it. Lets not do that, as it can end up leaving FDs around for a while.

Container: Fix liblxc handle leak in renderState

---

lxd/device/config/device_runconfig.go
lxd/device/disk.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go

This is a precursor to be able to use openat2 for restricted disk source paths in https://github.com/lxc/lxd/pull/9496

Device: Switch VM disk devices to use opened file descriptors for passing disk sources to QEMU

---

lxd/device/nic_bridged.go
lxd/device/nic_routed.go
lxd/ip/neigh.go
lxd/ip/neigh_proxy.go
lxd/network/network_utils.go

Also makes `ip.Neigh.Show()` function return a proper struct rather than a raw multi-line output string.
This PR is part of a precursor cleanup required for adding `routed` NIC VM support (continuing on work started in PR https://github.com/lxc/lxd/pull/9367.

Network: Separate IP neighbour and neighbour proxy management functions

---

lxd/device/nic_routed.go
test/suites/container_devices_nic_bridged.sh
test/suites/container_devices_nic_p2p.sh
test/suites/container_devices_nic_physical.sh
test/suites/container_devices_nic_routed.sh

Instead it configures a veth pair itself and then uses liblxc's phys NIC type to pass one end of the veth pair into the container.
This is part of adding routed NIC support for VMs by moving the common functionality into LXD.
Continues work started in https://github.com/lxc/lxd/pull/9367

NIC: Reworks routed NIC to not depend on liblxc's router NIC type

---

lxd/include/file_utils.h
lxd/include/lxd.h
lxd/include/macro.h
lxd/include/process_utils.h
lxd/main.go
lxd/main_forkexec.go
lxd/main_forkusernsexec.go
lxd/main_nsexec.go

Use from LXD like:
```
args := []string{
d.os.ExecPath,
"forkusernsexec",
"touch",
"/tmp/MUHU",
}
cmd := exec.Cmd{}
cmd.Path = d.os.ExecPath
cmd.Args = args
rUidMapPipe, wUidMapPipe, err := os.Pipe()
return err
}
defer rUidMapPipe.Close()
// Make sure the string is \x00 terminated so it's parseable as a C string
_, err = wUidMapPipe.WriteString("0 100000 1\n\x00")
return err
}
rGidMapPipe, wGidMapPipe, err := os.Pipe()
return err
}
defer rGidMapPipe.Close()
// Make sure the string is \x00 terminated so it's parseable as a C string
_, err = wGidMapPipe.WriteString("0 100000 1\n\x00")
return err
}
cmd.ExtraFiles = []*os.File{rUidMapPipe, rGidMapPipe}
err = cmd.Run()
return err
}
```
Signed-off-by: Christian …

lxd: add forkusernsexec()

---

lxd/instance.go
lxd/instance_snapshot.go
lxd/project/permissions.go
lxd/storage_volumes_snapshot.go

I kept seeing this debug error in my local logs:
```
DBUG[11-17|10:02:51] Database error: &errors.errorString{s:"Project test doesn't allow for snapshot creation"} 
```
On further inspection this also revealed some very inefficient query techniques, so have optimised them in the process.

Project: Separate checking if a project can support snapshots from the project DB lookup

---

lxd/device/device_utils_disk.go
lxd/device/disk.go
lxd/instance/drivers/driver_qemu.go
lxd/main_daemon.go
lxd/main_forkusernsexec.go
shared/subprocess/proc.go

Continues #9496
This is a prerequisite for running these disk share proxy processes in a user namespace (using #9536) in order to properly secure restricted disk device paths.
The 9p `virtfs-proxy-helper` process accepts an already opened unix socket FD (not a listener FD), whereas the virtio-fs `virtiofsd` accepts a listener FD.
So for the `virtfs-proxy-helper` share we create an abstract unix listener, connect to it, and accept from it. This creates file handlers for either end of the unix socket, and then close the listener. We then pass one end of the connection to `virtfs-proxy-helper` and the other to QEMU via the `proxyFD` config setting.
And for the `virtiofsd` share we create a real unix listener with a path, get the FD of that listener and pass it to the `virtiofsd` process, and …

VM: Use socket file descriptors for virtfs-proxy-helper and virtiofsd

---

lxd/device/device_utils_disk.go
lxd/device/disk.go

Don't wait for Go's garbage collector to do it.
We were leaking file handles for a little bit.

VM: Close unnecessary file handles for VM disk proxy processes

---

client/simplestreams_images.go
shared/util.go

Distrobuilder supports context and uses `DownloadFileHash`. In order to cancel downloads, `distrobuilder` needs to pass its own context to this function.

Allow passing context to DownloadFileHash

---

doc/projects.md
lxd/api_project.go
lxd/device/device_utils_disk.go
lxd/device/device_utils_disk_test.go
lxd/device/disk.go
lxd/instance/drivers/driver_qemu.go
lxd/project/permission_internal_test.go
lxd/project/permissions.go
lxd/project/permissions_test.go
shared/idmap/idmapset_linux.go
shared/idmap/idmapset_linux_test.go
shared/instance.go
shared/validate/validate.go
test/suites/container_devices_disk_restricted.sh

Uses `forkusernsexec` from @brauner in https://github.com/lxc/lxd/pull/9536 to run the VM `disk` proxy processes in their own user namespaces. This is to effectively disable the `shift=true` default behaviour for VM `disk` devices when using a restricted source path, in order to prevent the creation of root-owned setuid files which could then be used to gain root privileges on the host outside of the VM.
Also adds `restricted.idmap.uid` and `restricted.idmap.gid` project settings which will include a range of host uid/gid which the project can map disk devices to using `raw.idmap` on the instance/profile. This allows instances with restricted `disk` devices to "punch" holes through the instance's unprivileged idmap range, for certain allowed UID/GID ranges.

VM: Add raw.idmap support for running disk device proxy processes in user namespace

---

lxd/db/networks.go
lxd/network/driver_ovn.go

Fixes an issue seen in https://www.youtube.com/watch?v=1M__Rm9iZb8 where LXD did not auto select the only viable uplink network for use with a new OVN network because it was incorrectly considering another OVN network in the default project as a potential uplink, even though only `bridge` and `physical` networks types can be used as uplinks.

Network: Ensures OVN networks only consider only compatible networks for use as uplink

---

lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go

Previously any instance stop or shutdown errors would be masked if the instance had been stopped successfully (but perhaps some of the device or storage clean up had still failed). 
This PR changes it so that any error in the stop or shutdown sequences are returned to the caller, but even if there are errors if the instance is successfully stopped then the associated lifecycle event is still generated.

Instance: Improve and unify stop and shutdown error handling

---

lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/storage/drivers/driver_zfs_volumes.go

Sometimes when ZFS has a lot of data to flush (something @stgraber has experienced when using LXD VMs with MAAS), the unmount sequence can take a long time, and currently LXD is only waiting 5s for it to complete. Not waiting for it complete means that a subsequent restart of the instance can be interfered with by the ongoing unmount process.
We can't increase the ZFS unmount wait time beyond the operation lock timeout of 30s, as we don't want to be keeping the operation lock alive without knowing that LXD is still trying to unmount the ZFS volume (and right now the storage drivers don't have access to the instance lock instance to allow them to reset it, and that is outside of the scope of this change). Increasing the ZFs unmount wait time beyond the operation lock timeout would mean …

Instance: Reset operation lock timeout when unmounting instance and increase ZFS unmount wait

---

lxd/main_forkusernsexec.go

And have the caller indicate if they need more than that.
This also fixes a potential integer overlflow.

forkusernsexec: use unix.Stderr as standard --keep-fd-up-to value

---

lxd/network/driver_ovn.go

Fixes an issue @stgraber experience where restarting an instance with an OVN NIC that had `ipv{n}.routes` or `ipv{n}.routes.external` set would cause routes to be added to the network's peers with the incorrect nexthop IP and target port names.
Routes on a peer network after restarting instance with `ipv4.routes.external=10.0.0.1/32` before:
```
sudo ovn-nbctl lr-route-list lxd-net27-lr
IPv4 Routes
10.0.0.1               10.124.13.2 dst-ip lxd-net26-lr-lrp-int
10.124.13.0/24               10.124.13.1 dst-ip lxd-net27-lr-lrp-peer-net26
0.0.0.0/0               10.250.73.1 dst-ip lxd-net27-lr-lrp-ext
```
It should be going to `10.124.13.1 dst-ip lxd-net27-lr-lrp-peer-net26` same as `10.124.13.0/24 `
After fix:
```
sudo ovn-nbctl lr-route-list lxd-net27-lr
IPv4 Routes
10.0.0.1 …
```

Network: OVN instance peer route bug fix

---

lxd/device/disk.go

Something I noticed while working on VM tests for restricted disk paths.

lxd/device/disk: Support snap packages when opening restricted disk paths

---

lxd/db/generate/db/mapping.go

Running `make update-schema` has been broken since the the usage of `sql.NullTime` was introduced into the db package to support nullable datetimes.

Generator: Accept sql.NullTime as a valid type in the generator

---

doc/instances.md
lxd/device/nic_routed.go
test/suites/container_devices_nic_routed.sh

Backports the work done in (but without gvrp support as needed wider function changes outside of routed NIC):
- https://github.com/lxc/lxd/pull/9528
- https://github.com/lxc/lxd/pull/9529

NIC: Routed NIC rework and VM support backport (stable-4.0)

---

doc/doc-cheat-sheet.md

For now, the cheat sheet is not included in the navigation,
but it can be accessed by URL.

doc: add a cheat sheet for documentation

---

doc/index.md

With the existing recommended range the `container_devices_disk` integration test fails to launch an isolated container because it runs out of uids. The new range allows this test to pass.

Increases recommended subuid and subgid ranges in machine setup.

---

lxc/exec.go

This way signals can be relayed to non-interactive commands, and if the lxc command disconnects this can be detected
and used to clean up the running command.
Fixes #9578

lxc/exec: Always connect control websocket

---

lxd/instance/drivers/driver_lxc.go
lxd/instance_exec.go
shared/network.go
test/main.sh
test/suites/exec.sh

Thus preventing leaving the command running in the background (potentially indefinitely until the instance or LXD was stopped).
We cannot require that the client provide a control socket for non-interactive exec sessions as otherwise this would break older clients from using exec on newer servers. Instead we have to detect the client disconnecting by the stdout channel being closed.
Also:
- Makes the control connection required for interactive exec sessions.
- Removes duplication of interactive/non-interactive control connection handlers.
- Uses more structured logging.
- Fixes several file handle leaks.
Fixes #9578

Instance: Detect disconnect of non-interactive exec stdout websocket and kill command

---

lxd-agent/exec.go
lxd-agent/main_agent.go
lxd/instance/drivers/driver_qemu.go

Even if the `lxc` client doesn't connect to the control socket, we expect LXD to open a control socket, so that LXD can instruct the lxd-agent to kill the process if needed.

Instance: Rework VM exec to always expect control connection for websocket sessions

---

.sphinx/_static/custom.css
.sphinx/conf.py

Add a custom style sheet that can be used to tweak the CSS
of the Sphinx theme.
The current version of the style sheet fixes some of the low-
priority issues.

doc: css: temporary fixes for theme issues

---

lxd-agent/exec.go
lxd/instance/drivers/driver_lxc_cmd.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/drivers/driver_qemu_cmd.go
lxd/instance_exec.go
shared/util_linux.go

Fixes #9542 by removing the LXD internal PTY/TTY emulation for VM exec sessions, and instead just passing the data through to the lxd-agent.

Instance: Fix VM exec pts leak

---

lxd-agent/exec.go
lxd/instance/drivers/driver_lxc_cmd.go
lxd/instance/drivers/driver_qemu_cmd.go
lxd/instance_exec.go
shared/util_linux.go

Builds on change from https://github.com/lxc/lxd/pull/9598 by properly using `syscall.WaitStatus.Signaled()` to detect when a command is killed by ctrl+c during an interactive session.
This will now return the exit status 130 as documented by https://tldp.org/LDP/abs/html/exitcodes.html

Instance: Adds ExitStatus() to properly extract exit status when a command is signaled from interactive session

---

.sphinx/conf.py

For the Sphinx build, add a redirect from index/index to the
index.html in the root folder, to ensure that both
https://linuxcontainers.org/lxd/docs/master/index and
https://linuxcontainers.org/lxd/docs/master/index/ work.

doc: add redirect to index.html

---

doc/storage.md

As per the conversation [here](https://discuss.linuxcontainers.org/t/ceph-storage-with-existing-ceph-pool/12726/22),
I've updated the `docs/storage.md` page with details on how to use existing Ceph erasure coded pools with LXD.
Signed-off-by: Alexandar Yovchev <alexyov@protonmail.com>

doc: Update Ceph docs with details for erasure coded pools

---

lxd/daemon.go
lxd/main_checkfeature.go

Add a helper that we're only using during daemon startup to give an
indication whether the underlying kernel has the necessary
infrastructure to support idmapped mounts. This check does not give any
indication whether the relevant filesystem used for a container does
have this support.

lxd: log basic idmapped mount support

---

lxd-agent/exec.go
lxd/instance/drivers/driver_qemu.go

Non-websocket exec requests for VMs were working, but only by chance. Lets tighten up what is required and explain why.

Instance: Make VM WaitForWS for lxd-agent exec explicit

---

installing.md

Small fix to address #9623 
Simply created a link from installing.md to doc/installing.md (as is the current practice for files moved into /doc).

Added link for installing.md

---

lxd/storage/drivers/driver_btrfs_volumes.go

This reduces the impact of random writes to large block files on the BTRFS quota.
Although this does not entirely prevent CoW from taking up quota usage, as when a snapshot is taken,
the first write to a block after that will cause a CoW and the new and old extent will be referenced
as used in the quota
Related to #9124

Storage: Enable nodatacow on BTRFS subvolume for block volumes

---

lxd/storage/drivers/generic_vfs.go

Move unpack logging to where the unpack is actually occurring.

Storage: Improve logging during backup unpack

---

doc/storage.md

And covers the possible workarounds of `size.state` and `btrfs.mount_options=compress-force`.
Related to #9124

Storage: Add warning to docs about using VMs on BTRFS storage pools

---

doc/storage.md

doc/storage: fix 2 typos

---

lxd/storage/backend_lxd.go

Use `size.state` (if set) or otherwise use default 100MiB setting if `size` is set, to apply quota to VM's filesystem volume.
**Warning:** 
Whilst this PR does fix a bug, it will introduce further issues with the BTRFS storage driver.
Due to the way that BTRFS accounts for subvolume quota by conflating both CoW snapshot writes and actual new usage in a subvolume, this will cause issues with VM snapshots.
This is because when applying a VM disk quota, the LXD BTRFS driver will set the subvolume quota to `<size.state>+<raw disk image size>`, where `size.state` defaults to 100MiB.
When restoring a non-optimised VM backup, BTRFS will account (correctly) that 100% of the raw disk file has been written to.
But this will then mean that when creating a VM snapshot, that only up to 100MiB (or …

Storage: Restore VM filesystem size.state quota on backup restore

---

.gitignore
.sphinx/_extra/rest-api.yaml
.sphinx/_static/swagger-override.css
.sphinx/conf.py
Makefile
doc/api.md
doc/restapi_landing.md

Add the Swagger API to the Sphinx docs.
Not quite happy with the way of downloading the files, but the full repo is huge and it would be overkill to clone it.

Add swagger to doc

---

lxd/firewall/drivers/drivers_nftables.go
lxd/firewall/drivers/drivers_nftables_templates.go
lxd/firewall/drivers/drivers_util.go
lxd/firewall/drivers/drivers_util_test.go
lxd/firewall/drivers/drivers_xtables.go
test/suites/container_devices_proxy.sh

Currently, proxy device drivers add NAT rules for every listen port (e.g. given a listen range of `1000-1999` the driver will add 1000 NAT rules). This change optimises the number of rules added by the drivers by examining whether the given ports are part of a range.
Fixes #9073.

Optimise proxy device driver nat rules

---

lxc/copy.go

Previously, profiles provided using -p flag were appended to the
instance profiles. This brings the behaviour of copy in line with that
of launch.
Fixes #9554

lxc/copy: Replaces profiles when -p is set.

---

lxd/cluster/membership.go
lxd/cluster/membership_test.go
lxd/db/networks.go

To resolve #9466 
My solution modifies the GetNonPendingNetworkIDs function to pull the project name from the database and add it to map that maps project names to maps of network names to network IDs.
The Join function in cluster/membership.go may not be properly project aware while GetNonPendingNetworkIDs is. Is that something I should look into?

GetNonPendingNetworkIDs Project Aware

---

lxd/storage/drivers/driver_btrfs.go
lxd/storage/drivers/driver_lvm_utils.go
lxd/storage/drivers/utils_cgo.go

Resolves #9407
My current implementation passes the LO_FLAGS_DIRECT_IO flag into the PrepareLoopDev function when it's called from the lvm and btrfs drivers. I also included C functions to manually set direct IO on a given loop device if needed instead.
Also, should I add a storage pool configuration option to allow users to disable direct IO?

lxd/storage: Enable LO_FLAGS_DIRECT_IO by default for loop devices

---

lxd/cluster/gateway.go

Cluster: Include endpoint address in dqlite connect errors

---

lxd/api.go
lxd/daemon.go
lxd/devlxd.go
lxd/request/const.go
lxd/request/request.go
lxd/ucred/ucred.go

The connection was previously obtained via reflection. With golang >= 1.13 we can use `ConnContext` on the `http.Server` instead.
Fixes #9650.

Record net.Conn in request context

---

lxd/cluster/heartbeat.go
lxd/daemon.go
lxd/db/node.go
lxd/network/driver_bridge.go
test/suites/clustering.sh

- Cleans up the heartbeat handler to be more explicit and less prone to error when being changed.
- Changes member offline detection to fix an off-by-one error (this should make the tests more reliable).
- Keeps all heartbeat members state in global variable to detect future state changes (rather than just keeping online ones) - this way each consumer of the list can decide if they want to consider offline members or not.

Cluster: Heartbeat ordering

---

client/interfaces.go
client/lxd.go
client/lxd_events.go
lxc/monitor.go
lxd-agent/events.go
lxd/cluster/events.go
lxd/devlxd.go
lxd/events.go
lxd/events/events.go

Changes the events API to use `all-projects=true` instead of `project=*` query parameters. Adds validation on project parameter if one is passed.
Fixes #9647

Use all-projects parameter in events api

---

doc/instances.md
lxd/device/nic_bridged.go
test/suites/container_devices_nic_bridged_filtering.sh

lxd/device/nic/bridged: Allow ipv{n} filtering when ip is set to none 

---

lxd/api_cluster.go
lxd/cluster/events.go
lxd/daemon.go

Moves event listener refresh to be event driven (triggered on cluster task startup, heartbeat and member rebalance notification) rather than have every member polling the global database for a list of members continuously every 1 second.
For the heartbeat triggered event, it uses the member list sent with the heartbeat to further avoid additional leader DB traffic from other members.
This reduces network traffic significantly, here is an example in an idle 4-member cluster, with vnstat run on the leader member.
Before:
```
vnstat -tr -tr 60 -i enp5s0
12774 packets sampled in 60 seconds
Traffic average for enp5s0
rx       101.49 kbit/s           120 packets/s
tx       150.31 kbit/s            92 packets/s
```
After:
```
vnstat -tr 60 -i enp5s0
4058 packets sampled in 60 seconds
Traffic …
```

Cluster: Make event listener refresh event driven

---

test/suites/exec.sh

test: Add 1s between running non-interactive exec and checking for exit status in operation

---

lxd/cluster/connect.go
lxd/cluster/events.go
lxd/cluster/heartbeat.go
lxd/events/events.go

No need to keep polling unnecessarily.

Events: Make Connect use an event driven wait approach for waiting until the event stream is connected

---

lxd/cluster/membership.go

Othewise when the other members get the notification heartbeat, the member state in the DB will still be set to pending.
This is what generates the "Cluster member info not found" warning messages, and its not good keeping that transaction open whilst we make a network request to each and every member of the cluster.

Cluster: Move notifyNodesUpdate call out of transaction in Join

---

lxc/list.go

This fixes --all-projects with non-clustered setups.
It also makes it work properly with --fast.

lxc/list: Better handle --all-projects

---

doc/storage.md

The type of the `ceph.rbd.clone_copy` config key was listed as `string` in the storage docs, but in the codebase it's validated and used as a `bool` value.

Fix incorrect type of ceph.rbd.clone_copy in docs

---

lxd/device/nic_routed.go
test/suites/container_devices_nic_routed.sh

Fixes regression caused by https://github.com/lxc/lxd/pull/9528
Fixes #9678

NIC: Enable IP forwarding on routed NIC veth host_name interface 

---

lxd/device/nic_bridged.go
lxd/network/driver_bridge.go

Instead check network config to indicate if dnsmasq will be used and use that as an indicator instead.
This way if dnsmasq has failed to start for some reason we don't skip writing the static allocation file.

NIC: Don't depend on existance of dnsmasq.pid file to write static DHCP allocation file

---

lxd/db/certificates.mapper.go
lxd/db/cluster.go
lxd/db/cluster/constants.go
lxd/db/db.go
lxd/db/generate/db/mapping.go
lxd/db/generate/db/method.go
lxd/db/generate/db/stmt.go
lxd/db/images.go
lxd/db/images.mapper.go
lxd/db/instances.go
lxd/db/instances.mapper.go
lxd/db/network_acls.go
lxd/db/networks.go
lxd/db/profiles.go
lxd/db/profiles.mapper.go
lxd/db/projects.go
lxd/db/projects.mapper.go
lxd/db/query/slices.go
lxd/db/query/slices_test.go
lxd/db/storage_volumes.go
shared/api/url.go

Cleaning up URLs from #9364, I've made some changes to consolidate URL generation to always use the methods in `shared/api/url.go`.
Main changes:
* Remove generation of prepared statements for getting names and projects of entities, preferring instead to just use the pre-existing prepared statements for getting whole entities, but just returning name and project via go.
* Omit `target=none` from URLs with `target` form values.
* Move `urlsToResourceNames` to `shared/api/url.go` to have all URL conversion methods in one place.
* Remove db package `EntityFormatURIs` and `SelectURIs` in favour of using `api.NewURL` to create URLs.

Generator: Use api.NewURL for URL generation

---

lxd/api_cluster.go

AFAIK it doesn't make sense to be taking a local lock if we are redirecting the client to the leader.

Cluster: Only take clusterMembershipMutex on leader

---

.sphinx/_static/custom.css
.sphinx/_static/header-nav.js
.sphinx/_templates/footer.html
.sphinx/_templates/header.html
.sphinx/_templates/page.html
.sphinx/conf.py
.sphinx/requirements.txt
Makefile

Switch to a customized version of the Furo theme.
To do:

doc: use customized Furo theme

---

doc/api-extensions.md
doc/rest-api.yaml
lxd/instance_get.go
shared/version/api.go

Closes  #9555
This change adds additional information about state, backups and snapshots when
query `GET /1.0/instances/c1?recursion=1` is used.
@stgraber
I used recursion=1 to get full struct (with additional information) because no recursion already
returns basic struct. So this is a little bit different then instances_get where we have:
- urls for no recursion
- basic structs for recursion=1
- full structs for recursion=2
is this ok?

API get Instance with more in-depth information

---

lxd/db/cluster/schema.go
lxd/db/cluster/update.go

All views except for 'storage_volumes_all' were unused. These are
removed in advance of #9414 so that they are not needlessly recreated.
Signed-off-by: Mark Laing <mark.laing@canonical.com>

lxd/db/cluster: Removes unused database views.

---

lxd/api.go
lxd/api_cluster.go
lxd/cluster/gateway.go
lxd/cluster/heartbeat.go
lxd/cluster/membership.go
lxd/daemon.go
lxd/db/node.go

This lays the groundwork to allow triggering a full-state notification heartbeat to all members for distributing event hub role changes.
So now there are the following "types" of heartbeat:
1. Partial state - this is only ever sent as part of the 1st phase of the initial heartbeat generated when a leader is elected.
2. Full state - this is sent during the 2nd phase of the initial leader heartbeat, during scheduled and immediate leader heartbeats, and it is sent from non-leader members to all other members for member state change notifications.
When a full-state heartbeat is sent from the leader or received any member, it will run the heartbeat refresh task. 
However when the heartbeat refresh task is run on the leader after sending a full-state heartbeat, the heartbeat task may perform …

Cluster: Heartbeat system rework to allow for full-state member change notifications

---

lxd/daemon.go
lxd/endpoints/endpoints.go
lxd/endpoints/socket.go
lxd/endpoints/starttls.go
lxd/ucred/ucred.go

This allows using STARTTLS to run a TLS authenticated session of the local LXD unix socket.
Other than potentially helping for local testing of authentication mechanism, this will be used by an upcoming `lxd-user` daemon which will allow unprivileged users interacting with LXD by dynamically creating and managing LXD projects.
This daemon required the ability to restrict a particular connection to a specific project. Rather than re-inventing the wheel, we'll have it use per-user trust certificates restricted to their respective project and have that daemon establish individual TLS connections to LXD for authentication.
This PR makes it possible to do all that locally without having to expose LXD to the network and so retaining our current socket-activation support at the same time.

Add TLS over Unix Socket support

---

lxd/instances_get.go

This was noticed during review of #9698. When querying instances for all project, the project query parameter should be set on requests to other nodes if the project is not the default.

lxd: Uses api.NewURL and sets project when querying other nodes.

---

doc/api-extensions.md
doc/instances.md
lxd/instance/drivers/driver_qemu.go
lxd/instance/drivers/driver_qemu_metrics.go
lxd/instance/drivers/qmp/commands.go
shared/instance.go
shared/version/api.go

This adds a `security.agent.metrics` config key which when set to `false` will have LXD use host-side state information for the VM (CPU, disk, memory, network, ...) rather than relying on the agent.
It applies to both `/1.0/instances/NAME/state` and `/1.0/metrics`.
This is useful for environments where the guest cannot be trusted and where having potentially inflated values from QEMU is preferable to the more detailed values the agent would otherwise provide.

Agent-less VM metrics

---

README.md
doc/index.md

We renamed the contributing guide to uppercase - need to fix this
in the Readme as well.

doc: fix link in README

---

lxd/cluster/gateway.go
lxd/migrate.go
lxd/migrate_instance.go
lxd/migrate_storage_volumes.go
lxd/util/net.go

This way they will gracefully close rather than hanging if a network problem occurs.

Migration: Enable TCP_USER_TIMEOUT and TCP keep alives on migration connections

---

client/events.go
client/lxd.go
client/lxd_events.go
client/operations.go
lxd-agent/events.go
lxd/cluster/connect.go
lxd/cluster/events.go
lxd/events.go
lxd/events/events.go

Also lays the ground work for allowing a server-initiated client connection to another server to be considered active if there is an events connection to either the specific server being connected to, or, in the future, one or more event hub servers.

Cluster: Event listener socket cleanup and logging improvements

---

lxd/cluster/heartbeat.go
lxd/cluster/membership.go

Rather than sleeping for the spread duration.

Cluster: If heartbeat context is cancelled during spread sleep then exit quicker

---

lxc/main_aliases.go
lxc/main_test.go

Previously, users could use `@ARGS@` to pass arguments from the command
line into their alias. In addition to this, users can now reference
`@ARG1@`, `@ARG2@` etc. from their argument list. The value of `@ARG1@` is
removed from the list of `@ARGS@`.
Signed-off-by: Mark Laing <mark.laing@canonical.com>

lxc/alias: Allows users to reference specific arguments.

---

lxd/cluster/recover.go

lxd/cluster/recover: Return separate error if no raft role found

---

lxd/backup.go
lxd/instance_backup.go

`lxc export` uses two progress indicators. One for backing up instance and one for exporting the backup. The first one was broken. I added support for progress indicator directly in `backupCreate` method but I think there is other approach to solve this issue. We can pass `Operation` to: https://github.com/lxc/lxd/blob/e2fe2f8b74aa32d1fbcb50dfcd5f4143ade76008/lxd/backup.go#L168 as the last parameter. But then we need to implement support for progress indicator for every driver. Most of them uses: https://github.com/lxc/lxd/blob/e2fe2f8b74aa32d1fbcb50dfcd5f4143ade76008/lxd/storage/drivers/generic_vfs.go#L448 but there are two exceptions. I think this solution will be more complex so this is why I decided for first one.
Fixes #9711

Fix progress indicator for 'lxc export'

---

doc/api-extensions.md
doc/instances.md
lxd/device/device_utils_gpu.go
lxd/device/gpu.go
lxd/device/gpu_mig.go
shared/version/api.go

Introduce a new parameter `mig.uuid` which reflects the new MIG UUID format used by Nvidia `470+` drivers (eg. `MIG-74c6a31a-fde5-5c61-973b-70e12346c202`), the `MIG-` prefix can be omitted.
This extension supersedes old `mig.gi` and `mig.ci` parameters which are kept for compatibility with old drivers and
cannot be set together.
Resolves #9518.
Signed-off-by: Vincent KHERBACHE <v.kherbache@titandc.fr>

Add support for UUID selection of NVIDIA MIG devices

---

lxd/instance/drivers/driver_qemu.go
lxd/instance/drivers/driver_qemu_templates.go

Specify the number of USB2 and USB3 ports. The total number of ports is
4 + the number of configured USB devices. This fixes issues with some
USB devices which otherwise cannot be passed to the VM.

lxd/instance/drivers: Specify number of USB ports

---

.github/labeler.yml
.github/workflows/labeler.yml

Not sure if we have a guideline to not add labels to PRs, but if we don't, I think this would be very helpful to spot doc PRs.
Add a labeler that automatically labels pull requests that
contain changes to files in doc/ or .sphinx/.

automatically add labels to PRs that contain doc changes

---

lxd-agent/exec.go
lxd/instance_exec.go
shared/network.go

We expect the control connection to remain up and operational for the duration of the executed command, otherwise LXD will kill the running command.

Exec: Treat websocket control close message the same as a disconnect

---

.sphinx/_templates/header.html

Improve the placement of the header a bit by adding a left margin
for wide displays.

doc: improve placement of header

---

lxd/daemon_images.go
lxd/images.go
lxd/instances_post.go

public value was hardcoded in two places in `ImageDownload` method:
https://github.com/lxc/lxd/blob/7973ab78af5fba6fa6610174ffb3c0bc7328f76e/lxd/daemon_images.go#L181
https://github.com/lxc/lxd/blob/7973ab78af5fba6fa6610174ffb3c0bc7328f76e/lxd/daemon_images.go#L460
I added new field `Public` to ImageDownloadArgs, so now information can be passed from outside method.
I hardcoded public value in one place:
https://github.com/lxc/lxd/blob/7973ab78af5fba6fa6610174ffb3c0bc7328f76e/lxd/instances_post.go#L102-L114
but I don't see case where image should be public during instance creation.
I also wonder can we use `Secret` field from `ImageDownloadsArgs` to distinguish is image public or not. @stgraber, What do you think?
Fixes  #9730

Fix overriding public property by auto-update

---

client/connection.go
client/events.go
client/lxd.go
client/lxd_events.go
client/lxd_server.go

This fixes an issue where if multiple event listeners were started, they would reuse the same event websocket connection (using the first requested project configuration), and potentially result in either missed events or inappropriate events being received by the event listener. By keying the event listeners and websocket connections by project filter configuration, we can ensure we only re-use an appropriate listener connection.
Fixes #9718

Client: Maintain per-project event listeners and connections

---

doc/api-extensions.md
doc/rest-api.yaml
lxd-agent/events.go
lxd/daemon.go
lxd/devlxd.go
lxd/events/common.go
lxd/events/devlxdEvents.go
lxd/events/events.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/lifecycle/instance.go
lxd/state/state.go
shared/api/event.go
shared/version/api.go

Fixes #9718
- Adds `Project` field to `Event` struct to allow project info to be relayed between cluster members.
- Adds new `events.DevLXDServer` and `events.DevLXDListener` types and splits external event listeners from devlxd listeners (whilst sharing common logic).
- Updates VM lxd-agent devlxd listener to listen for events from all projects (and thus rely on LXD to only post it the correct events), rather than only accepting non-project events as it did previously.
- Tightens up the devlxd `devlxdEventSend` `eventMessage` type.
- Removes "lxd-agent" `Location` field value from VM devlxd events (to align with container devlxd events).
Example devlxd events:
Container:
```
root@c1:~# ./devlxd-client monitor
metadata:
key: user.foo
old_value: bar
value: foobar
timestamp: null
type: …
```

Event: Add Project field to Event and rename group concept to projectName

---

lxd/instance/drivers/driver_qemu_templates.go

This fixes issues with virtiofs when run on top of hugepages with NUMA pinning.

lxd/instance/qemu: Always set memory sharing on memory-backend-file

---

lxc/exec.go
lxc/exec_unix.go

Fixes a regression caused by 138387fc99a26b228ff117a1ed4bc9a7bcbb09e4

lxc/exec: Don't send SIGWINCH when non-interactive

---

doc/api-extensions.md
doc/instances.md
lxd/api_cluster.go
lxd/instance/drivers/driver_common.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/instance_interface.go
shared/instance.go
shared/version/api.go

Resolves #9489.
I had some questions that I left as a comment on the issue, but I think I've mostly figured them out. Here's a couple of the assumptions I made in this implementation:
- `canMigrate(instance)` in lxd/instance/drivers/driver_common.go will only return true for the new `live-migrate` option if all of the instance's devices can migrate (this is the same behavior as `auto`)
- If live-migration (i.e. stateful stop) of an instance fails during evacuation when `live-migrate` is the evacuation mode then we fail with the error "Failed to stop instance [name]," but if `auto` is set then we will attempt the normal non-stateful stop procedure
Should the clustering.sh test suite be updated to test the new `live-migrate` option?

Automatically attempt live migration during evacuation

---

lxd/network/driver_bridge.go

Previously, the `tunnel.NAME.interface` config value will not have
been validated (as there is no default case in the containing switch
statement to catch invalid values).

lxd/network: Fixes misspelling of interface.

---

lxd/main_forkstart.go
shared/util_linux_cgo.go

LXC will check inherited fds again and close them but make sure we don't
even leak any and abort if we failed to close them.
Signed-off-by: Christian Brauner <brauner@kernel.org>

lxd: ensure file descriptors are closed before starting container

---

Makefile

Only link the Swagger files that we actually need to reduce
the size of the documentation output.

doc: only link the Swagger files that we actually need

---

lxc/image.go
lxd/patches.go
lxd/storage/drivers/generic_vfs.go
shared/archive_linux.go

https://www.gnu.org/software/tar/manual/html_node/Option-Summary.html:
--restrict:
"[...] disables shell invocation from multi-volume menu."
--force-local:
"[...] interpret the file name [...] as a local file,
even if it looks like a remote tape drive name."
--one-file-system:
"Prevents tar from recursing into directories that are
on different file systems from the current directory."
The last one is only meaningful when creating archives.

Take extra precautions when calling tar

---

test/suites/container_devices_proxy.sh

When forcing lxd to use the `xtables` firewall driver I found that the `container_devices_proxy` test was failing consistently. 
The test expects to find more `iptables` rules than it does when using a NAT proxy. I believe that this should have been changed as part of #9633, but wasn't caught when running tests because the `nftables` driver was in use instead.

test: Fixes number of expected NAT rules when using xtables driver.

---

lxd/device/nic_bridged.go
lxd/dnsmasq/dhcpalloc/dhcpalloc.go
lxd/dnsmasq/dnsmasq.go
lxd/network/network_utils.go
lxd/patches.go
test/suites/container_devices_nic_bridged.sh
test/suites/container_devices_nic_bridged_filtering.sh
test/suites/network.sh

Appends the device name to files under `networks/<network>/dnsmasq.hosts`. These were previously named solely after the instance (and project) but this caused static IP allocation to break if multiple devices were attached.
Closes #9719

Bug static ip on multiple bridged nics

---

test/suites/container_devices_nic_bridged_filtering.sh

PR for #9666.
#9793 did not address this because the testing error was initially not reproducible. This was because the nftables driver was still being used (`nftables` must be uninstalled to force `xtables` if `xtables` is using the `nf_table` wrapper, i.e. `nft flush ruleset` does not work).
There is only one test in which this is required, and only `ebtables` needs to be legacy (`iptables` etc can be `nf_table`).

test: Ensure ebtables is legacy when driver is xtables.

---

doc/environment.md
lxc/config/file.go

In some cases it's useful to override the default remote for a single
lxc command invocation instead of switch the default remote statically
in the configuration. Specifically in automated environments where you
deal with different remotes and parallel lxc command invocations happen
this is extremely helpful.
Signed-off-by: Simon Fels <simon.fels@canonical.com>

lxc/config/file: allow overriding default remote by env variable

---

client/connection.go
client/lxd.go
client/lxd_server.go

Hi maintainers! :)
This PR adds `XXXWithContext` function.
This function's argument has [context.Context](https://pkg.go.dev/context#Context).
This context will use `http.Request`.
Users of a library can cancel using `context.Context`.
Signed-off-by: whywaita <whywaita@whywrite.it>

Support context.Context in client

---

lxd/api_cluster.go
lxd/instance/drivers/driver_qemu.go
lxd/instance_state.go

This fixes a number of issue with the evacuation logic especially when it comes to live-migration:
1. LXD didn't allow the stateful stop of the instance
2. A live-migrated instance shouldn't be started at the end of migration (it will happen as part of migration already)
3. We should consider the instance architecture when looking for a compatible server, not for the source's primary architecture
4. Live-migration should also be done on restore
5. To allow proper restoration after a live-migration, we need to be able to update the live instance config
This also removes some code duplication, fixes the revert logic which was unfortunately quite broken and allows a lot more configuration keys to be changed live on virtual machines.

Fix live-migrate during evacuation and restore

---

lxd/instance/drivers/driver_common.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go

Ensures that disk.state on the instance root disk device is larger than
limits.memory on the instance (when performing a stateful start).
Closes #9723

lxd/instance/drivers: Performs disk size check on stateful startup.

---

doc/storage.md

When lxd is installed via snap, like it happens in Ubuntu 20.04 (focal) the storage is mounted inside the namespace `/run/snapd/ns/lxd.mnt` and the command 
`sudo btrfs filesystem resize max /var/snap/lxd/common/lxd/storage-pools/<POOL>/` with `ERROR: not a btrfs filesystem: ....`.
Here I try to give the command required in this situation.

Growing a loop backed btrfs pool new note

---

.sphinx/_static/swagger-override.css
doc/api.md

It seems like Swagger has a problem with relative URLs.
Test if using an absolute URL fixes the issue.
If it does, we should find a way to add the full URL automatically.

doc: use absolute URL for Swagger

---

doc/network-acls.md
doc/network-forwards.md
doc/networks.md

Linking to the automatic ID does not work in Sphinx when appending
the automatic ID to the md file name.
It works within a page because you don't need the file name, but
this is error prone (because the ID depends on the heading and
changes when the heading changes) and should be changed as well in
the future.

doc: fix broken links

---

lxd/network/driver_common.go
lxd/network/network_interface.go
lxd/networks.go

On `GET /1.0/networks/<name>/state` we currently call `resources.GetNetworkState` for all networks. This doesn't work for OVN networks. 
This change attempts loads the network on `GET /1.0/networks/<name>/state` and calls `network.State` instead, allowing for driver specific implemenations.
Partially addresses #9232 and along with #9813.

Adds State function to network interface

---

lxd/storage/drivers/driver_btrfs_utils.go

Most people don't have nested subvolumes and recursively deleting
subvolumes can be time consuming and has additional restrictions on path
traversal that's caused issues to some users.
Closes #9479

lxd/storage/btrfs: Add volume delete shortcut

---

.sphinx/conf.py
doc/doc-cheat-sheet.md

TBH, I'm not sure if we want this or not. It has a few advantages (see commit message), but it also makes things more complicated.
It also increases the size of the objects.inv file by a factor of ten (but from 1.3 KiB to 12.6 KiB, so we can probably live with that).
Enable
https://myst-parser.readthedocs.io/en/latest/syntax/optional.html#auto-generated-header-anchors
Not sure if this really is a great improvement, since it adds more
options for linking, which will make it harder to be consistent.
It does allow for simpler links using Markdown syntax, but we can
only use those when overriding the link text (because otherwise,
they won't show up on GitHub at all).
When sticking to MyST syntax, linking gets a bit more complicated,
but we don't have to add manual targets for every link. …

doc: enable automatically generated anchors

---

lxd/db/cluster/schema.go
lxd/db/cluster/update.go

The previous patch didn't account for both storage_volumes and
storage_volumes_snapshots being potentially empty.

lxd/db: Fix storage_volumes sequence again

---

doc/api-extensions.md
doc/rest-api.yaml
lxd/network/driver_ovn.go
lxd/network/openvswitch/ovn.go
lxd/network/openvswitch/ovs.go
shared/api/network.go
shared/version/api.go

Implements `network.State` for the `OVN` network driver. 
Fixes #9232 when paired with #9817.

Report ovn network state

---

lxd/instance/drivers/driver_lxc.go

lxd/instance/lxc: Use absolute rootfs

---

doc/api-extensions.md
doc/rest-api.md
doc/rest-api.yaml
lxd/storage_volumes.go
shared/version/api.go

@stgraber, this PR adds server-side API filtering for storage volumes but I'm a little bit confused about filtering snapshots.
Default behavior allow us to filter by e.g. name, type, content_type but I don't see possibility to filter by snapshots.
Am I missing something? Should we implement additional behavior? E.g. by checking "/" in storage volume name?
Closes #9798

Implement server-side API filtering for storage volumes 

---

doc/api-extensions.md
doc/image-handling.md
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
shared/simplestreams/products.go
shared/util.go
shared/version/api.go

@stgraber per our discussion. My implementations stick mostly to what you suggested but there are some subtle differences. I think documentation is at a good start.
Closes #9408

Addition of image requirements metadata

---

lxd/instance/drivers/driver_qemu.go

This enables the Windows paravirtualization extensions in QEMU which
makes Windows think it's running on HyperV and therefore provides a good
performance improvement on Windows guests.
For Linux guests, all the VirtIO bits remain active and I've confirmed
that systemd-detect-virt and /proc/cpuinfo in our guests still look the
same.
Reported at: https://discuss.linuxcontainers.org/t/lxd-windows-server-2019-performance-validation/13159

lxd/instance/qemu: Enable HyperV flags on x86_64

---

lxd/db/cluster/schema.go
lxd/db/cluster/update.go
lxd/instance/drivers/driver_qemu.go

QEMU crashes on MSR related errors with 5.4 kernels, 5.10 and higher all
seem fine, so let's test for that.

Fix recent regressions (qemu & db)

---

lxd/patches.go

network.UpdateDNSMasqStatic will update all networks in the database if
passed an empty string. The previous implementation failed if any
directories were listed under $LXD_DIR/networks that were not managed by
LXD (maybe due to failed cluster setup) because the migration attempted
to load the network by it's directory name.
See https://discuss.linuxcontainers.org/t/error-applying-patch-dnsmasq-entries-include/13205

lxd: Only patch dnsmasq for networks in the db.

---

lxd/storage/backend_lxd.go
lxd/storage/drivers/driver_btrfs_volumes.go
lxd/storage/drivers/driver_lvm.go
lxd/storage/drivers/driver_zfs_volumes.go

* For `zfs` and `btrfs` takes a fast snapshot for use as the source of the volume migration. 
* In storage pool `MigrateInstance` method, only freezes the instance during the migration if `RunningCopyFreeze` is true *and* `AllowInconsistent` is false (so instance is never frozen with supported drivers, and optionally frozen for users invoking copy/migrate with and without the `--allow-inconsistent` flag.
* Sets `RunningCopyFreeze` to true for the `lvm` driver.
Closes #9789

Instance migration consistency

---

lxc/console.go
lxc/exec_unix.go
lxd/events/common.go
lxd/instance_console.go

The previous fix for the SIGWINCH issue on non-interactive incorrectly
used "return" rather than "continue", which then caused the websocket to
terminate rather than for the signal to be ignored.

`lxc exec` fixes

---

lxc/storage.go
lxd/db/storage_pools.go
lxd/storage/backend_lxd.go
lxd/storage_pools.go

This allows `lxc storage list` to display "used by" for all nodes (not
only the node receiving the request) whilst preserving existing
functionality.
Closes #9842

lxd/db: Refactor storage pool used by to get info on all nodes.

---

doc/instances.md
lxd/device/gpu_mig.go

Removes VMs from the list of allowed instance types for the `gpu_mig` device. Adds note to docs clarifying multiple device passthrough for GPUs.
Closes #9508

Clarify multiple gpu device passthrough

---

lxd/endpoints/network.go
lxd/endpoints/network_util.go
lxd/endpoints/network_util_test.go

Adds a `networkServerErrorLogWriter` which discards logs matching a regex (which contain the IP of the trusted proxy). Sets the writer in the network server logger.
Closes #9237

Discard TLS errors caused by early connect termination for trusted proxies.

---

lxd/db/generate/db/stmt.go
lxd/db/instance_profiles.go
lxd/db/instance_profiles.mapper.go

Closes #9868 
Adds a `db:"order=yes"` tag to the generator, that can be used to override the default behaviour of ordering by the primary key.
Currently being used for `instances_profiles` field `apply_order`.

Generator: Add 'order' tag to generator

---

lxd/firewall/drivers/drivers_xtables.go
lxd/network/driver_ovn.go

Reported from https://discuss.linuxcontainers.org/t/network-routed-odd-ip6-error-host-has-no-ipv6/
Also don't attempt to disable IPv6 on OVN uplink host interfaces if IPv6 not loaded.

NIC: Don't attempt to configure IPv6 reverse path filter on routed NIC if IPv6 not enabled

---

lxd/metrics/metrics.go

This allow detecting partial scrapes.
https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#metricfamily-metadata

lxd/metrics: add EOL marker

---

lxd/cluster/config.go
lxd/db/networks.go
lxd/db/query/retry.go
lxd/db/storage_pools.go
lxd/instance/drivers/driver_common.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/drivers/load.go
lxd/instance/instance_utils.go
lxd/instance_post.go
lxd/instances_post.go
lxd/profiles.go
lxd/profiles_utils.go
lxd/project/permissions.go
lxd/project/permissions_test.go

This attempts to reduce queries/transactions used when creating an instance in an attempt to better support instance migration on high latency networks.
Related to #9861
This reduces the operation time when used with a 40ms latency by about 3s.
Before:
```
t=2022-02-08T17:08:02+0000 lvl=eror msg="tomp instancesPost" duration=16.465716182s
t=2022-02-08T17:08:46+0000 lvl=eror msg="tomp instancesPost" duration=21.270856828s
t=2022-02-08T17:09:24+0000 lvl=eror msg="tomp instancesPost" duration=16.394522801s
```
After:
```
t=2022-02-08T17:10:59+0000 lvl=eror msg="tomp instancesPost" duration=13.822343883s
t=2022-02-08T17:11:30+0000 lvl=eror msg="tomp instancesPost" duration=18.717397529s
t=2022-02-08T17:11:55+0000 lvl=eror msg="tomp instancesPost" duration=13.731331391s
```
Unfortunately …

Instance: Optimise DB queries during instance creation

---

.sphinx/_templates/header.html

The image currently displays fine, but if we created subfolders
in doc/, it doesn't.
Make sure the path is adapted accordingly.

doc: fix path to image in the header

---

lxd/cluster/gateway.go

There appears to be an issue in dqlite/go-dqlite that means that a connection established via `dqliteNetworkDial` is not closed down cleanly when the remote member becomes unreachable. This sometimes (approx 50:50) leaves the connection in close-wait state with data in the send queue for circa 15mins until the OS releases the connection.
This causes DB transactions on the non-leader members to fail with errors like:
```
lxc cluster ls
Error: failed to begin transaction: call exec-sql (budget 9.999963394s): receive: header: EOF
```
This only seems to happen if the remote member is shutdown cleanly, so that the remote end is cleanly closed, and then the OS is waiting for dqlite/go-dqlite to close the local end of the connection (which it never does) and instead continues to use it resulting …

Cluster: Fix non-leader transaction errors when leader shuts down cleanly

---

lxd/daemon.go
lxd/util/http.go

This allows requests to identify the cluster member from the certificate fingerprint it uses.
Will be used for event-hub feature.

Daemon: Add the trusted cluster member fingerprint to the request context username field

---

lxd-agent/events.go
lxd/events.go
lxd/events/common.go
lxd/events/devlxdEvents.go
lxd/events/events.go

This will be needed for the event-hub feature (by utilising the `EventSourcePush` source type for pushed events from non-hub members).

Events: Replaces isLocal concept with event source

---

lxd-agent/events.go
lxd/cluster/events.go
lxd/events.go
lxd/events/events.go
test/main.sh
test/suites/clustering.sh

Replaces listener location with event server location as it makes more logical sense and avoids the need for a deep copy of the event.
Also includes fix for an intermittent event duplication caused by a joining member running `EventsUpdateListeners` concurrently both as part of its joining process whist at the same time receiving a heartbeat which also triggers `EventsUpdateListeners`.
Includes tests from https://github.com/lxc/lxd/pull/9905

Events: Replaces listener level server location with server level location

---

doc/metrics.md

doc/metrics: don't assume any default scrape_interval value

---

lxd-agent/file.go
lxd/images.go
lxd/instance_backup.go
lxd/instance_console.go
lxd/instance_file.go
lxd/instance_logs.go
lxd/instance_metadata.go
lxd/network_acls.go
lxd/response/response.go
lxd/storage_volumes_backup.go

This is in preparation for the upcoming `forkfile` rework as this adds the ability to stream entire files without ever having to read them into memory or have them be present on disk.

Rework FileResponse

---

lxd/fsmonitor/drivers/driver_fanotify.go

Checks the error number of the syscall and logs the error only if it's code is not `ESTALE`.
Closes #9885.

lxd/fsmonitor/drivers: Ignore stale file handle errors.

---

lxd/apparmor/apparmor.go
lxd/apparmor/instance.go
lxd/apparmor/instance_forkproxy.go
lxd/apparmor/network.go
lxd/apparmor/network_dnsmasq.go
lxd/apparmor/network_forkdns.go
lxd/device/proxy.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/network/driver_bridge.go

This PR removes the `state.State` dependency from `apparmor` package, so now it's dependent from `sys.OS`. This way its clearer what actually `apparmor` package depend on. This change is based on conversation from #9906.

Remove state.State dependency from apparmor package 

---

lxd/cluster/gateway.go
lxd/cluster/heartbeat.go
lxd/cluster/membership.go

I found that when a notification heartbeat was being triggered on the leader, it would cancel the ongoing heartbeat round and discard any node state it had recorded, then retrieve the previous state from the db and broadcast that to all the nodes triggering them to consider nodes offline incorrectly (due to old last heartbeat times) which in turn caused the event listeners to those nodes to be closed  causing missed events.
The fix is to not abruptly cancel the heartbeat round but instead ask it to abort its spread mode  and switch to immediate to finish quickly.
- Don't abruptly end ongoing heartbeat when asked to cancel, instead immediately ping any remaining members and save the state. This is so we don't end up sending out-of-date member info when a notification heartbeat causes an …

Cluster: Heartbeat improvements

---

lxc/config_trust.go

lxc/config_trust: Support --name flag for tokens

---

test/suites/clustering.sh

test: Update clustering membership tests to not expect a specific promotion order of members

---

lxd/storage/drivers/driver_zfs.go
lxd/storage/drivers/driver_zfs_patches.go
lxd/storage/drivers/driver_zfs_volumes.go

This is in relation to https://github.com/lxc/lxd-pkg-snap/issues/61 and trying to avoid
the ZFS tooling running inside the snap mount namspace from trying to mount/unmount the
datasets as it can get confused and fail to find the mounts.
Our experimentation in earier iterations of these changes suggest that using the legacy
mount/umount commands fair better than getting the ZFS tooling do it.
We previously set mountpoint=none but have seen that this is causing ZFS tooling to
try and unmount volumes which is still causing problems.
This is an attempt to try and further avoid ZFS from trying to mount/unmount datasets.

Storage: Set all ZFS dataset mountpoint settings to legacy

---

test/suites/clustering.sh

test: Update cluster rebalance tests to not use member specific role logic

---

shared/api/url.go

This adds a `WithQuery` method to `shared/api/url` so that we can easily add custom queries to an `api.URL`.

shared/api/url: Add WithQuery

---

lxd/certificates.go

The certificate token generation logic would not be hit if the user was
passing in a client certificate despite the Token property being set to true.
Reported-by: Pierre Ferrari

lxd/certificates: Fix token generation over HTTPS

---

client/interfaces.go
client/lxd.go
client/lxd_containers.go
client/lxd_images.go
client/lxd_instances.go
client/lxd_network_acls.go
client/lxd_storage_volumes.go
client/simplestreams.go
doc/rest-api.yaml
lxc/query.go
lxd/api_metrics.go

With this PR, `lxc query` will work against candid/RBAC authenticated endpoints and will be able to select a specific server by using `?target=XYZ`.

Improve `lxc query` support for metrics

---

doc/metrics.md

This aligns with the type of key/signature used by LXD itself.

doc/metrics: use secp384r1 curve with SHA384 signature

---

lxd/device/device_utils_network.go
lxd/device/nic_routed.go
test/suites/container_devices_nic_routed.sh

- Fixes an issue where if `vlan` and `parent` options are set, but VLAN interface doesn't exist, the instance wouldn't start (now it correctly creates the vlan interface on the parent).
- Simplifies the IP in use detection to use socket deadlines rather than go routines and contexts, to avoid leaving go routines behind after context has been cancelled and also to be able to better inspect the resulting error and log warnings for unknown errors, rather than just ignoring them.
- Cleans up parent environmental checks to keep them together and reduce duplicated logic.
- Removes created VLAN interface on error.
- Adds default 500ms timeout to isIPAvailable (which is what the ARP package used as a default anyway), in case `context.Background()` was ever passed to this function, which would …

NIC: Various routed fixes and improvements

---

lxd/device/nic_bridged.go

Avoids inadvertently clearing externally added rules that happen to match rules that would have been added by LXD should filtering have been enabled.
Fixes #9923

NIC: Don't attempt to clear bridged filter rules on stop if filtering is not enabled

---

doc/api-extensions.md
doc/instances.md
lxd/device/nic_routed.go
shared/version/api.go
test/suites/clustering.sh
test/suites/container_devices_nic_macvlan.sh
test/suites/container_devices_nic_routed.sh

Fixes #9940
Allows disabling IP availability probe checks.
Also adds missing tests for IP availability checks.

NIC: Adds ipv{n}.neighbor_probe settings to routed NIC

---

lxd/certificates.go

rbac.UserIsAdmin will return true if the user is:
- local user (admin)
- TLS user (no restriction)
- candid user
- RBAC user (with global admin role)
We then need to check again whether the user is considered to be trusted.
If they are, then we can't add them to the trust store.

lxd/certificates: Better handle authentication

---

doc/api-extensions.md
doc/rest-api.yaml
lxd-agent/daemon.go
lxd-agent/events.go
lxd/api_1.0.go
lxd/api_cluster.go
lxd/cluster/events.go
lxd/cluster/heartbeat.go
lxd/cluster/membership.go
lxd/daemon.go
lxd/db/node.go
lxd/events.go
lxd/events/events.go
shared/api/server.go
shared/version/api.go
test/suites/clustering.sh

Currently in a cluster, event distribution is done as a full-mesh with every member connecting to every other member in the cluster. In larger clusters this causes a lot of unnecessary connections, go routines and interrupts.
The intention of this PR is to provide the ability to specify which cluster members should be responsible for collecting and relaying cluster event messages from other cluster members. 
So by introducing some control over which cluster members will handle the connections from other members, it is expected this will provide the ability to better isolate and control event messaging flows.
This PR includes:
- Adds the concept of an event-hub cluster member role.
- Adds cluster member roles to the heartbeat payload.
- Adding the ability to specify the `event-hub` cluster …

Events: Add event-hub cluster member role

---

lxd/device/device_load.go
lxd/instance/instance_utils.go
lxd/network/acl/acl_validation.go
shared/util.go
shared/validate/validate.go

In #9790 and #9893 we began using device names for naming files (e.g. `<instance>.<device>` for #9790). This means we can no longer use certain characters in device names such as `/` or `..` which would cause files to written to the wrong place.
This PR limits device names to hostname characters plus underscores.

Restrict device names

---

.sphinx/conf.py
.sphinx/requirements.txt

Open Graph tags add information to websites that are displayed when linking in supported tools - like Facebook, Mattermost or the forum:
This fix seems to work for the forum. :grinning: 
However, it looks like there is a bug in the Sphinx extension, because it generates a wrong page URL (...installing.html instead of ...installing/ ). The Facebook debugger complains about this - seems the forum is more tolerant. ;)
I'll check if I can fix this in the extension.

doc: add Open Graph metadata

---

lxd/device/device_load.go
lxd/device/device_utils_unix.go
lxd/device/disk.go
lxd/device/unix_common.go
lxd/dnsmasq/dnsmasq.go
lxd/storage/drivers/driver_btrfs_volumes.go
lxd/storage/drivers/utils.go
lxd/storage/filesystem/fs.go
shared/validate/validate.go
test/suites/container_devices_nic_bridged.sh

- This PR restores the ability to use `.`, `:`, `/` in device names.
- It also allows device names to start with a number.
- But still prevents device names starting with `.` to prevent the creation of hidden files.
- It escapes `/` in device names used in filenames to `-` and escapes `-` to `--`.
- Allows for invalid devices to be stopped and removed.
Following on the heels from https://github.com/lxc/lxd/pull/9946
Prompted by this discussion https://discuss.linuxcontainers.org/t/lxc-4-23-invalid-devices-name-must-not-start-with-a-number/13440

Device: Name validation improvements

---

lxd/device/nic_bridged.go
lxd/dnsmasq/dhcpalloc/dhcpalloc.go
lxd/dnsmasq/dnsmasq.go
lxd/dnsmasq/dnsmasq_test.go
lxd/network/network_utils.go

Fixes an issue introduced by https://github.com/lxc/lxd/pull/9790 that I noticed whilst working on https://github.com/lxc/lxd/pull/9960.
The change to `DHCPStaticAllocation()` to accept either a `projectName`, `instanceName` and `deviceName` *or* an `entryFileName` caused a bug because in the latter scenario the returned `DHCPAllocation` was populated with an empty instance `Name` field - which is used later when finding an existing static allocation for an instance NIC device.
This PR modifies the static allocation subsystem to use the NIC device's static allocation file itself as an identifier, in that way it is the lowest common denominator that is available in both usage scenarios, and also not supports matching the device name of a static allocation not just the instance name.

Network: Fix DHCP static allocation bug

---

doc/api-extensions.md
doc/instances.md
lxd-agent/main_agent.go
lxd-agent/network.go
lxd/device/config/device_runconfig.go
lxd/device/nic_bridged.go
lxd/instance/drivers/driver_qemu.go
shared/instance.go
shared/version/api.go

Adds information about expected nic devices to the VM config share. The lxd-agent reads and applies the configuration on startup.
Closes #7233

Adds lxd-agent option to apply name and MTU to nic devices

---

lxd/api_internal.go
lxd/db/query/dump.go
lxd/db/query/dump_test.go
lxd/db/query/transaction.go

This adds an optional context to two areas: `query.Dump` and `query.TransactionCtx` so that we can use contexts with some backwards compatibility.

Add Context option to some DB actions.

---

doc/metrics.md

The openssl command to create certs writes to your current directory, not `~/.config/lxc/`

doc: Fix cert pathing in metrics.md

---

doc/api-extensions.md
doc/instances.md
lxd-agent/network.go
lxd/device/config/device_runconfig.go
lxd/device/device_utils_network.go
lxd/device/nic_bridged.go
lxd/device/nic_macvlan.go
lxd/device/nic_ovn.go
lxd/device/nic_p2p.go
lxd/device/nic_routed.go
lxd/instance/drivers/driver_qemu.go
shared/instance.go
shared/version/api.go
test/suites/container_devices_nic_routed.sh

Following on from https://github.com/lxc/lxd/pull/9893
I noticed that using a device name like "eth1/foo" without a NIC name set would prevent the VM from starting for two reasons:
1. If `agent.rename_interfaces=true` then the NIC config file couldn't be written due to missing escaping of file name (similar to issues raised in https://github.com/lxc/lxd/pull/9960).
2. The QEMU device config doesn't like `/` in the device IDs.
But escaping the NIC config file introduced another issue, in that the lxd-agent was getting the desired NIC name from the NIC config's file name. To avoid needing to unescape the file, this PR expands the NICConfig struct to include both the DeviceName and the NICName so that they are stored in the file's contents. This also changes the NIC config file to always be …

VM: Bug fixes and improvements to the lxd-agent NIC settings feature

---

lxd/instance/drivers/driver_lxc.go
lxd/instance/instance_utils.go
lxd/instance_console.go
lxd/migrate_instance.go
lxd/sys/os.go
lxd/util/sys.go
shared/idmap/idmapset_linux.go

So that we can export the lxd/util package without liblxc dependencies,
this commit adds the liblxc version as an argument to this helper
instead.

lxd/util/sys: Pass liblxc version to RuntimeLiblxcVersionAtLeast

---

lxd/instance/drivers/driver_qemu.go

Otherwise we get an error like this on QEMU 4.2 and LXD does not support VMs.
```
WARN[02-28|14:15:57] Instance type not operational type=virtual-machine driver=qemu err="QEMU failed to run a feature check: exit status 1"
```
Fixes regression caused by https://github.com/lxc/lxd/pull/9973

VM: Fix VM support detection regression

---

lxd/apparmor/instance_lxc.go

Apparently some distros are now doing a rw rather than ro remount of
/run on shutdown, this should be harmless (as it's effectively its
default state).
Closes #9977

lxd/apparmor: Allow rw remount of /run

---

lxd/cluster/gateway.go
lxd/migrate.go
lxd/network/driver_common.go
lxd/util/net.go
shared/tcp/tcp_timeout_user.go
shared/tcp/tcp_timeout_user_noop.go
shared/tcp/tcp_timeouts.go
test/suites/clustering.sh

Will be used by LXD server and client.
Also removes use of deprecated `syscall` package.

Shared: Adds tcp package for setting timeouts on TCP connections

---

lxd/network/driver_bridge.go

As forward listen address cannot be changed during update.

Network: Don't refresh BGP prefixes during forward update

---

lxd/device/disk.go

Device: Detect disk pool VM mount options using single call to os.Stat

---

lxd/seccomp/seccomp.go

As process_still_alive calls pidfd_send_signal, it expects a pidfd and not a PID.
Failure to do this causes an error when the thread attaching the BPF program isn't a thread-group leader.
As I understand the code, we want to check that the comparison done before was done on a stable ground.
So it seems that sending a signal to the PID FD opened before the check should be the way to go.

seccomp: pass a PID FD to process_still_alive

---

lxd/daemon.go
lxd/device/disk.go
lxd/instance/drivers/driver_common.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/instances.go
lxd/storage.go
lxd/storage/backend_lxd.go
lxd/storage/errors.go
lxd/storage/load.go
lxd/task/group.go
lxd/task/group_test.go

This PR improves upon https://github.com/lxc/lxd/pull/9951 by adding a pre-start check for auto starting instances to check that all storage pools required by the instance's `disk` devices are available. If they are not then the auto start is skipped initially on LXD start up.
If the pool then later becomes available then the instance auto start mechanism is tried again to see if any instances can now auto start where they should have before.
This PR also fixes a missing error check for warning resolution on LXD daemon start up and checks pool status before proceeding with volume mounting.

Storage: Try auto starting instances when storage pools become available

---

lxd/instance/drivers/driver_qemu_templates.go

CRB mode is apparently faster than TIS and since we don't need 1.2 mode
(we only run in 2.0), TIS doesn't provide anything of value.

lxd/instance/qemu: Switch TPM mode to CRB

---

lxd/apparmor/archive.go

When backups or images are stored on a custom volume, VarPath/backups
and VarPath/images becomes a symlink which then causes unsquashfs to
fail as apparmor doesn't follow symlinks and prevents it from reading
the image.

lxd/apparmor/archive: Expand all paths

---

lxd/device/device_utils_disk.go
lxd/device/disk.go

Introduced by https://github.com/lxc/lxd/pull/9991 whist fixing https://github.com/lxc/lxd/pull/9976
By removing `srcPath` and using `mount.DevPath` directly, I inadvertently caused virtiofsd to not start properly because it was being passed the FD number of virtiofs-proxy-helper (which rewrites the mount.DevPath).
Changing the start order fixes this.
Also improves `DiskVMVirtiofsdStart` validation to check `sharePath` looks like a path to catch this sort of regression more quickly in the future.

Device: Fix regression for VM disk shares

---

lxd/instance/drivers/driver_lxc.go

This is a tentative fix for https://github.com/lxc/lxd/issues/10011

LXD: Disable idmapped mounts if LXD_SHIFTFS_DISABLE=true

---

lxc/alias.go
lxc/cluster.go
lxc/cluster_group.go
lxc/config_template.go
lxc/config_trust.go
lxc/image.go
lxc/image_alias.go
lxc/info.go
lxc/list.go
lxc/network.go
lxc/network_acl.go
lxc/network_forward.go
lxc/network_peer.go
lxc/network_zone.go
lxc/operation.go
lxc/profile.go
lxc/project.go
lxc/remote.go
lxc/storage.go
lxc/storage_volume.go
lxc/utils.go
lxc/utils/sort.go
lxc/utils_test.go
lxc/warning.go

Exports `byName`, `stringList`, and `byNameAndType` so that we can use LXD's sorting implementation for cli tables in other projects.

Export sorting helpers.

---

lxd/instance/drivers/driver_qemu.go

spawn=allow is required when QEMU is asked to daemonize.
Previous QEMU versions would incorrectly block `fork` when spawn=deny
was passed while allowing clone to succeed.
This was then making it possible for us to use daemnize thanks to most
Linux distributions using the clone syscall to implement fork.
Current QEMU has fixed their seccomp profile to block both fork and
clone, preventing -daemonize when spawn=deny is passed.

lxd/instance/qemu: Set spawn=allow

---

lxd/db/generate/db/stmt.go
lxd/db/instances.mapper.go
lxd/db/warnings.go
lxd/db/warnings.interface.mapper.go
lxd/db/warnings.mapper.go

Updates the DB generator's `naturalKeySelect` function to only join on scalar fields that are part of the natural key, as there's no point in joining on additional tables when just getting the entity's ID.
As per suggestion from @masnax in https://github.com/lxc/lxd/pull/9970#issuecomment-1051233703

Warnings: Use WarningExists from DB generator

---

lxd/api_1.0.go
lxd/daemon.go
lxd/instance/drivers/driver_lxc.go
lxd/sys/os.go

And updates start up kernel feature detection to use it, and take into account LXD_SHIFTFS_DISABLE.
Follows comment from @brauner here https://github.com/lxc/lxd/pull/10012#issuecomment-1060886789

lxd: Adds IdmappedMounts field to OS struct

---

lxd/device/nic_ovn.go
lxd/device/nic_sriov.go

This might help prevent syscall hangs when calling `DeviceUnbind` when multiple instances are shutting down at the same time.
@stgraber has seen this blocked go routine when shutting down a VM using SRIOV:
```
goroutine 14561 [syscall, 218 minutes]:
syscall.Syscall(0x1, 0x28, 0xc000a375e8, 0xc)
/snap/go/9028/src/syscall/asm_linux_amd64.s:20 +0x5
syscall.write(0xc001287080, {0xc000a375e8, 0x426801, 0xc000a37498})
/snap/go/9028/src/syscall/zsyscall_linux_amd64.go:915 +0x4d
syscall.Write(...)
/snap/go/9028/src/syscall/syscall_unix.go:214
internal/poll.ignoringEINTRIO(...)
/snap/go/9028/src/internal/poll/fd_unix.go:582
internal/poll.(*FD).Write(0xc001287080, {0xc000a375e8, 0xc, 0x20})
/snap/go/9028/src/internal/poll/fd_unix.go:275 +0x36e
os.(*File).write(...) …
```

lxd/device/nic: Lock concurrent access to networkSRIOVRestoreVF

---

lxd/storage/drivers/generic_vfs.go

This ensures that owner/group name info inside the tarball isn't used to resolve to a different
UID/GID as they are unpacked on the host, and instead ensures they remain the same UID/GID that
they were inside the instance when it was exported.
Reported from https://discuss.linuxcontainers.org/t/no-remapping-of-container-after-restore/13490

Storage: Pass --numeric-owner to backup tar unpack command

---

lxd/device/nic_bridged.go
test/suites/container_devices_nic_bridged_filtering.sh

`ipv{n}.address=none` is currently not a valid setting when the parent network of the NIC is managed (if DHCP is enabled). This PR allows for this setting in validation, and then checks against this setting later to ensure that IPs are not allocated dynamically.
A test has also been added to ensure that when `ipv{n}.address=none` and `security.ipv{n}_filtering=true`, then all protocols are blocked.
Closes #10024

Allow ipv{n}.address=none for bridged NICs on managed networks

---

lxd-agent/exec.go
lxd/instance_exec.go

lxd: Warn if exec control connection disconnects prematurely

---

lxd/db/storage_volumes.go
lxd/storage_volumes_snapshot.go

`lxc storage volume info default f1`  command returns:
```
Name: f1
Type: custom
Content type: filesystem
Usage: 24.00KiB
Snapshots:
+-------+-------------+------------+
| NAME  | DESCRIPTION | EXPIRES AT |
+-------+-------------+------------+
| snap5 |             |            |
+-------+-------------+------------+
| snap6 |             |            |
+-------+-------------+------------+
| snap7 |             |            |
+-------+-------------+------------+
| snap8 |             |            |
+-------+-------------+------------+
| snap9 |             |            |
+-------+-------------+------------+
```
even though there is `snapshots.expiry` value set for storage volume.
Below is output after fix:
```
Name: f1
Type: custom
Content type: filesystem
Usage: 24.00KiB
Snapshots: …
```

'lxc storage volume info' returns empty 'EXPIRES AT' values

---

client/lxd.go
lxd/cluster/heartbeat.go
lxd/instances_post.go
lxd/migrate.go
lxd/storage_volumes.go
test/deps/devlxd-client.go

This PR fixes an issue intermittently caused LXD cluster upgrades to hang before triggering the snap package refresh and reload.
This was happened when the first member was refreshed. It would stand down as leader and a new member would become leader, triggering a heartbeat. As part of the heartbeat round, the event connections are checked for freshness, and because the first member had just been refreshed and reloaded, the old event connection to that first member was closed.
However not enough time had passed for the first member to be considered "offline", so rather than skipping it instead each member attempted to connect to the first member and setup an event websocket stream. 
Unfortunately in certain scenarios it was possible for the TCP/TLS connection to be established, but have …

Cluster: Fix hang during cluster upgrade due to missing event websocket handshake timeout

---

test/suites/container_devices_nic_bridged_filtering.sh

It now outputs in hex rather than decimal in nftables on Jammy.
So this PR now supports both Focal and Jammy versions of nftables.

test: Fix container devices nic bridged filtering tests on recent versions of nftables

---

lxd/instance/drivers/driver_lxc.go

This allows accessing a container's files if it has never been started.
Also cleans up forkfile.pid on exit.
Reported from https://discuss.linuxcontainers.org/t/error-listen-unix-var-snap-lxd-common-lxd-logs-name-forkfile-sock-bind-no-such-file-or-directory-when-using-lxc-file-push-immediately-after-lxd-migrate/13554

Instance: Create log directory if needed before starting forkfile

---

.sphinx/requirements.txt

Seems docutils 0.18.1 messes up note formatting, which is probably
the reason why both Sphinx and myst-parser require docutils<0.18.
Pages with issues:
https://linuxcontainers.org/lxd/docs/master/network-acls/ 
https://linuxcontainers.org/lxd/docs/master/network-forwards/
I had checked mainly https://linuxcontainers.org/lxd/docs/master/doc-cheat-sheet/#notes , and there it works strangely enough ...

doc: restrict docutils version to fix parsing of notes

---

lxd/daemon.go
lxd/instance/drivers/driver_qemu.go
lxd/state/state.go

We've been seeing multiple issues with VMs not starting on various storage drivers with io_uring on earlier kernels.
Tested on the 5.4 and 5.13 kernels, with the latter confirming that iouring support was enabled in QEMU:
- `dir` driver
- `btrfs` driver on loop image (io_uring still not used).
- `zfs` driver atop an LVM volume.
- `zfs` driver atop loop image.
- `lvm` driver atop physical disk.
- `lvm` driver atop loop image.
Fixes #10061

VM: Only enable io_uring support on kernels >= 5.13.0

---

lxd/db/node.go

Regardless of what state a cluster member is in, it's failure to respond
to hearbeats should be reported in the status message.
This is particularly visible when evacuating servers as prior to this
change, it was impossible to know if the server was responsive or not.

lxd/cluster: Don't mask lack of cluster response

---

lxc/file.go
lxd-agent/sftp.go
lxd/cluster/gateway.go
lxd/instance_sftp.go
lxd/response/upgrade.go

Fixes #10073
Also makes the stopping of sshfs more reliable when the remote instance connection goes away.

HTTP: Ensure Connection: Upgrade header is returned when LXD upgrades a connection 

---

lxd/device/nic_bridged.go
lxd/firewall/drivers/drivers_consts.go
lxd/firewall/drivers/drivers_nftables.go
lxd/firewall/drivers/drivers_nftables_templates.go
lxd/firewall/drivers/drivers_util.go
lxd/firewall/drivers/drivers_xtables.go
lxd/firewall/firewall_interface.go
test/suites/container_devices_nic_bridged_filtering.sh

Changes the firewall interface for the bridge filter setup and and teardown to accept a slice of networks. These are passed in by the bridged nic device from it's settings and handled by each firewall driver accordingly.
Closes #9878

Allow ipv{4,6} routes when using bridged security.ipv{4,6}_filtering

---

lxd/daemon.go
lxd/device/config/devices.go
lxd/device/device_common.go
lxd/device/device_interface.go
lxd/device/disk.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/instances.go
lxd/networks.go
lxd/patches.go
lxd/storage.go
lxd/storage/backend_lxd.go
lxd/storage/errors.go
lxd/storage/load.go

This lays the groundwork for degraded network startup by adding the concept of a pre-start check to devices.
The pre-start check will optionally perform some (cheap) checks that will indicate that the device cannot start, and use this as an indicator not to bother starting the device.
The error returned from the pre-start check will then be returned from the instance's `Start()` function and will be used to inform the auto-start instances function to avoid retrying the start of an instance. 
The instance disk device pool availability check was previously done in the auto-start instances function, but with the forthcoming degraded network start up feature we needed a way to push this check into the device itself so that a NIC can check whether its managed parent network is available whilst …

Device: Adds concept of a pre-start check to devices and pushes storage pool availability check into disk device

---

lxd/device/device_interface.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go

Includes https://github.com/lxc/lxd/pull/10082
This PR builds on the device pre-start check concept added in https://github.com/lxc/lxd/pull/10082 by running the pre-start checks for all devices before calling `Start()` for any of the instance's devices.
This way if any of the instance's devices fail their pre-start check then we don't have to go through the (potentially expensive) device stop revert steps.
As well as being generally more efficient when manually starting an instance that is unavailable. It is also useful because when a storage pool (or eventually network) becomes available all auto-start instance candidates will tried to be started, and if they still cannot start because one of its other dependencies is unavailable then this may mean that some of the devices had been …

Instance: Run all device pre-start checks before starting any device

---

lxc/network.go
lxd/daemon.go
lxd/db/warnings_types.go
lxd/device/nic_bridged.go
lxd/device/nic_macvlan.go
lxd/device/nic_ovn.go
lxd/device/nic_sriov.go
lxd/network/driver_bridge.go
lxd/network/driver_common.go
lxd/network/driver_macvlan.go
lxd/network/driver_ovn.go
lxd/network/driver_physical.go
lxd/network/driver_sriov.go
lxd/network/network_interface.go
lxd/network/network_load.go
lxd/networks.go
lxd/patches.go
lxd/storage.go
shared/api/network.go

Includes https://github.com/lxc/lxd/pull/10072
- Attempts to initialize all networks at LXD startup.
- If any fail then launches a go routine to retry them in the background every 1 minute.
Items:

Network: Degraded startup

---

.sphinx/_extensions/discourse-links.py
.sphinx/_static/custom.css
.sphinx/_templates/page.html
.sphinx/conf.py
doc/authentication.md
doc/backup.md
doc/cloud-init.md
doc/clustering.md
doc/containers.md
doc/installing.md
doc/instances.md
doc/metrics.md
doc/network-acls.md
doc/network-forwards.md
doc/network-peers.md
doc/network-zones.md
doc/networks.md
doc/storage.md
doc/virtual-machines.md

Add an extension to add related Discourse links to the documentation.
They can be added as meta tags at the top of the file.
For now, I just added some random topics for testing. Need to add useful links before this is merged. ;)

Discourse links clean

---

lxd/instance/drivers/driver_common.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/storage/backend_lxd.go
lxd/storage/utils.go

For consistency with VolumeDBCreate.
This also ensures that all calls to RemoveStoragePoolVolume will ignore errors if they indicate the record was not found.

Storage: Add and use VolumeDBDelete helper function

---

doc/environment.md
lxd/daemon.go

Adds `LXD_IDMAPPED_MOUNTS_DISABLE` env var to allow disabling shiftfs independently of idmapped mount support.
This is because the LXD snap package uses `LXD_SHIFTFS_DISABLE=true` to disable shiftfs support, but we do not want to also disable idmapped mount support.
This fixes an issue introduced with https://github.com/lxc/lxd/pull/6558
Reported from https://discuss.linuxcontainers.org/t/disk-device-inside-unprivileged-container-with-shiftfs/13622

LXD: Allow disabling shiftfs independently of idmapped mount support 

---

lxd/instance/drivers/driver_qemu.go

This prevents the following during shutdown (`journalctl -b-1 --grep lxd`):
```
Mar 21 21:03:17 foo systemd[1]: Unmounting /run/lxd_agent...
Mar 21 21:03:17 foo umount[487]: umount: /run/lxd_agent: target is busy.
Mar 21 21:03:17 foo systemd[1]: run-lxd_agent.mount: Mount process exited, code=exited, status=32/n/a
Mar 21 21:03:17 foo systemd[1]: Failed unmounting /run/lxd_agent.
```

lxd-agent: cleaner shutdown sequence

---

lxd/network/openvswitch/ovn.go

The snap has a generated /etc/ovn which always points to the right
location, so we shouldn't be trying to directly reach the host path.

lxd/network/ovn: Don't use HostPathFollow on OVN configs

---

lxd/instance.go
lxd/migrate_instance.go
lxd/migrate_storage_volumes.go
lxd/storage/backend_lxd.go
lxd/storage/load.go
lxd/storage/pool_interface.go
lxd/storage/utils.go
lxd/storage_volumes.go

This ensures that it will use an pre-loaded storage pool var inside the instance,
to avoid extra DB queries.
This is also essential as we move to creating the storage volume DB records in the
storage package, as at instance create time the storage pool to use is derived from
the instance's root disk config and then that storage pool is pre-loaded inside the
instance. Meaning that we can then access it to create the instance's volume, whereas
without this the storage volume select query would fail as the DB record hasn't been
created yet.
Also improves error messages and several other storage related improvements or clarifications.

Storage: Update GetPoolByInstance to use instance's StoragePool() function

---

lxd/db/storage_volumes.go
lxd/migrate_storage_volumes.go
lxd/storage/backend_lxd.go
lxd/storage/utils.go

And reduce the amount of DB queries needed in `migrationSourceWs.DoStorage` by not loading all storage volume snapshots once and then iterating through them and loading them again in a different format.
Now `GetLocalStoragePoolVolumeSnapshotsWithType` will populate the `Config` field but within a single transaction.

Storage: Update VolumeDBSnapshotsGet for consistency with other functions

---

client/lxd_instances.go
doc/api-extensions.md
doc/rest-api.yaml
lxd/instance_post.go
shared/api/instance.go
shared/version/api.go

When making a calling `InstancePost` to set up a migration, the value of `AllowInconsistent` was not being set. This change should stop instances from being frozen when copying from one remote to another (e.g. `lxc copy remote1:a remote2:b --allow-inconsistent`).
Closes #10091

Use allow inconsistent for cluster migrations

---

lxd/storage/backend_lxd.go
lxd/storage/drivers/volume.go
lxd/storage/utils.go

And add extra validation that instance root disk effective config fields are not stored in the volume database records.

Storage: Simplify instance root disk volume config

---

lxd/instance/drivers/driver_qemu.go

Drives were always using the "file" driver which required the block
device file to be a regular file. The "file" driver however doesn't work
with character or or block devices.
This fixes the issue by checking whether the file is a character or
block device. In this case, the "host_device" driver is used.

lxd/instance/drivers/qemu: Fix block devices

---

lxd/images.go
test/main.sh
test/suites/image.sh

When refreshing an image, the old image was kept in the database whereas
the actual files were deleted.
This removes the database entry of the old image when refreshing.
This fixes #10120.

lxd/images: Remove old db entry after image refresh

---

lxd/api_internal.go
lxd/api_internal_recover.go
lxd/db/instances.go
lxd/db/storage_pools.go
lxd/instance.go
lxd/instance/drivers/driver_common.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/drivers/load.go
lxd/instance/instance_utils.go
lxd/instance_post.go
lxd/instance_test.go
lxd/instances_post.go
lxd/migrate_instance.go
lxd/snapshot_common_test.go
lxd/storage/backend_lxd.go
lxd/storage/backend_mock.go
lxd/storage/pool_interface.go
test/suites/backup.sh

This PR completes the move of the storage volume DB record management from being spread over different subsystems in LXD to being exlusively managed in the `lxd/storage` package.
As part of this process I have found several bugs in the existing storage layer, which I have not attempted to fix in this PR in an attempt to minimise the risk of a regression whilst the DB record management is moved.
* https://github.com/lxc/lxd/issues/10118
* https://github.com/lxc/lxd/issues/10117
* https://github.com/lxc/lxd/issues/10103
* https://github.com/lxc/lxd/issues/10102

Storage: Manage instance storage volume database records in storage package

---

lxd/instance/drivers/driver_qemu.go

This reverts commit 51eaa589f799d8814ed3fe0af6b8a6995c3daa2b.
This fixes a regression breaking lxd-agent on a variety of Linux distributions.
Closes https://github.com/lxc/lxc-ci/issues/480

Revert "lxd-agent: cleaner shutdown sequence"

---

shared/util.go
shared/util_test.go

Sets minimum Go version to 1.18.
Based on discussion https://github.com/lxc/lxd/pull/10115#discussion_r834708023

shared: Adds generic HasKey

---

lxd/db/db_internal_test.go
lxd/db/images.go
lxd/images.go
lxd/operations/operations.go
lxd/storage/backend_lxd.go
lxd/storage_pools.go
test/suites/clustering.sh
test/suites/image.sh

- Reverts #10121 so that clustering image refresh tests don't fail.
- Fixes #10120 by moving the image record deletion into the API route handler.
- Improves image refresh logging and errors.
- Ensures full image fingerprint is returned to client when deleting image.
- Distributes manually refreshed image in cluster.

Image: Fix image refresh record management

---

shared/network.go

`crypto/tls` defaults to enabling TLS 1.0+ on server-side [*].
Before commit f91da807, LXD_INSECURE_TLS relied on the default
CipherSuites list but still had tls.VersionTLS12 as the MinVersion.
Bring back the MinVersion of TLS 1.2.
*: https://pkg.go.dev/crypto/tls#Config

shared/network: require TLS 1.2+ if LXD_INSECURE_TLS

---

lxd/apparmor/instance.go
lxd/apparmor/instance_qemu.go
lxd/instance/drivers/driver_common.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/instance_interface.go

This removes the devPaths logic as disks and devices are not accessed by
QEMU directly but are given a file descriptor instead.

lxd: Drop devPaths logic

---

doc/authentication.md
doc/projects.md

Add the link as a related link instead of a YouTube link, since the
video shows an example for how to use projects/authentication,
not how it works in general.

doc: add link to multi-user video

---

lxd/main_forksyscall.go
lxd/seccomp/seccomp.go

lxd: make sure we're operating relative to the correct pid namespace

---

lxd/instance/drivers/driver_qemu.go

lxd/instance/qemu: Fix bad topoext logic

---

lxd/instance/drivers/driver_qemu.go

This adds the serial key to the device. Having this key set will
populate /dev/disk/by-id.

lxd/instance/drivers/qemu: Add serial key to device

---

lxd/api_cluster.go
lxd/certificates.go
lxd/db/certificate_projects.go
lxd/db/certificate_projects.interface.mapper.go
lxd/db/certificate_projects.mapper.go
lxd/db/certificates.go
lxd/db/certificates.mapper.go
lxd/db/generate/db.go
lxd/db/generate/db/method_v2.go
lxd/events.go

Coming off of the discussions in #9775, this is going to be the first (likely also the simplest) of several refactors to the db package to reduce the number of opened transactions, and also limit the number of tables "automatically" queried when calling a `ClusterTx` helper.
* First new thing here is V2 method generation:
This introduces a very temporary `version=2` optional flag that can be included in the db generator comments, in order to pick between one of 2 implementations of method generation. 
Basically, as we are going to go through each of these entities (Instances, Certificates, Profiles, Projects...) one by one in this refactor, it helps to be able to split up the new generated code from the old generated code that will still be used for the not-yet updated entities. Once …

Database Refactor Part 1: Decouple Certificates from their Projects.

---

doc/api-extensions.md
lxd/storage_volumes_state.go
shared/api/storage_pool_volume_state.go
shared/version/api.go

Closes #10085
I was not sure about modifying `size` units. Maybe we should this in separate PR but what about backward compatibility?

Storage volume total size and used in a single query

---

lxd/util/net.go

Closes #10181 
Assigns the `defaultPort` (8443) to an address when a colon is specified. A trailing colon makes `net.SplitHostPort` return successfully, but with an empty port.

lxd/util/net: Assign default port if no port given

---

lxd/device/device_utils_disk.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/storage/drivers/driver_ceph_utils.go
lxd/storage/drivers/driver_lvm_utils.go
lxd/storage/drivers/driver_lvm_volumes.go
lxd/storage/drivers/generic_vfs.go
lxd/storage/drivers/utils.go
lxd/storage/drivers/volume.go
lxd/storage/utils.go
lxd/storage_volumes_snapshot.go
shared/instancewriter/instance_tar_writer.go
test/includes/storage.sh
test/suites/incremental_copy.sh
test/suites/storage_local_volume_handling.sh

To fix VM shutdown problems due to `config.mount` bind mount being unmountable immediately after the QEMU process ends sometimes (such as when the VM has been exported).
In doing so I also noticed that errors from unmounts in `MountTask()` were not handled, and in changing that so they were, revealed some more bugs in the LVM non-thinpool driver, which are also fixed in this PR.
Fixes https://github.com/lxc/lxd/issues/10184
Fixes https://github.com/lxc/lxd/issues/10187

Storage: Use TryUnmount without MNT_DETACH in DiskMountClear

---

lxd/instance/instance_utils.go

This fixes an issue when parsing a version like 5.0.0~git1234 similar to what Ubuntu 22.04 currently ships.

lxd/instance: Fix RuntimeLiblxcVersionAtLeast to handle ~

---

shared/util_linux.go

Some filesystems don't support llistxattr() for various reasons. Let's
interpret this as a set of no xattrs, instead of an error.
The goal here is to be able to use the idmap shifting code on xattr-less
filesystems, which is not currently possible, since there is the following
call graph:
github.com/lxc/lxd/shared/idmap.(*IdmapSet).doUidshiftIntoContainer.func1
-> github.com/lxc/lxd/shared/idmap.GetCaps
-> github.com/lxc/lxd/shared.GetAllXattr
-> github.com/lxc/lxd/shared.llistxattr
Signed-off-by: Tycho Andersen <tycho@tycho.pizza>

shared: allow EOPNOTSUPP from llistxattr()

---

lxd/backup/backup_config.go

Backup: Default to container instance type if not specified in backup config

---

lxd/api_cluster.go
lxd/api_networks_test.go
lxd/api_storage_pools_test.go
lxd/db/backups.go
lxd/db/certificates.go
lxd/db/cluster.go
lxd/db/db_internal_test.go
lxd/db/errors.go
lxd/db/images.go
lxd/db/instances.go
lxd/db/network_acls.go
lxd/db/network_zones.go
lxd/db/networks.go
lxd/db/node.go
lxd/db/raft.go
lxd/db/storage_pools.go
lxd/db/storage_volume_snapshots.go
lxd/db/storage_volumes.go
lxd/operations.go
lxd/response/smart.go
lxd/storage/drivers/driver_ceph_utils.go
lxd/storage/drivers/driver_lvm.go
lxd/storage/drivers/driver_lvm_utils.go
test/suites/backup.sh

We've been gradually moving away from using `ErrNotFound`, so this PR finishes off that migration.
Fixes https://github.com/lxc/lxd/issues/5548

LXD: Replace use of ErrNotFound with api.StatusError with code set to http.StatusNotFound

---

.github/SUPPORT.md
.sphinx/conf.py
CONTRIBUTING.md
README.md
doc/README.md
grafana/LXD.json

As in general anything under doc/ isn't cleanly readable by normal markdown parsers, we shouldn't link to them from pages that are in clean markdown. Instead, link to the rendered documentation.
I've also updated all mention of `/master/` to use the now available `/latest/` symlink.

Update doc links

---

lxd/storage/drivers/driver_dir_volumes.go
lxd/storage/drivers/generic_vfs.go
lxd/storage/drivers/utils.go

For filesystem backed storage pools (dir and btrfs) this function was previously copying the block
volume files twice, first via rsync and then second using Go's io.Copy().
This commit changes it do behave more like genericVFSMigrateVolume where the rsync part of the
transfer excludes the block volume file.
Related to #10111

Storage: Updates genericVFSCopyVolume to not copy block volume files twice

---

lxd/instance/drivers/driver_qemu.go
lxd/sys/os.go

lxd/instance/qemu: Avoid conflicting vsock IDs

---

lxd/instance/drivers/driver_qemu.go
lxd/main_forklimits.go
lxd/storage/backend_lxd.go
lxd/storage/drivers/driver_dir_volumes.go
lxd/storage/drivers/utils.go
lxd/storage/utils.go
shared/util_linux.go

- Fixes missing instance snapshot symlink not being created when copying instance in same pool.
- Changes `copyDevice()` function to use `dd` with direct I/O and 16MB byte size, running with a low priority, in order to reduce CPU impact to other processes on the system and to avoid expiring the filesystem cache when copying larger block images.
- Updates `dir` `CreateVolumeSnapshot` to use `copyDevice()` for copying block volume files rather than `rsync`.
- Runs `qemu-img` as low priority, and for image unpack uses a 16MB buffer size for `qemu-img dd` to improve performance.
Fixes #10111

Storage: VM copy dir driver peformance improvements

---

doc/installing.md
test/includes/lxc.sh
test/main.sh

`uuidgen` was used to generate a single placeholder remote name.
If we ever want a UUID generator back, we should use:
`systemd-id128 new -u`
Which doesn't depend on an additional package.

test: drop dependency on uuidgen

---

lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
test/suites/basic.sh
test/suites/storage_profiles.sh

When updating an instance, the root device was updated as well. This
caused problems when doing migration and the names of the source and
target storage pools differed.
This fixes the issue by not updating the root device pool.

lxc/instance/drivers: Do not update root device pool

---

lxd/util/net_test.go

lxd/util: Extend tests for CanonicalNetworkAddress

---

lxd/device/device_utils_disk.go

This is where they are installed by default when building QEMU from source.

VM: Look for QEMU helpers in /usr/libexec/

---

doc/instances.md
lxd/device/disk.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/drivers/load.go

lxd/device/disk: Apply name length restriction to VM only

---

lxd/instance/drivers/driver_qemu.go
lxd/storage/drivers/driver_dir_volumes.go
lxd/storage/drivers/utils.go
lxd/storage/utils.go

To avoid polluting the page cache and improve performance:
- Use `qemu-img convert` in direct I/O mode where possible.
- Uses `dd`, in direct I/O mode where possible, for restoring block volume snapshots on `dir` storage pools, rather than rsync.
Also: 
- Protects calls to `qemu-img info` with `prlimit` and disables image format detection, for security.

VM: Use qemu-img convert rather than qemu-img dd and use direct I/O where possible

---

lxd/instance/drivers/driver_qemu.go

QEMU 6.2 attempts to reopen the nvram file for writing during stateful snapshot.
LXD was preventing this because the nvram file was only writable by root, but the QEMU process was normally run as `lxd`.
To fix this, we pass the nvram file by FD and make writable by the user that runs the QEMU process.
This allows the QEMU process to bypass the root:root 0700 restriction on the instance's directory, by opening /dev/fd/<n>, and the nvram file itself is writable by the user that QEMU process is run as.
Fixes https://github.com/lxc/lxd/issues/9875
Related to https://gitlab.com/qemu-project/qemu/-/issues/975

VM: Fix stateful snapshot with QEMU >= 6.2

---

lxd/apparmor/instance_lxc.go

On a Focal host with kernel 5.13, starting an unpriv Jammy
container (security.nesting=false) with the /etc/systemd/
system-generators/lxc modified to NOT override LoadCredential,
the following denials are visible:
```
apparmor="DENIED" operation="mount" info="failed flags match" error=-13 profile="lxd-c1_</var/snap/lxd/common/lxd>" name="/dev/shm/" pid=2176973 comm="(sd-mkdcreds)" fstype="ramfs" srcname="ramfs" flags="rw, nosuid, nodev, noexec"
```
/dev/shm is showned as a tmpfs inside the container but for
some reason, its fstype is reported as ramfs in the host's logs.
```
$ lxc exec c1 -- mount | grep shm
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev,uid=1000000,gid=1000000,inode64)
```
As such, let's treat ramfs the same as tmpfs.

lxd/apparmor: Treat ramfs the same as tmpfs

---

lxd/network/driver_sriov.go

Network: Mark `sriov` network as available on successful start

---

lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go

Because Go maps are iterated in a random order, if there were multiple NICs without a `name` property
then the generated interface name stored in volatile may be unexpected based on the order the devices
were added.
E.g. for 2 NICs (eth0, and eth1), they may end up with respective volatile interface names of eth1 and eth0, which is confusing.
Fixes #10282

Instance: Ensure that devices are added and removed in the correct order

---

shared/util_linux.go

This message often appears in my logs, sometimes around exiting `lxc shell` but not always. Anyway, since there is nothing to do about it from a user/admin perspective, I'd consider this to be debug info.

Lower log level of "Detected poll(POLLNVAL) event" message

---

lxd/sys/os.go

The vsock package doesn't return an error when the module isn't loaded,
instead it returns an invalid value of 4294967295.
So fix the main issue by loading the module if possible and then treat
any value past signed-32bit as invalid.
Closes #10300

lxd/sys: Fix vsockID detection

---

lxd/api_internal.go
lxd/db/query/dump.go
lxd/db/query/dump_export_test.go
lxd/db/query/dump_test.go
test/suites/sql.sh

The `query.Dump` function does not work for other dqlite databases because it explicitly dumps the the `schema` table (expected for both node and cluster dbs). 
To allow a more general usage of this function, now all tables, their schema, and their data is collected directly from the db.

Sql dump schema table

---

lxd/cluster/gateway.go

1. This fix prevents a deadlock in the following scenario:
- GET request comes in
- `HandlerFuncs` obtains `Rlock`
- `lxd shutdown` is called on the node handling the request, tries to take the `Lock`  https://github.com/lxc/lxd/blob/6fd49811c4792f26b9faa1c84a5cfb7de986c76c/lxd/cluster/gateway.go#L512 but blocks, because the `Rlock` is held by `HandlerFuncs`
- `HandlerFuncs` continues here https://github.com/lxc/lxd/blob/6fd49811c4792f26b9faa1c84a5cfb7de986c76c/lxd/cluster/gateway.go#L273 and tries to obtain `Rlock` (again, recursive) in `Leaderaddress`. This blocks because `Shutdown` is blocked on the `Lock`.
- Deadlock ensues
see https://pkg.go.dev/sync#RWMutex.RLock
```
func (*RWMutex) [RLock](https://cs.opensource.google/go/go/+/go1.18.1:src/sync/rwmutex.go;l=56) …
```

Recursive rlock shutdown

---

lxd/db/query/dump.go
lxd/db/query/dump_export_test.go
lxd/db/query/dump_test.go
lxd/main_sql.go
test/suites/sql.sh

Following #10298 it was noted that
* Behaviour which quoted table names and added "IF NOT EXISTS" was inconsistent.
* Only tables were included in the database dump (no indices, view, or triggers).
This PR removes the quotation behaviour and collects all entities from the sqlite_master table into the dump. Tests are updated to check for the previously missing entities.

Sql dump all entities

---

shared/cert.go

When configuring TLS for a HTTP client in LXD cloud we need to extract the public key as an `*x509.Certificate` from a `*shared.CertInfo`. This PR adds a convenience function to avoid duplication. See https://github.com/canonical/lxd-cloud/pull/107#discussion_r857949374.

shared/cert: Adds method for returning the public key as an x509 cert.

---

lxd/db/cluster/certificates.mapper.go
lxd/db/cluster/projects.mapper.go
lxd/db/generate/db/method_v2.go

Similar to #10317, this change returns an `api.StatusError` with `http.StatusNotFound` if zero rows are affected when executing a delete statement on an entity.

DB: Error status not found if "delete one" affects zero rows.

---

go.mod
go.sum

For compatibility with https://github.com/canonical/dqlite/pull/366

gomod: Update github.com/canonical/go-dqlite to v1.11.1

---

lxd/resources/gpu.go
lxd/resources/utils.go

With multi-port USB GPUs, it is possible to have a nested device path
with the top-level device just referring to an instance of the USB GPU.
Fixes: https://bugs.launchpad.net/maas/+bug/1970435

lxd/resources: Handle nested devices

---

lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go

By passing the previously loaded device's config into the `deviceRemove()` function (which previously ran validation again) during revert was failing to remove some NICs due to the internal device config being modified such that it would not pass validation.
```
ERROR  [2022-04-27T16:37:20+01:00] Device remove validation failed               device=eth0 err="Cannot use \"parent\" property in conjunction with \"network\" property" instance=v2 instanceType=virtual-machine project=default type=nic
```
Instead avoid running validation again during revert and just pass the already loaded device to `deviceRemove()`.

Instance: Fix NIC removal failure on revert

---

lxd/storage/drivers/driver_btrfs_volumes.go
test/suites/migration.sh

- lxd/storage/drivers/btrfs: Delete volume after receiving new one
- lxd/storage/drivers/btrfs: Check length of snapshots slice
Fixes #10186

Fix BTRFS optimized refresh 

---

doc/metrics.md

Document the problem reported in https://discuss.linuxcontainers.org/t/prometheus-when-using-cluster/13898/

doc: mention that ECDSA cert generation requires openssl 1.1.0+

---

client/interfaces.go
lxd/daemon_images.go
lxd/operations/operations.go
shared/cancel/canceller.go
shared/cancel/http.go
shared/util.go

When a resource such as a database must advertise when it becomes ready, we can use a cancellable `context.Context`. This is useful because subsequent calls to the associated `CancelFunc` will not cause the goroutine to panic (whereas calling `close()` on a channel will). However this means that the resource must keep a reference to both the cancellable context and it's `CancelFunc` which is less desirable.
This change adds a simple wrapper to a cancellable context such that it can be used like:
```golang
canceller := cancel.New(ctx)
defer canceller.Close()
```
Additionally, the existing canceller was renamed and moved to `shared/cancel/http.go`.
Based on chat here https://github.com/canonical/lxd-cloud/pull/114#discussion_r860759810

Adds simple wrapper for a cancellable context

---

lxd/storage/drivers/driver_btrfs_volumes.go
lxd/storage/drivers/driver_ceph_volumes.go
lxd/storage/drivers/driver_cephfs_volumes.go
lxd/storage/drivers/driver_common.go
lxd/storage/drivers/driver_dir_volumes.go
lxd/storage/drivers/driver_lvm_volumes.go
lxd/storage/drivers/driver_zfs_volumes.go
lxd/storage/utils.go

This PR moves the unsafe resizing mode logic into each driver rather than do it in common.
This allows non-thin LVM pools to use unsafe resizing mode for normal volumes as well as image volumes, as they don't use cached image volumes.
Fixes #10343 
Tested on: Dir, BTRFS, ZFS, LVM, LVM thin

Storage: Fix unpacking image larger than default volume size for non-thin LVM pools

---

lxd/seccomp/seccomp.go
lxd/seccomp/sysinfo.go
lxd/seccomp/sysinfo_32.go
lxd/seccomp/sysinfo_64.go

lxd/secommp: Fix sysinfo syscall interception on 32 bit platforms

---

client/util.go
lxd/cluster/tls.go
lxd/main_shutdown.go
lxd/util/http.go
lxd/vsock/vsock.go
shared/cert.go

Recently during an instability/outage in the LXC hosting infrastructure I noticed that the image download attempt that was being made hung for several minutes.
This sounds similar to the issue reported here https://github.com/lxc/lxd/issues/10279
This lead me to notice that several of the HTTP clients we use do not include any timeouts beyond establishing the initial TCP/Unix connection.
This is an attempt to introduce some (I hope) sensible defaults.

Client: Add some default timeouts

---

lxd/certificates.go

This checks the supplied token/password for trusted admins as well. In
the past this was not done which would return a misleading error
("Invalid certificate type") when trying to add a client certificate
twice.
This fixes #10350.

lxd/certificates: Check token for trusted admins

---

shared/network.go

In some error cases, Read() would return -1 as its first value. This is
problematic as io.ReadAll() uses this first return value before
checking the error:
```go
func ReadAll(r Reader) ([]byte, error) {
b := make([]byte, 0, 512)
for {
if len(b) == cap(b) {
// Add more capacity (let append pick how much).
b = append(b, 0)[:len(b)]
}
n, err := r.Read(b[len(b):cap(b)])
b = b[:len(b)+n]
if err == EOF {
err = nil
}
return b, err
}
}
}
```
If `len(b)` equals 0, and `n` equals `-1`, it will panic with
panic: runtime error: slice bounds out of range [:-1]
This commit changes the return value to always be 0 in case of an error.

shared/network: Always return 0 on error

---

lxd/instance_backup.go
lxd/instance_console.go
lxd/instance_delete.go
lxd/instance_exec.go
lxd/instance_file.go
lxd/instance_get.go
lxd/instance_logs.go
lxd/instance_metadata.go
lxd/instance_patch.go
lxd/instance_post.go
lxd/instance_put.go
lxd/instance_sftp.go
lxd/instance_snapshot.go
lxd/instance_state.go

lxd: Prevent use of instance/snapshot name in instance specific routes

---

doc/howto/network_ovn_setup.md

Update the existing documentation for setting up a standalone OVN
network to be clearer.
Add the instructions for setting up a LXD cluster on OVN from the
video tutorial.

doc: rework doc for setting up OVN

---

lxd/certificates.go

After our latest cleanup of the access logic to the certificates API, we
mistakenly would reject any request from a trusted user which doesn't
provide a certificate, this blocked the generation of tokens.
Closes #10374

lxd/certificates: Fix token request validation

---

lxd/request/const.go

[staticcheck SA1029](https://staticcheck.io/docs/checks#SA1029) requires that context be of a non built-in type to avoid collisions. The CtxKey type must be exported for use with lxd-cloud.
See https://github.com/canonical/lxd-cloud/pull/125 for more details.

lxd/request: Export CtxKey type and use for all keys.

---

lxd/daemon.go

lxd/daemon: Fix LXD crash is failing to start due to already running LXD process

---

lxd/storage/backend_lxd.go
lxd/storage/drivers/driver_btrfs_volumes.go
lxd/storage/drivers/driver_ceph_volumes.go
lxd/storage/drivers/driver_cephfs_volumes.go
lxd/storage/drivers/driver_dir_volumes.go
lxd/storage/drivers/driver_lvm_volumes.go
lxd/storage/drivers/driver_mock.go
lxd/storage/drivers/driver_zfs_volumes.go
lxd/storage/drivers/interface.go
lxd/storage/drivers/volume.go

Brings `MountVolumeSnapshot` inline with `MountVolume`.
Tested with VM daily scripts too (except ceph).

Storage: Adds ref counting to volume snapshot mount/unmount

---

lxd/network/driver_ovn.go
lxd/network/openvswitch/ovn.go

This ensures the `ovn-nbctl` command doesn't return until changes are in the OVN southbound database.
This seems to help with reliability of OVN on Ubuntu Jammy and avoid a bug in OVN where `ovn-controller` spins at 100% CPU after deleting a network sometimes.
This is no bad thing for consistency also.

Network: Pass --wait=sb when using ovn-nbctl for OVN networks

---

lxd/daemon_integration_test.go
lxd/response/swagger.go
test/suites/static_analysis.sh

First of many PRs addressing #10392. This one fixes linting for one of the enabled by default linters - deadcode.

golangci-lint github action: deadcode

---

lxd/resources/pci.go

lxd/resources: Handle unreadable VPD

---

lxd-agent/devlxd.go

lxd-agent/devlxd: Don't expand format strings

---

lxd/instance/drivers/driver_qemu.go

Setting the conf option will make the rbd driver apply the config.

lxd/instance/drivers/qemu: Set conf option in rbd driver

---

lxd/api_internal.go
lxd/api_internal_recover.go
lxd/backup.go
lxd/backup/backup_config_utils.go
lxd/backup/backup_info.go
lxd/backup/config/backup_config.go
lxd/instance/instance_utils.go
lxd/migrate_storage_volumes.go
lxd/storage/backend_lxd.go
lxd/storage/backend_mock.go
lxd/storage/pool_interface.go

This will allow us to generate a migration index header containing the same config used for backups.
Also includes a change to include the backup config in the backup `index.yaml` file to allow the unpack process full access to config to rebuild storage volumes (even for optimized backups) in the future.

Storage: Separate generation of backup config struct from writing it

---

lxd/db/cluster/certificates.mapper.go
lxd/db/cluster/profiles.mapper.go
lxd/db/cluster/projects.mapper.go
lxd/db/generate/db/method.go
lxd/db/generate/db/method_v2.go
lxd/db/instances.mapper.go
lxd/db/profiles.mapper.go
lxd/db/snapshots.mapper.go
lxd/db/warnings.mapper.go

Updates `lxd-generate` to explicitly ignore a `rows.Close()` error on a deferred execution and regenerates database functions. This is required for #10428 as these files shouldn't be changed manually.

lxd-generate: Appease errcheck linter in generated files

---

lxd/db/generate/db/stmt.go

All Create statements were using the hardcoded `name` as the primary key when joining another table. This PR changes this value to the table and primary key specified in the field's tag value: `db:join=certificates.fingerprint`

Generator: Use join tag for Create stmt primary key

---

doc/howto/network_ovn_setup.md

docs: Typo in ovn docs

---

lxd/instance_post.go
lxd/instance_snapshot.go
lxd/migrate.go
lxd/migrate_instance.go

Running `lxc copy c1 remote:c1 --stateless --allow-inconsistent` is currently causing the source container c1 to freeze. This change ensures that the container is not frozen for either `lxc copy c1 remote:c1 --allow-inconsistent` or `lxc copy remote:c1 c1 --allow-inconsistent`. 
Closes #10091

Instance: Stop source instance from freezing when using --allow-inconsistent

---

lxd/storage/backend_lxd.go
test/suites/migration.sh

Although this doesn't fix the issue for ZFS storage pools as due to an [optimized refresh bug](https://github.com/lxc/lxd/issues/10186) it hangs.
This PR is separate from https://github.com/lxc/lxd/pull/10423 to prove to myself that it didn't introduce the ZFS hanging issue during custom volume refresh.

Storage: Fix custom volume refresh if volume doesn't exist in target

---

lxd/instance_post.go
lxd/storage/backend_lxd.go
lxd/storage/drivers/driver_btrfs_volumes.go
lxd/storage/drivers/driver_ceph_volumes.go
lxd/storage/drivers/driver_cephfs_volumes.go
lxd/storage/drivers/driver_dir_volumes.go
lxd/storage/drivers/driver_lvm_volumes.go
lxd/storage/drivers/driver_mock.go
lxd/storage/drivers/driver_zfs_volumes.go
lxd/storage/drivers/generic_vfs.go
lxd/storage/drivers/interface.go

While investigating #10091 I found that local copies using rsync (e.g. between pools or projects) did not allow for inconsistent copies. This change checks for the exit status of rsync on a local copy and returns nil if allowInconsistent is set. This required passing the allowInconsistent argument through the driver and pool interfaces.

Bugfix: allow inconsistent copy for pool and project migrations

---

lxd/storage/backend_lxd.go
lxd/storage/drivers/driver_btrfs_volumes.go
lxd/storage/drivers/driver_ceph_volumes.go
lxd/storage/drivers/driver_cephfs_volumes.go
lxd/storage/drivers/driver_dir_volumes.go
lxd/storage/drivers/driver_lvm_volumes.go
lxd/storage/drivers/driver_mock.go
lxd/storage/drivers/driver_zfs_volumes.go
lxd/storage/drivers/interface.go

Drivers that use rsync for a local copy had the default value of `allowInconsistent` set to false when called vie `RefreshVolume`. See https://github.com/lxc/lxd/pull/10443#issuecomment-1134569526.

Allow inconsistent not working with refresh on the same storage pool.

---

lxd/bgp/server.go

Set multihop to the maximum (255) so LXD can be used with a router that
isn't directly connected.
Closes #10440

lxd/bgp: Enable multihop

---

lxd/instance/drivers/driver_qemu.go
lxd/instance/drivers/driver_qemu_config_test.go
lxd/instance/drivers/driver_qemu_templates.go

I'm proposing a refactor of all code which generates qemu config by moving from `text/template` into a set of functions which build an in-memory structure which represents the config, along with another function which transforms the structure into the final config string. This PR contains a POC for the qemuBase section.
While end goal is to move away from configs into QMP,  this is currently depending on external factors such as extra functionality being implemented in qemu upstream. Meanwhile I think this refactoring will bring the following advantages:
- Remove logic from template strings. There are many if/else/range  blocks inside template strings, which can be hard to maintain.
- Reuse config generation logic. Many templates are similar and  currently have repeated code. Devices for …

Instance: Refactor config generation (qemuBase)

---

lxd/apparmor/archive.go

It was recently reported that the Ubuntu official images now require
mknod during unpack which wasn't previously allowed.
Closes #10449

lxd/apparmor: Add mknod cap to archive

---

lxd/instance/drivers/driver_qemu_templates.go

Follow up to #10445 that fixes the variable names for `golint`
@tomponline

lxd/instance/qemu: Fix some variable names to match code style

---

lxd/db/snapshots.go
lxd/db/snapshots.mapper.go
lxd/db/storage_volume_snapshots.go
lxd/instance.go
lxd/storage_volumes_snapshot.go

This reworks the database aspect of snapshot expiry checking to reduce the minutely check down to a single DB query.

Optimize snapshot expiry

---

lxd-agent/events.go
lxd/devlxd.go
lxd/events.go
lxd/events/common.go
lxd/events/connections.go
lxd/events/devlxdEvents.go
lxd/events/events.go
test/deps/devlxd-client.go
test/suites/devlxd.sh

This adds http streaming support to the `/1.0/events` endpoint of devlxd. Clients can be notified about events without having to use websockets.

cloud-init notification API

---

lxd/api.go
lxd/api_1.0.go
lxd/api_cluster.go
lxd/api_metrics.go
lxd/backup.go
lxd/certificates.go
lxd/cluster/config/config.go
lxd/cluster/config/config_test.go
lxd/cluster/heartbeat_test.go
lxd/cluster/membership.go
lxd/cluster/membership_test.go
lxd/daemon.go
lxd/daemon_config.go
lxd/daemon_images.go
lxd/device/device_common.go
lxd/device/nic_ovn.go
lxd/images.go
lxd/instance/drivers/driver_common.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/instance_post.go
lxd/instances_post.go
lxd/network/openvswitch/ovn.go
lxd/state/state.go
lxd/state/testing.go
lxd/storage_volumes_snapshot.go
lxd/sys/os.go

This branch is meant to significantly reduce the number of needless DB queries that we're currently performing.
This is achieved partly by storing the global config in memory rather than fetching it several times per request as well as ensuring that a simple `GET /1.0` as done with just about every single CLI call doesn't hit the database at all.
Unfortunately this doesn't quite fix the performance issues we found during NorthSec, but it's a good initial step.

Database performance fixes

---

lxd/resources/network_ethtool.go

lxd/resources: Handle ethtool not supported

---

lxd/instance/drivers/driver_qemu.go
lxd/instance/drivers/driver_qemu_bus.go
lxd/instance/drivers/driver_qemu_config_test.go
lxd/instance/drivers/driver_qemu_templates.go

This is a follow up to #10445 which converts more templates to the style used in that PR.
I've used the same commit structure as #10445. For each template:
- The first commit implements the *Sections equivalent function + tests
- The second commit replaces the template.
There are a lot of changes here and if required I can split into multiple PRs, but it should be easy if each commit is reviewed individually.

Instance: Convert more qemu config templates

---

.sphinx/_extra/versions.json

Stable is 4.0.x and 5.0.x, not 4.x and 5.x.

doc: fix version numbers in the version switcher

---

lxd/events/common.go
lxd/events/devlxdEvents.go
lxd/events/events.go

This is happening since https://github.com/lxc/lxd/pull/10428 and was generating lots of noise in the logs.
Noticed whilst working on https://github.com/lxc/lxd/pull/10471

Events: Remove frequent `Failed closing listener connection` error

---

client/operations.go
lxd/backup.go
lxd/db/node.go
lxd/images.go
lxd/instance.go
lxd/instance_instance_types.go
lxd/logging.go
lxd/migrate_instance.go
lxd/operations.go
lxd/operations/linux.go
lxd/operations/notlinux.go
lxd/operations/operations.go
lxd/operations/response.go
lxd/state/notlinux.go
lxd/storage_volumes_snapshot.go
lxd/warnings.go

This PR started because I noticed the image prune and image update tasks were running concurrently and interfering with each other's image delete process when I started LXD for the first time after being away for a week. Whilst this PR doesn't fix that particular issue, it works towards the fix by cleaning up the interface to the `Operation` type to provide clearer state management.
- Renames `Run` to `Start` to avoid implying it returns after the operation has run (and finished).
- Removes unused finished channel returned from `Start` function (should use `Wait` instead).
- Renames `Wait` to `WaitFinal` and updates to accept a context. 
- Fixes races on internal status property.

Operations: Fixes race conditions on status propery and improves some function names

---

lxd/storage/backend_lxd.go

Let migration controller handle doing that so that errors are properly propagated.
Related to https://github.com/lxc/lxd/issues/10479

Storage: Don't close migration socket on error

---

lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/operationlock/operationlock.go
lxd/storage/drivers/driver_zfs_volumes.go

And increase ZFS volume deactivation retry timeout (allowed by the increased timeout for the unmount operation) to allow the host more time to flush the data back to the storage layer.
Fixes #10483

Instance: Allow 5 minutes for the root disk unmount process

---

doc/reference/storage_btrfs.md
doc/reference/storage_ceph.md
doc/reference/storage_cephfs.md
doc/reference/storage_dir.md
doc/reference/storage_lvm.md
doc/reference/storage_zfs.md

As a quick fix, give both the name and the driver "ID" to specify
when creating the driver in the title.
We can clarify more when cleaning up the driver documentation.

doc: storage: Clarify driver names

---

lxd/backup.go
lxd/images.go
lxd/instance.go
lxd/instance_instance_types.go
lxd/logging.go
lxd/operations.go
lxd/operations/operations.go
lxd/storage_volumes_snapshot.go
lxd/warnings.go

Introduces a lock to prevent image related background tasks from running concurrently with each other and potentially stepping on each other's toes by operating on the same image concurrently.
Also ensures other background tasks wait for the invocation to finish before the scheduler can run it again to avoid concurrent invocations of the same task.

Operations: Prevent image related background tasks from running concurrently and stepping on each other

---

doc/explanation/storage.md
doc/howto/storage_add_volume.md

Only filesystem storage volumes can be shared.

doc: storage: clarification about sharing of storage volumes

---

.github/workflows/builds.yml
.github/workflows/commits.yml
.github/workflows/triage.yml

Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: nathannaveen <42319948+nathannaveen@users.noreply.github.com>

chore: Set permissions for GitHub actions

---

lxd/patches.go
lxd/storage/backend_lxd.go
lxd/storage/backend_lxd_patches.go
lxd/storage/drivers/driver_btrfs.go
lxd/storage/drivers/driver_ceph.go
lxd/storage/drivers/driver_cephfs.go
lxd/storage/drivers/driver_dir.go
lxd/storage/drivers/driver_lvm.go
lxd/storage/drivers/driver_zfs.go
lxd/storage/pool_load.go
lxd/storage/utils.go
test/main.sh
test/suites/snapshots.sh

Fixes https://github.com/lxc/lxd/issues/10501
This patch detects missing instance volume snapshot DB records and recreates them using the parent volume's config.
Tested using:
```
lxc init images:ubuntu/jammy c1
lxc snapshot c1
lxc snapshot c1
lxd sql global 'delete from storage_volumes_snapshots where id IN(n,n)' # Using volume snapshot record IDs
lxc start c1
Error: Instance snapshot record count doesn't match instance snapshot volume record count
lxd shutdown
lxc storage volume ls <pool>
+----------------------+------------------------------------------------------------------+---------------+--------------+---------+
|         TYPE         |                               NAME                               |  DESCRIPTION  | CONTENT-TYPE | USED BY | …
```

Storage: Restore missing instance volume snapshot DB records

---

lxd/api_cluster.go
lxd/api_internal.go
lxd/api_internal_recover.go
lxd/device/config/device_runconfig.go
lxd/device/device_utils_disk.go
lxd/device/disk.go
lxd/device/nic_bridged.go
lxd/device/nic_ovn.go
lxd/init.go
lxd/instance.go
lxd/instance/drivers/driver_common.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/drivers/load.go
lxd/instance/instance_utils.go
lxd/instance_test.go
lxd/instances_post.go
lxd/migrate_instance.go
lxd/network/acl/acl_ovn.go
lxd/network/acl/driver_common.go
lxd/network/driver_ovn.go
lxd/snapshot_common_test.go
lxd/storage/drivers/driver_btrfs_volumes.go
lxd/storage/drivers/driver_dir_utils.go
lxd/storage/drivers/driver_zfs_volumes.go
lxd/storage/drivers/generic_vfs.go

By returning a `revert.Hook` rather than accepting a `*revert.Revert` argument it is clearer who is responsible for the eventual cleanup when an error occurs (the called function itself if an error occurs internally or the caller of the functions if an error after the function has finished) and it aligns better with the wider use of `defer` or `revert.Fail()` patterns in the code base.
Its also clearer to return a `revert.Hook` which indicates the function is for revert cleanup, rather than returning a `func()` which is unclear that the returned function is for.
Also in places where we were returning a `*revert.Reverter`, we now return a `revert.Hook` for consistency.
Also fixes a couple of places where the call to `revert.Success()` was incorrectly deferred.

LXD: Move away from accepting revert.Reverter as an argument and instead return revert.Hook for cleanup

---

lxd/certificates.go

lxd/certificates: Require an address for token issuance

---

lxd/instance/drivers/driver_qemu_config_test.go
lxd/instance/drivers/driver_qemu_templates.go

lxd/instance/qemu: Drop bootIndex from PCI

---

doc/api-extensions.md
doc/instances.md
lxd/instance/drivers/driver_qemu.go
lxd/instance/drivers/driver_qemu_config_override.go
lxd/instance/drivers/driver_qemu_config_test.go
scripts/bash/lxd-client
shared/instance.go
shared/version/api.go

This is my new attempt to implement a method for customizing the generated `qemu.conf` for VM instances. In my first PR (#9321) my goal was to modify the templates explicitly for every new config key/section that the user would have access to (that PR only the GPU driver could be modified).
The new approach is much more flexible while being less obtrusive (only one line is added to call the new function which handles overriding), and is made possible by the recent refactoring in how `qemu.conf` is generated. The goal here is to implement a mini DSL that allows users to have granular control over the generated `qemu.conf` for a VM instance using lxd config keys.
The new `qemuRawCfgOverride` function takes a `[]cfgSection` slice plus an expandedConfig map, and returns a new `[]cfgSection` …

New `raw.qemu.conf` config option

---

lxd/db/cluster/certificate_projects.interface.mapper.go
lxd/db/cluster/certificate_projects.mapper.go
lxd/db/cluster/devices.interface.mapper.go
lxd/db/cluster/devices.mapper.go
lxd/db/cluster/profiles.interface.mapper.go
lxd/db/cluster/profiles.mapper.go
lxd/db/cluster/projects.interface.mapper.go
lxd/db/cluster/projects.mapper.go
lxd/db/generate/db/method_v2.go
lxd/db/instances_test.go
lxd/profiles.go

To keep this in line with how we handle `Config` fields for entities (Instances, Profiles, etc), this updates the generator to expect a `map[string]cluster.Device` for generated database CRUD functions.

Generator: Handle Devices as a collection

---

lxd/cgroup/abstraction.go
lxd/seccomp/seccomp.go
lxd/sys/os.go
shared/util_linux.go

This aligns the boot time info in sysinfo with the logic we're using to generate /proc/uptime inside of LXCFS.
To do this without too much overhead, I'm also extending the sys package to give us the host system boot time through the OS struct.
Finally, when testing this logic on a cgroup2 system with swap accounting enabled, I noticed that our swap logic in cgroup2 would fail when the limit would be returned as `max`. So I re-shuffled our meminfo parsing logic a tiny bit and now have the cgroup2 parser return the host total swap when the swap limit is reported as `max` by the kernel.

Fix sysinfo boottime

---

lxd/db/images.go
lxd/profiles_utils.go

GetProfilesIfEnabled can return an empty slice with no error, so it's
not safe to check the first index without checking if the slice is
empty.

lxd/profiles/utils: Add missing profiles slice check

---

lxd/instance/drivers/driver_common.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go

Before adding more complexity to the instance device lifecycle logic related to https://github.com/lxc/lxd/issues/10114 I thought I would first move the duplicated logic into the common driver so that the future changes can be done in one place (or at least fewer places).

Instance: Move most of device lifecycle logic into common driver

---

lxd/daemon.go
lxd/dns/handler.go
lxd/dns/server.go
lxd/network/zone/interface.go
lxd/network/zone/zone.go

This change adds support for quickly returning a valid SOA request.
This is used by modern named/bind9 prior to any AXFR/IXFR attempt.
Additionally, also accept IXFR requests and just return AXFR data.
This is apparently much better handled than just rejecting IXFR requests.

lxd/dns: Add support for SOA (and accept IXFR)

---

lxd/device/nic_bridged.go
lxd/instance/drivers/driver_common.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
test/suites/container_devices_nic_bridged.sh

This allows the instance copy (or restored instance snapshot) operation to complete if there are device conflicts (such as NIC address conflicts with another instance's NIC), so they can be manually fixed before the instances can be started.
Builds on the work of @Viktor-Yakovchuk in https://github.com/lxc/lxd/pull/10363
The key difference between the original idea to fix this issue and this PR is that we do not remove the device `Add()` step.
Because removing this step would mean that NIC devices would not be able to reserve their static IPs via a static DHCP reservation at add time.
Instead this PR will optimistically try and reserve static IPs as DHCP leases, but if the config is conflicting with an existing instance, then it will skip the reservation.
In the end we didn't need the …

Device: Allow copying and snapshot restoring instance snapshots that results in device confict

---

lxd/migrate_instance.go

This was missed in https://github.com/lxc/lxd/commit/3f4fbf60ef249bad5e88d70f9d441f9a5d206dfb to actually use the negotiated version on the target side.
This allows migration between LXD 4.0.x and LXD current.
Otherwise get an error like:
```
lxc copy c1 v2: --refresh 
Error: Failed instance creation: Error transferring instance data: Failed creating instance on target: Failed decoding migration index header: invalid character '\x00' looking for beginning of value
```

Instance: Use the negotiated index migration header version on target

---

lxd/device/nic_bridged.go
lxd/dnsmasq/dnsmasq.go
lxd/instance/drivers/driver_common.go
test/suites/container_devices_nic_bridged.sh

This ensures that if we are applying invalid device config to the database that we don't leave the existing device on the system out-of-sync with the config in the database. 
Once the device has had its config fixed its system state will be re-applied when next started.
Also fixes scenario where an instance can be started but is missing its static DHCP lease file.
This can happen if the instance device was conflicting with another instance NIC device when it was created, and then subsequently the original instance device was removed meaning the new NIC no longer conflicts, so can be started without further config modification, in which case the static DHCP lease file would previously never had a chance to be created, and DHCP would not have worked correctly.
Follows on from …

Instance: Stop and remove device after non-user requested update validation fails

---

lxc/storage.go

This fixes #10578 where the storage pool would be listed when calling
`lxc storage info <pool>`. Instead of listing the storage pool, the
storage volumes need to be shown.

lxc: List volumes under used-by

---

doc/reference/storage_zfs.md

The proper name for `refquota` config key is `use_refquota` not `zfs_refquota`.

doc: Rename refquota config key name for use_refquota

---

doc/howto/storage_add_volume.md
doc/instances.md
doc/reference/storage_drivers.md

Clean up the section about configuring I/O limits, move it to the how-to, and link to it from the instances page.

doc: storage: I/O limits

---

lxc/cluster_group.go
lxc/network_peer.go
lxd-user/main_daemon.go
lxd/api_cluster_test.go
lxd/daemon.go
lxd/events/common.go
lxd/response/swagger.go
lxd/storage/drivers/driver_btrfs_utils.go
test/suites/static_analysis.sh

Fixes lint errors for the remaining default linters used by `golangci-lint` in preparation for #10392.

Fixes structcheck, typecheck, unused, varcheck lint errors

---

lxd/vsock/vsock.go

The problem was that the vsock HTTP client was using Dial instead of DialContext in it's `http.Transport`. I think `staticcheck` checks for deprecated function calls, but not for assignments to deprecated fields. I've searched the codebase for any other assignment to `transport.Dial` but can't find any so there shouldn't be any more issues :crossed_fingers: .
Closes #10596.

lxd-agent exec bug

---

lxd/migrate_instance.go
lxd/migrate_storage_volumes.go
lxd/migration/migration_volumes.go

- lxd: Add refresh arg to MatchTypes
- lxd/migration: Handle optimized refresh for older versions

Fix migration between LXD 4.0 and LXD 5.0

---

lxd/db/generate/lex/case.go

Usage of `cases.Title(language.English).String(str)` is subtely different
from `strings.Title`. For example, `strings.Title("UUID")` returns `"UUID"`,
whereas `cases.Title(language.English).String("UUID")` returns `"Uuid"`.
This is breaking the generated database code.
Signed-off-by: Mark Laing <mark.laing@canonical.com>

lxd-generate: Revert to deprecated strings.Title.

---

doc/howto/storage_move.md

The described way works only for custom storage volumes.
Instance storage volumes can be moved by moving the
corresponding instance.

doc: storage: clarify moving of storage volumes

---

.sphinx/_extra/versions.json
.sphinx/_static/version-switcher.js

The version switcher relies on the URL and assumes that the
current version is under "master". We've since added a link
that makes the current version available as "latest" as well.
Therefore, update the script to use "latest" by default and
replace "master" with "latest" if it is used.
This is a bit tricky to test locally, but I *think* it should work.
Basically, it should make the version dropdown show up for 
https://linuxcontainers.org/lxd/docs/latest/ as well, where the
dropdown is currently on an empty string.

doc: fix version switcher to work for latest

---

lxd/network/openvswitch/ovn.go

lxd/network/openvswitch: Use %s so that delimiting quotes are not escaped.

---

shared/subprocess/manager.go

Coming from https://discuss.linuxcontainers.org/t/lxd-refuses-to-start-after-arch-os-upgrade-complains-about-yaml-issue/14457

Subprocess: Improve errors in ImportProcess

---

doc/howto/storage_add_volume.md
doc/howto/storage_backup.md
doc/howto/storage_configure.md
doc/howto/storage_list.md

You cannot do the same things with an instance volume as you
can with custom volumes.

doc: storage: clarify that most docs are about custom volumes

---

lxd/instance/drivers/driver_lxc.go

Reported from https://discuss.linuxcontainers.org/t/failed-to-set-lxc-config-lxc-apparmor-profile-unconfined/14468

lxd/instance/lxc: Don't fail on missing apparmor

---

.github/workflows/tests.yml

This PR removes unit tests from the static analysis job in github actions, which has been failing since #10617. 
This is still an ideal place to include unit tests however, so they will be reinstated once we understand why they are failing.

workflows: Removes unit tests and reinstates ubuntu client tests.

---

lxd/db/generate/lex/case.go

Using the cases.NoLower option preserves behaviour to that of
strings.Title.
See https://github.com/lxc/lxd/pull/10598#issuecomment-1167941855

lxd/db/generate/lex: Use cases.Title instead of deprecated strings.Title

---

lxd/db/cluster/config.mapper.go
lxd/db/cluster/devices.mapper.go
lxd/db/cluster/instances.mapper.go
lxd/db/cluster/profiles.mapper.go
lxd/db/cluster/snapshots.mapper.go
lxd/db/generate/db/method_v2.go

While investigating the issue over [here](https://discuss.linuxcontainers.org/t/database-error-sql-transaction-has-already-been-committed-or-rolled-back/14464), I noticed the `GetConfig` error messages weren't informative of which `<parent>_config` table is actually having problems. Then I noticed that in `UpdateConfig`, the error from `CreateConfig` was only checked once for the whole config, instead of per call.
So this adds the actual table name to the error message for `GetConfig`, and properly checks the error from `CreateConfig`. 
Additionally adds some new-lines via `buf.N()` to make the code look a bit more readable/consistent.

Generator: Fix config table error handling.

---

.github/workflows/tests.yml

We should not update the go mod as part of the static analysis workflow because updated dependencies are not committed to the codebase and could cause the static analysis to fail.
Closes #10630.

workflows/static-analysis: Download but do not update dependencies.

---

test/suites/container_devices_disk.sh

LXD 5.3 had an issue passing some host paths as `disk` devices into containers that were working in LXD 5.2 and earlier.
These devices could be hot-plugged into a running container, but could not be present on container start otherwise it would fail to start with an error like this in the `lxc info --show-log <instance>` output similar to:
```
ERROR conf - …/src/src/lxc/conf.c:mount_entry:2459 - Operation not permitted - Failed to mount “/var/snap/lxd/common/lxd/devices/web/disk.X0.tmp-.X11–unix-X0” on “/var/snap/lxd/common/lxc//tmp/.X11-unix/X0”
```
This caused quite a bit of disruption:
- https://github.com/lxc/lxc/issues/4160
- https://github.com/lxc/lxc/issues/4162
- https://discuss.linuxcontainers.org/t/cant-mount-external-xfs-device-mountpoint-in-container/14510
- …

Test: Add tests for passing unix character devices as disks into a container

---

lxd/resources/pci_vpd.go

lxd/resources: Handle invalid VPD lengths

---

lxd/instance/drivers/driver_qemu_config_test.go
lxd/instance/drivers/driver_qemu_templates.go

Fix the issue reported in LXD forum: https://discuss.linuxcontainers.org/t/launching-vms-without-cpu-limit/14545/7
Signed-off-by: Thiago Padilha <thiago@padilha.cc>

lxd/instance/qemu: Fix qemuCPU template broken numa section

---

lxd-benchmark/main.go
lxd/db/cluster/projects.go
lxd/db/instances.go
lxd/db/instances_test.go
lxd/device/disk.go
lxd/device/nic_bridged.go
lxd/network/acl/acl_load.go
lxd/network/driver_bridge.go
lxd/network/driver_ovn.go
lxd/network/network_utils.go
lxd/network/network_utils_sriov.go
lxd/patches.go
lxd/storage/backend_lxd.go
lxd/storage/backend_lxd_patches.go
lxd/storage/utils.go
lxd/storage_volumes.go
lxd/storage_volumes_utils.go

This PR fixes the instance list speed regression introduced by https://github.com/lxc/lxd/commit/fe37c21bae5ab70f65a7e6639de5c759588fb339 and goes further to optimise the query pattern than was in LXD 5.2.
The main problem was that the `InstanceToArgs` function loads the profile(s) (and its config and devices) for every instance, even if multiple instances use the same profile(s). Additionally the `GetDevices()` and `GetConfig()` prepare a statement on every call, which is inefficient.
This PR updates `InstanceList()` to use its own optimised queries.
On LXD 5.2 (before that commit), my test box could create 128 `images:ubuntu/jammy` containers on ZFS (with pre-warmed image volume) in: **1m27.566s, 1m28.397s, 1m28.810s**
On LXD 5.3 (after that commit), the results are as follows: …

DB: Optimise query pattern for InstanceList

---

lxd-agent/main_agent.go
lxd-agent/network.go
lxd/vsock/vsock.go

For some reason our TLS over vsock logic was incredibly broken and we were effectively doing TLS over TLS.
Not only is that a big waste of CPU time, it's also causing some issues when we need to extract client certificates as is the case in #10610.
Unfortunately I couldn't find a way to gracefully fix this, so as soon as a system will receive this fix, the guests will need a reboot to receive a new agent with the corrected logic.

Don't double TLS connections between LXD and agent

---

lxd/instance/drivers/driver_lxc.go
lxd/instance/operationlock/operationlock.go

Instance: Don't wait for update operation to complete when removing disk from running container

---

lxd/db/instances.go
lxd/db/instances_test.go
lxd/device/nic_bridged.go
lxd/network/acl/acl_load.go
lxd/network/driver_bridge.go
lxd/network/driver_ovn.go
lxd/network/network_utils.go
lxd/network/network_utils_sriov.go
lxd/patches.go
lxd/storage/backend_lxd_patches.go
lxd/storage/utils.go

This allowed the introduction of a hard to debug OVN bug because of the way that Go doesn't panic when reading from a nil map.
The particular optimisation wasn't much used, and its potential to introduce subtle bugs in the future means I don't think its worth keeping in its current form.

Instance: Revert InstanceList selective config loading optimisation

---

lxd/networks.go
lxd/storage_pools.go

lxd: Replace use of cluster "node" with "member" in user facing text

---

lxd/db/generate/db/lex.go
lxd/db/generate/db/method.go
lxd/db/generate/db/method_v2.go
lxd/db/generate/db/stmt.go

This adds some small changes/fixes for using `lxd-generate` from outside the lxd project.
* When the `-d` or `--database` flag is passed, the keyword will now properly be used as a package receiver. The actual package path is imported via `goimports`. 
* The above flag will now no longer affect other generated helpers. The generator will assume that any necessary helper is defined within the package from which the generator was called. Instead, the `-d` flag will now only work on the globally defined prepared statement helpers: `Stmt` and `RegisterStmt`. It makes sense to have these be referenced since there should only be one collection of statements prepared when the database first opens.
*  A table name override flag has been added as well: Sometimes the generator just isn't too smart, …

Generator: Fixes for external calling

---

lxd/storage/drivers/driver_ceph.go
scripts/bash/lxd-client

Ceph OSD pools are a logical construct, so there's no good reason not to allocate a new one and because Ceph is by-designed accessible by multiple systems, the likelihood of someone using this to have two or more LXD servers on the same pool is pretty high and will fail quite disastrously (data loss).
Fixes #10659

lxd: Deprecates `ceph.osd.force_reuse` Ceph storage pool setting

---

doc/explanation/storage.md
doc/faq.md
doc/howto/storage_create_pool.md
doc/reference/storage_btrfs.md
doc/reference/storage_drivers.md
doc/reference/storage_lvm.md
doc/reference/storage_zfs.md

Move some details from the FAQ about creating storage to the
storage section and remove the question from the FAQ.

doc/storage: move content from FAQ to storage section

---

client/lxd_images.go
client/simplestreams_images.go
lxd/daemon_images.go

Fixes #10279
This is to avoid LXD holding the image download lock too long when a remote source is not responding in a timely manner.
This can occur when the remote image server is up and running, but is not generating the HTTP header response due to internal I/O issues.

Client: Add 30s HTTP header timeout for image download

---

doc/cloud-init.md

Context
==
I found the current documentation to be very lacking in terms of a clear explanation of how to apply the `user-data` configuration options, and how to confirm that the `cloud-init` process had received the data. It was only through a lot of searching that I found out that `#cloud-config` is actually not just a comment, but actually required for `cloud-init` to even process that set of piped configuration keys.
Approach
==
This change
* Adds a small "how to" for setting up a new profile for testing
* Adds documentation on the pipe syntax that's needed to pipe the configuration to cloud-init
* Adds documentation for the specific syntax required to get `cloud-init.user-data` to work (`#cloud-config`)
* Adds documentation on where to check on the instance to see if the user-data …

doc: Update cloud-init.md with user-data examples

---

doc/authentication.md

If the LXD server is behind NAT, adding a remote using a token
might not work. The user must manually specify the external IP
address of the server.

doc/authentication: add information about a server behind NAT

---

doc/reference/storage_drivers.md

Added as a related link instead of "embedded" video, because the
video isn't illustrating the same content as the page, but presents
additional, related information.

doc/storage: add link to video about benchmarking storage drivers

---

lxd/db/cluster.go
lxd/db/cluster/certificate_projects.mapper.go
lxd/db/cluster/certificates.mapper.go
lxd/db/cluster/images.mapper.go
lxd/db/cluster/instance_profiles.go
lxd/db/cluster/instance_profiles.mapper.go
lxd/db/cluster/instances.mapper.go
lxd/db/cluster/operations.mapper.go
lxd/db/cluster/profiles.mapper.go
lxd/db/cluster/projects.go
lxd/db/cluster/projects.mapper.go
lxd/db/cluster/snapshots.mapper.go
lxd/db/cluster/stmt.go
lxd/db/cluster/warnings.mapper.go
lxd/db/db.go
lxd/db/generate/db/method.go
lxd/db/testing.go
lxd/db/transaction.go
lxd/db/warnings.go

Closes #10183 
With all uses of lxd-generate moved into the cluster package, this PR removes the `stmts` maps from `Cluster` and `ClusterTx` in favour of the global `PreparedStatements` map defined in the cluster package. The refactor of the lxd-generate helpers to facilitate usage from external packages removed the reliance on the `Cluster` and `ClusterTx` structs, so this just consolidates all prepared statements into the map that lxd-generate expects to exist.
And with that, finally we can close that long running issue :)

Remove duplicate prepared statement store

---

lxd/db/cluster.go
lxd/db/images.go
lxd/db/instances.go
lxd/db/network_forwards.go
lxd/db/network_load_balancers.go
lxd/db/transaction.go

There seems to be an issue with Dqlite that returns partial result sets (with no error) if using >255 query parameters.
Fixes #10705
This is safe because the inputs are `int` and not `string` so cannot be used to modify the query in a malicious way.
Tested with 512 containers.
Also : 
- Uses a standard way of generating IN statement argument placeholders and remove `generateInClauseParams`.
- Removes the `prepare()` function as it was being used in an inefficient way.

DB: Don't use query parameters with IN statement when loading instance config in InstanceList

---

lxd/resources/pci_vpd.go

Another case of invalid VPD data (length larger than record) causing the
parser to crash.
Closes #10708

lxd/resources: Fix VPD parser crash

---

doc/howto/storage_create_pool.md

One character fix for a pool name in the ZFS section.
Signed-off-by: Duncan Hill <github.commits@cricalix.net>

docs: Update storage create pool howto

---

lxd/networks.go
lxd/storage_pools.go

Suggested by @stgraber via https://discuss.linuxcontainers.org/t/lxd-object-storage-s3-api/14579/26?u=tomp
This is so a non-admin user will not be able to see the forthcoming `volatile.radosgw.admin.*` credential keys.

API: Only allow admin users to see storage pool and network config

---

lxd/fsmonitor/drivers/errors.go
lxd/storage/backend_lxd.go
lxd/storage/backend_mock.go
lxd/storage/drivers/driver_cephfs_volumes.go
lxd/storage/drivers/driver_common.go
lxd/storage/drivers/errors.go

So that new storage pool drivers have less to implement if they don't offer storage volume support.
Also removes unnecessary `ErrNotImplemented` error left over from when we transitioned a driver at a time to the new storage subsystem.

Storage: Add common volume management "not supported" functions

---

lxc/config.go

Otherwise `lxc config show <instance>/<snapshot> --expanded` would panic.

LXC: Fix expanded show of instance snapshot

---

lxd/storage/drivers/driver_btrfs.go

Attempts to fix the BTRFS "invalid argument" errors when mounting the storage pool.

Storage: Scan pool device source for BTRFS filesystems before mounting

---

lxd/daemon.go

As `instance.LoadNodeAll` was recently changed so that it does return nil slice if no instances found.
This was breaking the opaque logic for shared mount removal which relied on a non-nil response from `instance.LoadNodeall`, so this makes it more obvious.

Daemon: Add explicit instancesLoaded bool to indicate if shared mounts can be cleaned up

---

client/util.go

Fixes regression caused by 9cda9c2135601e223a462f2fbd8a4e0f8dc0e017
Fixes #10734

Client: Set transport.DialTLSContext in tlsHTTPClient

---

lxd/db/network_load_balancers.go

Introduced with df55120483f11031266ab67c5a35f977813e11db

Network: Fix regression in GetNetworkLoadBalancers

---

lxd/db/storage_volumes.go

Project usedby urls for storage volumes were double encoding forward slashes to be `%252F`.

lxd/db: Fix escaped slashes in storage volume URIs.

---

lxd/storage/drivers/driver_zfs.go

This reduces the amount of write ops associated with read ops and also
aligns ZFS with other file systems supported by LXD.

lxd/storage/drivers/zfs: set atime=off and relatime=on

---

lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/instance_utils.go

This is something I noticed when deleting the instance I used for snapshot listing testing - snapshots are removed in alphabetical order.
So this PR deletes them in reverse creation date order, rather than alphabetically. To avoid any restrictions on deletion order from the underlying storage driver.
And uses the more efficient snapshot loading function `inst.Snapshots()` rather than perform the same queries over and over again for each snapshot.

Instance: Use more efficient snapshot loading query when deleting snapshots

---

lxd/archive/archive.go
lxd/device/device_utils_disk.go
lxd/instance/drivers/driver_lxc.go
lxd/network/network_utils_sriov.go
lxd/network/openvswitch/ovs.go
lxd/rsync/rsync.go
lxd/seccomp/seccomp.go
lxd/storage/drivers/driver_btrfs_utils.go
lxd/storage/drivers/driver_btrfs_volumes.go
lxd/storage/drivers/driver_ceph.go
lxd/storage/drivers/driver_ceph_utils.go
lxd/storage/drivers/driver_common.go
lxd/storage/drivers/driver_lvm_utils.go
lxd/storage/drivers/driver_zfs_volumes.go
lxd/storage/drivers/utils.go
shared/util.go
shared/util_linux.go

- Adds `RunCommandContext` function to allow timeouts.
- Reworks `RunError` to use unexported fields and support the Go >=1.13 error unwrapping by adding an `Unwrap()` function.
- Makes the string message returned from `RunError.Error()` dynamically generated and include the underlying error message.
- Stores a pointer to the stdout and stderror `bytes.Buffer` rather than passing around (potentially) large strings, and makes these accessible via `RunError.StdOut()` and `RunError.StdErr()` function.
- Updates `ExitStatus` to take advantage of `RunError.Unwrap()` by using `errors.As()` (which now means it supports detecting `ExitError` in any wrapped error type not just `RunError`).
I needed this lot in order to run `radosgw-admin` commands with a sensible timeout, as unlike the `ceph` …

lxd: Adds `RunCommandContext` function and updates `RunError` with `Unwrap` function

---

lxd/main_init_interactive.go
lxd/storage/drivers/driver_btrfs.go
lxd/storage/drivers/driver_lvm.go
lxd/storage/drivers/driver_zfs.go
lxd/storage/drivers/utils.go

While watching https://www.youtube.com/watch?v=ysLi_LYAs_M (nice video!), I noticed the loopback file was created as 30GB thus showing as 28GiB with `ls`.

Use SI units for storage

---

lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go

As discussed in https://github.com/canonical/lxd-cloud/issues/136#issuecomment-1209589892 for tracking instance types in upstream servers and listing associated filesystem storage volumes.

Adds instance type to instance-created lifecycle event context.

---

doc/migration.md

This doesn't really fit in the place where the docs currently
are, but the content should be a bit clearer than what we have.
The page will be moved into a migration section in a follow-up
PR.

doc/migration: clean up "live migration" documentation

---

lxd/db/instances.go
lxd/db/storage_volumes.go
lxd/instance/drivers/driver_common.go
lxd/instance/drivers/driver_qemu_config_override.go
lxd/instances_get.go
lxd/project/project.go
lxd/resources/cpu.go
lxd/storage_volumes.go
shared/api/instance.go
shared/api/storage_pool_volume.go

- Makes `/1.0/storage-pools/<pool>/volumes` generate far fewer queries than before - it still loads volume config (even when doing a non-recursive request), but it is much more efficient than before. Previously it was performing a query per-volume-type to get volume names, and then for each volume name loading the volume info (which just for a single volume was doing multiple queries to get ID, description, node and config!).
- Lays the ground work for supporting `all-projects` argument (see https://github.com/lxc/lxd/issues/10753).
- I considered using the DB generator for this, but the query was complicated enough that I couldn't justify it.
- Fixes `/1.0/storage-pools/<pool>/volumes/<volType>/<volName>` effective storage project logic (as previously hard-coded to custom volume type).
- …

Storage: Improve and simplify `/1.0/storage-pools/<pool>/volumes` endpoint

---

doc/containers.md
doc/production-setup.md

Both pages redirect http to https and the CRIU site also has
HSTS with preload.

doc: use HTTPS for links to CRIU site and inotify man

---

doc/api-extensions.md
doc/howto/network_bgp.md
doc/reference/network_bridge.md
doc/reference/network_physical.md
lxd/bgp/debug.go
lxd/bgp/server.go
lxd/network/driver_common.go
shared/version/api.go

Hi,
BGP peer holdtime option configuration with proper documentation
Mine need to have ability to set peer's holdtime on lxd side.
I've already created additional optional configuration node and change complementary code with documentation.
This leads to adding new peer configuration `lxc network set lxdbr0 bgp.peers.foo.holdtime=1`
Сonsider including this option please.

Network: BGP peer holdtime option configuration

---

grafana/LXD.json

Since we only care about the current topk() metrics to display
the piecharts, there is no point in calculating with old data.

grafana: Only use instant queries on piechart graphs

---

lxd/db/cluster/schema.go
lxd/db/cluster/update.go

- I noticed whilst working on the object storage feature that the current `storage_volumes` table's unique index was not guarding against duplicate volumes when using remote storage pools (where the `node_id` field is set to NULL). This is because NULL fields are not considered as part of unique indexes normally. Duplicate volumes should still be impossible due to LXD checking whether an existing volume exists before attempting a `INSERT`, however for consistency with the forthcoming `storage_buckets` table, and to be extra cautious (as doing SELECT then INSERT could be racy) this PR adds an extra unique index that handles NULL `node_id` fields. We have previously added a similar fix for `storage_pools_config`: `CREATE UNIQUE INDEX storage_pools_unique_storage_pool_id_node_id_key ON …

Database: Adds remote storage aware unique index to `storage_volumes`

---

lxd/network/driver_bridge.go

Network: Include error from bridge n.populateAutoConfig

---

lxd/network/openvswitch/ovn.go

Otherwise if the instance name includes upper case characters it won't be resolvable.
Reported from https://discuss.linuxcontainers.org/t/temporary-failure-in-name-resolution-when-pinging-container-with-uppercase-name/14813
Without that `nslookup C1.lxd` fails, whereas once its stored in OVN as lower case `nslookup C1.lxd` succeeds.

Network: Lower case OVN DNS names

---

lxd/db/storage_volumes.go
lxd/storage_pools.go

As discussed here https://github.com/lxc/lxd/pull/10703#discussion_r932217217 do not take requested project into account when deleting image volumes as part of storage pool deletion.

Storage: Don't use project param when deleting image volumes during storage pool deletion

---

doc/reference/storage_ceph.md
doc/reference/storage_cephfs.md

I cannot include the other commit (https://github.com/tomponline/lxd/pull/5/commits/e8821a455ed63114e040f3ee1b5ab4e99c999fd8) here since the file isn't on master yet.

doc/storage/ceph: remove YouTube link from content that is reused

---

Makefile

Makefile: Moves shellcheck version call into static-analysis target.

---

lxd/db/generate/db/method.go

We discovered in https://github.com/canonical/lxd-cloud/pull/151 that when a `Type` field is tagged as a primary key, generation fails with `Error: Can't format generated source code: 7:16: expected operand, found 'type' (and 1 more errors)`. See https://github.com/canonical/lxd-cloud/pull/151#discussion_r947782558.
This occurred because generation of the filter in the `GetOne` method was lowercasing all of the filter fields. This fix applies the same transformation as in the [mapping field args](https://github.com/lxc/lxd/blob/a7563fac60d1588948766ada061607b9571dee2c/lxd/db/generate/db/mapping.go#L188-L191) so that the `Type` field in the filter is set to the value of the `{entity}Type` argument.

lxd-generate: Allow GetOne filter to include a 'type' field.

---

doc/explanation/storage.md
doc/howto/storage_backup_volume.md
doc/howto/storage_configure_pool.md
doc/howto/storage_configure_volume.md
doc/howto/storage_create_instance.md
doc/howto/storage_create_volume.md
doc/howto/storage_move_volume.md
doc/howto/storage_resize_pool.md
doc/howto/storage_resize_volume.md
doc/howto/storage_view_pools.md
doc/howto/storage_view_volumes.md
doc/storage.md

As well as better SEO in the resulting URLs, this makes way for allowing storage bucket howtos whilst keeping the howto structure consistent and not merging multiple concepts into a single howto.

Doc: Separate storage howtos to cover pool and volumes separately

---

doc/api-extensions.md
shared/version/api.go

This adds the API extension missing in #10791

api: metrics_memory_oom_total

---

lxd/network/driver_ovn.go

If an existing Linux native bridge is used as an uplink for OVN, the (managed) uplink interface type is "physical". So it hasn't "bridge.mtu" option, only "mtu" one. But only "bridge.mtu" option of uplink interface is honored by the "startUplinkPortBridgeNative" function. Because of this, the interfaces of the veths pair connecting the uplink and the ovs-system bridges always gets MTU value 1500. When such interface is added to the uplink bridge, the MTU of the uplink bridge is automatically reduced to 1500 even if the physical interface has a higher MTU.

Network: Fixes impossibility to set MTU for a pair of veths connecting OVN uplink and ovs-system bridges

---

lxd/storage/drivers/driver_cephobject.go
lxd/storage/drivers/driver_cephobject_utils.go

Storage: Fix detection of missing lxd-admin radosgw user in cephobject driver

---

doc/requirements.md

LXD depends on dqlite depends on C-raft depends on AIO.
See https://github.com/canonical/raft/issues/228.
Signed-off-by: Cole Miller <m@cole-miller.net>

doc: Note AIO requirement

---

doc/howto/storage_create_pool.md
doc/reference/storage_cephobject.md
lxd/db/cluster/update.go
lxd/storage/drivers/driver_cephobject.go
lxd/storage/drivers/driver_cephobject_buckets.go
test/suites/storage_buckets.sh

Typo began in the spec https://discuss.linuxcontainers.org/t/lxd-object-storage-s3-api/14579 (also now fixed) and was propagated into the code and tests.

Storage: Fix typo in `cephobject.radosgw.endpoint*` settings

---

lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go

This is required for https://github.com/canonical/lxd-cloud/issues/155 so that the cell/region are aware of instance storage pools.

Adds storage pool to instance-created lifecycle context

---

lxd/db/generate/db/method.go

#10833 causes `make update-schema` in LXD Cloud with:
```
Error: Can't format generated source code: 7:16: expected operand, found 'type'
```
This is the same error as in #10802 and this PR fixes it in the same way.

lxd-generate Allow Type field in filter struct

---

lxd/db/generate/db/method.go

If `-d <package name>` is specified, then `lxd-generate` helpers are generated in an external package, so properly set the receiver to be the package that is specified.

lxd/db/generate/db/method: Fix external package support

---

lxd/db/generate/db/stmt.go

@stgraber This plus the changes in #10845 should fix up `lxd-generate` for you. 
Here are what the generated queries should look like:
https://paste.ubuntu.com/p/4bcBwcd94m/

lxd/db/generate/db/stmt: Use joinon tag for ID query generation

---

lxd/db/generate/db/mapping.go
lxd/db/generate/db/stmt.go

Uses the join configuration in the `db` struct tag to set correct table and column names in the where, join, and order by clauses or generated statements.
`make update-schema` does not change generated statements for LXD.
@masnax I've made the changes necessary to fix the issues in #10844 but I'm not sure if there are any other parts of the generator that might need similar changes. Also in the `whereClause` function, I'm not sure if it's ok to use the singular form of the join table name in the `via` map. Let me know what you think.
Closes #10844.

lxd-generate join config

---

doc/rest-api.yaml
lxd/api_project.go

Change swagger documentation for `POST /1.0/projects/{projectName}` to an operation response (`EmptySyncResponse` was incorrect).

Project rename response docs

---

doc/requirements.md

I mixed up Linux's native async I/O facilities with POSIX AIO -- dqlite (via raft) uses the first one.
Signed-off-by: Cole Miller <m@cole-miller.net>

doc/requirements: correct statement about AIO

---

lxd/storage/backend_lxd.go
lxd/storage/drivers/bucket.go
lxd/storage/drivers/driver_cephobject.go
lxd/storage/drivers/driver_cephobject_buckets.go
lxd/storage/drivers/driver_common.go
lxd/storage/drivers/interface.go
lxd/storage/drivers/volume.go
lxd/storage/utils.go
lxd/storage_buckets.go

As part of implementing local storage buckets we need to use local volumes to back the MinIO process that is providing the S3 bucket service.
Because each storage driver can provide pool level volume defaults (some of these necessary for mounting the volume) I think it makes sense to re-use the `Volume` struct, with all of its existing config handling logic rather than duplicate/merge/over complicate it with a dedicated `Bucket` struct type.
This was OK when we only had `cephobject` pool type as that didn't have the concept of volumes at all.
Note: We are still not creating bucket DB records in the `storage_volumes` table, and there is a specific check to prevent this should it be accidentally tried.

Storage: Use `Volume` to represent buckets with a new VolumeType

---

lxd/db/storage_buckets.go
lxd/storage/drivers/driver_cephobject_buckets.go
lxd/storage/drivers/driver_zfs.go
lxd/storage/storage.go
lxd/storage_buckets.go

- Initialise ZFS pool datasets on mounts. So we can be sure that they exist and have the correct policy. Will also mean that existing ZFS pools get the forthcoming buckets datasets. This is similar to how `backendLXD.Mount()` already creates any missing pool directories if needed.
- Add support for searching for buckets across pools (required for looking up local buckets by name).

Storage: Precursor changes before local bucket support

---

doc/howto/network_bridge_resolved.md

RemainAfterExit=yes avoids the oneshot job from running stop commands
immediatly after running the start ones. ExecStopPost is used instead
of ExecStop because the later is skipped if start commands failed.

doc: improve systemd-resolved integration by adding stop command

---

scripts/empty-lxd.sh
test/includes/lxc.sh
test/includes/lxd.sh
test/includes/storage.sh

- If a `lxc` call (or the associated LXD API handler) hangs for some reason then don't hold up the tests and quickly fail.
- Cleanup storage buckets when cleaning up storage pools in tests.
- Allow use of `losetup -d` during tests to allow automatic removal of loop devices when unmounted.

Test: Adds timeout to `lxc` command calls

---

lxd-agent/server.go
lxd/daemon.go
lxd/db/networks.go
lxd/db/storage_pools.go
lxd/device/disk.go
lxd/instance.go
lxd/instance/drivers/driver_common.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/drivers/load.go
lxd/instance/instance_utils.go
lxd/instances.go
lxd/operations/websocket.go
lxd/profiles_utils.go
lxd/storage/backend_lxd.go
lxd/storage_volumes.go
lxd/storage_volumes_utils.go

As part of introducing `restricted.networks.access` feature for projects I intend to make the instance's `api.Project` struct available inside the instance `driver.Common` struct (like we do with profiles), so that the project's config is available during instance device validation without having to load it repeatedly.
As a precursor to this I noticed that the `instance.Load()` function accepted a `profiles` argument that was largely redundant since we started embedding the instance's profiles inside the instance args struct. So this PR removes it.
Whilst doing that I also noticed a few other minor tweaks that improve error logging and reduce logging noise.

Instance: Remove duplicate profiles argument from `instance.Load()`

---

lxd/instance/drivers/driver_qemu.go

Closes #10873
Also enables vhostfds mode for increased CPU offloading (like we do for bridged NICs already).
Tested with side-loaded edge snap using:
- `bridged` NIC with 1 CPU.
- `bridged` NIC with 4 CPUs.
- `macvlan` NIC with 1 CPU.
- `macvlan` NIC with 4 CPUs.
- `physical` NIC with 1 CPU.
- `physical` NIC with 4 CPUs.
So doesn't appear to be any regressions.
Difference in `ethtool` output with 4 CPUs and macvlan before and after:
Before:
```
ethtool -L enp5s0
no channel parameters changed.
current values: rx 0 tx 0 other 0 combined 1
```
After:
```
ethtool -L enp5s0
no channel parameters changed.
current values: rx 0 tx 0 other 0 combined 4
```

VM: Adds support for multi-queue macvlan NICs in VMs

---

lxd/backup/config/backup_config.go
lxd/storage/backend_lxd.go

This PR adds profiles into `backup.yaml` upon `lxc export`.
Example:
```
pool:
config:
size: 7GiB
source: /var/lib/lxd/disks/default.img
zfs.pool_name: default
name: default
driver: zfs
used_by: []
status: Created
locations:
- none
profiles:
- config: {}
description: Default LXD profile
devices:
eth0:
name: eth0
network: lxdbr0
type: nic
root:
path: /
pool: default
type: disk
name: default
used_by: []
- config: {}
devices: {}
name: p1
used_by: []
```
Fixes: #10329

Add profiles to backup data

---

lxd/db/cluster/certificate_projects.go
lxd/db/cluster/certificate_projects.mapper.go
lxd/db/cluster/certificates.mapper.go
lxd/db/cluster/cluster_groups.mapper.go
lxd/db/cluster/images.mapper.go
lxd/db/cluster/instance_profiles.go
lxd/db/cluster/instance_profiles.mapper.go
lxd/db/cluster/instances.mapper.go
lxd/db/cluster/nodes_cluster_groups.mapper.go
lxd/db/cluster/operations.mapper.go
lxd/db/cluster/profiles.mapper.go
lxd/db/cluster/projects.mapper.go
lxd/db/cluster/snapshots.mapper.go
lxd/db/cluster/warnings.mapper.go
lxd/db/generate/README.md
lxd/db/generate/db/parse.go
lxd/db/generate/db/stmt.go

As per our discussions on irc, I've updated `lxd-generate`'s statement generation for all statements of the type `objects-by-FIELD` to first search the package for a variable declaration of the form
```go
var <entity>Objects = RegisterStmt(`SQL String`)
```
And then extract the `SQL String` from the syntax tree, and append a `WHERE` clause with the given filters, and create a new variable declaration of the form
```go
var <entity>ObjectsByField = RegisterStmt(`SQL String with WHERE clause`)
```
This will allow us to specify our own `<entity>Objects` for more complex queries, and still be able to use `lxd-generate` to create filterable statements. 
Additionally, I went ahead and created a `lxd-generate.md` under the `docs` directory with an overview of all the functionality of …

lxd-generate: Create filtered statements from pre-existing "objects" statement.

---

doc/containers.md
doc/howto/move_instances.md
doc/instances.md
doc/virtual-machines.md

A small follow-up to the migration docs - move the live migration content from the container page to the new page that covers live migration.

Migration cleanup

---

lxd/network/driver_bridge.go
lxd/warnings.go
test/suites/warnings.sh

- This will trigger network start retry functionality.
- This will cause a warning to be shown in `lxc warning list`.
- Also fixes `lxc warning show` breakage and adds tests to catch any future regressions.
Fixes #10874

Network: Make dnsmasq start failure a network start failure

---

shared/util_linux.go

When calling listxattr with sz 0, overlay does not filter the results.  When subsequently calling it with non-zero sz, it will filter out some xattrs.  If all xattrs were filtered out, then the next result will be 0.  In this case, we were continuing on to call getxattr on xattr=="", and getting back an ERANGE, after which we returned ERANGE for the whole ShiftFile operation.
So if listxattr returns 0 on our second call, simply return with no error.
Signed-off-by: Serge Hallyn <serge@hallyn.com>

GetAllXattr: handle overlay filtering

---

go.mod
go.sum
shared/idmap/idmapset_linux.go
shared/util_linux.go

Although there was no reproducer for the reported issue, by using this package we should benefit from wider spread exposure (and the associated bug fixes) than the previous internal implementation. The package has been recently updated and we already depend on other packages from this repository.
Includes fix from https://github.com/lxc/lxd/pull/10198
Closes #10731

Shared: Update GetAllXattr implementation using github.com/pkg/xattr

---

shared/logger/log.go

Instead create a new one for LXD's Log variable.
Fixes #10806

Shared: Don't modify the global logrus standard logger

---

Makefile
lxd/device/device_utils_unix_hotplug_events.go
lxd/device/device_utils_usb_events.go
lxd/instance.go
lxd/instances_post.go
lxd/maas/controller.go
lxd/storage.go

These were missed during https://github.com/lxc/lxd/pull/10869

lxd: Fix calls to inst.Project().Name when used in fmt.Sprintf

---

lxd/db/query/retry.go
lxd/firewall/drivers/drivers_nftables.go
lxd/network/openvswitch/ovn.go
lxd/networks.go
lxd/storage/backend_lxd.go

This allows for larger rulesets so we don't hit the maximum number of command line arguments limit.
Reported from https://discuss.linuxcontainers.org/t/network-forward-ports-maximum-500-per-network-possible-bug/15012
In testing this it also revealed some other issues which are now fixed:
- Deferred network starting wasn't taking into account that a physical network can depend on an interface provided by a bridge network, so its important to start non-dependent networks first before networks that rely on physical interfaces being available (followed by the OVN networks that depend on the managed networks being available).
- Also improved deferred network startup by maintaining this ordering both during the initial start up phase as well as subsequent retry attempts. This means that LXD …

Firewall: Pass nftables rules via stdin rather than as command arguments

---

lxd/daemon_images.go
lxd/db/images.go
lxd/images.go
lxd/instance.go

Fixes #10855
Also fixes some issues caused by lack of project support in some image management functions which would have caused images in different projects to have their last used date be updated incorrectly.
The database access in the image management functions is not very efficient, but fixing that will be a larger project so I've left it for now.

Image: Maintain `Cached` property when creating an image in a project from an existing project

---

lxd/db/cluster/certificates.mapper.go
lxd/db/cluster/cluster_groups.mapper.go
lxd/db/cluster/instances.mapper.go
lxd/db/cluster/nodes.mapper.go
lxd/db/cluster/nodes_cluster_groups.mapper.go
lxd/db/cluster/profiles.mapper.go
lxd/db/cluster/projects.mapper.go
lxd/db/cluster/snapshots.mapper.go
lxd/db/cluster/warnings.mapper.go
lxd/db/generate/db/method.go

@tomponline noted in #10899 that since we call `row.Scan`, we don't need to manually check the row error. 
Indeed the first thing `row.Scan` checks is the existing `row.err`.

Lxd-generate: Remove superfluous GetID error check

---

shared/osarch/architectures.go

This adds both armv6l and armv8l and changes the way we track personalities to chain them and hopefully result in the correct set of images being supported.
Closes #10909

shared/osarch: Improve 32bit arm handling

---

lxd/network/driver_physical.go

Fixes regression from 632c588fe8cf90af11637b307c94b3f4d8d9c599

Network: Fix ipv4.routes validation in `physical` network driver

---

lxd/storage/backend_lxd.go
lxd/storage/drivers/driver_dir_volumes.go
lxd/storage/drivers/volume.go
lxd/storage/s3/miniod/miniod.go

As this is potentially network accessible service (via LXD acting as a reverse proxy) it is preferable from a security perspective to run the `minio` process as non-root.
This PR also adds automatic on-demand correction of ownership and permissions should the LXD unprivileged user change after the `minio` process has previously written data to the volume.
Also fixes 2 other issues:
- Storage volumes on `dir` pools were being allowed to be created even if the volume already existed on disk. This is a problem as if a subsequent action (like creating a local bucket on it) should fail, the volume will be deleted via a revert, and any existing data would be lost. We should not allow creating a storage volume if one already exists.
- If creating a local storage bucket didn't succeed, the local …

Storage: Run local bucket `minio` process as LXD's unprivileged user

---

test/README.md
test/main.sh
test/suites/storage_buckets.sh

And updates `test_storage_buckets` to check for `minio` command or skip (if not in `LXD_REQUIRED_TESTS`).
The aim of this PR is to prevent specialist tests that have uncommon external requirements (such as having minio installed) from failing the test suite if their external requirements are not met, unless the test name is explicitly listed `LXD_REQUIRED_TESTS` environment variable.
This allows for downstream packagers to run the common tests are part of the packaging process and not to have to worry about maintaining a list of skipped tests via the `LXD_SKIP_TESTS` environment variable (although this is possible if needed).
I originally discussed with @stgraber about adding a special return value for the test functions and checking for that.
But in the end I went for setting the …

test: Adds LXD_REQUIRED_TESTS support

---

lxd/device/device_common.go

This was missed during https://github.com/lxc/lxd/pull/10869

Device: Fix project name in device logger

---

client/lxd_images.go

client: Handle nil args in CopyImage

---

.sphinx/.wordlist.txt
.sphinx/conf.py
doc/explanation/performance_tuning.md
doc/faq.md
doc/howto/network_increase_bandwidth.md
doc/metrics.md
doc/operation.md
doc/production-setup.md
doc/reference/server_settings.md
doc/security.md

Add a performance tuning section to the docs that replaces and extends the current production setup page. That page is moved to a reference page (incl. a redirect to ensure no links/bookmarks break).
The next step will be to add a how to guide for the benchmarking tool.

Add a performance tuning section

---

doc/dev-lxd.md

Also mention that security.devlxd must be set to true.

doc/instance API: add link to YouTube video

---

.sphinx/conf.py
README.md
doc/index.md

Update the IRC link to https://web.libera.chat/#lxc .
Configure the link checker to ignore that link, since `#lxc` is not an anchor and therefore would cause the link checker to fail.

doc: update IRC link

---

lxd/apparmor/instance_qemu.go

Starting a VM result in this Apparmor denial:
```
Sep 26 15:15:11 sdeziel-lemur kernel: audit: type=1400 audit(1664219711.839:917): apparmor="DENIED" operation="open" profile="lxd-pylxd-test_</var/snap/lxd/common/lxd>" name="/proc/334670/cpuset" pid=334670 comm="lxd" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
```
Environment details:
```
lsb_release -rd
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
$ uname -a
Linux sdeziel-lemur 5.15.0-48-generic #54-Ubuntu SMP Fri Aug 26 13:26:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
$ snap list lxd
Name  Version      Rev    Tracking       Publisher   Notes
lxd   5.5-37534be  23537  latest/stable  canonical✓  -
```

lxd/apparmor/instance: allow reading /proc/pid/cpuset

---

doc/metrics.md

doc/metrics: add `lxd_cpu_effective_total` to the list of metrics

---

lxd/api.go
lxd/api_1.0.go
lxd/api_internal.go
lxd/api_metrics.go
lxd/daemon.go
lxd/devices.go
lxd/instance_state.go
lxd/instances_put.go

Otherwise storage may not be ready yet and running instances may not have had their mount counters initialised. This can lead to an incoming metrics request triggering an unwanted unmount at the end of the request as it doesn't know the volume is in use.
Also removes the unnecessary loading of all local instances twice during daemon start up.

Daemon: Wait until server is ready before handling metrics and bucket API requests that can cause mounts

---

lxd/instance/drivers/driver_qemu.go

VM: Dont offer VM support if /dev/vsock is missing

---

lxd/device/nic_ovn.go
lxd/network/driver_ovn.go
lxd/network/openvswitch/ovn.go

Part of https://github.com/lxc/lxd/issues/10553
- Updates `LogicalSwitchPortSetDNS` to just accept the IPs to use for the DNS record directly rather than trying to extract them from the logical switch port config.
- Moves the logical switch port dynamic IP extraction into the `ovn` network driver and use this to drive `LogicalSwitchPortSetDNS` directly with extracted IPs.
- Adds optimisation where if all IPs are statically allocated, there's no need to ask OVN for the dynamic logical switch port IPs.
- Makes DNS name IPs dependent on the relevant protocol's DHCP setting being enabled. Because OVN will generate dynamic IPs even if DHCP is disabled, and we don't want those IPs to appear in DNS in that case.

Network: Separate DNS IP configuration from dynamic IP extraction logic

---

lxd/device/nic_ovn.go
lxd/network/driver_ovn.go
lxd/network/openvswitch/ovn.go

This allows for static IP allocations to be reserved even when the instance isn't running.
Uses the logical switch's `exclude_ips` list to prevent a reserved IP from being allocated dynamically to another instance NIC.
Because the `exclude_ips` list is just a list of IPs without any ability to associate them to a particular device name, this presented a problem because it is possible to have conflicting instance IP configs in the database (for example copying an instance that has a static IP configured). This would be a problem if the conflicting instance was removed as it would then remove the reservation for the original instance.
I have solved this problem by changing how DNS records in OVN are managed by LXD. An empty DNS record entry is now created on `Add()` and deleted on …

Network: Manage DHCPv4 reservations when adding/removing OVN NICs

---

lxd/apparmor/qemuimg.go
lxd/instance/drivers/driver_qemu.go
lxd/storage/utils.go

Hi, this is first step to cover qemu-img calls with apparmor.
Only one call is currently covered: `rlimit --cpu=2 --as=1000000000 qemu-img info -f qcow2 --output=json /var/lib/lxd/images/zxy.rootfs`
It is triggered by `lxc launch images:ubuntu/20.04 vm1 --vm`
I appreciate any comment or reviews.
Fixes #10253

lxd/apparmor: apparmor profile for qemu-img

---

lxd-agent/metrics.go

This fixes an issue where available bytes and free bytes would always be
0.
This fixes #10994.

lxd-agent: Fix filesystem metrics

---

lxd/api_1.0.go
lxd/api_cluster.go
lxd/cluster/gateway.go
lxd/cluster/gateway_test.go
lxd/cluster/heartbeat.go
lxd/cluster/heartbeat_test.go
lxd/cluster/membership.go
lxd/cluster/membership_test.go
lxd/cluster/notify.go
lxd/cluster/notify_test.go
lxd/cluster/upgrade_test.go
lxd/daemon.go
lxd/endpoints/cluster.go
lxd/endpoints/endpoints_exported_test.go
lxd/endpoints/network.go
lxd/images.go
lxd/network/driver_bridge.go
lxd/node/config.go
lxd/node/config_test.go
lxd/operations.go
lxd/patches.go
lxd/state/state.go

Which always loads full node config from DB unnecessarily.
Instead add and maintain a cache of the local config in the `Daemon.localConfig` variable and make available via State() function.
This aligns with what we have done for `Daemon.globalConfig`.

LXD: Remove use of node.ClusterAddress helper

---

lxd/api_1.0.go
lxd/api_cluster.go
lxd/certificates.go
lxd/cluster/heartbeat.go
lxd/cluster/membership.go
lxd/daemon.go
lxd/init.go
lxd/instances_put.go
lxd/main_activateifneeded.go
lxd/network/driver_bridge.go
lxd/node/config.go
lxd/node/config_test.go

Also:
-  Remove unnecessary duplicate network load request in initDataNodeApply.
- Fixed couple of cases where the HTTP address was incorrectly being used to identify the local cluster member rather than using the local cluster address.
- Fixes clusterCertificatePut to use tx.GetNodes to get all members rather than only RAFT members.

LXD: Use cached local HTTP address and remove node.HTTPAddress() function 

---

lxd/instance/drivers/driver_common.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/drivers/load.go
lxd/instance/instance_utils.go
lxd/profiles.go
lxd/profiles_utils.go

When a device is added to a profile that is not supported by a specific instance type we should ignore the error and just not use the device with the specific instance.
This allows for using a sharing a profile between multiple instance types when a device isn't supported with all instance types.
However still should prevent adding unsupported devices to an instance's local config.
Fixes #10552

Instance: Handle unsupported devices from profiles shared with multiple instance types

---

lxd/api_cluster.go
lxd/cluster/events.go
lxd/cluster/gateway.go
lxd/cluster/heartbeat.go
lxd/cluster/heartbeat_test.go
lxd/cluster/membership.go
lxd/cluster/membership_test.go
lxd/cluster/notify.go
lxd/cluster/notify_test.go
lxd/db/db.go
lxd/instances_put.go
lxd/network/driver_ovn.go
lxd/networks.go
lxd/operations.go
lxd/patches.go
lxd/storage_volumes_snapshot.go

And fixes some user facing errors that mention "nodes" rather than "members".

LXD: Use consistent "member" terminology when using `tx.GetNodes()`

---

lxd/instance/drivers/driver_common.go

Fixes intermittent migration test failures caused by incorrect snapshot send order if snapshots were all created in same second.

Instance: Sort snapshots by ID if creation datetime matches

---

lxd/api_internal.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/operationlock/operationlock.go

Prevents a Delete request from being processed while there is an ongoing start operation. 
Otherwise this can leave the mount counter in an inconsistent state.
Previously got:
```
lxc init images:alpine/edge c -p foo ; lxc start c & lxc exec c hostname; lxc delete -f c
Creating c
The instance you are starting doesn't have any network attached to it.
To create a new network, use: lxc network create
To attach a network to an instance, use: lxc network attach
[4] 82997
Error: Instance is not running
Error: Failed to run: /home/user/go/bin/lxd forkstart c /var/lib/lxd/containers /var/log/lxd/c/lxc.conf: exit status 1
```
Now get:
```
lxc init images:alpine/edge c -p foo ; lxc start c & lxc exec c hostname; lxc delete -f c
Creating c
The instance you are starting doesn't have any network …
```

Instance: Add Delete operation lock

---

doc/explanation/storage.md
doc/howto/storage_buckets.md
doc/howto/storage_volumes.md

Add a link to the YouTube video about storage buckets, and also link the volume/bucket videos from the respective how-tos.

doc/storage: add video links

---

lxd/device/nic_bridged.go
lxd/ip/link.go
lxd/network/driver_bridge.go

If the parent bridge does not have a default PVID set then don't try to remove it from instance NICs, as this will prevent start.
Also during network setup, don't set the default PVID to 1, as if it has been previously set to something else it won't be applied if VLAN filtering is enabled.
Fixes #10926

Device: Fix bridge NIC start failures when using `vlan` when parent bridge has no default PVID

---

shared/version/useragent.go

A recent change to the user-agent logic caused the architecture to get incorrectly capitalized and for the OS name to be dropped.

shared/version: Fix regression in useragent string

---

lxc/file.go

Fix symlink following in cmdFilePull when output is stdout or recursive flag is used.
Also imposes a 255 max depth for symlinks.
This aligns with the one in Go's walkSymlinks:
https://cs.opensource.google/go/go/+/refs/tags/go1.19.2:src/path/filepath/symlink.go;l=99
Fixes #11016

lxc: Fix symlink following in cmdFilePull

---

.sphinx/.wordlist.txt

.sphinx: Add `goroutines` and `uptime` to wordlist

---

lxc/exec.go
lxc/main.go
lxd-agent/exec.go
lxd/instance/drivers/driver_common.go
lxd/instance/drivers/driver_lxc_cmd.go
lxd/instance/drivers/driver_qemu_cmd.go
lxd/instance_exec.go

Improves exit status detection when running `lxc exec` on a VM:
- Detects missing parent directory and returns 127 exit status.
- Detects permission denied and returns 126 exit status.
And for both containers and VMs if exit status 126 (command not executable) or 127 (command not found) occurs then an operation error is returned and `lxc exec` command will now display it, whilst still maintaining the exit status of the command.
Fixes #10534

Instance: Improve exit status and error handling in exec

---

lxd/main_init_interactive.go

Changes them to "server" or "member".

lxd/main/interactive: Remove user facing "node" references

---

doc/explanation/performance_tuning.md
doc/metrics.md

This renames the `instance metrics` page, and includes the internal
metrics.

doc: Update metrics

---

lxd/device/nic.go
lxd/device/nic_bridged.go
lxd/device/nic_ovn.go
test/suites/container_devices_nic_bridged.sh

Device: Add case insensitive DNS name conflict check for `bridged` and `ovn` NICs connected to managed networks

---

doc/rest-api.md

doc/rest-api: Add missing Ready state

---

.sphinx/.markdownlint/exceptions.txt
doc/contributing.md

Added as a related link and not embedded since the video has a much wider focus than the documentation page.

doc: add a link to the development process YouTube video

---

lxd/certificates.go
lxd/main_init.go
lxd/main_init_interactive.go
shared/util.go

This exports some helpers to make it easy to initialize LXD from a `go` application. These helpers were initially under the `main` package, so I've moved the `node` related helpers to the `node` package, and moved `ClusterMemberJoinTokenDecode` to the cluster package.
This will be particularly helpful in bootstrapping LXD for MicroCloud, reducing code duplication.

Export initialization helpers

---

lxd/instance/drivers/driver_qemu.go

Fixes an issue introduced by `advertiseVsockAddress` by removing mount & unmount calls from `generateAgentCert`.
We expect the callers of `generateAgentCert` to have ascertained whether the VM is running (and therefore mounted) before calling this function.
By making this change it prevents a mount/unmount race when LXD starts up during the `devicesRegister` function call.
During this function call, each instance has its `IsRunning()` function called to check if it needs its devices registered. For `disk` devices of running instances its important that their `Register`functions are called on LXD start in order to initialise the mount counter for that disk (so that a subsequent unmount call isn't incorrectly run if LXD incorrectly thinks that the disk volume isn't in use anymore).
For VMs …

VM: Fix unmount race during LXD startup registeration of running VMs

---

doc/rest-api.yaml
lxd/api_cluster.go
lxd/init.go
lxd/main_init.go
lxd/main_init_auto.go
lxd/main_init_dump.go
lxd/main_init_interactive.go
lxd/main_init_preseed.go
shared/api/init.go
shared/version/api.go

From the discussions with @tomponline in #11036,  this PR adds some new api structs:
* `Preseed` -- A representation of the `lxd init` preseed.yaml file.
* `LocalPreseed` -- Local node-specific initialization configuration from the preseed.yaml.
* `ClusterPreseed` -- Cluster-specific initialization configuration from the preseed.yaml.
* `NetworksProjectPost` -- effectively `api.NetworksPost` but with a project associated.

Export preseed structs

---

lxd/device/unix_hotplug.go

device maybe a nil pointer will cause a run-time panic
Signed-off-by: luoguanzhong <549899794@qq.com>

lxd/device: Continue if device is nil

---

lxd/network/driver_ovn.go

This way a dynamic IP is still assigned to the logical switch port, so it can be used for the target of static routes (so it resolves to the port's MAC address), even when DHCP is disabled.

Network: Get dynamically allocated IPs from OVN switch port even if not using DHCP

---

lxc/image.go

This filters images not just by their properties but by any other field.
This fixes #10558 

lxc: Extend image filtering

---

test/suites/clustering.sh

This unsets the join_token_expiry config key after the test has
finished. This will make LXD use the default expiry of 3h.

test/suites: Unset join_token_expiry when done

---

doc/authentication.md

Also add a related link to the ACME specification.

doc/authentication: clarify expiration of cluster join tokens

---

lxd/api_internal.go
lxd/daemon.go
lxd/operations.go

This fixes `lxd shutdown` to respect `core.shutdown_timeout` (and its default), as well as doing a little clean up to improve logging.

Daemon: Respect core.shutdown_timeout

---

lxc/init.go

The usage is currently given as `lxc init [[<remote>:]<image>] [<remote>:][<name>] [< config [flags]`
This aligns it with what we have for `lxc launch`.
No idea if there's anything else needed for the PR. ;)

lxc init: Fix usage line in the help output

---

lxd/apparmor/network_dnsmasq.go

When the LXD snap runs under WSL, and WSL is allowed to manage /etc/resolv.conf automatically (the default), containers are unable to resolve DNS names. This happens because when WSL manages /etc/resolv.conf automatically, /etc/resolv.conf is a symlink to /mnt/wsl/resolv.conf, and AppArmor therefore denies _dnsmasq_ access to it:
```
Oct 25 10:35:05 pallas-wsl dnsmasq[9258]: started, version 2.80 cachesize 150
Oct 25 10:35:05 pallas-wsl kernel: audit: type=1400 audit(1666712105.134:153): apparmor="DENIED" operation="open" profile="lxd_dnsmasq-lxdbr0_</var/snap/lxd/common/lxd>" name="/mnt/wsl/resolv.conf" pid=9900 comm="dnsmasq" requested_mask="r" denied_mask="r" fsuid=999 ouid=0
Oct 25 10:35:05 pallas-wsl audit[9900]: AVC apparmor="DENIED" operation="open" …
```

Add resolv.conf location under WSL

---

doc/configuration.md

The introduction doesn't make sense anymore after we removed most of the pages underneath.
We should probably get rid of the whole section in the future.

doc: remove intro sentence for configuration

---

lxd/api_metrics.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/instance_interface.go
lxd/instance_get.go
lxd/instance_state.go
lxd/instance_test.go
lxd/instances_get.go
lxd/main_forknet.go
shared/netutils/network_linux_cgo.go

Rather than for every container in a list.
This can significantly increase the speed of `lxc list` output if you have hundreds of running containers.
Fixes #11042

Device: Speed up getting NIC host name info by loading host interface info once per request

---

shared/instance.go
shared/validate/validate.go
shared/validate/validate_test.go

This moves the CPU set validator from instance.go to a separate
validator function. It extends the regular expression which allows the
previous character checks to be removed.

Extend CPU limit validation

---

lxc/copy.go
lxc/init.go
lxc/utils.go
po/lxd.pot
test/suites/basic.sh

Adds a `--device`/`-d` flag to `lxc init` and `lxc launch` to pass in device overrides of the form `<deviceName>,<key>=<value>`. The overrides are performed after the instance is created, if an overridden device is not found in the expanded devices of the instance (i.e. devices applied via profile), then the instance is deleted.
Closes #10796

Allow device overrides when initialising or launching an instance.

---

lxd/storage_pools.go

LXD panics if the storage pool config passed to a `POST` is nil, as we try to create the storage pool. This initializes the storage pool config if it's nil, so that doesn't happen.

lxd/storage/pools: Initialize pool config if nil

---

lxd/profiles.go

The shadowed variable "p" of type *api.Profile was being used incorrectly to retreive the project name (via p.Name). So project names were incorrect when listing profiles without recursion.
Closes #11083

lxd: Remove shadowed variable name.

---

lxd-agent/devlxd.go
lxd-agent/response.go

This changes the error messages for devlxd queries, in that it
returns the correct HTTP error instead of an Internal Status Error.

lxd-agent: Return correct error when querying devlxd

---

lxd/instance_delete.go
lxd/instance_patch.go
lxd/instance_post.go
lxd/instance_put.go

This fixes an issue where instances could be updated or deleted while
LXD is in setup mode and the instances themselves are being started.

lxd: Check LXD ready state before changing instance

---

doc/explanation/instances.md
doc/howto/instances_console.md
doc/howto/instances_manage.md
doc/howto/storage_move_volume.md
doc/instance-exec.md
doc/instances.md
doc/operation.md

This also includes moving the existing page from "Operations" to "Instances".

doc/instances: add instructions for running commands and logging on

---

lxd/device/tpm.go

lxd/device/tpm: Handle TPM devices in profiles

---

lxd/network/driver_bridge.go

Needed when using fan mode with VMs.
Fixes #11072

Network: Adds MTU DHCP option when using bridge fan mode

---

lxd/main_init_preseed.go

This commit adds strict checking to init preseed, and will return an
error if provided keys are unknown.
This fixes #11106.

lxd/init: Use strict checking for preseed

---

CONTRIBUTING.md
doc/rest-api.yaml
shared/api/instance_backup.go
shared/api/storage_pool_volume_backup.go
test/lint/rest-api-up-to-date.sh

When reviewing the weekly news, I noticed the `create_at` field for `storage volume` and `storage volume snapshot` was missing from #11034. I then went on manually adding them to `doc/rest-api.yaml` only to notice it was auto-generated (good!) and was missing some other bits. To make it extra clear (for the future me), I updated the doc while in there.

Refresh REST API

---

doc/remotes.md

As reported in Debian bug [1021624](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1021624), the configuration directory listed in docs/remotes.md is incorrect. The string "etc/lxc" doesn't appear anywhere else in the code, so hopefully there aren't any other incorrect references remaining.

doc: Fix configuration directory in remotes.md

---

doc/howto/instances_manage.md

You can add a "location" filter to display only instances on a specific cluster member.

doc/instances: add example for filtering by location

---

lxd/instance/drivers/driver_common.go
lxd/instance/drivers/driver_lxc.go
lxd/instance/drivers/driver_qemu.go
lxd/instance/operationlock/operationlock.go

Because there are 2 container stop hooks (onstopns and onstop) the instance initiated operation lock was being created on onstopns, but the instance-shutdown lifecycle event was only being generated in the onstop hook. Because of this the operation lock already existed (because it was created by the onstopns hook) by the time onstop hook run and the instance-shutdown lifecycle event never fired.
This has been fixed by adding an instance initiated marker on the operation lock itself which can be propagated between stop hooks, allowing for the final onstop hook to detect an instance initiated stop and correctly trigger the instance-shutdown lifecycle event.
VMs were never affected because they don't have the same stop hooks that containers have.
Reported from …

Instance: Fixes missing container initiated instance-shutdown lifecycle event

---

client/lxd.go
client/lxd_instances.go
lxd/api.go
lxd/cluster/gateway.go
lxd/instance_exec.go
lxd/instance_sftp.go
lxd/migrate.go
shared/tcp/tcp_timeout_user.go
shared/tcp/tcp_timeouts.go

While keeping the dqlite TCP user timeout to 30s for fast failure detection.
Attempts to address issue raised in https://discuss.linuxcontainers.org/t/anyone-else-got-btrfs-send-failures-since-5-7/15486

shared: Increase default TCP user timeout from 30 seconds to 2 minutes 

---

lxd/devlxd.go
test/devlxd-client/devlxd-client.go
test/suites/devlxd.sh

This is so cloud-init running inside the instance can identify the NIC when the interface name is different than the LXD device name (such as when run inside a VM).
Fixes #11115

devlxd: Add volatile NIC hwaddr to devices output

---

lxd/storage/backend_lxd.go

We can ascertain the content type of the volume from the storage volume record, rather than relying on the image DB record existing.
This makes this function more resilient as it removes the dependency of having an associated image DB record, which in some cases where the DB is not in a consistent state, can prevent the storage pool from being deleted.
Fixes https://discuss.linuxcontainers.org/t/cant-remove-node-from-cluster/15614/

Storage: Update DeleteImage to not use GetImageFromAnyProject

---

lxd/daemon.go
lxd/fsmonitor/drivers/driver_fanotify.go
lxd/instances.go
test/includes/lxc.sh

This fixes a shutdown hang I observed when stopping LXD with 500 running instances on an 8 core system.

lxd: Limit shutdown concurrency to number of instances or number of CPU cores (which ever is less).

---

lxd/device/disk.go

Fixes regression caused by 897a481be9738ccc1e3a0ab3c736ed02e4de05f6
The use of `if d.pool.Driver().Info().Remote` incorrectly covers both `ceph` and `cephfs` pool types, whereas it should have been `if d.pool.Driver().Info().Name == "ceph"` to only cover `ceph` type pools.
Fixes #11126

Device: Fix attaching cephfs disk volumes to VMs

---

test/includes/lxd.sh
test/includes/storage.sh
test/suites/basic.sh
test/suites/container_local_cross_pool_handling.sh
test/suites/devlxd.sh
test/suites/image.sh
test/suites/storage_local_volume_handling.sh

SC2034: "foo appears unused. Verify it or export it."

test: Reduce "shellcheck disable=SC2034" usage

---

lxd/storage/drivers/driver_zfs_volumes.go
lxd/storage/utils.go

Reported from https://discuss.linuxcontainers.org/t/howto-set-zfs-recordsize-attr-on-storage-volume-creation/10008/7?u=tomp
Although this PR fixes the reported problem, while investigating it I also found a broader set of problems around incorrect values of zfs.blocksize making it into storage volume DB record (when creating volumes from other volumes/images).
Although they can occur without this change so I thought it OK to include this PR separately to fix the obvious blocking problem.

Storage: Allow ZFS block volumes to use pool's zfs.blocksize setting

---

doc/howto/network_bridge_firewalld.md

Apparently, the `DOCKER-USER` custom chain does not (or no longer) allow returning traffic. Here's a sample `iptables-save` from a user:
```
*filter
:INPUT ACCEPT [0:0]
:FORWARD DROP [72:11392]
:OUTPUT ACCEPT [0:0]
:DOCKER - [0:0]
:DOCKER-ISOLATION-STAGE-1 - [0:0]
:DOCKER-ISOLATION-STAGE-2 - [0:0]
:DOCKER-USER - [0:0]
:ts-forward - [0:0]
:ts-input - [0:0]
-A INPUT -j ts-input
-A FORWARD -j ts-forward
-A FORWARD -j DOCKER-USER
-A FORWARD -j DOCKER-ISOLATION-STAGE-1
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A FORWARD -o br-544f43c9c288 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o br-544f43c9c288 -j DOCKER
-A FORWARD …
```

doc: allow returning traffic in DOCKER-USER custom chain

---

lxd/instance_post.go

It was possible via the API to move an instance to a different cluster member using an invalid (or empty) instance name.
Reported from https://discuss.linuxcontainers.org/t/container-name-is-set-to-an-empty-string-after-move/15566

Instance: Prevent moving instance to invalid (or empty) name

---

lxd/instance/drivers/driver_qemu.go

This avoids using "+" and "=" characters in the hashed device name, which QEMU doesn't allow. Also avoids the need to trim the padding "=" character by not having it in the first place.
Fixes #11129

VM: Fix blockNodeName to use base64 raw URL format

---

lxd/api_metrics.go
lxd/devlxd.go
lxd/instance.go
lxd/instance/instance_utils.go
lxd/instance_exec.go
lxd/migrate_instance.go
lxd/network/driver_bridge.go
lxd/seccomp/seccomp.go

And a couple of other bug fixes.

Network: Remove unnecessary query for server name in `bridge` Leases

---

scripts/bash/lxd-client

Autocompletion of commands for running guests which are in a state other than RUNNING doesn't work. 
This change adds READY so now, autocompletion in lxc shell, lxc stop, lxc exec, work as expected
Signed-off-by: Norberto Bensa <nbensa@gmail.com>

scripts/bash/lxd-client: fix autocompletion not working

---

lxd/api_project.go
lxd/db/cluster/projects.go
lxd/db/images.go
test/suites/projects.sh

All projects with `features.images=false` can use all images added to the "default" project.
If these projects also have `features.profiles=true`, their default profiles should be associated
with all created images, otherwise
```
Error: Failed instance creation: Failed creating
instance record: Failed initialising instance: Failed getting root disk: No root device could be found
```
will arise on attempt to create an instance from this image inside all projects (with `features.images=false` and
`features.profiles=true`) except "default" and the project the image was created from.
The same error will take place when `features.images` option changes from `true` to `false`.
Both of these cases was fixed.

lxd: Fix handling of images in projects with features.images=false

---

lxd/device/nic_bridged.go
lxd/device/nic_macvlan.go
lxd/device/nic_ovn.go
lxd/device/nic_p2p.go
lxd/device/nic_routed.go

This is an attempt to workaround potential race conditions with udev/systemd-networkd when creating NICs and passing them to instances.
Although its not proven this is an actual issue. So this is more "belt and braces" approach.
By passing the hwaddr to liblxc (as well as setting it via ip link) it gives another chance for the MAC address to be set before its passed into the container.
Reported from https://bugs.launchpad.net/lxd/+bug/1991552

Device: Add hwaddr key to liblxc NIC config

---

lxd/api_1.0.go
lxd/apparmor/archive.go
lxd/daemon_storage.go
lxd/storage/drivers/volume.go
lxd/storage/drivers/volume_test.go
test/suites/serverconfig.sh

When using custom VM image volume.
Also fixes image volume size comparison issue.
Fixes #11081  #11150
Associated VM tests https://github.com/lxc/lxc-ci/pull/650

VM: Fix VM image unpack apparmor profile in archiveProfile

---

lxd/cluster/config/config.go

This fixes an inconsistency with the `acme.agree_tos` option where if set
to true, then set to false, it would show the option as `false` in
/1.0.
The correct behaviour is to omit the config key if the default value is
set.
Fixes #11153

config: Fix inconsistency with acme.agree_tos option

---

lxd/device/nic_bridged.go
lxd/device/nic_ovn.go
lxd/network/driver_bridge.go
lxd/network/driver_common.go
lxd/network/driver_macvlan.go
lxd/network/driver_ovn.go
lxd/network/driver_physical.go
lxd/network/driver_sriov.go
lxd/network/network_load.go
lxd/network/network_utils.go
lxd/networks.go
test/suites/config.sh

* Use `UsedByInstanceDevices` helper to avoid logic duplication for what constitutes an instance connected to a network.
* Fixes a bug in `UsedByInstanceDevices` where a `macvlan` NIC could be incorrectly considered connected to an OVN network if it was using `parent` property connected to an unmanaged bridge of the same name as an OVN network in a non-default project. 
* Parse MAC and IPs in `Leases()` so they use their canonical form rather than what is provided from the user.
Related to #11145

Network: Use `UsedByInstanceDevices` for `checkAddressConflict` and `Leases`

---

doc/explanation/performance_tuning.md
doc/getting_started.md

Adding the link as a related link to two pages - the video is a bit all over the place (and in the future, we should maybe have a guide about all steps to consider for a production setup), but for now this will have to do. :)

doc: add link to Running in production YouTube video

---

lxd/storage/drivers/driver_ceph.go

This removes the unnecessary volume.block.* config keys from the
Validate() function as they already exist in commonVolumeRules().
Removing these config keys will _not_ change anything, they will
still be validated correctly.

ceph: Drop unnecessary volume.block.* config keys

---

lxd/instance_put.go
lxd/project/permissions.go
lxd/storage_volumes.go

Brings `storagePoolVolumePut` inline with behaviour of `instancePut` (which also doesn't check project limits when restoring an instance snapshot).
Fixes https://github.com/lxc/lxd/issues/11084

Storage: Don't check project limits when doing a volume snapshot restore

---

lxd/device/proxy.go
lxd/network/driver_bridge.go
lxd/network/driver_ovn.go

So we don't add these uplink addresses when viewing leases for other projects where they aren't relevant.
Also adds the network's own gateway IPs to `Leases()` list for consistency (when requesting the network's own project), as we are including OVN router uplink addresses in leases list already.
This will aid with consistency of view between `list-leases` command and DNS zones created within projects.
Related to #11145
E.g.
```
lxc network list-leases lxdbr0
+---------------------+-------------------+----------------------------------------+---------+
|      HOSTNAME       |    MAC ADDRESS    |               IP ADDRESS               |  TYPE   |
+---------------------+-------------------+----------------------------------------+---------+
| c1                  | 00:16:3e:19:6e:de | …
```

Network: Exclude gateway and uplink addresses in leases list when filtering by project other than network's

---

lxd/network_zones.go

Missed one needed use of `project.NetworkZoneProject ` in https://github.com/lxc/lxd/pull/11160

Networks: Use project.NetworkZoneProject in networkZonesGet

---

lxd/db/cluster/certificate_projects.mapper.go
lxd/db/cluster/certificates.mapper.go
lxd/db/cluster/cluster_groups.mapper.go
lxd/db/cluster/config.mapper.go
lxd/db/cluster/devices.mapper.go
lxd/db/cluster/images.mapper.go
lxd/db/cluster/instance_profiles.mapper.go
lxd/db/cluster/instances.mapper.go
lxd/db/cluster/nodes_cluster_groups.mapper.go
lxd/db/cluster/operations.mapper.go
lxd/db/cluster/profiles.mapper.go
lxd/db/cluster/projects.mapper.go
lxd/db/cluster/snapshots.mapper.go
lxd/db/cluster/warnings.mapper.go
lxd/db/generate/db/method.go

As discussed in Prague and in #10944, this PR adds more function support for handwritten SQL statements in lxd-generate. 
In particular, 3 new functions are generated per entity on a call to `GetMany`:
* `<entity>Columns()` - returns a string to be used for the columns to retrieve in a SELECT statement, such that the result will map to the `<entity>` struct.
* `get<entities>(ctx context.Context, stmt *sql.Stmt, args ...any)` - executes the given registered statement with the supplied arguments, returning a slice of type `<entity>`.
* `get<entities>Raw(ctx context.Context, tx *sql.Tx, query string, args ...any)` - executes the given query string with the given transaction and the supplied arguments, returning a slice of type `<entity>`. 
Closes  #10944

lxd-generate: Generate boilerplate functions

---

lxd/apparmor/qemuimg.go

qemu-img uses "/sys/devices/virtual/block/{device_name}/queue/max_segments" with ZFS for its purpose, so path "/sys/devices/** r" is added to AppArmor profile to prevent Apparmor denials
see also https://github.com/qemu/qemu/blob/75d30fde55485b965a1168a21d016dd07b50ed32/block/file-posix.c#L1225
ipc_lock capability is added for memory locking used by qemu-img
Fixes #11154
Signed-off-by: Viktor Iakovchuk <viktor@yakovchuk.net>

lxd/apparmor: fix AppArmor profile for qemu-img

---

doc/howto/cluster_manage.md

To ensure that all cluster members are in the latest unphased cohort.

doc: Adds `--cohort="+"` to snap refresh command

---

lxd/main_forkdns.go
test/suites/clustering.sh
test/suites/network_zone.sh

This fixes a regression caused when I moved this to use the inotify package (https://github.com/lxc/lxd/pull/11152) as by watching for all events, this included the open and read events causing a busy event loop and log spam.
This also fixes a small inefficiency that caused the forkdns server to reload its servers file twice because it was triggering both on writes to the servers file and the temporary file that is generated first.
We now only watch for files being renamed to the main servers list file.
This also updates the tests to properly simulate what LXD does (moving a temporary file into position) to properly trigger the watched for event.

forkdns: Updates serversFileMonitor to only watch for inotify.InMovedTo event

---

lxd/endpoints/vsock.go
lxd/instance/drivers/driver_qemu.go

Fixes https://github.com/lxc/lxd/issues/11187 
The output of the vsock's `Addr().String()` was incompatible with `fmt.Sscanf(addr, "host(%d):%d"` pattern when nesting (as the "host" part became "vm").
Rather than account for the various output patterns I just extracted the underlying context ID and port directly using type smuggling.

Instance: Fix VM vsock nesting regression
