- .github/labeler.yml
> github: Add API label to labeler

- lxd/fsmonitor/drivers/driver_fanotify.go
Signed-off-by: Christian Brauner <brauner@kernel.org>
> fsmonitor: fixes

- .gitignore
- lxd-user/lxd.go
- lxd-user/main.go
- lxd-user/main_daemon.go
- lxd-user/proxy.go
- lxd/main_init.go
- lxd/main_init_auto.go
- lxd/main_init_interactive.go
- lxd/util/storage.go
This introduces the `lxd-user` daemon that will be primarily used by Linux distributions wanting easy on-demand LXD setup for multi-user systems.
> Introduce the `lxd-user` daemon

- lxd-user/main_daemon.go
- lxd-user/proxy.go
Rather than relying on heavy-handed locks, rely on atomic operations.
Signed-off-by: Christian Brauner <brauner@kernel.org>
> lxd-user: use atomic operations

- lxc/main.go
- lxd-user/lxd.go
- lxd-user/main_daemon.go
- lxd-user/proxy.go
> lxd-user: More integration bits

- go.mod
- go.sum
- lxd/device/device_utils_network.go
- lxd/device/nic_routed.go
When adding a routed nic device, check that the given ip address is
not in use during input validation via ping.
Closes #9547
> lxd/device: Adds arp check for nic routed device.

- doc/installing.md
> doc: Adds note about newuidmap to machine setup.

- lxd/instance_put.go
- test/suites/projects.sh
> lxd/projects: Use expanded devices/config when checking for limits

- client/interfaces.go
- client/lxd_instances.go
- lxc/info.go
- lxc/list.go
Let's make use of the new `?recursion=1` that @presztak introduced recently and make some of our CLI tools significantly faster in the process :)
> Introduce GetInstanceFull

- lxd/patches.go
Previous version of this patch attempted to rename files based on
the config properties of each instance. This was error prone and may
have led to errors. This patch wipes and recreates all of them using an
established method.
See https://github.com/lxc/lxd/pull/9790#discussion_r785232013 and relation to #9719.
> lxd: Refresh all dnsmasq hosts during patch.

- .sphinx/_static/custom.css
- README.md
- SECURITY.md
- doc/authentication.md
- doc/index.md
- doc/operation.md
- doc/projects.md
- doc/security.md
Clean up and extend the contents of SECURITY.md and doc/security.md.
> Security docs

- doc/instances.md
- lxd/device/device_utils_network.go
- lxd/device/nic_bridged.go
- shared/validate/validate.go
- test/suites/container_devices_nic_bridged_vlan.sh
Signed-off-by: Ricky Yu lijierickyyu@gmail.com.
Resolves #9560.
> Enable VLAN ranges in vlan.tagged

- lxd/device/device_utils_network.go
- shared/validate/validate.go
> Align ParseNetworkVLANRange with ParseUint32Range

- lxd/networks.go
> lxd: Use projectParam function in networkStateGet.

- doc/api-extensions.md
- doc/storage.md
- lxd/storage/drivers/driver_zfs.go
- lxd/storage_pools_config.go
- shared/version/api.go
> Add option to not export ZFS pool on shutdown

- lxd-agent/metrics.go
> lxd-agent: Fix bad network metric

- doc/api-extensions.md
- doc/storage.md
- lxd/storage/drivers/driver_zfs.go
- lxd/storage/drivers/driver_zfs_volumes.go
- lxd/storage_pools_config.go
- scripts/bash/lxd-client
- shared/version/api.go
> ZFS reservation

- lxd/storage/drivers/driver_btrfs_volumes.go
- lxd/storage/drivers/driver_zfs_volumes.go
Defers `revert.Fail` to simplify error handling. Returns a clone of the reverter after deferring `revert.Success`.
See https://github.com/lxc/lxd/pull/9833#discussion_r793504207
> lxd/storage/drivers: Fixes reverter usage.

- doc/api-extensions.md
- doc/storage.md
- lxd/storage/drivers/driver_zfs.go
- lxd/storage/drivers/driver_zfs_utils.go
- lxd/storage/drivers/driver_zfs_volumes.go
- lxd/storage_pools_config.go
- shared/version/api.go
> Option to configure the ZFS block size on volumes

- doc/faq.md
- doc/security.md
Some quick copy edits and some added links in the FAQ.
> doc: quick cleanup of FAQ

- lxd/instance/drivers/driver_lxc.go
> lxd/instance/metrics: Fix incorrect memory metrics

- doc/api-extensions.md
- lxc/config_trust.go
- lxc/console.go
- lxd/certificates.go
- shared/api/cluster.go
- shared/util.go
This is a mix of small fixes I've piled up or copied from #9816 which can already get reviewed/merged on their own.
> Varied fixes (console, certificate, trust store)

- lxd-agent/metrics.go
> lxd-agent: Fix bad copy/paste

- lxd-agent/server.go
- lxd/daemon.go
> lxd/daemon: Fix http response error typos

- lxd/main_init_interactive.go
> lxd/main_init_interactive: Add missing :

- lxc/console.go
This moves the user cancelation to its own channel and has the goroutine
monitor for both server side or client side cancelation.
Closes #9910
> lxc/console: Don't crash on manual disconnect

- lxd/instance_console.go
- lxd/network_acls.go
- lxd/response/response.go
> lxd/response: Rename FileModify to FileModified

- lxd/cgroup/init.go
> lxd/cgroup: Fix bad cpuset check

- lxd/instance/drivers/driver_qemu.go
> lxd/instance/qemu: Allow live update of cluster.evacuate

- lxd/db/certificate_projects.mapper.go
- lxd/db/generate/db/method.go
> lxd/db/generate: Fix bad loop logic

- lxd/instance/drivers/driver_lxc.go
> lxd/instance/lxc: Use contextual logger in Metrics

- lxd/daemon.go
- lxd/db/warnings_types.go
- lxd/warnings/warnings.go
And a couple of minor improvements/cleanups.
> Warnings: Fix logic bug in matching entityID in resolve and delete warning functions

- .sphinx/_static/custom.css
- .sphinx/_templates/footer.html
The footer in Furo has been updated (see
https://github.com/pradyunsg/furo/commit/29d65fdb8c0d9ab760c6c50771975e44b4978a39
).
Adapt our footer accordingly.
> doc: fix the footer

- lxd/apparmor/archive.go
- lxd/archive/archive.go
- lxd/storage/utils.go
Fixes issues introduced by https://github.com/lxc/lxd/pull/9906
> Image: Fix regressions in image unpack

- grafana/LXD.json
https://grafana.com/grafana/dashboards/15726
Fixes #9978
> Add the Grafana dashboard (15726)

- lxd/bgp/server.go
> lxd/bgp: Fix RemovePrefixByOwner when multiple matches

- client/lxd.go
- lxd/instance/drivers/driver_lxc.go
- lxd/instance/drivers/driver_qemu.go
- shared/tcp/tcp_timeouts.go
And some other small improvements.
> shared: Update ExtractConn to detect net.TCPConn

- lxd/device/disk.go
- lxd/instance/drivers/driver_qemu.go
> Disk: Storage the storage pool inside device to avoid repeated DB queries

- doc/instances.md
- doc/network-acls.md
- doc/networks.md
Rework the network ACLs documentation.
> Improve network ACLs documentation

- doc/network-forwards.md
- doc/networks.md
Update the network forwards documentation to be clearer and more task based.
> Improve network forwards documentation

- lxd/instance/drivers/driver_qemu.go
By giving advice on how to disable it.
Something I notice whilst watching https://www.youtube.com/watch?v=EthK-8hm_fY
> VM: Improve secureboot needs to be disabled error

- lxd/network/openvswitch/ovn.go
Recent versions of OVN introduce support for routers having multiple routing tables.
This changed the output of `ovn-nbctl lr-route-list`.
This PR updates `LogicalRouterRoutes` to support both the old and new output formats.
Right now we just ignore non-main routing tables as we don't use them.
This also allows us to gracefully support older versions of ovn that don't have support for multiple router routing tables.
> Network: Update OVN LogicalRouterRoutes to support recent versions of ovn

- lxd/apparmor/archive.go
> lxd/apparmor: Handle missing paths

- test/suites/container_devices_nic_bridged_filtering.sh
a6a6c8c7e95efc8b832ce9042c4e1e893ef7896b introduced a new filtering test
which relies on br_netfilter being loaded but added it prior to the test
checking for and loading br_netfilter causing failures on any system
which didn't have br_netfilter loaded already.
> tests: Fix ordering in bridge filtering test

- lxd/daemon.go
- lxd/db/storage_volume_snapshots.go
- lxd/instance.go
- lxd/storage/backend_lxd.go
- lxd/storage_volumes_snapshot.go
> Prevent concurent snapshot and snapshot expiry for a volume

- client/lxd_instances.go
- test/suites/filemanip.sh
Also update file manipulation tests to use projects.
> client: Avoid connecting twice in rawSFTPConn

- lxd/cluster/upgrade.go
> Cluster: Improve logging in triggerUpdate

- test/includes/net.sh
- test/suites/container_devices_nic_bridged.sh
- test/suites/container_devices_nic_bridged_filtering.sh
- test/suites/container_devices_nic_ipvlan.sh
- test/suites/container_devices_nic_p2p.sh
- test/suites/container_devices_nic_routed.sh
Adds function to wait for DAD and uses it wherever possible.
Closes #10053.
> Tests: Add function to wait for duplicate address detection

- lxd/storage/utils.go
> Storage: Prevent white space in storage pool names

- .sphinx/_extensions/youtube-link.py
- .sphinx/_static/custom.css
Small improvements to the YouTube extension.
> Youtube links

- lxd/instance/drivers/driver_lxc.go
> lxd/instance/lxc: Handle long forkfile socket paths

- shared/util_linux.go
If the xattr (list) size reported for a file is larger than the
actual size, this should not be considered an error, since the
allocated buffer will be large enough to hold the actual xattrs
returned, and is only a temporary allocation in any case.
Signed-off-by: Andreas Dilger <adilger@dilger.ca>
> shared/util/linux: only complain on xattr size increase

- lxd/storage/backend_lxd.go
> Storage: Replaces bespoke revert with revert package

- lxd/networks.go
> Network: Don't keep trying to start removed degraded networks

- .github/workflows/test.yml
- doc/clustering.md
- lxd/api_internal.go
- lxd/network/driver_ovn.go
This fixes a number of small issues found while working on #9347
> Various small fixes

- grafana/LXD.json
> grafana: Add missing datasource field

- doc/api-extensions.md
- doc/clustering.md
- lxd/daemon.go
- lxd/db/node.go
- lxd/network/driver_ovn.go
- lxd/networks.go
- lxd/networks_utils.go
- shared/version/api.go
> Introduce OVN chassis role

- test/suites/clustering.sh
- test/suites/image.sh
Following on from https://github.com/lxc/lxd/pull/10136
> Image: Fix refresh tests

- doc/network-acls.md
- doc/network-zones.md
Updated and clarify the network zones documentation.
> Network zones documentation

- lxd/device/device_utils_usb_events.go
- lxd/device/usb.go
- lxd/instance/drivers/driver_qemu.go
- lxd/instance/drivers/driver_qemu_templates.go
- lxd/instance/drivers/qmp/commands.go
This adds support for USB hotplugging.
> Support USB hotplugging

- client/interfaces.go
- client/lxd.go
- client/lxd_containers.go
- client/lxd_images.go
- client/lxd_instances.go
Signed-off-by: 745150400 <745150400@qq.com>
> client: add function useCurrentServer instead of "r == source"

- lxd/certificates.go
- lxd/cluster/info.go
- lxd/db/db.go
- lxd/main_activateifneeded.go
- lxd/operations/operations.go
- test/suites/pki.sh
- test/suites/tls_restrictions.sh
This does a bit more of DB cleanup and also adds a check for RSA certificates.
> Pre-5.0 fixes

- lxd/storage/drivers/driver_btrfs_utils.go
> lxd/storage/btrfs: Fix usage nested

- lxd/instance/drivers/driver_qemu.go
With this change, the -bios or -kernel options inside of raw.qemu will
cause LXD to log a warning message and then proceed to disable the
normal firmware setup.
This allows for booting LXD off of an external firmware file or directly
into a specific kernel. Such firmware or kernel will likely need a
matching raw.apparmor entry so that QEMU can actually access them.
> lxd/instance/qemu: Allow using external firmware or kernel

- lxd/instance/drivers/driver_qemu.go
> lxd/instance/qemu: Tweak warning on -bios/-kernel

- doc/howto/network_bgp.md
- doc/instances.md
Updates to https://linuxcontainers.org/lxd/docs/master/howto/network_bgp/
> Lxd 100 network bgp

- lxd/migration/wsproto.go
- lxd/storage/backend_lxd.go
- lxd/migration/wsproto: Check websocket argument
- lxd/storage/backend: Fix VolumeDBDelete revert
> Miscellaneous fixes

- lxd/instance/drivers/driver_lxc.go
- lxd/instance/drivers/driver_qemu.go
- lxd/instance/operationlock/operationlock.go
Closes https://github.com/lxc/lxd/issues/10081
> Introduction operationlock around Update

- doc/explanation/networks.md
- doc/howto/network_acls.md
- doc/howto/network_bgp.md
- doc/howto/network_bridge_firewalld.md
- doc/howto/network_bridge_resolved.md
- doc/howto/network_forwards.md
- doc/howto/network_ovn_peers.md
- doc/howto/network_ovn_setup.md
- doc/howto/network_zones.md
- doc/reference/network_bridge.md
- doc/reference/network_external.md
- doc/reference/network_macvlan.md
- doc/reference/network_ovn.md
- doc/reference/network_physical.md
- doc/reference/network_sriov.md
- doc/substitutions.yaml
Update the documentation pages about network types to make them consistent and up-to-date.
> Network types documentation

- lxd/apparmor/network_dnsmasq.go
- lxd/fsmonitor/drivers/driver_fsnotify.go
- lxd/instance/drivers/driver_lxc.go
> Properly handle nesting a manually built LXD 

- doc/api-extensions.md
- doc/server.md
- lxd/cluster/config.go
- lxd/device/device_common.go
- lxd/device/nic_bridged.go
- lxd/device/nic_ipvlan.go
- lxd/device/nic_macvlan.go
- lxd/device/nic_ovn.go
- lxd/device/nic_p2p.go
- lxd/device/nic_routed.go
- lxd/network/network_utils.go
- shared/version/api.go
> Add global config option instances.nic.host_name

- test/suites/container_devices_nic_bridged.sh
> tests: Add test for instances.nic.host_name

- lxd/storage/drivers/driver_zfs.go
- lxd/storage/drivers/driver_zfs_volumes.go
- lxd/storage/drivers/zfs: Check for encryption
- lxd/storage/drivers/zfs: Handle encrypted send
> lxd/storage/drivers/zfs: Use -w flag with `zfs send` if possible

- client/doc.go
- shared/api/doc.go
- shared/subprocess/bgpm_test.go
This updates a few files to be better handled by the newer godoc.
The changes were generated by gofmt from tip.
We however can't do a full run because of https://github.com/go-swagger/go-swagger/issues/2759
> Comment updates for upcoming godoc/gofmt changes

- lxd/instances_post.go
- lxd/migrate.go
- lxd/migrate_instance.go
- lxd/migrate_storage_volumes.go
- lxd/storage_volumes.go
> Migration: Improve errors returned when failing to read control message 

- lxd/cluster/connect.go
- lxd/instance_console.go
- lxd/instance_exec.go
- lxd/instance_post.go
- lxd/instance_sftp.go
> LXD: Updates ConnectIfInstanceIsRemote to return client preconfigured with instance's project

- lxd-agent/main_agent.go
> lxd-agent: Fix trans= handling

- client/interfaces.go
- client/lxd_server.go
> client: Add GetMetrics

- lxd/instance/drivers/driver_qemu.go
- lxd/instance/drivers/driver_qemu_templates.go
Fixes #10275
Fixes regression caused by https://github.com/lxc/lxd/pull/10262
> VM: Only attempt to open NVRAM file on UEFI architectures

- lxd/cluster/gateway.go
A blocked request can use the whole context time budget leading to the
other nodes not being contacted to determine the leader resulting in a `RAFT cluster is unavailable` error.
I'm not sure why a single request could use the whole time budget though, is probably interesting to investigate further.
Signed-off-by: Mathieu Borderé <mathieu.bordere@canonical.com>
> Cluster: Separate, smaller timeout for client leader request

- lxd/storage/drivers/driver_zfs_volumes.go
- test/suites/migration.sh
> lxd/storage/drivers/zfs: Fix optimized refresh in migration

- lxd/network/zone/zone.go
- test/suites/network_zone.sh
> Network: Improve network zone name validation

- test/includes/lxd.sh
The same logic is used in spawn_lxd()
> test: restore "set -x" at the end of respawn_lxd()

- lxd/instance/drivers/driver_qemu.go
> lxd/instance/qemu: Don't timeout during migration

- lxd/instance/drivers/driver_qemu.go
- lxd/storage/drivers/driver_lvm_utils.go
- lxd/storage/drivers/driver_lvm_volumes.go
- lxd/storage/drivers/generic_vfs.go
- test/suites/migration.sh
> Storage: Fix restoring non-thin LVM block volumes

- lxd/storage/utils.go
> lxd/storage: Allow parallel writes in qemu-img

- lxd/device/device_utils_disk.go
- lxd/storage/drivers/driver_cephfs.go
- lxd/storage/drivers/utils_ceph.go
Related to https://discuss.linuxcontainers.org/t/unable-to-add-device-disk-cephfs/13903
> Improve ceph.conf parser

- doc/howto/network_bridge_resolved.md
Update the documentation on how to integrate with systemd-resolved.
> Doc: integrate with systemd-resolved

- lxd/project/permissions.go
> lxd/project: Allow sysinfo intercept

- lxd/device/device_utils_disk.go
Paths longer than 107 characters would cause an error in bind.
This fixes the issue by using an fd workaround which shortens the path.
Fixes #10312.
> lxd/device/disk: Handle long paths in virtiofsd

- lxc/file.go
> lxc/file: Fix edit in snap environment

- doc/howto/network_bgp.md
- doc/metrics.md
> doc: Fix typos

- doc/metrics.md
Signed-off-by: Pietro Marini <pietro.marini@nextcloud.com>
> server.crt referred to as lxd.crt in the prometheus config file

- .github/workflows/woke.yml
- doc/api-extensions.md
- doc/authentication.md
- doc/contributing.md
- doc/doc-cheat-sheet.md
- doc/instances.md
- doc/rest-api.md
- doc/security.md
Add a GitHub action that runs woke on the documentation files.
> Inclusive language

- doc/howto/network_ovn_peers.md
Rework the documentation about peer routing relationships.
> Peer routing relationships

- doc/metrics.md
Documentation for https://discuss.linuxcontainers.org/t/question-on-lxd-dashboard-values/14003/5
> doc: document how to handle SAN vs target name mismatch in Prometheus sample

- lxc/list.go
> lxc/list: Don't skip extra info when name filtering

- doc/howto/network_bridge_firewalld.md
- doc/reference/network_bridge.md
Update the existing documentation and add information for UFW.
> doc: update firewall configuration documentation

- lxd/project/permissions.go
> lxd/project: Fix bad error on invalid instance type

- lxd/storage/drivers/driver_ceph_volumes.go
- lxd/storage/drivers/driver_lvm_volumes.go
- lxd/storage/drivers/driver_zfs_volumes.go
Makes the `UnmountVolume` function more closely aligned in the storage drivers.
> Storage: Align UnmountVolume in storage drivers

- lxd/resources/cpu.go
> lxd/resources: Handle negative CPU indexes

- doc/instances.md
- lxd/instance/drivers/driver_qemu.go
- shared/instance.go
> Instance: Regenerate running VM NVRAM on next start if profile `security.secureboot` setting is changed

- lxc/profile.go
- test/suites/projects.sh
> lxc/profile: Add cross-project copy

- lxd/instance.go
> lxd/instance: Fix auto-snapshot on restricted projects

- lxd-agent/state.go
> Fix cpu and memory state for VMs

- lxd/instance/drivers/driver_qemu.go
> lxd/instance/qemu: Fix ceph username key

- doc/howto/network_acls.md
> doc: add link to YouTube video for network ACLs

- lxc/storage_volume.go
- lxd/cluster/heartbeat.go
- test/suites/storage_local_volume_handling.sh
> Storage: Fix copy/move of custom volume snapshot so that its config is used for new volume

- lxd/instance/drivers/driver_qemu.go
> lxd/instance/drivers/qemu: Fix ceph conf filename

- lxd/storage/backend_lxd.go
- lxd/storage/drivers/driver_btrfs_volumes.go
- lxd/storage/drivers/driver_zfs_volumes.go
- lxd/storage/drivers/generic_vfs.go
Separates some of the error handling fixes @markylaing found in https://github.com/lxc/lxd/pull/10428
> Storage: Adds additonal error handling

- test/suites/migration.sh
> tests: Test stateless migration

- .sphinx/_extra/versions.json
- .sphinx/_static/custom.css
- .sphinx/_static/version-switcher.js
- .sphinx/_templates/sidebar/variant-selector.html
- .sphinx/conf.py
See the main commit for a detailed explanation.
Need to update some paths to (hopefully ;) ) get this working in the preview, and again to prepare for the final docs, so DNM for now.
> Version switcher

- doc/howto/network_bgp.md
> doc: add a link to the YouTube video on BGP

- doc/api-extensions.md
- doc/explanation/storage.md
- doc/faq.md
- doc/instances.md
- doc/migration.md
- doc/reference/storage_btrfs.md
- doc/reference/storage_ceph.md
- doc/reference/storage_cephfs.md
- doc/reference/storage_drivers.md
- doc/reference/storage_lvm.md
- doc/reference/storage_zfs.md
No content updates, just some quick fixes for consistency and small mistakes.
> Quick fixes to storage docs

- lxd/network/driver_bridge.go
- test/suites/container_devices_nic_bridged.sh
> lxd/network: Disable IPv6 on bridges with no IPv6 address

- lxd/main_forkfile.go
The use of CompareAndSwap from the atomic package is causing a large
number of EAGAIN during the accept phase of connection handling.
This in turn results in a number of "Connection reset by peer".
Instead change the logic to rely on more traditional locks and counters,
combined with a grace period of 5s, this gives us a pretty solid
auto-exit behavior.
Closes #10448
> lxd/main_forkfile: Change counting model

- lxd/instance/drivers/driver_lxc.go
> lxd/instance/lxc: Stop forkfile on restore

- .sphinx/_static/custom.css
- doc/explanation/storage.md
- doc/reference/storage_drivers.md
Extend and rewrite the "About storage" page, adding information about storage volumes.
> Storage doc

- doc/reference/storage_zfs.md
Update based on a forum post. Also added a link to the post.
> doc: update info on how to grow a ZFS pool

- lxd/instance/drivers/driver_qemu.go
- lxd/instance/drivers/driver_qemu_config_test.go
- lxd/instance/drivers/driver_qemu_templates.go
Last batch of template conversions
> Instance: convert remaining qemu templates

- doc/explanation/storage.md
- doc/howto/storage_create_pool.md
- doc/reference/storage_btrfs.md
- doc/reference/storage_ceph.md
- doc/reference/storage_cephfs.md
- doc/reference/storage_dir.md
- doc/reference/storage_drivers.md
- doc/reference/storage_lvm.md
- doc/reference/storage_zfs.md
- doc/storage.md
Add general information on how to create a storage pool and move the examples from the reference docs to the how to. 
Also clean up and align the example commands, and add commands for CephFS.
> How to create a storage pool

- doc/explanation/storage.md
- doc/howto/storage_add_volume.md
- doc/howto/storage_create_pool.md
- doc/instances.md
- doc/storage.md
Add instructions for creating a storage volume and attaching it to an instance.
Also clarify how storage pools work in a LXD cluster.
> How to add storage volumes

- lxd/archive/archive.go
- shared/util.go
> Restore unprivileged archive unpack behavior

- lxd/apparmor/instance.go
- lxd/apparmor/instance_qemu.go
- lxd/instance/drivers/driver_qemu.go
> lxd/instance/qemu: Support running inside a LXD container

- lxd/operations/operations.go
> lxd/operations: Fix crash on nil state

- lxd/cgroup/init.go
> lxd/cgroup: Better handle broken CGroupV2 setups

- lxd/migrate_instance.go
- lxd/migrate_storage_volumes.go
- lxd/migration/migration_volumes.go
- lxd/storage/backend_lxd.go
- lxd/storage/drivers/driver_btrfs_volumes.go
- lxd/storage/drivers/driver_zfs_volumes.go
- test/suites/migration.sh
- lxd/migrate_storage_volumes: Make sender aware of refresh
- lxd/migration: Add Refresh to InfoResponse
- lxd/storage: Return InfoResponse from migrationIndexHeaderSend
- lxd/storage: Use Refresh from InfoResponse
- lxd/storage/backend: Add refresh arg to migrationIndexHeaderReceive
Closes  #10186
> Handle custom volume refresh properly

- .github/workflows/tests.yml
> github: Only run dependencies check on PR

- test/suites/config.sh
> tests: Skip EDITOR=cat when not a terminal

- doc/howto/network_forwards.md
> doc: add link to video about network forwards

- doc/explanation/storage.md
- doc/howto/storage_add_volume.md
- doc/howto/storage_configure.md
- doc/howto/storage_list.md
- doc/howto/storage_move.md
- doc/storage.md
Add and expand how-to guides for working with storage volumes.
> Storage doc: add howtos

- lxd/network/acl/acl_load.go
- lxd/network/acl/acl_ovn.go
- lxd/network/acl/driver_common.go
> Fix ACL UsedBy Instance type assertion

- lxd/device/disk.go
> lxd/device/disk: Fix ceph creds on custom volumes

- .github/dependabot.yml
> github: Disable dependabot labels

- lxd/network/openvswitch/ovn.go
> lxd/network/ovs: Add timeout to nbctl/sbctl

- shared/logger/syslog_linux.go
> shared/logger: Filter event levels for syslog

- doc/image-handling.md
> doc: add link to YouTube video about image handling

- Makefile
- test/lint/client-imports.sh
- test/lint/i18n-up-to-date.sh
- test/lint/mixed-whitespace.sh
- test/lint/negated-is-bool.sh
- test/lint/newline-after-block.sh
- test/lint/no-oneline-assign-and-test.sh
- test/lint/no-short-form-imports.sh
- test/lint/trailing-space.sh
Address the feedback left in #10617 after it was merged and a few more things.
> Tiny lint fixes

- .sphinx/_static/custom.css
- doc/howto/network_ovn_setup.md
Fix the OVN configuration for the cluster setup.
And also clean up the nested list, which was kinda hacked - which doesn't work when adding an additional bullet list. ;)
> Fix OVN docs

- doc/api-extensions.md
- doc/explanation/storage.md
- doc/howto/storage_backup.md
- doc/howto/storage_create_pool.md
- doc/reference/storage_btrfs.md
- doc/reference/storage_ceph.md
- doc/reference/storage_cephfs.md
- doc/reference/storage_dir.md
- doc/reference/storage_drivers.md
- doc/reference/storage_lvm.md
- doc/reference/storage_zfs.md
- doc/substitutions.yaml
The section in the ZFS docs about growing the pool will be moved out in a separate PR.
> doc: update storage driver reference

- doc/howto/network_load_balancers.md
- doc/networks.md
- doc/reference/network_ovn.md
Small fixes to the load balancer documentation.
> Load balancer fixes

- lxd/resources/pci_vpd.go
> lxd/resources: Better handle invalid VPD

- doc/container-environment.md
- doc/dev-lxd.md
- doc/environment.md
- doc/instances.md
- doc/requirements.md
- doc/server.md
> doc: Fix use of setup/set up

- doc/api-extensions.md
- lxd-agent/api_1.0.go
- lxd-agent/daemon.go
- lxd-agent/devlxd.go
- lxd-agent/main_agent.go
- lxd/api.go
- lxd/api_vsock.go
- lxd/daemon.go
- lxd/db/instances.go
- lxd/devlxd.go
- lxd/endpoints/endpoints.go
- lxd/endpoints/endpoints_test.go
- lxd/endpoints/vsock.go
- lxd/instance/drivers/driver_qemu.go
- lxd/instance/drivers/qmp/monitor.go
- lxd/instance/instance_interface.go
- lxd/response/response.go
- lxd/vsock/vsock.go
- shared/api/lxd-agent.go
- shared/api/server.go
- shared/version/api.go
https://discuss.linuxcontainers.org/t/lxd-bidirectional-vsock-interface-for-vms/14066
> Bidirectional vsock interface

- doc/explanation/storage.md
- doc/howto/storage_create_instance.md
- doc/howto/storage_resize.md
- doc/reference/storage_btrfs.md
- doc/reference/storage_lvm.md
- doc/reference/storage_zfs.md
- doc/storage.md
Add how-to guides for launching instances in a specific pool and resizing storage.
> Doc: Two additional storage how-tos

- lxd/storage/drivers/driver_lvm_utils.go
The LVM thin volume data used percentage value is only available when instance is running.
> Storage: Fix ParseFloat warnings when instance on LVM thinpool not running

- lxd/resources/network_ethtool.go
> lxd/resources: Better handle ethtool errors

- lxd/instance/drivers/driver_qemu.go
> lxd/instance/drivers: Handle QEMU I/O errors

- lxd/instance/drivers/driver_qemu.go
Also improve logging messages.
> VM: Fix instance reference leak in getMonitorEventHandler

- lxd/instance/drivers/driver_qemu.go
- lxd/instance/drivers/qmp/monitor.go
- lxd/instance/drivers: Rename LXD-AGENT-READY to LXD-AGENT-STARTED
- lxd/instance/drivers/qmp: Rename agentReady to agentStarted
> lxd/instance/drivers: Rename agentReady to agentStarted

- lxd/db/generate/db/method.go
> Fix v1 generator code style

- lxd/api_cluster.go
- lxd/backup.go
- lxd/certificates.go
- lxd/cluster/config/config.go
- lxd/daemon_images.go
- lxd/db/instances.go
- lxd/db/node.go
- lxd/device/device_common.go
- lxd/device/nic_ovn.go
- lxd/devices.go
- lxd/events.go
- lxd/images.go
- lxd/instance.go
- lxd/instance/drivers/driver_common.go
- lxd/instance/instance_utils.go
- lxd/instances_post.go
- lxd/network/driver_bridge.go
- lxd/network/network_utils_sriov.go
- lxd/network/openvswitch/ovn.go
- lxd/profiles_utils.go
- lxd/storage/backend_lxd.go
- lxd/storage/utils.go
- lxd/storage_pools.go
Various DB optimisations:
- Instance list optimisations.
- Config loading optimisations.
- Don't query for local server name and use the cached server name.
> DB: Query optimisations

- doc/reference/storage_zfs.md
> Remove redundant LXD before ZFS pool

- doc/reference/storage_lvm.md
> Doc: Fix LXD volume group to LVM

- lxd/api_project.go
- lxd/db/cluster/open.go
- lxd/db/cluster/projects.go
- lxd/db/network_forwards.go
- lxd/db/network_load_balancers.go
- lxd/network/driver_bridge.go
- lxd/network/driver_ovn.go
- lxd/network_forwards.go
- lxd/network_load_balancers.go
This bug isn't actually reachable at the moment, but if we ever add member specific load balancers it becomes reachable.
> DB: Fix bug in GetNetworkLoadBalancers and other DB query tweaks

- lxd/storage/drivers/driver_lvm_volumes.go
When the storage pool has `volume.stripes*` settings specified.
These should not be copied into new volume config when the pool is a thin pool (but should still be allowed on the pool itself so that the initial thinpool LV can use them).
This fixes a regression introduced by https://github.com/lxc/lxd/pull/10613
> Storage: Fix "lvm.stripes cannot be used with thin pool volumes" error

- lxd/api_cluster.go
- lxd/api_project.go
- lxd/certificates.go
- lxd/images.go
- lxd/lifecycle/storage_pool.go
- lxd/network_acls.go
- lxd/network_forwards.go
- lxd/network_load_balancers.go
- lxd/network_peer.go
- lxd/network_zones.go
- lxd/network_zones_records.go
- lxd/networks.go
- lxd/profiles.go
- lxd/storage_pools.go
- lxd/storage_volumes.go
Changes based on discussion https://github.com/lxc/lxd/pull/10701#issuecomment-1197374257
> LXD: Update SyncResponseLocation URLs to include project parameter where appropriate

- doc/api-extensions.md
- doc/dev-lxd.md
- lxd/daemon.go
- lxd/db/instances.go
- lxd/devlxd.go
- lxd/instance/drivers/driver_lxc.go
- lxd/instance/drivers/driver_qemu.go
- shared/api/status_code.go
- shared/instance.go
- shared/version/api.go
- test/deps/devlxd-client.go
- test/suites/devlxd.sh
https://discuss.linuxcontainers.org/t/lxd-instance-ready-state/14657
> Add instance Ready state

- lxd-agent/devlxd.go
> lxd-agent: Handle PATCH /1.0 in devlxd

- .sphinx/requirements.txt
- doc/clustering.md
- doc/howto/network_zones.md
- doc/instances.md
- doc/production-setup.md
- doc/projects.md
- doc/reference/network_bridge.md
- doc/reference/network_macvlan.md
- doc/reference/network_ovn.md
- doc/reference/network_physical.md
- doc/reference/storage_btrfs.md
- doc/reference/storage_ceph.md
- doc/reference/storage_cephfs.md
- doc/reference/storage_dir.md
- doc/reference/storage_lvm.md
- doc/reference/storage_zfs.md
- doc/security.md
- doc/server.md
> doc: mark up default values correctly 

- lxd/network_forwards.go
- lxd/network_load_balancers.go
This functionality is currently missing compared to network zones.
> Network: Support patching forwarder and load balancer configs

- README.md
- doc/index.md
Update the landing page for the documentation to be more in line with other documentation sites.
> Doc landing page

- shared/util_linux.go
- shared/validate/validate.go
Also adds `validate.IsRequestURL` function.
> Util: Adds detection of `RunError` type to `ExitStatus` function

- test/suites/container_devices_nic_bridged.sh
- test/suites/container_devices_nic_bridged_acl.sh
- test/suites/container_devices_nic_bridged_filtering.sh
- test/suites/container_devices_proxy.sh
- test/suites/network.sh
To try and improve reliability of tests.
Also adds retries to udhcp requests.
> Test: Order tweaks for proxy device tests

- doc/reference/storage_dir.md
- doc/reference/storage_lvm.md
- doc/reference/storage_zfs.md
I'm not familiar with LVM so please let me know if `LVM pool` is wrong or confusing.
> doc/reference: improve description of storage  option

- .github/workflows/tests.yml
> workflows: Adds edge ppa's and removes make deps step.

- client/lxd_cluster.go
- go.mod
- go.sum
- lxd/cluster/membership.go
- lxd/cluster/membership_test.go
- lxd/db/cluster.go
Also:
- Improve error message in membershipCheckClusterStateForAccept.
- Use `query()` rather than `queryStruct()` in DeleteClusterMember (aligns with other delete functions).
- Update go mod.
> URLs: Generate URLs  in GetClusterGroupURIs correctly

- lxd/cgroup/abstraction.go
Close #10746
Will set the issue to close and we can reopen when the issue occurs with the improved errors.
> lxd/cgroup/abstractions: Improve errors from GetIOStats

- lxd/include/process_utils.h
- lxd/include/syscall_wrappers.h
- lxd/main_checkfeature.go
- lxd/main_forkmount.go
- lxd/main_forksyscall.go
- lxd/main_nsexec.go
- lxd/seccomp/seccomp.go
- shared/idmap/shift_linux.go
- shared/util_linux_cgo.go
> cgo: ensure that lxd wrappers don't conflict with libc provided wrapper

- lxd/storage/backend_lxd.go
- lxd/storage/drivers/utils.go
- lxd/storage/storage.go
- lxd/storage_pools.go
- test/includes/lxd.sh
Also lay foundation for adding bucket support to storage pool `UserBy` field.
> Storage: Don't use losetup --direct-io=off to support CentOS 7

- lxd-user/proxy.go
> lxd-user: Fix use with clusters

- lxd/db/storage_volumes.go
- lxd/storage/storage.go
- lxd/storage_volumes.go
- lxd/storage_volumes_snapshot.go
- lxd/storage_volumes_utils.go
- Adds `db.StorageVolume` and `db.StorageVolumeFilter` types (similar to those used by the DB generator for other entity types).
- One difference though is that `db.StorageVolume` embeds `api.StorageVolume` making type conversion easy.
- Adds filtering support to `GetStoragePoolVolumes()` and returns a slice of `db.StorageVolumes` for more flexibility (and to align forthcoming `GetStoragePoolBuckets()` function.
- Avoids unnecessary slice conversions in API `storagePoolVolumesGet` handler.
- Uses more efficient `GetStoragePoolVolume()` for single volume loading.
- Fixes bugs with missing `target` params and missing instances in `UsedBy` fields when using non-default projects.
> Storage: Volume list improvements

- lxd/db/cluster/open.go
- lxd/db/migration.go
Fixes a regression introduced by c6d0928b0f5ad63d8eb835d0ff454e14b4931b16
Closes #10776
> lxd/projects: Ensure default project has features.networks

- lxd/network/driver_common.go
> lxd/network: Fix BGP without hold time

- lxd/firewall/drivers/drivers_xtables.go
> Firewall: Use xtables locking in `NetworkApplyACLRules`

- lxd/daemon.go
- lxd/endpoints/endpoints.go
- lxd/node/config.go
Also improves socket binding/closing logging.
> Node: Removes inefficient convenience functions that load all node config unnecessarily

- lxd/storage/drivers/driver_cephobject_buckets.go
This way if the lxd-admin user is removed after the pool is created, it is automatically re-created on next bucket create.
> Storage: Ceate admin cephobject radosgw-admin user if missing in CreateBucket

- lxd/db/generate/db/method.go
> lxd/db/generate/db/method: Fix lxd-generate typo

- doc/howto/storage_backup_volume.md
> Doc: Fix typo in howto/storage_backup

- doc/server.md
> doc: backquote true and NO_PROXY in doc/server.md

- doc/cloud-init.md
> doc: backqoute cloud-init in doc/cloud-init.md

- doc/api-extensions.md
> doc: backquote mac in doc/api-extensions.md

- .sphinx/.wordlist.txt
- doc/faq.md
- doc/howto/import_machines_to_instances.md
- doc/installing.md
- doc/reference/storage_btrfs.md
- doc/reference/storage_lvm.md
- doc/storage.md
Several small, unrelated fixes to the docs - see the separate commits.
> Doc: several fixes

- lxd/instance/drivers/driver_lxc.go
- lxd/metrics/types.go
Pull request for the issue: https://github.com/lxc/lxd/issues/10820
> api: metric: lxd_cpu_seconds_total: fix help text, floats

- lxd/db/generate/db/stmt.go
Allows specifying the column name on which to join on. 
Works like this:
```go
type Service struct {
ID                  int
MemberID            int
Member              string `db:"primary=yes&join=internal_cluster_members.name-ON-member_id"`
Service             string `db:"primary=yes"`
}
```
> lxd/db/generate/db/stmt: Add joinon tag

- doc/api-extensions.md
- lxd/cgroup/abstraction.go
- lxd/instance/drivers/driver_lxc.go
- lxd/metrics/api.go
- lxd/metrics/metrics.go
- lxd/metrics/types.go
- shared/version/api.go
Added new metric for containers: lxd_cpus - The total number of CPUs.
> New lxd_cpu_effective_total metric

- doc/howto/storage_volumes.md
> doc/storage/volumes: add `--all-projects` to documentation

- lxd/apparmor/archive.go
> lxd/apparmor: Deref compress commands

- doc/index.md
> doc: add related links to the start page

- doc/metrics.md
> doc/metrics: add a list of provided metrics

- doc/howto/network_bgp.md
> doc/network/bgp: add some clarifications to the BGP docs

- lxc-to-lxd/main_migrate.go
If lxc.arch is linux32 or linux64, the architecture ID cannot be
determined as multiple architectures have the linux32 or linux64
personality. In this case, assume the native architecture.
This fixes #10865.
> lxc-to-lxd: Handle linux32 and linux64 arch personalities

- doc/reference/storage_dir.md
> doc/storage/dir: add link to the YouTube video

- doc/api-extensions.md
- doc/projects.md
- lxd/api_project.go
- lxd/network_forwards.go
- lxd/network_load_balancers.go
- lxd/network_peer.go
- lxd/networks.go
- lxd/project/permissions.go
- lxd/project/project.go
- shared/version/api.go
- test/suites/projects.sh
> Networks: Adds `restricted.networks.access` setting

- doc/howto/migrate_from_lxc.md
- doc/migration.md
> doc/migration: Document lxc-to-lxd tool

- doc/howto/move_instances.md
> doc/migration: clarify how to enable live migration for VMs

- lxc/config/config.go
- lxc/config/default.go
- lxc/config/file.go
> lxc: Fix panic when doing `lxc alias add` without existing config.yaml

- lxd/storage/s3/miniod/miniod.go
- Avoids any issues with directories created on the root volume by the filesystem intefering with MinIO.
- Allows easier changing of ownership/permissions later if we want to run MinIO as unprivileged user.
> Storage: Use a sub-directory for minio on storage volume

- go.mod
- go.sum
> gomod: Updates dependencies

- lxd/archive/archive.go
- lxd/device/device_utils_disk.go
- lxd/device/proxy.go
- lxd/device/tpm.go
- lxd/instance/drivers/driver_qemu.go
- lxd/network/driver_bridge.go
- shared/subprocess/bgpm_test.go
- shared/subprocess/manager.go
- shared/subprocess/proc.go
This will be useful if we want to run MinIO as an unprivileged user.
> LXD: Add context support to `subprocess` package

- .sphinx/_templates/footer.html
Update the footer to match what has been changed in the Furo theme: https://github.com/pradyunsg/furo/commit/8eba6499b812d7aeab2a99fcdf33e8bcb07b05fc
> doc: update footer to display correctly

- .sphinx/.wordlist.txt
- doc/explanation/performance_tuning.md
- doc/howto/benchmark_performance.md
- doc/howto/migrate_from_lxc.md
Adds a how-to guide for lxd-benchmark.
> How to benchmark performance

- doc/backup.md
- doc/explanation/storage.md
- doc/howto/storage_backup_volume.md
- doc/howto/storage_buckets.md
- doc/howto/storage_create_instance.md
- doc/howto/storage_move_volume.md
- doc/howto/storage_pools.md
- doc/howto/storage_volumes.md
- doc/image-handling.md
Some additions to the storage documentation:
- Link to storage volume video
- Information about special storage volumes
- Links between storage explanation and how tos
> Storage documentation

- .github/workflows/tests.yml
- .sphinx/conf.py
- Makefile
- README.md
- doc/doc-cheat-sheet.md
- doc/index.md
- doc/reference/storage_ceph.md
Enable the Sphinx link checker for the documentation and run it as part of the tests.
> Enable link checker for the documentation

- test/suites/container_devices_disk.sh
- test/suites/security.sh
> tests: Respect LXD_SHIFTFS_DISABLE

- lxd/cgroup/abstraction.go
- test/suites/security.sh
Allows additional metrics to be added to io.stat file without it failing.
Fixes #10953
Also includes shiftfs fix for test suite.
> Cgroup: Update GetIOStats to be more flexible

- doc/howto/network_bridge_firewalld.md
Signed-off-by: Johan Ehnberg <johan@molnix.com>
> doc: Allow forwarded traffic to the lxd bridge for proxy nat devices 

- lxd/storage/s3/miniod/miniod.go
So its clearer if the issue is a missing minio command.
> Storage: Expose minio start up error to client

- shared/instance.go
- shared/validate/validate.go
This validates cloud-init config keys, and ensures they are valid cloud-config or YAML.
> cloud-init schema validation

- lxd/device/nic_ovn.go
- lxd/network/driver_ovn.go
- lxd/network/network_utils.go
> Network: Adds duplicate address check for `ovn` NICs

- client/interfaces.go
- client/operations.go
See [How to wait client.Operation with timeout in Go? - LXD - Linux Containers Forum](https://discuss.linuxcontainers.org/t/how-to-wait-client-operation-with-timeout-in-go/15237)
> Add client.operation.WaitContext

- lxd/storage/drivers/driver_zfs.go
This relaxes the requirements introduced by 88f4ec56563ba07048947d590df9c606368bce5a so that now any existing datasets need not fail the pool mount if the policy cannot be applied to them.
Instead a warning is logged.
This is so any missing datasets are still created. And if there are active subdata sets mounted and the top level dataset has a historical mountpoint set that we don't try and unmount that top level dataset at mount time which can sometimes fail.
Reported from https://discuss.linuxcontainers.org/t/error-storage-pool-lxdpool-unavailable-on-this-server-after-update-to-lxd-5-6/15231
> Storage: Don't fail ZFS pool Mount if policy cannot be applied to existing datasets

- .sphinx/_templates/header.html
Documentation header should comply with new menu style on linuxcontainers.org 
See also https://github.com/lxc/linuxcontainers.org/pull/615
Signed-off-by: David Edler <david.edler@canonical.com>
> doc/header: update to new menu style for linuxcontainers.org

- lxd/apparmor/qemuimg.go
- Fixes QemuImg when using symlinks.
- Improves comments and error messages.
- Tidys defer call.
Fixes a regression caused by https://github.com/lxc/lxd/pull/10690
> AppArmor: Fix QemuImg when using symlinks

- lxd/storage/drivers/driver_zfs.go
> Storage: Fix incorrect ZFS mount dataset policy error check

- lxd/storage/utils.go
> lxd/storage/utils: Fix error in ImageUnpack

- lxd-agent/api_1.0.go
- lxd-agent/daemon.go
- lxd-agent/main_agent.go
- lxd/vsock/vsock.go
- lxd/vsock: Add ContextID()
- lxd-agent: Restart server on CID change
> lxd-agent: Restart server on CID change

- lxd/apparmor/qemuimg.go
Also uses consistent spacing in existing lines.
Fixes a regression caused by https://github.com/lxc/lxd/pull/10690
> AppArmor: Fix QemuImg policy to support snap

- lxd/instance/drivers/driver_qemu.go
> lxd/instance/drivers/driver/qemu: comment typo

- client/lxd_images.go
When encoding 2-part image into a multipart mime body.
Rather than creating a (potentially large) temporary file.
Fixes #10765
> Client: Updates CreateImage to stream files from disk to server

- doc/api-extensions.md
- shared/version/api.go
> api: Add internal_metrics API extension

- lxc/list.go
> lxc: Fix filtering in `lxc list` when using YAML output format

- doc/api-extensions.md
- doc/server.md
- lxc/config_trust.go
- lxd/certificates.go
- lxd/cluster/config/config.go
- shared/api/certificate.go
- shared/api/operation.go
- shared/version/api.go
- test/suites/remote.sh
Related to https://github.com/lxc/lxd/issues/10505
> Add remote token expiry

- doc/rest-api.yaml
- doc/server.md
- lxd/api_cluster.go
- lxd/daemon.go
- lxd/db/operationtype/operation_type.go
- lxd/tokens.go
Related to https://github.com/lxc/lxd/issues/10505
> Token expiry updates

- lxd/certificates.go
- lxd/cluster/connect.go
- shared/cert.go
This will be useful for adding trusted certificates via the go API.
> Export CertInfo to api.Certificate helper

- lxd/device/nic_bridged.go
- test/suites/container_devices_nic_bridged.sh
- Don't check if parent network has `dns.mode=none` as there cannot be conflicting DNS names in that case.
- Check the conflicting NIC instance is connected to same bridge VLAN.
> Device: Relax `bridged` NIC duplicate instance DNS name checks

- lxd/devlxd.go
> lxd: Sets Location field to hostname for GET /1.0 in devlxd API.

- doc/explanation/devices.md
- doc/explanation/instance_config.md
- doc/howto/instances_configure.md
- doc/howto/instances_create.md
- doc/howto/instances_manage.md
- doc/instances.md
- doc/profiles.md
- doc/reference/instance_options.md
Add instructions for managing and configuring instances and using profiles.
Still more how-tos to come. ;-)
> Add some how-to guides to the instances docs

- lxd/instance/drivers/driver_lxc.go
> lxd/instances/lxc: Fix build on MIPS

- lxd/devlxd.go
This changes devlxd in that it will return HTTP Forbidden if
`security.devlxd` is false. Previously, a bad agent could still have
retrieved devlxd information if the socket was present as the LXD never
checked whether or not it was turned on and always served the endpoints.
> devlxd: Do not return devlxd info if turned off

- .sphinx/.wordlist.txt
- doc/howto/instances_access_files.md
- doc/instances.md
> doc/instances: add instructions for accessing files

- doc/dev-lxd.md
Follow-up on commit 47c50839de
> doc: the location is set in responses from GET /1.0 in devlxd API

- doc/security.md
> doc/security: add YouTube link

- lxc/storage_volume.go
- lxd/cluster/resolve.go
Fixes regression introduced by https://github.com/lxc/lxd/commit/5a4172780b0bb8360f2819ae848c15620e6d264a
> lxc: Fix copying storage volume to remote from cluster member

- lxd/util/storage.go
> lxd/util: Skip cephobject in AvailableStorageDrivers

- doc/reference/devices_tpm.md
- lxd/device/tpm.go
- test/suites/container_devices_tpm.sh
> lxd/device/tpm: Expose tpmrm to the container

- test/includes/lxd.sh
- test/includes/setup.sh
- test/suites/backup.sh
- test/suites/basic.sh
- test/suites/clustering.sh
- test/suites/config.sh
- test/suites/console.sh
- test/suites/container_devices_nic_bridged_filtering.sh
- test/suites/idmap.sh
- test/suites/image.sh
- test/suites/image_auto_update.sh
- test/suites/image_prefer_cached.sh
- test/suites/kernel_limits.sh
- test/suites/remote.sh
Those are mostly replacing "useless use of" tools piped to other tools.
The one exception is the LXC driver version check which is more than "cosmetic".
> Test tweaks

- doc/remotes.md
Signed-off-by: anubisfup <axe3228@yandex.ru>
> docs: Added snap version directory for local remotes

- lxd/resources/network.go
> Resources: Ignore errors from ethtoolAddPortInfo

- .sphinx/.wordlist.txt
- doc/explanation/networks.md
- doc/howto/network_acls.md
- doc/reference/devices_disk.md
- doc/reference/devices_gpu.md
- doc/reference/devices_infiniband.md
- doc/reference/devices_nic.md
- doc/reference/devices_none.md
- doc/reference/devices_pci.md
- doc/reference/devices_proxy.md
- doc/reference/devices_tpm.md
- doc/reference/devices_unix_block.md
- doc/reference/devices_unix_char.md
- doc/reference/devices_unix_hotplug.md
- doc/reference/devices_usb.md
Clean up and make more consistent.
> doc/devices: Clean up the documentation for devices and device options

- lxd/device/disk.go
- lxd/instance/drivers/driver_qemu.go
- lxd/storage/drivers/driver_btrfs.go
- lxd/storage/drivers/driver_ceph.go
- lxd/storage/drivers/driver_dir.go
- lxd/storage/drivers/driver_lvm.go
- lxd/storage/drivers/driver_types.go
> lxd/storage: Disable io_uring on ZFS

- lxd/migrate_instance.go
Consider RBD transfer non-optimised.
Fixes regression caused by https://github.com/lxc/lxd/pull/11196
> Storage: Include ceph to ceph migration in multi sync mode

- doc/howto/instances_snapshots.md
> doc/instances: small clarifications to the snapshot documentation

- doc/reference/devices_nic.md
> doc/devices: Sort macvlan NIC device options in table

- lxd/daemon_images.go
- lxd/db/db_internal_test.go
- lxd/db/images.go
- lxd/instance.go
- lxd/instance/instance_utils.go
- lxd/instances_post.go
Part of the requirements in order to provide an expanded request to the instance placement scriptlet (https://github.com/lxc/lxd/pull/11180).
Also reduces transactions and queries used.
Merge https://github.com/lxc/lxd/pull/11222 first.
> Instance: Unify profile validation and loading for instance create endpoint

- lxd/instance.go
> lxd: Improve logging in autoCreateInstanceSnapshots

- doc/howto/import_machines_to_instances.md
After migrating a machine to an instance, you typically need to update some of the instance configs.
> doc/lxd-migrate: add information about updating the configuration

- lxd/main_forksyscall.go
otherwise we can't MS_MOVE the shiftfs child mount.
> forksyscall: ensure that parent mount is dependent mount

- lxd/main_forksyscall.go
by mounting the second shiftfs mount onto @template instead of stacking it on top of @target again.
> forksyscall: avoid double MS_MOVE

- grafana/LXD.json
@stgraber if you are pleased with the result, please upload a fresh copy to Grafana, thanks!
> grafana: add top network usage graphs

- lxd/device/device_utils_unix_events.go
dead lock found when watch an existing device
unixRunHandlers acquires lock unixMutex while, if the watch function being triggered, together with the acquiring d.mu.lock, dead lock will be found.
The fix moved device watch register from unixMutex lock scope
Signed-off-by:   ichiro999 <93505768@qq.com>
> fix dead lock bug

- lxd/api.go
> lxd/api: Add support for serving the UI

- doc/rest-api.yaml
- lxd/api_cluster.go
- lxd/db/node.go
- lxd/db/node_test.go
- lxd/instances_post.go
Part of my work for https://github.com/lxc/lxd/pull/11180
> lxd: Efficiency improvements to cluster member listing and showing

- doc/reference/devices_nic.md
> doc/ref/devices_nic: Add queue.tx.length

- lxd/instances_post.go
> lxd/instances_post: Fix copying profiles during instance copy

- doc/howto/cluster_groups.md
> doc/clustering: add link to YouTube video about cluster groups

- doc/howto/cluster_manage.md
> doc/clustering: document `lxc cluster info`

- doc/reference/storage_drivers.md
> doc/storage: explain how optimized instance transfer works

- Makefile
> Makefile: Immediately fail on lint errors

- doc/README.md
- doc/architectures.md
- doc/backup.md
- doc/doc-cheat-sheet.md
- doc/faq.md
- doc/metrics.md
- doc/reference/storage_btrfs.md
Global update to some terms to be more consistent.
> Terminology fixes

- lxd/storage/backend_lxd.go
- lxd/storage/drivers/driver_ceph_volumes.go
- lxd/storage/drivers/driver_lvm_volumes.go
- lxd/storage/drivers/volume.go
Related to changes required for https://github.com/lxc/lxd/pull/11206
> storage: Various changes

- doc/reference/devices_nic.md
- lxd/device/nic_physical.go
- lxd/device/nictype/nictype.go
- test/suites/container_devices_nic_physical.sh
Fixes: https://github.com/lxc/lxd/issues/11177
> device: support managed network with physical nic

- lxd/instance/drivers/driver_lxc.go
- lxd/instance/drivers/driver_qemu.go
In response of : https://github.com/lxc/lxd/issues/11345https://github.com/lxc/lxd/issues/11345
Signed-off-by: Gabriel Mougard <gabriel.mougard@canonical.com>
> instance: differentiate msg for creation/deletion of snapshots

- lxd/device/disk.go
This fixes an issue where a filesystem custom volume on ceph would fail
to be added to a VM as filesystem volumes would falsely use RBD support.
With this commit, only block volumes will use the RBD support, and
filesystem volumes will be mounted and passed into the VM through
9p/virtio-fs.
Fixes #11351
> device/disk: Don't use RBD for FS custom volumes

- lxd/storage/backend_lxd.go
Introduced with https://github.com/lxc/lxd/pull/11206/commits/5876e3e30b6b4a7b8f3a5f80aebc945db195f7f9
> Storage: Fix BTRFS regression from ZFS block mode

- doc/explanation/clustering.md
- lxd/api_1.0.go
- lxd/scriptlet/starlark.go
- lxd/scriptlet/starlark_test.go
- test/suites/clustering_instance_placement_scriptlet.sh
- Updated https://discuss.linuxcontainers.org/t/lxd-scriptlet-based-instance-placement-scheduler/15728
> Scriptlet: Change `StarlarkMarshal` to convert Go structs to Starlark objects

- lxd/storage/drivers/utils_ceph.go
If starting a VM on ceph, and the `<cluster>.client.<user>.keyring`
is missing, it'll fail.
This commit adds a check for the key in the ceph config file.
Fixes #11352
> ceph: Check ceph config file for key

- lxd/storage/drivers/driver_btrfs_volumes.go
Fixes https://github.com/lxc/lxd/issues/11308
> Storage: Fix optimized BTRFS refresh

- doc/reference/devices_disk.md
- doc/reference/devices_unix_block.md
- doc/reference/devices_unix_char.md
- doc/reference/devices_unix_hotplug.md
Plus clarifications for disk devices.
> doc: add video links

- doc/clustering.md
- doc/explanation/clustering.md
- doc/projects.md
- doc/reference/storage_zfs.md
Add a couple of links to specifications and tutorials, and a quick cleanup of the scriptlet docs.
> doc: add links

- lxd/device/nic_ipvlan.go
Rather than depending on the underlying liblxc features.
This brings the ipvlan NIC inline with how the routed NIC performs host-side setup.
> Device: Configure ipvlan NIC host-side routes and neighbour proxy entries with LXD

- lxd/db/instances.go
- lxd/db/instances_test.go
- lxd/instance.go
- lxd/instance/filter.go
- lxd/instances.go
- lxd/instances_get.go
And did some tidying up and optimisations to avoid unnecessary DB query.
Fixes #11375
> Instance: Fix non-recursive filtering in instances list

- lxd/storage/backend_lxd.go
- lxd/storage/drivers/driver_ceph_volumes.go
- lxd/storage/drivers/driver_lvm_volumes.go
- lxd/storage/drivers/driver_zfs_volumes.go
- test/suites/storage_driver_zfs.sh
Resizing of ZFS block mode (https://github.com/lxc/lxd/pull/11206) filesystem volumes wasn't working at all.
Fixes #11396
> Storage: Fix volume resize for ZFS block mode filesystem volumes

- lxd/instance/drivers/driver_qemu.go
> Instance: Don't collect metrics unless VM is running

- lxd/api.go
- lxd/storage/s3/types.go
> Storage: Only use path parts of URL to extract bucket name

- lxd/storage/drivers/driver_zfs_volumes.go
For Btrfs and XFS the filesystem UUID wasn't regenerated on migration.
This fixes the issue by correctly regenerating the UUID.
Fixes #11417
> zfs: Regenerate UUID on optimized migration

- lxd/main_init_interactive.go
> lxd/main_interactive: Tweak LVM thin pool error

- doc/howto/network_zones.md
by default the DNS listens on 53.
> removed the `-p 1053` param from the `dig` call

- lxd/main_forkmount.go
> lxd: tweak do_move_forkmount()

- lxd/instance/drivers/driver_qemu.go
> lxd/instance/qemu: Fix SMP on s390x

- .sphinx/.markdownlint/exceptions.txt
- .sphinx/conf.py
- doc/cloud-init.md
- doc/howto/cluster_form.md
- doc/howto/cluster_manage.md
- doc/howto/import_machines_to_instances.md
- doc/howto/instances_troubleshoot.md
- doc/howto/migrate_from_lxc.md
- doc/howto/network_bridge_resolved.md
- doc/howto/network_create.md
- doc/howto/network_ovn_setup.md
- doc/howto/network_zones.md
- doc/howto/storage_pools.md
- doc/installing.md
- doc/metrics.md
Draft PR for review - before merging, I'll move the extension out to our extension package.
> Doc: extension for terminal output

- lxd/storage/drivers/driver_zfs_volumes.go
- test/suites/migration.sh
Fixes https://github.com/lxc/lxd/issues/11308
> Various zfs block mode fixes

- doc/reference/devices_unix_hotplug.md
> Documentation: fixed typo

- .sphinx/conf.py
- doc/config_options_cheat_sheet.md
A draft PR to show what we can do.
Before merging, I want to move the extension to our extension package, but it might be easier to review here.
Example output: https://linuxcontainers.org/lxd/docs/pr.11405/config_options_cheat_sheet/
> Config options

- doc/reference/storage_drivers.md
- lxd/instance/drivers/driver_lxc.go
- lxd/instance/drivers/driver_qemu.go
- lxd/migrate_storage_volumes.go
- lxd/storage/backend_lxd.go
- lxd/storage/backend_mock.go
- lxd/storage/drivers/driver_btrfs.go
- lxd/storage/drivers/driver_ceph.go
- lxd/storage/drivers/driver_cephfs.go
- lxd/storage/drivers/driver_cephobject.go
- lxd/storage/drivers/driver_common.go
- lxd/storage/drivers/driver_zfs.go
- lxd/storage/drivers/interface.go
- lxd/storage/pool_interface.go
> storage: Use rsync when refreshing filesystem volumes in volume-only mode

- lxd/storage/drivers/driver_ceph_volumes.go
Don't fail CreateVolumeSnapshot when freezing filesystem not possible. 
Still attempt it, as this will also try doing a `sync` call, but if the filesystem is busy, go on with he snapshot.
Fixes VM snapshots on ceph caused by 518a9bafa877e5f4acf7ecb0b44fe3052b7ded93.
> Storage: Fix VM snapshots on Ceph

- lxd/instance/drivers/driver_qemu.go
- lxd/instance/drivers/driver_qemu_templates.go
> lxd/instance/qemu: Move vmgenid to using qemu.conf

- lxd/instance/drivers/driver_qemu.go
Fixes issue caused by 384114482c8807dcf19b3394277f6050b627401f
> Instance: Fix VM start with vmgenid

- lxd/db/cluster/config.mapper.go
- lxd/db/cluster/devices.mapper.go
- lxd/db/generate/db/method.go
> lxd-generate: Use tx.ExecContext over tx.Exec

- lxd/daemon.go
- lxd/instance.go
> lxd: auto snap create and pruning are in the same task

- doc/authentication.md
And add mention of the env variable to allow TLS 1.2.
Closes #11504
> doc/authentication: Update minimum TLS

- lxd/instance/drivers/driver_qemu.go
- lxd/instance/drivers/qmp/commands.go
- lxd/instance/drivers/qmp/monitor.go
And a precursor change before live VM migration support.
> Instance: VM QMP improvements

- doc/doc-cheat-sheet.md
We have added some extensions that should be mentioned in the cheat sheet.
> doc/cheat-sheet: update with more markup

- .sphinx/_templates/footer.html
Add links to the footer of each page to ask a question on the forum or open a GitHub issue.
> doc/footer: add community links

- lxd/device/device_utils_network.go
Fixes regression caused by b2936739b8e0a18761cdfb2c5edbdcab074d39e4
@stgraber I noticed the https://jenkins.linuxcontainers.org/job/lxd-github-commit-stable-5.0/ test has been failing for a while.
> lxd/device/device/utils/network: Fix networkCreateVethPair backport

- doc/api-extensions.md
- doc/reference/network_ovn.md
- lxd/network/driver_ovn.go
- lxd/network/network_utils.go
- lxd/network/openvswitch/ovn.go
- shared/version/api.go
Associated tests https://github.com/lxc/lxc-ci/pull/727
> Network: Add L3 only mode for OVN networks

- lxd/instance/drivers/driver_lxc.go
Fixes #11539
Closes #11578
Forcefully stop any running forkfile process in `Stop()` so its already killed by the time the `onStop` hook runs (which would only notify that it stop when there are no more connections).
> Instance: Forcefully stop SFTP forkfile processs when forcefully stopping container

- lxc/query.go
https://github.com/lxc/lxd/issues/11388
Added fix to detect EOF error on queries and retry HTTP request with plain text encoding.
> Added fix to detect EOF error on queries and retry with plain text

- lxd/apparmor/rsync.go
- lxd/daemon.go
- lxd/rsync/rsync.go
Cover rsync calls from rsync package by the Apparmor profile
Fixed issue #10261
> AppArmor profile for rsync

- lxd/instance/operationlock/operationlock.go
> instance: no timeout on the operationlock for creating an instance

- doc/api-extensions.md
- doc/rest-api.yaml
- lxd-agent/state.go
- lxd/instance/drivers/driver_lxc.go
- lxd/instance/drivers/driver_qemu.go
- lxd/storage/backend_lxd.go
- lxd/storage/backend_mock.go
- lxd/storage/pool_interface.go
- lxd/storage/utils.go
- lxd/storage_volumes_state.go
- shared/api/instance_state.go
- shared/version/api.go
> Add Total fields to InstanceStateDisk and InstanceStateMemory

- doc/authentication.md
- doc/howto/move_instances.md
- doc/howto/network_ovn_setup.md
- doc/howto/storage_pools.md
- doc/reference/devices_proxy.md
Also link to the proxy video and add some info there.
> Various doc updates for 5.13 

- doc/howto/network_create.md
- doc/howto/storage_volumes.md
> doc/storage: clarify that "attach" is an alias for "device add"

- lxd/cgroup/abstraction.go
closes #10052 
Example :
```go
package main
import (
"fmt"
"regexp"
"strings"
)
var devIDregex = regexp.MustCompile(`(?m)([0-9]+:[0-9]+)`)
func main() {
l1 := "1123:1 12:12 234:233 rbytes=1 wbytes=22 rios=0 wios=1 dbytes=0 dios=0"
l2 := "234:288 rbytes=0 wbytes=5 rios=0 wios=1 dbytes=33 dios=0"
l3 := "234:266"
var devID, nestedDevIDs string
// There might be multiple devID in the beginning of the line, we need to take the rightmost one.
for _, devIDmatch := range devIDregex.FindAllString(l1, -1) {
devID = devIDmatch
nestedDevIDs += fmt.Sprintf("%s ", devID)
}
stats := strings.TrimLeft(l1, nestedDevIDs)
fmt.Println(devID) // '234:233'
fmt.Println(stats) // 'rbytes=1 wbytes=22 rios=0 wios=1 dbytes=0 dios=0'
nestedDevIDs = ""
for _, devIDmatch := range devIDregex.FindAllString(l2, -1) { …
```
> lxd/cgroup: Better matching of devID and io stats

- lxd/storage/drivers/driver_zfs_volumes.go
Only use unsafe resize when operating on block backed filesystem volumes.
Caused by 5c4f1109bcb984e7bac5ffcd41d47ead9852b37d
Fixes test failures: https://jenkins.linuxcontainers.org/job/lxd-test-storage-vm/backend=zfs,restrict=master/1431/console
> Storage: Fix ZFS block volume shrink regression

- client/lxd.go
- client/lxd_oidc.go
- client: Always set Authorization if using OIDC
- client: Simplify response check in OIDC
> OIDC fixes

- doc/reference/instance_options.md
As raised in https://discuss.linuxcontainers.org/t/clarify-the-cpu-limits/17002
> doc/instance options: clarify CPU limits

- lxd/sys/apparmor.go
- shared/subprocess/proc.go
> Subprocess: Respect LXD_SECURITY_APPARMOR env var

- lxc/storage.go
As was panicking on storage pool bucket resource URLs.
Also changes "target" attribute to "location" to clarify the meaning of it.
> lxc/storage: Rework cmdStorageInfo.Run() to be more resilient to used by resource URLs

- doc/rest-api.yaml
- lxd/storage_pools.go
- lxd/storage_volumes.go
- lxd/storage_volumes_backup.go
- lxd/storage_volumes_snapshot.go
- lxd/storage_volumes_state.go
This changes the storage API endpoints to use consistent route variable names.
> storage: Use consistent route variable names

- lxd/daemon_images.go
- lxd/db/images.go
And reduce scope of intermediate id64 var.
Related to #11636
> lxd: Improve errors for image record creation

- lxc/storage.go
- lxd/instance_post.go
- lxd/storage_volumes.go
> Storage: Prevent moving volumes to projects that dont have features.storage.volumes enabled

- lxd/device/unix_common.go
- lxd/instance/drivers/driver_lxc.go
- lxd/network/driver_bridge.go
- lxd/network/network_utils.go
> Use `shared.IsTrueOrEmpty` where appropriate

- lxd/instance/drivers/driver_qemu.go
In #11594 we disabled vhost-net acceleration for VM TAP devices as it was not working with the LXD AppArmor profile.
It apparently had never worked, but whereas previously it had logged a warning and the VM had still started, from QEMU >= 7.2 the VMs failed to start.
This PR re-enables vhost-net acceleration for VM TAP devices (used by `bridged`, `p2p`, `routed`, `ovn` and `macvlan` LXD NIC devices).
It does this by using the same method of passing file descriptors to QEMU that `macvtap` devices already use.
However in order to get the file descriptor of a `tap` interface it was necessary to call the IOCTL `TUNSETIFF` on `/dev/net/tun` in (multiple times, once for each queue).
Once we were able to pass the `tap` device as multiple file descriptors, this opened the door to also passing the …
> VM: Enable vhost-net acceleration for TAP based NIC devices

- lxd/api_cluster.go
This PR fixes cluster member rename by:
- Forwarding the request to the member being renamed.
- Updating the local server name variable (as well as the database).
Fixes #11534
> Cluster: Fix member rename in clusterNodePost

- lxd/storage/drivers/driver_lvm.go
- lxd/storage/drivers/driver_lvm_utils.go
> Storage: Adds support for specifying the LVM thinpool size when reusing an existing PV or VG

- lxd/metrics/types.go
> lxd/metrics: fix copy-n-paste error for MemoryInactiveAnonBytes help text

- lxd/instance/drivers/driver_qemu.go
Tries to load vhost_net module at LXD start, and if /dev/vhost-net still not available then disables vhost-net CPU offloading for VM NICs.
Fixes regression caused by https://github.com/lxc/lxd/pull/11715
> Instance: Fixes LXD crash when starting VMs if /dev/vhost-net not available

- lxd/storage/drivers/utils.go
Also requires that there be at least 5GiB space free for use with the loop file.
Fixes #11646
> Storage: Updates loopFileSizeDefault to consider non-root free space

- doc/faq.md
> doc/faq: Drop reference to eth1

- shared/instance.go
Noticed from https://github.com/lxc/lxd/issues/11508#issuecomment-1564379335
> shared/instance: Separate some instance type specific config key validation

- lxd/device/nic_ovn.go
> lxd/device/nic/ovn: Enable hotplug for VMs

- doc/explanation/clustering.md
- doc/howto/cluster_form.md
- doc/howto/cluster_manage.md
- doc/howto/cluster_recover.md
Add information about `cluster.healing_threshold`.
> Doc: cluster healing

- doc/reference/instance_options.md
> doc/CPU limits: clarify what live update means for CPU limits

- lxd/api_cluster.go
- lxd/instance/drivers/driver_common.go
- lxd/instance/drivers/driver_lxc.go
- lxd/instance/drivers/driver_qemu.go
- lxd/instance/instance_interface.go
- lxd/instances.go
- lxd/main_activateifneeded.go
Also fix inconsistency between logic that triggers LXD start and instance auto start.
> Cluster: Fix instance start after cluster member healing

- lxc/publish.go
This PR switches the order of image deletion and creation for `lxc publish` command when `--reuse` flag is used. After this change the order will look like:
1. Create image
2. Delete image if necessary
3. Add/remove aliases
Fixes: #11657
> Perform alias and image deletion after image creation

- lxd/instance_snapshot.go
In https://github.com/lxc/lxd/issues/11713 it was reported that the linked instances shown for operations point to the snapshot instead of the instance. 
This sets the correct path and removes not used parameters from function calls.
Fixes https://github.com/lxc/lxd/issues/11713
> api: Set correct instance resource path for snapshot operations

- lxd/instance/drivers/driver_qemu.go
And also log any errors from io.Copy.
> VM: Fix potential race condition with context being cancelled too early in restoreState

- lxd/storage/drivers/driver_zfs.go
https://discuss.linuxcontainers.org/t/downgrading-from-self-compiled-to-debian-sid-package/17318
> lxd/storage/drivers/driver/zfs: Fix zfs list recommendation in Create

- lxd/apparmor/qemuimg.go
Fixes regression in https://github.com/lxc/lxd/pull/11784
> Instance: Fix VM image unpack apparmor regression

- lxd/device/nic_ovn.go
- lxd/network/network_utils_sriov.go
Please review commit by commit.
> Fix SRIOV representor port lookup

- lxd/db/warnings.go
similar to https://github.com/lxc/lxd/pull/11790/
> lxd/db: return an error in `UpdateWarningState` is the warning is not found

- lxd/db/warnings.go
closes #11785
Now:
```
$ lxc warning ack foo
Error: Warning not found
```
> lxd: Check if warning exists before acknowledging it

- lxd/storage/drivers/driver_zfs_volumes.go
> Storage: Only delete ZFS volume on failure if not doing refresh in createVolumeFromMigrationOptimized

- lxd-migrate/main_migrate.go
> lxd-migrate: Fix SecureBoot handling

- lxd/instance/drivers/driver_qemu.go
- lxd/sys/os.go
> Fix loading vhost_vsock module when VMs are not supported

- doc/api-extensions.md
- doc/reference/instance_options.md
- lxd/devices.go
- lxd/instance/drivers/driver_lxc.go
- lxd/resources/cpu.go
- shared/instance.go
- shared/version/api.go
This is the cleaned up version comming originally from here : https://github.com/lxc/lxd/pull/11803
> Restrict CPU placement to NUMA nodes

- lxd/instance/drivers/driver_qemu.go
This fixes an issue when using a `dir` pool backed by a tmpfs directory. As tmpfs does not support direct I/O.
But this will also fix `dir` pools on any filesystem that does not support direct I/O as well.
Closes #11862
> Instance: Fix VMs on filesystems that do not support direct I/O

- lxc/rebuild.go
> lxc/rebuild: Don't stop all instances on force

- .github/workflows/tests.yml
https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md
> github: use shellcheck package (22.04 has 0.8.0)

- client/lxd_candid.go
Hey there,
I just added a heading in the **client/lxd_candid.go** file that was missing. With this heading, it will be easy to understand what this function does.
Thank you!
> Added a heading in the client/lxd_candid.go file that was missing

- doc/.sphinx/_templates/header.html
Make the header fully compatible for mobile sized screens
> doc: update header for mobile compatibility

- .github/workflows/builds.yml
- test/suites/clustering.sh
This doesn't push yet, its just for testing.
> github: Add manually dispatch launchpad workflow

- lxc/cluster_group.go
- lxc/cluster_role.go
Hey @tomponline,
I now added the concise function headings in the comments. I hope they will be accepted now.
Thank you!
> Added headings in the files of the LXC directory

- lxd/instances_post.go
- test/suites/projects.sh
> lxd: Check project permissions when importing from backup

- lxd-migrate/transfer.go
- lxd-migrate/utils.go
- shared/ws/mirror.go
> lxd-migrate: Fix hang when performing rsync over websocket

- test/suites/clustering.sh
> test: Fix flaky clustering image refresh

- lxd/patches.go
- lxd/storage/backend_lxd.go
- lxd/storage/drivers/driver_btrfs_utils.go
- lxd/storage/drivers/driver_btrfs_volumes.go
- lxd/storage/drivers/driver_ceph_utils.go
- lxd/storage/drivers/driver_ceph_volumes.go
- lxd/storage/drivers/driver_lvm_utils.go
- lxd/storage/drivers/driver_lvm_volumes.go
- lxd/storage/drivers/driver_zfs_utils.go
- lxd/storage/drivers/driver_zfs_volumes.go
- lxd/storage/drivers/generic_vfs.go
- lxd/storage/drivers/utils_ceph.go
- lxd/storage/drivers/volume.go
- test/suites/backup.sh
- test/suites/storage_volume_import.sh
> Suffix custom ISO volumes with ".iso"

- lxd/api_internal_recover.go
- lxd/backup/config/backup_config.go
- lxd/storage/backend_lxd.go
- lxd/storage/backend_mock.go
- lxd/storage/pool_interface.go
- lxd/storage/s3/policy.go
- lxd/storage/utils.go
- test/main.sh
- test/suites/backup.sh
> Add support for storage bucket recovery

- doc/reference/projects.md
Closes https://github.com/canonical/lxd/issues/11875
> doc: Clarify documentation on restricted.cluster.target key

- lxd/patches.go
- lxd/storage/drivers/driver_zfs_volumes.go
- test/suites/backup.sh
> Set `lxd:content_type` user property on zfs volumes

- .github/workflows/tests.yml
https://bugs.launchpad.net/ubuntu/+source/curl/+bug/2028170
> github: Update runners before tests start

- doc/metrics.md
Followup on https://github.com/canonical/lxd/pull/12021#issuecomment-1640120053
> doc/metrics: add missing line break

- CONTRIBUTING.md
Please update the LXD DCO to be more inclusive.
The term "real name" is ambiguous. It can be interpreted as meaning someones legal name. Requiring legal name can be used for discrimination. For this reason, [the Kernel recently changed their DCO requirements with](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=d4563201f33a022fc0353033d9dfeb1606a88330): 
```
-using your real name (sorry, no pseudonyms or anonymous contributions.)
+using a known identity (sorry, no anonymous contributions.)
```
> inclusive identities

- doc/.sphinx/.markdownlint/exceptions.txt
- doc/howto/import_machines_to_instances.md
- doc/networks.md
> doc/lxd-migrate: add an example for importing to a VM

- client/simplestreams_images.go
- lxd-agent/metrics.go
- lxd/util/kernel.go
- shared/simplestreams/simplestreams.go
There are many more unchecked array accesses but I figured I shouldn't wait to have them all fixed.
> Improve bound checking

- lxd/instance/drivers/driver_common.go
- test/suites/basic.sh
> lxd/instance/drivers: update instance config if rebuild as empty

- README.md
- doc/index.md
- doc/index_topical.md
Moved to the Ubuntu Discourse.
> doc: update link to IRC tutorial

- doc/howto/import_machines_to_instances.md
- doc/installing.md
It's actually possible to link directly to GitHub artifacts of the latest release. :-)
> doc: update download links

- client/interfaces.go
- client/lxd_operations.go
- doc/api-extensions.md
- doc/rest-api.yaml
- lxd/db/operations.go
- lxd/operations.go
- shared/version/api.go
- test/main.sh
- test/suites/operations.sh
Due to permission issues, I have opened a new PR which just continues the work of #12078.
Fixes #11808
Closes https://github.com/canonical/lxd/pull/12078
> lxd: add all-projects param to the operation API

- lxd/storage/drivers/driver_ceph.go
- lxd/storage/drivers/driver_ceph_utils.go
> storage/drivers/ceph: Differentiate between a true non-existent OSD pool and a Ceph internal issue

- doc/api-extensions.md
- doc/config_options.txt
- lxd/cluster/config/config.go
- lxd/metadata/configuration.json
> Better document `loki.api.url`

- lxd/loki/loki.go
> loki: Add hostname as `instance` label value

- lxd/patches.go
> patches: Remove invalid block settings from existing volumes

- lxd/instance_rebuild.go
This reflects https://github.com/lxc/incus/pull/157/files
> lxd: Properly forward rebuild requests

- doc/support.md
> doc/support: clarify information about LTS releases and timing

- lxd/patches.go
> patches: Fix patch regarding unsetting zfs block settings

- lxd/storage_pools.go
> Fix missing etag when retrieving storage pool

- doc/config_options.txt
- doc/howto/instances_create.md
- lxd/metadata/configuration.json
- shared/instance.go
Some small additions to the doc updates for 5.19.
> Doc updates 5.19

- doc/index.md
As requested by our director of documentation.
> Doc: remove undesired content

- lxc/config/remote.go
From https://github.com/lxc/incus/pull/185
> shared/cliconfig: Nicer error on missing socket

- lxd/loki/loki.go
- test/suites/container_devices_unix.sh
@monstermunchkin was this intentional or maybe a debug/test setting left behind?
> loki: enable TLS verification if a CA cert is provided

- test/suites/rbac.sh
This caused problems in #12313, though luckily it has helped me to uncover a potential bug!
> test/suites: Unsets RBAC configuration after test.

- shared/util_linux.go
Seeks to improve ExecWrapper such that we don't lose output intermittently on non-interactive tests.
We saw some increase of that with PR https://github.com/canonical/lxd/pull/12443
> lxd: Exec wrapper improvements

- lxd/cluster/config/config.go
> lxd/cluster/config: Add missing bool default values

- doc/authentication.md
- doc/authorization.md
- doc/config_options.txt
- doc/server.md
- lxd/cluster/config/config.go
- lxd/metadata/configuration.json
Just some small nitpicks. ;)
As a quick explanation if interested:
- "can" describes ability ("I can open the door" - I'm strong enough and the door isn't locked)
- "may" describes permission ("I may open the door" - nobody has told me to keep it shut)
- "might" describes possibility ("I might open the door" - either I will or I won't)
> doc: small fixes OpenFGA docs

- lxd/storage/drivers/driver_zfs.go
> zfs: Support zfs pools containing '/' in the patch

- lxd/storage/drivers/driver_zfs_utils.go
- lxd/storage/drivers/driver_zfs_volumes.go
…ption"
This reverts commit a56e5c55d00e26b5c4680d659f88d1373bee4b53.
Closes https://github.com/canonical/lxd/issues/12473
> Revert "lxd/storage/zfs/volumes: Fix ZFS does not respect atime=off option" (stable-5.0)

- lxd/images.go
- lxd/instances_get.go
- lxd/storage_volumes.go
- shared/filter/clause.go
- shared/filter/match.go
https://github.com/lxc/incus/pull/239
> Improved filtering from Incus

- lxc/move.go
- lxd/instance_post.go
- test/suites/container_move.sh
> Fix profiles not retained when instance is move between projects

- .github/labeler.yml
- lxd/acme.go
- lxd/api_1.0.go
- lxd/api_cluster.go
- lxd/api_internal_recover.go
- lxd/daemon.go
- lxd/devlxd.go
- lxd/instance_post.go
- lxd/instances_post.go
- lxd/instances_put.go
- lxd/networks.go
- lxd/operations.go
- lxd/patches.go
- lxd/state/state.go
- lxd/storage_pools.go
- lxd/storage_volumes.go
Imported from Incus. This also include the labeler config fix to resolve the test failure in https://github.com/canonical/lxd/pull/12622
> Add new ServerClustered field

- doc/config_options.txt
- lxd/cluster/config/config.go
- lxd/metadata/configuration.json
- lxd/node/config.go
Fixes https://github.com/canonical/lxd/issues/12583.
> Fix missing config defaults

- doc/backup.md
- doc/howto/instances_backup.md
- doc/howto/move_instances.md
- doc/howto/storage_move_volume.md
Make sure we link to required information.
Also add information about the `--refresh` option in all places.
> doc/backup: improve linking between pages and mention `--refresh`

- doc/reference/storage_drivers.md
As part of https://github.com/canonical/lxd/issues/12668 we saw that refreshing Ceph RBD backed volumes does not use the optimized volume transfer.
Since the section about the optimized volume transfer is merged together with the concept of refreshing, a new entry is added to the drivers feature comparison that depicts the support for optimized volume refreshes across the various drivers. 
Furthermore the optimized volume transfer section is now split into transfer and refresh in order to explain its features separately.
> Clarify optimized volume refresh

- test/main.sh
- test/suites/exec.sh
This PR adds a test for exec exit code: https://github.com/terraform-lxd/terraform-provider-lxd/pull/407#issuecomment-1867810689
> test: Add exec exit code test

- doc/api-extensions.md
- doc/config_options.txt
- lxd/cluster/config/config.go
- lxd/metadata/configuration.json
- lxd/network/openvswitch/ovn.go
- shared/linux/memfd.go
- shared/version/api.go
https://github.com/lxc/incus/pull/281
> Allow configuring OVN SSL settings through server configuration

- lxd/response/response.go
closes #12611  
___
@tomponline @roosterfish Here is an example of a reproducer with the patch (left is the server machine, right is the client machine. At some point, I create a network outage in the client side. The server is now able to finish its snapshotting operation even when the client died pulling for some files):
https://github.com/canonical/lxd/assets/27967361/3c8b3e21-fb86-43c8-928d-7e0958dd50d6
> Stop dead client connection from blocking instance snapshot / remove 

- lxd/storage_volumes_snapshot.go
- test/suites/storage_snapshots.sh
> Apply the `snapshots.pattern` option for manual custom volume snapshot

- lxd/api_cluster.go
- lxd/api_project.go
- lxd/cluster/config/config.go
- lxd/instance/drivers/driver_lxc.go
- lxd/instance/instancetype/instance.go
- lxd/lxd-metadata/lxd_metadata.go
- lxd/lxd-metadata/lxd_metadata_test.go
- lxd/node/config.go
This is a preliminary work needed by:
* https://warthogs.atlassian.net/browse/LXD-442
* https://warthogs.atlassian.net/browse/LXD-441
* https://warthogs.atlassian.net/browse/LXD-440
follow-up PR: https://github.com/canonical/lxd/pull/12645
> lxdmetadata: support for multiple entities comments

- Makefile
- go.sum
github.com/openfga/go-sdk@v0.2 and github.com/mdlayher/socket@v0.4.1
> Makefile: Removes unnecessary pins of go deps (stable-5.0)

- lxd/instance/drivers/driver_lxc.go
- lxd/instance/drivers/driver_qemu.go
This is just some lint fixing required for https://github.com/canonical/lxd/pull/12821 and https://github.com/canonical/lxd/pull/12832
> Instance: fix linting issues in the instance drivers

- lxd/patches.go
https://github.com/canonical/lxd/pull/12830 removed Candid and RBAC support from LXD but the database entries for the config items in any existing LXD installations that are using Candid/RBAC will remain. This patch removes those config items.
> lxd: Remove RBAC and Candid config keys (patch).

- lxd/device/disk.go
- lxd/storage/backend_lxd.go
- lxd/storage/drivers/generic_vfs.go
In preparation for https://github.com/canonical/lxd/pull/12840
> Various linter fixes

- lxd/instance/drivers/driver_qemu.go
As of now, in order to live migrate a VM, the user has to manually configure the `size.state` config option of the instance root disk (alongside the `migration.stateful=true` instance config option). The optimal value of `size.state` is hard to predict and makes the user experience tedious.
This work proposes to remove the need for the `size.state` disk config option when doing a live vm migration if the instance's root disk is on remote storage as `size.state` is not required for this particular case. However, we still need to check for `size.state` when doing a stateful stop.
> Instance: Do not check for `size.state` during live migration if VM is backed by shared storage 

- .github/dependabot.yml
- .github/labeler.yml
* Ask dependabot to look after gomod updates on main
* Add labels when PRs target LTS branches
> Dependabot and labeler update

- doc/external_resources.md
- doc/reference/index.md
- lxd/instance_instance_types.go
- meta/instance-types/.yaml
- meta/instance-types/aws.yaml
- meta/instance-types/azure.yaml
- meta/instance-types/gce.yaml
Until the new image server is online.
> Instance: Temporarily host the instance type preset files on Github

- doc/.wordlist.txt
- doc/profiles.md
> doc/profiles: link to instance configuration

- README.md
> README: fix link to translations on Weblate

- lxd/instance/drivers/driver_qemu.go
This was merged yesterday in https://github.com/canonical/lxd/pull/12754/commits/3dec35308f1b504f8f4ce72a586afa9cff389267 (as part of https://github.com/canonical/lxd/pull/12754). This PR reverts the linter fix to it's old state.
When trying to start a VM, it fails with the following error:
```bash
root@julian01:~# lxc launch ubuntu:jammy v1 --vm -s pf
Creating v1
Starting v1                                 
Error: Failed to setup virtiofsd for config drive: %!w(<nil>)
Try `lxc info --show-log local:v1` for more info
```
> Qemu: Revert linter fix

- lxd/auth/driver_tls.go
- lxd/certificates.go
- lxd/images.go
- lxd/network_acls.go
- lxd/network_zones.go
- lxd/networks.go
- lxd/profiles.go
- lxd/request/const.go
- lxd/request/context.go
- lxd/storage_buckets.go
- lxd/storage_volumes.go
- test/suites/tls_restrictions.sh
This is implemented differently from the original incus cherry picks but there is one commit that I want to double check before merging.
Depends on #12872 
Fixes https://github.com/canonical/lxd/issues/12903
> Auth: Expand certificate/image fingerprints and handle effective projects in authorization check.

- .github/workflows/tests.yml
- doc/.wordlist.txt
- doc/contributing.md
- test/main.sh
Take the opportunity of known test failures to improve the logging of tests while at it.
> Doc: Mention that SVG/PNG are preferred in CONTRIBUTING

- lxd/apparmor/rsync.go
- lxd/rsync/rsync.go
Backports #12927 to stable-5.0
> Backport rsync apparmor fix (stable-5.0)

- lxd/storage/drivers/driver_ceph_volumes.go
- lxd/storage/drivers/driver_lvm_volumes.go
Backports #12938 to stable-5.0
> Backport volume.block.filesystem restriction (stable-5.0)

- lxd/instance/drivers/driver_qemu.go
- shared/subprocess/proc.go
Cherry picks the Go tip fixes from https://github.com/canonical/lxd/pull/12942
> Backport go tip fixes (stable-5.0)

- client/lxd_instances.go
- test/suites/container_devices_nic_bridged.sh
And add test for the functionality.
> client: Add API extension check for instance import with device override support

- lxd/instance/drivers/driver_qemu.go
Fixes #12935
Closes #12940
Tested with:
```
lxc init ubuntu:22.04 v1 --vm
lxc config uefi set v1 SecureBootEnable-f0a30bc7-af08-4556-99c4-001009c93a44=00
lxc config uefi get v1 SecureBootEnable-f0a30bc7-af08-4556-99c4-001009c93a44
00
```
> Instance: Initialise UEFI vars NVRAM on first access if needed

- lxd/db/cluster/update_test.go
In this test the schema is only updated to version 70. When there are schema updates in the future, this test will likely fail because it will fail to prepare statements in the `cluster` package against an earlier schema version.
> DB: Preemptively fix schema update unit test.

- lxd/db/cluster/entities.go
As discussed earlier, the comment describing these odd queries has been improved and the queries have been split up over multiple lines to make them clearer.
> DB: Clarify entity URL to ID SQL queries.

- lxd/storage/backend_lxd.go
There is one part in the LXD backend for which I have already added a fix a few days ago, see https://github.com/canonical/lxd/pull/12946. I have observed another behavior that now requires getting rid of this "optimization". 
The initial idea was to be able to generate the list of snapshots "on the fly" so that we don't have to query the database again for getting the target volume's snapshots. However this is causing trouble if a snapshot requires an "out of order" refresh:
```
srcVol            targetVol
\_ snap0          \_ snap0
\_ snap1          \_ snap2
\_ snap2
```
In the example above `snap1` would require a refresh on the target side. This would lead to the following list being passed to the storage drivers `RefreshVolume` function since we append to the existing list that was …
> Storage: Pass custom storage volume snapshots in the right order

- lxd/db/cluster/entities.go
Noticed this while working on #12992
> DB: Fix query for storage volume snaphot.

- lxd/storage/drivers/driver_ceph.go
> Storage: remove reference to "ceph.osd.force_reuse"

- doc/config_options.txt
- doc/reference/devices_pci.md
- lxd/device/pci.go
- lxd/metadata/configuration.json
> lxd-metadata: Annotate codebase for `pci` device config keys

- doc/config_options.txt
- doc/reference/devices_gpu.md
- lxd/device/gpu.go
- lxd/lxd-metadata/lxd_metadata.go
- lxd/metadata/configuration.json
> lxd-metadata: Annotate codebase for `gpu` device config keys

- doc/config_options.txt
- doc/reference/devices_unix_block.md
- doc/reference/devices_unix_char.md
- doc/reference/devices_unix_hotplug.md
- doc/reference/devices_usb.md
- lxd/device/unix_common.go
- lxd/device/unix_hotplug.go
- lxd/lxd-metadata/lxd_metadata.go
- lxd/metadata/configuration.json
> lxd-metadata: Annotate codebase for `unix-{char,block,hotplug,usb}` device config keys

- doc/config_options.txt
- doc/howto/move_instances.md
- doc/howto/storage_volumes.md
- doc/reference/devices_disk.md
- doc/reference/storage_btrfs.md
- lxd/device/config/devices.go
- lxd/device/disk.go
- lxd/metadata/configuration.json
> lxd-metadata: Annotate codebase for `disk` device config keys

- doc/config_options.txt
- doc/reference/devices_infiniband.md
- lxd/device/infiniband_physical.go
- lxd/metadata/configuration.json
> lxd-metadata: Annotate codebase for `infiniband` device config keys

- doc/config_options.txt
- doc/reference/network_sriov.md
- lxd/metadata/configuration.json
- lxd/network/driver_sriov.go
See the root PR https://github.com/canonical/lxd/pull/13027 for a summary
> lxd-metadata: Annotate codebase for `sriov` network config keys

- doc/config_options.txt
- doc/reference/devices_proxy.md
- lxd/device/proxy.go
- lxd/metadata/configuration.json
> lxd-metadata: Annotate codebase for `proxy` device config keys

- doc/config_options.txt
- doc/reference/network_physical.md
- lxd/metadata/configuration.json
- lxd/network/driver_physical.go
See the root PR https://github.com/canonical/lxd/pull/13027 for a summary
> lxd-metadata: Annotate codebase for `physical` network config keys

- doc/config_options.txt
- doc/reference/instance_properties.md
- lxd/instance/drivers/driver_lxc.go
- lxd/metadata/configuration.json
JIRA ticket: https://warthogs.atlassian.net/jira/software/c/projects/LXD/boards/54?assignee=63d9eb6128cddcc70770aff1&selectedIssue=LXD-439
> lxd-metadata: Annotate codebase for instance properties

- doc/config_options.txt
- doc/reference/network_ovn.md
- lxd/metadata/configuration.json
- lxd/network/driver_ovn.go
See the root PR https://github.com/canonical/lxd/pull/13027 for a summary
> lxd-metadata: Annotate codebase for `ovn` network config keys

- lxd/storage/drivers/driver_powerflex_volumes.go
This is not causing an error on LXD side but prints messages in the kernels log when resizing the volume on PowerFlex whilst it is mapped to the host using NVMe/TCP.
If we unmap the volume beforehand, it gets removed from the system by the NVMe controller. We can then change its size and map it again to the system.
> PowerFlex: Unmap the volume before performing resize

- lxd/instance/drivers/driver_qemu.go
- lxd/main_init.go
- lxd/main_init_interactive.go
- lxd/network/network_utils.go
- lxd/seccomp/seccomp.go
- lxd/util/net.go
Addresses some issues from https://github.com/canonical/lxd/security/code-scanning
> Incorrect integer conversion fixes

- lxd/storage/drivers/driver_ceph_volumes.go
When migrating a snapshot into a new volume don't send a VMs filesystem vol if the target expects the root volume. This was first discovered here https://github.com/canonical/lxd-ci/pull/101#issuecomment-1985657489.
This fixes a bug that already existed before we have added https://github.com/canonical/lxd/pull/12743. LXD is sending the VMs filesystem volume twice for both the block and filesystem volume to the target.
This was observed because on the target both the VMs root and filesystem volume appeared to have the same size which is causing the startup of `v2` to never succeed:
```bash
root@thinkpad:/home/julian/dev/lxd-ci# lxc cp v1/snap0 localhost:v2
root@thinkpad:/home/julian/dev/lxd-ci# lxc shell m1
root@m1:~# rbd ls c -l
NAME …
```
> Ceph: Send the actual block vol when migrating snapshot

- doc/api-extensions.md
- lxd/device/config/device_runconfig.go
- lxd/device/disk.go
- lxd/instance/drivers/driver_qemu.go
- lxd/instance/drivers/qmp/commands.go
- shared/version/api.go
I feel this warrants an API extension but none was added in Incus.
> VM: Add disk I/O limit support - from Incus

- doc/rest-api.yaml
- lxd/storage_volumes.go
Noticed this was missing while working on #12550.
> API: Documents all-projects parameter for storage volumes

- lxd/auth/driver_tls.go
- test/suites/tls_restrictions.sh
Additionally adds test cases to prevent this in future.
> Auth: Ensure projects cannot be edited or deleted by restricted clients.

- lxc/copy.go
Noticed this while working on #13118
> lxc/copy.go: remove impossible condition

- doc/howto/access_ui.md
We don't have feature parity yet, but the UI covers a lot of features by now.
> doc/UI: reword status of the LXD UI

- shared/version/flex.go
(cherry picked from commit 761d134ceabd306f57acfb0ca51f59b03751a5b0)
> Release LXD 5.21.0

- lxc/config/remote.go
> lxc: Print "permission denied" when LXD socket isn't writable

- lxc/auth.go
When listing permissions, the first argument (if provided) was always expected to be a remote. This may not be the case as the remote is optional and supplementary arguments have the form `<key>=<value>`.
This commit treats the first argument as a remote only if it has a colon as a suffix. Remaining arguments are parsed as key-value pairs.
Will wait for Maria to validate before unmarking as draft.
> lxc: Correctly parse remote when listing permissions.

- doc/.sphinx/.markdownlint/exceptions.txt
- doc/clustering.md
- doc/custom_conf.py
- doc/explanation/index.md
- doc/getting_started.md
- doc/howto/import_machines_to_instances.md
- doc/howto/index.md
- doc/howto/migrate_from_lxc.md
- doc/howto/troubleshoot.md
- doc/images.md
- doc/index.md
- doc/instances.md
- doc/networks.md
- doc/operation.md
- doc/production-setup.md
- doc/projects.md
- doc/reference/index.md
- doc/storage.md
- doc/support.md
Also update the start page with links.
> doc/howto: reorder pages and update the landing pages 

- lxd/instance/drivers/driver_qemu.go
- lxd/instance/drivers/driver_qemu_templates.go
Sponsored-by: ActivePort (https://www.activeport.com.au) (cherry picked from commit b0c2bdd66bcfb5e7a1f68351718b7601a941cde4)
> VM: Fix handling of > 64 limits.cpu

- grafana/LXD.json
Connecting null values should help with instances that are not always online.
> Grafana fixes

- lxd/api_metrics.go
- lxd/instance/drivers/driver_lxc.go
- lxd/metrics/metrics.go
- lxd/metrics/types.go
- test/suites/metrics.sh
Metrics fixes from https://github.com/canonical/lxd/pull/13222
> Backports (stable-5.21)

- doc/api-extensions.md
- doc/image-handling.md
- lxd/instance/drivers/driver_lxc.go
- shared/version/api.go
Cherry picked from https://github.com/lxc/incus/pull/650
> Introduce requirements.nesting for images

- lxd/auth/driver_openfga.go
closes #13236
There is no need to list server objects for a server entity to return a PermissionChecker. We just need to check the permission on the server URL, given its entitlement.
> lxd/auth/openfga: If the `entityType` is `TypeServer`, no need to list the server objects

- client/lxd_instances.go
- test/suites/filemanip.sh
Made a typo; added a test to catch that typo in future.
> Fix push permissions

- .github/workflows/tests.yml
> github: check for lxd-agent binary size changes

- scripts/bash/lxd-client
The most noteworthy bits are fixing `lxc restore $instance <tab>` and augmenting the `lxc image <tab>`.
> Additional bash completions and fixes

- .github/workflows/tests.yml
- Makefile
- doc/installing.md
> Have dqlite build raft

- Makefile
- doc/installing.md
This should have been part of #13392 but was forgotten.
> Remove traces of raft being a separated lib

- doc/explanation/index.md
- doc/explanation/lxc_show_info.md
This replaces previous PR https://github.com/canonical/lxd/pull/13327
> Add page describing lxc show and info

- doc/operation.md
Add the new page to the topical navigation as well to prevent a build error.
> doc: fix topical build

- doc/requirements.md
> doc/requirements: mention that HW support is required for running VMs

- doc/.sphinx/.markdownlint/exceptions.txt
- doc/config_options.txt
- doc/howto/network_acls.md
- doc/howto/network_forwards.md
- doc/howto/network_load_balancers.md
- doc/howto/network_ovn_peers.md
- doc/howto/network_zones.md
- lxd/metadata/configuration.json
- lxd/network/zone/record.go
- lxd/network/zone/zone.go
- shared/api/network_acl.go
- shared/api/network_forward.go
- shared/api/network_load_balancer.go
- shared/api/network_peer.go
JIRA ticket: https://warthogs.atlassian.net/jira/software/c/projects/LXD/boards/54?assignee=63d9eb6128cddcc70770aff1&selectedIssue=LXD-918
> lxd_metadata: annotate remaining network properties

- test/lint/golangci.sh
> test/lint: Reintroduce --whole-files linter flag.

- doc/howto/network_ipam.md
> doc: Add network list-leases to IPAM How-to

- doc/howto/dqlite_troubleshoot.md
- doc/howto/troubleshoot.md
This is a first stab at writing down some of the heuristics I use to help people on the forum troubleshoot dqlite-related errors. I hope to add more to it over time as I get more experienced with this (and as we figure out the root causes of some of these problems and hopefully fix them in dqlite).
Signed-off-by: Cole Miller <cole.miller@canonical.com>
> doc: Add a page about dqlite troubleshooting

- doc/database.md
- doc/howto/dqlite_troubleshoot.md
- doc/howto/instances_create.md
> doc: small content cleanup

- doc/README.md
- doc/contributing.md
- doc/custom_conf.py
> doc: update the documentation for the doc framework

- lxd/apparmor/instance_lxc.go
Based on https://bugs.launchpad.net/lxc/+bug/2064144/comments/11
> lxd/apparmor/lxc: Tweak rule syntax

- lxd/device/device_utils_disk.go
- lxd/device/disk.go
- lxd/device/tpm.go
- lxd/instance/drivers/driver_qemu.go
- lxd/util/sys.go
Fix regression introduced by https://github.com/canonical/lxd/pull/13320
> Device: Fix TPM for VMs

- doc/config_options.txt
- lxd/instance/instancetype/instance.go
- lxd/metadata/configuration.json
> Fix limits.memroy unit in docs

- lxd/storage/drivers/driver_ceph_volumes.go
When receiving the migration stream for a VM don't run `genericVFSCreateVolumeFromMigration` twice for both the VM's config drive and the root block volume. The function already takes care of this and tries to receive both.
If the function gets called to first receive the VM's config drive using the exchanged BLOCK_AND_RSYNC type, it will return ErrNotSupported as it is not intended to be invoked for a volume of type filesystem if the exchanged migration type is BLOCK_AND_RSYNC.
This is also causing an rsync error on the sending side as the receiving side interrupts and cancels the migration:
```
Rsync send failed: v1, /var/snap/lxd/common/lxd/storage-pools/default/virtual-machines/v1/: [exit status 12 read unix @lxd/9ede970f-5c31-49b8-9a72-217b0a647927->@: use of closed network …
```
> Storage: Call `genericVFSCreateVolumeFromMigration` never twice

- doc/.readthedocs.yaml
https://github.com/readthedocs/readthedocs.org/pull/11386 added support for Go 1.22
> doc: Update build tools used on readthedocs

- lxd/storage/drivers/driver_zfs_volumes.go
When system is highly loaded, the udev rules may take more than half a second to be applied. As a result, the device may still not be visible when trying to retrieve it's disk path.
Instead of giving a udev rules half a second to be applied, wait up to 30 seconds for the device to appear. This fixes the issue where zvol device cannot be located if the rules are not applied in time.
> Storage: Wait for ZFS device to appear when activating a volume

- lxd/instance/drivers/driver_lxc.go
(cherry picked from commit 36b995ef876e04ec4f54e1a8f82e178980276392)
Fixes #12084
> Instance: Re-generate missing container lxc.conf during Exec (from Incus)

- lxd/certificates.go
- test/includes/uuid.sh
- test/main.sh
- test/suites/clustering.sh
Cherry-picks #13733 and https://github.com/canonical/lxd/pull/13740.
> Extract certificate add token metadata from remote member (stable-5.21)

- lxd/apparmor/archive.go
- lxd/apparmor/instance.go
- lxd/apparmor/instance_qemu.go
- lxd/apparmor/rsync.go
- lxd/instance/drivers/driver_qemu.go
requires https://github.com/canonical/lxd-pkg-snap/pull/505
https://warthogs.atlassian.net/browse/LXD-1164
> VM: External QEMU snap support

- doc/authentication.md
Move the information from the note about using PKI with ACME to the main instructions, and update the docs to cover a cluster setup as well.
> doc/authentication: clean up PKI instructions

- doc/howto/index.md
> fix typo in index.md

- lxd/instances_post.go
- lxd/migrate.go
- lxd/migrate_instance.go
- lxd/migrate_storage_volumes.go
- lxd/storage_volumes.go
Just makes the migrations sink arguments private.
> Make migration sink arguments private

- doc/howto/storage_pools.md
This provides additional examples when to define (non-)member specific config keys and
how to create cluster storage pools backed by remote storage drivers.
> Doc: Additional examples for cluster storage pools using remote drivers

- lxd/storage/drivers/driver_zfs_volumes.go
Cherry-picked from https://github.com/lxc/incus/pull/1060
> lxd/zfs: Always try to wait for device path to appear (from Incus)

- lxd-migrate/main_migrate.go
- lxd/apparmor/qemuimg.go
- lxd/apparmor/qemuimg_test.go
- lxd/instance/drivers/driver_qemu.go
- lxd/storage/backend_lxd.go
- lxd/storage/utils.go
- shared/util.go
Track qemu-img convert progress.
Cherry-picked from https://github.com/lxc/incus/pull/1025 and https://github.com/lxc/incus/pull/1015
> lxd: Add tracker for qemu-img progress (from Incus)

- lxd-migrate/main_migrate.go
Cherry-picked from https://github.com/lxc/incus/pull/1077
> lxd-migrate: Properly handle projects (from Incus)

- .github/renovate.json
We are getting duplicate suggestions from both this and dependabot.
> github: Disable renovate

- doc/custom_conf.py
- doc/howto/access_ui.md
- doc/tutorial/first_steps.md
- doc/tutorial/ui.md
Incorporate feedback received on the UI tutorial
> doc/tutorial: improve the UI tutorial

- lxd/device/nic_physical.go
- lxd/device/pci/pci.go
- lxd/instance/drivers/driver_qemu.go
- lxd/instance/instancetype/instance.go
What constitutes adequate testing for this set of changes? I don't have access (currently) to a USB/Ethernet adapter; while I'm sure it's _possible_ to simulate one I doubt that would be a straightforward/worthwhile process. Should I check if someone else on the team has appropriate hardware to run a quick check on this?
> VM usb nic passthrough (from Incus)

- lxd/instance_file.go
cherry picked from lxc/incus#383
> lxd/instance/file: Add type and size to HEAD (from Incus)

- lxd/api_cluster.go
> lxd/cluster: Ensure the cluster member config is always sorted (From Incus)

- doc/api-extensions.md
- doc/metadata.txt
- lxd/device/disk.go
- lxd/instance/drivers/driver_qemu.go
- lxd/metadata/configuration.json
- shared/version/api.go
cherry picked from lxc/incus#384
> lxd: Add virtio-blk support for virtual machines (from Incus)

- lxd/networks.go
Based on https://github.com/lxc/incus/pull/351
> lxd/networks: Don't fill network config when joining cluster (from Incus)

- lxd/instance_post.go
Makes allow migration from offline source member and cluster self healing (by set cluster.healing_threshold > 0) if remote shared storage like `powerflex` , not only `ceph` .
For now, Remote shared storage is `ceph` and `powerflex` only.
- https://github.com/canonical/lxd/blob/main/doc/explanation/storage.md#data-storage-location
> Instance: For remote shared storage, make allow cluster self healing and migration from offline source member

- .github/workflows/tests.yml
I used this to debug the github tests this week and I thought this may be useful, feel free to close this if it is not needed.
> Run verbose unit tests

- lxd/cluster/notify.go
- lxd/cluster/notify_test.go
Fixes #13811 
There doesn't seem to be a well-established pattern for differentiating between error types other than `strings.Contains`. I'd be happy to drop something like [`IsConnectionError` ](https://github.com/canonical/lxd/blob/main/shared/network.go#L53) in a new file `shared/errors.go` if you're concerned about fragility when comparing error messages.
LXD-1371
> Don't fail when notifying a server that is shutting down when using NotifyAlive

- doc/tutorial/ui.md
Update some wordings to make things clearer.
> doc/tutorial: integrate feedback for UI tutorial

- doc/howto/instances_manage.md
Needed for https://github.com/canonical/microcloud/pull/369
> doc/instances: add anchor to allow linking to section

- shared/cert.go
Requested by the k8s team to use with their Canonical K8s which relies on microcluster. 
This will be used to supply both the `microcluster` internal cluster name as well as the system hostname to the certificate SAN, so either can be used to identify the certificate. 
`CommonName` is the same as the old `SubjectName` in that it is used both in the Subject Common Name field, as well as in the Subjcet Alternative Names field, if defined. If not defined, it will default to the hostname.
`SubjectAlternativeNames` are any alternative names that should be included in the SAN field in addition to `CommonName` and the local IPs.
> shared: Allow adding multiple names to certificate SAN

- lxd/certificates.go
- test/suites/remote.sh
> lxd/certificates: Add input validation for certificate names

- lxd/api_internal_recover.go
- test/suites/backup.sh
> lxd/recover: Add snapshot expiry when recovering instance snapshots

- lxd/storage_volumes_state.go
This goes from a 500 resp to something that looks like this if the driver reports `ErrNotSupported`:
```json
{
"usage": null
}
```
For example, a btrfs volume [without a quota set](https://github.com/canonical/lxd/blob/main/lxd/storage/drivers/driver_btrfs_volumes.go#L892).
It makes sense to me to pass through the lack of quota rather than just failing the entire request/response.
Contains cherry-picks from https://github.com/lxc/incus/pull/1143
> storage: Handle unsupported response from drivers (From Incus)

- Makefile
Until pending testing on the new version is completed.
> Makefile: Pin github.com/dell/goscaleio@v1.15.0

- test/suites/storage.sh
attempt to fix ceph storage tests
> test: fix ceph storage tests

- doc/installing.md
Documentation updates for https://github.com/canonical/lxd/pull/13959
> doc: Add shell completions instructions to LXD installation docs

- lxd/instance/drivers/driver_common.go
- lxd/instance/drivers/driver_lxc.go
- lxd/instance/drivers/driver_qemu.go
Was doing a little housekeeping and found this languishing in my local repo.
Following a similar change 37b4cd360cefe49644afde039356468eba8e8a28.
> lxd/instance/drivers: Move removeDiskDevices to common

- lxd/db/cluster/entity_type_instance_snapshot.go
- lxd/patches.go
Fixes https://github.com/canonical/lxd/issues/13862
> Patches: Fix spelling error in instance snapshot deletion trigger name

- .github/workflows/tests.yml
And some other small tweaks.
Later on we should look at de-duping some of the repeated steps, such as space reclaim, into sub-workflows we can call from multiple places.
Example of a successful test run on my fork: https://github.com/tomponline/lxd/actions/runs/10817095654
Once merged will need to GH TICS secrete set up.
> Github: Tiobe TICS integration

- .github/actions/reclaim-disk-space/action.yml
- .github/actions/tune-disk-performance/action.yml
- .github/workflows/codeql.yml
- .github/workflows/commits.yml
- .github/workflows/tests.yml
This avoids canceling scheduled and manual runs when merging into main.
Also add some sub-actions to de-dupe some repeated steps.
> github: Don't interrupt ongoing tests for different actions on same github.ref

- doc/howto/import_machines_to_instances.md
I slightly reworded the section related to the import of a Windows VM from a foreign hypervisor to better clarify that the steps described are optional
> Doc: Changes to the import of a Windows VM

- lxd/instance/drivers/driver_qemu.go
(cherry picked from commit e39888708011f980edce8fb4bda7f13caac3ef7d)
Fixes https://github.com/canonical/lxd/issues/14101
> VM: Fix RecordOutput (from Incus)

- lxd/storage_buckets.go
Check ETag when updating/patching storage bucket.
Request with an invalid ETag:
```sh
curl \
--unix-socket /var/snap/lxd/common/lxd/unix.socket \
-X PUT lxd/1.0/storage-pools/default/buckets/test \
-H "If-Match: invalid" \
-d '{"config": {"user.foo": "bar"}}'
```
```json
{
"type": "error",
"status": "",
"status_code": 0,
"operation": "",
"error_code": 412,
"error": "ETag doesn't match: 42fb4f3ad6a95d6c34ad521ddd97726841103005c7b651541ffafac3aa002242 vs invalid",
"metadata": null
}
```
Request with a valid ETag:
```sh
curl \
--unix-socket /var/snap/lxd/common/lxd/unix.socket \
-X PUT lxd/1.0/storage-pools/default/buckets/test \
-H "If-Match: 42fb4f3ad6a95d6c34ad521ddd97726841103005c7b651541ffafac3aa002242" \
-d '{"config": {"user.foo": "bar"}}'
```
```json
{
"type": "sync",
"status": …
```
> lxd: Check etag when updating storage bucket

- lxc/export.go
Fixes https://github.com/canonical/lxd/issues/13967.
For this one, the `c.global.flagQuiet` was set to `true` too late in the `run()` function, i.e. the progress renderer was writing instance backup progress info to stdout, corrupting the tarball.
Tested locally using the same steps in https://github.com/canonical/lxd/issues/13967 ✅
> lxc: Fix exporting vm backups to stdout

- .github/workflows/tests.yml
To help with debugging (requested by TICS)
> github: Enable tmpdir for TICS

- lxd/storage/backend_lxd.go
Check for direct I/O when converting image format using `qemu-img` to bypass OS cache if possible.
> lxd/storage: Check for direct I/O when converting image format

- lxd/storage/drivers/utils.go
- lxd/storage/utils.go
Follow up on https://github.com/canonical/lxd/pull/14157
> storage: Fix direct I/O write check

- doc/custom_conf.py
Workaround https://github.com/executablebooks/sphinx-tabs/issues/197
> doc: silence warning caused by sphinx-tabs

- test/suites/pki.sh
When asserting that a truststore entry is present, we can be more specific than just using the common name of the certificate (which is determined by the name of the certificate on input to easy-rsa at the beginning of the test).
When asserting that a truststore entry is not present, we shouldn't be grepping at all. (E.g. what if a truststore is added but the name we're grepping for is wrong?). We should instead check that the number of truststore entries is unchanged.
*Note: This failed to backport due to usage of trust passwords in 5.21, see https://github.com/canonical/lxd/pull/14235#issuecomment-2399655828*
> test/suites: Improve grep usage in PKI tests. (stable-5.21)

- .github/workflows/codeql.yml
- .github/workflows/commits.yml
- .github/workflows/security.yml
- .github/workflows/tests-snap.yml
- .github/workflows/triage.yml
- .yamllint
- Makefile
GHA runners comes with `yamllint` installed by default (https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md)
> Makefile: opportunistically run yamllint against GH workflows

- doc/howto/projects_create.md
- doc/howto/server_expose.md
A couple small typo fixes + testing that all is well with my git setup.
> doc: fix minor typos

- doc/api-extensions.md
- shared/version/api.go
> api: Add `state_logical_cpus` extension

- lxd/instances_get.go
Just a cherry pick for https://github.com/lxc/incus/pull/1140/commits/7c60b4a520c7554bb4a8103783419ed144e511e1
> Remove old retry logic (from Incus)

- lxd/instance/drivers/driver_qemu.go
Sponsored-by: https://webdock.io
(cherry picked from commit 045926b2d9099b18c4d552601bd4ae4fc9b1e8be)
> VM: Properly plumb I/O limits (from Incus)

- lxd/cluster/gateway.go
> lxd/cluster: Replace deprecated Recover with ReconfigureMembership

- lxc/launch.go
Fixes #14339
Fixes a regression introduced in #13695
> lxc/launch: Start console if instance start was performed on server

- lxd/device/cdi/configure.go
- lxd/device/cdi/spec.go
- lxd/device/gpu_physical.go
- lxd/instance/instance_utils.go
- lxd/sys/os.go
Tested using testflinger with `core24-latest` image deployed.
> Support NVIDIA CDI in Ubuntu Core environment

- lxd/device/cdi/spec.go
- lxd/device/gpu_physical.go
https://github.com/canonical/lxd/pull/14347#discussion_r1816694946
> Device: Improvements to GPU CDI mode & Ubuntu Core validation

- doc/tutorial/first_steps.md
- specify that it is the LXD snap and not snap in general that is being referred to in the tutorial, per contribution by @Alwoch #14152
> doc/tutorial: specify LXD snap

- lxd/device/cdi/spec.go
Instead of using a hardcoded NVIDIA driver root path, let's use a recently introduced NVIDIA_DRIVER_ROOT environment variable.
> Device: Use NVIDIA_DRIVER_ROOT env variable for GPU CDI

- doc/dev-lxd.md
> doc: Document devlxd Ubuntu Pro API endpoints.

- lxd/network/driver_ovn.go
(cherry picked from https://github.com/lxc/incus/pull/343)
> Network: Properly handle OVN uplink with disabled DHCP/DHCPv6 (from Incus)

- test/main.sh
trying to investigate https://github.com/canonical/lxd/actions/runs/11852057329/job/33029976380?pr=14324#step:12:44044
> tests: print Apport crash reports in case of failure

- .github/actions/install-lxd-builddeps/action.yml
- .github/actions/install-lxd-runtimedeps/action.yml
- .github/workflows/tests.yml
The aim is to reuse this for other jobs like `lxd-ui e2e`.
> Add install-lxd-runtimedeps action

- lxd/storage_volumes.go
- test/suites/auth.sh
Addresses two final comments on #14324
> API: Storage pool used-by list follow up (#14324)

- doc/howto/initialize.md
Fix broken link (already fixed in main with #14450 )
> doc: fix broken maas link (stable-5.0)

- lxc/main.go
Cherry picked from https://github.com/lxc/incus/pull/347.
This PR adds support for creating config paths (`~/.config/lxc/config.yml`) when only the LXC client is installed.
> LXC: Create config paths when no local daemons (from Incus)

- lxd/instance.go
Cherry-picked from https://github.com/lxc/incus/pull/1408 and tested with script from https://github.com/canonical/lxd/issues/12581
Closes https://github.com/canonical/lxd/issues/12581
> lxd/instance: Lock image access (from Incus)

- .github/workflows/tests.yml
- fix reference secrets from ui workflow
- dynamically select ui testsuite based on branch name
- only issue snap build if the ui tests succeed
> E2e UI tests

- doc/.sphinx/.markdownlint/exceptions.txt
Follow-up from https://github.com/canonical/lxd/pull/14573
> doc: Update doclint exceptions

- client/lxd.go
Addresses comment https://github.com/canonical/lxd/pull/14587#discussion_r1872808972
> client: Fix unnecessary error formatting

- README.md
- SECURITY.md
- doc/installing.md
- doc/support.md
> Doc: Remove monthly from feature release

- doc/howto/network_load_balancers.md
The existing doc says that if target ports are not provided, "the listen ports for the backend" will be used. This is incorrect (or at least, incomplete) as the backend specification does not define listen ports; the ports specification associated with that backend does. This PR clarifies and expands on how this works, including what happens if target ports are not provided _and_ no ports specification associated with that backend exists.
Also:
* Adds command syntax examples
* Removes redundancy in explaining how allocate flag is used
* Minor grammar/formatting improvements
* Shows example YAML configuration file
> Doc: Improve network load-balancer instructions and add examples

- .github/actions/setup-microceph/action.yml
- .github/workflows/codeql.yml
- Makefile
- lxd/db/cluster/config.mapper.go
- lxd/db/cluster/devices.mapper.go
- lxd/db/generate/db/method.go
- lxd/resources/cpu.go
- test/lint/test-tests.sh
- test/suites/backup.sh
- test/suites/basic.sh
- test/suites/clustering.sh
- test/suites/container_devices_disk.sh
- test/suites/container_devices_disk_restricted.sh
- test/suites/container_devices_nic_routed.sh
- test/suites/devlxd.sh
- test/suites/filtering.sh
- test/suites/image_profiles.sh
- test/suites/projects.sh
- test/suites/snapshots.sh
- test/suites/sql.sh
- test/suites/storage_snapshots.sh
- test/suites/warnings.sh
Address a few small things noticed while doing code reviews.
> Minor tweaks

- lxd/main_cluster.go
> lxd: `lxd cluster show` print bytes

- doc/cloud-init.md
Signed-off-by: Minae Lee <minae.lee@canonical.com>
(cherry picked from commit bc61d00724e69133d96c2151a71eabe1e49a689c)
> doc: fix malformed ref to cloud-init docs (stable-5.0)

- lxd/network/driver_ovn.go
- lxd/network/network_utils.go
- lxd/project/limits/permissions.go
Pre-requisite for https://github.com/canonical/lxd/pull/14631
> Network: Factor out uplink validation logic

- lxd/device/gpu_physical.go
If a host machine is not shut down properly [ i.e. it loses power ], the instances having CDI GPU attached to them won't start again after the host is started, even if a start command is issued manually.
LXD returns as exception:
`Failed to start device "nvidia-gpu": Failed to create device "/var/snap/lxd/common/lxd/devices/oel-ogrp623/cdi.unix.nvidia--gpu.dev-nvidia0" for "/dev/nvidia0": file exists`
To solve that, we must remove any remaining device files before adding new CDI device files in the instance GPU device directory. These old files are still present if the host crash because the GPU device stop hook is not called.
Fixes https://github.com/canonical/lxd/issues/14843
> Device: Remove existing GPU CDI device files before new device files are added

- client/lxd_oidc.go
The client was attempting to open the browser at `verification_uri_complete` which is marked as optional and might not be populated: https://www.rfc-editor.org/rfc/rfc8628#section-3.2
This commit falls back to the `verification_uri` if the former is not present.
> client: Fall back to OIDC `verification_uri`

- doc/explanation/instances.md
No longer an accurate description, because the implementation of VMs has improved greatly since this document was written.
> doc: revise/replace where VMs described as less featureful than containers

- lxd/api_project.go
- lxd/images.go
- lxd/instance_patch.go
- lxd/instance_put.go
- lxd/instances_post.go
- lxd/profiles_utils.go
- lxd/project/limits/permissions.go
- lxd/project/limits/permissions_test.go
- lxd/project/limits/state.go
- lxd/storage/backend_lxd.go
- lxd/storage_volumes.go
Pre-requisite for https://github.com/canonical/lxd/pull/14867
> Project: Avoid using empty context

- doc/.sphinx/.markdownlint/exceptions.txt
- doc/howto/network_forwards.md
- add how to list forwards
- add how to view info for a single forward
- update information about requirements for listen addresses
- add separate sections for how to create a forward in an OVN vs bridge network, add command examples
- update port specifications configuration info, add command examples
> doc: improve network forward docs pt1

- lxc/cluster.go
- lxc/completion.go
Closes https://github.com/canonical/lxd/issues/14560.
> CLI: Cluster member config key completions

- lxd/device/gpu_physical.go
The initial error was that the WalkDir callback (see `startCDIDevices` method) meant to cleanup the files was wrong.. The `HasPrefix` conditions were never met. Now they should be correct. This will remove:
- Any unix-char mount prefixed with `cdi.unix`
- Any disk mount prefixed with `cdi.disk`
- Any CDI metadata files (the cdi_config_devices.json file and the cdi_hooks.json file)
This has been tested locally on an dGPU NVIDIA-enabled laptop. Here is the tested approach:
```
lxc init ubuntu:22.04 c1
lxc config device add c1 gpu0 gpu gputype=physical id=nvidia.com/gpu=0
lxc start c1
lxc exec c1 -- nvidia-smi # Wokrking
sudo shutdown -i
lxc exec c1 -- nvidia-smi
```
> Device: Allow containers with CDI GPU to be restarted even after abrupt host shutdown

- doc/metadata.txt
- lxd/device/disk.go
- lxd/instance/instancetype/instance.go
- lxd/metadata/configuration.json
- lxd/storage/utils.go
Documentation and comment changes that I made while working on container root attachment. Since that item is on hold I thought I'd at least get these improvements put up.
Hopefully this improves clarity around IDmaps by a small measure.
> Storage: Disk device doc updates

- lxd/daemon.go
- lxd/loki/loki.go
Fixes https://github.com/canonical/lxd/issues/14835.
cc. @edlerd
> CLI: Improve config key update for `loki.api.url`

- lxd/api_project.go
- lxd/network/driver_ovn.go
- lxd/network/network_utils.go
- test/suites/network_ovn.sh
- Reduces the number of transactions used.
- Fixes validation of ovn uplink volatile IP to ensure its within ranges allowed from uplink.
> Network: Improve ovn validation efficiency and logic

- lxd/storage/drivers/driver_pure_util.go
Always create new request body reader and ensure safe access to `accessToken` in Pure Storage driver.
Fixes https://github.com/canonical/lxd/issues/14965
> Storage: Always create new request body reader 

- lxd/network/driver_ovn.go
- lxd/network/openvswitch/ovn.go
Backport of https://github.com/canonical/lxd/pull/14978
> Network: Fix OVN LogicalSwitchPortGetDNS to understand DNS records field that contains PTR records (stable-5.21)

- lxd/cgroup/abstraction.go
- lxd/instance/drivers/driver_lxc.go
- shared/util_linux.go
Addressing CodeQL warnings:
* https://github.com/canonical/lxd/security/code-scanning/148
* https://github.com/canonical/lxd/security/code-scanning/122
> Assorted small fixes and improvements

- test/suites/auth.sh
* https://github.com/canonical/lxd/pull/14973#discussion_r1968105687
* https://github.com/canonical/lxd/pull/14973#discussion_r1968109079
> lxd/auth: Fix missing comments from @markylaing

- doc/.custom_wordlist.txt
- doc/howto/oidc_auth0.md
- doc/operation.md
- added How to configure auth0.com as login method for the LXD UI
> docs: add oidc configuration with auth0 and idp groups WD-18947

- lxd/resources/network.go
In cases when the ovs daemon is not active, retrieving native bridge information would fail. Check if the bridge is native first before doing any OVS checks in order to avoid this scenario
> Resources: Prioritize native bridges over ovs ones

- lxd/resources/network.go
Fixes regression from e4a837c8fa32a1e234989c0fede8d2abb198c0b9
This caused the `Bridge` field in api.NetworkState to be populated by an empty api.NetworkStateBridge struct even if the interface was neither a native or OVS bridge.
> lxd/resources/network: Fix regression in GetNetworkState

- lxd/bgp/server.go
- lxd/network/driver_ovn.go
- lxd/network/driver_physical.go
Includes cherry-picks from https://github.com/lxc/incus/pull/1805.
> lxd: BGP fixes (from Incus)

- doc/howto/oidc_keycloak.md
https://github.com/canonical/lxd/pull/15176 was merged before I could finish my testing & review, so adding my revisions here. Minor copy/format edits.
> doc: minor revisions to keycloak docs

- .github/ISSUE_TEMPLATE/feature-request.yml
New feature request issue form (template); will be available from template chooser once merged.
> github: add feature request issue form

- doc/api-extensions.md
- lxd/api_internal.go
Follow up PR on https://github.com/canonical/lxd/pull/15009
> Small adjustments on top of BPF Token support PR

- lxd/daemon.go
- lxd/instances.go
And one bug fix wrt to storage unmount at shutdown time.
> lxd: Logging improvements for `instancesShutdown`

- lxd/main_forkproxy.go
- test/suites/container_devices_proxy.sh
Fixes https://github.com/canonical/lxd/issues/15024.
> forkproxy: proxy device early disconnect fix

- lxc/copy.go
- lxc/move.go
- test/suites/snapshots.sh
This is a follow up on https://github.com/canonical/lxd/pull/15155
> Apply instance profiles to snapshots with --profile as well

- lxd/storage/block/utils.go
Whilst backporting https://github.com/canonical/lxd/pull/15310 and testing with an isolated 5.21 LXD with completely clean storage disks I found the blkid command returns exit 2 in case the disk doesn't contain any traces of device identifiers or device contents.
The [man page](https://www.man7.org/linux/man-pages/man8/blkid.8.html) says:
> If the specified token was not found, or no (specified) devices
could be identified, or it is impossible to gather any information
about the device identifiers or device content an exit status of 2
is returned.
> Block: Fix `DiskFSUUID` for pristine disks

- lxd/ubuntupro/client.go
As discussed internally, the Ubuntu Pro client will place `interfaces/lxd-config.json` under `/var/lib/ubuntu-advantage`. This is because the `/var/lib/ubuntu-advantage` directory is already present on the Ubuntu system, whereas `/var/lib/ubuntu-pro` was only created when `pro config set lxd_guest_attach <value>` was called.
> Ubuntu Pro: Revert "lxd/ubuntu-pro: Change Ubuntu Pro directory."

- client/lxd_cluster.go
Updates client functions in `lxd_cluster.go` to construct URLs using `api.NewURL()` and replaces HTTP method literals with constants from `http` package.
> Refactor cluster client functions

- lxd/cluster/events.go
- lxd/daemon_images.go
- lxd/images.go
- lxd/instance_instance_types.go
- lxd/instance_state.go
- lxd/instances_get.go
- lxd/instances_put.go
- lxd/project/permissions.go
- lxd/storage_pools.go
Just separated the linter fixes from the upcoming handler refactor PR. The intention of passing request context around instead of the request affects various files.
> lxd: Fix various linter issues

- doc/cloud-init.md
Cherry pick from Incus https://github.com/lxc/incus/pull/681
> doc/cloud-init: Update network example to v2 (from Incus)

- doc/cloud-init.md
Cherry pick from Incus https://github.com/lxc/incus/pull/1155
> Change Cloud Init "user" to "users" (from Incus)

- doc/howto/initialize.md
Signed-off-by: Minae Lee <minae.lee@canonical.com>
(cherry picked from commit 9b9409e389497f4058f7f4020a06090452a6b270)
> doc: update broken maas anchor link (stable-5.0)

- .github/workflows/triage.yml
Minus the notification for doc PRs.
(cherry picked from commit 6081683271ea7f3fc9203bd9edfa3eb629ddd234)
> github/workflows/triage: Sync with main (stable-5.0)

- lxd/instance_file.go
- test/suites/filemanip.sh
> api: On file push to containers, only change uid/gid if it fits within uidmap range

- lxd/instance_file.go
This is a follow up on https://github.com/canonical/lxd/pull/15400 .
With these changes, if UID is adjusted on `file push`, LXD logs an INFO line such as:
```
INFO   [2025-04-25T08:47:57Z] Requested UID 1522341878 not within idmaprange  file=/root/filemanip instance=filemanip project=test
```
> api: Improve logging on file push

- lxd/api_internal.go
- lxd/main_waitready.go
- Changes `/internal/wait` to accept a `timeout` parameter rather than a `wait` parameter.
- Updates `lxd waitready` to pass its `--timeout` flag value to `/interna/wait` as `timeout` parameter.
- Updates `lxd waitready` to use contexts and to detect `http.StatusServiceUnavailable` response from server after timeout is reached in order to differentiate between an unreachable server and a not-ready server.
- Simplifies logging logic.
> lxd: Rework waitready to use contexts and server-side timeout support

- doc/.custom_wordlist.txt
- doc/debugging.md
- doc/metadata.txt
- lxd/metadata/configuration.json
- lxd/node/config.go
This knowledge is pretty tribal - let's make it a little easier to find.
> Document `core.debug_address`

- lxc/init.go
- lxc/launch.go
- lxc/monitor.go
- lxc/rebuild.go
- test/main.sh
- test/suites/completions.sh
These were found in testing and were easy to add after previous refactoring work.
This is the last of the PRs that split up #15311 and contains the tests from that PR - this will fail until all other completion refactor PRs are merged.
Depends on #15471 
Fixes https://github.com/canonical/lxd/issues/14512
> lxc: Add missing completions for top level commands

- lxd/network/driver_bridge.go
- test/includes/lxd.sh
- test/main.sh
- test/suites/clustering.sh
This should go after #15512 and will likely need rebasing to adapt to the overlapping changes in `lxd/network/driver_bridge.go` due to using `strings.Cut()` before replacing the `fmt.Sprintf()`.
> Misc improvements

- lxd/storage_volumes_utils.go
In the transaction only collect the necessary information but don't spend time persisting the data. This can be done outside of the transaction for performance reasons and also allows fetching further information down the line.
This fixes the following warning message in the log when running `lxc storage volume rename`: 
`level=warning msg="Transaction timed out. Retrying once" err="Failed to begin transaction: context deadline exceeded" member=1`
> Storage: Fix nested transaction in `storagePoolVolumeUpdateUsers`

- .github/workflows/tests.yml
Moving to https://launchpad.net/~lxd-snap/+snaps
> github: Update repo of lp-snap-build

- lxd/storage_volumes_snapshot.go
- test/suites/clustering.sh
Fixes https://github.com/canonical/lxd/issues/15480.
> Cluster: Add cluster target response forwarding to storage volume snapshot `GET` handler

- test/includes/clustering.sh
- test/suites/clustering.sh
- test/suites/clustering_move.sh
Avoid conflicts with Microsoft Azure Github runners.
(cherry picked from commit 4fff11cc45dae2a88baea0a87d8164ae163c95c2)
> tests: Switch clustering test subnet (from Incus)

- test/includes/clustering.sh
- test/suites/clustering.sh
Avoid conflicts with Microsoft Azure Github runners.
(cherry picked from commit 4fff11cc45dae2a88baea0a87d8164ae163c95c2)
> tests: Switch clustering test subnet (stable-4.0)

- lxd/util/http.go
- Improve etag error message to guide towards a solution
- resolving https://github.com/canonical/lxd-ui/issues/1228
> util/http: Improve etag error message to guide towards a solution

- lxd/db/cluster/entities.go
- lxd/device/device_utils_unix.go
- lxd/main_cluster.go
- lxd/migration/migration_volumes.go
- lxd/network/driver_bridge.go
- lxd/network_allocations.go
- lxd/project/project.go
- shared/util.go
> Various fixes (follow-up to #15584)

- lxd/db/networks.go
- lxd/network/driver_physical.go
- test/suites/clustering.sh
Fixes https://github.com/canonical/lxd/issues/14810.
> Network: Improve checking parent interface in use for physical networks

- lxd/seccomp/seccomp.go
Mimic the kernel behavior [1] and allow unprivileged whiteout creation in all cases, included nested user namespace.
It is a bugfix for 67b16ca026d ("lxd/seccomp/seccomp: tighten capability checks a bit") from PR #13458. We should consider backports to stable releases.
[1] https://github.com/torvalds/linux/commit/a3c751a50fe6bbe50eb7622a14b18b361804ee0c
Locally tested.
> lxd/seccomp: allow unprivileged whiteout creation

- .shellcheckrc
- test/backends/btrfs.sh
- test/backends/ceph.sh
- test/backends/dir.sh
- test/backends/lvm.sh
- test/backends/pure.sh
- test/backends/zfs.sh
- test/includes/check.sh
- test/includes/lxd.sh
- test/includes/storage.sh
- test/lint/godeps.sh
- test/lint/newline-after-block.sh
- test/suites/backup.sh
- test/suites/clustering.sh
- test/suites/clustering_move.sh
- test/suites/container_devices_nic_bridged.sh
- test/suites/container_devices_nic_bridged_filtering.sh
- test/suites/container_devices_nic_ipvlan.sh
- test/suites/container_devices_nic_p2p.sh
- test/suites/container_devices_nic_routed.sh
- test/suites/container_devices_proxy.sh
- test/suites/container_local_cross_pool_handling.sh
- test/suites/container_move.sh
- test/suites/devlxd.sh
- test/suites/exec.sh
- test/suites/fdleak.sh
- test/suites/filemanip.sh
- test/suites/storage_local_volume_handling.sh
- test/suites/syslog.sh
- test/suites/tls_restrictions.sh
Also fix some `grep` patterns along the way.
> Enable some optional shellchecks checks.

- lxd/cloudinit/config.go
This is a fix for the recent `lxd-ci` failures (or rather lxd crashes): https://github.com/canonical/lxd-ci/pull/488 .
Fixes regression in https://github.com/canonical/lxd/pull/15689
The problem is that this is not a valid yaml file: https://github.com/canonical/lxd-ci/blob/c0ba34b31fe3412208ae3f5eefb620fe866f20cf/tests/cloud-init#L66-L69
(or at least `yaml.Unmarshall()` call returns an error here: https://github.com/canonical/lxd/blob/825c4eb370a7dab14ed5fbab7980f64cb6cf4631/lxd/cloudinit/config.go#L150)
Previously lxd didn't crash, despite having `userCloudConfig == nil` here: https://github.com/canonical/lxd/blob/825c4eb370a7dab14ed5fbab7980f64cb6cf4631/lxd/cloudinit/config.go#L92
because golang allows calling methods on type `map[any]any` even if the map has value of `nil`, and …
> lxd/cloudinit: Fix parsing of invalid cloud-init yaml

- .github/workflows/tests.yml
Fixes b4ed34c7c3300e9e086e039ac553aef53f382b13
> github: fix conditional around optionally skipping unit tests

- test/suites/container_devices_nic_macvlan.sh
Follow-up to https://github.com/canonical/lxd/pull/15682.  
Adds tests to check that `lxc network info` shows correct MTU values for a macvlan network.
> test: Check that network info shows correct MTU for macvlan network

- lxd/cluster/connect.go
Addresses comment https://github.com/canonical/lxd/pull/15762#discussion_r2144464429
> lxd: Add headers only if value is not empty when connecting to other cluster member

- test/suites/lxd-benchmark.sh
The main aim is to increase code coverage.
> lxd-benchmark: test report generation and `launch` command

- lxd/device/device_common.go
- lxd/device/device_interface.go
- lxd/device/nic_bridged.go
- lxd/instance/drivers/driver_common.go
- lxd/instance/drivers/driver_lxc.go
- lxd/instance/drivers/driver_qemu.go
- lxd/instance/instance_interface.go
- lxd/instance_post.go
- lxd/migrate_instance.go
- test/suites/clustering.sh
Fixes https://github.com/canonical/lxd/issues/15511.
> Cluster: Add post-migration instance device cleanup

- test/includes/setup.sh
- test/suites/clustering.sh
- test/suites/projects.sh
- test/suites/remote.sh
- test/suites/storage_snapshots.sh
- test/suites/tls_restrictions.sh
Should be merged before #15836 as a prerequisite.
> Tests backport (stable-5.21)

- lxd/instances_post.go
Cherry-picked from https://github.com/lxc/incus/pull/503.
> lxd/instances_post: Use correct project on cross-project copy (from Incus)

- test/suites/migration.sh
Follow-up to https://github.com/canonical/lxd/pull/15798.
Adds a test for container migration (`lxc copy` and `lxc move`) with attached local volume.
> test: Add test for container migration with attached local volume

- lxd/device/device_common.go
- lxd/device/device_interface.go
- lxd/device/nic_bridged.go
- lxd/instance/drivers/driver_common.go
- lxd/instance/drivers/driver_lxc.go
- lxd/instance/drivers/driver_qemu.go
- lxd/instance/instance_interface.go
- lxd/migrate_instance.go
Closes https://github.com/canonical/lxd/issues/15511.
> Cluster: Rework post-migration steps to cleanup NIC bridged devices for cluster member moves only

- lxd/network/driver_bridge.go
Fixes https://github.com/canonical/lxd/issues/15117
> Fix duplicate IP assignment to VM copies

- test/suites/basic.sh
- test/suites/clustering.sh
- test/suites/container_devices_infiniband_physical.sh
- test/suites/container_devices_infiniband_sriov.sh
- test/suites/container_devices_nic_bridged.sh
- test/suites/container_devices_nic_bridged_filtering.sh
- test/suites/container_devices_nic_bridged_vlan.sh
- test/suites/container_devices_nic_ipvlan.sh
- test/suites/container_devices_nic_macvlan.sh
- test/suites/container_devices_nic_p2p.sh
- test/suites/container_devices_nic_physical.sh
- test/suites/container_devices_nic_routed.sh
- test/suites/container_devices_nic_sriov.sh
- test/suites/container_devices_proxy.sh
- test/suites/container_devices_tpm.sh
- test/suites/container_syscall_interception.sh
- test/suites/storage_driver_btrfs.sh
- test/suites/storage_driver_ceph.sh
- test/suites/storage_driver_cephfs.sh
- test/suites/storage_driver_dir.sh
- test/suites/storage_driver_pure.sh
- test/suites/storage_driver_zfs.sh
- test/suites/storage_volume_attach.sh
Remove some races by waiting for IPv6 DAD when needed.
Also improve runtime by shortening sleeps where possible.
> Misc test fixes

- test/suites/container_devices_unix.sh
Only skip the part that is known broken ATM due to https://github.com/canonical/lxd/issues/15894
> test/suites/container_devices_unix: do not completely skip tests with `fanotify`

- test/suites/clustering.sh
Cherry-picked from https://github.com/lxc/incus/pull/1054 (https://github.com/lxc/incus/pull/1054/commits/8366dfbe8026f75d4c23cb757b90b12f686614fc).
> tests/clustering: Use correct target project argument

- doc/metadata.txt
- lxd/auth/drivers/openfga_model.openfga
- lxd/auth/entitlements_generated.go
- lxd/metadata/configuration.json
The description did not make it clear that members of a group with this permission can edit any resource belonging to any project.
> Auth: Update project manager description

- lxd/instance/drivers/driver_qemu.go
Replace deprecated `-runas` with supported `-run-with user` parameter for QEMU versions 9.1 and above.
(cherry picked from commit 8dc3e34146834a683a5da6ba9279b8a76ca36d26)
Fixes #15771
> lxd/instances/qemu: Handle deprecation of runas (from Incus)

- lxd/images.go
Enforce that an untrusted caller cannot list images in non-default projects before making database calls. Additionally, don't check the effective project if the caller is not trusted, since the request must be for the default project, which must have images enabled.
> lxd: Reorganise checks in images GET handler.

- .github/workflows/tests.yml
Run Tiobe TICS on self-hosted runners.
> tests: Run Tiobe TICS on self-hosted runners

- lxd/instance/instance_utils.go
- lxd/storage/utils.go
- shared/util.go
- shared/util_test.go
Inspired by https://github.com/lxc/incus/commit/298c06f03249be8253d7cb421f1d7559ee09fd8a
> Pongo2 templates rework

- shared/util.go
- shared/util_test.go
Fixes https://github.com/canonical/lxd/issues/16042
> shared/util: Handle panics in the pongo2 package

- scripts/setup-grafana.sh
See https://github.com/canonical/lxd-ui/issues/1406 for more context and https://github.com/canonical/lxd-ui/commit/efe590ef394dcb79c2ea3f0391c17d1be8f8e7ca for change in lxd-ui.
> doc: update grafana base url to encounter ui prefix

- lxd/instance/drivers/driver_lxc.go
- test/suites/config.sh
- test/suites/container_devices_unix.sh
Closes https://github.com/canonical/lxd/issues/12648.
> Only remove mount points created in `/dev` (from Incus)

- .github/workflows/tests.yml
- lxd/cluster/membership.go
- lxd/daemon.go
- lxd/state/state.go
- lxd/storage/drivers/driver_powerflex.go
- lxd/storage/drivers/driver_powerflex_utils.go
- lxd/storage/drivers/driver_pure.go
- lxd/sys/os.go
Ensure this at the very beginning of the Daemon init function
> init: Ensure the LXD_DIR exists

- test/suites/vm.sh
Follow up to https://github.com/canonical/lxd/pull/16138.
> tests: Add basic disk mount VM checks

- shared/validate/validate_test.go
Increase code coverage from 11.1% to 28.4%.
> shared/validate: add a few unit tests

- lxd/daemon.go
- lxd/events.go
These were also part of https://github.com/canonical/lxd/pull/16223 but can be merged separately to ease it's review. This will need to be rebased when https://github.com/canonical/lxd/pull/16255 is merged.
> Various auth improvements

- lxd/auth/drivers/openfga.go
- lxd/images.go
- lxd/network_acls.go
- lxd/network_allocations.go
- lxd/network_forwards.go
- lxd/network_load_balancers.go
- lxd/network_peer.go
- lxd/network_zones.go
- lxd/network_zones_records.go
- lxd/networks.go
- lxd/profiles.go
- lxd/request/const.go
- lxd/request/context.go
- lxd/storage_buckets.go
- lxd/storage_volumes.go
- lxd/storage_volumes_backup.go
- lxd/storage_volumes_snapshot.go
This is part of #16223 but is standalone and can be merged separately to ease review.
> Auth: Remove effective project from request.Info

- lxd/db/query/retry.go
- lxd/db/storage_buckets.go
Based on learnings from https://blog.fillmore-labs.com/posts/errors-1/
> lxd/db: Fix dqlite retry and conflict detection

- lxd/auth/encryption/errors.go
- lxd/auth/encryption/key.go
- lxd/auth/encryption/key_test.go
- lxd/auth/oidc/oidc.go
These are a couple of commits from #16225 that can be moved into a separate PR
> Auth: Add encryption package

- Makefile
- test/lint/errortype.sh
- test/lint/zerolint.sh
[zerolint](https://github.com/fillmore-labs/zerolint)
[errortype](https://github.com/fillmore-labs/errortype)
> Add zerolint and errortype linters

- lxd/api_cluster.go
- lxd/auth/oidc/oidc.go
- lxd/config/map.go
- lxd/network/acl/acl_ovn.go
- lxd/network/acl/acl_ovn_test.go
All changes done by `modernize` tool except for the last 2 commits adding tests and making a tiny change.
> Apply `modernize` recommendations

- lxd/api_project.go
- lxd/operations.go
Follow up on feedback received in #16284
> Restore ctx parameter to some functions

- lxd/instance_file.go
Hello,
I found a bug about file push so push commit for fix it.
After https://github.com/canonical/lxd/pull/15448 merged, file's uid/gid change is available in container type instance only, because code got return from applyEffectiveFileOwnership before run file.Chown if not container type.
The problem is here.
https://github.com/canonical/lxd/blob/lxd-6.4/lxd/instance_file.go#L379-L381
And after return that function, there is no chance run chown.
Here is a test.
- in LXD 6.2, UID and GID can set
```
root@testlxd-1:/home/heat1024# lxc file push test vm-1/root/test --uid 65534 --gid 65534
root@testlxd-1:/home/heat1024# lxc exec vm-1 -- bash -c 'ls -al /root/test'
-rw-r--r-- 1 nobody nogroup 5 Aug 25 17:21 /root/test
```
- after LXD 6.4, UID and GID cannot set if instance is VM
``` …
```
> fix bug about file owner/group change not work on vm

- go.mod
- go.sum
- lxc/exec.go
- po/lxd.pot
And update Go modules while at it.
Closes #16159.
> Add help test for `lxc shell` alias

- lxd/images.go
Suggested by @tomponline: https://github.com/canonical/lxd/pull/14316#discussion_r1812861877.
> lxd: use imageDeleteFromDisk()

- shared/validate/validate.go
- shared/validate/validate_test.go
- test/main.sh
Increase test coverage of `shared/validate` from 35% to 41%.
> Tiny tweaks

- lxd/storage/drivers/driver_ceph_volumes.go
- lxd/storage/drivers/driver_powerflex_volumes.go
- lxd/storage/drivers/driver_zfs_volumes.go
Follow up on review comment in #16438
> Early exit on read-only images

- lxd-agent/devlxd_storage.go
- lxd/devlxd_instances_test.go
- lxd/devlxd_storage.go
- test/suites/devlxd.sh
This PR includes some minor tweaks for the recent DevLXD volume management.
- Removes unnecessary recursion check in LXD Agent (already handled by DevLXD)
- Extracts parsing of volume identifiers (pool, type, name) into a separate func
- Tweaks the tests to ensure access control is better checked
None of those changes affect the existing functionality.
> devlxd: Minor improvements

- lxd/storage/drivers/driver_pure.go
- lxd/storage/drivers/driver_pure_util.go
- lxd/storage/drivers/driver_pure_volumes.go
Implements Pure's `ListVolumes` function to enable recovery.
> Storage: Enable Pure recovery

- lxd/api_project.go
- lxd/db/cluster/entities.go
- shared/entity/ref.go
Follow-up to https://github.com/canonical/lxd/pull/16533.
> Forced project deletion follow up

- lxd/api_project.go
- shared/entity/ref.go
See discussion here: https://github.com/canonical/lxd/commit/cc8f2c39e4144a4296ad470d0ec33a34d0db5a4e#r166782565
> Fix `Name` function for `shared.EntityRef`

- doc/howto/cluster_manage.md
This ports and adapts information about cluster healing (automatic evacuation of workloads from clusters when a cluster member goes offline) from the Incus documentation, with edits for LXD terminology and context.
Inspired-by: [fc1d7d0191 (\"doc/clustering: Better document healing\")](https://github.com/lxc/incus/pull/1075/files#diff-dd7677da7f945b89e7e144c9848ca0603c332793beac980926c06021037e3620R88)
Details:
Specifically, I adapted two parts of the cluster healing documentation from Incus in the above-referenced commit:
- Incus added a `note` admonition that "This automatic cluster healing only applies to instances on shared storage and which don't use any local devices." I lightly edited this and placed it inline.
- Incus added a `warning` admonition about the risk of automatic …
> doc: partial port of cluster healing section (from Incus)

- lxd/api_project.go
Follow-up to https://github.com/canonical/lxd/pull/16623.
> Prune cached images during project delete follow-up

- test/lint/test-tests.sh
- test/main.sh.bash-completion
This builds on the nice work done in #16660
> Test `tab` completion tweaks

- test/suites/container_devices_disk.sh
- test/suites/container_devices_unix.sh
Closes https://github.com/canonical/lxd/issues/16264.
Adds tests for https://github.com/lxc/lxc/pull/4581.
> Add disk mount tests
